var menulist=[
"== INTRODUCTION ==",
"== NINETEEN EIGHTY-FOUR ==",
"=== PART ONE ===",
"==== Chapter 1 ====",
"==== Chapter 2 ====",
"==== Chapter 3 ====",
"==== Chapter 4 ====",
"==== Chapter 5 ====",
"==== Chapter 6 ====",
"==== Chapter 7 ====",
"==== Chapter 8 ====",
"=== PART TWO ===",
"==== Chapter 1 ====",
"==== Chapter 2 ====",
"==== Chapter 3 ====",
"==== Chapter 4 ====",
"==== Chapter 5 ====",
"==== Chapter 6 ====",
"==== Chapter 7 ====",
"==== Chapter 8 ====",
"==== Chapter 9 ====",
"==== Chapter 10 ====",
"=== PART THREE ===",
"==== Chapter 1 ====",
"==== Chapter 2 ====",
"==== Chapter 3 ====",
"==== Chapter 4 ====",
"==== Chapter 5 ====",
"==== Chapter 6 ====",
"=== APPENDIX: THE PRINCIPLES OF NEWSPEAK ===",
"== Animal Farm ==",
"==== Chapter 1 ====",
"==== Chapter 2 ====",
"==== Chapter 3 ====",
"==== Chapter 4 ====",
"==== Chapter 5 ====",
"==== Chapter 6 ====",
"==== Chapter 7 ====",
"==== Chapter 8 ====",
"==== Chapter 9 ====",
"==== Chapter 10 ====",
];
