var menulist=[
"= Table of Contents =",
"= To Stanley =",
"= Introduction to the Millennial Edition =",
"= Foreword =",
"= PART ONE =",
"== PRIMEVAL NIGHT ==",
"== The Road to Extinction ==",
"== The New Rock ==",
"== Academy ==",
"== The Leopard ==",
"== Encounter in the Dawn ==",
"== Ascent of Man ==",
"= PART TWO =",
"== TMA-1 ==",
"== Special Flight ==",
"== Orbital Rendezvous ==",
"== Moon Shuttle ==",
"== Clavius Base ==",
"== Anomaly ==",
"== Journey by Earthlight ==",
"== The Slow Dawn ==",
"== The Listeners ==",
"= PART THREE =",
"== BETWEEN PLANETS ==",
"== Discovery ==",
"== Hal ==",
"== Cruise Mode ==",
"== Through the Asteroids ==",
"== Transit of Jupiter ==",
"== The World of the Gods ==",
"= PART FOUR =",
"== ABYSS ==",
"== Birthday Party ==",
"== Excursion ==",
"== Diagnosis ==",
"== Broken Circuit ==",
"== First Man to Saturn ==",
"== Dialogue with Hal ==",
"== “Need to Know” ==",
"== In Vacuum ==",
"== Alone ==",
"== The Secret ==",
"= PART FIVE =",
"== THE MOONS OF SATURN ==",
"== Survival ==",
"== Concerning E.T.’s ==",
"== Ambassador ==",
"== The Orbiting Ice ==",
"== The Eye of Japetus ==",
"== Big Brother ==",
"== Experiment ==",
"== The Sentinel ==",
"== Into the Eye ==",
"== Exit ==",
"= PART SIX =",
"== THROUGH THE STAR GATE ==",
"== Grand Central ==",
"== The Alien Sky ==",
"== Inferno ==",
"== Reception ==",
"== Recapitulation ==",
"== Transformation ==",
"== Star-Child ==",
"= Sir Arthur C. Clarke (1917&ndash;2008) =",
];
