var menulist=[
"== Title Page ==",
"== Copyright Notice ==",
"== Dedication ==",
"== Epigraph ==",
"== Introduction ==",
"== 1. The Independent Self ==",
"== 2. Things Fall Apart ==",
"== 3. Dependence ==",
"== 4. Assistance ==",
"== 5. A Better Life ==",
"== 6. Letting Go ==",
"== 7. Hard Conversations ==",
"== 8. Courage ==",
"== Epilogue ==",
"== Notes on Sources ==",
"== Acknowledgements ==",
"== Discussion Questions ==",
"== Also by Atul Gawande ==",
"== About the Author ==",
"== Newsletter Sign-up ==",
"== Copyright ==",
];
