var menulist=[
"== I.Before Breakfast ==",
"== II.Wilbur ==",
"== III.Escape ==",
"== IV.Loneliness ==",
"== V.Charlotte ==",
"== VI.Summer Days ==",
"== VII.Bad News ==",
"== VIII.A Talk at Home ==",
"== IX.Wilbur’s Boast ==",
"== X.An Explosion ==",
"== XI.The Miracle ==",
"== XII.A Meeting ==",
"== XIII.Good Progress ==",
"== XIV.Dr. Dorian ==",
"== XV.The Crickets ==",
"== XVI.Off to the Fair ==",
"== XVII.Uncle ==",
"== XVIII.The Cool of the Evening ==",
"== XIX.The Egg Sac ==",
"== XX.The Hour of Triumph ==",
"== XXI.Last Day ==",
"== XXII.A Warm Wind ==",
"== Excerpt from Stuart Little ==",
"== Excerpt from The Trumpet of the Swan ==",
"== Back Ad ==",
"== About the Author and Artists ==",
"== Books by E. B. White ==",
"== Credits ==",
"== Copyright ==",
"== About the Publisher ==",
];
