var menulist=[
"= Prologue =",
"= The All-Father’s Fear =",
"= A Growing Chill =",
"= What Loki Saw =",
"= The Power of Three =",
"= The All-Father’s Burden =",
"= A Stranger’s Arrival =",
"= A Touch of Blue =",
"= A Feast of Delights =",
"= Long Live the King =",
"= Finding Answers =",
"= S. H. I. E. L. D. =",
"= Darkest Hour =",
"= Unexpected Allies =",
"= A New Tale to Tell =",
"= Broken =",
"= Epilogue =",
"= 序 =",
"= 众神之父的忧虑 =",
"= 寒意渐增 =",
"= 洛基所见 =",
"= 三武士的能力 =",
"= 众神之父的压力 =",
"= 不速之客 =",
"= 蓝色之痕 =",
"= 惊喜相聚 =",
"= 国王万岁 =",
"= 寻找答案 =",
"= 神盾局 =",
"= 黑暗时刻 =",
"= 意外的盟友 =",
"= 新的史诗 =",
"= 断桥 =",
"= 后记 =",
];
