var menulist=[
"=== 译　序 ===",
"=== 意切情深信达雅 　　&mdash;&mdash;序《英诗经典名家名译》 ===",
"== Forest Picture ==",
"== 森林美景 ==",
"== Clown in the Moon ==",
"== 月中的小丑 ==",
"== The Oak ==",
"== 橡　树 ==",
"== I have come to catch your voice ==",
"== 我来领会你的声音 ==",
"== Admit the sun ==",
"== 准许阳光 ==",
"== The air you breathe ==",
"== 你呼吸的空气 ==",
"== It's not in misery but in oblivion ==",
"== 不在痛苦中而在遗忘中 ==",
"== Since, on a quiet night ==",
"== 一个宁静的夜晚 ==",
"== Never to reach the oblivious dark ==",
"== 永不触及那忘却的黑暗 ==",
"== Children of darkness got no wings ==",
"== 黑暗里的孩子没有翅膀 ==",
"== Youth Calls to Age ==",
"== 青春呼唤年轮 ==",
"== Being but men ==",
"== 只不过是人 ==",
"== The midnight road ==",
"== 午夜之路 ==",
"== Their faces shone under some radiance ==",
"== 他们的脸闪烁光芒 ==",
"== The almanac of time ==",
"== 时光的年鉴 ==",
"== Your pain shall be a music ==",
"== 你的疼痛将是乐音 ==",
"== I see the boys of summer ==",
"== 我看见夏日的男孩 ==",
"== When once the twilight locks no longer ==",
"== 一旦晨曦不再伫留 ==",
"== A process in the weather of the heart ==",
"== 心的气候进程 ==",
"== Before I knocked ==",
"== 在我敲开之前 ==",
"== The force that through the green fuse drives the flower ==",
"== 穿过绿色茎管催动花朵的力 ==",
"== My hero bares his nerves ==",
"== 我的英雄裸露他的神经 ==",
"== Where once the waters of your face ==",
"== 在你脸上的水 ==",
"== If I were tickled by the rub of love ==",
"== 假如我被爱的抚摸撩得心醉 ==",
"== Our eunuch dreams ==",
"== 我们的阉人梦见 ==",
"== Especially when the October wind ==",
"== 尤其当十月的风 ==",
"== When, like a running grave ==",
"== 时光，像座奔跑的坟墓 ==",
"== From love's first fever to her plague ==",
"== 当初恋从狂热趋于烦扰 ==",
"== In the beginning ==",
"== 最　初 ==",
"== Light breaks where no sun shines ==",
"== 没有太阳照耀的地方，光降临 ==",
"== I fellowed sleep ==",
"== 我与睡眠作伴 ==",
"== I dreamed my genesis ==",
"== 我梦见自身的起源 ==",
"== All all and all the dry worlds lever ==",
"== 一切一切干枯的世界杠杆 ==",
"== This bread I break ==",
"== 这片我切开的面包 ==",
"== Incarnate devil ==",
"== 魔鬼化身 ==",
"== The seed-at-zero ==",
"== 零度种子 ==",
"== Shall gods be said to thump the clouds ==",
"== 据说众神将捶击云层 ==",
"== Here in this spring ==",
"== 在此春天 ==",
"== Out of the sighs ==",
"== 叹息中 ==",
"== Hold hard, these ancient minutes in the cuckoo's month ==",
"== 等一等，布谷鸟月份中的古老时分 ==",
"== Was there a time ==",
"== 是否有过这样的时候 ==",
"== Now ==",
"== 现　在 ==",
"== Why east wind chills ==",
"== 为何东风凛冽 ==",
"== A grief ago ==",
"== 在悲伤之前 ==",
"== Ears in the turrets hear ==",
"== 耳朵在塔楼里听见 ==",
"== The hand that signed the paper ==",
"== 那只签署文件的手 ==",
"== Should lanterns shine ==",
"== 一旦灯笼闪亮 ==",
"== I have longed to move away ==",
"== 我渴望远离 ==",
"== Grief thief of time ==",
"== 悲伤的时光贼子 ==",
"== And death shall have no dominion ==",
"== 而死亡也一统不了天下 ==",
"== Because the pleasure-bird whistles ==",
"== 因为快乐鸟唿哨 ==",
"== When all my five and country senses see ==",
"== 当我天生的五官看见 ==",
"== We lying by seasand ==",
"== 我们躺在沙滩上 ==",
"== It is the sinners' dust-tongued bell ==",
"== 是罪人的尘埃之舌鼓动起钟声 ==",
"== O make me a mask ==",
"== 哦，为我打制一副面具 ==",
"== The spire cranes ==",
"== 塔尖，鹤一样耸立 ==",
"=== After the funeral ===",
"=== 葬礼之后 ===",
"== Once it was the colour of saying ==",
"== 那话语的音色曾经 ==",
"== Not from this anger ==",
"== 并非因这种愤怒 ==",
"== The tombstone told when she died ==",
"== 她死后的墓碑在诉说 ==",
"== On no work of words ==",
"== 当词语失效 ==",
"== 'If my head hurt a hair's foot' ==",
"== “如果我的头伤着一丝发根” ==",
"== Twenty-four years ==",
"== 二十四年 ==",
"== The conversation of prayers ==",
"== 祈祷者的对话 ==",
"== Poem in October ==",
"== 十月献诗 ==",
"== To Others than You ==",
"== 致你及他人 ==",
"== Love in the Asylum ==",
"== 疯人院里的爱 ==",
"== Unluckily for a death ==",
"== 不幸地等待死亡 ==",
"== Into her lying down head ==",
"== 进入她躺下的头颅 ==",
"== Do not go gentle into that good night ==",
"== 不要温顺地走进那个良宵 ==",
"== Deaths and Entrances ==",
"== 死亡与入口 ==",
"== On a Wedding Anniversary ==",
"== 结婚周年纪念日 ==",
"== On the Marriage of a Virgin ==",
"== 处女新婚 ==",
"== In my craft or sullen art ==",
"== 我的手艺或沉寂的诗艺 ==",
"== Lie still, sleep becalmed ==",
"== 静静地躺下，安然入睡 ==",
"== Fern Hill ==",
"== 羊齿山 ==",
"== In Country Sleep ==",
"== 梦中的乡村 ==",
"== Over Sir John's Hill ==",
"== 在约翰爵爷的山岗上 ==",
"== In the White Giant's Thigh ==",
"== 在白色巨人的大腿间 ==",
"== Elegy ==",
"== 挽　歌 ==",
];
