var menulist=[
"== Woody ==",
"== 胡迪 ==",
"== Buzz Lightyear ==",
"== 巴斯光年 ==",
"== Rex ==",
"== 抱抱龙 ==",
"== Hamm ==",
"== 火腿 ==",
"== Slinky Dog ==",
"== 弹簧狗 ==",
"== Mr. Potato Head ==",
"== 蛋头 ==",
"= Chapter 1 =",
"= 第 1 章 =",
"= Chapter 2 =",
"= 第 2 章 =",
"= Chapter 3 =",
"= 第 3 章 =",
"= Chapter 4 =",
"= 第 4 章 =",
"= Chapter 5 =",
"= 第 5 章 =",
"= Chapter 6 =",
"= 第 6 章 =",
"= Chapter 7 =",
"= 第 7 章 =",
"= Chapter 8  =",
"= 第 8 章 =",
"= Chapter 9 =",
"= 第 9 章 =",
"= Chapter 10 =",
"= 第 10 章 =",
"= Epilogue =",
"= 尾　声 =",
];
