var menulist=[
"== Mr. Incredible ==",
"== 超能先生 ==",
"== Elastigirl ==",
"== 弹力女超人 ==",
"== Dash Parr ==",
"== 巴小飞 ==",
"== Violet Parr ==",
"== 巴小丽 ==",
"== Frozone ==",
"== 冰条侠 ==",
"== Syndrome ==",
"== 超劲先生 ==",
"= Chapter 1 =",
"= Chapter 2 =",
"= Chapter 3 =",
"= Chapter 4 =",
"= Chapter 5 =",
"= Chapter 6 =",
"= Chapter 7 =",
"= Chapter 8 =",
"= Chapter 9 =",
"= Chapter 10 =",
"= Chapter 11 =",
"= Chapter 12 =",
"= Chapter 13 =",
"= Chapter 14 =",
"= Chapter 15 =",
"= Chapter 16 =",
"= Chapter 17 =",
"= Chapter 18 =",
"= Chapter 19 =",
"= Chapter 20 =",
"= Chapter 21 =",
"= Chapter 22 =",
"= Chapter 23 =",
"= Chapter 24 =",
"= Chapter 25 =",
"= Chapter 26 =",
"= Chapter 27 =",
"= Chapter 28 =",
"= Chapter 29 =",
"= Chapter 30 =",
"= Chapter 31 =",
"= Chapter 32 =",
"= 第 1 章 =",
"= 第 2 章 =",
"= 第 3 章 =",
"= 第 4 章 =",
"= 第 5 章 =",
"= 第 6 章 =",
"= 第 7 章 =",
"= 第 8 章 =",
"= 第 9 章 =",
"= 第 10 章 =",
"= 第 11 章 =",
"= 第 12 章 =",
"= 第 13 章 =",
"= 第 14 章 =",
"= 第 15 章 =",
"= 第 16 章 =",
"= 第 17 章 =",
"= 第 18 章 =",
"= 第 19 章 =",
"= 第 20 章 =",
"= 第 21 章 =",
"= 第 22 章 =",
"= 第 23 章 =",
"= 第 24 章 =",
"= 第 25 章 =",
"= 第 26 章 =",
"= 第 27 章 =",
"= 第 28 章 =",
"= 第 29 章 =",
"= 第 30 章 =",
"= 第 31 章 =",
"= 第 32 章 =",
];
