var menulist=[
"== Rapunzel ==",
"== 乐佩公主 ==",
"== Flynn Rider ==",
"== 费林·雷德 ==",
"== Pascal ==",
"== 帕斯考 ==",
"== Maximus ==",
"== 捍马 ==",
"= PROLOGUE =",
"= 前 　言 =",
"= Chapter 1 =",
"= 第 1 章 =",
"= Chapter 2 =",
"= 第 2 章 =",
"= Chapter 3 =",
"= 第 3 章 =",
"= Chapter 4 =",
"= 第 4 章 =",
"= Chapter 5 =",
"= 第 5 章 =",
"= Chapter 6 =",
"= 第 6 章 =",
"= Chapter 7 =",
"= 第 7 章 =",
"= Chapter 8 =",
"= 第 8 章 =",
"= Chapter 9 =",
"= 第 9 章 =",
"= Chapter 10 =",
"= 第 10 章 =",
"= Chapter 11 =",
"= 第 11 章 =",
"= Chapter 12 =",
"= 第 12 章 =",
"= Chapter 13 =",
"= 第 13 章 =",
"= Chapter 14 =",
"= 第 14 章 =",
"= Chapter 15 =",
"= 第 15 章 =",
"= Chapter 16 =",
"= 第 16 章 =",
"= Chapter 17 =",
"= 第 17 章 =",
"= Chapter 18 =",
"= 第 18 章 =",
"= Chapter 19 =",
"= 第 19 章 =",
"= Chapter 20 =",
"= 第 20 章 =",
"= Chapter 21 =",
"= 第 21 章 =",
"= Chapter 22 =",
"= 第 22 章 =",
"= Chapter 23 =",
"= 第 23 章 =",
"= Chapter 24 =",
"= 第 24 章 =",
"= Chapter 25 =",
"= 第 25 章 =",
"= Chapter 26 =",
"= 第 26 章 =",
];
