var menulist=[
"== Praise for the Dune Chronicles ==",
"== Books by Frank Herbert and Brian Herbert ==",
"== Title Page ==",
"== Copyright ==",
"== Introduction by Brian Herbert ==",
"== Excerpts from the Death Cell Interview with Bronso of Ix ==",
"== Chapter 1 ==",
"== Chapter 2 ==",
"== Chapter 3 ==",
"== Chapter 4 ==",
"== Chapter 5 ==",
"== Chapter 6 ==",
"== Chapter 7 ==",
"== Chapter 8 ==",
"== Chapter 9 ==",
"== Chapter 10 ==",
"== Chapter 11 ==",
"== Chapter 12 ==",
"== Chapter 13 ==",
"== Chapter 14 ==",
"== Chapter 15 ==",
"== Chapter 16 ==",
"== Chapter 17 ==",
"== Chapter 18 ==",
"== Chapter 19 ==",
"== Chapter 20 ==",
"== Chapter 21 ==",
"== Chapter 22 ==",
"== Chapter 23 ==",
"== Chapter 24 ==",
"== Epilogue ==",
"== About the Author ==",
];
