var menulist=[
"== BOOK I: DUNE ==",
"=== Chapter 01 ===",
"=== Chapter 02 ===",
"=== Chapter 03 ===",
"=== Chapter 04 ===",
"=== Chapter 05 ===",
"=== Chapter 06 ===",
"=== Chapter 07 ===",
"=== Chapter 08 ===",
"=== Chapter 09 ===",
"=== Chapter 10 ===",
"=== Chapter 11 ===",
"=== Chapter 12 ===",
"=== Chapter 13 ===",
"=== Chapter 14 ===",
"=== Chapter 15 ===",
"=== Chapter 16 ===",
"=== Chapter 17 ===",
"=== Chapter 18 ===",
"=== Chapter 19 ===",
"=== Chapter 20 ===",
"=== Chapter 21 ===",
"=== Chapter 22 ===",
"== BOOK II: MUAD’DIB ==",
"=== Chapter 23 ===",
"=== Chapter 24 ===",
"=== Chapter 25 ===",
"=== Chapter 26 ===",
"=== Chapter 27 ===",
"=== Chapter 28 ===",
"=== Chapter 29 ===",
"=== Chapter 30 ===",
"=== Chapter 31 ===",
"=== Chapter 32 ===",
"=== Chapter 33 ===",
"=== Chapter 34 ===",
"=== Chapter 35 ===",
"=== Chapter 36 ===",
"=== Chapter 37 ===",
"== BOOK III: THE PROPHET ==",
"=== Chapter 38 ===",
"=== Chapter 39 ===",
"=== Chapter 40 ===",
"=== Chapter 41 ===",
"=== Chapter 42 ===",
"=== Chapter 43 ===",
"=== Chapter 44 ===",
"=== Chapter 45 ===",
"=== Chapter 46 ===",
"=== Chapter 47 ===",
"=== Chapter 48 ===",
"== APPENDIX I: The Ecology of Dune ==",
"== APPENDIX II: The Religion of Dune ==",
"== APPENDIX III: Report on Bene Gesserit Motives and Purposes ==",
"== APPENDIX IV: The Almanak en-Ashraf (Selected Excerpts of the Noble Houses) ==",
"== Terminology of the Imperium ==",
"== Cartographic Notes ==",
"== Map ==",
"== Afterword by Brian Herbert ==",
];
