var menulist=[
"= Contents =",
"== PROLOGUE ==",
"== 1 SEARCH FOR MAGICIANS ==",
"== 2 THE MAGICIANS ==",
"== 3 THE DEAD HAND ==",
"== 4 THE EMPEROR ==",
"== 5 THE WAR BEGINS ==",
"== 6 THE FAVORITE ==",
"== 7 BRIBERY ==",
"== 8 TO TRANTOR ==",
"== 9 ON TRANTOR ==",
"== 10 THE WAR ENDS ==",
"== 11 BRIDE AND GROOM ==",
"== 12 CAPTAIN AND MAYOR ==",
"== 13 LIEUTENANT AND CLOWN ==",
"== 14 THE MUTANT ==",
"== 15 THE PSYCHOLOGIST ==",
"== 16 CONFERENCE ==",
"== 17 THE VISI-SONOR ==",
"== 18 FALL OF THE FOUNDATION ==",
"== 19 START OF THE SEARCH ==",
"== 20 CONSPIRATOR ==",
"== 21 INTERLUDE IN SPACE ==",
"== 22 DEATH ON NEOTRANTOR ==",
"== 23 THE RUINS OF TRANTOR ==",
"== 24 CONVERT ==",
"== 25 DEATH OF A PSYCHOLOGIST ==",
"== 26 END OF THE SEARCH ==",
"== About the Author ==",
];
