var menulist=[
"= A Game of Thrones =",
"== Dedication ==",
"== Maps ==",
"== Prologue ==",
"== Chapter 1 ==",
"== Chapter 2 ==",
"== Chapter 3 ==",
"== Chapter 4 ==",
"== Chapter 5 ==",
"== Chapter 6 ==",
"== Chapter 7 ==",
"== Chapter 8 ==",
"== Chapter 9 ==",
"== Chapter 10 ==",
"== Chapter 11 ==",
"== Chapter 12 ==",
"== Chapter 13 ==",
"== Chapter 14 ==",
"== Chapter 15 ==",
"== Chapter 16 ==",
"== Chapter 17 ==",
"== Chapter 18 ==",
"== Chapter 19 ==",
"== Chapter 20 ==",
"== Chapter 21 ==",
"== Chapter 22 ==",
"== Chapter 23 ==",
"== Chapter 24 ==",
"== Chapter 25 ==",
"== Chapter 26 ==",
"== Chapter 27 ==",
"== Chapter 28 ==",
"== Chapter 29 ==",
"== Chapter 30 ==",
"== Chapter 31 ==",
"== Chapter 32 ==",
"== Chapter 33 ==",
"== Chapter 34 ==",
"== Chapter 35 ==",
"== Chapter 36 ==",
"== Chapter 37 ==",
"== Chapter 38 ==",
"== Chapter 39 ==",
"== Chapter 40 ==",
"== Chapter 41 ==",
"== Chapter 42 ==",
"== Chapter 43 ==",
"== Chapter 44 ==",
"== Chapter 45 ==",
"== Chapter 46 ==",
"== Chapter 47 ==",
"== Chapter 48 ==",
"== Chapter 49 ==",
"== Chapter 50 ==",
"== Chapter 51 ==",
"== Chapter 52 ==",
"== Chapter 53 ==",
"== Chapter 54 ==",
"== Chapter 55 ==",
"== Chapter 56 ==",
"== Chapter 57 ==",
"== Chapter 58 ==",
"== Chapter 59 ==",
"== Chapter 60 ==",
"== Chapter 61 ==",
"== Chapter 62 ==",
"== Chapter 63 ==",
"== Chapter 64 ==",
"== Chapter 65 ==",
"== Chapter 66 ==",
"== Chapter 67 ==",
"== Chapter 68 ==",
"== Chapter 69 ==",
"== Chapter 70 ==",
"== Chapter 71 ==",
"== Chapter 72 ==",
"== Appendix ==",
"=== House Baratheon ===",
"=== House Stark ===",
"=== House Lannister ===",
"=== House Arryn ===",
"=== House Tully ===",
"=== House Tyrell ===",
"=== House Greyjoy ===",
"=== House Martell ===",
"=== The Old Dynasty: House Targaryen ===",
"== Acknowledgments ==",
"== Preview of A Game of Thrones Graphic Novel",
"= A Clash of Kings =",
"== Dedication ==",
"== Maps ==",
"== Prologue ==",
"== Chapter 1 ==",
"== Chapter 2 ==",
"== Chapter 3 ==",
"== Chapter 4 ==",
"== Chapter 5 ==",
"== Chapter 6 ==",
"== Chapter 7 ==",
"== Chapter 8 ==",
"== Chapter 9 ==",
"== Chapter 10 ==",
"== Chapter 11 ==",
"== Chapter 12 ==",
"== Chapter 13 ==",
"== Chapter 14 ==",
"== Chapter 15 ==",
"== Chapter 16 ==",
"== Chapter 17 ==",
"== Chapter 18 ==",
"== Chapter 19 ==",
"== Chapter 20 ==",
"== Chapter 21 ==",
"== Chapter 22 ==",
"== Chapter 23 ==",
"== Chapter 24 ==",
"== Chapter 25 ==",
"== Chapter 26 ==",
"== Chapter 27 ==",
"== Chapter 28 ==",
"== Chapter 29 ==",
"== Chapter 30 ==",
"== Chapter 31 ==",
"== Chapter 32 ==",
"== Chapter 33 ==",
"== Chapter 34 ==",
"== Chapter 35 ==",
"== Chapter 36 ==",
"== Chapter 37 ==",
"== Chapter 38 ==",
"== Chapter 39 ==",
"== Chapter 40 ==",
"== Chapter 41 ==",
"== Chapter 42 ==",
"== Chapter 43 ==",
"== Chapter 44 ==",
"== Chapter 45 ==",
"== Chapter 46 ==",
"== Chapter 47 ==",
"== Chapter 48 ==",
"== Chapter 49 ==",
"== Chapter 50 ==",
"== Chapter 51 ==",
"== Chapter 52 ==",
"== Chapter 53 ==",
"== Chapter 54 ==",
"== Chapter 55 ==",
"== Chapter 56 ==",
"== Chapter 57 ==",
"== Chapter 58 ==",
"== Chapter 59 ==",
"== Chapter 60 ==",
"== Chapter 61 ==",
"== Chapter 62 ==",
"== Chapter 63 ==",
"== Chapter 64 ==",
"== Chapter 65 ==",
"== Chapter 66 ==",
"== Chapter 67 ==",
"== Chapter 68 ==",
"== Chapter 69 ==",
"== Appendix: The Kings and Their Courts ==",
"=== The King on the Iron Throne ===",
"=== The King in the Narrow Sea ===",
"=== The King in Highgarden ===",
"=== The King in the North ===",
"=== The Queen Across the Water ===",
"== Other Houses Great and Small ==",
"=== House Arryn ===",
"=== House Florent ===",
"=== House Frey ===",
"=== House Greyjoy ===",
"=== House Lannister ===",
"=== House Martell ===",
"=== House Tyrell ===",
"=== The Men of the Night’s Watch ===",
"== Acknowledgments ==",
"= A Storm of Swords =",
"== Dedication ==",
"== A Note on Chronology ==",
"== Maps ==",
"== Prologue ==",
"== Chapter 1 ==",
"== Chapter 2 ==",
"== Chapter 3 ==",
"== Chapter 4 ==",
"== Chapter 5 ==",
"== Chapter 6 ==",
"== Chapter 7 ==",
"== Chapter 8 ==",
"== Chapter 9 ==",
"== Chapter 10 ==",
"== Chapter 11 ==",
"== Chapter 12 ==",
"== Chapter 13 ==",
"== Chapter 14 ==",
"== Chapter 15 ==",
"== Chapter 16 ==",
"== Chapter 17 ==",
"== Chapter 18 ==",
"== Chapter 19 ==",
"== Chapter 20 ==",
"== Chapter 21 ==",
"== Chapter 22 ==",
"== Chapter 23 ==",
"== Chapter 24 ==",
"== Chapter 25 ==",
"== Chapter 26 ==",
"== Chapter 27 ==",
"== Chapter 28 ==",
"== Chapter 29 ==",
"== Chapter 30 ==",
"== Chapter 31 ==",
"== Chapter 32 ==",
"== Chapter 33 ==",
"== Chapter 34 ==",
"== Chapter 35 ==",
"== Chapter 36 ==",
"== Chapter 37 ==",
"== Chapter 38 ==",
"== Chapter 39 ==",
"== Chapter 40 ==",
"== Chapter 41 ==",
"== Chapter 42 ==",
"== Chapter 43 ==",
"== Chapter 44 ==",
"== Chapter 45 ==",
"== Chapter 46 ==",
"== Chapter 47 ==",
"== Chapter 48 ==",
"== Chapter 49 ==",
"== Chapter 50 ==",
"== Chapter 51 ==",
"== Chapter 52 ==",
"== Chapter 53 ==",
"== Chapter 54 ==",
"== Chapter 55 ==",
"== Chapter 56 ==",
"== Chapter 57 ==",
"== Chapter 58 ==",
"== Chapter 59 ==",
"== Chapter 60 ==",
"== Chapter 61 ==",
"== Chapter 62 ==",
"== Chapter 63 ==",
"== Chapter 64 ==",
"== Chapter 65 ==",
"== Chapter 66 ==",
"== Chapter 67 ==",
"== Chapter 68 ==",
"== Chapter 69 ==",
"== Chapter 70 ==",
"== Chapter 71 ==",
"== Chapter 72 ==",
"== Chapter 73 ==",
"== Chapter 74 ==",
"== Chapter 75 ==",
"== Chapter 76 ==",
"== Chapter 77 ==",
"== Chapter 78 ==",
"== Chapter 79 ==",
"== Chapter 80 ==",
"== Epilogue ==",
"== Appendix ==",
"== The Kings and Their Courts ==",
"=== The King on the Iron Throne ===",
"=== The King in the North The King of the Trident ===",
"=== The King in the Narrow Sea ===",
"=== The Queen Across the Water ===",
"=== King of the Isles and the North ===",
"== Other Houses Great and Small ==",
"=== House Arryn ===",
"=== House Florent ===",
"=== House Frey ===",
"=== House Lannister ===",
"=== House Martell ===",
"=== House Tully ===",
"=== House Tyrell ===",
"== Rebels, Rogues, and Sworn Brothers ==",
"=== The Sworn Brothers of the Night’s Watch ===",
"=== The Brotherhood Without Banners: An Outlaw Fellowship ===",
"=== The Wildlings, or the Free Folk ===",
"== Acknowledgments ==",
"= A Feast for Crows =",
"== Dedication ==",
"== Maps ==",
"== Prologue ==",
"== Chapter 1 ==",
"== Chapter 2 ==",
"== Chapter 3 ==",
"== Chapter 4 ==",
"== Chapter 5 ==",
"== Chapter 6 ==",
"== Chapter 7 ==",
"== Chapter 8 ==",
"== Chapter 9 ==",
"== Chapter 10 ==",
"== Chapter 11 ==",
"== Chapter 12 ==",
"== Chapter 13 ==",
"== Chapter 14 ==",
"== Chapter 15 ==",
"== Chapter 16 ==",
"== Chapter 17 ==",
"== Chapter 18 ==",
"== Chapter 19 ==",
"== Chapter 20 ==",
"== Chapter 21 ==",
"== Chapter 22 ==",
"== Chapter 23 ==",
"== Chapter 24 ==",
"== Chapter 25 ==",
"== Chapter 26 ==",
"== Chapter 27 ==",
"== Chapter 28 ==",
"== Chapter 29 ==",
"== Chapter 30 ==",
"== Chapter 31 ==",
"== Chapter 32 ==",
"== Chapter 33 ==",
"== Chapter 34 ==",
"== Chapter 35 ==",
"== Chapter 36 ==",
"== Chapter 37 ==",
"== Chapter 38 ==",
"== Chapter 39 ==",
"== Chapter 40 ==",
"== Chapter 41 ==",
"== Chapter 42 ==",
"== Chapter 43 ==",
"== Chapter 44 ==",
"== Chapter 45 ==",
"== Chapter 46 ==",
"== Appendix I: The Kings and Their Courts ==",
"=== The Queen Regent ===",
"=== The King at the Wall ===",
"=== King of the Isles and the North ===",
"== Appendix II: Other Houses Great and Small ==",
"=== House Arryn ===",
"=== House Florent ===",
"=== House Frey ===",
"=== House Hightower ===",
"=== House Lannister ===",
"=== House Martell ===",
"=== House Stark ===",
"=== House Tully ===",
"=== House Tyrell ===",
"== Appendix III: Rebels and Rogues Smallfolk and Sworn Brothers ==",
"=== Lordlings, Wanderers, and Common Men ===",
"=== Outlaws and Broken Men ===",
"=== The Sworn Brothers of the Night’s Watch ===",
"=== The Wildlings, or the Free Folk ===",
"== Appendix IV: Beyond the Narrow Sea ==",
"=== The Queen Across the Water ===",
"=== In Braavos ===",
"== Acknowledgments ==",
"= A Dance with Dragons =",
"== Dedication ==",
"== A Cavil on Chronology ==",
"== Maps ==",
"== Prologue ==",
"== Chapter 1 ==",
"== Chapter 2 ==",
"== Chapter 3 ==",
"== Chapter 4 ==",
"== Chapter 5 ==",
"== Chapter 6 ==",
"== Chapter 7 ==",
"== Chapter 8 ==",
"== Chapter 9 ==",
"== Chapter 10 ==",
"== Chapter 11 ==",
"== Chapter 12 ==",
"== Chapter 13 ==",
"== Chapter 14 ==",
"== Chapter 15 ==",
"== Chapter 16 ==",
"== Chapter 17 ==",
"== Chapter 18 ==",
"== Chapter 19 ==",
"== Chapter 20 ==",
"== Chapter 21 ==",
"== Chapter 22 ==",
"== Chapter 23 ==",
"== Chapter 24 ==",
"== Chapter 25 ==",
"== Chapter 26 ==",
"== Chapter 27 ==",
"== Chapter 28 ==",
"== Chapter 29 ==",
"== Chapter 30 ==",
"== Chapter 31 ==",
"== Chapter 32 ==",
"== Chapter 33 ==",
"== Chapter 34 ==",
"== Chapter 35 ==",
"== Chapter 36 ==",
"== Chapter 37 ==",
"== Chapter 38 ==",
"== Chapter 39 ==",
"== Chapter 40 ==",
"== Chapter 41 ==",
"== Chapter 42 ==",
"== Chapter 43 ==",
"== Chapter 44 ==",
"== Chapter 45 ==",
"== Chapter 46 ==",
"== Chapter 47 ==",
"== Chapter 48 ==",
"== Chapter 49 ==",
"== Chapter 50 ==",
"== Chapter 51 ==",
"== Chapter 52 ==",
"== Chapter 53 ==",
"== Chapter 54 ==",
"== Chapter 55 ==",
"== Chapter 56 ==",
"== Chapter 57 ==",
"== Chapter 58 ==",
"== Chapter 59 ==",
"== Chapter 60 ==",
"== Chapter 61 ==",
"== Chapter 62 ==",
"== Chapter 63 ==",
"== Chapter 64 ==",
"== Chapter 65 ==",
"== Chapter 66 ==",
"== Chapter 67 ==",
"== Chapter 68 ==",
"== Chapter 69 ==",
"== Chapter 70 ==",
"== Chapter 71 ==",
"== Epilogue ==",
"== Appendix ==",
"=== Westeros ===",
"==== The Boy King ====",
"==== The King at the Wall ====",
"==== King of the Isles and the North ====",
"=== Other Houses Great and Small ===",
"==== House Arryn ====",
"==== House Baratheon ====",
"==== House Frey ====",
"==== House Lannister ====",
"==== House Martell ====",
"==== House Stark ====",
"==== House Tully ====",
"==== House Tyrell ====",
"==== The Sworn Brothers of the Night’s Watch ====",
"==== The Wildings, or the Free Folk ====",
"==== Beyond the Wall ====",
"=== Essos Beyond the Narrow Sea ===",
"==== In Braavos ====",
"==== In Old Volantis ====",
"==== On Slaver’s Bay ====",
"==== The Queen Across the Water ====",
"==== The Sellswords Men and Women of the Free Companies ====",
"== Acknowledgments ==",
"== Other Books by This Author ==",
"== About the Author ==",
];
