var menulist=[
"===== CONTENTS =====",
"==== &mdash; CHAPTER ONE &mdash; ====",
"= The Boy Who Lived =",
"==== &mdash; CHAPTER TWO &mdash; ====",
"= The Vanishing Glass =",
"==== &mdash; CHAPTER THREE &mdash; ====",
"= The Letters from No One =",
"==== &mdash; CHAPTER FOUR &mdash; ====",
"= The Keeper of the Keys =",
"==== &mdash; CHAPTER FIVE &mdash; ====",
"= Diagon Alley =",
"==== &mdash; CHAPTER SIX &mdash; ====",
"= The Journey from Platform Nine and Three-Quarters =",
"==== &mdash; CHAPTER SEVEN &mdash; ====",
"= The Sorting Hat =",
"==== &mdash; CHAPTER EIGHT &mdash; ====",
"= The Potions Master =",
"==== &mdash; CHAPTER NINE &mdash; ====",
"= The Midnight Duel =",
"==== &mdash; CHAPTER TEN &mdash; ====",
"= Hallowe’en =",
"==== &mdash; CHAPTER ELEVEN &mdash; ====",
"= Quidditch =",
"==== &mdash; CHAPTER TWELVE &mdash; ====",
"= The Mirror of Erised =",
"==== &mdash; CHAPTER THIRTEEN &mdash; ====",
"= Nicolas Flamel =",
"==== &mdash; CHAPTER FOURTEEN &mdash; ====",
"= Norbert the Norwegian Ridgeback =",
"==== &mdash; CHAPTER FIFTEEN &mdash; ====",
"= The Forbidden Forest =",
"==== &mdash; CHAPTER SIXTEEN &mdash; ====",
"= Through the Trapdoor =",
"==== &mdash; CHAPTER SEVENTEEN &mdash; ====",
"= The Man with Two Faces =",
"===== CONTENTS =====",
"==== &mdash; CHAPTER ONE &mdash; ====",
"= The Worst Birthday =",
"==== &mdash; CHAPTER TWO &mdash; ====",
"= Dobby’s Warning =",
"==== &mdash; CHAPTER THREE &mdash; ====",
"= The Burrow =",
"==== &mdash; CHAPTER FOUR &mdash; ====",
"= At Flourish and Blotts =",
"==== &mdash; CHAPTER FIVE &mdash; ====",
"= The Whomping Willow =",
"==== &mdash; CHAPTER SIX &mdash; ====",
"= Gilderoy Lockhart =",
"==== &mdash; CHAPTER SEVEN &mdash; ====",
"= Mudbloods and Murmurs =",
"==== &mdash; CHAPTER EIGHT &mdash; ====",
"= The Deathday Party =",
"==== &mdash; CHAPTER NINE &mdash; ====",
"= The Writing on the Wall =",
"==== &mdash; CHAPTER TEN &mdash; ====",
"= The Rogue Bludger =",
"==== &mdash; CHAPTER ELEVEN &mdash; ====",
"= The Duelling Club =",
"==== &mdash; CHAPTER TWELVE &mdash; ====",
"= The Polyjuice Potion =",
"==== &mdash; CHAPTER THIRTEEN &mdash; ====",
"= The Very Secret Diary =",
"==== &mdash; CHAPTER FOURTEEN &mdash; ====",
"= Cornelius Fudge =",
"==== &mdash; CHAPTER FIFTEEN &mdash; ====",
"= Aragog =",
"==== &mdash; CHAPTER SIXTEEN &mdash; ====",
"= The Chamber of Secrets =",
"==== &mdash; CHAPTER SEVENTEEN &mdash; ====",
"= The Heir of Slytherin =",
"==== &mdash; CHAPTER EIGHTEEN &mdash; ====",
"= Dobby’s Reward =",
"===== CONTENTS =====",
"==== &ndash; CHAPTER ONE &ndash; ====",
"= Owl Post =",
"==== &mdash; CHAPTER TWO &mdash; ====",
"= Aunt Marge’s Big Mistake =",
"==== &ndash; CHAPTER THREE &ndash; ====",
"= The Knight Bus =",
"==== &ndash; CHAPTER FOUR &ndash; ====",
"= The Leaky Cauldron =",
"==== &ndash; CHAPTER FIVE &ndash; ====",
"= The Dementor =",
"==== &ndash; CHAPTER SIX &ndash; ====",
"= Talons and Tea Leaves =",
"==== &ndash; CHAPTER SEVEN &ndash; ====",
"= The Boggart in the Wardrobe =",
"==== &ndash; CHAPTER EIGHT &ndash; ====",
"= Flight of the Fat Lady =",
"==== &ndash; CHAPTER NINE &ndash; ====",
"= Grim Defeat =",
"==== &ndash; CHAPTER TEN &ndash; ====",
"= The Marauder’s Map =",
"==== &ndash; CHAPTER ELEVEN &ndash; ====",
"= The Firebolt =",
"==== &ndash; CHAPTER TWELVE &ndash; ====",
"= The Patronus =",
"==== &ndash; CHAPTER THIRTEEN &ndash; ====",
"= Gryffindor versus Ravenclaw =",
"==== &ndash; CHAPTER FOURTEEN &ndash; ====",
"= Snape’s Grudge =",
"==== &ndash; CHAPTER FIFTEEN &ndash; ====",
"= The Quidditch Final =",
"==== &ndash; CHAPTER SIXTEEN &ndash; ====",
"= Professor Trelawney’s Prediction =",
"==== &ndash; CHAPTER SEVENTEEN &ndash; ====",
"= Cat, Rat and Dog =",
"==== &ndash; CHAPTER EIGHTEEN &ndash; ====",
"= Moony, Wormtail, Padfoot and Prongs =",
"==== &ndash; CHAPTER NINETEEN &ndash; ====",
"= The Servant of Lord Voldemort =",
"==== &ndash; CHAPTER TWENTY &ndash; ====",
"= The Dementor’s Kiss =",
"==== &ndash; CHAPTER TWENTY-ONE &ndash; ====",
"= Hermione’s Secret =",
"==== &ndash; CHAPTER TWENTY-TWO &ndash; ====",
"= Owl Post Again =",
"===== CONTENTS =====",
"==== &mdash; CHAPTER ONE &mdash; ====",
"= The Riddle House =",
"==== &mdash; CHAPTER TWO &mdash; ====",
"= The Scar =",
"==== &mdash; CHAPTER THREE &mdash; ====",
"= The Invitation =",
"==== &mdash; CHAPTER FOUR &mdash; ====",
"= Back to The Burrow =",
"==== &mdash; CHAPTER FIVE &mdash; ====",
"= Weasleys’ Wizard Wheezes =",
"==== &mdash; CHAPTER SIX &mdash; ====",
"= The Portkey =",
"==== &mdash; CHAPTER SEVEN &mdash; ====",
"= Bagman and Crouch =",
"==== &mdash; CHAPTER EIGHT &mdash; ====",
"= The Quidditch World Cup =",
"==== &mdash; CHAPTER NINE &mdash; ====",
"= The Dark Mark =",
"==== &mdash; CHAPTER TEN &mdash; ====",
"= Mayhem at the Ministry =",
"==== &mdash; CHAPTER ELEVEN &mdash; ====",
"= Aboard the Hogwarts Express =",
"==== &mdash; CHAPTER TWELVE &mdash; ====",
"= The Triwizard Tournament =",
"==== &mdash; CHAPTER THIRTEEN &mdash; ====",
"= Mad-Eye Moody =",
"==== &mdash; CHAPTER FOURTEEN &mdash; ====",
"= The Unforgivable Curses =",
"==== &mdash; CHAPTER FIFTEEN &mdash; ====",
"= Beauxbatons and Durmstrang =",
"==== &mdash; CHAPTER SIXTEEN &mdash; ====",
"= The Goblet of Fire =",
"==== &mdash; CHAPTER SEVENTEEN &mdash; ====",
"= The Four Champions =",
"==== &mdash; CHAPTER EIGHTEEN &mdash; ====",
"= The Weighing of the Wands =",
"==== &mdash; CHAPTER NINETEEN &mdash; ====",
"= The Hungarian Horntail =",
"==== &mdash; CHAPTER TWENTY &mdash; ====",
"= The First Task =",
"==== &mdash; CHAPTER TWENTY-ONE &mdash; ====",
"= The House-Elf Liberation Front =",
"==== &mdash; CHAPTER TWENTY-TWO &mdash; ====",
"= The Unexpected Task =",
"==== &mdash; CHAPTER TWENTY-THREE &mdash; ====",
"= The Yule Ball =",
"==== &mdash; CHAPTER TWENTY-FOUR &mdash; ====",
"= Rita Skeeter’s Scoop =",
"==== &mdash; CHAPTER TWENTY-FIVE &mdash; ====",
"= The Egg and the Eye =",
"==== &mdash; CHAPTER TWENTY-SIX &mdash; ====",
"= The Second Task =",
"==== &mdash; CHAPTER TWENTY-SEVEN &mdash; ====",
"= Padfoot Returns =",
"==== &mdash; CHAPTER TWENTY-EIGHT &mdash; ====",
"= The Madness of Mr Crouch =",
"==== &mdash; CHAPTER TWENTY-NINE &mdash; ====",
"= The Dream =",
"==== &mdash; CHAPTER THIRTY &mdash; ====",
"= The Pensieve =",
"==== &mdash; CHAPTER THIRTY-ONE &mdash; ====",
"= The Third Task =",
"==== &mdash; CHAPTER THIRTY-TWO &mdash; ====",
"= Flesh, Blood and Bone =",
"==== &mdash; CHAPTER THIRTY-THREE &mdash; ====",
"= The Death Eaters =",
"==== &mdash; CHAPTER THIRTY-FOUR &mdash; ====",
"= Priori Incantatem =",
"==== &mdash; CHAPTER THIRTY-FIVE &mdash; ====",
"= Veritaserum =",
"==== &mdash; CHAPTER THIRTY-SIX &mdash; ====",
"= The Parting of the Ways =",
"==== &mdash; CHAPTER THIRTY-SEVEN &mdash; ====",
"= The Beginning =",
"===== CONTENTS =====",
"==== &mdash; CHAPTER ONE &mdash; ====",
"= Dudley Demented =",
"==== &mdash; CHAPTER TWO &mdash; ====",
"= A Peck of Owls =",
"==== &mdash; CHAPTER THREE &mdash; ====",
"= The Advance Guard =",
"==== &mdash; CHAPTER FOUR &mdash; ====",
"= Number Twelve, Grimmauld Place =",
"==== &mdash; CHAPTER FIVE &mdash; ====",
"= The Order of the Phoenix =",
"==== &mdash; CHAPTER SIX &mdash; ====",
"= The Noble and Most Ancient House of Black =",
"==== &mdash; CHAPTER SEVEN &mdash; ====",
"= The Ministry of Magic =",
"==== &mdash; CHAPTER EIGHT &mdash; ====",
"= The Hearing =",
"==== &mdash; CHAPTER NINE &mdash; ====",
"= The Woes of Mrs Weasley =",
"==== &mdash; CHAPTER TEN &mdash; ====",
"= Luna Lovegood =",
"==== &mdash; CHAPTER ELEVEN &mdash; ====",
"= The Sorting Hat’s New Song =",
"==== &mdash; CHAPTER TWELVE &mdash; ====",
"= Professor Umbridge =",
"==== &mdash; CHAPTER THIRTEEN &mdash; ====",
"= Detention with Dolores =",
"==== &mdash; CHAPTER FOURTEEN &mdash; ====",
"= Percy and Padfoot =",
"==== &mdash; CHAPTER FIFTEEN &mdash; ====",
"= The Hogwarts High Inquisitor =",
"==== &mdash; CHAPTER SIXTEEN &mdash; ====",
"= In the Hog’s Head =",
"==== &mdash; CHAPTER SEVENTEEN &mdash; ====",
"= Educational Decree Number Twenty-Four =",
"==== &mdash; CHAPTER EIGHTEEN &mdash; ====",
"= Dumbledore’s Army =",
"==== &mdash; CHAPTER NINETEEN &mdash; ====",
"= The Lion and the Serpent =",
"==== &mdash; CHAPTER TWENTY &mdash; ====",
"= Hagrid’s Tale =",
"==== &mdash; CHAPTER TWENTY-ONE &mdash; ====",
"= The Eye of the Snake =",
"==== &mdash; CHAPTER TWENTY-TWO &mdash; ====",
"= St Mungo’s Hospital for Magical Maladies and Injuries =",
"==== &mdash; CHAPTER TWENTY-THREE &mdash; ====",
"= Christmas on the Closed Ward =",
"==== &mdash; CHAPTER TWENTY-FOUR &mdash; ====",
"= Occlumency =",
"==== &mdash; CHAPTER TWENTY-FIVE &mdash; ====",
"= The Beetle at Bay =",
"==== &mdash; CHAPTER TWENTY-SIX &mdash; ====",
"= Seen and Unforeseen =",
"==== &mdash; CHAPTER TWENTY-SEVEN &mdash; ====",
"= The Centaur and the Sneak =",
"==== &mdash; CHAPTER TWENTY-EIGHT &mdash; ====",
"= Snape’s Worst Memory =",
"==== &mdash; CHAPTER TWENTY-NINE &mdash; ====",
"= Careers Advice =",
"==== &mdash; CHAPTER THIRTY &mdash; ====",
"= Grawp =",
"==== &mdash; CHAPTER THIRTY-ONE &mdash; ====",
"= O.W.L.s =",
"==== &mdash; CHAPTER THIRTY-TWO &mdash; ====",
"= Out of the Fire =",
"==== &mdash; CHAPTER THIRTY-THREE &mdash; ====",
"= Fight and Flight =",
"==== &mdash; CHAPTER THIRTY-FOUR &mdash; ====",
"= The Department of Mysteries =",
"==== &mdash; CHAPTER THIRTY-FIVE &mdash; ====",
"= Beyond the Veil =",
"==== &mdash; CHAPTER THIRTY-SIX &mdash; ====",
"= The Only One He Ever Feared =",
"==== &mdash; CHAPTER THIRTY-SEVEN &mdash; ====",
"= The Lost Prophecy =",
"==== &mdash; CHAPTER THIRTY-EIGHT &mdash; ====",
"= The Second War Begins =",
"===== CONTENTS =====",
"==== &mdash; CHAPTER ONE &mdash; ====",
"= The Other Minister =",
"==== &mdash; CHAPTER TWO &mdash; ====",
"= Spinner’s End =",
"==== &mdash; CHAPTER THREE &mdash; ====",
"= Will and Won’t =",
"==== &mdash; CHAPTER FOUR &mdash; ====",
"= Horace Slughorn =",
"==== &mdash; CHAPTER FIVE &mdash; ====",
"= An Excess of Phlegm =",
"==== &mdash; CHAPTER SIX &mdash; ====",
"= Draco’s Detour =",
"==== &mdash; CHAPTER SEVEN &mdash; ====",
"= The Slug Club =",
"==== &mdash; CHAPTER EIGHT &mdash; ====",
"= Snape Victorious =",
"==== &mdash; CHAPTER NINE &mdash; ====",
"= The Half-Blood Prince =",
"==== &mdash; CHAPTER TEN &mdash; ====",
"= The House of Gaunt =",
"==== &mdash; CHAPTER ELEVEN &mdash; ====",
"= Hermione’s Helping Hand =",
"==== &mdash; CHAPTER TWELVE &mdash; ====",
"= Silver and Opals =",
"==== &mdash; CHAPTER THIRTEEN &mdash; ====",
"= The Secret Riddle =",
"==== &mdash; CHAPTER FOURTEEN &mdash; ====",
"= Felix Felicis =",
"==== &mdash; CHAPTER FIFTEEN &mdash; ====",
"= The Unbreakable Vow =",
"==== &mdash; CHAPTER SIXTEEN &mdash; ====",
"= A Very Frosty Christmas =",
"==== &mdash; CHAPTER SEVENTEEN &mdash; ====",
"= A Sluggish Memory =",
"==== &mdash; CHAPTER EIGHTEEN &mdash; ====",
"= Birthday Surprises =",
"==== &mdash; CHAPTER NINETEEN &mdash; ====",
"= Elf Tails =",
"==== &mdash; CHAPTER TWENTY &mdash; ====",
"= Lord Voldemort’s Request =",
"==== &mdash; CHAPTER TWENTY-ONE &mdash; ====",
"= The Unknowable Room =",
"==== &mdash; CHAPTER TWENTY-TWO &mdash; ====",
"= After the Burial =",
"==== &mdash; CHAPTER TWENTY-THREE &mdash; ====",
"= Horcruxes =",
"==== &mdash; CHAPTER TWENTY-FOUR &mdash; ====",
"= Sectumsempra =",
"==== &mdash; CHAPTER TWENTY-FIVE &mdash; ====",
"= The Seer Overheard =",
"==== &mdash; CHAPTER TWENTY-SIX &mdash; ====",
"= The Cave =",
"==== &mdash; CHAPTER TWENTY-SEVEN &mdash; ====",
"= The Lightning-Struck Tower =",
"==== &mdash; CHAPTER TWENTY-EIGHT &mdash; ====",
"= Flight of the Prince =",
"==== &mdash; CHAPTER TWENTY-NINE &mdash; ====",
"= The Phoenix Lament =",
"==== &mdash; CHAPTER THIRTY &mdash; ====",
"= The White Tomb =",
"===== CONTENTS =====",
"==== &mdash; CHAPTER ONE &mdash; ====",
"= The Dark Lord Ascending =",
"==== &mdash; CHAPTER TWO &mdash; ====",
"= In Memoriam =",
"==== &mdash; CHAPTER THREE &mdash; ====",
"= The Dursleys Departing =",
"==== &mdash; CHAPTER FOUR &mdash; ====",
"= The Seven Potters =",
"==== &mdash; CHAPTER FIVE &mdash; ====",
"= Fallen Warrior =",
"==== &mdash; CHAPTER SIX &mdash; ====",
"= The Ghoul in Pyjamas =",
"==== &mdash; CHAPTER SEVEN &mdash; ====",
"= The Will of Albus Dumbledore =",
"==== &mdash; CHAPTER EIGHT &mdash; ====",
"= The Wedding =",
"==== &mdash; CHAPTER NINE &mdash; ====",
"= A Place to Hide =",
"==== &mdash; CHAPTER TEN &mdash; ====",
"= Kreacher’s Tale =",
"==== &mdash; CHAPTER ELEVEN &mdash; ====",
"= The Bribe =",
"==== &mdash; CHAPTER TWELVE &mdash; ====",
"= Magic is Might =",
"==== &mdash; CHAPTER THIRTEEN &mdash; ====",
"= The Muggle-Born Registration Commission =",
"==== &mdash; CHAPTER FOURTEEN &mdash; ====",
"= The Thief =",
"==== &mdash; CHAPTER FIFTEEN &mdash; ====",
"= The Goblin’s Revenge =",
"==== &mdash; CHAPTER SIXTEEN &mdash; ====",
"= Godric’s Hollow =",
"==== &mdash; CHAPTER SEVENTEEN &mdash; ====",
"= Bathilda’s Secret =",
"==== &mdash; CHAPTER EIGHTEEN &mdash; ====",
"= The Life and Lies of Albus Dumbledore =",
"==== &mdash; CHAPTER NINETEEN &mdash; ====",
"= The Silver Doe =",
"==== &mdash; CHAPTER TWENTY &mdash; ====",
"= Xenophilius Lovegood =",
"==== &mdash; CHAPTER TWENTY-ONE &mdash; ====",
"= The Tale of the Three Brothers =",
"==== &mdash; CHAPTER TWENTY-TWO &mdash; ====",
"= The Deathly Hallows =",
"==== &mdash; CHAPTER TWENTY-THREE &mdash; ====",
"= Malfoy Manor =",
"==== &mdash; CHAPTER TWENTY-FOUR &mdash; ====",
"= The Wandmaker =",
"==== &mdash; CHAPTER TWENTY-FIVE &mdash; ====",
"= Shell Cottage =",
"==== &mdash; CHAPTER TWENTY-SIX &mdash; ====",
"= Gringotts =",
"==== &mdash; CHAPTER TWENTY-SEVEN &mdash; ====",
"= The Final Hiding Place =",
"==== &mdash; CHAPTER TWENTY-EIGHT &mdash; ====",
"= The Missing Mirror =",
"==== &mdash; CHAPTER TWENTY-NINE &mdash; ====",
"= The Lost Diadem =",
"==== &mdash; CHAPTER THIRTY &mdash; ====",
"= The Sacking of Severus Snape =",
"==== &mdash; CHAPTER THIRTY-ONE &mdash; ====",
"= The Battle of Hogwarts =",
"==== &mdash; CHAPTER THIRTY-TWO &mdash; ====",
"= The Elder Wand =",
"==== &mdash; CHAPTER THIRTY-THREE &mdash; ====",
"= The Prince’s Tale =",
"==== &mdash; CHAPTER THIRTY-FOUR &mdash; ====",
"= The Forest Again =",
"==== &mdash; CHAPTER THIRTY-FIVE &mdash; ====",
"= King’s Cross =",
"==== &mdash; CHAPTER THIRTY-SIX &mdash; ====",
"= The Flaw in the Plan =",
"= Nineteen Years Later =",
];
