var menulist=[
"==== &mdash; CHAPTER ONE &mdash; ====",
"= The Boy Who Lived =",
"==== &mdash; CHAPTER TWO &mdash; ====",
"= The Vanishing Glass =",
"==== &mdash; CHAPTER THREE &mdash; ====",
"= The Letters from No One =",
"==== &mdash; CHAPTER FOUR &mdash; ====",
"= The Keeper of the Keys =",
"==== &mdash; CHAPTER FIVE &mdash; ====",
"= Diagon Alley =",
"==== &mdash; CHAPTER SIX &mdash; ====",
"= The Journey from Platform Nine and Three-Quarters =",
"==== &mdash; CHAPTER SEVEN &mdash; ====",
"= The Sorting Hat =",
"==== &mdash; CHAPTER EIGHT &mdash; ====",
"= The Potions Master =",
"==== &mdash; CHAPTER NINE &mdash; ====",
"= The Midnight Duel =",
"==== &mdash; CHAPTER TEN &mdash; ====",
"= Hallowe’en =",
"==== &mdash; CHAPTER ELEVEN &mdash; ====",
"= Quidditch =",
"==== &mdash; CHAPTER TWELVE &mdash; ====",
"= The Mirror of Erised =",
"==== &mdash; CHAPTER THIRTEEN &mdash; ====",
"= Nicolas Flamel =",
"==== &mdash; CHAPTER FOURTEEN &mdash; ====",
"= Norbert the Norwegian Ridgeback =",
"==== &mdash; CHAPTER FIFTEEN &mdash; ====",
"= The Forbidden Forest =",
"==== &mdash; CHAPTER SIXTEEN &mdash; ====",
"= Through the Trapdoor =",
"==== &mdash; CHAPTER SEVENTEEN &mdash; ====",
"= The Man with Two Faces =",
"==== &mdash; CHAPTER ONE &mdash; ====",
"= The Worst Birthday =",
];
