var menulist=[
"= Chapter01 安娜 =",
"= Chapter02 佩格一家 =",
"= Chapter03 在码头上 =",
"= Chapter04 老房子 =",
"= Chapter05 随心所欲的安娜 =",
"= Chapter06 呆板无趣的家伙 =",
"= Chapter07 “肥猪” =",
"= Chapter08 宾戈游戏之夜 =",
"= Chapter09 女孩和小船 =",
"= Chapter10 腌海蓬草 =",
"= Chapter11 每次三个问题 =",
"= Chapter12 佩格太太打碎了茶壶 =",
"= Chapter13 流浪女 =",
"= Chapter14 舞会之后 =",
"= Chapter15 再来找我！ =",
"= Chapter16 蘑菇和秘密 =",
"= Chapter17 世上最幸运的女孩 =",
"= Chapter18 爱德华到来以后 =",
"= Chapter19 风车 =",
"= Chapter20 不再是朋友 =",
"= Chapter21 窗户后面的玛妮 =",
"= Chapter22 别墅的另一侧 =",
"= Chapter23 追逐 =",
"= Chapter24 被捉住了！ =",
"= Chapter25 林赛一家 =",
"= Chapter26 西拉的秘密 =",
"= Chapter27 西拉是如何发现秘密的 =",
"= Chapter28 日记 =",
"= Chapter29 关于船的讨论 =",
"= Chapter30 普雷斯顿太太的来信 =",
"= Chapter31 普雷斯顿太太受到邀请 =",
"= Chapter32 坦白 =",
"= Chapter33 佩内洛普·吉利小姐 =",
"= Chapter34 吉利小姐讲故事 =",
"= Chapter35 谁的错？ =",
"= Chapter36 故事的结尾 =",
"= Chapter37 再见，多余儿！ =",
"= 后记 =",
"= 关于安娜，关于玛妮。 =",
];
