var menulist=[
"== 译者卷首语 ==",
"== 篇一 作为隐喻的疾病 ==",
"=== 引子 ===",
"=== 1 ===",
"=== 2 ===",
"=== 3 ===",
"=== 4 ===",
"=== 5 ===",
"=== 6 ===",
"=== 7 ===",
"=== 8 ===",
"=== 9 ===",
"== 篇二 艾滋病及其隐喻 ==",
"=== 1 ===",
"=== 2 ===",
"=== 3 ===",
"=== 4 ===",
"=== 5 ===",
"=== 6 ===",
"=== 7 ===",
"=== 8 ===",
"== 译后记 ==",
"== ILLNESS AS METAPHOR ==",
"=== Chapter One ===",
"=== Chapter Two ===",
"=== Chapter Three ===",
"=== Chapter Four ===",
"=== Chapter Five ===",
"=== Chapter Six ===",
"=== Chapter Seven ===",
"=== Chapter Eight ===",
"=== Chapter Nine ===",
"== AIDS AND ITS METAPHORS ==",
"=== Chapter One ===",
"=== Chapter Two ===",
"=== Chapter Three ===",
"=== Chapter Four ===",
"=== Chapter Five ===",
"=== Chapter Six ===",
"=== Chapter Seven ===",
"=== Chapter Eight ===",
];
