var menulist=[
"= “A TAUT THRILLER&nbsp;… FASCINATING&nbsp;… =",
"= “AN EXCITING, FAST-PACED TALE THAT’S HARD TO PUT DOWN.” =",
"= &mdash;Milwaukee Journal =",
"= “[A] DEFT SCIENTIFIC THRILLER&nbsp;…&nbsp;A SNAPPY NIGHTMARE OF SCIENCE RUN AMOK.” =",
"= &mdash;The Wall Street Journal =",
"= Contents =",
"= INTRODUCTION =",
"= PROLOGUE: THE BITE OF THE RAPTOR =",
"= FIRST ITERATION =",
"= ALMOST PARADISE =",
"= PUNTARENAS =",
"= THE BEACH =",
"= NEW YORK =",
"= THE SHAPE OF THE DATA =",
"= SECOND ITERATION =",
"= THE SHORE OF THE INLAND SEA =",
"= SKELETON =",
"= COWAN, SWAIN AND ROSS =",
"= PLANS =",
"= HAMMOND =",
"= CHOTEAU =",
"= TARGET OF OPPORTUNITY =",
"= AIRPORT =",
"= MALCOLM =",
"= ISLA NUBLAR =",
"= WELCOME =",
"= THIRD ITERATION =",
"= JURASSIC PARK =",
"= WHEN DINOSAURS RULED THE EARTH =",
"= THE TOUR =",
"= CONTROL =",
"= VERSION 4.4 =",
"= CONTROL =",
"= THE TOUR =",
"= CONTROL =",
"= BIG REX =",
"= CONTROL =",
"= STEGOSAUR =",
"= CONTROL =",
"= BREEDING SITES =",
"= FOURTH ITERATION =",
"= THE MAIN ROAD =",
"= RETURN =",
"= NEDRY =",
"= BUNGALOW =",
"= TIM =",
"= LEX =",
"= CONTROL =",
"= THE ROAD =",
"= CONTROL =",
"= IN THE PARK =",
"= CONTROL =",
"= THE PARK =",
"= DAWN =",
"= THE PARK =",
"= FIFTH ITERATION =",
"= SEARCH =",
"= AVIARY =",
"= TYRANNOSAUR =",
"= CONTROL =",
"= SIXTH ITERATION =",
"= RETURN =",
"= THE GRID =",
"= LODGE =",
"= CONTROL =",
"= SEVENTH ITERATION =",
"= DESTROYING THE WORLD =",
"= UNDER CONTROL =",
"= ALMOST PARADIGM =",
"= DESCENT =",
"= HAMMOND =",
"= THE BEACH =",
"= APPROACHING DARK =",
"= EPILOGUE: SAN JOSÉ =",
"= ACKNOWLEDGMENTS =",
"= ABOUT THE AUTHOR =",
"= 	What’s next on your reading list? =",
];
