var menulist=[
"== Contents ==",
"== Title Page ==",
"== Dedication ==",
"== Author's Note ==",
"== Part One: Toronto and Pondicherry ==",
"=== Chapter One ===",
"=== Chapter Two ===",
"=== Chapter Three ===",
"=== Chapter Four ===",
"=== Chapter Five ===",
"=== Chapter Six ===",
"=== Chapter Seven ===",
"=== Chapter Eight ===",
"=== Chapter Nine ===",
"=== Chapter Ten ===",
"=== Chapter Eleven ===",
"=== Chapter Twelve ===",
"=== Chapter Thirteen ===",
"=== Chapter Fourteen ===",
"=== Chapter Fifteen ===",
"=== Chapter Sixteen ===",
"=== Chapter Seventeen ===",
"=== Chapter Eighteen ===",
"=== Chapter Nineteen ===",
"=== Chapter Twenty ===",
"=== Chapter Twenty One ===",
"=== Chapter Twenty Two ===",
"=== Chapter Twenty Three ===",
"=== Chapter Twenty Four ===",
"=== Chapter Twenty Five ===",
"=== Chapter Twenty Six ===",
"=== Chapter Twenty Seven ===",
"=== Chapter Twenty Eight ===",
"=== Chapter Twenty Nine ===",
"=== Chapter Thirty ===",
"=== Chapter Thirty One ===",
"=== Chapter Thirty Two ===",
"=== Chapter Thirty Three ===",
"=== Chapter Thirty Four ===",
"=== Chapter Thirty Five ===",
"=== Chapter Thirty Six ===",
"== Part Two: The Pacific Ocean ==",
"=== Chapter Thirty Seven ===",
"=== Chapter Thirty Eight ===",
"=== Chapter Thirty Nine ===",
"=== Chapter Forty ===",
"=== Chapter Forty One ===",
"=== Chapter Forty Two ===",
"=== Chapter Forty Three ===",
"=== Chapter Forty Four ===",
"=== Chapter Forty Five ===",
"=== Chapter Forty Six ===",
"=== Chapter Forty Seven ===",
"=== Chapter Forty Eight ===",
"=== Chapter Forty Nine ===",
"=== Chapter Fifty ===",
"=== Chapter Fifty One ===",
"=== Chapter Fifty Two ===",
"=== Chapter Fifty Three ===",
"=== Chapter Fifty Four ===",
"=== Chapter Fifty Five ===",
"=== Chapter Fifty Six ===",
"=== Chapter Fifty Seven ===",
"=== Chapter Fifty Eight ===",
"=== Chapter Fifty Nine ===",
"=== Chapter Sixty ===",
"=== Chapter Sixty One ===",
"=== Chapter Sixty Two ===",
"=== Chapter Sixty Three ===",
"=== Chapter Sixty Four ===",
"=== Chapter Sixty Five ===",
"=== Chapter Sixty Six ===",
"=== Chapter Sixty Seven ===",
"=== Chapter Sixty Eight ===",
"=== Chapter Sixty Nine ===",
"=== Chapter Seventy ===",
"=== Chapter Seventy One ===",
"=== Chapter Seventy Two ===",
"=== Chapter Seventy Three ===",
"=== Chapter Seventy Four ===",
"=== Chapter Seventy Five ===",
"=== Chapter Seventy Six ===",
"=== Chapter Seventy Seven ===",
"=== Chapter Seventy Eight ===",
"=== Chapter Seventy Nine ===",
"=== Chapter Eighty ===",
"=== Chapter Eighty One ===",
"=== Chapter Eighty Two ===",
"=== Chapter Eighty Three ===",
"=== Chapter Eighty Four ===",
"=== Chapter Eighty Five ===",
"=== Chapter Eighty Six ===",
"=== Chapter Eighty Seven ===",
"=== Chapter Eighty Eight ===",
"=== Chapter Eighty Nine ===",
"=== Chapter Ninety ===",
"=== Chapter Ninety One ===",
"=== Chapter Ninety Two ===",
"=== Chapter Ninety Three ===",
"=== Chapter Ninety Four ===",
"== Part Three: Benito Juárez Infirmary,Tomatlán, Mexico ==",
"=== Chapter Ninety Five ===",
"=== Chapter Ninety Six ===",
"=== Chapter Ninety Seven ===",
"=== Chapter Ninety Eight ===",
"=== Chapter Ninety Nine ===",
"=== Chapter Hundred ===",
"== About the Author ==",
"== Copyright ==",
];
