var menulist=[
"= 第一章 =",
"= 黑马厩镇的童年 =",
"==== A Blackstable Boyhood ====",
"= 第二章 =",
"= 圣托马斯医院 =",
"==== At St. Thomas's Hospital ====",
"= 第三章 =",
"= 本能作家 =",
"==== A Writer by Instinct ====",
"= 第四章 =",
"= 白猫餐厅 =",
"==== Le Chat Blanc ====",
"= 第五章 =",
"= 英伦剧匠 =",
"==== England's Dramatist ====",
"= 第六章 =",
"= 西莉 =",
"==== Syrie ====",
"= 第七章 =",
"= 代号“萨默维尔” =",
"==== Code Name “Somerville” ====",
"= 第八章 =",
"= 面纱背后 =",
"==== Behind the Painted Veil ====",
"= 第九章 =",
"= 游廊与三角帆船的国度 =",
"==== A World of Veranda and Prahu ====",
"= 第十章 =",
"= 分居 =",
"==== Separation ====",
"= 第十一章 =",
"= 玛莱斯科别墅 =",
"==== The Villa Mauresque ====",
"= 第十二章 =",
"= 哈克主人 =",
"==== Master Hacky ====",
"= 第十三章 =",
"= 讲故事的人 =",
"==== The Teller of Tales ====",
"= 第十四章 =",
"= 投身宣传 =",
"==== An Exercise in Propaganda ====",
"= 第十五章 =",
"= 布隆基诺男孩 =",
"==== The Bronzino Boy ====",
"= 第十六章 =",
"= 背叛 =",
"==== Betrayal ====",
"= 致谢 =",
"==== Acknowledgments ====",
"= 注释 =",
"==== Source Notes ====",
"= 部分参考文献 =",
"==== Select Bibliography ====",
"= 插图版权 =",
"==== Illustration Credits ====",
];
