var menulist=[
"== TITLE PAGE ==",
"== COPYRIGHT PAGE ==",
"== PROLOGUE ==",
"== CHAPTER 1 ==",
"== CHAPTER 2 ==",
"== CHAPTER 3 ==",
"== CHAPTER 4 ==",
"== CHAPTER 5 ==",
"== CHAPTER 6 ==",
"== CHAPTER 7 ==",
"== CHAPTER 8 ==",
"== CHAPTER 9 ==",
"== CHAPTER 10 ==",
"== CHAPTER 11 ==",
"== CHAPTER 12 ==",
"== CHAPTER 13 ==",
"== EPILOGUE ==",
"== DEDICATION ==",
"== ACKNOWLEDGMENTS ==",
"== ALSO BY MARIO PUZO ==",
"== ABOUT THE AUTHOR ==",
];
