var menulist=[
"== Cover ==",
"== Introduction ==",
"== Title Page ==",
"== Copyright ==",
"== Prologue ==",
"== Chapter 1 ==",
"== Chapter 2 ==",
"== Chapter 3 ==",
"== Chapter 4 ==",
"== Chapter 5 ==",
"== Chapter 6 ==",
"== Chapter 7 ==",
"== Chapter 8 ==",
"== Chapter 9 ==",
"== About the Author ==",
"== Introduction to the Star Wars Expanded Universe ==",
"== Excerpt from Star Wars: Heir to the Empire ==",
"== Introduction to the Old Republic Era ==",
"== Introduction to the Rise of the Empire Era ==",
"== Introduction to the Rebellion Era ==",
"== Introduction to the New Republic Era ==",
"== Introduction to the New Jedi Order Era ==",
"== Introduction to the Legacy Era ==",
"== Star Wars Novels Timeline ==",
];
