var menulist=[
"== Cover ==",
"== Other Books by This Author ==",
"== Title Page ==",
"== Copyright ==",
"== Introduction: The Age of Heroes ==",
"== Part One: Victory ==",
"===   1: Anakin and Obi-Wan ===",
"===   2: Dooku ===",
"===   3: The Way of the Sith ===",
"===   4: Jedi Trap ===",
"===   5: Grievous ===",
"===   6: Rescue ===",
"===   7: Obi-Wan and Anakin 2 ===",
"== Part Two: Seduction ==",
"===   8: Fault Lines ===",
"===   9: Padmé ===",
"=== 10: Masters ===",
"=== 11: Politics ===",
"=== 12: Not From a Jedi ===",
"=== 13: The Will of the Force ===",
"=== 14: Free Fall in the Dark ===",
"=== 15: Death on Utapau ===",
"=== 16: Revelation ===",
"== Part Three: Apocalypse ==",
"=== 17: The Face of the Dark ===",
"=== 18: Order Sixty-Six ===",
"=== 19: The Face of the Sith ===",
"=== 20: Chiaroscuro ===",
"=== 21: A New Jedi Order ===",
"== Dedication ==",
"== About the Author ==",
"== Also by this Author ==",
"== Preview of Star Wars: Dark Lord ==",
"== Introduction to the Star Wars Expanded Universe ==",
"== Excerpt from Sar Wars: Dark Lord: The Rise of Darth Vader ==",
"== Introduction to the Old Republic Era ==",
"== Introduction to the Rise of the Empire Era ==",
"== Introduction to the Rebellion Era ==",
"== Introduction to the New Republic Era ==",
"== Introduction to the New Jedi Order Era ==",
"== Introduction to the Legacy Era ==",
"== Star Wars Novels Timeline ==",
];
