var menulist=[
"== Cover ==",
"== Title Page ==",
"== Copyright ==",
"== Prologue ==",
"== Part I: Search by the Mule ==",
"=== Chapter 1: Two Men and the Mule ===",
"=== Chapter 2: Two Men Without the Mule ===",
"=== Chapter 3: Two Men and a Peasant ===",
"=== Chapter 4: Two Men and the Elders ===",
"=== Chapter 5: One Man and the Mule ===",
"=== Chapter 6: One Man, the Mule— and Another ===",
"== Part II: Search by the Foundation ==",
"=== Chapter 7: Arcadia ===",
"=== Chapter 8: Seldon’s Plan ===",
"=== Chapter 9: The Conspirators ===",
"=== Chapter 10: Approaching Crisis ===",
"=== Chapter 11: Stowaway ===",
"=== Chapter 12: Lord ===",
"=== Chapter 13: Lady ===",
"=== Chapter 14: Anxiety ===",
"=== Chapter 15: Through the Grid ===",
"=== Chapter 16: Beginning of War ===",
"=== Chapter 17: War ===",
"=== Chapter 18: Ghost of a World ===",
"=== Chapter 19: End of War ===",
"=== Chapter 20: “I Know…” ===",
"=== Chapter 21: The Answer That Satisfied ===",
"=== Chapter 22: The Answer That Was True ===",
"== Dedication ==",
"== By Isaac Asimov ==",
"== About the Author ==",
];
