var menulist=[
"== Title Page ==",
"== Copyright ==",
"== NOTE ON THE TEXT ==",
"== NOTE ON THE 50TH ANNIVERSARY EDITION ==",
"== FOREWORD TO THE SECOND EDITION ==",
"== PROLOGUE Concerning Hobbits, and other matters ==",
"== THE FELLOWSHIP OF THE RING ==",
"=== BOOK ONE ===",
"==== Chapter 1: A LONG-EXPECTED PARTY ====",
"==== Chapter 2: THE SHADOW OF THE PAST ====",
"==== Chapter 3: THREE IS COMPANY ====",
"==== Chapter 4: A SHORT CUT TO MUSHROOMS ====",
"==== Chapter 5: A CONSPIRACY UNMASKED ====",
"==== Chapter 6: THE OLD FOREST ====",
"==== Chapter 7: IN THE HOUSE OF TOM BOMBADIL ====",
"==== Chapter 8: FOG ON THE BARROW-DOWNS ====",
"==== Chapter 9: AT THE SIGN OF THE PRANCING PONY ====",
"==== Chapter 10: STRIDER ====",
"==== Chapter 11: A KNIFE IN THE DARK ====",
"==== Chapter 12: FLIGHT TO THE FORD ====",
"=== BOOK TWO ===",
"==== Chapter 1: MANY MEETINGS ====",
"==== Chapter 2: THE COUNCIL OF ELROND ====",
"==== Chapter 3: THE RING GOES SOUTH ====",
"==== Chapter 4: A JOURNEY IN THE DARK ====",
"==== Chapter 5: THE BRIDGE OF KHAZAD-DÛM ====",
"==== Chapter 6: LOTHLÓRIEN ====",
"==== Chapter 7: THE MIRROR OF GALADRIEL ====",
"==== Chapter 8: FAREWELL TO LÓRIEN ====",
"==== Chapter 9: THE GREAT RIVER ====",
"==== Chapter 10: THE BREAKING OF THE FELLOWSHIP ====",
"== THE TWO TOWERS ==",
"=== BOOK THREE ===",
"==== Chapter 1: THE DEPARTURE OF BOROMIR ====",
"==== Chapter 2: THE RIDERS OF ROHAN ====",
"==== Chapter 3: THE URUK-HAI ====",
"==== Chapter 4: TREEBEARD ====",
"==== Chapter 5: THE WHITE RIDER ====",
"==== Chapter 6: THE KING OF THE GOLDEN HALL ====",
"==== Chapter 7: HELM’S DEEP ====",
"==== Chapter 8: THE ROAD TO ISENGARD ====",
"==== Chapter 9: FLOTSAM AND JETSAM ====",
"==== Chapter 10: THE VOICE OF SARUMAN ====",
"==== Chapter 11: THE PALANTÍR ====",
"=== BOOK FOUR ===",
"==== Chapter 1: THE TAMING OF SMÉAGOL ====",
"==== Chapter 2: THE PASSAGE OF THE MARSHES ====",
"==== Chapter 3: THE BLACK GATE IS CLOSED ====",
"==== Chapter 4: OF HERBS AND STEWED RABBIT ====",
"==== Chapter 5: THE WINDOW ON THE WEST ====",
"==== Chapter 6: THE FORBIDDEN POOL ====",
"==== Chapter 7: JOURNEY TO THE CROSS-ROADS ====",
"==== Chapter 8: THE STAIRS OF CIRITH UNGOL ====",
"==== Chapter 9: SHELOB’S LAIR ====",
"==== Chapter 10: THE CHOICES OF MASTER SAMWISE ====",
"== THE RETURN OF THE KING ==",
"=== BOOK FIVE ===",
"==== Chapter 1: MINAS TIRITH ====",
"==== Chapter 2: THE PASSING OF THE GREY COMPANY ====",
"==== Chapter 3: THE MUSTER OF ROHAN ====",
"==== Chapter 4: THE SIEGE OF GONDOR ====",
"==== Chapter 5: THE RIDE OF THE ROHIRRIM ====",
"==== Chapter 6: THE BATTLE OF THE PELENNOR FIELDS ====",
"==== Chapter 7: THE PYRE OF DENETHOR ====",
"==== Chapter 8: THE HOUSES OF HEALING ====",
"==== Chapter 9: THE LAST DEBATE ====",
"==== Chapter 10: THE BLACK GATE OPENS ====",
"=== BOOK SIX ===",
"==== Chapter 1: THE TOWER OF CIRITH UNGOL ====",
"==== Chapter 2: THE LAND OF SHADOW ====",
"==== Chapter 3: MOUNT DOOM ====",
"==== Chapter 4: THE FIELD OF CORMALLEN ====",
"==== Chapter 5: THE STEWARD AND THE KING ====",
"==== Chapter 6: MANY PARTINGS ====",
"==== Chapter 7: HOMEWARD BOUND ====",
"==== Chapter 8: THE SCOURING OF THE SHIRE ====",
"==== Chapter 9: THE GREY HAVENS ====",
"== APPENDIX A: ANNALS OF THE KINGS AND RULERS ==",
"== APPENDIX B: THE TALE OF YEARS ==",
"== APPENDIX C: FAMILY TREES ==",
"== APPENDIX D: SHIRE CALENDAR FOR USE IN ALL YEARS ==",
"== APPENDIX E: WRITING AND SPELLING ==",
"== APPENDIX F: I THE LANGUAGES AND PEOPLES OF THE THIRD AGE ==",
"== INDEX ==",
"== MAPS ==",
"== Keep Reading ==",
"== Works by J.R.R. Tolkien ==",
"== About the Publisher ==",
];
