var menulist=[
"= “PRACTICAL POLITICS”&mdash;AND THE DEATH OF A WORLD =",
"= CONTENTS =",
"= I. Against Stupidity&nbsp;… =",
"== 6 ==",
"== 1 ==",
"== 6 (continued) ==",
"== 2 ==",
"== 3 ==",
"== 6 (continued) ==",
"== 4 ==",
"== 5 ==",
"== 6 (concluded) ==",
"== 7 ==",
"== 8 ==",
"== 9 ==",
"== 10 ==",
"= II. … The Gods Themselves&nbsp;… =",
"== 1a ==",
"== 1b ==",
"== 1c ==",
"== 2a ==",
"== 2b ==",
"== 2c ==",
"== 3a ==",
"== 3b ==",
"== 3c ==",
"== 4a ==",
"== 4b ==",
"== 4c ==",
"== 5a ==",
"== 5b ==",
"== 5c ==",
"== 6a ==",
"== 6b ==",
"== 7abc ==",
"= III. … Contend in Vain? =",
"== 1 ==",
"== 2 ==",
"== 3 ==",
"== 4 ==",
"== 5 ==",
"== 6 ==",
"== 7 ==",
"== 8 ==",
"== 9 ==",
"== 10 ==",
"== 11 ==",
"== 12 ==",
"== 13 ==",
"== 14 ==",
"== 15 ==",
"== 16 ==",
"== 17 ==",
"== 18 ==",
"== 19 ==",
"= Bantam Spectra Books by Isaac Asimov =",
"= ABOUT THE AUTHOR =",
];
