var menulist=[
"= “SOLID ENTERTAINMENT&nbsp;… =",
"= Contents =",
"== Introduction: “Extinction at the K-T Boundary” ==",
"== Prologue: “Life at the Edge of Chaos” ==",
"== The Lost World Hypothesis ==",
"== FIRST CONFIGURATION ==",
"== Aberrant Forms ==",
"== San José ==",
"== Departure ==",
"== Palo Alto ==",
"== Berkeley ==",
"== The Lost World ==",
"== School ==",
"== Tag ==",
"== Thorne ==",
"== SECOND CONFIGURATION ==",
"== Clues ==",
"== Raptor ==",
"== The Five Deaths ==",
"== James ==",
"== Field Systems ==",
"== Harding ==",
"== Message ==",
"== Exploitation ==",
"== THIRD CONFIGURATION ==",
"== Costa Rica ==",
"== Isla Sorna ==",
"== The Stream ==",
"== The Road ==",
"== Site B ==",
"== Trailer ==",
"== Interior ==",
"== Arby ==",
"== Laboratory ==",
"== Power ==",
"== Nest ==",
"= FOURTH CONFIGURATION =",
"== Levine ==",
"== Dodgson ==",
"== The High Hide ==",
"== The Red Queen ==",
"== Puerto Cortés ==",
"== King ==",
"== Harding ==",
"== The Valley ==",
"== Cave ==",
"== Dodgson ==",
"== Mating Calls ==",
"== Problems of Evolution ==",
"== Parasaurs ==",
"== Heat ==",
"== Noise ==",
"== Trail ==",
"== Nest ==",
"== The High Hide ==",
"== Trailer ==",
"== Nest ==",
"== Dodgson ==",
"== Decision ==",
"== Nest ==",
"== Gambler’s Ruin ==",
"== King ==",
"== Bad News ==",
"= FIFTH CONFIGURATION =",
"== Baby ==",
"== The High Hide ==",
"== The Herd ==",
"== Dodgson ==",
"== Trailer ==",
"== Thorne ==",
"== Trailer ==",
"== The High Hide ==",
"== Malcolm ==",
"== The High Hide ==",
"= SIXTH CONFIGURATION =",
"== Chase ==",
"== At the Edge of Chaos ==",
"== Trailer ==",
"== Village ==",
"== Good Mother ==",
"== Dodgson ==",
"== Explorer ==",
"== Daylight ==",
"== A Way Out ==",
"== Escape ==",
"== Exit ==",
"= SEVENTH CONFIGURATION =",
"== Departure ==",
"== Acknowledgments ==",
"= ABOUT THE AUTHOR =",
];
