var menulist=[
"= Acknowledgments =",
"= Miracles =",
"= Ghosts =",
"= Reunion =",
"= Phone Calls =",
"= Kayaks and Forgotten Dreams =",
"= Moving Water =",
"= Swans and Storms =",
"= Courtrooms =",
"= An Unexpected Visitor =",
"= Crossroads =",
"= A Letter from Yesterday =",
"= Winter for Two =",
"= <jsdocimg>00003.jpeg</jsdocimg> =",
"= ALSO BY NICHOLAS SPARKS =",
"= THE WORLD LOVES NICHOLAS SPARKS =",
"= Reading Group Guide =",
"= A Q &amp; A with Nicholas Sparks =",
"= Discussion Questions =",
"= Nicholas Sparks on Nicholas Sparks =",
"= Discover more from Nicholas Sparks =",
"== Message in a Bottle ==",
"== A Walk to Remember ==",
"== The Rescue ==",
"== A Bend in the Road ==",
"== Nights in Rodanthe ==",
"== The Guardian ==",
"== The Wedding ==",
"== True Believer ==",
"== At First Sight ==",
"== Dear John ==",
"== The Choice ==",
"== The Lucky One ==",
"== The Last Song ==",
"== Safe Haven ==",
"== The Best of Me ==",
"== All of these novels are available now from Sphere ==",
"= Contents =",
"= Navigation =",
"= Copyright =",
"= PART I =",
"= TRU =",
];
