var menulist=[
"== Title Page ==",
"== Copyright Page ==",
"== Book 1 ==",
"=== Chapter 1 ===",
"== Book 2 ==",
"=== Chapter 2 ===",
"=== Chapter 3 ===",
"=== Chapter 4 ===",
"=== Chapter 5 ===",
"=== Chapter 6 ===",
"=== Chapter 7 ===",
"=== Chapter 8 ===",
"=== Chapter 9 ===",
"=== Chapter 10 ===",
"=== Chapter 11 ===",
"=== Chapter 12 ===",
"=== Chapter 13 ===",
"=== Chapter 14 ===",
"=== Chapter 15 ===",
"== Book 3 ==",
"=== Chapter 16 ===",
"=== Chapter 17 ===",
"== Book 4 ==",
"=== Chapter 18 ===",
"=== Chapter 19 ===",
"=== Chapter 20 ===",
"=== Chapter 21 ===",
"=== Chapter 22 ===",
"=== Chapter 23 ===",
"=== Chapter 24 ===",
"== Book 5 ==",
"=== Chapter 25 ===",
"=== Chapter 26 ===",
"=== Chapter 27 ===",
"=== Chapter 28 ===",
"=== Chapter 29 ===",
"=== Chapter 30 ===",
"=== Chapter 31 ===",
"== Dedication ==",
"== Also by Mario Puzo ==",
];
