var menulist=[
"== Cover ==",
"== About the Book ==",
"== Title Page ==",
"== Dedication ==",
"== Epigraph ==",
"== 1. The Boy Who Belonged to St Cloud’s ==",
"== 2. The Lord’s Work ==",
"== 3. Princes of Maine, Kings of New England ==",
"== 4. Young Dr Wells ==",
"== 5. Homer Breaks a Promise ==",
"== 6. Ocean View ==",
"== 7. Before the War ==",
"== 8. Opportunity Knocks ==",
"== 9. Over Burma ==",
"== 10. Fifteen Years ==",
"== 11. Breaking the Rules ==",
"== Afterword ==",
"== Author’s Notes ==",
"== In One Person Extract ==",
"== About the Author ==",
"== Also by John Irving ==",
"== Copyright ==",
];
