var menulist=[
"= CONTENTS =",
"= I =",
"== Statue ==",
"== The Ardua Hall Holograph ==",
"== 1 ==",
"= II =",
"== PRECIOUS FLOWER ==",
"== Transcript of Witness Testimony 369A ==",
"== 2 ==",
"== 3 ==",
"== 4 ==",
"== 5 ==",
"= III =",
"== Hymn ==",
"== The Ardua Hall Holograph ==",
"== 6 ==",
"= IV =",
"== THE CLOTHES HOUND ==",
"== Transcript of Witness Testimony 369B ==",
"== 7 ==",
"== 8 ==",
"== 9 ==",
"== 10 ==",
"== 11 ==",
"= V =",
"== Van ==",
"== The Ardua Hall Holograph ==",
"== 12 ==",
"= VI =",
"== SIX FOR DEAD ==",
"== Transcript of Witness Testimony 369A ==",
"== 13 ==",
"== 14 ==",
"== 15 ==",
"== 16 ==",
"== 17 ==",
"== 18 ==",
"== 19 ==",
"= VII =",
"== Stadium ==",
"== The Ardua Hall Holograph ==",
"== 20 ==",
"= VIII =",
"== CARNARVON ==",
"== Transcript of Witness Testimony 369B ==",
"== 21 ==",
"== 22 ==",
"== 23 ==",
"= IX =",
"== Thank Tank ==",
"== The Ardua Hall Holograph ==",
"== 24 ==",
"= X =",
"== SPRING GREEN ==",
"== Transcript of Witness Testimony 369A ==",
"== 25 ==",
"== 26 ==",
"== 27 ==",
"== 28 ==",
"= XI =",
"== Sackcloth ==",
"== The Ardua Hall Holograph ==",
"== 29 ==",
"= XII =",
"== CARPITZ ==",
"== Transcript of Witness Testimony 369B ==",
"== 30 ==",
"== 31 ==",
"== 32 ==",
"== 33 ==",
"= XIII =",
"== Secateurs ==",
"== The Ardua Hall Holograph ==",
"== 34 ==",
"= XIV =",
"== ARDUA HALL ==",
"== Transcript of Witness Testimony 369A ==",
"== 35 ==",
"== 36 ==",
"== 37 ==",
"== 38 ==",
"== 39 ==",
"== 40 ==",
"= XV =",
"== Fox and Cat ==",
"== The Ardua Hall Holograph ==",
"== 41 ==",
"= XVI =",
"== PEARL GIRLS ==",
"== Transcript of Witness Testimony 369B ==",
"== 42 ==",
"== 43 ==",
"== 44 ==",
"== 45 ==",
"= XVII =",
"== Perfect Teeth ==",
"== The Ardua Hall Holograph ==",
"== 46 ==",
"= XVIII =",
"== READING ROOM ==",
"== Transcript of Witness Testimony 369A ==",
"== 47 ==",
"== 48 ==",
"== 49 ==",
"== 50 ==",
"== 51 ==",
"= XIX =",
"== Study ==",
"== The Ardua Hall Holograph ==",
"== 52 ==",
"= XX =",
"== BLOODLINES ==",
"== Transcript of Witness Testimony 369B ==",
"== 53 ==",
"== Transcript of Witness Testimony 369A ==",
"== 54 ==",
"== Transcript of Witness Testimony 369B ==",
"== 55 ==",
"== Transcript of Witness Testimony 369A ==",
"== 56 ==",
"== Transcript of Witness Testimony 369B ==",
"== 57 ==",
"== Transcript of Witness Testimony 369A ==",
"== 58 ==",
"= XXI =",
"== Fast and Thick ==",
"== The Ardua Hall Holograph ==",
"== 59 ==",
"= XXII =",
"== HEARTSTOPPER ==",
"== Transcript of Witness Testimony 369A ==",
"== 60 ==",
"== 61 ==",
"== Transcript of Witness Testimony 369B ==",
"== 62 ==",
"== Transcript of Witness Testimony 369A ==",
"== 63 ==",
"== Transcript of Witness Testimony 369B ==",
"== 64 ==",
"= XXIII =",
"== Wall ==",
"== The Ardua Hall Holograph ==",
"== 65 ==",
"= XXIV =",
"== THE NELLIE J. BANKS ==",
"== Transcript of Witness Testimony 369B ==",
"== 66 ==",
"== Transcript of Witness Testimony 369A ==",
"== 67 ==",
"= XXV =",
"== Wakeup ==",
"== The Ardua Hall Holograph ==",
"== 68 ==",
"= XXVI =",
"== LANDFALL ==",
"== Transcript of Witness Testimony 369A ==",
"== 69 ==",
"== Transcript of Witness Testimony 369B ==",
"== 70 ==",
"= XXVII =",
"== Sendoff ==",
"== The Ardua Hall Holograph ==",
"== 71 ==",
"== The Thirteenth Symposium ==",
"= HISTORICAL NOTES =",
"= Acknowledgements =",
"= A Trip to the Archive with Margaret Atwood =",
"= ABOUT THE AUTHOR =",
];
