var menulist=[
"= POEMS LYRICAL AND NARRATIVE BEING THE FIRST VOLUME OF THE COLLECTED WORKS IN VERSE AND PROSE OF WILLIAM BUTLER YEATS IMPRINTED AT THE SHAKESPEARE HEAD PRESS STRATFORD-ON-AVON MCMVIII =",
"== CONTENTS ==",
"== THE WIND AMONG THE REEDS ==",
"=== THE HOSTING OF THE SIDHE ===",
"=== THE EVERLASTING VOICES ===",
"=== THE MOODS ===",
"=== THE LOVER TELLS OF THE ROSE IN HIS HEART ===",
"=== THE HOST OF THE AIR ===",
"=== THE FISHERMAN ===",
"=== A CRADLE SONG ===",
"=== INTO THE TWILIGHT ===",
"=== THE SONG OF WANDERING AENGUS ===",
"=== THE HEART OF THE WOMAN ===",
"=== THE LOVER MOURNS FOR THE LOSS OF LOVE ===",
"=== HE MOURNS FOR THE CHANGE THAT HAS COME UPON HIM AND HIS BELOVED AND LONGS FOR THE END OF THE WORLD ===",
"=== HE BIDS HIS BELOVED BE AT PEACE ===",
"=== HE REPROVES THE CURLEW ===",
"=== HE REMEMBERS FORGOTTEN BEAUTY ===",
"=== A POET TO HIS BELOVED ===",
"=== HE GIVES HIS BELOVED CERTAIN RHYMES ===",
"=== TO MY HEART, BIDDING IT HAVE NO FEAR ===",
"=== THE CAP AND BELLS ===",
"=== THE VALLEY OF THE BLACK PIG ===",
"=== THE LOVER ASKS FORGIVENESS BECAUSE OF HIS MANY MOODS ===",
"=== HE TELLS OF A VALLEY FULL OF LOVERS ===",
"=== HE TELLS OF THE PERFECT BEAUTY ===",
"=== HE HEARS THE CRY OF THE SEDGE ===",
"=== HE THINKS OF THOSE WHO HAVE SPOKEN EVIL OF HIS BELOVED ===",
"=== THE BLESSED ===",
"=== THE SECRET ROSE ===",
"=== MAID QUIET ===",
"=== THE TRAVAIL OF PASSION ===",
"=== THE LOVER PLEADS WITH HIS FRIEND FOR OLD FRIENDS ===",
"=== A LOVER SPEAKS TO THE HEARERS OF HIS SONGS IN COMING DAYS ===",
"=== THE POET PLEADS WITH THE ELEMENTAL POWERS ===",
"=== HE WISHES HIS BELOVED WERE DEAD ===",
"=== HE WISHES FOR THE CLOTHS OF HEAVEN ===",
"=== HE THINKS OF HIS PAST GREATNESS WHEN A PART OF THE CONSTELLATIONS OF HEAVEN ===",
"== THE OLD AGE OF QUEEN MAEVE ==",
"== BAILE AND AILLINN ==",
"== IN THE SEVEN WOODS ==",
"=== THE ARROW ===",
"=== THE FOLLY OF BEING COMFORTED ===",
"=== OLD MEMORY ===",
"=== NEVER GIVE ALL THE HEART ===",
"=== THE WITHERING OF THE BOUGHS ===",
"=== ADAM’S CURSE ===",
"=== RED HANRAHAN’S SONG ABOUT IRELAND ===",
"=== THE OLD MEN ADMIRING THEMSELVES IN THE WATER ===",
"=== UNDER THE MOON ===",
"=== THE HOLLOW WOOD ===",
"=== O DO NOT LOVE TOO LONG ===",
"=== THE PLAYERS ASK FOR A BLESSING ON THE PSALTERIES AND ON THEMSELVES ===",
"=== THE HAPPY TOWNLAND ===",
"== EARLY POEMS I BALLADS AND LYRICS ==",
"== EARLY POEMS: BALLADS AND LYRICS ==",
"=== THE SONG OF THE HAPPY SHEPHERD ===",
"=== THE SAD SHEPHERD ===",
"=== THE CLOAK, THE BOAT, AND THE SHOES ===",
"=== ANASHUYA AND VIJAYA ===",
"=== THE INDIAN UPON GOD ===",
"=== THE INDIAN TO HIS LOVE ===",
"=== THE FALLING OF THE LEAVES ===",
"=== EPHEMERA ===",
"=== THE MADNESS OF KING GOLL ===",
"=== THE STOLEN CHILD ===",
"=== TO AN ISLE IN THE WATER ===",
"=== DOWN BY THE SALLEY GARDENS ===",
"=== THE MEDITATION OF THE OLD FISHERMAN ===",
"=== THE BALLAD OF FATHER O’HART ===",
"=== THE BALLAD OF MOLL MAGEE ===",
"=== THE BALLAD OF THE FOXHUNTER ===",
"=== THE BALLAD OF FATHER GILLIGAN ===",
"=== THE LAMENTATION OF THE OLD PENSIONER ===",
"=== THE FIDDLER OF DOONEY ===",
"=== THE DEDICATION TO A BOOK OF STORIES SELECTED FROM THE IRISH NOVELISTS ===",
"== EARLY POEMS II THE ROSE ==",
"== EARLY POEMS: THE ROSE ==",
"=== TO THE ROSE UPON THE ROOD OF TIME ===",
"=== FERGUS AND THE DRUID ===",
"=== THE DEATH OF CUCHULAIN ===",
"=== THE ROSE OF THE WORLD ===",
"=== THE ROSE OF PEACE ===",
"=== THE ROSE OF BATTLE ===",
"=== A FAERY SONG ===",
"=== THE LAKE ISLE OF INNISFREE ===",
"=== A CRADLE SONG ===",
"=== THE SONG OF THE OLD MOTHER ===",
"=== THE PITY OF LOVE ===",
"=== THE SORROW OF LOVE ===",
"=== WHEN YOU ARE OLD ===",
"=== THE WHITE BIRDS ===",
"=== A DREAM OF DEATH ===",
"=== A DREAM OF A BLESSED SPIRIT ===",
"=== THE MAN WHO DREAMED OF FAERYLAND ===",
"=== THE TWO TREES ===",
"=== TO IRELAND IN THE COMING TIMES ===",
"== EARLY POEMS III THE WANDERINGS OF OISIN ==",
"== BOOK I ==",
"== THE WANDERINGS OF OISIN ==",
"== BOOK II ==",
"== THE WANDERINGS OF OISIN ==",
"== BOOK III ==",
"== THE WANDERINGS OF OISIN ==",
"== NOTES ==",
"=== THE WIND AMONG THE REEDS. ===",
"==== The Hosting of the Sidhe . ====",
"==== The Poet pleads with the Elemental Powers . He thinks of his past Greatness when a part of the Constellations of Heaven . He hears the Cry of the Sedge . ====",
"==== The Host of the Air . ====",
"==== The Song of Wandering Aengus . ====",
"==== He Mourns for the Change that has Come upon Him and His Beloved, and Longs for the End of the World . ====",
"==== The Cap and Bells . ====",
"==== The Valley of the Black Pig . ====",
"==== The Secret Rose . ====",
"=== EARLY POEMS: ===",
"==== Ballads and Lyrics . ‘ The Rose ’ . ‘ The Wanderings of Oisin ’ . ====",
"= THE KING’S THRESHOLD. ON BAILE’S STRAND. DEIRDRE. SHADOWY WATERS :: BEING THE SECOND VOLUME OF THE COLLECTED WORKS IN VERSE &amp; PROSE OF WILLIAM BUTLER YEATS :: IMPRINTED AT THE SHAKESPEARE HEAD PRESS STRATFORD-ON-AVON MCMVIII =",
"== CONTENTS ==",
"== THE KING’S THRESHOLD ==",
"=== PERSONS IN THE PLAY ===",
"== THE KING’S THRESHOLD. ==",
"== ON BAILE’S STRAND ==",
"== PERSONS IN THE PLAY ==",
"== ON BAILE’S STRAND ==",
"== DEIRDRE ==",
"=== PERSONS IN THE PLAY ===",
"== DEIRDRE ==",
"== THE SHADOWY WATERS ==",
"== THE HARP OF AENGUS ==",
"=== PERSONS IN THE PLAY ===",
"== APPENDIX I ACTING VERSION OF THE SHADOWY WATERS ==",
"== APPENDIX II. A different Version of Deirdre’s Entrance. ==",
"== APPENDIX III. The Legendary and Mythological Foundation of the Plays. ==",
"== APPENDIX IV. The Dates and Places of Performance of Plays. ==",
"= THE COUNTESS CATHLEEN. THE LAND OF HEART’S DESIRE. THE UNICORN FROM THE STARS: BEING THE THIRD VOLUME OF THE COLLECTED WORKS IN VERSE AND PROSE OF WILLIAM BUTLER YEATS =",
"== CONTENTS ==",
"== THE COUNTESS CATHLEEN ==",
"=== PERSONS IN THE PLAY ===",
"== THE COUNTESS CATHLEEN. ==",
"=== ACT I. ===",
"=== ACT II. ===",
"== ACT III. ==",
"=== ACT IV. ===",
"== THE LAND OF HEART’S DESIRE ==",
"=== PERSONS IN THE PLAY ===",
"== THE LAND OF HEART’S DESIRE ==",
"== THE UNICORN FROM THE STARS ==",
"=== PERSONS IN THE PLAY ===",
"== THE UNICORN FROM THE STARS ==",
"== ACT I. ==",
"=== ACT II ===",
"=== ACT III ===",
"== APPENDIX. ==",
"=== THE COUNTESS CATHLEEN. ===",
"=== FOOTNOTE: ===",
"== NOTES ==",
"=== FOOTNOTE: ===",
"== THE MUSIC FOR USE IN THE PERFORMANCE OF THESE PLAYS. ==",
"=== THE KING’S THRESHOLD. ===",
"=== ON BAILE’S STRAND. THE FOOL’S SONG. ===",
"=== ON BAILE’S STRAND.&mdash;SONG OF THE WOMEN. ===",
"=== THE FOOL’S SONG. &mdash;II. ===",
"=== DEIRDRE. MUSICIANS’ SONG. &mdash;I. ===",
"==== First Musician. ====",
"==== Second Musician. ====",
"==== The Three Musicians together. ====",
"=== DEIRDRE. MUSICIANS’ SONG. &mdash;II. ===",
"=== DEIRDRE. MUSICIANS’ SONG. &mdash;III. Farr. ===",
"==== First Musician. ====",
"==== Second Musician. ====",
"==== First Musician. ====",
"==== Second Musician. ====",
"==== First Musician. ====",
"==== Second Musician. ====",
"==== First Musician. ====",
"=== DEIRDRE. MUSICIANS’ SONG. &mdash;III. ALLGOOD. ===",
"==== First Musician ====",
"==== Second Musician ====",
"==== First Musician ====",
"==== Second Musician ====",
"==== First Musician. ====",
"==== Second Musician ====",
"==== First Musician ====",
"=== SHADOWY WATERS. ===",
"=== FOOTNOTE: ===",
"=== THE UNICORN FROM THE STARS “The Airy Bachelor.” ===",
"=== THE UNICORN FROM THE STARS “Johnnie Gibbons.” ===",
"==== 1. ====",
"==== 2. ====",
"=== THE UNICORN FROM THE STARS “The Lion shall lose his strength.” ===",
"=== THE HOUR-GLASS. ===",
"=== CATHLEEN NI HOULIHAN. ===",
"==== I. ====",
"==== II. ====",
"==== III. ====",
"== MUSIC FOR LYRICS. ==",
"=== NOTE BY FLORENCE FARR. ===",
"=== THE WIND BLOWS OUT OF THE GATES OF THE DAY. ===",
"=== THE HAPPY TOWNLAND. ===",
"=== FOOTNOTE: ===",
"=== I HAVE DRUNK ALE FROM THE COUNTRY OF THE YOUNG. ===",
"=== THE SONG OF WANDERING AENGUS. ===",
"=== THE HOST OF THE AIR. ===",
"=== FOOTNOTE: ===",
"=== THE SONG OF THE OLD MOTHER. ===",
"= THE HOUR-GLASS. CATHLEEN NI HOULIHAN. THE GOLDEN HELMET. THE IRISH DRAMATIC MOVEMENT :: BEING THE FOURTH VOLUME OF THE COLLECTED WORKS IN VERSE &amp; PROSE OF WILLIAM BUTLER YEATS =",
"== CONTENTS ==",
"== THE HOUR-GLASS: A MORALITY ==",
"=== PERSONS IN THE PLAY ===",
"== CATHLEEN NI HOULIHAN ==",
"=== PERSONS IN THE PLAY ===",
"== THE GOLDEN HELMET ==",
"=== PERSONS IN THE PLAY ===",
"== THE GOLDEN HELMET ==",
"== THE IRISH DRAMATIC MOVEMENT ==",
"== SAMHAIN: 1901 ==",
"=== 1902 ===",
"=== 1903 ===",
"==== THE REFORM OF THE THEATRE. ====",
"==== MORAL AND IMMORAL PLAYS. ====",
"==== AN IRISH NATIONAL THEATRE. ====",
"==== THE THEATRE, THE PULPIT, AND THE NEWSPAPERS. ====",
"=== 1904 THE DRAMATIC MOVEMENT ===",
"==== FIRST PRINCIPLES. ====",
"==== THE PLAY, THE PLAYER, AND THE SCENE. ====",
"=== 1905 ===",
"=== 1906 LITERATURE AND THE LIVING VOICE. ===",
"==== I ====",
"==== II ====",
"==== IV ====",
"==== V ====",
"==== VI ====",
"=== THE ARROW: 1906. ===",
"==== THE SEASON’S WORK. ====",
"==== THE CONTROVERSY OVER THE PLAYBOY OF THE WESTERN WORLD . ====",
"===== From Mr. Yeats’ opening Speech in the Debate on February 4, 1907, at the Abbey Theatre. =====",
"=== 1907 ON TAKING THE PLAYBOY TO LONDON. ===",
"=== FOOTNOTES: ===",
"== APPENDIX I THE HOUR-GLASS. ==",
"=== THE PRIEST’S SOUL. ===",
"== APPENDIX II CATHLEEN NI HOULIHAN. ==",
"== APPENDIX III THE GOLDEN HELMET. ==",
"== APPENDIX IV DATES AND PLACES OF THE FIRST PERFORMANCE OF NEW PLAYS PRODUCED BY THE NATIONAL THEATRE SOCIETY AND ITS PREDECESSORS:&mdash; ==",
"= THE CELTIC TWILIGHT AND STORIES OF RED HANRAHAN BEING THE FIFTH VOLUME OF THE COLLECTED WORKS IN VERSE &amp; PROSE OF WILLIAM BUTLER YEATS :: IMPRINTED AT THE SHAKESPEARE HEAD PRESS STRATFORD-ON-AVON MCMVIII =",
"== THE CELTIC TWILIGHT AND STORIES OF RED HANRAHAN BEING THE FIFTH VOLUME OF THE COLLECTED WORKS IN VERSE &amp; PROSE OF WILLIAM BUTLER YEATS IMPRINTED AT THE SHAKESPEARE HEAD PRESS STRATFORD-ON-AVON MCMVIII ==",
"== CONTENTS ==",
"== THE CELTIC TWILIGHT ==",
"== THE HOSTING OF THE SIDHE ==",
"== THE CELTIC TWILIGHT ==",
"== THIS BOOK ==",
"=== I ===",
"=== II ===",
"== A TELLER OF TALES ==",
"== BELIEF AND UNBELIEF ==",
"== MORTAL HELP ==",
"== A VISIONARY ==",
"=== FOOTNOTE: ===",
"== VILLAGE GHOSTS ==",
"=== FOOTNOTE: ===",
"== ‘DUST HATH CLOSED HELEN’S EYE.’ ==",
"=== I ===",
"=== II ===",
"=== FOOTNOTE: ===",
"== A KNIGHT OF THE SHEEP ==",
"== AN ENDURING HEART ==",
"== THE SORCERERS ==",
"=== FOOTNOTE: ===",
"== THE DEVIL ==",
"== HAPPY AND UNHAPPY THEOLOGIANS ==",
"=== I ===",
"=== II ===",
"=== FOOTNOTE: ===",
"== THE LAST GLEEMAN ==",
"== REGINA, REGINA PIGMEORUM VENI ==",
"=== FOOTNOTE: ===",
"== ‘AND FAIR, FIERCE WOMEN’ ==",
"=== FOOTNOTE: ===",
"== ENCHANTED WOODS ==",
"=== I ===",
"=== II ===",
"== MIRACULOUS CREATURES ==",
"== ARISTOTLE OF THE BOOKS ==",
"== THE SWINE OF THE GODS ==",
"== A VOICE ==",
"== KIDNAPPERS ==",
"=== FOOTNOTE: ===",
"== THE UNTIRING ONES ==",
"=== FOOTNOTE: ===",
"== EARTH, FIRE AND WATER ==",
"== THE OLD TOWN ==",
"== THE MAN AND HIS BOOTS ==",
"== A COWARD ==",
"== THE THREE O’BYRNES AND THE EVIL FAERIES ==",
"== DRUMCLIFF AND ROSSES ==",
"== THE THICK SKULL OF THE FORTUNATE ==",
"=== I ===",
"=== II ===",
"== THE RELIGION OF A SAILOR ==",
"== CONCERNING THE NEARNESS TOGETHER OF HEAVEN, EARTH, AND PURGATORY ==",
"== THE EATERS OF PRECIOUS STONES ==",
"== OUR LADY OF THE HILLS ==",
"== THE GOLDEN AGE ==",
"== A REMONSTRANCE WITH SCOTSMEN FOR HAVING SOURED THE DISPOSITION OF THEIR GHOSTS AND FAERIES ==",
"== WAR ==",
"== THE QUEEN AND THE FOOL ==",
"== THE FRIENDS OF THE PEOPLE OF FAERY ==",
"== DREAMS THAT HAVE NO MORAL ==",
"== BY THE ROADSIDE ==",
"== INTO THE TWILIGHT ==",
"== STORIES OF RED HANRAHAN ==",
"== RED HANRAHAN ==",
"== THE TWISTING OF THE ROPE ==",
"== HANRAHAN AND CATHLEEN THE DAUGHTER OF HOOLIHAN ==",
"== RED HANRAHAN’S CURSE ==",
"== HANRAHAN’S VISION ==",
"== THE DEATH OF HANRAHAN ==",
"= IDEAS OF GOOD AND EVIL BEING THE SIXTH VOLUME OF THE COLLECTED WORKS IN VERSE &amp; PROSE OF WILLIAM BUTLER YEATS :: IMPRINTED AT THE SHAKESPEARE HEAD PRESS STRATFORD-ON-AVON =",
"== CONTENTS ==",
"== WHAT IS ‘POPULAR POETRY’? ==",
"== SPEAKING TO THE PSALTERY. ==",
"=== I ===",
"=== II ===",
"=== III ===",
"== MAGIC. ==",
"=== I ===",
"=== II ===",
"=== III ===",
"=== IV ===",
"=== V ===",
"=== VI ===",
"=== VII ===",
"=== VIII ===",
"== THE HAPPIEST OF THE POETS. ==",
"=== I ===",
"=== II ===",
"=== III ===",
"=== IV ===",
"=== V ===",
"== THE PHILOSOPHY OF SHELLEY’S POETRY ==",
"=== I. HIS RULING IDEAS ===",
"=== II. HIS RULING SYMBOLS ===",
"== AT STRATFORD-ON-AVON ==",
"=== I ===",
"=== II ===",
"=== III ===",
"=== IV ===",
"=== V ===",
"=== VI ===",
"== WILLIAM BLAKE AND THE IMAGINATION. ==",
"== WILLIAM BLAKE AND HIS ILLUSTRATIONS TO THE DIVINE COMEDY . ==",
"=== I. HIS OPINIONS UPON ART. ===",
"=== II. HIS OPINIONS ON DANTE. ===",
"=== III. THE ILLUSTRATIONS OF DANTE. ===",
"== SYMBOLISM IN PAINTING ==",
"== THE SYMBOLISM OF POETRY ==",
"=== I ===",
"=== II ===",
"=== III ===",
"=== IV ===",
"=== V ===",
"== THE THEATRE ==",
"=== I ===",
"=== II ===",
"== THE CELTIC ELEMENT IN LITERATURE ==",
"=== I ===",
"=== II ===",
"=== III ===",
"=== IV ===",
"== THE AUTUMN OF THE BODY ==",
"== THE MOODS ==",
"== THE BODY OF THE FATHER CHRISTIAN ROSENCRUX ==",
"== THE RETURN OF ULYSSES ==",
"=== I ===",
"=== II ===",
"== IRELAND AND THE ARTS ==",
"== THE GALWAY PLAINS ==",
"== EMOTION OF MULTITUDE ==",
"=== FOOTNOTES: ===",
"= THE SECRET ROSE. ROSA ALCHEMICA. THE TABLES OF THE LAW. THE ADORATION OF THE MAGI. JOHN SHERMAN AND DHOYA :: BEING THE SEVENTH VOLUME OF THE COLLECTED WORKS IN VERSE &amp; PROSE OF WILLIAM BUTLER YEATS =",
"== CONTENTS ==",
"== THE SECRET ROSE ==",
"=== TO THE SECRET ROSE ===",
"=== THE CRUCIFIXION OF THE OUTCAST ===",
"=== OUT OF THE ROSE ===",
"=== THE WISDOM OF THE KING ===",
"=== THE HEART OF THE SPRING ===",
"=== THE CURSE OF THE FIRES AND OF THE SHADOWS ===",
"=== THE OLD MEN OF THE TWILIGHT ===",
"=== WHERE THERE IS NOTHING, THERE IS GOD. ===",
"=== OF COSTELLO THE PROUD, OF OONA THE DAUGHTER OF DERMOTT AND OF THE BITTER TONGUE. ===",
"== ROSA ALCHEMICA ==",
"=== I ===",
"=== II ===",
"=== III ===",
"=== IV ===",
"=== V ===",
"== THE TABLES OF THE LAW ==",
"=== I ===",
"=== II ===",
"== THE ADORATION OF THE MAGI ==",
"== JOHN SHERMAN AND DHOYA: TWO EARLY STORIES ==",
"== JOHN SHERMAN ==",
"=== FIRST PART JOHN SHERMAN LEAVES BALLAH ===",
"==== I ====",
"==== II ====",
"==== III ====",
"==== IV ====",
"=== SECOND PART MARGARET LELAND ===",
"==== I ====",
"==== II ====",
"==== III ====",
"==== IV ====",
"==== V ====",
"==== VI ====",
"==== VII ====",
"==== VIII ====",
"==== IX ====",
"=== THIRD PART JOHN SHERMAN REVISITS BALLAH ===",
"==== I ====",
"==== II ====",
"==== III ====",
"=== FOURTH PART THE REV. WILLIAM HOWARD ===",
"==== I ====",
"==== II ====",
"==== III ====",
"==== IV ====",
"==== V ====",
"==== VI ====",
"=== FIFTH PART JOHN SHERMAN RETURNS TO BALLAH ===",
"==== I ====",
"=== II ===",
"==== III ====",
"==== IV ====",
"== DHOYA ==",
"=== I ===",
"=== II ===",
"=== III ===",
"= DISCOVERIES. EDMUND SPENSER. POETRY AND TRADITION; &amp; OTHER ESSAYS BEING THE EIGHTH VOLUME OF THE COLLECTED WORKS IN VERSE &amp; PROSE OF WILLIAM BUTLER YEATS =",
"== CONTENTS ==",
"== DISCOVERIES ==",
"=== PROPHET, PRIEST AND KING ===",
"=== PERSONALITY AND THE INTELLECTUAL ESSENCES ===",
"=== THE MUSICIAN AND THE ORATOR ===",
"=== A GUITAR PLAYER ===",
"=== THE LOOKING-GLASS ===",
"=== THE TREE OF LIFE ===",
"=== THE PRAISE OF OLD WIVES’ TALES ===",
"=== THE PLAY OF MODERN MANNERS ===",
"=== HAS THE DRAMA OF CONTEMPORARY LIFE A ROOT OF ITS OWN? ===",
"=== WHY THE BLIND MAN IN ANCIENT TIMES WAS MADE A POET ===",
"=== CONCERNING SAINTS AND ARTISTS ===",
"=== THE SUBJECT MATTER OF DRAMA ===",
"=== THE TWO KINDS OF ASCETICISM ===",
"=== IN THE SERPENT’S MOUTH ===",
"=== THE BLACK AND THE WHITE ARROWS ===",
"=== HIS MISTRESS’S EYEBROWS ===",
"=== THE TRESSES OF THE HAIR ===",
"=== A TOWER ON THE APENNINE ===",
"=== THE THINKING OF THE BODY ===",
"=== RELIGIOUS BELIEF NECESSARY TO SYMBOLIC ART ===",
"=== THE HOLY PLACES ===",
"== EDMUND SPENSER ==",
"=== I ===",
"=== II ===",
"=== III ===",
"=== IV ===",
"=== V ===",
"=== VI ===",
"=== VII ===",
"=== VIII ===",
"=== IX ===",
"== POETRY AND TRADITION ==",
"=== I ===",
"=== II ===",
"=== III ===",
"=== IV ===",
"== MODERN IRISH POETRY ==",
"== LADY GREGORY’S CUCHULAIN OF MUIRTHEMNE ==",
"=== I ===",
"=== II ===",
"=== III ===",
"=== IV ===",
"=== V ===",
"=== VI ===",
"== LADY GREGORY’S GODS AND FIGHTING MEN ==",
"=== I ===",
"=== II ===",
"=== III ===",
"=== IV ===",
"=== V ===",
"=== VI ===",
"=== VII ===",
"=== VIII ===",
"=== IX ===",
"=== X ===",
"== MR. SYNGE AND HIS PLAYS ==",
"== LIONEL JOHNSON ==",
"== THE PATHWAY ==",
"== A BIBLIOGRAPHY OF THE WRITINGS OF WILLIAM BUTLER YEATS BY ALLAN WADE. ==",
"=== NOTE. ===",
"== PART I.&mdash;ORIGINAL WORKS. ==",
"=== 1886. ===",
"=== 1889. ===",
"==== CONTENTS. ====",
"=== 1891. ===",
"==== CONTENTS. ====",
"=== 1892. ===",
"==== CONTENTS. ====",
"=== 1893. ===",
"==== CONTENTS. ====",
"=== 1894. ===",
"=== 1895. ===",
"==== CONTENTS. ====",
"=== 1897. ===",
"==== CONTENTS. ====",
"==== CONTENTS. ====",
"==== CONTENTS. ====",
"=== 1899. ===",
"==== CONTENTS. ====",
"=== 1900. ===",
"==== CONTENTS. ====",
"=== 1902. ===",
"==== CONTENTS. ====",
"=== 1903. ===",
"==== CONTENTS. ====",
"==== CONTENTS. ====",
"==== CONTENTS. ====",
"=== 1904. ===",
"==== CONTENTS. ====",
"==== CONTENTS. ====",
"==== CONTENTS. ====",
"=== 1906. ===",
"==== CONTENTS. ====",
"=== 1907. ===",
"==== CONTENTS. ====",
"==== CONTENTS. ====",
"=== 1908. ===",
"==== VOLUME I. ====",
"===== CONTENTS. =====",
"==== VOLUME II. ====",
"==== VOLUME III. ====",
"==== VOLUME IV. ====",
"==== VOLUME V. ====",
"==== VOLUME VI. ====",
"==== VOLUME VII. ====",
"==== VOLUME VIII. ====",
"== PART II. BOOKS EDITED OR CONTRIBUTED TO BY W. B. YEATS. ==",
"=== 1888. ===",
"=== 1889. ===",
"=== 1890. ===",
"==== VOLUME I. ====",
"==== VOLUME II. ====",
"=== 1892. ===",
"=== 1893. ===",
"=== 1894. ===",
"=== 1895. ===",
"=== 1898. ===",
"=== 1899. ===",
"== 1899.-1900. ==",
"=== 1900. ===",
"=== 1901. ===",
"=== 1902. ===",
"=== 1903. ===",
"=== 1904. ===",
"=== 1905. ===",
"=== 1906. ===",
"=== 1906-7. ===",
"== PART III. CONTRIBUTIONS TO PERIODICALS. ==",
"=== 1885. ===",
"=== 1886. ===",
"=== 1887. ===",
"=== 1889. ===",
"=== 1890. ===",
"=== 1891. ===",
"=== 1892. ===",
"=== 1893. ===",
"=== 1894. ===",
"=== 1895. ===",
"=== 1896. ===",
"=== 1897. ===",
"=== 1898. ===",
"=== 1899. ===",
"=== 1900. ===",
"=== 1901. ===",
"=== 1902. ===",
"=== 1903. ===",
"=== 1904. ===",
"=== 1905. ===",
"=== 1906. ===",
"=== 1907. ===",
"=== 1908. ===",
"== PART IV. AMERICAN EDITIONS. (COMPILED BY JOHN QUINN.) ==",
"=== [1892.] ===",
"=== 1894. ===",
"=== 1895. ===",
"=== 1897. ===",
"=== 1899. ===",
"=== 1901. ===",
"=== 1902. ===",
"=== 1903. ===",
"=== 1904. ===",
"=== 1906. ===",
"==== CONTENTS. ====",
"=== 1907. ===",
"==== CONTENTS. ====",
"=== 1908. ===",
"==== CONTENTS. ====",
"=== FOOTNOTES: ===",
];
