var menulist=[
"I. A SCANDAL IN BOHEMIA",
"II. THE RED-HEADED LEAGUE",
"III. A CASE OF IDENTITY",
"IV. THE BOSCOMBE VALLEY MYSTERY",
"V. THE FIVE ORANGE PIPS",
"VI. THE MAN WITH THE TWISTED LIP",
"VII. THE ADVENTURE OF THE BLUE CARBUNCLE",
"VIII. THE ADVENTURE OF THE SPECKLED BAND",
"IX. THE ADVENTURE OF THE ENGINEER'S THUMB",
"X. THE ADVENTURE OF THE NOBLE BACHELOR",
"XI. THE ADVENTURE OF THE BERYL CORONET",
"XII. THE ADVENTURE OF THE COPPER BEECHES",
];
