var menulist=[
"= Acclaim for MICHAEL ONDAATJE’S THE ENGLISH PATIENT =",
"= MICHAEL ONDAATJE THE ENGLISH PATIENT =",
"= Also by MICHAEL ONDAATJE =",
"= Contents =",
"= I The Villa =",
"= II In Near Ruins =",
"= III Sometime a Fire =",
"= IV South Cairo 1930&ndash;1938 =",
"= V Katharine =",
"= VI A Buried Plane =",
"= VII In Situ =",
"= VIII The Holy Forest =",
"= IX The Cave of Swimmers =",
"= X August =",
"= Acknowledgements =",
"= BOOKS BY M ICHAEL O NDAATJE =",
"= What’s next on your reading list? =",
];
