var menulist=[
"== Contents ==",
"== Editors’ Note ==",
"== 1 ==",
"== Open Government ==",
"===== October 22nd =====",
"===== October 23rd =====",
"===== October 24th =====",
"===== October 26th =====",
"===== October 27th =====",
"===== October 28th =====",
"===== November 5th =====",
"===== November 6th =====",
"===== November 9th =====",
"== 2 ==",
"== The Official Visit ==",
"===== November 10th =====",
"===== November 11th =====",
"===== November 12th =====",
"===== November 13th =====",
"===== November 18th =====",
"===== November 19th =====",
"===== November 26th =====",
"===== November 27th =====",
"===== Later today: =====",
"== 3 ==",
"== The Economy Drive ==",
"===== December 7th =====",
"===== December 20th =====",
"===== December 21st =====",
"===== December 22nd =====",
"===== December 24th =====",
"== 4 ==",
"== Big Brother ==",
"===== January 4th =====",
"===== January 7th =====",
"===== January 11th =====",
"===== January 12th =====",
"===== January 13th =====",
"===== January 14th =====",
"===== January 15th =====",
"== 5 ==",
"== The Writing on the Wall ==",
"===== January 18th =====",
"===== January 19th =====",
"===== January 20th =====",
"===== February 1st =====",
"===== February 2nd =====",
"===== February 3rd =====",
"===== February 4th =====",
"===== February 5th =====",
"===== February 8th =====",
"== 6 ==",
"== The Right to Know ==",
"===== February 9th =====",
"===== February 10th =====",
"===== February 16th =====",
"===== February 20th =====",
"===== February 21st =====",
"===== February 22nd =====",
"== 7 ==",
"== Jobs for the Boys ==",
"===== March 2nd =====",
"===== March 4th =====",
"===== March 5th =====",
"===== March 7th =====",
"===== March 8th =====",
"===== March 10th =====",
"== 8 ==",
"== The Compassionate Society ==",
"===== March 13th =====",
"===== March 14th =====",
"===== March 15th =====",
"===== March 16th =====",
"===== March 17th =====",
"===== March 22nd =====",
"===== Any Other Business: =====",
"===== March 26th =====",
"== 9 ==",
"== The Death List ==",
"===== March 28th =====",
"===== March 29th =====",
"===== March 30th =====",
"===== March 31st =====",
"===== April 2nd =====",
"===== April 5th =====",
"===== April 11th =====",
"===== April 13th =====",
"== 10 ==",
"== Doing the Honours ==",
"===== April 23rd =====",
"===== April 28th =====",
"===== May 5th =====",
"== 11 ==",
"== The Greasy Pole ==",
"===== June 4th =====",
"===== June 7th =====",
"===== June 8th =====",
"===== Stage one: The public interest =====",
"===== Stage two: Discredit the evidence that you are not publishing =====",
"===== Stage three: Undermine the recommendations =====",
"===== Stage four: If stage three still leaves doubts, then Discredit The Man Who Produced the Report =====",
"===== June 9th =====",
"===== June 10th =====",
"===== June 11th =====",
"===== June 14th =====",
"===== June 15th =====",
"===== June 18th =====",
"===== June 22nd =====",
"===== June 23rd =====",
"== 12 ==",
"== The Devil You Know ==",
"===== July 1st =====",
"===== July 2nd =====",
"===== July 9th =====",
"===== July 12th =====",
"===== July 14th =====",
"===== July 15th =====",
"===== July 22nd =====",
"===== July 23rd =====",
"===== July 26th =====",
"== 13 ==",
"== The Quality of Life ==",
"===== September 14th =====",
"===== September 15th =====",
"===== [Hacker’s diary continues &ndash; Ed.] =====",
"===== September 20th =====",
"===== September 21st =====",
"== 14 ==",
"== A Question of Loyalty ==",
"===== September 27th =====",
"===== October 4th =====",
"===== October 5th =====",
"===== October 6th =====",
"===== October 13th =====",
"===== October 14th =====",
"===== October 15th =====",
"== 15 ==",
"== Equal Opportunities ==",
"===== October 23rd =====",
"===== October 25th =====",
"===== October 27th =====",
"===== November 2nd =====",
"===== November 5th =====",
"== 16 ==",
"== The Challenge ==",
"===== March 10th =====",
"===== March 16th =====",
"===== March 17th =====",
"===== March 23rd =====",
"===== March 29th =====",
"===== March 30th =====",
"===== March 31st =====",
"===== April 5th =====",
"== 17 ==",
"== The Moral Dimension ==",
"===== May 14th =====",
"===== May 17th =====",
"== 18 ==",
"== The Bed of Nails ==",
"===== August 11th =====",
"===== August 12th =====",
"===== August 15th =====",
"===== August 17th =====",
"===== August 19th =====",
"===== August 22nd =====",
"===== August 23rd =====",
"===== August 25th =====",
"== 19 ==",
"== The Whisky Priest ==",
"===== September 4th =====",
"===== September 5th =====",
"===== September 8th =====",
"===== September 10th =====",
"===== September 12th =====",
"===== September 13th =====",
"===== September 14th =====",
"== 20 ==",
"== The Middle-Class Rip-off ==",
"===== September 24th =====",
"===== September 25th =====",
"===== September 29th =====",
"===== October 4th =====",
"===== October 11th =====",
"== 21 ==",
"== The Skeleton in the Cupboard ==",
"===== November 16th =====",
"===== November 17th =====",
"===== November 18th =====",
"===== November 21st =====",
"===== November 22nd =====",
"===== November 23rd =====",
];
