var menulist=[
"== Title Page ==",
"== Copyright Page ==",
"== Introduction ==",
"== A Note from Anthony Puzo, Son of Mario Puzo ==",
"== Dedication ==",
"== BOOK I ==",
"=== Chapter 1 ===",
"=== Chapter 2 ===",
"=== Chapter 3 ===",
"=== Chapter 4 ===",
"=== Chapter 5 ===",
"=== Chapter 6 ===",
"=== Chapter 7 ===",
"=== Chapter 8 ===",
"=== Chapter 9 ===",
"=== Chapter 10 ===",
"=== Chapter 11 ===",
"== BOOK II ==",
"=== Chapter 12 ===",
"=== Chapter 13 ===",
"== BOOK III ==",
"=== Chapter 14 ===",
"== BOOK IV ==",
"=== Chapter 15 ===",
"=== Chapter 16 ===",
"=== Chapter 17 ===",
"=== Chapter 18 ===",
"=== Chapter 19 ===",
"== BOOK V ==",
"=== Chapter 20 ===",
"=== Chapter 21 ===",
"=== Chapter 22 ===",
"== BOOK VI ==",
"=== Chapter 23 ===",
"=== Chapter 24 ===",
"== BOOK VII ==",
"=== Chapter 25 ===",
"=== Chapter 26 ===",
"=== Chapter 27 ===",
"=== Chapter 28 ===",
"== BOOK VIII ==",
"=== Chapter 29 ===",
"=== Chapter 30 ===",
"=== Chapter 31 ===",
"== BOOK IX ==",
"=== Chapter 32 ===",
"== Afterword ==",
"== About the Author ==",
];
