var menulist=[
"== THE STORY BEHIND THE ROBOT NOVELS ==",
"== 1 ==",
"== A QUESTION IS ASKED ==",
"== 2 ==",
"== A FRIEND IS ENCOUNTERED ==",
"== 3 ==",
"== A VICTIM IS NAMED ==",
"== 4 ==",
"== A WOMAN IS VIEWED ==",
"== 5 ==",
"== A CRIME IS DISCUSSED ==",
"== 6 ==",
"== A THEORY IS REFUTED ==",
"== 7 ==",
"== A DOCTOR IS PRODDED ==",
"== 8 ==",
"== A SPACER IS DEFIED ==",
"== 9 ==",
"== A ROBOT IS STYMIED ==",
"== 10 ==",
"== A CULTURE IS TRACED ==",
"== 11 ==",
"== A FARM IS INSPECTED ==",
"== 12 ==",
"== A TARGET IS MISSED ==",
"== 13 ==",
"== A ROBOTICIST IS CONFRONTED ==",
"== 14 ==",
"== A MOTIVE IS REVEALED ==",
"== 15 ==",
"== A PORTRAIT IS COLORED ==",
"== 16 ==",
"== A SOLUTION IS OFFERED ==",
"== 17 ==",
"== A MEETING IS HELD ==",
"== 18 ==",
"== A QUESTION IS ANSWERED ==",
"== ABOUT THE AUTHOR   ==",
];
