var menulist=[
"=== LIST OF MAPS ===",
"=== Introduction ===",
"=== A NOTE ABOUT The Inner Sanctum Edition of WAR AND PEACE ===",
"==== A READER'S GUIDE AND BOOKMARK ====",
"=== FOREWORD ===",
"==== 1 ====",
"==== 2 ====",
"=== TRANSLATOR'S PREFACE ===",
"=== NOTES TO THE OPENING CHAPTERS ===",
"=== BOOK ONE ===",
"==== 1. Anna Schérer's soiree ====",
"==== 2. Pierre at Prince Andrew's ====",
"==== 3. Pierre at Anatole Kurágins. Dólokhov's bet ====",
"==== 4. A name day at the Rostóvs' ====",
"==== 5. Natásha and Borís ====",
"==== 6. Anna Mikháylovna and Borís go to the dying Count Bezúkhov's ====",
"==== 7. Pierre at his father's house; talks with Borís ====",
"==== 8. Countess Rostóva and Anna Mikháylovna ====",
"==== 9. Dinner at the Rostóvs'. Márya Dmítrievna ====",
"==== 10. Sónya and Natásha. Nicholas sings. The Daniel Cooper ====",
"==== 11. At Count Bezúkhov's. Prince Vasíli and Catiche ====",
"==== 12. Anna Mikháylovna and Pierre at Count Bezúkhov's ====",
"==== 13. Anna Mikháylovna and Catiche struggle for the inlaid portfolio ====",
"==== 14. Bald Hills. Prince N. A. Bolkónski. Princess Mary's correspondence with Julie, Karágina ====",
"==== 15. Prince Andrew at Bald Hills ====",
"==== 16. Prince Andrew leaves to join the army. Princess Mary gives him an icon ====",
"=== BOOK TWO ===",
"==== DATES OF PRINCIPAL HISTORICAL EVENTS 1805 ====",
"==== 1. Review near Braunau. Zherkóv and Dólokhov ====",
"==== 2. Kutúzov and an Austrian general. Le malheureux Mack. Zherkóvs foolery ====",
"==== 3. Nicholas and Denísov. Telyánin and the missing purse ====",
"==== 4. Nicholas in trouble with his fellow officers ====",
"==== 5. Crossing the Enns. Burning the bridge. Rostóv's baptism of fire ====",
"==== 6. Prince Andrew sent with dispatches to the Austrian court. The Minister of War ====",
"==== 7. Prince Andrew and Bilíbin ====",
"==== 8. Hippolyte Kurágin and les nôtres ====",
"==== 9. Prince Andrew received by the Emperor Francis. Bilíbin s story of the Thabor Bridge ====",
"==== 10. Prince Andrew returns to Kutúzov. Bagratión sent to Hollabrünn. Napoleon s letter to Murat ====",
"==== 11. Prince Andrew reports to Bagratión. Captain Túshin. Soldiers at the front. Dólokhov talks to a French grenadier ====",
"==== 12. Prince Andrew surveys the position. The first shot ====",
"==== 13. Bagratión in action. Túshin's battery. Setting Schön Grabern on fire ====",
"==== 14. Battle scenes. Quarrelsome commanders. Nicholas injured ====",
"==== 15. Panic. Timókhins counterattack. Dólokhovs insistence. Túshins battery. Prince Andrew sent to order him to retreat ====",
"==== 16. Withdrawal of the forces. Nicholas rides on a gun carriage. Túshin called to account by Bagratión. Prince Andrew defends him. Nicholas' depression ====",
"=== BOOK THREE ===",
"==== DATES OF PRINCIPAL HISTORICAL EVENTS 1805 ====",
"==== 1. Prince Vasíli and Pierre. A soiree at Anna Pávlovnas. Hélène's name day. Pierre's marriage ====",
"==== 2. Prince Vasíli and Anatole visit Prince N. A. Bolkónski. Princess Mary's appearance ====",
"==== 3. Lise, Mademoiselle Bourienne, Mary, Anatole, and old Bolkónski ====",
"==== 4. Her father's opposition to Mary's marrying. She Ends Mademoiselle Bourienne and Anatole in the conservatory; declines marriage ====",
"==== 5. A letter from Nicholas. Sónya and Natásha ====",
"==== 6. Nicholas visits Borís and Berg in camp. Nicholas tells of Schön Grabern. His encounter with Prince Andrew ====",
"==== 7. The Emperor reviews the army. Enthusiasm of Nicholas ====",
"==== 8. Borís visits Prince Andrew at Olmütz. Prince Dolgorúkov ====",
"==== 9. Nicholas not in the action at Wischau. The Emperor. Nicholas' devotion to him ====",
"==== 10. Preparations for action. Dolgorúkov's opinion of Napoleon and of his position. Kutúzov's depression ====",
"==== 11. The Council of War. Weyrother's plans. Kutúzov sleeps. Prince Andrew's reflections ====",
"==== 12. Rostóv at the front Visit of Bagratión and Dolgorúkov. Rostóv sent to reconnoiter. Napoleon's proclamation ====",
"==== 13. Battle of Austerlitz. Prince Andrew badly wounded ====",
"=== BOOK FOUR ===",
"==== 1. Nicholas home on leave ====",
"==== 2. Preparations for Club dinner ====",
"==== 3. The dinner. Bagratión as guest of honor ====",
"==== 4. Pierre challenges Dólokhov ====",
"==== 5. The duel ====",
"==== 6. Pierre's separation from Hélène ====",
"==== 7. Andrew considered dead ====",
"==== 8. Lise's confinement. Andrew arrives ====",
"==== 9. Death of Lise ====",
"==== 10. Denísov and Dólokhov at the Rostóvs' ====",
"==== 11. Sónya. declines Dólokhov's proposal ====",
"==== 12. Iogel's ball. Denísov's mazurka ====",
"==== 13. Nicholas loses 43,000 rubles to Dólokhov ====",
"==== 14. Nicholas at home. Natásha sings ====",
"==== 15. Nicholas tells his father of his losses. Denísov proposes to Natásha ====",
"=== BOOK FIVE ===",
"==== DATES OF PRINCIPAL HISTORICAL EVENTS 1807 ====",
"==== 1. Pierre meets Bazdéev ====",
"==== 2. Pierre becomes a Freemason ====",
"==== 3. Pierre repulses Prince Vasíli ====",
"==== 4. A soiree at Anna Pávlovna's. Hélène takes up Borís ====",
"==== 5. Hippolyte at Anna Pávlovna's ====",
"==== 6. Old Bolkónski as commander in chief of the conscription. Andrew's anxiety. A letter from his father ====",
"==== 7. Bilíbin's letter about the campaign. The baby convalescent ====",
"==== 8. Pierre goes to Kiev and visits his estates. Obstacles to the emancipation of his serfs ====",
"==== 9. Pierre visits Prince Andrew ====",
"==== 10. Pierre's and Prince Andrew's talk on the ferry raft ====",
"==== 11. \"God's folk\" at Bald Hills ====",
"==== 12. Old Bolkónski and Pierre ====",
"==== 13. Nicholas rejoins his regiment. Shortage of provisions ====",
"==== 14. Denísov seizes transports of food, gets into trouble, is wounded ====",
"==== 15. Nicholas visits Denísov in hospital ====",
"==== 16. Borís at Tilsit Nicholas' inopportune visit ====",
"==== 17. Nicholas tries to present Denísov's petition at the Emperor s residence, but fails ====",
"==== 18. Napoleon and Alexander as allies. Perplexity of Nicholas. \"Another bottle ' ====",
"=== BOOK SIX ===",
"==== 2. Speránskiy Arakchéev, and Prince Andrew ====",
"==== 3. Pierre and the Petersburg Freemasons. He visits Joseph Alexéevich. Reconciliation with Hélène ====",
"==== 4. Hélène's social success. Her salon and relations with Borís ====",
"==== 5. Pierre's diary ====",
"==== 6. The Rostóvs in Petersburg. Berg engaged to Véra and demands her dowry ====",
"==== 7. Natásha and Borís ====",
"==== 8. Natásha's bedtime talks with her mother ====",
"==== 9. Natásha's first grand ball. She dances with Prince Andrew ====",
"==== 10. Bítski calls on Prince Andrew. Dinner at Speránski's. Prince Andrew's disillusionment with him and his reforms ====",
"==== 11. Prince Andrew calls on the Rostóvs. Natásha's effect on him ====",
"==== 12. The Bergs' evening party ====",
"==== 13. Natásha consults her mother. Prince Andrew confides in Pierre ====",
"==== 14. Prince N. Bolkónski insists on postponement of his son's marriage. Natásha's distress at Prince Andrew's absence. He returns and they become engaged ====",
"==== 15. Prince Andrew's last days with Natásha ====",
"==== 16. Prince N. Bolkónski's treatment of Mary. Her letter to Julie Karágina ====",
"==== 17. Prince N. Bolkónski threatens to marry Mile Bourienne ====",
"=== BOOK SEVEN ===",
"==== 1. Nicholas Rostóv returns home on leave. His doubts about Natásha's engagement ====",
"==== 2. Nicholas settles accounts with Mítenka ====",
"==== 3. Nicholas decides to go hunting ====",
"==== 4. The wolf hunt begins ====",
"==== 5. The wolf is taken ====",
"==== 6. The fox hunt and the huntsmen's quarrel. Ilágins courtesy. Chasing a hare. Rugáy's triumph ====",
"==== 7. An evening at \"Uncle's\" The balaláyka. Natásha's Russian dance ====",
"==== 8. His mother urges Nicholas to marry Julie Karágina, and grumbles at Sónya ====",
"==== 9. Christmas at Otrádnoe. Natásha is depressed and capricious ====",
"==== 10. Nicholas, Natásha, and Sónya indulge in recollections. Dimmler plays and Natásha sings. The maskers. A troyka drive to the Melyukóvs' ====",
"==== 11. At Melyukóvka. Sónya goes to the barn to try her fortune ====",
"==== 12. The drive home. Natásha and Sónya try the future with looking glasses ====",
"==== 13. His mother opposes Nicholas' wish to marry Sónya, and he returns to his regiment. Natásha becomes restless and impatient for Prince Andrew's return ====",
"=== BOOK EIGHT ===",
"==== 1. Pierre's life in Moscow. Asks himself \"What for? and \"Why?\" ====",
"==== 2. Prince N. Bolkónski in Moscow. His harsh treatment of Princess Mary. She teaches little Nicholas. The old prince and Mile Bourienne ====",
"==== 3. Dr. Métivier treated as a spy by the old prince. The dinner on the prince's name day ====",
"==== 4. Pierre and Princess Mary discuss Borís and Natásha ====",
"==== 5. Borís and Julie. Their melancholy. Borís proposes and is accepted ====",
"==== 6. Count Ilyá Rostóv, Natásha, and Sónya stay with Márya Dmítrievna in Moscow ====",
"==== 7. Count Rostóv and Natásha call on Prince N. Bolkónski. They are received by Princess Mary. Prince Bolkónski's strange behavior. Mary and Natásha dislike one another ====",
"==== 8. The Rostóvs at the Opera. Hélène in the next box ====",
"==== 9. The Opera described. Anatole and Pierre arrive. Natásha makes Hélène's acquaintance. Duport dances ====",
"==== 10. Hélène presents Anatole to Natásha. He courts her ====",
"==== 11. Anatole and Dólokhov in Moscow ====",
"==== 12. Sunday at Márya Dmítrievna's. Hélène calls and invites the Rostóvs to hear Mlle George recite. She tells Natásha that Anatole is in love with her ====",
"==== 13. The reception at Hélène's. Mlle George. Anatole dances with Natásha and makes love to her. Her perplexity as to her own feelings ====",
"==== 14. Princess Mary's letter to Natásha, who also receives one from Anatole ====",
"==== 15. Sónya Ends Anatole's letter and remonstrates with Natásha, who writes to Princess Mary breaking off her engagement with Prince Andrew. A party at the Karágins. Anatole meets Natásha. She is angry with Sónya, who resolves to prevent her elopement ====",
"==== 16. Anatole at Dólokhov's. Balagá ====",
"==== 17. Anatole sets off to abduct Natásha, but encounters Márya Dmítrievna's footman ====",
"==== 18. Márya Dmítrievna reproaches Natásha. Count Ilyá Rostóv is kept in ignorance ====",
"==== 19. Pierre at Márya Dmítrievna's. He tells Natásha that Anatole is married ====",
"==== 20. Pierre's explanation with Anatole ====",
"==== 21. Natásha tries to poison herself. Prince Andrew returns to Moscow and Pierre talks to him ====",
"==== 22. Pierre and Natásha. He tells her of his devotion. The great comet of 1812 ====",
"=== BOOK NINE ===",
"==== DATES OF PRINCIPAL HISTORICAL EVENTS 1812 ====",
"==== 1. The year 1812. Rulers and generals are \"history's slaves\" ====",
"==== 2. Napoleon crosses the Niemen and sees Polish Uhlans drowned swimming the Víliya ====",
"==== 3. Alexander I at Vílna. The ball at Count Bennigsen's. Borís overhears the Emperor speaking to Balashëv and learns that the French have crossed the frontier. Alexander's letter to Napoleon ====",
"==== 4. Balashëv's mission to Napoleon. He meets Murat, \"the King of Naples\" ====",
"==== 5. Balashëv taken to Davout, who treats him badly, but he is at last presented to Napoleon in Vílna ====",
"==== 6. Balashëv's interview with Napoleon ====",
"==== 7. Balashëv dines with Napoleon ====",
"==== 8. Prince Andrew on Kutúzov's staff in Moldavia. He is sent to Barclay's army. Visits Bald Hills. His talks with his father and Princess Mary ====",
"==== 9. Prince Andrew in the army at Drissa. Eight conflicting parties ====",
"==== 10. Prince Andrew is introduced to Pfuel ====",
"==== 11. An informal Council of War. Pfuel's dogmatism ====",
"==== 12. Nicholas writes to Sónya. He and Ilyín in a storm ====",
"==== 13. Mary Hendríkhovna. The officers and the doctor ====",
"==== 14. Courage. Rostóv goes into action at Ostróvna ====",
"==== 15. Rostóv's hussars charge the French dragoons. He wounds and captures a prisoner ====",
"==== 16. Natásha's illness. The use of doctors ====",
"==== 17. Natásha and Pierre. She prepares for communion with Belóva. The church service. Her health improves ====",
"==== 18. Natásha attends Mass and hears the special prayer for victory ====",
"==== 19. Pierre's relation to life altered by his feeling for Natásha. 666. Napoleon as Antichrist. Pierre's belief that he is destined to end Napoleon's power. He gets news for the Rostóvs ====",
"==== 20. Pierre at the Rostóvs'. Natásha again takes up her singing. Sónya reads Alexander's manifesto. Pétya declares that he will enter the army. Natásha realizes that Pierre loves her. He decides to cease going to the Rostóvs' ====",
"==== 21. Pétya goes to the Krémlin to see the Emperor. He gets crushed. He secures a biscuit thrown by the Emperor after dinner ====",
"==== 22. Assembly of gentry and merchants at the Slobóda Palace. A limited discussion. Pierre's part in it ====",
"==== 23. Count Rostopchín's remarks. The offer made by the Moscow nobility and gentry. The Emperor's speech. Pierre offers to supply and maintain a thousand men ====",
"=== BOOK TEN ===",
"==== DATES OF PRINCIPAL HISTORICAL EVENTS 1812 ====",
"==== 1. Reflections on the campaign of 1812. The course of events was fortuitous and unforeseen by either side ====",
"==== 2. Prince N. Bolkónski and his daughter. His break with Mile Bourienne. Mary's correspondence with Julie. The old prince receives a letter from Prince Andrew but does not grasp its meaning and confuses the present invasion with the Polish campaign of 1807 ====",
"==== 3. The old prince sends Alpátych to Smolénsk with various commissions, and does not know where to have his bed placed. He remembers Prince Andrew's letter and reads and understands it ====",
"==== 4. Princess Mary sends a letter to the Governor at Smolénsk. Alpátych sets off on August 4; reaches Smolénsk that evening and stays at Ferapóntovs inn. Firing heard outside the town. Next day he does his business, but finds alarm spreading, and is advised by the Governor that the Bolkónskis had better go to Moscow. The town bombarded. Ferapóntovs cook has her thigh broken by a shell. Retreating soldiers loot Ferapóntovs shop and he declares he will set his place on Ere himself and not leave it to the French. Alpátych meets Prince Andrew, who has an encounter with Berg ====",
"==== 5. Prince Andrew passing Bald Hills with his regiment. The retreat: heat and terrible dust. He rides over to the house. The little girls and the plums. The soldiers bathe in a pond. \"Cannon fodder\" Bagratións letter to Arakchéev ====",
"==== 6. Matter and form. Anna Pávlovna's and Hélène's rival salons. Prince Vasílis opinion of Kutúzov ====",
"==== 7. Napoleon orders an advance on Moscow. Napoleon's conversation with Lavrúshka ====",
"==== 8. Prince Nicholas Bolkónski has a paralytic stroke and is taken to Boguchárovo. Princess Mary decides that they must move on to Moscow. Her last interview with her father. His affection for her. His death ====",
"==== 9. Character of the Boguchárovo peasantry and the baffling undercurrents in the life of the Russian people. The village Elder, Dron. Alpátych talks to him. The peasants decide not to supply horses or carts ====",
"==== 10. Mile Bourienn advises Princess Mary to appeal to the French for protection. Princess Mary speaks to Dron ====",
"==== 11. Princess Mary addresses the peasants. They distrust her and refuse to leave Boguchárovo ====",
"==== 12. Princess Mary at night recalls her last sight of her father ====",
"==== 13. Nicholas and Ilyín ride to Boguchárovo. They are asked by Alpátych to protect the princess. Nicholas makes her acquaintance and places himself at her service ====",
"==== 14. Nicholas calls the peasants to account and intimidates them. Carts and horses are provided for Princess Marys departure. Princess Mary feels that she loves him ====",
"==== 15. Prince Andrew goes to headquarters and meets Denísov, who wants guerrilla troops to break the French line of communication. Kutúzov's reception of them. He transacts business ====",
"==== 16. The priest's wife offers Kutúzov \"bread and salt\" He has a further talk with Prince Andrew, who declines a place on the staff. Patience and Time. Prince Andrew's confidence in Kutúzov ====",
"==== 17. Moscow after the Emperor's visit. Rostopchín's broadsheets. Julie's farewell soiree. Forfeits for speaking French. Pierre hears of Princess Mary's arrival in Moscow ====",
"==== 18. Rostopchíns broadsheets. Pierre and the eldest princess. Leppich's balloon. A public flogging. Pierre leaves Moscow for the army ====",
"==== 19. Senselessness of the battle of Borodinó, and erroneousness of the historians' accounts of it Where and how it was fought ====",
"==== 20. Pierre encounters cavalry advancing and carts of wounded retiring. He talks to an army doctor. Pierre looks for the \"position\" occupied by the army. Peasant militia digging entrenchments ====",
"==== 21. Pierre ascends a knoll at Górki, surveys the scene, and inquires as to the \"position\" occupied. A procession carrying the \"Smolénsk Mother of God\" The reverence of the crowd and of Kutúzov ====",
"==== 22. Borís meets Pierre. Dólokhov makes his way to Kutúzov. Kutúzov notices Pierre. Dólokhov asks Pierre to be reconciled ====",
"==== 23. Pierre rides to the left flank with Bennigsen, who explains the \"position\" in a way Pierre does not understand and changes one of Kutúzovs dispositions ====",
"==== 24. Prince Andrew's reflections on life and death. Pierre comes to see him ====",
"==== 25. Timókhin s opinion of Kutúzov. Prince Andrew on Barclay de Tolly. War and chess. The spirit of the army. Woizogen and Clausewitz. \"The war must be extended widely\" Pierre understands the importance of this war. \"Not take prisoners\" What is war? Prince Andrew thinks of Natásha ====",
"==== 26. De Beausset brings a portrait of the \"King of Rome\" to Napoleon. Napoleon's proclamation ====",
"==== 27. Napoleon's dispositions for the battle of Borodinó. They were not carried out ====",
"==== 28. Napoleon's cold. Why the battle had to be fought ====",
"==== 29. Napoleon's talk to de Beausset and Rapp. The game begins ====",
"==== 30. Pierre views the battlefield from the knoll at Górki ====",
"==== 31. Pierre at the Borodinó bridge. Under firee. Goes to Raévski's Redoubt. His horse wounded under him. The Raévski Redoubt. The young officer. Pierre is accepted at the redoubt as one of the family. The flame of hidden fire in the men's souls. Shortage of ammunition. Pierre sees ammunition wagons blown up ====",
"==== 32. The redoubt captured by the French. Pierre's conflict with a French officer. The redoubt retaken by the Russians ====",
"==== 33. The course of the battle. Difficulty of discerning what was going on. Things take their own course apart from the orders issued ====",
"==== 34. Reinforcements. Belliard appeals to Napoleon. De Beausset proposes breakfast. Friant's division sent in support. The expected success not secured. Continuous and useless slaughter ====",
"==== 35. Kutúzov. His rebuke to WoJzogen. An order of the day for an attack tomorrow. The spirit of the army ====",
"==== 36. Prince Andrew with the reserve under Ere. Hit by a bursting shell. Outside the dressing station ====",
"==== 37. The operating tent. Portion of Prince Andrew's thighbone extracted. Anatole's leg amputated. Prince Andrew pities him ====",
"==== 38. Napoleon is depressed. His mind and conscience darkened. His calculation that few Frenchmen perished in Russia ====",
"==== 39. Appearance of the field at the end of the battle. Doubts maturing in every soul. Only a little further effort needed to secure victory, but such effort impossible. Could Napoleon have used his Old Guard? The Russians had gained a moral victory ====",
"=== BOOK ELEVEN ===",
"==== DATE OF PRINCIPAL HISTORICAL EVENT 1812 ====",
"==== 1. Continuity of motion. Achilles and the tortoise. The method of history; its explanation of events compared with explanations of the movement of a locomotive ====",
"==== 2. Summary of campaign before Borodinó and explanation of Kutúzov's subsequent movements ====",
"==== 3. Kutúzov and his generals at the Poklónny Hill. Council of War at Filí ====",
"==== 4.The author's reflections on the abandonment of Moscow. Rostopchín's conduct and that of private individuals ====",
"==== 5.Hélène in Petersburg. Conversion to Catholicism and plans for remarriage ====",
"==== 6. Pierre walks to Mozháysk. His night lodging there. His dream, and his return to Moscow ====",
"==== 7. Pierre at Rostopchíns. The affair of Klyucharëv and Vereshchágin. Pierre leaves home secretly ====",
"==== 8. The Rostóvs: packing up and leaving Moscow. They allow wounded officers to stay in their house and avail themselves of their carts to leave Moscow. Berg's wish to borrow a cart. Natásha when leaving Moscow sees and speaks to Pierre. Prince Andrew travels in their train of vehicles ====",
"==== 9. Pierre at Bazdéev's house. He wears a coachman's coat ====",
"==== 10. Napoleon surveys Moscow from the Poklónny Hill. He awaits a deputation of les boyars ====",
"==== 11. Moscow compared to a queenless hive. The army's departure. Looting by Russian soldiers. The Moskvá bridge blocked, and cleared by Ermólov. A brawl among workmen. Reading a Rostopchín broadsheet to a crowd. Scene with the superintendent of police ====",
"==== 12. Rostopchín. The killing of Vereshchágin. The released lunatics. Rostopchín s encounter with Kutúzov at the bridge ====",
"==== 13. The French enter Moscow. Shots from the Krémlin gate. The Fire of Moscow discussed ====",
"==== 14. Pierre: his plan to kill Napoleon. Bazdéev's drunken brother fires at Captain Ramballe, who regards Pierre as a friend ====",
"==== 15. The Rostóvs at Mytíshchi. Natásha sees Prince Andrew ====",
"==== 16. Pierre sets out to meet Napoleon. He saves a child, defends an Armenian girl from a French soldier, and is arrested as an incendiary ====",
"=== BOOK TWELVE ===",
"==== 1. Anna Pávlovna's soiree. Talk of Hélène's illness. The Bishop's letter. Victory at Borodinó reported. Death of Hélène. News of abandonment of Moscow. Michaud's report ====",
"==== 2. Nicholas sent to Vorónezh. An evening at the Governor's. Nicholas and Princess Mary. A letter from Sónya ====",
"==== 3. Pierre's treatment as a prisoner. He is questioned by Davout. Shooting of prisoners. Platón Karatáev ====",
"==== 4. Princess Mary goes to the Rostóvs' in Yaroslávl. Prince Andrew's last days and death ====",
"=== BOOK THIRTEEN ===",
"==== DATES OF PRINCIPAL HISTORICAL EVENTS 1812 ====",
"==== 1. The cause of historical events. A survey of movements of the Russian army after leaving Moscow. Napoleon's letter to Kutúzov. The camp at Tarutino. Alexander's letters to Kutuzov. Ermólov and others absent when wanted. The battle postponed. Kutúzov's wrath. The action next day. Cossacks surprise Murat's army and capture prisoners, guns, and booty. Inactivity of the rest of the army ====",
"==== 2. Napoleon's measures. Proclamation in Moscow. Effects of pillage on French discipline ====",
"==== 3. Pierre: four weeks in captivity. Karatâev and a French soldier. The French leave Moscow. The drum. Pierre's mental change; he recovers his grip on life. Exit of troops and prisoners. The road blocked. Pierre's reflections ====",
"==== 4. The Russian army. Dokhtúrov. News of the French having left Moscow reaches Kutúzov at night. His emotion. Cossacks nearly capture Napoleon at Malo-Yaroslavets. He retreats by the Smolénsk road. A third of his army melts away before reaching Vyázma ====",
"=== BOOK FOURTEEN ===",
"==== DATE OF PRINCIPAL HISTORICAL EVENT 1812 ====",
"==== 1. National character of the war. A duelist who drops his rapier and seizes a cudgel. Guerrilla warfare. The spirit of the army ====",
"==== 2. The partisans or guerrillas. Denísov, Dólokhov, Pétya Rostóv, and Tíkhon. A French drummer boy. A visit to the enemy's camp. Attack on a French convoy. The death of Pétya ====",
"==== 3. Pierre's journey among the prisoners. Karatëev. His story of the merchant. His death. Pierre rescued ====",
"==== 4. The French retreat. Berthier's report to Napoleon. Their flight beyond Smolénsk ====",
"=== BOOK FIFTEEN ===",
"==== DATES OF PRINCIPAL HISTORICAL EVENTS 1812 ====",
"==== 1. The Rostóvs. Natásha's grief. The news of Pétyas death. Natásha leaves with Princess Mary for Moscow ====",
"==== 2. Analysis of Kutúzov's movements ====",
"==== 3. Kutúzov at Krásnoe; his speech to the army. Encampment for the night: soldier scenes. Ramballes appearance with his orderly. The song of Henri Quatre ====",
"==== 4. The crossing of the Berëzina. Vílna. The Emperor Alexander. Kutúzov; his failing health ====",
"==== 5. Pierre. Illness and recovery at Orël. His new attitude to life and his fellow men. His affairs. He goes to Moscow; the town's animation and rapid recovery. Pierre meets Natásha at Princess Mary's. Love ====",
"=== FIRST EPILOGUE ===",
"==== 1. Discussion of forces operating in history. Chance and genius. The ideals of glory and grandeur. Alexander's renunciation of power. The purpose of a bee ====",
"==== 2. Death of old Count Rostóv. Nicholas in retirement. His mother. His meeting with Princess Mary. Their wedding; estate management in the country; their family life. Sónya a sterile flower. Denísov. Nichola's name day ====",
"==== 3. Natásha's and Pierre's family life. His return after a visit to Petersburg. The old countess in decay. Conversation about social tendencies, and indignation at reactionary trend of the government. Views of Pierre and Nicholas ====",
"==== 4. The two married couples and their mutual relations. Natásha's jealousy. Young Nicholas Bol kónski's aspirations ====",
"=== SECOND EPILOGUE ===",
"==== A general discussion on the historians' study of human life, and on the difficulty of defining the forces that move nations. The problem of free will and necessity ====",
"=== SOME WORDS ABOUT WAR AND PEACE ===",
"==== CHARACTERS IN WAR AND PEACE ====",
"==== THE PRINCIPAL CHARACTERS ARRANGED IN FAMILY GROUPS ====",
"==== DATES OF PRINCIPAL HISTORICAL EVENTS ====",
"=== A Note on the Design and Production of This Book ===",
];
