var menulist=[
"= 引言 =",
"= 文本注释 =",
"= 鸣谢 =",
"= 英国2012版注释 =",
"= 序章 =",
"== 维也纳 ==",
"= A =",
"== 安娜·阿赫玛托娃 ==",
"== Anna Akhmatova ==",
"== 皮特·阿尔滕伯格 ==",
"== Peter Altenberg ==",
"== 路易·阿姆斯特朗 ==",
"== Louis Armstrong ==",
"== 雷蒙·阿隆 ==",
"== Raymond Aron ==",
"= B =",
"== 瓦尔特·本雅明 ==",
"== Walter Benjamin ==",
"== 马克·布洛赫 ==",
"== Marc Bloch ==",
"== 豪尔赫·路易斯·博尔赫斯 ==",
"== Jorge Luis Borges ==",
"== 罗伯特·布拉西亚克 ==",
"== Robert Brasillach ==",
"== 托马斯·布朗爵士 ==",
"== Sir Thomas Browne ==",
"= C =",
"== 阿尔贝·加缪 ==",
"== Albert Camus ==",
"== 迪克·卡维特 ==",
"== Dick Cavett ==",
"== 保罗·策兰 ==",
"== Paul Celan ==",
"== 尚福 ==",
"== Chamfort ==",
"== 可可·香奈儿 ==",
"== Coco Chanel ==",
"== 查尔斯·卓别林 ==",
"== Charles Chaplin ==",
"== 尼拉德·C.乔杜里 ==",
"== Nirad C. Chaudhuri ==",
"== G. K.切斯特顿 ==",
"== G. K. Chesterton ==",
"== 让·科克托 ==",
"== Jean Cocteau ==",
"== 詹弗兰科·孔蒂尼 ==",
"== Gianfranco Contini ==",
"== 贝内代托·克罗齐 ==",
"== Benedetto Croce ==",
"== 托尼·柯蒂斯 ==",
"== Tony Curtis ==",
"== 恩斯特·罗伯特·库尔提乌斯 ==",
"== Ernst Robert Curtius ==",
"= D =",
"== 迈尔斯·戴维斯 ==",
"== Miles Davis ==",
"== 谢尔盖·佳吉列夫 ==",
"== Sergei Diaghilev ==",
"== 皮埃尔·德里厄·拉罗谢尔 ==",
"== Pierre Drieu La Rochelle ==",
"= E =",
"== 阿尔弗雷德·爱因斯坦 ==",
"== Alfred Einstein ==",
"== 艾灵顿公爵 ==",
"== Duke Ellington ==",
"= F =",
"== 费德里科·费里尼 ==",
"== Federico Fellini ==",
"== W. C.菲尔茨 ==",
"== W. C.Fields ==",
"== F. 司各特·菲茨杰拉德 ==",
"== F. Scott Fitzgerald ==",
"== 古斯塔夫·福楼拜 ==",
"== Gustave Flaubert ==",
"== 西格蒙德·弗洛伊德 ==",
"== Sigmund Freud ==",
"== 埃贡·弗里德尔 ==",
"== Egon Friedell ==",
"= G =",
"== 夏尔·戴高乐 ==",
"== Charles de Gaulle ==",
"== 爱德华·吉本 ==",
"== Edward Gibbon ==",
"== 特里·吉列姆 ==",
"== Terry Gilliam ==",
"== 约瑟夫·戈培尔 ==",
"== Joseph Goebbels ==",
"== 维托尔德·贡布罗维奇 ==",
"== Witold Gombrowicz ==",
"= H =",
"== 威廉·黑兹利特 ==",
"== William Hazlitt ==",
"== 黑格尔 ==",
"== Hegel ==",
"== 海因里希·海涅 ==",
"== Heinrich Heine ==",
"== 阿道夫·希特勒 ==",
"== Adolf Hitler ==",
"== 丽卡达·胡赫 ==",
"== Ricarda Huch ==",
"= J =",
"== 恩斯特·荣格 ==",
"== Ernst Jünger ==",
"= K =",
"== 弗兰兹·卡夫卡 ==",
"== Franz Kafka ==",
"== 约翰·济慈 ==",
"== John Keats ==",
"== 海达·马尔戈柳斯·科瓦利 ==",
"== Heda Margolius Kovaly ==",
"== 卡尔·克劳斯 ==",
"== Karl Kraus ==",
"= L =",
"== 格奥尔格·克里斯托夫·利希滕贝格 ==",
"== Georg Christoph Lichtenberg ==",
"= M =",
"== 诺曼·梅勒 ==",
"== Norman Mailer ==",
"== 娜杰日达·曼德尔施塔姆 ==",
"== Nadezhda Mandelstam ==",
"== 戈洛·曼 ==",
"== Golo Mann ==",
"== 海因里希·曼 ==",
"== Heinrich Mann ==",
"== 迈克尔·曼 ==",
"== Michael Mann ==",
"== 托马斯·曼 ==",
"== Thomas Mann ==",
"== 津卡·米拉诺夫 ==",
"== Zinka Milanov ==",
"== 切斯瓦夫·米沃什 ==",
"== Czeslaw Milosz ==",
"== 埃乌杰尼奥·蒙塔莱 ==",
"== Eugenio Montale ==",
"== 孟德斯鸠 ==",
"== Montesquieu ==",
"== 艾伦·穆尔黑德 ==",
"== Alan Moorehead ==",
"== 保罗·穆拉托夫 ==",
"== Paul Muratov ==",
"= N =",
"== 刘易斯·内米尔 ==",
"== Lewis Namier ==",
"= P =",
"== 奥克塔维奥·帕斯 ==",
"== Octavio Paz ==",
"== 阿尔弗雷德·波尔加 ==",
"== Alfred Polgar ==",
"== 比阿特丽克斯·波特 ==",
"== Beatrix Potter ==",
"== 让·普雷沃 ==",
"== Jean Prévost ==",
"== 马塞尔·普鲁斯特 ==",
"== Marcel Proust ==",
"= Q =",
"== 埃德加·基内 ==",
"== Edgar Quinet ==",
"= R =",
"== 马塞尔·赖希&mdash;拉尼奇 ==",
"== Marcel Reich-Ranicki ==",
"== 理查德·罗兹 ==",
"== Richard Rhodes ==",
"== 莱纳·马利亚·里尔克 ==",
"== Rainer Maria Rilke ==",
"= S =",
"== 埃内斯托·萨瓦托 ==",
"== Ernesto Sábato ==",
"== 爱德华·萨义德 ==",
"== Edward Said ==",
"== 圣伯夫 ==",
"== Sainte-Beuve ==",
"== 让&mdash;保罗·萨特 ==",
"== Jean-Paul Sartre ==",
"== 埃里克·萨蒂 ==",
"== Erik Satie ==",
"== 阿图尔·施尼茨勒 ==",
"== Arthur Schnitzler ==",
"== 苏菲·绍尔 ==",
"== Sophie Scholl ==",
"== 沃尔夫·约布斯特·西德勒 ==",
"== Wolf Jobst Siedler ==",
"= T =",
"== 塔西佗 ==",
"== Tacitus ==",
"== 玛格丽特·撒切尔 ==",
"== Margaret Thatcher ==",
"== 亨宁·冯·特雷斯科 ==",
"== Henning von Tresckow ==",
"== 卡尔·楚皮克 ==",
"== Karl Tschuppik ==",
"= U =",
"== 杜布拉芙卡·乌格雷希奇 ==",
"== Dubravka Ugresic ==",
"== 米格尔·德·乌纳穆诺 ==",
"== Miguel de Unamuno ==",
"== 佩德罗·恩里克斯·乌雷尼亚 ==",
"== Pedro Henríquez Ureña ==",
"= V =",
"== 保罗·瓦莱里 ==",
"== Paul Valéry ==",
"== 马里奥·巴尔加斯&mdash;略萨 ==",
"== Mario Vargas Llosa ==",
"= W =",
"== 伊夫林·沃 ==",
"== Evelyn Waugh ==",
"== 路德维希·维特根斯坦 ==",
"== Ludwig Wittgenstein ==",
"= Y =",
"== 山本五十六 ==",
"== Isoroku Yamamoto ==",
"= Z =",
"== 卡尔·楚克迈尔 ==",
"== Carl Zuckmayer ==",
"== 斯蒂芬·茨威格 ==",
"== Stefan Zweig ==",
"= 尾声 =",
"== Coda: Kun-Han-Su ==",
"= 增补 =",
"== 增补简介 ==",
"== 从垃圾读物开始 ==",
"== 跟踪妮可·基德曼的诗人 ==",
"== 达蒙最勇敢的日子 ==",
];
