var menulist=[
"== Chapter One ==",
"=== ANNA ===",
"== Chapter Two ==",
"=== THE PEGGS ===",
"== Chapter Three ==",
"=== ON THE STAITHE ===",
"== Chapter Four ==",
"=== THE OLD HOUSE ===",
"== Chapter Five ==",
"=== ANNA FOLLOWS HER FANCY ===",
"== Chapter Six ==",
"=== “A STIFF, PLAIN THING&mdash;” ===",
"== Chapter Seven ==",
"=== “&mdash;AND A FAT PIG” ===",
"== Chapter Eight ==",
"=== MRS PEGG’S BINGO NIGHT ===",
"== Chapter Nine ==",
"=== A GIRL AND A BOAT ===",
"== Chapter Ten ==",
"=== PICKLED SAMPHIRE ===",
"== Chapter Eleven ==",
"=== THREE QUESTIONS EACH ===",
"== Chapter Twelve ==",
"=== MRS PEGG BREAKS HER TEAPOT ===",
"== Chapter Thirteen ==",
"=== THE BEGGAR GIRL ===",
"== Chapter Fourteen ==",
"=== AFTER THE PARTY ===",
"== Chapter Fifteen ==",
"=== “LOOK OUT FOR ME AGAIN!” ===",
"== Chapter Sixteen ==",
"=== MUSHROOMS AND SECRETS ===",
"== Chapter Seventeen ==",
"=== THE LUCKIEST GIRL IN THE WORLD ===",
"== Chapter Eighteen ==",
"=== AFTER EDWARD CAME ===",
"== Chapter Nineteen ==",
"=== THE WINDMILL ===",
"== Chapter Twenty ==",
"=== FRIENDS NO MORE ===",
"== Chapter Twenty-One ==",
"=== MARNIE IN THE WINDOW ===",
"== Chapter Twenty-Two ==",
"=== THE OTHER SIDE OF THE HOUSE ===",
"== Chapter Twenty-Three ==",
"=== THE CHASE ===",
"== Chapter Twenty-Four ==",
"=== CAUGHT! ===",
"== Chapter Twenty-Five ==",
"=== THE LINDSAYS ===",
"== Chapter Twenty-Six ==",
"=== SCILLA’S SECRET ===",
"== Chapter Twenty-Seven ==",
"=== HOW SCILLA KNEW ===",
"== Chapter Twenty-Eight ==",
"=== THE BOOK ===",
"== Chapter Twenty-Nine ==",
"=== TALKING ABOUT BOATS ===",
"== Chapter Thirty ==",
"=== A LETTER FROM MRS PRESTON ===",
"== Chapter Thirty-One ==",
"=== MRS PRESTON GOES OUT TO TEA ===",
"== Chapter Thirty-Two ==",
"=== A CONFESSION ===",
"== Chapter Thirty-Three ==",
"=== MISS PENELOPE GILL ===",
"== Chapter Thirty-Four ==",
"=== GILLIE TELLS A STORY ===",
"== Chapter Thirty-Five ==",
"=== WHOSE FAULT WAS IT? ===",
"== Chapter Thirty-Six ==",
"=== THE END OF THE STORY ===",
"== Chapter Thirty-Seven ==",
"=== GOODBYE TO WUNTERMENNY ===",
"== Postscript ==",
"== If you enjoyed When Marnie Was There, check out these other great HarperCollins titles. ==",
"== About the Author ==",
"== About the Publisher ==",
];
