var menulist=[
"== 出版说明 ==",
"== 校订版序 ==",
"== 编辑大意 ==",
"== The Bear 熊 ==",
"=== William Faulkner(1897&mdash;1962) ===",
"== The Whistle 寒笛 ==",
"=== Eudora Welty (1909&mdash;2001) ===",
"== The Life And Work Of Professor Roy Millen 米伦教授的生活与工作 ==",
"=== Robert Penn Warren (1905&mdash;1989) ===",
"== The Ballet Dancer 芭蕾舞家 ==",
"=== Jane Mayhall (1918&mdash;2009) ===",
"== Herb Gathering 采药 ==",
"=== Truman Capote (1924&mdash;1984) ===",
"== Two Mutes 两哑巴 ==",
"=== Carson McCullers (1917&mdash;1967) ===",
"== The Last Puritan 最后一个清教徒 ==",
"=== George Santayana (1863&mdash;1952) ===",
"== The Great Fire of 1945 一九四五年大火记 ==",
"=== Margaret Shedd (1900&mdash;1986) ===",
"== The Jersey Heifer 杰西牛 ==",
"=== Peggy Harding Love (1920&mdash; ) ===",
"== A Visit to the Grandfather's Grave 扫墓 ==",
"=== James Turner Jackson ===",
"== Natives Don't Cry 亨利小姐的信 ==",
"=== Kay Boyle (1902&mdash;1992) ===",
"== Rosie 露西姑娘 ==",
"=== William Van Buskirk (1922&mdash;？) ===",
"== At Gallipoli 大军出征 ==",
"=== John Masefield (1878&mdash;1967) ===",
"== The Treasure Game 觅宝 ==",
"=== H. E. Bates (1905&mdash;1974) ===",
"== The Duck 鸭 ==",
"=== J. B. Priestley (1894&mdash;1984) ===",
"== A Special Occasion 两小 ==",
"=== Joyce Cary (1888&mdash;1957) ===",
"== Bookshops in Paris 巴黎的书店 ==",
"=== Aldous Huxley (1894&mdash;1963) ===",
"== A World of Glass 玻璃世界 ==",
"=== William Sansom (1912&mdash;1976) ===",
"== A Hemingway Sample 海明威的写作技巧 ==",
"=== Caroline Gordon (1895&mdash;1981) ===",
"== Kant the Man 康德的日常生活 ==",
"=== W. Somerset Maugham (1874&mdash;1965) ===",
"== In Dreams Begin Responsibilities 君子好逑 ==",
"=== Delmore Schwartz (1913&mdash;1966) ===",
"== A Mountain Adventure 登山遇险记 ==",
"=== Gerald Warner Brace (1901&mdash;1978) ===",
"== Father and Daughter 父与女 ==",
"=== James Yaffe (1927&mdash;？) ===",
"== Merry Christmas 圣诞快乐 ==",
"=== William Saroyan (1908&mdash;1981) ===",
"== D-Day 诺曼第登陆 ==",
"=== Winston S. Churchill (1874&mdash;1965) ===",
"== A Student in Economics 工读生 ==",
"=== George Milburn (1906&mdash;1966) ===",
"== Prescott 历史家普瑞斯各德 ==",
"=== Van Wyck Brooks (1886&mdash;1963) ===",
"== Man and Woman 男与女 ==",
"=== Erskine Caldwell (1903&mdash;1987) ===",
"== A Pretty Girl 美丽的姑娘 ==",
"=== Max Beerbohm (1872&mdash;1956) ===",
"== Her Graduation Day 毕业的那一天 ==",
"=== Nancy G. Chaikin ===",
"== Emergency Landing 紧急着陆 ==",
"=== John Cheever (1912&mdash;1982) ===",
"== Romeo 大情人 ==",
"=== Charles Jackson (1903&mdash;1968) ===",
"== Dialogues of A. N. Whitehead 怀德海语录 ==",
"=== Lucien Price (1883&mdash;1964) ===",
"== Michael and Mary 金船 ==",
"=== Seumas O'Kelly (1881&mdash;1918) ===",
"== University Days 大学生活回忆 ==",
"=== James G. Thurber (1894&mdash;1961) ===",
"== British Bicycles in Spain 英国自行车在西班牙 ==",
"=== Robert Graves (1895&mdash;1985) ===",
"== The Reigning Royalty of Europe 欧洲之王室 ==",
"=== Lord David Cecil (1902&mdash;1986) ===",
"== A Professor in Retirement 退休教授 ==",
"=== Jean Stafford (1915&mdash;1979) ===",
"== A Writer's Life 作家甘苦 ==",
"=== Catherine Drinker Bowen (1897&mdash;1973) ===",
"== We Need Humor 我们需要幽默 ==",
"=== Malcolm Muggeridge (1903&mdash;1990) ===",
"== Skeffington's Decision to Run for Re-election 市长决心竞选 ==",
"=== Edwin O'Connor (1918&mdash;1968) ===",
"== Moon Shell 月形螺壳 ==",
"=== Anne Morrow Lindbergh (1906&mdash;2001) ===",
"== Invite 邀舞 ==",
"=== John O'Hara (1905&mdash;1970) ===",
"== Captain Carlsen 卡尔逊船长 ==",
"=== Thomas Whiteside (1918&mdash;1997) ===",
"== Moscow, 1918 一九一八年的莫斯科 ==",
"=== George F. Kennan (1904&mdash;2005) ===",
];
