var menulist=[
"= Contents =",
"= LESSON 1 MY CAT =",
"=== 1. ===",
"=== 2. ===",
"=== 3. ===",
"=== 4. ===",
"= LESSON 2 THE HOOP =",
"= LESSON 3 KNIFE AND FORK =",
"= LESSON 4 THE BIRD'S NEST =",
"= LESSON 5 LITTLE ROBIN REDBREAST =",
"=== 1. ===",
"=== 2. ===",
"=== 3. ===",
"=== 4. ===",
"= LESSON 6 NURSERY RHYMES =",
"=== 1. ===",
"=== 2. ===",
"=== 3. ===",
"= LESSON 7 SAILING THE BOAT =",
"= LESSON 8 LONG TIME AGO =",
"= LESSON 9 THE LITTLE MILK-MAID =",
"= LESSON 10 THE SWING =",
"= LESSON 11 GOING FOR A DRIVE =",
"=== 5. ===",
"=== 6. ===",
"= LESSON 12 LUCY AND HER KITTEN =",
"= LESSON 13 THE CAT AND THE MOUSE =",
"=== 1. ===",
"=== 2. ===",
"=== 3. ===",
"=== 4. ===",
"=== 5. ===",
"=== 6. ===",
"=== 7. ===",
"==== WORD LESSON ====",
"= LESSON 14 TOM AND HIS DOG =",
"=== 1. ===",
"=== 2. ===",
"=== 3. ===",
"=== 4. ===",
"=== 5. ===",
"=== 6. ===",
"==== WORD LESSON ====",
"= LESSON 15 THE SHEEP AND THE LAMB =",
"=== 1. ===",
"=== 2. ===",
"=== 3. ===",
"=== 4. ===",
"=== 5. ===",
"=== 6. ===",
"=== 7. ===",
"==== WORD LESSON ====",
"= LESSON 16 THE HEN AND ITS CHICKS =",
"=== 1. ===",
"=== 2. ===",
"=== 3. ===",
"=== 4. ===",
"=== 5. ===",
"==== WORD LESSON ====",
"= LESSON 17 THE BIRD AND ITS NEST =",
"=== 1. ===",
"=== 2. ===",
"=== 3. ===",
"=== 4. ===",
"==== WORD LESSON ====",
"= LESSON 18 THE COW ON THE GRASS =",
"=== 1. ===",
"=== 2. ===",
"==== WORD LESSON ====",
"= LESSON 19 THE SEE-SAW =",
"= LESSON 20 THE CAT ON THE TREE =",
"= LESSON 21 THE BIRD'S SONG =",
"= LESSON 22 THE OLD MAN AND THE DOG =",
"= LESSON 23 MORNING AND NIGHT =",
"= LESSON 24 THE PET BIRD =",
"= LESSON 25 LITTLE PUSSY =",
"= LESSON 26 A WEEK AT THE FARM =",
"= LESSON 27 THE OWL =",
"= LESSON 28 THE PET GOAT =",
"= LESSON 29 THE STORM =",
"= LESSON 30 ON INSTINCT =",
"= LESSON 31 THE GREAT JUMP =",
"= LESSON 32 FRISK AND NED =",
"= LESSON 33 I WILL NOT HURT MY LITTLE DOG =",
"= LESSON 34 THE LARK =",
"= LESSON 35 MARY'S LITTLE LAMB =",
"= LESSON 36 ONE THING AT A TIME =",
"= LESSON 37 NURSERY RHYMES =",
"=== I ===",
"=== II ===",
"=== III ===",
"= LESSON 38 COUNT TEN =",
"==== PRONUNCIATION ====",
"= LESSON 39 MY DOG DASH =",
"==== PRONUNCIATION ====",
"= LESSON 40 GOOD-NIGHT =",
"=== THE MOMENTS ===",
"= LESSON 41 THE BOY THAT LIKED PLAY I =",
"==== PRONUNCIATION ====",
"= LESSON 42 THE BOY THAT LIKED PLAY II =",
"==== PRONUNCIATION ====",
"= LESSON 43 FORGIVE =",
"==== PRONUNCIATION ====",
"= LESSON 44 SPRING =",
"==== PRONUNCIATION ====",
"= LESSON 45 RAIN =",
"==== PRONUNCIATION ====",
"= LESSON 46 NORTH, SOUTH, EAST, WEST =",
"==== PRONUNCIATION ====",
"=== \"WASTE NOT, WANT NOT.\" ===",
"= LESSON 47 A VISIT TO THE BLACKSMITH'S SHOP =",
"==== PRONUNCIATION ====",
"= LESSON 48 FACTS FOR LITTLE FOLKS =",
"==== PRONUNCIATION ====",
"= LESSON 49 THE LAST CROSS WORD =",
"==== PRONUNCIATION ====",
"= LESSON 50 SUMMER =",
"==== PRONUNCIATION ====",
"= LESSON 51 AUTUMN =",
"==== PRONUNCIATION ====",
"= LESSON 52 MICE =",
"==== PRONUNCIATION ====",
"= LESSON 53 WHAT THE CLOCK SAYS =",
"=== DO JUSTLY ===",
"= LESSON 54 WINTER =",
"==== PRONUNCIATION ====",
"= LESSON 55 QUITE A MAN =",
"=== EVENING ===",
"=== MORNING ===",
"=== BEFORE MEAT ===",
"= LESSON 56 A WILLING BOY =",
"==== PRONUNCIATION ====",
"= LESSON 57 THE TWO WHITE RABBITS =",
"==== PRONUNCIATION ====",
"= LESSON 58 FAN AND HER PUPS =",
"==== PRONUNCIATION ====",
"= LESSON 59 A GAME WITH PUSS =",
"==== PRONUNCIATION ====",
"= LESSON 60 A GOOD LITTLE GIRL =",
"==== PRONUNCIATION ====",
"= LESSON 61 LITTLE WHEEL AND BIG WHEEL =",
"==== PRONUNCIATION ====",
"= LESSON 62 TIDY TOM =",
"==== PRONUNCIATION ====",
"= LESSON 63 WASHING DAY =",
"==== PRONUNCIATION ====",
"= LESSON 64 ON THE SHORE =",
"==== PRONUNCIATION ====",
"= LESSON 65 THE SUN =",
"==== PRONUNCIATION ====",
"= LESSON 66 SKIPPING =",
"==== PRONUNCIATION ====",
"= LESSON 67 EACH ONE USEFUL =",
"==== PRONUNCIATION ====",
"= LESSON 68 GOD IS IN HEAVEN =",
"= LESSON 69 THE RABBIT IN THE WOOD =",
"= LESSON 70 THE KETTLE AND ITS FRIENDS =",
"==== PRONUNCIATION ====",
"= LESSON 71 SAILING THE BOAT =",
"==== PRONUNCIATION ====",
"=== MORNING SONG ===",
"=== EVENING SONG ===",
"= LESSON 1 THE SPIDER =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 2 THE CHILD AND THE BIRD =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 3 THE RABBITS =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 4 THE TWO GOATS =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 5 EARLY RISING =",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 6 BEES =",
"=== I. ===",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"=== II. ===",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"=== III. ===",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 7 THE BEE =",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"=== PROVERBS ===",
"= LESSON 8 THE SWAN =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 9 TELL THE TRUTH =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"=== PROVERBS ===",
"= LESSON 10 WELCOME, LITTLE ROBIN =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 11 THE WOLF =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 12 THE ECHO =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 13 GOOD NIGHT AND GOOD MORNING =",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 14 STORY OF A PARROT =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"=== LITTLE THINGS ===",
"= LESSON 15 THE CAT AND THE CANARY =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 16 THE WASP AND THE BEE =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 17 THE HORSE =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 18 THE DOG WITH THE LANTERN =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"=== TRUTH ===",
"== USEFUL KNOWLEDGE I ==",
"=== ANIMALS ===",
"= LESSON 19 THE CAMEL =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 20 STORY OF A DOG =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 21 THE DONKEY =",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 22 STORY OF THE SHEEP AND THE LAMB =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 23 THE BROWN BEAR =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 24 THE LION AND THE MOUSE =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"= LESSON 25 THE PET LAMB =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 26 PERSEVERE =",
"= LESSON 27 THE CROW AND THE PITCHER =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 28 THE SOLDIER AND THE HORSE =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 29 LESSONS =",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 30 THE WHITE BEAR =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"=== NEVER PUT OFF ===",
"= LESSON 31 THE FOX AND THE GOAT =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 32 PLAY =",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"== USEFUL KNOWLEDGE II ==",
"=== A HOUSE ===",
"= LESSON 33 THE TRAVELLER AND THE LION =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 34 THE BEAR IN SCHOOL =",
"=== I. ===",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"=== II. ===",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 35 THE FAIRY RING =",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 36 THE WHALE =",
"==== QUESTIONS ====",
"= LESSON 37 THE HARE AND THE TORTOISE =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 38 SPEEDY AND STEADY =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 39 THE WOOD-MOUSE =",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 40 THE BOY AND THE PLUMS =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 41 THE TWO CROSSING-SWEEPERS =",
"==== QUESTIONS ====",
"== USEFUL KNOWLEDGE III ==",
"=== THE SEASONS ===",
"= LESSON 42 TOO CLEVER =",
"==== PRONUNCIATION ====",
"= LESSON 43 THE PRINCE AND THE PRISONERS =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 44 THE BRAVE LITTLE HOLLANDER =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 45 WHAT THE SPARROW CHIRPS =",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 46 THE LION =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 47 THE TIGER =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 48 THE LEOPARD =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 49 THE ZEBRA =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 50 THE JAGUAR =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 51 METALS =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"= LESSON 52 HIS GOOD ANGELS =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 53 ABOUT KINGS AND QUEENS =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 54 WORDS WHICH DECEIVE =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"= LESSON 55 THE SEA-GULL =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 56 KINDNESS REWARDED =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 57 TEA AND COFFEE =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 58 THE IDLE BOY =",
"=== THE IDLE BOY AT SCHOOL ===",
"=== THE IDLE BOY BECOMES A MAN ===",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 59 THROUGH THE SNOW =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 60 TRUE COURAGE =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 61 THE WIDOW'S LAMP =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 62 A GOOD EXAMPLE =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 63 A NOBLE BOY =",
"= LESSON 64 WHAT MAGGIE'S PENNY DID =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 65 LET US SPEAK THE BEST WE CAN =",
"==== PRONUNCIATION ====",
"= LESSON 1 THE SNAIL ON THE WALL =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 2 LITTLE JIM =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 3 THE TEA-FARMER =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 4 TIT FOR TAT =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"=== PROVERBS ===",
"= LESSON 5 THE HUMMING-BIRD =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 6 THE HUMMING-BIRD =",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 7 THE BOY WHO WAS ALWAYS TOO LATE =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 8 THE SAILOR AND THE MONKEYS =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 9 THE VOICE OF SPRING =",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 10 THE WONDERFUL PUDDING =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 11 STORIES OF THE ELEPHANT =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"== USEFUL KNOWLEDGE I ==",
"=== CLOTHING ===",
"=== COMMON THINGS ===",
"= LESSON 12 HOW A DOG GOT HIS DINNER =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 13 THE SALE OF THE PET LAMB =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 14 BRAVE BOBBY =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 15 THE TRAVELLERS AND THE BEAR =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 16 THE DUN COW =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 17 WE ARE SEVEN =",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 18 THE GATE WITHOUT A LATCH =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 19 THE SPIDER AND THE FLY =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"= LESSON 20 TAKE CARE OF THE MINUTES =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 21 THE BEGGAR MAN =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 22 HALF THE PROFIT =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 23 STORIES OF TIGERS I. =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"== USEFUL KNOWLEDGE II ==",
"=== COMMON THINGS ===",
"= LESSON 24 RED AND BLACK =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 25 THE DAW IN BORROWED FEATHERS =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 26 THE ANT AND THE CRICKET =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 27 THE DOG AND THE SHADOW =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 28 THE AMBITIOUS BOY =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 29 THE BETTER LAND =",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 30 THE ENGLISH GIRL AND HER AYAH =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 31 STORIES OF TIGERS II. =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 32 HOUSES MADE OF SNOW =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 33 THE CHILD'S FIRST GRIEF =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 34 THE FOX AND THE STORK =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 35 THE OSTRICH =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 36 DON'T BE TOO SURE =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 37 BUDS =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"== USEFUL KNOWLEDGE III ==",
"=== THE BREAKFAST-TABLE ===",
"= LESSON 38 THE DUKE AND THE COW-BOY =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 39 STORIES OF DOGS =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 40 LUCY GRAY =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 41 THE SAINT BERNARD DOG =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 42 THE LOST CHILD =",
"=== I. ===",
"=== II. ===",
"=== III. ===",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 43 THE BUSY LITTLE LAPP =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 44 THE DOG AT HIS MASTER'S GRAVE =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 45 THE STONE THAT REBOUNDED =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 46 WHALE HUNTING =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 47 THE BLIND BOY =",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 48 THE SPEAKING CHIP =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"== USEFUL KNOWLEDGE IV ==",
"=== METALS ===",
"= LESSON 49 THE SAILOR'S MOTHER =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 50 THE PRINCE AND THE JUDGE =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 51 A BEAVER TOWN =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 52 THE WEST INDIA ISLANDS =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 53 THE HEROIC DAUGHTER =",
"=== I. ===",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"=== II. ===",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"== USEFUL KNOWLEDGE V ==",
"=== THE EARTH ===",
"=== MOTIONS OF THE EARTH ===",
"= LESSON 54 LETTERS OF RECOMMENDATION =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 55 MEDDLESOME MATTY =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 56 HABITS OF FLOWERS =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 57 COMPLAINTS OF THE POOR =",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 58 THE CANVAS BOAT =",
"=== I. ===",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"=== II. ===",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 59 THE RAIN LESSON =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 60 THE ELEPHANT =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 61 CATCHING WILD ELEPHANTS IN CEYLON =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 62 THE PARROT =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 63 THE PARROT IN EXILE =",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 64 STORIES OF THE ELEPHANT =",
"=== II. ===",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 65 RALEIGH'S TWO PLANTS =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 66 THE ARK AND THE DOVE =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== WRITE ====",
"= LESSON 67 NO PAY, NO WORK =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 68 THE ORPHAN BOY'S TALE =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 69 LITTLE DICK AND THE GIANT =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 70 THE TRUNK OF THE ELEPHANT =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 1 SCENES IN THE TROPICS =",
"=== I．THE FOREST ===",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"=== II．THE BIRD OF PARADISE ===",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 2 CASABIANCA =",
"==== PRONUNCIATION ====",
"= LESSON 3 LITTLE ROBERT, THE TRAPPER =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 4 HOME, SWEET HOME =",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 5 THE WRECK OF THE \"HESPERUS\" =",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 6 TRY AGAIN =",
"=== I． ===",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"=== II． ===",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 7 THE SEA-GULL =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 8 MONKEYS ON BOARD SHIP =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"= LESSON 9 THE VOICE OF SPRING =",
"==== PRONUNCIATION ====",
"= LESSON 10 THE STINGING NETTLE =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 11 FABLES =",
"=== I．THE MONKEY AND THE CATS ===",
"=== II．THE FOX WITHOUT A TAIL ===",
"=== III．MERCURY AND THE WOODMAN ===",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"= LESSON 12 THE CUCKOO =",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 13 A FAITHFUL DOG =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 14 THE LOSS OF THE \"ROYAL GEORGE\" =",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 15 THE TAILOR-BIRD =",
"==== QUESTIONS ====",
"==== DICTATION ====",
"= LESSON 16 NAPOLEON AND THE YOUNG ENGLISH SAILOR =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 17 PEARL-FISHING =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"= LESSON 18 BE KIND =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 19 OBSERVATION =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"= LESSON 20 THE CHAMOIS =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 21 FIDELITY =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"= LESSON 22 THE ARAB AND HIS HORSE =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 23 ANECDOTES OF WASHINGTON =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 24 THE \"WHITE SHIP\" =",
"=== (A. D. 1120.) ===",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 25 HE NEVER SMILED AGAIN =",
"= LESSON 26 ANDROCLES AND THE LION =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 27 THE WIND IN A FROLIC =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 28 LLEWELYN AND HIS DOG =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"== OUTLINES OF BRITISH HISTORY I ==",
"=== I．THE ROMAN PERIOD ===",
"=== QUESTIONS ===",
"=== MEMORABLE DATES OF THE ROMAN PERIOD ===",
"=== II．THE OLD ENGLISH PERIOD ===",
"=== FROM THE ENGLISH SETTLEMENT TO EGBERT ===",
"=== QUESTIONS ===",
"=== EGBERT TO HAROLD ===",
"=== QUESTIONS ===",
"=== MEMORABLE DATES OF THE OLD ENGLISH PERIOD ===",
"=== CHIEF AUTHORS OF THE OLD ENGLISH PERIOD ===",
"=== III．&mdash;THE NORMAN LINE ===",
"=== WILLIAM I. &mdash;THE CONQUEROR ===",
"=== QUESTIONS ===",
"=== WILLIAM II. &mdash;RUFUS ===",
"=== QUESTIONS ===",
"=== HENRY I. &mdash; BEAUCLERC ===",
"=== QUESTIONS ===",
"=== STEPHEN ===",
"=== QUESTIONS ===",
"=== SCOTLAND ===",
"=== QUESTIONS ===",
"=== IRELAND ===",
"=== QUESTIONS ===",
"=== MEMORABLE DATES OF THE NORMAN PERIOD ===",
"=== CHIEF AUTHORS OF THE NORMAN PERIOD ===",
"= LESSON 29 THE MAY QUEEN I． =",
"==== DICTATION ====",
"= LESSON 30 THE SKY-LARK I． =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 31 THE SKY-LARK II． =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 32 THE MAY QUEEN II． =",
"==== PRONUNCIATION ====",
"= LESSON 33 THE BISON, OR AMERICAN BUFFALO =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 34 BISON-HUNTING =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 35 THE SHELTERING ROCK I． =",
"==== QUESTIONS ====",
"==== DICTATION ====",
"= LESSON 36 THE SHELTERING ROCK II． =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 37 LORD ULLIN'S DAUGHTER =",
"==== DICTATION ====",
"= LESSON 38 THE RORQUAL =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 39 THE INCHCAPE ROCK =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 40 THE SWALLOW I． =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 41 THE SWALLOW II． =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 42 BRUCE AND THE SPIDER =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 43 THE MOCKING-BIRD =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"= LESSON 44 THE VILLAGE BLACKSMITH =",
"= LESSON 45 THE GOLDEN EAGLE'S NEST I． =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 46 THE GOLDEN EAGLE'S NEST II． =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 47 THE GRAVES OF A HOUSEHOLD =",
"= LESSON 48 THE BATTLE OF BANNOCKBURN (A. D. 1314.) I． =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 49 THE BATTLE OF BANNOCKBURN II． =",
"==== QUESTIONS ====",
"==== DICTATION ====",
"= LESSON 50 THE SHIP ON FIRE =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 51 CROSSING THE ALPS =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"==== NOTE ====",
"= LESSON 52 THE WHITE-HEADED EAGLE =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 53 THE BURIAL OF SIR JOHN MOORE =",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 54 BRAVE WOMEN =",
"==== QUESTIONS ====",
"= LESSON 55 THE DEATH OF DE BOUNE =",
"== OUTLINES OF BRITISH HISTORY II ==",
"=== IV．THE PLANTAGENET LINE ===",
"=== HENRY II. CURTMANTLE ===",
"=== QUESTIONS ===",
"=== RICHARD I. COEUR DE LION, OR LION-HEARTED ===",
"=== QUESTIONS ===",
"=== JOHN&mdash;SANSTERRE, OR LACKLAND ===",
"=== QUESTIONS ===",
"=== HENRY III. WINCHESTER ===",
"=== QUESTIONS ===",
"=== EDWARD I. LONGSHANKS ===",
"=== QUESTIONS ===",
"=== EDWARD II. CAERNARVON ===",
"=== QUESTIONS ===",
"=== EDWARD III ===",
"=== QUESTIONS ===",
"=== RICHARD II. BORDEAUX ===",
"=== QUESTIONS ===",
"=== SCOTLAND ===",
"=== QUESTIONS ===",
"=== IRELAND ===",
"=== QUESTIONS ===",
"=== MEMORABLE DATES UNDER THE PLANTAGENETS PROPER ===",
"=== CHIEF AUTHORS OF THE EARLY PLANTAGENET PERIOD ===",
"= LESSON 56 STORY OF SIR RICHARD ARKWRIGHT =",
"=== Come to the SUBTERRANEOUS BARBER! He Shaves for a Penny!! ===",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"= LESSON 57 THE LEGEND OF THE HEART OF BRUCE =",
"==== QUESTIONS ====",
"==== DICTATION ====",
"= LESSON 58 THE ROMANS IN BRITAIN =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 59 BOADICEA =",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 60 ARCHERY IN THE OLDEN TIME I． =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 61 ARCHERY IN THE OLDEN TIME II． =",
"==== QUESTIONS ====",
"= LESSON 62 JESSIE OF LUCKNOW =",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 63 THE FALLS OF NIAGARA =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 64 TO-DAY AND TO-MORROW =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 65 AN ICEBERG =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 66 LOVE OF COUNTRY =",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 67 THE HAND =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 68 THE BONFIRE OF CRAIG-GOWAN =",
"==== DICTATION ====",
"= LESSON 69 NOBLE REVENGE =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 70 THE RELIEF OF LONDONDERRY =",
"==== QUESTIONS ====",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"= LESSON 71 THE LOSS OF THE \"BIRKENHEAD\" =",
"==== QUESTIONS ====",
"= LESSON 72 A WILD NIGHT AT SEA =",
"==== PRONUNCIATION ====",
"==== DICTATION ====",
"== OUTLINES OF BRITISH HISTORY III ==",
"=== HOUSE OF LANCASTER ===",
"=== HENRY IV. BOLINGBROKE ===",
"=== QUESTIONS ===",
"=== HENRY V. MONMOUTH. ===",
"=== QUESTIONS ===",
"=== HENRY VI. WINDSOR ===",
"=== QUESTIONS ===",
"=== HOUSE OF YORK ===",
"=== EDWARD IV ===",
"=== QUESTIONS ===",
"=== EDWARD V ===",
"=== QUESTIONS ===",
"=== RICHARD III. CROOKBACK ===",
"=== QUESTIONS ===",
"=== SCOTLAND ===",
"=== QUESTIONS ===",
"=== IRELAND ===",
"=== QUESTIONS ===",
"=== MEMORABLE DATES OF THE LANCASTER AND YORK PERIODS ===",
"=== CHIEF AUTHORS OF THE LANCASTER AND YORK PERIODS ===",
"=== SCOTLAND ===",
"=== QUESTIONS ===",
"= LESSON 1 A PERILOUS ADVENTURE =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 2 THE DESTRUCTION OF SENNACHERIB'S ARMY =",
"==== WORDS ====",
"= LESSON 3 \"ABOVE THE CLOUDS\" =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 4 THE CONDOR OF THE ANDES =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 5 THE PRAIRIE ON FIRE (I) =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 6 THE PRAIRIE ON FIRE (II) =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 7 MARY, QUEEN OF SCOTS =",
"==== WORDS ====",
"= LESSON 8 DEATH OF LITTLE NELL =",
"==== WORDS ====",
"= LESSON 9 GRACE DARLING =",
"==== WORDS ====",
"= LESSON 10 THE FRIGATE-BIRD =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 11 A MOTHER'S LOVE =",
"==== WORDS ====",
"= LESSON 12 NELSON AND HARDY =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 13 THE SPANISH CHAMPION =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 14 THE CHEMISTRY OF A CANDLE (I) =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 15 THE CHEMISTRY OF A CANDLE (II) =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 16 THE \"MAYFLOWER\" =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 17 THE PILGRIM FATHERS =",
"==== WORDS ====",
"= LESSON 18 LIVING STOVES =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 19 DAVID'S LAMENT FOR ABSALOM =",
"==== WORDS ====",
"= LESSON 20 SCENES IN CANTON =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 21 THE RAINBOW =",
"==== WORDS ====",
"= LESSON 22 GREENLAND (I) =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 23 GREENLAND (II) =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 24 ICELAND, AND THE GEYSERS =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 25 LADY CLARE =",
"==== WORDS ====",
"= LESSON 26 THE BATTLE OF THE NILE =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 27 THE AURORA =",
"==== WORDS ====",
"= LESSON 28 THE BATTLE OF THE BALTIC =",
"==== WORDS ====",
"= LESSON 29 TRIUMPHS OF THE ENGLISH LANGUAGE =",
"==== WORDS ====",
"= LESSON 30 YOUNG LOCHINVAR =",
"==== WORDS ====",
"= LESSON 31 THE TIDAL BORE OF THE TSIEN-TANG =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 32 THE SAXON AND THE GAEL =",
"==== WORDS ====",
"= LESSON 33 THE WELL OF ST. KEYNE =",
"==== WORDS ====",
"= LESSON 34 CAPTURING THE WILD HORSE =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 35 THE SIEGE OF QUEBEC =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 36 THE DESERTED VILLAGE =",
"==== WORDS ====",
"= LESSON 37 HUDSON BAY TERRITORY =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 38 THE FOUR ERAS =",
"==== WORDS ====",
"= LESSON 39 THE SKATER AND THE WOLVES =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 40 THE VILLAGE PREACHER =",
"==== WORDS ====",
"= LESSON 41 AN INDIAN'S TRAPS =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 42 VIRGINIA =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 43 WATERLOO =",
"==== WORDS ====",
"= LESSON 44 THE SLAVE'S DREAM =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 45 THE SIEGE OF TORQUILSTONE (I) =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 46 THE SIEGE OF TORQUILSTONE (II) =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 47 PENNSYLVANIA =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 48 THE SKY-LARK =",
"==== WORDS ====",
"= LESSON 49 WEATHERING CAPE HORN =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 50 ON THE DOWNFALL OF POLAND =",
"==== WORDS ====",
"= LESSON 51 THE EYE (I) =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 52 THE EYE (II) =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 53 THE SHIPWRECK =",
"==== WORDS ====",
"= LESSON 54 THE FIVE GREAT OCEANS =",
"=== THE ARCTIC OCEAN ===",
"=== THE ANTARCTIC OCEAN ===",
"=== THE ATLANTIC OCEAN ===",
"=== PRINCIPAL SEAS&mdash;EAST ===",
"=== PRINCIPAL SEAS&mdash;WEST ===",
"=== BED OF THE ATLANTIC ===",
"=== THE PACIFIC OCEAN ===",
"=== THE INDIAN OCEAN ===",
"= LESSON 55 HEALTH OF THE BODY =",
"=== FOOD ===",
"==== QUESTIONS ====",
"=== CLEANLINESS ===",
"==== QUESTIONS ====",
"=== CLOTHING ===",
"==== QUESTIONS ====",
"=== VENTILATION ===",
"==== QUESTIONS ====",
"=== EXERCISE AND REST ===",
"==== QUESTIONS ====",
"= LESSON 56 THE AMAZON =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 57 THE PACIFIC OCEAN (I) =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 58 THE PACIFIC OCEAN (II) =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 59 THE HIMALAYAH (I) =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 60 THE HIMALAYAH (II) =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 61 LONDON AND ITS FOOD =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 62 THE WATERS OF THE GLOBE =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 63 THE OCEAN =",
"==== WORDS ====",
"= LESSON 64 THE VISION OF MIRZA =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 65 A PSALM OF LIFE =",
"==== WORDS ====",
"= LESSON 66 THE TIDE-WAVE IN THE BAY OF FUNDY =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 67 COAL =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 68 THE AIR-OCEAN =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 69 UNWRITTEN HISTORY, AND HOW TO READ IT =",
"==== WORDS ====",
"==== QUESTIONS ====",
"= LESSON 1 THE GREAT SIEGE OF GIBRALTAR =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 2 BATTLE OF CORUNA AND DEATH OF MOORE =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 3 THE BURIAL OF SIR JOHN MOORE =",
"= LESSON 4 THE BED OF THE ATLANTIC =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 5 BINGEN ON THE RHINE =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 6 THE CLOUD =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 7 THE TRIAL BY COMBAT (I) =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 8 THE TRIAL BY COMBAT (II) =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 9 DAMASCUS AND LONDON (I) =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 10 DAMASCUS AND LONDON (II) =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 11 BATTLE OF TRAFALGAR, AND DEATH OF NELSON (I) =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 12 BATTLE OF TRAFALGAR, AND DEATH OF NELSON (II) =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 13 ROUND THE WORLD =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 14 NATURE =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 15 THE TROPICAL WORLD (I) =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 16 MAN AND THE INDUSTRIAL ARTS =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 17 SOMEBODY'S DARLING =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 18 THE TROPICAL WORLD (II) =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 19 THE SONG OF THE SHIRT =",
"==== WORDS ====",
"= LESSON 20 LAND AND SEA BREEZES =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 21 THE RELIEF OF LEYDEN =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 22 THE GLOVE AND THE LIONS =",
"==== WORDS ====",
"=== DESPISED OLD AGE ===",
"= LESSON 23 THE POLAR WORLD (I) =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 24 THE BELLS =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 25 THE POLAR WORLD (II) =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 26 THE BURNING OF MOSCOW =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 27 THE RETREAT OF THE FRENCH ARMY FROM MOSCOW =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 28 THE TEMPERATE REGIONS =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 29 THE OVERLAND ROUTE =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 30 CAIRO AND THE PYRAMIDS =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 31 FAMILY WORSHIP =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 32 THE VALLEY OF THE NILE =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 33 PANEGYRIC ON MARIE ANTOINETTE =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 34 CRUELTY TO ANIMALS =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 35 THE DELUGE =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 36 WHAT IS WAR? =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 37 COLONIAL LOYALTY =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 38 JERUSALEM FROM THE MOUNT OF OLIVES =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 39 THE SIEGE OF JERUSALEM =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 40 LEBANON =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 41 GREAT OCEAN ROUTES =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 42 THE LLANOS OF SOUTH AMERICA =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 43 THE DEATH OF NAPOLEON AT ST. HELENA =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 44 HYMN BEFORE SUNRISE, IN THE VALE OF CHAMOUNI =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 45 \"WITH BRAINS, SIR.\" =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 46 LIFE IN SAXON ENGLAND (I) =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 47 LIFE IN SAXON ENGLAND (II) =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 48 THE RELIEF OF LUCKNOW =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 49 THE BALACLAVA CHARGE =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 50 THE CHARGE OF THE LIGHT BRIGADE =",
"==== WORDS ====",
"==== NOTES ====",
"=== FRIENDS ===",
"= LESSON 51 THE DISCOVERY OF THE SEA ROUTE TO INDIA =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 52 GREECE =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 53 THERMOPYLÆ =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 54 PAUL AT ATHENS =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 55 EVIDENCES OF DESIGN IN CREATION =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 56 THE STORY OF HORATIUS =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 57 ROMAN GIRL'S SONG =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 58 REGULUS BEFORE THE ROMAN SENATE =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 59 THE SAHARA =",
"=== OASES ===",
"=== THE ARABS ===",
"=== CARAVANS ===",
"==== WORDS ====",
"==== NOTES ====",
"==== QUSTIONS ====",
"= LESSON 60 THE LIGHT-HOUSE =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 61 THE LAST FIGHT IN THE COLISÆUM =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 62 THE DESTRUCTION OF POMPEII =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 63 THE SOUTH-WEST MONSOON IN CEYLON =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"=== AMBITION CLAD IN HUMILITY. ===",
"= LESSON 64 THE SEVEN AGES OF MAN =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 65 LIFE IN NORMAN ENGLAND =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 66 SIR ROGER DE COVERLEY =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 67 OLD ENGLISH AND NORMAN-FRENCH =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 68 VENICE =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 69 THE CIRCULATION OF WATER =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 70 GINEVRA =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 71 THE DIGNITY OF LABOUR =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 72 THE PROBLEM OF CREATION =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 73 EDUCATION AND THE STATE =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"==== NOTES ====",
"= LESSON 74 ENGLISH SELF-ESTEEM =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 75 PLEASURES OF KNOWLEDGE =",
"==== WORDS ====",
"==== NOTES ====",
"= LESSON 76 THE BRITISH CONSTITUTIONAL SYSTEM OF CANADA =",
"==== WORDS ====",
"= LESSON 77 THE SCHOOLMASTER AND THE CONQUEROR =",
"==== WORDS ====",
"= LESSON 78 BRITISH COLONIAL AND NAVAL POWER =",
"==== WORDS ====",
"==== NOTES ====",
"==== QUESTIONS ====",
"= LESSON 79 KING JOHN =",
"=== PART I. ===",
"==== WORDS ====",
"==== NOTES ====",
"=== PART II. ===",
"==== WORDS ====",
"==== NOTES ====",
];
