var menulist=[
"= 前  言 =",
"= Odes 颂 =",
"== Ode on Indolence ==",
"=== I ===",
"=== II ===",
"=== III ===",
"=== IV ===",
"=== V ===",
"=== VI ===",
"== 怠惰颂 ==",
"=== I ===",
"=== II ===",
"=== III ===",
"=== IV ===",
"=== V ===",
"=== VI ===",
"== Ode to Psyche ==",
"== 赛吉颂 ==",
"== Ode to a Nightingale ==",
"=== I ===",
"=== II ===",
"=== III ===",
"=== IV ===",
"=== V ===",
"=== VI ===",
"=== VII ===",
"=== VIII ===",
"== 夜莺颂 ==",
"=== I ===",
"=== II ===",
"=== III ===",
"=== IV ===",
"=== V ===",
"=== VI ===",
"=== VII ===",
"=== VIII ===",
"== Ode on a Grecian Urn ==",
"=== I ===",
"=== II ===",
"=== III ===",
"=== IV ===",
"=== V ===",
"== 希腊古瓮颂 ==",
"=== I ===",
"=== II ===",
"=== III ===",
"=== IV ===",
"=== V ===",
"== Ode on Melancholy ==",
"=== I ===",
"=== II ===",
"=== III ===",
"== 忧郁颂 ==",
"=== I ===",
"=== II ===",
"=== III ===",
"== To Autumn ==",
"=== I ===",
"=== II ===",
"=== III ===",
"== 秋  颂 ==",
"=== I ===",
"=== II ===",
"=== III ===",
"= Sonnets 十四行诗 =",
"== On Peace ==",
"== 咏和平 ==",
"== To Chatterton ==",
"== 致查特顿 ==",
"== To Lord Byron ==",
"== 致拜伦 ==",
"== Written on the Day that Mr. Leigh Hunt Left Prison ==",
"== 写于李·亨特先生出狱之日 ==",
"== 'O Solitude! if I must with thee dwell' ==",
"== “哦，孤独！如果我和你必须同住” ==",
"== 'How many bards gild the lapses of time' ==",
"== “多少诗人把光阴镀成了黄金” ==",
"== To a Friend who Sent Me Some Roses ==",
"== 给一位赠我以玫瑰的朋友 ==",
"== On Receiving a Laurel Crown from Leigh Hunt ==",
"== 接受李·亨特递过来的桂冠 ==",
"== To the Ladies who Saw Me Crowned ==",
"== 致姑娘们&mdash;&mdash;她们见我戴上了桂冠 ==",
"== 'To one who has been long in city pent' ==",
"== “对于一个长困在城里的人” ==",
"== To my Brother George ==",
"== 给我的弟弟乔治 ==",
"== On First Looking into Chapman's Homer ==",
"== 初读恰普曼译荷马史诗 ==",
"== 'Keen, fitful gusts are whispering here and there' ==",
"== “刺骨的寒风阵阵，在林中回旋” ==",
"== On Leaving Some Friends at an Early Hour ==",
"== 一清早送别友人们 ==",
"== To my Brothers ==",
"== 给我的两个弟弟 ==",
"== Addressed to Haydon ==",
"== 致海登（一） ==",
"== Addressed to the Same ['Great Spirits'] ==",
"== 致海登（二） ==",
"== Written in Disgust of Vulgar Superstition ==",
"== 厌于世人的迷信而作 ==",
"== On the Grasshopper and Cricket ==",
"== 蝈蝈和蟋蟀 ==",
"== To Kosciusko ==",
"== 致柯斯丘什科 ==",
"== To Georgiana Augusta Wylie ==",
"== 给G. A. W. ==",
"== 'Oh! How I love, on a fair summer's eve' ==",
"== “啊！我真爱&mdash;&mdash;在一个美丽的夏夜” ==",
"== 'After dark vapours have oppressed our plains' ==",
"== “漫长的严冬过去了，愁云惨雾” ==",
"== Written on a Blank Space at the End of Chaucer's Tale 'The Floure and the Leafe' ==",
"== 写在乔叟的故事《花与叶》的末页上 ==",
"== On Seeing the Elgin Marbles ==",
"== 初见额尔金石雕有感 ==",
"== To Leigh Hunt, Esq. ==",
"== 献诗&mdash;&mdash;呈李·亨特先生 ==",
"== On the Sea ==",
"== 咏大海 ==",
"== Sonnet on a Picture of Leander ==",
"== 咏勒安得画像 ==",
"== 'Happy is England! I could be content' ==",
"== “英国多快乐！我感到由衷满意” ==",
"== On Sitting Down to Read King Lear Once Again ==",
"== 坐下来重读《里亚王》有感 ==",
"== 'When I have fears that I may cease to be' ==",
"== “我恐惧，我可能就要停止呼吸” ==",
"== To&mdash;['Time's sea'] ==",
"== 给&mdash;&mdash; ==",
"== Sonnet to Spenser ==",
"== 致斯宾塞 ==",
"== Sonnet&mdash;The Human Seasons ==",
"== 人的季节 ==",
"== On Visiting the Tomb of Burns ==",
"== 访彭斯墓 ==",
"== Sonnet Written in the Cottage where Burns was Born ==",
"== 写于彭斯诞生的村舍 ==",
"== To Ailsa Rock ==",
"== 致艾尔萨巨岩 ==",
"== Sonnet Written upon the Top of Ben Nevis ==",
"== 写于本·尼维斯山巅 ==",
"== To Homer ==",
"== 致荷马 ==",
"== 'Why did I laugh to-night? No voice will tell' ==",
"== “为什么今夜我发笑？没声音回答” ==",
"== Sonnet&mdash;A Dream, after Reading Dante's Episode of Paulo and Francesca ==",
"== 咏梦&mdash;&mdash;读但丁所写保罗和弗兰切斯卡故事后 ==",
"== To Sleep ==",
"== 致睡眠 ==",
"== Two Sonnets on Fame (Ⅰ) ==",
"== 咏名声（一） ==",
"== Two Sonnets on Fame（Ⅱ） ==",
"== 咏名声（二） ==",
"== 'If by dull rhymes our English must be chained' ==",
"== “如果英诗必须受韵式制约” ==",
"== Sonnet to Fanny ==",
"== 致芳妮 ==",
"== 'The day is gone and all its sweets are gone' ==",
"== “白天消逝了，甜蜜的一切已失去！” ==",
"== 'Bright star! Would I were steadfast as thou art' ==",
"== “亮星！但愿我像你一样坚持” ==",
"= Lyrics·Ballads·Others 抒情诗·歌谣·其他 =",
"== On Death ==",
"=== I ===",
"=== II ===",
"== 死 ==",
"=== I ===",
"=== II ===",
"== Sleep and Poetry ==",
"== 睡与诗 ==",
"== To Emma Mathew ==",
"== 致爱玛 ==",
"== Lines on the Mermaid Tavern ==",
"== 咏美人鱼酒店 ==",
"== Faery Song ==",
"== 仙子的歌 ==",
"== Daisy's Song ==",
"=== I ===",
"=== II ===",
"=== III ===",
"== 雏菊的歌 ==",
"=== I ===",
"=== II ===",
"=== III ===",
"== 'Where be ye going, you Devon maid?' ==",
"=== I ===",
"=== II ===",
"=== III ===",
"=== IV ===",
"== “你到哪儿去，德文郡姑娘？” ==",
"=== I ===",
"=== II ===",
"=== III ===",
"=== IV ===",
"== Robin Hood&mdash;To a friend ==",
"== 罗宾汉&mdash;&mdash;给一位朋友 ==",
"== Ode ==",
"== 诗人颂 ==",
"== Fancy ==",
"== 幻  想 ==",
"== La Belle Dame Sans Merci ==",
"=== I ===",
"=== II ===",
"=== III ===",
"=== IV ===",
"=== V ===",
"=== VI ===",
"=== VII ===",
"=== VIII ===",
"=== IX ===",
"=== X ===",
"=== XI ===",
"=== XII ===",
"== 冷酷的妖女 ==",
"=== I ===",
"=== II ===",
"=== III ===",
"=== IV ===",
"=== V ===",
"=== VI ===",
"=== VII ===",
"=== VIII ===",
"=== IX ===",
"=== X ===",
"=== XI ===",
"=== XII ===",
"= Narrative Poem 叙事诗 =",
"== The Eve of St. Agnes ==",
"=== I ===",
"=== II ===",
"=== III ===",
"=== IV ===",
"=== V ===",
"=== VI ===",
"=== VII ===",
"=== VIII ===",
"=== IX ===",
"=== X ===",
"=== XI ===",
"=== XII ===",
"=== XIII ===",
"=== XIV ===",
"=== XV ===",
"=== XVI ===",
"=== XVII ===",
"=== XVIII ===",
"=== XIX ===",
"=== XX ===",
"=== XXI ===",
"=== XXII ===",
"=== XXIII ===",
"=== XXIV ===",
"=== XXV ===",
"=== XXVI ===",
"=== XXVII ===",
"=== XXVIII ===",
"=== XXIX ===",
"=== XXX ===",
"=== XXXI ===",
"=== XXXII ===",
"=== XXXIII ===",
"=== XXXIV ===",
"=== XXXV ===",
"=== XXXVI ===",
"=== XXXVII ===",
"=== XXXVIII ===",
"=== XXXIX ===",
"=== XL ===",
"=== XLI ===",
"=== XLII ===",
"== 圣亚尼节前夕 ==",
"=== I ===",
"=== II ===",
"=== III ===",
"=== IV ===",
"=== V ===",
"=== VI ===",
"=== VII ===",
"=== VIII ===",
"=== IX ===",
"=== X ===",
"=== XI ===",
"=== XII ===",
"=== XIII ===",
"=== XIV ===",
"=== XV ===",
"=== XVI ===",
"=== XVII ===",
"=== XVIII ===",
"=== XIX ===",
"=== XX ===",
"=== XXI ===",
"=== XXII ===",
"=== XXIII ===",
"=== XXIV ===",
"=== XXV ===",
"=== XXVI ===",
"=== XXVII ===",
"=== XXVIII ===",
"=== XXIX ===",
"=== XXX ===",
"=== XXXI ===",
"=== XXXII ===",
"=== XXXIII ===",
"=== XXXIV ===",
"=== XXXV ===",
"=== XXXVI ===",
"=== XXXVII ===",
"=== XXXVIII ===",
"=== XXXIX ===",
"=== XL ===",
"=== XLI ===",
"=== XLII ===",
];
