var menulist=[
"= 目录 =",
"= INTRODUCTION =",
"= 导&nbsp;&nbsp;&nbsp;论 =",
"== ●&nbsp;&nbsp;&nbsp;I ==",
"== ●&nbsp;&nbsp;&nbsp;一 ==",
"== ●&nbsp;&nbsp;&nbsp;II ==",
"== ●&nbsp;&nbsp;&nbsp;二 ==",
"== ●&nbsp;&nbsp;&nbsp;III ==",
"== ●&nbsp;&nbsp;&nbsp;三 ==",
"== ●&nbsp;&nbsp;&nbsp;IV ==",
"== ●&nbsp;&nbsp;&nbsp;四 ==",
"== ●&nbsp;&nbsp;&nbsp;V ==",
"== ●&nbsp;&nbsp;&nbsp;五 ==",
"== ●&nbsp;&nbsp;&nbsp;VI ==",
"== ●&nbsp;&nbsp;&nbsp;六 ==",
"= Chapter One&nbsp;&nbsp;&nbsp;The Gentry and the Imperial Power =",
"= 第壹章&nbsp;&nbsp;&nbsp;士绅与皇权 =",
"= Chapter Two&nbsp;&nbsp;&nbsp;The Scholar Becomes the Official =",
"= 第贰章&nbsp;&nbsp;&nbsp;文人当官 =",
"= Chapter Three&nbsp;&nbsp;&nbsp;The Gentry and Technical Knowledge =",
"= 第叁章&nbsp;&nbsp;&nbsp;士绅与技术知识 =",
"= Chapter Four&nbsp;&nbsp;&nbsp;Basic Power Structure in Rural China =",
"= 第肆章&nbsp;&nbsp;&nbsp;中国乡村的基本权力结构 =",
"== ●&nbsp;&nbsp;&nbsp;THE DO-NOTHING POLICY OF THE IMPERIAL POWER ==",
"== ●&nbsp;&nbsp;&nbsp;皇权的无为政策 ==",
"== ●&nbsp;&nbsp;&nbsp;THE POLITICAL TRACK FROM THE BOTTOM UP ==",
"== ●&nbsp;&nbsp;&nbsp;由下而上的政治轨道 ==",
"== ●&nbsp;&nbsp;&nbsp;THE BREAKDOWN OF THE LOCAL SELF-GOVERNING GROUP ==",
"== ●&nbsp;&nbsp;&nbsp;地方自治团体的崩溃 ==",
"== ●&nbsp;&nbsp;&nbsp;TEARING UP THE DOUBLE TRACK ==",
"== ●&nbsp;&nbsp;&nbsp;双轨的拆除 ==",
"= Chapter Five&nbsp;&nbsp;&nbsp;Village, Town, and City =",
"= 第伍章&nbsp;&nbsp;&nbsp;村、镇与城市 =",
"== ●&nbsp;&nbsp;&nbsp;POPULATION AND URBAN COMMUNITIES ==",
"== ●&nbsp;&nbsp;&nbsp;人口与城市社区 ==",
"== ●&nbsp;&nbsp;&nbsp;THE WALLED OR GARRISON TOWN: A POLITICAL CENTER ==",
"== ●&nbsp;&nbsp;&nbsp;衙门围墙式的城：一个政治中心 ==",
"== ●&nbsp;&nbsp;&nbsp;MARKETS AND TOWNS DEVELOPED FROM TRADE ==",
"== ●&nbsp;&nbsp;&nbsp;由贸易发展而来的集市和镇 ==",
"== ●&nbsp;&nbsp;&nbsp;THE TREATY PORT ==",
"== ●&nbsp;&nbsp;&nbsp;通商口岸 ==",
"= Chapter Six&nbsp;&nbsp;&nbsp;Rural Livelihood: Agriculture and Handicraft =",
"= 第陆章&nbsp;&nbsp;&nbsp;乡村生计：农业与手工业 =",
"== ●&nbsp;&nbsp;&nbsp;DISTRIBUTION OF LAND AND THE WELFARE OF THE PEOPLE ==",
"== ●&nbsp;&nbsp;&nbsp;分田与人民的福利 ==",
"== ●&nbsp;&nbsp;&nbsp;RURAL LIVELIHOOD&mdash;HANDICRAFTS AND AGRICULTURE ==",
"== ●&nbsp;&nbsp;&nbsp;乡村生计&mdash;&mdash;手工业和农业 ==",
"== ●&nbsp;&nbsp;&nbsp;THE TRADITIONAL MECHANISM OUT OF GEAR ==",
"== ●&nbsp;&nbsp;&nbsp;传统机制的脱栓 ==",
"== ●&nbsp;&nbsp;&nbsp;THE REASONABLE WAY OUT FOR THE LANDLORD CLASS ==",
"== ●&nbsp;&nbsp;&nbsp;地主阶级的合理出路 ==",
"== ●&nbsp;&nbsp;&nbsp;THE GROWING GAP BETWEEN RURAL AND URBAN AREAS ==",
"== ●&nbsp;&nbsp;&nbsp;城乡差别的不断扩大 ==",
"= Chapter Seven&nbsp;&nbsp;&nbsp;Social Erosion in the Rural Communities =",
"= 第柒章&nbsp;&nbsp;&nbsp;乡土社区的社会侵蚀 =",
"== ●&nbsp;&nbsp;&nbsp;EROSION: OF LAND AND OF MAN ==",
"== ●&nbsp;&nbsp;&nbsp;对土地和人的侵蚀 ==",
"== ●&nbsp;&nbsp;&nbsp;THE DESERTERS&mdash;RURAL BOYS WHO DO NOT COME BACK HOME ==",
"== ●&nbsp;&nbsp;&nbsp;逃亡者&mdash;&mdash;不回家的乡村子弟 ==",
"== ●&nbsp;&nbsp;&nbsp;THE PARASITIC LAYER ==",
"== ●&nbsp;&nbsp;&nbsp;寄生阶层 ==",
"== ●&nbsp;&nbsp;&nbsp;BENEATH THE FLOOD ==",
"== ●&nbsp;&nbsp;&nbsp;在洪流的冲洗下 ==",
"= EDITOR'S NOTE =",
"= 编后记 =",
"= 译后记：逝者如斯的结构秩序 =",
"== 一 ==",
"== 二 ==",
"== 三 ==",
"== 四 ==",
"== 五 ==",
"== 六 ==",
"== 七 ==",
];
