var menulist=[
"== 前　言 ==",
"== 考试小贴士 ==",
"== 重点单词 ==",
"== Word List 1 ==",
"== Word List 2 ==",
"== Word List 3 ==",
"== Word List 4 ==",
"== Word List 5 ==",
"== Word List 6 ==",
"== Word List 7 ==",
"== Word List 8 ==",
"== Word List 9 ==",
"== Word List 10 ==",
"== Word List 11 ==",
"== Word List 12 ==",
"== Word List 13 ==",
"== Word List 14 ==",
"== Word List 15 ==",
"== Word List 16 ==",
"== Word List 17 ==",
"== Word List 18 ==",
"== Word List 19 ==",
"== Word List 20 ==",
"== 认知词 ==",
"== 常考词回顾 ==",
"== 索引 ==",
];
