var menulist=[
"= 目录 =",
"= 路西法的女儿（代译序） =",
"=== 凯伦其人 ===",
"=== 《走出非洲》其书 ===",
"=== 几点说明 ===",
"= 卡曼特与露露 =",
"== 恩贡农场 ==",
"== 一个原住民男孩 ==",
"== 原住民在我家 ==",
"== 一头瞪羚 ==",
"= 农场上的枪击事故 =",
"== 枪击事故 ==",
"== 在野生动物保护区驭马而行 ==",
"== 瓦麦 ==",
"== 万扬格里 ==",
"== 一位基库尤酋长 ==",
"= 农场访客 =",
"== 盛大舞会 ==",
"== 亚洲来客 ==",
"== 索马里妇女 ==",
"== 老努森 ==",
"== 流浪者农场小住 ==",
"== 有朋自远近来 ==",
"== 拓荒者中的贵族 ==",
"== 翼 ==",
"= 移民手记 =",
"== 萤火虫 ==",
"== 生活之路 ==",
"== 猛兽的救赎 ==",
"== 埃萨的故事 ==",
"== 鬣蜥蜴 ==",
"== 法拉与《威尼斯商人》 ==",
"== 伯恩茅斯的上流社会 ==",
"== 有关骄傲 ==",
"== 牛 ==",
"== 两个种族 ==",
"== 战时的远征 ==",
"== 斯瓦希里数字体系 ==",
"== “我绝不容许你离开，直到你赐福于我” ==",
"== 月食 ==",
"== 原住民与诗 ==",
"== 有关千禧年 ==",
"== 基托希事件 ==",
"== 一些非洲鸟类 ==",
"== 帕尼亚 ==",
"== 埃萨之死 ==",
"== 有关原住民与历史 ==",
"== 地震 ==",
"== 乔治 ==",
"== 小汤匙 ==",
"== 长颈鹿去汉堡 ==",
"== 在动物展览会里 ==",
"== 旅伴 ==",
"== 博物学家与猴子 ==",
"== 卡罗门亚 ==",
"== 普莱·辛格 ==",
"== 奇遇 ==",
"== 鹦鹉 ==",
"= 别了，农场 =",
"== 艰难时世 ==",
"== 吉南朱伊之死 ==",
"== 山中坟茔 ==",
"== 法拉与我倾家抛售 ==",
"== 永别 ==",
"= 假如你还想知道更多（代译后记） =",
"= CONTENTS =",
"= KAMANTE AND LULU =",
"== The Ngong Farm ==",
"== A Native Child ==",
"== The Savage in the Immigrant's House ==",
"== A Gazelle ==",
"= A SHOOTING ACCIDENT ON THE FARM =",
"== The Shooting Accident ==",
"== Riding in the Reserve ==",
"== Wamai ==",
"== Wanyangerri ==",
"== A Kikuyu Chief ==",
"= VISITORS TO THE FARM =",
"== Big Dances ==",
"== A Visitor from Asia ==",
"== The Somali Women ==",
"== Old Knudsen ==",
"== A Fugitive Rests on the Farm ==",
"== Visits of Friends ==",
"== The Noble Pioneer ==",
"== Wings ==",
"= FROM AN IMMIGRANT'S NOTEBOOK =",
"== The Fireflies ==",
"== The Roads of Life ==",
"== The Wild came to the Aid of the Wild ==",
"== Esa's Story ==",
"== The Iguana ==",
"== Farah and the Merchant of Venice ==",
"== The Elite of Bournemouth ==",
"== Of Pride ==",
"== The Oxen ==",
"== Of the Two Races ==",
"== A War-time Safari ==",
"== The Swaheli Numeral System ==",
"== “I will not let Thee go except Thou bless me．” ==",
"== The Eclipse of the Moon ==",
"== Natives and Verse ==",
"== Of the Millennium ==",
"== Kitosch's Story ==",
"== Some African Birds ==",
"== Pania ==",
"== Esa's Death ==",
"== Of Natives and History ==",
"== The Earthquake ==",
"== George ==",
"== Kejiko ==",
"== The Giraffes go to Hamburg ==",
"== In the Menagerie ==",
"== Fellow-Travellers ==",
"== The Naturalist and the Monkeys ==",
"== Karomenya ==",
"== Pooran Singh ==",
"== A Strange Happening ==",
"== The Parrot ==",
"= FAREWELL TO THE FARM =",
"== Hard Times ==",
"== Death of Kinanjui ==",
"== The Grave in the Hills ==",
"== Farah and I Sell out ==",
"== Farewell ==",
];
