var menulist=[
"= A JOURNEY TO THE CENTRE OF THE EARTH =",
"== By Jules Verne ==",
"== Table of Contents ==",
"== CHAPTER 1 ==",
"==== MY UNCLE MAKES A GREAT DISCOVERY ====",
"== CHAPTER 2 ==",
"==== THE MYSTERIOUS PARCHMENT ====",
"== CHAPTER 3 ==",
"==== AN ASTOUNDING DISCOVERY ====",
"== CHAPTER 4 ==",
"==== WE START ON THE JOURNEY ====",
"== CHAPTER 5 ==",
"==== FIRST LESSONS IN CLIMBING ====",
"== CHAPTER 6 ==",
"==== OUR VOYAGE TO ICELAND ====",
"== CHAPTER 7 ==",
"==== CONVERSATION AND DISCOVERY ====",
"== CHAPTER 8 ==",
"==== THE EIDER-DOWN HUNTER&mdash;OFF AT LAST ====",
"== CHAPTER 9 ==",
"==== OUR START&mdash;WE MEET WITH ADVENTURES BY THE WAY ====",
"== CHAPTER 10 ==",
"==== TRAVELING IN ICELAND ====",
"== CHAPTER 11 ==",
"==== WE REACH MOUNT SNEFFELS&mdash;THE \"REYKIR\" ====",
"== CHAPTER 12 ==",
"==== THE ASCENT OF MOUNT SNEFFELS ====",
"== CHAPTER 13 ==",
"==== THE SHADOW OF SCARTARIS ====",
"== CHAPTER 14 ==",
"==== THE REAL JOURNEY COMMENCES ====",
"== CHAPTER 15 ==",
"==== WE CONTINUE OUR DESCENT ====",
"== CHAPTER 16 ==",
"==== THE EASTERN TUNNEL ====",
"== CHAPTER 17 ==",
"==== DEEPER AND DEEPER&mdash;THE COAL MINE ====",
"== CHAPTER 18 ==",
"==== THE WRONG ROAD! ====",
"== CHAPTER 19 ==",
"==== THE WESTERN GALLERY&mdash;A NEW ROUTE ====",
"== CHAPTER 20 ==",
"==== WATER, WHERE IS IT? A BITTER DISAPPOINTMENT ====",
"== CHAPTER 21 ==",
"==== UNDER THE OCEAN ====",
"== CHAPTER 22 ==",
"==== SUNDAY BELOW GROUND ====",
"== CHAPTER 23 ==",
"==== ALONE ====",
"== CHAPTER 24 ==",
"==== LOST! ====",
"== CHAPTER 25 ==",
"==== THE WHISPERING GALLERY ====",
"== CHAPTER 26 ==",
"==== A RAPID RECOVERY ====",
"== CHAPTER 27 ==",
"==== THE CENTRAL SEA ====",
"== CHAPTER 28 ==",
"==== LAUNCHING THE RAFT ====",
"== CHAPTER 29 ==",
"==== ON THE WATERS&mdash;A RAFT VOYAGE ====",
"== CHAPTER 30 ==",
"==== TERRIFIC SAURIAN COMBAT ====",
"== CHAPTER 31 ==",
"==== THE SEA MONSTER ====",
"== CHAPTER 32 ==",
"==== THE BATTLE OF THE ELEMENTS ====",
"== CHAPTER 33 ==",
"==== OUR ROUTE REVERSED ====",
"== CHAPTER 34 ==",
"==== A VOYAGE OF DISCOVERY ====",
"== CHAPTER 35 ==",
"==== DISCOVERY UPON DISCOVERY ====",
"== CHAPTER 36 ==",
"==== WHAT IS IT? ====",
"== CHAPTER 37 ==",
"==== THE MYSTERIOUS DAGGER ====",
"== CHAPTER 38 ==",
"==== NO OUTLET&mdash;BLASTING THE ROCK ====",
"== CHAPTER 39 ==",
"==== THE EXPLOSION AND ITS RESULTS ====",
"== CHAPTER 40 ==",
"==== THE APE GIGANS ====",
"== CHAPTER 41 ==",
"==== HUNGER ====",
"== CHAPTER 42 ==",
"==== THE VOLCANIC SHAFT ====",
"== CHAPTER 43 ==",
"==== DAYLIGHT AT LAST ====",
"== CHAPTER 44 ==",
"==== THE JOURNEY ENDED ====",
];
