var menulist=[
"=== With my back against a golden throne, I fought once again for Dejah Thoris. ===",
"= A PRINCESS OF MARS =",
"=== by ===",
"== Edgar Rice Burroughs ==",
"=== To My Son Jack ===",
"=== FOREWORD ===",
"=== To the Reader of this Work: ===",
"== CONTENTS ==",
"=== ILLUSTRATIONS ===",
"=== CHAPTER I ===",
"=== ON THE ARIZONA HILLS ===",
"=== CHAPTER II ===",
"=== THE ESCAPE OF THE DEAD ===",
"=== CHAPTER III ===",
"=== MY ADVENT ON MARS ===",
"=== CHAPTER IV ===",
"=== A PRISONER ===",
"=== CHAPTER V ===",
"=== I ELUDE MY WATCH DOG ===",
"=== CHAPTER VI ===",
"=== A FIGHT THAT WON FRIENDS ===",
"=== CHAPTER VII ===",
"=== CHILD-RAISING ON MARS ===",
"=== CHAPTER VIII ===",
"=== A FAIR CAPTIVE FROM THE SKY ===",
"=== CHAPTER IX ===",
"=== I LEARN THE LANGUAGE ===",
"=== CHAPTER X ===",
"=== CHAMPION AND CHIEF ===",
"=== CHAPTER XI ===",
"=== WITH DEJAH THORIS ===",
"=== CHAPTER XII ===",
"=== A PRISONER WITH POWER ===",
"=== CHAPTER XIII ===",
"=== LOVE-MAKING ON MARS ===",
"=== CHAPTER XIV ===",
"=== A DUEL TO THE DEATH ===",
"=== I sought out Dejah Thoris in the throng of departing chariots. ===",
"=== CHAPTER XV ===",
"=== SOLA TELLS ME HER STORY ===",
"=== CHAPTER XVI ===",
"=== WE PLAN ESCAPE ===",
"=== She drew upon the marble floor the first map of Barsoomian territory I had ever seen. ===",
"=== CHAPTER XVII ===",
"=== A COSTLY RECAPTURE ===",
"=== CHAPTER XVIII ===",
"=== CHAINED IN WARHOON ===",
"=== CHAPTER XIX ===",
"=== BATTLING IN THE ARENA ===",
"=== CHAPTER XX ===",
"=== IN THE ATMOSPHERE FACTORY ===",
"=== The old man sat and talked with me for hours. ===",
"=== CHAPTER XXI ===",
"=== AN AIR SCOUT FOR ZODANGA ===",
"=== CHAPTER XXII ===",
"=== I FIND DEJAH ===",
"=== CHAPTER XXIII ===",
"=== LOST IN THE SKY ===",
"=== CHAPTER XXIV ===",
"=== TARS TARKAS FINDS A FRIEND ===",
"=== CHAPTER XXV ===",
"=== THE LOOTING OF ZODANGA ===",
"=== CHAPTER XXVI ===",
"=== THROUGH CARNAGE TO JOY ===",
"=== CHAPTER XXVII ===",
"=== FROM JOY TO DEATH ===",
"=== CHAPTER XXVIII ===",
"=== AT THE ARIZONA CAVE ===",
];
