var menulist=[
"== The Project Gutenberg eBook of A Room with a View ==",
"= A Room With A View =",
"== By E. M. Forster ==",
"== CONTENTS ==",
"== PART ONE ==",
"== Chapter I The Bertolini ==",
"== Chapter II In Santa Croce with No Baedeker ==",
"== Chapter III Music, Violets, and the Letter “S” ==",
"== Chapter IV Fourth Chapter ==",
"== Chapter V Possibilities of a Pleasant Outing ==",
"== Chapter VI The Reverend Arthur Beebe, the Reverend Cuthbert Eager, Mr. Emerson, Mr. GeorgeEmerson, Miss Eleanor Lavish, Miss Charlotte Bartlett, and Miss LucyHoneychurch Drive Out in Carriages to See a View; Italians Drive Them. ==",
"== Chapter VII They Return ==",
"== PART TWO ==",
"== Chapter VIII Medieval ==",
"== Chapter IX Lucy As a Work of Art ==",
"== Chapter X Cecil as a Humourist ==",
"== Chapter XI In Mrs. Vyse’s Well-Appointed Flat ==",
"== Chapter XII Twelfth Chapter ==",
"== Chapter XIII How Miss Bartlett’s Boiler Was So Tiresome ==",
"== Chapter XIV How Lucy Faced the External Situation Bravely ==",
"== Chapter XV The Disaster Within ==",
"== Chapter XVI Lying to George ==",
"== Chapter XVII Lying to Cecil ==",
"== Chapter XVIII Lying to Mr. Beebe, Mrs. Honeychurch, Freddy, and The Servants ==",
"== Chapter XIX Lying to Mr. Emerson ==",
"== Chapter XX The End of the Middle Ages ==",
"== THE FULL PROJECT GUTENBERG LICENSE ==",
];
