var menulist=[
"== The Project Gutenberg eBook of Adventures of Huckleberry Finn ==",
"= ADVENTURES OF HUCKLEBERRY FINN =",
"=== (Tom Sawyer’s Comrade) ===",
"== By Mark Twain ==",
"== CONTENTS. ==",
"== ILLUSTRATIONS. ==",
"== HUCKLEBERRY FINN ==",
"== CHAPTER I. ==",
"== CHAPTER II. ==",
"== CHAPTER III. ==",
"== CHAPTER IV. ==",
"== CHAPTER V. ==",
"== CHAPTER VI. ==",
"== CHAPTER VII. ==",
"== CHAPTER VIII. ==",
"== CHAPTER IX. ==",
"== CHAPTER X. ==",
"== CHAPTER XI. ==",
"== CHAPTER XII. ==",
"== CHAPTER XIII. ==",
"== CHAPTER XIV. ==",
"== CHAPTER XV. ==",
"== CHAPTER XVI. ==",
"== CHAPTER XVII. ==",
"== CHAPTER XVIII. ==",
"== CHAPTER XIX. ==",
"== CHAPTER XX. ==",
"== CHAPTER XXI. ==",
"== CHAPTER XXII. ==",
"== CHAPTER XXIII. ==",
"== CHAPTER XXIV. ==",
"== CHAPTER XXV. ==",
"== CHAPTER XXVI. ==",
"== CHAPTER XXVII. ==",
"== CHAPTER XXVIII. ==",
"== CHAPTER XXIX. ==",
"== CHAPTER XXX. ==",
"== CHAPTER XXXI. ==",
"== CHAPTER XXXII. ==",
"== CHAPTER XXXIII. ==",
"== CHAPTER XXXIV. ==",
"== CHAPTER XXXV. ==",
"== CHAPTER XXXVI. ==",
"== CHAPTER XXXVII. ==",
"== CHAPTER XXXVIII. ==",
"== CHAPTER XXXIX. ==",
"== CHAPTER XL. ==",
"== CHAPTER XLI. ==",
"== CHAPTER XLII. ==",
"== CHAPTER THE LAST ==",
"== THE FULL PROJECT GUTENBERG LICENSE ==",
];
