var menulist=[
"== The Project Gutenberg eBook of Anne of Green Gables ==",
"= ANNE OF GREEN GABLES =",
"== By Lucy Maud Montgomery ==",
"== CONTENTS ==",
"== ANNE OF GREEN GABLES ==",
"== CHAPTER I. Mrs. Rachel Lynde is Surprised ==",
"== CHAPTER II. Matthew Cuthbert is surprised ==",
"== CHAPTER III. Marilla Cuthbert is Surprised ==",
"== CHAPTER IV. Morning at Green Gables ==",
"== CHAPTER V. Anne’s History ==",
"== CHAPTER VI. Marilla Makes Up Her Mind ==",
"== CHAPTER VII. Anne Says Her Prayers ==",
"== CHAPTER VIII. Anne’s Bringing-up Is Begun ==",
"== CHAPTER IX. Mrs. Rachel Lynde Is Properly Horrified ==",
"== CHAPTER X. Anne’s Apology ==",
"== CHAPTER XI. Anne’s Impressions of Sunday-School ==",
"== CHAPTER XII. A Solemn Vow and Promise ==",
"== CHAPTER XIII. The Delights of Anticipation ==",
"== CHAPTER XIV. Anne’s Confession ==",
"== CHAPTER XV. A Tempest in the School Teapot ==",
"== CHAPTER XVI. Diana Is Invited to Tea with Tragic Results ==",
"== CHAPTER XVII. A New Interest in Life ==",
"== CHAPTER XVIII. Anne to the Rescue ==",
"== CHAPTER XIX. A Concert a Catastrophe and a Confession ==",
"== CHAPTER XX. A Good Imagination Gone Wrong ==",
"== CHAPTER XXI. A New Departure in Flavorings ==",
"== CHAPTER XXII. Anne is Invited Out to Tea ==",
"== CHAPTER XXIII. Anne Comes to Grief in an Affair of Honor ==",
"== CHAPTER XXIV. Miss Stacy and Her Pupils Get Up a Concert ==",
"== CHAPTER XXV. Matthew Insists on Puffed Sleeves ==",
"== CHAPTER XXVI. The Story Club Is Formed ==",
"== CHAPTER XXVII. Vanity and Vexation of Spirit ==",
"== CHAPTER XXVIII. An Unfortunate Lily Maid ==",
"== CHAPTER XXIX. An Epoch in Anne’s Life ==",
"== CHAPTER XXX. The Queens Class Is Organized ==",
"== CHAPTER XXXI. Where the Brook and River Meet ==",
"== CHAPTER XXXII. The Pass List Is Out ==",
"== CHAPTER XXXIII. The Hotel Concert ==",
"== CHAPTER XXXIV. A Queen’s Girl ==",
"== CHAPTER XXXV. The Winter at Queen’s ==",
"== CHAPTER XXXVI. The Glory and the Dream ==",
"== CHAPTER XXXVII. The Reaper Whose Name Is Death ==",
"== CHAPTER XXXVIII. The Bend in the road ==",
"== THE FULL PROJECT GUTENBERG LICENSE ==",
];
