var menulist=[
"== The Project Gutenberg eBook of Ben-Hur: A tale of the Christ ==",
"= Ben-Hur =",
"=== A Tale of the Christ ===",
"== by Lew Wallace ==",
"== Contents ==",
"== BOOK FIRST ==",
"== CHAPTER I ==",
"== CHAPTER II ==",
"== CHAPTER III ==",
"== CHAPTER IV ==",
"== CHAPTER V ==",
"== CHAPTER VI ==",
"== CHAPTER VII ==",
"== CHAPTER VIII ==",
"== CHAPTER IX ==",
"== CHAPTER X. ==",
"== CHAPTER XI ==",
"== CHAPTER XII ==",
"== CHAPTER XIII ==",
"== CHAPTER XIV ==",
"== BOOK SECOND ==",
"== CHAPTER I ==",
"== CHAPTER II ==",
"== CHAPTER III ==",
"== CHAPTER IV ==",
"== CHAPTER V ==",
"== CHAPTER VI ==",
"== CHAPTER VII ==",
"== BOOK THIRD ==",
"== CHAPTER I ==",
"== CHAPTER II ==",
"== CHAPTER III ==",
"== CHAPTER IV ==",
"== CHAPTER V ==",
"== CHAPTER VI ==",
"== BOOK FOURTH ==",
"== CHAPTER I ==",
"== CHAPTER II ==",
"== CHAPTER III ==",
"== CHAPTER IV ==",
"== CHAPTER V ==",
"== CHAPTER VI ==",
"== CHAPTER VII ==",
"== CHAPTER VIII ==",
"== CHAPTER IX ==",
"== CHAPTER X ==",
"== CHAPTER XI ==",
"== CHAPTER XII ==",
"== CHAPTER XIII ==",
"== CHAPTER XIV ==",
"== CHAPTER XV ==",
"== CHAPTER XVI ==",
"== CHAPTER XVII ==",
"== BOOK FIFTH ==",
"== CHAPTER I ==",
"== CHAPTER II ==",
"== CHAPTER III ==",
"== CHAPTER IV ==",
"== CHAPTER V ==",
"== CHAPTER VI ==",
"== CHAPTER VII ==",
"== CHAPTER VIII ==",
"== CHAPTER IX ==",
"== CHAPTER X ==",
"== CHAPTER XI ==",
"== CHAPTER XII ==",
"== CHAPTER XIII ==",
"== CHAPTER XIV ==",
"== CHAPTER XV ==",
"== CHAPTER XVI ==",
"==== THORD THE NORTHMAN. ====",
"== BOOK SIXTH ==",
"== CHAPTER I ==",
"== CHAPTER II ==",
"== CHAPTER III ==",
"== CHAPTER IV ==",
"==== “THIS IS THE PROPERTY OF THE EMPEROR.” ====",
"== CHAPTER V ==",
"== CHAPTER VI ==",
"== BOOK SEVENTH ==",
"== CHAPTER I ==",
"== CHAPTER II ==",
"== CHAPTER III ==",
"== CHAPTER IV ==",
"== CHAPTER V ==",
"== BOOK EIGHTH ==",
"== CHAPTER I ==",
"== CHAPTER II ==",
"== CHAPTER III ==",
"== CHAPTER IV ==",
"== CHAPTER V ==",
"== CHAPTER VI ==",
"== CHAPTER VII ==",
"== CHAPTER VIII ==",
"== CHAPTER IX ==",
"== CHAPTER X ==",
"== THE FULL PROJECT GUTENBERG LICENSE ==",
];
