var menulist=[
"== The Project Gutenberg eBook of Crime and Punishment ==",
"=       CRIME AND PUNISHMENT     =",
"==       By Fyodor Dostoevsky     ==",
"===       Translated By Constance Garnett     ===",
"==       TRANSLATOR’S PREFACE     ==",
"==       CRIME AND PUNISHMENT     ==",
"==       PART I     ==",
"==       CHAPTER I     ==",
"==       CHAPTER II     ==",
"==       CHAPTER III     ==",
"==       CHAPTER IV     ==",
"==       CHAPTER V     ==",
"==       CHAPTER VI     ==",
"==       CHAPTER VII     ==",
"==       PART II     ==",
"==       CHAPTER I     ==",
"==       CHAPTER II     ==",
"==       CHAPTER III     ==",
"==       CHAPTER IV     ==",
"==       CHAPTER V     ==",
"==       CHAPTER VI     ==",
"==       CHAPTER VII     ==",
"==       PART III     ==",
"==       CHAPTER I     ==",
"==       CHAPTER II     ==",
"==       CHAPTER III     ==",
"==       CHAPTER IV     ==",
"==       CHAPTER V     ==",
"==       CHAPTER VI     ==",
"==       PART IV     ==",
"==       CHAPTER I     ==",
"==       CHAPTER II     ==",
"==       CHAPTER III     ==",
"==       CHAPTER IV     ==",
"==       CHAPTER V     ==",
"==       CHAPTER VI     ==",
"==       PART V     ==",
"==       CHAPTER I     ==",
"==       CHAPTER II     ==",
"==       CHAPTER III     ==",
"==       CHAPTER IV     ==",
"==       CHAPTER V     ==",
"==       PART VI     ==",
"==       CHAPTER I     ==",
"==       CHAPTER II     ==",
"==       CHAPTER III     ==",
"==       CHAPTER IV     ==",
"==       CHAPTER V     ==",
"==       CHAPTER VI     ==",
"==       CHAPTER VII     ==",
"==       CHAPTER VIII     ==",
"==       EPILOGUE     ==",
"===       I     ===",
"===       II     ===",
"== THE FULL PROJECT GUTENBERG LICENSE ==",
];
