var menulist=[
"== The Project Gutenberg eBook of Down and Out in the Magic Kingdom ==",
"= Down and Out  in the  Magic Kingdom =",
"== Cory Doctorow ==",
"= Table of Contents =",
"= Blurbs: =",
"= A note about this book: =",
"= PROLOGUE =",
"= CHAPTER 1 =",
"= CHAPTER 2 =",
"= CHAPTER 3 =",
"= CHAPTER 4 =",
"= CHAPTER 5 =",
"= CHAPTER 6 =",
"= CHAPTER 7 =",
"= CHAPTER 8 =",
"= CHAPTER 9 =",
"= CHAPTER 10 =",
"= Acknowledgements: =",
"= About the author: =",
"= Other books by Cory Doctorow: =",
"== THE FULL PROJECT GUTENBERG LICENSE ==",
];
