var menulist=[
"== The Project Gutenberg eBook of Essays of Michel de Montaigne &mdash; Complete ==",
"= ESSAYS OF   MICHEL DE MONTAIGNE =",
"=== Translated by Charles Cotton   Edited by William Carew Hazlitt ===",
"=== 1877 ===",
"== PREFACE ==",
"== THE LIFE OF MONTAIGNE ==",
"== I.&mdash;&mdash;To Monsieur de MONTAIGNE ==",
"== II.&mdash;&mdash;To Monseigneur, Monseigneur de MONTAIGNE. ==",
"== III.&mdash;&mdash;To Monsieur, Monsieur de LANSAC, ==",
"== IV.&mdash;&mdash;To Monsieur, Monsieur de MESMES, Lord of Roissy and      Malassize, Privy ==",
"== V.&mdash;&mdash;To Monsieur, Monsieur de L’HOSPITAL, Chancellor of      France ==",
"== VI.&mdash;&mdash;To Monsieur, Monsieur de Folx, Privy Councillor, and      Ambassador of His Majesty to the Signory of Venice. ==",
"=== &mdash;[ Printed before the ‘Vers Francois’ of Etienne de la      Boetie, 8vo, Paris, 1572.] ===",
"== VII.&mdash;&mdash;To Mademoiselle de MONTAIGNE, my Wife. ==",
"== VIII.&mdash;&mdash;To Monsieur DUPUY, ==",
"== IX.&mdash;&mdash;To the Jurats of Bordeaux. ==",
"== X.&mdash;&mdash;To the same. ==",
"=== &mdash;[The original is among the archives of Toulouse.] ===",
"== XI.&mdash;&mdash;To the same. ==",
"== XII. ==",
"== XIII.&mdash;&mdash;To Mademoiselle PAULMIER. ==",
"== XIV.&mdash;&mdash;To the KING, HENRY IV. ==",
"== XV.&mdash;&mdash;To the same. ==",
"== XVI.&mdash;&mdash;To the Governor of Guienne. ==",
"== ESSAYS OF MICHEL DE MONTAIGNE ==",
"=== Translated by Charles Cotton ===",
"=== Edited by William Carew Hazlitt ===",
"=== 1877 ===",
"== CHAPTER I&mdash;&mdash;THAT MEN BY VARIOUS WAYS ARRIVE AT THE SAME END. ==",
"== CHAPTER II&mdash;&mdash;OF SORROW ==",
"== CHAPTER III&mdash;&mdash;THAT OUR AFFECTIONS CARRY THEMSELVES BEYOND US. ==",
"== CHAPTER IV&mdash;&mdash;THAT THE SOUL EXPENDS ITS PASSIONS UPON FALSE      OBJECTS, WHERE THE TRUE ARE WANTING ==",
"== CHAPTER V&mdash;&mdash;WHETHER THE GOVERNOR OF A PLACE BESIEGED OUGHT      HIMSELF TO GO OUT TO PARLEY ==",
"== CHAPTER VI&mdash;&mdash;THAT THE HOUR OF PARLEY DANGEROUS ==",
"== CHAPTER VII&mdash;&mdash;THAT THE INTENTION IS JUDGE OF OUR ACTIONS ==",
"== CHAPTER VIII&mdash;&mdash;OF IDLENESS ==",
"== CHAPTER IX&mdash;&mdash;OF LIARS ==",
"== CHAPTER X&mdash;&mdash;OF QUICK OR SLOW SPEECH ==",
"== CHAPTER XI&mdash;&mdash;OF PROGNOSTICATIONS ==",
"== CHAPTER XII&mdash;&mdash;OF CONSTANCY ==",
"== CHAPTER XIII&mdash;&mdash;THE CEREMONY OF THE INTERVIEW OF PRINCES ==",
"== CHAPTER XIV&mdash;&mdash;THAT MEN ARE JUSTLY PUNISHED FOR BEING OBSTINATE      IN THE DEFENCE OF A FORT THAT IS NOT IN REASON TO BE DEFENDED ==",
"== CHAPTER XV&mdash;&mdash;OF THE PUNISHMENT OF COWARDICE ==",
"== CHAPTER XVI&mdash;&mdash;A PROCEEDING OF SOME AMBASSADORS ==",
"== CHAPTER XVII&mdash;&mdash;OF FEAR ==",
"== CHAPTER XVIII&mdash;&mdash;THAT MEN ARE NOT TO JUDGE OF OUR HAPPINESS TILL      AFTER DEATH. ==",
"== CHAPTER XIX&mdash;&mdash;THAT TO STUDY PHILOSOPY IS TO LEARN TO DIE ==",
"== CHAPTER XX&mdash;&mdash;OF THE FORCE OF IMAGINATION ==",
"== CHAPTER XXI&mdash;&mdash;THAT THE PROFIT OF ONE MAN IS THE DAMAGE OF      ANOTHER ==",
"== CHAPTER XXII&mdash;&mdash;OF CUSTOM, AND THAT WE SHOULD NOT EASILY CHANGE      A LAW RECEIVED ==",
"== CHAPTER XXIII&mdash;&mdash;VARIOUS EVENTS FROM THE SAME COUNSEL ==",
"== CHAPTER XXIV&mdash;&mdash;OF PEDANTRY ==",
"== CHAPTER XXV&mdash;&mdash;OF THE EDUCATION OF CHILDREN ==",
"=== TO MADAME DIANE DE FOIX, Comtesse de Gurson ===",
"== CHAPTER XXVI&mdash;&mdash;THAT IT IS FOLLY TO MEASURE TRUTH AND ERROR BY      OUR OWN CAPACITY ==",
"== CHAPTER XXVII&mdash;&mdash;OF FRIENDSHIP ==",
"== CHAPTER XXVIII&mdash;&mdash;NINE AND TWENTY SONNETS OF ESTIENNE DE LA      BOITIE ==",
"=== TO MADAME DE GRAMMONT, COMTESSE DE GUISSEN. ===",
"== CHAPTER XXIX&mdash;&mdash;OF MODERATION ==",
"== CHAPTER XXX&mdash;&mdash;OF CANNIBALS ==",
"== CHAPTER XXXI&mdash;&mdash;THAT A MAN IS SOBERLY TO JUDGE OF THE DIVINE      ORDINANCES ==",
"== CHAPTER XXXII&mdash;&mdash;THAT WE ARE TO AVOID PLEASURES, EVEN AT THE      EXPENSE OF LIFE ==",
"== CHAPTER XXXIII&mdash;&mdash;THAT FORTUNE IS OFTEN-TIMES OBSERVED TO ACT BY      THE RULE OF REASON ==",
"=== The inconstancy and various motions of Fortune ===",
"== CHAPTER XXXIV&mdash;&mdash;OF ONE DEFECT IN OUR GOVERNMENT ==",
"== CHAPTER XXXV&mdash;&mdash;OF THE CUSTOM OF WEARING CLOTHES ==",
"== CHAPTER XXXVI&mdash;&mdash;OF CATO THE YOUNGER ==",
"== CHAPTER XXXVII&mdash;&mdash;THAT WE LAUGH AND CRY FOR THE SAME THING ==",
"== CHAPTER XXXVIII&mdash;&mdash;OF SOLITUDE ==",
"== CHAPTER XXXIX&mdash;&mdash;A CONSIDERATION UPON CICERO ==",
"== CHAPTER XL&mdash;&mdash;THAT THE RELISH FOR GOOD AND EVIL DEPENDS IN GREAT      MEASURE UPON THE OPINION WE HAVE OF THEM ==",
"== CHAPTER XLI&mdash;&mdash;NOT TO COMMUNICATE A MAN’S HONOUR ==",
"== CHAPTER XLII&mdash;&mdash;OF THE INEQUALITY AMOUNGST US. ==",
"== CHAPTER XLIII&mdash;&mdash;OF SUMPTUARY LAWS ==",
"== CHAPTER XLIV&mdash;&mdash;OF SLEEP ==",
"== CHAPTER XLV&mdash;&mdash;OF THE BATTLE OF DREUX ==",
"== CHAPTER XLVI&mdash;&mdash;OF NAMES ==",
"== CHAPTER XLVII&mdash;&mdash;OF THE UNCERTAINTY OF OUR JUDGMENT ==",
"=== Well says this verse: ===",
"== CHAPTER XLVIII&mdash;&mdash;OF WAR HORSES, OR DESTRIERS ==",
"== CHAPTER XLIX&mdash;&mdash;OF ANCIENT CUSTOMS ==",
"== CHAPTER L&mdash;&mdash;OF DEMOCRITUS AND HERACLITUS ==",
"== CHAPTER LI&mdash;&mdash;OF THE VANITY OF WORDS ==",
"== CHAPTER LII&mdash;&mdash;OF THE PARSIMONY OF THE ANCIENTS ==",
"== CHAPTER LIII&mdash;&mdash;OF A SAYING OF CAESAR ==",
"== CHAPTER LIV&mdash;&mdash;OF VAIN SUBTLETIES ==",
"== CHAPTER LV&mdash;&mdash;OF SMELLS ==",
"== CHAPTER LVI&mdash;&mdash;OF PRAYERS ==",
"== CHAPTER LVII&mdash;&mdash;OF AGE ==",
"== BOOK THE SECOND ==",
"== CHAPTER I&mdash;&mdash;OF THE INCONSTANCY OF OUR ACTIONS ==",
"== CHAPTER II&mdash;&mdash;OF DRUNKENNESS ==",
"== CHAPTER III&mdash;&mdash;A CUSTOM OF THE ISLE OF CEA ==",
"== CHAPTER IV&mdash;&mdash;TO-MORROW’S A NEW DAY ==",
"== CHAPTER V&mdash;&mdash;OF CONSCIENCE ==",
"== CHAPTER VI&mdash;&mdash;USE MAKES PERFECT ==",
"== CHAPTER VII&mdash;&mdash;OF RECOMPENSES OF HONOUR ==",
"== CHAPTER VIII&mdash;&mdash;OF THE AFFECTION OF FATHERS TO THEIR CHILDREN ==",
"=== To Madame D’Estissac. ===",
"== CHAPTER IX&mdash;&mdash;OF THE ARMS OF THE PARTHIANS ==",
"== CHAPTER X&mdash;&mdash;OF BOOKS ==",
"== CHAPTER XI&mdash;&mdash;OF CRUELTY ==",
"== CHAPTER XII. &mdash; APOLOGY FOR RAIMOND SEBOND. ==",
"== CHAPTER XIII&mdash;&mdash;OF JUDGING OF THE DEATH OF ANOTHER ==",
"== CHAPTER XIV&mdash;&mdash;THAT OUR MIND HINDERS ITSELF ==",
"== CHAPTER XV&mdash;&mdash;THAT OUR DESIRES ARE AUGMENTED BY DIFFICULTY ==",
"== CHAPTER XVI&mdash;&mdash;OF GLORY ==",
"== CHAPTER XVII&mdash;&mdash;OF PRESUMPTION ==",
"== CHAPTER XVIII&mdash;&mdash;OF GIVING THE LIE ==",
"== CHAPTER XIX&mdash;&mdash;OF LIBERTY OF CONSCIENCE ==",
"== CHAPTER XX&mdash;&mdash;THAT WE TASTE NOTHING PURE ==",
"== CHAPTER XXI&mdash;&mdash;AGAINST IDLENESS ==",
"== CHAPTER XXII&mdash;&mdash;OF POSTING ==",
"== CHAPTER XXIII&mdash;&mdash;OF ILL MEANS EMPLOYED TO A GOOD END ==",
"== CHAPTER XXIV&mdash;&mdash;OF THE ROMAN GRANDEUR ==",
"== CHAPTER XXV&mdash;&mdash;NOT TO COUNTERFEIT BEING SICK ==",
"== CHAPTER XXVI&mdash;&mdash;OF THUMBS ==",
"== CHAPTER XXVII&mdash;&mdash;COWARDICE THE MOTHER OF CRUELTY ==",
"== CHAPTER XXVIII&mdash;&mdash;ALL THINGS HAVE THEIR SEASON ==",
"== CHAPTER XXIX&mdash;&mdash;OF VIRTUE ==",
"== CHAPTER XXX&mdash;&mdash;OF A MONSTROUS CHILD ==",
"== CHAPTER XXXI&mdash;&mdash;OF ANGER ==",
"== CHAPTER XXXII&mdash;&mdash;DEFENCE OF SENECA AND PLUTARCH ==",
"== CHAPTER XXXIII&mdash;&mdash;THE STORY OF SPURINA ==",
"== CHAPTER XXXIV&mdash;&mdash;OBSERVATION ON THE MEANS TO CARRY ON A WAR      ACCORDING TO JULIUS CAESAR ==",
"== CHAPTER XXXV&mdash;&mdash;OF THREE GOOD WOMEN ==",
"== CHAPTER XXXVI&mdash;&mdash;OF THE MOST EXCELLENT MEN ==",
"== CHAPTER XXXVII&mdash;&mdash;OF THE RESEMBLANCE OF CHILDREN TO THEIR      FATHERS ==",
"== BOOK THE THIRD ==",
"== CHAPTER I&mdash;&mdash;OF PROFIT AND HONESTY ==",
"== CHAPTER II&mdash;&mdash;OF REPENTANCE ==",
"== CHAPTER III&mdash;&mdash;OF THREE COMMERCES ==",
"== CHAPTER IV&mdash;&mdash;OF DIVERSION ==",
"== CHAPTER V&mdash;&mdash;UPON SOME VERSES OF VIRGIL ==",
"== CHAPTER VI&mdash;&mdash;OF COACHES ==",
"== CHAPTER VII&mdash;&mdash;OF THE INCONVENIENCE OF GREATNESS ==",
"== CHAPTER VIII&mdash;&mdash;OF THE ART OF CONFERENCE ==",
"== CHAPTER IX&mdash;&mdash;OF VANITY ==",
"== CHAPTER X&mdash;&mdash;OF MANAGING THE WILL ==",
"== CHAPTER XI&mdash;&mdash;OF CRIPPLES ==",
"== CHAPTER XII&mdash;&mdash;OF PHYSIOGNOMY ==",
"== CHAPTER XIII&mdash;&mdash;OF EXPERIENCE ==",
"== APOLOGY: ==",
"== PROJECT GUTENBERG EDITOR’S BOOKMARKS: ==",
"== THE FULL PROJECT GUTENBERG LICENSE ==",
];
