var menulist=[
"== The Project Gutenberg eBook of History of Tom Jones, a Foundling ==",
"= THE HISTORY OF TOM JONES, A FOUNDLING =",
"== By Henry Fielding ==",
"== To the Honourable ==",
"=== GEORGE LYTTLETON, ESQ; ===",
"=== HENRY FIELDING. ===",
"= THE HISTORY OF TOM JONES, A FOUNDLING. =",
"== BOOK I. &mdash; CONTAINING AS MUCH OF THE BIRTH OF THE FOUNDLING AS IS      NECESSARY OR PROPER TO ACQUAINT THE READER WITH IN THE BEGINNING OF THIS      HISTORY. ==",
"== Chapter i. &mdash; The introduction to the work, or bill of fare to the      feast. ==",
"== Chapter ii. &mdash; A short description of squire Allworthy, and a fuller      account of Miss Bridget Allworthy, his sister. ==",
"== Chapter iii. &mdash; An odd accident which befel Mr Allworthy at his      return home. The decent behaviour of Mrs Deborah Wilkins, with some proper      animadversions on bastards. ==",
"== Chapter iv. &mdash; The reader's neck brought into danger by a      description; his escape; and the great condescension of Miss Bridget      Allworthy. ==",
"== Chapter v. &mdash; Containing a few common matters, with a very uncommon      observation upon them. ==",
"== Chapter vi. &mdash; Mrs Deborah is introduced into the parish with a      simile. A short account of Jenny Jones, with the difficulties and      discouragements which may attend young women in the pursuit of learning. ==",
"== Chapter vii. &mdash; Containing such grave matter, that the reader cannot      laugh once through the whole chapter, unless peradventure he should laugh      at the author. ==",
"== Chapter viii. &mdash; A dialogue between Mesdames Bridget and Deborah;      containing more amusement, but less instruction, than the former. ==",
"== Chapter ix. &mdash; Containing matters which will surprize the reader. ==",
"== Chapter x. &mdash; The hospitality of Allworthy; with a short sketch of      the characters of two brothers, a doctor and a captain, who were      entertained by that gentleman. ==",
"== Chapter xi. &mdash; Containing many rules, and some examples, concerning      falling in love: descriptions of beauty, and other more prudential      inducements to matrimony. ==",
"== Chapter xii. &mdash; Containing what the reader may, perhaps, expect to      find in it. ==",
"== Chapter xiii. &mdash; Which concludes the first book; with an instance of      ingratitude, which, we hope, will appear unnatural. ==",
"== BOOK II. &mdash; CONTAINING SCENES OF MATRIMONIAL FELICITY IN DIFFERENT      DEGREES OF LIFE; AND VARIOUS OTHER TRANSACTIONS DURING THE FIRST TWO YEARS      AFTER THE MARRIAGE BETWEEN CAPTAIN BLIFIL AND MISS BRIDGET ALLWORTHY. ==",
"== Chapter i. &mdash; Showing what kind of a history this is; what it is      like, and what it is not like. ==",
"== Chapter ii. &mdash; Religious cautions against showing too much favour to      bastards; and a great discovery made by Mrs Deborah Wilkins. ==",
"== Chapter iii. &mdash; The description of a domestic government founded upon      rules directly contrary to those of Aristotle. ==",
"== Chapter iv. &mdash; Containing one of the most bloody battles, or rather      duels, that were ever recorded in domestic history. ==",
"== Chapter v. &mdash; Containing much matter to exercise the judgment and      reflection of the reader. ==",
"== Chapter vi. &mdash; The trial of Partridge, the schoolmaster, for      incontinency; the evidence of his wife; a short reflection on the wisdom      of our law; with other grave matters, which those will like best who      understand them most. ==",
"== Chapter vii. &mdash; A short sketch of that felicity which prudent couples      may extract from hatred: with a short apology for those people who      overlook imperfections in their friends. ==",
"== Chapter viii. &mdash; A receipt to regain the lost affections of a wife,      which hath never been known to fail in the most desperate cases. ==",
"== Chapter ix. &mdash; A proof of the infallibility of the foregoing receipt,      in the lamentations of the widow; with other suitable decorations of      death, such as physicians, &amp;c., and an epitaph in the true stile. ==",
"== BOOK III. &mdash; CONTAINING THE MOST MEMORABLE TRANSACTIONS WHICH PASSED      IN THE FAMILY OF MR ALLWORTHY, FROM THE TIME WHEN TOMMY JONES ARRIVED AT      THE AGE OF FOURTEEN, TILL HE ATTAINED THE AGE OF NINETEEN. IN THIS BOOK ==",
"=== THE READER MAY PICK UP SOME HINTS CONCERNING THE EDUCATION OF CHILDREN. ===",
"== Chapter i. &mdash; Containing little or nothing. ==",
"== Chapter ii. &mdash; The heroe of this great history appears with very bad      omens. A little tale of so LOW a kind that some may think it not worth      their notice. A word or two concerning a squire, and more relating to a      gamekeeper and a schoolmaster. ==",
"== Chapter iii. &mdash; The character of Mr Square the philosopher, and of Mr      Thwackum the divine; with a dispute concerning&mdash;&mdash; ==",
"== Chapter iv. &mdash; Containing a necessary apology for the author; and a      childish incident, which perhaps requires an apology likewise. ==",
"== Chapter v. &mdash; The opinions of the divine and the philosopher      concerning the two boys; with some reasons for their opinions, and other      matters. ==",
"== Chapter vi. &mdash; Containing a better reason still for the      before-mentioned opinions. ==",
"== Chapter vii. &mdash; In which the author himself makes his appearance on      the stage. ==",
"== Chapter viii. &mdash; A childish incident, in which, however, is seen a      good-natured disposition in Tom Jones. ==",
"== Chapter ix. &mdash; Containing an incident of a more heinous kind, with      the comments of Thwackum and Square. ==",
"== Chapter x. &mdash; In which Master Blifil and Jones appear in different      lights. ==",
"== BOOK IV. &mdash; CONTAINING THE TIME OF A YEAR. ==",
"== Chapter i. &mdash; Containing five pages of paper. ==",
"== Chapter ii. &mdash; A short hint of what we can do in the sublime, and a      description of Miss Sophia Western. ==",
"== Chapter iii. &mdash; Wherein the history goes back to commemorate a      trifling incident that happened some years since; but which, trifling as      it was, had some future consequences. ==",
"== Chapter iv. &mdash; Containing such very deep and grave matters, that some      readers, perhaps, may not relish it. ==",
"== Chapter v. &mdash; Containing matter accommodated to every taste. ==",
"== Chapter vi. &mdash; An apology for the insensibility of Mr Jones to all      the charms of the lovely Sophia; in which possibly we may, in a      considerable degree, lower his character in the estimation of those men of      wit and gallantry who approve the heroes in most of our modern comedies. ==",
"== Chapter vii. &mdash; Being the shortest chapter in this book. ==",
"== Chapter viii. &mdash; A battle sung by the muse in the Homerican style,      and which none but the classical reader can taste. ==",
"== Chapter ix. &mdash; Containing matter of no very peaceable colour. ==",
"== Chapter x. &mdash; A story told by Mr Supple, the curate. The penetration      of Squire Western. His great love for his daughter, and the return to it      made by her. ==",
"== Chapter xi. &mdash; The narrow escape of Molly Seagrim, with some      observations for which we have been forced to dive pretty deep into      nature. ==",
"== Chapter xii. &mdash; Containing much clearer matters; but which flowed      from the same fountain with those in the preceding chapter. ==",
"== Chapter xiii. &mdash; A dreadful accident which befel Sophia. The gallant      behaviour of Jones, and the more dreadful consequence of that behaviour to      the young lady; with a short digression in favour of the female sex.      &mdash; ==",
"== Chapter xiv. &mdash; The arrival of a surgeon.&mdash;His operations, and a      long dialogue between Sophia and her maid. ==",
"== BOOK V. &mdash; CONTAINING A PORTION OF TIME SOMEWHAT LONGER THAN HALF A      YEAR. ==",
"== Chapter i. &mdash; Of the SERIOUS in writing, and for what purpose it is      introduced. ==",
"== Chapter ii. &mdash; In which Mr Jones receives many friendly visits during      his confinement; with some fine touches of the passion of love, scarce      visible to the naked eye. ==",
"== Chapter iii. &mdash; Which all who have no heart will think to contain      much ado about nothing. ==",
"== Chapter iv. &mdash; A little chapter, in which is contained a little      incident. ==",
"== Chapter v. &mdash; A very long chapter, containing a very great incident. ==",
"== Chapter vi. &mdash; By comparing which with the former, the reader may      possibly correct some abuse which he hath formerly been guilty of in the      application of the word love. ==",
"== Chapter vii. &mdash; In which Mr Allworthy appears on a sick-bed. ==",
"== Chapter viii. &mdash; Containing matter rather natural than pleasing. ==",
"== Chapter ix. &mdash; Which, among other things, may serve as a comment on      that saying of Aeschines, that “drunkenness shows the mind of a man,      as a mirrour reflects his person.” ==",
"== Chapter x. &mdash; Showing the truth of many observations of Ovid, and of      other more grave writers, who have proved beyond contradiction, that wine      is often the forerunner of incontinency. ==",
"== Chapter xi. &mdash; In which a simile in Mr Pope's period of a mile      introduces as bloody a battle as can possibly be fought without the      assistance of steel or cold iron. ==",
"== Chapter xii. &mdash; In which is seen a more moving spectacle than all the      blood in the bodies of Thwackum and Blifil, and of twenty other such, is      capable of producing. ==",
"== BOOK VI. &mdash; CONTAINING ABOUT THREE WEEKS. ==",
"== Chapter i. &mdash; Of love. ==",
"== Chapter ii. &mdash; The character of Mrs Western. Her great learning and      knowledge of the world, and an instance of the deep penetration which she      derived from those advantages. ==",
"== Chapter iii. &mdash; Containing two defiances to the critics. ==",
"== Chapter iv. &mdash; Containing sundry curious matters. ==",
"== Chapter v. &mdash; In which is related what passed between Sophia and her      aunt. ==",
"== Chapter vi. &mdash; Containing a dialogue between Sophia and Mrs Honour,      which may a little relieve those tender affections which the foregoing      scene may have raised in the mind of a good-natured reader. ==",
"== Chapter vii. &mdash; A picture of formal courtship in miniature, as it      always ought to be drawn, and a scene of a tenderer kind painted at full      length. ==",
"== Chapter viii. &mdash; The meeting between Jones and Sophia. ==",
"== Chapter ix. &mdash; Being of a much more tempestuous kind than the former. ==",
"== Chapter x. &mdash; In which Mr Western visits Mr Allworthy. ==",
"== Chapter xi. &mdash; A short chapter; but which contains sufficient matter      to affect the good-natured reader. ==",
"== Chapter xii. &mdash; Containing love-letters, &amp;c. ==",
"== Chapter xiii. &mdash; The behaviour of Sophia on the present occasion;      which none of her sex will blame, who are capable of behaving in the same      manner. And the discussion of a knotty point in the court of conscience. ==",
"== Chapter xiv. &mdash; A short chapter, containing a short dialogue between      Squire Western and his sister. ==",
"== BOOK VII. &mdash; CONTAINING THREE DAYS. ==",
"== Chapter i. &mdash; A comparison between the world and the stage. ==",
"== Chapter ii. &mdash; Containing a conversation which Mr Jones had with      himself. ==",
"== Chapter iii. &mdash; Containing several dialogues. ==",
"== Chapter iv. &mdash; A picture of a country gentlewoman taken from the      life. ==",
"== Chapter v. &mdash; The generous behaviour of Sophia towards her aunt. ==",
"== Chapter vi. &mdash; Containing great variety of matter. ==",
"== Chapter vii. &mdash; A strange resolution of Sophia, and a more strange      stratagem of Mrs Honour. ==",
"== Chapter viii. &mdash; Containing scenes of altercation, of no very      uncommon kind. ==",
"== Chapter ix. &mdash; The wise demeanour of Mr Western in the character of a      magistrate. A hint to justices of peace, concerning the necessary      qualifications of a clerk; with extraordinary instances of paternal      madness and ==",
"== Chapter x. &mdash; Containing several matters, natural enough perhaps, but      low. ==",
"== Chapter xi. &mdash; The adventure of a company of soldiers. ==",
"== Chapter xii. &mdash; The adventure of a company of officers. ==",
"== Chapter xiii. &mdash; Containing the great address of the landlady, the      great learning of a surgeon, and the solid skill in casuistry of the      worthy lieutenant. ==",
"== Chapter xiv. &mdash; A most dreadful chapter indeed; and which few readers      ought to venture upon in an evening, especially when alone. ==",
"== Chapter xv. &mdash; The conclusion of the foregoing adventure. ==",
"== BOOK VIII. &mdash; CONTAINING ABOUT TWO DAYS. ==",
"== Chapter i. &mdash; A wonderful long chapter concerning the marvellous;      being much the longest of all our introductory chapters. ==",
"== Chapter ii. &mdash; In which the landlady pays a visit to Mr Jones. ==",
"== Chapter iii. &mdash; In which the surgeon makes his second appearance. ==",
"== Chapter iv. &mdash; In which is introduced one of the pleasantest barbers      that was ever recorded in history, the barber of Bagdad, or he in Don      Quixote, not excepted. ==",
"== Chapter v. &mdash; A dialogue between Mr Jones and the barber. ==",
"== Chapter vi. &mdash; In which more of the talents of Mr Benjamin will      appear, as well as who this extraordinary person was. ==",
"== Chapter vii. &mdash; Containing better reasons than any which have yet      appeared for the conduct of Partridge; an apology for the weakness of      Jones; and some further anecdotes concerning my landlady. ==",
"== Chapter viii. &mdash; Jones arrives at Gloucester, and goes to the Bell;      the character of that house, and of a petty-fogger which he there meets      with. ==",
"== Chapter ix. &mdash; Containing several dialogues between Jones and      Partridge, concerning love, cold, hunger, and other matters; with the      lucky and narrow escape of Partridge, as he was on the very brink of      making a fatal ==",
"== Chapter x. &mdash; In which our travellers meet with a very extraordinary      adventure. ==",
"== Chapter xi. &mdash; In which the Man of the Hill begins to relate his      history. ==",
"== Chapter xii. &mdash; In which the Man of the Hill continues his history. ==",
"== Chapter xiii. &mdash; In which the foregoing story is farther continued. ==",
"== Chapter xiv. &mdash; In which the Man of the Hill concludes his history. ==",
"== Chapter xv. &mdash; A brief history of Europe; and a curious discourse      between Mr Jones and the Man of the Hill. ==",
"== BOOK IX. &mdash; CONTAINING TWELVE HOURS. ==",
"== Chapter i. &mdash; Of those who lawfully may, and of those who may not,      write such histories as this. ==",
"== Chapter ii. &mdash; Containing a very surprizing adventure indeed, which      Mr Jones met with in his walk with the Man of the Hill. ==",
"== Chapter iii. &mdash; The arrival of Mr Jones with his lady at the inn;      with a very full description of the battle of Upton. ==",
"== Chapter iv. &mdash; In which the arrival of a man of war puts a final end      to hostilities, and causes the conclusion of a firm and lasting peace      between all parties. ==",
"== Chapter v. &mdash; An apology for all heroes who have good stomachs, with      a description of a battle of the amorous kind. ==",
"== Chapter vi. &mdash; A friendly conversation in the kitchen, which had a      very common, though not very friendly, conclusion. ==",
"== Chapter vii. &mdash; Containing a fuller account of Mrs Waters, and by      what means she came into that distressful situation from which she was      rescued by Jones. ==",
"== BOOK X. &mdash; IN WHICH THE HISTORY GOES FORWARD ABOUT TWELVE HOURS. ==",
"== Chapter i. &mdash; Containing instructions very necessary to be perused by      modern critics. ==",
"== Chapter ii. &mdash; Containing the arrival of an Irish gentleman, with      very extraordinary adventures which ensued at the inn. ==",
"== Chapter iii. &mdash; A dialogue between the landlady and Susan the      chamber-maid, proper to be read by all inn-keepers and their servants;      with the arrival, and affable behaviour of a beautiful young lady; which      may teach ==",
"== Chapter iv. &mdash; Containing infallible nostrums for procuring universal      disesteem and hatred. ==",
"== Chapter v. &mdash; Showing who the amiable lady, and her unamiable maid,      were. ==",
"== Chapter vi. &mdash; Containing, among other things, the ingenuity of      Partridge, the madness of Jones, and the folly of Fitzpatrick. ==",
"== Chapter vii. &mdash; In which are concluded the adventures that happened      at the inn at Upton. ==",
"== Chapter viii. &mdash; In which the history goes backward. ==",
"== Chapter ix. &mdash; The escape of Sophia. ==",
"== BOOK XI. &mdash; CONTAINING ABOUT THREE DAYS. ==",
"== Chapter i. &mdash; A crust for the critics. ==",
"== Chapter ii. &mdash; The adventures which Sophia met with after her leaving      Upton. ==",
"== Chapter iii. &mdash; A very short chapter, in which however is a sun, a      moon, a star, and an angel. ==",
"== Chapter iv. &mdash; The history of Mrs Fitzpatrick. ==",
"== Chapter v. &mdash; In which the history of Mrs Fitzpatrick is continued. ==",
"== Chapter vi. &mdash; In which the mistake of the landlord throws Sophia      into a dreadful consternation. ==",
"== Chapter vii. &mdash; In which Mrs Fitzpatrick concludes her history. ==",
"== Chapter viii. &mdash; A dreadful alarm in the inn, with the arrival of an      unexpected friend of Mrs Fitzpatrick. ==",
"== Chapter ix. &mdash; The morning introduced in some pretty writing. A      stagecoach. The civility of chambermaids. The heroic temper of Sophia. Her      generosity. The return to it. The departure of the company, and their ==",
"== Chapter x. &mdash; Containing a hint or two concerning virtue, and a few      more concerning suspicion. ==",
"== BOOK XII. &mdash; CONTAINING THE SAME INDIVIDUAL TIME WITH THE FORMER. ==",
"== Chapter i. &mdash; Showing what is to be deemed plagiarism in a modern      author, and what is to be considered as lawful prize. ==",
"== Chapter ii. &mdash; In which, though the squire doth not find his      daughter, something is found which puts an end to his pursuit. ==",
"== Chapter iii. &mdash; The departure of Jones from Upton, with what passed      between him and Partridge on the road. ==",
"== Chapter iv. &mdash; The adventure of a beggar-man. ==",
"== Chapter v. &mdash; Containing more adventures which Mr Jones and his      companion met on the road. ==",
"== Chapter vi. &mdash; From which it may be inferred that the best things are      liable to be misunderstood and misinterpreted. ==",
"== Chapter vii. &mdash; Containing a remark or two of our own and many more      of the good company assembled in the kitchen. ==",
"== Chapter viii. &mdash; In which fortune seems to have been in a better      humour with Jones than we have hitherto seen her. ==",
"== Chapter ix. &mdash; Containing little more than a few odd observations. ==",
"== Chapter x. &mdash; In which Mr Jones and Mr Dowling drink a bottle      together. ==",
"== Chapter xi. &mdash; The disasters which befel Jones on his departure for      Coventry; with the sage remarks of Partridge. ==",
"== Chapter xii. &mdash; Relates that Mr Jones continued his journey, contrary      to the advice of Partridge, with what happened on that occasion. ==",
"== Chapter xiii. &mdash; A dialogue between Jones and Partridge. ==",
"== Chapter xiv. &mdash; What happened to Mr Jones in his journey from St      Albans. ==",
"== BOOK XIII. &mdash; CONTAINING THE SPACE OF TWELVE DAYS. ==",
"== Chapter i. &mdash; An Invocation. ==",
"== Chapter ii. &mdash; What befel Mr Jones on his arrival in London. ==",
"== Chapter iii. &mdash; A project of Mrs Fitzpatrick, and her visit to Lady      Bellaston. ==",
"== Chapter iv. &mdash; Which consists of visiting. ==",
"== Chapter v. &mdash; An adventure which happened to Mr Jones at his      lodgings, with some account of a young gentleman who lodged there, and of      the mistress of the house, and her two daughters. ==",
"== Chapter vi. &mdash; What arrived while the company were at breakfast, with      some hints concerning the government of daughters. ==",
"== Chapter vii. &mdash; Containing the whole humours of a masquerade. ==",
"== Chapter viii. &mdash; Containing a scene of distress, which will appear      very extraordinary to most of our readers. ==",
"== Chapter ix. &mdash; Which treats of matters of a very different kind from      those in the preceding chapter. ==",
"== Chapter x. &mdash; A chapter which, though short, may draw tears from some      eyes. ==",
"== Chapter xi. &mdash; In which the reader will be surprized. ==",
"== Chapter xii. &mdash; In which the thirteenth book is concluded. ==",
"== BOOK XIV. &mdash; CONTAINING TWO DAYS. ==",
"== Chapter i. &mdash; An essay to prove that an author will write the better      for having some knowledge of the subject on which he writes. ==",
"== Chapter ii. &mdash; Containing letters and other matters which attend      amours. ==",
"== Chapter iii. &mdash; Containing various matters. ==",
"== Chapter iv. &mdash; Which we hope will be very attentively perused by      young people of both sexes. ==",
"== Chapter v. &mdash; A short account of the history of Mrs Miller. ==",
"== Chapter vi. &mdash; Containing a scene which we doubt not will affect all      our readers. ==",
"== Chapter vii. &mdash; The interview between Mr Jones and Mr Nightingale. ==",
"== Chapter viii. &mdash; What passed between Jones and old Mr Nightingale;      with the arrival of a person not yet mentioned in this history. ==",
"== Chapter ix. &mdash; Containing strange matters. ==",
"== Chapter x. &mdash; A short chapter, which concludes the book. ==",
"== BOOK XV. &mdash; IN WHICH THE HISTORY ADVANCES ABOUT TWO DAYS. ==",
"== Chapter i. &mdash; Too short to need a preface. ==",
"== Chapter ii. &mdash; In which is opened a very black design against Sophia. ==",
"== Chapter iii. &mdash; A further explanation of the foregoing design. ==",
"== Chapter iv. &mdash; By which it will appear how dangerous an advocate a      lady is when she applies her eloquence to an ill purpose. ==",
"== Chapter v. &mdash; Containing some matters which may affect, and others      which may surprize, the reader. ==",
"== Chapter vi. &mdash; By what means the squire came to discover his      daughter. ==",
"== Chapter vii. &mdash; In which various misfortunes befel poor Jones. ==",
"== Chapter viii. &mdash; Short and sweet. ==",
"== Chapter ix. &mdash; Containing love-letters of several sorts. ==",
"== Chapter x. &mdash; Consisting partly of facts, and partly of observations      upon them. ==",
"== Chapter xi. &mdash; Containing curious, but not unprecedented matter. ==",
"== Chapter xii. &mdash; A discovery made by Partridge. ==",
"== BOOK XVI. ==",
"=== CONTAINING THE SPACE OF FIVE DAYS. ===",
"== Chapter i. &mdash; Of prologues. ==",
"== Chapter ii. &mdash; A whimsical adventure which befel the squire, with the      distressed situation of Sophia. ==",
"== Chapter iii. &mdash; What happened to Sophia during her confinement. ==",
"== Chapter iv. &mdash; In which Sophia is delivered from her confinement. ==",
"== Chapter v. &mdash; In which Jones receives a letter from Sophia, and goes      to a play with Mrs Miller and Partridge. ==",
"== Chapter vi. &mdash; In which the history is obliged to look back. ==",
"== Chapter vii. &mdash; In which Mr Western pays a visit to his sister, in      company with Mr Blifil. ==",
"== Chapter viii. &mdash; Schemes of Lady Bellaston for the ruin of Jones. ==",
"== Chapter ix. &mdash; In which Jones pays a visit to Mrs Fitzpatrick. ==",
"== Chapter x. &mdash; The consequence of the preceding visit. ==",
"== BOOK XVII. ==",
"=== CONTAINING THREE DAYS. ===",
"== Chapter i. &mdash; Containing a portion of introductory writing. ==",
"== Chapter ii. &mdash; The generous and grateful behaviour of Mrs Miller. ==",
"== Chapter iii. &mdash; The arrival of Mr Western, with some matters      concerning the paternal authority. ==",
"== Chapter iv. &mdash; An extraordinary scene between Sophia and her aunt. ==",
"== Chapter v. &mdash; Mrs Miller and Mr Nightingale visit Jones in the      prison. ==",
"== Chapter vi. &mdash; In which Mrs Miller pays a visit to Sophia. ==",
"== Chapter vii. &mdash; A pathetic scene between Mr Allworthy and Mrs Miller. ==",
"== Chapter viii. &mdash; Containing various matters. ==",
"== Chapter ix. &mdash; What happened to Mr Jones in the prison. ==",
"== BOOK XVIII. ==",
"=== CONTAINING ABOUT SIX DAYS. ===",
"== Chapter i. &mdash; A farewel to the reader. ==",
"== Chapter ii. &mdash; Containing a very tragical incident. ==",
"== Chapter iii. &mdash; Allworthy visits old Nightingale; with a strange      discovery that he made on that occasion. ==",
"== Chapter iv. &mdash; Containing two letters in very different stiles. ==",
"== Chapter v. &mdash; In which the history is continued. ==",
"== Chapter vi. &mdash; In which the history is farther continued ==",
"== Chapter vii. &mdash; Continuation of the history. ==",
"== Chapter viii. &mdash; Further continuation. ==",
"== Chapter ix. &mdash; A further continuation. ==",
"== Chapter x. &mdash; Wherein the history begins to draw towards a      conclusion. ==",
"== Chapter xi. &mdash; The history draws nearer to a conclusion. ==",
"== Chapter xii. &mdash; Approaching still nearer to the end. ==",
"== Chapter the last. ==",
"=== In which the history is concluded. ===",
"=== FINIS. ===",
"== THE FULL PROJECT GUTENBERG LICENSE ==",
];
