var menulist=[
"= PREFACE =",
"= THE DAWN =",
"== I ==",
"== II ==",
"== III ==",
"= MORNING =",
"== I ==",
"== THE DEATH OF JEAN MICHEL ==",
"== II ==",
"== OTTO ==",
"== III ==",
"== MINNA ==",
"= YOUTH =",
"== I ==",
"== THE HOUSE OF EULER ==",
"== II ==",
"== SABINE ==",
"== III ==",
"== ADA ==",
"= REVOLT =",
"== I ==",
"== SHIFTING SANDS ==",
"== II ==",
"== ENGULFED ==",
"== III ==",
"== DELIVERANCE ==",
];
