var menulist=[
"== The Project Gutenberg eBook of Meditations ==",
"=       MEDITATIONS     =",
"==       By Marcus Aurelius     ==",
"===       MARCUS AURELIUS ANTONINUS THE ROMAN EMPEROR     ===",
"==       BOOKS     ==",
"==       INTRODUCTION     ==",
"==       HIS FIRST BOOK     ==",
"===       concerning HIMSELF:     ===",
"==       THE FIRST BOOK     ==",
"==       THE SECOND BOOK     ==",
"==       THE THIRD BOOK     ==",
"==       THE FOURTH BOOK     ==",
"==       THE FIFTH BOOK     ==",
"==       THE SIXTH BOOK     ==",
"==       THE SEVENTH BOOK     ==",
"==       THE EIGHTH BOOK     ==",
"==       THE NINTH BOOK     ==",
"==       THE TENTH BOOK     ==",
"==       THE ELEVENTH BOOK     ==",
"==       THE TWELFTH BOOK     ==",
"==       APPENDIX     ==",
"==       NOTES     ==",
"==       GLOSSARY     ==",
"=== Paragraphs with First Lines ===",
"== THE FULL PROJECT GUTENBERG LICENSE ==",
];
