var menulist=[
"== The Project Gutenberg eBook of Middlemarch ==",
"= Middlemarch =",
"== George Eliot ==",
"==== New York and Boston H. M. Caldwell Company Publishers ====",
"==== To my dear Husband, George Henry Lewes, in this nineteenth year of our blessed union. ====",
"== Contents ==",
"== PRELUDE. ==",
"== BOOK I. MISS BROOKE. ==",
"=== CHAPTER I. ===",
"=== CHAPTER II. ===",
"=== CHAPTER III. ===",
"=== CHAPTER IV. ===",
"=== CHAPTER V. ===",
"=== CHAPTER VI. ===",
"=== CHAPTER VII. ===",
"=== CHAPTER VIII. ===",
"=== CHAPTER IX. ===",
"=== CHAPTER X. ===",
"=== CHAPTER XI. ===",
"=== CHAPTER XII. ===",
"== BOOK II. OLD AND YOUNG. ==",
"=== CHAPTER XIII. ===",
"=== CHAPTER XIV. ===",
"=== CHAPTER XV. ===",
"=== CHAPTER XVI. ===",
"=== CHAPTER XVII. ===",
"=== CHAPTER XVIII. ===",
"=== CHAPTER XIX. ===",
"=== CHAPTER XX. ===",
"=== CHAPTER XXI. ===",
"=== CHAPTER XXII. ===",
"== BOOK III. WAITING FOR DEATH. ==",
"=== CHAPTER XXIII. ===",
"=== CHAPTER XXIV. ===",
"=== CHAPTER XXV. ===",
"=== CHAPTER XXVI. ===",
"=== CHAPTER XXVII. ===",
"=== CHAPTER XXVIII. ===",
"=== CHAPTER XXIX. ===",
"=== CHAPTER XXX. ===",
"=== CHAPTER XXXI. ===",
"=== CHAPTER XXXII. ===",
"=== CHAPTER XXXIII. ===",
"== BOOK IV. THREE LOVE PROBLEMS. ==",
"=== CHAPTER XXXIV. ===",
"=== CHAPTER XXXV. ===",
"=== CHAPTER XXXVI. ===",
"=== CHAPTER XXXVII. ===",
"=== CHAPTER XXXVIII. ===",
"=== CHAPTER XXXIX. ===",
"=== CHAPTER XL. ===",
"=== CHAPTER XLI. ===",
"=== CHAPTER XLII. ===",
"== BOOK V. THE DEAD HAND. ==",
"=== CHAPTER XLIII. ===",
"=== CHAPTER XLIV. ===",
"=== CHAPTER XLV. ===",
"=== CHAPTER XLVI. ===",
"=== CHAPTER XLVII. ===",
"=== CHAPTER XLVIII. ===",
"=== CHAPTER XLIX. ===",
"=== CHAPTER L. ===",
"=== CHAPTER LI. ===",
"=== CHAPTER LII. ===",
"=== CHAPTER LIII. ===",
"== BOOK VI. THE WIDOW AND THE WIFE. ==",
"=== CHAPTER LIV. ===",
"=== CHAPTER LV. ===",
"=== CHAPTER LVI. ===",
"=== CHAPTER LVII. ===",
"=== CHAPTER LVIII. ===",
"=== CHAPTER LIX. ===",
"=== CHAPTER LX. ===",
"=== CHAPTER LXI. ===",
"=== CHAPTER LXII. ===",
"== BOOK VII. TWO TEMPTATIONS. ==",
"=== CHAPTER LXIII. ===",
"=== CHAPTER LXIV. ===",
"=== CHAPTER LXV. ===",
"=== CHAPTER LXVI. ===",
"=== CHAPTER LXVII. ===",
"=== CHAPTER LXVIII. ===",
"=== CHAPTER LXIX. ===",
"=== CHAPTER LXX. ===",
"=== CHAPTER LXXI. ===",
"== BOOK VIII. SUNSET AND SUNRISE. ==",
"=== CHAPTER LXXII. ===",
"=== CHAPTER LXXIII. ===",
"=== CHAPTER LXXIV. ===",
"=== CHAPTER LXXV. ===",
"=== CHAPTER LXXVI. ===",
"=== CHAPTER LXXVII. ===",
"=== CHAPTER LXXVIII. ===",
"=== CHAPTER LXXIX. ===",
"=== CHAPTER LXXX. ===",
"=== CHAPTER LXXXI. ===",
"=== CHAPTER LXXXII. ===",
"=== CHAPTER LXXXIII. ===",
"=== CHAPTER LXXXIV. ===",
"=== CHAPTER LXXXV. ===",
"=== CHAPTER LXXXVI. ===",
"=== FINALE. ===",
"==== THE END ====",
"== THE FULL PROJECT GUTENBERG LICENSE ==",
];
