var menulist=[
"== The Project Gutenberg eBook of Robert's Rules of Order ==",
"= ROBERT’S RULES OF ORDER =",
"=== For Deliberative Assemblies ===",
"=== Part I. Rules of Order. ===",
"=== Part II. Organization and Conduct Of Business. ===",
"== by Major Henry M. Robert, Corps of Engineers, U.S.A. ==",
"== PREFACE. ==",
"== TABLE OF CONTENTS. ==",
"== INTRODUCTION. ==",
"=== Parliamentary Law. ===",
"=== Plan of the Work. ===",
"=== Definitions. ===",
"== Part I. Rules of Order. ==",
"=== Art. I. Introduction of Business. [§§ 1-5.] ===",
"=== Art. II. General Classification of Motions. [§§ 6-9.] ===",
"=== Art. III. Motions and their Order of Precedence.* [For a list of allthe ordinary motions, arranged in their order of precedence, see § 64.All the Privileged and Subsidiary ones in this Article are so arranged.][§§ 10-27.] ===",
"=== Privileged Motions. [§§ 10-13. See § 9.] ===",
"=== Incidental Motions. [§§ 14-18; see § 8] ===",
"=== Subsidiary Motions. [§§ 19-24; see § 7.] ===",
"=== Miscellaneous Motions. [§§ 25-27.] ===",
"=== Art. IV. Committees and Informal Action. [§§ 28-33.] ===",
"=== Art. V. Debate and Decorum. [§§ 34-37.] ===",
"=== Art. VI. Vote. [§§ 38-39.] ===",
"=== Art. VII. The Officers and the Minutes. [§§ 40, 41.] ===",
"=== Art. VIII. Miscellaneous. [§§ 42-45.] ===",
"== PART II. ORGANIZATION AND CONDUCT OF BUSINESS.* ==",
"=== Art. IX. Organization and Meetings. [§§ 46-49.] ===",
"=== Art. X. Officers and Committees. ===",
"=== Art. XI. Introduction of Business. ===",
"=== Art. XII. Motions. ===",
"=== Art. XIII. Debate. ===",
"=== Art. XIV. Miscellaneous. ===",
"=== Legal Rights of Assemblies and the Trial of theirMembers. ===",
"== TABLE OF RULES RELATING TO MOTIONS. ==",
"=== Notes To The Table. ===",
"== MISCELLANEOUS RULES. ==",
"=== Order of Precedence of Motions. ===",
"=== Two-thirds Vote. ===",
"=== Forms of Putting Certain Questions. ===",
"=== Various Forms of Amendments. ===",
"=== Additions and Corrections. ===",
"== INDEX. ==",
"== THE FULL PROJECT GUTENBERG LICENSE ==",
];
