var menulist=[
"== The Project Gutenberg eBook of Ten Years Later ==",
"= Ten Years Later =",
"== by Alexandre Dumas, Père ==",
"=== PROJECT GUTENBERG TRANSCRIBER’S NOTES: ===",
"== Introduction: ==",
"== Contents ==",
"== THE VICOMTE DE BRAGELONNE. ==",
"== Volume I. ==",
"== CHAPTER 1. The Letter. ==",
"== CHAPTER 2. The Messenger. ==",
"== CHAPTER 3. The Interview. ==",
"== CHAPTER 4. Father and Son. ==",
"== CHAPTER 5. In which Something will be said of Cropoli&mdash;of Cropoli and of a GreatUnknown Painter. ==",
"== CHAPTER 6. The Unknown. ==",
"== CHAPTER 7. Parry. ==",
"== CHAPTER 8. What his Majesty King Louis XIV. was at the Age of Twenty-Two ==",
"== CHAPTER 9. In which the Unknown of the Hostelry of Les Medici loses his Incognito. ==",
"== CHAPTER 10. The Arithmetic of M. de Mazarin ==",
"== CHAPTER 11. Mazarin’s Policy ==",
"== CHAPTER 12. The King and the Lieutenant ==",
"== CHAPTER 13. Mary de Mancini ==",
"== CHAPTER 14. In which the King and the Lieutenant each give Proofs of Memory ==",
"== CHAPTER 15. The Proscribed ==",
"== CHAPTER 16. “Remember!” ==",
"== CHAPTER 17. In which Aramis is sought and only Bazin is found ==",
"== CHAPTER 18. In which D’Artagnan seeks Porthos, and only finds Mousqueton ==",
"== CHAPTER 19. What D’Artagnan went to Paris for ==",
"== CHAPTER 20. Of the Society which was formed in the Rue des Lombards, at the Sign of thePilon d’Or, to carry out M. d’Artagnan’s Idea ==",
"== CHAPTER 21. In which D’Artagnan prepares to travel for the Firm of Planchet andCompany ==",
"== CHAPTER 22. D’Artagnan travels for the House of Planchet and Company ==",
"== CHAPTER 23. In which the Author, very unwillingly, is forced to write a Little History ==",
"== CHAPTER 24. The Treasure ==",
"== CHAPTER 25. The March ==",
"== CHAPTER 26. Heart and Mind ==",
"== CHAPTER 27. The Next Day ==",
"== CHAPTER 28. Smuggling ==",
"== CHAPTER 29. In which D’Artagnan begins to fear he has placed his Money and that ofPlanchet in the Sinking Fund ==",
"== CHAPTER 30. The Shares of Planchet and Company rise again to Par ==",
"== CHAPTER 31. Monk reveals himself ==",
"== CHAPTER 32. Athos and D’Artagnan meet once more at the Hostelry of the Corne du Cerf ==",
"== CHAPTER 33. The Audience. ==",
"== CHAPTER 34. Of the Embarrassment of Riches ==",
"== CHAPTER 35. On the Canal ==",
"== CHAPTER 36. How D’Artagnan drew, as a Fairy would have done, a Country-seat from aDeal Box ==",
"== CHAPTER 37. How D’Artagnan regulated the “Assets” of the Company beforehe established its “Liabilities” ==",
"== CHAPTER 38. In which it is seen that the French Grocer had already been established in theSeventeenth Century ==",
"== CHAPTER 39. Mazarin’s Gaming Party ==",
"== CHAPTER 40. An Affair of State ==",
"== CHAPTER 41. The Recital ==",
"== CHAPTER 42. In which Mazarin becomes Prodigal ==",
"== CHAPTER 43. Guenaud ==",
"== CHAPTER 44. Colbert ==",
"== CHAPTER 45. Confession of a Man of Wealth ==",
"== CHAPTER 46. The Donation ==",
"== CHAPTER 47. How Anne of Austria gave one Piece of Advice to Louis XIV., and how M. Fouquetgave him another. ==",
"== CHAPTER 48. Agony ==",
"== CHAPTER 49. The First Appearance of Colbert ==",
"== CHAPTER 50. The First Day of the Royalty of Louis XIV ==",
"== CHAPTER 51. A Passion ==",
"== CHAPTER 52. D’Artagnan’s Lesson ==",
"== CHAPTER 53. The King ==",
"== CHAPTER 54. The Houses of M. Fouquet ==",
"== CHAPTER 55. The Abbe Fouquet ==",
"== CHAPTER 56. M. de la Fontaine’s Wine ==",
"== CHAPTER 57. The Gallery of Saint-Mande ==",
"== CHAPTER 58. Epicureans ==",
"== CHAPTER 59. A Quarter of an Hour’s Delay ==",
"== CHAPTER 60. Plan of Battle ==",
"== CHAPTER 61. The Cabaret of the Image-de-Notre-Dame ==",
"== CHAPTER 62. Vive Colbert! ==",
"== CHAPTER 63. How M. d’Eymeris’s Diamond passed into the Hands of M. D’Artagnan. ==",
"== CHAPTER 64. Of the Notable Difference D’Artagnan finds between Monsieur the Intendantand Monsieur the Superintendent ==",
"== CHAPTER 65. Philosophy of the Heart and Mind ==",
"== CHAPTER 66. The Journey ==",
"== CHAPTER 67. How D’Artagnan became acquainted with a Poet, who had turned Printer forthe sake of printing his own Verses ==",
"== CHAPTER 68. D’Artagnan continues his Investigations ==",
"== CHAPTER 69. In which the Reader, no doubt, will be as astonished as D’Artagnan was tomeet an Old Acquaintance ==",
"== CHAPTER 70. Wherein the Ideas of D’Artagnan, at first strangely clouded, begin toclear up a little. ==",
"== CHAPTER 71. A Procession at Vannes ==",
"== CHAPTER 72. The Grandeur of the Bishop of Vannes ==",
"== CHAPTER 73. In which Porthos begins to be sorry for having come with D’Artagnan ==",
"== CHAPTER 74. In which D’Artagnan makes all Speed, Porthos snores, and Aramis counsels ==",
"== CHAPTER 75. In which Monsieur Fouquet acts ==",
"== CHAPTER 76. In which D’Artagnan finishes by at length placing his Hand upon hisCaptain’s Commission ==",
"== CHAPTER 77. A Lover and his Mistress ==",
"== CHAPTER 78. In which we at length see the true Heroine of this History appear ==",
"== CHAPTER 79. Malicorne and Manicamp ==",
"== CHAPTER 80. Manicamp and Malicorne ==",
"== CHAPTER 81. The Courtyard of the Hotel Grammont ==",
"== CHAPTER 82. The Portrait of Madame ==",
"== CHAPTER 83. Havre ==",
"== CHAPTER 84. At Sea ==",
"== CHAPTER 85. The Tents ==",
"== CHAPTER 86. Night ==",
"== CHAPTER 87. From Havre to Paris ==",
"== CHAPTER 88. An Account of what the Chevalier de Lorraine thought of Madame ==",
"== CHAPTER 89. A Surprise for Madame de Montalais ==",
"== CHAPTER 90. The Consent of Athos ==",
"== CHAPTER 91. Monsieur becomes jealous of the Duke of Buckingham ==",
"== CHAPTER 92. Forever! ==",
"== CHAPTER 93. King Louis XIV. does not think Mademoiselle de la Valliere either rich enoughor pretty enough for a Gentleman of the Rank of the Vicomte de Bragelonne ==",
"== CHAPTER 94. Sword-thrusts in the Water ==",
"== CHAPTER 95. Sword-thrusts in the Water (concluded) ==",
"== CHAPTER 96. Baisemeaux de Montlezun ==",
"== CHAPTER 97. The King’s Card-table ==",
"== CHAPTER 98. M. Baisemeaux de Montlezun’s Accounts ==",
"== CHAPTER 99. The Breakfast at Monsieur de Baisemeaux’s ==",
"== CHAPTER 100. The Second Floor of la Bertaudiere ==",
"== CHAPTER 101. The Two Friends ==",
"== CHAPTER 102. Madame de Belliere’s Plate ==",
"== CHAPTER 103. The Dowry ==",
"== CHAPTER 104. Le Terrain de Dieu ==",
"== THE FULL PROJECT GUTENBERG LICENSE ==",
];
