var menulist=[
"== The Project Gutenberg eBook of The Man in the Iron Mask ==",
"= The Man in the Iron Mask =",
"== by Alexandre Dumas, Père ==",
"== Contents ==",
"== Transcriber’s Notes: ==",
"== Introduction: ==",
"== Chapter I. The Prisoner. ==",
"== Chapter II. How Mouston Had Become Fatter without Giving Porthos NoticeThereof, and of the Troubles Which Consequently Befell that WorthyGentleman. ==",
"== Chapter III. Who Messire Jean Percerin Was. ==",
"== Chapter IV. The Patterns. ==",
"== Chapter V. Where, Probably, Moliere Obtained His First Idea of the BourgeoisGentilhomme. ==",
"== Chapter VI. The Bee-Hive, the Bees, and the Honey. ==",
"== Chapter VII. Another Supper at the Bastile. ==",
"== Chapter VIII. The General of the Order. ==",
"== Chapter IX. The Tempter. ==",
"== Chapter X. Crown and Tiara. ==",
"== Chapter XI. The Chateau de Vaux-le-Vicomte. ==",
"== Chapter XII. The Wine of Melun. ==",
"== Chapter XIII. Nectar and Ambrosia. ==",
"== Chapter XIV. A Gascon, and a Gascon and a Half. ==",
"== Chapter XV. Colbert. ==",
"== Chapter XVI. Jealousy. ==",
"== Chapter XVII. High Treason. ==",
"== Chapter XVIII. A Night at the Bastile. ==",
"== Chapter XIX. The Shadow of M. Fouquet. ==",
"== Chapter XX. The Morning. ==",
"== Chapter XXI. The King’s Friend. ==",
"== Chapter XXII. Showing How the Countersign Was Respected at the Bastile. ==",
"== Chapter XXIII. The King’s Gratitude. ==",
"== Chapter XXIV. The False King. ==",
"== Chapter XXV. In Which Porthos Thinks He Is Pursuing a Duchy. ==",
"== Chapter XXVI. The Last Adieux. ==",
"== Chapter XXVII. Monsieur de Beaufort. ==",
"== Chapter XXVIII. Preparations for Departure. ==",
"== Chapter XXIX. Planchet’s Inventory. ==",
"== Chapter XXX. The Inventory of M. de Beaufort. ==",
"== Chapter XXXI. The Silver Dish. ==",
"== Chapter XXXII. Captive and Jailers. ==",
"== Chapter XXXIII. Promises. ==",
"== Chapter XXXIV. Among Women. ==",
"== Chapter XXXV. The Last Supper. ==",
"== Chapter XXXVI. In M. Colbert’s Carriage. ==",
"== Chapter XXXVII. The Two Lighters. ==",
"== Chapter XXXVIII. Friendly Advice. ==",
"== Chapter XXXIX. How the King, Louis XIV., Played His Little Part. ==",
"== Chapter XL: The White Horse and the Black. ==",
"== Chapter XLI. In Which the Squirrel Falls,&mdash;the Adder Flies. ==",
"== Chapter XLII. Belle-Ile-en-Mer. ==",
"== Chapter XLIII. Explanations by Aramis. ==",
"== Chapter XLIV. Result of the Ideas of the King, and the Ideas ofD’Artagnan. ==",
"== Chapter XLV. The Ancestors of Porthos. ==",
"== Chapter XLVI. The Son of Biscarrat. ==",
"== Chapter XLVII. The Grotto of Locmaria. ==",
"== Chapter XLVIII. The Grotto. ==",
"== Chapter XLIX. An Homeric Song. ==",
"== Chapter L: The Death of a Titan. ==",
"== Chapter LI. Porthos’s Epitaph. ==",
"== Chapter LII. M. de Gesvres’s Round. ==",
"== Chapter LIII. King Louis XIV. ==",
"== Chapter LIV. M. Fouquet’s Friends. ==",
"== Chapter LV. Porthos’s Will. ==",
"== Chapter LVI. The Old Age of Athos. ==",
"== Chapter LVII. Athos’s Vision. ==",
"== Chapter LVIII. The Angel of Death. ==",
"== Chapter LIX. The Bulletin. ==",
"== Chapter LX. The Last Canto of the Poem. ==",
"== Epilogue. ==",
"== Footnotes ==",
"== THE FULL PROJECT GUTENBERG LICENSE ==",
];
