var menulist=[
"== The Project Gutenberg eBook of The Picture of Dorian Gray ==",
"= The Picture of Dorian Gray =",
"== by Oscar Wilde ==",
"== Contents ==",
"== THE PREFACE ==",
"== CHAPTER I. ==",
"== CHAPTER II. ==",
"== CHAPTER III. ==",
"== CHAPTER IV. ==",
"== CHAPTER V. ==",
"== CHAPTER VI. ==",
"== CHAPTER VII. ==",
"== CHAPTER VIII. ==",
"== CHAPTER IX. ==",
"== CHAPTER X. ==",
"== CHAPTER XI. ==",
"== CHAPTER XII. ==",
"== CHAPTER XIII. ==",
"== CHAPTER XIV. ==",
"== CHAPTER XV. ==",
"== CHAPTER XVI. ==",
"== CHAPTER XVII. ==",
"== CHAPTER XVIII. ==",
"== CHAPTER XIX. ==",
"== CHAPTER XX. ==",
"== THE FULL PROJECT GUTENBERG LICENSE ==",
];
