var menulist=[
"== The Project Gutenberg eBook of The Adventures of Tom Sawyer, Complete ==",
"= THE ADVENTURES OF TOM SAWYER =",
"== CONTENTS ==",
"== ILLUSTRATIONS ==",
"==       PREFACE     ==",
"==       CHAPTER I     ==",
"==       CHAPTER II     ==",
"==       CHAPTER III     ==",
"==       CHAPTER IV     ==",
"==       CHAPTER V     ==",
"==       CHAPTER VI     ==",
"==       CHAPTER VII     ==",
"==       CHAPTER VIII     ==",
"==       CHAPTER IX     ==",
"==       CHAPTER X     ==",
"==       CHAPTER XI     ==",
"==       CHAPTER XII     ==",
"==       CHAPTER XIII     ==",
"==       CHAPTER XIV     ==",
"==       CHAPTER XV     ==",
"==       CHAPTER XVI     ==",
"==       CHAPTER XVII     ==",
"==       CHAPTER XVIII     ==",
"==       CHAPTER XIX     ==",
"==       CHAPTER XX     ==",
"==       CHAPTER XXI     ==",
"==       CHAPTER XXII     ==",
"==       CHAPTER XXIII     ==",
"==       CHAPTER XXIV     ==",
"==       CHAPTER XXV     ==",
"==       CHAPTER XXVI     ==",
"==       CHAPTER XXVII     ==",
"==       CHAPTER XXVIII     ==",
"==       CHAPTER XXIX     ==",
"==       CHAPTER XXX     ==",
"==       CHAPTER XXXI     ==",
"==       CHAPTER XXXII     ==",
"==       CHAPTER XXXIII     ==",
"==       CHAPTER XXXIV     ==",
"==       CHAPTER XXXV     ==",
"== THE FULL PROJECT GUTENBERG LICENSE ==",
];
