var menulist=[
"== The Project Gutenberg eBook of The Imitation of Christ ==",
"= The Imitation of Christ =",
"== by Thomas à Kempis ==",
"== Contents ==",
"== INTRODUCTORY NOTE ==",
"== THE IMITATION OF CHRIST ==",
"== THE FIRST BOOK ADMONITIONS PROFITABLE FOR THE SPIRITUAL LIFE ==",
"=== CHAPTER I ===",
"=== CHAPTER II ===",
"=== CHAPTER III ===",
"=== CHAPTER IV ===",
"=== CHAPTER V ===",
"=== CHAPTER VI ===",
"=== CHAPTER VII ===",
"=== CHAPTER VIII ===",
"=== CHAPTER IX ===",
"=== CHAPTER X ===",
"=== CHAPTER XI ===",
"=== CHAPTER XII ===",
"=== CHAPTER XIII ===",
"=== CHAPTER XIV ===",
"=== CHAPTER XV ===",
"=== CHAPTER XVI ===",
"=== CHAPTER XVII ===",
"=== CHAPTER XVIII ===",
"=== CHAPTER XIX ===",
"=== CHAPTER XX ===",
"=== CHAPTER XXI ===",
"=== CHAPTER XXII ===",
"=== CHAPTER XXIII ===",
"=== CHAPTER XXIV ===",
"=== CHAPTER XXV ===",
"== THE SECOND BOOK ADMONITIONS CONCERNING THE INNER LIFE ==",
"=== CHAPTER I ===",
"=== CHAPTER II ===",
"=== CHAPTER III ===",
"=== CHAPTER IV ===",
"=== CHAPTER V ===",
"=== CHAPTER VI ===",
"=== CHAPTER VII ===",
"=== CHAPTER VIII ===",
"=== CHAPTER IX ===",
"=== CHAPTER X ===",
"=== CHAPTER XI ===",
"=== CHAPTER XII ===",
"== THE THIRD BOOK ON INWARD CONSOLATION ==",
"=== CHAPTER I ===",
"=== CHAPTER II ===",
"=== CHAPTER III ===",
"=== CHAPTER IV ===",
"=== CHAPTER V ===",
"=== CHAPTER VI ===",
"=== CHAPTER VII ===",
"=== CHAPTER VIII ===",
"=== CHAPTER IX ===",
"=== CHAPTER X ===",
"=== CHAPTER XI ===",
"=== CHAPTER XII ===",
"=== CHAPTER XIII ===",
"=== CHAPTER XIV ===",
"=== CHAPTER XV ===",
"=== CHAPTER XVI ===",
"=== CHAPTER XVII ===",
"=== CHAPTER XVIII ===",
"=== CHAPTER XIX ===",
"=== CHAPTER XX ===",
"=== CHAPTER XXI ===",
"=== CHAPTER XXII ===",
"=== CHAPTER XXIII ===",
"=== CHAPTER XXIV ===",
"=== CHAPTER XXV ===",
"=== CHAPTER XXVI ===",
"=== CHAPTER XXVII ===",
"=== CHAPTER XXVIII ===",
"=== CHAPTER XXIX ===",
"=== CHAPTER XXX ===",
"=== CHAPTER XXXI ===",
"=== CHAPTER XXXII ===",
"=== CHAPTER XXXIII ===",
"=== CHAPTER XXXIV ===",
"=== CHAPTER XXXV ===",
"=== CHAPTER XXXVI ===",
"=== CHAPTER XXXVII ===",
"=== CHAPTER XXXVIII ===",
"=== CHAPTER XXXIX ===",
"=== CHAPTER XL ===",
"=== CHAPTER XLI ===",
"=== CHAPTER XLII ===",
"=== CHAPTER XLIII ===",
"=== CHAPTER XLIV ===",
"=== CHAPTER XLV ===",
"=== CHAPTER XLVI ===",
"=== CHAPTER XLVII ===",
"=== CHAPTER XLVIII ===",
"=== CHAPTER XLIX ===",
"=== CHAPTER L ===",
"=== CHAPTER LI ===",
"=== CHAPTER LII ===",
"=== CHAPTER LIII ===",
"=== CHAPTER LIV ===",
"=== CHAPTER LV ===",
"=== CHAPTER LVI ===",
"=== CHAPTER LVII ===",
"=== CHAPTER LVIII ===",
"=== CHAPTER LIX ===",
"== THE FOURTH BOOK OF THE SACRAMENT OF THE ALTAR ==",
"=== CHAPTER I ===",
"=== CHAPTER II ===",
"=== CHAPTER III ===",
"=== CHAPTER IV ===",
"=== CHAPTER V ===",
"=== CHAPTER VI ===",
"=== CHAPTER VII ===",
"=== CHAPTER VIII ===",
"=== CHAPTER IX ===",
"=== CHAPTER X ===",
"=== CHAPTER XI ===",
"=== CHAPTER XII ===",
"=== CHAPTER XIII ===",
"=== CHAPTER XIV ===",
"=== CHAPTER XV ===",
"=== CHAPTER XVI ===",
"=== CHAPTER XVII ===",
"=== CHAPTER XVIII ===",
"== THE FULL PROJECT GUTENBERG LICENSE ==",
];
