var menulist=[
"== The Project Gutenberg eBook of The Odyssey ==",
"= The Odyssey =",
"== by Homer ==",
"===== rendered into English prose for the use of those who cannot read theoriginal =====",
"=== Contents ===",
"== PREFACE TO FIRST EDITION ==",
"== PREFACE TO SECOND EDITION ==",
"== THE ODYSSEY ==",
"== BOOK I ==",
"== BOOK II ==",
"== BOOK III ==",
"== BOOK IV ==",
"== BOOK V ==",
"== BOOK VI ==",
"== BOOK VII ==",
"== BOOK VIII ==",
"== BOOK IX ==",
"== BOOK X ==",
"== BOOK XI ==",
"== BOOK XII ==",
"== BOOK XIII ==",
"== BOOK XIV ==",
"== BOOK XV ==",
"== BOOK XVI ==",
"== BOOK XVII ==",
"== BOOK XVIII ==",
"== BOOK XIX ==",
"== BOOK XX ==",
"== BOOK XXI ==",
"== BOOK XXII ==",
"== BOOK XXIII ==",
"== BOOK XXIV ==",
"== FOOTNOTES: ==",
"== THE FULL PROJECT GUTENBERG LICENSE ==",
];
