var menulist=[
"== THE SONNETS ==",
"==== THE END ====",
"== ALL’S WELL THAT ENDS WELL ==",
"==== Contents ====",
"==== Dramatis Personæ ====",
"==== SCENE: Partly in France, and partly in Tuscany. ====",
"=== ACT I ===",
"==== SCENE I. Rossillon. A room in the Countess’s palace. ====",
"==== SCENE II. Paris. A room in the King’s palace. ====",
"==== SCENE III. Rossillon. A Room in the Palace. ====",
"=== ACT II. ===",
"==== SCENE I. Paris. A room in the King’s palace. ====",
"==== SCENE II. Rossillon. A room in the Countess’s palace. ====",
"==== SCENE III. Paris. The King’s palace. ====",
"==== SCENE IV. Paris. The King’s palace. ====",
"==== SCENE V. Another room in the same. ====",
"=== ACT III. ===",
"==== SCENE I. Florence. A room in the Duke’s palace. ====",
"==== SCENE II. Rossillon. A room in the Countess’s palace. ====",
"==== SCENE III. Florence. Before the Duke’s palace. ====",
"==== SCENE IV. Rossillon. A room in the Countess’s palace. ====",
"==== SCENE V. Without the walls of Florence. ====",
"==== SCENE VI. Camp before Florence. ====",
"==== SCENE VII. Florence. A room in the Widow’s house. ====",
"=== ACT IV. ===",
"==== SCENE I. Without the Florentine camp. ====",
"==== SCENE II. Florence. A room in the Widow’s house. ====",
"==== SCENE III. The Florentine camp. ====",
"==== SCENE IV. Florence. A room in the Widow’s house. ====",
"==== SCENE V. Rossillon. A room in the Countess’s palace. ====",
"=== ACT V. ===",
"==== SCENE I. Marseilles. A street. ====",
"==== SCENE II. Rossillon. The inner court of the Countess’s palace. ====",
"==== SCENE III. The same. A room in the Countess’s palace. ====",
"==== [EPILOGUE] ====",
"== ANTONY AND CLEOPATRA ==",
"=== Contents ===",
"=== Dramatis Personæ ===",
"=== SCENE: Dispersed, in several parts of the Roman Empire. ===",
"== ACT I ==",
"=== SCENE I. Alexandria. A Room in Cleopatra’s palace. ===",
"=== SCENE II. Alexandria. Another Room in Cleopatra’s palace. ===",
"=== SCENE III. Alexandria. A Room in Cleopatra’s palace. ===",
"=== SCENE IV. Rome. An Apartment in Caesar’s House. ===",
"=== SCENE V. Alexandria. A Room in the Palace. ===",
"== ACT II ==",
"=== SCENE I. Messina. A Room in Pompey’s house. ===",
"=== SCENE II. Rome. A Room in the House of Lepidus. ===",
"=== SCENE III. Rome. A Room in Caesar’s House. ===",
"=== SCENE IV. Rome. A street. ===",
"=== SCENE V. Alexandria. A Room in the Palace. ===",
"=== SCENE VI. Near Misenum. ===",
"=== SCENE VII. On board Pompey’s Galley, lying near Misenum. ===",
"== ACT III ==",
"=== SCENE I. A plain in Syria. ===",
"=== SCENE II. Rome. An Ante-chamber in Caesar’s house. ===",
"=== SCENE III. Alexandria. A Room in the Palace. ===",
"=== SCENE IV. Athens. A Room in Antony’s House. ===",
"=== SCENE V. Athens. Another Room in Antony’s House. ===",
"=== SCENE VI. Rome. A Room in Caesar’s House. ===",
"=== SCENE VII. Antony’s Camp near the Promontory of Actium. ===",
"=== SCENE VIII. A plain near Actium. ===",
"=== SCENE IX. Another part of the Plain. ===",
"=== SCENE X. Another part of the Plain. ===",
"=== SCENE XI. Alexandria. A Room in the Palace. ===",
"=== SCENE XII. Caesar’s camp in Egypt. ===",
"=== SCENE XIII. Alexandria. A Room in the Palace. ===",
"== ACT IV ==",
"=== SCENE I. Caesar’s Camp at Alexandria. ===",
"=== SCENE II. Alexandria. A Room in the Palace. ===",
"=== SCENE III. Alexandria. Before the Palace. ===",
"=== SCENE IV. Alexandria. A Room in the Palace. ===",
"=== SCENE V. Antony’s camp near Alexandria. ===",
"=== SCENE VI. Alexandria. Caesar’s camp. ===",
"=== SCENE VII. Field of battle between the Camps. ===",
"=== SCENE VIII. Under the Walls of Alexandria. ===",
"=== SCENE IX. Caesar’s camp. ===",
"=== SCENE X. Ground between the two Camps. ===",
"=== SCENE XI. Another part of the Ground. ===",
"=== SCENE XII. Another part of the Ground. ===",
"=== SCENE XIII. Alexandria. A Room in the Palace. ===",
"=== SCENE XIV. Alexandria. Another Room. ===",
"=== SCENE XV. Alexandria. A monument. ===",
"== ACT V ==",
"=== SCENE I. Caesar’s Camp before Alexandria. ===",
"=== SCENE II. Alexandria. A Room in the Monument. ===",
"== AS YOU LIKE IT ==",
"==== DRAMATIS PERSONAE. ====",
"==== SCENE: OLIVER'S house; FREDERICK'S court; and the Forest of Arden ====",
"==== ACT I. SCENE I. Orchard of OLIVER'S house ====",
"==== SCENE II. A lawn before the DUKE'S palace ====",
"==== SCENE III. The DUKE's palace ====",
"==== ACT II. SCENE I. The Forest of Arden ====",
"==== SCENE II. The DUKE'S palace ====",
"==== SCENE III. Before OLIVER'S house ====",
"==== SCENE IV. The Forest of Arden ====",
"==== SCENE V. Another part of the forest ====",
"==== SCENE VI. The forest ====",
"==== SCENE VII. The forest ====",
"==== ACT III. SCENE I. The palace ====",
"==== SCENE II. The forest ====",
"==== SCENE III. The forest ====",
"==== SCENE IV. The forest ====",
"==== SCENE V. Another part of the forest ====",
"==== ACT IV. SCENE I. The forest ====",
"==== SCENE II. The forest ====",
"==== SCENE III. The forest ====",
"==== ACT V. SCENE I. The forest ====",
"==== SCENE II. The forest ====",
"==== SCENE III. The forest ====",
"==== SCENE IV. The forest ====",
"== THE COMEDY OF ERRORS ==",
"=== Contents ===",
"=== Dramatis Personæ ===",
"==== SCENE: Ephesus ====",
"=== ACT I ===",
"==== SCENE I. A hall in the Duke’s palace. ====",
"==== SCENE II. A public place. ====",
"=== ACT II ===",
"==== SCENE I. A public place. ====",
"==== SCENE II. The same. ====",
"=== ACT III ===",
"==== SCENE I. The same. ====",
"==== SCENE II. The same. ====",
"=== ACT IV ===",
"==== SCENE I. The same. ====",
"==== SCENE II. The same. ====",
"==== SCENE III. The same. ====",
"==== SCENE IV. The same. ====",
"=== ACT V ===",
"==== SCENE I. The same. ====",
"== THE TRAGEDY OF CORIOLANUS ==",
"==== SCENE: Rome and the neighbourhood; Corioli and the neighbourhood; Antium ====",
"==== ACT I. SCENE I. Rome. A street ====",
"==== SCENE II. Corioli. The Senate House. ====",
"==== SCENE III. Rome. MARCIUS' house ====",
"==== SCENE IV. Before Corioli ====",
"==== SCENE V. Within Corioli. A street ====",
"==== SCENE VI. Near the camp of COMINIUS ====",
"==== SCENE VII. The gates of Corioli ====",
"==== SCENE VIII. A field of battle between the Roman and the Volscian camps ====",
"==== SCENE IX. The Roman camp ====",
"==== SCENE X. The camp of the Volsces ====",
"==== ACT II. SCENE I. Rome. A public place ====",
"==== SCENE II. Rome. The Capitol ====",
"==== SCENE III. Rome. The Forum ====",
"==== ACT III. SCENE I. Rome. A street ====",
"==== SCENE II. Rome. The house of CORIOLANUS ====",
"==== SCENE III. Rome. The Forum ====",
"==== ACT IV. SCENE I. Rome. Before a gate of the city ====",
"==== SCENE II. Rome. A street near the gate ====",
"==== SCENE III. A highway between Rome and Antium ====",
"==== SCENE IV. Antium. Before AUFIDIUS' house ====",
"==== SCENE V. Antium. AUFIDIUS' house ====",
"==== SCENE VI. Rome. A public place ====",
"==== SCENE VII. A camp at a short distance from Rome ====",
"==== ACT V. SCENE I. Rome. A public place ====",
"==== SCENE II. The Volscian camp before Rome ====",
"==== SCENE III. The tent of CORIOLANUS ====",
"==== SCENE IV. Rome. A public place ====",
"==== SCENE V. Rome. A street near the gate ====",
"==== SCENE VI. Corioli. A public place ====",
"== CYMBELINE ==",
"==== Contents ====",
"==== Dramatis Personæ ====",
"==== SCENE: Britain; Italy. ====",
"=== ACT I ===",
"==== SCENE I. Britain. The garden of Cymbeline’s palace. ====",
"==== SCENE II. The same. ====",
"==== SCENE III. Britain. A public place. ====",
"==== SCENE IV. Britain. Cymbeline’s palace. ====",
"==== SCENE V. Rome. Philario’s house. ====",
"==== SCENE VI. Britain. Cymbeline’s palace. ====",
"==== SCENE VII. Britain. The palace. ====",
"=== ACT II ===",
"==== SCENE I. Britain. Before Cymbeline’s palace. ====",
"==== SCENE II. Britain. Imogen’s bedchamber in Cymbeline’s palace; a trunk in one corner. ====",
"==== SCENE III. Cymbeline’s palace. An ante-chamber adjoining Imogen’s apartments. ====",
"==== SCENE IV. Rome. Philario’s house. ====",
"==== SCENE V. Rome. Another room in Philario’s house. ====",
"=== ACT III ===",
"==== SCENE I. Britain. A hall in Cymbeline’s palace. ====",
"==== SCENE II. Britain. Another room in Cymbeline’s palace. ====",
"==== SCENE III. Wales. A mountainous country with a cave. ====",
"==== SCENE IV. Wales, near Milford Haven. ====",
"==== SCENE V. Britain. Cymbeline’s palace. ====",
"==== SCENE VI. Wales. Before the cave of Belarius. ====",
"==== SCENE VII. The same. ====",
"==== SCENE VIII. Rome. A public place. ====",
"=== ACT IV ===",
"==== SCENE I. Wales. Near the cave of Belarius. ====",
"==== SCENE II. Wales. Before the cave of Belarius. ====",
"==== SCENE III. Britain. Cymbeline’s palace. ====",
"==== SCENE IV. Wales. Before the cave of Belarius. ====",
"=== ACT V ===",
"==== SCENE I. Britain. The Roman camp. ====",
"==== SCENE II. Britain. A field of battle between the British and Roman camps. ====",
"==== SCENE III. Another part of the field. ====",
"==== SCENE IV. Britain. A prison. ====",
"==== SCENE V. Britain. Cymbeline’s tent. ====",
"== THE TRAGEDY OF HAMLET, PRINCE OF DENMARK ==",
"==== Contents ====",
"==== Dramatis Personæ ====",
"==== SCENE. Elsinore. ====",
"=== ACT I ===",
"==== SCENE I. Elsinore. A platform before the Castle. ====",
"==== SCENE II. Elsinore. A room of state in the Castle. ====",
"==== SCENE III. A room in Polonius’s house. ====",
"==== SCENE IV. The platform. ====",
"==== SCENE V. A more remote part of the Castle. ====",
"=== ACT II ===",
"==== SCENE I. A room in Polonius’s house. ====",
"==== SCENE II. A room in the Castle. ====",
"=== ACT III ===",
"==== SCENE I. A room in the Castle. ====",
"==== SCENE II. A hall in the Castle. ====",
"==== SCENE III. A room in the Castle. ====",
"==== SCENE IV. Another room in the Castle. ====",
"=== ACT IV ===",
"==== SCENE I. A room in the Castle. ====",
"==== SCENE II. Another room in the Castle. ====",
"==== SCENE III. Another room in the Castle. ====",
"==== SCENE IV. A plain in Denmark. ====",
"==== SCENE V. Elsinore. A room in the Castle. ====",
"==== SCENE VI. Another room in the Castle. ====",
"==== SCENE VII. Another room in the Castle. ====",
"=== ACT V ===",
"==== SCENE I. A churchyard. ====",
"==== SCENE II. A hall in the Castle. ====",
"== THE FIRST PART OF KING HENRY THE FOURTH ==",
"==== Dramatis Personæ ====",
"==== SCENE. England and Wales. ====",
"==== ACT I ====",
"==== SCENE I. London. A Room in the Palace. ====",
"==== SCENE II. The same. An Apartment of Prince Henry’s. ====",
"==== SCENE III. The Same. A Room in the Palace. ====",
"==== ACT II ====",
"==== SCENE I. Rochester. An Inn-Yard. ====",
"==== SCENE II. The Road by Gads-hill. ====",
"==== SCENE III. Warkworth. A Room in the Castle. ====",
"==== SCENE IV. Eastcheap. A Room in the Boar’s-Head Tavern. ====",
"==== ACT III ====",
"==== SCENE I. Bangor. A Room in the Archdeacon’s House. ====",
"==== SCENE II. London. A Room in the Palace. ====",
"==== SCENE III. Eastcheap. A Room in the Boar’s-Head Tavern. ====",
"==== ACT IV ====",
"==== SCENE I. The Rebel Camp near Shrewsbury. ====",
"==== SCENE II. A public Road near Coventry. ====",
"==== SCENE III. The Rebel Camp near Shrewsbury. ====",
"==== SCENE IV. York. A Room in the Archbishop’s Palace. ====",
"==== ACT V ====",
"==== SCENE I. The King’s Camp near Shrewsbury. ====",
"==== SCENE II. The Rebel Camp. ====",
"==== SCENE III. Plain between the Camps. ====",
"==== SCENE IV. Another Part of the Field. ====",
"==== SCENE V. Another Part of the Field. ====",
"== THE SECOND PART OF KING HENRY THE FOURTH ==",
"==== SCENE: England ====",
"==== ACT I. SCENE I. Warkworth. Before NORTHUMBERLAND'S Castle ====",
"==== SCENE II. London. A street ====",
"==== SCENE III. York. The ARCHBISHOP'S palace ====",
"==== ACT II. SCENE I. London. A street ====",
"==== SCENE II. London. Another street ====",
"==== SCENE III. Warkworth. Before the castle ====",
"==== SCENE IV. London. The Boar's Head Tavern in Eastcheap ====",
"==== ACT III. SCENE I. Westminster. The palace ====",
"==== SCENE II. Gloucestershire. Before Justice, SHALLOW'S house ====",
"==== ACT IV. SCENE I. Yorkshire. Within the Forest of Gaultree ====",
"==== SCENE II. Another part of the forest ====",
"==== SCENE III. Another part of the forest ====",
"==== SCENE IV. Westminster. The Jerusalem Chamber ====",
"==== SCENE V. Westminster. Another chamber ====",
"==== ACT V. SCENE I. Gloucestershire. SHALLOW'S house ====",
"==== SCENE II. Westminster. The palace ====",
"==== SCENE III. Gloucestershire. SHALLOW'S orchard ====",
"==== SCENE IV. London. A street ====",
"==== SCENE V. Westminster. Near the Abbey ====",
"==== EPILOGUE EPILOGUE. ====",
"== THE LIFE OF KING HENRY V ==",
"=== Contents ===",
"=== Dramatis Personæ ===",
"=== SCENE: England; afterwards France. ===",
"==== PROLOGUE. ====",
"=== ACT I ===",
"==== SCENE I. London. An ante-chamber in the King’s palace. ====",
"==== SCENE II. The same. The presence chamber. ====",
"=== ACT II ===",
"==== SCENE I. London. A street. ====",
"==== SCENE II. Southampton. A council-chamber. ====",
"==== SCENE III. London. Before a tavern. ====",
"==== SCENE IV. France. The King’s palace. ====",
"=== ACT III ===",
"==== SCENE I. France. Before Harfleur. ====",
"==== SCENE II. The same. ====",
"==== SCENE III. Before the gates. ====",
"==== SCENE IV. The French King’s palace. ====",
"==== SCENE V. The same. ====",
"==== SCENE VI. The English camp in Picardy. ====",
"==== SCENE VII. The French camp, near Agincourt. ====",
"=== ACT IV ===",
"==== SCENE I. The English camp at Agincourt. ====",
"==== SCENE II. The French camp. ====",
"==== SCENE III. The English camp. ====",
"==== SCENE IV. The field of battle. ====",
"==== SCENE V. Another part of the field. ====",
"==== SCENE VI. Another part of the field. ====",
"==== SCENE VII. Another part of the field. ====",
"==== SCENE VIII. Before King Henry’s pavilion. ====",
"=== ACT V ===",
"==== SCENE I. France. The English camp. ====",
"==== SCENE II. France. A royal palace. ====",
"==== EPILOGUE. ====",
"== THE FIRST PART OF HENRY THE SIXTH ==",
"==== SCENE: England and France ====",
"==== ACT I. SCENE 1. ====",
"==== SCENE 2. ====",
"==== SCENE 3. ====",
"==== SCENE 4. ====",
"==== SCENE 5. ====",
"==== SCENE 6. ====",
"==== ORLEANS ====",
"==== ACT II. SCENE 1. ====",
"==== SCENE 2. ====",
"==== SCENE 3. ====",
"==== SCENE 4. ====",
"==== SCENE 5. ====",
"==== ACT III. SCENE 1. ====",
"==== SCENE 2. ====",
"==== SCENE 3. ====",
"==== SCENE 4. ====",
"==== ACT IV. SCENE 1. ====",
"==== SCENE 2. ====",
"==== SCENE 3. ====",
"==== SCENE 4. ====",
"==== SCENE 5. ====",
"==== SCENE 6. ====",
"==== SCENE 7. ====",
"==== ACT V. SCENE 1. ====",
"==== SCENE 2. ====",
"==== SCENE 3. ====",
"==== SCENE 4. ====",
"==== SCENE 5. ====",
"== THE SECOND PART OF KING HENRY THE SIXTH ==",
"==== SCENE: England ====",
"==== ACT I. SCENE I. London. The palace ====",
"==== SCENE II. The DUKE OF GLOUCESTER'S house ====",
"==== SCENE III. London. The palace ====",
"==== SCENE IV. London. The DUKE OF GLOUCESTER'S garden ====",
"==== ACT II. SCENE I. Saint Albans ====",
"==== SCENE II. London. The DUKE OF YORK'S garden ====",
"==== SCENE III. London. A hall of justice ====",
"==== SCENE IV. London. A street ====",
"==== ACT III. SCENE I. The Abbey at Bury St. Edmunds ====",
"==== SCENE II. Bury St. Edmunds. A room of state ====",
"==== SCENE III. London. CARDINAL BEAUFORT'S bedchamber ====",
"==== ACT IV. SCENE I. The coast of Kent ====",
"==== SCENE II. Blackheath ====",
"==== SCENE III. Another part of Blackheath ====",
"==== SCENE IV. London. The palace ====",
"==== SCENE V. London. The Tower ====",
"==== SCENE VI. London. Cannon street ====",
"==== SCENE VII. London. Smithfield ====",
"==== SCENE VIII. Southwark ====",
"==== SCENE IX. Killing, worth Castle ====",
"==== SCENE X. Kent. Iden's garden ====",
"==== ACT V. SCENE I. Fields between Dartford and Blackheath ====",
"==== SCENE II. Saint Albans ====",
"==== SCENE III. Fields near Saint Albans ====",
"== THE THIRD PART OF KING HENRY THE SIXTH ==",
"==== DRAMATIS PERSONAE ====",
"==== SCENE: England and France ====",
"==== ACT I. SCENE I. London. The Parliament House ====",
"==== SCENE II. Sandal Castle, near Wakefield, in Yorkshire ====",
"==== SCENE III. Field of battle between Sandal Castle and Wakefield ====",
"==== SCENE IV. Another part of the field ====",
"==== ACT II. SCENE I. A plain near Mortimer's Cross in Herefordshire ====",
"==== SCENE II. Before York ====",
"==== SCENE III. A field of battle between Towton and Saxton, in Yorkshire ====",
"==== SCENE IV. Another part of the field ====",
"==== SCENE V. Another part of the field ====",
"==== SCENE VI. Another part of the field ====",
"==== ACT III. SCENE I. A chase in the north of England ====",
"==== SCENE II. London. The palace ====",
"==== SCENE III. France. The KING'S palace ====",
"==== ACT IV. SCENE I. London. The palace ====",
"==== SCENE II. A plain in Warwickshire ====",
"==== SCENE III. Edward's camp, near Warwick ====",
"==== SCENE IV. London. The palace ====",
"==== SCENE V. A park near Middleham Castle in Yorkshire ====",
"==== SCENE VI. London. The Tower ====",
"==== SCENE VII. Before York ====",
"==== SCENE VIII. London. The palace ====",
"==== ACT V. SCENE I. Coventry ====",
"==== SCENE II. A field of battle near Barnet ====",
"==== SCENE III. Another part of the field ====",
"==== SCENE IV. Plains wear Tewksbury ====",
"==== SCENE V. Another part of the field ====",
"==== SCENE VI. London. The Tower ====",
"==== SCENE VII. London. The palace ====",
"== KING HENRY THE EIGHTH ==",
"==== DRAMATIS PERSONAE ====",
"==== SCENE: ====",
"==== KING HENRY THE EIGHTH ====",
"==== THE PROLOGUE. ====",
"==== ACT I. SCENE 1. ====",
"==== ACT I. SCENE 2. ====",
"==== ACT I. SCENE 3. ====",
"==== ACT I. SCENE 4. ====",
"==== ACT II. SCENE 1. ====",
"==== ACT II. SCENE 2. ====",
"==== ACT II. SCENE 3. ====",
"==== ACT II. SCENE 4. ====",
"==== ACT III. SCENE 1. ====",
"==== ACT III.SCENE 2. ====",
"==== ACT IV. SCENE 1. ====",
"===== THE ORDER OF THE CORONATION. =====",
"==== ACT IV. SCENE 2. ====",
"===== THE VISION. =====",
"==== ACT V. SCENE 1. ====",
"==== ACT V. SCENE 2. ====",
"==== ACT V. SCENE 3. ====",
"==== ACT V. SCENE 4. ====",
"==== ACT V. SCENE 5. ====",
"==== KING_HENRY_VIII|EPILOGUE THE EPILOGUE. ====",
"== KING JOHN ==",
"==== DRAMATIS PERSONAE ====",
"==== SCENE: England and France ====",
"==== ACT I. SCENE 1 ====",
"==== ACT II. SCENE 1 ====",
"==== ACT III. SCENE 1. ====",
"==== SCENE 2. ====",
"==== SCENE 3. ====",
"==== SCENE 4. ====",
"==== ACT IV. SCENE 1. ====",
"==== SCENE 2. ====",
"==== SCENE 3. ====",
"==== ACT V. SCENE 1. England. KING JOHN'S palace ====",
"==== SCENE 2. England. The DAUPHIN'S camp at Saint Edmundsbury ====",
"==== SCENE 3. ====",
"==== SCENE 4. ====",
"==== SCENE 5. ====",
"==== SCENE 6. ====",
"==== SCENE 7. ====",
"== THE TRAGEDY OF JULIUS CAESAR ==",
"==== Contents ====",
"==== Dramatis Personæ ====",
"==== SCENE: Rome, the conspirators’ camp near Sardis, and the plains of Philippi. ====",
"=== ACT I ===",
"==== SCENE I. Rome. A street. ====",
"==== SCENE II. The same. A public place. ====",
"==== SCENE III. The same. A street. ====",
"=== ACT II ===",
"==== SCENE I. Rome. Brutus’ orchard. ====",
"==== SCENE II. A room in Caesar’s palace. ====",
"==== SCENE III. A street near the Capitol. ====",
"==== SCENE IV. Another part of the same street, before the house of Brutus. ====",
"=== ACT III ===",
"==== SCENE I. Rome. Before the Capitol; the Senate sitting. ====",
"==== SCENE II. The same. The Forum. ====",
"==== SCENE III. The same. A street. ====",
"=== ACT IV ===",
"==== SCENE I. Rome. A room in Antony’s house. ====",
"==== SCENE II. Before Brutus’ tent, in the camp near Sardis. ====",
"==== SCENE III. Within the tent of Brutus. ====",
"=== ACT V ===",
"==== SCENE I. The plains of Philippi. ====",
"==== SCENE II. The same. The field of battle. ====",
"==== SCENE III. Another part of the field. ====",
"==== SCENE IV. Another part of the field. ====",
"==== SCENE V. Another part of the field. ====",
"== THE TRAGEDY OF KING LEAR ==",
"==== Contents ====",
"==== Dramatis Personæ ====",
"==== SCENE: Britain. ====",
"=== ACT I ===",
"==== SCENE I. A Room of State in King Lear’s Palace. ====",
"==== SCENE II. A Hall in the Earl of Gloucester’s Castle. ====",
"==== SCENE III. A Room in the Duke of Albany’s Palace. ====",
"==== SCENE IV. A Hall in Albany’s Palace. ====",
"==== SCENE V. Court before the Duke of Albany’s Palace. ====",
"=== ACT II ===",
"==== SCENE I. A court within the Castle of the Earl of Gloucester. ====",
"==== SCENE II. Before Gloucester’s Castle. ====",
"==== SCENE III. The open Country. ====",
"==== SCENE IV. Before Gloucester’s Castle; Kent in the stocks. ====",
"=== ACT III ===",
"==== SCENE I. A Heath. ====",
"==== SCENE II. Another part of the heath. ====",
"==== SCENE III. A Room in Gloucester’s Castle. ====",
"==== SCENE IV. A part of the Heath with a Hovel. ====",
"==== SCENE V. A Room in Gloucester’s Castle. ====",
"==== SCENE VI. A Chamber in a Farmhouse adjoining the Castle. ====",
"==== SCENE VII. A Room in Gloucester’s Castle. ====",
"=== ACT IV ===",
"==== SCENE I. The heath. ====",
"==== SCENE II. Before the Duke of Albany’s Palace. ====",
"==== SCENE III. The French camp near Dover. ====",
"==== SCENE IV. The French camp. A Tent. ====",
"==== SCENE V. A Room in Gloucester’s Castle. ====",
"==== SCENE VI. The country near Dover. ====",
"==== SCENE VII. A Tent in the French Camp. ====",
"=== ACT V ===",
"==== SCENE I. The Camp of the British Forces near Dover. ====",
"==== SCENE II. A field between the two Camps. ====",
"==== SCENE III. The British Camp near Dover. ====",
"== LOVE’S LABOUR’S LOST ==",
"==== SCENE: Navarre ====",
"==== ACT I. SCENE I. Navarre. The King's park ====",
"==== SCENE II. The park ====",
"==== ACT II. SCENE II. The park ====",
"==== ACT III. SCENE I. The park ====",
"==== ACT IV. SCENE I. The park ====",
"==== SCENE II. The park ====",
"==== SCENE III. The park ====",
"==== ACT V. SCENE I. The park ====",
"==== SCENE II. The park ====",
"==== WINTER ====",
"== MACBETH ==",
"==== Contents ====",
"==== Dramatis Personæ ====",
"==== SCENE: In the end of the Fourth Act, in England; through the rest of the Play, in Scotland; and chiefly at Macbeth’s Castle. ====",
"=== ACT I ===",
"==== SCENE I. An open Place. ====",
"==== SCENE II. A Camp near Forres. ====",
"==== SCENE III. A heath. ====",
"==== SCENE IV. Forres. A Room in the Palace. ====",
"==== SCENE V. Inverness. A Room in Macbeth’s Castle. ====",
"==== SCENE VI. The same. Before the Castle. ====",
"==== SCENE VII. The same. A Lobby in the Castle. ====",
"=== ACT II ===",
"==== SCENE I. Inverness. Court within the Castle. ====",
"==== SCENE II. The same. ====",
"==== SCENE III. The same. ====",
"==== SCENE IV. The same. Without the Castle. ====",
"=== ACT III ===",
"==== SCENE I. Forres. A Room in the Palace. ====",
"==== SCENE II. The same. Another Room in the Palace. ====",
"==== SCENE III. The same. A Park or Lawn, with a gate leading to the Palace. ====",
"==== SCENE IV. The same. A Room of state in the Palace. ====",
"==== SCENE V. The heath. ====",
"==== SCENE VI. Forres. A Room in the Palace. ====",
"=== ACT IV ===",
"==== SCENE I. A dark Cave. In the middle, a Cauldron Boiling. ====",
"==== SCENE II. Fife. A Room in Macduff’s Castle. ====",
"==== SCENE III. England. Before the King’s Palace. ====",
"=== ACT V ===",
"==== SCENE I. Dunsinane. A Room in the Castle. ====",
"==== SCENE II. The Country near Dunsinane. ====",
"==== SCENE III. Dunsinane. A Room in the Castle. ====",
"==== SCENE IV. Country near Dunsinane: a Wood in view. ====",
"==== SCENE V. Dunsinane. Within the castle. ====",
"==== SCENE VI. The same. A Plain before the Castle. ====",
"==== SCENE VII. The same. Another part of the Plain. ====",
"==== SCENE VIII. The same. Another part of the field. ====",
"== MEASURE FOR MEASURE ==",
"==== DRAMATIS PERSONAE ====",
"==== SCENE: Vienna ====",
"==== ACT I. SCENE I. The DUKE'S palace ====",
"==== SCENE II. A street ====",
"==== SCENE III. A monastery ====",
"==== SCENE IV. A nunnery ====",
"==== ACT II. Scene I. A hall in ANGELO'S house ====",
"==== SCENE II. Another room in ANGELO'S house ====",
"==== SCENE III. A prison ====",
"==== SCENE IV. ANGELO'S house ====",
"==== ACT III. SCENE I. The prison ====",
"==== Scene II. The street before the prison ====",
"==== ACT IV. Scene I. The moated grange at Saint Duke's ====",
"==== SCENE II. The prison ====",
"==== SCENE III. The prison ====",
"==== SCENE IV. ANGELO'S house ====",
"==== SCENE V. Fields without the town ====",
"==== SCENE VI. A street near the city gate ====",
"==== ACT V. SCENE I. The city gate ====",
"== THE MERCHANT OF VENICE ==",
"==== Contents ====",
"==== Dramatis Personæ ====",
"==== SCENE: Partly at Venice, and partly at Belmont, the seat of Portia on the Continent ====",
"=== ACT I ===",
"==== SCENE I. Venice. A street. ====",
"==== SCENE II. Belmont. A room in Portia’s house. ====",
"==== SCENE III. Venice. A public place. ====",
"=== ACT II ===",
"==== SCENE I. Belmont. A room in Portia’s house. ====",
"==== SCENE II. Venice. A street. ====",
"==== SCENE III. The same. A room in Shylock’s house. ====",
"==== SCENE IV. The same. A street. ====",
"==== SCENE V. The same. Before Shylock’s house. ====",
"==== SCENE VI. The same. ====",
"==== SCENE VII. Belmont. A room in Portia’s house. ====",
"==== SCENE VIII. Venice. A street. ====",
"==== SCENE IX. Belmont. A room in Portia’s house. ====",
"=== ACT III ===",
"==== SCENE I. Venice. A street. ====",
"==== SCENE II. Belmont. A room in Portia’s house. ====",
"==== SCENE III. Venice. A street. ====",
"==== SCENE IV. Belmont. A room in Portia’s house. ====",
"==== SCENE V. The same. A garden. ====",
"=== ACT IV ===",
"==== SCENE I. Venice. A court of justice. ====",
"==== SCENE II. The same. A street. ====",
"=== ACT V ===",
"==== SCENE I. Belmont. The avenue to Portia’s house. ====",
"== THE MERRY WIVES OF WINDSOR ==",
"==== SCENE: Windsor, and the neighbourhood ====",
"==== ACT I. SCENE 1. ====",
"==== SCENE 2. ====",
"==== SCENE 3. ====",
"==== SCENE 4. ====",
"==== ACT II. SCENE 1. ====",
"==== SCENE 2. ====",
"==== SCENE 3. ====",
"==== ACT III SCENE 1. ====",
"==== SCENE 2. ====",
"==== SCENE 3. ====",
"==== SCENE 4. ====",
"==== SCENE 5. ====",
"==== ACT IV. SCENE I. ====",
"==== SCENE 2. ====",
"==== SCENE 3. ====",
"==== SCENE 4 ====",
"==== SCENE 5. ====",
"==== SCENE 6. ====",
"==== ACT V. SCENE 1. ====",
"==== SCENE 2. ====",
"==== SCENE 3. ====",
"==== SCENE 4. ====",
"==== SCENE 5. ====",
"== A MIDSUMMER NIGHT’S DREAM ==",
"==== Contents ====",
"==== Dramatis Personæ ====",
"==== SCENE: Athens, and a wood not far from it ====",
"=== ACT I ===",
"==== SCENE I. Athens. A room in the Palace of Theseus ====",
"==== SCENE II. The Same. A Room in a Cottage ====",
"=== ACT II ===",
"==== SCENE I. A wood near Athens ====",
"==== SCENE II. Another part of the wood ====",
"=== ACT III ===",
"==== SCENE I. The Wood. ====",
"==== SCENE II. Another part of the wood ====",
"=== ACT IV ===",
"==== SCENE I. The Wood ====",
"==== SCENE II. Athens. A Room in Quince’s House ====",
"=== ACT V ===",
"==== SCENE I. Athens. An Apartment in the Palace of Theseus ====",
"== MUCH ADO ABOUT NOTHING ==",
"==== Contents ====",
"==== Dramatis Personæ ====",
"==== SCENE. Messina. ====",
"=== ACT I ===",
"==== SCENE I. Before Leonato’s House. ====",
"==== SCENE II. A room in Leonato’s house. ====",
"==== SCENE III. Another room in Leonato’s house. ====",
"=== ACT II ===",
"==== SCENE I. A hall in Leonato’s house. ====",
"==== SCENE II. Another room in Leonato’s house. ====",
"==== SCENE III. Leonato’s Garden. ====",
"=== ACT III ===",
"==== SCENE I. Leonato’s Garden. ====",
"==== SCENE II. A Room in Leonato’s House. ====",
"==== Scene III. A Street. ====",
"==== Scene IV. A Room in Leonato’s House. ====",
"==== Scene V. Another Room in Leonato’s House. ====",
"=== ACT IV ===",
"==== SCENE I. The Inside of a Church. ====",
"==== Scene II. A Prison. ====",
"=== ACT V ===",
"==== SCENE I. Before Leonato’s House. ====",
"==== SCENE II. Leonato’s Garden. ====",
"==== SCENE III. The Inside of a Church. ====",
"==== SCENE IV. A Room in Leonato’s House. ====",
"== OTHELLO, THE MOOR OF VENICE ==",
"=== Contents ===",
"=== Dramatis Personæ ===",
"=== SCENE: The First Act in Venice; during the rest of the Play at a Seaport in Cyprus. ===",
"=== ACT I ===",
"==== SCENE I. Venice. A street. ====",
"==== SCENE II. Venice. Another street. ====",
"==== SCENE III. Venice. A council chamber. ====",
"=== ACT II ===",
"==== SCENE I. A seaport in Cyprus. A Platform. ====",
"==== SCENE II. A street. ====",
"==== SCENE III. A Hall in the Castle. ====",
"=== ACT III ===",
"==== SCENE I. Cyprus. Before the Castle. ====",
"==== SCENE II. Cyprus. A Room in the Castle. ====",
"==== SCENE III. Cyprus. The Garden of the Castle. ====",
"==== SCENE IV. Cyprus. Before the Castle. ====",
"=== ACT IV ===",
"==== SCENE I. Cyprus. Before the Castle. ====",
"==== SCENE II. Cyprus. A Room in the Castle. ====",
"==== SCENE III. Cyprus. Another Room in the Castle. ====",
"=== ACT V ===",
"==== SCENE I. Cyprus. A Street. ====",
"==== SCENE II. Cyprus. A Bedchamber in the castle. ====",
"== PERICLES, PRINCE OF TYRE ==",
"==== Contents ====",
"==== Dramatis Personæ ====",
"==== SCENE: Dispersedly in various countries. ====",
"=== ACT I ===",
"==== SCENE I. Antioch. A room in the palace. ====",
"==== SCENE II. Tyre. A room in the palace. ====",
"==== SCENE III. Tyre. An ante-chamber in the Palace. ====",
"==== SCENE IV. Tarsus. A room in the Governor’s house. ====",
"=== ACT II ===",
"==== SCENE I. Pentapolis. An open place by the seaside. ====",
"==== SCENE II. The same. A public way, or platform leading to the lists. A pavilion by the side of it for the reception of the King, Princess, Lords, etc. ====",
"==== SCENE III. The same. A hall of state: a banquet prepared. ====",
"==== SCENE IV. Tyre. A room in the Governor’s house. ====",
"==== SCENE V. Pentapolis. A room in the palace. ====",
"=== ACT III ===",
"==== SCENE I. ====",
"==== SCENE II. Ephesus. A room in Cerimon’s house. ====",
"==== SCENE III. Tarsus. A room in Cleon’s house. ====",
"==== SCENE IV. Ephesus. A room in Cerimon’s house. ====",
"=== ACT IV ===",
"==== Scene I. Tarsus. An open place near the seashore. ====",
"==== Scene II. Mytilene. A room in a brothel. ====",
"==== SCENE III. Tarsus. A room in Cleon’s house. ====",
"==== SCENE IV. ====",
"==== SCENE V. Mytilene. A street before the brothel. ====",
"==== SCENE VI. The same. A room in the brothel. ====",
"=== ACT V ===",
"==== SCENE I. On board Pericles’ ship, off Mytilene. A close pavilion on deck, with a curtain before it; Pericles within it, reclined on a couch. A barge lying beside the Tyrian vessel. ====",
"==== SCENE II. ====",
"==== SCENE III. The temple of Diana at Ephesus; Thaisa standing near the altar, as high priestess; a number of Virgins on each side; Cerimon and other inhabitants of Ephesus attending. ====",
"== KING RICHARD THE SECOND ==",
"==== DRAMATIS PERSONAE ====",
"==== SCENE: England and Wales ====",
"==== ACT I. SCENE I. London. The palace ====",
"==== SCENE 2. London. The DUKE OF LANCASTER'S palace ====",
"==== SCENE 3. The lists at Coventry ====",
"==== SCENE 4. London. The court ====",
"==== ACT II. SCENE I. London. Ely House ====",
"==== SCENE 2. Windsor Castle ====",
"==== SCENE 3. Gloucestershire ====",
"==== SCENE 4. A camp in Wales ====",
"==== ACT III. SCENE I. BOLINGBROKE'S camp at Bristol ====",
"==== SCENE 2. The coast of Wales. A castle in view ====",
"==== SCENE 3. Wales. Before Flint Castle ====",
"==== SCENE 4. The DUKE OF YORK's garden ====",
"==== ACT IV. SCENE 1. Westminster Hall ====",
"==== ACT V. SCENE 1. London. A street leading to the Tower ====",
"==== SCENE 2. The DUKE OF YORK's palace ====",
"==== SCENE 3. Windsor Castle ====",
"==== SCENE 4. Windsor Castle ====",
"==== SCENE 5. Pomfret Castle. The dungeon of the Castle ====",
"==== SCENE 6. Windsor Castle ====",
"== KING RICHARD THE THIRD ==",
"==== SCENE: England ====",
"==== ACT I. SCENE 1. ====",
"==== SCENE 2. ====",
"==== SCENE 3. ====",
"==== SCENE 4. ====",
"==== ACT II. SCENE 1. ====",
"==== SCENE 2. ====",
"==== SCENE 3. ====",
"==== SCENE 4. ====",
"==== ACT III. SCENE 1. ====",
"==== SCENE 2. ====",
"==== SCENE 3. ====",
"==== SCENE 4 ====",
"==== SCENE 5. ====",
"==== SCENE 6. ====",
"==== SCENE 7. ====",
"==== ACT IV. SCENE 1. ====",
"==== SCENE 2. ====",
"==== SCENE 3. ====",
"==== SCENE 4. ====",
"==== SCENE 5. ====",
"==== ACT V. SCENE 1. ====",
"==== SCENE 2. ====",
"==== SCENE 3. ====",
"==== SCENE 4. ====",
"==== SCENE 5. ====",
"== THE TRAGEDY OF ROMEO AND JULIET ==",
"==== Contents ====",
"==== Dramatis Personæ ====",
"==== SCENE. During the greater part of the Play in Verona; once, in the Fifth Act, at Mantua. ====",
"==== THE PROLOGUE ====",
"=== ACT I ===",
"==== SCENE I. A public place. ====",
"==== SCENE II. A Street. ====",
"==== SCENE III. Room in Capulet’s House. ====",
"==== SCENE IV. A Street. ====",
"==== SCENE V. A Hall in Capulet’s House. ====",
"=== ACT II ===",
"==== SCENE I. An open place adjoining Capulet’s Garden. ====",
"==== SCENE II. Capulet’s Garden. ====",
"==== SCENE III. Friar Lawrence’s Cell. ====",
"==== SCENE IV. A Street. ====",
"==== SCENE V. Capulet’s Garden. ====",
"==== SCENE VI. Friar Lawrence’s Cell. ====",
"=== ACT III ===",
"==== SCENE I. A public Place. ====",
"==== SCENE II. A Room in Capulet’s House. ====",
"==== SCENE III. Friar Lawrence’s cell. ====",
"==== SCENE IV. A Room in Capulet’s House. ====",
"==== SCENE V. An open Gallery to Juliet’s Chamber, overlooking the Garden. ====",
"=== ACT IV ===",
"==== SCENE I. Friar Lawrence’s Cell. ====",
"==== SCENE II. Hall in Capulet’s House. ====",
"==== SCENE III. Juliet’s Chamber. ====",
"==== SCENE IV. Hall in Capulet’s House. ====",
"==== SCENE V. Juliet’s Chamber; Juliet on the bed. ====",
"=== ACT V ===",
"==== SCENE I. Mantua. A Street. ====",
"==== SCENE II. Friar Lawrence’s Cell. ====",
"==== SCENE III. A churchyard; in it a Monument belonging to the Capulets. ====",
"== THE TAMING OF THE SHREW ==",
"==== Contents ====",
"==== Dramatis Personæ ====",
"==== SCENE: Sometimes in Padua, and sometimes in PETRUCHIO’S house in the country. ====",
"=== INDUCTION ===",
"==== SCENE I. Before an alehouse on a heath. ====",
"==== SCENE II. A bedchamber in the LORD’S house. ====",
"=== ACT I ===",
"==== SCENE I. Padua. A public place. ====",
"==== SCENE II. Padua. Before HORTENSIO’S house. ====",
"=== ACT II ===",
"==== SCENE I. Padua. A room in BAPTISTA’S house. ====",
"=== ACT III ===",
"==== SCENE I. Padua. A room in BAPTISTA’S house. ====",
"==== SCENE II. The same. Before BAPTISTA’S house. ====",
"=== ACT IV ===",
"==== SCENE I. A hall in PETRUCHIO’S country house. ====",
"==== SCENE II. Padua. Before BAPTISTA’S house. ====",
"==== SCENE III. A room in PETRUCHIO’S house. ====",
"==== SCENE IV. Padua. Before BAPTISTA’S house. ====",
"==== SCENE V. A public road. ====",
"=== ACT V ===",
"==== SCENE I. Padua. Before LUCENTIO’S house. ====",
"==== SCENE II. A room in LUCENTIO’S house. ====",
"== THE TEMPEST ==",
"=== Contents ===",
"=== Dramatis Personæ ===",
"==== SCENE: The sea, with a Ship; afterwards an Island. ====",
"=== ACT I ===",
"==== SCENE I. On a ship at sea; a tempestuous noise of thunder and lightning heard. ====",
"==== SCENE II. The Island. Before the cell of Prospero. ====",
"=== ACT II ===",
"==== SCENE I. Another part of the island. ====",
"==== SCENE II. Another part of the island. ====",
"=== ACT III ===",
"==== SCENE I. Before Prospero’s cell. ====",
"==== SCENE II. Another part of the island. ====",
"==== SCENE III. Another part of the island. ====",
"=== ACT IV ===",
"==== SCENE I. Before Prospero’s cell. ====",
"=== ACT V ===",
"==== SCENE I. Before the cell of Prospero. ====",
"==== EPILOGUE ====",
"== THE LIFE OF TIMON OF ATHENS ==",
"==== DRAMATIS PERSONAE ====",
"==== SCENE: Athens and the neighbouring woods ====",
"==== ACT I. SCENE I. Athens. TIMON'S house ====",
"==== SCENE II. A room of state in TIMON'S house ====",
"==== ACT II. SCENE I. A SENATOR'S house ====",
"==== SCENE II. Before TIMON'S house ====",
"==== ACT III. SCENE I. LUCULLUS' house ====",
"==== SCENE II. A public place ====",
"==== SCENE III. SEMPRONIUS' house ====",
"==== SCENE IV. A hall in TIMON'S house ====",
"==== SCENE V. The Senate House ====",
"==== SCENE VI. A banqueting hall in TIMON'S house ====",
"==== ACT IV. SCENE I. Without the walls of Athens ====",
"==== SCENE II. Athens. TIMON's house ====",
"==== SCENE III. The woods near the sea-shore. Before TIMON'S cave ====",
"==== ACT V. SCENE I. The woods. Before TIMON's cave ====",
"==== SCENE II. Before the walls of Athens ====",
"==== SCENE III. The TIMON's cave, and a rude tomb seen ====",
"==== SCENE IV. Before the walls of Athens ====",
"== THE TRAGEDY OF TITUS ANDRONICUS ==",
"==== SCENE: Rome and the neighbourhood ====",
"==== ACT 1. SCENE I. Rome. Before the Capitol ====",
"==== ACT II. SCENE I. Rome. Before the palace ====",
"==== SCENE II. A forest near Rome ====",
"==== SCENE III. A lonely part of the forest ====",
"==== SCENE IV. Another part of the forest ====",
"==== ACT III. SCENE I. Rome. A street ====",
"==== SCENE II. Rome. TITUS' house ====",
"==== ACT IV. SCENE I. Rome. TITUS' garden ====",
"==== SCENE II. Rome. The palace ====",
"==== SCENE III. Rome. A public place ====",
"==== SCENE IV. Rome. Before the palace ====",
"==== ACT V. SCENE I. Plains near Rome ====",
"==== SCENE II. Rome. Before TITUS' house ====",
"==== SCENE III. The court of TITUS' house ====",
"== THE HISTORY OF TROILUS AND CRESSIDA ==",
"==== Contents ====",
"==== Dramatis Personæ ====",
"==== SCENE: Troy and the Greek camp before it ====",
"==== PROLOGUE ====",
"=== ACT I ===",
"==== SCENE I. Troy. Before PRIAM’S palace. ====",
"==== SCENE II. Troy. A street. ====",
"==== SCENE III. The Grecian camp. Before AGAMEMNON’S tent. ====",
"=== ACT II ===",
"==== SCENE I. The Grecian camp. ====",
"==== SCENE II. Troy. PRIAM’S palace. ====",
"==== SCENE III. The Grecian camp. Before the tent of ACHILLES. ====",
"=== ACT III ===",
"==== SCENE I. Troy. PRIAM’S palace. ====",
"==== SCENE II. Troy. PANDARUS’ orchard. ====",
"==== SCENE III. The Greek camp. ====",
"=== ACT IV ===",
"==== SCENE I. Troy. A street. ====",
"==== SCENE II. Troy. The court of PANDARUS’ house. ====",
"==== SCENE III. Troy. A street before PANDARUS’ house. ====",
"==== SCENE IV. Troy. PANDARUS’ house. ====",
"==== SCENE V. The Grecian camp. Lists set out. ====",
"=== ACT V ===",
"==== SCENE I. The Grecian camp. Before the tent of ACHILLES. ====",
"==== SCENE II. The Grecian camp. Before CALCHAS’ tent. ====",
"==== SCENE III. Troy. Before PRIAM’S palace. ====",
"==== SCENE IV. The plain between Troy and the Grecian camp. ====",
"==== SCENE V. Another part of the plain. ====",
"==== SCENE VI. Another part of the plain. ====",
"==== SCENE VII. Another part of the plain. ====",
"==== SCENE VIII. Another part of the plain. ====",
"==== SCENE IX. Another part of the plain. ====",
"==== SCENE X. Another part of the plain. ====",
"== TWELFTH NIGHT: OR, WHAT YOU WILL ==",
"==== Contents ====",
"==== Dramatis Personæ ====",
"==== SCENE: A City in Illyria; and the Sea-coast near it. ====",
"=== ACT I. ===",
"==== SCENE I. An Apartment in the Duke’s Palace. ====",
"==== SCENE II. The sea-coast. ====",
"==== SCENE III. A Room in Olivia’s House. ====",
"==== SCENE IV. A Room in the Duke’s Palace. ====",
"==== SCENE V. A Room in Olivia’s House. ====",
"=== ACT II. ===",
"==== SCENE I. The sea-coast. ====",
"==== SCENE II. A street. ====",
"==== SCENE III. A Room in Olivia’s House. ====",
"==== SCENE IV. A Room in the Duke’s Palace. ====",
"==== SCENE V. Olivia’s garden. ====",
"=== ACT III. ===",
"==== SCENE I. Olivia’s garden. ====",
"==== SCENE II. A Room in Olivia’s House. ====",
"==== SCENE III. A street. ====",
"==== SCENE IV. Olivia’s garden. ====",
"=== ACT IV. ===",
"==== SCENE I. The Street before Olivia’s House. ====",
"==== SCENE II. A Room in Olivia’s House. ====",
"==== SCENE III. Olivia’s Garden. ====",
"=== ACT V. ===",
"==== SCENE I. The Street before Olivia’s House. ====",
"== THE TWO GENTLEMEN OF VERONA ==",
"==== DRAMATIS PERSONAE ====",
"==== SCENE: Verona; Milan; the frontiers of Mantua ====",
"==== ACT I. SCENE I. Verona. An open place ====",
"==== SCENE II. Verona. The garden Of JULIA'S house ====",
"==== SCENE III. Verona. ANTONIO'S house ====",
"==== ACT II. SCENE I. Milan. The DUKE'S palace ====",
"==== SCENE II. Verona. JULIA'S house ====",
"==== SCENE III. Verona. A street ====",
"==== SCENE IV. Milan. The DUKE'S palace ====",
"==== SCENE V. Milan. A street ====",
"==== SCENE VI. Milan. The DUKE's palace ====",
"==== SCENE VII. Verona. JULIA'S house ====",
"==== ACT III. SCENE I. Milan. The DUKE'S palace ====",
"==== SCENE II. Milan. The DUKE'S palace ====",
"==== ACT IV. SCENE I. The frontiers of Mantua. A forest ====",
"==== SCENE II. Milan. Outside the DUKE'S palace, under SILVIA'S window ====",
"==== SCENE III. Under SILVIA'S window ====",
"==== SCENE IV. Under SILVIA'S Window ====",
"==== ACT V. SCENE I. Milan. An abbey ====",
"==== SCENE II. Milan. The DUKE'S palace ====",
"==== SCENE III. The frontiers of Mantua. The forest ====",
"==== SCENE IV. Another part of the forest ====",
"== THE TWO NOBLE KINSMEN: ==",
"==== PROLOGUE. ====",
"==== ACT I ====",
"==== SCENE 1. (Athens. Before a temple.) ====",
"==== SCENE 2. (Thebs). ====",
"==== SCENE 3. (Before the gates of Athens.) ====",
"==== SCENE 4. (A field before Thebes. Dead bodies lying on the ground.) ====",
"==== SCENE 5. (Another part of the same.) ====",
"==== ACT II ====",
"==== SCENE 1. (Athens. A garden, with a prison in the background.) ====",
"==== SCENE 2. (The prison) ====",
"==== SCENE 3. (The country near Athens. ====",
"==== SCENE 4. (Athens. A room in the prison.) ====",
"==== SCENE 5. (An open place in Athens.) ====",
"==== SCENE 6. (Before the prison.) ====",
"==== ACT III ====",
"==== SCENE 1. (A forest near Athens.) ====",
"==== SCENE 2. (Another Part of the forest.) ====",
"==== SCENE 3. (Same as Scene I.) ====",
"==== SCENE 4. (Another part of the forest.) ====",
"==== SCENE 5. (Another part of the forest.) ====",
"==== SCENE 6. (Same as Scene III.) ====",
"==== ACT IV ====",
"==== SCENE 1. (Athens. A room in the prison.) ====",
"==== SCENE 2. (A Room in the Palace.) ====",
"==== SCENE 3. (A room in the prison.) ====",
"==== ACT V ====",
"==== SCENE 1. (Before the Temples of Mars, Venus, and Diana.) ====",
"==== SCENE 2. (A darkened Room in the Prison.) ====",
"==== SCENE 3. (A Place near the Lists.) ====",
"==== SCENE 4. (The same; a Block prepared.) ====",
"==== EPILOGUE ====",
"== THE WINTER’S TALE ==",
"=== Contents ===",
"=== Dramatis Personæ ===",
"==== Scene: Sometimes in Sicilia; sometimes in Bohemia. ====",
"=== ACT I ===",
"==== SCENE I. Sicilia. An Antechamber in Leontes’ Palace. ====",
"==== SCENE II. The same. A Room of State in the Palace. ====",
"=== ACT II ===",
"==== SCENE I. Sicilia. A Room in the Palace. ====",
"==== SCENE II. The same. The outer Room of a Prison. ====",
"==== SCENE III. The same. A Room in the Palace. ====",
"=== ACT III ===",
"==== SCENE I. Sicilia. A Street in some Town. ====",
"==== SCENE II. The same. A Court of Justice. ====",
"==== SCENE III. Bohemia. A desert Country near the Sea. ====",
"=== ACT IV ===",
"==== SCENE I. ====",
"==== SCENE II. Bohemia. A Room in the palace of Polixenes. ====",
"==== SCENE III. The same. A Road near the Shepherd’s cottage. ====",
"==== SCENE IV. The same. A Shepherd’s Cottage. ====",
"=== ACT V ===",
"==== SCENE I. Sicilia. A Room in the palace of Leontes. ====",
"==== SCENE II. The same. Before the Palace. ====",
"==== SCENE III. The same. A Room in Paulina’s house. ====",
"== A LOVER’S COMPLAINT ==",
"== THE PASSIONATE PILGRIM ==",
"===== I. =====",
"===== II. =====",
"===== III. =====",
"===== IV. =====",
"===== V. =====",
"===== VI. =====",
"===== VII. =====",
"===== VIII. =====",
"===== IX. =====",
"===== X. =====",
"===== XI. =====",
"===== XII. =====",
"===== XIII. =====",
"== THE PHOENIX AND THE TURTLE ==",
"== THE RAPE OF LUCRECE ==",
"==== TO THE ====",
"===== RIGHT HONOURABLE HENRY WRIOTHESLY, =====",
"===== EARL OF SOUTHAMPTON, AND BARON OF TITCHFIELD. =====",
"==== THE ARGUMENT. ====",
"== VENUS AND ADONIS ==",
"==== TO THE RIGHT HONOURABLE HENRY WRIOTHESLEY, EARL OF SOUTHAMPTON, and Baron of Titchfield. ====",
"==== VENUS AND ADONIS ====",
];
