var menulist=[
"== The Project Gutenberg eBook of The Brothers Karamazov ==",
"= The Brothers Karamazov =",
"==== Translated from the Russian of ====",
"== Fyodor Dostoyevsky ==",
"=== by Constance Garnett ===",
"==== The Lowell Press ====",
"==== New York ====",
"== Contents ==",
"== PART I ==",
"== Book I. The History Of A Family ==",
"== Chapter I. Fyodor Pavlovitch Karamazov ==",
"== Chapter II. He Gets Rid Of His Eldest Son ==",
"== Chapter III. The Second Marriage And The Second Family ==",
"== Chapter IV. The Third Son, Alyosha ==",
"== Chapter V. Elders ==",
"== Book II. An Unfortunate Gathering ==",
"== Chapter I. They Arrive At The Monastery ==",
"== Chapter II. The Old Buffoon ==",
"== Chapter III. Peasant Women Who Have Faith ==",
"== Chapter IV. A Lady Of Little Faith ==",
"== Chapter V. So Be It! So Be It! ==",
"== Chapter VI. Why Is Such A Man Alive? ==",
"== Chapter VII. A Young Man Bent On A Career ==",
"== Chapter VIII. The Scandalous Scene ==",
"== Book III. The Sensualists ==",
"== Chapter I. In The Servants’ Quarters ==",
"== Chapter II. Lizaveta ==",
"== Chapter III. The Confession Of A Passionate Heart&mdash;In Verse ==",
"== Chapter IV. The Confession Of A Passionate Heart&mdash;In Anecdote ==",
"== Chapter V. The Confession Of A Passionate Heart&mdash;“Heels Up” ==",
"== Chapter VI. Smerdyakov ==",
"== Chapter VII. The Controversy ==",
"== Chapter VIII. Over The Brandy ==",
"== Chapter IX. The Sensualists ==",
"== Chapter X. Both Together ==",
"== Chapter XI. Another Reputation Ruined ==",
"== PART II ==",
"== Book IV. Lacerations ==",
"== Chapter I. Father Ferapont ==",
"== Chapter II. At His Father’s ==",
"== Chapter III. A Meeting With The Schoolboys ==",
"== Chapter IV. At The Hohlakovs’ ==",
"== Chapter V. A Laceration In The Drawing‐Room ==",
"== Chapter VI. A Laceration In The Cottage ==",
"== Chapter VII. And In The Open Air ==",
"== Book V. Pro And Contra ==",
"== Chapter I. The Engagement ==",
"== Chapter II. Smerdyakov With A Guitar ==",
"== Chapter III. The Brothers Make Friends ==",
"== Chapter IV. Rebellion ==",
"== Chapter V. The Grand Inquisitor ==",
"== Chapter VI. For Awhile A Very Obscure One ==",
"== Chapter VII. “It’s Always Worth While Speaking To A Clever Man” ==",
"== Book VI. The Russian Monk ==",
"== Chapter I. Father Zossima And His Visitors ==",
"== Chapter II. The Duel ==",
"== Chapter III. Conversations And Exhortations Of Father Zossima ==",
"== PART III ==",
"== Book VII. Alyosha ==",
"== Chapter I. The Breath Of Corruption ==",
"== Chapter II. A Critical Moment ==",
"== Chapter III. An Onion ==",
"== Chapter IV. Cana Of Galilee ==",
"== Book VIII. Mitya ==",
"== Chapter I. Kuzma Samsonov ==",
"== Chapter II. Lyagavy ==",
"== Chapter III. Gold‐Mines ==",
"== Chapter IV. In The Dark ==",
"== Chapter V. A Sudden Resolution ==",
"== Chapter VI. “I Am Coming, Too!” ==",
"== Chapter VII. The First And Rightful Lover ==",
"== Chapter VIII. Delirium ==",
"== Book IX. The Preliminary Investigation ==",
"== Chapter I. The Beginning Of Perhotin’s Official Career ==",
"== Chapter II. The Alarm ==",
"== Chapter III. The Sufferings Of A Soul, The First Ordeal ==",
"== Chapter IV. The Second Ordeal ==",
"== Chapter V. The Third Ordeal ==",
"== Chapter VI. The Prosecutor Catches Mitya ==",
"== Chapter VII. Mitya’s Great Secret. Received With Hisses ==",
"== Chapter VIII. The Evidence Of The Witnesses. The Babe ==",
"== Chapter IX. They Carry Mitya Away ==",
"== PART IV ==",
"== Book X. The Boys ==",
"== Chapter I. Kolya Krassotkin ==",
"== Chapter II. Children ==",
"== Chapter III. The Schoolboy ==",
"== Chapter IV. The Lost Dog ==",
"== Chapter V. By Ilusha’s Bedside ==",
"== Chapter VI. Precocity ==",
"== Chapter VII. Ilusha ==",
"== Book XI. Ivan ==",
"== Chapter I. At Grushenka’s ==",
"== Chapter II. The Injured Foot ==",
"== Chapter III. A Little Demon ==",
"== Chapter IV. A Hymn And A Secret ==",
"== Chapter V. Not You, Not You! ==",
"== Chapter VI. The First Interview With Smerdyakov ==",
"== Chapter VII. The Second Visit To Smerdyakov ==",
"== Chapter VIII. The Third And Last Interview With Smerdyakov ==",
"== Chapter IX. The Devil. Ivan’s Nightmare ==",
"== Chapter X. “It Was He Who Said That” ==",
"== Book XII. A Judicial Error ==",
"== Chapter I. The Fatal Day ==",
"== Chapter II. Dangerous Witnesses ==",
"== Chapter III. The Medical Experts And A Pound Of Nuts ==",
"== Chapter IV. Fortune Smiles On Mitya ==",
"== Chapter V. A Sudden Catastrophe ==",
"== Chapter VI. The Prosecutor’s Speech. Sketches Of Character ==",
"== Chapter VII. An Historical Survey ==",
"== Chapter VIII. A Treatise On Smerdyakov ==",
"== Chapter IX. The Galloping Troika. The End Of The Prosecutor’s Speech. ==",
"== Chapter X. The Speech For The Defense. An Argument That Cuts Both Ways ==",
"== Chapter XI. There Was No Money. There Was No Robbery ==",
"== Chapter XII. And There Was No Murder Either ==",
"== Chapter XIII. A Corrupter Of Thought ==",
"== Chapter XIV. The Peasants Stand Firm ==",
"== EPILOGUE ==",
"== Chapter I. Plans For Mitya’s Escape ==",
"== Chapter II. For A Moment The Lie Becomes Truth ==",
"== Chapter III. Ilusha’s Funeral. The Speech At The Stone ==",
"== FOOTNOTES ==",
"== THE FULL PROJECT GUTENBERG LICENSE ==",
];
