var menulist=[
"== The Project Gutenberg eBook of The Wonderful Wizard of Oz ==",
"= The Wonderful Wizard of Oz =",
"== by L. Frank Baum ==",
"== Contents ==",
"== Introduction ==",
"== The Wonderful Wizard of Oz ==",
"== Chapter I The Cyclone ==",
"== Chapter II The Council with the Munchkins ==",
"== Chapter III How Dorothy Saved the Scarecrow ==",
"== Chapter IV The Road Through the Forest ==",
"== Chapter V The Rescue of the Tin Woodman ==",
"== Chapter VI The Cowardly Lion ==",
"== Chapter VII The Journey to the Great Oz ==",
"== Chapter VIII The Deadly Poppy Field ==",
"== Chapter IX The Queen of the Field Mice ==",
"== Chapter X The Guardian of the Gate ==",
"== Chapter XI The Wonderful City of Oz ==",
"== Chapter XII The Search for the Wicked Witch ==",
"== Chapter XIII The Rescue ==",
"== Chapter XIV The Winged Monkeys ==",
"== Chapter XV The Discovery of Oz, the Terrible ==",
"== Chapter XVI The Magic Art of the Great Humbug ==",
"== Chapter XVII How the Balloon Was Launched ==",
"== Chapter XVIII Away to the South ==",
"== Chapter XIX Attacked by the Fighting Trees ==",
"== Chapter XX The Dainty China Country ==",
"== Chapter XXI The Lion Becomes the King of Beasts ==",
"== Chapter XXII The Country of the Quadlings ==",
"== Chapter XXIII Glinda The Good Witch Grants Dorothy’s Wish ==",
"== Chapter XXIV Home Again ==",
"== THE FULL PROJECT GUTENBERG LICENSE ==",
];
