var menulist=[
"=== Chapter I  Hiram's Hospital ===",
"=== Chapter II  The Barchester Reformer ===",
"=== Chapter III  The Bishop of Barchester ===",
"=== Chapter IV  Hiram's Bedesmen ===",
"=== Chapter V  Dr Grantly Visits the Hospital ===",
"=== Chapter VI  The Warden's Tea Party ===",
"=== Chapter VII  The Jupiter ===",
"=== Chapter VIII  Plumstead Episcopi ===",
"=== Chapter IX  The Conference ===",
"=== Chapter X  Tribulation ===",
"=== Chapter XI  Iphigenia ===",
"=== Chapter XII  Mr Bold's Visit to Plumstead ===",
"=== Chapter XIII  The Warden's Decision ===",
"=== Chapter XIV  Mount Olympus ===",
"=== Chapter XV  Tom Towers, Dr Anticant, and Mr Sentiment ===",
"=== Chapter XVI  A Long Day in London ===",
"=== Chapter XVII  Sir Abraham Haphazard ===",
"=== Chapter XVIII  The Warden Is Very Obstinate ===",
"=== Chapter XIX  The Warden Resigns ===",
"=== Chapter XX  Farewell ===",
"=== Chapter XXI  Conclusion ===",
];
