var menulist=[
"== Chapter I. ==",
"=== Into the Primitive ===",
"== Chapter II. ==",
"=== The Law of Club and Fang ===",
"== Chapter III. ==",
"=== The Dominant Primordial Beast ===",
"== Chapter IV. ==",
"=== Who Has Won to Mastership ===",
"== Chapter V. ==",
"=== The Toil of Trace and Trail ===",
"== Chapter VI. ==",
"=== For the Love of a Man ===",
"== Chapter VII. ==",
"=== The Sounding of the Call ===",
];
