var menulist=[
"= The Complete Works of William Shakespeare =",
"=== by William Shakespeare ===",
"== Contents ==",
"= THE SONNETS =",
"==== THE END ====",
"= ALL’S WELL THAT ENDS WELL =",
"== SCENE: Rousillon; Paris; Florence; Marseilles ==",
"==== ACT I. SCENE 1. Rousillon. The COUNT'S palace ====",
"== ACT I. SCENE 2. Paris. The KING'S palace ==",
"== ACT I. SCENE 3. Rousillon. The COUNT'S palace ==",
"== ACT II. SCENE 1. Paris. The KING'S palace ==",
"== ACT II. SCENE 2. Rousillon. The COUNT'S palace ==",
"== ACT II. SCENE 3. Paris. The KING'S palace ==",
"== ACT II. SCENE 4. Paris. The KING'S palace ==",
"== ACT II. SCENE 5. Paris. The KING'S palace ==",
"== ACT III. SCENE 1. Florence. The DUKE's palace ==",
"== ACT III. SCENE 2. Rousillon. The COUNT'S palace ==",
"== ACT III. SCENE 3. Florence. Before the DUKE's palace ==",
"== ACT III. SCENE 4. Rousillon. The COUNT'S palace ==",
"== ACT III. SCENE 5. ==",
"== ACT III. SCENE 6. Camp before Florence ==",
"== ACT III. SCENE 7. Florence. The WIDOW'S house ==",
"== ACT IV. SCENE 1. Without the Florentine camp ==",
"== ACT IV. SCENE 2. Florence. The WIDOW'S house ==",
"== ACT IV. SCENE 3. The Florentine camp ==",
"== ACT IV SCENE 4. The WIDOW'S house ==",
"== ACT IV SCENE 5. Rousillon. The COUNT'S palace ==",
"== ACT V. SCENE 1. Marseilles. A street ==",
"== ACT V SCENE 2. Rousillon. The inner court of the COUNT'S palace ==",
"== ACT V SCENE 3. Rousillon. The COUNT'S palace ==",
"===== EPILOGUE EPILOGUE. =====",
"==== THE END ====",
"= THE TRAGEDY OF ANTONY AND CLEOPATRA =",
"=== DRAMATIS PERSONAE ===",
"== SCENE: The Roman Empire ==",
"===== ACT I. SCENE I. Alexandria. CLEOPATRA'S palace =====",
"== SCENE II. Alexandria. CLEOPATRA'S palace ==",
"== SCENE III. Alexandria. CLEOPATRA'S palace ==",
"== SCENE IV. Rome. CAESAR'S house ==",
"== SCENE V. Alexandria. CLEOPATRA'S palace ==",
"== ACT II. SCENE I. Messina. POMPEY'S house ==",
"== SCENE II. Rome. The house of LEPIDUS ==",
"== SCENE III. Rome. CAESAR'S house ==",
"== SCENE IV. Rome. A street ==",
"== SCENE V. Alexandria. CLEOPATRA'S palace ==",
"== SCENE VI. Near Misenum ==",
"==== THE END ====",
"= AS YOU LIKE IT =",
"=== DRAMATIS PERSONAE. ===",
"=== SCENE: OLIVER'S house; FREDERICK'S court; and the Forest of Arden ===",
"===== ACT I. SCENE I. Orchard of OLIVER'S house =====",
"== SCENE II. A lawn before the DUKE'S palace ==",
"== SCENE III. The DUKE's palace ==",
"=== ACT II. SCENE I. The Forest of Arden ===",
"== SCENE II. The DUKE'S palace ==",
"== SCENE III. Before OLIVER'S house ==",
"== SCENE IV. The Forest of Arden ==",
"==== SCENE V. Another part of the forest ====",
"== SCENE VI. The forest ==",
"== SCENE VII. The forest ==",
"== ACT III. SCENE I. The palace ==",
"== SCENE II. The forest ==",
"== SCENE III. The forest ==",
"== SCENE IV. The forest ==",
"== SCENE V. Another part of the forest ==",
"=== ACT IV. SCENE I. The forest ===",
"== SCENE II. The forest ==",
"===== SONG. =====",
"== SCENE III. The forest ==",
"=== ACT V. SCENE I. The forest ===",
"== SCENE II. The forest ==",
"== SCENE III. The forest ==",
"== SCENE IV. The forest ==",
"===== THE END =====",
"= THE COMEDY OF ERRORS =",
"==== DRAMATIS PERSONAE ====",
"===== A COURTEZAN =====",
"=== SCENE: Ephesus ===",
"== ACT I. SCENE 1 ==",
"==== SCENE 2 ====",
"== ACT II. SCENE 1 ==",
"==== SCENE 2 ====",
"=== ACT III. SCENE 1 ===",
"==== SCENE 2 ====",
"== ACT IV. SCENE 1 ==",
"==== SCENE 2 ====",
"==== SCENE 3 ====",
"==== SCENE 4 ====",
"== ACT V. SCENE 1 ==",
"==== THE END ====",
"= THE TRAGEDY OF CORIOLANUS =",
"=== SCENE: Rome and the neighbourhood; Corioli and the neighbourhood; Antium ===",
"=== ACT I. SCENE I. Rome. A street ===",
"== SCENE II. Corioli. The Senate House. ==",
"== SCENE III. Rome. MARCIUS' house ==",
"== SCENE IV. Before Corioli ==",
"== SCENE V. Within Corioli. A street ==",
"== SCENE VI. Near the camp of COMINIUS ==",
"== SCENE VII. The gates of Corioli ==",
"== SCENE VIII. A field of battle between the Roman and the Volscian camps ==",
"== SCENE IX. The Roman camp ==",
"== SCENE X. The camp of the Volsces ==",
"=== ACT II. SCENE I. Rome. A public place ===",
"== SCENE II. Rome. The Capitol ==",
"== SCENE III. Rome. The Forum ==",
"== ACT III. SCENE I. Rome. A street ==",
"== SCENE II. Rome. The house of CORIOLANUS ==",
"== SCENE III. Rome. The Forum ==",
"=== ACT IV. SCENE I. Rome. Before a gate of the city ===",
"== SCENE II. Rome. A street near the gate ==",
"== SCENE III. A highway between Rome and Antium ==",
"== SCENE IV. Antium. Before AUFIDIUS' house ==",
"== SCENE V. Antium. AUFIDIUS' house ==",
"== SCENE VI. Rome. A public place ==",
"== SCENE VII. A camp at a short distance from Rome ==",
"=== ACT V. SCENE I. Rome. A public place ===",
"== SCENE II. The Volscian camp before Rome ==",
"== SCENE III. The tent of CORIOLANUS ==",
"== SCENE IV. Rome. A public place ==",
"== SCENE V. Rome. A street near the gate ==",
"== SCENE VI. Corioli. A public place ==",
"==== THE END ====",
"= CYMBELINE =",
"===== APPARITIONS =====",
"== SCENE: Britain; Italy ==",
"=== ACT I. SCENE I. Britain. The garden of CYMBELINE'S palace ===",
"== SCENE II. Britain. A public place ==",
"== SCENE III. Britain. CYMBELINE'S palace ==",
"== SCENE IV. Rome. PHILARIO'S house ==",
"== SCENE V. Britain. CYMBELINE'S palace ==",
"== SCENE VI. Britain. The palace ==",
"=== ACT II. SCENE I. Britain. Before CYMBELINE'S palace ===",
"== SCENE II. Britain. IMOGEN'S bedchamber in CYMBELINE'S palace; a trunk in one corner ==",
"== SCENE III. CYMBELINE'S palace. An ante-chamber adjoining IMOGEN'S apartments ==",
"===== SONG =====",
"== SCENE IV. Rome. PHILARIO'S house ==",
"== SCENE V. Rome. Another room in PHILARIO'S house ==",
"=== ACT III. SCENE I. Britain. A hall in CYMBELINE'S palace ===",
"== SCENE II. Britain. Another room in CYMBELINE'S palace ==",
"== SCENE III. Wales. A mountainous country with a cave ==",
"== SCENE IV. Wales, near Milford Haven ==",
"== SCENE V. Britain. CYMBELINE'S palace ==",
"== SCENE VI. Wales. Before the cave of BELARIUS ==",
"== SCENE VII. Rome. A public place ==",
"== ACT IV. SCENE I. Wales. Near the cave of BELARIUS ==",
"== SCENE II. Wales. Before the cave of BELARIUS ==",
"===== SONG =====",
"== SCENE III. Britain. CYMBELINE'S palace ==",
"== SCENE IV. Wales. Before the cave of BELARIUS ==",
"=== ACT V. SCENE I. Britain. The Roman camp ===",
"== SCENE II. Britain. A field of battle between the British and Roman camps ==",
"== SCENE III. Another part of the field ==",
"== SCENE IV. Britain. A prison ==",
"== SCENE V. Britain. CYMBELINE'S tent ==",
"===== THE END =====",
"= THE TRAGEDY OF HAMLET, PRINCE OF DENMARK =",
"=== by William Shakespeare ===",
"=== Contents ===",
"=== Dramatis Personæ ===",
"==== SCENE. Elsinore. ====",
"=== ACT I ===",
"==== SCENE I. Elsinore. A platform before the Castle. ====",
"==== SCENE II. Elsinore. A room of state in the Castle. ====",
"==== SCENE III. A room in Polonius’s house. ====",
"==== SCENE IV. The platform. ====",
"==== SCENE V. A more remote part of the Castle. ====",
"=== ACT II ===",
"==== SCENE I. A room in Polonius’s house. ====",
"==== SCENE II. A room in the Castle. ====",
"=== ACT III ===",
"==== SCENE I. A room in the Castle. ====",
"==== SCENE II. A hall in the Castle. ====",
"==== SCENE III. A room in the Castle. ====",
"==== SCENE IV. Another room in the Castle. ====",
"=== ACT IV ===",
"==== SCENE I. A room in the Castle. ====",
"==== SCENE II. Another room in the Castle. ====",
"==== SCENE III. Another room in the Castle. ====",
"==== SCENE IV. A plain in Denmark. ====",
"==== SCENE V. Elsinore. A room in the Castle. ====",
"==== SCENE VI. Another room in the Castle. ====",
"==== SCENE VII. Another room in the Castle. ====",
"=== ACT V ===",
"==== SCENE I. A churchyard. ====",
"==== SCENE II. A hall in the Castle. ====",
"= THE FIRST PART OF KING HENRY THE FOURTH =",
"=== by William Shakespeare ===",
"=== Dramatis Personæ ===",
"==== SCENE. England and Wales. ====",
"=== ACT I ===",
"==== SCENE I. London. A Room in the Palace. ====",
"==== SCENE II. The same. An Apartment of Prince Henry’s. ====",
"==== SCENE III. The Same. A Room in the Palace. ====",
"=== ACT II ===",
"==== SCENE I. Rochester. An Inn-Yard. ====",
"==== SCENE II. The Road by Gads-hill. ====",
"==== SCENE III. Warkworth. A Room in the Castle. ====",
"==== SCENE IV. Eastcheap. A Room in the Boar’s-Head Tavern. ====",
"=== ACT III ===",
"==== SCENE I. Bangor. A Room in the Archdeacon’s House. ====",
"==== SCENE II. London. A Room in the Palace. ====",
"==== SCENE III. Eastcheap. A Room in the Boar’s-Head Tavern. ====",
"=== ACT IV ===",
"==== SCENE I. The Rebel Camp near Shrewsbury. ====",
"==== SCENE II. A public Road near Coventry. ====",
"==== SCENE III. The Rebel Camp near Shrewsbury. ====",
"==== SCENE IV. York. A Room in the Archbishop’s Palace. ====",
"=== ACT V ===",
"==== SCENE I. The King’s Camp near Shrewsbury. ====",
"==== SCENE II. The Rebel Camp. ====",
"==== SCENE III. Plain between the Camps. ====",
"==== SCENE IV. Another Part of the Field. ====",
"==== SCENE V. Another Part of the Field. ====",
"= THE SECOND PART OF KING HENRY THE FOURTH =",
"===== SCENE: England =====",
"=== ACT I. SCENE I. Warkworth. Before NORTHUMBERLAND'S Castle ===",
"== SCENE II. London. A street ==",
"== SCENE III. York. The ARCHBISHOP'S palace ==",
"=== ACT II. SCENE I. London. A street ===",
"== SCENE II. London. Another street ==",
"== SCENE III. Warkworth. Before the castle ==",
"== SCENE IV. London. The Boar's Head Tavern in Eastcheap ==",
"=== ACT III. SCENE I. Westminster. The palace ===",
"== SCENE II. Gloucestershire. Before Justice, SHALLOW'S house ==",
"=== ACT IV. SCENE I. Yorkshire. Within the Forest of Gaultree ===",
"== SCENE II. Another part of the forest ==",
"== SCENE III. Another part of the forest ==",
"== SCENE IV. Westminster. The Jerusalem Chamber ==",
"== SCENE V. Westminster. Another chamber ==",
"=== ACT V. SCENE I. Gloucestershire. SHALLOW'S house ===",
"== SCENE II. Westminster. The palace ==",
"== SCENE III. Gloucestershire. SHALLOW'S orchard ==",
"== SCENE IV. London. A street ==",
"== SCENE V. Westminster. Near the Abbey ==",
"===== EPILOGUE EPILOGUE. =====",
"==== THE END ====",
"= THE LIFE OF KING HENRY THE FIFTH =",
"=== DRAMATIS PERSONAE ===",
"===== BOY A HERALD =====",
"==== SCENE: England and France ====",
"===== PROLOGUE PROLOGUE. =====",
"=== ACT I. SCENE I. London. An ante-chamber in the KING'S palace ===",
"== SCENE II. London. The Presence Chamber in the KING'S palace ==",
"=== ACT II. PROLOGUE. ===",
"== SCENE I. London. Before the Boar's Head Tavern, Eastcheap ==",
"== SCENE II. Southampton. A council-chamber ==",
"== SCENE III. Eastcheap. Before the Boar's Head tavern ==",
"== SCENE IV. France. The KING'S palace ==",
"=== ACT III. PROLOGUE. ===",
"=== SCENE I. France. Before Harfleur ===",
"== SCENE II. Before Harfleur ==",
"== SCENE III. Before the gates of Harfleur ==",
"== SCENE IV. Rouen. The FRENCH KING'S palace ==",
"== SCENE V. The FRENCH KING'S palace ==",
"== SCENE VI. The English camp in Picardy ==",
"== SCENE VII. The French camp near Agincourt ==",
"=== ACT IV. PROLOGUE. ===",
"== SCENE I. France. The English camp at Agincourt ==",
"== SCENE II. The French camp ==",
"== SCENE III. The English camp ==",
"== SCENE IV. The field of battle ==",
"== SCENE V. Another part of the field of battle ==",
"== SCENE VI. Another part of the field ==",
"== SCENE VII. Another part of the field ==",
"== SCENE VIII. Before KING HENRY'S PAVILION ==",
"=== ACT V. PROLOGUE. ===",
"== SCENE I. France. The English camp ==",
"== SCENE II. France. The FRENCH KING'S palace ==",
"===== EPILOGUE EPILOGUE. =====",
"===== THE END =====",
"= THE FIRST PART OF HENRY THE SIXTH =",
"=== SCENE: England and France ===",
"==== ACT I. SCENE 1. ====",
"== SCENE 2. ==",
"== SCENE 3. ==",
"== SCENE 4. ==",
"== SCENE 5. ==",
"=== SCENE 6. ===",
"===== ORLEANS =====",
"=== ACT II. SCENE 1. ===",
"== SCENE 2. ==",
"== SCENE 3. ==",
"== SCENE 4. ==",
"== SCENE 5. ==",
"=== ACT III. SCENE 1. ===",
"== SCENE 2. ==",
"== SCENE 3. ==",
"== SCENE 4. ==",
"=== ACT IV. SCENE 1. ===",
"== SCENE 2. ==",
"== SCENE 3. ==",
"== SCENE 4. ==",
"==== SCENE 5. ====",
"== SCENE 6. ==",
"== SCENE 7. ==",
"=== ACT V. SCENE 1. ===",
"==== SCENE 2. ====",
"== SCENE 3. ==",
"== SCENE 4. ==",
"== SCENE 5. ==",
"==== THE END ====",
"= THE SECOND PART OF KING HENRY THE SIXTH =",
"=== SCENE: England ===",
"==== ACT I. SCENE I. London. The palace ====",
"== SCENE II. The DUKE OF GLOUCESTER'S house ==",
"== SCENE III. London. The palace ==",
"== SCENE IV. London. The DUKE OF GLOUCESTER'S garden ==",
"=== ACT II. SCENE I. Saint Albans ===",
"== SCENE II. London. The DUKE OF YORK'S garden ==",
"== SCENE III. London. A hall of justice ==",
"== SCENE IV. London. A street ==",
"=== ACT III. SCENE I. The Abbey at Bury St. Edmunds ===",
"== SCENE II. Bury St. Edmunds. A room of state ==",
"== SCENE III. London. CARDINAL BEAUFORT'S bedchamber ==",
"=== ACT IV. SCENE I. The coast of Kent ===",
"== SCENE II. Blackheath ==",
"== SCENE III. Another part of Blackheath ==",
"== SCENE IV. London. The palace ==",
"== SCENE V. London. The Tower ==",
"== SCENE VI. London. Cannon street ==",
"== SCENE VII. London. Smithfield ==",
"== SCENE VIII. Southwark ==",
"== SCENE IX. Killing, worth Castle ==",
"== SCENE X. Kent. Iden's garden ==",
"=== ACT V. SCENE I. Fields between Dartford and Blackheath ===",
"== SCENE II. Saint Albans ==",
"== SCENE III. Fields near Saint Albans ==",
"==== THE END ====",
"= THE THIRD PART OF KING HENRY THE SIXTH =",
"=== DRAMATIS PERSONAE ===",
"=== SCENE: England and France ===",
"===== ACT I. SCENE I. London. The Parliament House =====",
"== SCENE II. Sandal Castle, near Wakefield, in Yorkshire ==",
"== SCENE III. Field of battle between Sandal Castle and Wakefield ==",
"== SCENE IV. Another part of the field ==",
"=== ACT II. SCENE I. A plain near Mortimer's Cross in Herefordshire ===",
"== SCENE II. Before York ==",
"== SCENE III. A field of battle between Towton and Saxton, in Yorkshire ==",
"== SCENE IV. Another part of the field ==",
"== SCENE V. Another part of the field ==",
"== SCENE VI. Another part of the field ==",
"=== ACT III. SCENE I. A chase in the north of England ===",
"=== SCENE II. London. The palace ===",
"== SCENE III. France. The KING'S palace ==",
"=== ACT IV. SCENE I. London. The palace ===",
"== SCENE II. A plain in Warwickshire ==",
"=== SCENE III. Edward's camp, near Warwick ===",
"== SCENE IV. London. The palace ==",
"== SCENE V. A park near Middleham Castle in Yorkshire ==",
"== SCENE VI. London. The Tower ==",
"== SCENE VII. Before York ==",
"== SCENE VIII. London. The palace ==",
"=== ACT V. SCENE I. Coventry ===",
"== SCENE II. A field of battle near Barnet ==",
"== SCENE III. Another part of the field ==",
"== SCENE IV. Plains wear Tewksbury ==",
"== SCENE V. Another part of the field ==",
"== SCENE VI. London. The Tower ==",
"== SCENE VII. London. The palace ==",
"==== THE END ====",
"= KING HENRY THE EIGHTH =",
"==== DRAMATIS PERSONAE ====",
"===== SCENE: =====",
"=== KING HENRY THE EIGHTH ===",
"===== THE PROLOGUE. =====",
"=== ACT I. SCENE 1. ===",
"== ACT I. SCENE 2. ==",
"== ACT I. SCENE 3. ==",
"== ACT I. SCENE 4. ==",
"=== ACT II. SCENE 1. ===",
"== ACT II. SCENE 2. ==",
"== ACT II. SCENE 3. ==",
"== ACT II. SCENE 4. ==",
"=== ACT III. SCENE 1. ===",
"===== SONG =====",
"=== ACT III.SCENE 2. ===",
"=== ACT IV. SCENE 1. ===",
"===== THE ORDER OF THE CORONATION. =====",
"== ACT IV. SCENE 2. ==",
"===== THE VISION. =====",
"=== ACT V. SCENE 1. ===",
"== ACT V. SCENE 2. ==",
"== ACT V. SCENE 3. ==",
"== ACT V. SCENE 4. ==",
"== ACT V. SCENE 5. ==",
"===== KING_HENRY_VIII|EPILOGUE THE EPILOGUE. =====",
"===== THE END =====",
"= KING JOHN =",
"=== DRAMATIS PERSONAE ===",
"=== SCENE: England and France ===",
"=== ACT I. SCENE 1 ===",
"=== ACT II. SCENE 1 ===",
"=== ACT III. SCENE 1. ===",
"== SCENE 2. ==",
"== SCENE 3. ==",
"== SCENE 4. ==",
"=== ACT IV. SCENE 1. ===",
"== SCENE 2. ==",
"== SCENE 3. ==",
"=== ACT V. SCENE 1. England. KING JOHN'S palace ===",
"== SCENE 2. England. The DAUPHIN'S camp at Saint Edmundsbury ==",
"== SCENE 3. ==",
"== SCENE 4. ==",
"== SCENE 5. ==",
"== SCENE 6. ==",
"== SCENE 7. ==",
"===== THE END =====",
"= THE TRAGEDY OF JULIUS CAESAR =",
"=== SCENE: Rome, the conspirators' camp near Sardis, and the plains of Philippi. ===",
"==== ACT I. SCENE I. Rome. A street. ====",
"== SCENE II. A public place. ==",
"== SCENE III. A street. Thunder and lightning. ==",
"=== ACT II. SCENE I. ===",
"== SCENE II. Caesar's house. Thunder and lightning. ==",
"== SCENE III. A street near the Capitol. ==",
"== SCENE IV. Another part of the same street, before the house of Brutus. ==",
"=== ACT III. SCENE I. Rome. Before the Capitol; the Senate sitting above. A crowd of people, among them Artemidorus and the Soothsayer. ===",
"== SCENE II. The Forum. ==",
"== SCENE III. A street. ==",
"=== ACT IV. SCENE I. A house in Rome. Antony, Octavius, and Lepidus, seated at a table. ===",
"== SCENE II. Camp near Sardis. Before Brutus' tent. Drum. ==",
"== SCENE III. Brutus' tent. ==",
"=== ACT V. SCENE I. The plains of Philippi. ===",
"== SCENE II. The field of battle. ==",
"== SCENE III. Another part of the field. ==",
"== SCENE IV. Another part of the field. ==",
"== SCENE V. Another part of the field. ==",
"==== THE END ====",
"= THE TRAGEDY OF KING LEAR =",
"=== by William Shakespeare ===",
"=== Contents ===",
"=== Dramatis Personæ ===",
"==== SCENE: Britain. ====",
"=== ACT I ===",
"==== SCENE I. A Room of State in King Lear’s Palace. ====",
"==== SCENE II. A Hall in the Earl of Gloucester’s Castle. ====",
"==== SCENE III. A Room in the Duke of Albany’s Palace. ====",
"==== SCENE IV. A Hall in Albany’s Palace. ====",
"==== SCENE V. Court before the Duke of Albany’s Palace. ====",
"=== ACT II ===",
"==== SCENE I. A court within the Castle of the Earl of Gloucester. ====",
"==== SCENE II. Before Gloucester’s Castle. ====",
"==== SCENE III. The open Country. ====",
"==== SCENE IV. Before Gloucester’s Castle; Kent in the stocks. ====",
"=== ACT III ===",
"==== SCENE I. A Heath. ====",
"==== SCENE II. Another part of the heath. ====",
"==== SCENE III. A Room in Gloucester’s Castle. ====",
"==== SCENE IV. A part of the Heath with a Hovel. ====",
"==== SCENE V. A Room in Gloucester’s Castle. ====",
"==== SCENE VI. A Chamber in a Farmhouse adjoining the Castle. ====",
"==== SCENE VII. A Room in Gloucester’s Castle. ====",
"=== ACT IV ===",
"==== SCENE I. The heath. ====",
"==== SCENE II. Before the Duke of Albany’s Palace. ====",
"==== SCENE III. The French camp near Dover. ====",
"==== SCENE IV. The French camp. A Tent. ====",
"==== SCENE V. A Room in Gloucester’s Castle. ====",
"==== SCENE VI. The country near Dover. ====",
"==== SCENE VII. A Tent in the French Camp. ====",
"=== ACT V ===",
"==== SCENE I. The Camp of the British Forces near Dover. ====",
"==== SCENE II. A field between the two Camps. ====",
"==== SCENE III. The British Camp near Dover. ====",
"= LOVE’S LABOUR’S LOST =",
"=== SCENE: Navarre ===",
"==== ACT I. SCENE I. Navarre. The King's park ====",
"== SCENE II. The park ==",
"=== ACT II. SCENE II. The park ===",
"=== ACT III. SCENE I. The park ===",
"=== ACT IV. SCENE I. The park ===",
"== SCENE II. The park ==",
"== SCENE III. The park ==",
"=== ACT V. SCENE I. The park ===",
"== SCENE II. The park ==",
"==== WINTER ====",
"===== THE END =====",
"= THE TRAGEDY OF MACBETH =",
"=== SCENE: Scotland and England ===",
"==== ACT I. SCENE I. A desert place. Thunder and lightning. ====",
"== SCENE II. A camp near Forres. Alarum within. ==",
"== SCENE III. A heath. Thunder. ==",
"== SCENE IV. Forres. The palace. ==",
"== SCENE V. Inverness. Macbeth's castle. ==",
"== SCENE VI. Before Macbeth's castle. Hautboys and torches. ==",
"== SCENE VII Macbeth's castle. Hautboys and torches. ==",
"=== ACT II. SCENE I. Inverness. Court of Macbeth's castle. ===",
"== SCENE II. The same. ==",
"== SCENE III. The same. ==",
"== SCENE IV. Outside Macbeth's castle. ==",
"=== ACT III. SCENE I. Forres. The palace. ===",
"== SCENE II. The palace. ==",
"== SCENE III. A park near the palace. ==",
"== SCENE IV. A Hall in the palace. A banquet prepared. ==",
"== SCENE V. A heath. Thunder. ==",
"== SCENE VI. Forres. The palace. ==",
"=== ACT IV. SCENE I. A cavern. In the middle, a boiling cauldron. Thunder. ===",
"== SCENE II. Fife. Macduff's castle. ==",
"== SCENE III. England. Before the King's palace. ==",
"=== ACT V. SCENE I. Dunsinane. Anteroom in the castle. ===",
"== SCENE II. The country near Dunsinane. Drum and colors. ==",
"== SCENE III. Dunsinane. A room in the castle. ==",
"== SCENE IV. Country near Birnam Wood. Drum and colors. ==",
"== SCENE V. Dunsinane. Within the castle. ==",
"== SCENE VI. Dunsinane. Before the castle. ==",
"== SCENE VII. Dunsinane. Before the castle. Alarums. ==",
"== SCENE VIII. Another part of the field. ==",
"== SCENE IX. ==",
"= MEASURE FOR MEASURE =",
"=== DRAMATIS PERSONAE ===",
"=== SCENE: Vienna ===",
"==== ACT I. SCENE I. The DUKE'S palace ====",
"== SCENE II. A street ==",
"== SCENE III. A monastery ==",
"== SCENE IV. A nunnery ==",
"=== ACT II. Scene I. A hall in ANGELO'S house ===",
"== SCENE II. Another room in ANGELO'S house ==",
"== SCENE III. A prison ==",
"== SCENE IV. ANGELO'S house ==",
"=== ACT III. SCENE I. The prison ===",
"== Scene II. The street before the prison ==",
"== ACT IV. Scene I. The moated grange at Saint Duke's ==",
"===== SONG =====",
"== SCENE II. The prison ==",
"== SCENE III. The prison ==",
"== SCENE IV. ANGELO'S house ==",
"== SCENE V. Fields without the town ==",
"== SCENE VI. A street near the city gate ==",
"=== ACT V. SCENE I. The city gate ===",
"===== THE END =====",
"= THE MERCHANT OF VENICE =",
"=== DRAMATIS PERSONAE ===",
"=== SCENE: Venice, and PORTIA'S house at Belmont ===",
"==== ACT I. SCENE I. Venice. A street ====",
"=== SCENE II. Belmont. PORTIA'S house ===",
"== SCENE III. Venice. A public place ==",
"=== ACT II. SCENE I. Belmont. PORTIA'S house ===",
"== SCENE II. Venice. A street ==",
"== SCENE III. Venice. SHYLOCK'S house ==",
"== SCENE IV. Venice. A street ==",
"== SCENE V. Venice. Before SHYLOCK'S house ==",
"== SCENE VI. Venice. Before SHYLOCK'S house ==",
"== SCENE VII. Belmont. PORTIA's house ==",
"== SCENE VIII. Venice. A street ==",
"== SCENE IX. Belmont. PORTIA'S house ==",
"=== ACT III. SCENE I. Venice. A street ===",
"== SCENE II. Belmont. PORTIA'S house ==",
"===== A SONG =====",
"== SCENE III. Venice. A street ==",
"== SCENE IV. Belmont. PORTIA'S house ==",
"== SCENE V. Belmont. The garden ==",
"== ACT IV. SCENE I. Venice. The court of justice ==",
"== SCENE II. Venice. A street ==",
"== ACT V. SCENE I. Belmont. The garden before PORTIA'S house ==",
"===== THE END =====",
"= THE MERRY WIVES OF WINDSOR =",
"=== SCENE: Windsor, and the neighbourhood ===",
"=== ACT I. SCENE 1. ===",
"== SCENE 2. ==",
"== SCENE 3. ==",
"== SCENE 4. ==",
"=== ACT II. SCENE 1. ===",
"== SCENE 2. ==",
"== SCENE 3. ==",
"=== ACT III SCENE 1. ===",
"=== SCENE 2. ===",
"=== SCENE 3. ===",
"== SCENE 4. ==",
"== SCENE 5. ==",
"=== ACT IV. SCENE I. ===",
"== SCENE 2. ==",
"== SCENE 3. ==",
"== SCENE 4 ==",
"== SCENE 5. ==",
"== SCENE 6. ==",
"=== ACT V. SCENE 1. ===",
"== SCENE 2. ==",
"== SCENE 3. ==",
"== SCENE 4. ==",
"== SCENE 5. ==",
"===== THE END =====",
"= A MIDSUMMER NIGHT’S DREAM =",
"=== DRAMATIS PERSONAE ===",
"=== SCENE: Athens and a wood near it ===",
"==== ACT I. SCENE I. Athens. The palace of THESEUS ====",
"== SCENE II. Athens. QUINCE'S house ==",
"=== ACT II. SCENE I. A wood near Athens ===",
"== SCENE II. Another part of the wood ==",
"=== ACT III. SCENE I. The wood. TITANIA lying asleep ===",
"== SCENE II. Another part of the wood ==",
"=== ACT IV. SCENE I. The wood. LYSANDER, DEMETRIUS, HELENA, and HERMIA, lying asleep ===",
"== SCENE II. Athens. QUINCE'S house ==",
"=== ACT V. SCENE I. Athens. The palace of THESEUS ===",
"===== THE END =====",
"= MUCH ADO ABOUT NOTHING =",
"=== by William Shakespeare ===",
"=== Contents ===",
"=== Dramatis Personæ ===",
"==== SCENE. Messina. ====",
"=== ACT I ===",
"==== SCENE I. Before LEONATO’S House. ====",
"==== SCENE II. A room in LEONATO’S house. ====",
"==== SCENE III. Another room in LEONATO’S house. ====",
"=== ACT II ===",
"==== SCENE I. A hall in LEONATO’S house. ====",
"==== SCENE II. Another room in LEONATO’S house. ====",
"==== SCENE III. LEONATO’S Garden. ====",
"=== ACT III ===",
"==== SCENE I. LEONATO’S Garden. ====",
"==== SCENE II. A Room in LEONATO’S House. ====",
"==== Scene III. A Street. ====",
"==== Scene IV. A Room in LEONATO’S House. ====",
"==== Scene V. Another Room in LEONATO’S House. ====",
"=== ACT IV ===",
"==== SCENE I. The Inside of a Church. ====",
"==== Scene II. A Prison. ====",
"=== ACT V ===",
"==== SCENE I. Before LEONATO’S House. ====",
"==== SCENE II. LEONATO’S Garden. ====",
"==== SCENE III. The Inside of a Church. ====",
"==== SCENE IV. A Room in LEONATO’S House. ====",
"= THE TRAGEDY OF OTHELLO, MOOR OF VENICE =",
"=== SCENE: Venice and Cyprus ===",
"===== ACT I. SCENE I. Venice. A street. =====",
"== SCENE II. Another street. ==",
"== SCENE III. A council chamber. The Duke and Senators sitting at a table; Officers attending. ==",
"=== ACT II. SCENE I. A seaport in Cyprus. An open place near the quay. ===",
"== SCENE II. A street. ==",
"== SCENE III. A hall in the castle. ==",
"=== ACT III. SCENE I. Before the castle. ===",
"== SCENE II. A room in the castle. ==",
"== SCENE III. The garden of the castle. ==",
"== SCENE IV. Before the castle. ==",
"=== ACT IV. SCENE I. Cyprus. Before the castle. ===",
"== SCENE II. A room in the castle. ==",
"== SCENE III. Another room in the castle. ==",
"=== ACT V. SCENE I. Cyprus. A street. ===",
"== SCENE II. A bedchamber in the castle. Desdemona in bed asleep; a light burning. ==",
"==== THE END ====",
"= PERICLES, PRINCE OF TYRE =",
"=== by William Shakespeare ===",
"=== Contents ===",
"=== Dramatis Personæ ===",
"==== SCENE: Dispersedly in various countries. ====",
"=== ACT I ===",
"==== SCENE I. Antioch. A room in the palace. ====",
"==== SCENE II. Tyre. A room in the palace. ====",
"==== SCENE III. Tyre. An ante-chamber in the Palace. ====",
"==== SCENE IV. Tarsus. A room in the Governor’s house. ====",
"=== ACT II ===",
"==== SCENE I. Pentapolis. An open place by the seaside. ====",
"==== SCENE II. The same. A public way, or platform leading to the lists. A pavilion by the side of it for the reception of the King, Princess, Lords, etc. ====",
"==== SCENE III. The same. A hall of state: a banquet prepared. ====",
"==== SCENE IV. Tyre. A room in the Governor’s house. ====",
"==== SCENE V. Pentapolis. A room in the palace. ====",
"=== ACT III ===",
"==== SCENE I. ====",
"==== SCENE II. Ephesus. A room in Cerimon’s house. ====",
"==== SCENE III. Tarsus. A room in Cleon’s house. ====",
"==== SCENE IV. Ephesus. A room in Cerimon’s house. ====",
"=== ACT IV ===",
"==== Scene I. Tarsus. An open place near the seashore. ====",
"==== Scene II. Mytilene. A room in a brothel. ====",
"==== SCENE III. Tarsus. A room in Cleon’s house. ====",
"==== SCENE IV. ====",
"==== SCENE V. Mytilene. A street before the brothel. ====",
"==== SCENE VI. The same. A room in the brothel. ====",
"=== ACT V ===",
"==== SCENE I. On board Pericles’ ship, off Mytilene. A close pavilion on deck, with a curtain before it; Pericles within it, reclined on a couch. A barge lying beside the Tyrian vessel. ====",
"==== SCENE II. ====",
"==== SCENE III. The temple of Diana at Ephesus; Thaisa standing near the altar, as high priestess; a number of Virgins on each side; Cerimon and other inhabitants of Ephesus attending. ====",
"= KING RICHARD THE SECOND =",
"=== DRAMATIS PERSONAE ===",
"=== SCENE: England and Wales ===",
"==== ACT I. SCENE I. London. The palace ====",
"== SCENE 2. London. The DUKE OF LANCASTER'S palace ==",
"== SCENE 3. The lists at Coventry ==",
"== SCENE 4. London. The court ==",
"=== ACT II. SCENE I. London. Ely House ===",
"== SCENE 2. Windsor Castle ==",
"== SCENE 3. Gloucestershire ==",
"== SCENE 4. A camp in Wales ==",
"=== ACT III. SCENE I. BOLINGBROKE'S camp at Bristol ===",
"== SCENE 2. The coast of Wales. A castle in view ==",
"== SCENE 3. Wales. Before Flint Castle ==",
"== SCENE 4. The DUKE OF YORK's garden ==",
"=== ACT IV. SCENE 1. Westminster Hall ===",
"=== ACT V. SCENE 1. London. A street leading to the Tower ===",
"== SCENE 2. The DUKE OF YORK's palace ==",
"== SCENE 3. Windsor Castle ==",
"== SCENE 4. Windsor Castle ==",
"== SCENE 5. Pomfret Castle. The dungeon of the Castle ==",
"== SCENE 6. Windsor Castle ==",
"===== THE END =====",
"= KING RICHARD THE THIRD =",
"===== EDWARD THE FOURTH =====",
"=== SCENE: England ===",
"=== ACT I. SCENE 1. ===",
"== SCENE 2. ==",
"== SCENE 3. ==",
"== SCENE 4. ==",
"=== ACT II. SCENE 1. ===",
"== SCENE 2. ==",
"== SCENE 3. ==",
"== SCENE 4. ==",
"=== ACT III. SCENE 1. ===",
"== SCENE 2. ==",
"== SCENE 3. ==",
"== SCENE 4 ==",
"== SCENE 5. ==",
"== SCENE 6. ==",
"== SCENE 7. ==",
"=== ACT IV. SCENE 1. ===",
"== SCENE 2. ==",
"== SCENE 3. ==",
"== SCENE 4. ==",
"== SCENE 5. ==",
"=== ACT V. SCENE 1. ===",
"== SCENE 2. ==",
"== SCENE 3. ==",
"== SCENE 4. ==",
"== SCENE 5. ==",
"===== THE END =====",
"= THE TRAGEDY OF ROMEO AND JULIET =",
"=== by William Shakespeare ===",
"== PERSONS REPRESENTED ==",
"=== SCENE.&mdash;During the greater part of the Play in Verona; once, in the Fifth Act, at Mantua. ===",
"===== THE PROLOGUE =====",
"==== ACT I. ====",
"===== Scene I. A public place. =====",
"=== Scene II. A Street. ===",
"=== Scene III. Room in Capulet's House. ===",
"=== Scene IV. A Street. ===",
"=== Scene V. A Hall in Capulet's House. ===",
"=== ACT II. ===",
"===== Scene I. An open place adjoining Capulet's Garden. =====",
"=== Scene II. Capulet's Garden. ===",
"=== Scene III. Friar Lawrence's Cell. ===",
"=== Scene IV. A Street. ===",
"=== Scene V. Capulet's Garden. ===",
"=== Scene VI. Friar Lawrence's Cell. ===",
"=== ACT III. ===",
"===== Scene I. A public Place. =====",
"=== Scene II. A Room in Capulet's House. ===",
"=== Scene III. Friar Lawrence's cell. ===",
"=== Scene IV. A Room in Capulet's House. ===",
"=== Scene V. An open Gallery to Juliet's Chamber, overlooking the Garden. ===",
"=== ACT IV. ===",
"===== Scene I. Friar Lawrence's Cell. =====",
"=== Scene II. Hall in Capulet's House. ===",
"=== Scene III. Juliet's Chamber. ===",
"=== Scene IV. Hall in Capulet's House. ===",
"=== Scene V. Juliet's Chamber; Juliet on the bed. ===",
"=== Act V. ===",
"===== Scene I. Mantua. A Street. =====",
"=== Scene II. Friar Lawrence's Cell. ===",
"=== Scene III. A churchyard; in it a Monument belonging to the Capulets. ===",
"= THE TAMING OF THE SHREW =",
"=== by William Shakespeare ===",
"=== Contents ===",
"=== Dramatis Personæ ===",
"==== SCENE: Sometimes in Padua, and sometimes in PETRUCHIO’S house in the country. ====",
"=== INDUCTION ===",
"==== SCENE I. Before an alehouse on a heath. ====",
"==== SCENE II. A bedchamber in the LORD’S house. ====",
"=== ACT I ===",
"==== SCENE I. Padua. A public place. ====",
"==== SCENE II. Padua. Before HORTENSIO’S house. ====",
"=== ACT II ===",
"==== SCENE I. Padua. A room in BAPTISTA’S house. ====",
"=== ACT III ===",
"==== SCENE I. Padua. A room in BAPTISTA’S house. ====",
"==== SCENE II. The same. Before BAPTISTA’S house. ====",
"=== ACT IV ===",
"==== SCENE I. A hall in PETRUCHIO’S country house. ====",
"==== SCENE II. Padua. Before BAPTISTA’S house. ====",
"==== SCENE III. A room in PETRUCHIO’S house. ====",
"==== SCENE IV. Padua. Before BAPTISTA’S house. ====",
"==== SCENE V. A public road. ====",
"=== ACT V ===",
"==== SCENE I. Padua. Before LUCENTIO’S house. ====",
"==== SCENE II. A room in LUCENTIO’S house. ====",
"= THE TEMPEST =",
"=== DRAMATIS PERSONAE ===",
"=== SCENE: A ship at sea; afterwards an uninhabited island ===",
"=== THE TEMPEST ACT I. SCENE 1 ===",
"== SCENE 2 ==",
"=== ACT II. SCENE 1 ===",
"== SCENE 2 ==",
"=== ACT III. SCENE 1 ===",
"== SCENE 2 ==",
"== SCENE 3 ==",
"=== ACT IV. SCENE 1 ===",
"=== ACT V. SCENE 1 ===",
"===== THE END =====",
"= THE LIFE OF TIMON OF ATHENS =",
"=== DRAMATIS PERSONAE ===",
"===== POET PAINTER JEWELLER MERCHANT MERCER AN OLD ATHENIAN THREE STRANGERS A PAGE A FOOL =====",
"=== SCENE: Athens and the neighbouring woods ===",
"==== ACT I. SCENE I. Athens. TIMON'S house ====",
"== SCENE II. A room of state in TIMON'S house ==",
"=== ACT II. SCENE I. A SENATOR'S house ===",
"== SCENE II. Before TIMON'S house ==",
"=== ACT III. SCENE I. LUCULLUS' house ===",
"== SCENE II. A public place ==",
"== SCENE III. SEMPRONIUS' house ==",
"== SCENE IV. A hall in TIMON'S house ==",
"== SCENE V. The Senate House ==",
"== SCENE VI. A banqueting hall in TIMON'S house ==",
"=== ACT IV. SCENE I. Without the walls of Athens ===",
"== SCENE II. Athens. TIMON's house ==",
"== SCENE III. The woods near the sea-shore. Before TIMON'S cave ==",
"=== ACT V. SCENE I. The woods. Before TIMON's cave ===",
"== SCENE II. Before the walls of Athens ==",
"== SCENE III. The TIMON's cave, and a rude tomb seen ==",
"== SCENE IV. Before the walls of Athens ==",
"===== THE END =====",
"= THE TRAGEDY OF TITUS ANDRONICUS =",
"=== SCENE: Rome and the neighbourhood ===",
"==== ACT 1. SCENE I. Rome. Before the Capitol ====",
"=== ACT II. SCENE I. Rome. Before the palace ===",
"== SCENE II. A forest near Rome ==",
"== SCENE III. A lonely part of the forest ==",
"== SCENE IV. Another part of the forest ==",
"=== ACT III. SCENE I. Rome. A street ===",
"== SCENE II. Rome. TITUS' house ==",
"=== ACT IV. SCENE I. Rome. TITUS' garden ===",
"== SCENE II. Rome. The palace ==",
"== SCENE III. Rome. A public place ==",
"== SCENE IV. Rome. Before the palace ==",
"=== ACT V. SCENE I. Plains near Rome ===",
"== SCENE II. Rome. Before TITUS' house ==",
"== SCENE III. The court of TITUS' house ==",
"===== THE END =====",
"= THE HISTORY OF TROILUS AND CRESSIDA =",
"=== by William Shakespeare ===",
"=== Contents ===",
"=== Dramatis Personæ ===",
"==== SCENE: Troy and the Greek camp before it ====",
"==== PROLOGUE ====",
"=== ACT I ===",
"==== SCENE I. Troy. Before PRIAM’S palace. ====",
"==== SCENE II. Troy. A street. ====",
"==== SCENE III. The Grecian camp. Before AGAMEMNON’S tent. ====",
"=== ACT II ===",
"==== SCENE I. The Grecian camp. ====",
"==== SCENE II. Troy. PRIAM’S palace. ====",
"==== SCENE III. The Grecian camp. Before the tent of ACHILLES. ====",
"=== ACT III ===",
"==== SCENE I. Troy. PRIAM’S palace. ====",
"==== SCENE II. Troy. PANDARUS’ orchard. ====",
"==== SCENE III. The Greek camp. ====",
"=== ACT IV ===",
"==== SCENE I. Troy. A street. ====",
"==== SCENE II. Troy. The court of PANDARUS’ house. ====",
"==== SCENE III. Troy. A street before PANDARUS’ house. ====",
"==== SCENE IV. Troy. PANDARUS’ house. ====",
"==== SCENE V. The Grecian camp. Lists set out. ====",
"=== ACT V ===",
"==== SCENE I. The Grecian camp. Before the tent of ACHILLES. ====",
"==== SCENE II. The Grecian camp. Before CALCHAS’ tent. ====",
"==== SCENE III. Troy. Before PRIAM’S palace. ====",
"==== SCENE IV. The plain between Troy and the Grecian camp. ====",
"==== SCENE V. Another part of the plain. ====",
"==== SCENE VI. Another part of the plain. ====",
"==== SCENE VII. Another part of the plain. ====",
"==== SCENE VIII. Another part of the plain. ====",
"==== SCENE IX. Another part of the plain. ====",
"==== SCENE X. Another part of the plain. ====",
"= TWELFTH NIGHT; OR, WHAT YOU WILL =",
"=== DRAMATIS PERSONAE ===",
"=== SCENE: A city in Illyria; and the sea-coast near it ===",
"=== ACT I. SCENE I. The DUKE'S palace ===",
"== SCENE II. The sea-coast ==",
"== SCENE III. OLIVIA'S house ==",
"== SCENE IV. The DUKE'S palace ==",
"== SCENE V. OLIVIA'S house ==",
"=== ACT II. SCENE I. The sea-coast ===",
"== SCENE II. A street ==",
"== SCENE III. OLIVIA'S house ==",
"== SCENE IV. The DUKE'S palace ==",
"===== FESTE'S SONG =====",
"== SCENE V. OLIVIA'S garden ==",
"=== ACT III. SCENE I. OLIVIA'S garden ===",
"== SCENE II. OLIVIA'S house ==",
"== SCENE III. A street ==",
"== SCENE IV. OLIVIA'S garden ==",
"=== ACT IV. SCENE I. Before OLIVIA'S house ===",
"== SCENE II. OLIVIA'S house ==",
"== SCENE III. OLIVIA'S garden ==",
"=== ACT V. SCENE I. Before OLIVIA's house ===",
"===== THE END =====",
"= THE TWO GENTLEMEN OF VERONA =",
"=== DRAMATIS PERSONAE ===",
"===== SERVANTS MUSICIANS =====",
"=== SCENE: Verona; Milan; the frontiers of Mantua ===",
"==== ACT I. SCENE I. Verona. An open place ====",
"== SCENE II. Verona. The garden Of JULIA'S house ==",
"== SCENE III. Verona. ANTONIO'S house ==",
"=== ACT II. SCENE I. Milan. The DUKE'S palace ===",
"== SCENE II. Verona. JULIA'S house ==",
"== SCENE III. Verona. A street ==",
"== SCENE IV. Milan. The DUKE'S palace ==",
"== SCENE V. Milan. A street ==",
"== SCENE VI. Milan. The DUKE's palace ==",
"== SCENE VII. Verona. JULIA'S house ==",
"=== ACT III. SCENE I. Milan. The DUKE'S palace ===",
"== SCENE II. Milan. The DUKE'S palace ==",
"=== ACT IV. SCENE I. The frontiers of Mantua. A forest ===",
"== SCENE II. Milan. Outside the DUKE'S palace, under SILVIA'S window ==",
"== SCENE III. Under SILVIA'S window ==",
"== SCENE IV. Under SILVIA'S Window ==",
"=== ACT V. SCENE I. Milan. An abbey ===",
"== SCENE II. Milan. The DUKE'S palace ==",
"== SCENE III. The frontiers of Mantua. The forest ==",
"== SCENE IV. Another part of the forest ==",
"===== THE END =====",
"= THE TWO NOBLE KINSMEN: =",
"== PROLOGUE. ==",
"=== ACT I ===",
"==== SCENE 1. (Athens. Before a temple.) ====",
"==== SCENE 2. (Thebs). ====",
"==== SCENE 3. (Before the gates of Athens.) ====",
"==== SCENE 4. (A field before Thebes. Dead bodies lying on the ground.) ====",
"==== SCENE 5. (Another part of the same.) ====",
"=== ACT II ===",
"==== SCENE 1. (Athens. A garden, with a prison in the background.) ====",
"==== SCENE 2. (The prison) ====",
"==== SCENE 3. (The country near Athens. ====",
"==== SCENE 4. (Athens. A room in the prison.) ====",
"==== SCENE 5. (An open place in Athens.) ====",
"==== SCENE 6. (Before the prison.) ====",
"=== ACT III ===",
"==== SCENE 1. (A forest near Athens.) ====",
"==== SCENE 2. (Another Part of the forest.) ====",
"==== SCENE 3. (Same as Scene I.) ====",
"==== SCENE 4. (Another part of the forest.) ====",
"==== SCENE 5. (Another part of the forest.) ====",
"==== SCENE 6. (Same as Scene III.) ====",
"=== ACT IV ===",
"==== SCENE 1. (Athens. A room in the prison.) ====",
"==== SCENE 2. (A Room in the Palace.) ====",
"==== SCENE 3. (A room in the prison.) ====",
"=== ACT V ===",
"==== SCENE 1. (Before the Temples of Mars, Venus, and Diana.) ====",
"==== SCENE 2. (A darkened Room in the Prison.) ====",
"==== SCENE 3. (A Place near the Lists.) ====",
"==== SCENE 4. (The same; a Block prepared.) ====",
"== EPILOGUE ==",
"= THE WINTER’S TALE =",
"===== SCENE: Sicilia and Bohemia =====",
"=== ACT I. SCENE I. Sicilia. The palace of LEONTES ===",
"== SCENE II. Sicilia. The palace of LEONTES ==",
"=== ACT II. SCENE I. Sicilia. The palace of LEONTES ===",
"== SCENE II. Sicilia. A prison ==",
"== SCENE III. Sicilia. The palace of LEONTES ==",
"=== ACT III. SCENE I. Sicilia. On the road to the Capital ===",
"== SCENE II. Sicilia. A court of justice ==",
"== SCENE III. Bohemia. The sea-coast ==",
"=== ACT IV. SCENE I. ===",
"== SCENE II. Bohemia. The palace of POLIXENES ==",
"== SCENE III. Bohemia. A road near the SHEPHERD'S cottage ==",
"== SCENE IV. Bohemia. The SHEPHERD'S cottage ==",
"===== SONG =====",
"=== ACT V. SCENE I. Sicilia. The palace of LEONTES ===",
"== SCENE II. Sicilia. Before the palace of LEONTES ==",
"== SCENE III. Sicilia. A chapel in PAULINA's house ==",
"===== THE END =====",
"= A LOVER’S COMPLAINT =",
"===== THE END =====",
"= THE PASSIONATE PILGRIM =",
"===== I. =====",
"===== II. =====",
"===== III. =====",
"===== IV. =====",
"===== V. =====",
"===== VI. =====",
"===== VII. =====",
"===== VIII. =====",
"===== IX. =====",
"===== X. =====",
"===== XI. =====",
"===== XII. =====",
"===== XIII. =====",
"= THE PHOENIX AND THE TURTLE =",
"===== THRENOS. =====",
"= THE RAPE OF LUCRECE =",
"== THE RAPE OF LUCRECE ==",
"=== TO THE ===",
"===== RIGHT HONOURABLE HENRY WRIOTHESLY, =====",
"===== EARL OF SOUTHAMPTON, AND BARON OF TITCHFIELD. =====",
"== THE ARGUMENT. ==",
"= VENUS AND ADONIS =",
"=== by William Shakespeare ===",
"==== TO THE RIGHT HONOURABLE HENRY WRIOTHESLEY, EARL OF SOUTHAMPTON, and Baron of Titchfield. ====",
"= VENUS AND ADONIS =",
];
