var menulist=[
"== The Project Gutenberg eBook of The Expedition of Humphry Clinker ==",
"= THE EXPEDITION OF HUMPHRY CLINKER =",
"== by Tobias Smollett ==",
"== To Mr HENRY DAVIS, Bookseller, in London. ==",
"=== ABERGAVENNY, Aug. 4. ===",
"== To the Revd. Mr JONATHAN DUSTWICH, at&mdash; ==",
"=== SIR, ===",
"== THE EXPEDITION OF HUMPHRY CLINKER ==",
"== To Dr LEWIS. ==",
"=== DOCTOR, ===",
"== To Mrs GWYLLIM, house-keeper at Brambleton-hall. ==",
"=== MRS GWILLIM, ===",
"== To Sir WATKIN PHILLIPS, Bart. of Jesus college, Oxon. ==",
"=== DEAR PHILLIPS, ===",
"== To Mrs JERMYN at her house in Gloucester. ==",
"=== DEAR MADAM, ===",
"== To Miss LAETITIA WILLIS, at Gloucester. ==",
"=== MY DEAREST LETTY, ===",
"== To Dr LEWIS. ==",
"=== DEAR LEWIS, ===",
"== To Miss LYDIA MELFORD. ==",
"== To Sir WATKIN PHILLIPS, of Jesus college, Oxon. ==",
"=== HOT WELL, April 18. ===",
"== To Sir WATKIN PHILLIPS, of Jesus college, Oxon. ==",
"=== HOT WELL, April 20. ===",
"== To Dr LEWIS. ==",
"=== HOT WELL, April 20. ===",
"== To Miss LETTY WILLIS, at Gloucester ==",
"=== HOT WELL, April 21. ===",
"== To Sir WATKIN PHILLIPS, of Jesus college, Oxon. ==",
"=== BATH, April 24. ===",
"== To Dr LEWIS. BATH, April 23. DEAR DOCTOR, ==",
"== To Miss WILLIS at Gloucester. BATH, April 26. MY DEAREST COMPANION, ==",
"== To Mrs MARY JONES, at Brambleton-hall. ==",
"=== DEAR MOLLY JONES, ===",
"== To Mrs GWYLLIM, house-keeper at Brambleton-hall. ==",
"== To Dr LEWIS. ==",
"=== DEAR DICK, ===",
"== To Sir WATKIN PHILLIPS, of Jesus college, Oxon. ==",
"=== DEAR KNIGHT, ===",
"== To Dr LEWIS. ==",
"=== DEAR LEWIS, ===",
"== To Miss LAETITIA WILLIS, at Gloucester. ==",
"=== MY DEAR LETTY, ===",
"== To Sir WATKIN PHILLIPS, of Jesus college, Oxon. ==",
"== To Dr LEWIS. ==",
"== To Sir WATKIN PHILLIPS, of Jesus college, Oxon. ==",
"=== DEAR PHILLIPS, ===",
"== To Mrs MARY JONES, at Brambleton-hall. ==",
"=== DEAR MOLLY, ===",
"== To Sir WATKIN PHILLIPS, Bart. of Jesus college, Oxon. ==",
"== To Dr LEWIS. ==",
"=== DEAR DICK, ===",
"== To Dr LEWIS. ==",
"=== DOCTER LEWS, ===",
"== To Sir WATKIN PHILLIPS, of Jesus college, Oxon. ==",
"=== DEAR PHILLIPS, ===",
"== To Dr LEWIS. ==",
"=== DEAR DOCTOR, ===",
"== To Miss LAETITIA WILLIS, at Gloucester. ==",
"=== MY DEAR LETTY, ===",
"== To Sir WATKIN PHILLIPS, of Jesus college, Oxon. ==",
"=== DEAR PHILLIPS, ===",
"== To Dr LEWIS. ==",
"== To Mrs MARY JONES, at Brambleton-hall. ==",
"=== DEAR MARY JONES, ===",
"== To Sir WATKIN PHILLIPS, of Jesus college, Oxon. ==",
"=== DEAR WAT, ===",
"== To Dr LEWIS. ==",
"=== DEAR LEWIS ===",
"== To Sir WATKIN PHILLIPS, Bart. of Jesus college, Oxon. ==",
"=== DEAR PHILLIPS, ===",
"== To Miss LAETITIA WILLIS, at Gloucester. ==",
"=== MY DEAR LETTY, ===",
"== To Sir WATKIN PHILLIPS, of Jesus college, Oxon. ==",
"=== DEAR PHILLIPS, ===",
"== To Dr LEWIS. ==",
"=== DEAR LEWIS, ===",
"== To Sir WATKIN PHILLIPS, of Jesus college, Oxon. ==",
"=== DEAR WAT, ===",
"== To Dr LEWIS. ==",
"== To Mrs MARY JONES, at Brambleton-hall, &amp;c. ==",
"=== DEAR MARY, ===",
"== To Mrs GWYLLIM, house-keeper at Brambleton-hall. MRS GWYLLIM, ==",
"== To Sir WATKIN PHILLIPS, Bart. of Jesus college, Oxon. ==",
"=== DEAR PHILLIPS, ===",
"== To Dr LEWIS. ==",
"=== DEAR DOCTOR, ===",
"== To Sir WATKIN PHILLIPS, Bart. of Jesus college, Oxon. ==",
"=== DEAR KNIGHT, ===",
"== To Dr LEWIS. ==",
"== To Sir WATKIN PHILLIPS, Bart of Jesus college, Oxon. ==",
"=== DEAR WAT, ===",
"== To Sir WATKIN PHILLIPS Bart. of Jesus college, Oxon. ==",
"=== DEAR PHILLIPS, ===",
"== To Dr LEWIS. ==",
"=== DEAR DOCTOR, ===",
"== To Sir WATKIN PHILLIPS, Bart. at Oxon. ==",
"=== DEAR WAT, ===",
"== To Dr LEWIS. ==",
"=== DEAR LEWIS, ===",
"== To Mrs MARY JONES, at Brambleton-hall. ==",
"=== DEAR MARY, ===",
"== To Sir WATKIN PHILLIPS, Bart. of Jesus college, Oxon. ==",
"=== DEAR PHILLIPS, ===",
"== To Dr LEWIS. ==",
"== To Sir WATKIN PHILLIPS, Bart. of Jesus college, Oxon. ==",
"=== DEAR KNIGHT, ===",
"== To Dr LEWIS. ==",
"=== DEAR DICK, ===",
"== To Dr LEWIS. ==",
"=== DEAR DOCTOR, ===",
"== To Miss LAETITIA WILLIS, at Gloucester. ==",
"=== MY DEAREST LETTY, ===",
"== To Mrs MARY JONES, at Brambleton-hall. ==",
"=== DEAR MARY, ===",
"== To Sir WATKIN PHILLIPS, Bart. at Oxon. ==",
"=== DEAR KNIGHT, ===",
"== To Dr LEWIS. ==",
"=== DEAR DOCTOR, ===",
"== To Mrs GWILLIM, house-keeper at Brambleton-hall. ==",
"=== MRS GWYLLIM, ===",
"== To Dr LEWIS. ==",
"=== DEAR LEWIS, ===",
"== To Sir WATKIN PHILLIPS, Bart. of Jesus college, Oxon. ==",
"=== DEAR WAT, ===",
"== To Dr LEWIS. ==",
"=== DEAR DICK, ===",
"== To Sir WATKIN PHILLIPS, Bart. at Oxon. ==",
"=== DEAR KNIGHT, ===",
"== To Mrs MARY JONES, at Brambleton-hall. ==",
"=== DEAR MARY JONES, ===",
"== To Miss LAETITIA WILLIS, at Gloucester. ==",
"=== MY DEAR LETTY, ===",
"== To Sir WATKIN PHILLIPS, Bart. of Jesus college, Oxon. ==",
"=== DEAR WATKIN, ===",
"== To Sir WATKIN PHILLIPS, Bart. of Jesus college, Oxon. ==",
"=== DEAR PHILLIPS, ===",
"== To Dr LEWIS. ==",
"=== DEAR DICK, ===",
"== To Dr LEWIS. ==",
"== To Sir WATKIN PHILLIPS, Bart. at Oxon. ==",
"=== DEAR WAT, ===",
"== To Miss LAETITIA WILLIS, at Gloucester. ==",
"=== MY DEAR, DEAR LETTY, ===",
"== To Mrs JERMYN, at her house in Gloucester. ==",
"=== DEAR MADAM, ===",
"== To Mrs MARY JONES, at Brambleton-hall. ==",
"=== O MARY JONES! MARY JONES! ===",
"== To Dr LEWIS. ==",
"=== DEAR DICK, ===",
"== To Sir WATKIN PHILLIPS, Bart. at Oxon. ==",
"=== DEAR KNIGHT, ===",
"== To Dr LEWIS. ==",
"=== DEAR DOCTOR, ===",
"== To Mrs GWYLLIM, at Brambleton-hall. ==",
"=== GOOD MRS GWYLLIM, ===",
"== To Mrs MARY JONES, at Brambleton-hall. ==",
"=== MRS JONES, ===",
"== THE FULL PROJECT GUTENBERG LICENSE ==",
];
