var menulist=[
"= THE FEDERALIST PAPERS =",
"== By Alexander Hamilton, John Jay, James Madison ==",
"== FEDERALIST No. 1. General Introduction ==",
"=== For the Independent Journal. Saturday, October 27, 1787 ===",
"== FEDERALIST No. 2. Concerning Dangers from Foreign Force and Influence ==",
"=== For the Independent Journal. Wednesday, October 31, 1787 ===",
"== FEDERALIST No. 3. The Same Subject Continued (Concerning Dangers From Foreign Force and Influence) ==",
"=== For the Independent Journal. Saturday, November 3, 1787 ===",
"== FEDERALIST No. 4. The Same Subject Continued (Concerning Dangers From Foreign Force and Influence) ==",
"=== For the Independent Journal. Wednesday, November 7, 1787 ===",
"== FEDERALIST No. 5. The Same Subject Continued (Concerning Dangers From Foreign Force and Influence) ==",
"=== For the Independent Journal. Saturday, November 10, 1787 ===",
"== FEDERALIST No. 6. Concerning Dangers from Dissensions Between the States ==",
"=== For the Independent Journal. Wednesday, November 14, 1787 ===",
"== FEDERALIST No. 7. The Same Subject Continued (Concerning Dangers from Dissensions Between the States) ==",
"=== For the Independent Journal. Thursday, November 15, 1787 ===",
"== FEDERALIST No. 8. The Consequences of Hostilities Between the States ==",
"=== From the New York Packet. Tuesday, November 20, 1787. ===",
"== FEDERALIST No. 9. The Union as a Safeguard Against Domestic Faction and Insurrection ==",
"=== For the Independent Journal. Wednesday, November 21, 1787 ===",
"== FEDERALIST No. 10. The Same Subject Continued (The Union as a Safeguard Against Domestic Faction and Insurrection) ==",
"=== From the Daily Advertiser. Thursday, November 22, 1787. ===",
"== FEDERALIST No. 11. The Utility of the Union in Respect to Commercial Relations and a Navy ==",
"=== For the Independent Journal. Saturday, November 24, 1787 ===",
"== FEDERALIST No. 12. The Utility of the Union In Respect to Revenue ==",
"=== From the New York Packet. Tuesday, November 27, 1787. ===",
"== FEDERALIST No. 13. Advantage of the Union in Respect to Economy in Government ==",
"=== For the Independent Journal. Wednesday, November 28, 1787 ===",
"== FEDERALIST No. 14. Objections to the Proposed Constitution From Extent of Territory Answered ==",
"=== From the New York Packet. Friday, November 30, 1787. ===",
"== FEDERALIST No. 15. The Insufficiency of the Present Confederation to Preserve the Union ==",
"=== For the Independent Journal. Saturday, December 1, 1787 ===",
"== FEDERALIST No. 16. The Same Subject Continued (The Insufficiency of the Present Confederation to Preserve the Union) ==",
"=== From the New York Packet. Tuesday, December 4, 1787. ===",
"== FEDERALIST No. 17. The Same Subject Continued (The Insufficiency of the Present Confederation to Preserve the Union) ==",
"=== For the Independent Journal. Wednesday, December 5, 1787 ===",
"== FEDERALIST No. 18. The Same Subject Continued (The Insufficiency of the Present Confederation to Preserve the Union) ==",
"=== For the New York Packet. Friday, December 7, 1787 ===",
"== FEDERALIST No. 19. The Same Subject Continued (The Insufficiency of the Present Confederation to Preserve the Union) ==",
"=== For the Independent Journal. Saturday, December 8, 1787 ===",
"== FEDERALIST No. 20. The Same Subject Continued (The Insufficiency of the Present Confederation to Preserve the Union) ==",
"=== From the New York Packet. Tuesday, December 11, 1787. ===",
"== FEDERALIST No. 21. Other Defects of the Present Confederation ==",
"=== For the Independent Journal. Wednesday, December 12, 1787 ===",
"== FEDERALIST No. 22. The Same Subject Continued (Other Defects of the Present Confederation) ==",
"=== From the New York Packet. Friday, December 14, 1787. ===",
"== FEDERALIST No. 23. The Necessity of a Government as Energetic as the One Proposed to the Preservation of the Union ==",
"=== From the New York Packet. Tuesday, December 18, 1787. ===",
"== FEDERALIST No. 24. The Powers Necessary to the Common Defense Further Considered ==",
"=== For the Independent Journal. Wednesday, December 19, 1787 ===",
"== FEDERALIST No. 25. The Same Subject Continued (The Powers Necessary to the Common Defense Further Considered) ==",
"=== From the New York Packet. Friday, December 21, 1787. ===",
"== FEDERALIST No. 26. The Idea of Restraining the Legislative Authority in Regard to the Common Defense Considered. ==",
"=== For the Independent Journal. Saturday, December 22, 1788 ===",
"== FEDERALIST No. 27. The Same Subject Continued (The Idea of Restraining the Legislative Authority in Regard to the Common Defense Considered) ==",
"=== From the New York Packet. Tuesday, December 25, 1787. ===",
"== FEDERALIST No. 28. The Same Subject Continued (The Idea of Restraining the Legislative Authority in Regard to the Common Defense Considered) ==",
"=== For the Independent Journal. Wednesday, December 26, 1787 ===",
"== FEDERALIST No. 29. Concerning the Militia ==",
"=== From the New York Packet. Wednesday, January 9, 1788 ===",
"== FEDERALIST No. 30. Concerning the General Power of Taxation ==",
"=== From the New York Packet. Friday, December 28, 1787. ===",
"== FEDERALIST No. 31. The Same Subject Continued (Concerning the General Power of Taxation) ==",
"=== From the New York Packet. Tuesday, January 1, 1788. ===",
"== FEDERALIST No. 32. The Same Subject Continued (Concerning the General Power of Taxation) ==",
"=== From The Independent Journal. Wednesday, January 2, 1788. ===",
"== FEDERALIST No. 33. The Same Subject Continued (Concerning the General Power of Taxation) ==",
"=== From The Independent Journal. Wednesday, January 2, 1788. ===",
"== FEDERALIST No. 34. The Same Subject Continued (Concerning the General Power of Taxation) ==",
"=== From The Independent Journal. Saturday, January 5, 1788. ===",
"== FEDERALIST No. 35. The Same Subject Continued (Concerning the General Power of Taxation) ==",
"=== For the Independent Journal. Saturday, January 5, 1788 ===",
"== FEDERALIST No. 36. The Same Subject Continued (Concerning the General Power of Taxation) ==",
"=== From the New York Packet. Tuesday, January 8, 1788. ===",
"== FEDERALIST No. 37. Concerning the Difficulties of the Convention in Devising a Proper Form of Government. ==",
"=== From the Daily Advertiser. Friday, January 11, 1788. ===",
"== FEDERALIST No. 38. The Same Subject Continued, and the Incoherence of the Objections to the New Plan Exposed. ==",
"=== From The Independent Journal. Saturday, January 12, 1788. ===",
"== FEDERALIST No. 39. The Conformity of the Plan to Republican Principles ==",
"=== For the Independent Journal. Wednesday, January 16, 1788 ===",
"== FEDERALIST No. 40. On the Powers of the Convention to Form a Mixed Government Examined and Sustained. ==",
"=== For the New York Packet. Friday, January 18, 1788. ===",
"== FEDERALIST No. 41. General View of the Powers Conferred by The Constitution ==",
"=== For the Independent Journal. Saturday, January 19, 1788 ===",
"== FEDERALIST No. 42. The Powers Conferred by the Constitution Further Considered ==",
"=== From the New York Packet. Tuesday, January 22, 1788. ===",
"== FEDERALIST No. 43. The Same Subject Continued (The Powers Conferred by the Constitution Further Considered) ==",
"=== For the Independent Journal. Wednesday, January 23, 1788 ===",
"== FEDERALIST No. 44. Restrictions on the Authority of the Several States ==",
"=== From the New York Packet. Friday, January 25, 1788. ===",
"== FEDERALIST No. 45. The Alleged Danger From the Powers of the Union to the State Governments. ==",
"=== Considered For the Independent Journal. Saturday, January 26, 1788 ===",
"== FEDERALIST No. 46. The Influence of the State and Federal Governments Compared ==",
"=== From the New York Packet. Tuesday, January 29, 1788. ===",
"== FEDERALIST No. 47. The Particular Structure of the New Government and the Distribution of Power Among Its Different Parts. ==",
"=== For the Independent Journal. Wednesday, January 30, 1788. ===",
"== FEDERALIST No. 48. These Departments Should Not Be So Far Separated as to Have No Constitutional Control Over Each Other. ==",
"=== From the New York Packet. Friday, February 1, 1788. ===",
"== FEDERALIST No. 49. Method of Guarding Against the Encroachments of Any One Department of Government by Appealing to the People Through a Convention. ==",
"=== For the Independent Journal. Saturday, February 2, 1788. ===",
"== FEDERALIST No. 50. Periodical Appeals to the People Considered ==",
"=== From the New York Packet. Tuesday, February 5, 1788. ===",
"== FEDERALIST No. 51. The Structure of the Government Must Furnish the Proper Checks and Balances Between the Different Departments. ==",
"=== For the Independent Journal. Wednesday, February 6, 1788. ===",
"== FEDERALIST No. 52. The House of Representatives ==",
"=== From the New York Packet. Friday, February 8, 1788. ===",
"== FEDERALIST No. 53. The Same Subject Continued (The House of Representatives) ==",
"=== For the Independent Journal. Saturday, February 9, 1788. ===",
"== FEDERALIST No. 54. The Apportionment of Members Among the States ==",
"=== From the New York Packet. Tuesday, February 12, 1788. ===",
"== FEDERALIST No. 55. The Total Number of the House of Representatives ==",
"=== For the Independent Journal. Wednesday, February 13, 1788. ===",
"== FEDERALIST No. 56. The Same Subject Continued (The Total Number of the House of Representatives) ==",
"=== For the Independent Journal. Saturday, February 16, 1788. ===",
"== FEDERALIST No. 57. The Alleged Tendency of the New Plan to Elevate the Few at the Expense of the Many Considered in Connection with Representation. ==",
"=== From the New York Packet. Tuesday, February 19, 1788. ===",
"== FEDERALIST No. 58. Objection That The Number of Members Will Not Be Augmented as the Progress of Population Demands. ==",
"=== Considered For the Independent Journal Wednesday, February 20, 1788. ===",
"== FEDERALIST No. 59. Concerning the Power of Congress to Regulate the Election of Members ==",
"=== From the New York Packet. Friday, February 22, 1788. ===",
"== FEDERALIST No. 60. The Same Subject Continued (Concerning the Power of Congress to Regulate the Election of Members) ==",
"=== From The Independent Journal. Saturday, February 23, 1788. ===",
"== FEDERALIST No. 61. The Same Subject Continued (Concerning the Power of Congress to Regulate the Election of Members) ==",
"=== From the New York Packet. Tuesday, February 26, 1788. ===",
"== FEDERALIST No. 62. The Senate ==",
"=== For the Independent Journal. Wednesday, February 27, 1788 ===",
"== FEDERALIST No. 63. The Senate Continued ==",
"=== For the Independent Journal. Saturday, March 1, 1788 ===",
"== FEDERALIST No. 64. The Powers of the Senate ==",
"=== From The Independent Journal. Wednesday, March 5, 1788. ===",
"== FEDERALIST No. 65. The Powers of the Senate Continued ==",
"=== From the New York Packet. Friday, March 7, 1788. ===",
"== FEDERALIST No. 66. Objections to the Power of the Senate To Set as a Court for Impeachments Further Considered. ==",
"=== From The Independent Journal. Saturday, March 8, 1788. ===",
"== FEDERALIST No. 67. The Executive Department ==",
"=== From the New York Packet. Tuesday, March 11, 1788. ===",
"== FEDERALIST No. 68. The Mode of Electing the President ==",
"=== From The Independent Journal. Wednesday, March 12, 1788. ===",
"== FEDERALIST No. 69. The Real Character of the Executive ==",
"=== From the New York Packet. Friday, March 14, 1788. ===",
"== FEDERALIST No. 70. The Executive Department Further Considered ==",
"=== From The Independent Journal. Saturday, March 15, 1788. ===",
"== FEDERALIST No. 71. The Duration in Office of the Executive ==",
"=== From the New York Packet. Tuesday, March 18, 1788. ===",
"== FEDERALIST No. 72. The Same Subject Continued, and Re-Eligibility of the Executive Considered. ==",
"=== From The Independent Journal. Wednesday, March 19, 1788. ===",
"== FEDERALIST No. 73. The Provision For The Support of the Executive, and the Veto Power ==",
"=== From the New York Packet. Friday, March 21, 1788. ===",
"== FEDERALIST No. 74. The Command of the Military and Naval Forces, and the Pardoning Power of the Executive. ==",
"=== From the New York Packet. Tuesday, March 25, 1788. ===",
"== FEDERALIST No. 75. The Treaty-Making Power of the Executive ==",
"=== For the Independent Journal. Wednesday, March 26, 1788 ===",
"== FEDERALIST No. 76. The Appointing Power of the Executive ==",
"=== From the New York Packet. Tuesday, April 1, 1788. ===",
"== FEDERALIST No. 77. The Appointing Power Continued and Other Powers of the Executive Considered. ==",
"=== From The Independent Journal. Wednesday, April 2, 1788. ===",
"== FEDERALIST No. 78. The Judiciary Department ==",
"=== From McLEAN'S Edition, New York. Wednesday, May 28, 1788 ===",
"== FEDERALIST No. 79. The Judiciary Continued ==",
"=== From MCLEAN's Edition, New York. Wednesday, May 28, 1788 ===",
"== FEDERALIST No. 80. The Powers of the Judiciary ==",
"=== From McLEAN's Edition, New York. Wednesday, May 28, 1788. ===",
"== FEDERALIST No. 81. The Judiciary Continued, and the Distribution of the Judicial Authority. ==",
"=== From McLEAN's Edition, New York. Wednesday, May 28, 1788. ===",
"== FEDERALIST No. 82. The Judiciary Continued. ==",
"=== From McLEAN's Edition, New York. Wednesday, May 28, 1788 ===",
"== FEDERALIST No. 83. The Judiciary Continued in Relation to Trial by Jury ==",
"=== From MCLEAN's Edition, New York. Wednesday, May 28, 1788 ===",
"== FEDERALIST No. 84. Certain General and Miscellaneous Objections to the Constitution Considered and Answered. ==",
"=== From McLEAN's Edition, New York. Wednesday, May 28, 1788 ===",
"== FEDERALIST No. 85. Concluding Remarks ==",
"=== From MCLEAN's Edition, New York. Wednesday, May 28, 1788 ===",
];
