var menulist=[
"== The Project Gutenberg eBook of The Count of Monte Cristo, Illustrated ==",
"= THE COUNT OF MONTE CRISTO =",
"== by Alexandre Dumas [père] ==",
"=== Contents ===",
"== VOLUME ONE ==",
"===  Chapter 1.Marseilles&mdash;The Arrival ===",
"===  Chapter 2. Father andSon ===",
"===  Chapter 3. TheCatalans ===",
"===  Chapter 4. Conspiracy ===",
"===  Chapter 5. The MarriageFeast ===",
"===  Chapter 6. The DeputyProcureur du Roi ===",
"===  Chapter 7. TheExamination ===",
"===  Chapter 8. The Châteaud’If ===",
"===  Chapter 9. The Evening ofthe Betrothal ===",
"===  Chapter 10. TheKing’s Closet at the Tuileries ===",
"===  Chapter 11. The CorsicanOgre ===",
"===  Chapter 12. Father andSon ===",
"===  Chapter 13. The HundredDays ===",
"===  Chapter 14. The TwoPrisoners ===",
"===  Chapter 15. Number 34 andNumber 27 ===",
"===  Chapter 16. A LearnedItalian ===",
"===  Chapter 17. TheAbbé’s Chamber ===",
"===  Chapter 18. TheTreasure ===",
"===  Chapter 19. The ThirdAttack ===",
"===  Chapter 20. The Cemetery ofthe Château d’If ===",
"===  Chapter 21. The Island ofTiboulen ===",
"===  Chapter 22. TheSmugglers ===",
"===  Chapter 23. The Island ofMonte Cristo ===",
"===  Chapter 24. The SecretCave ===",
"===  Chapter 25. TheUnknown ===",
"===  Chapter 26. The Pont duGard Inn ===",
"===  Chapter 27. The Story ===",
"==  VOLUME TWO ==",
"===  Chapter 28. The PrisonRegister ===",
"===  Chapter 29. The House ofMorrel &amp; Son ===",
"===  Chapter 30. The Fifth ofSeptember ===",
"===  Chapter 31. Italy: Sinbadthe Sailor ===",
"===  Chapter 32. The Waking ===",
"===  Chapter 33. RomanBandits ===",
"===  Chapter 34. TheColosseum ===",
"===  Chapter 35. LaMazzolata ===",
"===  Chapter 36. The Carnival atRome ===",
"===  Chapter 37. The Catacombsof Saint Sebastian ===",
"===  Chapter 38. TheRendezvous ===",
"===  Chapter 39. The Guests ===",
"===  Chapter 40. TheBreakfast ===",
"===  Chapter 41. ThePresentation ===",
"===  Chapter 42. MonsieurBertuccio ===",
"===  Chapter 43. The House atAuteuil ===",
"===  Chapter 44. TheVendetta ===",
"===  Chapter 45. The Rain ofBlood ===",
"===  Chapter 46. UnlimitedCredit ===",
"===  Chapter 47. The DappledGrays ===",
"== VOLUME THREE ==",
"===  Chapter 48. Ideology ===",
"===  Chapter 49. Haydée ===",
"===  Chapter 50. The MorrelFamily ===",
"===  Chapter 51. Pyramus andThisbe ===",
"===  Chapter 52. Toxicology ===",
"===  Chapter 53. Robert leDiable ===",
"===  Chapter 54. A Flurry inStocks ===",
"===  Chapter 55. MajorCavalcanti ===",
"===  Chapter 56. AndreaCavalcanti ===",
"===  Chapter 57. In the LucernPatch ===",
"===  Chapter 58. M. Noirtier deVillefort ===",
"===  Chapter 59. The Will ===",
"===  Chapter 60. TheTelegraph ===",
"===  Chapter 61. How a GardenerMay Get Rid of the Dormice that Eat His Peaches ===",
"===  Chapter 62. Ghosts ===",
"===  Chapter 63. The Dinner ===",
"===  Chapter 64. The Beggar ===",
"===  Chapter 65. A ConjugalScene ===",
"===  Chapter 66. MatrimonialProjects ===",
"===  Chapter 67. The Office ofthe King’s Attorney ===",
"===  Chapter 68. A SummerBall ===",
"===  Chapter 69. TheInquiry ===",
"===  Chapter 70. The Ball ===",
"===  Chapter 71. Bread andSalt ===",
"===  Chapter 72. Madame deSaint-Méran ===",
"===  Chapter 73. ThePromise ===",
"== VOLUME FOUR ==",
"===  Chapter 74. The VillefortFamily Vault ===",
"===  Chapter 75. A SignedStatement ===",
"===  Chapter 76. Progress ofCavalcanti the Younger ===",
"===  Chapter 77. Haydée ===",
"===  Chapter 78. We hear FromYanina ===",
"===  Chapter 79. TheLemonade ===",
"===  Chapter 80. TheAccusation ===",
"===  Chapter 81. The Room of theRetired Baker ===",
"===  Chapter 82. TheBurglary ===",
"===  Chapter 83. The Hand ofGod ===",
"===  Chapter 84. Beauchamp ===",
"===  Chapter 85. TheJourney ===",
"===  Chapter 86. The Trial ===",
"===  Chapter 87. TheChallenge ===",
"===  Chapter 88. The Insult ===",
"===  Chapter 89. The Night ===",
"===  Chapter 90. TheMeeting ===",
"===  Chapter 91. Mother andSon ===",
"===  Chapter 92. TheSuicide ===",
"===  Chapter 93. Valentine ===",
"===  Chapter 94.Maximilian’s Avowal ===",
"===  Chapter 95. Father andDaughter ===",
"== VOLUME FIVE ==",
"===  Chapter 96. TheContract ===",
"===  Chapter 97. The Departurefor Belgium ===",
"===  Chapter 98. The Bell andBottle Tavern ===",
"===  Chapter 99. The Law ===",
"===  Chapter 100. TheApparition ===",
"===  Chapter 101. Locusta ===",
"===  Chapter 102. Valentine ===",
"===  Chapter 103.Maximilian ===",
"===  Chapter 104.Danglars’ Signature ===",
"===  Chapter 105. The Cemeteryof Père-Lachaise ===",
"===  Chapter 106. Dividing theProceeds ===",
"===  Chapter 107. TheLions’ Den ===",
"===  Chapter 108. The Judge ===",
"===  Chapter 109. TheAssizes ===",
"===  Chapter 110. TheIndictment ===",
"===  Chapter 111. Expiation ===",
"===  Chapter 112. TheDeparture ===",
"===  Chapter 113. The Past ===",
"===  Chapter 114. Peppino ===",
"===  Chapter 115. LuigiVampa’s Bill of Fare ===",
"===  Chapter 116. ThePardon ===",
"===  Chapter 117. The Fifth ofOctober ===",
"== FOOTNOTES: ==",
"== THE FULL PROJECT GUTENBERG LICENSE ==",
];
