var menulist=[
"== The Project Gutenberg eBook of Twenty Years After ==",
"= Twenty Years After =",
"== By Alexandre Dumas, Père ==",
"== CONTENTS ==",
"== Chapter I. The Shade of Cardinal Richelieu. ==",
"== Chapter II. A Nightly Patrol. ==",
"== Chapter III. Dead Animosities. ==",
"== Chapter IV. Anne of Austria at the Age of Forty-six. ==",
"== Chapter V. The Gascon and the Italian. ==",
"== Chapter VI. D’Artagnan in his Fortieth Year. ==",
"== Chapter VII. Touches upon the Strange Effects a Half-pistole may have. ==",
"== Chapter VIII. D’Artagnan, Going to a Distance to discover Aramis. ==",
"== Chapter IX. The Abbé D’Herblay. ==",
"== Chapter X. Monsieur Porthos du Vallon de Bracieux de Pierrefonds. ==",
"== Chapter XI. Wealth does not necessarily produce Happiness. ==",
"== Chapter XII. Porthos was Discontented with his Condition. ==",
"== Chapter XIII. Two Angelic Faces. ==",
"== Chapter XIV. The Castle of Bragelonne. ==",
"== Chapter XV. Athos as a Diplomatist. ==",
"== Chapter XVI. The Duc de Beaufort. ==",
"== Chapter XVII. Duc de Beaufort amused his Leisure Hours in the Donjon of Vincennes. ==",
"== Chapter XVIII. Grimaud begins his Functions. ==",
"== Chapter XIX. Pâtés made by the Successor of Father Marteau are described. ==",
"== Chapter XX. One of Marie Michon’s Adventures. ==",
"== Chapter XXI. The Abbé Scarron. ==",
"== Chapter XXII. Saint Denis. ==",
"== Chapter XXIII. One of the Forty Methods of Escape of the Duc de Beaufort. ==",
"== Chapter XXIV. The timely Arrival of D’Artagnan in Paris. ==",
"== Chapter XXV. An Adventure on the High Road. ==",
"== Chapter XXVI. The Rencontre. ==",
"== Chapter XXVII. The four old Friends prepare to meet again. ==",
"== Chapter XXVIII. The Place Royale. ==",
"== Chapter XXIX. The Ferry across the Oise. ==",
"== Chapter XXX. Skirmishing. ==",
"== Chapter XXXI. The Monk. ==",
"== Chapter XXXII. The Absolution. ==",
"== Chapter XXXIII. Grimaud Speaks. ==",
"== Chapter XXXIV. On the Eve of Battle. ==",
"== Chapter XXXV. A Dinner in the Old Style. ==",
"== Chapter XXXVI. A Letter from Charles the First. ==",
"== Chapter XXXVII. Cromwell’s Letter. ==",
"== Chapter XXXVIII. Henrietta Maria and Mazarin. ==",
"== Chapter XXXIX. How, sometimes, the Unhappy mistake Chance for Providence. ==",
"== Chapter XL. Uncle and Nephew. ==",
"== Chapter XLI. Paternal Affection. ==",
"== Chapter XLII. Another Queen in Want of Help. ==",
"== Chapter XLIII. In which it is proved that first Impulses are oftentimes the best. ==",
"== Chapter XLIV. Te Deum for the Victory of Lens. ==",
"== Chapter XLV. The Beggar of St. Eustache. ==",
"== Chapter XLVI. The Tower of St. Jacques de la Boucherie. ==",
"== Chapter XLVII. The Riot. ==",
"== Chapter XLVIII. The Riot becomes a Revolution. ==",
"== Chapter XLIX. Misfortune refreshes the Memory. ==",
"== Chapter L. The Interview. ==",
"== Chapter LI. The Flight. ==",
"== Chapter LII. The Carriage of Monsieur le Coadjuteur. ==",
"== Chapter LIII. How D’Artagnan and Porthos earned by selling Straw. ==",
"== Chapter LIV. In which we hear Tidings of Aramis. ==",
"== Chapter LV. The Scotchman. ==",
"== Chapter LVI. The Avenger. ==",
"== Chapter LVII. Oliver Cromwell. ==",
"== Chapter LVIII. Jesus Seigneur. ==",
"== Chapter LIX. Noble Natures never lose Courage, nor good Stomachs their Appetites. ==",
"== Chapter LX. Respect to Fallen Majesty. ==",
"== Chapter LXI. D’Artagnan hits on a Plan. ==",
"== Chapter LXII. London. ==",
"== Chapter LXIII. The Trial. ==",
"== Chapter LXIV. Whitehall. ==",
"== Chapter LXV. The Workmen. ==",
"== Chapter LXVI. Remember! ==",
"== Chapter LXVII. The Man in the Mask. ==",
"== Chapter LXVIII. Cromwell’s House. ==",
"== Chapter LXIX. Conversational. ==",
"== Chapter LXX. The Skiff “Lightning.” ==",
"== Chapter LXXI. Port Wine. ==",
"== Chapter LXXII. End of the Port Wine Mystery. ==",
"== Chapter LXIII. Fatality. ==",
"== Chapter LXIV. How Mousqueton had a Narrow Escape of being eaten. ==",
"== Chapter LXXV. The Return. ==",
"== Chapter LXXVI. The Ambassadors. ==",
"== Chapter LXXVII. The three Lieutenants of the Generalissimo. ==",
"== Chapter LXXVIII. The Battle of Charenton. ==",
"== Chapter LXXIX. The Road to Picardy. ==",
"== Chapter LXXX. The Gratitude of Anne of Austria. ==",
"== Chapter LXXXI. Cardinal Mazarin as King. ==",
"== Chapter LXXXII. Precautions. ==",
"== Chapter LXXXIII. Strength and Sagacity. ==",
"== Chapter LXXXIV. Strength and Sagacity&mdash;Continued. ==",
"== Chapter LXXXV. The Oubliettes of Cardinal Mazarin. ==",
"== Chapter LXXXVI. Conferences. ==",
"== Chapter LXXXVII. Thinking that Porthos will be at last a Baron, and D’Artagnan a Captain. ==",
"== Chapter LXXXVIII. Shows how with Threat and Pen more is effected than by the Sword. ==",
"== Chapter LXXXIX. Difficult for Kings to return to the Capitals of their Kingdoms. ==",
"== Chapter XC. Conclusion. ==",
"== THE FULL PROJECT GUTENBERG LICENSE ==",
];
