var menulist=[
"== The Project Gutenberg eBook of Ulysses ==",
"= Ulysses =",
"== by James Joyce ==",
"== Contents ==",
"== &mdash; I &mdash; ==",
"=== [ 1 ] ===",
"=== [ 2 ] ===",
"=== [ 3 ] ===",
"== &mdash; II &mdash; ==",
"=== [ 4 ] ===",
"=== [ 5 ] ===",
"=== [ 6 ] ===",
"=== [ 7 ] ===",
"==== IN THE HEART OF THE HIBERNIAN METROPOLIS ====",
"==== THE WEARER OF THE CROWN ====",
"==== GENTLEMEN OF THE PRESS ====",
"==== WILLIAM BRAYDEN, ESQUIRE, OF OAKLANDS, SANDYMOUNT ====",
"==== THE CROZIER AND THE PEN ====",
"==== WITH UNFEIGNED REGRET IT IS WE ANNOUNCE THE DISSOLUTION OF A MOST RESPECTEDDUBLIN BURGESS ====",
"==== HOW A GREAT DAILY ORGAN IS TURNED OUT ====",
"==== WE SEE THE CANVASSER AT WORK ====",
"==== HOUSE OF KEY(E)S ====",
"==== ORTHOGRAPHICAL ====",
"==== NOTED CHURCHMAN AN OCCASIONAL CONTRIBUTOR ====",
"==== A DAYFATHER ====",
"==== AND IT WAS THE FEAST OF THE PASSOVER ====",
"==== ONLY ONCE MORE THAT SOAP ====",
"==== ERIN, GREEN GEM OF THE SILVER SEA ====",
"==== SHORT BUT TO THE POINT ====",
"==== SAD ====",
"==== HIS NATIVE DORIC ====",
"==== WHAT WETHERUP SAID ====",
"==== MEMORABLE BATTLES RECALLED ====",
"==== O, HARP EOLIAN! ====",
"==== SPOT THE WINNER ====",
"==== A COLLISION ENSUES ====",
"==== EXIT BLOOM ====",
"==== A STREET CORTÈGE ====",
"==== THE CALUMET OF PEACE ====",
"==== THE GRANDEUR THAT WAS ROME ====",
"==== ??? ====",
"==== SHINDY IN WELLKNOWN RESTAURANT ====",
"==== LOST CAUSES NOBLE MARQUESS MENTIONED ====",
"==== KYRIE ELEISON! ====",
"==== LENEHAN’S LIMERICK ====",
"==== OMNIUM GATHERUM ====",
"==== “YOU CAN DO IT!” ====",
"==== THE GREAT GALLAHER ====",
"==== A DISTANT VOICE ====",
"==== CLEVER, VERY ====",
"==== RHYMES AND REASONS ====",
"==== SUFFICIENT FOR THE DAY... ====",
"==== LINKS WITH BYGONE DAYS OF YORE ====",
"==== ITALIA, MAGISTRA ARTIUM ====",
"==== A POLISHED PERIOD ====",
"==== A MAN OF HIGH MORALE ====",
"==== IMPROMPTU ====",
"==== FROM THE FATHERS ====",
"==== OMINOUS&mdash;FOR HIM! ====",
"==== LET US HOPE ====",
"==== DEAR DIRTY DUBLIN ====",
"==== LIFE ON THE RAW ====",
"==== RETURN OF BLOOM ====",
"==== INTERVIEW WITH THE EDITOR ====",
"==== K.M.A. ====",
"==== K.M.R.I.A. ====",
"==== RAISING THE WIND ====",
"==== SOME COLUMN!&mdash;THAT’S WHAT WADDLER ONE SAID ====",
"==== THOSE SLIGHTLY RAMBUNCTIOUS FEMALES ====",
"==== DAMES DONATE DUBLIN’S CITS SPEEDPILLS VELOCITOUS AEROLITHS, BELIEF ====",
"==== SOPHIST WALLOPS HAUGHTY HELEN SQUARE ON PROBOSCIS. SPARTANS GNASH MOLARS.ITHACANS VOW PEN IS CHAMP. ====",
"==== HELLO THERE, CENTRAL! ====",
"==== WHAT?&mdash;AND LIKEWISE&mdash;WHERE? ====",
"==== VIRGILIAN, SAYS PEDAGOGUE. SOPHOMORE PLUMPS FOR OLD MAN MOSES. ====",
"==== HORATIO IS CYNOSURE THIS FAIR JUNE DAY ====",
"==== DIMINISHED DIGITS PROVE TOO TITILLATING FOR FRISKY FRUMPS. ANNE WIMBLES, FLOWANGLES&mdash;YET CAN YOU BLAME THEM? ====",
"=== [ 8 ] ===",
"=== [ 9 ] ===",
"=== [ 10 ] ===",
"=== [ 11 ] ===",
"=== [ 12 ] ===",
"=== [ 13 ] ===",
"=== [ 14 ] ===",
"=== [ 15 ] ===",
"== &mdash; III &mdash; ==",
"=== [ 16 ] ===",
"=== [ 17 ] ===",
"=== [ 18 ] ===",
"== THE FULL PROJECT GUTENBERG LICENSE ==",
];
