var bible31_global=[
[
"5 Even so the tongue is a little member, and boasteth great things. Behold, how great a matter a little fire kindleth!",
"6 And the tongue is a fire, a world of iniquity: so is the tongue among our members, that it defileth the whole body, and setteth on fire the course of nature; and it is set on fire of hell.",
"7 For every kind of beasts, and of birds, and of serpents, and of things in the sea, is tamed, and hath been tamed of mankind:",
"8 But the tongue can no man tame; it is an unruly evil, full of deadly poison.",
"",
"——【The General Epistle of James 3】",
"",
"5 这样，舌头在百体里也是最小的，却能说大话。看哪，最小的火能点著最大的树林。",
"6 舌头就是火，在我们百体中，舌头是个罪恶的世界，能污秽全身，也能把生命的轮子点起来，并且是从地狱里点著的。",
"7 各类的走兽、飞禽、昆虫，水族，本来都可以制伏，也已经被人制伏了；",
"8 惟独舌头没有人能制伏，是不止息的恶物，满了害死人的毒气。",
"",
"——【雅各书 3】",
],
[
"1 And Moses answered and said, But, behold, they will not believe me, nor hearken unto my voice: for they will say, The LORD hath not appeared unto thee.",
"2 And the LORD said unto him, What is that in thine hand? And he said, A rod.",
"",
"——【The Second Book of Moses: Called Exodus 4】",
"",
"1 摩西回答说：「他们必不信我，也不听我的话，必说：『耶和华并没有向你显现。』」",
"2 耶和华对摩西说：「你手里是什么？」他说：「是杖。」",
"",
"——【出埃及记 4】",
],
[
"1 Unto thee will I cry, O LORD my rock; be not silent to me: lest, if thou be silent to me, I become like them that go down into the pit.",
"2 Hear the voice of my supplications, when I cry unto thee, when I lift up my hands toward thy holy oracle.",
"3 Draw me not away with the wicked, and with the workers of iniquity, which speak peace to their neighbours, but mischief is in their hearts.",
"4 Give them according to their deeds, and according to the wickedness of their endeavours: give them after the work of their hands; render to them their desert.",
"",
"——【The Book of Psalms 28】",
"",
"1 （大卫的诗。）耶和华啊，我要求告你！我的磐石啊，不要向我缄默！倘若你向我闭口，我就如将死的人一样。",
"2 我呼求你，向你至圣所举手的时候，求你垂听我恳求的声音！",
"3 不要把我和恶人并作孽的一同除掉；他们与邻舍说和平话，心里却是奸恶。",
"4 愿你按著他们所做的，并他们所行的恶事待他们。愿你照着他们手所做的待他们，将他们所应得的报应加给他们。",
"",
"——【诗篇 28】",
],
[
"5 And it shall come to pass, that the man's rod, whom I shall choose, shall blossom: and I will make to cease from me the murmurings of the children of Israel, whereby they murmur against you.",
"6 And Moses spake unto the children of Israel, and every one of their princes gave him a rod apiece, for each prince one, according to their fathers' houses, even twelve rods: and the rod of Aaron was among their rods.",
"7 And Moses laid up the rods before the LORD in the tabernacle of witness.",
"",
"——【The Fourth Book of Moses: Called Numbers 17】",
"",
"5 后来我所拣选的那人，他的杖必发芽。这样，我必使以色列人向你们所发的怨言止息，不再达到我耳中。」",
"6 于是摩西晓谕以色列人，他们的首领就把杖交给他，按著支派，每首领一根，共有十二根；亚伦的杖也在其中。",
"7 摩西就把杖存在法柜的帐幕内，在耶和华面前。",
"",
"——【民数记 17】",
],
[
"15 I speak as to wise men; judge ye what I say.",
"16 The cup of blessing which we bless, is it not the communion of the blood of Christ? The bread which we break, is it not the communion of the body of Christ?",
"17 For we being many are one bread, and one body: for we are all partakers of that one bread.",
"18 Behold Israel after the flesh: are not they which eat of the sacrifices partakers of the altar?",
"",
"——【The First Epistle of Paul the Apostle to the Corinthians 10】",
"",
"15 我好像对明白人说的，你们要审察我的话。",
"16 我们所祝福的杯，岂不是同领基督的血吗？我们所擘开的饼，岂不是同领基督的身体吗？",
"17 我们虽多，仍是一个饼，一个身体，因为我们都是分受这一个饼。",
"18 你们看属肉体的以色列人，那吃祭物的岂不是在祭坛上有分吗？",
"",
"——【哥林多前书 10】",
],
[
"1 For, behold, the day cometh, that shall burn as an oven; and all the proud, yea, and all that do wickedly, shall be stubble: and the day that cometh shall burn them up, saith the LORD of hosts, that it shall leave them neither root nor branch.",
"2 But unto you that fear my name shall the Sun of righteousness arise with healing in his wings; and ye shall go forth, and grow up as calves of the stall.",
"3 And ye shall tread down the wicked; for they shall be ashes under the soles of your feet in the day that I shall do this, saith the LORD of hosts.",
"4 Remember ye the law of Moses my servant, which I commanded unto him in Horeb for all Israel, with the statutes and judgments.",
"5 Behold, I will send you Elijah the prophet before the coming of the great and dreadful day of the LORD:",
"",
"——【Malachi 4】",
"",
"1 万军之耶和华说：「那日临近，势如烧著的火炉，凡狂傲的和行恶的必如碎秸，在那日必被烧尽，根本枝条一无存留。",
"2 但向你们敬畏我名的人必有公义的日头出现，其光线（原文是翅膀）有医治之能。你们必出来跳跃如圈里的肥犊。",
"3 你们必践踏恶人；在我所定的日子，他们必如灰尘在你们脚掌之下。这是万军之耶和华说的。",
"4 「你们当记念我仆人摩西的律法，就是我在何烈山为以色列众人所吩咐他的律例典章。",
"5 「看哪，耶和华大而可畏之日未到以前，我必差遣先知以利亚到你们那里去。",
"",
"——【玛拉基书 4】",
],
[
"1 It is a good thing to give thanks unto the LORD, and to sing praises unto thy name, O most High:",
"2 To shew forth thy lovingkindness in the morning, and thy faithfulness every night,",
"3 Upon an instrument of ten strings, and upon the psaltery; upon the harp with a solemn sound.",
"",
"——【The Book of Psalms 92】",
"",
"1 （安息日的诗歌。）称谢耶和华！歌颂你至高者的名！",
"2 用十弦的乐器和瑟，用琴弹幽雅的声音，早晨传扬你的慈爱；每夜传扬你的信实。这本为美事。",
"3 并入上节",
"",
"——【诗篇 92】",
],
[
"12 And it is turned round about by his counsels: that they may do whatsoever he commandeth them upon the face of the world in the earth.",
"13 He causeth it to come, whether for correction, or for his land, or for mercy.",
"14 Hearken unto this, O Job: stand still, and consider the wondrous works of God.",
"15 Dost thou know when God disposed them, and caused the light of his cloud to shine?",
"16 Dost thou know the balancings of the clouds, the wondrous works of him which is perfect in knowledge?",
"",
"——【The Book of Job 37】",
"",
"12 这云是借他的指引游行旋转，得以在全地面上行他一切所吩咐的，",
"13 或为责罚，或为润地，或为施行慈爱。",
"14 约伯啊，你要留心听，要站立思想　神奇妙的作为。",
"15 　神如何吩咐这些，如何使云中的电光照耀，你知道吗？",
"16 云彩如何浮于空中，那知识全备者奇妙的作为，你知道吗？",
"",
"——【约伯记 37】",
],
[
"9 According to the custom of the priest's office, his lot was to burn incense when he went into the temple of the Lord.",
"10 And the whole multitude of the people were praying without at the time of incense.",
"11 And there appeared unto him an angel of the Lord standing on the right side of the altar of incense.",
"12 And when Zacharias saw him, he was troubled, and fear fell upon him.",
"13 But the angel said unto him, Fear not, Zacharias: for thy prayer is heard; and thy wife Elisabeth shall bear thee a son, and thou shalt call his name John.",
"",
"——【The Gospel According to Saint Luke 1】",
"",
"9 照祭司的规矩掣籤，得进主殿烧香。",
"10 烧香的时候，众百姓在外面祷告。",
"11 有主的使者站在香坛的右边，向他显现。",
"12 撒迦利亚看见，就惊慌害怕。",
"13 天使对他说：撒迦利亚，不要害怕，因为你的祈祷已经被听见了。你的妻子以利沙伯要给你生一个儿子，你要给他起名叫约翰。",
"",
"——【路加福音 1】",
],
[
"1 But the children of Israel committed a trespass in the accursed thing: for Achan, the son of Carmi, the son of Zabdi, the son of Zerah, of the tribe of Judah, took of the accursed thing: and the anger of the LORD was kindled against the children of Israel.",
"2 And Joshua sent men from Jericho to Ai, which is beside Beth–aven, on the east side of Beth–el, and spake unto them, saying, Go up and view the country. And the men went up and viewed Ai.",
"",
"——【The Book of Joshua 7】",
"",
"1 以色列人在当灭的物上犯了罪；因为犹大支派中，谢拉的曾孙，撒底的孙子，迦米的儿子亚干取了当灭的物；耶和华的怒气就向以色列人发作。",
"2 当下，约书亚从耶利哥打发人往伯特利东边、靠近伯‧亚文的艾城去，吩咐他们说：你们上去窥探那地。他们就上去窥探艾城。",
"",
"——【约书亚记 7】",
],
[
"4 For thus hath the LORD spoken unto me, Like as the lion and the young lion roaring on his prey, when a multitude of shepherds is called forth against him, he will not be afraid of their voice, nor abase himself for the noise of them: so shall the LORD of hosts come down to fight for mount Zion, and for the hill thereof.",
"5 As birds flying, so will the LORD of hosts defend Jerusalem; defending also he will deliver it; and passing over he will preserve it.",
"6 Turn ye unto him from whom the children of Israel have deeply revolted.",
"",
"——【The Book of the Prophet Isaiah 31】",
"",
"4 耶和华对我如此说：狮子和少壮狮子护食咆哮，就是喊许多牧人来攻击牠，牠总不因他们的声音惊惶，也不因他们的喧哗缩伏。如此，万军之耶和华也必降临在锡安山冈上争战。",
"5 雀鸟怎样搧翅覆雏，万军之耶和华也要照样保护耶路撒冷。他必保护拯救，要越门保守。",
"6 以色列人哪，你们深深地悖逆耶和华，现今要归向他。",
"",
"——【以赛亚书 31】",
],
[
"15 And when he had spoken such words unto me, I set my face toward the ground, and I became dumb.",
"16 And, behold, one like the similitude of the sons of men touched my lips: then I opened my mouth, and spake, and said unto him that stood before me, O my lord, by the vision my sorrows are turned upon me, and I have retained no strength.",
"17 For how can the servant of this my lord talk with this my lord? for as for me, straightway there remained no strength in me, neither is there breath left in me.",
"18 Then there came again and touched me one like the appearance of a man, and he strengthened me,",
"19 And said, O man greatly beloved, fear not: peace be unto thee, be strong, yea, be strong. And when he had spoken unto me, I was strengthened, and said, Let my lord speak; for thou hast strengthened me.",
"",
"——【The Book of Daniel 10】",
"",
"15 他向我这样说，我就脸面朝地，哑口无声。",
"16 不料，有一位像人的，摸我的嘴唇，我便开口向那站在我面前的说：「我主啊，因见这异象，我大大愁苦，毫无气力。",
"17 我主的仆人怎能与我主说话呢？我一见异象就浑身无力，毫无气息。」",
"18 有一位形状像人的又摸我，使我有力量。",
"19 他说：「大蒙眷爱的人哪，不要惧怕，愿你平安！你总要坚强。」他一向我说话，我便觉得有力量，说：「我主请说，因你使我有力量。」",
"",
"——【但以理书 10】",
],
[
"7 But go your way, tell his disciples and Peter that he goeth before you into Galilee: there shall ye see him, as he said unto you.",
"8 And they went out quickly, and fled from the sepulchre; for they trembled and were amazed: neither said they any thing to any man; for they were afraid.",
"9 Now when Jesus was risen early the first day of the week, he appeared first to Mary Magdalene, out of whom he had cast seven devils.",
"10 And she went and told them that had been with him, as they mourned and wept.",
"11 And they, when they had heard that he was alive, and had been seen of her, believed not.",
"12 After that he appeared in another form unto two of them, as they walked, and went into the country.",
"",
"——【The Gospel According to Saint Mark 16】",
"",
"7 你们可以去告诉他的门徒和彼得，说：他在你们以先往加利利去。在那里你们要见他，正如他从前所告诉你们的。",
"8 她们就出来，从坟墓那里逃跑，又发抖又惊奇，什么也不告诉人，因为她们害怕。",
"9 在七日的第一日清早，耶稣复活了，就先向抹大拉的马利亚显现。耶稣从她身上曾赶出七个鬼。",
"10 他去告诉那向来跟随耶稣的人；那时他们正哀恸哭泣。",
"11 他们听见耶稣活了，被马利亚看见，却是不信。",
"12 这事以后，门徒中间有两个人往乡下去。走路的时候，耶稣变了形像，向他们显现。",
"",
"——【马可福音 16】",
],
[
"1 These are the journeys of the children of Israel, which went forth out of the land of Egypt with their armies under the hand of Moses and Aaron.",
"2 And Moses wrote their goings out according to their journeys by the commandment of the LORD: and these are their journeys according to their goings out.",
"3 And they departed from Rameses in the first month, on the fifteenth day of the first month; on the morrow after the passover the children of Israel went out with an high hand in the sight of all the Egyptians.",
"",
"——【The Fourth Book of Moses: Called Numbers 33】",
"",
"1 以色列人按着军队，在摩西、亚伦的手下出埃及地所行的路程（或作：站口；下同）记在下面。",
"2 摩西遵著耶和华的吩咐记载他们所行的路程，其路程乃是这样：",
"3 正月十五日，就是逾越节的次日，以色列人从兰塞起行，在一切埃及人眼前昂然无惧地出去。",
"",
"——【民数记 33】",
],
[
"10 Unto the men of the east with the Ammonites, and will give them in possession, that the Ammonites may not be remembered among the nations.",
"11 And I will execute judgments upon Moab; and they shall know that I am the LORD.",
"12 Thus saith the Lord GOD; Because that Edom hath dealt against the house of Judah by taking vengeance, and hath greatly offended, and revenged himself upon them;",
"13 Therefore thus saith the Lord GOD; I will also stretch out mine hand upon Edom, and will cut off man and beast from it; and I will make it desolate from Teman; and they of Dedan shall fall by the sword.",
"14 And I will lay my vengeance upon Edom by the hand of my people Israel: and they shall do in Edom according to mine anger and according to my fury; and they shall know my vengeance, saith the Lord GOD.",
"15 Thus saith the Lord GOD; Because the Philistines have dealt by revenge, and have taken vengeance with a despiteful heart, to destroy it for the old hatred;",
"",
"——【The Book of the Prophet Ezekiel 25】",
"",
"10 好使东方人来攻击亚扪人。我必将亚扪人之地交给他们为业，使亚扪人在列国中不再被记念。",
"11 我必向摩押施行审判，他们就知道我是耶和华。」",
"12 主耶和华如此说：「因为以东报仇雪恨，攻击犹大家，向他们报仇，大大有罪，",
"13 所以主耶和华如此说：我必伸手攻击以东，剪除人与牲畜，使以东从提幔起，人必倒在刀下，地要变为荒凉，直到底但。",
"14 我必借我民以色列的手报复以东；以色列民必照我的怒气，按我的忿怒在以东施报，以东人就知道是我施报。这是主耶和华说的。」",
"15 主耶和华如此说：「因非利士人向犹大人报仇，就是以恨恶的心报仇雪恨，永怀仇恨，要毁灭他们，",
"",
"——【以西结书 25】",
],
[
"23 And when he was entered into a ship, his disciples followed him.",
"24 And, behold, there arose a great tempest in the sea, insomuch that the ship was covered with the waves: but he was asleep.",
"25 And his disciples came to him, and awoke him, saying, Lord, save us: we perish.",
"",
"——【The Gospel According to Saint Matthew 8】",
"",
"23 耶稣上了船，门徒跟著他。",
"24 海里忽然起了暴风，甚至船被波浪掩盖；耶稣却睡著了。",
"25 门徒来叫醒了他，说：「主啊，救我们，我们丧命啦！」",
"",
"——【马太福音 8】",
],
[
"11 And Solomon gave Hiram twenty thousand measures of wheat for food to his household, and twenty measures of pure oil: thus gave Solomon to Hiram year by year.",
"12 And the LORD gave Solomon wisdom, as he promised him: and there was peace between Hiram and Solomon; and they two made a league together.",
"13 And king Solomon raised a levy out of all Israel; and the levy was thirty thousand men.",
"",
"——【The First Book of the Kings 5】",
"",
"11 所罗门给希兰麦子二万歌珥，清油二十歌珥，作他家的食物。所罗门每年都是这样给希兰。",
"12 耶和华照著所应许的赐智慧给所罗门。希兰与所罗门和好，彼此立约。",
"13 所罗门王从以色列人中挑取服苦的人共有三万，",
"",
"——【列王记上 5】",
],
[
"17 But upon mount Zion shall be deliverance, and there shall be holiness; and the house of Jacob shall possess their possessions.",
"18 And the house of Jacob shall be a fire, and the house of Joseph a flame, and the house of Esau for stubble, and they shall kindle in them, and devour them; and there shall not be any remaining of the house of Esau; for the LORD hath spoken it.",
"19 And they of the south shall possess the mount of Esau; and they of the plain the Philistines: and they shall possess the fields of Ephraim, and the fields of Samaria: and Benjamin shall possess Gilead.",
"20 And the captivity of this host of the children of Israel shall possess that of the Canaanites, even unto Zarephath; and the captivity of Jerusalem, which is in Sepharad, shall possess the cities of the south.",
"",
"——【Obadiah 1】",
"",
"17 在锡安山必有逃脱的人，那山也必成圣；雅各家必得原有的产业。",
"18 雅各家必成为大火；约瑟家必为火焰；以扫家必如碎秸；火必将他烧著吞灭。以扫家必无余剩的。这是耶和华说的。",
"19 南地的人必得以扫山；高原的人必得非利士地，也得以法莲地和撒马利亚地；便雅悯人必得基列。",
"20 在迦南人中被掳的以色列众人必得地直到撒勒法；在西法拉中被掳的耶路撒冷人必得南地的城邑。",
"",
"——【俄巴底亚书 1】",
],
[
"1 The fool hath said in his heart, There is no God. Corrupt are they, and have done abominable iniquity: there is none that doeth good.",
"2 God looked down from heaven upon the children of men, to see if there were any that did understand, that did seek God.",
"3 Every one of them is gone back: they are altogether become filthy; there is none that doeth good, no, not one.",
"4 Have the workers of iniquity no knowledge? who eat up my people as they eat bread: they have not called upon God.",
"5 There were they in great fear, where no fear was: for God hath scattered the bones of him that encampeth against thee: thou hast put them to shame, because God hath despised them.",
"6 Oh that the salvation of Israel were come out of Zion! When God bringeth back the captivity of his people, Jacob shall rejoice, and Israel shall be glad.",
"",
"——【The Book of Psalms 53】",
"",
"1 （大卫的训诲诗，交与伶长。调用麻哈拉。）愚顽人心里说：没有　神。他们都是邪恶，行了可憎恶的罪孽；没有一个人行善。",
"2 　神从天上垂看世人，要看有明白的没有？有寻求他的没有？",
"3 他们各人都退后，一同变为污秽；并没有行善的，连一个也没有。",
"4 作孽的没有知识吗？他们吞吃我的百姓如同吃饭一样，并不求告　神。",
"5 他们在无可惧怕之处就大大害怕，因为　神把那安营攻击你之人的骨头散开了。你使他们蒙羞，因为　神弃绝了他们。",
"6 但愿以色列的救恩从锡安而出。　神救回他被掳的子民那时，雅各要快乐，以色列要欢喜。",
"",
"——【诗篇 53】",
],
[
"22 Having therefore obtained help of God, I continue unto this day, witnessing both to small and great, saying none other things than those which the prophets and Moses did say should come:",
"23 That Christ should suffer, and that he should be the first that should rise from the dead, and should shew light unto the people, and to the Gentiles.",
"24 And as he thus spake for himself, Festus said with a loud voice, Paul, thou art beside thyself; much learning doth make thee mad.",
"25 But he said, I am not mad, most noble Festus; but speak forth the words of truth and soberness.",
"26 For the king knoweth of these things, before whom also I speak freely: for I am persuaded that none of these things are hidden from him; for this thing was not done in a corner.",
"",
"——【The Acts of the Apostles 26】",
"",
"22 然而我蒙　神的帮助，直到今日还站得住，对著尊贵、卑贱、老幼作见证；所讲的并不外乎众先知和摩西所说将来必成的事，",
"23 就是基督必须受害，并且因从死里复活，要首先把光明的道传给百姓和外邦人。",
"24 保罗这样分诉，非斯都大声说：保罗，你癫狂了吧。你的学问太大，反叫你癫狂了！",
"25 保罗说：非斯都大人，我不是癫狂，我说的乃是真实明白话。",
"26 王也晓得这些事，所以我向王放胆直言，我深信这些事没有一件向王隐藏的，因都不是在背地里做的。",
"",
"——【使徒行传 26】",
],
[
"22 Having therefore obtained help of God, I continue unto this day, witnessing both to small and great, saying none other things than those which the prophets and Moses did say should come:",
"23 That Christ should suffer, and that he should be the first that should rise from the dead, and should shew light unto the people, and to the Gentiles.",
"24 And as he thus spake for himself, Festus said with a loud voice, Paul, thou art beside thyself; much learning doth make thee mad.",
"25 But he said, I am not mad, most noble Festus; but speak forth the words of truth and soberness.",
"26 For the king knoweth of these things, before whom also I speak freely: for I am persuaded that none of these things are hidden from him; for this thing was not done in a corner.",
"27 King Agrippa, believest thou the prophets? I know that thou believest.",
"",
"——【The Acts of the Apostles 26】",
"",
"22 然而我蒙　神的帮助，直到今日还站得住，对著尊贵、卑贱、老幼作见证；所讲的并不外乎众先知和摩西所说将来必成的事，",
"23 就是基督必须受害，并且因从死里复活，要首先把光明的道传给百姓和外邦人。",
"24 保罗这样分诉，非斯都大声说：保罗，你癫狂了吧。你的学问太大，反叫你癫狂了！",
"25 保罗说：非斯都大人，我不是癫狂，我说的乃是真实明白话。",
"26 王也晓得这些事，所以我向王放胆直言，我深信这些事没有一件向王隐藏的，因都不是在背地里做的。",
"27 亚基帕王啊，你信先知吗？我知道你是信的。",
"",
"——【使徒行传 26】",
],
[
"1 And I, brethren, could not speak unto you as unto spiritual, but as unto carnal, even as unto babes in Christ.",
"2 I have fed you with milk, and not with meat: for hitherto ye were not able to bear it, neither yet now are ye able.",
"3 For ye are yet carnal: for whereas there is among you envying, and strife, and divisions, are ye not carnal, and walk as men?",
"4 For while one saith, I am of Paul; and another, I am of Apollos; are ye not carnal?",
"",
"——【The First Epistle of Paul the Apostle to the Corinthians 3】",
"",
"1 弟兄们，我从前对你们说话，不能把你们当作属灵的，只得把你们当作属肉体，在基督里为婴孩的。",
"2 我是用奶喂你们，没有用饭喂你们。那时你们不能吃，就是如今还是不能。",
"3 你们仍是属肉体的，因为在你们中间有嫉妒、纷争，这岂不是属乎肉体、照著世人的样子行吗？",
"4 有说：我是属保罗的；有说：我是属亚波罗的。这岂不是你们和世人一样吗？",
"",
"——【哥林多前书 3】",
],
[
"16 And Naomi took the child, and laid it in her bosom, and became nurse unto it.",
"17 And the women her neighbours gave it a name, saying, There is a son born to Naomi; and they called his name Obed: he is the father of Jesse, the father of David.",
"18 Now these are the generations of Pharez: Pharez begat Hezron,",
"19 And Hezron begat Ram, and Ram begat Amminadab,",
"20 And Amminadab begat Nahshon, and Nahshon begat Salmon,",
"21 And Salmon begat Boaz, and Boaz begat Obed,",
"",
"——【The Book of Ruth 4】",
"",
"16 拿俄米就把孩子抱在怀中，作他的养母。",
"17 邻舍的妇人说：「拿俄米得孩子了！」就给孩子起名叫俄备得。这俄备得是耶西的父，耶西是大卫的父。",
"18 法勒斯的后代记在下面：法勒斯生希斯仑；",
"19 希斯仑生兰；兰生亚米拿达；",
"20 亚米拿达生拿顺；拿顺生撒门；",
"21 撒门生波阿斯；波阿斯生俄备得；",
"",
"——【路得记 4】",
],
[
"6 And it came to pass, that when he had commanded the man clothed with linen, saying, Take fire from between the wheels, from between the cherubims; then he went in, and stood beside the wheels.",
"7 And one cherub stretched forth his hand from between the cherubims unto the fire that was between the cherubims, and took thereof, and put it into the hands of him that was clothed with linen: who took it, and went out.",
"8 And there appeared in the cherubims the form of a man's hand under their wings.",
"9 And when I looked, behold the four wheels by the cherubims, one wheel by one cherub, and another wheel by another cherub: and the appearance of the wheels was as the colour of a beryl stone.",
"10 And as for their appearances, they four had one likeness, as if a wheel had been in the midst of a wheel.",
"11 When they went, they went upon their four sides; they turned not as they went, but to the place whither the head looked they followed it; they turned not as they went.",
"",
"——【The Book of the Prophet Ezekiel 10】",
"",
"6 他吩咐那穿细麻衣的人说：「要从旋转的轮内基路伯中间取火。」那人就进去站在一个轮子旁边。",
"7 有一个基路伯从基路伯中伸手到基路伯中间的火那里，取些放在那穿细麻衣的人两手中，那人就拿出去了。",
"8 在基路伯翅膀之下，显出有人手的样式。",
"9 我又观看，见基路伯旁边有四个轮子。这基路伯旁有一个轮子，那基路伯旁有一个轮子，每基路伯都是如此；轮子的颜色（原文是形状）彷彿水苍玉。",
"10 至于四轮的形状，都是一个样式，彷彿轮中套轮。",
"11 轮行走的时候，向四方都能直行，并不掉转。头向何方，他们也随向何方，行走的时候并不掉转。",
"",
"——【以西结书 10】",
],
[
"25 For he stretcheth out his hand against God, and strengtheneth himself against the Almighty.",
"26 He runneth upon him, even on his neck, upon the thick bosses of his bucklers:",
"",
"——【The Book of Job 15】",
"",
"25 他伸手攻击　神，以骄傲攻击全能者，",
"26 挺著颈项，用盾牌的厚凸面向全能者直闯；",
"",
"——【约伯记 15】",
],
[
"7 Or ministry, let us wait on our ministering: or he that teacheth, on teaching;",
"8 Or he that exhorteth, on exhortation: he that giveth, let him do it with simplicity; he that ruleth, with diligence; he that sheweth mercy, with cheerfulness.",
"9 Let love be without dissimulation. Abhor that which is evil; cleave to that which is good.",
"10 Be kindly affectioned one to another with brotherly love; in honour preferring one another;",
"",
"——【The Epistle of Paul the Apostle to the Romans 12】",
"",
"7 或作执事，就当专一执事；或作教导的，就当专一教导；",
"8 或作劝化的，就当专一劝化；施舍的，就当诚实；治理的，就当殷勤；怜悯人的，就当甘心。",
"9 爱人不可虚假；恶要厌恶，善要亲近。",
"10 爱弟兄，要彼此亲热；恭敬人，要彼此推让。",
"",
"——【罗马书 12】",
],
[
"1 LORD, who shall abide in thy tabernacle? who shall dwell in thy holy hill?",
"2 He that walketh uprightly, and worketh righteousness, and speaketh the truth in his heart.",
"",
"——【The Book of Psalms 15】",
"",
"1 （大卫的诗。）耶和华啊，谁能寄居你的帐幕？谁能住在你的圣山？",
"2 就是行为正直、做事公义、心里说实话的人。",
"",
"——【诗篇 15】",
],
[
"6 These are the children of the province, that went up out of the captivity, of those that had been carried away, whom Nebuchadnezzar the king of Babylon had carried away, and came again to Jerusalem and to Judah, every one unto his city;",
"7 Who came with Zerubbabel, Jeshua, Nehemiah, Azariah, Raamiah, Nahamani, Mordecai, Bilshan, Mispereth, Bigvai, Nehum, Baanah. The number, I say, of the men of the people of Israel was this;",
"8 The children of Parosh, two thousand an hundred seventy and two.",
"9 The children of Shephatiah, three hundred seventy and two.",
"10 The children of Arah, six hundred fifty and two.",
"11 The children of Pahath–moab, of the children of Jeshua and Joab, two thousand and eight hundred and eighteen.",
"",
"——【The Book of Nehemiah 7】",
"",
"6 巴比伦王尼布甲尼撒从前掳去犹大省的人，现在他们的子孙从被掳到之地回耶路撒冷和犹大，各归本城。",
"7 他们是同著所罗巴伯、耶书亚、尼希米、亚撒利雅、拉米、拿哈玛尼、末底改、必珊、米斯毗列、比革瓦伊、尼宏、巴拿回来的。",
"8 以色列人民的数目记在下面：巴录的子孙二千一百七十二名；",
"9 示法提雅的子孙三百七十二名；",
"10 亚拉的子孙六百五十二名；",
"11 巴哈摩押的后裔，就是耶书亚和约押的子孙二千八百一十八名；",
"",
"——【尼希米记 7】",
],
[
"9 And Esau said, I have enough, my brother; keep that thou hast unto thyself.",
"10 And Jacob said, Nay, I pray thee, if now I have found grace in thy sight, then receive my present at my hand: for therefore I have seen thy face, as though I had seen the face of God, and thou wast pleased with me.",
"11 Take, I pray thee, my blessing that is brought to thee; because God hath dealt graciously with me, and because I have enough. And he urged him, and he took it.",
"12 And he said, Let us take our journey, and let us go, and I will go before thee.",
"13 And he said unto him, My lord knoweth that the children are tender, and the flocks and herds with young are with me: and if men should overdrive them one day, all the flock will die.",
"",
"——【The First Book of Moses: Called Genesis 33】",
"",
"9 以扫说：「兄弟啊，我的已经够了，你的仍归你吧！」",
"10 雅各说：「不然，我若在你眼前蒙恩，就求你从我手里收下这礼物；因为我见了你的面，如同见了　神的面，并且你容纳了我。",
"11 求你收下我带来给你的礼物；因为　神恩待我，使我充足。」雅各再三地求他，他才收下了。",
"12 以扫说：「我们可以起身前往，我在你前头走。」",
"13 雅各对他说：「我主知道孩子们年幼娇嫩，牛羊也正在乳养的时候，若是催赶一天，群畜都必死了。",
"",
"——【创世记 33】",
],
[
"45 He sent divers sorts of flies among them, which devoured them; and frogs, which destroyed them.",
"46 He gave also their increase unto the caterpiller, and their labour unto the locust.",
"47 He destroyed their vines with hail, and their sycomore trees with frost.",
"48 He gave up their cattle also to the hail, and their flocks to hot thunderbolts.",
"",
"——【The Book of Psalms 78】",
"",
"45 他叫苍蝇成群落在他们当中，嘬尽他们，又叫青蛙灭了他们，",
"46 把他们的土产交给蚂蚱，把他们辛苦得来的交给蝗虫。",
"47 他降冰雹打坏他们的葡萄树，下严霜打坏他们的桑树，",
"48 又把他们的牲畜交给冰雹，把他们的群畜交给闪电。",
"",
"——【诗篇 78】",
],
[
"1 It is reported commonly that there is fornication among you, and such fornication as is not so much as named among the Gentiles, that one should have his father's wife.",
"2 And ye are puffed up, and have not rather mourned, that he that hath done this deed might be taken away from among you.",
"3 For I verily, as absent in body, but present in spirit, have judged already, as though I were present, concerning him that hath so done this deed,",
"",
"——【The First Epistle of Paul the Apostle to the Corinthians 5】",
"",
"1 风闻在你们中间有淫乱的事。这样的淫乱连外邦人中也没有，就是有人收了他的继母。",
"2 你们还是自高自大，并不哀痛，把行这事的人从你们中间赶出去。",
"3 我身子虽不在你们那里，心却在你们那里，好像我亲自与你们同在，已经判断了行这事的人。",
"",
"——【哥林多前书 5】",
],
];
