var bible31_global=[
[
"4 I am a stranger and a sojourner with you: give me a possession of a buryingplace with you, that I may bury my dead out of my sight.",
"5 And the children of Heth answered Abraham, saying unto him,",
"6 Hear us, my lord: thou art a mighty prince among us: in the choice of our sepulchres bury thy dead; none of us shall withhold from thee his sepulchre, but that thou mayest bury thy dead.",
"",
"——【The First Book of Moses: Called Genesis 23】",
"",
"4 「我在你们中间是外人，是寄居的。求你们在这里给我一块地，我好埋葬我的死人，使她不在我眼前。」",
"5 赫人回答亚伯拉罕说：",
"6 「我主请听。你在我们中间是一位尊大的王子，只管在我们最好的坟地里埋葬你的死人；我们没有一人不容你在他的坟地里埋葬你的死人。」",
"",
"——【创世记 23】",
],
[
"10 And Johanan begat Azariah, (he it is that executed the priest's office in the temple that Solomon built in Jerusalem:)",
"11 And Azariah begat Amariah, and Amariah begat Ahitub,",
"",
"——【The First Book of the Chronicles 6】",
"",
"10 约哈难生亚撒利雅（这亚撒利雅在所罗门于耶路撒冷所建造的殿中，供祭司的职分）；",
"11 亚撒利雅生亚玛利雅；亚玛利雅生亚希突；",
"",
"——【历代志上 6】",
],
[
"7 And some fell among thorns; and the thorns sprang up with it, and choked it.",
"8 And other fell on good ground, and sprang up, and bare fruit an hundredfold. And when he had said these things, he cried, He that hath ears to hear, let him hear.",
"9 And his disciples asked him, saying, What might this parable be?",
"",
"——【The Gospel According to Saint Luke 8】",
"",
"7 有落在荆棘里的，荆棘一同生长，把它挤住了。",
"8 又有落在好土里的，生长起来，结实百倍。耶稣说了这些话，就大声说：有耳可听的，就应当听！",
"9 门徒问耶稣说：这比喻是什么意思呢？",
"",
"——【路加福音 8】",
],
[
"24 Then the congregation shall judge between the slayer and the revenger of blood according to these judgments:",
"25 And the congregation shall deliver the slayer out of the hand of the revenger of blood, and the congregation shall restore him to the city of his refuge, whither he was fled: and he shall abide in it unto the death of the high priest, which was anointed with the holy oil.",
"26 But if the slayer shall at any time come without the border of the city of his refuge, whither he was fled;",
"27 And the revenger of blood find him without the borders of the city of his refuge, and the revenger of blood kill the slayer; he shall not be guilty of blood:",
"28 Because he should have remained in the city of his refuge until the death of the high priest: but after the death of the high priest the slayer shall return into the land of his possession.",
"29 So these things shall be for a statute of judgment unto you throughout your generations in all your dwellings.",
"",
"——【The Fourth Book of Moses: Called Numbers 35】",
"",
"24 会众就要照典章，在打死人的和报血仇的中间审判。",
"25 会众要救这误杀人的脱离报血仇人的手，也要使他归入逃城。他要住在其中，直等到受圣膏的大祭司死了。",
"26 但误杀人的，无论什么时候，若出了逃城的境外，",
"27 报血仇的在逃城境外遇见他，将他杀了，报血仇的就没有流血之罪。",
"28 因为误杀人的该住在逃城里，等到大祭司死了。大祭司死了以后，误杀人的才可以回到他所得为业之地。",
"29 这在你们一切的住处，要作你们世世代代的律例典章。",
"",
"——【民数记 35】",
],
[
"5 And they found Adoni–bezek in Bezek: and they fought against him, and they slew the Canaanites and the Perizzites.",
"6 But Adoni–bezek fled; and they pursued after him, and caught him, and cut off his thumbs and his great toes.",
"7 And Adoni–bezek said, Threescore and ten kings, having their thumbs and their great toes cut off, gathered their meat under my table: as I have done, so God hath requited me. And they brought him to Jerusalem, and there he died.",
"8 Now the children of Judah had fought against Jerusalem, and had taken it, and smitten it with the edge of the sword, and set the city on fire.",
"",
"——【The Book of Judges 1】",
"",
"5 又在那里遇见亚多尼比色，与他争战，杀败迦南人和比利洗人。",
"6 亚多尼比色逃跑；他们追赶，拿住他，砍断他手脚的大姆指。",
"7 亚多尼比色说：「从前有七十个王，手脚的大姆指都被我砍断，在我桌子底下拾取零碎食物。现在　神按著我所行的报应我了。」于是他们将亚多尼比色带到耶路撒冷，他就死在那里。",
"8 犹大人攻打耶路撒冷，将城攻取，用刀杀了城内的人，并且放火烧城。",
"",
"——【士师记 1】",
],
[
"1 Hear this word, ye kine of Bashan, that are in the mountain of Samaria, which oppress the poor, which crush the needy, which say to their masters, Bring, and let us drink.",
"2 The Lord GOD hath sworn by his holiness, that, lo, the days shall come upon you, that he will take you away with hooks, and your posterity with fishhooks.",
"3 And ye shall go out at the breaches, every cow at that which is before her; and ye shall cast them into the palace, saith the LORD.",
"4 Come to Beth–el, and transgress; at Gilgal multiply transgression; and bring your sacrifices every morning, and your tithes after three years:",
"",
"——【Amos 4】",
"",
"1 你们住撒马利亚山如巴珊母牛的啊，当听我的话─你们欺负贫寒的，压碎穷乏的，对家主说：拿酒来，我们喝吧！",
"2 主耶和华指着自己的圣洁起誓说：日子快到，人必用钩子将你们钩去，用鱼钩将你们余剩的钩去。",
"3 你们各人必从破口直往前行，投入哈门。这是耶和华说的。",
"4 以色列人哪，任你们往伯特利去犯罪，到吉甲加增罪过；每日早晨献上你们的祭物，每三日奉上你们的十分之一。",
"",
"——【阿摩司书 4】",
],
[
"23 Rejoice ye in that day, and leap for joy: for, behold, your reward is great in heaven: for in the like manner did their fathers unto the prophets.",
"24 But woe unto you that are rich! for ye have received your consolation.",
"25 Woe unto you that are full! for ye shall hunger. Woe unto you that laugh now! for ye shall mourn and weep.",
"26 Woe unto you, when all men shall speak well of you! for so did their fathers to the false prophets.",
"",
"——【The Gospel According to Saint Luke 6】",
"",
"23 当那日，你们要欢喜跳跃，因为你们在天上的赏赐是大的。他们的祖宗待先知也是这样。",
"24 但你们富足的人有祸了！因为你们受过你们的安慰。",
"25 你们饱足的人有祸了！因为你们将要饥饿。你们喜笑的人有祸了！因为你们将要哀恸哭泣。",
"26 人都说你们好的时候，你们就有祸了！因为他们的祖宗待假先知也是这样。",
"",
"——【路加福音 6】",
],
[
"7 In whom we have redemption through his blood, the forgiveness of sins, according to the riches of his grace;",
"8 Wherein he hath abounded toward us in all wisdom and prudence;",
"",
"——【The Epistle of Paul the Apostle to the Ephesians 1】",
"",
"7 我们借这爱子的血得蒙救赎，过犯得以赦免，乃是照他丰富的恩典。",
"8 这恩典是　神用诸般智慧聪明，充充足足赏给我们的；",
"",
"——【以弗所书 1】",
],
[
"25 That be far from thee to do after this manner, to slay the righteous with the wicked: and that the righteous should be as the wicked, that be far from thee: Shall not the Judge of all the earth do right?",
"26 And the LORD said, If I find in Sodom fifty righteous within the city, then I will spare all the place for their sakes.",
"27 And Abraham answered and said, Behold now, I have taken upon me to speak unto the Lord, which am but dust and ashes:",
"",
"——【The First Book of Moses: Called Genesis 18】",
"",
"25 将义人与恶人同杀，将义人与恶人一样看待，这断不是你所行的。审判全地的主岂不行公义吗？」",
"26 耶和华说：「我若在所多玛城里见有五十个义人，我就为他们的缘故饶恕那地方的众人。」",
"27 亚伯拉罕说：「我虽然是灰尘，还敢对主说话。",
"",
"——【创世记 18】",
],
[
"10 And all the people saw the cloudy pillar stand at the tabernacle door: and all the people rose up and worshipped, every man in his tent door.",
"11 And the LORD spake unto Moses face to face, as a man speaketh unto his friend. And he turned again into the camp: but his servant Joshua, the son of Nun, a young man, departed not out of the tabernacle.",
"12 And Moses said unto the LORD, See, thou sayest unto me, Bring up this people: and thou hast not let me know whom thou wilt send with me. Yet thou hast said, I know thee by name, and thou hast also found grace in my sight.",
"13 Now therefore, I pray thee, if I have found grace in thy sight, shew me now thy way, that I may know thee, that I may find grace in thy sight: and consider that this nation is thy people.",
"",
"——【The Second Book of Moses: Called Exodus 33】",
"",
"10 众百姓看见云柱立在会幕门前，就都起来，各人在自己帐棚的门口下拜。",
"11 耶和华与摩西面对面说话，好像人与朋友说话一般。摩西转到营里去，惟有他的帮手─一个少年人嫩的儿子约书亚不离开会幕。",
"12 摩西对耶和华说：「你吩咐我说：『将这百姓领上去』，却没有叫我知道你要打发谁与我同去，只说：『我按你的名认识你，你在我眼前也蒙了恩。』",
"13 我如今若在你眼前蒙恩，求你将你的道指示我，使我可以认识你，好在你眼前蒙恩。求你想到这民是你的民。」",
"",
"——【出埃及记 33】",
],
[
"13 Yet it came to pass, when the children of Israel were waxen strong, that they put the Canaanites to tribute; but did not utterly drive them out.",
"14 And the children of Joseph spake unto Joshua, saying, Why hast thou given me but one lot and one portion to inherit, seeing I am a great people, forasmuch as the LORD hath blessed me hitherto?",
"15 And Joshua answered them, If thou be a great people, then get thee up to the wood country, and cut down for thyself there in the land of the Perizzites and of the giants, if mount Ephraim be too narrow for thee.",
"",
"——【The Book of Joshua 17】",
"",
"13 及至以色列人强盛了，就使迦南人做苦工，没有把他们全然赶出。",
"14 约瑟的子孙对约书亚说：「耶和华到如今既然赐福与我们，我们也族大人多，你为什么仅将一阄一段之地分给我们为业呢？」",
"15 约书亚说：「你们如果族大人多，嫌以法莲山地窄小，就可以上比利洗人、利乏音人之地，在树林中砍伐树木。」",
"",
"——【约书亚记 17】",
],
[
"6 This poor man cried, and the LORD heard him, and saved him out of all his troubles.",
"7 The angel of the LORD encampeth round about them that fear him, and delivereth them.",
"8 O taste and see that the LORD is good: blessed is the man that trusteth in him.",
"9 O fear the LORD, ye his saints: for there is no want to them that fear him.",
"10 The young lions do lack, and suffer hunger: but they that seek the LORD shall not want any good thing.",
"11 Come, ye children, hearken unto me: I will teach you the fear of the LORD.",
"",
"——【The Book of Psalms 34】",
"",
"6 我这困苦人呼求，耶和华便垂听，救我脱离一切患难。",
"7 耶和华的使者在敬畏他的人四围安营，搭救他们。",
"8 你们要尝尝主恩的滋味，便知道他是美善；投靠他的人有福了！",
"9 耶和华的圣民哪，你们当敬畏他，因敬畏他的一无所缺。",
"10 少壮狮子还缺食忍饿，但寻求耶和华的什么好处都不缺。",
"11 众弟子啊，你们当来听我的话！我要将敬畏耶和华的道教训你们。",
"",
"——【诗篇 34】",
],
[
"18 Because thou obeyedst not the voice of the LORD, nor executedst his fierce wrath upon Amalek, therefore hath the LORD done this thing unto thee this day.",
"19 Moreover the LORD will also deliver Israel with thee into the hand of the Philistines: and to morrow shalt thou and thy sons be with me: the LORD also shall deliver the host of Israel into the hand of the Philistines.",
"20 Then Saul fell straightway all along on the earth, and was sore afraid, because of the words of Samuel: and there was no strength in him; for he had eaten no bread all the day, nor all the night.",
"",
"——【The First Book of Samuel 28】",
"",
"18 因你没有听从耶和华的命令；他恼怒亚玛力人，你没有灭绝他们，所以今日耶和华向你这样行，",
"19 并且耶和华必将你和以色列人交在非利士人的手里。明日你和你众子必与我在一处了；耶和华必将以色列的军兵交在非利士人手里。」",
"20 扫罗猛然仆倒，挺身在地，因撒母耳的话甚是惧怕；那一昼一夜没有吃什么，就毫无气力。",
"",
"——【撒母耳记上 28】",
],
[
"2 Because he hath inclined his ear unto me, therefore will I call upon him as long as I live.",
"3 The sorrows of death compassed me, and the pains of hell gat hold upon me: I found trouble and sorrow.",
"4 Then called I upon the name of the LORD; O LORD, I beseech thee, deliver my soul.",
"5 Gracious is the LORD, and righteous; yea, our God is merciful.",
"6 The LORD preserveth the simple: I was brought low, and he helped me.",
"",
"——【The Book of Psalms 116】",
"",
"2 他既向我侧耳，我一生要求告他。",
"3 死亡的绳索缠绕我；阴间的痛苦抓住我；我遭遇患难愁苦。",
"4 那时，我便求告耶和华的名，说：耶和华啊，求你救我的灵魂！",
"5 耶和华有恩惠，有公义；我们的　神以怜悯为怀。",
"6 耶和华保护愚人；我落到卑微的地步，他救了我。",
"",
"——【诗篇 116】",
],
[
"1 In the LORD put I my trust: how say ye to my soul, Flee as a bird to your mountain?",
"2 For, lo, the wicked bend their bow, they make ready their arrow upon the string, that they may privily shoot at the upright in heart.",
"3 If the foundations be destroyed, what can the righteous do?",
"4 The LORD is in his holy temple, the LORD'S throne is in heaven: his eyes behold, his eyelids try, the children of men.",
"5 The LORD trieth the righteous: but the wicked and him that loveth violence his soul hateth.",
"",
"——【The Book of Psalms 11】",
"",
"1 （大卫的诗，交与伶长。）我是投靠耶和华；你们怎么对我说：你当像鸟飞往你的山去。",
"2 看哪，恶人弯弓，把箭搭在弦上，要在暗中射那心里正直的人。",
"3 根基若毁坏，义人还能做什么呢？",
"4 耶和华在他的圣殿里；耶和华的宝座在天上；他的慧眼察看世人。",
"5 耶和华试验义人；惟有恶人和喜爱强暴的人，他心里恨恶。",
"",
"——【诗篇 11】",
],
[
"13 And he put forth his hand, and touched him, saying, I will: be thou clean. And immediately the leprosy departed from him.",
"14 And he charged him to tell no man: but go, and shew thyself to the priest, and offer for thy cleansing, according as Moses commanded, for a testimony unto them.",
"",
"——【The Gospel According to Saint Luke 5】",
"",
"13 耶稣伸手摸他，说：我肯，你洁净了吧！大痲疯立刻就离了他的身。",
"14 耶稣嘱咐他：你切不可告诉人，只要去把身体给祭司察看，又要为你得了洁净，照摩西所吩咐的献上礼物，对众人作证据。",
"",
"——【路加福音 5】",
],
[
"1 Then said the LORD unto me, Go yet, love a woman beloved of her friend, yet an adulteress, according to the love of the LORD toward the children of Israel, who look to other gods, and love flagons of wine.",
"2 So I bought her to me for fifteen pieces of silver, and for an homer of barley, and an half homer of barley:",
"3 And I said unto her, Thou shalt abide for me many days; thou shalt not play the harlot, and thou shalt not be for another man: so will I also be for thee.",
"4 For the children of Israel shall abide many days without a king, and without a prince, and without a sacrifice, and without an image, and without an ephod, and without teraphim:",
"5 Afterward shall the children of Israel return, and seek the LORD their God, and David their king; and shall fear the LORD and his goodness in the latter days.",
"",
"——【Hosea 3】",
"",
"1 耶和华对我说：「你再去爱一个淫妇，就是她情人所爱的；好像以色列人，虽然偏向别神，喜爱葡萄饼，耶和华还是爱他们。」",
"2 我便用银子十五舍客勒，大麦一贺梅珥半，买她归我。",
"3 我对她说：「你当多日为我独居，不可行淫，不可归别人为妻，我向你也必这样。」",
"4 以色列人也必多日独居，无君王，无首领，无祭祀，无柱像，无以弗得，无家中的神像。",
"5 后来以色列人必归回（或译：回心转意），寻求他们的　神─耶和华和他们的王大卫。在末后的日子，必以敬畏的心归向耶和华，领受他的恩惠。",
"",
"——【何西阿书 3】",
],
[
"3 Be not hasty to go out of his sight: stand not in an evil thing; for he doeth whatsoever pleaseth him.",
"4 Where the word of a king is, there is power: and who may say unto him, What doest thou?",
"",
"——【Ecclesiastes 8】",
"",
"3 不要急躁离开王的面前，不要固执行恶，因为他凡事都随自己的心意而行。",
"4 王的话本有权力，谁敢问他说「你做什么呢？」",
"",
"——【传道书 8】",
],
[
"2 One basket had very good figs, even like the figs that are first ripe: and the other basket had very naughty figs, which could not be eaten, they were so bad.",
"3 Then said the LORD unto me, What seest thou, Jeremiah? And I said, Figs; the good figs, very good; and the evil, very evil, that cannot be eaten, they are so evil.",
"4 Again the word of the LORD came unto me, saying,",
"5 Thus saith the LORD, the God of Israel; Like these good figs, so will I acknowledge them that are carried away captive of Judah, whom I have sent out of this place into the land of the Chaldeans for their good.",
"6 For I will set mine eyes upon them for good, and I will bring them again to this land: and I will build them, and not pull them down; and I will plant them, and not pluck them up.",
"7 And I will give them an heart to know me, that I am the LORD: and they shall be my people, and I will be their God: for they shall return unto me with their whole heart.",
"",
"——【The Book of the Prophet Jeremiah 24】",
"",
"2 一筐是极好的无花果，好像是初熟的；一筐是极坏的无花果，坏得不可吃。",
"3 于是耶和华问我说：「耶利米你看见什么？」我说：「我看见无花果，好的极好，坏的极坏，坏得不可吃。」",
"4 耶和华的话临到我说：",
"5 「耶和华─以色列的　神如此说：被掳去的犹大人，就是我打发离开这地到迦勒底人之地去的，我必看顾他们如这好无花果，使他们得好处。",
"6 我要眷顾他们，使他们得好处，领他们归回这地。我也要建立他们，必不拆毁；栽植他们，并不拔出。",
"7 我要赐他们认识我的心，知道我是耶和华。他们要作我的子民，我要作他们的　神，因为他们要一心归向我。」",
"",
"——【耶利米书 24】",
],
[
"5 Thus saith the LORD concerning the prophets that make my people err, that bite with their teeth, and cry, Peace; and he that putteth not into their mouths, they even prepare war against him.",
"6 Therefore night shall be unto you, that ye shall not have a vision; and it shall be dark unto you, that ye shall not divine; and the sun shall go down over the prophets, and the day shall be dark over them.",
"",
"——【Micah 3】",
"",
"5 论到使我民走差路的先知─他们牙齿有所嚼的，他们就呼喊说：平安了！凡不供给他们吃的，他们就预备攻击他（预备攻击他：或译说必遭遇刀兵）─耶和华如此说：",
"6 你们必遭遇黑夜，以致不见异象；又必遭遇幽暗，以致不能占卜。日头必向你们沉落，白昼变为黑暗。",
"",
"——【弥迦书 3】",
],
[
"1 Him that is weak in the faith receive ye, but not to doubtful disputations.",
"2 For one believeth that he may eat all things: another, who is weak, eateth herbs.",
"",
"——【The Epistle of Paul the Apostle to the Romans 14】",
"",
"1 信心软弱的，你们要接纳，但不要辩论所疑惑的事。",
"2 有人信百物都可吃；但那软弱的，只吃蔬菜。",
"",
"——【罗马书 14】",
],
[
"17 And ye have seen their abominations, and their idols, wood and stone, silver and gold, which were among them:)",
"18 Lest there should be among you man, or woman, or family, or tribe, whose heart turneth away this day from the LORD our God, to go and serve the gods of these nations; lest there should be among you a root that beareth gall and wormwood;",
"19 And it come to pass, when he heareth the words of this curse, that he bless himself in his heart, saying, I shall have peace, though I walk in the imagination of mine heart, to add drunkenness to thirst:",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 29】",
"",
"17 你们也看见他们中间可憎之物，并他们木、石、金、银的偶像。",
"18 惟恐你们中间，或男或女，或族长或支派长，今日心里偏离耶和华─我们的　神，去事奉那些国的　神；又怕你们中间有恶根生出苦菜和茵蔯来，",
"19 听见这咒诅的话，心里仍是自夸说：『我虽然行事心里顽梗，连累众人，却还是平安。』",
"",
"——【申命记 29】",
],
[
"27 Say thou thus unto them, Thus saith the Lord GOD; As I live, surely they that are in the wastes shall fall by the sword, and him that is in the open field will I give to the beasts to be devoured, and they that be in the forts and in the caves shall die of the pestilence.",
"28 For I will lay the land most desolate, and the pomp of her strength shall cease; and the mountains of Israel shall be desolate, that none shall pass through.",
"29 Then shall they know that I am the LORD, when I have laid the land most desolate because of all their abominations which they have committed.",
"30 Also, thou son of man, the children of thy people still are talking against thee by the walls and in the doors of the houses, and speak one to another, every one to his brother, saying, Come, I pray you, and hear what is the word that cometh forth from the LORD.",
"31 And they come unto thee as the people cometh, and they sit before thee as my people, and they hear thy words, but they will not do them: for with their mouth they shew much love, but their heart goeth after their covetousness.",
"32 And, lo, thou art unto them as a very lovely song of one that hath a pleasant voice, and can play well on an instrument: for they hear thy words, but they do them not.",
"",
"——【The Book of the Prophet Ezekiel 33】",
"",
"27 你要对他们这样说，主耶和华如此说：我指着我的永生起誓，在荒场中的，必倒在刀下；在田野间的，必交给野兽吞吃；在保障和洞里的，必遭瘟疫而死。",
"28 我必使这地荒凉，令人惊骇；她因势力而有的骄傲也必止息。以色列的山都必荒凉，无人经过。",
"29 我因他们所行一切可憎的事使地荒凉，令人惊骇。那时，他们就知道我是耶和华。」",
"30 「人子啊，你本国的子民在墙垣旁边、在房屋门口谈论你。弟兄对弟兄彼此说：『来吧！听听有什么话从耶和华而出。』",
"31 他们来到你这里如同民来聚会，坐在你面前彷彿是我的民。他们听你的话却不去行；因为他们的口多显爱情，心却追随财利。",
"32 他们看你如善于奏乐、声音幽雅之人所唱的雅歌，他们听你的话却不去行。",
"",
"——【以西结书 33】",
],
[
"3 And death shall be chosen rather than life by all the residue of them that remain of this evil family, which remain in all the places whither I have driven them, saith the LORD of hosts.",
"4 Moreover thou shalt say unto them, Thus saith the LORD; Shall they fall, and not arise? shall he turn away, and not return?",
"",
"——【The Book of the Prophet Jeremiah 8】",
"",
"3 并且这恶族所剩下的民在我所赶他们到的各处，宁可拣死不拣生。这是万军之耶和华说的。」",
"4 你要对他们说，耶和华如此说：人跌倒，不再起来吗？人转去，不再转来吗？",
"",
"——【耶利米书 8】",
],
[
"14 And when Abram heard that his brother was taken captive, he armed his trained servants, born in his own house, three hundred and eighteen, and pursued them unto Dan.",
"15 And he divided himself against them, he and his servants, by night, and smote them, and pursued them unto Hobah, which is on the left hand of Damascus.",
"16 And he brought back all the goods, and also brought again his brother Lot, and his goods, and the women also, and the people.",
"",
"——【The First Book of Moses: Called Genesis 14】",
"",
"14 亚伯兰听见他侄儿【原文作弟兄】被掳去，就率领他家里生养的精练壮丁三百一十八人，直追到但，",
"15 便在夜间，自己同仆人分队杀败敌人，又追到大马士革左边的何把，",
"16 将被掳掠的一切财物夺回来，连他侄儿罗得和他的财物，以及妇女、人民也都夺回来。",
"",
"——【创世记 14】",
],
[
"13 Who hath delivered us from the power of darkness, and hath translated us into the kingdom of his dear Son:",
"14 In whom we have redemption through his blood, even the forgiveness of sins:",
"",
"——【The Epistle of Paul the Apostle to the Colossians 1】",
"",
"13 他救了我们脱离黑暗的权势，把我们迁到他爱子的国里；",
"14 我们在爱子里得蒙救赎，罪过得以赦免。",
"",
"——【歌罗西书 1】",
],
[
"11 For whereas my father put a heavy yoke upon you, I will put more to your yoke: my father chastised you with whips, but I will chastise you with scorpions.",
"12 So Jeroboam and all the people came to Rehoboam on the third day, as the king bade, saying, Come again to me on the third day.",
"13 And the king answered them roughly; and king Rehoboam forsook the counsel of the old men,",
"14 And answered them after the advice of the young men, saying, My father made your yoke heavy, but I will add thereto: my father chastised you with whips, but I will chastise you with scorpions.",
"15 So the king hearkened not unto the people: for the cause was of God, that the LORD might perform his word, which he spake by the hand of Ahijah the Shilonite to Jeroboam the son of Nebat.",
"16 And when all Israel saw that the king would not hearken unto them, the people answered the king, saying, What portion have we in David? and we have none inheritance in the son of Jesse: every man to your tents, O Israel: and now, David, see to thine own house. So all Israel went to their tents.",
"",
"——【The Second Book of the Chronicles 10】",
"",
"11 我父亲使你们负重轭，我必使你们负更重的轭；我父亲用鞭子责打你们，我要用蠍子鞭责打你们。』」",
"12 耶罗波安和众百姓遵著罗波安王所说「你们第三日再来见我」的那话，第三日他们果然来了。",
"13 罗波安王用严厉的话回覆他们，不用老年人所出的主意，",
"14 照著少年人所出的主意对他们说：「我父亲使你们负重轭，我必使你们负更重的轭；我父亲用鞭子责打你们，我要用蠍子鞭责打你们。」",
"15 王不肯依从百姓；这事乃出于　神，为要应验耶和华借示罗人亚希雅对尼八儿子耶罗波安所说的话。",
"16 以色列众民见王不依从他们，就对王说：我们与大卫有什么分儿呢？与耶西的儿子并没有关涉！以色列人哪，各回各家去吧！大卫家啊，自己顾自己吧！于是，以色列众人都回自己家里去了。",
"",
"——【历代志下 10】",
],
[
"2 For one believeth that he may eat all things: another, who is weak, eateth herbs.",
"3 Let not him that eateth despise him that eateth not; and let not him which eateth not judge him that eateth: for God hath received him.",
"4 Who art thou that judgest another man's servant? to his own master he standeth or falleth. Yea, he shall be holden up: for God is able to make him stand.",
"",
"——【The Epistle of Paul the Apostle to the Romans 14】",
"",
"2 有人信百物都可吃；但那软弱的，只吃蔬菜。",
"3 吃的人不可轻看不吃的人；不吃的人不可论断吃的人；因为　神已经收纳他了。",
"4 你是谁，竟论断别人的仆人呢？他或站住，或跌倒，自有他的主人在；而且他也必要站住，因为主能使他站住。",
"",
"——【罗马书 14】",
],
[
"8 And his host, and those that were numbered thereof, were fifty and seven thousand and four hundred.",
"9 All that were numbered in the camp of Judah were an hundred thousand and fourscore thousand and six thousand and four hundred, throughout their armies. These shall first set forth.",
"10 On the south side shall be the standard of the camp of Reuben according to their armies: and the captain of the children of Reuben shall be Elizur the son of Shedeur.",
"11 And his host, and those that were numbered thereof, were forty and six thousand and five hundred.",
"12 And those which pitch by him shall be the tribe of Simeon: and the captain of the children of Simeon shall be Shelumiel the son of Zurishaddai.",
"13 And his host, and those that were numbered of them, were fifty and nine thousand and three hundred.",
"",
"——【The Fourth Book of Moses: Called Numbers 2】",
"",
"8 他军队被数的，共有五万七千四百名。",
"9 凡属犹大营按着军队被数的，共有十八万六千四百名，要作第一队往前行。",
"10 「在南边，按着军队是流便营的纛。有示丢珥的儿子以利蓿作流便人的首领。",
"11 他军队被数的，共有四万六千五百名。",
"12 挨著他安营的是西缅支派。苏利沙代的儿子示路蔑作西缅人的首领。",
"13 他军队被数的，共有五万九千三百名。",
"",
"——【民数记 2】",
],
[
"1 Ahaz was twenty years old when he began to reign, and he reigned sixteen years in Jerusalem: but he did not that which was right in the sight of the LORD, like David his father:",
"2 For he walked in the ways of the kings of Israel, and made also molten images for Baalim.",
"3 Moreover he burnt incense in the valley of the son of Hinnom, and burnt his children in the fire, after the abominations of the heathen whom the LORD had cast out before the children of Israel.",
"4 He sacrificed also and burnt incense in the high places, and on the hills, and under every green tree.",
"5 Wherefore the LORD his God delivered him into the hand of the king of Syria; and they smote him, and carried away a great multitude of them captives, and brought them to Damascus. And he was also delivered into the hand of the king of Israel, who smote him with a great slaughter.",
"",
"——【The Second Book of the Chronicles 28】",
"",
"1 亚哈斯登基的时候年二十岁，在耶路撒冷作王十六年；不像他祖大卫行耶和华眼中看为正的事，",
"2 却行以色列诸王的道，又铸造巴力的像，",
"3 并且在欣嫩子谷烧香，用火焚烧他的儿女，行耶和华在以色列人面前所驱逐的外邦人那可憎的事；",
"4 并在邱坛上、山冈上、各青翠树下献祭烧香。",
"5 所以，耶和华─他的　神将他交在亚兰王手里。亚兰王打败他，掳了他许多的民，带到大马色去。　神又将他交在以色列王手里，以色列王向他大行杀戮。",
"",
"——【历代志下 28】",
],
[
"7 For the mystery of iniquity doth already work: only he who now letteth will let, until he be taken out of the way.",
"8 And then shall that Wicked be revealed, whom the Lord shall consume with the spirit of his mouth, and shall destroy with the brightness of his coming:",
"",
"——【The Second Epistle of Paul the Apostle to the Thessalonians 2】",
"",
"7 因为那不法的隐意已经发动，只是现在有一个拦阻的，等到那拦阻的被除去，",
"8 那时这不法的人必显露出来。主耶稣要用口中的气灭绝他，用降临的荣光废掉他。",
"",
"——【帖撒罗尼迦后书 2】",
],
];
