var bible31_global=[
[
"15 I will feed my flock, and I will cause them to lie down, saith the Lord GOD.",
"16 I will seek that which was lost, and bring again that which was driven away, and will bind up that which was broken, and will strengthen that which was sick: but I will destroy the fat and the strong; I will feed them with judgment.",
"17 And as for you, O my flock, thus saith the Lord GOD; Behold, I judge between cattle and cattle, between the rams and the he goats.",
"18 Seemeth it a small thing unto you to have eaten up the good pasture, but ye must tread down with your feet the residue of your pastures? and to have drunk of the deep waters, but ye must foul the residue with your feet?",
"19 And as for my flock, they eat that which ye have trodden with your feet; and they drink that which ye have fouled with your feet.",
"",
"——【The Book of the Prophet Ezekiel 34】",
"",
"15 主耶和华说：我必亲自作我羊的牧人，使牠们得以躺卧。",
"16 失丧的，我必寻找；被逐的，我必领回；受伤的，我必缠裹；有病的，我必医治；只是肥的壮的，我必除灭，也要秉公牧养牠们。",
"17 「我的羊群哪，论到你们，主耶和华如此说：我必在羊与羊中间、公绵羊与公山羊中间施行判断。",
"18 你们这些肥壮的羊，在美好的草场吃草还以为小事吗？剩下的草，你们竟用蹄践踏了；你们喝清水，剩下的水，你们竟用蹄搅浑了。",
"19 至于我的羊，只得吃你们所践踏的，喝你们所搅浑的。",
"",
"——【以西结书 34】",
],
[
"20 Seest thou a man that is hasty in his words? there is more hope of a fool than of him.",
"21 He that delicately bringeth up his servant from a child shall have him become his son at the length.",
"",
"——【The Proverbs 29】",
"",
"20 你见言语急躁的人吗？愚昧人比他更有指望。",
"21 人将仆人从小娇养，这仆人终久必成了他的儿子。",
"",
"——【箴言 29】",
],
[
"1 And David numbered the people that were with him, and set captains of thousands and captains of hundreds over them.",
"2 And David sent forth a third part of the people under the hand of Joab, and a third part under the hand of Abishai the son of Zeruiah, Joab's brother, and a third part under the hand of Ittai the Gittite. And the king said unto the people, I will surely go forth with you myself also.",
"",
"——【The Second Book of Samuel 18】",
"",
"1 大卫数点跟随他的人，立千夫长、百夫长率领他们。",
"2 大卫打发军兵出战，分为三队：一队在约押手下，一队在洗鲁雅的儿子、约押兄弟亚比筛手下，一队在迦特人以太手下。大卫对军兵说：「我必与你们一同出战。」",
"",
"——【撒母耳记下 18】",
],
[
"8 Therefore thus saith the Lord GOD; Behold, I, even I, am against thee, and will execute judgments in the midst of thee in the sight of the nations.",
"9 And I will do in thee that which I have not done, and whereunto I will not do any more the like, because of all thine abominations.",
"10 Therefore the fathers shall eat the sons in the midst of thee, and the sons shall eat their fathers; and I will execute judgments in thee, and the whole remnant of thee will I scatter into all the winds.",
"11 Wherefore, as I live, saith the Lord GOD; Surely, because thou hast defiled my sanctuary with all thy detestable things, and with all thine abominations, therefore will I also diminish thee; neither shall mine eye spare, neither will I have any pity.",
"12 A third part of thee shall die with the pestilence, and with famine shall they be consumed in the midst of thee: and a third part shall fall by the sword round about thee; and I will scatter a third part into all the winds, and I will draw out a sword after them.",
"13 Thus shall mine anger be accomplished, and I will cause my fury to rest upon them, and I will be comforted: and they shall know that I the LORD have spoken it in my zeal, when I have accomplished my fury in them.",
"",
"——【The Book of the Prophet Ezekiel 5】",
"",
"8 所以主耶和华如此说：看哪，我与你反对，必在列国的眼前，在你中间，施行审判；",
"9 并且因你一切可憎的事，我要在你中间行我所未曾行的，以后我也不再照著行。",
"10 在你中间父亲要吃儿子，儿子要吃父亲。我必向你施行审判，我必将你所剩下的分散四方（方：原文是风）。」",
"11 主耶和华说：「我指着我的永生起誓，因你用一切可憎的物、可厌的事玷污了我的圣所，故此，我定要使你人数减少，我眼必不顾惜你，也不可怜你。",
"12 你的民三分之一必遭瘟疫而死，在你中间必因饥荒消灭；三分之一必在你四围倒在刀下；我必将三分之一分散四方（方：原文是风），并要拔刀追赶他们。",
"13 「我要这样成就怒中所定的；我向他们发的忿怒止息了，自己就得著安慰。我在他们身上成就怒中所定的那时，他们就知道我─耶和华所说的是出于热心；",
"",
"——【以西结书 5】",
],
[
"1 O God, thou art my God; early will I seek thee: my soul thirsteth for thee, my flesh longeth for thee in a dry and thirsty land, where no water is;",
"2 To see thy power and thy glory, so as I have seen thee in the sanctuary.",
"3 Because thy lovingkindness is better than life, my lips shall praise thee.",
"4 Thus will I bless thee while I live: I will lift up my hands in thy name.",
"5 My soul shall be satisfied as with marrow and fatness; and my mouth shall praise thee with joyful lips:",
"6 When I remember thee upon my bed, and meditate on thee in the night watches.",
"",
"——【The Book of Psalms 63】",
"",
"1 （大卫在犹大旷野的时候，作了这诗。）　神啊，你是我的　神，我要切切地寻求你，在干旱疲乏无水之地，我渴想你；我的心切慕你。",
"2 我在圣所中曾如此瞻仰你，为要见你的能力和你的荣耀。",
"3 因你的慈爱比生命更好，我的嘴唇要颂赞你。",
"4 我还活的时候要这样称颂你；我要奉你的名举手。",
"5 我在床上记念你，在夜更的时候思想你；我的心就像饱足了骨髓肥油，我也要以欢乐的嘴唇赞美你。",
"6 合和译本并入上一节",
"",
"——【诗篇 63】",
],
[
"27 And there came a man of God unto Eli, and said unto him, Thus saith the LORD, Did I plainly appear unto the house of thy father, when they were in Egypt in Pharaoh's house?",
"28 And did I choose him out of all the tribes of Israel to be my priest, to offer upon mine altar, to burn incense, to wear an ephod before me? and did I give unto the house of thy father all the offerings made by fire of the children of Israel?",
"",
"——【The First Book of Samuel 2】",
"",
"27 有神人来见以利，对他说：「耶和华如此说：『你祖父在埃及法老家作奴仆的时候，我不是向他们显现吗？",
"28 在以色列众支派中，我不是拣选人作我的祭司，使他烧香，在我坛上献祭，在我面前穿以弗得，又将以色列人所献的火祭都赐给你父家吗？",
"",
"——【撒母耳记上 2】",
],
[
"10 And Jacob said, Nay, I pray thee, if now I have found grace in thy sight, then receive my present at my hand: for therefore I have seen thy face, as though I had seen the face of God, and thou wast pleased with me.",
"11 Take, I pray thee, my blessing that is brought to thee; because God hath dealt graciously with me, and because I have enough. And he urged him, and he took it.",
"12 And he said, Let us take our journey, and let us go, and I will go before thee.",
"",
"——【The First Book of Moses: Called Genesis 33】",
"",
"10 雅各说：「不然，我若在你眼前蒙恩，就求你从我手里收下这礼物；因为我见了你的面，如同见了　神的面，并且你容纳了我。",
"11 求你收下我带来给你的礼物；因为　神恩待我，使我充足。」雅各再三地求他，他才收下了。",
"12 以扫说：「我们可以起身前往，我在你前头走。」",
"",
"——【创世记 33】",
],
[
"1 When Mordecai perceived all that was done, Mordecai rent his clothes, and put on sackcloth with ashes, and went out into the midst of the city, and cried with a loud and a bitter cry;",
"2 And came even before the king's gate: for none might enter into the king's gate clothed with sackcloth.",
"3 And in every province, whithersoever the king's commandment and his decree came, there was great mourning among the Jews, and fasting, and weeping, and wailing; and many lay in sackcloth and ashes.",
"",
"——【The Book of Esther 4】",
"",
"1 末底改知道所做的这一切事，就撕裂衣服，穿麻衣，蒙灰尘，在城中行走，痛哭哀号。",
"2 到了朝门前停住脚步，因为穿麻衣的不可进朝门。",
"3 王的谕旨所到的各省各处，犹大人大大悲哀，禁食哭泣哀号，穿麻衣躺在灰中的甚多。",
"",
"——【以斯帖记 4】",
],
[
"24 Then answered Simon, and said, Pray ye to the Lord for me, that none of these things which ye have spoken come upon me.",
"25 And they, when they had testified and preached the word of the Lord, returned to Jerusalem, and preached the gospel in many villages of the Samaritans.",
"26 And the angel of the Lord spake unto Philip, saying, Arise, and go toward the south unto the way that goeth down from Jerusalem unto Gaza, which is desert.",
"",
"——【The Acts of the Apostles 8】",
"",
"24 西门说：愿你们为我求主，叫你们所说的，没有一样临到我身上。",
"25 使徒既证明主道，而且传讲，就回耶路撒冷去，一路在撒马利亚好些村庄传扬福音。",
"26 有主的一个使者对腓利说：起来！向南走，往那从耶路撒冷下迦萨的路上去。那路是旷野。",
"",
"——【使徒行传 8】",
],
[
"13 Why dost thou strive against him? for he giveth not account of any of his matters.",
"14 For God speaketh once, yea twice, yet man perceiveth it not.",
"15 In a dream, in a vision of the night, when deep sleep falleth upon men, in slumberings upon the bed;",
"16 Then he openeth the ears of men, and sealeth their instruction,",
"17 That he may withdraw man from his purpose, and hide pride from man.",
"",
"——【The Book of Job 33】",
"",
"13 你为何与他争论呢？因他的事都不对人解说？",
"14 　神说一次、两次，世人却不理会。",
"15 人躺在床上沉睡的时候，　神就用梦和夜间的异象，",
"16 开通他们的耳朵，将当受的教训印在他们心上，",
"17 好叫人不从自己的谋算，不行骄傲的事（原文是将骄傲向人隐藏），",
"",
"——【约伯记 33】",
],
[
"10 I believed, therefore have I spoken: I was greatly afflicted:",
"11 I said in my haste, All men are liars.",
"",
"——【The Book of Psalms 116】",
"",
"10 我因信，所以如此说话；我受了极大的困苦。",
"11 我曾急促地说：人都是说谎的！",
"",
"——【诗篇 116】",
],
[
"15 Nevertheless, brethren, I have written the more boldly unto you in some sort, as putting you in mind, because of the grace that is given to me of God,",
"16 That I should be the minister of Jesus Christ to the Gentiles, ministering the gospel of God, that the offering up of the Gentiles might be acceptable, being sanctified by the Holy Ghost.",
"",
"——【The Epistle of Paul the Apostle to the Romans 15】",
"",
"15 但我稍微放胆写信给你们，是要提醒你们的记性，特因　神所给我的恩典，",
"16 使我为外邦人作基督耶稣的仆役，作　神福音的祭司，叫所献上的外邦人，因著圣灵成为圣洁，可蒙悦纳。",
"",
"——【罗马书 15】",
],
[
"5 For in the time of trouble he shall hide me in his pavilion: in the secret of his tabernacle shall he hide me; he shall set me up upon a rock.",
"6 And now shall mine head be lifted up above mine enemies round about me: therefore will I offer in his tabernacle sacrifices of joy; I will sing, yea, I will sing praises unto the LORD.",
"7 Hear, O LORD, when I cry with my voice: have mercy also upon me, and answer me.",
"",
"——【The Book of Psalms 27】",
"",
"5 因为我遭遇患难，他必暗暗地保守我；在他亭子里，把我藏在他帐幕的隐密处，将我高举在磐石上。",
"6 现在我得以昂首，高过四面的仇敌。我要在他的帐幕里欢然献祭；我要唱诗歌颂耶和华。",
"7 耶和华啊，我用声音呼籲的时候，求你垂听；并求你怜恤我，应允我。",
"",
"——【诗篇 27】",
],
[
"13 And ye shall offer a burnt offering, a sacrifice made by fire, of a sweet savour unto the LORD; thirteen young bullocks, two rams, and fourteen lambs of the first year; they shall be without blemish:",
"14 And their meat offering shall be of flour mingled with oil, three tenth deals unto every bullock of the thirteen bullocks, two tenth deals to each ram of the two rams,",
"15 And a several tenth deal to each lamb of the fourteen lambs:",
"16 And one kid of the goats for a sin offering; beside the continual burnt offering, his meat offering, and his drink offering.",
"",
"——【The Fourth Book of Moses: Called Numbers 29】",
"",
"13 又要将公牛犊十三只，公绵羊两只，一岁的公羊羔十四只，都要没有残疾的，用火献给耶和华为馨香的燔祭。",
"14 同献的素祭用调油的细面；为那十三只公牛，每只要献伊法十分之三；为那两只公羊，每只要献伊法十分之二；",
"15 为那十四只羊羔，每只要献伊法十分之一。",
"16 并献一只公山羊为赎罪祭，这是在常献的燔祭和同献的素祭并同献的奠祭以外。",
"",
"——【民数记 29】",
],
[
"2 Only the people sacrificed in high places, because there was no house built unto the name of the LORD, until those days.",
"3 And Solomon loved the LORD, walking in the statutes of David his father: only he sacrificed and burnt incense in high places.",
"4 And the king went to Gibeon to sacrifice there; for that was the great high place: a thousand burnt offerings did Solomon offer upon that altar.",
"5 In Gibeon the LORD appeared to Solomon in a dream by night: and God said, Ask what I shall give thee.",
"",
"——【The First Book of the Kings 3】",
"",
"2 当那些日子，百姓仍在邱坛献祭，因为还没有为耶和华的名建殿。",
"3 所罗门爱耶和华，遵行他父亲大卫的律例，只是还在邱坛献祭烧香。",
"4 所罗门王上基遍去献祭；因为在那里有极大【或作出名】的邱坛，他在那坛上献一千牺牲作燔祭。",
"5 在基遍，夜间梦中，耶和华向所罗门显现，对他说：「你愿我赐你什么？你可以求。」",
"",
"——【列王记上 3】",
],
[
"2 Then said David, I will shew kindness unto Hanun the son of Nahash, as his father shewed kindness unto me. And David sent to comfort him by the hand of his servants for his father. And David's servants came into the land of the children of Ammon.",
"3 And the princes of the children of Ammon said unto Hanun their lord, Thinkest thou that David doth honour thy father, that he hath sent comforters unto thee? hath not David rather sent his servants unto thee, to search the city, and to spy it out, and to overthrow it?",
"4 Wherefore Hanun took David's servants, and shaved off the one half of their beards, and cut off their garments in the middle, even to their buttocks, and sent them away.",
"5 When they told it unto David, he sent to meet them, because the men were greatly ashamed: and the king said, Tarry at Jericho until your beards be grown, and then return.",
"6 And when the children of Ammon saw that they stank before David, the children of Ammon sent and hired the Syrians of Beth–rehob, and the Syrians of Zoba, twenty thousand footmen, and of king Maacah a thousand men, and of Ish–tob twelve thousand men.",
"",
"——【The Second Book of Samuel 10】",
"",
"2 大卫说：「我要照哈嫩的父亲拿辖厚待我的恩典厚待哈嫩。」于是大卫差遣臣仆，为他丧父安慰他。大卫的臣仆到了亚扪人的境内。",
"3 但亚扪人的首领对他们的主哈嫩说：「大卫差人来安慰你，你想他是尊敬你父亲吗？他差臣仆来不是详察窥探、要倾覆这城吗？」",
"4 哈嫩便将大卫臣仆的胡须剃去一半，又割断他们下半截的衣服，使他们露出下体，打发他们回去。",
"5 有人告诉大卫，他就差人去迎接他们，（因为他们甚觉羞耻），告诉他们说：「可以住在耶利哥，等到胡须长起再回来。」",
"6 亚扪人知道大卫憎恶他们，就打发人去，招募伯‧利合的亚兰人和琐巴的亚兰人，步兵二万，与玛迦王的人一千、陀伯人一万二千。",
"",
"——【撒母耳记下 10】",
],
[
"7 And he knew their desolate palaces, and he laid waste their cities; and the land was desolate, and the fulness thereof, by the noise of his roaring.",
"8 Then the nations set against him on every side from the provinces, and spread their net over him: he was taken in their pit.",
"9 And they put him in ward in chains, and brought him to the king of Babylon: they brought him into holds, that his voice should no more be heard upon the mountains of Israel.",
"",
"——【The Book of the Prophet Ezekiel 19】",
"",
"7 他知道列国的宫殿，又使他们的城邑变为荒场；因他咆哮的声音，遍地和其中所有的就都荒废。",
"8 于是四围邦国各省的人来攻击他，将网撒在他身上，捉在他们的坑中。",
"9 他们用钩子钩住他，将他放在笼中，带到巴比伦王那里，将他放入坚固之所，使他的声音在以色列山上不再听见。",
"",
"——【以西结书 19】",
],
[
"21 Yea, they opened their mouth wide against me, and said, Aha, aha, our eye hath seen it.",
"22 This thou hast seen, O LORD: keep not silence: O Lord, be not far from me.",
"23 Stir up thyself, and awake to my judgment, even unto my cause, my God and my Lord.",
"24 Judge me, O LORD my God, according to thy righteousness; and let them not rejoice over me.",
"",
"——【The Book of Psalms 35】",
"",
"21 他们大大张口攻击我，说：阿哈，阿哈，我们的眼已经看见了！",
"22 耶和华啊，你已经看见了，求你不要闭口！主啊，求你不要远离我！",
"23 我的　神我的主啊，求你奋兴醒起，判清我的事，伸明我的冤！",
"24 耶和华─我的　神啊，求你按你的公义判断我，不容他们向我夸耀！",
"",
"——【诗篇 35】",
],
[
"11 And again, Praise the Lord, all ye Gentiles; and laud him, all ye people.",
"12 And again, Esaias saith, There shall be a root of Jesse, and he that shall rise to reign over the Gentiles; in him shall the Gentiles trust.",
"13 Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.",
"",
"——【The Epistle of Paul the Apostle to the Romans 15】",
"",
"11 又说：外邦啊，你们当赞美主！万民哪，你们都当颂赞他！",
"12 又有以赛亚说：将来有耶西的根，就是那兴起来要治理外邦的；外邦人要仰望他。",
"13 但愿使人有盼望的　神，因信将诸般的喜乐、平安充满你们的心，使你们借著圣灵的能力大有盼望。",
"",
"——【罗马书 15】",
],
[
"1 And it came to pass, that when Jeremiah had made an end of speaking unto all the people all the words of the LORD their God, for which the LORD their God had sent him to them, even all these words,",
"2 Then spake Azariah the son of Hoshaiah, and Johanan the son of Kareah, and all the proud men, saying unto Jeremiah, Thou speakest falsely: the LORD our God hath not sent thee to say, Go not into Egypt to sojourn there:",
"",
"——【The Book of the Prophet Jeremiah 43】",
"",
"1 耶利米向众百姓说完了耶和华─他们　神的一切话，就是耶和华─他们　神差遣他去所说的一切话。",
"2 何沙雅的儿子亚撒利雅和加利亚的儿子约哈难，并一切狂傲的人，就对耶利米说：「你说谎言！耶和华─我们的　神并没有差遣你来说：『你们不可进入埃及，在那里寄居。』",
"",
"——【耶利米书 43】",
],
[
"8 Wherefore, though I might be much bold in Christ to enjoin thee that which is convenient,",
"9 Yet for love's sake I rather beseech thee, being such an one as Paul the aged, and now also a prisoner of Jesus Christ.",
"",
"——【The Epistle of Paul the Apostle to Philemon 1】",
"",
"8 我虽然靠著基督能放胆吩咐你合宜的事；",
"9 然而像我这有年纪的保罗，现在又是为基督耶稣被囚的，宁可凭著爱心求你，",
"",
"——【腓利门书 1】",
],
[
"4 And the damsel was very fair, and cherished the king, and ministered to him: but the king knew her not.",
"5 Then Adonijah the son of Haggith exalted himself, saying, I will be king: and he prepared him chariots and horsemen, and fifty men to run before him.",
"6 And his father had not displeased him at any time in saying, Why hast thou done so? and he also was a very goodly man; and his mother bare him after Absalom.",
"",
"——【The First Book of the Kings 1】",
"",
"4 这童女极其美貌，她奉养王，伺候王，王却没有与她亲近。",
"5 那时，哈及的儿子亚多尼雅自尊，说：「我必作王」，就为自己预备车辆、马兵，又派五十人在他前头奔走。",
"6 他父亲素来没有使他忧闷，说：「你是做什么呢？」他甚俊美，生在押沙龙之后。",
"",
"——【列王记上 1】",
],
[
"9 But thou hast cast off, and put us to shame; and goest not forth with our armies.",
"10 Thou makest us to turn back from the enemy: and they which hate us spoil for themselves.",
"",
"——【The Book of Psalms 44】",
"",
"9 但如今你丢弃了我们，使我们受辱，不和我们的军兵同去。",
"10 你使我们向敌人转身退后；那恨我们的人任意抢夺。",
"",
"——【诗篇 44】",
],
[
"6 And ye know that with all my power I have served your father.",
"7 And your father hath deceived me, and changed my wages ten times; but God suffered him not to hurt me.",
"8 If he said thus, The speckled shall be thy wages; then all the cattle bare speckled: and if he said thus, The ringstraked shall be thy hire; then bare all the cattle ringstraked.",
"9 Thus God hath taken away the cattle of your father, and given them to me.",
"10 And it came to pass at the time that the cattle conceived, that I lifted up mine eyes, and saw in a dream, and, behold, the rams which leaped upon the cattle were ringstraked, speckled, and grisled.",
"",
"——【The First Book of Moses: Called Genesis 31】",
"",
"6 你们也知道，我尽了我的力量服事你们的父亲。",
"7 你们的父亲欺哄我，十次改了我的工价；然而　神不容他害我。",
"8 他若说：『有点的归你作工价』，羊群所生的都有点；他若说：『有纹的归你作工价』，羊群所生的都有纹。",
"9 这样，　神把你们父亲的牲畜夺来赐给我了。",
"10 羊配合的时候，我梦中举目一看，见跳母羊的公羊都是有纹的、有点的、有花斑的。",
"",
"——【创世记 31】",
],
[
"3 The horseman lifteth up both the bright sword and the glittering spear: and there is a multitude of slain, and a great number of carcases; and there is none end of their corpses; they stumble upon their corpses:",
"4 Because of the multitude of the whoredoms of the wellfavoured harlot, the mistress of witchcrafts, that selleth nations through her whoredoms, and families through her witchcrafts.",
"5 Behold, I am against thee, saith the LORD of hosts; and I will discover thy skirts upon thy face, and I will shew the nations thy nakedness, and the kingdoms thy shame.",
"6 And I will cast abominable filth upon thee, and make thee vile, and will set thee as a gazingstock.",
"7 And it shall come to pass, that all they that look upon thee shall flee from thee, and say, Nineveh is laid waste: who will bemoan her? whence shall I seek comforters for thee?",
"8 Art thou better than populous No, that was situate among the rivers, that had the waters round about it, whose rampart was the sea, and her wall was from the sea?",
"",
"——【Nahum 3】",
"",
"3 马兵争先，刀剑发光，枪矛闪烁，被杀的甚多，尸首成了大堆，尸骸无数，人碰著而跌倒，",
"4 都因那美貌的妓女多有淫行，惯行邪术，借淫行诱惑列国，用邪术诱惑（原文是卖）多族。",
"5 万军之耶和华说：我与你为敌；我必揭起你的衣襟，蒙在你脸上，使列国看见你的赤体，使列邦观看你的丑陋。",
"6 我必将可憎污秽之物抛在你身上，辱没你，为众目所观。",
"7 凡看见你的，都必逃跑离开你，说：尼尼微荒凉了！有谁为你悲伤呢？我何处寻得安慰你的人呢？",
"8 你岂比挪亚们（或）强呢？挪亚们坐落在众河之间，周围有水；海（指尼罗河）作她的濠沟，又作她的城墙。",
"",
"——【那鸿书 3】",
],
[
"20 Jesus answered him, I spake openly to the world; I ever taught in the synagogue, and in the temple, whither the Jews always resort; and in secret have I said nothing.",
"21 Why askest thou me? ask them which heard me, what I have said unto them: behold, they know what I said.",
"22 And when he had thus spoken, one of the officers which stood by struck Jesus with the palm of his hand, saying, Answerest thou the high priest so?",
"",
"——【The Gospel According to Saint John 18】",
"",
"20 耶稣回答说：我从来是明明的对世人说话。我常在会堂和殿里，就是犹太人聚集的地方教训人；我在暗地里并没有说什么。",
"21 你为什么问我呢？可以问那听见的人，我对他们说的是什么；我所说的，他们都知道。",
"22 耶稣说了这话，旁边站著的一个差役用手掌打他，说：你这样回答大祭司吗？",
"",
"——【约翰福音 18】",
],
[
"4 Whereby, when ye read, ye may understand my knowledge in the mystery of Christ)",
"5 Which in other ages was not made known unto the sons of men, as it is now revealed unto his holy apostles and prophets by the Spirit;",
"6 That the Gentiles should be fellowheirs, and of the same body, and partakers of his promise in Christ by the gospel:",
"",
"——【The Epistle of Paul the Apostle to the Ephesians 3】",
"",
"4 你们念了，就能晓得我深知基督的奥祕。",
"5 这奥祕在以前的世代没有叫人知道，像如今借著圣灵启示他的圣使徒和先知一样。",
"6 这奥祕就是外邦人在基督耶稣里，借著福音，得以同为后嗣，同为一体，同蒙应许。",
"",
"——【以弗所书 3】",
],
[
"1 And thou, son of man, take thee a sharp knife, take thee a barber's razor, and cause it to pass upon thine head and upon thy beard: then take thee balances to weigh, and divide the hair.",
"2 Thou shalt burn with fire a third part in the midst of the city, when the days of the siege are fulfilled: and thou shalt take a third part, and smite about it with a knife: and a third part thou shalt scatter in the wind; and I will draw out a sword after them.",
"3 Thou shalt also take thereof a few in number, and bind them in thy skirts.",
"",
"——【The Book of the Prophet Ezekiel 5】",
"",
"1 「人子啊，你要拿一把快刀，当作剃头刀，用这刀剃你的头发和你的胡须，用天平将须发平分。",
"2 围困城的日子满了，你要将三分之一在城中用火焚烧，将三分之一在城的四围用刀砍碎，将三分之一任风吹散；我也要拔刀追赶。",
"3 你要从其中取几根包在衣襟里，",
"",
"——【以西结书 5】",
],
[
"5 The LORD is the portion of mine inheritance and of my cup: thou maintainest my lot.",
"6 The lines are fallen unto me in pleasant places; yea, I have a goodly heritage.",
"7 I will bless the LORD, who hath given me counsel: my reins also instruct me in the night seasons.",
"8 I have set the LORD always before me: because he is at my right hand, I shall not be moved.",
"9 Therefore my heart is glad, and my glory rejoiceth: my flesh also shall rest in hope.",
"10 For thou wilt not leave my soul in hell; neither wilt thou suffer thine Holy One to see corruption.",
"",
"——【The Book of Psalms 16】",
"",
"5 耶和华是我的产业，是我杯中的分；我所得的，你为我持守。",
"6 用绳量给我的地界，坐落在佳美之处；我的产业实在美好。",
"7 我必称颂那指教我的耶和华；我的心肠在夜间也警戒我。",
"8 我将耶和华常摆在我面前，因他在我右边，我便不致摇动。",
"9 因此，我的心欢喜，我的灵（原文是荣耀）快乐；我的肉身也要安然居住。",
"10 因为你必不将我的灵魂撇在阴间，也不叫你的圣者见朽坏。",
"",
"——【诗篇 16】",
],
[
"1 And the LORD said unto Moses, See, I have made thee a god to Pharaoh: and Aaron thy brother shall be thy prophet.",
"2 Thou shalt speak all that I command thee: and Aaron thy brother shall speak unto Pharaoh, that he send the children of Israel out of his land.",
"3 And I will harden Pharaoh's heart, and multiply my signs and my wonders in the land of Egypt.",
"4 But Pharaoh shall not hearken unto you, that I may lay my hand upon Egypt, and bring forth mine armies, and my people the children of Israel, out of the land of Egypt by great judgments.",
"5 And the Egyptians shall know that I am the LORD, when I stretch forth mine hand upon Egypt, and bring out the children of Israel from among them.",
"",
"——【The Second Book of Moses: Called Exodus 7】",
"",
"1 耶和华对摩西说：「我使你在法老面前代替　神，你的哥哥亚伦是替你说话的。",
"2 凡我所吩咐你的，你都要说。你的哥哥亚伦要对法老说，容以色列人出他的地。",
"3 我要使法老的心刚硬，也要在埃及地多行神迹奇事。",
"4 但法老必不听你们；我要伸手重重地刑罚埃及，将我的军队以色列民从埃及地领出来。",
"5 我伸手攻击埃及，将以色列人从他们中间领出来的时候，埃及人就要知道我是耶和华。」",
"",
"——【出埃及记 7】",
],
[
"1 And the LORD spake unto Moses, saying,",
"2 Speak unto Aaron and to his sons, that they separate themselves from the holy things of the children of Israel, and that they profane not my holy name in those things which they hallow unto me: I am the LORD.",
"3 Say unto them, Whosoever he be of all your seed among your generations, that goeth unto the holy things, which the children of Israel hallow unto the LORD, having his uncleanness upon him, that soul shall be cut off from my presence: I am the LORD.",
"4 What man soever of the seed of Aaron is a leper, or hath a running issue; he shall not eat of the holy things, until he be clean. And whoso toucheth any thing that is unclean by the dead, or a man whose seed goeth from him;",
"5 Or whosoever toucheth any creeping thing, whereby he may be made unclean, or a man of whom he may take uncleanness, whatsoever uncleanness he hath;",
"6 The soul which hath touched any such shall be unclean until even, and shall not eat of the holy things, unless he wash his flesh with water.",
"",
"——【The Third Book of Moses: Called Leviticus 22】",
"",
"1 耶和华对摩西说：",
"2 「你吩咐亚伦和他子孙说：要远离以色列人所分别为圣、归给我的圣物，免得亵渎我的圣名。我是耶和华。",
"3 你要对他们说：你们世世代代的后裔，凡身上有污秽、亲近以色列人所分别为圣、归耶和华圣物的，那人必在我面前剪除。我是耶和华。",
"4 亚伦的后裔，凡长大痲疯的，或是有漏症的，不可吃圣物，直等他洁净了。无论谁摸那因死尸不洁净的物（物或作：人），或是遗精的人，",
"5 或是摸什么使他不洁净的爬物，或是摸那使他不洁净的人（不拘那人有什么不洁净），",
"6 摸了这些人、物的，必不洁净到晚上；若不用水洗身，就不可吃圣物。",
"",
"——【利未记 22】",
],
];
