var bible31_global=[
[
"1 Be ye therefore followers of God, as dear children;",
"2 And walk in love, as Christ also hath loved us, and hath given himself for us an offering and a sacrifice to God for a sweetsmelling savour.",
"3 But fornication, and all uncleanness, or covetousness, let it not be once named among you, as becometh saints;",
"4 Neither filthiness, nor foolish talking, nor jesting, which are not convenient: but rather giving of thanks.",
"5 For this ye know, that no whoremonger, nor unclean person, nor covetous man, who is an idolater, hath any inheritance in the kingdom of Christ and of God.",
"",
"——【The Epistle of Paul the Apostle to the Ephesians 5】",
"",
"1 所以，你们该效法　神，好像蒙慈爱的儿女一样。",
"2 也要凭爱心行事，正如基督爱我们，为我们舍了自己，当作馨香的供物和祭物，献与　神。",
"3 至于淫乱并一切污秽，或是贪婪，在你们中间连提都不可，方合圣徒的体统。",
"4 淫词、妄语，和戏笑的话都不相宜；总要说感谢的话。",
"5 因为你们确实的知道，无论是淫乱的，是污秽的，是有贪心的，在基督和　神的国里都是无分的。有贪心的，就与拜偶像的一样。",
"",
"——【以弗所书 5】",
],
[
"3 And desired favour against him, that he would send for him to Jerusalem, laying wait in the way to kill him.",
"4 But Festus answered, that Paul should be kept at Cæsarea, and that he himself would depart shortly thither.",
"5 Let them therefore, said he, which among you are able, go down with me, and accuse this man, if there be any wickedness in him.",
"6 And when he had tarried among them more than ten days, he went down unto Cæsarea; and the next day sitting on the judgment seat commanded Paul to be brought.",
"7 And when he was come, the Jews which came down from Jerusalem stood round about, and laid many and grievous complaints against Paul, which they could not prove.",
"8 While he answered for himself, Neither against the law of the Jews, neither against the temple, nor yet against Cæsar, have I offended any thing at all.",
"",
"——【The Acts of the Apostles 25】",
"",
"3 又央告他，求他的情，将保罗提到耶路撒冷来，他们要在路上埋伏杀害他。",
"4 非斯都却回答说：保罗押在凯撒利亚，我自己快要往那里去；",
"5 又说：你们中间有权势的人与我一同下去，那人若有什么不是，就可以告他。",
"6 非斯都在他们那里住了不过十天八天，就下凯撒利亚去；第二天坐堂，吩咐将保罗提上来。",
"7 保罗来了，那些从耶路撒冷下来的犹太人周围站著，将许多重大的事控告他，都是不能证实的。",
"8 保罗分诉说：无论犹太人的律法，或是圣殿，或是凯撒，我都没有干犯。",
"",
"——【使徒行传 25】",
],
[
"25 And the stars of heaven shall fall, and the powers that are in heaven shall be shaken.",
"26 And then shall they see the Son of man coming in the clouds with great power and glory.",
"27 And then shall he send his angels, and shall gather together his elect from the four winds, from the uttermost part of the earth to the uttermost part of heaven.",
"",
"——【The Gospel According to Saint Mark 13】",
"",
"25 众星要从天上坠落，天势都要震动。",
"26 那时，他们（马太二十四章三十节是地上的万族）要看见人子有大能力、大荣耀，驾云降临。",
"27 他要差遣天使，把他的选民，从四方（方：原文是风），从地极直到天边，都招聚了来。",
"",
"——【马可福音 13】",
],
[
"1 And Jehoshaphat the king of Judah returned to his house in peace to Jerusalem.",
"2 And Jehu the son of Hanani the seer went out to meet him, and said to king Jehoshaphat, Shouldest thou help the ungodly, and love them that hate the LORD? therefore is wrath upon thee from before the LORD.",
"3 Nevertheless there are good things found in thee, in that thou hast taken away the groves out of the land, and hast prepared thine heart to seek God.",
"4 And Jehoshaphat dwelt at Jerusalem: and he went out again through the people from Beer–sheba to mount Ephraim, and brought them back unto the LORD God of their fathers.",
"",
"——【The Second Book of the Chronicles 19】",
"",
"1 犹大王约沙法平平安安地回耶路撒冷，到宫里去了。",
"2 先见哈拿尼的儿子耶户出来迎接约沙法王，对他说：「你岂当帮助恶人，爱那恨恶耶和华的人呢？因此耶和华的忿怒临到你。",
"3 然而你还有善行，因你从国中除掉木偶，立定心意寻求　神。」",
"4 约沙法住在耶路撒冷，以后又出巡民间，从别是巴直到以法莲山地，引导民归向耶和华─他们列祖的　神；",
"",
"——【历代志下 19】",
],
[
"9 Hide not thy face far from me; put not thy servant away in anger: thou hast been my help; leave me not, neither forsake me, O God of my salvation.",
"10 When my father and my mother forsake me, then the LORD will take me up.",
"11 Teach me thy way, O LORD, and lead me in a plain path, because of mine enemies.",
"12 Deliver me not over unto the will of mine enemies: for false witnesses are risen up against me, and such as breathe out cruelty.",
"13 I had fainted, unless I had believed to see the goodness of the LORD in the land of the living.",
"14 Wait on the LORD: be of good courage, and he shall strengthen thine heart: wait, I say, on the LORD.",
"",
"——【The Book of Psalms 27】",
"",
"9 不要向我掩面。不要发怒赶逐仆人，你向来是帮助我的。救我的　神啊，不要丢掉我，也不要离弃我。",
"10 我父母离弃我，耶和华必收留我。",
"11 耶和华啊，求你将你的道指教我，因我仇敌的缘故引导我走平坦的路。",
"12 求你不要把我交给敌人，遂其所愿；因为妄作见证的和口吐凶言的，起来攻击我。",
"13 我若不信在活人之地得见耶和华的恩惠，就早已丧胆了。",
"14 要等候耶和华！当壮胆，坚固你的心！我再说，要等候耶和华！",
"",
"——【诗篇 27】",
],
[
"11 Let the extortioner catch all that he hath; and let the strangers spoil his labour.",
"12 Let there be none to extend mercy unto him: neither let there be any to favour his fatherless children.",
"13 Let his posterity be cut off; and in the generation following let their name be blotted out.",
"14 Let the iniquity of his fathers be remembered with the LORD; and let not the sin of his mother be blotted out.",
"15 Let them be before the LORD continually, that he may cut off the memory of them from the earth.",
"",
"——【The Book of Psalms 109】",
"",
"11 愿强暴的债主牢笼他一切所有的！愿外人抢他劳碌得来的！",
"12 愿无人向他延绵施恩！愿无人可怜他的孤儿！",
"13 愿他的后人断绝，名字被涂抹，不传于下代！",
"14 愿他祖宗的罪孽被耶和华记念！愿他母亲的罪过不被涂抹！",
"15 愿这些罪常在耶和华面前，使他的名号断绝于世！",
"",
"——【诗篇 109】",
],
[
"26 When Jesus therefore saw his mother, and the disciple standing by, whom he loved, he saith unto his mother, Woman, behold thy son!",
"27 Then saith he to the disciple, Behold thy mother! And from that hour that disciple took her unto his own home.",
"28 After this, Jesus knowing that all things were now accomplished, that the scripture might be fulfilled, saith, I thirst.",
"29 Now there was set a vessel full of vinegar: and they filled a spunge with vinegar, and put it upon hyssop, and put it to his mouth.",
"",
"——【The Gospel According to Saint John 19】",
"",
"26 耶稣见母亲和他所爱的那门徒站在旁边，就对他母亲说：母亲（原文作妇人），看，你的儿子！",
"27 又对那门徒说：看，你的母亲！从此，那门徒就接她到自己家里去了。",
"28 这事以后，耶稣知道各样的事已经成了，为要使经上的话应验，就说：我渴了。",
"29 有一个器皿盛满了醋，放在那里；他们就拿海绒蘸满了醋，绑在牛膝草上，送到他口。",
"",
"——【约翰福音 19】",
],
[
"13 And Moses rose up, and his minister Joshua: and Moses went up into the mount of God.",
"14 And he said unto the elders, Tarry ye here for us, until we come again unto you: and, behold, Aaron and Hur are with you: if any man have any matters to do, let him come unto them.",
"",
"——【The Second Book of Moses: Called Exodus 24】",
"",
"13 摩西和他的帮手约书亚起来，上了　神的山。",
"14 摩西对长老说：「你们在这里等著，等到我们再回来，有亚伦、户珥与你们同在。凡有争讼的，都可以就近他们去。」",
"",
"——【出埃及记 24】",
],
[
"12 And the Midianites and the Amalekites and all the children of the east lay along in the valley like grasshoppers for multitude; and their camels were without number, as the sand by the sea side for multitude.",
"13 And when Gideon was come, behold, there was a man that told a dream unto his fellow, and said, Behold, I dreamed a dream, and, lo, a cake of barley bread tumbled into the host of Midian, and came unto a tent, and smote it that it fell, and overturned it, that the tent lay along.",
"14 And his fellow answered and said, This is nothing else save the sword of Gideon the son of Joash, a man of Israel: for into his hand hath God delivered Midian, and all the host.",
"15 And it was so, when Gideon heard the telling of the dream, and the interpretation thereof, that he worshipped, and returned into the host of Israel, and said, Arise; for the LORD hath delivered into your hand the host of Midian.",
"",
"——【The Book of Judges 7】",
"",
"12 米甸人、亚玛力人，和一切东方人都布散在平原，如同蝗虫那样多。他们的骆驼无数，多如海边的沙。",
"13 基甸到了，就听见一人将梦告诉同伴说：「我做了一梦，梦见一个大麦饼滚入米甸营中，到了帐幕，将帐幕撞倒，帐幕就翻转倾覆了。」",
"14 那同伴说：「这不是别的，乃是以色列人约阿施的儿子基甸的刀；　神已将米甸和全军都交在他的手中。」",
"15 基甸听见这梦和梦的讲解，就敬拜　神，回到以色列营中，说：「起来吧！耶和华已将米甸的军队交在你们手中了。」",
"",
"——【士师记 7】",
],
[
"3 Therefore shall the land mourn, and every one that dwelleth therein shall languish, with the beasts of the field, and with the fowls of heaven; yea, the fishes of the sea also shall be taken away.",
"4 Yet let no man strive, nor reprove another: for thy people are as they that strive with the priest.",
"5 Therefore shalt thou fall in the day, and the prophet also shall fall with thee in the night, and I will destroy thy mother.",
"6 My people are destroyed for lack of knowledge: because thou hast rejected knowledge, I will also reject thee, that thou shalt be no priest to me: seeing thou hast forgotten the law of thy God, I will also forget thy children.",
"7 As they were increased, so they sinned against me: therefore will I change their glory into shame.",
"8 They eat up the sin of my people, and they set their heart on their iniquity.",
"",
"——【Hosea 4】",
"",
"3 因此，这地悲哀，其上的民、田野的兽、空中的鸟必都衰微，海中的鱼也必消灭。",
"4 然而，人都不必争辩，也不必指责，因为这民与抗拒祭司的人一样。",
"5 你这祭司必日间跌倒；先知也必夜间与你一同跌倒；我必灭绝你的母亲。",
"6 我的民因无知识而灭亡。你弃掉知识，我也必弃掉你，使你不再给我作祭司。你既忘了你　神的律法，我也必忘记你的儿女。",
"7 祭司越发增多，就越发得罪我；我必使他们的荣耀变为羞辱。",
"8 他们吃我民的赎罪祭，满心愿意我民犯罪。",
"",
"——【何西阿书 4】",
],
[
"8 And Naomi said unto her two daughters in law, Go, return each to her mother's house: the LORD deal kindly with you, as ye have dealt with the dead, and with me.",
"9 The LORD grant you that ye may find rest, each of you in the house of her husband. Then she kissed them; and they lifted up their voice, and wept.",
"10 And they said unto her, Surely we will return with thee unto thy people.",
"",
"——【The Book of Ruth 1】",
"",
"8 拿俄米对两个儿妇说：「你们各人回娘家去吧。愿耶和华恩待你们，像你们恩待已死的人与我一样！",
"9 愿耶和华使你们各在新夫家中得平安！」于是拿俄米与她们亲嘴。她们就放声而哭，",
"10 说：「不然，我们必与你一同回你本国去。」",
"",
"——【路得记 1】",
],
[
"16 So Esther was taken unto king Ahasuerus into his house royal in the tenth month, which is the month Tebeth, in the seventh year of his reign.",
"17 And the king loved Esther above all the women, and she obtained grace and favour in his sight more than all the virgins; so that he set the royal crown upon her head, and made her queen instead of Vashti.",
"18 Then the king made a great feast unto all his princes and his servants, even Esther's feast; and he made a release to the provinces, and gave gifts, according to the state of the king.",
"19 And when the virgins were gathered together the second time, then Mordecai sat in the king's gate.",
"20 Esther had not yet shewed her kindred nor her people; as Mordecai had charged her: for Esther did the commandment of Mordecai, like as when she was brought up with him.",
"",
"——【The Book of Esther 2】",
"",
"16 亚哈随鲁王第七年十月，就是提别月，以斯帖被引入宫见王。",
"17 王爱以斯帖过于爱众女，她在王眼前蒙宠爱比众处女更甚。王就把王后的冠冕戴在她头上，立她为王后，代替瓦实提。",
"18 王因以斯帖的缘故给众首领和臣仆设摆大筵席，又豁免各省的租税，并照王的厚意大颁赏赐。",
"19 第二次招聚处女的时候，末底改坐在朝门。",
"20 以斯帖照著末底改所嘱咐的，还没有将籍贯宗族告诉人；因为以斯帖遵末底改的命，如抚养她的时候一样。",
"",
"——【以斯帖记 2】",
],
[
"14 Salute Asyncritus, Phlegon, Hermas, Patrobas, Hermes, and the brethren which are with them.",
"15 Salute Philologus, and Julia, Nereus, and his sister, and Olympas, and all the saints which are with them.",
"16 Salute one another with an holy kiss. The churches of Christ salute you.",
"17 Now I beseech you, brethren, mark them which cause divisions and offences contrary to the doctrine which ye have learned; and avoid them.",
"18 For they that are such serve not our Lord Jesus Christ, but their own belly; and by good words and fair speeches deceive the hearts of the simple.",
"19 For your obedience is come abroad unto all men. I am glad therefore on your behalf: but yet I would have you wise unto that which is good, and simple concerning evil.",
"",
"——【The Epistle of Paul the Apostle to the Romans 16】",
"",
"14 又问亚逊其土、弗勒干、黑米、八罗巴、黑马，并与他们在一处的弟兄们安。",
"15 又问非罗罗古和犹利亚，尼利亚和他姊妹，同阿林巴并与他们在一处的众圣徒安。",
"16 你们亲嘴问安，彼此务要圣洁。基督的众教会都问你们安。",
"17 弟兄们，那些离间你们、叫你们跌倒、背乎所学之道的人，我劝你们要留意躲避他们。",
"18 因为这样的人不服事我们的主基督，只服事自己的肚腹，用花言巧语诱惑那些老实人的心。",
"19 你们的顺服已经传于众人，所以我为你们欢喜；但我愿意你们在善上聪明，在恶上愚拙。",
"",
"——【罗马书 16】",
],
[
"1 We then that are strong ought to bear the infirmities of the weak, and not to please ourselves.",
"2 Let every one of us please his neighbour for his good to edification.",
"",
"——【The Epistle of Paul the Apostle to the Romans 15】",
"",
"1 我们坚固的人应该担代不坚固人的软弱，不求自己的喜悦。",
"2 我们各人务要叫邻舍喜悦，使他得益处，建立德行。",
"",
"——【罗马书 15】",
],
[
"5 Get wisdom, get understanding: forget it not; neither decline from the words of my mouth.",
"6 Forsake her not, and she shall preserve thee: love her, and she shall keep thee.",
"7 Wisdom is the principal thing; therefore get wisdom: and with all thy getting get understanding.",
"",
"——【The Proverbs 4】",
"",
"5 要得智慧，要得聪明，不可忘记，也不可偏离我口中的言语。",
"6 不可离弃智慧，智慧就护卫你；要爱她，她就保守你。",
"7 智慧为首；所以，要得智慧。在你一切所得之内必得聪明（或译：用你一切所得的去换聪明）。",
"",
"——【箴言 4】",
],
[
"6 Then she arose with her daughters in law, that she might return from the country of Moab: for she had heard in the country of Moab how that the LORD had visited his people in giving them bread.",
"7 Wherefore she went forth out of the place where she was, and her two daughters in law with her; and they went on the way to return unto the land of Judah.",
"8 And Naomi said unto her two daughters in law, Go, return each to her mother's house: the LORD deal kindly with you, as ye have dealt with the dead, and with me.",
"9 The LORD grant you that ye may find rest, each of you in the house of her husband. Then she kissed them; and they lifted up their voice, and wept.",
"10 And they said unto her, Surely we will return with thee unto thy people.",
"",
"——【The Book of Ruth 1】",
"",
"6 她就与两个儿妇起身，要从摩押地归回；因为她在摩押地听见耶和华眷顾自己的百姓，赐粮食与他们。",
"7 于是她和两个儿妇起行离开所住的地方，要回犹大地去。",
"8 拿俄米对两个儿妇说：「你们各人回娘家去吧。愿耶和华恩待你们，像你们恩待已死的人与我一样！",
"9 愿耶和华使你们各在新夫家中得平安！」于是拿俄米与她们亲嘴。她们就放声而哭，",
"10 说：「不然，我们必与你一同回你本国去。」",
"",
"——【路得记 1】",
],
[
"1 And when Abram was ninety years old and nine, the LORD appeared to Abram, and said unto him, I am the Almighty God; walk before me, and be thou perfect.",
"2 And I will make my covenant between me and thee, and will multiply thee exceedingly.",
"3 And Abram fell on his face: and God talked with him, saying,",
"",
"——【The First Book of Moses: Called Genesis 17】",
"",
"1 亚伯兰年九十九岁的时候，耶和华向他显现，对他说：「我是全能的　神。你当在我面前作完全人，",
"2 我就与你立约，使你的后裔极其繁多。」",
"3 亚伯兰俯伏在地；　神又对他说：",
"",
"——【创世记 17】",
],
[
"7 So Joshua came, and all the people of war with him, against them by the waters of Merom suddenly; and they fell upon them.",
"8 And the LORD delivered them into the hand of Israel, who smote them, and chased them unto great Zidon, and unto Misrephoth–maim, and unto the valley of Mizpeh eastward; and they smote them, until they left them none remaining.",
"9 And Joshua did unto them as the LORD bade him: he houghed their horses, and burnt their chariots with fire.",
"10 And Joshua at that time turned back, and took Hazor, and smote the king thereof with the sword: for Hazor beforetime was the head of all those kingdoms.",
"11 And they smote all the souls that were therein with the edge of the sword, utterly destroying them: there was not any left to breathe: and he burnt Hazor with fire.",
"",
"——【The Book of Joshua 11】",
"",
"7 于是约书亚率领一切兵丁，在米伦水边突然向前攻打他们。",
"8 耶和华将他们交在以色列人手里，以色列人就击杀他们，追赶他们到西顿大城，到米斯利弗‧玛音，直到东边米斯巴的平原，将他们击杀，没有留下一个。",
"9 约书亚就照耶和华所吩咐他的去行，砍断他们马的蹄筋，用火焚烧他们的车辆。",
"10 当时，约书亚转回夺了夏琐，用刀击杀夏琐王。（素来夏琐在这诸国中是为首的。）",
"11 以色列人用刀击杀城中的人口，将他们尽行杀灭；凡有气息的没有留下一个。约书亚又用火焚烧夏琐。",
"",
"——【约书亚记 11】",
],
[
"13 Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.",
"14 And I myself also am persuaded of you, my brethren, that ye also are full of goodness, filled with all knowledge, able also to admonish one another.",
"15 Nevertheless, brethren, I have written the more boldly unto you in some sort, as putting you in mind, because of the grace that is given to me of God,",
"16 That I should be the minister of Jesus Christ to the Gentiles, ministering the gospel of God, that the offering up of the Gentiles might be acceptable, being sanctified by the Holy Ghost.",
"",
"——【The Epistle of Paul the Apostle to the Romans 15】",
"",
"13 但愿使人有盼望的　神，因信将诸般的喜乐、平安充满你们的心，使你们借著圣灵的能力大有盼望。",
"14 弟兄们，我自己也深信你们是满有良善，充足了诸般的知识，也能彼此劝戒。",
"15 但我稍微放胆写信给你们，是要提醒你们的记性，特因　神所给我的恩典，",
"16 使我为外邦人作基督耶稣的仆役，作　神福音的祭司，叫所献上的外邦人，因著圣灵成为圣洁，可蒙悦纳。",
"",
"——【罗马书 15】",
],
[
"7 And there was a young man out of Beth–lehem–judah of the family of Judah, who was a Levite, and he sojourned there.",
"8 And the man departed out of the city from Beth–lehem–judah to sojourn where he could find a place: and he came to mount Ephraim to the house of Micah, as he journeyed.",
"9 And Micah said unto him, Whence comest thou? And he said unto him, I am a Levite of Beth–lehem–judah, and I go to sojourn where I may find a place.",
"10 And Micah said unto him, Dwell with me, and be unto me a father and a priest, and I will give thee ten shekels of silver by the year, and a suit of apparel, and thy victuals. So the Levite went in.",
"11 And the Levite was content to dwell with the man; and the young man was unto him as one of his sons.",
"",
"——【The Book of Judges 17】",
"",
"7 犹大的伯利恒有一个少年人，是犹大族的利未人，他在那里寄居。",
"8 这人离开犹大的伯利恒城，要找一个可住的地方。行路的时候，到了以法莲山地，走到米迦的家。",
"9 米迦问他说：「你从哪里来？」他回答说：「从犹大的伯利恒来。我是利未人，要找一个可住的地方。」",
"10 米迦说：「你可以住在我这里，我以你为父、为祭司。我每年给你十舍客勒银子，一套衣服和度日的食物。」利未人就进了他的家。",
"11 利未人情愿与那人同住；那人看这少年人如自己的儿子一样。",
"",
"——【士师记 17】",
],
[
"1 Thus saith the LORD unto me, Go and get thee a linen girdle, and put it upon thy loins, and put it not in water.",
"2 So I got a girdle according to the word of the LORD, and put it on my loins.",
"3 And the word of the LORD came unto me the second time, saying,",
"4 Take the girdle that thou hast got, which is upon thy loins, and arise, go to Euphrates, and hide it there in a hole of the rock.",
"5 So I went, and hid it by Euphrates, as the LORD commanded me.",
"6 And it came to pass after many days, that the LORD said unto me, Arise, go to Euphrates, and take the girdle from thence, which I commanded thee to hide there.",
"",
"——【The Book of the Prophet Jeremiah 13】",
"",
"1 耶和华对我如此说：「你去买一根麻布带子束腰，不可放在水中。」",
"2 我就照著耶和华的话，买了一根带子束腰。",
"3 耶和华的话第二次临到我说：",
"4 「要拿著你所买的腰带，就是你腰上的带子，起来往幼发拉底河去，将腰带藏在那里的磐石穴中。」",
"5 我就去，照著耶和华所吩咐我的，将腰带藏在幼发拉底河边。",
"6 过了多日，耶和华对我说：「你起来往幼发拉底河去，将我吩咐你藏在那里的腰带取出来。」",
"",
"——【耶利米书 13】",
],
[
"21 Take heed, regard not iniquity: for this hast thou chosen rather than affliction.",
"22 Behold, God exalteth by his power: who teacheth like him?",
"23 Who hath enjoined him his way? or who can say, Thou hast wrought iniquity?",
"24 Remember that thou magnify his work, which men behold.",
"25 Every man may see it; man may behold it afar off.",
"26 Behold, God is great, and we know him not, neither can the number of his years be searched out.",
"",
"——【The Book of Job 36】",
"",
"21 你要谨慎，不可重看罪孽，因你选择罪孽过于选择苦难。",
"22 　神行事有高大的能力；教训人的有谁像他呢？",
"23 谁派定他的道路？谁能说：你所行的不义？",
"24 你不可忘记称讚他所行的为大，就是人所歌颂的。",
"25 他所行的，万人都看见；世人也从远处观看。",
"26 　神为大，我们不能全知；他的年数不能测度。",
"",
"——【约伯记 36】",
],
[
"148 Mine eyes prevent the night watches, that I might meditate in thy word.",
"149 Hear my voice according unto thy lovingkindness: O LORD, quicken me according to thy judgment.",
"150 They draw nigh that follow after mischief: they are far from thy law.",
"151 Thou art near, O LORD; and all thy commandments are truth.",
"152 Concerning thy testimonies, I have known of old that thou hast founded them for ever.",
"",
"——【The Book of Psalms 119】",
"",
"148 我趁夜更未换将眼睁开，为要思想你的话语。",
"149 求你照你的慈爱听我的声音；耶和华啊，求你照你的典章将我救活！",
"150 追求奸恶的人临近了；他们远离你的律法。",
"151 耶和华啊，你与我相近；你一切的命令尽都真实！",
"152 我因学你的法度，久已知道是你永远立定的。",
"",
"——【诗篇 119】",
],
[
"17 And they made an end with all the men that had taken strange wives by the first day of the first month.",
"18 And among the sons of the priests there were found that had taken strange wives: namely, of the sons of Jeshua the son of Jozadak, and his brethren; Maaseiah, and Eliezer, and Jarib, and Gedaliah.",
"19 And they gave their hands that they would put away their wives; and being guilty, they offered a ram of the flock for their trespass.",
"20 And of the sons of Immer; Hanani, and Zebadiah.",
"21 And of the sons of Harim; Maaseiah, and Elijah, and Shemaiah, and Jehiel, and Uzziah.",
"22 And of the sons of Pashur; Elioenai, Maaseiah, Ishmael, Nethaneel, Jozabad, and Elasah.",
"",
"——【Ezra 10】",
"",
"17 到正月初一日，才查清娶外邦女子的人数。",
"18 在祭司中查出娶外邦女子为妻的，就是耶书亚的子孙约萨达的儿子，和他弟兄玛西雅、以利以谢、雅立、基大利；",
"19 他们便应许必休他们的妻。他们因有罪，就献群中的一只公绵羊赎罪。",
"20 音麦的子孙中，有哈拿尼、西巴第雅。",
"21 哈琳的子孙中，有玛西雅、以利雅、示玛雅、耶歇、乌西雅。",
"22 巴施户珥的子孙中，有以利约乃、玛西雅、以实玛利、拿坦业、约撒拔、以利亚撒。",
"",
"——【以斯拉记 10】",
],
[
"37 And saying, If thou be the king of the Jews, save thyself.",
"38 And a superscription also was written over him in letters of Greek, and Latin, and Hebrew, THIS IS THE KING OF THE JEWS.",
"39 And one of the malefactors which were hanged railed on him, saying, If thou be Christ, save thyself and us.",
"",
"——【The Gospel According to Saint Luke 23】",
"",
"37 说：你若是犹太人的王，可以救自己吧！",
"38 在耶稣以上有一个牌子（有古卷在此有：用希腊、罗马、希伯来的文字）写著：这是犹太人的王。",
"39 那同钉的两个犯人有一个讥诮他，说：你不是基督吗？可以救自己和我们吧！",
"",
"——【路加福音 23】",
],
[
"25 Wherefore I gave them also statutes that were not good, and judgments whereby they should not live;",
"26 And I polluted them in their own gifts, in that they caused to pass through the fire all that openeth the womb, that I might make them desolate, to the end that they might know that I am the LORD.",
"27 Therefore, son of man, speak unto the house of Israel, and say unto them, Thus saith the Lord GOD; Yet in this your fathers have blasphemed me, in that they have committed a trespass against me.",
"28 For when I had brought them into the land, for the which I lifted up mine hand to give it to them, then they saw every high hill, and all the thick trees, and they offered there their sacrifices, and there they presented the provocation of their offering: there also they made their sweet savour, and poured out there their drink offerings.",
"29 Then I said unto them, What is the high place whereunto ye go? And the name thereof is called Bamah unto this day.",
"30 Wherefore say unto the house of Israel, Thus saith the Lord GOD; Are ye polluted after the manner of your fathers? and commit ye whoredom after their abominations?",
"",
"——【The Book of the Prophet Ezekiel 20】",
"",
"25 我也任他们遵行不美的律例，谨守不能使人活著的恶规。",
"26 因他们将一切头生的经火，我就任凭他们在这供献的事上玷污自己，好叫他们凄凉，使他们知道我是耶和华。",
"27 「人子啊，你要告诉以色列家说，主耶和华如此说：你们的列祖在得罪我的事上亵渎我；",
"28 因为我领他们到了我起誓应许赐给他们的地，他们看见各高山、各茂密树，就在那里献祭，奉上惹我发怒的供物，也在那里焚烧馨香的祭牲，并浇上奠祭。",
"29 我就对他们说：你们所上的那高处叫什么呢？（那高处的名字叫巴麻直到今日。）",
"30 所以你要对以色列家说，主耶和华如此说：你们仍照你们列祖所行的玷污自己吗？仍照他们可憎的事行邪淫吗？",
"",
"——【以西结书 20】",
],
[
"6 Whosoever abideth in him sinneth not: whosoever sinneth hath not seen him, neither known him.",
"7 Little children, let no man deceive you: he that doeth righteousness is righteous, even as he is righteous.",
"",
"——【The First Epistle General of John 3】",
"",
"6 凡住在他里面的，就不犯罪；凡犯罪的，是未曾看见他，也未曾认识他。",
"7 小子们哪，不要被人诱惑，行义的才是义人，正如主是义的一样。",
"",
"——【约翰一书 3】",
],
[
"10 I am not worthy of the least of all the mercies, and of all the truth, which thou hast shewed unto thy servant; for with my staff I passed over this Jordan; and now I am become two bands.",
"11 Deliver me, I pray thee, from the hand of my brother, from the hand of Esau: for I fear him, lest he will come and smite me, and the mother with the children.",
"12 And thou saidst, I will surely do thee good, and make thy seed as the sand of the sea, which cannot be numbered for multitude.",
"13 And he lodged there that same night; and took of that which came to his hand a present for Esau his brother;",
"",
"——【The First Book of Moses: Called Genesis 32】",
"",
"10 你向仆人所施的一切慈爱和诚实，我一点也不配得；我先前只拿著我的杖过这约旦河，如今我却成了两队了。",
"11 求你救我脱离我哥哥以扫的手；因为我怕他来杀我，连妻子带儿女一同杀了。",
"12 你曾说：『我必定厚待你，使你的后裔如同海边的沙，多得不可胜数。』」",
"13 当夜，雅各在那里住宿，就从他所有的物中拿礼物要送给他哥哥以扫：",
"",
"——【创世记 32】",
],
[
"21 For there is a man whose labour is in wisdom, and in knowledge, and in equity; yet to a man that hath not laboured therein shall he leave it for his portion. This also is vanity and a great evil.",
"22 For what hath man of all his labour, and of the vexation of his heart, wherein he hath laboured under the sun?",
"23 For all his days are sorrows, and his travail grief; yea, his heart taketh not rest in the night. This is also vanity.",
"24 There is nothing better for a man, than that he should eat and drink, and that he should make his soul enjoy good in his labour. This also I saw, that it was from the hand of God.",
"25 For who can eat, or who else can hasten hereunto, more than I?",
"26 For God giveth to a man that is good in his sight wisdom, and knowledge, and joy: but to the sinner he giveth travail, to gather and to heap up, that he may give to him that is good before God. This also is vanity and vexation of spirit.",
"",
"——【Ecclesiastes 2】",
"",
"21 因为有人用智慧、知识、灵巧所劳碌得来的，却要留给未曾劳碌的人为分。这也是虚空，也是大患。",
"22 人在日光之下劳碌累心，在他一切的劳碌上得著什么呢？",
"23 因为他日日忧虑，他的劳苦成为愁烦，连夜间心也不安。这也是虚空。",
"24 人莫强如吃喝，且在劳碌中享福，我看这也是出于　神的手。",
"25 论到吃用、享福，谁能胜过我呢？",
"26 　神喜悦谁，就给谁智慧、知识，和喜乐；惟有罪人，　神使他劳苦，叫他将所收聚的、所堆积的归给　神所喜悦的人。这也是虚空，也是捕风。",
"",
"——【传道书 2】",
],
[
"2 And Jephthah said unto them, I and my people were at great strife with the children of Ammon; and when I called you, ye delivered me not out of their hands.",
"3 And when I saw that ye delivered me not, I put my life in my hands, and passed over against the children of Ammon, and the LORD delivered them into my hand: wherefore then are ye come up unto me this day, to fight against me?",
"4 Then Jephthah gathered together all the men of Gilead, and fought with Ephraim: and the men of Gilead smote Ephraim, because they said, Ye Gileadites are fugitives of Ephraim among the Ephraimites, and among the Manassites.",
"",
"——【The Book of Judges 12】",
"",
"2 耶弗他对他们说：「我和我的民与亚扪人大大争战；我招你们来，你们竟没有来救我脱离他们的手。",
"3 我见你们不来救我，我就拚命前去攻击亚扪人，耶和华将他们交在我手中。你们今日为什么上我这里来攻打我呢？」",
"4 于是耶弗他招聚基列人，与以法莲人争战。基列人击杀以法莲，是因他们说：「你们基列人在以法莲、玛拿西中间，不过是以法莲逃亡的人。」",
"",
"——【士师记 12】",
],
[
"9 And saith unto him, All these things will I give thee, if thou wilt fall down and worship me.",
"10 Then saith Jesus unto him, Get thee hence, Satan: for it is written, Thou shalt worship the Lord thy God, and him only shalt thou serve.",
"11 Then the devil leaveth him, and, behold, angels came and ministered unto him.",
"12 Now when Jesus had heard that John was cast into prison, he departed into Galilee;",
"13 And leaving Nazareth, he came and dwelt in Capernaum, which is upon the sea coast, in the borders of Zabulon and Nephthalim:",
"",
"——【The Gospel According to Saint Matthew 4】",
"",
"9 对他说：「你若俯伏拜我，我就把这一切都赐给你。」",
"10 耶稣说：「撒但（撒但就是抵挡的意思，乃魔鬼的别名），退去吧！因为经上记著说：当拜主你的　神，单要事奉他。」",
"11 于是，魔鬼离了耶稣，有天使来伺候他。",
"12 耶稣听见约翰下了监，就退到加利利去；",
"13 后又离开拿撒勒，往迦百农去，就住在那里。那地方靠海，在西布伦和拿弗他利的边界上。",
"",
"——【马太福音 4】",
],
];
