var bible31_global=[
[
"1 O Israel, return unto the LORD thy God; for thou hast fallen by thine iniquity.",
"2 Take with you words, and turn to the LORD: say unto him, Take away all iniquity, and receive us graciously: so will we render the calves of our lips.",
"3 Asshur shall not save us; we will not ride upon horses: neither will we say any more to the work of our hands, Ye are our gods: for in thee the fatherless findeth mercy.",
"4 I will heal their backsliding, I will love them freely: for mine anger is turned away from him.",
"",
"——【Hosea 14】",
"",
"1 以色列啊，你要归向耶和华─你的　神；你是因自己的罪孽跌倒了。",
"2 当归向耶和华，用言语祷告他说：求你除净罪孽，悦纳善行；这样，我们就把嘴唇的祭代替牛犊献上。",
"3 我们不向亚述求救，不骑埃及的马，也不再对我们手所造的说：你是我们的　神。因为孤儿在你─耶和华那里得蒙怜悯。",
"4 我必医治他们背道的病，甘心爱他们；因为我的怒气向他们转消。",
"",
"——【何西阿书 14】",
],
[
"19 And a certain scribe came, and said unto him, Master, I will follow thee whithersoever thou goest.",
"20 And Jesus saith unto him, The foxes have holes, and the birds of the air have nests; but the Son of man hath not where to lay his head.",
"21 And another of his disciples said unto him, Lord, suffer me first to go and bury my father.",
"22 But Jesus said unto him, Follow me; and let the dead bury their dead.",
"23 And when he was entered into a ship, his disciples followed him.",
"",
"——【The Gospel According to Saint Matthew 8】",
"",
"19 有一个文士来，对他说：「夫子，你无论往那里去，我要跟从你。」",
"20 耶稣说：「狐狸有洞，天空的飞鸟有窝，人子却没有枕头的地方。」",
"21 又有一个门徒对耶稣说：「主啊，容我先回去埋葬我的父亲。」",
"22 耶稣说：「任凭死人埋葬他们的死人；你跟从我吧！」",
"23 耶稣上了船，门徒跟著他。",
"",
"——【马太福音 8】",
],
[
"23 And when Jesus came into the ruler's house, and saw the minstrels and the people making a noise,",
"24 He said unto them, Give place: for the maid is not dead, but sleepeth. And they laughed him to scorn.",
"25 But when the people were put forth, he went in, and took her by the hand, and the maid arose.",
"26 And the fame hereof went abroad into all that land.",
"27 And when Jesus departed thence, two blind men followed him, crying, and saying, Thou Son of David, have mercy on us.",
"28 And when he was come into the house, the blind men came to him: and Jesus saith unto them, Believe ye that I am able to do this? They said unto him, Yea, Lord.",
"",
"——【The Gospel According to Saint Matthew 9】",
"",
"23 耶稣到了管会堂的家里，看见有吹手，又有许多人乱嚷，",
"24 就说：退去吧！这闺女不是死了，是睡著了。他们就嗤笑他。",
"25 众人既被撵出，耶稣就进去，拉著闺女的手，闺女便起来了。",
"26 于是这风声传遍了那地方。",
"27 耶稣从那里往前走，有两个瞎子跟著他，喊叫说：大卫的子孙，可怜我们吧！",
"28 耶稣进了房子，瞎子就来到他跟前。耶稣说：你们信我能作这事吗？他们说：主啊，我们信。",
"",
"——【马太福音 9】",
],
[
"3 Behold, thou art wiser than Daniel; there is no secret that they can hide from thee:",
"4 With thy wisdom and with thine understanding thou hast gotten thee riches, and hast gotten gold and silver into thy treasures:",
"",
"——【The Book of the Prophet Ezekiel 28】",
"",
"3 看哪，你比但以理更有智慧，什么祕事都不能向你隐藏。",
"4 你靠自己的智慧聪明得了金银财宝，收入库中。",
"",
"——【以西结书 28】",
],
[
"3 Lay down now, put me in a surety with thee; who is he that will strike hands with me?",
"4 For thou hast hid their heart from understanding: therefore shalt thou not exalt them.",
"5 He that speaketh flattery to his friends, even the eyes of his children shall fail.",
"6 He hath made me also a byword of the people; and aforetime I was as a tabret.",
"7 Mine eye also is dim by reason of sorrow, and all my members are as a shadow.",
"",
"——【The Book of Job 17】",
"",
"3 愿主拿凭据给我，自己为我作保。在你以外谁肯与我击掌呢？",
"4 因你使他们心不明理，所以你必不高举他们。",
"5 控告他的朋友、以朋友为可抢夺的，连他儿女的眼睛也要失明。",
"6 　神使我作了民中的笑谈；他们也吐唾沫在我脸上。",
"7 我的眼睛因忧愁昏花；我的百体好像影儿。",
"",
"——【约伯记 17】",
],
[
"14 And he said unto him, Man, who made me a judge or a divider over you?",
"15 And he said unto them, Take heed, and beware of covetousness: for a man's life consisteth not in the abundance of the things which he possesseth.",
"",
"——【The Gospel According to Saint Luke 12】",
"",
"14 耶稣说：你这个人！谁立我作你们断事的官，给你们分家业呢？",
"15 于是对众人说：你们要谨慎自守，免去一切的贪心，因为人的生命不在乎家道丰富。",
"",
"——【路加福音 12】",
],
[
"1 And Moses went and spake these words unto all Israel.",
"2 And he said unto them, I am an hundred and twenty years old this day; I can no more go out and come in: also the LORD hath said unto me, Thou shalt not go over this Jordan.",
"3 The LORD thy God, he will go over before thee, and he will destroy these nations from before thee, and thou shalt possess them: and Joshua, he shall go over before thee, as the LORD hath said.",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 31】",
"",
"1 摩西去告诉以色列众人",
"2 说：「我现在一百二十岁了，不能照常出入；耶和华也曾对我说：『你必不得过这约旦河。』",
"3 耶和华─你们的　神必引导你们过去，将这些国民在你们面前灭绝，你们就得他们的地。约书亚必引导你们过去，正如耶和华所说的。",
"",
"——【申命记 31】",
],
[
"3 And they said, The God of the Hebrews hath met with us: let us go, we pray thee, three days' journey into the desert, and sacrifice unto the LORD our God; lest he fall upon us with pestilence, or with the sword.",
"4 And the king of Egypt said unto them, Wherefore do ye, Moses and Aaron, let the people from their works? get you unto your burdens.",
"5 And Pharaoh said, Behold, the people of the land now are many, and ye make them rest from their burdens.",
"6 And Pharaoh commanded the same day the taskmasters of the people, and their officers, saying,",
"7 Ye shall no more give the people straw to make brick, as heretofore: let them go and gather straw for themselves.",
"8 And the tale of the bricks, which they did make heretofore, ye shall lay upon them; ye shall not diminish ought thereof: for they be idle; therefore they cry, saying, Let us go and sacrifice to our God.",
"",
"——【The Second Book of Moses: Called Exodus 5】",
"",
"3 他们说：「希伯来人的　神遇见了我们。求你容我们往旷野去，走三天的路程，祭祀耶和华─我们的　神，免得他用瘟疫、刀兵攻击我们。」",
"4 埃及王对他们说：「摩西、亚伦！你们为什么叫百姓旷工呢？你们去担你们的担子吧！」",
"5 又说：「看哪，这地的以色列人如今众多，你们竟叫他们歇下担子！」",
"6 当天，法老吩咐督工的和官长说：",
"7 「你们不可照常把草给百姓做砖，叫他们自己去捡草。",
"8 他们素常做砖的数目，你们仍旧向他们要，一点不可减少；因为他们是懒惰的，所以呼求说：『容我们去祭祀我们的　神。』",
"",
"——【出埃及记 5】",
],
[
"1 The LORD is my shepherd; I shall not want.",
"2 He maketh me to lie down in green pastures: he leadeth me beside the still waters.",
"3 He restoreth my soul: he leadeth me in the paths of righteousness for his name's sake.",
"4 Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.",
"",
"——【The Book of Psalms 23】",
"",
"1 （大卫的诗。）耶和华是我的牧者，我必不致缺乏。",
"2 他使我躺卧在青草地上，领我在可安歇的水边。",
"3 他使我的灵魂甦醒，为自己的名引导我走义路。",
"4 我虽然行过死荫的幽谷，也不怕遭害，因为你与我同在；你的杖，你的竿，都安慰我。",
"",
"——【诗篇 23】",
],
[
"3 Be merciful unto me, O Lord: for I cry unto thee daily.",
"4 Rejoice the soul of thy servant: for unto thee, O Lord, do I lift up my soul.",
"5 For thou, Lord, art good, and ready to forgive; and plenteous in mercy unto all them that call upon thee.",
"",
"——【The Book of Psalms 86】",
"",
"3 主啊，求你怜悯我，因我终日求告你。",
"4 主啊，求你使仆人心里欢喜，因为我的心仰望你。",
"5 主啊，你本为良善，乐意饶恕人，有丰盛的慈爱赐给凡求告你的人。",
"",
"——【诗篇 86】",
],
[
"7 Thou breakest the ships of Tarshish with an east wind.",
"8 As we have heard, so have we seen in the city of the LORD of hosts, in the city of our God: God will establish it for ever. Selah.",
"9 We have thought of thy lovingkindness, O God, in the midst of thy temple.",
"10 According to thy name, O God, so is thy praise unto the ends of the earth: thy right hand is full of righteousness.",
"11 Let mount Zion rejoice, let the daughters of Judah be glad, because of thy judgments.",
"12 Walk about Zion, and go round about her: tell the towers thereof.",
"",
"——【The Book of Psalms 48】",
"",
"7 　神啊，你用东风打破他施的船只。",
"8 我们在万军之耶和华的城中─就是我们　神的城中─所看见的，正如我们所听见的。　神必坚立这城，直到永远。（细拉）",
"9 　神啊，我们在你的殿中想念你的慈爱。",
"10 　神啊，你受的讚美正与你的名相称，直到地极！你的右手满了公义。",
"11 因你的判断，锡安山应当欢喜，犹大的城邑（原文是女子）应当快乐。",
"12 你们当周游锡安，四围旋绕，数点城楼，",
"",
"——【诗篇 48】",
],
[
"11 These things command and teach.",
"12 Let no man despise thy youth; but be thou an example of the believers, in word, in conversation, in charity, in spirit, in faith, in purity.",
"13 Till I come, give attendance to reading, to exhortation, to doctrine.",
"14 Neglect not the gift that is in thee, which was given thee by prophecy, with the laying on of the hands of the presbytery.",
"15 Meditate upon these things; give thyself wholly to them; that thy profiting may appear to all.",
"16 Take heed unto thyself, and unto the doctrine; continue in them: for in doing this thou shalt both save thyself, and them that hear thee.",
"",
"——【The First Epistle of Paul the Apostle to Timothy 4】",
"",
"11 这些事，你要吩咐人，也要教导人。",
"12 不可叫人小看你年轻，总要在言语、行为、爱心、信心、清洁上，都作信徒的榜样。",
"13 你要以宣读、劝勉、教导为念，直等到我来。",
"14 你不要轻忽所得的恩赐，就是从前借著预言、在众长老按手的时候赐给你的。",
"15 这些事你要殷勤去做，并要在此专心，使众人看出你的长进来。",
"16 你要谨慎自己和自己的教训，要在这些事上恒心；因为这样行，又能救自己，又能救听你的人。",
"",
"——【提摩太前书 4】",
],
[
"11 And to him they had regard, because that of long time he had bewitched them with sorceries.",
"12 But when they believed Philip preaching the things concerning the kingdom of God, and the name of Jesus Christ, they were baptized, both men and women.",
"13 Then Simon himself believed also: and when he was baptized, he continued with Philip, and wondered, beholding the miracles and signs which were done.",
"14 Now when the apostles which were at Jerusalem heard that Samaria had received the word of God, they sent unto them Peter and John:",
"15 Who, when they were come down, prayed for them, that they might receive the Holy Ghost:",
"",
"——【The Acts of the Apostles 8】",
"",
"11 他们听从他，因他久用邪术，使他们惊奇。",
"12 及至他们信了腓利所传　神国的福音和耶稣基督的名，连男带女就受了洗。",
"13 西门自己也信了；既受了洗，就常与腓利在一处，看见他所行的神迹和大异能，就甚惊奇。",
"14 使徒在耶路撒冷听见撒马利亚人领受了　神的道，就打发彼得、约翰往他们那里去。",
"15 两个人到了，就为他们祷告，要叫他们受圣灵。",
"",
"——【使徒行传 8】",
],
[
"25 And immediately he rose up before them, and took up that whereon he lay, and departed to his own house, glorifying God.",
"26 And they were all amazed, and they glorified God, and were filled with fear, saying, We have seen strange things to day.",
"27 And after these things he went forth, and saw a publican, named Levi, sitting at the receipt of custom: and he said unto him, Follow me.",
"28 And he left all, rose up, and followed him.",
"29 And Levi made him a great feast in his own house: and there was a great company of publicans and of others that sat down with them.",
"",
"——【The Gospel According to Saint Luke 5】",
"",
"25 那人当众人面前立刻起来，拿著他所躺卧的褥子回家去，归荣耀与　神。",
"26 众人都惊奇，也归荣耀与　神，并且满心惧怕，说：我们今日看见非常的事了。",
"27 这事以后，耶稣出去，看见一个税吏，名叫利未，坐在税关上，就对他说：你跟从我来。",
"28 他就撇下所有的，起来，跟从了耶稣。",
"29 利未在自己家里为耶稣大摆筵席，有许多税吏和别人与他们一同坐席。",
"",
"——【路加福音 5】",
],
[
"13 He shall spare the poor and needy, and shall save the souls of the needy.",
"14 He shall redeem their soul from deceit and violence: and precious shall their blood be in his sight.",
"15 And he shall live, and to him shall be given of the gold of Sheba: prayer also shall be made for him continually; and daily shall he be praised.",
"16 There shall be an handful of corn in the earth upon the top of the mountains; the fruit thereof shall shake like Lebanon: and they of the city shall flourish like grass of the earth.",
"17 His name shall endure for ever: his name shall be continued as long as the sun: and men shall be blessed in him: all nations shall call him blessed.",
"18 Blessed be the LORD God, the God of Israel, who only doeth wondrous things.",
"",
"——【The Book of Psalms 72】",
"",
"13 他要怜恤贫寒和穷乏的人，拯救穷苦人的性命。",
"14 他要救赎他们脱离欺压和强暴；他们的血在他眼中看为宝贵。",
"15 他们要存活。示巴的金子要奉给他；人要常常为他祷告，终日称颂他。",
"16 在地的山顶上，五谷必然茂盛（或译：有一把五谷）；所结的谷实要响动，如黎巴嫩的树林；城里的人要发旺，如地上的草。",
"17 他的名要存到永远，要留传如日之久。人要因他蒙福；万国要称他有福。",
"18 独行奇事的耶和华─以色列的　神是应当称颂的！",
"",
"——【诗篇 72】",
],
[
"3 And he sought to see Jesus who he was; and could not for the press, because he was little of stature.",
"4 And he ran before, and climbed up into a sycomore tree to see him: for he was to pass that way.",
"5 And when Jesus came to the place, he looked up, and saw him, and said unto him, Zacchæus, make haste, and come down; for to day I must abide at thy house.",
"6 And he made haste, and came down, and received him joyfully.",
"",
"——【The Gospel According to Saint Luke 19】",
"",
"3 他要看看耶稣是怎样的人；只因人多，他的身量又矮，所以不得看见，",
"4 就跑到前头，爬上桑树，要看耶稣，因为耶稣必从那里经过。",
"5 耶稣到了那里，抬头一看，对他说：撒该，快下来！今天我必住在你家里。",
"6 他就急忙下来，欢欢喜喜的接待耶稣。",
"",
"——【路加福音 19】",
],
[
"13 And he left them, and entering into the ship again departed to the other side.",
"14 Now the disciples had forgotten to take bread, neither had they in the ship with them more than one loaf.",
"",
"——【The Gospel According to Saint Mark 8】",
"",
"13 他就离开他们，又上船往海那边去了。",
"14 门徒忘了带饼；在船上除了一个饼，没有别的食物。",
"",
"——【马可福音 8】",
],
[
"11 Therefore I am full of the fury of the LORD; I am weary with holding in: I will pour it out upon the children abroad, and upon the assembly of young men together: for even the husband with the wife shall be taken, the aged with him that is full of days.",
"12 And their houses shall be turned unto others, with their fields and wives together: for I will stretch out my hand upon the inhabitants of the land, saith the LORD.",
"13 For from the least of them even unto the greatest of them every one is given to covetousness; and from the prophet even unto the priest every one dealeth falsely.",
"14 They have healed also the hurt of the daughter of my people slightly, saying, Peace, peace; when there is no peace.",
"15 Were they ashamed when they had committed abomination? nay, they were not at all ashamed, neither could they blush: therefore they shall fall among them that fall: at the time that I visit them they shall be cast down, saith the LORD.",
"16 Thus saith the LORD, Stand ye in the ways, and see, and ask for the old paths, where is the good way, and walk therein, and ye shall find rest for your souls. But they said, We will not walk therein.",
"",
"——【The Book of the Prophet Jeremiah 6】",
"",
"11 因此我被耶和华的忿怒充满，难以含忍。我要倾在街中的孩童和聚会的少年人身上，连夫带妻，并年老的与日子满足的都必被擒拿。",
"12 他们的房屋、田地，和妻子都必转归别人；我要伸手攻击这地的居民。这是耶和华说的。",
"13 因为他们从最小的到至大的都一味地贪婪，从先知到祭司都行事虚谎。",
"14 他们轻轻忽忽地医治我百姓的损伤，说：平安了！平安了！其实没有平安。",
"15 他们行可憎的事知道惭愧吗？不然，他们毫不惭愧，也不知羞耻。因此，他们必在仆倒的人中仆倒；我向他们讨罪的时候，他们必致跌倒。这是耶和华说的。",
"16 耶和华如此说：你们当站在路上察看，访问古道，哪是善道，便行在其间；这样，你们心里必得安息。他们却说：我们不行在其间。",
"",
"——【耶利米书 6】",
],
[
"5 The foolish shall not stand in thy sight: thou hatest all workers of iniquity.",
"6 Thou shalt destroy them that speak leasing: the LORD will abhor the bloody and deceitful man.",
"7 But as for me, I will come into thy house in the multitude of thy mercy: and in thy fear will I worship toward thy holy temple.",
"",
"——【The Book of Psalms 5】",
"",
"5 狂傲人不能站在你眼前；凡作孽的，都是你所恨恶的。",
"6 说谎言的，你必灭绝；好流人血弄诡诈的，都为耶和华所憎恶。",
"7 至于我，我必凭你丰盛的慈爱进入你的居所；我必存敬畏你的心向你的圣殿下拜。",
"",
"——【诗篇 5】",
],
[
"18 If he hath wronged thee, or oweth thee ought, put that on mine account;",
"19 I Paul have written it with mine own hand, I will repay it: albeit I do not say to thee how thou owest unto me even thine own self besides.",
"20 Yea, brother, let me have joy of thee in the Lord: refresh my bowels in the Lord.",
"21 Having confidence in thy obedience I wrote unto thee, knowing that thou wilt also do more than I say.",
"22 But withal prepare me also a lodging: for I trust that through your prayers I shall be given unto you.",
"23 There salute thee Epaphras, my fellowprisoner in Christ Jesus;",
"",
"——【The Epistle of Paul the Apostle to Philemon 1】",
"",
"18 他若亏负你，或欠你什么，都归在我的帐上，",
"19 我必偿还。这是我保罗亲笔写的。我并不用对你说，连你自己也是亏欠于我。",
"20 兄弟啊，望你使我在主里因你得快乐（或作：益处）并望你使我的心在基督里得畅快。",
"21 我写信给你，深信你必顺服，知道你所要行的，必过于我所说的。",
"22 此外你还要给我预备住处；因为我盼望借著你们的祷告，必蒙恩到你们那里去。",
"23 为基督耶稣与我同坐监的以巴弗问你安。",
"",
"——【腓利门书 1】",
],
[
"9 And they put him in ward in chains, and brought him to the king of Babylon: they brought him into holds, that his voice should no more be heard upon the mountains of Israel.",
"10 Thy mother is like a vine in thy blood, planted by the waters: she was fruitful and full of branches by reason of many waters.",
"11 And she had strong rods for the sceptres of them that bare rule, and her stature was exalted among the thick branches, and she appeared in her height with the multitude of her branches.",
"12 But she was plucked up in fury, she was cast down to the ground, and the east wind dried up her fruit: her strong rods were broken and withered; the fire consumed them.",
"13 And now she is planted in the wilderness, in a dry and thirsty ground.",
"14 And fire is gone out of a rod of her branches, which hath devoured her fruit, so that she hath no strong rod to be a sceptre to rule. This is a lamentation, and shall be for a lamentation.",
"",
"——【The Book of the Prophet Ezekiel 19】",
"",
"9 他们用钩子钩住他，将他放在笼中，带到巴比伦王那里，将他放入坚固之所，使他的声音在以色列山上不再听见。",
"10 你的母亲先前如葡萄树，极其茂盛（原文是在你血中），栽于水旁。因为水多，就多结果子，满生枝子；",
"11 生出坚固的枝干，可作掌权者的杖。这枝干高举在茂密的枝中，而且它生长高大，枝子繁多，远远可见。",
"12 但这葡萄树因忿怒被拔出摔在地上；东风吹干其上的果子，坚固的枝干折断枯干，被火烧毁了；",
"13 如今栽于旷野干旱无水之地。",
"14 火也从它枝干中发出，烧灭果子，以致没有坚固的枝干可作掌权者的杖。这是哀歌，也必用以作哀歌。",
"",
"——【以西结书 19】",
],
[
"22 But thou hast not called upon me, O Jacob; but thou hast been weary of me, O Israel.",
"23 Thou hast not brought me the small cattle of thy burnt offerings; neither hast thou honoured me with thy sacrifices. I have not caused thee to serve with an offering, nor wearied thee with incense.",
"24 Thou hast bought me no sweet cane with money, neither hast thou filled me with the fat of thy sacrifices: but thou hast made me to serve with thy sins, thou hast wearied me with thine iniquities.",
"25 I, even I, am he that blotteth out thy transgressions for mine own sake, and will not remember thy sins.",
"26 Put me in remembrance: let us plead together: declare thou, that thou mayest be justified.",
"27 Thy first father hath sinned, and thy teachers have transgressed against me.",
"",
"——【The Book of the Prophet Isaiah 43】",
"",
"22 雅各啊，你并没有求告我；以色列啊，你倒厌烦我。",
"23 你没有将你的羊带来给我作燔祭，也没有用祭物尊敬我；我没有因供物使你服劳，也没有因乳香使你厌烦。",
"24 你没有用银子为我买菖蒲，也没有用祭物的脂油使我饱足；倒使我因你的罪恶服劳，使我因你的罪孽厌烦。",
"25 惟有我为自己的缘故涂抹你的过犯；我也不记念你的罪恶。",
"26 你要提醒我，你我可以一同辩论；你可以将你的理陈明，自显为义。",
"27 你的始祖犯罪；你的师傅违背我。",
"",
"——【以赛亚书 43】",
],
[
"29 The righteous shall inherit the land, and dwell therein for ever.",
"30 The mouth of the righteous speaketh wisdom, and his tongue talketh of judgment.",
"31 The law of his God is in his heart; none of his steps shall slide.",
"32 The wicked watcheth the righteous, and seeketh to slay him.",
"",
"——【The Book of Psalms 37】",
"",
"29 义人必承受地土，永居其上。",
"30 义人的口谈论智慧；他的舌头讲说公平。",
"31 　神的律法在他心里；他的脚总不滑跌。",
"32 恶人窥探义人，想要杀他。",
"",
"——【诗篇 37】",
],
[
"45 Strangers shall submit themselves unto me: as soon as they hear, they shall be obedient unto me.",
"46 Strangers shall fade away, and they shall be afraid out of their close places.",
"",
"——【The Second Book of Samuel 22】",
"",
"45 外邦人要投降我，一听见我的名声就必顺从我。",
"46 外邦人要衰残，战战兢兢地出他们的营寨。",
"",
"——【撒母耳记下 22】",
],
[
"28 And the altar of burnt offering with all his vessels, and the laver and his foot.",
"29 And thou shalt sanctify them, that they may be most holy: whatsoever toucheth them shall be holy.",
"30 And thou shalt anoint Aaron and his sons, and consecrate them, that they may minister unto me in the priest's office.",
"",
"——【The Second Book of Moses: Called Exodus 30】",
"",
"28 燔祭坛，和坛的一切器具，洗濯盆和盆座。",
"29 要使这些物成为圣，好成为至圣；凡挨著的都成为圣。",
"30 要膏亚伦和他的儿子，使他们成为圣，可以给我供祭司的职分。",
"",
"——【出埃及记 30】",
],
[
"2 Let my sentence come forth from thy presence; let thine eyes behold the things that are equal.",
"3 Thou hast proved mine heart; thou hast visited me in the night; thou hast tried me, and shalt find nothing; I am purposed that my mouth shall not transgress.",
"4 Concerning the works of men, by the word of thy lips I have kept me from the paths of the destroyer.",
"5 Hold up my goings in thy paths, that my footsteps slip not.",
"",
"——【The Book of Psalms 17】",
"",
"2 愿我的判语从你面前发出；愿你的眼睛观看公正。",
"3 你已经试验我的心；你在夜间鉴察我；你熬炼我，却找不著什么；我立志叫我口中没有过失。",
"4 论到人的行为，我借著你嘴唇的言语自己谨守，不行强暴人的道路。",
"5 我的脚踏定了你的路径；我的两脚未曾滑跌。",
"",
"——【诗篇 17】",
],
[
"9 Sing unto him, sing psalms unto him, talk ye of all his wondrous works.",
"10 Glory ye in his holy name: let the heart of them rejoice that seek the LORD.",
"11 Seek the LORD and his strength, seek his face continually.",
"12 Remember his marvellous works that he hath done, his wonders, and the judgments of his mouth;",
"",
"——【The First Book of the Chronicles 16】",
"",
"9 要向他唱诗、歌颂，谈论他一切奇妙的作为。",
"10 要以他的圣名夸耀；寻求耶和华的人，心中应当欢喜。",
"11 要寻求耶和华与他的能力，时常寻求他的面。",
"12 他仆人以色列的后裔，他所拣选雅各的子孙哪，你们要记念他奇妙的作为和他的奇事，并他口中的判语。",
"",
"——【历代志上 16】",
],
[
"1 The LORD said unto my Lord, Sit thou at my right hand, until I make thine enemies thy footstool.",
"2 The LORD shall send the rod of thy strength out of Zion: rule thou in the midst of thine enemies.",
"3 Thy people shall be willing in the day of thy power, in the beauties of holiness from the womb of the morning: thou hast the dew of thy youth.",
"",
"——【The Book of Psalms 110】",
"",
"1 （大卫的诗。）耶和华对我主说：你坐在我的右边，等我使你仇敌作你的脚凳。",
"2 耶和华必使你从锡安伸出能力的杖来；你要在你仇敌中掌权。",
"3 当你掌权的日子（或译：行军的日子），你的民要以圣洁的妆饰为衣（或译：以圣洁为妆饰），甘心牺牲自己；你的民多如清晨的甘露（或译：你少年时光耀如清晨的甘露）。",
"",
"——【诗篇 110】",
],
[
"4 For the LORD taketh pleasure in his people: he will beautify the meek with salvation.",
"5 Let the saints be joyful in glory: let them sing aloud upon their beds.",
"",
"——【The Book of Psalms 149】",
"",
"4 因为耶和华喜爱他的百姓；他要用救恩当作谦卑人的妆饰。",
"5 愿圣民因所得的荣耀高兴！愿他们在床上欢呼！",
"",
"——【诗篇 149】",
],
[
"1 Then answered Bildad the Shuhite, and said,",
"2 How long wilt thou speak these things? and how long shall the words of thy mouth be like a strong wind?",
"3 Doth God pervert judgment? or doth the Almighty pervert justice?",
"4 If thy children have sinned against him, and he have cast them away for their transgression;",
"",
"——【The Book of Job 8】",
"",
"1 书亚人比勒达回答说：",
"2 这些话你要说到几时？口中的言语如狂风要到几时呢？",
"3 　神岂能偏离公平？全能者岂能偏离公义？",
"4 或者你的儿女得罪了他；他使他们受报应。",
"",
"——【约伯记 8】",
],
[
"25 Rehum, Hashabnah, Maaseiah,",
"26 And Ahijah, Hanan, Anan,",
"27 Malluch, Harim, Baanah.",
"28 And the rest of the people, the priests, the Levites, the porters, the singers, the Nethinims, and all they that had separated themselves from the people of the lands unto the law of God, their wives, their sons, and their daughters, every one having knowledge, and having understanding;",
"29 They clave to their brethren, their nobles, and entered into a curse, and into an oath, to walk in God's law, which was given by Moses the servant of God, and to observe and do all the commandments of the LORD our Lord, and his judgments and his statutes;",
"30 And that we would not give our daughters unto the people of the land, nor take their daughters for our sons:",
"",
"——【The Book of Nehemiah 10】",
"",
"25 利宏、哈沙拿、玛西雅、",
"26 亚希雅、哈难、亚难、",
"27 玛鹿、哈琳、巴拿。",
"28 其余的民、祭司、利未人、守门的、歌唱的、尼提宁，和一切离绝邻邦居民归服　神律法的，并他们的妻子、儿女，凡有知识能明白的，",
"29 都随从他们贵冑的弟兄，发咒起誓，必遵行　神借他仆人摩西所传的律法，谨守遵行耶和华─我们主的一切诫命、典章、律例；",
"30 并不将我们的女儿嫁给这地的居民，也不为我们的儿子娶他们的女儿。",
"",
"——【尼希米记 10】",
],
];
