var bible31_global=[
[
"1 He that dasheth in pieces is come up before thy face: keep the munition, watch the way, make thy loins strong, fortify thy power mightily.",
"2 For the LORD hath turned away the excellency of Jacob, as the excellency of Israel: for the emptiers have emptied them out, and marred their vine branches.",
"3 The shield of his mighty men is made red, the valiant men are in scarlet: the chariots shall be with flaming torches in the day of his preparation, and the fir trees shall be terribly shaken.",
"4 The chariots shall rage in the streets, they shall justle one against another in the broad ways: they shall seem like torches, they shall run like the lightnings.",
"",
"——【Nahum 2】",
"",
"1 尼尼微啊，那打碎邦国的上来攻击你。你要看守保障，谨防道路，使腰强壮，大大勉力。",
"2 耶和华复兴雅各的荣华，好像以色列的荣华一样；因为使地空虚的，已经使雅各和以色列空虚，将他们的葡萄枝毁坏了。",
"3 他勇士的盾牌是红的，精兵都穿朱红衣服。在他预备争战的日子，战车上的钢铁闪烁如火，柏木把的枪也抡起来了。",
"4 车辆在街上（或译：城外）急行，在宽阔处奔来奔去，形状如火把，飞跑如闪电。",
"",
"——【那鸿书 2】",
],
[
"6 And the sea coast shall be dwellings and cottages for shepherds, and folds for flocks.",
"7 And the coast shall be for the remnant of the house of Judah; they shall feed thereupon: in the houses of Ashkelon shall they lie down in the evening: for the LORD their God shall visit them, and turn away their captivity.",
"8 I have heard the reproach of Moab, and the revilings of the children of Ammon, whereby they have reproached my people, and magnified themselves against their border.",
"9 Therefore as I live, saith the LORD of hosts, the God of Israel, Surely Moab shall be as Sodom, and the children of Ammon as Gomorrah, even the breeding of nettles, and saltpits, and a perpetual desolation: the residue of my people shall spoil them, and the remnant of my people shall possess them.",
"10 This shall they have for their pride, because they have reproached and magnified themselves against the people of the LORD of hosts.",
"11 The LORD will be terrible unto them: for he will famish all the gods of the earth; and men shall worship him, every one from his place, even all the isles of the heathen.",
"",
"——【Zephaniah 2】",
"",
"6 沿海之地要变为草场，其上有牧人的住处和羊群的圈。",
"7 这地必为犹大家剩下的人所得；他们必在那里牧放群羊，晚上必躺卧在亚实基伦的房屋中；因为耶和华─他们的　神必眷顾他们，使他们被掳的人归回。",
"8 我听见摩押人的毁谤和亚扪人的辱骂，就是毁谤我的百姓，自夸自大，侵犯他们的境界。",
"9 万军之耶和华─以色列的　神说：我指著我的永生起誓：摩押必像所多玛，亚扪人必像蛾摩拉，都变为刺草、盐坑、永远荒废之地。我百姓所剩下的必掳掠他们；我国中所余剩的必得著他们的地。",
"10 这事临到他们是因他们骄傲，自夸自大，毁谤万军之耶和华的百姓。",
"11 耶和华必向他们显可畏之威，因他必叫世上的诸神瘦弱。列国海岛的居民各在自己的地方敬拜他。",
"",
"——【西番雅书 2】",
],
[
"1 Help, LORD; for the godly man ceaseth; for the faithful fail from among the children of men.",
"2 They speak vanity every one with his neighbour: with flattering lips and with a double heart do they speak.",
"3 The LORD shall cut off all flattering lips, and the tongue that speaketh proud things:",
"4 Who have said, With our tongue will we prevail; our lips are our own: who is lord over us?",
"5 For the oppression of the poor, for the sighing of the needy, now will I arise, saith the LORD; I will set him in safety from him that puffeth at him.",
"6 The words of the LORD are pure words: as silver tried in a furnace of earth, purified seven times.",
"",
"——【The Book of Psalms 12】",
"",
"1 （大卫的诗，交与伶长。调用第八。）耶和华啊，求你帮助，因虔诚人断绝了；世人中间的忠信人没有了。",
"2 人人向邻舍说谎；他们说话，是嘴唇油滑，心口不一。",
"3 凡油滑的嘴唇和夸大的舌头，耶和华必要剪除。",
"4 他们曾说：我们必能以舌头得胜；我们的嘴唇是我们自己的，谁能作我们的主呢？",
"5 耶和华说：因为困苦人的冤屈和贫穷人的叹息，我现在要起来，把他安置在他所切慕的稳妥之地。",
"6 耶和华的言语是纯净的言语，如同银子在泥炉中炼过七次。",
"",
"——【诗篇 12】",
],
[
"27 And he put all upon Aaron's hands, and upon his sons' hands, and waved them for a wave offering before the LORD.",
"28 And Moses took them from off their hands, and burnt them on the altar upon the burnt offering: they were consecrations for a sweet savour: it is an offering made by fire unto the LORD.",
"29 And Moses took the breast, and waved it for a wave offering before the LORD: for of the ram of consecration it was Moses' part; as the LORD commanded Moses.",
"30 And Moses took of the anointing oil, and of the blood which was upon the altar, and sprinkled it upon Aaron, and upon his garments, and upon his sons, and upon his sons' garments with him; and sanctified Aaron, and his garments, and his sons, and his sons' garments with him.",
"31 And Moses said unto Aaron and to his sons, Boil the flesh at the door of the tabernacle of the congregation: and there eat it with the bread that is in the basket of consecrations, as I commanded, saying, Aaron and his sons shall eat it.",
"",
"——【The Third Book of Moses: Called Leviticus 8】",
"",
"27 把这一切放在亚伦的手上和他儿子的手上作摇祭，在耶和华面前摇一摇。",
"28 摩西从他们的手上拿下来，烧在坛上的燔祭上，都是为承接圣职献给耶和华馨香的火祭。",
"29 摩西拿羊的胸作为摇祭，在耶和华面前摇一摇，是承接圣职之礼，归摩西的分，都是照耶和华所吩咐摩西的。",
"30 摩西取点膏油和坛上的血，弹在亚伦和他的衣服上，并他儿子和他儿子的衣服上，使他和他们的衣服一同成圣。",
"31 摩西对亚伦和他儿子说：「把肉煮在会幕门口，在那里吃，又吃承接圣职筐子里的饼，按我所吩咐的说（或作：按所吩咐我的说）：『这是亚伦和他儿子要吃的。』",
"",
"——【利未记 8】",
],
[
"5 And he asked them, How many loaves have ye? And they said, Seven.",
"6 And he commanded the people to sit down on the ground: and he took the seven loaves, and gave thanks, and brake, and gave to his disciples to set before them; and they did set them before the people.",
"7 And they had a few small fishes: and he blessed, and commanded to set them also before them.",
"8 So they did eat, and were filled: and they took up of the broken meat that was left seven baskets.",
"",
"——【The Gospel According to Saint Mark 8】",
"",
"5 耶稣问他们说：你们有多少饼？他们说：七个。",
"6 他吩咐众人坐在地上，就拿著这七个饼祝谢了，擘开，递给门徒，叫他们摆开，门徒就摆在众人面前。",
"7 又有几条小鱼；耶稣祝了福，就吩咐也摆在众人面前。",
"8 众人都吃，并且吃饱了，收拾剩下的零碎，有七筐子。",
"",
"——【马可福音 8】",
],
[
"20 But Amaziah would not hear; for it came of God, that he might deliver them into the hand of their enemies, because they sought after the gods of Edom.",
"21 So Joash the king of Israel went up; and they saw one another in the face, both he and Amaziah king of Judah, at Beth–shemesh, which belongeth to Judah.",
"22 And Judah was put to the worse before Israel, and they fled every man to his tent.",
"",
"——【The Second Book of the Chronicles 25】",
"",
"20 亚玛谢却不肯听从。这是出乎　神，好将他们交在敌人手里，因为他们寻求以东的神。",
"21 于是以色列王约阿施上来，在犹大的伯‧示麦与犹大王亚玛谢相见于战场。",
"22 犹大人败在以色列人面前，各自逃回家里去了。",
"",
"——【历代志下 25】",
],
[
"27 Wherefore whosoever shall eat this bread, and drink this cup of the Lord, unworthily, shall be guilty of the body and blood of the Lord.",
"28 But let a man examine himself, and so let him eat of that bread, and drink of that cup.",
"29 For he that eateth and drinketh unworthily, eateth and drinketh damnation to himself, not discerning the Lord's body.",
"30 For this cause many are weak and sickly among you, and many sleep.",
"31 For if we would judge ourselves, we should not be judged.",
"32 But when we are judged, we are chastened of the Lord, that we should not be condemned with the world.",
"",
"——【The First Epistle of Paul the Apostle to the Corinthians 11】",
"",
"27 所以，无论何人，不按理吃主的饼，喝主的杯，就是干犯主的身、主的血了。",
"28 人应当自己省察，然后吃这饼、喝这杯。",
"29 因为人吃喝，若不分辨是主的身体，就是吃喝自己的罪了。",
"30 因此，在你们中间有好些软弱的与患病的，死（原文是睡）的也不少。",
"31 我们若是先分辨自己，就不至于受审。",
"32 我们受审的时候，乃是被主惩治，免得我们和世人一同定罪。",
"",
"——【哥林多前书 11】",
],
[
"23 Have I any pleasure at all that the wicked should die? saith the Lord GOD: and not that he should return from his ways, and live?",
"24 But when the righteous turneth away from his righteousness, and committeth iniquity, and doeth according to all the abominations that the wicked man doeth, shall he live? All his righteousness that he hath done shall not be mentioned: in his trespass that he hath trespassed, and in his sin that he hath sinned, in them shall he die.",
"",
"——【The Book of the Prophet Ezekiel 18】",
"",
"23 主耶和华说：恶人死亡，岂是我喜悦的吗？不是喜悦他回头离开所行的道存活吗？",
"24 义人若转离义行而作罪孽，照著恶人所行一切可憎的事而行，他岂能存活吗？他所行的一切义都不被记念；他必因所犯的罪、所行的恶死亡。",
"",
"——【以西结书 18】",
],
[
"5 And all the souls that came out of the loins of Jacob were seventy souls: for Joseph was in Egypt already.",
"6 And Joseph died, and all his brethren, and all that generation.",
"7 And the children of Israel were fruitful, and increased abundantly, and multiplied, and waxed exceeding mighty; and the land was filled with them.",
"8 Now there arose up a new king over Egypt, which knew not Joseph.",
"9 And he said unto his people, Behold, the people of the children of Israel are more and mightier than we:",
"10 Come on, let us deal wisely with them; lest they multiply, and it come to pass, that, when there falleth out any war, they join also unto our enemies, and fight against us, and so get them up out of the land.",
"",
"——【The Second Book of Moses: Called Exodus 1】",
"",
"5 凡从雅各而生的，共有七十人。约瑟已经在埃及。",
"6 约瑟和他的弟兄，并那一代的人，都死了。",
"7 以色列人生养众多，并且繁茂，极其强盛，满了那地。",
"8 有不认识约瑟的新王起来，治理埃及，",
"9 对他的百姓说：「看哪，这以色列民比我们还多，又比我们强盛。",
"10 来吧，我们不如用巧计待他们，恐怕他们多起来，日后若遇什么争战的事，就连合我们的仇敌攻击我们，离开这地去了。」",
"",
"——【出埃及记 1】",
],
[
"19 The chains, and the bracelets, and the mufflers,",
"20 The bonnets, and the ornaments of the legs, and the headbands, and the tablets, and the earrings,",
"21 The rings, and nose jewels,",
"22 The changeable suits of apparel, and the mantles, and the wimples, and the crisping pins,",
"",
"——【The Book of the Prophet Isaiah 3】",
"",
"19 耳环、手镯、蒙脸的帕子、",
"20 华冠、足鍊、华带、香盒、符囊、",
"21 戒指、鼻环、",
"22 吉服、外套、云肩、荷包、",
"",
"——【以赛亚书 3】",
],
[
"1 When the LORD thy God shall bring thee into the land whither thou goest to possess it, and hath cast out many nations before thee, the Hittites, and the Girgashites, and the Amorites, and the Canaanites, and the Perizzites, and the Hivites, and the Jebusites, seven nations greater and mightier than thou;",
"2 And when the LORD thy God shall deliver them before thee; thou shalt smite them, and utterly destroy them; thou shalt make no covenant with them, nor shew mercy unto them:",
"3 Neither shalt thou make marriages with them; thy daughter thou shalt not give unto his son, nor his daughter shalt thou take unto thy son.",
"4 For they will turn away thy son from following me, that they may serve other gods: so will the anger of the LORD be kindled against you, and destroy thee suddenly.",
"5 But thus shall ye deal with them; ye shall destroy their altars, and break down their images, and cut down their groves, and burn their graven images with fire.",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 7】",
"",
"1 「耶和华─你　神领你进入要得为业之地，从你面前赶出许多国民，就是赫人、革迦撒人、亚摩利人、迦南人、比利洗人、希未人、耶布斯人，共七国的民，都比你强大。",
"2 耶和华─你　神将他们交给你击杀，那时你要把他们灭绝净尽，不可与他们立约，也不可怜恤他们。",
"3 不可与他们结亲。不可将你的女儿嫁他们的儿子，也不可叫你的儿子娶他们的女儿；",
"4 因为他必使你儿子转离不跟从主，去事奉别神，以致耶和华的怒气向你们发作，就速速地将你们灭绝。",
"5 你们却要这样待他们：拆毁他们的祭坛，打碎他们的柱像，砍下他们的木偶，用火焚烧他们雕刻的偶像。",
"",
"——【申命记 7】",
],
[
"11 But the younger widows refuse: for when they have begun to wax wanton against Christ, they will marry;",
"12 Having damnation, because they have cast off their first faith.",
"13 And withal they learn to be idle, wandering about from house to house; and not only idle, but tattlers also and busybodies, speaking things which they ought not.",
"14 I will therefore that the younger women marry, bear children, guide the house, give none occasion to the adversary to speak reproachfully.",
"",
"——【The First Epistle of Paul the Apostle to Timothy 5】",
"",
"11 至于年轻的寡妇，就可以辞她；因为她们的情欲发动，违背基督的时候就想要嫁人。",
"12 她们被定罪，是因废弃了当初所许的愿；",
"13 并且她们又习惯懒惰，挨家闲游；不但是懒惰，又说长道短，好管闲事，说些不当说的话。",
"14 所以我愿意年轻的寡妇嫁人，生养儿女，治理家务，不给敌人辱骂的把柄。",
"",
"——【提摩太前书 5】",
],
[
"7 Send thine hand from above; rid me, and deliver me out of great waters, from the hand of strange children;",
"8 Whose mouth speaketh vanity, and their right hand is a right hand of falsehood.",
"9 I will sing a new song unto thee, O God: upon a psaltery and an instrument of ten strings will I sing praises unto thee.",
"10 It is he that giveth salvation unto kings: who delivereth David his servant from the hurtful sword.",
"11 Rid me, and deliver me from the hand of strange children, whose mouth speaketh vanity, and their right hand is a right hand of falsehood:",
"",
"——【The Book of Psalms 144】",
"",
"7 求你从上伸手救拔我，救我出离大水，救我脱离外邦人的手。",
"8 他们的口说谎话；他们的右手起假誓。",
"9 　神啊，我要向你唱新歌，用十弦瑟向你歌颂。",
"10 你是那拯救君王的；你是那救仆人大卫脱离害命之刀的。",
"11 求你救拔我，救我脱离外邦人的手。他们的口说谎话；他们的右手起假誓。",
"",
"——【诗篇 144】",
],
[
"1 Simon Peter, a servant and an apostle of Jesus Christ, to them that have obtained like precious faith with us through the righteousness of God and our Saviour Jesus Christ:",
"2 Grace and peace be multiplied unto you through the knowledge of God, and of Jesus our Lord,",
"3 According as his divine power hath given unto us all things that pertain unto life and godliness, through the knowledge of him that hath called us to glory and virtue:",
"",
"——【The Second General Epistle of Peter 1】",
"",
"1 作耶稣基督仆人和使徒的西门。彼得写信给那因我们的　神和（有古卷没有和字）救主耶稣基督之义，与我们同得一样宝贵信心的人。",
"2 愿恩惠、平安，因你们认识　神和我们主耶稣，多多的加给你们。",
"3 　神的神能已将一切关乎生命和虔敬的事赐给我们，皆因我们认识那用自己荣耀和美德召我们的主。",
"",
"——【彼得后书 1】",
],
[
"3 And one cried unto another, and said, Holy, holy, holy, is the LORD of hosts: the whole earth is full of his glory.",
"4 And the posts of the door moved at the voice of him that cried, and the house was filled with smoke.",
"5 Then said I, Woe is me! for I am undone; because I am a man of unclean lips, and I dwell in the midst of a people of unclean lips: for mine eyes have seen the King, the LORD of hosts.",
"6 Then flew one of the seraphims unto me, having a live coal in his hand, which he had taken with the tongs from off the altar:",
"",
"——【The Book of the Prophet Isaiah 6】",
"",
"3 彼此呼喊说：圣哉！圣哉！圣哉！万军之耶和华；他的荣光充满全地！",
"4 因呼喊者的声音，门槛的根基震动，殿充满了烟云。",
"5 那时我说：「祸哉！我灭亡了！因为我是嘴唇不洁的人，又住在嘴唇不洁的民中，又因我眼见大君王─万军之耶和华。」",
"6 有一撒拉弗飞到我跟前，手里拿著红炭，是用火剪从坛上取下来的，",
"",
"——【以赛亚书 6】",
],
[
"4 There were also that said, We have borrowed money for the king's tribute, and that upon our lands and vineyards.",
"5 Yet now our flesh is as the flesh of our brethren, our children as their children: and, lo, we bring into bondage our sons and our daughters to be servants, and some of our daughters are brought unto bondage already: neither is it in our power to redeem them; for other men have our lands and vineyards.",
"6 And I was very angry when I heard their cry and these words.",
"",
"——【The Book of Nehemiah 5】",
"",
"4 有的说：「我们已经指著田地、葡萄园，借了钱给王纳税。",
"5 我们的身体与我们弟兄的身体一样；我们的儿女与他们的儿女一般。现在我们将要使儿女作人的仆婢，我们的女儿已有为婢的；我们并无力拯救，因为我们的田地、葡萄园已经归了别人。」",
"6 我听见他们呼号说这些话，便甚发怒。",
"",
"——【尼希米记 5】",
],
[
"2 Arise, go unto Nineveh, that great city, and preach unto it the preaching that I bid thee.",
"3 So Jonah arose, and went unto Nineveh, according to the word of the LORD. Now Nineveh was an exceeding great city of three days' journey.",
"4 And Jonah began to enter into the city a day's journey, and he cried, and said, Yet forty days, and Nineveh shall be overthrown.",
"5 So the people of Nineveh believed God, and proclaimed a fast, and put on sackcloth, from the greatest of them even to the least of them.",
"6 For word came unto the king of Nineveh, and he arose from his throne, and he laid his robe from him, and covered him with sackcloth, and sat in ashes.",
"7 And he caused it to be proclaimed and published through Nineveh by the decree of the king and his nobles, saying, Let neither man nor beast, herd nor flock, taste any thing: let them not feed, nor drink water:",
"",
"——【Jonah 3】",
"",
"2 「你起来！往尼尼微大城去，向其中的居民宣告我所吩咐你的话。」",
"3 约拿便照耶和华的话起来，往尼尼微去。这尼尼微是极大的城，有三日的路程。",
"4 约拿进城走了一日，宣告说：「再等四十日，尼尼微必倾覆了！」",
"5 尼尼微人信服　神，便宣告禁食，从最大的到至小的都穿麻衣（或译：披上麻布）。",
"6 这信息传到尼尼微王的耳中，他就下了宝座，脱下朝服，披上麻布，坐在灰中。",
"7 他又使人遍告尼尼微通城，说：「王和大臣有令，人不可尝什么，牲畜、牛羊不可吃草，也不可喝水。",
"",
"——【约拿书 3】",
],
[
"3 And David prepared iron in abundance for the nails for the doors of the gates, and for the joinings; and brass in abundance without weight;",
"4 Also cedar trees in abundance: for the Zidonians and they of Tyre brought much cedar wood to David.",
"5 And David said, Solomon my son is young and tender, and the house that is to be builded for the LORD must be exceeding magnifical, of fame and of glory throughout all countries: I will therefore now make preparation for it. So David prepared abundantly before his death.",
"6 Then he called for Solomon his son, and charged him to build an house for the LORD God of Israel.",
"7 And David said to Solomon, My son, as for me, it was in my mind to build an house unto the name of the LORD my God:",
"8 But the word of the LORD came to me, saying, Thou hast shed blood abundantly, and hast made great wars: thou shalt not build an house unto my name, because thou hast shed much blood upon the earth in my sight.",
"",
"——【The First Book of the Chronicles 22】",
"",
"3 大卫预备许多铁做门上的钉子和钩子，又预备许多铜，多得无法可称；",
"4 又预备无数的香柏木，因为西顿人和推罗人给大卫运了许多香柏木来。",
"5 大卫说：「我儿子所罗门还年幼娇嫩，要为耶和华建造的殿宇必须高大辉煌，使名誉荣耀传遍万国；所以我要为殿预备材料。」于是，大卫在未死之先预备的材料甚多。",
"6 大卫召了他儿子所罗门来，嘱咐他给耶和华─以色列的　神建造殿宇，",
"7 对所罗门说：「我儿啊，我心里本想为耶和华─我　神的名建造殿宇，",
"8 只是耶和华的话临到我说：『你流了多人的血，打了多次大仗，你不可为我的名建造殿宇，因为你在我眼前使多人的血流在地上。",
"",
"——【历代志上 22】",
],
[
"1 Paul, an apostle of Jesus Christ by the will of God, and Timothy our brother, unto the church of God which is at Corinth, with all the saints which are in all Achaia:",
"2 Grace be to you and peace from God our Father, and from the Lord Jesus Christ.",
"3 Blessed be God, even the Father of our Lord Jesus Christ, the Father of mercies, and the God of all comfort;",
"",
"——【The Second Epistle of Paul the Apostle to the Corinthians 1】",
"",
"1 奉　神旨意作基督耶稣使徒的保罗和兄弟提摩太，写信给在哥林多　神的教会，并亚该亚遍处的众圣徒。",
"2 愿恩惠、平安从　神我们的父和主耶稣基督归与你们！",
"3 愿颂讚归与我们的主耶稣基督的父　神，就是发慈悲的父，赐各样安慰的　神。",
"",
"——【哥林多后书 1】",
],
[
"2 Arise, go unto Nineveh, that great city, and preach unto it the preaching that I bid thee.",
"3 So Jonah arose, and went unto Nineveh, according to the word of the LORD. Now Nineveh was an exceeding great city of three days' journey.",
"4 And Jonah began to enter into the city a day's journey, and he cried, and said, Yet forty days, and Nineveh shall be overthrown.",
"",
"——【Jonah 3】",
"",
"2 「你起来！往尼尼微大城去，向其中的居民宣告我所吩咐你的话。」",
"3 约拿便照耶和华的话起来，往尼尼微去。这尼尼微是极大的城，有三日的路程。",
"4 约拿进城走了一日，宣告说：「再等四十日，尼尼微必倾覆了！」",
"",
"——【约拿书 3】",
],
[
"8 A gift is as a precious stone in the eyes of him that hath it: whithersoever it turneth, it prospereth.",
"9 He that covereth a transgression seeketh love; but he that repeateth a matter separateth very friends.",
"10 A reproof entereth more into a wise man than an hundred stripes into a fool.",
"11 An evil man seeketh only rebellion: therefore a cruel messenger shall be sent against him.",
"12 Let a bear robbed of her whelps meet a man, rather than a fool in his folly.",
"13 Whoso rewardeth evil for good, evil shall not depart from his house.",
"",
"——【The Proverbs 17】",
"",
"8 贿赂在餽送的人眼中看为宝玉，随处运动都得顺利。",
"9 遮掩人过的，寻求人爱；屡次挑错的，离间密友。",
"10 一句责备话深入聪明人的心，强如责打愚昧人一百下。",
"11 恶人只寻背叛，所以必有严厉的使者奉差攻击他。",
"12 宁可遇见丢崽子的母熊，不可遇见正行愚妄的愚昧人。",
"13 以恶报善的，祸患必不离他的家。",
"",
"——【箴言 17】",
],
[
"3 Speak, and say, Thus saith the Lord GOD; Behold, I am against thee, Pharaoh king of Egypt, the great dragon that lieth in the midst of his rivers, which hath said, My river is mine own, and I have made it for myself.",
"4 But I will put hooks in thy jaws, and I will cause the fish of thy rivers to stick unto thy scales, and I will bring thee up out of the midst of thy rivers, and all the fish of thy rivers shall stick unto thy scales.",
"",
"——【The Book of the Prophet Ezekiel 29】",
"",
"3 说主耶和华如此说：埃及王法老啊，我与你这卧在自己河中的大鱼为敌。你曾说：这河是我的，是我为自己造的。",
"4 我─耶和华必用钩子钩住你的腮颊，又使江河中的鱼贴住你的鳞甲；我必将你和所有贴住你鳞甲的鱼，从江河中拉上来，",
"",
"——【以西结书 29】",
],
[
"13 I saw in the night visions, and, behold, one like the Son of man came with the clouds of heaven, and came to the Ancient of days, and they brought him near before him.",
"14 And there was given him dominion, and glory, and a kingdom, that all people, nations, and languages, should serve him: his dominion is an everlasting dominion, which shall not pass away, and his kingdom that which shall not be destroyed.",
"15 I Daniel was grieved in my spirit in the midst of my body, and the visions of my head troubled me.",
"",
"——【The Book of Daniel 7】",
"",
"13 我在夜间的异象中观看，见有一位像人子的，驾著天云而来，被领到亘古常在者面前，",
"14 得了权柄、荣耀、国度，使各方、各国、各族的人都事奉他。他的权柄是永远的，不能废去；他的国必不败坏。",
"15 至于我─但以理，我的灵在我里面愁烦，我脑中的异象使我惊惶。",
"",
"——【但以理书 7】",
],
[
"16 Take his garment that is surety for a stranger: and take a pledge of him for a strange woman.",
"17 Bread of deceit is sweet to a man; but afterwards his mouth shall be filled with gravel.",
"",
"——【The Proverbs 20】",
"",
"16 谁为生人作保，就拿谁的衣服；谁为外人作保，谁就要承当。",
"17 以虚谎而得的食物，人觉甘甜；但后来，他的口必充满尘沙。",
"",
"——【箴言 20】",
],
[
"21 And then if any man shall say to you, Lo, here is Christ; or, lo, he is there; believe him not:",
"22 For false Christs and false prophets shall rise, and shall shew signs and wonders, to seduce, if it were possible, even the elect.",
"23 But take ye heed: behold, I have foretold you all things.",
"",
"——【The Gospel According to Saint Mark 13】",
"",
"21 那时若有人对你们说：看哪，基督在这里，或说：基督在那里，你们不要信！",
"22 因为假基督、假先知将要起来，显神迹奇事，倘若能行，就把选民迷惑了。",
"23 你们要谨慎。看哪，凡事我都预先告诉你们了。",
"",
"——【马可福音 13】",
],
[
"1 When a man hath taken a wife, and married her, and it come to pass that she find no favour in his eyes, because he hath found some uncleanness in her: then let him write her a bill of divorcement, and give it in her hand, and send her out of his house.",
"2 And when she is departed out of his house, she may go and be another man's wife.",
"3 And if the latter husband hate her, and write her a bill of divorcement, and giveth it in her hand, and sendeth her out of his house; or if the latter husband die, which took her to be his wife;",
"4 Her former husband, which sent her away, may not take her again to be his wife, after that she is defiled; for that is abomination before the LORD: and thou shalt not cause the land to sin, which the LORD thy God giveth thee for an inheritance.",
"5 When a man hath taken a new wife, he shall not go out to war, neither shall he be charged with any business: but he shall be free at home one year, and shall cheer up his wife which he hath taken.",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 24】",
"",
"1 「人若娶妻以后，见她有什么不合理的事，不喜悦她，就可以写休书交在她手中，打发她离开夫家。",
"2 妇人离开夫家以后，可以去嫁别人。",
"3 后夫若恨恶她，写休书交在她手中，打发她离开夫家，或是娶她为妻的后夫死了，",
"4 打发她去的前夫不可在妇人玷污之后再娶她为妻，因为这是耶和华所憎恶的；不可使耶和华─你　神所赐为业之地被玷污了。",
"5 「新娶妻之人不可从军出征，也不可托他办理什么公事，可以在家清闲一年，使他所娶的妻快活。",
"",
"——【申命记 24】",
],
[
"8 Then came Amalek, and fought with Israel in Rephidim.",
"9 And Moses said unto Joshua, Choose us out men, and go out, fight with Amalek: to morrow I will stand on the top of the hill with the rod of God in mine hand.",
"10 So Joshua did as Moses had said to him, and fought with Amalek: and Moses, Aaron, and Hur went up to the top of the hill.",
"11 And it came to pass, when Moses held up his hand, that Israel prevailed: and when he let down his hand, Amalek prevailed.",
"12 But Moses' hands were heavy; and they took a stone, and put it under him, and he sat thereon; and Aaron and Hur stayed up his hands, the one on the one side, and the other on the other side; and his hands were steady until the going down of the sun.",
"",
"——【The Second Book of Moses: Called Exodus 17】",
"",
"8 那时，亚玛力人来在利非订，和以色列人争战。",
"9 摩西对约书亚说：「你为我们选出人来，出去和亚玛力人争战。明天我手里要拿著　神的杖，站在山顶上。」",
"10 于是约书亚照著摩西对他所说的话行，和亚玛力人争战。摩西、亚伦，与户珥都上了山顶。",
"11 摩西何时举手，以色列人就得胜，何时垂手，亚玛力人就得胜。",
"12 但摩西的手发沉，他们就搬石头来，放在他以下，他就坐在上面。亚伦与户珥扶著他的手，一个在这边，一个在那边，他的手就稳住，直到日落的时候。",
"",
"——【出埃及记 17】",
],
[
"1 If one be found slain in the land which the LORD thy God giveth thee to possess it, lying in the field, and it be not known who hath slain him:",
"2 Then thy elders and thy judges shall come forth, and they shall measure unto the cities which are round about him that is slain:",
"3 And it shall be, that the city which is next unto the slain man, even the elders of that city shall take an heifer, which hath not been wrought with, and which hath not drawn in the yoke;",
"4 And the elders of that city shall bring down the heifer unto a rough valley, which is neither eared nor sown, and shall strike off the heifer's neck there in the valley:",
"5 And the priests the sons of Levi shall come near; for them the LORD thy God hath chosen to minister unto him, and to bless in the name of the LORD; and by their word shall every controversy and every stroke be tried:",
"6 And all the elders of that city, that are next unto the slain man, shall wash their hands over the heifer that is beheaded in the valley:",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 21】",
"",
"1 「在耶和华─你　神所赐你为业的地上，若遇见被杀的人倒在田野，不知道是谁杀的，",
"2 长老和审判官就要出去，从被杀的人那里量起，直量到四围的城邑，",
"3 看哪城离被杀的人最近，那城的长老就要从牛群中取一只未曾耕地、未曾负轭的母牛犊，",
"4 把母牛犊牵到流水、未曾耕种的山谷去，在谷中打折母牛犊的颈项。",
"5 祭司利未的子孙要近前来；因为耶和华─你的　神拣选了他们事奉他，奉耶和华的名祝福，所有争讼殴打的事都要凭他们判断。",
"6 那城的众长老，就是离被杀的人最近的，要在那山谷中，在所打折颈项的母牛犊以上洗手，",
"",
"——【申命记 21】",
],
[
"25 And the sons of Elkanah; Amasai, and Ahimoth.",
"26 As for Elkanah: the sons of Elkanah; Zophai his son, and Nahath his son,",
"27 Eliab his son, Jeroham his son, Elkanah his son.",
"",
"——【The First Book of the Chronicles 6】",
"",
"25 以利加拿的儿子是亚玛赛和亚希摩。",
"26 亚希摩的儿子是以利加拿；以利加拿的儿子是琐菲；琐菲的儿子是拿哈；",
"27 拿哈的儿子是以利押；以利押的儿子是耶罗罕；耶罗罕的儿子是以利加拿；以利加拿的儿子是撒母耳。",
"",
"——【历代志上 6】",
],
[
"13 Then she said, Let me find favour in thy sight, my lord; for that thou hast comforted me, and for that thou hast spoken friendly unto thine handmaid, though I be not like unto one of thine handmaidens.",
"14 And Boaz said unto her, At mealtime come thou hither, and eat of the bread, and dip thy morsel in the vinegar. And she sat beside the reapers: and he reached her parched corn, and she did eat, and was sufficed, and left.",
"15 And when she was risen up to glean, Boaz commanded his young men, saying, Let her glean even among the sheaves, and reproach her not:",
"16 And let fall also some of the handfuls of purpose for her, and leave them, that she may glean them, and rebuke her not.",
"17 So she gleaned in the field until even, and beat out that she had gleaned: and it was about an ephah of barley.",
"18 And she took it up, and went into the city: and her mother in law saw what she had gleaned: and she brought forth, and gave to her that she had reserved after she was sufficed.",
"",
"——【The Book of Ruth 2】",
"",
"13 路得说：「我主啊，愿在你眼前蒙恩。我虽然不及你的一个使女，你还用慈爱的话安慰我的心。」",
"14 到了吃饭的时候，波阿斯对路得说：「你到这里来吃饼，将饼蘸在醋里。」路得就在收割的人旁边坐下；他们把烘了的穗子递给她。她吃饱了，还有余剩的。",
"15 她起来又拾取麦穗，波阿斯吩咐仆人说：「她就是在捆中拾取麦穗，也可以容她，不可羞辱她；",
"16 并要从捆里抽出些来，留在地下任她拾取，不可叱吓她。」",
"17 这样，路得在田间拾取麦穗，直到晚上，将所拾取的打了，约有一伊法大麦。",
"18 她就把所拾取的带进城去给婆婆看，又把她吃饱了所剩的给了婆婆。",
"",
"——【路得记 2】",
],
[
"8 Shall not the land tremble for this, and every one mourn that dwelleth therein? and it shall rise up wholly as a flood; and it shall be cast out and drowned, as by the flood of Egypt.",
"9 And it shall come to pass in that day, saith the Lord GOD, that I will cause the sun to go down at noon, and I will darken the earth in the clear day:",
"10 And I will turn your feasts into mourning, and all your songs into lamentation; and I will bring up sackcloth upon all loins, and baldness upon every head; and I will make it as the mourning of an only son, and the end thereof as a bitter day.",
"",
"——【Amos 8】",
"",
"8 地岂不因这事震动？其上的居民不也悲哀吗？地必全然像尼罗河涨起，如同埃及河涌上落下。",
"9 主耶和华说：到那日，我必使日头在午间落下，使地在白昼黑暗。",
"10 我必使你们的节期变为悲哀，歌曲变为哀歌。众人腰束麻布，头上光秃，使这场悲哀如丧独生子，至终如痛苦的日子一样。",
"",
"——【阿摩司书 8】",
],
];
