var bible31_global=[
[
"9 Not of works, lest any man should boast.",
"10 For we are his workmanship, created in Christ Jesus unto good works, which God hath before ordained that we should walk in them.",
"11 Wherefore remember, that ye being in time past Gentiles in the flesh, who are called Uncircumcision by that which is called the Circumcision in the flesh made by hands;",
"12 That at that time ye were without Christ, being aliens from the commonwealth of Israel, and strangers from the covenants of promise, having no hope, and without God in the world:",
"13 But now in Christ Jesus ye who sometimes were far off are made nigh by the blood of Christ.",
"",
"——【The Epistle of Paul the Apostle to the Ephesians 2】",
"",
"9 也不是出于行为，免得有人自夸。",
"10 我们原是他的工作，在基督耶稣里造成的，为要叫我们行善，就是　神所预备叫我们行的。",
"11 所以你们应当记念：你们从前按肉体是外邦人，是称为没受割礼的；这名原是那些凭人手在肉身上称为受割礼之人所起的。",
"12 那时，你们与基督无关，在以色列国民以外，在所应许的诸约上是局外人，并且活在世上没有指望，没有　神。",
"13 你们从前远离　神的人，如今却在基督耶稣里，靠著他的血，已经得亲近了。",
"",
"——【以弗所书 2】",
],
[
"24 But they hearkened not, nor inclined their ear, but walked in the counsels and in the imagination of their evil heart, and went backward, and not forward.",
"25 Since the day that your fathers came forth out of the land of Egypt unto this day I have even sent unto you all my servants the prophets, daily rising up early and sending them:",
"26 Yet they hearkened not unto me, nor inclined their ear, but hardened their neck: they did worse than their fathers.",
"27 Therefore thou shalt speak all these words unto them; but they will not hearken to thee: thou shalt also call unto them; but they will not answer thee.",
"",
"——【The Book of the Prophet Jeremiah 7】",
"",
"24 他们却不听从，不侧耳而听，竟随从自己的计谋和顽梗的恶心，向后不向前。",
"25 自从你们列祖出埃及地的那日，直到今日，我差遣我的仆人众先知到你们那里去，每日从早起来差遣他们。",
"26 你们却不听从，不侧耳而听，竟硬著颈项行恶，比你们列祖更甚。",
"27 「你要将这一切的话告诉他们，他们却不听从；呼唤他们，他们却不答应。",
"",
"——【耶利米书 7】",
],
[
"9 And he came thither unto a cave, and lodged there; and, behold, the word of the LORD came to him, and he said unto him, What doest thou here, Elijah?",
"10 And he said, I have been very jealous for the LORD God of hosts: for the children of Israel have forsaken thy covenant, thrown down thine altars, and slain thy prophets with the sword; and I, even I only, am left; and they seek my life, to take it away.",
"",
"——【The First Book of the Kings 19】",
"",
"9 他在那里进了一个洞，就住在洞中。耶和华的话临到他说：「以利亚啊，你在这里做什么？」",
"10 他说：「我为耶和华─万军之　神大发热心；因为以色列人背弃了你的约，毁坏了你的坛，用刀杀了你的先知，只剩下我一个人，他们还要寻索我的命。」",
"",
"——【列王记上 19】",
],
[
"1 When Israel went out of Egypt, the house of Jacob from a people of strange language;",
"2 Judah was his sanctuary, and Israel his dominion.",
"",
"——【The Book of Psalms 114】",
"",
"1 以色列出了埃及，雅各家离开说异言之民；",
"2 那时，犹大为主的圣所，以色列为他所治理的国度。",
"",
"——【诗篇 114】",
],
[
"17 Which said unto God, Depart from us: and what can the Almighty do for them?",
"18 Yet he filled their houses with good things: but the counsel of the wicked is far from me.",
"19 The righteous see it, and are glad: and the innocent laugh them to scorn.",
"20 Whereas our substance is not cut down, but the remnant of them the fire consumeth.",
"21 Acquaint now thyself with him, and be at peace: thereby good shall come unto thee.",
"",
"——【The Book of Job 22】",
"",
"17 他们向　神说：离开我们吧！又说：全能者能把我们怎么样呢？",
"18 哪知　神以美物充满他们的房屋；但恶人所谋定的离我好远。",
"19 义人看见他们的结局就欢喜；无辜的人嗤笑他们，",
"20 说：那起来攻击我们的果然被剪除，其余的都被火烧灭。",
"21 你要认识　神，就得平安；福气也必临到你。",
"",
"——【约伯记 22】",
],
[
"5 And afterward offered the continual burnt offering, both of the new moons, and of all the set feasts of the LORD that were consecrated, and of every one that willingly offered a freewill offering unto the LORD.",
"6 From the first day of the seventh month began they to offer burnt offerings unto the LORD. But the foundation of the temple of the LORD was not yet laid.",
"",
"——【Ezra 3】",
"",
"5 其后献常献的燔祭，并在月朔与耶和华的一切圣节献祭，又向耶和华献各人的甘心祭。",
"6 从七月初一日起，他们就向耶和华献燔祭。但耶和华殿的根基尚未立定。",
"",
"——【以斯拉记 3】",
],
[
"1 Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us,",
"2 Looking unto Jesus the author and finisher of our faith; who for the joy that was set before him endured the cross, despising the shame, and is set down at the right hand of the throne of God.",
"3 For consider him that endured such contradiction of sinners against himself, lest ye be wearied and faint in your minds.",
"4 Ye have not yet resisted unto blood, striving against sin.",
"5 And ye have forgotten the exhortation which speaketh unto you as unto children, My son, despise not thou the chastening of the Lord, nor faint when thou art rebuked of him:",
"6 For whom the Lord loveth he chasteneth, and scourgeth every son whom he receiveth.",
"",
"——【The Epistle of Paul the Apostle to the Hebrews 12】",
"",
"1 我们既有这许多的见证人，如同云彩围著我们，就当放下各样的重担，脱去容易缠累我们的罪，存心忍耐，奔那摆在我们前头的路程，",
"2 仰望为我们信心创始成终的耶稣（或作：仰望那将真道创始成终的耶稣）。他因那摆在前面的喜乐，就轻看羞辱，忍受了十字架的苦难，便坐在　神宝座的右边。",
"3 那忍受罪人这样顶撞的，你们要思想，免得疲倦灰心。",
"4 你们与罪恶相争，还没有抵挡到流血的地步。",
"5 你们又忘了那劝你们如同劝儿子的话，说：我儿，你不可轻看主的管教，被他责备的时候也不可灰心；",
"6 因为主所爱的，他必管教，又鞭打凡所收纳的儿子。",
"",
"——【希伯来书 12】",
],
[
"2 Let us come before his presence with thanksgiving, and make a joyful noise unto him with psalms.",
"3 For the LORD is a great God, and a great King above all gods.",
"4 In his hand are the deep places of the earth: the strength of the hills is his also.",
"5 The sea is his, and he made it: and his hands formed the dry land.",
"6 O come, let us worship and bow down: let us kneel before the LORD our maker.",
"",
"——【The Book of Psalms 95】",
"",
"2 我们要来感谢他，用诗歌向他欢呼！",
"3 因耶和华为大　神，为大王，超乎万神之上。",
"4 地的深处在他手中；山的高峰也属他。",
"5 海洋属他，是他造的；旱地也是他手造成的。",
"6 来啊，我们要屈身敬拜，在造我们的耶和华面前跪下。",
"",
"——【诗篇 95】",
],
[
"17 And have no root in themselves, and so endure but for a time: afterward, when affliction or persecution ariseth for the word's sake, immediately they are offended.",
"18 And these are they which are sown among thorns; such as hear the word,",
"19 And the cares of this world, and the deceitfulness of riches, and the lusts of other things entering in, choke the word, and it becometh unfruitful.",
"20 And these are they which are sown on good ground; such as hear the word, and receive it, and bring forth fruit, some thirtyfold, some sixty, and some an hundred.",
"21 And he said unto them, Is a candle brought to be put under a bushel, or under a bed? and not to be set on a candlestick?",
"22 For there is nothing hid, which shall not be manifested; neither was any thing kept secret, but that it should come abroad.",
"",
"——【The Gospel According to Saint Mark 4】",
"",
"17 但他心里没有根，不过是暂时的，及至为道遭了患难，或是受了逼迫，立刻就跌倒了。",
"18 还有那撒在荆棘里的，就是人听了道，",
"19 后来有世上的思虑、钱财的迷惑，和别样的私欲进来，把道挤住了，就不能结实。",
"20 那撒在好地上的，就是人听道，又领受，并且结实，有三十倍的，有六十倍的，有一百倍的。",
"21 耶稣又对他们说：人拿灯来，岂是要放在斗底下，床底下，不放在灯台上吗？",
"22 因为掩藏的事，没有不显出来的；隐瞒的事，没有不露出来的。",
"",
"——【马可福音 4】",
],
[
"3 That they may do evil with both hands earnestly, the prince asketh, and the judge asketh for a reward; and the great man, he uttereth his mischievous desire: so they wrap it up.",
"4 The best of them is as a brier: the most upright is sharper than a thorn hedge: the day of thy watchmen and thy visitation cometh; now shall be their perplexity.",
"5 Trust ye not in a friend, put ye not confidence in a guide: keep the doors of thy mouth from her that lieth in thy bosom.",
"",
"——【Micah 7】",
"",
"3 他们双手作恶；君王徇情面，审判官要贿赂；位分大的吐出恶意，都彼此结联行恶。",
"4 他们最好的，不过是蒺藜；最正直的，不过是荆棘篱笆。你守望者说，降罚的日子已经来到。他们必扰乱不安。",
"5 不要倚赖邻舍；不要信靠密友。要守住你的口；不要向你怀中的妻提说。",
"",
"——【弥迦书 7】",
],
[
"1 Judge me, O God, and plead my cause against an ungodly nation: O deliver me from the deceitful and unjust man.",
"2 For thou art the God of my strength: why dost thou cast me off? why go I mourning because of the oppression of the enemy?",
"3 O send out thy light and thy truth: let them lead me; let them bring me unto thy holy hill, and to thy tabernacles.",
"4 Then will I go unto the altar of God, unto God my exceeding joy: yea, upon the harp will I praise thee, O God my God.",
"",
"——【The Book of Psalms 43】",
"",
"1 　神啊，求你伸我的冤，向不虔诚的国为我辨屈；求你救我脱离诡诈不义的人。",
"2 因为你是赐我力量的　神，为何丢弃我呢？我为何因仇敌的欺压时常哀痛呢？",
"3 求你发出你的亮光和真实，好引导我，带我到你的圣山，到你的居所！",
"4 我就走到　神的祭坛，到我最喜乐的　神那里。　神啊，我的　神，我要弹琴称讚你！",
"",
"——【诗篇 43】",
],
[
"21 Separate yourselves from among this congregation, that I may consume them in a moment.",
"22 And they fell upon their faces, and said, O God, the God of the spirits of all flesh, shall one man sin, and wilt thou be wroth with all the congregation?",
"23 And the LORD spake unto Moses, saying,",
"",
"——【The Fourth Book of Moses: Called Numbers 16】",
"",
"21 「你们离开这会众，我好在转眼之间把他们灭绝。」",
"22 摩西、亚伦就俯伏在地，说：「　神，万人之灵的　神啊，一人犯罪，你就要向全会众发怒吗？」",
"23 耶和华晓谕摩西说：",
"",
"——【民数记 16】",
],
[
"1 The burden of the word of the LORD for Israel, saith the LORD, which stretcheth forth the heavens, and layeth the foundation of the earth, and formeth the spirit of man within him.",
"2 Behold, I will make Jerusalem a cup of trembling unto all the people round about, when they shall be in the siege both against Judah and against Jerusalem.",
"3 And in that day will I make Jerusalem a burdensome stone for all people: all that burden themselves with it shall be cut in pieces, though all the people of the earth be gathered together against it.",
"",
"——【Zechariah 12】",
"",
"1 耶和华论以色列的默示。铺张诸天、建立地基、造人里面之灵的耶和华说：",
"2 「我必使耶路撒冷被围困的时候，向四围列国的民成为令人昏醉的杯；这默示也论到犹大（或译：犹大也是如此）。",
"3 那日，我必使耶路撒冷向聚集攻击他的万民当作一块重石头；凡举起的必受重伤。",
"",
"——【撒迦利亚书 12】",
],
[
"17 I am glad of the coming of Stephanas and Fortunatus and Achaicus: for that which was lacking on your part they have supplied.",
"18 For they have refreshed my spirit and yours: therefore acknowledge ye them that are such.",
"19 The churches of Asia salute you. Aquila and Priscilla salute you much in the Lord, with the church that is in their house.",
"20 All the brethren greet you. Greet ye one another with an holy kiss.",
"",
"——【The First Epistle of Paul the Apostle to the Corinthians 16】",
"",
"17 司提反和福徒拿都，并亚该古到这里来，我很喜欢；因为你们待我有不及之处，他们补上了。",
"18 他们叫我和你们心里都快活。这样的人，你们务要敬重。",
"19 亚细亚的众教会问你们安。亚居拉和百基拉并在他们家里的教会，因主多多的问你们安。",
"20 众弟兄都问你们安。你们要亲嘴问安，彼此务要圣洁。",
"",
"——【哥林多前书 16】",
],
[
"51 And smote all the firstborn in Egypt; the chief of their strength in the tabernacles of Ham:",
"52 But made his own people to go forth like sheep, and guided them in the wilderness like a flock.",
"53 And he led them on safely, so that they feared not: but the sea overwhelmed their enemies.",
"54 And he brought them to the border of his sanctuary, even to this mountain, which his right hand had purchased.",
"55 He cast out the heathen also before them, and divided them an inheritance by line, and made the tribes of Israel to dwell in their tents.",
"",
"——【The Book of Psalms 78】",
"",
"51 在埃及击杀一切长子，在含的帐棚中击杀他们强壮时头生的。",
"52 他却领出自己的民如羊，在旷野引他们如羊群。",
"53 他领他们稳稳妥妥地，使他们不致害怕；海却淹没他们的仇敌。",
"54 他带他们到自己圣地的边界，到他右手所得的这山地。",
"55 他在他们面前赶出外邦人，用绳子将外邦的地量给他们为业，叫以色列支派的人住在他们的帐棚里。",
"",
"——【诗篇 78】",
],
[
"3 I thank God, whom I serve from my forefathers with pure conscience, that without ceasing I have remembrance of thee in my prayers night and day;",
"4 Greatly desiring to see thee, being mindful of thy tears, that I may be filled with joy;",
"5 When I call to remembrance the unfeigned faith that is in thee, which dwelt first in thy grandmother Lois, and thy mother Eunice; and I am persuaded that in thee also.",
"",
"——【The Second Epistle of Paul the Apostle to Timothy 1】",
"",
"3 我感谢　神，就是我接续祖先用清洁的良心所事奉的　神。祈祷的时候，不住的想念你！",
"4 记念你的眼泪，昼夜切切的想要见你，好叫我满心快乐。",
"5 想到你心里无伪之信，这信是先在你外祖母罗以和你母亲友尼基心里的，我深信也在你的心里。",
"",
"——【提摩太后书 1】",
],
[
"4 Every man praying or prophesying, having his head covered, dishonoureth his head.",
"5 But every woman that prayeth or prophesieth with her head uncovered dishonoureth her head: for that is even all one as if she were shaven.",
"6 For if the woman be not covered, let her also be shorn: but if it be a shame for a woman to be shorn or shaven, let her be covered.",
"",
"——【The First Epistle of Paul the Apostle to the Corinthians 11】",
"",
"4 凡男人祷告或是讲道（或作：说预言；下同），若蒙著头，就羞辱自己的头。",
"5 凡女人祷告或是讲道，若不蒙著头，就羞辱自己的头，因为这就如同剃了头发一样。",
"6 女人若不蒙著头，就该剪了头发；女人若以剪发、剃发为羞愧，就该蒙著头。",
"",
"——【哥林多前书 11】",
],
[
"30 This is he of whom I said, After me cometh a man which is preferred before me: for he was before me.",
"31 And I knew him not: but that he should be made manifest to Israel, therefore am I come baptizing with water.",
"32 And John bare record, saying, I saw the Spirit descending from heaven like a dove, and it abode upon him.",
"33 And I knew him not: but he that sent me to baptize with water, the same said unto me, Upon whom thou shalt see the Spirit descending, and remaining on him, the same is he which baptizeth with the Holy Ghost.",
"34 And I saw, and bare record that this is the Son of God.",
"",
"——【The Gospel According to Saint John 1】",
"",
"30 这就是我曾说：『有一位在我以后来、反成了在我以前的，因他本来在我以前。』",
"31 我先前不认识他，如今我来用水施洗，为要叫他显明给以色列人。」",
"32 约翰又作见证说：「我曾看见圣灵，彷彿鸽子从天降下，住在他的身上。",
"33 我先前不认识他，只是那差我来用水施洗的、对我说：『你看见圣灵降下来，住在谁的身上，谁就是用圣灵施洗的。』",
"34 我看见了，就证明这是　神的儿子。」",
"",
"——【约翰福音 1】",
],
[
"1 The burden of the word of the LORD to Israel by Malachi.",
"2 I have loved you, saith the LORD. Yet ye say, Wherein hast thou loved us? Was not Esau Jacob's brother? saith the LORD: yet I loved Jacob,",
"3 And I hated Esau, and laid his mountains and his heritage waste for the dragons of the wilderness.",
"",
"——【Malachi 1】",
"",
"1 耶和华借玛拉基传给以色列的默示。",
"2 耶和华说：「我曾爱你们。」你们却说：「你在何事上爱我们呢？」耶和华说：「以扫不是雅各的哥哥吗？我却爱雅各，",
"3 恶以扫，使他的山岭荒凉，把他的地业交给旷野的野狗。」",
"",
"——【玛拉基书 1】",
],
[
"24 And David sat between the two gates: and the watchman went up to the roof over the gate unto the wall, and lifted up his eyes, and looked, and behold a man running alone.",
"25 And the watchman cried, and told the king. And the king said, If he be alone, there is tidings in his mouth. And he came apace, and drew near.",
"26 And the watchman saw another man running: and the watchman called unto the porter, and said, Behold another man running alone. And the king said, He also bringeth tidings.",
"27 And the watchman said, Me thinketh the running of the foremost is like the running of Ahimaaz the son of Zadok. And the king said, He is a good man, and cometh with good tidings.",
"28 And Ahimaaz called, and said unto the king, All is well. And he fell down to the earth upon his face before the king, and said, Blessed be the LORD thy God, which hath delivered up the men that lifted up their hand against my lord the king.",
"",
"——【The Second Book of Samuel 18】",
"",
"24 大卫正坐在城甕里。守望的人上城门楼的顶上，举目观看，见有一个人独自跑来。",
"25 守望的人就大声告诉王。王说：「他若独自来，必是报口信的。」那人跑得渐渐近了。",
"26 守望的人又见一人跑来，就对守城门的人说：「又有一人独自跑来。」王说：「这也必是报信的。」",
"27 守望的人说：「我看前头人的跑法，好像撒督的儿子亚希玛斯的跑法一样。」王说：「他是个好人，必是报好信息。」",
"28 亚希玛斯向王呼叫说：「平安了！」就在王面前脸伏于地叩拜，说：「耶和华─你的　神是应当称颂的，因他已将那举手攻击我主我王的人交给王了。」",
"",
"——【撒母耳记下 18】",
],
[
"3 For the enemy hath persecuted my soul; he hath smitten my life down to the ground; he hath made me to dwell in darkness, as those that have been long dead.",
"4 Therefore is my spirit overwhelmed within me; my heart within me is desolate.",
"5 I remember the days of old; I meditate on all thy works; I muse on the work of thy hands.",
"6 I stretch forth my hands unto thee: my soul thirsteth after thee, as a thirsty land. Selah.",
"",
"——【The Book of Psalms 143】",
"",
"3 原来仇敌逼迫我，将我打倒在地，使我住在幽暗之处，像死了许久的人一样。",
"4 所以，我的灵在我里面发昏；我的心在我里面悽惨。",
"5 我追想古时之日，思想你的一切作为，默念你手的工作。",
"6 我向你举手；我的心渴想你，如干旱之地盼雨一样。（细拉）",
"",
"——【诗篇 143】",
],
[
"13 Beriah also, and Shema, who were heads of the fathers of the inhabitants of Aijalon, who drove away the inhabitants of Gath:",
"14 And Ahio, Shashak, and Jeremoth,",
"15 And Zebadiah, and Arad, and Ader,",
"16 And Michael, and Ispah, and Joha, the sons of Beriah;",
"17 And Zebadiah, and Meshullam, and Hezeki, and Heber,",
"18 Ishmerai also, and Jezliah, and Jobab, the sons of Elpaal;",
"",
"——【The First Book of the Chronicles 8】",
"",
"13 又有比利亚和示玛是亚雅崙居民的族长，是驱逐迦特人的。",
"14 亚希约、沙煞、耶利末、",
"15 西巴第雅、亚拉得、亚得、",
"16 米迦勒、伊施巴、约哈都是比利亚的儿子。",
"17 西巴第雅、米书兰、希西基、希伯、",
"18 伊施米莱、伊斯利亚、约巴都是以利巴力的儿子。",
"",
"——【历代志上 8】",
],
[
"4 These are the feasts of the LORD, even holy convocations, which ye shall proclaim in their seasons.",
"5 In the fourteenth day of the first month at even is the LORD'S passover.",
"6 And on the fifteenth day of the same month is the feast of unleavened bread unto the LORD: seven days ye must eat unleavened bread.",
"7 In the first day ye shall have an holy convocation: ye shall do no servile work therein.",
"8 But ye shall offer an offering made by fire unto the LORD seven days: in the seventh day is an holy convocation: ye shall do no servile work therein.",
"",
"——【The Third Book of Moses: Called Leviticus 23】",
"",
"4 耶和华的节期，就是你们到了日期要宣告为圣会的，乃是这些。」",
"5 正月十四日，黄昏的时候，是耶和华的逾越节。",
"6 这月十五日是向耶和华守的无酵节；你们要吃无酵饼七日。",
"7 第一日当有圣会，什么劳碌的工都不可做；",
"8 要将火祭献给耶和华七日。第七日是圣会，什么劳碌的工都不可做。」",
"",
"——【利未记 23】",
],
[
"25 And weighed unto them the silver, and the gold, and the vessels, even the offering of the house of our God, which the king, and his counsellors, and his lords, and all Israel there present, had offered:",
"26 I even weighed unto their hand six hundred and fifty talents of silver, and silver vessels an hundred talents, and of gold an hundred talents;",
"",
"——【Ezra 8】",
"",
"25 将王和谋士、军长，并在那里的以色列众人为我们　神殿所献的金银和器皿，都秤了交给他们。",
"26 我秤了交在他们手中的银子有六百五十他连得；银器重一百他连得；金子一百他连得；",
"",
"——【以斯拉记 8】",
],
[
"20 And Isaac was forty years old when he took Rebekah to wife, the daughter of Bethuel the Syrian of Padan–aram, the sister to Laban the Syrian.",
"21 And Isaac intreated the LORD for his wife, because she was barren: and the LORD was intreated of him, and Rebekah his wife conceived.",
"22 And the children struggled together within her; and she said, If it be so, why am I thus? And she went to enquire of the LORD.",
"23 And the LORD said unto her, Two nations are in thy womb, and two manner of people shall be separated from thy bowels; and the one people shall be stronger than the other people; and the elder shall serve the younger.",
"24 And when her days to be delivered were fulfilled, behold, there were twins in her womb.",
"25 And the first came out red, all over like an hairy garment; and they called his name Esau.",
"",
"——【The First Book of Moses: Called Genesis 25】",
"",
"20 以撒娶利百加为妻的时候正四十岁。利百加是巴旦‧亚兰地的亚兰人彼土利的女儿，是亚兰人拉班的妹子。",
"21 以撒因他妻子不生育，就为她祈求耶和华；耶和华应允他的祈求，他的妻子利百加就怀了孕。",
"22 孩子们在她腹中彼此相争，她就说：「若是这样，我为什么活著呢【或作我为什么如此呢】？」她就去求问耶和华。",
"23 耶和华对她说：两国在你腹内；两族要从你身上出来。这族必强于那族；将来大的要服事小的。",
"24 生产的日子到了，腹中果然是双子。",
"25 先产的身体发红，浑身有毛，如同皮衣，他们就给他起名叫以扫【就是有毛的意思】。",
"",
"——【创世记 25】",
],
[
"4 And Ben–hadad hearkened unto king Asa, and sent the captains of his armies against the cities of Israel; and they smote Ijon, and Dan, and Abel–maim, and all the store cities of Naphtali.",
"5 And it came to pass, when Baasha heard it, that he left off building of Ramah, and let his work cease.",
"6 Then Asa the king took all Judah; and they carried away the stones of Ramah, and the timber thereof, wherewith Baasha was building; and he built therewith Geba and Mizpah.",
"7 And at that time Hanani the seer came to Asa king of Judah, and said unto him, Because thou hast relied on the king of Syria, and not relied on the LORD thy God, therefore is the host of the king of Syria escaped out of thine hand.",
"",
"——【The Second Book of the Chronicles 16】",
"",
"4 便哈达听从亚撒王的话，派军长去攻击以色列的城邑。他们就攻破以云、但、亚伯玛音，和拿弗他利一切的积货城。",
"5 巴沙听见就停工，不修筑拉玛了。",
"6 于是亚撒王率领犹大众人，将巴沙修筑拉玛所用的石头、木头都运去，用以修筑迦巴和米斯巴。",
"7 那时，先见哈拿尼来见犹大王亚撒，对他说：「因你仰赖亚兰王，没有仰赖耶和华─你的　神，所以亚兰王的军兵脱离了你的手。",
"",
"——【历代志下 16】",
],
[
"10 And it came to pass, that as soon as he had made an end of offering the burnt offering, behold, Samuel came; and Saul went out to meet him, that he might salute him.",
"11 And Samuel said, What hast thou done? And Saul said, Because I saw that the people were scattered from me, and that thou camest not within the days appointed, and that the Philistines gathered themselves together at Michmash;",
"12 Therefore said I, The Philistines will come down now upon me to Gilgal, and I have not made supplication unto the LORD: I forced myself therefore, and offered a burnt offering.",
"",
"——【The First Book of Samuel 13】",
"",
"10 刚献完燔祭，撒母耳就到了。扫罗出去迎接他，要问他好。",
"11 撒母耳说：「你做的是什么事呢？」扫罗说：「因为我见百姓离开我散去，你也不照所定的日期来到，而且非利士人聚集在密抹。",
"12 所以我心里说：恐怕我没有祷告耶和华。非利士人下到吉甲攻击我，我就勉强献上燔祭。」",
"",
"——【撒母耳记上 13】",
],
[
"1 Preserve me, O God: for in thee do I put my trust.",
"2 O my soul, thou hast said unto the LORD, Thou art my Lord: my goodness extendeth not to thee;",
"3 But to the saints that are in the earth, and to the excellent, in whom is all my delight.",
"4 Their sorrows shall be multiplied that hasten after another god: their drink offerings of blood will I not offer, nor take up their names into my lips.",
"",
"——【The Book of Psalms 16】",
"",
"1 （大卫的金诗。）　神啊，求你保佑我，因为我投靠你。",
"2 我的心哪，你曾对耶和华说：你是我的主；我的好处不在你以外。",
"3 论到世上的圣民，他们又美又善，是我最喜悦的。",
"4 以别神代替耶和华的（或译：送礼物给别神的），他们的愁苦必加增；他们所浇奠的血我不献上；我嘴唇也不提别神的名号。",
"",
"——【诗篇 16】",
],
[
"1 Be merciful unto me, O God, be merciful unto me: for my soul trusteth in thee: yea, in the shadow of thy wings will I make my refuge, until these calamities be overpast.",
"2 I will cry unto God most high; unto God that performeth all things for me.",
"3 He shall send from heaven, and save me from the reproach of him that would swallow me up. Selah. God shall send forth his mercy and his truth.",
"4 My soul is among lions: and I lie even among them that are set on fire, even the sons of men, whose teeth are spears and arrows, and their tongue a sharp sword.",
"",
"——【The Book of Psalms 57】",
"",
"1 （大卫逃避扫罗，藏在洞里。那时，他作这金诗，交与伶长。调用休要毁坏。）　神啊，求你怜悯我，怜悯我！因为我的心投靠你。我要投靠在你翅膀的荫下，等到灾害过去。",
"2 我要求告至高的　神，就是为我成全诸事的　神。",
"3 那要吞我的人辱骂我的时候，　神从天上必施恩救我，也必向我发出慈爱和诚实。",
"4 我的性命在狮子中间；我躺卧在性如烈火的世人当中。他们的牙齿是枪、箭；他们的舌头是快刀。",
"",
"——【诗篇 57】",
],
[
"14 So Joab and the people that were with him drew nigh before the Syrians unto the battle; and they fled before him.",
"15 And when the children of Ammon saw that the Syrians were fled, they likewise fled before Abishai his brother, and entered into the city. Then Joab came to Jerusalem.",
"16 And when the Syrians saw that they were put to the worse before Israel, they sent messengers, and drew forth the Syrians that were beyond the river: and Shophach the captain of the host of Hadarezer went before them.",
"17 And it was told David; and he gathered all Israel, and passed over Jordan, and came upon them, and set the battle in array against them. So when David had put the battle in array against the Syrians, they fought with him.",
"18 But the Syrians fled before Israel; and David slew of the Syrians seven thousand men which fought in chariots, and forty thousand footmen, and killed Shophach the captain of the host.",
"",
"——【The First Book of the Chronicles 19】",
"",
"14 于是约押和跟随他的人前进攻打亚兰人；亚兰人在约押面前逃跑。",
"15 亚扪人见亚兰人逃跑，他们也在约押的兄弟亚比筛面前逃跑进城。约押就回耶路撒冷去了。",
"16 亚兰人见自己被以色列人打败，就打发使者将大河那边的亚兰人调来，哈大利谢的将军朔法率领他们。",
"17 有人告诉大卫，他就聚集以色列众人过约旦河，来到亚兰人那里，迎著他们摆阵。大卫既摆阵攻击亚兰人，亚兰人就与他打仗。",
"18 亚兰人在以色列人面前逃跑。大卫杀了亚兰七千辆战车的人，四万步兵，又杀了亚兰的将军朔法。",
"",
"——【历代志上 19】",
],
[
"13 And he declared unto you his covenant, which he commanded you to perform, even ten commandments; and he wrote them upon two tables of stone.",
"14 And the LORD commanded me at that time to teach you statutes and judgments, that ye might do them in the land whither ye go over to possess it.",
"15 Take ye therefore good heed unto yourselves; for ye saw no manner of similitude on the day that the LORD spake unto you in Horeb out of the midst of the fire:",
"16 Lest ye corrupt yourselves, and make you a graven image, the similitude of any figure, the likeness of male or female,",
"17 The likeness of any beast that is on the earth, the likeness of any winged fowl that flieth in the air,",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 4】",
"",
"13 他将所吩咐你们当守的约指示你们，就是十条诫，并将这诫写在两块石版上。",
"14 那时耶和华又吩咐我将律例典章教训你们，使你们在所要过去得为业的地上遵行。」",
"15 所以，你们要分外谨慎；因为耶和华在何烈山、从火中对你们说话的那日，你们没有看见什么形像。",
"16 惟恐你们败坏自己，雕刻偶像，彷彿什么男像女像，",
"17 或地上走兽的像，或空中飞鸟的像，",
"",
"——【申命记 4】",
],
];
