var bible31_global=[
[
"1 Paul, and Silvanus, and Timotheus, unto the church of the Thessalonians which is in God the Father and in the Lord Jesus Christ: Grace be unto you, and peace, from God our Father, and the Lord Jesus Christ.",
"2 We give thanks to God always for you all, making mention of you in our prayers;",
"3 Remembering without ceasing your work of faith, and labour of love, and patience of hope in our Lord Jesus Christ, in the sight of God and our Father;",
"4 Knowing, brethren beloved, your election of God.",
"5 For our gospel came not unto you in word only, but also in power, and in the Holy Ghost, and in much assurance; as ye know what manner of men we were among you for your sake.",
"6 And ye became followers of us, and of the Lord, having received the word in much affliction, with joy of the Holy Ghost:",
"",
"——【The First Epistle of Paul the Apostle to the Thessalonians 1】",
"",
"1 保罗、西拉、提摩太写信给帖撒罗尼迦在父　神和主耶稣基督里的教会。愿恩惠、平安归与你们！",
"2 我们为你们众人常常感谢　神，祷告的时候提到你们，",
"3 在　神我们的父面前，不住的记念你们因信心所做的工夫，因爱心所受的劳苦，因盼望我们主耶稣基督所存的忍耐。",
"4 被　神所爱的弟兄啊，我知道你们是蒙拣选的；",
"5 因为我们的福音传到你们那里，不独在乎言语，也在乎权能和圣灵，并充足的信心，正如你们知道、我们在你们那里，为你们的缘故是怎样为人。",
"6 并且你们在大难之中，蒙了圣灵所赐的喜乐，领受真道就效法我们，也效法了主；",
"",
"——【帖撒罗尼迦前书 1】",
],
[
"1 How long wilt thou forget me, O LORD? for ever? how long wilt thou hide thy face from me?",
"2 How long shall I take counsel in my soul, having sorrow in my heart daily? how long shall mine enemy be exalted over me?",
"3 Consider and hear me, O LORD my God: lighten mine eyes, lest I sleep the sleep of death;",
"4 Lest mine enemy say, I have prevailed against him; and those that trouble me rejoice when I am moved.",
"",
"——【The Book of Psalms 13】",
"",
"1 （大卫的诗，交与伶长。）耶和华啊，你忘记我要到几时呢？要到永远吗？你掩面不顾我要到几时呢？",
"2 我心里筹算，终日愁苦，要到几时呢？我的仇敌升高压制我，要到几时呢？",
"3 耶和华─我的　神啊，求你看顾我，应允我！使我眼目光明，免得我沉睡至死；",
"4 免得我的仇敌说：我胜了他；免得我的敌人在我摇动的时候喜乐。",
"",
"——【诗篇 13】",
],
[
"16 Though he heap up silver as the dust, and prepare raiment as the clay;",
"17 He may prepare it, but the just shall put it on, and the innocent shall divide the silver.",
"",
"——【The Book of Job 27】",
"",
"16 他虽积蓄银子如尘沙，预备衣服如泥土；",
"17 他只管预备，义人却要穿上；他的银子，无辜的人要分取。",
"",
"——【约伯记 27】",
],
[
"1 In thee, O LORD, do I put my trust: let me never be put to confusion.",
"2 Deliver me in thy righteousness, and cause me to escape: incline thine ear unto me, and save me.",
"3 Be thou my strong habitation, whereunto I may continually resort: thou hast given commandment to save me; for thou art my rock and my fortress.",
"4 Deliver me, O my God, out of the hand of the wicked, out of the hand of the unrighteous and cruel man.",
"5 For thou art my hope, O Lord GOD: thou art my trust from my youth.",
"",
"——【The Book of Psalms 71】",
"",
"1 耶和华啊，我投靠你；求你叫我永不羞愧！",
"2 求你凭你的公义搭救我，救拔我；侧耳听我，拯救我！",
"3 求你作我常住的磐石；你已经命定要救我，因为你是我的岩石，我的山寨。",
"4 我的　神啊，求你救我脱离恶人的手，脱离不义和残暴之人的手。",
"5 主─耶和华啊，你是我所盼望的；从我年幼，你是我所倚靠的。",
"",
"——【诗篇 71】",
],
[
"22 Moreover the LORD spake unto Moses, saying,",
"23 Take thou also unto thee principal spices, of pure myrrh five hundred shekels, and of sweet cinnamon half so much, even two hundred and fifty shekels, and of sweet calamus two hundred and fifty shekels,",
"24 And of cassia five hundred shekels, after the shekel of the sanctuary, and of oil olive an hin:",
"25 And thou shalt make it an oil of holy ointment, an ointment compound after the art of the apothecary: it shall be an holy anointing oil.",
"",
"——【The Second Book of Moses: Called Exodus 30】",
"",
"22 耶和华晓谕摩西说：",
"23 「你要取上品的香料，就是流质的没药五百舍客勒，香肉桂一半，就是二百五十舍客勒，菖蒲二百五十舍客勒，",
"24 桂皮五百舍客勒，都按着圣所的平，又取橄榄油一欣，",
"25 按做香之法调和做成圣膏油。",
"",
"——【出埃及记 30】",
],
[
"25 And all the women that were wise hearted did spin with their hands, and brought that which they had spun, both of blue, and of purple, and of scarlet, and of fine linen.",
"26 And all the women whose heart stirred them up in wisdom spun goats' hair.",
"27 And the rulers brought onyx stones, and stones to be set, for the ephod, and for the breastplate;",
"28 And spice, and oil for the light, and for the anointing oil, and for the sweet incense.",
"29 The children of Israel brought a willing offering unto the LORD, every man and woman, whose heart made them willing to bring for all manner of work, which the LORD had commanded to be made by the hand of Moses.",
"30 And Moses said unto the children of Israel, See, the LORD hath called by name Bezaleel the son of Uri, the son of Hur, of the tribe of Judah;",
"",
"——【The Second Book of Moses: Called Exodus 35】",
"",
"25 凡心中有智慧的妇女亲手纺线，把所纺的蓝色、紫色、朱红色线，和细麻都拿了来。",
"26 凡有智慧、心里受感的妇女就纺山羊毛。",
"27 众官长把红玛瑙和别样的宝石，可以镶嵌在以弗得与胸牌上的，都拿了来；",
"28 又拿香料做香，拿油点灯，做膏油。",
"29 以色列人，无论男女，凡甘心乐意献礼物给耶和华的，都将礼物拿来，做耶和华借摩西所吩咐的一切工。",
"30 摩西对以色列人说：「犹大支派中，户珥的孙子、乌利的儿子比撒列，耶和华已经题他的名召他，",
"",
"——【出埃及记 35】",
],
[
"8 O Lord, what shall I say, when Israel turneth their backs before their enemies!",
"9 For the Canaanites and all the inhabitants of the land shall hear of it, and shall environ us round, and cut off our name from the earth: and what wilt thou do unto thy great name?",
"",
"——【The Book of Joshua 7】",
"",
"8 主啊，以色列人既在仇敌面前转背逃跑，我还有什么可说的呢？",
"9 迦南人和这地一切的居民听见了就必围困我们，将我们的名从地上除灭。那时你为你的大名要怎样行呢？」",
"",
"——【约书亚记 7】",
],
[
"16 Not now as a servant, but above a servant, a brother beloved, specially to me, but how much more unto thee, both in the flesh, and in the Lord?",
"17 If thou count me therefore a partner, receive him as myself.",
"18 If he hath wronged thee, or oweth thee ought, put that on mine account;",
"",
"——【The Epistle of Paul the Apostle to Philemon 1】",
"",
"16 不再是奴仆，乃是高过奴仆，是亲爱的兄弟。在我实在是如此，何况在你呢！这也不拘是按肉体说，是按主说，",
"17 你若以我为同伴，就收纳他，如同收纳我一样。",
"18 他若亏负你，或欠你什么，都归在我的帐上，",
"",
"——【腓利门书 1】",
],
[
"19 Then the magicians said unto Pharaoh, This is the finger of God: and Pharaoh's heart was hardened, and he hearkened not unto them; as the LORD had said.",
"20 And the LORD said unto Moses, Rise up early in the morning, and stand before Pharaoh; lo, he cometh forth to the water; and say unto him, Thus saith the LORD, Let my people go, that they may serve me.",
"21 Else, if thou wilt not let my people go, behold, I will send swarms of flies upon thee, and upon thy servants, and upon thy people, and into thy houses: and the houses of the Egyptians shall be full of swarms of flies, and also the ground whereon they are.",
"",
"——【The Second Book of Moses: Called Exodus 8】",
"",
"19 行法术的就对法老说：「这是　神的手段。」法老心里刚硬，不肯听摩西、亚伦，正如耶和华所说的。",
"20 耶和华对摩西说：「你清早起来，法老来到水边，你站在他面前，对他说：耶和华这样说：容我的百姓去，好事奉我。",
"21 你若不容我的百姓去，我要叫成群的苍蝇到你和你臣仆并你百姓的身上，进你的房屋，并且埃及人的房屋和他们所住的地都要满了成群的苍蝇。",
"",
"——【出埃及记 8】",
],
[
"1 I will sing of mercy and judgment: unto thee, O LORD, will I sing.",
"2 I will behave myself wisely in a perfect way. O when wilt thou come unto me? I will walk within my house with a perfect heart.",
"3 I will set no wicked thing before mine eyes: I hate the work of them that turn aside; it shall not cleave to me.",
"4 A froward heart shall depart from me: I will not know a wicked person.",
"",
"——【The Book of Psalms 101】",
"",
"1 （大卫的诗）。我要歌唱慈爱和公平；耶和华啊，我要向你歌颂！",
"2 我要用智慧行完全的道。你几时到我这里来呢？我要存完全的心行在我家中。",
"3 邪僻的事，我都不摆在我眼前；悖逆人所做的事，我甚恨恶，不容沾在我身上。",
"4 弯曲的心思，我必远离；一切的恶人（或译：恶事），我不认识。",
"",
"——【诗篇 101】",
],
[
"1 And the word of the LORD came unto me, saying,",
"2 Son of man, prophesy against the shepherds of Israel, prophesy, and say unto them, Thus saith the Lord GOD unto the shepherds; Woe be to the shepherds of Israel that do feed themselves! should not the shepherds feed the flocks?",
"",
"——【The Book of the Prophet Ezekiel 34】",
"",
"1 耶和华的话临到我说：",
"2 「人子啊，你要向以色列的牧人发预言，攻击他们，说，主耶和华如此说：祸哉！以色列的牧人只知牧养自己。牧人岂不当牧养群羊吗？",
"",
"——【以西结书 34】",
],
[
"21 If I have lifted up my hand against the fatherless, when I saw my help in the gate:",
"22 Then let mine arm fall from my shoulder blade, and mine arm be broken from the bone.",
"23 For destruction from God was a terror to me, and by reason of his highness I could not endure.",
"24 If I have made gold my hope, or have said to the fine gold, Thou art my confidence;",
"",
"——【The Book of Job 31】",
"",
"21 我若在城门口见有帮助我的，举手攻击孤儿；",
"22 情愿我的肩头从缺盆骨脱落，我的膀臂从羊矢骨折断。",
"23 因　神降的灾祸使我恐惧；因他的威严，我不能妄为。",
"24 我若以黄金为指望，对精金说：你是我的倚靠；",
"",
"——【约伯记 31】",
],
[
"1 Jotham was twenty and five years old when he began to reign, and he reigned sixteen years in Jerusalem. His mother's name also was Jerushah, the daughter of Zadok.",
"2 And he did that which was right in the sight of the LORD, according to all that his father Uzziah did: howbeit he entered not into the temple of the LORD. And the people did yet corruptly.",
"3 He built the high gate of the house of the LORD, and on the wall of Ophel he built much.",
"4 Moreover he built cities in the mountains of Judah, and in the forests he built castles and towers.",
"5 He fought also with the king of the Ammonites, and prevailed against them. And the children of Ammon gave him the same year an hundred talents of silver, and ten thousand measures of wheat, and ten thousand of barley. So much did the children of Ammon pay unto him, both the second year, and the third.",
"",
"——【The Second Book of the Chronicles 27】",
"",
"1 约坦登基的时候年二十五岁，在耶路撒冷作王十六年，他母亲名叫耶路沙，是撒督的女儿。",
"2 约坦行耶和华眼中看为正的事，效法他父乌西雅一切所行的，只是不入耶和华的殿。百姓还行邪僻的事。",
"3 约坦建立耶和华殿的上门，在俄斐勒城上多有建造，",
"4 又在犹大山地建造城邑，在树林中建筑营寨和高楼。",
"5 约坦与亚扪人的王打仗胜了他们，当年他们进贡银一百他连得，小麦一万歌珥，大麦一万歌珥；第二年、第三年也是这样。",
"",
"——【历代志下 27】",
],
[
"6 Now, brethren, if I come unto you speaking with tongues, what shall I profit you, except I shall speak to you either by revelation, or by knowledge, or by prophesying, or by doctrine?",
"7 And even things without life giving sound, whether pipe or harp, except they give a distinction in the sounds, how shall it be known what is piped or harped?",
"8 For if the trumpet give an uncertain sound, who shall prepare himself to the battle?",
"9 So likewise ye, except ye utter by the tongue words easy to be understood, how shall it be known what is spoken? for ye shall speak into the air.",
"10 There are, it may be, so many kinds of voices in the world, and none of them is without signification.",
"",
"——【The First Epistle of Paul the Apostle to the Corinthians 14】",
"",
"6 弟兄们，我到你们那里去，若只说方言，不用启示，或知识，或预言，或教训，给你们讲解，我与你们有什么益处呢？",
"7 就是那有声无气的物，或箫，或琴，若发出来的声音没有分别，怎能知道所吹所弹的是什么呢？",
"8 若吹无定的号声，谁能预备打仗呢？",
"9 你们也是如此。舌头若不说容易明白的话，怎能知道所说的是什么呢？这就是向空说话了。",
"10 世上的声音，或者甚多，却没有一样是无意思的。",
"",
"——【哥林多前书 14】",
],
[
"10 Thus saith the LORD; Again there shall be heard in this place, which ye say shall be desolate without man and without beast, even in the cities of Judah, and in the streets of Jerusalem, that are desolate, without man, and without inhabitant, and without beast,",
"11 The voice of joy, and the voice of gladness, the voice of the bridegroom, and the voice of the bride, the voice of them that shall say, Praise the LORD of hosts: for the LORD is good; for his mercy endureth for ever: and of them that shall bring the sacrifice of praise into the house of the LORD. For I will cause to return the captivity of the land, as at the first, saith the LORD.",
"12 Thus saith the LORD of hosts; Again in this place, which is desolate without man and without beast, and in all the cities thereof, shall be an habitation of shepherds causing their flocks to lie down.",
"13 In the cities of the mountains, in the cities of the vale, and in the cities of the south, and in the land of Benjamin, and in the places about Jerusalem, and in the cities of Judah, shall the flocks pass again under the hands of him that telleth them, saith the LORD.",
"14 Behold, the days come, saith the LORD, that I will perform that good thing which I have promised unto the house of Israel and to the house of Judah.",
"",
"——【The Book of the Prophet Jeremiah 33】",
"",
"10 耶和华如此说：「你们论这地方，说是荒废无人民无牲畜之地，但在这荒凉无人民无牲畜的犹大城邑和耶路撒冷的街上，",
"11 必再听见有欢喜和快乐的声音、新郎和新妇的声音，并听见有人说：要称谢万军之耶和华，因耶和华本为善；他的慈爱永远长存！又有奉感谢祭到耶和华殿中之人的声音；因为我必使这地被掳的人归回，和起初一样。这是耶和华说的。」",
"12 万军之耶和华如此说：「在这荒废无人民无牲畜之地，并其中所有的城邑，必再有牧人的住处；他们要使羊群躺卧在那里。",
"13 在山地的城邑、高原的城邑、南地的城邑、便雅悯地、耶路撒冷四围的各处，和犹大的城邑必再有羊群从数点的人手下经过。这是耶和华说的。」",
"14 耶和华说：「日子将到，我应许以色列家和犹大家的恩言必然成就。",
"",
"——【耶利米书 33】",
],
[
"13 And the high places that were before Jerusalem, which were on the right hand of the mount of corruption, which Solomon the king of Israel had builded for Ashtoreth the abomination of the Zidonians, and for Chemosh the abomination of the Moabites, and for Milcom the abomination of the children of Ammon, did the king defile.",
"14 And he brake in pieces the images, and cut down the groves, and filled their places with the bones of men.",
"",
"——【The Second Book of the Kings 23】",
"",
"13 从前以色列王所罗门在耶路撒冷前、邪僻山右边为西顿人可憎的神亚斯她录、摩押人可憎的神基抹、亚扪人可憎的神米勒公所筑的邱坛，王都污秽了，",
"14 又打碎柱像，砍下木偶，将人的骨头充满了那地方。",
"",
"——【列王记下 23】",
],
[
"15 Henceforth I call you not servants; for the servant knoweth not what his lord doeth: but I have called you friends; for all things that I have heard of my Father I have made known unto you.",
"16 Ye have not chosen me, but I have chosen you, and ordained you, that ye should go and bring forth fruit, and that your fruit should remain: that whatsoever ye shall ask of the Father in my name, he may give it you.",
"17 These things I command you, that ye love one another.",
"18 If the world hate you, ye know that it hated me before it hated you.",
"19 If ye were of the world, the world would love his own: but because ye are not of the world, but I have chosen you out of the world, therefore the world hateth you.",
"20 Remember the word that I said unto you, The servant is not greater than his lord. If they have persecuted me, they will also persecute you; if they have kept my saying, they will keep yours also.",
"",
"——【The Gospel According to Saint John 15】",
"",
"15 以后我不再称你们为仆人，因仆人不知道主人所做的事。我乃称你们为朋友；因我从我父所听见的，已经都告诉你们了。",
"16 不是你们拣选了我，是我拣选了你们，并且分派你们去结果子，叫你们的果子常存，使你们奉我的名，无论向父求什么，他就赐给你们。",
"17 我这样吩咐你们，是要叫你们彼此相爱。",
"18 世人若恨你们，你们知道（或作：该知道），恨你们以先已经恨我了。",
"19 你们若属世界，世界必爱属自己的；只因你们不属世界，乃是我从世界中拣选了你们，所以世界就恨你们。",
"20 你们要记念我从前对你们所说的话：仆人不能大于主人。他们若逼迫了我，也要逼迫你们；若遵守了我的话，也要遵守你们的话。",
"",
"——【约翰福音 15】",
],
[
"1 And it came to pass in the sixth year, in the sixth month, in the fifth day of the month, as I sat in mine house, and the elders of Judah sat before me, that the hand of the Lord GOD fell there upon me.",
"2 Then I beheld, and lo a likeness as the appearance of fire: from the appearance of his loins even downward, fire; and from his loins even upward, as the appearance of brightness, as the colour of amber.",
"3 And he put forth the form of an hand, and took me by a lock of mine head; and the spirit lifted me up between the earth and the heaven, and brought me in the visions of God to Jerusalem, to the door of the inner gate that looketh toward the north; where was the seat of the image of jealousy, which provoketh to jealousy.",
"4 And, behold, the glory of the God of Israel was there, according to the vision that I saw in the plain.",
"5 Then said he unto me, Son of man, lift up thine eyes now the way toward the north. So I lifted up mine eyes the way toward the north, and behold northward at the gate of the altar this image of jealousy in the entry.",
"6 He said furthermore unto me, Son of man, seest thou what they do? even the great abominations that the house of Israel committeth here, that I should go far off from my sanctuary? but turn thee yet again, and thou shalt see greater abominations.",
"",
"——【The Book of the Prophet Ezekiel 8】",
"",
"1 第六年六月初五日，我坐在家中；犹大的众长老坐在我面前。在那里主耶和华的灵（原文是手）降在我身上。",
"2 我观看，见有形像彷彿火的形状，从他腰以下的形状有火，从他腰以上有光辉的形状，彷彿光耀的精金。",
"3 他伸出彷彿一只手的样式，抓住我的一绺头发，灵就将我举到天地中间，在　神的异象中，带我到耶路撒冷朝北的内院门口，在那里有触动主怒偶像的坐位，就是惹动忌邪的。",
"4 谁知，在那里有以色列　神的荣耀，形状与我在平原所见的一样。",
"5 　神对我说：「人子啊，你举目向北观看。」我就举目向北观看，见祭坛门的北边，在门口有这惹忌邪的偶像；",
"6 又对我说：「人子啊，以色列家所行的，就是在此行这大可憎的事，使我远离我的圣所，你看见了吗？你还要看见另有大可憎的事。」",
"",
"——【以西结书 8】",
],
[
"8 For bodily exercise profiteth little: but godliness is profitable unto all things, having promise of the life that now is, and of that which is to come.",
"9 This is a faithful saying and worthy of all acceptation.",
"10 For therefore we both labour and suffer reproach, because we trust in the living God, who is the Saviour of all men, specially of those that believe.",
"11 These things command and teach.",
"12 Let no man despise thy youth; but be thou an example of the believers, in word, in conversation, in charity, in spirit, in faith, in purity.",
"13 Till I come, give attendance to reading, to exhortation, to doctrine.",
"",
"——【The First Epistle of Paul the Apostle to Timothy 4】",
"",
"8 操练身体，益处还少；惟独敬虔，凡事都有益处，因有今生和来生的应许。",
"9 这话是可信的，是十分可佩服的。",
"10 我们劳苦努力，正是为此，因我们的指望在乎永生的　神；他是万人的救主，更是信徒的救主。",
"11 这些事，你要吩咐人，也要教导人。",
"12 不可叫人小看你年轻，总要在言语、行为、爱心、信心、清洁上，都作信徒的榜样。",
"13 你要以宣读、劝勉、教导为念，直等到我来。",
"",
"——【提摩太前书 4】",
],
[
"13 The slothful man saith, There is a lion without, I shall be slain in the streets.",
"14 The mouth of strange women is a deep pit: he that is abhorred of the LORD shall fall therein.",
"15 Foolishness is bound in the heart of a child; but the rod of correction shall drive it far from him.",
"16 He that oppresseth the poor to increase his riches, and he that giveth to the rich, shall surely come to want.",
"",
"——【The Proverbs 22】",
"",
"13 懒惰人说：外头有狮子；我在街上就必被杀。",
"14 淫妇的口为深坑；耶和华所憎恶的，必陷在其中。",
"15 愚蒙迷住孩童的心，用管教的杖可以远远赶除。",
"16 欺压贫穷为要利己的，并送礼与富户的，都必缺乏。",
"",
"——【箴言 22】",
],
[
"5 Then the devil taketh him up into the holy city, and setteth him on a pinnacle of the temple,",
"6 And saith unto him, If thou be the Son of God, cast thyself down: for it is written, He shall give his angels charge concerning thee: and in their hands they shall bear thee up, lest at any time thou dash thy foot against a stone.",
"7 Jesus said unto him, It is written again, Thou shalt not tempt the Lord thy God.",
"8 Again, the devil taketh him up into an exceeding high mountain, and sheweth him all the kingdoms of the world, and the glory of them;",
"9 And saith unto him, All these things will I give thee, if thou wilt fall down and worship me.",
"10 Then saith Jesus unto him, Get thee hence, Satan: for it is written, Thou shalt worship the Lord thy God, and him only shalt thou serve.",
"",
"——【The Gospel According to Saint Matthew 4】",
"",
"5 魔鬼就带他进了圣城，叫他站在殿顶（顶：原文是翅）上，",
"6 对他说：「你若是　神的儿子，可以跳下去，因为经上记着说：主要为你吩咐他的使者用手托着你，免得你的脚碰在石头上。」",
"7 耶稣对他说：「经上又记着说：『不可试探主─你的　神。』」",
"8 魔鬼又带他上了一座最高的山，将世上的万国与万国的荣华都指给他看，",
"9 对他说：「你若俯伏拜我，我就把这一切都赐给你。」",
"10 耶稣说：「撒但（撒但就是抵挡的意思，乃魔鬼的别名），退去吧！因为经上记着说：当拜主你的　神，单要事奉他。」",
"",
"——【马太福音 4】",
],
[
"6 Thy throne, O God, is for ever and ever: the sceptre of thy kingdom is a right sceptre.",
"7 Thou lovest righteousness, and hatest wickedness: therefore God, thy God, hath anointed thee with the oil of gladness above thy fellows.",
"8 All thy garments smell of myrrh, and aloes, and cassia, out of the ivory palaces, whereby they have made thee glad.",
"9 Kings' daughters were among thy honourable women: upon thy right hand did stand the queen in gold of Ophir.",
"",
"——【The Book of Psalms 45】",
"",
"6 　神啊，你的宝座是永永远远的；你的国权是正直的。",
"7 你喜爱公义，恨恶罪恶；所以　神─就是你的　神─用喜乐油膏你，胜过膏你的同伴。",
"8 你的衣服都有没药、沉香、肉桂的香气；象牙宫中有丝弦乐器的声音使你欢喜。",
"9 有君王的女儿在你尊贵妇女之中；王后佩戴俄斐金饰站在你右边。",
"",
"——【诗篇 45】",
],
[
"1 Behold, the LORD'S hand is not shortened, that it cannot save; neither his ear heavy, that it cannot hear:",
"2 But your iniquities have separated between you and your God, and your sins have hid his face from you, that he will not hear.",
"3 For your hands are defiled with blood, and your fingers with iniquity; your lips have spoken lies, your tongue hath muttered perverseness.",
"4 None calleth for justice, nor any pleadeth for truth: they trust in vanity, and speak lies; they conceive mischief, and bring forth iniquity.",
"5 They hatch cockatrice' eggs, and weave the spider's web: he that eateth of their eggs dieth, and that which is crushed breaketh out into a viper.",
"",
"——【The Book of the Prophet Isaiah 59】",
"",
"1 耶和华的膀臂并非缩短，不能拯救，耳朵并非发沉，不能听见，",
"2 但你们的罪孽使你们与　神隔绝；你们的罪恶使他掩面不听你们。",
"3 因你们的手被血沾染，你们的指头被罪孽沾污，你们的嘴唇说谎言，你们的舌头出恶语。",
"4 无一人按公义告状，无一人凭诚实辨白；都倚靠虚妄，说谎言。所怀的是毒害；所生的是罪孽。",
"5 他们抱毒蛇蛋，结蜘蛛网；人吃这蛋必死。这蛋被踏，必出蝮蛇。",
"",
"——【以赛亚书 59】",
],
[
"5 For this cause, when I could no longer forbear, I sent to know your faith, lest by some means the tempter have tempted you, and our labour be in vain.",
"6 But now when Timotheus came from you unto us, and brought us good tidings of your faith and charity, and that ye have good remembrance of us always, desiring greatly to see us, as we also to see you:",
"",
"——【The First Epistle of Paul the Apostle to the Thessalonians 3】",
"",
"5 为此，我既不能再忍，就打发人去，要晓得你们的信心如何，恐怕那诱惑人的到底诱惑了你们，叫我们的劳苦归于徒然。",
"6 但提摩太刚才从你们那里回来，将你们信心和爱心的好消息报给我们，又说你们常常记念我们，切切的想见我们，如同我们想见你们一样。",
"",
"——【帖撒罗尼迦前书 3】",
],
[
"15 And the LORD said unto him, Go, return on thy way to the wilderness of Damascus: and when thou comest, anoint Hazael to be king over Syria:",
"16 And Jehu the son of Nimshi shalt thou anoint to be king over Israel: and Elisha the son of Shaphat of Abel–meholah shalt thou anoint to be prophet in thy room.",
"17 And it shall come to pass, that him that escapeth the sword of Hazael shall Jehu slay: and him that escapeth from the sword of Jehu shall Elisha slay.",
"18 Yet I have left me seven thousand in Israel, all the knees which have not bowed unto Baal, and every mouth which hath not kissed him.",
"",
"——【The First Book of the Kings 19】",
"",
"15 耶和华对他说：「你回去，从旷野往大马士革去。到了那里，就要膏哈薛作亚兰王，",
"16 又膏宁示的孙子耶户作以色列王，并膏亚伯‧米何拉人沙法的儿子以利沙作先知接续你。",
"17 将来躲避哈薛之刀的，必被耶户所杀；躲避耶户之刀的，必被以利沙所杀。",
"18 但我在以色列人中为自己留下七千人，是未曾向巴力屈膝的，未曾与巴力亲嘴的。」",
"",
"——【列王记上 19】",
],
[
"16 O Lord, by these things men live, and in all these things is the life of my spirit: so wilt thou recover me, and make me to live.",
"17 Behold, for peace I had great bitterness: but thou hast in love to my soul delivered it from the pit of corruption: for thou hast cast all my sins behind thy back.",
"18 For the grave cannot praise thee, death can not celebrate thee: they that go down into the pit cannot hope for thy truth.",
"19 The living, the living, he shall praise thee, as I do this day: the father to the children shall make known thy truth.",
"",
"——【The Book of the Prophet Isaiah 38】",
"",
"16 主啊，人得存活乃在乎此。我灵存活也全在此。所以求你使我痊癒，仍然存活。",
"17 看哪，我受大苦，本为使我得平安；你因爱我的灵魂（或译：生命）便救我脱离败坏的坑，因为你将我一切的罪扔在你的背后。",
"18 原来，阴间不能称谢你，死亡不能颂扬你；下坑的人不能盼望你的诚实。",
"19 只有活人，活人必称谢你，像我今日称谢你一样。为父的，必使儿女知道你的诚实。",
"",
"——【以赛亚书 38】",
],
[
"9 Then shalt thou call, and the LORD shall answer; thou shalt cry, and he shall say, Here I am. If thou take away from the midst of thee the yoke, the putting forth of the finger, and speaking vanity;",
"10 And if thou draw out thy soul to the hungry, and satisfy the afflicted soul; then shall thy light rise in obscurity, and thy darkness be as the noonday:",
"",
"——【The Book of the Prophet Isaiah 58】",
"",
"9 那时你求告，耶和华必应允；你呼求，他必说：我在这里。你若从你中间除掉重轭和指摘人的指头，并发恶言的事，",
"10 你心若向饥饿的人发怜悯，使困苦的人得满足，你的光就必在黑暗中发现；你的幽暗必变如正午。",
"",
"——【以赛亚书 58】",
],
[
"8 Thus have we obeyed the voice of Jonadab the son of Rechab our father in all that he hath charged us, to drink no wine all our days, we, our wives, our sons, nor our daughters;",
"9 Nor to build houses for us to dwell in: neither have we vineyard, nor field, nor seed:",
"",
"——【The Book of the Prophet Jeremiah 35】",
"",
"8 凡我们先祖利甲的儿子约拿达所吩咐我们的话，我们都听从了。我们和我们的妻子儿女一生的年日都不喝酒，",
"9 也不盖房居住，也没有葡萄园、田地，和种子，",
"",
"——【耶利米书 35】",
],
[
"2 And David took the crown of their king from off his head, and found it to weigh a talent of gold, and there were precious stones in it; and it was set upon David's head: and he brought also exceeding much spoil out of the city.",
"3 And he brought out the people that were in it, and cut them with saws, and with harrows of iron, and with axes. Even so dealt David with all the cities of the children of Ammon. And David and all the people returned to Jerusalem.",
"4 And it came to pass after this, that there arose war at Gezer with the Philistines; at which time Sibbechai the Hushathite slew Sippai, that was of the children of the giant: and they were subdued.",
"5 And there was war again with the Philistines; and Elhanan the son of Jair slew Lahmi the brother of Goliath the Gittite, whose spear staff was like a weaver's beam.",
"6 And yet again there was war at Gath, where was a man of great stature, whose fingers and toes were four and twenty, six on each hand, and six on each foot: and he also was the son of the giant.",
"",
"——【The First Book of the Chronicles 20】",
"",
"2 大卫夺了亚扪人之王【王或作玛勒堪。玛勒堪即米勒公，是亚扪族之神名】所戴的金冠冕，其上的金子重一他连得，又嵌着宝石；人将这冠冕戴在大卫头上。大卫从城里夺了许多财物，",
"3 将城里的人拉出来，放在锯下，或铁耙下，或铁斧下【或作强他们用锯，或用打粮食的铁器，或用铁斧作工】，大卫待亚扪各城的居民都是如此。其后大卫和众军都回耶路撒冷去了。",
"4 后来，以色列人在基色与非利士人打仗。户沙人西比该杀了伟人的一个儿子细派，非利士人就被制伏了。",
"5 又与非利士人打仗。睚珥的儿子伊勒哈难杀了迦特人歌利亚的兄弟拉哈米；这人的枪杆粗如织布的机轴。",
"6 又在迦特打仗。那里有一个身量高大的人，手脚都是六指，共有二十四个指头，他也是伟人的儿子。",
"",
"——【历代志上 20】",
],
[
"26 And his host, and those that were numbered of them, were threescore and two thousand and seven hundred.",
"27 And those that encamp by him shall be the tribe of Asher: and the captain of the children of Asher shall be Pagiel the son of Ocran.",
"",
"——【The Fourth Book of Moses: Called Numbers 2】",
"",
"26 他军队被数的，共有六万二千七百名。",
"27 挨着他安营的是亚设支派。俄兰的儿子帕结作亚设人的首领。",
"",
"——【民数记 2】",
],
[
"4 And patience, experience; and experience, hope:",
"5 And hope maketh not ashamed; because the love of God is shed abroad in our hearts by the Holy Ghost which is given unto us.",
"6 For when we were yet without strength, in due time Christ died for the ungodly.",
"7 For scarcely for a righteous man will one die: yet peradventure for a good man some would even dare to die.",
"8 But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us.",
"9 Much more then, being now justified by his blood, we shall be saved from wrath through him.",
"",
"——【The Epistle of Paul the Apostle to the Romans 5】",
"",
"4 忍耐生老练，老练生盼望；",
"5 盼望不至于羞耻，因为所赐给我们的圣灵将　神的爱浇灌在我们心里。",
"6 因我们还软弱的时候，基督就按所定的日期为罪人死。",
"7 为义人死，是少有的；为仁人死、或者有敢做的。",
"8 惟有基督在我们还作罪人的时候为我们死，　神的爱就在此向我们显明了。",
"9 现在我们既靠着他的血称义，就更要藉着他免去　神的忿怒。",
"",
"——【罗马书 5】",
],
];
