var bible31_global=[
[
"17 Iron sharpeneth iron; so a man sharpeneth the countenance of his friend.",
"18 Whoso keepeth the fig tree shall eat the fruit thereof: so he that waiteth on his master shall be honoured.",
"19 As in water face answereth to face, so the heart of man to man.",
"",
"——【The Proverbs 27】",
"",
"17 铁磨铁，磨出刃来；朋友相感（原文是磨朋友的脸）也是如此。",
"18 看守无花果树的，必吃树上的果子；敬奉主人的，必得尊荣。",
"19 水中照脸，彼此相符；人与人，心也相对。",
"",
"——【箴言 27】",
],
[
"11 And now, my daughter, fear not; I will do to thee all that thou requirest: for all the city of my people doth know that thou art a virtuous woman.",
"12 And now it is true that I am thy near kinsman: howbeit there is a kinsman nearer than I.",
"13 Tarry this night, and it shall be in the morning, that if he will perform unto thee the part of a kinsman, well; let him do the kinsman's part: but if he will not do the part of a kinsman to thee, then will I do the part of a kinsman to thee, as the LORD liveth: lie down until the morning.",
"14 And she lay at his feet until the morning: and she rose up before one could know another. And he said, Let it not be known that a woman came into the floor.",
"15 Also he said, Bring the vail that thou hast upon thee, and hold it. And when she held it, he measured six measures of barley, and laid it on her: and she went into the city.",
"",
"——【The Book of Ruth 3】",
"",
"11 女儿啊，现在不要惧怕，凡你所说的，我必照着行；我本城的人都知道你是个贤德的女子。",
"12 我实在是你一个至近的亲属，只是还有一个人比我更近。",
"13 你今夜在这里住宿，明早他若肯为你尽亲属的本分，就由他吧！倘若不肯，我指着永生的耶和华起誓，我必为你尽了本分，你只管躺到天亮。」",
"14 路得便在他脚下躺到天快亮，人彼此不能辨认的时候就起来了。波阿斯说：「不可使人知道有女子到场上来」；",
"15 又对路得说：「打开你所披的外衣。」她打开了，波阿斯就撮了六簸箕大麦，帮她扛在肩上，她便进城去了。",
"",
"——【路得记 3】",
],
[
"7 But thou hast saved us from our enemies, and hast put them to shame that hated us.",
"8 In God we boast all the day long, and praise thy name for ever. Selah.",
"9 But thou hast cast off, and put us to shame; and goest not forth with our armies.",
"10 Thou makest us to turn back from the enemy: and they which hate us spoil for themselves.",
"11 Thou hast given us like sheep appointed for meat; and hast scattered us among the heathen.",
"12 Thou sellest thy people for nought, and dost not increase thy wealth by their price.",
"",
"——【The Book of Psalms 44】",
"",
"7 惟你救了我们脱离敌人，使恨我们的人羞愧。",
"8 我们终日因　神夸耀，还要永远称谢你的名。（细拉）",
"9 但如今你丢弃了我们，使我们受辱，不和我们的军兵同去。",
"10 你使我们向敌人转身退后；那恨我们的人任意抢夺。",
"11 你使我们当作快要被吃的羊，把我们分散在列邦中。",
"12 你卖了你的子民也不赚利，所得的价值并不加添你的资财。",
"",
"——【诗篇 44】",
],
[
"5 He shall recount his worthies: they shall stumble in their walk; they shall make haste to the wall thereof, and the defence shall be prepared.",
"6 The gates of the rivers shall be opened, and the palace shall be dissolved.",
"",
"——【Nahum 2】",
"",
"5 尼尼微王招聚他的贵冑；他们步行绊跌，速上城墙，预备挡牌。",
"6 河闸开放，宫殿冲没。",
"",
"——【那鸿书 2】",
],
[
"5 Although my house be not so with God; yet he hath made with me an everlasting covenant, ordered in all things, and sure: for this is all my salvation, and all my desire, although he make it not to grow.",
"6 But the sons of Belial shall be all of them as thorns thrust away, because they cannot be taken with hands:",
"7 But the man that shall touch them must be fenced with iron and the staff of a spear; and they shall be utterly burned with fire in the same place.",
"8 These be the names of the mighty men whom David had: The Tachmonite that sat in the seat, chief among the captains; the same was Adino the Eznite: he lift up his spear against eight hundred, whom he slew at one time.",
"9 And after him was Eleazar the son of Dodo the Ahohite, one of the three mighty men with David, when they defied the Philistines that were there gathered together to battle, and the men of Israel were gone away:",
"10 He arose, and smote the Philistines until his hand was weary, and his hand clave unto the sword: and the LORD wrought a great victory that day; and the people returned after him only to spoil.",
"",
"——【The Second Book of Samuel 23】",
"",
"5 我家在　神面前并非如此；　神却与我立永远的约。这约凡事坚稳，关乎我的一切救恩和我一切所想望的，他岂不为我成就吗？",
"6 但匪类都必像荆棘被丢弃；人不敢用手拿它；",
"7 拿它的人必带铁器和枪杆，终久它必被火焚烧。",
"8 大卫勇士的名字记在下面：他革扪人约设巴设，又称伊斯尼人亚底挪，他是军长的统领，一时击杀了八百人。",
"9 其次是亚合人朵多的儿子以利亚撒。从前非利士人聚集要打仗，以色列人迎着上去，有跟随大卫的三个勇士向非利士人骂阵，其中有以利亚撒。",
"10 他起来击杀非利士人，直到手臂疲乏，手黏住刀把。那日耶和华使以色列人大获全胜；众民在以利亚撒后头专夺财物。",
"",
"——【撒母耳记下 23】",
],
[
"18 And he took up his parable, and said, Rise up, Balak, and hear; hearken unto me, thou son of Zippor:",
"19 God is not a man, that he should lie; neither the son of man, that he should repent: hath he said, and shall he not do it? or hath he spoken, and shall he not make it good?",
"20 Behold, I have received commandment to bless: and he hath blessed; and I cannot reverse it.",
"",
"——【The Fourth Book of Moses: Called Numbers 23】",
"",
"18 巴兰就题诗歌说：巴勒，你起来听；西拨的儿子，你听我言。",
"19 　神非人，必不致说谎，也非人子，必不致后悔。他说话岂不照着行呢？他发言岂不要成就呢？",
"20 我奉命祝福；　神也曾赐福，此事我不能翻转。",
"",
"——【民数记 23】",
],
[
"7 And of the angels he saith, Who maketh his angels spirits, and his ministers a flame of fire.",
"8 But unto the Son he saith, Thy throne, O God, is for ever and ever: a sceptre of righteousness is the sceptre of thy kingdom.",
"9 Thou hast loved righteousness, and hated iniquity; therefore God, even thy God, hath anointed thee with the oil of gladness above thy fellows.",
"10 And, Thou, Lord, in the beginning hast laid the foundation of the earth; and the heavens are the works of thine hands:",
"",
"——【The Epistle of Paul the Apostle to the Hebrews 1】",
"",
"7 论到使者，又说：　神以风为使者，以火焰为仆役；",
"8 论到子却说：　神啊，你的宝座是永永远远的；你的国权是正直的。",
"9 你喜爱公义，恨恶罪恶；所以　神，就是你的　神，用喜乐油膏你，胜过膏你的同伴；",
"10 又说：主啊，你起初立了地的根基；天也是你手所造的。",
"",
"——【希伯来书 1】",
],
[
"17 But the bullock, and his hide, his flesh, and his dung, he burnt with fire without the camp; as the LORD commanded Moses.",
"18 And he brought the ram for the burnt offering: and Aaron and his sons laid their hands upon the head of the ram.",
"",
"——【The Third Book of Moses: Called Leviticus 8】",
"",
"17 惟有公牛，连皮带肉并粪，用火烧在营外，都是照耶和华所吩咐摩西的。",
"18 他奉上燔祭的公绵羊；亚伦和他儿子按手在羊的头上，",
"",
"——【利未记 8】",
],
[
"1 And Moses called all Israel, and said unto them, Hear, O Israel, the statutes and judgments which I speak in your ears this day, that ye may learn them, and keep, and do them.",
"2 The LORD our God made a covenant with us in Horeb.",
"3 The LORD made not this covenant with our fathers, but with us, even us, who are all of us here alive this day.",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 5】",
"",
"1 摩西将以色列众人召了来，对他们说：「以色列人哪，我今日晓谕你们的律例典章，你们要听，可以学习，谨守遵行。",
"2 耶和华─我们的　神在何烈山与我们立约。",
"3 这约不是与我们列祖立的，乃是与我们今日在这里存活之人立的。",
"",
"——【申命记 5】",
],
[
"17 But the other of love, knowing that I am set for the defence of the gospel.",
"18 What then? notwithstanding, every way, whether in pretence, or in truth, Christ is preached; and I therein do rejoice, yea, and will rejoice.",
"",
"——【The Epistle of Paul the Apostle to the Philippians 1】",
"",
"17 那一等传基督是出于结党，并不诚实，意思要加增我捆锁的苦楚。",
"18 这有何妨呢？或是假意，或是真心，无论怎样，基督究竟被传开了。为此，我就欢喜，并且还要欢喜；",
"",
"——【腓立比书 1】",
],
[
"5 Let the enemy persecute my soul, and take it; yea, let him tread down my life upon the earth, and lay mine honour in the dust. Selah.",
"6 Arise, O LORD, in thine anger, lift up thyself because of the rage of mine enemies: and awake for me to the judgment that thou hast commanded.",
"7 So shall the congregation of the people compass thee about: for their sakes therefore return thou on high.",
"",
"——【The Book of Psalms 7】",
"",
"5 就任凭仇敌追赶我，直到追上，将我的性命踏在地下，使我的荣耀归于灰尘。（细拉）",
"6 耶和华啊，求你在怒中起来，挺身而立，抵挡我敌人的暴怒！求你为我兴起！你已经命定施行审判！",
"7 愿众民的会环绕你！愿你从其上归于高位！",
"",
"——【诗篇 7】",
],
[
"1 Give ear to my words, O LORD, consider my meditation.",
"2 Hearken unto the voice of my cry, my King, and my God: for unto thee will I pray.",
"3 My voice shalt thou hear in the morning, O LORD; in the morning will I direct my prayer unto thee, and will look up.",
"4 For thou art not a God that hath pleasure in wickedness: neither shall evil dwell with thee.",
"",
"——【The Book of Psalms 5】",
"",
"1 （大卫的诗，交与伶长。用吹的乐器。）耶和华啊，求你留心听我的言语，顾念我的心思！",
"2 我的王我的　神啊，求你垂听我呼求的声音！因为我向你祈祷。",
"3 耶和华啊，早晨你必听我的声音；早晨我必向你陈明我的心意，并要警醒！",
"4 因为你不是喜悦恶事的　神，恶人不能与你同居。",
"",
"——【诗篇 5】",
],
[
"37 And I will take thee, and thou shalt reign according to all that thy soul desireth, and shalt be king over Israel.",
"38 And it shall be, if thou wilt hearken unto all that I command thee, and wilt walk in my ways, and do that is right in my sight, to keep my statutes and my commandments, as David my servant did; that I will be with thee, and build thee a sure house, as I built for David, and will give Israel unto thee.",
"39 And I will for this afflict the seed of David, but not for ever.",
"40 Solomon sought therefore to kill Jeroboam. And Jeroboam arose, and fled into Egypt, unto Shishak king of Egypt, and was in Egypt until the death of Solomon.",
"41 And the rest of the acts of Solomon, and all that he did, and his wisdom, are they not written in the book of the acts of Solomon?",
"",
"——【The First Book of the Kings 11】",
"",
"37 我必拣选你，使你照心里一切所愿的，作王治理以色列。",
"38 你若听从我一切所吩咐你的，遵行我的道，行我眼中看为正的事，谨守我的律例诫命，像我仆人大卫所行的，我就与你同在，为你立坚固的家，像我为大卫所立的一样，将以色列人赐给你。",
"39 我必因所罗门所行的使大卫后裔受患难，但不至于永远。』」",
"40 所罗门因此想要杀耶罗波安。耶罗波安却起身逃往埃及；到了埃及王示撒那里，就住在埃及，直到所罗门死了。",
"41 所罗门其余的事，凡他所行的和他的智慧都写在所罗门记上。",
"",
"——【列王记上 11】",
],
[
"1 After these things the word of the LORD came unto Abram in a vision, saying, Fear not, Abram: I am thy shield, and thy exceeding great reward.",
"2 And Abram said, Lord GOD, what wilt thou give me, seeing I go childless, and the steward of my house is this Eliezer of Damascus?",
"3 And Abram said, Behold, to me thou hast given no seed: and, lo, one born in my house is mine heir.",
"4 And, behold, the word of the LORD came unto him, saying, This shall not be thine heir; but he that shall come forth out of thine own bowels shall be thine heir.",
"5 And he brought him forth abroad, and said, Look now toward heaven, and tell the stars, if thou be able to number them: and he said unto him, So shall thy seed be.",
"6 And he believed in the LORD; and he counted it to him for righteousness.",
"",
"——【The First Book of Moses: Called Genesis 15】",
"",
"1 这事以后，耶和华在异象中有话对亚伯兰说：「亚伯兰，你不要惧怕！我是你的盾牌，必大大的赏赐你。」",
"2 亚伯兰说：「主耶和华啊，我既无子，你还赐我什么呢？并且要承受我家业的是大马士革人以利以谢。」",
"3 亚伯兰又说：「你没有给我儿子；那生在我家中的人就是我的后嗣。」",
"4 耶和华又有话对他说：「这人必不成为你的后嗣；你本身所生的才成为你的后嗣。」",
"5 于是领他走到外边，说：「你向天观看，数算众星，能数得过来吗？」又对他说：「你的后裔将要如此。」",
"6 亚伯兰信耶和华，耶和华就以此为他的义。",
"",
"——【创世记 15】",
],
[
"14 They have wandered as blind men in the streets, they have polluted themselves with blood, so that men could not touch their garments.",
"15 They cried unto them, Depart ye; it is unclean; depart, depart, touch not: when they fled away and wandered, they said among the heathen, They shall no more sojourn there.",
"16 The anger of the LORD hath divided them; he will no more regard them: they respected not the persons of the priests, they favoured not the elders.",
"17 As for us, our eyes as yet failed for our vain help: in our watching we have watched for a nation that could not save us.",
"",
"——【The Lamentations of Jeremiah 4】",
"",
"14 他们在街上如瞎子乱走，又被血玷污，以致人不能摸他们的衣服。",
"15 人向他们喊着说：！不洁净的，躲开，躲开！不要挨近我！他们逃走飘流的时候，列国中有人说：他们不可仍在这里寄居。",
"16 耶和华发怒，将他们分散，不再眷顾他们；人不重看祭司，也不厚待长老。",
"17 我们仰望人来帮助，以致眼目失明，还是枉然；我们所盼望的，竟盼望一个不能救人的国！",
"",
"——【耶利米哀歌 4】",
],
[
"1 Judge me, O God, and plead my cause against an ungodly nation: O deliver me from the deceitful and unjust man.",
"2 For thou art the God of my strength: why dost thou cast me off? why go I mourning because of the oppression of the enemy?",
"",
"——【The Book of Psalms 43】",
"",
"1 　神啊，求你伸我的冤，向不虔诚的国为我辨屈；求你救我脱离诡诈不义的人。",
"2 因为你是赐我力量的　神，为何丢弃我呢？我为何因仇敌的欺压时常哀痛呢？",
"",
"——【诗篇 43】",
],
[
"16 Or as an hidden untimely birth I had not been; as infants which never saw light.",
"17 There the wicked cease from troubling; and there the weary be at rest.",
"",
"——【The Book of Job 3】",
"",
"16 或像隐而未现、不到期而落的胎，归于无有，如同未见光的婴孩。",
"17 在那里恶人止息搅扰，困乏人得享安息，",
"",
"——【约伯记 3】",
],
[
"1 Thus saith the LORD, Where is the bill of your mother's divorcement, whom I have put away? or which of my creditors is it to whom I have sold you? Behold, for your iniquities have ye sold yourselves, and for your transgressions is your mother put away.",
"2 Wherefore, when I came, was there no man? when I called, was there none to answer? Is my hand shortened at all, that it cannot redeem? or have I no power to deliver? behold, at my rebuke I dry up the sea, I make the rivers a wilderness: their fish stinketh, because there is no water, and dieth for thirst.",
"3 I clothe the heavens with blackness, and I make sackcloth their covering.",
"",
"——【The Book of the Prophet Isaiah 50】",
"",
"1 耶和华如此说：我休你们的母亲，休书在哪里呢？我将你们卖给我哪一个债主呢？你们被卖，是因你们的罪孽；你们的母亲被休，是因你们的过犯。",
"2 我来的时候，为何无人等候呢？我呼唤的时候，为何无人答应呢？我的膀臂岂是缩短、不能救赎吗？我岂无拯救之力吗？看哪，我一斥责，海就干了；我使江河变为旷野；其中的鱼因无水腥臭，干渴而死。",
"3 我使诸天以黑暗为衣服，以麻布为遮盖。",
"",
"——【以赛亚书 50】",
],
[
"1 The fool hath said in his heart, There is no God. They are corrupt, they have done abominable works, there is none that doeth good.",
"2 The LORD looked down from heaven upon the children of men, to see if there were any that did understand, and seek God.",
"",
"——【The Book of Psalms 14】",
"",
"1 （大卫的诗，交与伶长。）愚顽人心里说：没有　神。他们都是邪恶，行了可憎恶的事；没有一个人行善。",
"2 耶和华从天上垂看世人，要看有明白的没有，有寻求　神的没有。",
"",
"——【诗篇 14】",
],
[
"17 And the men of Israel, beside Benjamin, were numbered four hundred thousand men that drew sword: all these were men of war.",
"18 And the children of Israel arose, and went up to the house of God, and asked counsel of God, and said, Which of us shall go up first to the battle against the children of Benjamin? And the LORD said, Judah shall go up first.",
"19 And the children of Israel rose up in the morning, and encamped against Gibeah.",
"20 And the men of Israel went out to battle against Benjamin; and the men of Israel put themselves in array to fight against them at Gibeah.",
"21 And the children of Benjamin came forth out of Gibeah, and destroyed down to the ground of the Israelites that day twenty and two thousand men.",
"22 And the people the men of Israel encouraged themselves, and set their battle again in array in the place where they put themselves in array the first day.",
"",
"——【The Book of Judges 20】",
"",
"17 便雅悯人之外，点出以色列人拿刀的，共有四十万，都是战士。",
"18 以色列人就起来，到伯特利去求问　神说：「我们中间谁当首先上去与便雅悯人争战呢？」耶和华说：「犹大当先上去。」",
"19 以色列人早晨起来，对着基比亚安营。",
"20 以色列人出来，要与便雅悯人打仗，就在基比亚前摆阵。",
"21 便雅悯人就从基比亚出来，当日杀死以色列人二万二千。",
"22 以色列人彼此奋勇，仍在头一日摆阵的地方又摆阵。",
"",
"——【士师记 20】",
],
[
"9 Keep therefore the words of this covenant, and do them, that ye may prosper in all that ye do.",
"10 Ye stand this day all of you before the LORD your God; your captains of your tribes, your elders, and your officers, with all the men of Israel,",
"11 Your little ones, your wives, and thy stranger that is in thy camp, from the hewer of thy wood unto the drawer of thy water:",
"12 That thou shouldest enter into covenant with the LORD thy God, and into his oath, which the LORD thy God maketh with thee this day:",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 29】",
"",
"9 所以你们要谨守遵行这约的话，好叫你们在一切所行的事上亨通。",
"10 「今日，你们的首领、族长（原文作支派）、长老、官长、以色列的男丁，你们的妻子儿女，和营中寄居的，以及为你们劈柴挑水的人，都站在耶和华─你们的　神面前，",
"11 并入上一节",
"12 为要你顺从耶和华─你　神今日与你所立的约，向你所起的誓。",
"",
"——【申命记 29】",
],
[
"2 The LORD is great in Zion; and he is high above all the people.",
"3 Let them praise thy great and terrible name; for it is holy.",
"4 The king's strength also loveth judgment; thou dost establish equity, thou executest judgment and righteousness in Jacob.",
"5 Exalt ye the LORD our God, and worship at his footstool; for he is holy.",
"",
"——【The Book of Psalms 99】",
"",
"2 耶和华在锡安为大；他超乎万民之上。",
"3 他们当称赞他大而可畏的名；他本为圣！",
"4 王有能力，喜爱公平，坚立公正，在雅各中施行公平和公义。",
"5 你们当尊崇耶和华─我们的　神，在他脚凳前下拜。他本为圣！",
"",
"——【诗篇 99】",
],
[
"9 And when they forgat the LORD their God, he sold them into the hand of Sisera, captain of the host of Hazor, and into the hand of the Philistines, and into the hand of the king of Moab, and they fought against them.",
"10 And they cried unto the LORD, and said, We have sinned, because we have forsaken the LORD, and have served Baalim and Ashtaroth: but now deliver us out of the hand of our enemies, and we will serve thee.",
"11 And the LORD sent Jerubbaal, and Bedan, and Jephthah, and Samuel, and delivered you out of the hand of your enemies on every side, and ye dwelled safe.",
"12 And when ye saw that Nahash the king of the children of Ammon came against you, ye said unto me, Nay; but a king shall reign over us: when the LORD your God was your king.",
"",
"——【The First Book of Samuel 12】",
"",
"9 他们却忘记耶和华─他们的　神，他就把他们付与夏琐将军西西拉的手里，和非利士人并摩押王的手里。于是这些人常来攻击他们。",
"10 他们就呼求耶和华说：『我们离弃耶和华，事奉巴力和亚斯她录，是有罪了。现在求你救我们脱离仇敌的手，我们必事奉你。』",
"11 耶和华就差遣耶路巴力、比但、耶弗他、撒母耳救你们脱离四围仇敌的手，你们才安然居住。",
"12 你们见亚扪人的王拿辖来攻击你们，就对我说：『我们定要一个王治理我们。』其实耶和华─你们的　神是你们的王。",
"",
"——【撒母耳记上 12】",
],
[
"1 Praise ye the LORD. Praise God in his sanctuary: praise him in the firmament of his power.",
"2 Praise him for his mighty acts: praise him according to his excellent greatness.",
"3 Praise him with the sound of the trumpet: praise him with the psaltery and harp.",
"4 Praise him with the timbrel and dance: praise him with stringed instruments and organs.",
"5 Praise him upon the loud cymbals: praise him upon the high sounding cymbals.",
"6 Let every thing that hath breath praise the LORD. Praise ye the LORD.",
"",
"——【The Book of Psalms 150】",
"",
"1 你们要赞美耶和华！在　神的圣所赞美他！在他显能力的穹苍赞美他！",
"2 要因他大能的作为赞美他，按着他极美的大德赞美他！",
"3 要用角声赞美他，鼓瑟弹琴赞美他！",
"4 击鼓跳舞赞美他！用丝弦的乐器和箫的声音赞美他！",
"5 用大响的钹赞美他！用高声的钹赞美他！",
"6 凡有气息的都要赞美耶和华！你们要赞美耶和华！",
"",
"——【诗篇 150】",
],
[
"18 And she said, Let thine handmaid find grace in thy sight. So the woman went her way, and did eat, and her countenance was no more sad.",
"19 And they rose up in the morning early, and worshipped before the LORD, and returned, and came to their house to Ramah: and Elkanah knew Hannah his wife; and the LORD remembered her.",
"20 Wherefore it came to pass, when the time was come about after Hannah had conceived, that she bare a son, and called his name Samuel, saying, Because I have asked him of the LORD.",
"21 And the man Elkanah, and all his house, went up to offer unto the LORD the yearly sacrifice, and his vow.",
"",
"——【The First Book of Samuel 1】",
"",
"18 哈拿说：「愿婢女在你眼前蒙恩。」于是妇人走去吃饭，面上再不带愁容了。",
"19 次日清早，他们起来，在耶和华面前敬拜，就回拉玛。到了家里，以利加拿和妻哈拿同房，耶和华顾念哈拿，",
"20 哈拿就怀孕。日期满足，生了一个儿子，给他起名叫撒母耳，说：「这是我从耶和华那里求来的。」",
"21 以利加拿和他全家都上示罗去，要向耶和华献年祭，并还所许的愿。",
"",
"——【撒母耳记上 1】",
],
[
"1 At that time Merodach–baladan, the son of Baladan, king of Babylon, sent letters and a present to Hezekiah: for he had heard that he had been sick, and was recovered.",
"2 And Hezekiah was glad of them, and shewed them the house of his precious things, the silver, and the gold, and the spices, and the precious ointment, and all the house of his armour, and all that was found in his treasures: there was nothing in his house, nor in all his dominion, that Hezekiah shewed them not.",
"",
"——【The Book of the Prophet Isaiah 39】",
"",
"1 那时，巴比伦王巴拉但的儿子米罗达巴拉但听见希西家病而痊癒，就送书信和礼物给他。",
"2 希西家喜欢见使者，就把自己宝库的金子、银子、香料、贵重的膏油，和他武库的一切军器，并所有的财宝都给他们看；他家中和全国之内，希西家没有一样不给他们看的。",
"",
"——【以赛亚书 39】",
],
[
"20 Where is the wise? where is the scribe? where is the disputer of this world? hath not God made foolish the wisdom of this world?",
"21 For after that in the wisdom of God the world by wisdom knew not God, it pleased God by the foolishness of preaching to save them that believe.",
"22 For the Jews require a sign, and the Greeks seek after wisdom:",
"23 But we preach Christ crucified, unto the Jews a stumblingblock, and unto the Greeks foolishness;",
"",
"——【The First Epistle of Paul the Apostle to the Corinthians 1】",
"",
"20 智慧人在那里？文士在那里？这世上的辩士在那里？　神岂不是叫这世上的智慧变成愚拙吗？",
"21 世人凭自己的智慧，既不认识　神，　神就乐意用人所当作愚拙的道理，拯救那些信的人；这就是　神的智慧了。",
"22 犹太人是要神迹，希腊人是求智慧，",
"23 我们却是传钉十字架的基督，在犹太人为绊脚石，在外邦人为愚拙；",
"",
"——【哥林多前书 1】",
],
[
"19 The throne had six steps, and the top of the throne was round behind: and there were stays on either side on the place of the seat, and two lions stood beside the stays.",
"20 And twelve lions stood there on the one side and on the other upon the six steps: there was not the like made in any kingdom.",
"",
"——【The First Book of the Kings 10】",
"",
"19 宝座有六层台阶，座的后背是圆的，两旁有扶手，靠近扶手有两个狮子站立。",
"20 六层台阶上有十二个狮子站立，每层有两个：左边一个，右边一个；在列国中没有这样做的。",
"",
"——【列王记上 10】",
],
[
"39 Now the rest of the acts of Ahab, and all that he did, and the ivory house which he made, and all the cities that he built, are they not written in the book of the chronicles of the kings of Israel?",
"40 So Ahab slept with his fathers; and Ahaziah his son reigned in his stead.",
"41 And Jehoshaphat the son of Asa began to reign over Judah in the fourth year of Ahab king of Israel.",
"",
"——【The First Book of the Kings 22】",
"",
"39 亚哈其余的事，凡他所行的和他所修造的象牙宫，并所建筑的一切城邑，都写在以色列诸王记上。",
"40 亚哈与他列祖同睡。他儿子亚哈谢接续他作王。",
"41 以色列王亚哈第四年，亚撒的儿子约沙法登基作了犹大王。",
"",
"——【列王记上 22】",
],
[
"5 For Moses describeth the righteousness which is of the law, That the man which doeth those things shall live by them.",
"6 But the righteousness which is of faith speaketh on this wise, Say not in thine heart, Who shall ascend into heaven? (that is, to bring Christ down from above:)",
"7 Or, Who shall descend into the deep? (that is, to bring up Christ again from the dead.)",
"8 But what saith it? The word is nigh thee, even in thy mouth, and in thy heart: that is, the word of faith, which we preach;",
"9 That if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved.",
"",
"——【The Epistle of Paul the Apostle to the Romans 10】",
"",
"5 摩西写着说：人若行那出于律法的义，就必因此活着。",
"6 惟有出于信心的义如此说：你不要心里说：谁要升到天上去呢？就是要领下基督来；",
"7 谁要下到阴间去呢？就是要领基督从死里上来。",
"8 他到底怎么说呢？他说：这道离你不远，正在你口里，在你心里。（就是我们所传信主的道。）",
"9 你若口里认耶稣为主，心里信　神叫他从死里复活，就必得救。",
"",
"——【罗马书 10】",
],
[
"8 For we can do nothing against the truth, but for the truth.",
"9 For we are glad, when we are weak, and ye are strong: and this also we wish, even your perfection.",
"10 Therefore I write these things being absent, lest being present I should use sharpness, according to the power which the Lord hath given me to edification, and not to destruction.",
"11 Finally, brethren, farewell. Be perfect, be of good comfort, be of one mind, live in peace; and the God of love and peace shall be with you.",
"12 Greet one another with an holy kiss.",
"",
"——【The Second Epistle of Paul the Apostle to the Corinthians 13】",
"",
"8 我们凡事不能敌挡真理，只能扶助真理。",
"9 即使我们软弱，你们刚强，我们也欢喜；并且我们所求的，就是你们作完全人。",
"10 所以，我不在你们那里的时候，把这话写给你们，好叫我见你们的时候，不用照主所给我的权柄严厉的待你们；这权柄原是为造就人，并不是为败坏人。",
"11 还有末了的话：愿弟兄们都喜乐。要作完全人；要受安慰；要同心合意；要彼此和睦。如此，仁爱和平的　神必常与你们同在。",
"12 你们亲嘴问安，彼此务要圣洁。",
"",
"——【哥林多后书 13】",
],
];
