var bible31_global=[
[
"20 And Benaiah the son of Jehoiada, the son of a valiant man, of Kabzeel, who had done many acts, he slew two lionlike men of Moab: he went down also and slew a lion in the midst of a pit in time of snow:",
"21 And he slew an Egyptian, a goodly man: and the Egyptian had a spear in his hand; but he went down to him with a staff, and plucked the spear out of the Egyptian's hand, and slew him with his own spear.",
"",
"——【The Second Book of Samuel 23】",
"",
"20 有甲薛勇士耶何耶大的儿子比拿雅行过大能的事；他杀了摩押人亚利伊勒的两个儿子，又在下雪的时候下坑里去，杀了一个狮子，",
"21 又杀了一个强壮的埃及人；埃及人手里拿著枪，比拿雅只拿著棍子下去，从埃及人手里夺过枪来，用那枪将他杀死。",
"",
"——【撒母耳记下 23】",
],
[
"17 And the land of Judah shall be a terror unto Egypt, every one that maketh mention thereof shall be afraid in himself, because of the counsel of the LORD of hosts, which he hath determined against it.",
"18 In that day shall five cities in the land of Egypt speak the language of Canaan, and swear to the LORD of hosts; one shall be called, The city of destruction.",
"19 In that day shall there be an altar to the LORD in the midst of the land of Egypt, and a pillar at the border thereof to the LORD.",
"",
"——【The Book of the Prophet Isaiah 19】",
"",
"17 犹大地必使埃及惊恐，向谁提起犹大地，谁就惧怕。这是因万军之耶和华向埃及所定的旨意。",
"18 当那日，埃及地必有五城的人说迦南的方言，又指著万军之耶和华起誓。有一城必称为灭亡城。",
"19 当那日，在埃及地中必有为耶和华筑的一座坛；在埃及的边界上必有为耶和华立的一根柱。",
"",
"——【以赛亚书 19】",
],
[
"1 And he said unto them, Verily I say unto you, That there be some of them that stand here, which shall not taste of death, till they have seen the kingdom of God come with power.",
"2 And after six days Jesus taketh with him Peter, and James, and John, and leadeth them up into an high mountain apart by themselves: and he was transfigured before them.",
"",
"——【The Gospel According to Saint Mark 9】",
"",
"1 耶稣又对他们说：我实在告诉你们，站在这里的，有人在没尝死味以前，必要看见　神的国大有能力临到。",
"2 过了六天，耶稣带著彼得、雅各、约翰暗暗的上了高山，就在他们面前变了形像，",
"",
"——【马可福音 9】",
],
[
"12 But thou shouldest not have looked on the day of thy brother in the day that he became a stranger; neither shouldest thou have rejoiced over the children of Judah in the day of their destruction; neither shouldest thou have spoken proudly in the day of distress.",
"13 Thou shouldest not have entered into the gate of my people in the day of their calamity; yea, thou shouldest not have looked on their affliction in the day of their calamity, nor have laid hands on their substance in the day of their calamity;",
"14 Neither shouldest thou have stood in the crossway, to cut off those of his that did escape; neither shouldest thou have delivered up those of his that did remain in the day of distress.",
"15 For the day of the LORD is near upon all the heathen: as thou hast done, it shall be done unto thee: thy reward shall return upon thine own head.",
"16 For as ye have drunk upon my holy mountain, so shall all the heathen drink continually, yea, they shall drink, and they shall swallow down, and they shall be as though they had not been.",
"17 But upon mount Zion shall be deliverance, and there shall be holiness; and the house of Jacob shall possess their possessions.",
"",
"——【Obadiah 1】",
"",
"12 你兄弟遭难的日子，你不当瞪眼看著；犹大人被灭的日子，你不当因此欢乐；他们遭难的日子，你不当说狂傲的话。",
"13 我民遭灾的日子，你不当进他们的城门；他们遭灾的日子，你不当瞪眼看著他们受苦；他们遭灾的日子，你不当伸手抢他们的财物；",
"14 你不当站在岔路口剪除他们中间逃脱的；他们遭难的日子，你不当将他们剩下的人交付仇敌。",
"15 耶和华降罚的日子临近万国。你怎样行，他也必照样向你行；你的报应必归到你头上。",
"16 你们犹大人在我圣山怎样喝了苦杯，万国也必照样常常地喝；且喝且咽，他们就归于无有。",
"17 在锡安山必有逃脱的人，那山也必成圣；雅各家必得原有的产业。",
"",
"——【俄巴底亚书 1】",
],
[
"7 He layeth up sound wisdom for the righteous: he is a buckler to them that walk uprightly.",
"8 He keepeth the paths of judgment, and preserveth the way of his saints.",
"9 Then shalt thou understand righteousness, and judgment, and equity; yea, every good path.",
"10 When wisdom entereth into thine heart, and knowledge is pleasant unto thy soul;",
"11 Discretion shall preserve thee, understanding shall keep thee:",
"",
"——【The Proverbs 2】",
"",
"7 他给正直人存留真智慧，给行为纯正的人作盾牌，",
"8 为要保守公平人的路，护庇虔敬人的道。",
"9 你也必明白仁义、公平、正直、一切的善道。",
"10 智慧必入你心；你的灵要以知识为美。",
"11 谋略必护卫你；聪明必保守你，",
"",
"——【箴言 2】",
],
[
"8 Harden not your hearts, as in the provocation, in the day of temptation in the wilderness:",
"9 When your fathers tempted me, proved me, and saw my works forty years.",
"10 Wherefore I was grieved with that generation, and said, They do alway err in their heart; and they have not known my ways.",
"11 So I sware in my wrath, They shall not enter into my rest.)",
"12 Take heed, brethren, lest there be in any of you an evil heart of unbelief, in departing from the living God.",
"13 But exhort one another daily, while it is called To day; lest any of you be hardened through the deceitfulness of sin.",
"",
"——【The Epistle of Paul the Apostle to the Hebrews 3】",
"",
"8 就不可硬著心，像在旷野惹他发怒、试探他的时候一样。",
"9 在那里，你们的祖宗试我探我，并且观看我的作为有四十年之久。",
"10 所以，我厌烦那世代的人，说：他们心里常常迷糊，竟不晓得我的作为！",
"11 我就在怒中起誓说；他们断不可进入我的安息。",
"12 弟兄们，你们要谨慎，免得你们中间或有人存著不信的恶心，把永生　神离弃了。",
"13 总要趁著还有今日，天天彼此相劝，免得你们中间有人被罪迷惑，心里就刚硬了。",
"",
"——【希伯来书 3】",
],
[
"10 If ye will still abide in this land, then will I build you, and not pull you down, and I will plant you, and not pluck you up: for I repent me of the evil that I have done unto you.",
"11 Be not afraid of the king of Babylon, of whom ye are afraid; be not afraid of him, saith the LORD: for I am with you to save you, and to deliver you from his hand.",
"12 And I will shew mercies unto you, that he may have mercy upon you, and cause you to return to your own land.",
"",
"——【The Book of the Prophet Jeremiah 42】",
"",
"10 『你们若仍住在这地，我就建立你们，必不拆毁，栽植你们，并不拔出，因我为降与你们的灾祸后悔了。",
"11 不要怕你们所怕的巴比伦王。』」耶和华说：「不要怕他！因为我与你们同在，要拯救你们脱离他的手。",
"12 我也要使他发怜悯，好怜悯你们，叫你们归回本地。』",
"",
"——【耶利米书 42】",
],
[
"1 But in the last days it shall come to pass, that the mountain of the house of the LORD shall be established in the top of the mountains, and it shall be exalted above the hills; and people shall flow unto it.",
"2 And many nations shall come, and say, Come, and let us go up to the mountain of the LORD, and to the house of the God of Jacob; and he will teach us of his ways, and we will walk in his paths: for the law shall go forth of Zion, and the word of the LORD from Jerusalem.",
"",
"——【Micah 4】",
"",
"1 末后的日子，耶和华殿的山必坚立，超乎诸山，高举过于万岭；万民都要流归这山。",
"2 必有许多国的民前往，说：来吧，我们登耶和华的山，奔雅各　神的殿。主必将他的道教训我们；我们也要行他的路。因为训诲必出于锡安；耶和华的言语必出于耶路撒冷。",
"",
"——【弥迦书 4】",
],
[
"5 Happy is he that hath the God of Jacob for his help, whose hope is in the LORD his God:",
"6 Which made heaven, and earth, the sea, and all that therein is: which keepeth truth for ever:",
"7 Which executeth judgment for the oppressed: which giveth food to the hungry. The LORD looseth the prisoners:",
"",
"——【The Book of Psalms 146】",
"",
"5 以雅各的　神为帮助、仰望耶和华─他　神的，这人便为有福！",
"6 耶和华造天、地、海，和其中的万物；他守诚实，直到永远。",
"7 他为受屈的伸冤，赐食物与饥饿的。耶和华释放被囚的；",
"",
"——【诗篇 146】",
],
[
"9 And they said unto him, Where is Sarah thy wife? And he said, Behold, in the tent.",
"10 And he said, I will certainly return unto thee according to the time of life; and, lo, Sarah thy wife shall have a son. And Sarah heard it in the tent door, which was behind him.",
"11 Now Abraham and Sarah were old and well stricken in age; and it ceased to be with Sarah after the manner of women.",
"12 Therefore Sarah laughed within herself, saying, After I am waxed old shall I have pleasure, my lord being old also?",
"13 And the LORD said unto Abraham, Wherefore did Sarah laugh, saying, Shall I of a surety bear a child, which am old?",
"",
"——【The First Book of Moses: Called Genesis 18】",
"",
"9 他们问亚伯拉罕说：「你妻子撒拉在那里？」他说：「在帐棚里。」",
"10 三人中有一位说：「到明年这时候，我必要回到你这里；你的妻子撒拉必生一个儿子。」撒拉在那人后边的帐棚门口也听见了这话。",
"11 亚伯拉罕和撒拉年纪老迈，撒拉的月经已断绝了。",
"12 撒拉心里暗笑，说：「我既已衰败，我主也老迈，岂能有这喜事呢？」",
"13 耶和华对亚伯拉罕说：「撒拉为什么暗笑，说：『我既已年老，果真能生养么？』",
"",
"——【创世记 18】",
],
[
"11 For so an entrance shall be ministered unto you abundantly into the everlasting kingdom of our Lord and Saviour Jesus Christ.",
"12 Wherefore I will not be negligent to put you always in remembrance of these things, though ye know them, and be established in the present truth.",
"13 Yea, I think it meet, as long as I am in this tabernacle, to stir you up by putting you in remembrance;",
"14 Knowing that shortly I must put off this my tabernacle, even as our Lord Jesus Christ hath shewed me.",
"15 Moreover I will endeavour that ye may be able after my decease to have these things always in remembrance.",
"",
"——【The Second General Epistle of Peter 1】",
"",
"11 这样，必叫你们丰丰富富的得以进入我们主─救主耶稣基督永远的国。",
"12 你们虽然晓得这些事，并且在你们已有的真道上坚固，我却要将这些事常常提醒你们。",
"13 我以为应当趁我还在这帐棚的时候提醒你们，激发你们。",
"14 因为知道我脱离这帐棚的时候快到了，正如我们主耶稣基督所指示我的。",
"15 并且，我要尽心竭力，使你们在我去世以后时常记念这些事。",
"",
"——【彼得后书 1】",
],
[
"1 Judge me, O God, and plead my cause against an ungodly nation: O deliver me from the deceitful and unjust man.",
"2 For thou art the God of my strength: why dost thou cast me off? why go I mourning because of the oppression of the enemy?",
"",
"——【The Book of Psalms 43】",
"",
"1 　神啊，求你伸我的冤，向不虔诚的国为我辨屈；求你救我脱离诡诈不义的人。",
"2 因为你是赐我力量的　神，为何丢弃我呢？我为何因仇敌的欺压时常哀痛呢？",
"",
"——【诗篇 43】",
],
[
"3 For they being ignorant of God's righteousness, and going about to establish their own righteousness, have not submitted themselves unto the righteousness of God.",
"4 For Christ is the end of the law for righteousness to every one that believeth.",
"5 For Moses describeth the righteousness which is of the law, That the man which doeth those things shall live by them.",
"6 But the righteousness which is of faith speaketh on this wise, Say not in thine heart, Who shall ascend into heaven? (that is, to bring Christ down from above:)",
"7 Or, Who shall descend into the deep? (that is, to bring up Christ again from the dead.)",
"8 But what saith it? The word is nigh thee, even in thy mouth, and in thy heart: that is, the word of faith, which we preach;",
"",
"——【The Epistle of Paul the Apostle to the Romans 10】",
"",
"3 因为不知道　神的义，想要立自己的义，就不服　神的义了。",
"4 律法的总结就是基督，使凡信他的都得著义。",
"5 摩西写著说：人若行那出于律法的义，就必因此活著。",
"6 惟有出于信心的义如此说：你不要心里说：谁要升到天上去呢？就是要领下基督来；",
"7 谁要下到阴间去呢？就是要领基督从死里上来。",
"8 他到底怎么说呢？他说：这道离你不远，正在你口里，在你心里。（就是我们所传信主的道。）",
"",
"——【罗马书 10】",
],
[
"1 Then all the captains of the forces, and Johanan the son of Kareah, and Jezaniah the son of Hoshaiah, and all the people from the least even unto the greatest, came near,",
"2 And said unto Jeremiah the prophet, Let, we beseech thee, our supplication be accepted before thee, and pray for us unto the LORD thy God, even for all this remnant; (for we are left but a few of many, as thine eyes do behold us:)",
"",
"——【The Book of the Prophet Jeremiah 42】",
"",
"1 众军长和加利亚的儿子约哈难，并何沙雅的儿子耶撒尼亚（又名亚撒利雅，见四十三章二节）以及众百姓，从最小的到至大的都进前来，",
"2 对先知耶利米说：「求你准我们在你面前祈求，为我们这剩下的人祷告耶和华─你的　神。我们本来众多，现在剩下的极少，这是你亲眼所见的。",
"",
"——【耶利米书 42】",
],
[
"1 Remember, O LORD, what is come upon us: consider, and behold our reproach.",
"2 Our inheritance is turned to strangers, our houses to aliens.",
"3 We are orphans and fatherless, our mothers are as widows.",
"4 We have drunken our water for money; our wood is sold unto us.",
"5 Our necks are under persecution: we labour, and have no rest.",
"",
"——【The Lamentations of Jeremiah 5】",
"",
"1 耶和华啊，求你记念我们所遭遇的事，观看我们所受的凌辱。",
"2 我们的产业归与外邦人；我们的房屋归与外路人。",
"3 我们是无父的孤儿；我们的母亲好像寡妇。",
"4 我们出钱才得水喝；我们的柴是人卖给我们的。",
"5 追赶我们的，到了我们的颈项上；我们疲乏不得歇息。",
"",
"——【耶利米哀歌 5】",
],
[
"3 The LORD shall cut off all flattering lips, and the tongue that speaketh proud things:",
"4 Who have said, With our tongue will we prevail; our lips are our own: who is lord over us?",
"5 For the oppression of the poor, for the sighing of the needy, now will I arise, saith the LORD; I will set him in safety from him that puffeth at him.",
"",
"——【The Book of Psalms 12】",
"",
"3 凡油滑的嘴唇和夸大的舌头，耶和华必要剪除。",
"4 他们曾说：我们必能以舌头得胜；我们的嘴唇是我们自己的，谁能作我们的主呢？",
"5 耶和华说：因为困苦人的冤屈和贫穷人的叹息，我现在要起来，把他安置在他所切慕的稳妥之地。",
"",
"——【诗篇 12】",
],
[
"30 Then I was by him, as one brought up with him: and I was daily his delight, rejoicing always before him;",
"31 Rejoicing in the habitable part of his earth; and my delights were with the sons of men.",
"",
"——【The Proverbs 8】",
"",
"30 那时，我在他那里为工师，日日为他所喜爱，常常在他面前踊跃，",
"31 踊跃在他为人预备可住之地，也喜悦住在世人之间。",
"",
"——【箴言 8】",
],
[
"3 Speak unto Rehoboam the son of Solomon, king of Judah, and to all Israel in Judah and Benjamin, saying,",
"4 Thus saith the LORD, Ye shall not go up, nor fight against your brethren: return every man to his house: for this thing is done of me. And they obeyed the words of the LORD, and returned from going against Jeroboam.",
"5 And Rehoboam dwelt in Jerusalem, and built cities for defence in Judah.",
"",
"——【The Second Book of the Chronicles 11】",
"",
"3 「你去告诉所罗门的儿子犹大王罗波安和住犹大、便雅悯的以色列众人说，",
"4 耶和华如此说：『你们不可上去与你们的弟兄争战，各归各家去吧！因为这事出于我。』」众人就听从耶和华的话归回，不去与耶罗波安争战。",
"5 罗波安住在耶路撒冷，在犹大地修筑城邑，",
"",
"——【历代志下 11】",
],
[
"8 For we would not, brethren, have you ignorant of our trouble which came to us in Asia, that we were pressed out of measure, above strength, insomuch that we despaired even of life:",
"9 But we had the sentence of death in ourselves, that we should not trust in ourselves, but in God which raiseth the dead:",
"10 Who delivered us from so great a death, and doth deliver: in whom we trust that he will yet deliver us;",
"",
"——【The Second Epistle of Paul the Apostle to the Corinthians 1】",
"",
"8 弟兄们，我们不要你们不晓得，我们从前在亚细亚遭遇苦难，被压太重，力不能胜，甚至连活命的指望都绝了；",
"9 自己心里也断定是必死的，叫我们不靠自己，只靠叫死人复活的　神。",
"10 他曾救我们脱离那极大的死亡，现在仍要救我们，并且我们指望他将来还要救我们。",
"",
"——【哥林多后书 1】",
],
[
"9 I will bear the indignation of the LORD, because I have sinned against him, until he plead my cause, and execute judgment for me: he will bring me forth to the light, and I shall behold his righteousness.",
"10 Then she that is mine enemy shall see it, and shame shall cover her which said unto me, Where is the LORD thy God? mine eyes shall behold her: now shall she be trodden down as the mire of the streets.",
"11 In the day that thy walls are to be built, in that day shall the decree be far removed.",
"",
"——【Micah 7】",
"",
"9 我要忍受耶和华的恼怒；因我得罪了他，直等他为我辨屈，为我伸冤。他必领我到光明中；我必得见他的公义。",
"10 那时我的仇敌，就是曾对我说耶和华─你　神在哪里的，他一看见这事就被羞愧遮盖。我必亲眼见他遭报；他必被践踏，如同街上的泥土。",
"11 以色列啊，日子必到，你的墙垣必重修；到那日，你的境界必开展（或译：命令必传到远方）。",
"",
"——【弥迦书 7】",
],
[
"3 For this man was counted worthy of more glory than Moses, inasmuch as he who hath builded the house hath more honour than the house.",
"4 For every house is builded by some man; but he that built all things is God.",
"5 And Moses verily was faithful in all his house, as a servant, for a testimony of those things which were to be spoken after;",
"",
"——【The Epistle of Paul the Apostle to the Hebrews 3】",
"",
"3 他比摩西算是更配多得荣耀，好像建造房屋的比房屋更尊荣；",
"4 因为房屋都必有人建造，但建造万物的就是　神。",
"5 摩西为仆人，在　神的全家诚然尽忠，为要证明将来必传说的事。",
"",
"——【希伯来书 3】",
],
[
"6 For he wist not what to say; for they were sore afraid.",
"7 And there was a cloud that overshadowed them: and a voice came out of the cloud, saying, This is my beloved Son: hear him.",
"8 And suddenly, when they had looked round about, they saw no man any more, save Jesus only with themselves.",
"9 And as they came down from the mountain, he charged them that they should tell no man what things they had seen, till the Son of man were risen from the dead.",
"",
"——【The Gospel According to Saint Mark 9】",
"",
"6 彼得不知道说什么才好，因为他们甚是惧怕。",
"7 有一朵云彩来遮盖他们；也有声音从云彩里出来，说：这是我的爱子，你们要听他。",
"8 门徒忽然周围一看，不再见一人，只见耶稣同他们在那里。",
"9 下山的时候，耶稣嘱咐他们说：人子还没有从死里复活，你们不要将所看见的告诉人。",
"",
"——【马可福音 9】",
],
[
"13 And he shall slay the lamb in the place where he shall kill the sin offering and the burnt offering, in the holy place: for as the sin offering is the priest's, so is the trespass offering: it is most holy:",
"14 And the priest shall take some of the blood of the trespass offering, and the priest shall put it upon the tip of the right ear of him that is to be cleansed, and upon the thumb of his right hand, and upon the great toe of his right foot:",
"15 And the priest shall take some of the log of oil, and pour it into the palm of his own left hand:",
"",
"——【The Third Book of Moses: Called Leviticus 14】",
"",
"13 把公羊羔宰于圣地，就是宰赎罪祭牲和燔祭牲之地。赎愆祭要归祭司，与赎罪祭一样，是至圣的。",
"14 祭司要取些赎愆祭牲的血，抹在求洁净人的右耳垂上和右手的大拇指上，并右脚的大拇指上。",
"15 祭司要从那一罗革油中取些倒在自己的左手掌里，",
"",
"——【利未记 14】",
],
[
"21 But as it is written, To whom he was not spoken of, they shall see: and they that have not heard shall understand.",
"22 For which cause also I have been much hindered from coming to you.",
"23 But now having no more place in these parts, and having a great desire these many years to come unto you;",
"24 Whensoever I take my journey into Spain, I will come to you: for I trust to see you in my journey, and to be brought on my way thitherward by you, if first I be somewhat filled with your company.",
"25 But now I go unto Jerusalem to minister unto the saints.",
"",
"——【The Epistle of Paul the Apostle to the Romans 15】",
"",
"21 就如经上所记：未曾闻知他信息的，将要看见；未曾听过的，将要明白。",
"22 我因多次被拦阻，总不得到你们那里去。",
"23 但如今，在这里再没有可传的地方，而且这好几年，我切心想望到西班牙去的时候，可以到你们那里，",
"24 盼望从你们那里经过，得见你们，先与你们彼此交往，心里稍微满足，然后蒙你们送行。",
"25 但现在，我往耶路撒冷去供给圣徒。",
"",
"——【罗马书 15】",
],
[
"1 I beseech you therefore, brethren, by the mercies of God, that ye present your bodies a living sacrifice, holy, acceptable unto God, which is your reasonable service.",
"2 And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God.",
"3 For I say, through the grace given unto me, to every man that is among you, not to think of himself more highly than he ought to think; but to think soberly, according as God hath dealt to every man the measure of faith.",
"",
"——【The Epistle of Paul the Apostle to the Romans 12】",
"",
"1 所以弟兄们，我以　神的慈悲劝你们，将身体献上，当作活祭，是圣洁的，是　神所喜悦的；你们如此事奉乃是理所当然的。",
"2 不要效法这个世界，只要心意更新而变化，叫你们察验何为　神的善良、纯全、可喜悦的旨意。",
"3 我凭著所赐我的恩对你们各人说：不要看自己过于所当看的，要照著　神所分给各人信心的大小，看得合乎中道。",
"",
"——【罗马书 12】",
],
[
"3 Then this Daniel was preferred above the presidents and princes, because an excellent spirit was in him; and the king thought to set him over the whole realm.",
"4 Then the presidents and princes sought to find occasion against Daniel concerning the kingdom; but they could find none occasion nor fault; forasmuch as he was faithful, neither was there any error or fault found in him.",
"5 Then said these men, We shall not find any occasion against this Daniel, except we find it against him concerning the law of his God.",
"6 Then these presidents and princes assembled together to the king, and said thus unto him, King Darius, live for ever.",
"7 All the presidents of the kingdom, the governors, and the princes, the counsellors, and the captains, have consulted together to establish a royal statute, and to make a firm decree, that whosoever shall ask a petition of any God or man for thirty days, save of thee, O king, he shall be cast into the den of lions.",
"8 Now, O king, establish the decree, and sign the writing, that it be not changed, according to the law of the Medes and Persians, which altereth not.",
"",
"——【The Book of Daniel 6】",
"",
"3 因这但以理有美好的灵性，所以显然超乎其余的总长和总督，王又想立他治理通国。",
"4 那时，总长和总督寻找但以理误国的把柄，为要参他；只是找不著他的错误过失，因他忠心办事，毫无错误过失。",
"5 那些人便说：「我们要找参这但以理的把柄，除非在他　神的律法中就寻不著。」",
"6 于是，总长和总督纷纷聚集来见王，说：「愿大利乌王万岁！",
"7 国中的总长、钦差、总督、谋士，和巡抚彼此商议，要立一条坚定的禁令（或译：求王下旨要立一条……），三十日内，不拘何人，若在王以外，或向神或向人求什么，就必扔在狮子坑中。",
"8 王啊，现在求你立这禁令，加盖玉玺，使禁令决不更改；照玛代和波斯人的例是不可更改的。」",
"",
"——【但以理书 6】",
],
[
"3 And God Almighty bless thee, and make thee fruitful, and multiply thee, that thou mayest be a multitude of people;",
"4 And give thee the blessing of Abraham, to thee, and to thy seed with thee; that thou mayest inherit the land wherein thou art a stranger, which God gave unto Abraham.",
"5 And Isaac sent away Jacob: and he went to Padan–aram unto Laban, son of Bethuel the Syrian, the brother of Rebekah, Jacob's and Esau's mother.",
"6 When Esau saw that Isaac had blessed Jacob, and sent him away to Padan–aram, to take him a wife from thence; and that as he blessed him he gave him a charge, saying, Thou shalt not take a wife of the daughters of Canaan;",
"7 And that Jacob obeyed his father and his mother, and was gone to Padan–aram;",
"8 And Esau seeing that the daughters of Canaan pleased not Isaac his father;",
"",
"——【The First Book of Moses: Called Genesis 28】",
"",
"3 愿全能的　神赐福给你，使你生养众多，成为多族，",
"4 将应许亚伯拉罕的福赐给你和你的后裔，使你承受你所寄居的地为业，就是　神赐给亚伯拉罕的地。」",
"5 以撒打发雅各走了，他就往巴旦‧亚兰去，到亚兰人彼土利的儿子拉班那里。拉班是雅各、以扫的母舅。",
"6 以扫见以撒已经给雅各祝福，而且打发他往巴旦‧亚兰去，在那里娶妻，并见祝福的时候嘱咐他说：「不要娶迦南的女子为妻」，",
"7 又见雅各听从父母的话往巴旦‧亚兰去了，",
"8 以扫就晓得他父亲以撒看不中迦南的女子，",
"",
"——【创世记 28】",
],
[
"12 And Abner the son of Ner, and the servants of Ish–bosheth the son of Saul, went out from Mahanaim to Gibeon.",
"13 And Joab the son of Zeruiah, and the servants of David, went out, and met together by the pool of Gibeon: and they sat down, the one on the one side of the pool, and the other on the other side of the pool.",
"14 And Abner said to Joab, Let the young men now arise, and play before us. And Joab said, Let them arise.",
"15 Then there arose and went over by number twelve of Benjamin, which pertained to Ish–bosheth the son of Saul, and twelve of the servants of David.",
"16 And they caught every one his fellow by the head, and thrust his sword in his fellow's side; so they fell down together: wherefore that place was called Helkath–hazzurim, which is in Gibeon.",
"17 And there was a very sore battle that day; and Abner was beaten, and the men of Israel, before the servants of David.",
"",
"——【The Second Book of Samuel 2】",
"",
"12 尼珥的儿子押尼珥和扫罗的儿子伊施波设的仆人从玛哈念出来，往基遍去。",
"13 洗鲁雅的儿子约押和大卫的仆人也出来，在基遍池旁与他们相遇；一班坐在池这边，一班坐在池那边。",
"14 押尼珥对约押说：「让少年人起来，在我们面前戏耍吧！」约押说：「可以。」",
"15 就按著定数起来：属扫罗儿子伊施波设的便雅悯人过去十二名，大卫的仆人也过去十二名，",
"16 彼此揪头，用刀刺肋，一同仆倒。所以，那地叫作希利甲‧哈素林，就在基遍。",
"17 那日的战事凶猛，押尼珥和以色列人败在大卫的仆人面前。",
"",
"——【撒母耳记下 2】",
],
[
"3 The sea saw it, and fled: Jordan was driven back.",
"4 The mountains skipped like rams, and the little hills like lambs.",
"5 What ailed thee, O thou sea, that thou fleddest? thou Jordan, that thou wast driven back?",
"6 Ye mountains, that ye skipped like rams; and ye little hills, like lambs?",
"7 Tremble, thou earth, at the presence of the Lord, at the presence of the God of Jacob;",
"",
"——【The Book of Psalms 114】",
"",
"3 沧海看见就奔逃；约旦河也倒流。",
"4 大山踊跃，如公羊；小山跳舞，如羊羔。",
"5 沧海啊，你为何奔逃？约旦哪，你为何倒流？",
"6 大山哪，你为何踊跃，如公羊？小山哪，你为何跳舞，如羊羔？",
"7 大地啊，你因见主的面，就是雅各　神的面，便要震动。",
"",
"——【诗篇 114】",
],
[
"4 Greatly desiring to see thee, being mindful of thy tears, that I may be filled with joy;",
"5 When I call to remembrance the unfeigned faith that is in thee, which dwelt first in thy grandmother Lois, and thy mother Eunice; and I am persuaded that in thee also.",
"6 Wherefore I put thee in remembrance that thou stir up the gift of God, which is in thee by the putting on of my hands.",
"7 For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.",
"",
"——【The Second Epistle of Paul the Apostle to Timothy 1】",
"",
"4 记念你的眼泪，昼夜切切的想要见你，好叫我满心快乐。",
"5 想到你心里无伪之信，这信是先在你外祖母罗以和你母亲友尼基心里的，我深信也在你的心里。",
"6 为此我提醒你，使你将　神借我按手所给你的恩赐再如火挑旺起来。",
"7 因为　神赐给我们，不是胆怯的心，乃是刚强、仁爱、谨守的心。",
"",
"——【提摩太后书 1】",
],
[
"5 I saw a dream which made me afraid, and the thoughts upon my bed and the visions of my head troubled me.",
"6 Therefore made I a decree to bring in all the wise men of Babylon before me, that they might make known unto me the interpretation of the dream.",
"7 Then came in the magicians, the astrologers, the Chaldeans, and the soothsayers: and I told the dream before them; but they did not make known unto me the interpretation thereof.",
"8 But at the last Daniel came in before me, whose name was Belteshazzar, according to the name of my god, and in whom is the spirit of the holy gods: and before him I told the dream, saying,",
"9 O Belteshazzar, master of the magicians, because I know that the spirit of the holy gods is in thee, and no secret troubleth thee, tell me the visions of my dream that I have seen, and the interpretation thereof.",
"10 Thus were the visions of mine head in my bed; I saw, and behold a tree in the midst of the earth, and the height thereof was great.",
"",
"——【The Book of Daniel 4】",
"",
"5 我做了一梦，使我惧怕。我在床上的思念，并脑中的异象，使我惊惶。",
"6 所以我降旨召巴比伦的一切哲士到我面前，叫他们把梦的讲解告诉我。",
"7 于是那些术士、用法术的、迦勒底人、观兆的都进来，我将那梦告诉了他们，他们却不能把梦的讲解告诉我。",
"8 末后那照我　神的名，称为伯提沙撒的但以理来到我面前，他里头有圣神的灵，我将梦告诉他说：",
"9 『术士的领袖伯提沙撒啊，因我知道你里头有圣神的灵，什么奥祕的事都不能使你为难。现在要把我梦中所见的异象和梦的讲解告诉我。』",
"10 「我在床上脑中的异象是这样：我看见地当中有一棵树，极其高大。",
"",
"——【但以理书 4】",
],
];
