var bible31_global=[
[
"1 O LORD, rebuke me not in thy wrath: neither chasten me in thy hot displeasure.",
"2 For thine arrows stick fast in me, and thy hand presseth me sore.",
"3 There is no soundness in my flesh because of thine anger; neither is there any rest in my bones because of my sin.",
"",
"——【The Book of Psalms 38】",
"",
"1 （大卫的记念诗。）耶和华啊，求你不要在怒中责备我，不要在烈怒中惩罚我！",
"2 因为，你的箭射入我身；你的手压住我。",
"3 因你的恼怒，我的肉无一完全；因我的罪过，我的骨头也不安宁。",
"",
"——【诗篇 38】",
],
[
"2 Let my prayer be set forth before thee as incense; and the lifting up of my hands as the evening sacrifice.",
"3 Set a watch, O LORD, before my mouth; keep the door of my lips.",
"4 Incline not my heart to any evil thing, to practise wicked works with men that work iniquity: and let me not eat of their dainties.",
"",
"——【The Book of Psalms 141】",
"",
"2 愿我的祷告如香陈列在你面前！愿我举手祈求，如献晚祭！",
"3 耶和华啊，求你禁止我的口，把守我的嘴！",
"4 求你不叫我的心偏向邪恶，以致我和作孽的人同行恶事；也不叫我吃他们的美食。",
"",
"——【诗篇 141】",
],
[
"13 Woe unto thee, Chorazin! woe unto thee, Bethsaida! for if the mighty works had been done in Tyre and Sidon, which have been done in you, they had a great while ago repented, sitting in sackcloth and ashes.",
"14 But it shall be more tolerable for Tyre and Sidon at the judgment, than for you.",
"15 And thou, Capernaum, which art exalted to heaven, shalt be thrust down to hell.",
"16 He that heareth you heareth me; and he that despiseth you despiseth me; and he that despiseth me despiseth him that sent me.",
"",
"——【The Gospel According to Saint Luke 10】",
"",
"13 哥拉汛哪，你有祸了！伯赛大啊，你有祸了！因为在你们中间所行的异能若行在泰尔、西顿，他们早已披麻蒙灰，坐在地上悔改了。",
"14 当审判的日子，泰尔、西顿所受的，比你们还容易受呢！",
"15 迦百农啊，你已经升到天上（或作：你将要升到天上吗），将来必推下阴间。",
"16 又对门徒说：听从你们的就是听从我；弃绝你们的就是弃绝我；弃绝我的就是弃绝那差我来的。",
"",
"——【路加福音 10】",
],
[
"16 I will go in the strength of the Lord GOD: I will make mention of thy righteousness, even of thine only.",
"17 O God, thou hast taught me from my youth: and hitherto have I declared thy wondrous works.",
"18 Now also when I am old and grayheaded, O God, forsake me not; until I have shewed thy strength unto this generation, and thy power to every one that is to come.",
"19 Thy righteousness also, O God, is very high, who hast done great things: O God, who is like unto thee!",
"20 Thou, which hast shewed me great and sore troubles, shalt quicken me again, and shalt bring me up again from the depths of the earth.",
"",
"——【The Book of Psalms 71】",
"",
"16 我要来说主─耶和华大能的事；我单要提说你的公义。",
"17 　神啊，自我年幼时，你就教训我；直到如今，我传扬你奇妙的作为。",
"18 　神啊，我到年老发白的时候，求你不要离弃我！等我将你的能力指示下代，将你的大能指示后世的人。",
"19 　神啊，你的公义甚高；行过大事的　神啊，谁能像你！",
"20 你是叫我们多经历重大急难的，必使我们复活，从地的深处救上来。",
"",
"——【诗篇 71】",
],
[
"5 God thundereth marvellously with his voice; great things doeth he, which we cannot comprehend.",
"6 For he saith to the snow, Be thou on the earth; likewise to the small rain, and to the great rain of his strength.",
"7 He sealeth up the hand of every man; that all men may know his work.",
"8 Then the beasts go into dens, and remain in their places.",
"",
"——【The Book of Job 37】",
"",
"5 　神发出奇妙的雷声；他行大事，我们不能测透。",
"6 他对雪说：要降在地上；对大雨和暴雨也是这样说。",
"7 他封住各人的手，叫所造的万人都晓得他的作为。",
"8 百兽进入穴中，卧在洞内。",
"",
"——【约伯记 37】",
],
[
"17 Better is a dinner of herbs where love is, than a stalled ox and hatred therewith.",
"18 A wrathful man stirreth up strife: but he that is slow to anger appeaseth strife.",
"19 The way of the slothful man is as an hedge of thorns: but the way of the righteous is made plain.",
"20 A wise son maketh a glad father: but a foolish man despiseth his mother.",
"21 Folly is joy to him that is destitute of wisdom: but a man of understanding walketh uprightly.",
"",
"——【The Proverbs 15】",
"",
"17 吃素菜，彼此相爱，强如吃肥牛，彼此相恨。",
"18 暴怒的人挑启争端；忍怒的人止息纷争。",
"19 懒惰人的道像荆棘的篱笆；正直人的路是平坦的大道。",
"20 智慧子使父亲喜乐；愚昧人藐视母亲。",
"21 无知的人以愚妄为乐；聪明的人按正直而行。",
"",
"——【箴言 15】",
],
[
"6 And she conceived again, and bare a daughter. And God said unto him, Call her name Lo–ruhamah: for I will no more have mercy upon the house of Israel; but I will utterly take them away.",
"7 But I will have mercy upon the house of Judah, and will save them by the LORD their God, and will not save them by bow, nor by sword, nor by battle, by horses, nor by horsemen.",
"8 Now when she had weaned Lo–ruhamah, she conceived, and bare a son.",
"",
"——【Hosea 1】",
"",
"6 歌篾又怀孕生了一个女儿，耶和华对何西阿说：「给她起名叫罗路哈玛（就是不蒙怜悯的意思）；因为我必不再怜悯以色列家，决不赦免他们。",
"7 我却要怜悯犹大家，使他们靠耶和华─他们的　神得救，不使他们靠弓、刀、争战、马匹，与马兵得救。」",
"8 歌篾给罗路哈玛断奶以后，又怀孕生了一个儿子。",
"",
"——【何西阿书 1】",
],
[
"7 But God prepared a worm when the morning rose the next day, and it smote the gourd that it withered.",
"8 And it came to pass, when the sun did arise, that God prepared a vehement east wind; and the sun beat upon the head of Jonah, that he fainted, and wished in himself to die, and said, It is better for me to die than to live.",
"9 And God said to Jonah, Doest thou well to be angry for the gourd? And he said, I do well to be angry, even unto death.",
"",
"——【Jonah 4】",
"",
"7 次日黎明，　神却安排一条虫子咬这蓖麻，以致枯槁。",
"8 日头出来的时候，　神安排炎热的东风，日头曝晒约拿的头，使他发昏，他就为自己求死，说：「我死了比活着还好！」",
"9 　神对约拿说：「你因这棵蓖麻发怒合乎理吗？」他说：「我发怒以至于死，都合乎理！」",
"",
"——【约拿书 4】",
],
[
"6 And by the border of Ephraim, from the east side even unto the west side, a portion for Reuben.",
"7 And by the border of Reuben, from the east side unto the west side, a portion for Judah.",
"8 And by the border of Judah, from the east side unto the west side, shall be the offering which ye shall offer of five and twenty thousand reeds in breadth, and in length as one of the other parts, from the east side unto the west side: and the sanctuary shall be in the midst of it.",
"9 The oblation that ye shall offer unto the LORD shall be of five and twenty thousand in length, and of ten thousand in breadth.",
"10 And for them, even for the priests, shall be this holy oblation; toward the north five and twenty thousand in length, and toward the west ten thousand in breadth, and toward the east ten thousand in breadth, and toward the south five and twenty thousand in length: and the sanctuary of the LORD shall be in the midst thereof.",
"11 It shall be for the priests that are sanctified of the sons of Zadok; which have kept my charge, which went not astray when the children of Israel went astray, as the Levites went astray.",
"",
"——【The Book of the Prophet Ezekiel 48】",
"",
"6 挨着以法莲的地界，从东到西，是流便的一分。",
"7 挨着流便的地界，从东到西，是犹大的一分。",
"8 挨着犹大的地界，从东到西，必有你们所当献的供地，宽二万五千肘。从东界到西界，长短与各分之地相同，圣地当在其中。",
"9 你们献与耶和华的供地要长二万五千肘，宽一万肘。",
"10 这圣供地要归与祭司，北长二万五千肘，西宽一万肘，东宽一万肘，南长二万五千肘。耶和华的圣地当在其中。",
"11 这地要归与撒督的子孙中成为圣的祭司，就是那守我所吩咐的。当以色列人走迷的时候，他们不像那些利未人走迷了。",
"",
"——【以西结书 48】",
],
[
"5 For this cause, when I could no longer forbear, I sent to know your faith, lest by some means the tempter have tempted you, and our labour be in vain.",
"6 But now when Timotheus came from you unto us, and brought us good tidings of your faith and charity, and that ye have good remembrance of us always, desiring greatly to see us, as we also to see you:",
"",
"——【The First Epistle of Paul the Apostle to the Thessalonians 3】",
"",
"5 为此，我既不能再忍，就打发人去，要晓得你们的信心如何，恐怕那诱惑人的到底诱惑了你们，叫我们的劳苦归于徒然。",
"6 但提摩太刚才从你们那里回来，将你们信心和爱心的好消息报给我们，又说你们常常记念我们，切切的想见我们，如同我们想见你们一样。",
"",
"——【帖撒罗尼迦前书 3】",
],
[
"15 The sun and the moon shall be darkened, and the stars shall withdraw their shining.",
"16 The LORD also shall roar out of Zion, and utter his voice from Jerusalem; and the heavens and the earth shall shake: but the LORD will be the hope of his people, and the strength of the children of Israel.",
"17 So shall ye know that I am the LORD your God dwelling in Zion, my holy mountain: then shall Jerusalem be holy, and there shall no strangers pass through her any more.",
"18 And it shall come to pass in that day, that the mountains shall drop down new wine, and the hills shall flow with milk, and all the rivers of Judah shall flow with waters, and a fountain shall come forth of the house of the LORD, and shall water the valley of Shittim.",
"19 Egypt shall be a desolation, and Edom shall be a desolate wilderness, for the violence against the children of Judah, because they have shed innocent blood in their land.",
"20 But Judah shall dwell for ever, and Jerusalem from generation to generation.",
"",
"——【Joel 3】",
"",
"15 日月昏暗，星宿无光。",
"16 耶和华必从锡安吼叫，从耶路撒冷发声，天地就震动。耶和华却要作他百姓的避难所，作以色列人的保障。",
"17 你们就知道我是耶和华─你们的　神，且又住在锡安─我的圣山。那时，耶路撒冷必成为圣；外邦人不再从其中经过。",
"18 到那日，大山要滴甜酒；小山要流奶子；犹大溪河都有水流。必有泉源从耶和华的殿中流出来，滋润什亭谷。",
"19 埃及必然荒凉，以东变为悽凉的旷野，都因向犹大人所行的强暴，又因在本地流无辜人的血。",
"20 但犹大必存到永远；耶路撒冷必存到万代。",
"",
"——【约珥书 3】",
],
[
"5 Therefore I thought it necessary to exhort the brethren, that they would go before unto you, and make up beforehand your bounty, whereof ye had notice before, that the same might be ready, as a matter of bounty, and not as of covetousness.",
"6 But this I say, He which soweth sparingly shall reap also sparingly; and he which soweth bountifully shall reap also bountifully.",
"7 Every man according as he purposeth in his heart, so let him give; not grudgingly, or of necessity: for God loveth a cheerful giver.",
"8 And God is able to make all grace abound toward you; that ye, always having all sufficiency in all things, may abound to every good work:",
"9 (As it is written, He hath dispersed abroad; he hath given to the poor: his righteousness remaineth for ever.",
"10 Now he that ministereth seed to the sower both minister bread for your food, and multiply your seed sown, and increase the fruits of your righteousness;)",
"",
"——【The Second Epistle of Paul the Apostle to the Corinthians 9】",
"",
"5 因此，我想不得不求那几位弟兄先到你们那里去，把从前所应许的捐赀预备妥当，就显出你们所捐的是出于乐意，不是出于勉强。",
"6 少种的少收，多种的多收，这话是真的。",
"7 各人要随本心所酌定的，不要作难，不要勉强，因为捐得乐意的人是　神所喜爱的。",
"8 　神能将各样的恩惠多多的加给你们，使你们凡事常常充足，能多行各样善事。",
"9 如经上所记：他施舍钱财，赒济贫穷；他的仁义存到永远。",
"10 那赐种给撒种的，赐粮给人吃的，必多多加给你们种地的种子，又增添你们仁义的果子；",
"",
"——【哥林多后书 9】",
],
[
"5 Ashkelon shall see it, and fear; Gaza also shall see it, and be very sorrowful, and Ekron; for her expectation shall be ashamed; and the king shall perish from Gaza, and Ashkelon shall not be inhabited.",
"6 And a bastard shall dwell in Ashdod, and I will cut off the pride of the Philistines.",
"7 And I will take away his blood out of his mouth, and his abominations from between his teeth: but he that remaineth, even he, shall be for our God, and he shall be as a governor in Judah, and Ekron as a Jebusite.",
"8 And I will encamp about mine house because of the army, because of him that passeth by, and because of him that returneth: and no oppressor shall pass through them any more: for now have I seen with mine eyes.",
"",
"——【Zechariah 9】",
"",
"5 亚实基伦看见必惧怕；迦萨看见甚痛苦；以革伦因失了盼望蒙羞。迦萨必不再有君王；亚实基伦也不再有居民。",
"6 私生子（或译：外族人）必住在亚实突；我必除灭非利士人的骄傲。",
"7 我必除去他口中带血之肉和牙齿内可憎之物。他必作为余剩的人归与我们的　神，必在犹大像族长；以革伦人必如耶布斯人。",
"8 我必在我家的四围安营，使敌军不得任意往来，暴虐的人也不再经过，因为我亲眼看顾我的家。",
"",
"——【撒迦利亚书 9】",
],
[
"3 Incline your ear, and come unto me: hear, and your soul shall live; and I will make an everlasting covenant with you, even the sure mercies of David.",
"4 Behold, I have given him for a witness to the people, a leader and commander to the people.",
"5 Behold, thou shalt call a nation that thou knowest not, and nations that knew not thee shall run unto thee because of the LORD thy God, and for the Holy One of Israel; for he hath glorified thee.",
"6 Seek ye the LORD while he may be found, call ye upon him while he is near:",
"7 Let the wicked forsake his way, and the unrighteous man his thoughts: and let him return unto the LORD, and he will have mercy upon him; and to our God, for he will abundantly pardon.",
"",
"——【The Book of the Prophet Isaiah 55】",
"",
"3 你们当就近我来；侧耳而听，就必得活。我必与你们立永约，就是应许大卫那可靠的恩典。",
"4 我已立他作万民的见证，为万民的君王和司令。",
"5 你素不认识的国民，你也必召来；素不认识你的国民也必向你奔跑，都因耶和华─你的　神以色列的圣者，因为他已经荣耀你。",
"6 当趁耶和华可寻找的时候寻找他，相近的时候求告他。",
"7 恶人当离弃自己的道路；不义的人当除掉自己的意念。归向耶和华，耶和华就必怜恤他；当归向我们的　神，因为　神必广行赦免。",
"",
"——【以赛亚书 55】",
],
[
"7 But we were gentle among you, even as a nurse cherisheth her children:",
"8 So being affectionately desirous of you, we were willing to have imparted unto you, not the gospel of God only, but also our own souls, because ye were dear unto us.",
"9 For ye remember, brethren, our labour and travail: for labouring night and day, because we would not be chargeable unto any of you, we preached unto you the gospel of God.",
"10 Ye are witnesses, and God also, how holily and justly and unblameably we behaved ourselves among you that believe:",
"11 As ye know how we exhorted and comforted and charged every one of you, as a father doth his children,",
"12 That ye would walk worthy of God, who hath called you unto his kingdom and glory.",
"",
"——【The First Epistle of Paul the Apostle to the Thessalonians 2】",
"",
"7 只在你们中间存心温柔，如同母亲乳养自己的孩子。",
"8 我们既是这样爱你们，不但愿意将　神的福音给你们，连自己的性命也愿意给你们，因你们是我们所疼爱的。",
"9 弟兄们，你们记念我们的辛苦劳碌，昼夜做工，传　神的福音给你们，免得叫你们一人受累。",
"10 我们向你们信主的人，是何等圣洁、公义、无可指摘，有你们作见证，也有　神作见证。",
"11 你们也晓得我们怎样劝勉你们，安慰你们，嘱咐你们各人，好像父亲待自己的儿女一样，",
"12 要叫你们行事对得起那召你们进他国、得他荣耀的　神。",
"",
"——【帖撒罗尼迦前书 2】",
],
[
"1 In the year that Tartan came unto Ashdod, (when Sargon the king of Assyria sent him,) and fought against Ashdod, and took it;",
"2 At the same time spake the LORD by Isaiah the son of Amoz, saying, Go and loose the sackcloth from off thy loins, and put off thy shoe from thy foot. And he did so, walking naked and barefoot.",
"3 And the LORD said, Like as my servant Isaiah hath walked naked and barefoot three years for a sign and wonder upon Egypt and upon Ethiopia;",
"",
"——【The Book of the Prophet Isaiah 20】",
"",
"1 亚述王撒珥根打发他珥探到亚实突的那年，他珥探就攻打亚实突，将城攻取。",
"2 那时，耶和华晓谕亚摩斯的儿子以赛亚说：「你去解掉你腰间的麻布，脱下你脚上的鞋。」以赛亚就这样做，露身赤脚行走。",
"3 耶和华说：「我仆人以赛亚怎样露身赤脚行走三年，作为关乎埃及和古实的预兆奇迹。",
"",
"——【以赛亚书 20】",
],
[
"16 And let fall also some of the handfuls of purpose for her, and leave them, that she may glean them, and rebuke her not.",
"17 So she gleaned in the field until even, and beat out that she had gleaned: and it was about an ephah of barley.",
"",
"——【The Book of Ruth 2】",
"",
"16 并要从捆里抽出些来，留在地下任她拾取，不可叱吓她。」",
"17 这样，路得在田间拾取麦穗，直到晚上，将所拾取的打了，约有一伊法大麦。",
"",
"——【路得记 2】",
],
[
"7 All the labour of man is for his mouth, and yet the appetite is not filled.",
"8 For what hath the wise more than the fool? what hath the poor, that knoweth to walk before the living?",
"",
"——【Ecclesiastes 6】",
"",
"7 人的劳碌都为口腹，心里却不知足。",
"8 这样看来，智慧人比愚昧人有什么长处呢？穷人在众人面前知道如何行，有什么长处呢？",
"",
"——【传道书 6】",
],
[
"7 The tabernacle of the congregation, and the ark of the testimony, and the mercy seat that is thereupon, and all the furniture of the tabernacle,",
"8 And the table and his furniture, and the pure candlestick with all his furniture, and the altar of incense,",
"",
"——【The Second Book of Moses: Called Exodus 31】",
"",
"7 就是会幕和法柜，并其上的施恩座，与会幕中一切的器具，",
"8 桌子和桌子的器具，精金的灯台和灯台的一切器具并香坛，",
"",
"——【出埃及记 31】",
],
[
"8 Then I sent unto him, saying, There are no such things done as thou sayest, but thou feignest them out of thine own heart.",
"9 For they all made us afraid, saying, Their hands shall be weakened from the work, that it be not done. Now therefore, O God, strengthen my hands.",
"",
"——【The Book of Nehemiah 6】",
"",
"8 我就差遣人去见他，说：「你所说的这事，一概没有，是你心里捏造的。」",
"9 他们都要使我们惧怕，意思说，他们的手必软弱，以致工作不能成就。　神啊，求你坚固我的手。",
"",
"——【尼希米记 6】",
],
[
"6 He hath made me also a byword of the people; and aforetime I was as a tabret.",
"7 Mine eye also is dim by reason of sorrow, and all my members are as a shadow.",
"8 Upright men shall be astonied at this, and the innocent shall stir up himself against the hypocrite.",
"9 The righteous also shall hold on his way, and he that hath clean hands shall be stronger and stronger.",
"",
"——【The Book of Job 17】",
"",
"6 　神使我作了民中的笑谈；他们也吐唾沫在我脸上。",
"7 我的眼睛因忧愁昏花；我的百体好像影儿。",
"8 正直人因此必惊奇；无辜的人要兴起攻击不敬虔之辈。",
"9 然而，义人要持守所行的道；手洁的人要力上加力。",
"",
"——【约伯记 17】",
],
[
"9 Then spake the Lord to Paul in the night by a vision, Be not afraid, but speak, and hold not thy peace:",
"10 For I am with thee, and no man shall set on thee to hurt thee: for I have much people in this city.",
"11 And he continued there a year and six months, teaching the word of God among them.",
"12 And when Gallio was the deputy of Achaia, the Jews made insurrection with one accord against Paul, and brought him to the judgment seat,",
"13 Saying, This fellow persuadeth men to worship God contrary to the law.",
"",
"——【The Acts of the Apostles 18】",
"",
"9 夜间，主在异象中对保罗说：不要怕，只管讲，不要闭口，",
"10 有我与你同在，必没有人下手害你，因为在这城里我有许多的百姓。",
"11 保罗在那里住了一年零六个月，将　神的道教训他们。",
"12 到迦流作亚该亚方伯的时候，犹太人同心起来攻击保罗，拉他到公堂，",
"13 说：这个人劝人不按着律法敬拜　神。",
"",
"——【使徒行传 18】",
],
[
"2 And the king said again unto Esther on the second day at the banquet of wine, What is thy petition, queen Esther? and it shall be granted thee: and what is thy request? and it shall be performed, even to the half of the kingdom.",
"3 Then Esther the queen answered and said, If I have found favour in thy sight, O king, and if it please the king, let my life be given me at my petition, and my people at my request:",
"4 For we are sold, I and my people, to be destroyed, to be slain, and to perish. But if we had been sold for bondmen and bondwomen, I had held my tongue, although the enemy could not countervail the king's damage.",
"5 Then the king Ahasuerus answered and said unto Esther the queen, Who is he, and where is he, that durst presume in his heart to do so?",
"6 And Esther said, The adversary and enemy is this wicked Haman. Then Haman was afraid before the king and the queen.",
"",
"——【The Book of Esther 7】",
"",
"2 这第二次在酒席筵前，王又问以斯帖说：「王后以斯帖啊，你要什么，我必赐给你；你求什么，就是国的一半也必为你成就。」",
"3 王后以斯帖回答说：「我若在王眼前蒙恩，王若以为美，我所愿的，是愿王将我的性命赐给我；我所求的，是求王将我的本族赐给我。",
"4 因我和我的本族被卖了，要剪除杀戮灭绝我们。我们若被卖为奴为婢，我也闭口不言；但王的损失，敌人万不能补足。」",
"5 亚哈随鲁王问王后以斯帖说：「擅敢起意如此行的是谁？这人在哪里呢？」",
"6 以斯帖说：「仇人敌人就是这恶人哈曼！」哈曼在王和王后面前就甚惊惶。",
"",
"——【以斯帖记 7】",
],
[
"1 In the first year of Darius the son of Ahasuerus, of the seed of the Medes, which was made king over the realm of the Chaldeans;",
"2 In the first year of his reign I Daniel understood by books the number of the years, whereof the word of the LORD came to Jeremiah the prophet, that he would accomplish seventy years in the desolations of Jerusalem.",
"3 And I set my face unto the Lord God, to seek by prayer and supplications, with fasting, and sackcloth, and ashes:",
"4 And I prayed unto the LORD my God, and made my confession, and said, O Lord, the great and dreadful God, keeping the covenant and mercy to them that love him, and to them that keep his commandments;",
"5 We have sinned, and have committed iniquity, and have done wickedly, and have rebelled, even by departing from thy precepts and from thy judgments:",
"",
"——【The Book of Daniel 9】",
"",
"1 玛代族亚哈随鲁的儿子大利乌立为迦勒底国的王元年，",
"2 就是他在位第一年，我但以理从书上得知耶和华的话临到先知耶利米，论耶路撒冷荒凉的年数，七十年为满。",
"3 我便禁食，披麻蒙灰，定意向主　神祈祷恳求。",
"4 我向耶和华─我的　神祈祷、认罪，说：「主啊，大而可畏的　神，向爱主、守主诫命的人守约施慈爱。",
"5 我们犯罪作孽，行恶叛逆，偏离你的诫命典章，",
"",
"——【但以理书 9】",
],
[
"7 But Jesus withdrew himself with his disciples to the sea: and a great multitude from Galilee followed him, and from Judæa,",
"8 And from Jerusalem, and from Idumaea, and from beyond Jordan; and they about Tyre and Sidon, a great multitude, when they had heard what great things he did, came unto him.",
"9 And he spake to his disciples, that a small ship should wait on him because of the multitude, lest they should throng him.",
"10 For he had healed many; insomuch that they pressed upon him for to touch him, as many as had plagues.",
"11 And unclean spirits, when they saw him, fell down before him, and cried, saying, Thou art the Son of God.",
"",
"——【The Gospel According to Saint Mark 3】",
"",
"7 耶稣和门徒退到海边去，有许多人从加利利跟随他。",
"8 还有许多人听见他所做的大事，就从犹太、耶路撒冷、以土买、约旦河外，并泰尔、西顿的四方来到他那里。",
"9 他因为人多，就吩咐门徒叫一只小船伺候着，免得众人拥挤他。",
"10 他治好了许多人，所以凡有灾病的，都挤进来要摸他。",
"11 污鬼无论何时看见他，就俯伏在他面前，喊着说：你是　神的儿子。",
"",
"——【马可福音 3】",
],
[
"11 Moab hath been at ease from his youth, and he hath settled on his lees, and hath not been emptied from vessel to vessel, neither hath he gone into captivity: therefore his taste remained in him, and his scent is not changed.",
"12 Therefore, behold, the days come, saith the LORD, that I will send unto him wanderers, that shall cause him to wander, and shall empty his vessels, and break their bottles.",
"13 And Moab shall be ashamed of Chemosh, as the house of Israel was ashamed of Beth–el their confidence.",
"",
"——【The Book of the Prophet Jeremiah 48】",
"",
"11 摩押自幼年以来常享安逸，如酒在渣滓上澄清，没有从这器皿倒在那器皿里，也未曾被掳去。因此，它的原味尚存，香气未变。",
"12 耶和华说：「日子将到，我必打发倒酒的往他那里去，将他倒出来，倒空他的器皿，打碎他的罈子。",
"13 摩押必因基抹羞愧，像以色列家从前倚靠伯特利的神羞愧一样。",
"",
"——【耶利米书 48】",
],
[
"7 Behold, therefore I will stretch out mine hand upon thee, and will deliver thee for a spoil to the heathen; and I will cut thee off from the people, and I will cause thee to perish out of the countries: I will destroy thee; and thou shalt know that I am the LORD.",
"8 Thus saith the Lord GOD; Because that Moab and Seir do say, Behold, the house of Judah is like unto all the heathen;",
"9 Therefore, behold, I will open the side of Moab from the cities, from his cities which are on his frontiers, the glory of the country, Beth–jeshimoth, Baal–meon, and Kiriathaim,",
"",
"——【The Book of the Prophet Ezekiel 25】",
"",
"7 所以我伸手攻击你，将你交给列国作为掳物。我必从万民中剪除你，使你从万国中败亡。我必除灭你，你就知道我是耶和华。」",
"8 主耶和华如此说：「因摩押和西珥人说：『看哪，犹大家与列国无异』，",
"9 所以我要破开摩押边界上的城邑，就是摩押人看为本国之荣耀的伯‧耶西末、巴力‧免、基列亭，",
"",
"——【以西结书 25】",
],
[
"1 Behold, how good and how pleasant it is for brethren to dwell together in unity!",
"2 It is like the precious ointment upon the head, that ran down upon the beard, even Aaron's beard: that went down to the skirts of his garments;",
"",
"——【The Book of Psalms 133】",
"",
"1 （大卫上行之诗。）看哪，弟兄和睦同居是何等地善，何等地美！",
"2 这好比那贵重的油浇在亚伦的头上，流到胡须，又流到他的衣襟；",
"",
"——【诗篇 133】",
],
[
"6 Better is an handful with quietness, than both the hands full with travail and vexation of spirit.",
"7 Then I returned, and I saw vanity under the sun.",
"",
"——【Ecclesiastes 4】",
"",
"6 满了一把，得享安静，强如满了两把，劳碌捕风。",
"7 我又转念，见日光之下有一件虚空的事：",
"",
"——【传道书 4】",
],
[
"42 And those that were numbered of the families of the sons of Merari, throughout their families, by the house of their fathers,",
"43 From thirty years old and upward even unto fifty years old, every one that entereth into the service, for the work in the tabernacle of the congregation,",
"44 Even those that were numbered of them after their families, were three thousand and two hundred.",
"",
"——【The Fourth Book of Moses: Called Numbers 4】",
"",
"42 米拉利子孙中各族被数的，照着家室、宗族，",
"43 从三十岁直到五十岁，凡前来任职、在会幕里办事的，共有三千二百名。",
"44 并入上一节",
"",
"——【民数记 4】",
],
[
"1 And it came to pass afterward, that he went throughout every city and village, preaching and shewing the glad tidings of the kingdom of God: and the twelve were with him,",
"2 And certain women, which had been healed of evil spirits and infirmities, Mary called Magdalene, out of whom went seven devils,",
"",
"——【The Gospel According to Saint Luke 8】",
"",
"1 过了不多日，耶稣周游各城各乡传道，宣讲　神国的福音。和他同去的有十二个门徒，",
"2 还有被恶鬼所附、被疾病所累、已经治好的几个妇女，内中有称为抹大拉的马利亚，曾有七个鬼从她身上赶出来，",
"",
"——【路加福音 8】",
],
];
