var bible31_global=[
[
"13 Remember the word which Moses the servant of the LORD commanded you, saying, The LORD your God hath given you rest, and hath given you this land.",
"14 Your wives, your little ones, and your cattle, shall remain in the land which Moses gave you on this side Jordan; but ye shall pass before your brethren armed, all the mighty men of valour, and help them;",
"15 Until the LORD have given your brethren rest, as he hath given you, and they also have possessed the land which the LORD your God giveth them: then ye shall return unto the land of your possession, and enjoy it, which Moses the LORD'S servant gave you on this side Jordan toward the sunrising.",
"16 And they answered Joshua, saying, All that thou commandest us we will do, and whithersoever thou sendest us, we will go.",
"17 According as we hearkened unto Moses in all things, so will we hearken unto thee: only the LORD thy God be with thee, as he was with Moses.",
"18 Whosoever he be that doth rebel against thy commandment, and will not hearken unto thy words in all that thou commandest him, he shall be put to death: only be strong and of a good courage.",
"",
"——【The Book of Joshua 1】",
"",
"13 「你们要追念耶和华的仆人摩西所吩咐你们的话说：『耶和华─你们的　神使你们得享平安，也必将这地赐给你们。』",
"14 你们的妻子、孩子，和牲畜都可以留在约旦河东、摩西所给你们的地；但你们中间一切大能的勇士都要带著兵器在你们的弟兄前面过去，帮助他们，",
"15 等到耶和华使你们的弟兄像你们一样得享平安，并且得著耶和华─你们　神所赐他们为业之地，那时才可以回你们所得之地，承受为业，就是耶和华的仆人摩西在约旦河东、向日出之地所给你们的。」",
"16 他们回答约书亚说：「你所吩咐我们行的，我们都必行；你所差遣我们去的，我们都必去。",
"17 我们从前在一切事上怎样听从摩西，现在也必照样听从你；惟愿耶和华─你的　神与你同在，像与摩西同在一样。",
"18 无论什么人违背你的命令，不听从你所吩咐他的一切话，就必治死他。你只要刚强壮胆！」",
"",
"——【约书亚记 1】",
],
[
"2 For by it the elders obtained a good report.",
"3 Through faith we understand that the worlds were framed by the word of God, so that things which are seen were not made of things which do appear.",
"4 By faith Abel offered unto God a more excellent sacrifice than Cain, by which he obtained witness that he was righteous, God testifying of his gifts: and by it he being dead yet speaketh.",
"5 By faith Enoch was translated that he should not see death; and was not found, because God had translated him: for before his translation he had this testimony, that he pleased God.",
"6 But without faith it is impossible to please him: for he that cometh to God must believe that he is, and that he is a rewarder of them that diligently seek him.",
"",
"——【The Epistle of Paul the Apostle to the Hebrews 11】",
"",
"2 古人在这信上得了美好的证据。",
"3 我们因著信，就知道诸世界是借　神话造成的；这样，所看见的，并不是从显然之物造出来的。",
"4 亚伯因著信，献祭与　神，比该隐所献的更美，因此便得了称义的见证，就是　神指他礼物作的见证。他虽然死了，却因这信，仍旧说话。",
"5 以诺因著信，被接去，不至于见死，人也找不著他，因为　神已经把他接去了；只是他被接去以先，已经得了　神喜悦他的明证。",
"6 人非有信，就不能得　神的喜悦；因为到　神面前来的人必须信有　神，且信他赏赐那寻求他的人。",
"",
"——【希伯来书 11】",
],
[
"1 When thou goest out to battle against thine enemies, and seest horses, and chariots, and a people more than thou, be not afraid of them: for the LORD thy God is with thee, which brought thee up out of the land of Egypt.",
"2 And it shall be, when ye are come nigh unto the battle, that the priest shall approach and speak unto the people,",
"3 And shall say unto them, Hear, O Israel, ye approach this day unto battle against your enemies: let not your hearts faint, fear not, and do not tremble, neither be ye terrified because of them;",
"4 For the LORD your God is he that goeth with you, to fight for you against your enemies, to save you.",
"5 And the officers shall speak unto the people, saying, What man is there that hath built a new house, and hath not dedicated it? let him go and return to his house, lest he die in the battle, and another man dedicate it.",
"6 And what man is he that hath planted a vineyard, and hath not yet eaten of it? let him also go and return unto his house, lest he die in the battle, and another man eat of it.",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 20】",
"",
"1 「你出去与仇敌争战的时候，看见马匹、车辆，并有比你多的人民，不要怕他们，因为领你出埃及地的耶和华─你　神与你同在。",
"2 你们将要上阵的时候，祭司要到百姓面前宣告",
"3 说：『以色列人哪，你们当听，你们今日将要与仇敌争战，不要胆怯，不要惧怕战兢，也不要因他们惊恐；",
"4 因为耶和华─你们的　神与你们同去，要为你们与仇敌争战，拯救你们。』",
"5 官长也要对百姓宣告说：『谁建造房屋，尚未奉献，他可以回家去，恐怕他阵亡，别人去奉献。",
"6 谁种葡萄园，尚未用所结的果子，他可以回家去，恐怕他阵亡，别人去用。",
"",
"——【申命记 20】",
],
[
"13 When Jesus heard of it, he departed thence by ship into a desert place apart: and when the people had heard thereof, they followed him on foot out of the cities.",
"14 And Jesus went forth, and saw a great multitude, and was moved with compassion toward them, and he healed their sick.",
"15 And when it was evening, his disciples came to him, saying, This is a desert place, and the time is now past; send the multitude away, that they may go into the villages, and buy themselves victuals.",
"",
"——【The Gospel According to Saint Matthew 14】",
"",
"13 耶稣听见了，就上船从那里独自退到野地里去。众人听见，就从各城里步行跟随他。",
"14 耶稣出来，见有许多的人，就怜悯他们，治好了他们的病人。",
"15 天将晚的时候，门徒进前来，说：这是野地，时候已经过了，请叫众人散开，他们好往村子里去，自己买吃的。",
"",
"——【马太福音 14】",
],
[
"1 And if a soul sin, and hear the voice of swearing, and is a witness, whether he hath seen or known of it; if he do not utter it, then he shall bear his iniquity.",
"2 Or if a soul touch any unclean thing, whether it be a carcase of an unclean beast, or a carcase of unclean cattle, or the carcase of unclean creeping things, and if it be hidden from him; he also shall be unclean, and guilty.",
"",
"——【The Third Book of Moses: Called Leviticus 5】",
"",
"1 「若有人听见发誓的声音（或作：若有人听见叫人发誓的声音），他本是见证，却不把所看见的、所知道的说出来，这就是罪；他要担当他的罪孽。",
"2 或是有人摸了不洁的物，无论是不洁的死兽，是不洁的死畜，是不洁的死虫，他却不知道，因此成了不洁，就有了罪。",
"",
"——【利未记 5】",
],
[
"11 For whosoever exalteth himself shall be abased; and he that humbleth himself shall be exalted.",
"12 Then said he also to him that bade him, When thou makest a dinner or a supper, call not thy friends, nor thy brethren, neither thy kinsmen, nor thy rich neighbours; lest they also bid thee again, and a recompence be made thee.",
"13 But when thou makest a feast, call the poor, the maimed, the lame, the blind:",
"14 And thou shalt be blessed; for they cannot recompense thee: for thou shalt be recompensed at the resurrection of the just.",
"",
"——【The Gospel According to Saint Luke 14】",
"",
"11 因为，凡自高的，必降为卑，自卑的，必升为高。",
"12 耶稣又对请他的人说：你摆设午饭或晚饭，不要请你的朋友、弟兄、亲属，和富足的邻舍，恐怕他们也请你，你就得了报答。",
"13 你摆设筵席，倒要请那贫穷的、残废的、瘸腿的、瞎眼的，你就有福了！",
"14 因为他们没有什么可报答你。到义人复活的时候，你要得著报答。",
"",
"——【路加福音 14】",
],
[
"19 And he blessed him, and said, Blessed be Abram of the most high God, possessor of heaven and earth:",
"20 And blessed be the most high God, which hath delivered thine enemies into thy hand. And he gave him tithes of all.",
"",
"——【The First Book of Moses: Called Genesis 14】",
"",
"19 他为亚伯兰祝福，说：「愿天地的主、至高的　神赐福与亚伯兰！",
"20 至高的　神把敌人交在你手里，是应当称颂的！」亚伯兰就把所得的拿出十分之一来，给麦基洗德。",
"",
"——【创世记 14】",
],
[
"14 And thou shalt be blessed; for they cannot recompense thee: for thou shalt be recompensed at the resurrection of the just.",
"15 And when one of them that sat at meat with him heard these things, he said unto him, Blessed is he that shall eat bread in the kingdom of God.",
"16 Then said he unto him, A certain man made a great supper, and bade many:",
"",
"——【The Gospel According to Saint Luke 14】",
"",
"14 因为他们没有什么可报答你。到义人复活的时候，你要得著报答。",
"15 同席的有一人听见这话，就对耶稣说：在　神国里吃饭的有福了！",
"16 耶稣对他说：有一人摆设大筵席，请了许多客。",
"",
"——【路加福音 14】",
],
[
"2 And found a certain Jew named Aquila, born in Pontus, lately come from Italy, with his wife Priscilla; (because that Claudius had commanded all Jews to depart from Rome:) and came unto them.",
"3 And because he was of the same craft, he abode with them, and wrought: for by their occupation they were tentmakers.",
"",
"——【The Acts of the Apostles 18】",
"",
"2 遇见一个犹太人，名叫亚居拉，他生在本都；因为革老丢命犹太人都离开罗马，新近带著妻百基拉，从意大利来。保罗就投奔了他们。",
"3 他们本是制造帐棚为业。保罗因与他们同业，就和他们同住做工。",
"",
"——【使徒行传 18】",
],
[
"1 Then the prophets, Haggai the prophet, and Zechariah the son of Iddo, prophesied unto the Jews that were in Judah and Jerusalem in the name of the God of Israel, even unto them.",
"2 Then rose up Zerubbabel the son of Shealtiel, and Jeshua the son of Jozadak, and began to build the house of God which is at Jerusalem: and with them were the prophets of God helping them.",
"3 At the same time came to them Tatnai, governor on this side the river, and Shethar–boznai, and their companions, and said thus unto them, Who hath commanded you to build this house, and to make up this wall?",
"4 Then said we unto them after this manner, What are the names of the men that make this building?",
"5 But the eye of their God was upon the elders of the Jews, that they could not cause them to cease, till the matter came to Darius: and then they returned answer by letter concerning this matter.",
"",
"——【Ezra 5】",
"",
"1 那时，先知哈该和易多的孙子撒迦利亚奉以色列　神的名向犹大和耶路撒冷的犹大人说劝勉的话。",
"2 于是撒拉铁的儿子所罗巴伯和约萨达的儿子耶书亚都起来动手建造耶路撒冷　神的殿，有　神的先知在那里帮助他们。",
"3 当时河西的总督达乃和示他•波斯乃，并他们的同党来问说：「谁降旨让你们建造这殿，修成这墙呢？」",
"4 我们便告诉他们建造这殿的人叫什么名字。",
"5 　神的眼目看顾犹大的长老，以致总督等没有叫他们停工，直到这事奏告大利乌，得著他的回谕。",
"",
"——【以斯拉记 5】",
],
[
"1 And in that day seven women shall take hold of one man, saying, We will eat our own bread, and wear our own apparel: only let us be called by thy name, to take away our reproach.",
"2 In that day shall the branch of the LORD be beautiful and glorious, and the fruit of the earth shall be excellent and comely for them that are escaped of Israel.",
"3 And it shall come to pass, that he that is left in Zion, and he that remaineth in Jerusalem, shall be called holy, even every one that is written among the living in Jerusalem:",
"4 When the Lord shall have washed away the filth of the daughters of Zion, and shall have purged the blood of Jerusalem from the midst thereof by the spirit of judgment, and by the spirit of burning.",
"5 And the LORD will create upon every dwelling place of mount Zion, and upon her assemblies, a cloud and smoke by day, and the shining of a flaming fire by night: for upon all the glory shall be a defence.",
"",
"——【The Book of the Prophet Isaiah 4】",
"",
"1 在那日，七个女人必拉住一个男人，说：「我们吃自己的食物，穿自己的衣服，但求你许我们归你名下；求你除掉我们的羞耻。」",
"2 到那日，耶和华发生的苗必华美尊荣，地的出产必为以色列逃脱的人显为荣华茂盛。",
"3 主以公义的灵和焚烧的灵，将锡安女子的污秽洗去，又将耶路撒冷中杀人的血除净。那时，剩在锡安、留在耶路撒冷的，就是一切住耶路撒冷、在生命册上记名的，必称为圣。",
"4 并入上一节",
"5 耶和华也必在锡安全山，并各会众以上，使白日有烟云，黑夜有火焰的光。因为在全荣耀之上必有遮蔽。",
"",
"——【以赛亚书 4】",
],
[
"1 Awake, awake; put on thy strength, O Zion; put on thy beautiful garments, O Jerusalem, the holy city: for henceforth there shall no more come into thee the uncircumcised and the unclean.",
"2 Shake thyself from the dust; arise, and sit down, O Jerusalem: loose thyself from the bands of thy neck, O captive daughter of Zion.",
"3 For thus saith the LORD, Ye have sold yourselves for nought; and ye shall be redeemed without money.",
"4 For thus saith the Lord GOD, My people went down aforetime into Egypt to sojourn there; and the Assyrian oppressed them without cause.",
"5 Now therefore, what have I here, saith the LORD, that my people is taken away for nought? they that rule over them make them to howl, saith the LORD; and my name continually every day is blasphemed.",
"6 Therefore my people shall know my name: therefore they shall know in that day that I am he that doth speak: behold, it is I.",
"",
"——【The Book of the Prophet Isaiah 52】",
"",
"1 锡安哪，兴起！兴起！披上你的能力！圣城耶路撒冷啊，穿上你华美的衣服！因为从今以后，未受割礼、不洁净的必不再进入你中间。",
"2 耶路撒冷啊，要抖下尘土！起来坐在位上！锡安被掳的居民（原文是女子）哪，要解开你颈项的锁鍊！",
"3 耶和华如此说：你们是无价被卖的，也必无银被赎。",
"4 主耶和华如此说：起先我的百姓下到埃及，在那里寄居，又有亚述人无故欺压他们。",
"5 耶和华说：我的百姓既是无价被掳去，如今我在这里做什么呢？耶和华说：辖制他们的人呼叫，我的名整天受亵渎。",
"6 所以，我的百姓必知道我的名；到那日他们必知道说这话的就是我。看哪，是我！",
"",
"——【以赛亚书 52】",
],
[
"10 And the LORD turned the captivity of Job, when he prayed for his friends: also the LORD gave Job twice as much as he had before.",
"11 Then came there unto him all his brethren, and all his sisters, and all they that had been of his acquaintance before, and did eat bread with him in his house: and they bemoaned him, and comforted him over all the evil that the LORD had brought upon him: every man also gave him a piece of money, and every one an earring of gold.",
"",
"——【The Book of Job 42】",
"",
"10 约伯为他的朋友祈祷。耶和华就使约伯从苦境（原文是掳掠）转回，并且耶和华赐给他的比他从前所有的加倍。",
"11 约伯的弟兄、姊妹，和以先所认识的人都来见他，在他家里一同吃饭；又论到耶和华所降与他的一切灾祸，都为他悲伤安慰他。每人也送他一块银子和一个金环。",
"",
"——【约伯记 42】",
],
[
"11 Pass through the host, and command the people, saying, Prepare you victuals; for within three days ye shall pass over this Jordan, to go in to possess the land, which the LORD your God giveth you to possess it.",
"12 And to the Reubenites, and to the Gadites, and to half the tribe of Manasseh, spake Joshua, saying,",
"13 Remember the word which Moses the servant of the LORD commanded you, saying, The LORD your God hath given you rest, and hath given you this land.",
"14 Your wives, your little ones, and your cattle, shall remain in the land which Moses gave you on this side Jordan; but ye shall pass before your brethren armed, all the mighty men of valour, and help them;",
"15 Until the LORD have given your brethren rest, as he hath given you, and they also have possessed the land which the LORD your God giveth them: then ye shall return unto the land of your possession, and enjoy it, which Moses the LORD'S servant gave you on this side Jordan toward the sunrising.",
"16 And they answered Joshua, saying, All that thou commandest us we will do, and whithersoever thou sendest us, we will go.",
"",
"——【The Book of Joshua 1】",
"",
"11 「你们要走遍营中，吩咐百姓说：『当预备食物；因为三日之内你们要过这约旦河，进去得耶和华─你们　神赐你们为业之地。』」",
"12 约书亚对流便人、迦得人，和玛拿西半支派的人说：",
"13 「你们要追念耶和华的仆人摩西所吩咐你们的话说：『耶和华─你们的　神使你们得享平安，也必将这地赐给你们。』",
"14 你们的妻子、孩子，和牲畜都可以留在约旦河东、摩西所给你们的地；但你们中间一切大能的勇士都要带著兵器在你们的弟兄前面过去，帮助他们，",
"15 等到耶和华使你们的弟兄像你们一样得享平安，并且得著耶和华─你们　神所赐他们为业之地，那时才可以回你们所得之地，承受为业，就是耶和华的仆人摩西在约旦河东、向日出之地所给你们的。」",
"16 他们回答约书亚说：「你所吩咐我们行的，我们都必行；你所差遣我们去的，我们都必去。",
"",
"——【约书亚记 1】",
],
[
"3 And gathered them out of the lands, from the east, and from the west, from the north, and from the south.",
"4 They wandered in the wilderness in a solitary way; they found no city to dwell in.",
"5 Hungry and thirsty, their soul fainted in them.",
"6 Then they cried unto the LORD in their trouble, and he delivered them out of their distresses.",
"7 And he led them forth by the right way, that they might go to a city of habitation.",
"8 Oh that men would praise the LORD for his goodness, and for his wonderful works to the children of men!",
"",
"——【The Book of Psalms 107】",
"",
"3 从各地，从东从西，从南从北，所招聚来的。",
"4 他们在旷野荒地漂流，寻不见可住的城邑，",
"5 又饥又渴，心里发昏。",
"6 于是，他们在苦难中哀求耶和华；他从他们的祸患中搭救他们，",
"7 又领他们行走直路，使他们往可居住的城邑。",
"8 但愿人因耶和华的慈爱和他向人所行的奇事都称讚他；",
"",
"——【诗篇 107】",
],
[
"1 And the child Samuel ministered unto the LORD before Eli. And the word of the LORD was precious in those days; there was no open vision.",
"2 And it came to pass at that time, when Eli was laid down in his place, and his eyes began to wax dim, that he could not see;",
"3 And ere the lamp of God went out in the temple of the LORD, where the ark of God was, and Samuel was laid down to sleep;",
"4 That the LORD called Samuel: and he answered, Here am I.",
"",
"——【The First Book of Samuel 3】",
"",
"1 童子撒母耳在以利面前事奉耶和华。当那些日子，耶和华的言语稀少，不常有默示。",
"2 一日，以利睡卧在自己的地方；他眼目昏花，看不分明。",
"3 　神的灯在　神耶和华殿内约柜那里，还没有熄灭，撒母耳已经睡了。",
"4 耶和华呼唤撒母耳。撒母耳说：「我在这里！」",
"",
"——【撒母耳记上 3】",
],
[
"11 Doth not the ear try words? and the mouth taste his meat?",
"12 With the ancient is wisdom; and in length of days understanding.",
"13 With him is wisdom and strength, he hath counsel and understanding.",
"14 Behold, he breaketh down, and it cannot be built again: he shutteth up a man, and there can be no opening.",
"15 Behold, he withholdeth the waters, and they dry up: also he sendeth them out, and they overturn the earth.",
"",
"——【The Book of Job 12】",
"",
"11 耳朵岂不试验言语，正如上膛尝食物吗？",
"12 年老的有智慧；寿高的有知识。",
"13 在　神有智慧和能力；他有谋略和知识。",
"14 他拆毁的，就不能再建造；他捆住人，便不得开释。",
"15 他把水留住，水便枯干；他再发出水来，水就翻地。",
"",
"——【约伯记 12】",
],
[
"26 And when they had sung an hymn, they went out into the mount of Olives.",
"27 And Jesus saith unto them, All ye shall be offended because of me this night: for it is written, I will smite the shepherd, and the sheep shall be scattered.",
"28 But after that I am risen, I will go before you into Galilee.",
"29 But Peter said unto him, Although all shall be offended, yet will not I.",
"",
"——【The Gospel According to Saint Mark 14】",
"",
"26 他们唱了诗，就出来，往橄榄山去。",
"27 耶稣对他们说：你们都要跌倒了，因为经上记著说：我要击打牧人，羊就分散了。",
"28 但我复活以后，要在你们以先往加利利去。",
"29 彼得说：众人虽然跌倒，我总不能。",
"",
"——【马可福音 14】",
],
[
"4 Yet I am the LORD thy God from the land of Egypt, and thou shalt know no god but me: for there is no saviour beside me.",
"5 I did know thee in the wilderness, in the land of great drought.",
"6 According to their pasture, so were they filled; they were filled, and their heart was exalted; therefore have they forgotten me.",
"7 Therefore I will be unto them as a lion: as a leopard by the way will I observe them:",
"8 I will meet them as a bear that is bereaved of her whelps, and will rend the caul of their heart, and there will I devour them like a lion: the wild beast shall tear them.",
"",
"——【Hosea 13】",
"",
"4 自从你出埃及地以来，我就是耶和华─你的　神。在我以外，你不可认识别神；除我以外并没有救主。",
"5 我曾在旷野干旱之地认识你。",
"6 这些民照我所赐的食物得了饱足；既得饱足，心就高傲，忘记了我。",
"7 因此，我向他们如狮子，又如豹伏在道旁。",
"8 我遇见他们必像丢崽子的母熊，撕裂他们的胸膛（或译：心膜）。在那里，我必像母狮吞吃他们；野兽必撕裂他们。",
"",
"——【何西阿书 13】",
],
[
"16 Know that thus saith the LORD of the king that sitteth upon the throne of David, and of all the people that dwelleth in this city, and of your brethren that are not gone forth with you into captivity;",
"17 Thus saith the LORD of hosts; Behold, I will send upon them the sword, the famine, and the pestilence, and will make them like vile figs, that cannot be eaten, they are so evil.",
"18 And I will persecute them with the sword, with the famine, and with the pestilence, and will deliver them to be removed to all the kingdoms of the earth, to be a curse, and an astonishment, and an hissing, and a reproach, among all the nations whither I have driven them:",
"19 Because they have not hearkened to my words, saith the LORD, which I sent unto them by my servants the prophets, rising up early and sending them; but ye would not hear, saith the LORD.",
"20 Hear ye therefore the word of the LORD, all ye of the captivity, whom I have sent from Jerusalem to Babylon:",
"",
"——【The Book of the Prophet Jeremiah 29】",
"",
"16 所以耶和华论到坐大卫宝座的王和住在这城里的一切百姓，就是未曾与你们一同被掳的弟兄，",
"17 万军之耶和华如此说：『看哪，我必使刀剑、饥荒、瘟疫临到他们，使他们像极坏的无花果，坏得不可吃。",
"18 我必用刀剑、饥荒、瘟疫追赶他们，使他们在天下万国抛来抛去，在我所赶他们到的各国中，令人咒诅、惊骇、嗤笑、羞辱。",
"19 耶和华说：这是因为他们没有听从我的话，就是我从早起来差遣我仆人众先知去说的，无奈他们不听。这是耶和华说的。",
"20 所以你们一切被掳去的，就是我从耶路撒冷打发到巴比伦去的，当听耶和华的话。』」",
"",
"——【耶利米书 29】",
],
[
"5 The LORD is the portion of mine inheritance and of my cup: thou maintainest my lot.",
"6 The lines are fallen unto me in pleasant places; yea, I have a goodly heritage.",
"7 I will bless the LORD, who hath given me counsel: my reins also instruct me in the night seasons.",
"8 I have set the LORD always before me: because he is at my right hand, I shall not be moved.",
"",
"——【The Book of Psalms 16】",
"",
"5 耶和华是我的产业，是我杯中的分；我所得的，你为我持守。",
"6 用绳量给我的地界，坐落在佳美之处；我的产业实在美好。",
"7 我必称颂那指教我的耶和华；我的心肠在夜间也警戒我。",
"8 我将耶和华常摆在我面前，因他在我右边，我便不致摇动。",
"",
"——【诗篇 16】",
],
[
"15 And after those days we took up our carriages, and went up to Jerusalem.",
"16 There went with us also certain of the disciples of Cæsarea, and brought with them one Mnason of Cyprus, an old disciple, with whom we should lodge.",
"17 And when we were come to Jerusalem, the brethren received us gladly.",
"18 And the day following Paul went in with us unto James; and all the elders were present.",
"",
"——【The Acts of the Apostles 21】",
"",
"15 过了几日，我们收拾行李上耶路撒冷去。",
"16 有凯撒利亚的几个门徒和我们同去，带我们到一个久为（久为：或作老）门徒的家里，叫我们与他同住；他名叫拿孙，是塞浦路斯人。",
"17 到了耶路撒冷，弟兄们欢欢喜喜的接待我们。",
"18 第二天，保罗同我们去见雅各；长老们也都在那里。",
"",
"——【使徒行传 21】",
],
[
"29 For the gifts and calling of God are without repentance.",
"30 For as ye in times past have not believed God, yet have now obtained mercy through their unbelief:",
"31 Even so have these also now not believed, that through your mercy they also may obtain mercy.",
"32 For God hath concluded them all in unbelief, that he might have mercy upon all.",
"",
"——【The Epistle of Paul the Apostle to the Romans 11】",
"",
"29 因为　神的恩赐和选召是没有后悔的。",
"30 你们从前不顺服　神，如今因他们的不顺服，你们倒蒙了怜恤。",
"31 这样，他们也是不顺服，叫他们因著施给你们的怜恤，现在也就蒙怜恤。",
"32 因为　神将众人都圈在不顺服之中，特意要怜恤众人。",
"",
"——【罗马书 11】",
],
[
"1 In Judah is God known: his name is great in Israel.",
"2 In Salem also is his tabernacle, and his dwelling place in Zion.",
"3 There brake he the arrows of the bow, the shield, and the sword, and the battle. Selah.",
"4 Thou art more glorious and excellent than the mountains of prey.",
"5 The stouthearted are spoiled, they have slept their sleep: and none of the men of might have found their hands.",
"",
"——【The Book of Psalms 76】",
"",
"1 （亚萨的诗歌，交与伶长。用丝弦的乐器。）在犹大，　神为人所认识；在以色列，他的名为大。",
"2 在撒冷有他的帐幕；在锡安有他的居所。",
"3 他在那里折断弓上的火箭，并盾牌、刀剑，和争战的兵器。（细拉）",
"4 你从有野食之山而来，有光华和荣美。",
"5 心中勇敢的人都被抢夺；他们睡了长觉，没有一个英雄能措手。",
"",
"——【诗篇 76】",
],
[
"5 And spared not the old world, but saved Noah the eighth person, a preacher of righteousness, bringing in the flood upon the world of the ungodly;",
"6 And turning the cities of Sodom and Gomorrha into ashes condemned them with an overthrow, making them an ensample unto those that after should live ungodly;",
"7 And delivered just Lot, vexed with the filthy conversation of the wicked:",
"8 (For that righteous man dwelling among them, in seeing and hearing, vexed his righteous soul from day to day with their unlawful deeds;)",
"",
"——【The Second General Epistle of Peter 2】",
"",
"5 　神也没有宽容上古的世代，曾叫洪水临到那不敬虔的世代，却保护了传义道的挪亚一家八口。",
"6 又判定所多玛、蛾摩拉，将二城倾覆，焚烧成灰，作为后世不敬虔人的鑑戒；",
"7 只搭救了那常为恶人淫行忧伤的义人罗得。",
"8 （因为那义人住在他们中间，看见听见他们不法的事，他的义心就天天伤痛。）",
"",
"——【彼得后书 2】",
],
[
"22 This is the word which the LORD hath spoken concerning him; The virgin, the daughter of Zion, hath despised thee, and laughed thee to scorn; the daughter of Jerusalem hath shaken her head at thee.",
"23 Whom hast thou reproached and blasphemed? and against whom hast thou exalted thy voice, and lifted up thine eyes on high? even against the Holy One of Israel.",
"24 By thy servants hast thou reproached the Lord, and hast said, By the multitude of my chariots am I come up to the height of the mountains, to the sides of Lebanon; and I will cut down the tall cedars thereof, and the choice fir trees thereof: and I will enter into the height of his border, and the forest of his Carmel.",
"25 I have digged, and drunk water; and with the sole of my feet have I dried up all the rivers of the besieged places.",
"26 Hast thou not heard long ago, how I have done it; and of ancient times, that I have formed it? now have I brought it to pass, that thou shouldest be to lay waste defenced cities into ruinous heaps.",
"27 Therefore their inhabitants were of small power, they were dismayed and confounded: they were as the grass of the field, and as the green herb, as the grass on the housetops, and as corn blasted before it be grown up.",
"",
"——【The Book of the Prophet Isaiah 37】",
"",
"22 所以耶和华论他这样说：锡安的处女藐视你，嗤笑你；耶路撒冷的女子向你摇头。",
"23 你辱骂谁，亵渎谁？扬起声来，高举眼目攻击谁呢？乃是攻击以色列的圣者。",
"24 你借你的臣仆辱骂主说：我率领许多战车上山顶，到黎巴嫩极深之处；我要砍伐其中高大的香柏树和佳美的松树。我必上极高之处，进入肥田的树林。",
"25 我已经挖井喝水；我必用脚掌踏干埃及的一切河。",
"26 耶和华说：你岂没有听见我早先所做的，古时所立的吗？现在借你使坚固城荒废，变为乱堆。",
"27 所以其中的居民力量甚小，惊惶羞愧。他们像野草，像青菜，如房顶上的草，又如田间未长成的禾稼。",
"",
"——【以赛亚书 37】",
],
[
"39 All flesh is not the same flesh: but there is one kind of flesh of men, another flesh of beasts, another of fishes, and another of birds.",
"40 There are also celestial bodies, and bodies terrestrial: but the glory of the celestial is one, and the glory of the terrestrial is another.",
"41 There is one glory of the sun, and another glory of the moon, and another glory of the stars: for one star differeth from another star in glory.",
"42 So also is the resurrection of the dead. It is sown in corruption; it is raised in incorruption:",
"",
"——【The First Epistle of Paul the Apostle to the Corinthians 15】",
"",
"39 凡肉体各有不同：人是一样，兽又是一样，鸟又是一样，鱼又是一样。",
"40 有天上的形体，也有地上的形体；但天上形体的荣光是一样，地上形体的荣光又是一样。",
"41 日有日的荣光，月有月的荣光，星有星的荣光。这星和那星的荣光也有分别。",
"42 死人复活也是这样：所种的是必朽坏的，复活的是不朽坏的；",
"",
"——【哥林多前书 15】",
],
[
"13 The boar out of the wood doth waste it, and the wild beast of the field doth devour it.",
"14 Return, we beseech thee, O God of hosts: look down from heaven, and behold, and visit this vine;",
"15 And the vineyard which thy right hand hath planted, and the branch that thou madest strong for thyself.",
"16 It is burned with fire, it is cut down: they perish at the rebuke of thy countenance.",
"17 Let thy hand be upon the man of thy right hand, upon the son of man whom thou madest strong for thyself.",
"",
"——【The Book of Psalms 80】",
"",
"13 林中出来的野猪把它糟踏；野地的走兽拿它当食物。",
"14 万军之　神啊，求你回转！从天上垂看，眷顾这葡萄树，",
"15 保护你右手所栽的和你为自己所坚固的枝子。",
"16 这树已经被火焚烧，被刀砍伐；他们因你脸上的怒容就灭亡了。",
"17 愿你的手扶持你右边的人，就是你为自己所坚固的人子。",
"",
"——【诗篇 80】",
],
[
"18 For I know that in me (that is, in my flesh,) dwelleth no good thing: for to will is present with me; but how to perform that which is good I find not.",
"19 For the good that I would I do not: but the evil which I would not, that I do.",
"20 Now if I do that I would not, it is no more I that do it, but sin that dwelleth in me.",
"",
"——【The Epistle of Paul the Apostle to the Romans 7】",
"",
"18 我也知道在我里头，就是我肉体之中，没有良善。因为，立志为善由得我，只是行出来由不得我。",
"19 故此，我所愿意的善，我反不做；我所不愿意的恶，我倒去做。",
"20 若我去做所不愿意做的，就不是我做的，乃是住在我里头的罪做的。",
"",
"——【罗马书 7】",
],
[
"13 They took the young men to grind, and the children fell under the wood.",
"14 The elders have ceased from the gate, the young men from their musick.",
"15 The joy of our heart is ceased; our dance is turned into mourning.",
"16 The crown is fallen from our head: woe unto us, that we have sinned!",
"",
"——【The Lamentations of Jeremiah 5】",
"",
"13 少年人扛磨石，孩童背木柴，都绊跌了。",
"14 老年人在城门口断绝；少年人不再作乐。",
"15 我们心中的快乐止息，跳舞变为悲哀。",
"16 冠冕从我们的头上落下；我们犯罪了，我们有祸了！",
"",
"——【耶利米哀歌 5】",
],
[
"15 And David said to Abner, Art not thou a valiant man? and who is like to thee in Israel? wherefore then hast thou not kept thy lord the king? for there came one of the people in to destroy the king thy lord.",
"16 This thing is not good that thou hast done. As the LORD liveth, ye are worthy to die, because ye have not kept your master, the LORD'S anointed. And now see where the king's spear is, and the cruse of water that was at his bolster.",
"17 And Saul knew David's voice, and said, Is this thy voice, my son David? And David said, It is my voice, my lord, O king.",
"",
"——【The First Book of Samuel 26】",
"",
"15 大卫对押尼珥说：「你不是个勇士吗？以色列中谁能比你呢？民中有人进来要害死王─你的主，你为何没有保护王─你的主呢？",
"16 你这样是不好的！我指著永生的耶和华起誓，你们都是该死的；因为没有保护你们的主，就是耶和华的受膏者。现在你看看王头旁的枪和水瓶在哪里。」",
"17 扫罗听出是大卫的声音，就说：「我儿大卫，这是你的声音吗？」大卫说：「主─我的王啊，是我的声音」；",
"",
"——【撒母耳记上 26】",
],
];
