var bible31_global=[
[
"7 Since the days of our fathers have we been in a great trespass unto this day; and for our iniquities have we, our kings, and our priests, been delivered into the hand of the kings of the lands, to the sword, to captivity, and to a spoil, and to confusion of face, as it is this day.",
"8 And now for a little space grace hath been shewed from the LORD our God, to leave us a remnant to escape, and to give us a nail in his holy place, that our God may lighten our eyes, and give us a little reviving in our bondage.",
"9 For we were bondmen; yet our God hath not forsaken us in our bondage, but hath extended mercy unto us in the sight of the kings of Persia, to give us a reviving, to set up the house of our God, and to repair the desolations thereof, and to give us a wall in Judah and in Jerusalem.",
"10 And now, O our God, what shall we say after this? for we have forsaken thy commandments,",
"",
"——【Ezra 9】",
"",
"7 从我们列祖直到今日，我们的罪恶甚重；因我们的罪孽，我们和君王、祭司都交在外邦列王的手中，杀害、掳掠、抢夺、脸上蒙羞正如今日的光景。",
"8 现在耶和华─我们的　神暂且施恩与我们，给我们留些逃脱的人，使我们安稳如钉子钉在他的圣所，我们的　神好光照我们的眼目，使我们在受辖制之中稍微复兴。",
"9 我们是奴仆，然而在受辖制之中，我们的　神仍没有丢弃我们，在波斯王眼前向我们施恩，叫我们复兴，能重建我们　神的殿，修其毁坏之处，使我们在犹大和耶路撒冷有墙垣。",
"10 「我们的　神啊，既是如此，我们还有什么话可说呢？因为我们已经离弃你的命令，",
"",
"——【以斯拉记 9】",
],
[
"27 Then they returned, every man of Judah and Jerusalem, and Jehoshaphat in the forefront of them, to go again to Jerusalem with joy; for the LORD had made them to rejoice over their enemies.",
"28 And they came to Jerusalem with psalteries and harps and trumpets unto the house of the LORD.",
"29 And the fear of God was on all the kingdoms of those countries, when they had heard that the LORD fought against the enemies of Israel.",
"30 So the realm of Jehoshaphat was quiet: for his God gave him rest round about.",
"",
"——【The Second Book of the Chronicles 20】",
"",
"27 犹大人和耶路撒冷人都欢欢喜喜地回耶路撒冷，约沙法率领他们；因为耶和华使他们战胜仇敌，就欢喜快乐。",
"28 他们弹琴、鼓瑟、吹号来到耶路撒冷，进了耶和华的殿。",
"29 列邦诸国听见耶和华战败以色列的仇敌，就甚惧怕。",
"30 这样，约沙法的国得享太平，因为　神赐他四境平安。",
"",
"——【历代志下 20】",
],
[
"14 Then Daniel answered with counsel and wisdom to Arioch the captain of the king's guard, which was gone forth to slay the wise men of Babylon:",
"15 He answered and said to Arioch the king's captain, Why is the decree so hasty from the king? Then Arioch made the thing known to Daniel.",
"16 Then Daniel went in, and desired of the king that he would give him time, and that he would shew the king the interpretation.",
"17 Then Daniel went to his house, and made the thing known to Hananiah, Mishael, and Azariah, his companions:",
"",
"——【The Book of Daniel 2】",
"",
"14 王的护卫长亚略出来，要杀巴比伦的哲士，但以理就用婉言回答他，",
"15 向王的护卫长亚略说：「王的命令为何这样紧急呢？」亚略就将情节告诉但以理。",
"16 但以理遂进去求王宽限，就可以将梦的讲解告诉王。",
"17 但以理回到他的居所，将这事告诉他的同伴哈拿尼雅、米沙利、亚撒利雅，",
"",
"——【但以理书 2】",
],
[
"2 Abraham begat Isaac; and Isaac begat Jacob; and Jacob begat Judas and his brethren;",
"3 And Judas begat Phares and Zara of Thamar; and Phares begat Esrom; and Esrom begat Aram;",
"4 And Aram begat Aminadab; and Aminadab begat Naasson; and Naasson begat Salmon;",
"",
"——【The Gospel According to Saint Matthew 1】",
"",
"2 亚伯拉罕生以撒；以撒生雅各；雅各生犹大和他的弟兄；",
"3 犹大从她玛氏生法勒斯和谢拉；法勒斯生希斯仑；希斯仑生亚兰；",
"4 亚兰生亚米拿达；亚米拿达生拿顺；拿顺生撒门；",
"",
"——【马太福音 1】",
],
[
"1 The word of the LORD which came unto Zephaniah the son of Cushi, the son of Gedaliah, the son of Amariah, the son of Hizkiah, in the days of Josiah the son of Amon, king of Judah.",
"2 I will utterly consume all things from off the land, saith the LORD.",
"",
"——【Zephaniah 1】",
"",
"1 当犹大王亚们的儿子约西亚在位的时候，耶和华的话临到希西家的玄孙，亚玛利雅的曾孙基大利的孙子，古示的儿子西番雅。",
"2 耶和华说：我必从地上除灭万类。",
"",
"——【西番雅书 1】",
],
[
"25 And when Moses saw that the people were naked; (for Aaron had made them naked unto their shame among their enemies:)",
"26 Then Moses stood in the gate of the camp, and said, Who is on the LORD'S side? let him come unto me. And all the sons of Levi gathered themselves together unto him.",
"27 And he said unto them, Thus saith the LORD God of Israel, Put every man his sword by his side, and go in and out from gate to gate throughout the camp, and slay every man his brother, and every man his companion, and every man his neighbour.",
"",
"——【The Second Book of Moses: Called Exodus 32】",
"",
"25 摩西见百姓放肆（亚伦纵容他们，使他们在仇敌中间被讥刺），",
"26 就站在营门中，说：「凡属耶和华的，都要到我这里来！于是利未的子孙都到他那里聚集。",
"27 他对他们说：「耶和华─以色列的　神这样说：『你们各人把刀跨在腰间，在营中往来，从这门到那门，各人杀他的弟兄与同伴并邻舍。』」",
"",
"——【出埃及记 32】",
],
[
"3 And his men that were with him did David bring up, every man with his household: and they dwelt in the cities of Hebron.",
"4 And the men of Judah came, and there they anointed David king over the house of Judah. And they told David, saying, That the men of Jabesh–gilead were they that buried Saul.",
"5 And David sent messengers unto the men of Jabesh–gilead, and said unto them, Blessed be ye of the LORD, that ye have shewed this kindness unto your lord, even unto Saul, and have buried him.",
"6 And now the LORD shew kindness and truth unto you: and I also will requite you this kindness, because ye have done this thing.",
"7 Therefore now let your hands be strengthened, and be ye valiant: for your master Saul is dead, and also the house of Judah have anointed me king over them.",
"",
"——【The Second Book of Samuel 2】",
"",
"3 大卫也将跟随他的人和他们各人的眷属一同带上去，住在希伯仑的城邑中。",
"4 犹大人来到希伯仑，在那里膏大卫作犹大家的王。有人告诉大卫说：「葬埋扫罗的是基列‧雅比人。」",
"5 大卫就差人去见基列‧雅比人，对他们说：「你们厚待你们的主─扫罗，将他葬埋。愿耶和华赐福与你们！",
"6 你们既行了这事，愿耶和华以慈爱诚实待你们，我也要为此厚待你们。",
"7 现在你们的主─扫罗死了，犹大家已经膏我作他们的王，所以你们要刚强奋勇。」",
"",
"——【撒母耳记下 2】",
],
[
"1 By night on my bed I sought him whom my soul loveth: I sought him, but I found him not.",
"2 I will rise now, and go about the city in the streets, and in the broad ways I will seek him whom my soul loveth: I sought him, but I found him not.",
"3 The watchmen that go about the city found me: to whom I said, Saw ye him whom my soul loveth?",
"4 It was but a little that I passed from them, but I found him whom my soul loveth: I held him, and would not let him go, until I had brought him into my mother's house, and into the chamber of her that conceived me.",
"",
"——【The Song of Solomon 3】",
"",
"1 我夜间躺卧在床上，寻找我心所爱的；我寻找他，却寻不见。",
"2 我说：我要起来，游行城中，在街市上，在宽阔处，寻找我心所爱的。我寻找他，却寻不见。",
"3 城中巡逻看守的人遇见我；我问他们：你们看见我心所爱的没有？",
"4 我刚离开他们就遇见我心所爱的。我拉住他，不容他走，领他入我母家，到怀我者的内室。",
"",
"——【雅歌 3】",
],
[
"29 And they shall deal with thee hatefully, and shall take away all thy labour, and shall leave thee naked and bare: and the nakedness of thy whoredoms shall be discovered, both thy lewdness and thy whoredoms.",
"30 I will do these things unto thee, because thou hast gone a whoring after the heathen, and because thou art polluted with their idols.",
"31 Thou hast walked in the way of thy sister; therefore will I give her cup into thine hand.",
"",
"——【The Book of the Prophet Ezekiel 23】",
"",
"29 他们必以恨恶办你，夺取你一切劳碌得来的，留下你赤身露体。你淫乱的下体，连你的淫行，带你的淫乱，都被显露。",
"30 人必向你行这些事；因为你随从外邦人行邪淫，被他们的偶像玷污了。",
"31 你走了你姊姊所走的路，所以我必将她的杯交在你手中。」",
"",
"——【以西结书 23】",
],
[
"4 For we are sold, I and my people, to be destroyed, to be slain, and to perish. But if we had been sold for bondmen and bondwomen, I had held my tongue, although the enemy could not countervail the king's damage.",
"5 Then the king Ahasuerus answered and said unto Esther the queen, Who is he, and where is he, that durst presume in his heart to do so?",
"6 And Esther said, The adversary and enemy is this wicked Haman. Then Haman was afraid before the king and the queen.",
"7 And the king arising from the banquet of wine in his wrath went into the palace garden: and Haman stood up to make request for his life to Esther the queen; for he saw that there was evil determined against him by the king.",
"",
"——【The Book of Esther 7】",
"",
"4 因我和我的本族被卖了，要剪除杀戮灭绝我们。我们若被卖为奴为婢，我也闭口不言；但王的损失，敌人万不能补足。」",
"5 亚哈随鲁王问王后以斯帖说：「擅敢起意如此行的是谁？这人在哪里呢？」",
"6 以斯帖说：「仇人敌人就是这恶人哈曼！」哈曼在王和王后面前就甚惊惶。",
"7 王便大怒，起来离开酒席往御园去了。哈曼见王定意要加罪与他，就起来，求王后以斯帖救命。",
"",
"——【以斯帖记 7】",
],
[
"16 Therefore all they that devour thee shall be devoured; and all thine adversaries, every one of them, shall go into captivity; and they that spoil thee shall be a spoil, and all that prey upon thee will I give for a prey.",
"17 For I will restore health unto thee, and I will heal thee of thy wounds, saith the LORD; because they called thee an Outcast, saying, This is Zion, whom no man seeketh after.",
"18 Thus saith the LORD; Behold, I will bring again the captivity of Jacob's tents, and have mercy on his dwellingplaces; and the city shall be builded upon her own heap, and the palace shall remain after the manner thereof.",
"",
"——【The Book of the Prophet Jeremiah 30】",
"",
"16 故此，凡吞吃你的必被吞吃；你的敌人个个都被掳去；掳掠你的必成为掳物；抢夺你的必成为掠物。",
"17 耶和华说：我必使你痊癒，医好你的伤痕，都因人称你为被赶散的，说：这是锡安，无人来探问（或译：理会）的！",
"18 耶和华如此说：我必使雅各被掳去的帐棚归回，也必顾惜他的住处。城必建造在原旧的山冈；宫殿也照旧有人居住。",
"",
"——【耶利米书 30】",
],
[
"1 And in that day thou shalt say, O LORD, I will praise thee: though thou wast angry with me, thine anger is turned away, and thou comfortedst me.",
"2 Behold, God is my salvation; I will trust, and not be afraid: for the LORD JEHOVAH is my strength and my song; he also is become my salvation.",
"",
"——【The Book of the Prophet Isaiah 12】",
"",
"1 到那日，你必说：耶和华啊，我要称谢你！因为你虽然向我发怒，你的怒气却已转消；你又安慰了我。",
"2 看哪！　神是我的拯救；我要倚靠他，并不惧怕。因为主耶和华是我的力量，是我的诗歌，他也成了我的拯救。",
"",
"——【以赛亚书 12】",
],
[
"5 Then they said to Jeremiah, The LORD be a true and faithful witness between us, if we do not even according to all things for the which the LORD thy God shall send thee to us.",
"6 Whether it be good, or whether it be evil, we will obey the voice of the LORD our God, to whom we send thee; that it may be well with us, when we obey the voice of the LORD our God.",
"7 And it came to pass after ten days, that the word of the LORD came unto Jeremiah.",
"",
"——【The Book of the Prophet Jeremiah 42】",
"",
"5 于是他们对耶利米说：「我们若不照耶和华─你的　神差遣你来说的一切话行，愿耶和华在我们中间作真实诚信的见证。",
"6 我们现在请你到耶和华─我们的　神面前，他说的无论是好是歹，我们都必听从；我们听从耶和华─我们　神的话，就可以得福。」",
"7 过了十天，耶和华的话临到耶利米。",
"",
"——【耶利米书 42】",
],
[
"5 They are of the world: therefore speak they of the world, and the world heareth them.",
"6 We are of God: he that knoweth God heareth us; he that is not of God heareth not us. Hereby know we the spirit of truth, and the spirit of error.",
"",
"——【The First Epistle General of John 4】",
"",
"5 他们是属世界的，所以论世界的事，世人也听从他们。",
"6 我们是属　神的，认识　神的就听从我们；不属　神的就不听从我们。从此我们可以认出真理的灵和谬妄的灵来。",
"",
"——【约翰一书 4】",
],
[
"5 Harim, Meremoth, Obadiah,",
"6 Daniel, Ginnethon, Baruch,",
"7 Meshullam, Abijah, Mijamin,",
"",
"——【The Book of Nehemiah 10】",
"",
"5 哈琳、米利末、俄巴底亚、",
"6 但以理、近顿、巴录、",
"7 米书兰、亚比雅、米雅民、",
"",
"——【尼希米记 10】",
],
[
"9 Publish in the palaces at Ashdod, and in the palaces in the land of Egypt, and say, Assemble yourselves upon the mountains of Samaria, and behold the great tumults in the midst thereof, and the oppressed in the midst thereof.",
"10 For they know not to do right, saith the LORD, who store up violence and robbery in their palaces.",
"",
"——【Amos 3】",
"",
"9 要在亚实突的宫殿中和埃及地的宫殿里传扬说：你们要聚集在撒马利亚的山上，就看见城中有何等大的扰乱与欺压的事。",
"10 那些以强暴抢夺财物、积蓄在自己家中的人不知道行正直的事。这是耶和华说的。",
"",
"——【阿摩司书 3】",
],
[
"8 (For the redemption of their soul is precious, and it ceaseth for ever:)",
"9 That he should still live for ever, and not see corruption.",
"10 For he seeth that wise men die, likewise the fool and the brutish person perish, and leave their wealth to others.",
"11 Their inward thought is, that their houses shall continue for ever, and their dwelling places to all generations; they call their lands after their own names.",
"12 Nevertheless man being in honour abideth not: he is like the beasts that perish.",
"13 This their way is their folly: yet their posterity approve their sayings. Selah.",
"",
"——【The Book of Psalms 49】",
"",
"8 叫他长远活着，不见朽坏；因为赎他生命的价值极贵，只可永远罢休。",
"9 并入上节",
"10 他必见智慧人死，又见愚顽人和畜类人一同灭亡，将他们的财货留给别人。",
"11 他们心里思想：他们的家室必永存，住宅必留到万代；他们以自己的名称自己的地。",
"12 但人居尊贵中不能长久，如同死亡的畜类一样。",
"13 他们行的这道本为自己的愚昧；但他们以后的人还佩服他们的话语。（细拉）",
"",
"——【诗篇 49】",
],
[
"19 Now the works of the flesh are manifest, which are these; Adultery, fornication, uncleanness, lasciviousness,",
"20 Idolatry, witchcraft, hatred, variance, emulations, wrath, strife, seditions, heresies,",
"21 Envyings, murders, drunkenness, revellings, and such like: of the which I tell you before, as I have also told you in time past, that they which do such things shall not inherit the kingdom of God.",
"22 But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith,",
"",
"——【The Epistle of Paul the Apostle to the Galatians 5】",
"",
"19 情欲的事都是显而易见的，就如奸淫、污秽、邪荡、",
"20 拜偶像、邪术、仇恨、争竞、忌恨、恼怒、结党、纷争、异端、",
"21 嫉妒（有古卷在此有：凶杀二字）、醉酒、荒宴等类。我从前告诉你们，现在又告诉你们，行这样事的人必不能承受　神的国。",
"22 圣灵所结的果子，就是仁爱、喜乐、和平、忍耐、恩慈、良善、信实、",
"",
"——【加拉太书 5】",
],
[
"7 Be strong and courageous, be not afraid nor dismayed for the king of Assyria, nor for all the multitude that is with him: for there be more with us than with him:",
"8 With him is an arm of flesh; but with us is the LORD our God to help us, and to fight our battles. And the people rested themselves upon the words of Hezekiah king of Judah.",
"9 After this did Sennacherib king of Assyria send his servants to Jerusalem, (but he himself laid siege against Lachish, and all his power with him,) unto Hezekiah king of Judah, and unto all Judah that were at Jerusalem, saying,",
"",
"——【The Second Book of the Chronicles 32】",
"",
"7 「你们当刚强壮胆，不要因亚述王和跟随他的大军恐惧、惊慌；因为与我们同在的，比与他们同在的更大。",
"8 与他们同在的是肉臂，与我们同在的是耶和华─我们的　神，他必帮助我们，为我们争战。」百姓就靠犹大王希西家的话，安然无惧了。",
"9 此后，亚述王西拿基立和他的全军攻打拉吉，就差遣臣仆到耶路撒冷见犹大王希西家和一切在耶路撒冷的犹大人，说：",
"",
"——【历代志下 32】",
],
[
"15 The eighth to Jeshaiah, he, his sons, and his brethren, were twelve:",
"16 The ninth to Mattaniah, he, his sons, and his brethren, were twelve:",
"17 The tenth to Shimei, he, his sons, and his brethren, were twelve:",
"18 The eleventh to Azareel, he, his sons, and his brethren, were twelve:",
"19 The twelfth to Hashabiah, he, his sons, and his brethren, were twelve:",
"",
"——【The First Book of the Chronicles 25】",
"",
"15 第八是耶筛亚；他和他儿子并弟兄共十二人。",
"16 第九是玛探雅；他和他儿子并弟兄共十二人。",
"17 第十是示每；他和他儿子并弟兄共十二人。",
"18 第十一是亚萨烈；他和他儿子并弟兄共十二人。",
"19 第十二是哈沙比雅；他和他儿子并弟兄共十二人。",
"",
"——【历代志上 25】",
],
[
"15 And there was trembling in the host, in the field, and among all the people: the garrison, and the spoilers, they also trembled, and the earth quaked: so it was a very great trembling.",
"16 And the watchmen of Saul in Gibeah of Benjamin looked; and, behold, the multitude melted away, and they went on beating down one another.",
"17 Then said Saul unto the people that were with him, Number now, and see who is gone from us. And when they had numbered, behold, Jonathan and his armourbearer were not there.",
"18 And Saul said unto Ahiah, Bring hither the ark of God. For the ark of God was at that time with the children of Israel.",
"19 And it came to pass, while Saul talked unto the priest, that the noise that was in the host of the Philistines went on and increased: and Saul said unto the priest, Withdraw thine hand.",
"20 And Saul and all the people that were with him assembled themselves, and they came to the battle: and, behold, every man's sword was against his fellow, and there was a very great discomfiture.",
"",
"——【The First Book of Samuel 14】",
"",
"15 于是在营中、在田野、在众民内都有战兢，防兵和掠兵也都战兢，地也震动，战兢之势甚大。",
"16 在便雅悯的基比亚，扫罗的守望兵看见非利士的军众溃散，四围乱窜。",
"17 扫罗就对跟随他的民说：「你们查点查点，看从我们这里出去的是谁？」他们一查点，就知道约拿单和拿兵器的人没有在这里。",
"18 那时　神的约柜在以色列人那里。扫罗对亚希亚说：「你将　神的约柜运了来。」",
"19 扫罗正与祭司说话的时候，非利士营中的喧嚷越发大了；扫罗就对祭司说：「停手吧！」",
"20 扫罗和跟随他的人都聚集，来到战场，看见非利士人用刀互相击杀，大大惶乱。",
"",
"——【撒母耳记上 14】",
],
[
"23 And after he had spent some time there, he departed, and went over all the country of Galatia and Phrygia in order, strengthening all the disciples.",
"24 And a certain Jew named Apollos, born at Alexandria, an eloquent man, and mighty in the scriptures, came to Ephesus.",
"25 This man was instructed in the way of the Lord; and being fervent in the spirit, he spake and taught diligently the things of the Lord, knowing only the baptism of John.",
"26 And he began to speak boldly in the synagogue: whom when Aquila and Priscilla had heard, they took him unto them, and expounded unto him the way of God more perfectly.",
"27 And when he was disposed to pass into Achaia, the brethren wrote, exhorting the disciples to receive him: who, when he was come, helped them much which had believed through grace:",
"28 For he mightily convinced the Jews, and that publickly, shewing by the scriptures that Jesus was Christ.",
"",
"——【The Acts of the Apostles 18】",
"",
"23 住了些日子，又离开那里，挨次经过加拉太和弗吕家地方，坚固众门徒。",
"24 有一个犹太人，名叫亚波罗，来到以弗所。他生在亚力山太，是有学问（或作：口才）的，最能讲解圣经。",
"25 这人已经在主的道上受了教训，心里火热，将耶稣的事详细讲论教训人；只是他单晓得约翰的洗礼。",
"26 他在会堂里放胆讲道；百基拉，亚居拉听见，就接他来，将　神的道给他讲解更加详细。",
"27 他想要往亚该亚去，弟兄们就勉励他，并写信请门徒接待他（或作：弟兄们就写信劝门徒接待他）。他到了那里，多帮助那蒙恩信主的人，",
"28 在众人面前极有能力驳倒犹太人，引圣经证明耶稣是基督。",
"",
"——【使徒行传 18】",
],
[
"3 And they sing the song of Moses the servant of God, and the song of the Lamb, saying, Great and marvellous are thy works, Lord God Almighty; just and true are thy ways, thou King of saints.",
"4 Who shall not fear thee, O Lord, and glorify thy name? for thou only art holy: for all nations shall come and worship before thee; for thy judgments are made manifest.",
"5 And after that I looked, and, behold, the temple of the tabernacle of the testimony in heaven was opened:",
"6 And the seven angels came out of the temple, having the seven plagues, clothed in pure and white linen, and having their breasts girded with golden girdles.",
"7 And one of the four beasts gave unto the seven angels seven golden vials full of the wrath of God, who liveth for ever and ever.",
"",
"——【The Revelation of Saint John the Devine 15】",
"",
"3 唱　神仆人摩西的歌，和羔羊的歌，说：主　神─全能者啊，你的作为大哉！奇哉！万世（或作：国）之王啊，你的道途义哉！诚哉！",
"4 主啊，谁敢不敬畏你，不将荣耀归与你的名呢？因为独有你是圣的。万民都要来在你面前敬拜，因你公义的作为已经显出来了。",
"5 此后，我看见在天上那存法柜的殿开了。",
"6 那掌管七灾的七位天使从殿中出来，穿着洁白光明的细麻衣（细麻衣；有古卷是宝石），胸间束着金带。",
"7 四活物中有一个把盛满了活到永永远远之　神大怒的七个金碗给了那七位天使。",
"",
"——【启示录 15】",
],
[
"2 For if the word spoken by angels was stedfast, and every transgression and disobedience received a just recompence of reward;",
"3 How shall we escape, if we neglect so great salvation; which at the first began to be spoken by the Lord, and was confirmed unto us by them that heard him;",
"4 God also bearing them witness, both with signs and wonders, and with divers miracles, and gifts of the Holy Ghost, according to his own will?",
"5 For unto the angels hath he not put in subjection the world to come, whereof we speak.",
"",
"——【The Epistle of Paul the Apostle to the Hebrews 2】",
"",
"2 那藉着天使所传的话既是确定的；凡干犯悖逆的都受了该受的报应。",
"3 我们若忽略这么大的救恩，怎能逃罪呢？这救恩起先是主亲自讲的，后来是听见的人给我们证实了。",
"4 　神又按自己的旨意，用神迹、奇事和百般的异能，并圣灵的恩赐，同他们作见证。",
"5 我们所说将来的世界，　神原没有交给天使管辖。",
"",
"——【希伯来书 2】",
],
[
"2 But neither he, nor his servants, nor the people of the land, did hearken unto the words of the LORD, which he spake by the prophet Jeremiah.",
"3 And Zedekiah the king sent Jehucal the son of Shelemiah and Zephaniah the son of Maaseiah the priest to the prophet Jeremiah, saying, Pray now unto the LORD our God for us.",
"",
"——【The Book of the Prophet Jeremiah 37】",
"",
"2 但西底家和他的臣仆，并国中的百姓，都不听从耶和华借先知耶利米所说的话。",
"3 西底家王打发示利米雅的儿子犹甲和祭司玛西雅的儿子西番雅去见先知耶利米，说：「求你为我们祷告耶和华─我们的　神。」",
"",
"——【耶利米书 37】",
],
[
"14 With whom took he counsel, and who instructed him, and taught him in the path of judgment, and taught him knowledge, and shewed to him the way of understanding?",
"15 Behold, the nations are as a drop of a bucket, and are counted as the small dust of the balance: behold, he taketh up the isles as a very little thing.",
"16 And Lebanon is not sufficient to burn, nor the beasts thereof sufficient for a burnt offering.",
"",
"——【The Book of the Prophet Isaiah 40】",
"",
"14 他与谁商议，谁教导他，谁将公平的路指示他，又将知识教训他，将通达的道指教他呢？",
"15 看哪，万民都像水桶的一滴，又算如天平上的微尘；他举起众海岛，好像极微之物。",
"16 黎巴嫩的树林不够当柴烧；其中的走兽也不够作燔祭。",
"",
"——【以赛亚书 40】",
],
[
"5 For the LORD thy God hath chosen him out of all thy tribes, to stand to minister in the name of the LORD, him and his sons for ever.",
"6 And if a Levite come from any of thy gates out of all Israel, where he sojourned, and come with all the desire of his mind unto the place which the LORD shall choose;",
"7 Then he shall minister in the name of the LORD his God, as all his brethren the Levites do, which stand there before the LORD.",
"8 They shall have like portions to eat, beside that which cometh of the sale of his patrimony.",
"9 When thou art come into the land which the LORD thy God giveth thee, thou shalt not learn to do after the abominations of those nations.",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 18】",
"",
"5 因为耶和华─你的　神从你各支派中将他拣选出来，使他和他子孙永远奉耶和华的名侍立，事奉。",
"6 「利未人无论寄居在以色列中的那一座城，若从那里出来，一心愿意到耶和华所选择的地方，",
"7 就要奉耶和华─他　神的名事奉，像他众弟兄利未人侍立在耶和华面前事奉一样。",
"8 除了他卖祖父产业所得的以外，还要得一分祭物与他们同吃。」",
"9 「你到了耶和华─你　神所赐之地，那些国民所行可憎恶的事，你不可学着行。",
"",
"——【申命记 18】",
],
[
"12 And the prince that is among them shall bear upon his shoulder in the twilight, and shall go forth: they shall dig through the wall to carry out thereby: he shall cover his face, that he see not the ground with his eyes.",
"13 My net also will I spread upon him, and he shall be taken in my snare: and I will bring him to Babylon to the land of the Chaldeans; yet shall he not see it, though he shall die there.",
"14 And I will scatter toward every wind all that are about him to help him, and all his bands; and I will draw out the sword after them.",
"15 And they shall know that I am the LORD, when I shall scatter them among the nations, and disperse them in the countries.",
"16 But I will leave a few men of them from the sword, from the famine, and from the pestilence; that they may declare all their abominations among the heathen whither they come; and they shall know that I am the LORD.",
"",
"——【The Book of the Prophet Ezekiel 12】",
"",
"12 他们中间的君王也必在天黑的时候将物件搭在肩头上带出去。他们要挖通了墙，从其中带出去。他必蒙住脸，眼看不见地。",
"13 我必将我的网撒在他身上，他必在我的网罗中缠住。我必带他到迦勒底人之地的巴比伦；他虽死在那里，却看不见那地。",
"14 周围一切帮助他的和他所有的军队，我必分散四方（方：原文是风），也要拔刀追赶他们。",
"15 我将他们四散在列国、分散在列邦的时候，他们就知道我是耶和华。",
"16 我却要留下他们几个人得免刀剑、饥荒、瘟疫，使他们在所到的各国中述说他们一切可憎的事，人就知道我是耶和华。」",
"",
"——【以西结书 12】",
],
[
"35 And the children of Israel did according to the word of Moses; and they borrowed of the Egyptians jewels of silver, and jewels of gold, and raiment:",
"36 And the LORD gave the people favour in the sight of the Egyptians, so that they lent unto them such things as they required. And they spoiled the Egyptians.",
"37 And the children of Israel journeyed from Rameses to Succoth, about six hundred thousand on foot that were men, beside children.",
"",
"——【The Second Book of Moses: Called Exodus 12】",
"",
"35 以色列人照着摩西的话行，向埃及人要金器、银器，和衣裳。",
"36 耶和华叫百姓在埃及人眼前蒙恩，以致埃及人给他们所要的。他们就把埃及人的财物夺去了。",
"37 以色列人从兰塞起行，往疏割去；除了妇人孩子，步行的男人约有六十万。",
"",
"——【出埃及记 12】",
],
[
"2 What ye know, the same do I know also: I am not inferior unto you.",
"3 Surely I would speak to the Almighty, and I desire to reason with God.",
"4 But ye are forgers of lies, ye are all physicians of no value.",
"5 O that ye would altogether hold your peace! and it should be your wisdom.",
"6 Hear now my reasoning, and hearken to the pleadings of my lips.",
"",
"——【The Book of Job 13】",
"",
"2 你们所知道的，我也知道，并非不及你们。",
"3 我真要对全能者说话；我愿与　神理论。",
"4 你们是编造谎言的，都是无用的医生。",
"5 惟愿你们全然不作声；这就算为你们的智慧！",
"6 请你们听我的辩论，留心听我口中的分诉。",
"",
"——【约伯记 13】",
],
[
"10 And herein I give my advice: for this is expedient for you, who have begun before, not only to do, but also to be forward a year ago.",
"11 Now therefore perform the doing of it; that as there was a readiness to will, so there may be a performance also out of that which ye have.",
"12 For if there be first a willing mind, it is accepted according to that a man hath, and not according to that he hath not.",
"13 For I mean not that other men be eased, and ye burdened:",
"",
"——【The Second Epistle of Paul the Apostle to the Corinthians 8】",
"",
"10 我在这事上把我的意见告诉你们，是与你们有益；因为你们下手办这事，而且起此心意，已经有一年了，",
"11 如今就当办成这事。既有愿做的心，也当照你们所有的去办成。",
"12 因为人若有愿做的心，必蒙悦纳，乃是照他所有的，并不是照他所无的。",
"13 我原不是要别人轻省，你们受累，",
"",
"——【哥林多后书 8】",
],
];
