var bible31_global=[
[
"1 And the LORD spake unto Moses, saying,",
"2 Speak unto Aaron, and say unto him, When thou lightest the lamps, the seven lamps shall give light over against the candlestick.",
"3 And Aaron did so; he lighted the lamps thereof over against the candlestick, as the LORD commanded Moses.",
"4 And this work of the candlestick was of beaten gold, unto the shaft thereof, unto the flowers thereof, was beaten work: according unto the pattern which the LORD had shewed Moses, so he made the candlestick.",
"5 And the LORD spake unto Moses, saying,",
"6 Take the Levites from among the children of Israel, and cleanse them.",
"",
"——【The Fourth Book of Moses: Called Numbers 8】",
"",
"1 耶和华晓谕摩西说：",
"2 「你告诉亚伦说：点灯的时候，七盏灯都要向灯台前面发光。」",
"3 亚伦便这样行。他点灯台上的灯，使灯向前发光，是照耶和华所吩咐摩西的。",
"4 这灯台的作法是用金子锤出来的，连座带花都是锤出来的。摩西制造灯台，是照耶和华所指示的样式。",
"5 耶和华晓谕摩西说：",
"6 「你从以色列人中选出利未人来，洁净他们。",
"",
"——【民数记 8】",
],
[
"36 And they were all amazed, and spake among themselves, saying, What a word is this! for with authority and power he commandeth the unclean spirits, and they come out.",
"37 And the fame of him went out into every place of the country round about.",
"38 And he arose out of the synagogue, and entered into Simon's house. And Simon's wife's mother was taken with a great fever; and they besought him for her.",
"39 And he stood over her, and rebuked the fever; and it left her: and immediately she arose and ministered unto them.",
"40 Now when the sun was setting, all they that had any sick with divers diseases brought them unto him; and he laid his hands on every one of them, and healed them.",
"41 And devils also came out of many, crying out, and saying, Thou art Christ the Son of God. And he rebuking them suffered them not to speak: for they knew that he was Christ.",
"",
"——【The Gospel According to Saint Luke 4】",
"",
"36 众人都惊讶，彼此对问说：这是什么道理呢？因为他用权柄能力吩咐污鬼，污鬼就出来。",
"37 于是耶稣的名声传遍了周围地方。",
"38 耶稣出了会堂，进了西门的家。西门的岳母害热病甚重，有人为她求耶稣。",
"39 耶稣站在他旁边，斥责那热病，热就退了。他立刻起来服事他们。",
"40 日落的时候，凡有病人的，不论害什么病，都带到耶稣那里。耶稣按手在他们各人身上，医好他们。",
"41 又有鬼从好些人身上出来，喊著说：你是　神的儿子。耶稣斥责他们，不许他们说话。因为他们知道他是基督。",
"",
"——【路加福音 4】",
],
[
"5 We have sinned, and have committed iniquity, and have done wickedly, and have rebelled, even by departing from thy precepts and from thy judgments:",
"6 Neither have we hearkened unto thy servants the prophets, which spake in thy name to our kings, our princes, and our fathers, and to all the people of the land.",
"7 O Lord, righteousness belongeth unto thee, but unto us confusion of faces, as at this day; to the men of Judah, and to the inhabitants of Jerusalem, and unto all Israel, that are near, and that are far off, through all the countries whither thou hast driven them, because of their trespass that they have trespassed against thee.",
"8 O Lord, to us belongeth confusion of face, to our kings, to our princes, and to our fathers, because we have sinned against thee.",
"9 To the Lord our God belong mercies and forgivenesses, though we have rebelled against him;",
"",
"——【The Book of Daniel 9】",
"",
"5 我们犯罪作孽，行恶叛逆，偏离你的诫命典章，",
"6 没有听从你仆人众先知奉你名向我们君王、首领、列祖，和国中一切百姓所说的话。",
"7 主啊，你是公义的，我们是脸上蒙羞的；因我们犹大人和耶路撒冷的居民，并以色列众人，或在近处，或在远处，被你赶到各国的人，都得罪了你，正如今日一样。",
"8 主啊，我们和我们的君王、首领、列祖因得罪了你，就都脸上蒙羞。",
"9 主─我们的　神是怜悯饶恕人的，我们却违背了他，",
"",
"——【但以理书 9】",
],
[
"5 Thou feedest them with the bread of tears; and givest them tears to drink in great measure.",
"6 Thou makest us a strife unto our neighbours: and our enemies laugh among themselves.",
"7 Turn us again, O God of hosts, and cause thy face to shine; and we shall be saved.",
"8 Thou hast brought a vine out of Egypt: thou hast cast out the heathen, and planted it.",
"",
"——【The Book of Psalms 80】",
"",
"5 你以眼泪当食物给他们吃，又多量出眼泪给他们喝。",
"6 你使邻邦因我们纷争；我们的仇敌彼此戏笑。",
"7 万军之　神啊，求你使我们回转，使你的脸发光，我们便要得救！",
"8 你从埃及挪出一棵葡萄树，赶出外邦人，把这树栽上。",
"",
"——【诗篇 80】",
],
[
"14 Justice and judgment are the habitation of thy throne: mercy and truth shall go before thy face.",
"15 Blessed is the people that know the joyful sound: they shall walk, O LORD, in the light of thy countenance.",
"16 In thy name shall they rejoice all the day: and in thy righteousness shall they be exalted.",
"17 For thou art the glory of their strength: and in thy favour our horn shall be exalted.",
"",
"——【The Book of Psalms 89】",
"",
"14 公义和公平是你宝座的根基；慈爱和诚实行在你前面。",
"15 知道向你欢呼的，那民是有福的！耶和华啊，他们在你脸上的光里行走。",
"16 他们因你的名终日欢乐，因你的公义得以高举。",
"17 你是他们力量的荣耀；因为你喜悦我们，我们的角必被高举。",
"",
"——【诗篇 89】",
],
[
"18 Lest the LORD see it, and it displease him, and he turn away his wrath from him.",
"19 Fret not thyself because of evil men, neither be thou envious at the wicked;",
"",
"——【The Proverbs 24】",
"",
"18 恐怕耶和华看见就不喜悦，将怒气从仇敌身上转过来。",
"19 不要为作恶的心怀不平，也不要嫉妒恶人；",
"",
"——【箴言 24】",
],
[
"7 They are all hot as an oven, and have devoured their judges; all their kings are fallen: there is none among them that calleth unto me.",
"8 Ephraim, he hath mixed himself among the people; Ephraim is a cake not turned.",
"9 Strangers have devoured his strength, and he knoweth it not: yea, gray hairs are here and there upon him, yet he knoweth not.",
"10 And the pride of Israel testifieth to his face: and they do not return to the LORD their God, nor seek him for all this.",
"",
"——【Hosea 7】",
"",
"7 众民也热如火炉，烧灭他们的官长。他们的君王都仆倒而死；他们中间无一人求告我。",
"8 以法莲与列邦人搀杂；以法莲是没有翻过的饼。",
"9 外邦人吞吃他劳力得来的，他却不知道；头发斑白，他也不觉得。",
"10 以色列的骄傲当面见证自己，虽遭遇这一切，他们仍不归向耶和华─他们的　神，也不寻求他。",
"",
"——【何西阿书 7】",
],
[
"10 And the chief priests and scribes stood and vehemently accused him.",
"11 And Herod with his men of war set him at nought, and mocked him, and arrayed him in a gorgeous robe, and sent him again to Pilate.",
"12 And the same day Pilate and Herod were made friends together: for before they were at enmity between themselves.",
"13 And Pilate, when he had called together the chief priests and the rulers and the people,",
"14 Said unto them, Ye have brought this man unto me, as one that perverteth the people: and, behold, I, having examined him before you, have found no fault in this man touching those things whereof ye accuse him:",
"",
"——【The Gospel According to Saint Luke 23】",
"",
"10 祭司长和文士都站著，极力的告他。",
"11 希律和他的兵丁就藐视耶稣，戏弄他，给他穿上华丽衣服，把他送回彼拉多那里去。",
"12 从前希律和彼拉多彼此有仇，在那一天就成了朋友。",
"13 彼拉多传齐了祭司长和官府并百姓，",
"14 就对他们说：你们解这人到我这里，说他是诱惑百姓的。看哪，我也曾将你们告他的事，在你们面前审问他，并没有查出他什么罪来；",
"",
"——【路加福音 23】",
],
[
"9 And the Levites: both Jeshua the son of Azaniah, Binnui of the sons of Henadad, Kadmiel;",
"10 And their brethren, Shebaniah, Hodijah, Kelita, Pelaiah, Hanan,",
"11 Micha, Rehob, Hashabiah,",
"12 Zaccur, Sherebiah, Shebaniah,",
"",
"——【The Book of Nehemiah 10】",
"",
"9 又有利未人，就是亚散尼的儿子耶书亚、希拿达的子孙宾内、甲篾；",
"10 还有他们的弟兄示巴尼、荷第雅、基利他、毗莱雅、哈难、",
"11 米迦、利合、哈沙比雅、",
"12 撒刻、示利比、示巴尼、",
"",
"——【尼希米记 10】",
],
[
"1 Therefore, my brethren dearly beloved and longed for, my joy and crown, so stand fast in the Lord, my dearly beloved.",
"2 I beseech Euodias, and beseech Syntyche, that they be of the same mind in the Lord.",
"3 And I intreat thee also, true yokefellow, help those women which laboured with me in the gospel, with Clement also, and with other my fellowlabourers, whose names are in the book of life.",
"4 Rejoice in the Lord alway: and again I say, Rejoice.",
"5 Let your moderation be known unto all men. The Lord is at hand.",
"",
"——【The Epistle of Paul the Apostle to the Philippians 4】",
"",
"1 我所亲爱、所想念的弟兄们，你们就是我的喜乐，我的冠冕。我亲爱的弟兄，你们应当靠主站立得稳。",
"2 我劝友阿爹和循都基，要在主里同心。",
"3 我也求你这真实同负一轭的，帮助这两个女人，因为他们在福音上曾与我一同劳苦；还有革利免，并其余和我一同做工的，他们的名字都在生命册上。",
"4 你们要靠主常常喜乐。我再说，你们要喜乐。",
"5 当叫众人知道你们谦让的心。主已经近了。",
"",
"——【腓立比书 4】",
],
[
"8 And he shall not look to the altars, the work of his hands, neither shall respect that which his fingers have made, either the groves, or the images.",
"9 In that day shall his strong cities be as a forsaken bough, and an uppermost branch, which they left because of the children of Israel: and there shall be desolation.",
"10 Because thou hast forgotten the God of thy salvation, and hast not been mindful of the rock of thy strength, therefore shalt thou plant pleasant plants, and shalt set it with strange slips:",
"11 In the day shalt thou make thy plant to grow, and in the morning shalt thou make thy seed to flourish: but the harvest shall be a heap in the day of grief and of desperate sorrow.",
"12 Woe to the multitude of many people, which make a noise like the noise of the seas; and to the rushing of nations, that make a rushing like the rushing of mighty waters!",
"",
"——【The Book of the Prophet Isaiah 17】",
"",
"8 他们必不仰望祭坛，就是自己手所筑的，也不重看自己指头所做的，无论是木偶是日像。",
"9 在那日，他们的坚固城必像树林中和山顶上所撇弃的地方，就是从前在以色列人面前被人撇弃的。这样，地就荒凉了。",
"10 因你忘记救你的　神，不记念你能力的磐石；所以，你栽上佳美的树秧子，插上异样的栽子。",
"11 栽种的日子，你周围圈上篱笆，又到早晨使你所种的开花；但在愁苦极其伤痛的日子，所收割的都飞去了。",
"12 唉！多民鬨嚷，好像海浪匉訇；列邦奔腾，好像猛水滔滔；",
"",
"——【以赛亚书 17】",
],
[
"13 The sons of Amram; Aaron and Moses: and Aaron was separated, that he should sanctify the most holy things, he and his sons for ever, to burn incense before the LORD, to minister unto him, and to bless in his name for ever.",
"14 Now concerning Moses the man of God, his sons were named of the tribe of Levi.",
"15 The sons of Moses were, Gershom, and Eliezer.",
"",
"——【The First Book of the Chronicles 23】",
"",
"13 暗兰的儿子是亚伦、摩西。亚伦和他的子孙分出来，好分别至圣的物，在耶和华面前烧香、事奉他，奉他的名祝福，直到永远。",
"14 至于神人摩西，他的子孙名字记在利未支派的册上。",
"15 摩西的儿子是革舜和以利以谢。",
"",
"——【历代志上 23】",
],
[
"25 The baptism of John, whence was it? from heaven, or of men? And they reasoned with themselves, saying, If we shall say, From heaven; he will say unto us, Why did ye not then believe him?",
"26 But if we shall say, Of men; we fear the people; for all hold John as a prophet.",
"27 And they answered Jesus, and said, We cannot tell. And he said unto them, Neither tell I you by what authority I do these things.",
"28 But what think ye? A certain man had two sons; and he came to the first, and said, Son, go work to day in my vineyard.",
"",
"——【The Gospel According to Saint Matthew 21】",
"",
"25 约翰的洗礼是从那里来的？是从天上来的？是从人间来的呢？他们彼此商议说：我们若说从天上来，他必对我们说：这样，你们为什么不信他呢？",
"26 若说从人间来，我们又怕百姓，因为他们都以约翰为先知。",
"27 于是回答耶稣说：我们不知道。耶稣说：我也不告诉你们我仗著什么权柄做这些事。",
"28 又说：一个人有两个儿子。他来对大儿子说：我儿，你今天到葡萄园里去做工。",
"",
"——【马太福音 21】",
],
[
"11 No meat offering, which ye shall bring unto the LORD, shall be made with leaven: for ye shall burn no leaven, nor any honey, in any offering of the LORD made by fire.",
"12 As for the oblation of the firstfruits, ye shall offer them unto the LORD: but they shall not be burnt on the altar for a sweet savour.",
"13 And every oblation of thy meat offering shalt thou season with salt; neither shalt thou suffer the salt of the covenant of thy God to be lacking from thy meat offering: with all thine offerings thou shalt offer salt.",
"14 And if thou offer a meat offering of thy firstfruits unto the LORD, thou shalt offer for the meat offering of thy firstfruits green ears of corn dried by the fire, even corn beaten out of full ears.",
"15 And thou shalt put oil upon it, and lay frankincense thereon: it is a meat offering.",
"16 And the priest shall burn the memorial of it, part of the beaten corn thereof, and part of the oil thereof, with all the frankincense thereof: it is an offering made by fire unto the LORD.",
"",
"——【The Third Book of Moses: Called Leviticus 2】",
"",
"11 「凡献给耶和华的素祭都不可有酵；因为你们不可烧一点酵、一点蜜当作火祭献给耶和华。",
"12 这些物要献给耶和华作为初熟的供物，只是不可在坛上献为馨香的祭。",
"13 凡献为素祭的供物都要用盐调和，在素祭上不可缺了你　神立约的盐。一切的供物都要配盐而献。",
"14 若向耶和华献初熟之物为素祭，要献上烘了的禾穗子，就是轧了的新穗子，当作初熟之物的素祭。",
"15 并要抹上油，加上乳香；这是素祭。",
"16 祭司要把其中作为纪念的，就是一些轧了的禾穗子和一些油，并所有的乳香，都焚烧，是向耶和华献的火祭。」",
"",
"——【利未记 2】",
],
[
"1 My son, if thou be surety for thy friend, if thou hast stricken thy hand with a stranger,",
"2 Thou art snared with the words of thy mouth, thou art taken with the words of thy mouth.",
"3 Do this now, my son, and deliver thyself, when thou art come into the hand of thy friend; go, humble thyself, and make sure thy friend.",
"4 Give not sleep to thine eyes, nor slumber to thine eyelids.",
"",
"——【The Proverbs 6】",
"",
"1 我儿，你若为朋友作保，替外人击掌，",
"2 你就被口中的话语缠住，被嘴里的言语捉住。",
"3 我儿，你既落在朋友手中，就当这样行才可救自己：你要自卑，去恳求你的朋友。",
"4 不要容你的眼睛睡觉；不要容你的眼皮打盹。",
"",
"——【箴言 6】",
],
[
"21 For to me to live is Christ, and to die is gain.",
"22 But if I live in the flesh, this is the fruit of my labour: yet what I shall choose I wot not.",
"23 For I am in a strait betwixt two, having a desire to depart, and to be with Christ; which is far better:",
"24 Nevertheless to abide in the flesh is more needful for you.",
"25 And having this confidence, I know that I shall abide and continue with you all for your furtherance and joy of faith;",
"26 That your rejoicing may be more abundant in Jesus Christ for me by my coming to you again.",
"",
"——【The Epistle of Paul the Apostle to the Philippians 1】",
"",
"21 因我活著就是基督，我死了就有益处。",
"22 但我在肉身活著，若成就我工夫的果子，我就不知道该挑选什么。",
"23 我正在两难之间，情愿离世与基督同在，因为这是好得无比的。",
"24 然而，我在肉身活著，为你们更是要紧的。",
"25 我既然这样深信，就知道仍要住在世间，且与你们众人同住，使你们在所信的道上又长进又喜乐，",
"26 叫你们在基督耶稣里的欢乐，因我再到你们那里去，就越发加增。",
"",
"——【腓立比书 1】",
],
[
"4 And the burnt offering that the prince shall offer unto the LORD in the sabbath day shall be six lambs without blemish, and a ram without blemish.",
"5 And the meat offering shall be an ephah for a ram, and the meat offering for the lambs as he shall be able to give, and an hin of oil to an ephah.",
"6 And in the day of the new moon it shall be a young bullock without blemish, and six lambs, and a ram: they shall be without blemish.",
"7 And he shall prepare a meat offering, an ephah for a bullock, and an ephah for a ram, and for the lambs according as his hand shall attain unto, and an hin of oil to an ephah.",
"",
"——【The Book of the Prophet Ezekiel 46】",
"",
"4 安息日，王所献与耶和华的燔祭要用无残疾的羊羔六只，无残疾的公绵羊一只；",
"5 同献的素祭要为公绵羊献一伊法细面，为羊羔照他的力量而献，一伊法细面加油一欣。",
"6 当月朔，要献无残疾的公牛犊一只，羊羔六只，公绵羊一只，都要无残疾的。",
"7 他也要预备素祭，为公牛献一伊法细面，为公绵羊献一伊法细面，为羊羔照他的力量而献，一伊法细面加油一欣。",
"",
"——【以西结书 46】",
],
[
"3 And though I bestow all my goods to feed the poor, and though I give my body to be burned, and have not charity, it profiteth me nothing.",
"4 Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up,",
"",
"——【The First Epistle of Paul the Apostle to the Corinthians 13】",
"",
"3 我若将所有的赒济穷人，又舍己身叫人焚烧，却没有爱，仍然与我无益。",
"4 爱是恒久忍耐，又有恩慈；爱是不嫉妒；爱是不自夸，不张狂，",
"",
"——【哥林多前书 13】",
],
[
"5 Remember therefore from whence thou art fallen, and repent, and do the first works; or else I will come unto thee quickly, and will remove thy candlestick out of his place, except thou repent.",
"6 But this thou hast, that thou hatest the deeds of the Nicolaitans, which I also hate.",
"",
"——【The Revelation of Saint John the Devine 2】",
"",
"5 所以，应当回想你是从那里坠落的，并要悔改，行起初所行的事。你若不悔改，我就临到你那里，把你的灯台从原处挪去。",
"6 然而你还有一件可取的事，就是你恨恶尼哥拉一党人的行为，这也是我所恨恶的。",
"",
"——【启示录 2】",
],
[
"21 For the king's ships went to Tarshish with the servants of Huram: every three years once came the ships of Tarshish bringing gold, and silver, ivory, and apes, and peacocks.",
"22 And king Solomon passed all the kings of the earth in riches and wisdom.",
"23 And all the kings of the earth sought the presence of Solomon, to hear his wisdom, that God had put in his heart.",
"24 And they brought every man his present, vessels of silver, and vessels of gold, and raiment, harness, and spices, horses, and mules, a rate year by year.",
"25 And Solomon had four thousand stalls for horses and chariots, and twelve thousand horsemen; whom he bestowed in the chariot cities, and with the king at Jerusalem.",
"26 And he reigned over all the kings from the river even unto the land of the Philistines, and to the border of Egypt.",
"",
"——【The Second Book of the Chronicles 9】",
"",
"21 因为王的船只与希兰的仆人一同往他施去；他施船只三年一次装载金、银、象牙、猿猴、孔雀回来。",
"22 所罗门王的财宝与智慧胜过天下的列王。",
"23 普天下的王都求见所罗门，要听　神赐给他智慧的话。",
"24 他们各带贡物，就是金器、银器、衣服、军械、香料、骡马，每年有一定之例。",
"25 所罗门有套车的马四千棚，有马兵一万二千，安置在屯车的城邑和耶路撒冷，就是王那里。",
"26 所罗门统管诸王，从大河到非利士地，直到埃及的边界。",
"",
"——【历代志下 9】",
],
[
"1 Make haste, O God, to deliver me; make haste to help me, O LORD.",
"2 Let them be ashamed and confounded that seek after my soul: let them be turned backward, and put to confusion, that desire my hurt.",
"3 Let them be turned back for a reward of their shame that say, Aha, aha.",
"4 Let all those that seek thee rejoice and be glad in thee: and let such as love thy salvation say continually, Let God be magnified.",
"5 But I am poor and needy: make haste unto me, O God: thou art my help and my deliverer; O LORD, make no tarrying.",
"",
"——【The Book of Psalms 70】",
"",
"1 （大卫的记念诗，交与伶长。）　神啊，求你快快搭救我！耶和华啊，求你速速帮助我！",
"2 愿那些寻索我命的，抱愧蒙羞；愿那些喜悦我遭害的，退后受辱。",
"3 愿那些对我说阿哈、阿哈的，因羞愧退后。",
"4 愿一切寻求你的，因你高兴欢喜；愿那些喜爱你救恩的，常说：当尊　神为大！",
"5 但我是困苦穷乏的；　神啊，求你速速到我这里来！你是帮助我的，搭救我的。耶和华啊，求你不要耽延！",
"",
"——【诗篇 70】",
],
[
"8 And of the Gadites there separated themselves unto David into the hold to the wilderness men of might, and men of war fit for the battle, that could handle shield and buckler, whose faces were like the faces of lions, and were as swift as the roes upon the mountains;",
"9 Ezer the first, Obadiah the second, Eliab the third,",
"10 Mishmannah the fourth, Jeremiah the fifth,",
"",
"——【The First Book of the Chronicles 12】",
"",
"8 迦得支派中有人到旷野的山寨投奔大卫，都是大能的勇士，能拿盾牌和枪的战士。他们的面貌好像狮子，快跑如同山上的鹿。",
"9 第一以薛，第二俄巴底雅，第三以利押，",
"10 第四弥施玛拿，第五耶利米，",
"",
"——【历代志上 12】",
],
[
"2 Son of man, set thy face against the Ammonites, and prophesy against them;",
"3 And say unto the Ammonites, Hear the word of the Lord GOD; Thus saith the Lord GOD; Because thou saidst, Aha, against my sanctuary, when it was profaned; and against the land of Israel, when it was desolate; and against the house of Judah, when they went into captivity;",
"4 Behold, therefore I will deliver thee to the men of the east for a possession, and they shall set their palaces in thee, and make their dwellings in thee: they shall eat thy fruit, and they shall drink thy milk.",
"5 And I will make Rabbah a stable for camels, and the Ammonites a couchingplace for flocks: and ye shall know that I am the LORD.",
"",
"——【The Book of the Prophet Ezekiel 25】",
"",
"2 「人子啊，你要面向亚扪人说预言，攻击他们，",
"3 说：你们当听主耶和华的话。主耶和华如此说：我的圣所被亵渎，以色列地变荒凉，犹大家被掳掠；那时，你便因这些事说：『阿哈！』",
"4 所以我必将你的地交给东方人为业；他们必在你的地上安营居住，吃你的果子，喝你的奶。",
"5 我必使拉巴为骆驼场，使亚扪人的地为羊群躺卧之处，你们就知道我是耶和华。」",
"",
"——【以西结书 25】",
],
[
"1 And it came to pass, when Jesus had made an end of commanding his twelve disciples, he departed thence to teach and to preach in their cities.",
"2 Now when John had heard in the prison the works of Christ, he sent two of his disciples,",
"3 And said unto him, Art thou he that should come, or do we look for another?",
"",
"——【The Gospel According to Saint Matthew 11】",
"",
"1 耶稣吩咐完了十二个门徒，就离开那里，往各城去传道，教训人。",
"2 约翰在监里听见基督所作的事，就打发两个门徒去，",
"3 问他说：那将要来的是你吗？还是我们等候别人呢？",
"",
"——【马太福音 11】",
],
[
"15 And the LORD spake unto Joshua, saying,",
"16 Command the priests that bear the ark of the testimony, that they come up out of Jordan.",
"17 Joshua therefore commanded the priests, saying, Come ye up out of Jordan.",
"",
"——【The Book of Joshua 4】",
"",
"15 耶和华晓谕约书亚说：",
"16 「你吩咐抬法柜的祭司从约旦河里上来。」",
"17 约书亚就吩咐祭司说：「你们从约旦河里上来。」",
"",
"——【约书亚记 4】",
],
[
"1 Praise ye the LORD. Praise, O ye servants of the LORD, praise the name of the LORD.",
"2 Blessed be the name of the LORD from this time forth and for evermore.",
"",
"——【The Book of Psalms 113】",
"",
"1 你们要赞美耶和华！耶和华的仆人哪，你们要赞美，赞美耶和华的名。",
"2 耶和华的名是应当称颂的，从今时直到永远！",
"",
"——【诗篇 113】",
],
[
"4 And the LORD shall do unto them as he did to Sihon and to Og, kings of the Amorites, and unto the land of them, whom he destroyed.",
"5 And the LORD shall give them up before your face, that ye may do unto them according unto all the commandments which I have commanded you.",
"6 Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.",
"7 And Moses called unto Joshua, and said unto him in the sight of all Israel, Be strong and of a good courage: for thou must go with this people unto the land which the LORD hath sworn unto their fathers to give them; and thou shalt cause them to inherit it.",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 31】",
"",
"4 耶和华必待他们，如同从前待他所灭绝的亚摩利二王西宏与噩以及他们的国一样。",
"5 耶和华必将他们交给你们；你们要照我所吩咐的一切命令待他们。",
"6 你们当刚强壮胆，不要害怕，也不要畏惧他们，因为耶和华─你的　神和你同去。他必不撇下你，也不丢弃你。」",
"7 摩西召了约书亚来，在以色列众人眼前对他说：「你当刚强壮胆！因为，你要和这百姓一同进入耶和华向他们列祖起誓应许所赐之地；你也要使他们承受那地为业。",
"",
"——【申命记 31】",
],
[
"20 And David rose up early in the morning, and left the sheep with a keeper, and took, and went, as Jesse had commanded him; and he came to the trench, as the host was going forth to the fight, and shouted for the battle.",
"21 For Israel and the Philistines had put the battle in array, army against army.",
"22 And David left his carriage in the hand of the keeper of the carriage, and ran into the army, and came and saluted his brethren.",
"23 And as he talked with them, behold, there came up the champion, the Philistine of Gath, Goliath by name, out of the armies of the Philistines, and spake according to the same words: and David heard them.",
"24 And all the men of Israel, when they saw the man, fled from him, and were sore afraid.",
"25 And the men of Israel said, Have ye seen this man that is come up? surely to defy Israel is he come up: and it shall be, that the man who killeth him, the king will enrich him with great riches, and will give him his daughter, and make his father's house free in Israel.",
"",
"——【The First Book of Samuel 17】",
"",
"20 大卫早晨起来，将羊交托一个看守的人，照著他父亲所吩咐的话，带著食物去了。到了辎重营，军兵刚出到战场，呐喊要战。",
"21 以色列人和非利士人都摆列队伍，彼此相对。",
"22 大卫把他带来的食物留在看守物件人的手下，跑到战场，问他哥哥们安。",
"23 与他们说话的时候，那讨战的，就是属迦特的非利士人歌利亚，从非利士队中出来，说从前所说的话；大卫都听见了。",
"24 以色列众人看见那人，就逃跑，极其害怕。",
"25 以色列人彼此说：「这上来的人你看见了吗？他上来是要向以色列人骂阵。若有能杀他的，王必赏赐他大财，将自己的女儿给他为妻，并在以色列人中免他父家纳粮当差。」",
"",
"——【撒母耳记上 17】",
],
[
"5 What will ye do in the solemn day, and in the day of the feast of the LORD?",
"6 For, lo, they are gone because of destruction: Egypt shall gather them up, Memphis shall bury them: the pleasant places for their silver, nettles shall possess them: thorns shall be in their tabernacles.",
"7 The days of visitation are come, the days of recompence are come; Israel shall know it: the prophet is a fool, the spiritual man is mad, for the multitude of thine iniquity, and the great hatred.",
"8 The watchman of Ephraim was with my God: but the prophet is a snare of a fowler in all his ways, and hatred in the house of his God.",
"9 They have deeply corrupted themselves, as in the days of Gibeah: therefore he will remember their iniquity, he will visit their sins.",
"10 I found Israel like grapes in the wilderness; I saw your fathers as the firstripe in the fig tree at her first time: but they went to Baal–peor, and separated themselves unto that shame; and their abominations were according as they loved.",
"",
"——【Hosea 9】",
"",
"5 在大会的日子，到耶和华的节期，你们怎样行呢？",
"6 看哪，他们逃避灾难；埃及人必收殓他们的尸首，摩弗人必葬埋他们的骸骨。他们用银子做的美物上必长蒺藜；他们的帐棚中必生荆棘。",
"7 以色列人必知道降罚的日子临近，报应的时候来到。民说：作先知的是愚昧；受灵感的是狂妄，皆因他们多多作孽，大怀怨恨。",
"8 以法莲曾作我　神守望的；至于先知，在他一切的道上作为捕鸟人的网罗，在他　神的家中怀怨恨。",
"9 以法莲深深地败坏，如在基比亚的日子一样。耶和华必记念他们的罪孽，追讨他们的罪恶。",
"10 主说：我遇见以色列如葡萄在旷野；我看见你们的列祖如无花果树上春季初熟的果子。他们却来到巴力‧毗珥专拜那可羞耻的，就成为可憎恶的，与他们所爱的一样。",
"",
"——【何西阿书 9】",
],
[
"49 She bare also Shaaph the father of Madmannah, Sheva the father of Machbenah, and the father of Gibea: and the daughter of Caleb was Achsah.",
"50 These were the sons of Caleb the son of Hur, the firstborn of Ephratah; Shobal the father of Kirjath–jearim,",
"51 Salma the father of Beth–lehem, Hareph the father of Beth–gader.",
"52 And Shobal the father of Kirjath–jearim had sons; Haroeh, and half of the Manahethites.",
"53 And the families of Kirjath–jearim; the Ithrites, and the Puhites, and the Shumathites, and the Mishraites; of them came the Zareathites, and the Eshtaulites.",
"54 The sons of Salma; Beth–lehem, and the Netophathites, Ataroth, the house of Joab, and half of the Manahethites, the Zorites.",
"",
"——【The First Book of the Chronicles 2】",
"",
"49 又生麦玛拿之祖沙亚弗、抹比拿和基比亚之祖示法。迦勒的女儿是押撒。",
"50 迦勒的子孙就是以法她的长子、户珥的儿子，记在下面：基列‧耶琳之祖朔巴，",
"51 伯利恒之祖萨玛，伯迦得之祖哈勒。",
"52 基列‧耶琳之祖朔巴的子孙是哈罗以和一半米努哈人【即玛拿哈人】。",
"53 基列‧耶琳的诸族是以帖人、布特人、舒玛人、密来人，又从这些族中生出琐拉人和以实陶人来。",
"54 萨玛的子孙是伯利恒人、尼陀法人、亚他绿‧伯‧约押人、一半玛拿哈人、琐利人，",
"",
"——【历代志上 2】",
],
[
"1 Then the prophets, Haggai the prophet, and Zechariah the son of Iddo, prophesied unto the Jews that were in Judah and Jerusalem in the name of the God of Israel, even unto them.",
"2 Then rose up Zerubbabel the son of Shealtiel, and Jeshua the son of Jozadak, and began to build the house of God which is at Jerusalem: and with them were the prophets of God helping them.",
"3 At the same time came to them Tatnai, governor on this side the river, and Shethar–boznai, and their companions, and said thus unto them, Who hath commanded you to build this house, and to make up this wall?",
"4 Then said we unto them after this manner, What are the names of the men that make this building?",
"5 But the eye of their God was upon the elders of the Jews, that they could not cause them to cease, till the matter came to Darius: and then they returned answer by letter concerning this matter.",
"6 The copy of the letter that Tatnai, governor on this side the river, and Shethar–boznai, and his companions the Apharsachites, which were on this side the river, sent unto Darius the king:",
"",
"——【Ezra 5】",
"",
"1 那时，先知哈该和易多的孙子撒迦利亚奉以色列　神的名向犹大和耶路撒冷的犹大人说劝勉的话。",
"2 于是撒拉铁的儿子所罗巴伯和约萨达的儿子耶书亚都起来动手建造耶路撒冷　神的殿，有　神的先知在那里帮助他们。",
"3 当时河西的总督达乃和示他•波斯乃，并他们的同党来问说：「谁降旨让你们建造这殿，修成这墙呢？」",
"4 我们便告诉他们建造这殿的人叫什么名字。",
"5 　神的眼目看顾犹大的长老，以致总督等没有叫他们停工，直到这事奏告大利乌，得著他的回谕。",
"6 河西的总督达乃和示他•波斯乃，并他们的同党，就是住河西的亚法萨迦人，上本奏告大利乌王。",
"",
"——【以斯拉记 5】",
],
];
