var bible31_global=[
[
"1 Hear my cry, O God; attend unto my prayer.",
"2 From the end of the earth will I cry unto thee, when my heart is overwhelmed: lead me to the rock that is higher than I.",
"3 For thou hast been a shelter for me, and a strong tower from the enemy.",
"4 I will abide in thy tabernacle for ever: I will trust in the covert of thy wings. Selah.",
"5 For thou, O God, hast heard my vows: thou hast given me the heritage of those that fear thy name.",
"",
"——【The Book of Psalms 61】",
"",
"1 （大卫的诗，交与伶长。用丝弦的乐器。）　神啊，求你听我的呼求，侧耳听我的祷告！",
"2 我心里发昏的时候，我要从地极求告你。求你领我到那比我更高的磐石！",
"3 因为你作过我的避难所，作过我的坚固台，脱离仇敌。",
"4 我要永远住在你的帐幕里！我要投靠在你翅膀下的隐密处！（细拉）",
"5 　神啊，你原是听了我所许的愿；你将产业赐给敬畏你名的人。",
"",
"——【诗篇 61】",
],
[
"7 Thus he shewed me: and, behold, the Lord stood upon a wall made by a plumbline, with a plumbline in his hand.",
"8 And the LORD said unto me, Amos, what seest thou? And I said, A plumbline. Then said the Lord, Behold, I will set a plumbline in the midst of my people Israel: I will not again pass by them any more:",
"9 And the high places of Isaac shall be desolate, and the sanctuaries of Israel shall be laid waste; and I will rise against the house of Jeroboam with the sword.",
"10 Then Amaziah the priest of Beth–el sent to Jeroboam king of Israel, saying, Amos hath conspired against thee in the midst of the house of Israel: the land is not able to bear all his words.",
"11 For thus Amos saith, Jeroboam shall die by the sword, and Israel shall surely be led away captive out of their own land.",
"12 Also Amaziah said unto Amos, O thou seer, go, flee thee away into the land of Judah, and there eat bread, and prophesy there:",
"",
"——【Amos 7】",
"",
"7 他又指示我一件事：有一道墙是按准绳建筑的，主手拿准绳站在其上。",
"8 耶和华对我说：「阿摩司啊，你看见什么？」我说：「看见准绳。」主说：「我要吊起准绳在我民以色列中，我必不再宽恕他们。",
"9 以撒的邱坛必然凄凉，以色列的圣所必然荒废。我必兴起，用刀攻击耶罗波安的家。」",
"10 伯特利的祭司亚玛谢打发人到以色列王耶罗波安那里，说：「阿摩司在以色列家中图谋背叛你；他所说的一切话，这国担当不起；",
"11 因为阿摩司如此说：『耶罗波安必被刀杀，以色列民定被掳去离开本地。』」",
"12 亚玛谢又对阿摩司说：「你这先见哪，要逃往犹大地去，在那里糊口，在那里说预言，",
"",
"——【阿摩司书 7】",
],
[
"6 For which things' sake the wrath of God cometh on the children of disobedience:",
"7 In the which ye also walked some time, when ye lived in them.",
"8 But now ye also put off all these; anger, wrath, malice, blasphemy, filthy communication out of your mouth.",
"9 Lie not one to another, seeing that ye have put off the old man with his deeds;",
"",
"——【The Epistle of Paul the Apostle to the Colossians 3】",
"",
"6 因这些事，　神的忿怒必临到那悖逆之子。",
"7 当你们在这些事中活着的时候，也曾这样行过。",
"8 但现在你们要弃绝这一切的事，以及恼恨、忿怒、恶毒（或作：阴毒）、毁谤，并口中污秽的言语。",
"9 不要彼此说谎；因你们已经脱去旧人和旧人的行为，",
"",
"——【歌罗西书 3】",
],
[
"32 And Mikloth begat Shimeah. And these also dwelt with their brethren in Jerusalem, over against them.",
"33 And Ner begat Kish, and Kish begat Saul, and Saul begat Jonathan, and Malchi–shua, and Abinadab, and Esh–baal.",
"34 And the son of Jonathan was Merib–baal; and Merib–baal begat Micah.",
"35 And the sons of Micah were, Pithon, and Melech, and Tarea, and Ahaz.",
"36 And Ahaz begat Jehoadah; and Jehoadah begat Alemeth, and Azmaveth, and Zimri; and Zimri begat Moza,",
"",
"——【The First Book of the Chronicles 8】",
"",
"32 米基罗生示米暗。这些人和他们的弟兄在耶路撒冷对面居住。",
"33 尼珥生基士；基士生扫罗；扫罗生约拿单、麦基舒亚、亚比拿达、伊施巴力。",
"34 约拿单的儿子是米力巴力【撒下四章四节作米非波设】；米力巴力生米迦。",
"35 米迦的儿子是毗敦、米勒、他利亚、亚哈斯；",
"36 亚哈斯生耶何阿达；耶何阿达生亚拉篾、亚斯玛威、心利；心利生摩撒；",
"",
"——【历代志上 8】",
],
[
"17 Now Jonathan and Ahimaaz stayed by En–rogel; for they might not be seen to come into the city: and a wench went and told them; and they went and told king David.",
"18 Nevertheless a lad saw them, and told Absalom: but they went both of them away quickly, and came to a man's house in Bahurim, which had a well in his court; whither they went down.",
"19 And the woman took and spread a covering over the well's mouth, and spread ground corn thereon; and the thing was not known.",
"20 And when Absalom's servants came to the woman to the house, they said, Where is Ahimaaz and Jonathan? And the woman said unto them, They be gone over the brook of water. And when they had sought and could not find them, they returned to Jerusalem.",
"21 And it came to pass, after they were departed, that they came up out of the well, and went and told king David, and said unto David, Arise, and pass quickly over the water: for thus hath Ahithophel counselled against you.",
"",
"——【The Second Book of Samuel 17】",
"",
"17 那时，约拿单和亚希玛斯在隐‧罗结那里等候，不敢进城，恐怕被人看见。有一个使女出来，将这话告诉他们，他们就去报信给大卫王。",
"18 然而有一个童子看见他们，就去告诉押沙龙。他们急忙跑到巴户琳某人的家里；那人院中有一口井，他们就下到井里。",
"19 那家的妇人用盖盖上井口，又在上头铺上碎麦，事就没有洩漏。",
"20 押沙龙的仆人来到那家，问妇人说：「亚希玛斯和约拿单在哪里？」妇人说：「他们过了河了。」仆人找他们，找不着，就回耶路撒冷去了。",
"21 他们走后，二人从井里上来，去告诉大卫王说：「亚希多弗如此如此定计害你，你们务要起来，快快过河。」",
"",
"——【撒母耳记下 17】",
],
[
"4 Surely he hath borne our griefs, and carried our sorrows: yet we did esteem him stricken, smitten of God, and afflicted.",
"5 But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed.",
"6 All we like sheep have gone astray; we have turned every one to his own way; and the LORD hath laid on him the iniquity of us all.",
"",
"——【The Book of the Prophet Isaiah 53】",
"",
"4 他诚然担当我们的忧患，背负我们的痛苦；我们却以为他受责罚，被　神击打苦待了。",
"5 哪知他为我们的过犯受害，为我们的罪孽压伤。因他受的刑罚，我们得平安；因他受的鞭伤，我们得医治。",
"6 我们都如羊走迷；各人偏行己路；耶和华使我们众人的罪孽都归在他身上。",
"",
"——【以赛亚书 53】",
],
[
"24 Or if there be any flesh, in the skin whereof there is a hot burning, and the quick flesh that burneth have a white bright spot, somewhat reddish, or white;",
"25 Then the priest shall look upon it: and, behold, if the hair in the bright spot be turned white, and it be in sight deeper than the skin; it is a leprosy broken out of the burning: wherefore the priest shall pronounce him unclean: it is the plague of leprosy.",
"26 But if the priest look on it, and, behold, there be no white hair in the bright spot, and it be no lower than the other skin, but be somewhat dark; then the priest shall shut him up seven days:",
"27 And the priest shall look upon him the seventh day: and if it be spread much abroad in the skin, then the priest shall pronounce him unclean: it is the plague of leprosy.",
"28 And if the bright spot stay in his place, and spread not in the skin, but it be somewhat dark; it is a rising of the burning, and the priest shall pronounce him clean: for it is an inflammation of the burning.",
"29 If a man or woman have a plague upon the head or the beard;",
"",
"——【The Third Book of Moses: Called Leviticus 13】",
"",
"24 「人的皮肉上若起了火毒，火毒的瘀肉成了火斑，或是白中带红的，或是全白的，",
"25 祭司就要察看，火斑中的毛若变白了，现象又深于皮，是大痲疯在火毒中发出，就要定他为不洁净，是大痲疯的灾病。",
"26 但是祭司察看，在火斑中若没有白毛，也没有洼于皮，乃是发暗，就要将他关锁七天。",
"27 到第七天，祭司要察看他，火斑若在皮上发散开了，就要定他为不洁净，是大痲疯的灾病。",
"28 火斑若在原处止住，没有在皮上发散，乃是发暗，是起的火毒，祭司要定他为洁净，不过是火毒的痕迹。",
"29 「无论男女，若在头上有灾病，或是男人胡须上有灾病，",
"",
"——【利未记 13】",
],
[
"37 He answered and said unto them, Give ye them to eat. And they say unto him, Shall we go and buy two hundred pennyworth of bread, and give them to eat?",
"38 He saith unto them, How many loaves have ye? go and see. And when they knew, they say, Five, and two fishes.",
"39 And he commanded them to make all sit down by companies upon the green grass.",
"",
"——【The Gospel According to Saint Mark 6】",
"",
"37 耶稣回答说：你们给他们吃吧。门徒说：我们可以去买二十两银子的饼，给他们吃吗？",
"38 耶稣说：你们有多少饼，可以去看看。他们知道了，就说：五个饼，两条鱼。",
"39 耶稣吩咐他们，叫众人一帮一帮的坐在青草地上。",
"",
"——【马可福音 6】",
],
[
"1 Then the LORD said unto Moses, Go in unto Pharaoh, and tell him, Thus saith the LORD God of the Hebrews, Let my people go, that they may serve me.",
"2 For if thou refuse to let them go, and wilt hold them still,",
"3 Behold, the hand of the LORD is upon thy cattle which is in the field, upon the horses, upon the asses, upon the camels, upon the oxen, and upon the sheep: there shall be a very grievous murrain.",
"4 And the LORD shall sever between the cattle of Israel and the cattle of Egypt: and there shall nothing die of all that is the children's of Israel.",
"",
"——【The Second Book of Moses: Called Exodus 9】",
"",
"1 耶和华吩咐摩西说：「你进去见法老，对他说：耶和华─希伯来人的　神这样说：容我的百姓去，好事奉我。",
"2 你若不肯容他们去，仍旧强留他们，",
"3 耶和华的手加在你田间的牲畜上，就是在马、驴、骆驼、牛群、羊群上，必有重重的瘟疫。",
"4 耶和华要分别以色列的牲畜和埃及的牲畜，凡属以色列人的，一样都不死。』」",
"",
"——【出埃及记 9】",
],
[
"57 And he denied him, saying, Woman, I know him not.",
"58 And after a little while another saw him, and said, Thou art also of them. And Peter said, Man, I am not.",
"",
"——【The Gospel According to Saint Luke 22】",
"",
"57 彼得却不承认，说：女子，我不认得他。",
"58 过了不多的时候，又有一个人看见他，说：你也是他们一党的。彼得说：你这个人！我不是。",
"",
"——【路加福音 22】",
],
[
"1 My soul is weary of my life; I will leave my complaint upon myself; I will speak in the bitterness of my soul.",
"2 I will say unto God, Do not condemn me; shew me wherefore thou contendest with me.",
"3 Is it good unto thee that thou shouldest oppress, that thou shouldest despise the work of thine hands, and shine upon the counsel of the wicked?",
"",
"——【The Book of Job 10】",
"",
"1 我厌烦我的性命，必由著自己述说我的哀情；因心里苦恼，我要说话，",
"2 对　神说：不要定我有罪，要指示我，你为何与我争辩？",
"3 你手所造的，你又欺压，又藐视，却光照恶人的计谋。这事你以为美吗？",
"",
"——【约伯记 10】",
],
[
"16 But they mocked the messengers of God, and despised his words, and misused his prophets, until the wrath of the LORD arose against his people, till there was no remedy.",
"17 Therefore he brought upon them the king of the Chaldees, who slew their young men with the sword in the house of their sanctuary, and had no compassion upon young man or maiden, old man, or him that stooped for age: he gave them all into his hand.",
"18 And all the vessels of the house of God, great and small, and the treasures of the house of the LORD, and the treasures of the king, and of his princes; all these he brought to Babylon.",
"19 And they burnt the house of God, and brake down the wall of Jerusalem, and burnt all the palaces thereof with fire, and destroyed all the goodly vessels thereof.",
"20 And them that had escaped from the sword carried he away to Babylon; where they were servants to him and his sons until the reign of the kingdom of Persia:",
"",
"——【The Second Book of the Chronicles 36】",
"",
"16 他们却嘻笑　神的使者，藐视他的言语，讥诮他的先知，以致耶和华的忿怒向他的百姓发作，无法可救。",
"17 所以，耶和华使迦勒底人的王来攻击他们，在他们圣殿里用刀杀了他们的壮丁，不怜恤他们的少男处女、老人白叟。耶和华将他们都交在迦勒底王手里。",
"18 迦勒底王将　神殿里的大小器皿与耶和华殿里的财宝，并王和众首领的财宝，都带到巴比伦去了。",
"19 迦勒底人焚烧　神的殿，拆毁耶路撒冷的城墙，用火烧了城里的宫殿，毁坏了城里宝贵的器皿。",
"20 凡脱离刀剑的，迦勒底王都掳到巴比伦去，作他和他子孙的仆婢，直到波斯国兴起来。",
"",
"——【历代志下 36】",
],
[
"16 Then Paul stood up, and beckoning with his hand said, Men of Israel, and ye that fear God, give audience.",
"17 The God of this people of Israel chose our fathers, and exalted the people when they dwelt as strangers in the land of Egypt, and with an high arm brought he them out of it.",
"",
"——【The Acts of the Apostles 13】",
"",
"16 保罗就站起来，举手，说：以色列人和一切敬畏　神的人，请听。",
"17 这以色列民的　神拣选了我们的祖宗，当民寄居埃及的时候抬举他们，用大能的手领他们出来；",
"",
"——【使徒行传 13】",
],
[
"21 For the drunkard and the glutton shall come to poverty: and drowsiness shall clothe a man with rags.",
"22 Hearken unto thy father that begat thee, and despise not thy mother when she is old.",
"23 Buy the truth, and sell it not; also wisdom, and instruction, and understanding.",
"24 The father of the righteous shall greatly rejoice: and he that begetteth a wise child shall have joy of him.",
"",
"——【The Proverbs 23】",
"",
"21 因为好酒贪食的，必致贫穷；好睡觉的，必穿破烂衣服。",
"22 你要听从生你的父亲；你母亲老了，也不可藐视她。",
"23 你当买真理；就是智慧、训诲，和聪明也都不可卖。",
"24 义人的父亲必大得快乐；人生智慧的儿子，必因他欢喜。",
"",
"——【箴言 23】",
],
[
"2 Son of man, What is the vine tree more than any tree, or than a branch which is among the trees of the forest?",
"3 Shall wood be taken thereof to do any work? or will men take a pin of it to hang any vessel thereon?",
"4 Behold, it is cast into the fire for fuel; the fire devoureth both the ends of it, and the midst of it is burned. Is it meet for any work?",
"5 Behold, when it was whole, it was meet for no work: how much less shall it be meet yet for any work, when the fire hath devoured it, and it is burned?",
"",
"——【The Book of the Prophet Ezekiel 15】",
"",
"2 「人子啊，葡萄树比别样树有什么强处？葡萄枝比众树枝有什么好处？",
"3 其上可以取木料做什么工用，可以取来做钉子挂什么器皿么？",
"4 看哪，已经抛在火中当作柴烧，火既烧了两头，中间也被烧了，还有益于工用吗？",
"5 完全的时候尚且不合乎什么工用，何况被火烧坏，还能合乎什么工用么？」",
"",
"——【以西结书 15】",
],
[
"11 For their redeemer is mighty; he shall plead their cause with thee.",
"12 Apply thine heart unto instruction, and thine ears to the words of knowledge.",
"13 Withhold not correction from the child: for if thou beatest him with the rod, he shall not die.",
"",
"——【The Proverbs 23】",
"",
"11 因他们的救赎主大有能力，他必向你为他们辨屈。",
"12 你要留心领受训诲，侧耳听从知识的言语。",
"13 不可不管教孩童；你用杖打他，他必不至于死。",
"",
"——【箴言 23】",
],
[
"6 And they sat down, and did eat and drink both of them together: for the damsel's father had said unto the man, Be content, I pray thee, and tarry all night, and let thine heart be merry.",
"7 And when the man rose up to depart, his father in law urged him: therefore he lodged there again.",
"8 And he arose early in the morning on the fifth day to depart: and the damsel's father said, Comfort thine heart, I pray thee. And they tarried until afternoon, and they did eat both of them.",
"9 And when the man rose up to depart, he, and his concubine, and his servant, his father in law, the damsel's father, said unto him, Behold, now the day draweth toward evening, I pray you tarry all night: behold, the day groweth to an end, lodge here, that thine heart may be merry; and to morrow get you early on your way, that thou mayest go home.",
"10 But the man would not tarry that night, but he rose up and departed, and came over against Jebus, which is Jerusalem; and there were with him two asses saddled, his concubine also was with him.",
"11 And when they were by Jebus, the day was far spent; and the servant said unto his master, Come, I pray thee, and let us turn in into this city of the Jebusites, and lodge in it.",
"",
"——【The Book of Judges 19】",
"",
"6 于是二人坐下一同吃喝。女子的父亲对那人说：「请你再住一夜，畅快你的心。」",
"7 那人起来要走，他岳父强留他，他又住了一宿。",
"8 到第五天，他清早起来要走，女子的父亲说：「请你吃点饭，加添心力，等到日头偏西再走。」于是二人一同吃饭。",
"9 那人同他的妾和仆人起来要走，他岳父，就是女子的父亲，对他说：「看哪，日头偏西了，请你再住一夜；天快晚了，可以在这里住宿，畅快你的心。明天早早起行回家去。」",
"10 那人不愿再住一夜，就备上那两匹驴，带著妾起身走了，来到耶布斯的对面（耶布斯就是耶路撒冷。）",
"11 临近耶布斯的时候，日头快要落了，仆人对主人说：「我们不如进这耶布斯人的城里住宿。」",
"",
"——【士师记 19】",
],
[
"1 And when Saul's son heard that Abner was dead in Hebron, his hands were feeble, and all the Israelites were troubled.",
"2 And Saul's son had two men that were captains of bands: the name of the one was Baanah, and the name of the other Rechab, the sons of Rimmon a Beerothite, of the children of Benjamin: (for Beeroth also was reckoned to Benjamin:",
"3 And the Beerothites fled to Gittaim, and were sojourners there until this day.)",
"",
"——【The Second Book of Samuel 4】",
"",
"1 扫罗的儿子伊施波设听见押尼珥死在希伯仑，手就发软；以色列众人也都惊惶",
"2 扫罗的儿子伊施波设有两个军长，一名巴拿，一名利甲，是便雅悯支派、比录人临门的儿子。比录也属便雅悯。",
"3 比录人早先逃到基他音，在那里寄居，直到今日。",
"",
"——【撒母耳记下 4】",
],
[
"1 And the word of the LORD came unto me, saying,",
"2 Son of man, set thy face toward the mountains of Israel, and prophesy against them,",
"3 And say, Ye mountains of Israel, hear the word of the Lord GOD; Thus saith the Lord GOD to the mountains, and to the hills, to the rivers, and to the valleys; Behold, I, even I, will bring a sword upon you, and I will destroy your high places.",
"4 And your altars shall be desolate, and your images shall be broken: and I will cast down your slain men before your idols.",
"",
"——【The Book of the Prophet Ezekiel 6】",
"",
"1 耶和华的话临到我说：",
"2 「人子啊，你要面向以色列的众山说预言，",
"3 说：以色列的众山哪，要听主耶和华的话。主耶和华对大山、小冈、水沟、山谷如此说：我必使刀剑临到你们，也必毁灭你们的邱坛。",
"4 你们的祭坛必然荒凉，你们的日像必被打碎。我要使你们被杀的人倒在你们的偶像面前；",
"",
"——【以西结书 6】",
],
[
"4 And he sacrificed and burnt incense in the high places, and on the hills, and under every green tree.",
"5 Then Rezin king of Syria and Pekah son of Remaliah king of Israel came up to Jerusalem to war: and they besieged Ahaz, but could not overcome him.",
"6 At that time Rezin king of Syria recovered Elath to Syria, and drave the Jews from Elath: and the Syrians came to Elath, and dwelt there unto this day.",
"",
"——【The Second Book of the Kings 16】",
"",
"4 并在邱坛上、山冈上、各青翠树下献祭烧香。",
"5 亚兰王利汛和以色列王利玛利的儿子比加上来攻打耶路撒冷，围困亚哈斯，却不能胜他。",
"6 当时亚兰王利汛收回以拉他归与亚兰，将犹大人从以拉他赶出去。亚兰人【有作以东人的】就来到以拉他，住在那里，直到今日。",
"",
"——【列王记下 16】",
],
[
"7 In the day of my trouble I will call upon thee: for thou wilt answer me.",
"8 Among the gods there is none like unto thee, O Lord; neither are there any works like unto thy works.",
"",
"——【The Book of Psalms 86】",
"",
"7 我在患难之日要求告你，因为你必应允我。",
"8 主啊，诸神之中没有可比你的；你的作为也无可比。",
"",
"——【诗篇 86】",
],
[
"1 I will extol thee, my God, O king; and I will bless thy name for ever and ever.",
"2 Every day will I bless thee; and I will praise thy name for ever and ever.",
"3 Great is the LORD, and greatly to be praised; and his greatness is unsearchable.",
"4 One generation shall praise thy works to another, and shall declare thy mighty acts.",
"5 I will speak of the glorious honour of thy majesty, and of thy wondrous works.",
"6 And men shall speak of the might of thy terrible acts: and I will declare thy greatness.",
"",
"——【The Book of Psalms 145】",
"",
"1 （大卫的赞美诗。）我的　神我的王啊，我要尊崇你！我要永永远远称颂你的名！",
"2 我要天天称颂你，也要永永远远赞美你的名！",
"3 耶和华本为大，该受大赞美；其大无法测度。",
"4 这代要对那代颂赞你的作为，也要传扬你的大能。",
"5 我要默念你威严的尊荣和你奇妙的作为。",
"6 人要传说你可畏之事的能力；我也要传扬你的大德。",
"",
"——【诗篇 145】",
],
[
"7 And of the angels he saith, Who maketh his angels spirits, and his ministers a flame of fire.",
"8 But unto the Son he saith, Thy throne, O God, is for ever and ever: a sceptre of righteousness is the sceptre of thy kingdom.",
"9 Thou hast loved righteousness, and hated iniquity; therefore God, even thy God, hath anointed thee with the oil of gladness above thy fellows.",
"10 And, Thou, Lord, in the beginning hast laid the foundation of the earth; and the heavens are the works of thine hands:",
"",
"——【The Epistle of Paul the Apostle to the Hebrews 1】",
"",
"7 论到使者，又说：　神以风为使者，以火焰为仆役；",
"8 论到子却说：　神啊，你的宝座是永永远远的；你的国权是正直的。",
"9 你喜爱公义，恨恶罪恶；所以　神，就是你的　神，用喜乐油膏你，胜过膏你的同伴；",
"10 又说：主啊，你起初立了地的根基；天也是你手所造的。",
"",
"——【希伯来书 1】",
],
[
"9 And the land of Egypt shall be desolate and waste; and they shall know that I am the LORD: because he hath said, The river is mine, and I have made it.",
"10 Behold, therefore I am against thee, and against thy rivers, and I will make the land of Egypt utterly waste and desolate, from the tower of Syene even unto the border of Ethiopia.",
"11 No foot of man shall pass through it, nor foot of beast shall pass through it, neither shall it be inhabited forty years.",
"12 And I will make the land of Egypt desolate in the midst of the countries that are desolate, and her cities among the cities that are laid waste shall be desolate forty years: and I will scatter the Egyptians among the nations, and will disperse them through the countries.",
"13 Yet thus saith the Lord GOD; At the end of forty years will I gather the Egyptians from the people whither they were scattered:",
"",
"——【The Book of the Prophet Ezekiel 29】",
"",
"9 埃及地必荒废凄凉，他们就知道我是耶和华。「因为法老说：『这河是我的，是我所造的』，",
"10 所以我必与你并你的江河为敌，使埃及地，从色弗尼塔直到古实境界，全然荒废凄凉。",
"11 人的脚、兽的蹄都不经过，四十年之久并无人居住。",
"12 我必使埃及地在荒凉的国中成为荒凉，使埃及城在荒废的城中变为荒废，共有四十年。我必将埃及人分散在列国，四散在列邦。」",
"13 主耶和华如此说：「满了四十年，我必招聚分散在各国民中的埃及人。",
"",
"——【以西结书 29】",
],
[
"1 Unto thee lift I up mine eyes, O thou that dwellest in the heavens.",
"2 Behold, as the eyes of servants look unto the hand of their masters, and as the eyes of a maiden unto the hand of her mistress; so our eyes wait upon the LORD our God, until that he have mercy upon us.",
"3 Have mercy upon us, O LORD, have mercy upon us: for we are exceedingly filled with contempt.",
"4 Our soul is exceedingly filled with the scorning of those that are at ease, and with the contempt of the proud.",
"",
"——【The Book of Psalms 123】",
"",
"1 （上行之诗。）坐在天上的主啊，我向你举目。",
"2 看哪，仆人的眼睛怎样望主人的手，使女的眼睛怎样望主母的手，我们的眼睛也照样望耶和华─我们的　神，直到他怜悯我们。",
"3 耶和华啊，求你怜悯我们，怜悯我们！因为我们被藐视，已到极处。",
"4 我们被那些安逸人的讥诮和骄傲人的藐视，已到极处。",
"",
"——【诗篇 123】",
],
[
"40 On these two commandments hang all the law and the prophets.",
"41 While the Pharisees were gathered together, Jesus asked them,",
"",
"——【The Gospel According to Saint Matthew 22】",
"",
"40 这两条诫命是律法和先知一切道理的总纲。",
"41 法利赛人聚集的时候，耶稣问他们说：",
"",
"——【马太福音 22】",
],
[
"14 Behold, the heaven and the heaven of heavens is the LORD'S thy God, the earth also, with all that therein is.",
"15 Only the LORD had a delight in thy fathers to love them, and he chose their seed after them, even you above all people, as it is this day.",
"16 Circumcise therefore the foreskin of your heart, and be no more stiffnecked.",
"17 For the LORD your God is God of gods, and Lord of lords, a great God, a mighty, and a terrible, which regardeth not persons, nor taketh reward:",
"18 He doth execute the judgment of the fatherless and widow, and loveth the stranger, in giving him food and raiment.",
"19 Love ye therefore the stranger: for ye were strangers in the land of Egypt.",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 10】",
"",
"14 看哪，天和天上的天，地和地上所有的，都属耶和华─你的　神。",
"15 耶和华但喜悦你的列祖，爱他们，从万民中拣选他们的后裔，就是你们，像今日一样。",
"16 所以你们要将心里的污秽除掉，不可再硬著颈项。",
"17 因为耶和华─你们的　神─他是万神之神，万主之主，至大的　神，大有能力，大而可畏，不以貌取人，也不受贿赂。",
"18 他为孤儿寡妇伸冤，又怜爱寄居的，赐给他衣食。",
"19 所以你们要怜爱寄居的，因为你们在埃及地也作过寄居的。",
"",
"——【申命记 10】",
],
[
"7 And I heard the man clothed in linen, which was upon the waters of the river, when he held up his right hand and his left hand unto heaven, and sware by him that liveth for ever that it shall be for a time, times, and an half; and when he shall have accomplished to scatter the power of the holy people, all these things shall be finished.",
"8 And I heard, but I understood not: then said I, O my Lord, what shall be the end of these things?",
"9 And he said, Go thy way, Daniel: for the words are closed up and sealed till the time of the end.",
"10 Many shall be purified, and made white, and tried; but the wicked shall do wickedly: and none of the wicked shall understand; but the wise shall understand.",
"",
"——【The Book of Daniel 12】",
"",
"7 我听见那站在河水以上、穿细麻衣的，向天举起左右手，指著活到永远的主起誓说：「要到一载、二载、半载，打破圣民权力的时候，这一切事就都应验了。」",
"8 我听见这话，却不明白，就说：「我主啊，这些事的结局是怎样呢？」",
"9 他说：「但以理啊，你只管去；因为这话已经隐藏封闭，直到末时。",
"10 必有许多人使自己清净洁白，且被熬炼；但恶人仍必行恶，一切恶人都不明白，惟独智慧人能明白。",
"",
"——【但以理书 12】",
],
[
"3 If the clouds be full of rain, they empty themselves upon the earth: and if the tree fall toward the south, or toward the north, in the place where the tree falleth, there it shall be.",
"4 He that observeth the wind shall not sow; and he that regardeth the clouds shall not reap.",
"5 As thou knowest not what is the way of the spirit, nor how the bones do grow in the womb of her that is with child: even so thou knowest not the works of God who maketh all.",
"6 In the morning sow thy seed, and in the evening withhold not thine hand: for thou knowest not whether shall prosper, either this or that, or whether they both shall be alike good.",
"7 Truly the light is sweet, and a pleasant thing it is for the eyes to behold the sun:",
"",
"——【Ecclesiastes 11】",
"",
"3 云若满了雨，就必倾倒在地上。树若向南倒，或向北倒，树倒在何处，就存在何处。",
"4 看风的，必不撒种；望云的，必不收割。",
"5 风从何道来，骨头在怀孕妇人的胎中如何长成，你尚且不得知道；这样，行万事之　神的作为，你更不得知道。",
"6 早晨要撒你的种，晚上也不要歇你的手，因为你不知道哪一样发旺；或是早撒的，或是晚撒的，或是两样都好。",
"7 光本是佳美的，眼见日光也是可悦的。",
"",
"——【传道书 11】",
],
[
"7 O GOD the Lord, the strength of my salvation, thou hast covered my head in the day of battle.",
"8 Grant not, O LORD, the desires of the wicked: further not his wicked device; lest they exalt themselves. Selah.",
"9 As for the head of those that compass me about, let the mischief of their own lips cover them.",
"",
"——【The Book of Psalms 140】",
"",
"7 主─耶和华、我救恩的力量啊，在争战的日子，你遮蔽了我的头。",
"8 耶和华啊，求你不要遂恶人的心愿；不要成就他们的计谋，恐怕他们自高。（细拉）",
"9 至于那些昂首围困我的人，愿他们嘴唇的奸恶陷害（原文是遮蔽）自己！",
"",
"——【诗篇 140】",
],
[
"3 When the wicked cometh, then cometh also contempt, and with ignominy reproach.",
"4 The words of a man's mouth are as deep waters, and the wellspring of wisdom as a flowing brook.",
"5 It is not good to accept the person of the wicked, to overthrow the righteous in judgment.",
"6 A fool's lips enter into contention, and his mouth calleth for strokes.",
"7 A fool's mouth is his destruction, and his lips are the snare of his soul.",
"",
"——【The Proverbs 18】",
"",
"3 恶人来，藐视随来；羞耻到，辱骂同到。",
"4 人口中的言语如同深水；智慧的泉源好像涌流的河水。",
"5 瞻徇恶人的情面，偏断义人的案件，都为不善。",
"6 愚昧人张嘴启争端，开口招鞭打。",
"7 愚昧人的口自取败坏；他的嘴是他生命的网罗。",
"",
"——【箴言 18】",
],
];
