var bible31_global=[
[
"7 Thou shalt not take the name of the LORD thy God in vain; for the LORD will not hold him guiltless that taketh his name in vain.",
"8 Remember the sabbath day, to keep it holy.",
"",
"——【The Second Book of Moses: Called Exodus 20】",
"",
"7 「不可妄称耶和华─你　神的名；因为妄称耶和华名的，耶和华必不以他为无罪。",
"8 「当记念安息日，守为圣日。",
"",
"——【出埃及记 20】",
],
[
"1 Truly God is good to Israel, even to such as are of a clean heart.",
"2 But as for me, my feet were almost gone; my steps had well nigh slipped.",
"3 For I was envious at the foolish, when I saw the prosperity of the wicked.",
"4 For there are no bands in their death: but their strength is firm.",
"5 They are not in trouble as other men; neither are they plagued like other men.",
"6 Therefore pride compasseth them about as a chain; violence covereth them as a garment.",
"",
"——【The Book of Psalms 73】",
"",
"1 （亚萨的诗。）　神实在恩待以色列那些清心的人！",
"2 至于我，我的脚几乎失闪；我的脚险些滑跌。",
"3 我见恶人和狂傲人享平安就心怀不平。",
"4 他们死的时候没有疼痛；他们的力气却也壮实。",
"5 他们不像别人受苦，也不像别人遭灾。",
"6 所以，骄傲如链子戴在他们的项上；强暴像衣裳遮住他们的身体。",
"",
"——【诗篇 73】",
],
[
"1 Unto thee will I cry, O LORD my rock; be not silent to me: lest, if thou be silent to me, I become like them that go down into the pit.",
"2 Hear the voice of my supplications, when I cry unto thee, when I lift up my hands toward thy holy oracle.",
"3 Draw me not away with the wicked, and with the workers of iniquity, which speak peace to their neighbours, but mischief is in their hearts.",
"",
"——【The Book of Psalms 28】",
"",
"1 （大卫的诗。）耶和华啊，我要求告你！我的磐石啊，不要向我缄默！倘若你向我闭口，我就如将死的人一样。",
"2 我呼求你，向你至圣所举手的时候，求你垂听我恳求的声音！",
"3 不要把我和恶人并作孽的一同除掉；他们与邻舍说和平话，心里却是奸恶。",
"",
"——【诗篇 28】",
],
[
"9 Great men are not always wise: neither do the aged understand judgment.",
"10 Therefore I said, Hearken to me; I also will shew mine opinion.",
"11 Behold, I waited for your words; I gave ear to your reasons, whilst ye searched out what to say.",
"12 Yea, I attended unto you, and, behold, there was none of you that convinced Job, or that answered his words:",
"13 Lest ye should say, We have found out wisdom: God thrusteth him down, not man.",
"",
"——【The Book of Job 32】",
"",
"9 尊贵的不都有智慧；寿高的不都能明白公平。",
"10 因此我说：你们要听我言；我也要陈说我的意见。",
"11 你们查究所要说的话；那时我等候你们的话，侧耳听你们的辩论，",
"12 留心听你们；谁知你们中间无一人折服约伯，驳倒他的话。",
"13 你们切不可说：我们寻得智慧；　神能胜他，人却不能。",
"",
"——【约伯记 32】",
],
[
"22 Ye shall not fear them: for the LORD your God he shall fight for you.",
"23 And I besought the LORD at that time, saying,",
"24 O Lord GOD, thou hast begun to shew thy servant thy greatness, and thy mighty hand: for what God is there in heaven or in earth, that can do according to thy works, and according to thy might?",
"25 I pray thee, let me go over, and see the good land that is beyond Jordan, that goodly mountain, and Lebanon.",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 3】",
"",
"22 你不要怕他们，因那为你争战的是耶和华─你的　神。』」",
"23 「那时，我恳求耶和华说：",
"24 『主耶和华啊，你已将你的大力大能显给仆人看。在天上，在地下，有什么　神能像你行事、像你有大能的作为呢？",
"25 求你容我过去，看约旦河那边的美地，就是那佳美的山地和黎巴嫩。』",
"",
"——【申命记 3】",
],
[
"6 And I will deliver thee and this city out of the hand of the king of Assyria: and I will defend this city.",
"7 And this shall be a sign unto thee from the LORD, that the LORD will do this thing that he hath spoken;",
"8 Behold, I will bring again the shadow of the degrees, which is gone down in the sun dial of Ahaz, ten degrees backward. So the sun returned ten degrees, by which degrees it was gone down.",
"9 The writing of Hezekiah king of Judah, when he had been sick, and was recovered of his sickness:",
"10 I said in the cutting off of my days, I shall go to the gates of the grave: I am deprived of the residue of my years.",
"",
"——【The Book of the Prophet Isaiah 38】",
"",
"6 并且我要救你和这城脱离亚述王的手，也要保护这城。",
"7 我─耶和华必成就我所说的。我先给你一个兆头，",
"8 就是叫亚哈斯的日晷，向前进的日影往后退十度。」于是，前进的日影果然在日晷上往后退了十度。",
"9 犹大王希西家患病已经痊癒，就作诗说：",
"10 我说：正在我中年（或译：晌午）之日必进入阴间的门；我余剩的年岁不得享受。",
"",
"——【以赛亚书 38】",
],
[
"3 All things were made by him; and without him was not any thing made that was made.",
"4 In him was life; and the life was the light of men.",
"5 And the light shineth in darkness; and the darkness comprehended it not.",
"6 There was a man sent from God, whose name was John.",
"",
"——【The Gospel According to Saint John 1】",
"",
"3 万物是藉着他造的；凡被造的，没有一样不是藉着他造的。",
"4 生命在他里头，这生命就是人的光。",
"5 光照在黑暗里，黑暗却不接受光。",
"6 有一个人，是从　神那里差来的，名叫约翰。",
"",
"——【约翰福音 1】",
],
[
"5 Thine head upon thee is like Carmel, and the hair of thine head like purple; the king is held in the galleries.",
"6 How fair and how pleasant art thou, O love, for delights!",
"7 This thy stature is like to a palm tree, and thy breasts to clusters of grapes.",
"8 I said, I will go up to the palm tree, I will take hold of the boughs thereof: now also thy breasts shall be as clusters of the vine, and the smell of thy nose like apples;",
"9 And the roof of thy mouth like the best wine for my beloved, that goeth down sweetly, causing the lips of those that are asleep to speak.",
"",
"——【The Song of Solomon 7】",
"",
"5 你的头在你身上好像迦密山；你头上的发是紫黑色；王的心因这下垂的发绺系住了。",
"6 我所爱的，你何其美好！何其可悦，使人欢畅喜乐！",
"7 你的身量好像棕树；你的两乳如同其上的果子，累累下垂。",
"8 我说：我要上这棕树，抓住枝子。愿你的两乳好像葡萄累累下垂，你鼻子的气味香如苹果；",
"9 你的口如上好的酒。女子说：为我的良人下咽舒畅，流入睡觉人的嘴中。",
"",
"——【雅歌 7】",
],
[
"1 And he shewed me Joshua the high priest standing before the angel of the LORD, and Satan standing at his right hand to resist him.",
"2 And the LORD said unto Satan, The LORD rebuke thee, O Satan; even the LORD that hath chosen Jerusalem rebuke thee: is not this a brand plucked out of the fire?",
"3 Now Joshua was clothed with filthy garments, and stood before the angel.",
"4 And he answered and spake unto those that stood before him, saying, Take away the filthy garments from him. And unto him he said, Behold, I have caused thine iniquity to pass from thee, and I will clothe thee with change of raiment.",
"",
"——【Zechariah 3】",
"",
"1 天使（原文是他）又指给我看：大祭司约书亚站在耶和华的使者面前；撒但也站在约书亚的右边，与他作对。",
"2 耶和华向撒但说：「撒但哪，耶和华责备你！就是拣选耶路撒冷的耶和华责备你！这不是从火中抽出来的一根柴吗？」",
"3 约书亚穿着污秽的衣服站在使者面前。",
"4 使者吩咐站在面前的说：「你们要脱去他污秽的衣服」；又对约书亚说：「我使你脱离罪孽，要给你穿上华美的衣服。」",
"",
"——【撒迦利亚书 3】",
],
[
"1 And in the second year of the reign of Nebuchadnezzar Nebuchadnezzar dreamed dreams, wherewith his spirit was troubled, and his sleep brake from him.",
"2 Then the king commanded to call the magicians, and the astrologers, and the sorcerers, and the Chaldeans, for to shew the king his dreams. So they came and stood before the king.",
"3 And the king said unto them, I have dreamed a dream, and my spirit was troubled to know the dream.",
"4 Then spake the Chaldeans to the king in Syriack, O king, live for ever: tell thy servants the dream, and we will shew the interpretation.",
"5 The king answered and said to the Chaldeans, The thing is gone from me: if ye will not make known unto me the dream, with the interpretation thereof, ye shall be cut in pieces, and your houses shall be made a dunghill.",
"",
"——【The Book of Daniel 2】",
"",
"1 尼布甲尼撒在位第二年，他做了梦，心里烦乱，不能睡觉。",
"2 王吩咐人将术士、用法术的、行邪术的，和迦勒底人召来，要他们将王的梦告诉王，他们就来站在王前。",
"3 王对他们说：「我做了一梦，心里烦乱，要知道这是什么梦。」",
"4 迦勒底人用亚兰的言语对王说：「愿王万岁！请将那梦告诉仆人，仆人就可以讲解。」",
"5 王回答迦勒底人说：「梦我已经忘了（或译：我已定命；八节同），你们若不将梦和梦的讲解告诉我，就必被凌迟，你们的房屋必成为粪堆；",
"",
"——【但以理书 2】",
],
[
"11 For sin, taking occasion by the commandment, deceived me, and by it slew me.",
"12 Wherefore the law is holy, and the commandment holy, and just, and good.",
"13 Was then that which is good made death unto me? God forbid. But sin, that it might appear sin, working death in me by that which is good; that sin by the commandment might become exceeding sinful.",
"14 For we know that the law is spiritual: but I am carnal, sold under sin.",
"15 For that which I do I allow not: for what I would, that do I not; but what I hate, that do I.",
"",
"——【The Epistle of Paul the Apostle to the Romans 7】",
"",
"11 因为罪趁着机会，就藉着诫命引诱我，并且杀了我。",
"12 这样看来，律法是圣洁的，诫命也是圣洁、公义、良善的。",
"13 既然如此，那良善的是叫我死吗？断乎不是！叫我死的乃是罪。但罪藉着那良善的叫我死，就显出真是罪，叫罪因着诫命更显出是恶极了。",
"14 我们原晓得律法是属乎灵的，但我是属乎肉体的，是已经卖给罪了。",
"15 因为我所做的，我自己不明白；我所愿意的，我并不做；我所恨恶的，我倒去做。",
"",
"——【罗马书 7】",
],
[
"14 Now it came to pass, after that Amaziah was come from the slaughter of the Edomites, that he brought the gods of the children of Seir, and set them up to be his gods, and bowed down himself before them, and burned incense unto them.",
"15 Wherefore the anger of the LORD was kindled against Amaziah, and he sent unto him a prophet, which said unto him, Why hast thou sought after the gods of the people, which could not deliver their own people out of thine hand?",
"16 And it came to pass, as he talked with him, that the king said unto him, Art thou made of the king's counsel? forbear; why shouldest thou be smitten? Then the prophet forbare, and said, I know that God hath determined to destroy thee, because thou hast done this, and hast not hearkened unto my counsel.",
"17 Then Amaziah king of Judah took advice, and sent to Joash, the son of Jehoahaz, the son of Jehu, king of Israel, saying, Come, let us see one another in the face.",
"18 And Joash king of Israel sent to Amaziah king of Judah, saying, The thistle that was in Lebanon sent to the cedar that was in Lebanon, saying, Give thy daughter to my son to wife: and there passed by a wild beast that was in Lebanon, and trode down the thistle.",
"",
"——【The Second Book of the Chronicles 25】",
"",
"14 亚玛谢杀了以东人回来，就把西珥的神像带回，立为自己的神，在它面前叩拜烧香。",
"15 因此，耶和华的怒气向亚玛谢发作，就差一个先知去见他，说：「这些神不能救他的民脱离你的手，你为何寻求他呢？」",
"16 先知与王说话的时候，王对他说：「谁立你作王的谋士呢？你住口吧！为何找打呢？」先知就止住了，又说：「你行这事，不听从我的劝戒，我知道　神定意要灭你。」",
"17 犹大王亚玛谢与群臣商议，就差遣使者去见耶户的孙子、约哈斯的儿子、以色列王约阿施，说：「你来，我们二人相见于战场。」",
"18 以色列王约阿施差遣使者去见犹大王亚玛谢，说：「黎巴嫩的蒺藜差遣使者去见黎巴嫩的香柏树，说：『将你的女儿给我儿子为妻。』后来黎巴嫩有一个野兽经过，把蒺藜践踏了。",
"",
"——【历代志下 25】",
],
[
"40 For I lift up my hand to heaven, and say, I live for ever.",
"41 If I whet my glittering sword, and mine hand take hold on judgment; I will render vengeance to mine enemies, and will reward them that hate me.",
"42 I will make mine arrows drunk with blood, and my sword shall devour flesh; and that with the blood of the slain and of the captives, from the beginning of revenges upon the enemy.",
"43 Rejoice, O ye nations, with his people: for he will avenge the blood of his servants, and will render vengeance to his adversaries, and will be merciful unto his land, and to his people.",
"44 And Moses came and spake all the words of this song in the ears of the people, he, and Hoshea the son of Nun.",
"45 And Moses made an end of speaking all these words to all Israel:",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 32】",
"",
"40 我向天举手说：我凭我的永生起誓：",
"41 我若磨我闪亮的刀，手掌审判之权，就必报复我的敌人，报应恨我的人。",
"42 我要使我的箭饮血饮醉，就是被杀被掳之人的血。我的刀要吃肉，乃是仇敌中首领之头的肉。",
"43 你们外邦人当与主的百姓一同欢呼；因他要伸他仆人流血的冤，报应他的敌人，洁净他的地，救赎他的百姓。",
"44 摩西和嫩的儿子约书亚去将这歌的一切话说给百姓听。",
"45 摩西向以色列众人说完了这一切的话，",
"",
"——【申命记 32】",
],
[
"1 The LORD is my shepherd; I shall not want.",
"2 He maketh me to lie down in green pastures: he leadeth me beside the still waters.",
"3 He restoreth my soul: he leadeth me in the paths of righteousness for his name's sake.",
"4 Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.",
"",
"——【The Book of Psalms 23】",
"",
"1 （大卫的诗。）耶和华是我的牧者，我必不致缺乏。",
"2 他使我躺卧在青草地上，领我在可安歇的水边。",
"3 他使我的灵魂苏醒，为自己的名引导我走义路。",
"4 我虽然行过死荫的幽谷，也不怕遭害，因为你与我同在；你的杖，你的竿，都安慰我。",
"",
"——【诗篇 23】",
],
[
"11 O ye Corinthians, our mouth is open unto you, our heart is enlarged.",
"12 Ye are not straitened in us, but ye are straitened in your own bowels.",
"13 Now for a recompence in the same, (I speak as unto my children,) be ye also enlarged.",
"14 Be ye not unequally yoked together with unbelievers: for what fellowship hath righteousness with unrighteousness? and what communion hath light with darkness?",
"",
"——【The Second Epistle of Paul the Apostle to the Corinthians 6】",
"",
"11 哥林多人哪，我们向你们，口是张开的，心是宽宏的。",
"12 你们狭窄，原不在乎我们，是在乎自己的心肠狭窄。",
"13 你们也要照样用宽宏的心报答我。我这话正像对自己的孩子说的。",
"14 你们和不信的原不相配，不要同负一轭。义和不义有什么相交呢？光明和黑暗有什么相通呢？",
"",
"——【哥林多后书 6】",
],
[
"1 Afterward he brought me to the gate, even the gate that looketh toward the east:",
"2 And, behold, the glory of the God of Israel came from the way of the east: and his voice was like a noise of many waters: and the earth shined with his glory.",
"",
"——【The Book of the Prophet Ezekiel 43】",
"",
"1 以后，他带我到一座门，就是朝东的门。",
"2 以色列　神的荣光从东而来。他的声音如同多水的声音；地就因他的荣耀发光。",
"",
"——【以西结书 43】",
],
[
"7 And they gave them drink in vessels of gold, (the vessels being diverse one from another,) and royal wine in abundance, according to the state of the king.",
"8 And the drinking was according to the law; none did compel: for so the king had appointed to all the officers of his house, that they should do according to every man's pleasure.",
"",
"——【The Book of Esther 1】",
"",
"7 用金器皿赐酒，器皿各有不同。御酒甚多，足显王的厚意。",
"8 喝酒有例，不准勉强人，因王吩咐宫里的一切臣宰，让人各随己意。",
"",
"——【以斯帖记 1】",
],
[
"1 Awake, awake; put on thy strength, O Zion; put on thy beautiful garments, O Jerusalem, the holy city: for henceforth there shall no more come into thee the uncircumcised and the unclean.",
"2 Shake thyself from the dust; arise, and sit down, O Jerusalem: loose thyself from the bands of thy neck, O captive daughter of Zion.",
"3 For thus saith the LORD, Ye have sold yourselves for nought; and ye shall be redeemed without money.",
"4 For thus saith the Lord GOD, My people went down aforetime into Egypt to sojourn there; and the Assyrian oppressed them without cause.",
"5 Now therefore, what have I here, saith the LORD, that my people is taken away for nought? they that rule over them make them to howl, saith the LORD; and my name continually every day is blasphemed.",
"",
"——【The Book of the Prophet Isaiah 52】",
"",
"1 锡安哪，兴起！兴起！披上你的能力！圣城耶路撒冷啊，穿上你华美的衣服！因为从今以后，未受割礼、不洁净的必不再进入你中间。",
"2 耶路撒冷啊，要抖下尘土！起来坐在位上！锡安被掳的居民（原文是女子）哪，要解开你颈项的锁链！",
"3 耶和华如此说：你们是无价被卖的，也必无银被赎。",
"4 主耶和华如此说：起先我的百姓下到埃及，在那里寄居，又有亚述人无故欺压他们。",
"5 耶和华说：我的百姓既是无价被掳去，如今我在这里做什么呢？耶和华说：辖制他们的人呼叫，我的名整天受亵渎。",
"",
"——【以赛亚书 52】",
],
[
"21 Wherefore of these men which have companied with us all the time that the Lord Jesus went in and out among us,",
"22 Beginning from the baptism of John, unto that same day that he was taken up from us, must one be ordained to be a witness with us of his resurrection.",
"23 And they appointed two, Joseph called Barsabas, who was surnamed Justus, and Matthias.",
"",
"——【The Acts of the Apostles 1】",
"",
"21 所以，主耶稣在我们中间始终出入的时候，",
"22 就是从约翰施洗起，直到主离开我们被接上升的日子为止，必须从那常与我们作伴的人中立一位与我们同作耶稣复活的见证。",
"23 于是选举两个人，就是那叫作巴撒巴，又称呼犹士都的约瑟，和马提亚。",
"",
"——【使徒行传 1】",
],
[
"15 Because they have done that which was evil in my sight, and have provoked me to anger, since the day their fathers came forth out of Egypt, even unto this day.",
"16 Moreover Manasseh shed innocent blood very much, till he had filled Jerusalem from one end to another; beside his sin wherewith he made Judah to sin, in doing that which was evil in the sight of the LORD.",
"17 Now the rest of the acts of Manasseh, and all that he did, and his sin that he sinned, are they not written in the book of the chronicles of the kings of Judah?",
"",
"——【The Second Book of the Kings 21】",
"",
"15 是因他们自从列祖出埃及直到如今，常行我眼中看为恶的事，惹动我的怒气。",
"16 玛拿西行耶和华眼中看为恶的事，使犹大人陷在罪里，又流许多无辜人的血，充满了耶路撒冷，从这边直到那边。",
"17 玛拿西其余的事，凡他所行的和他所犯的罪都写在犹大列王记上。",
"",
"——【列王记下 21】",
],
[
"17 (As it is written, I have made thee a father of many nations,) before him whom he believed, even God, who quickeneth the dead, and calleth those things which be not as though they were.",
"18 Who against hope believed in hope, that he might become the father of many nations; according to that which was spoken, So shall thy seed be.",
"19 And being not weak in faith, he considered not his own body now dead, when he was about an hundred years old, neither yet the deadness of Sara's womb:",
"20 He staggered not at the promise of God through unbelief; but was strong in faith, giving glory to God;",
"",
"——【The Epistle of Paul the Apostle to the Romans 4】",
"",
"17 亚伯拉罕所信的，是那叫死人复活、使无变为有的　神，他在主面前作我们世人的父。如经上所记：我已经立你作多国的父。",
"18 他在无可指望的时候，因信仍有指望，就得以作多国的父，正如先前所说，你的后裔将要如此。",
"19 他将近百岁的时候，虽然想到自己的身体如同已死，撒拉的生育已经断绝，他的信心还是不软弱；",
"20 并且仰望　神的应许，总没有因不信心里起疑惑，反倒因信心里得坚固，将荣耀归给　神，",
"",
"——【罗马书 4】",
],
[
"17 Even the Spirit of truth; whom the world cannot receive, because it seeth him not, neither knoweth him: but ye know him; for he dwelleth with you, and shall be in you.",
"18 I will not leave you comfortless: I will come to you.",
"19 Yet a little while, and the world seeth me no more; but ye see me: because I live, ye shall live also.",
"20 At that day ye shall know that I am in my Father, and ye in me, and I in you.",
"",
"——【The Gospel According to Saint John 14】",
"",
"17 就是真理的圣灵，乃世人不能接受的；因为不见他，也不认识他。你们却认识他，因他常与你们同在，也要在你们里面。",
"18 我不撇下你们为孤儿，我必到你们这里来。",
"19 还有不多的时候，世人不再看见我，你们却看见我；因为我活着，你们也要活着。",
"20 到那日，你们就知道我在父里面，你们在我里面，我也在你们里面。",
"",
"——【约翰福音 14】",
],
[
"22 And Ephraim their father mourned many days, and his brethren came to comfort him.",
"23 And when he went in to his wife, she conceived, and bare a son, and he called his name Beriah, because it went evil with his house.",
"",
"——【The First Book of the Chronicles 7】",
"",
"22 他们的父亲以法莲为他们悲哀了多日，他的弟兄都来安慰他。",
"23 以法莲与妻同房，他妻就怀孕生了一子，以法莲因为家里遭祸，就给这儿子起名叫比利亚。",
"",
"——【历代志上 7】",
],
[
"14 And there was given him dominion, and glory, and a kingdom, that all people, nations, and languages, should serve him: his dominion is an everlasting dominion, which shall not pass away, and his kingdom that which shall not be destroyed.",
"15 I Daniel was grieved in my spirit in the midst of my body, and the visions of my head troubled me.",
"16 I came near unto one of them that stood by, and asked him the truth of all this. So he told me, and made me know the interpretation of the things.",
"17 These great beasts, which are four, are four kings, which shall arise out of the earth.",
"18 But the saints of the most High shall take the kingdom, and possess the kingdom for ever, even for ever and ever.",
"19 Then I would know the truth of the fourth beast, which was diverse from all the others, exceeding dreadful, whose teeth were of iron, and his nails of brass; which devoured, brake in pieces, and stamped the residue with his feet;",
"",
"——【The Book of Daniel 7】",
"",
"14 得了权柄、荣耀、国度，使各方、各国、各族的人都事奉他。他的权柄是永远的，不能废去；他的国必不败坏。",
"15 至于我─但以理，我的灵在我里面愁烦，我脑中的异象使我惊惶。",
"16 我就近一位侍立者，问他这一切的真情。他就告诉我，将那事的讲解给我说明。",
"17 这四个大兽就是四王将要在世上兴起。",
"18 然而，至高者的圣民，必要得国享受，直到永永远远。",
"19 那时我愿知道第四兽的真情，牠为何与那三兽的真情大不相同，甚是可怕，有铁牙铜爪，吞吃嚼碎，所剩下的用脚践踏；",
"",
"——【但以理书 7】",
],
[
"9 Also I said, It is not good that ye do: ought ye not to walk in the fear of our God because of the reproach of the heathen our enemies?",
"10 I likewise, and my brethren, and my servants, might exact of them money and corn: I pray you, let us leave off this usury.",
"11 Restore, I pray you, to them, even this day, their lands, their vineyards, their oliveyards, and their houses, also the hundredth part of the money, and of the corn, the wine, and the oil, that ye exact of them.",
"12 Then said they, We will restore them, and will require nothing of them; so will we do as thou sayest. Then I called the priests, and took an oath of them, that they should do according to this promise.",
"",
"——【The Book of Nehemiah 5】",
"",
"9 我又说：「你们所行的不善！你们行事不当敬畏我们的　神吗？不然，难免我们的仇敌外邦人毁谤我们。",
"10 我和我的弟兄与仆人也将银钱粮食借给百姓；我们大家都当免去利息。",
"11 如今我劝你们将他们的田地、葡萄园、橄榄园、房屋，并向他们所取的银钱、粮食、新酒，和油，百分之一的利息都归还他们。」",
"12 众人说：「我们必归还，不再向他们索要，必照你的话行。」我就召了祭司来，叫众人起誓，必照着所应许的而行。",
"",
"——【尼希米记 5】",
],
[
"17 By faith Abraham, when he was tried, offered up Isaac: and he that had received the promises offered up his only begotten son,",
"18 Of whom it was said, That in Isaac shall thy seed be called:",
"19 Accounting that God was able to raise him up, even from the dead; from whence also he received him in a figure.",
"20 By faith Isaac blessed Jacob and Esau concerning things to come.",
"",
"——【The Epistle of Paul the Apostle to the Hebrews 11】",
"",
"17 亚伯拉罕因着信，被试验的时候，就把以撒献上；这便是那欢喜领受应许的，将自己独生的儿子献上。",
"18 论到这儿子，曾有话说：从以撒生的才要称为你的后裔。",
"19 他以为　神还能叫人从死里复活；他也彷彿从死中得回他的儿子来。",
"20 以撒因着信，就指着将来的事给雅各、以扫祝福。",
"",
"——【希伯来书 11】",
],
[
"10 Which thing I also did in Jerusalem: and many of the saints did I shut up in prison, having received authority from the chief priests; and when they were put to death, I gave my voice against them.",
"11 And I punished them oft in every synagogue, and compelled them to blaspheme; and being exceedingly mad against them, I persecuted them even unto strange cities.",
"12 Whereupon as I went to Damascus with authority and commission from the chief priests,",
"13 At midday, O king, I saw in the way a light from heaven, above the brightness of the sun, shining round about me and them which journeyed with me.",
"14 And when we were all fallen to the earth, I heard a voice speaking unto me, and saying in the Hebrew tongue, Saul, Saul, why persecutest thou me? it is hard for thee to kick against the pricks.",
"15 And I said, Who art thou, Lord? And he said, I am Jesus whom thou persecutest.",
"",
"——【The Acts of the Apostles 26】",
"",
"10 我在耶路撒冷也曾这样行了。既从祭司长得了权柄，我就把许多圣徒囚在监里。他们被杀，我也出名定案。",
"11 在各会堂，我屡次用刑强逼他们说亵渎的话，又分外恼恨他们，甚至追逼他们，直到外邦的城邑。",
"12 那时，我领了祭司长的权柄和命令，往大马士革去。",
"13 王啊，我在路上，晌午的时候，看见从天发光，比日头还亮，四面照着我并与我同行的人。",
"14 我们都仆倒在地，我就听见有声音用希伯来话向我说：扫罗！扫罗！为什么逼迫我？你用脚踢刺是难的！",
"15 我说：主啊，你是谁？主说：我就是你所逼迫的耶稣。",
"",
"——【使徒行传 26】",
],
[
"1 LORD, remember David, and all his afflictions:",
"2 How he sware unto the LORD, and vowed unto the mighty God of Jacob;",
"3 Surely I will not come into the tabernacle of my house, nor go up into my bed;",
"4 I will not give sleep to mine eyes, or slumber to mine eyelids,",
"5 Until I find out a place for the LORD, an habitation for the mighty God of Jacob.",
"",
"——【The Book of Psalms 132】",
"",
"1 （上行之诗。）耶和华啊，求你记念大卫所受的一切苦难！",
"2 他怎样向耶和华起誓，向雅各的大能者许愿，",
"3 说：我必不进我的帐幕，也不上我的床榻；",
"4 我不容我的眼睛睡觉，也不容我的眼目打盹；",
"5 直等我为耶和华寻得所在，为雅各的大能者寻得居所。",
"",
"——【诗篇 132】",
],
[
"9 And it shall be to me a name of joy, a praise and an honour before all the nations of the earth, which shall hear all the good that I do unto them: and they shall fear and tremble for all the goodness and for all the prosperity that I procure unto it.",
"10 Thus saith the LORD; Again there shall be heard in this place, which ye say shall be desolate without man and without beast, even in the cities of Judah, and in the streets of Jerusalem, that are desolate, without man, and without inhabitant, and without beast,",
"11 The voice of joy, and the voice of gladness, the voice of the bridegroom, and the voice of the bride, the voice of them that shall say, Praise the LORD of hosts: for the LORD is good; for his mercy endureth for ever: and of them that shall bring the sacrifice of praise into the house of the LORD. For I will cause to return the captivity of the land, as at the first, saith the LORD.",
"12 Thus saith the LORD of hosts; Again in this place, which is desolate without man and without beast, and in all the cities thereof, shall be an habitation of shepherds causing their flocks to lie down.",
"13 In the cities of the mountains, in the cities of the vale, and in the cities of the south, and in the land of Benjamin, and in the places about Jerusalem, and in the cities of Judah, shall the flocks pass again under the hands of him that telleth them, saith the LORD.",
"",
"——【The Book of the Prophet Jeremiah 33】",
"",
"9 这城要在地上万国人面前使我得颂赞，得荣耀，名为可喜可乐之城。万国人因听见我向这城所赐的福乐、所施的恩惠平安，就惧怕战兢。",
"10 耶和华如此说：「你们论这地方，说是荒废无人民无牲畜之地，但在这荒凉无人民无牲畜的犹大城邑和耶路撒冷的街上，",
"11 必再听见有欢喜和快乐的声音、新郎和新妇的声音，并听见有人说：要称谢万军之耶和华，因耶和华本为善；他的慈爱永远长存！又有奉感谢祭到耶和华殿中之人的声音；因为我必使这地被掳的人归回，和起初一样。这是耶和华说的。」",
"12 万军之耶和华如此说：「在这荒废无人民无牲畜之地，并其中所有的城邑，必再有牧人的住处；他们要使羊群躺卧在那里。",
"13 在山地的城邑、高原的城邑、南地的城邑、便雅悯地、耶路撒冷四围的各处，和犹大的城邑必再有羊群从数点的人手下经过。这是耶和华说的。」",
"",
"——【耶利米书 33】",
],
[
"1 When a man hath taken a wife, and married her, and it come to pass that she find no favour in his eyes, because he hath found some uncleanness in her: then let him write her a bill of divorcement, and give it in her hand, and send her out of his house.",
"2 And when she is departed out of his house, she may go and be another man's wife.",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 24】",
"",
"1 「人若娶妻以后，见她有什么不合理的事，不喜悦她，就可以写休书交在她手中，打发她离开夫家。",
"2 妇人离开夫家以后，可以去嫁别人。",
"",
"——【申命记 24】",
],
[
"11 And if they be ashamed of all that they have done, shew them the form of the house, and the fashion thereof, and the goings out thereof, and the comings in thereof, and all the forms thereof, and all the ordinances thereof, and all the forms thereof, and all the laws thereof: and write it in their sight, that they may keep the whole form thereof, and all the ordinances thereof, and do them.",
"12 This is the law of the house; Upon the top of the mountain the whole limit thereof round about shall be most holy. Behold, this is the law of the house.",
"",
"——【The Book of the Prophet Ezekiel 43】",
"",
"11 他们若因自己所行的一切事惭愧，你就将殿的规模、样式、出入之处，和一切形状、典章、礼仪、法则指示他们，在他们眼前写上，使他们遵照殿的一切规模典章去做。",
"12 殿的法则乃是如此：殿在山顶上，四围的全界要称为至圣。这就是殿的法则。」",
"",
"——【以西结书 43】",
],
];
