var bible31_global=[
[
"8 And he arose early in the morning on the fifth day to depart: and the damsel's father said, Comfort thine heart, I pray thee. And they tarried until afternoon, and they did eat both of them.",
"9 And when the man rose up to depart, he, and his concubine, and his servant, his father in law, the damsel's father, said unto him, Behold, now the day draweth toward evening, I pray you tarry all night: behold, the day groweth to an end, lodge here, that thine heart may be merry; and to morrow get you early on your way, that thou mayest go home.",
"10 But the man would not tarry that night, but he rose up and departed, and came over against Jebus, which is Jerusalem; and there were with him two asses saddled, his concubine also was with him.",
"11 And when they were by Jebus, the day was far spent; and the servant said unto his master, Come, I pray thee, and let us turn in into this city of the Jebusites, and lodge in it.",
"12 And his master said unto him, We will not turn aside hither into the city of a stranger, that is not of the children of Israel; we will pass over to Gibeah.",
"",
"——【The Book of Judges 19】",
"",
"8 到第五天，他清早起来要走，女子的父亲说：「请你吃点饭，加添心力，等到日头偏西再走。」于是二人一同吃饭。",
"9 那人同他的妾和仆人起来要走，他岳父，就是女子的父亲，对他说：「看哪，日头偏西了，请你再住一夜；天快晚了，可以在这里住宿，畅快你的心。明天早早起行回家去。」",
"10 那人不愿再住一夜，就备上那两匹驴，带著妾起身走了，来到耶布斯的对面（耶布斯就是耶路撒冷。）",
"11 临近耶布斯的时候，日头快要落了，仆人对主人说：「我们不如进这耶布斯人的城里住宿。」",
"12 主人回答说：「我们不可进不是以色列人住的外邦城，不如过到基比亚去」；",
"",
"——【士师记 19】",
],
[
"5 And he gave him none inheritance in it, no, not so much as to set his foot on: yet he promised that he would give it to him for a possession, and to his seed after him, when as yet he had no child.",
"6 And God spake on this wise, That his seed should sojourn in a strange land; and that they should bring them into bondage, and entreat them evil four hundred years.",
"7 And the nation to whom they shall be in bondage will I judge, said God: and after that shall they come forth, and serve me in this place.",
"8 And he gave him the covenant of circumcision: and so Abraham begat Isaac, and circumcised him the eighth day; and Isaac begat Jacob; and Jacob begat the twelve patriarchs.",
"9 And the patriarchs, moved with envy, sold Joseph into Egypt: but God was with him,",
"",
"——【The Acts of the Apostles 7】",
"",
"5 在这地方，　神并没有给他产业，连立足之地也没有给他；但应许要将这地赐给他和他的后裔为业；那时他还没有儿子。",
"6 　神说：他的后裔必寄居外邦，那里的人要叫他们作奴仆，苦待他们四百年。",
"7 　神又说：使他们作奴仆的那国，我要惩罚。以后他们要出来，在这地方事奉我。",
"8 　神又赐他割礼的约。于是亚伯拉罕生了以撒，第八日给他行了割礼。以撒生雅各，雅各生十二位先祖。",
"9 先祖嫉妒约瑟，把他卖到埃及去；　神却与他同在，",
"",
"——【使徒行传 7】",
],
[
"9 And Saul said, Bring hither a burnt offering to me, and peace offerings. And he offered the burnt offering.",
"10 And it came to pass, that as soon as he had made an end of offering the burnt offering, behold, Samuel came; and Saul went out to meet him, that he might salute him.",
"11 And Samuel said, What hast thou done? And Saul said, Because I saw that the people were scattered from me, and that thou camest not within the days appointed, and that the Philistines gathered themselves together at Michmash;",
"12 Therefore said I, The Philistines will come down now upon me to Gilgal, and I have not made supplication unto the LORD: I forced myself therefore, and offered a burnt offering.",
"",
"——【The First Book of Samuel 13】",
"",
"9 扫罗说：「把燔祭和平安祭带到我这里来。」扫罗就献上燔祭。",
"10 刚献完燔祭，撒母耳就到了。扫罗出去迎接他，要问他好。",
"11 撒母耳说：「你做的是什么事呢？」扫罗说：「因为我见百姓离开我散去，你也不照所定的日期来到，而且非利士人聚集在密抹。",
"12 所以我心里说：恐怕我没有祷告耶和华。非利士人下到吉甲攻击我，我就勉强献上燔祭。」",
"",
"——【撒母耳记上 13】",
],
[
"10 For in that he died, he died unto sin once: but in that he liveth, he liveth unto God.",
"11 Likewise reckon ye also yourselves to be dead indeed unto sin, but alive unto God through Jesus Christ our Lord.",
"12 Let not sin therefore reign in your mortal body, that ye should obey it in the lusts thereof.",
"13 Neither yield ye your members as instruments of unrighteousness unto sin: but yield yourselves unto God, as those that are alive from the dead, and your members as instruments of righteousness unto God.",
"",
"——【The Epistle of Paul the Apostle to the Romans 6】",
"",
"10 他死是向罪死了，只有一次；他活是向　神活著。",
"11 这样，你们向罪也当看自己是死的；向　神在基督耶稣里，却当看自己是活的。",
"12 所以，不要容罪在你们必死的身上作王，使你们顺从身子的私欲。",
"13 也不要将你们的肢体献给罪作不义的器具；倒要像从死里复活的人，将自己献给　神，并将肢体作义的器具献给　神。",
"",
"——【罗马书 6】",
],
[
"21 Moreover thou shalt provide out of all the people able men, such as fear God, men of truth, hating covetousness; and place such over them, to be rulers of thousands, and rulers of hundreds, rulers of fifties, and rulers of tens:",
"22 And let them judge the people at all seasons: and it shall be, that every great matter they shall bring unto thee, but every small matter they shall judge: so shall it be easier for thyself, and they shall bear the burden with thee.",
"23 If thou shalt do this thing, and God command thee so, then thou shalt be able to endure, and all this people shall also go to their place in peace.",
"24 So Moses hearkened to the voice of his father in law, and did all that he had said.",
"25 And Moses chose able men out of all Israel, and made them heads over the people, rulers of thousands, rulers of hundreds, rulers of fifties, and rulers of tens.",
"",
"——【The Second Book of Moses: Called Exodus 18】",
"",
"21 并要从百姓中拣选有才能的人，就是敬畏　神、诚实无妄、恨不义之财的人，派他们作千夫长、百夫长、五十夫长、十夫长，管理百姓，",
"22 叫他们随时审判百姓，大事都要呈到你这里，小事他们自己可以审判。这样，你就轻省些，他们也可以同当此任。",
"23 你若这样行，　神也这样吩咐你，你就能受得住，这百姓也都平平安安归回他们的住处。」",
"24 于是，摩西听从他岳父的话，按著他所说的去行。",
"25 摩西从以色列人中拣选了有才能的人，立他们为百姓的首领，作千夫长、百夫长、五十夫长、十夫长。",
"",
"——【出埃及记 18】",
],
[
"1 Make a joyful noise unto the LORD, all ye lands.",
"2 Serve the LORD with gladness: come before his presence with singing.",
"3 Know ye that the LORD he is God: it is he that hath made us, and not we ourselves; we are his people, and the sheep of his pasture.",
"",
"——【The Book of Psalms 100】",
"",
"1 （称谢诗。）普天下当向耶和华欢呼！",
"2 你们当乐意事奉耶和华，当来向他歌唱！",
"3 你们当晓得耶和华是　神！我们是他造的，也是属他的；我们是他的民，也是他草场的羊。",
"",
"——【诗篇 100】",
],
[
"16 And were carried over into Sychem, and laid in the sepulchre that Abraham bought for a sum of money of the sons of Emmor the father of Sychem.",
"17 But when the time of the promise drew nigh, which God had sworn to Abraham, the people grew and multiplied in Egypt,",
"18 Till another king arose, which knew not Joseph.",
"",
"——【The Acts of the Apostles 7】",
"",
"16 又被带到示剑，葬于亚伯拉罕在示剑用银子从哈抹子孙买来的坟墓里。",
"17 及至　神应许亚伯拉罕的日期将到，以色列民在埃及兴盛众多，",
"18 直到有不晓得约瑟的新王兴起。",
"",
"——【使徒行传 7】",
],
[
"7 And I saw him come close unto the ram, and he was moved with choler against him, and smote the ram, and brake his two horns: and there was no power in the ram to stand before him, but he cast him down to the ground, and stamped upon him: and there was none that could deliver the ram out of his hand.",
"8 Therefore the he goat waxed very great: and when he was strong, the great horn was broken; and for it came up four notable ones toward the four winds of heaven.",
"9 And out of one of them came forth a little horn, which waxed exceeding great, toward the south, and toward the east, and toward the pleasant land.",
"10 And it waxed great, even to the host of heaven; and it cast down some of the host and of the stars to the ground, and stamped upon them.",
"",
"——【The Book of Daniel 8】",
"",
"7 我见公山羊就近公绵羊，向牠发烈怒，牴触牠，折断牠的两角。绵羊在牠面前站立不住；牠将绵羊触倒在地，用脚践踏，没有能救绵羊脱离牠手的。",
"8 这山羊极其自高自大，正强盛的时候，那大角折断了，又在角根上向天的四方（原文是风）长出四个非常的角来。",
"9 四角之中有一角长出一个小角，向南、向东、向荣美之地，渐渐成为强大。",
"10 牠渐渐强大，高及天象，将些天象和星宿抛落在地，用脚践踏。",
"",
"——【但以理书 8】",
],
[
"9 And when James, Cephas, and John, who seemed to be pillars, perceived the grace that was given unto me, they gave to me and Barnabas the right hands of fellowship; that we should go unto the heathen, and they unto the circumcision.",
"10 Only they would that we should remember the poor; the same which I also was forward to do.",
"11 But when Peter was come to Antioch, I withstood him to the face, because he was to be blamed.",
"12 For before that certain came from James, he did eat with the Gentiles: but when they were come, he withdrew and separated himself, fearing them which were of the circumcision.",
"13 And the other Jews dissembled likewise with him; insomuch that Barnabas also was carried away with their dissimulation.",
"",
"——【The Epistle of Paul the Apostle to the Galatians 2】",
"",
"9 又知道所赐给我的恩典，那称为教会柱石的雅各、矶法、约翰，就向我和巴拿巴用右手行相交之礼，叫我们往外邦人那里去，他们往受割礼的人那里去。",
"10 只是愿意我们记念穷人；这也是我本来热心去行的。",
"11 后来，矶法到了安提阿；因他有可责之处，我就当面抵挡他。",
"12 从雅各那里来的人未到以先，他和外邦人一同吃饭，及至他们来到，他因怕奉割礼的人，就退去与外邦人隔开了。",
"13 其余的犹太人也都随著他装假，甚至连巴拿巴也随伙装假。",
"",
"——【加拉太书 2】",
],
[
"8 I will therefore that men pray every where, lifting up holy hands, without wrath and doubting.",
"9 In like manner also, that women adorn themselves in modest apparel, with shamefacedness and sobriety; not with broided hair, or gold, or pearls, or costly array;",
"10 But (which becometh women professing godliness) with good works.",
"",
"——【The First Epistle of Paul the Apostle to Timothy 2】",
"",
"8 我愿男人无忿怒，无争论（或作：疑惑），举起圣洁的手，随处祷告。",
"9 又愿女人廉耻、自守，以正派衣裳为妆饰，不以编发、黄金、珍珠，和贵价的衣裳为妆饰；",
"10 只要有善行，这才与自称是敬　神的女人相宜。",
"",
"——【提摩太前书 2】",
],
[
"11 And when they were by Jebus, the day was far spent; and the servant said unto his master, Come, I pray thee, and let us turn in into this city of the Jebusites, and lodge in it.",
"12 And his master said unto him, We will not turn aside hither into the city of a stranger, that is not of the children of Israel; we will pass over to Gibeah.",
"13 And he said unto his servant, Come, and let us draw near to one of these places to lodge all night, in Gibeah, or in Ramah.",
"14 And they passed on and went their way; and the sun went down upon them when they were by Gibeah, which belongeth to Benjamin.",
"15 And they turned aside thither, to go in and to lodge in Gibeah: and when he went in, he sat him down in a street of the city: for there was no man that took them into his house to lodging.",
"16 And, behold, there came an old man from his work out of the field at even, which was also of mount Ephraim; and he sojourned in Gibeah: but the men of the place were Benjamites.",
"",
"——【The Book of Judges 19】",
"",
"11 临近耶布斯的时候，日头快要落了，仆人对主人说：「我们不如进这耶布斯人的城里住宿。」",
"12 主人回答说：「我们不可进不是以色列人住的外邦城，不如过到基比亚去」；",
"13 又对仆人说：「我们可以到一个地方，或住在基比亚，或住在拉玛。」",
"14 他们就往前走。将到便雅悯的基比亚，日头已经落了；",
"15 他们进入基比亚要在那里住宿，就坐在城里的街上，因为无人接他们进家住宿。",
"16 晚上，有一个老年人从田间做工回来。他原是以法莲山地的人，住在基比亚；那地方的人却是便雅悯人。",
"",
"——【士师记 19】",
],
[
"43 But know this, that if the goodman of the house had known in what watch the thief would come, he would have watched, and would not have suffered his house to be broken up.",
"44 Therefore be ye also ready: for in such an hour as ye think not the Son of man cometh.",
"45 Who then is a faithful and wise servant, whom his lord hath made ruler over his household, to give them meat in due season?",
"46 Blessed is that servant, whom his lord when he cometh shall find so doing.",
"",
"——【The Gospel According to Saint Matthew 24】",
"",
"43 家主若知道几更天有贼来，就必儆醒，不容人挖透房屋；这是你们所知道的。",
"44 所以，你们也要预备，因为你们想不到的时候，人子就来了。",
"45 谁是忠心有见识的仆人，为主人所派，管理家里的人，按时分粮给他们呢？",
"46 主人来到，看见他这样行，那仆人就有福了。",
"",
"——【马太福音 24】",
],
[
"4 Let them be confounded and put to shame that seek after my soul: let them be turned back and brought to confusion that devise my hurt.",
"5 Let them be as chaff before the wind: and let the angel of the LORD chase them.",
"6 Let their way be dark and slippery: and let the angel of the LORD persecute them.",
"",
"——【The Book of Psalms 35】",
"",
"4 愿那寻索我命的，蒙羞受辱！愿那谋害我的，退后羞愧！",
"5 愿他们像风前的糠，有耶和华的使者赶逐他们。",
"6 愿他们的道路又暗又滑，有耶和华的使者追赶他们。",
"",
"——【诗篇 35】",
],
[
"27 And Joab said, As God liveth, unless thou hadst spoken, surely then in the morning the people had gone up every one from following his brother.",
"28 So Joab blew a trumpet, and all the people stood still, and pursued after Israel no more, neither fought they any more.",
"29 And Abner and his men walked all that night through the plain, and passed over Jordan, and went through all Bithron, and they came to Mahanaim.",
"30 And Joab returned from following Abner: and when he had gathered all the people together, there lacked of David's servants nineteen men and Asahel.",
"31 But the servants of David had smitten of Benjamin, and of Abner's men, so that three hundred and threescore men died.",
"32 And they took up Asahel, and buried him in the sepulchre of his father, which was in Beth–lehem. And Joab and his men went all night, and they came to Hebron at break of day.",
"",
"——【The Second Book of Samuel 2】",
"",
"27 约押说：「我指着永生的　神起誓：你若不说戏耍的那句话，今日早晨百姓就回去，不追赶弟兄了。」",
"28 于是约押吹角，众民就站住，不再追赶以色列人，也不再打仗了。",
"29 押尼珥和跟随他的人整夜经过亚拉巴，过约旦河，走过毕伦，到了玛哈念。",
"30 约押追赶押尼珥回来，聚集众民，见大卫的仆人中缺少了十九个人和亚撒黑。",
"31 但大卫的仆人杀了便雅悯人和跟随押尼珥的人，共三百六十名。",
"32 众人将亚撒黑送到伯利恒，葬在他父亲的坟墓里。约押和跟随他的人走了一夜，天亮的时候到了希伯仑。",
"",
"——【撒母耳记下 2】",
],
[
"5 And when Jesus was entered into Capernaum, there came unto him a centurion, beseeching him,",
"6 And saying, Lord, my servant lieth at home sick of the palsy, grievously tormented.",
"7 And Jesus saith unto him, I will come and heal him.",
"8 The centurion answered and said, Lord, I am not worthy that thou shouldest come under my roof: but speak the word only, and my servant shall be healed.",
"9 For I am a man under authority, having soldiers under me: and I say to this man, Go, and he goeth; and to another, Come, and he cometh; and to my servant, Do this, and he doeth it.",
"",
"——【The Gospel According to Saint Matthew 8】",
"",
"5 耶稣进了迦百农，有一个百夫长进前来，求他说：",
"6 「主啊，我的仆人害瘫痪病，躺在家里，甚是疼苦。」",
"7 耶稣说：「我去医治他。」",
"8 百夫长回答说：「主啊，你到我舍下，我不敢当；只要你说一句话，我的仆人就必好了。",
"9 因为我在人的权下，也有兵在我以下；对这个说：『去！』他就去；对那个说：『来！』他就来；对我的仆人说：『你做这事！』他就去做。」",
"",
"——【马太福音 8】",
],
[
"5 Thine head upon thee is like Carmel, and the hair of thine head like purple; the king is held in the galleries.",
"6 How fair and how pleasant art thou, O love, for delights!",
"7 This thy stature is like to a palm tree, and thy breasts to clusters of grapes.",
"8 I said, I will go up to the palm tree, I will take hold of the boughs thereof: now also thy breasts shall be as clusters of the vine, and the smell of thy nose like apples;",
"9 And the roof of thy mouth like the best wine for my beloved, that goeth down sweetly, causing the lips of those that are asleep to speak.",
"10 I am my beloved's, and his desire is toward me.",
"",
"——【The Song of Solomon 7】",
"",
"5 你的头在你身上好像迦密山；你头上的发是紫黑色；王的心因这下垂的发绺系住了。",
"6 我所爱的，你何其美好！何其可悦，使人欢畅喜乐！",
"7 你的身量好像棕树；你的两乳如同其上的果子，累累下垂。",
"8 我说：我要上这棕树，抓住枝子。愿你的两乳好像葡萄累累下垂，你鼻子的气味香如苹果；",
"9 你的口如上好的酒。女子说：为我的良人下咽舒畅，流入睡觉人的嘴中。",
"10 我属我的良人，他也恋慕我。",
"",
"——【雅歌 7】",
],
[
"14 Feed thy people with thy rod, the flock of thine heritage, which dwell solitarily in the wood, in the midst of Carmel: let them feed in Bashan and Gilead, as in the days of old.",
"15 According to the days of thy coming out of the land of Egypt will I shew unto him marvellous things.",
"16 The nations shall see and be confounded at all their might: they shall lay their hand upon their mouth, their ears shall be deaf.",
"17 They shall lick the dust like a serpent, they shall move out of their holes like worms of the earth: they shall be afraid of the LORD our God, and shall fear because of thee.",
"18 Who is a God like unto thee, that pardoneth iniquity, and passeth by the transgression of the remnant of his heritage? he retaineth not his anger for ever, because he delighteth in mercy.",
"19 He will turn again, he will have compassion upon us; he will subdue our iniquities; and thou wilt cast all their sins into the depths of the sea.",
"",
"——【Micah 7】",
"",
"14 求耶和华在迦密山的树林中，用你的杖牧放你独居的民，就是你产业的羊群。求你容他们在巴珊和基列得食物，像古时一样。",
"15 耶和华说：我要把奇事显给他们看，好像出埃及地的时候一样。",
"16 列国看见这事，就必为自己的势力惭愧；他们必用手摀口，掩耳不听。",
"17 他们必舔土如蛇，又如土中腹行的物，战战兢兢地出他们的营寨。他们必战惧投降耶和华，也必因我们的　神而惧怕。",
"18 　神啊，有何神像你，赦免罪孽，饶恕你产业之余民的罪过，不永远怀怒，喜爱施恩？",
"19 必再怜悯我们，将我们的罪孽踏在脚下，又将我们的一切罪投于深海。",
"",
"——【弥迦书 7】",
],
[
"1 My heart is inditing a good matter: I speak of the things which I have made touching the king: my tongue is the pen of a ready writer.",
"2 Thou art fairer than the children of men: grace is poured into thy lips: therefore God hath blessed thee for ever.",
"",
"——【The Book of Psalms 45】",
"",
"1 （可拉后裔的训诲诗，又是爱慕歌，交与伶长。调用百合花。）我心里涌出美辞；我论到我为王做的事，我的舌头是快手笔。",
"2 你比世人更美；在你嘴里满有恩惠；所以　神赐福给你，直到永远。",
"",
"——【诗篇 45】",
],
[
"7 Even every one that is called by my name: for I have created him for my glory, I have formed him; yea, I have made him.",
"8 Bring forth the blind people that have eyes, and the deaf that have ears.",
"",
"——【The Book of the Prophet Isaiah 43】",
"",
"7 就是凡称为我名下的人，是我为自己的荣耀创造的，是我所做成，所造作的。",
"8 你要将有眼而瞎、有耳而聋的民都带出来！",
"",
"——【以赛亚书 43】",
],
[
"13 Then David and his men, which were about six hundred, arose and departed out of Keilah, and went whithersoever they could go. And it was told Saul that David was escaped from Keilah; and he forbare to go forth.",
"14 And David abode in the wilderness in strong holds, and remained in a mountain in the wilderness of Ziph. And Saul sought him every day, but God delivered him not into his hand.",
"15 And David saw that Saul was come out to seek his life: and David was in the wilderness of Ziph in a wood.",
"16 And Jonathan Saul's son arose, and went to David into the wood, and strengthened his hand in God.",
"",
"——【The First Book of Samuel 23】",
"",
"13 大卫和跟随他的约有六百人，就起身出了基伊拉，往他们所能往的地方去。有人告诉扫罗，大卫离开基伊拉逃走；于是扫罗不出来了。",
"14 大卫住在旷野的山寨里，常在西弗旷野的山地。扫罗天天寻索大卫，　神却不将大卫交在他手里。",
"15 大卫知道扫罗出来寻索他的命。那时，他住在西弗旷野的树林里；",
"16 扫罗的儿子约拿单起身，往那树林里去见大卫，使他倚靠　神得以坚固，",
"",
"——【撒母耳记上 23】",
],
[
"5 Behold, as wild asses in the desert, go they forth to their work; rising betimes for a prey: the wilderness yieldeth food for them and for their children.",
"6 They reap every one his corn in the field: and they gather the vintage of the wicked.",
"7 They cause the naked to lodge without clothing, that they have no covering in the cold.",
"8 They are wet with the showers of the mountains, and embrace the rock for want of a shelter.",
"9 They pluck the fatherless from the breast, and take a pledge of the poor.",
"",
"——【The Book of Job 24】",
"",
"5 这些贫穷人如同野驴出到旷野，殷勤寻找食物；他们靠著野地给儿女糊口，",
"6 收割别人田间的禾稼，摘取恶人余剩的葡萄，",
"7 终夜赤身无衣，天气寒冷毫无遮盖，",
"8 在山上被大雨淋湿，因没有避身之处就挨近磐石。",
"9 又有人从母怀中抢夺孤儿，强取穷人的衣服为当头，",
"",
"——【约伯记 24】",
],
[
"14 I will feed them in a good pasture, and upon the high mountains of Israel shall their fold be: there shall they lie in a good fold, and in a fat pasture shall they feed upon the mountains of Israel.",
"15 I will feed my flock, and I will cause them to lie down, saith the Lord GOD.",
"16 I will seek that which was lost, and bring again that which was driven away, and will bind up that which was broken, and will strengthen that which was sick: but I will destroy the fat and the strong; I will feed them with judgment.",
"",
"——【The Book of the Prophet Ezekiel 34】",
"",
"14 我必在美好的草场牧养牠们。牠们的圈必在以色列高处的山上，牠们必在佳美之圈中躺卧，也在以色列山肥美的草场吃草。",
"15 主耶和华说：我必亲自作我羊的牧人，使牠们得以躺卧。",
"16 失丧的，我必寻找；被逐的，我必领回；受伤的，我必缠裹；有病的，我必医治；只是肥的壮的，我必除灭，也要秉公牧养牠们。",
"",
"——【以西结书 34】",
],
[
"19 And when he had saluted them, he declared particularly what things God had wrought among the Gentiles by his ministry.",
"20 And when they heard it, they glorified the Lord, and said unto him, Thou seest, brother, how many thousands of Jews there are which believe; and they are all zealous of the law:",
"21 And they are informed of thee, that thou teachest all the Jews which are among the Gentiles to forsake Moses, saying that they ought not to circumcise their children, neither to walk after the customs.",
"22 What is it therefore? the multitude must needs come together: for they will hear that thou art come.",
"23 Do therefore this that we say to thee: We have four men which have a vow on them;",
"24 Them take, and purify thyself with them, and be at charges with them, that they may shave their heads: and all may know that those things, whereof they were informed concerning thee, are nothing; but that thou thyself also walkest orderly, and keepest the law.",
"",
"——【The Acts of the Apostles 21】",
"",
"19 保罗问了他们安，便将　神用他传教，在外邦人中间所行之事，一一的述说了。",
"20 他们听见，就归荣耀与　神，对保罗说：兄台，你看犹太人中信主的有多少万，并且都为律法热心。",
"21 他们听见人说：你教训一切在外邦的犹太人离弃摩西，对他们说：不要给孩子行割礼，也不要遵行条规。",
"22 众人必听见你来了，这可怎么办呢？",
"23 你就照著我们的话行吧？我们这里有四个人，都有愿在身。",
"24 你带他们去，与他们一同行洁净的礼，替他们拿出规费，叫他们得以剃头。这样，众人就可知道，先前所听见你的事都是虚的；并可知道，你自己为人，循规蹈矩，遵行律法。",
"",
"——【使徒行传 21】",
],
[
"13 Now when Paul and his company loosed from Paphos, they came to Perga in Pamphylia: and John departing from them returned to Jerusalem.",
"14 But when they departed from Perga, they came to Antioch in Pisidia, and went into the synagogue on the sabbath day, and sat down.",
"",
"——【The Acts of the Apostles 13】",
"",
"13 保罗和他的同人从帕弗开船，来到旁非利亚的别加，约翰就离开他们，回耶路撒冷去。",
"14 他们离了别加往前行，来到彼西底的安提阿，在安息日进会堂坐下。",
"",
"——【使徒行传 13】",
],
[
"1 But of the times and the seasons, brethren, ye have no need that I write unto you.",
"2 For yourselves know perfectly that the day of the Lord so cometh as a thief in the night.",
"3 For when they shall say, Peace and safety; then sudden destruction cometh upon them, as travail upon a woman with child; and they shall not escape.",
"",
"——【The First Epistle of Paul the Apostle to the Thessalonians 5】",
"",
"1 弟兄们，论到时候、日期，不用写信给你们；",
"2 因为你们自己明明晓得，主的日子来到，好像夜间的贼一样。",
"3 人正说平安稳妥的时候，灾祸忽然临到他们，如同产难临到怀胎的妇人一样。他们绝不能逃脱。",
"",
"——【帖撒罗尼迦前书 5】",
],
[
"23 And Sihon would not suffer Israel to pass through his border: but Sihon gathered all his people together, and went out against Israel into the wilderness: and he came to Jahaz, and fought against Israel.",
"24 And Israel smote him with the edge of the sword, and possessed his land from Arnon unto Jabbok, even unto the children of Ammon: for the border of the children of Ammon was strong.",
"25 And Israel took all these cities: and Israel dwelt in all the cities of the Amorites, in Heshbon, and in all the villages thereof.",
"26 For Heshbon was the city of Sihon the king of the Amorites, who had fought against the former king of Moab, and taken all his land out of his hand, even unto Arnon.",
"",
"——【The Fourth Book of Moses: Called Numbers 21】",
"",
"23 西宏不容以色列人从他的境界经过，就招聚他的众民出到旷野，要攻击以色列人，到了雅杂与以色列人争战。",
"24 以色列人用刀杀了他，得了他的地，从亚嫩河到雅博河，直到亚扪人的境界，因为亚扪人的境界多有坚垒。",
"25 以色列人夺取这一切的城邑，也住亚摩利人的城邑，就是希实本与希实本的一切乡村。",
"26 这希实本是亚摩利王西宏的京城；西宏曾与摩押的先王争战，从他手中夺取了全地，直到亚嫩河。",
"",
"——【民数记 21】",
],
[
"1 Wherefore laying aside all malice, and all guile, and hypocrisies, and envies, and all evil speakings,",
"2 As newborn babes, desire the sincere milk of the word, that ye may grow thereby:",
"3 If so be ye have tasted that the Lord is gracious.",
"",
"——【The First Epistle General of Peter 2】",
"",
"1 所以，你们既除去一切的恶毒（或译：阴毒）、诡诈，并假善、嫉妒，和一切毁谤的话，",
"2 就要爱慕那纯净的灵奶，像才生的婴孩爱慕奶一样，叫你们因此渐长，以致得救。",
"3 你们若尝过主恩的滋味，就必如此。",
"",
"——【彼得前书 2】",
],
[
"49 For he that is mighty hath done to me great things; and holy is his name.",
"50 And his mercy is on them that fear him from generation to generation.",
"51 He hath shewed strength with his arm; he hath scattered the proud in the imagination of their hearts.",
"52 He hath put down the mighty from their seats, and exalted them of low degree.",
"",
"——【The Gospel According to Saint Luke 1】",
"",
"49 那有权能的，为我成就了大事；他的名为圣。",
"50 他怜悯敬畏他的人，直到世世代代。",
"51 他用膀臂施展大能；那狂傲的人正心里妄想就被他赶散了。",
"52 他叫有权柄的失位，叫卑贱的升高；",
"",
"——【路加福音 1】",
],
[
"8 And I answered, Who art thou, Lord? And he said unto me, I am Jesus of Nazareth, whom thou persecutest.",
"9 And they that were with me saw indeed the light, and were afraid; but they heard not the voice of him that spake to me.",
"10 And I said, What shall I do, Lord? And the Lord said unto me, Arise, and go into Damascus; and there it shall be told thee of all things which are appointed for thee to do.",
"11 And when I could not see for the glory of that light, being led by the hand of them that were with me, I came into Damascus.",
"12 And one Ananias, a devout man according to the law, having a good report of all the Jews which dwelt there,",
"13 Came unto me, and stood, and said unto me, Brother Saul, receive thy sight. And the same hour I looked up upon him.",
"",
"——【The Acts of the Apostles 22】",
"",
"8 我回答说：主啊，你是谁？他说：我就是你所逼迫的拿撒勒人耶稣。",
"9 与我同行的人看见了那光，却没有听明那位对我说话的声音。",
"10 我说：主啊，我当做什么？主说：起来，进大马士革去，在那里，要将所派你做的一切事告诉你。",
"11 我因那光的荣耀不能看见，同行的人就拉著我手进了大马士革。",
"12 那里有一个人，名叫亚拿尼亚，按著律法是虔诚人，为一切住在那里的犹太人所称赞。",
"13 他来见我，站在旁边，对我说：兄弟扫罗，你可以看见。我当时往上一看，就看见了他。",
"",
"——【使徒行传 22】",
],
[
"14 I am the good shepherd, and know my sheep, and am known of mine.",
"15 As the Father knoweth me, even so know I the Father: and I lay down my life for the sheep.",
"16 And other sheep I have, which are not of this fold: them also I must bring, and they shall hear my voice; and there shall be one fold, and one shepherd.",
"",
"——【The Gospel According to Saint John 10】",
"",
"14 我是好牧人；我认识我的羊，我的羊也认识我，",
"15 正如父认识我，我也认识父一样；并且我为羊舍命。",
"16 我另外有羊，不是这圈里的；我必须领他们来，他们也要听我的声音，并且要合成一群，归一个牧人了。",
"",
"——【约翰福音 10】",
],
[
"19 For the Son of God, Jesus Christ, who was preached among you by us, even by me and Silvanus and Timotheus, was not yea and nay, but in him was yea.",
"20 For all the promises of God in him are yea, and in him Amen, unto the glory of God by us.",
"21 Now he which stablisheth us with you in Christ, and hath anointed us, is God;",
"22 Who hath also sealed us, and given the earnest of the Spirit in our hearts.",
"",
"——【The Second Epistle of Paul the Apostle to the Corinthians 1】",
"",
"19 因为我和西拉并提摩太，在你们中间所传　神的儿子耶稣基督，总没有是而又非的，在他只有一是。",
"20 　神的应许，不论有多少，在基督都是是的。所以借著他也都是实在（实在：原文是阿们）的，叫　神因我们得荣耀。",
"21 那在基督里坚固我们和你们，并且膏我们的就是　神。",
"22 他又用印印了我们，并赐圣灵在我们心里作凭据（原文是质）。",
"",
"——【哥林多后书 1】",
],
];
