var bible31_global=[
[
"5 But thus shall ye deal with them; ye shall destroy their altars, and break down their images, and cut down their groves, and burn their graven images with fire.",
"6 For thou art an holy people unto the LORD thy God: the LORD thy God hath chosen thee to be a special people unto himself, above all people that are upon the face of the earth.",
"7 The LORD did not set his love upon you, nor choose you, because ye were more in number than any people; for ye were the fewest of all people:",
"8 But because the LORD loved you, and because he would keep the oath which he had sworn unto your fathers, hath the LORD brought you out with a mighty hand, and redeemed you out of the house of bondmen, from the hand of Pharaoh king of Egypt.",
"9 Know therefore that the LORD thy God, he is God, the faithful God, which keepeth covenant and mercy with them that love him and keep his commandments to a thousand generations;",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 7】",
"",
"5 你们却要这样待他们：拆毁他们的祭坛，打碎他们的柱像，砍下他们的木偶，用火焚烧他们雕刻的偶像。",
"6 因为你归耶和华─你　神为圣洁的民；耶和华─你　神从地上的万民中拣选你，特作自己的子民。",
"7 耶和华专爱你们，拣选你们，并非因你们的人数多于别民，原来你们的人数在万民中是最少的。",
"8 只因耶和华爱你们，又因要守他向你们列祖所起的誓，就用大能的手领你们出来，从为奴之家救赎你们脱离埃及王法老的手。",
"9 所以，你要知道耶和华─你的　神，他是　神，是信实的　神；向爱他、守他诫命的人守约，施慈爱，直到千代；",
"",
"——【申命记 7】",
],
[
"12 The king's wrath is as the roaring of a lion; but his favour is as dew upon the grass.",
"13 A foolish son is the calamity of his father: and the contentions of a wife are a continual dropping.",
"14 House and riches are the inheritance of fathers: and a prudent wife is from the LORD.",
"15 Slothfulness casteth into a deep sleep; and an idle soul shall suffer hunger.",
"",
"——【The Proverbs 19】",
"",
"12 王的忿怒好像狮子吼叫；他的恩典却如草上的甘露。",
"13 愚昧的儿子是父亲的祸患；妻子的争吵如雨连连滴漏。",
"14 房屋钱财是祖宗所遗留的；惟有贤慧的妻是耶和华所赐的。",
"15 懒惰使人沉睡；懈怠的人必受饥饿。",
"",
"——【箴言 19】",
],
[
"1 And the king Ahasuerus laid a tribute upon the land, and upon the isles of the sea.",
"2 And all the acts of his power and of his might, and the declaration of the greatness of Mordecai, whereunto the king advanced him, are they not written in the book of the chronicles of the kings of Media and Persia?",
"3 For Mordecai the Jew was next unto king Ahasuerus, and great among the Jews, and accepted of the multitude of his brethren, seeking the wealth of his people, and speaking peace to all his seed.",
"== The Book of Job ==",
"",
"——【The Book of Esther 10】",
"",
"1 亚哈随鲁王使旱地和海岛的人民都进贡。",
"2 他以权柄能力所行的，并他抬举末底改使他高升的事，岂不都写在玛代和波斯王的历史上吗？",
"3 犹大人末底改作亚哈随鲁王的宰相，在犹大人中为大，得他众弟兄的喜悦，为本族的人求好处，向他们说和平的话。",
"== 约伯记 ==",
"",
"——【以斯帖记 10】",
],
[
"29 Howbeit every nation made gods of their own, and put them in the houses of the high places which the Samaritans had made, every nation in their cities wherein they dwelt.",
"30 And the men of Babylon made Succoth–benoth, and the men of Cuth made Nergal, and the men of Hamath made Ashima,",
"31 And the Avites made Nibhaz and Tartak, and the Sepharvites burnt their children in fire to Adrammelech and Anammelech, the gods of Sepharvaim.",
"32 So they feared the LORD, and made unto themselves of the lowest of them priests of the high places, which sacrificed for them in the houses of the high places.",
"33 They feared the LORD, and served their own gods, after the manner of the nations whom they carried away from thence.",
"34 Unto this day they do after the former manners: they fear not the LORD, neither do they after their statutes, or after their ordinances, or after the law and commandment which the LORD commanded the children of Jacob, whom he named Israel;",
"",
"——【The Second Book of the Kings 17】",
"",
"29 然而，各族之人在所住的城里各为自己制造神像，安置在撒马利亚人所造有邱坛的殿中。",
"30 巴比伦人造疏割•比讷像；古他人造匿甲像；哈马人造亚示玛像；",
"31 亚瓦人造匿哈和他珥他像；西法瓦音人用火焚烧儿女，献给西法瓦音的神亚得米勒和亚拿米勒。",
"32 他们惧怕耶和华，也从他们中间立邱坛的祭司，为他们在有邱坛的殿中献祭。",
"33 他们又惧怕耶和华，又事奉自己的神，从何邦迁移，就随何邦的风俗。",
"34 他们直到如今仍照先前的风俗去行，不专心敬畏耶和华，不全守自己的规矩、典章，也不遵守耶和华吩咐雅各后裔的律法、诫命。〈雅各，就是从前耶和华起名叫以色列的。〉",
"",
"——【列王记下 17】",
],
[
"13 And it came to pass, when she saw that he had left his garment in her hand, and was fled forth,",
"14 That she called unto the men of her house, and spake unto them, saying, See, he hath brought in an Hebrew unto us to mock us; he came in unto me to lie with me, and I cried with a loud voice:",
"15 And it came to pass, when he heard that I lifted up my voice and cried, that he left his garment with me, and fled, and got him out.",
"16 And she laid up his garment by her, until his lord came home.",
"17 And she spake unto him according to these words, saying, The Hebrew servant, which thou hast brought unto us, came in unto me to mock me:",
"18 And it came to pass, as I lifted up my voice and cried, that he left his garment with me, and fled out.",
"",
"——【The First Book of Moses: Called Genesis 39】",
"",
"13 妇人看见约瑟把衣裳丢在她手里跑出去了，",
"14 就叫了家里的人来，对他们说：「你们看！他带了一个希伯来人进入我们家里，要戏弄我们。他到我这里来，要与我同寝，我就大声喊叫。",
"15 他听见我放声喊起来，就把衣裳丢在我这里，跑到外边去了。」",
"16 妇人把约瑟的衣裳放在自己那里，等著他主人回家，",
"17 就对他如此如此说：「你所带到我们这里的那希伯来仆人进来要戏弄我，",
"18 我放声喊起来，他就把衣裳丢在我这里，跑出去了。」",
"",
"——【创世记 39】",
],
[
"21 There are many devices in a man's heart; nevertheless the counsel of the LORD, that shall stand.",
"22 The desire of a man is his kindness: and a poor man is better than a liar.",
"23 The fear of the LORD tendeth to life: and he that hath it shall abide satisfied; he shall not be visited with evil.",
"",
"——【The Proverbs 19】",
"",
"21 人心多有计谋；惟有耶和华的筹算才能立定。",
"22 施行仁慈的，令人爱慕；穷人强如说谎言的。",
"23 敬畏耶和华的，得著生命；他必恒久知足，不遭祸患。",
"",
"——【箴言 19】",
],
[
"4 Which I commanded your fathers in the day that I brought them forth out of the land of Egypt, from the iron furnace, saying, Obey my voice, and do them, according to all which I command you: so shall ye be my people, and I will be your God:",
"5 That I may perform the oath which I have sworn unto your fathers, to give them a land flowing with milk and honey, as it is this day. Then answered I, and said, So be it, O LORD.",
"6 Then the LORD said unto me, Proclaim all these words in the cities of Judah, and in the streets of Jerusalem, saying, Hear ye the words of this covenant, and do them.",
"7 For I earnestly protested unto your fathers in the day that I brought them up out of the land of Egypt, even unto this day, rising early and protesting, saying, Obey my voice.",
"",
"——【The Book of the Prophet Jeremiah 11】",
"",
"4 这约是我将你们列祖从埃及地领出来、脱离铁炉的那日所吩咐他们的，说：『你们要听从我的话，照我一切所吩咐的去行。』这样，你们就作我的子民，我也作你们的　神；",
"5 我好坚定向你们列祖所起的誓，给他们流奶与蜜之地，正如今日一样。」我就回答说：「耶和华啊，阿们！」",
"6 耶和华对我说：「你要在犹大城邑中和耶路撒冷街市上，宣告这一切话说：你们当听从遵行这约的话。",
"7 因为我将你们列祖从埃及地领出来的那日，直到今日，都是从早起来，切切诰诫他们说：『你们当听从我的话。』",
"",
"——【耶利米书 11】",
],
[
"5 He loveth righteousness and judgment: the earth is full of the goodness of the LORD.",
"6 By the word of the LORD were the heavens made; and all the host of them by the breath of his mouth.",
"7 He gathereth the waters of the sea together as an heap: he layeth up the depth in storehouses.",
"8 Let all the earth fear the LORD: let all the inhabitants of the world stand in awe of him.",
"",
"——【The Book of Psalms 33】",
"",
"5 他喜爱仁义公平；遍地满了耶和华的慈爱。",
"6 诸天借耶和华的命而造；万象借他口中的气而成。",
"7 他聚集海水如垒，收藏深洋在库房。",
"8 愿全地都敬畏耶和华！愿世上的居民都惧怕他！",
"",
"——【诗篇 33】",
],
[
"26 And the weight of the golden earrings that he requested was a thousand and seven hundred shekels of gold; beside ornaments, and collars, and purple raiment that was on the kings of Midian, and beside the chains that were about their camels' necks.",
"27 And Gideon made an ephod thereof, and put it in his city, even in Ophrah: and all Israel went thither a whoring after it: which thing became a snare unto Gideon, and to his house.",
"28 Thus was Midian subdued before the children of Israel, so that they lifted up their heads no more. And the country was in quietness forty years in the days of Gideon.",
"",
"——【The Book of Judges 8】",
"",
"26 基甸所要出来的金耳环重一千七百舍客勒金子。此外还有米甸王所戴的月环、耳坠，和所穿的紫色衣服，并骆驼项上还有的金鍊子。",
"27 基甸以此制造了一个以弗得，设立在本城俄弗拉。后来以色列人拜那以弗得行了邪淫；这就作了基甸和他全家的网罗。",
"28 这样，米甸人被以色列人制伏了，不敢再抬头。基甸还在的日子，国中太平四十年。",
"",
"——【士师记 8】",
],
[
"9 And he was three days without sight, and neither did eat nor drink.",
"10 And there was a certain disciple at Damascus, named Ananias; and to him said the Lord in a vision, Ananias. And he said, Behold, I am here, Lord.",
"11 And the Lord said unto him, Arise, and go into the street which is called Straight, and enquire in the house of Judas for one called Saul, of Tarsus: for, behold, he prayeth,",
"",
"——【The Acts of the Apostles 9】",
"",
"9 三日不能看见，也不吃也不喝。",
"10 当下，在大马士革有一个门徒，名叫亚拿尼亚。主在异象中对他说：亚拿尼亚。他说：主，我在这里。",
"11 主对他说：起来！往直街去，在犹大的家里，访问一个大数人，名叫扫罗。他正祷告，",
"",
"——【使徒行传 9】",
],
[
"1 Thus hath the Lord GOD shewed unto me: and behold a basket of summer fruit.",
"2 And he said, Amos, what seest thou? And I said, A basket of summer fruit. Then said the LORD unto me, The end is come upon my people of Israel; I will not again pass by them any more.",
"3 And the songs of the temple shall be howlings in that day, saith the Lord GOD: there shall be many dead bodies in every place; they shall cast them forth with silence.",
"4 Hear this, O ye that swallow up the needy, even to make the poor of the land to fail,",
"",
"——【Amos 8】",
"",
"1 主耶和华又指示我一件事：我看见一筐夏天的果子。",
"2 他说：「阿摩司啊，你看见什么？」我说：「看见一筐夏天的果子。」耶和华说：「我民以色列的结局到了，我必不再宽恕他们。」",
"3 主耶和华说：「那日，殿中的诗歌变为哀号；必有许多尸首在各处抛弃，无人作声。」",
"4 你们这些要吞吃穷乏人、使困苦人衰败的，当听我的话！",
"",
"——【阿摩司书 8】",
],
[
"1 His foundation is in the holy mountains.",
"2 The LORD loveth the gates of Zion more than all the dwellings of Jacob.",
"3 Glorious things are spoken of thee, O city of God. Selah.",
"4 I will make mention of Rahab and Babylon to them that know me: behold Philistia, and Tyre, with Ethiopia; this man was born there.",
"",
"——【The Book of Psalms 87】",
"",
"1 （可拉后裔的诗歌。）耶和华所立的根基在圣山上。",
"2 他爱锡安的门，胜于爱雅各一切的住处。",
"3 　神的城啊，有荣耀的事乃指著你说的。（细拉）",
"4 我要提起拉哈伯和巴比伦人，是在认识我之中的；看哪，非利士和推罗并古实人，个个生在那里。",
"",
"——【诗篇 87】",
],
[
"41 And the priests; Eliakim, Maaseiah, Miniamin, Michaiah, Elioenai, Zechariah, and Hananiah, with trumpets;",
"42 And Maaseiah, and Shemaiah, and Eleazar, and Uzzi, and Jehohanan, and Malchijah, and Elam, and Ezer. And the singers sang loud, with Jezrahiah their overseer.",
"43 Also that day they offered great sacrifices, and rejoiced: for God had made them rejoice with great joy: the wives also and the children rejoiced: so that the joy of Jerusalem was heard even afar off.",
"44 And at that time were some appointed over the chambers for the treasures, for the offerings, for the firstfruits, and for the tithes, to gather into them out of the fields of the cities the portions of the law for the priests and Levites: for Judah rejoiced for the priests and for the Levites that waited.",
"",
"——【The Book of Nehemiah 12】",
"",
"41 还有祭司以利亚金、玛西雅、米拿民、米该雅、以利约乃、撒迦利亚、哈楠尼亚吹号；",
"42 又有玛西雅、示玛雅、以利亚撒、乌西、约哈难、玛基雅、以拦，和以谢奏乐。歌唱的就大声歌唱，伊斯拉希雅管理他们。",
"43 那日，众人献大祭而欢乐；因为　神使他们大大欢乐，连妇女带孩童也都欢乐，甚至耶路撒冷中的欢声听到远处。",
"44 当日，派人管理库房，将举祭、初熟之物和所取的十分之一，就是按各城田地，照律法所定归给祭司和利未人的分，都收在里头。犹大人因祭司和利未人供职，就欢乐了。",
"",
"——【尼希米记 12】",
],
[
"6 I have called upon thee, for thou wilt hear me, O God: incline thine ear unto me, and hear my speech.",
"7 Shew thy marvellous lovingkindness, O thou that savest by thy right hand them which put their trust in thee from those that rise up against them.",
"8 Keep me as the apple of the eye, hide me under the shadow of thy wings,",
"9 From the wicked that oppress me, from my deadly enemies, who compass me about.",
"10 They are inclosed in their own fat: with their mouth they speak proudly.",
"",
"——【The Book of Psalms 17】",
"",
"6 　神啊，我曾求告你，因为你必应允我；求你向我侧耳，听我的言语。",
"7 求你显出你奇妙的慈爱来；你是那用右手拯救投靠你的脱离起来攻击他们的人。",
"8 求你保护我，如同保护眼中的瞳人；将我隐藏在你翅膀的荫下，",
"9 使我脱离那欺压我的恶人，就是围困我要害我命的仇敌。",
"10 他们的心被脂油包裹；他们用口说骄傲的话。",
"",
"——【诗篇 17】",
],
[
"1 And the LORD spake unto Moses, saying,",
"2 Speak unto the children of Israel, and take of every one of them a rod according to the house of their fathers, of all their princes according to the house of their fathers twelve rods: write thou every man's name upon his rod.",
"",
"——【The Fourth Book of Moses: Called Numbers 17】",
"",
"1 耶和华对摩西说：",
"2 「你晓谕以色列人，从他们手下取杖，每支派一根；从他们所有的首领，按著支派，共取十二根。你要将各人的名字写在各人的杖上，",
"",
"——【民数记 17】",
],
[
"19 In the sweat of thy face shalt thou eat bread, till thou return unto the ground; for out of it wast thou taken: for dust thou art, and unto dust shalt thou return.",
"20 And Adam called his wife's name Eve; because she was the mother of all living.",
"21 Unto Adam also and to his wife did the LORD God make coats of skins, and clothed them.",
"22 And the LORD God said, Behold, the man is become as one of us, to know good and evil: and now, lest he put forth his hand, and take also of the tree of life, and eat, and live for ever:",
"",
"——【The First Book of Moses: Called Genesis 3】",
"",
"19 你必汗流满面才得糊口，直到你归了土，因为你是从土而出的。你本是尘土，仍要归于尘土。",
"20 亚当给他妻子起名叫夏娃，因为她是众生之母。",
"21 耶和华　神为亚当和他妻子用皮子作衣服给他们穿。",
"22 耶和华　神说：「那人已经与我们相似，能知道善恶；现在恐怕他伸手又摘生命树的果子吃，就永远活著。」",
"",
"——【创世记 3】",
],
[
"13 And the evening and the morning were the third day.",
"14 And God said, Let there be lights in the firmament of the heaven to divide the day from the night; and let them be for signs, and for seasons, and for days, and years:",
"",
"——【The First Book of Moses: Called Genesis 1】",
"",
"13 有晚上，有早晨，是第三日。",
"14 　神说：「天上要有光体，可以分昼夜，作记号，定节令、日子、年岁，",
"",
"——【创世记 1】",
],
[
"3 For Moses had given the inheritance of two tribes and an half tribe on the other side Jordan: but unto the Levites he gave none inheritance among them.",
"4 For the children of Joseph were two tribes, Manasseh and Ephraim: therefore they gave no part unto the Levites in the land, save cities to dwell in, with their suburbs for their cattle and for their substance.",
"5 As the LORD commanded Moses, so the children of Israel did, and they divided the land.",
"6 Then the children of Judah came unto Joshua in Gilgal: and Caleb the son of Jephunneh the Kenezite said unto him, Thou knowest the thing that the LORD said unto Moses the man of God concerning me and thee in Kadesh–barnea.",
"7 Forty years old was I when Moses the servant of the LORD sent me from Kadesh–barnea to espy out the land; and I brought him word again as it was in mine heart.",
"",
"——【The Book of Joshua 14】",
"",
"3 原来，摩西在约旦河东已经把产业分给那两个半支派，只是在他们中间没有把产业分给利未人。",
"4 因为约瑟的子孙是两个支派，就是玛拿西和以法莲，所以没有把地分给利未人，但给他们城邑居住，并城邑的郊野，可以牧养他们的牲畜，安置他们的财物。",
"5 耶和华怎样吩咐摩西，以色列人就照样行，把地分了。",
"6 那时，犹大人来到吉甲见约书亚，有基尼洗族耶孚尼的儿子迦勒对约书亚说：「耶和华在加低斯‧巴尼亚指著我与你对神人摩西所说的话，你都知道了。",
"7 耶和华的仆人摩西从加低斯‧巴尼亚打发我窥探这地，那时我正四十岁；我按著心意回报他。",
"",
"——【约书亚记 14】",
],
[
"1 And if a soul sin, and hear the voice of swearing, and is a witness, whether he hath seen or known of it; if he do not utter it, then he shall bear his iniquity.",
"2 Or if a soul touch any unclean thing, whether it be a carcase of an unclean beast, or a carcase of unclean cattle, or the carcase of unclean creeping things, and if it be hidden from him; he also shall be unclean, and guilty.",
"",
"——【The Third Book of Moses: Called Leviticus 5】",
"",
"1 「若有人听见发誓的声音（或作：若有人听见叫人发誓的声音），他本是见证，却不把所看见的、所知道的说出来，这就是罪；他要担当他的罪孽。",
"2 或是有人摸了不洁的物，无论是不洁的死兽，是不洁的死畜，是不洁的死虫，他却不知道，因此成了不洁，就有了罪。",
"",
"——【利未记 5】",
],
[
"7 And said unto him, Go, wash in the pool of Siloam, (which is by interpretation, Sent.) He went his way therefore, and washed, and came seeing.",
"8 The neighbours therefore, and they which before had seen him that he was blind, said, Is not this he that sat and begged?",
"9 Some said, This is he: others said, He is like him: but he said, I am he.",
"10 Therefore said they unto him, How were thine eyes opened?",
"11 He answered and said, A man that is called Jesus made clay, and anointed mine eyes, and said unto me, Go to the pool of Siloam, and wash: and I went and washed, and I received sight.",
"",
"——【The Gospel According to Saint John 9】",
"",
"7 对他说：你往西罗亚池子里去洗（西罗亚繙出来就是奉差遣）。他去一洗，回头就看见了。",
"8 他的邻舍和那素常见他是讨饭的，就说：这不是那从前坐著讨饭的人吗？",
"9 有人说：是他；又有人说；不是，却是像他。他自己说：是我。",
"10 他们对他说：你的眼睛是怎么开的呢？",
"11 他回答说：有一个人，名叫耶稣，他和泥抹我的眼睛，对我说：你往西罗亚池子去洗。我去一洗，就看见了。",
"",
"——【约翰福音 9】",
],
[
"1 And the Philistines took the ark of God, and brought it from Eben–ezer unto Ashdod.",
"2 When the Philistines took the ark of God, they brought it into the house of Dagon, and set it by Dagon.",
"",
"——【The First Book of Samuel 5】",
"",
"1 非利士人将　神的约柜从以便以谢抬到亚实突。",
"2 非利士人将　神的约柜抬进大衮庙，放在大衮的旁边。",
"",
"——【撒母耳记上 5】",
],
[
"10 Which perished at Endor: they became as dung for the earth.",
"11 Make their nobles like Oreb, and like Zeeb: yea, all their princes as Zebah, and as Zalmunna:",
"",
"——【The Book of Psalms 83】",
"",
"10 他们在隐‧多珥灭亡，成了地上的粪土。",
"11 求你叫他们的首领像俄立和西伊伯，叫他们的王子都像西巴和撒慕拿。",
"",
"——【诗篇 83】",
],
[
"29 For some of them thought, because Judas had the bag, that Jesus had said unto him, Buy those things that we have need of against the feast; or, that he should give something to the poor.",
"30 He then having received the sop went immediately out: and it was night.",
"31 Therefore, when he was gone out, Jesus said, Now is the Son of man glorified, and God is glorified in him.",
"",
"——【The Gospel According to Saint John 13】",
"",
"29 有人因犹大带著钱囊，以为耶稣是对他说：你去买我们过节所应用的东西，或是叫他拿什么赒济穷人。",
"30 犹大受了那点饼，立刻就出去。那时候是夜间了。",
"31 他既出去，耶稣就说：如今人子得了荣耀，　神在人子身上也得了荣耀。",
"",
"——【约翰福音 13】",
],
[
"7 How excellent is thy lovingkindness, O God! therefore the children of men put their trust under the shadow of thy wings.",
"8 They shall be abundantly satisfied with the fatness of thy house; and thou shalt make them drink of the river of thy pleasures.",
"9 For with thee is the fountain of life: in thy light shall we see light.",
"10 O continue thy lovingkindness unto them that know thee; and thy righteousness to the upright in heart.",
"",
"——【The Book of Psalms 36】",
"",
"7 　神啊，你的慈爱何其宝贵！世人投靠在你翅膀的荫下。",
"8 他们必因你殿里的肥甘得以饱足；你也必叫他们喝你乐河的水。",
"9 因为，在你那里有生命的源头；在你的光中，我们必得见光。",
"10 愿你常施慈爱给认识你的人，常以公义待心里正直的人。",
"",
"——【诗篇 36】",
],
[
"9 And they shall take a cloth of blue, and cover the candlestick of the light, and his lamps, and his tongs, and his snuffdishes, and all the oil vessels thereof, wherewith they minister unto it:",
"10 And they shall put it and all the vessels thereof within a covering of badgers' skins, and shall put it upon a bar.",
"",
"——【The Fourth Book of Moses: Called Numbers 4】",
"",
"9 要拿蓝色毯子，把灯台和灯台上所用的灯盏、剪子、蜡花盘，并一切盛油的器皿，全都遮盖。",
"10 又要把灯台和灯台的一切器具包在海狗皮里，放在抬架上。",
"",
"——【民数记 4】",
],
[
"9 If any man have an ear, let him hear.",
"10 He that leadeth into captivity shall go into captivity: he that killeth with the sword must be killed with the sword. Here is the patience and the faith of the saints.",
"11 And I beheld another beast coming up out of the earth; and he had two horns like a lamb, and he spake as a dragon.",
"12 And he exerciseth all the power of the first beast before him, and causeth the earth and them which dwell therein to worship the first beast, whose deadly wound was healed.",
"",
"——【The Revelation of Saint John the Devine 13】",
"",
"9 凡有耳的，就应当听！",
"10 掳掠人的，必被掳掠；用刀杀人的，必被刀杀。圣徒的忍耐和信心就是在此。",
"11 我又看见另有一个兽从地中上来有两角如同羊羔，说话好像龙。",
"12 牠在头一个兽面前，施行头一个兽所有的权柄，并且叫地和住在地上的人拜那死伤医好的头一个兽。",
"",
"——【启示录 13】",
],
[
"6 And in this mountain shall the LORD of hosts make unto all people a feast of fat things, a feast of wines on the lees, of fat things full of marrow, of wines on the lees well refined.",
"7 And he will destroy in this mountain the face of the covering cast over all people, and the vail that is spread over all nations.",
"8 He will swallow up death in victory; and the Lord GOD will wipe away tears from off all faces; and the rebuke of his people shall he take away from off all the earth: for the LORD hath spoken it.",
"",
"——【The Book of the Prophet Isaiah 25】",
"",
"6 在这山上，万军之耶和华必为万民用肥甘设摆筵席，用陈酒和满髓的肥甘，并澄清的陈酒，设摆筵席。",
"7 他又必在这山上除灭遮盖万民之物和遮蔽万国蒙脸的帕子。",
"8 他已经吞灭死亡直到永远。主耶和华必擦去各人脸上的眼泪，又除掉普天下他百姓的羞辱，因为这是耶和华说的。",
"",
"——【以赛亚书 25】",
],
[
"17 Of the Levites, Hashabiah the son of Kemuel: of the Aaronites, Zadok:",
"18 Of Judah, Elihu, one of the brethren of David: of Issachar, Omri the son of Michael:",
"19 Of Zebulun, Ishmaiah the son of Obadiah: of Naphtali, Jerimoth the son of Azriel:",
"20 Of the children of Ephraim, Hoshea the son of Azaziah: of the half tribe of Manasseh, Joel the son of Pedaiah:",
"21 Of the half tribe of Manasseh in Gilead, Iddo the son of Zechariah: of Benjamin, Jaasiel the son of Abner:",
"",
"——【The First Book of the Chronicles 27】",
"",
"17 管利未人的是基母利的儿子哈沙比雅；管亚伦子孙的是撒督；",
"18 管犹大人的是大卫的一个哥哥以利户，管以萨迦人的是米迦勒的儿子暗利；",
"19 管西布伦人的是俄巴第雅的儿子伊施玛雅；管拿弗他利人的是亚斯列的儿子耶利摩；",
"20 管以法莲人的是阿撒细雅的儿子何细亚；管玛拿西半支派的是毗大雅的儿子约珥；",
"21 管基列地玛拿西那半支派的是撒迦利亚的儿子易多；管便雅悯人的是押尼珥的儿子雅西业；",
"",
"——【历代志上 27】",
],
[
"16 Hamath, Berothah, Sibraim, which is between the border of Damascus and the border of Hamath; Hazar–hatticon, which is by the coast of Hauran.",
"17 And the border from the sea shall be Hazar–enan, the border of Damascus, and the north northward, and the border of Hamath. And this is the north side.",
"18 And the east side ye shall measure from Hauran, and from Damascus, and from Gilead, and from the land of Israel by Jordan, from the border unto the east sea. And this is the east side.",
"19 And the south side southward, from Tamar even to the waters of strife in Kadesh, the river to the great sea. And this is the south side southward.",
"20 The west side also shall be the great sea from the border, till a man come over against Hamath. This is the west side.",
"21 So shall ye divide this land unto you according to the tribes of Israel.",
"",
"——【The Book of the Prophet Ezekiel 47】",
"",
"16 又往哈马、比罗他、西伯莲（西伯莲在大马士革与哈马两界中间），到浩兰边界的哈撒‧哈提干。",
"17 这样，境界从海边往大马士革地界上的哈萨‧以难，北边以哈马地为界。这是北界。",
"18 东界在浩兰、大马士革、基列，和以色列地的中间，就是约旦河。你们要从北界量到东海。这是东界。",
"19 南界是从他玛到米利巴‧加低斯的水，延到埃及小河，直到大海。这是南界。",
"20 「西界就是大海，从南界直到哈马口对面之地。这是西界。",
"21 「你们要按著以色列的支派彼此分这地。",
"",
"——【以西结书 47】",
],
[
"1 In the LORD put I my trust: how say ye to my soul, Flee as a bird to your mountain?",
"2 For, lo, the wicked bend their bow, they make ready their arrow upon the string, that they may privily shoot at the upright in heart.",
"3 If the foundations be destroyed, what can the righteous do?",
"4 The LORD is in his holy temple, the LORD'S throne is in heaven: his eyes behold, his eyelids try, the children of men.",
"",
"——【The Book of Psalms 11】",
"",
"1 （大卫的诗，交与伶长。）我是投靠耶和华；你们怎么对我说：你当像鸟飞往你的山去。",
"2 看哪，恶人弯弓，把箭搭在弦上，要在暗中射那心里正直的人。",
"3 根基若毁坏，义人还能做什么呢？",
"4 耶和华在他的圣殿里；耶和华的宝座在天上；他的慧眼察看世人。",
"",
"——【诗篇 11】",
],
[
"38 But God giveth it a body as it hath pleased him, and to every seed his own body.",
"39 All flesh is not the same flesh: but there is one kind of flesh of men, another flesh of beasts, another of fishes, and another of birds.",
"40 There are also celestial bodies, and bodies terrestrial: but the glory of the celestial is one, and the glory of the terrestrial is another.",
"",
"——【The First Epistle of Paul the Apostle to the Corinthians 15】",
"",
"38 但　神随自己的意思给他一个形体，并叫各等子粒各有自己的形体。",
"39 凡肉体各有不同：人是一样，兽又是一样，鸟又是一样，鱼又是一样。",
"40 有天上的形体，也有地上的形体；但天上形体的荣光是一样，地上形体的荣光又是一样。",
"",
"——【哥林多前书 15】",
],
];
