var bible31_global=[
[
"28 And they answered, John the Baptist: but some say, Elias; and others, One of the prophets.",
"29 And he saith unto them, But whom say ye that I am? And Peter answereth and saith unto him, Thou art the Christ.",
"30 And he charged them that they should tell no man of him.",
"31 And he began to teach them, that the Son of man must suffer many things, and be rejected of the elders, and of the chief priests, and scribes, and be killed, and after three days rise again.",
"32 And he spake that saying openly. And Peter took him, and began to rebuke him.",
"",
"——【The Gospel According to Saint Mark 8】",
"",
"28 他们说：有人说是施洗的约翰；有人说是以利亚；又有人说是先知里的一位。",
"29 又问他们说：你们说我是谁？彼得回答说：你是基督。",
"30 耶稣就禁戒他们，不要告诉人。",
"31 从此，他教训他们说：人子必须受许多的苦，被长老、祭司长，和文士弃绝，并且被杀，过三天复活。",
"32 耶稣明明的说这话，彼得就拉著他，劝他。",
"",
"——【马可福音 8】",
],
[
"1 Hear, ye children, the instruction of a father, and attend to know understanding.",
"2 For I give you good doctrine, forsake ye not my law.",
"3 For I was my father's son, tender and only beloved in the sight of my mother.",
"4 He taught me also, and said unto me, Let thine heart retain my words: keep my commandments, and live.",
"",
"——【The Proverbs 4】",
"",
"1 众子啊，要听父亲的教训，留心得知聪明。",
"2 因我所给你们的是好教训；不可离弃我的法则（或译：指教）。",
"3 我在父亲面前为孝子，在母亲眼中为独一的娇儿。",
"4 父亲教训我说：你心要存记我的言语，遵守我的命令，便得存活。",
"",
"——【箴言 4】",
],
[
"13 For I the LORD thy God will hold thy right hand, saying unto thee, Fear not; I will help thee.",
"14 Fear not, thou worm Jacob, and ye men of Israel; I will help thee, saith the LORD, and thy redeemer, the Holy One of Israel.",
"15 Behold, I will make thee a new sharp threshing instrument having teeth: thou shalt thresh the mountains, and beat them small, and shalt make the hills as chaff.",
"16 Thou shalt fan them, and the wind shall carry them away, and the whirlwind shall scatter them: and thou shalt rejoice in the LORD, and shalt glory in the Holy One of Israel.",
"17 When the poor and needy seek water, and there is none, and their tongue faileth for thirst, I the LORD will hear them, I the God of Israel will not forsake them.",
"18 I will open rivers in high places, and fountains in the midst of the valleys: I will make the wilderness a pool of water, and the dry land springs of water.",
"",
"——【The Book of the Prophet Isaiah 41】",
"",
"13 因为我耶和华─你的　神必搀扶你的右手，对你说：不要害怕！我必帮助你。",
"14 你这虫雅各和你们以色列人，不要害怕！耶和华说：我必帮助你。你的救赎主就是以色列的圣者。",
"15 看哪，我已使你成为有快齿打粮的新器具；你要把山岭打得粉碎，使冈陵如同糠秕。",
"16 你要把它簸扬，风要吹去；旋风要把它刮散。你倒要以耶和华为喜乐，以色列的圣者为夸耀。",
"17 困苦穷乏人寻求水却没有；他们因口渴，舌头干燥。我─耶和华必应允他们；我─以色列的　神必不离弃他们。",
"18 我要在净光的高处开江河，在谷中开泉源；我要使沙漠变为水池，使干地变为涌泉。",
"",
"——【以赛亚书 41】",
],
[
"1 Cry aloud, spare not, lift up thy voice like a trumpet, and shew my people their transgression, and the house of Jacob their sins.",
"2 Yet they seek me daily, and delight to know my ways, as a nation that did righteousness, and forsook not the ordinance of their God: they ask of me the ordinances of justice; they take delight in approaching to God.",
"3 Wherefore have we fasted, say they, and thou seest not? wherefore have we afflicted our soul, and thou takest no knowledge? Behold, in the day of your fast ye find pleasure, and exact all your labours.",
"4 Behold, ye fast for strife and debate, and to smite with the fist of wickedness: ye shall not fast as ye do this day, to make your voice to be heard on high.",
"",
"——【The Book of the Prophet Isaiah 58】",
"",
"1 你要大声喊叫，不可止息；扬起声来，好像吹角。向我百姓说明他们的过犯；向雅各家说明他们的罪恶。",
"2 他们天天寻求我，乐意明白我的道，好像行义的国民，不离弃他们　神的典章，向我求问公义的判语，喜悦亲近　神。",
"3 他们说：我们禁食，你为何不看见呢？我们刻苦己心，你为何不理会呢？看哪，你们禁食的日子仍求利益，勒逼人为你们做苦工。",
"4 你们禁食，却互相争竞，以凶恶的拳头打人。你们今日禁食，不得使你们的声音听闻于上。",
"",
"——【以赛亚书 58】",
],
[
"1 Hear, ye children, the instruction of a father, and attend to know understanding.",
"2 For I give you good doctrine, forsake ye not my law.",
"3 For I was my father's son, tender and only beloved in the sight of my mother.",
"4 He taught me also, and said unto me, Let thine heart retain my words: keep my commandments, and live.",
"5 Get wisdom, get understanding: forget it not; neither decline from the words of my mouth.",
"",
"——【The Proverbs 4】",
"",
"1 众子啊，要听父亲的教训，留心得知聪明。",
"2 因我所给你们的是好教训；不可离弃我的法则（或译：指教）。",
"3 我在父亲面前为孝子，在母亲眼中为独一的娇儿。",
"4 父亲教训我说：你心要存记我的言语，遵守我的命令，便得存活。",
"5 要得智慧，要得聪明，不可忘记，也不可偏离我口中的言语。",
"",
"——【箴言 4】",
],
[
"3 The watchmen that go about the city found me: to whom I said, Saw ye him whom my soul loveth?",
"4 It was but a little that I passed from them, but I found him whom my soul loveth: I held him, and would not let him go, until I had brought him into my mother's house, and into the chamber of her that conceived me.",
"",
"——【The Song of Solomon 3】",
"",
"3 城中巡逻看守的人遇见我；我问他们：你们看见我心所爱的没有？",
"4 我刚离开他们就遇见我心所爱的。我拉住他，不容他走，领他入我母家，到怀我者的内室。",
"",
"——【雅歌 3】",
],
[
"8 Be not thou therefore ashamed of the testimony of our Lord, nor of me his prisoner: but be thou partaker of the afflictions of the gospel according to the power of God;",
"9 Who hath saved us, and called us with an holy calling, not according to our works, but according to his own purpose and grace, which was given us in Christ Jesus before the world began,",
"10 But is now made manifest by the appearing of our Saviour Jesus Christ, who hath abolished death, and hath brought life and immortality to light through the gospel:",
"11 Whereunto I am appointed a preacher, and an apostle, and a teacher of the Gentiles.",
"12 For the which cause I also suffer these things: nevertheless I am not ashamed: for I know whom I have believed, and am persuaded that he is able to keep that which I have committed unto him against that day.",
"13 Hold fast the form of sound words, which thou hast heard of me, in faith and love which is in Christ Jesus.",
"",
"——【The Second Epistle of Paul the Apostle to Timothy 1】",
"",
"8 你不要以给我们的主作见证为耻，也不要以我这为主被囚的为耻；总要按　神的能力，与我为福音同受苦难。",
"9 　神救了我们，以圣召召我们，不是按我们的行为，乃是按他的旨意和恩典；这恩典是万古之先，在基督耶稣里赐给我们的，",
"10 但如今借著我们救主基督耶稣的显现才表明出来了。他已经把死废去，借著福音，将不能坏的生命彰显出来。",
"11 我为这福音奉派作传道的，作使徒，作师傅。",
"12 为这缘故，我也受这些苦难。然而我不以为耻；因为知道我所信的是谁，也深信他能保全我所交付他的（或作：他所交托我的），直到那日。",
"13 你从我听的那纯正话语的规模，要用在基督耶稣里的信心和爱心，常常守著。",
"",
"——【提摩太后书 1】",
],
[
"7 There is that maketh himself rich, yet hath nothing: there is that maketh himself poor, yet hath great riches.",
"8 The ransom of a man's life are his riches: but the poor heareth not rebuke.",
"",
"——【The Proverbs 13】",
"",
"7 假作富足的，却一无所有；装作穷乏的，却广有财物。",
"8 人的资财是他生命的赎价；穷乏人却听不见威吓的话。",
"",
"——【箴言 13】",
],
[
"4 And they came near before Eleazar the priest, and before Joshua the son of Nun, and before the princes, saying, The LORD commanded Moses to give us an inheritance among our brethren. Therefore according to the commandment of the LORD he gave them an inheritance among the brethren of their father.",
"5 And there fell ten portions to Manasseh, beside the land of Gilead and Bashan, which were on the other side Jordan;",
"",
"——【The Book of Joshua 17】",
"",
"4 她们来到祭司以利亚撒和嫩的儿子约书亚并众首领面前，说：「耶和华曾吩咐摩西在我们弟兄中分给我们产业。」于是约书亚照耶和华所吩咐的，在她们伯叔中，把产业分给她们。",
"5 除了约旦河东的基列和巴珊地之外，还有十分地归玛拿西，",
"",
"——【约书亚记 17】",
],
[
"5 Turn away thine eyes from me, for they have overcome me: thy hair is as a flock of goats that appear from Gilead.",
"6 Thy teeth are as a flock of sheep which go up from the washing, whereof every one beareth twins, and there is not one barren among them.",
"7 As a piece of a pomegranate are thy temples within thy locks.",
"8 There are threescore queens, and fourscore concubines, and virgins without number.",
"9 My dove, my undefiled is but one; she is the only one of her mother, she is the choice one of her that bare her. The daughters saw her, and blessed her; yea, the queens and the concubines, and they praised her.",
"10 Who is she that looketh forth as the morning, fair as the moon, clear as the sun, and terrible as an army with banners?",
"",
"——【The Song of Solomon 6】",
"",
"5 求你掉转眼目不看我，因你的眼目使我惊乱。你的头发如同山羊群卧在基列山旁。",
"6 你的牙齿如一群母羊洗净上来，个个都有双生，没有一只丧掉子的。",
"7 你的两太阳在帕子内，如同一块石榴。",
"8 有六十王后八十妃嫔，并有无数的童女。",
"9 我的鸽子，我的完全人，只有这一个是她母亲独生的，是生养她者所宝爱的。众女子见了就称她有福；王后妃嫔见了也讚美她。",
"10 那向外观看、如晨光发现、美丽如月亮、皎洁如日头、威武如展开旌旗军队的是谁呢？",
"",
"——【雅歌 6】",
],
[
"35 And all that dwelt at Lydda and Saron saw him, and turned to the Lord.",
"36 Now there was at Joppa a certain disciple named Tabitha, which by interpretation is called Dorcas: this woman was full of good works and almsdeeds which she did.",
"37 And it came to pass in those days, that she was sick, and died: whom when they had washed, they laid her in an upper chamber.",
"",
"——【The Acts of the Apostles 9】",
"",
"35 凡住吕大和沙崙的人都看见了他，就归服主。",
"36 在约帕有一个女徒，名叫大比大，繙希腊话就是多加（就是羚羊的意思）；她广行善事，多施赒济。",
"37 当时，她患病而死，有人把她洗了，停在楼上。",
"",
"——【使徒行传 9】",
],
[
"1 And the LORD spake unto Moses and to Aaron, saying,",
"2 Speak unto the children of Israel, and say unto them, When any man hath a running issue out of his flesh, because of his issue he is unclean.",
"3 And this shall be his uncleanness in his issue: whether his flesh run with his issue, or his flesh be stopped from his issue, it is his uncleanness.",
"",
"——【The Third Book of Moses: Called Leviticus 15】",
"",
"1 耶和华对摩西、亚伦说：",
"2 「你们晓谕以色列人说：人若身患漏症，他因这漏症就不洁净了。",
"3 他患漏症，无论是下流的，是止住的，都是不洁净。",
"",
"——【利未记 15】",
],
[
"8 Neither did we eat any man's bread for nought; but wrought with labour and travail night and day, that we might not be chargeable to any of you:",
"9 Not because we have not power, but to make ourselves an ensample unto you to follow us.",
"10 For even when we were with you, this we commanded you, that if any would not work, neither should he eat.",
"",
"——【The Second Epistle of Paul the Apostle to the Thessalonians 3】",
"",
"8 也未尝白吃人的饭，倒是辛苦劳碌，昼夜做工，免得叫你们一人受累。",
"9 这并不是因我们没有权柄，乃是要给你们作榜样，叫你们效法我们。",
"10 我们在你们那里的时候，曾吩咐你们说，若有人不肯做工，就不可吃饭。",
"",
"——【帖撒罗尼迦后书 3】",
],
[
"4 And he brought them before the king of Moab: and they dwelt with him all the while that David was in the hold.",
"5 And the prophet Gad said unto David, Abide not in the hold; depart, and get thee into the land of Judah. Then David departed, and came into the forest of Hareth.",
"6 When Saul heard that David was discovered, and the men that were with him, (now Saul abode in Gibeah under a tree in Ramah, having his spear in his hand, and all his servants were standing about him;)",
"7 Then Saul said unto his servants that stood about him, Hear now, ye Benjamites; will the son of Jesse give every one of you fields and vineyards, and make you all captains of thousands, and captains of hundreds;",
"8 That all of you have conspired against me, and there is none that sheweth me that my son hath made a league with the son of Jesse, and there is none of you that is sorry for me, or sheweth unto me that my son hath stirred up my servant against me, to lie in wait, as at this day?",
"9 Then answered Doeg the Edomite, which was set over the servants of Saul, and said, I saw the son of Jesse coming to Nob, to Ahimelech the son of Ahitub.",
"",
"——【The First Book of Samuel 22】",
"",
"4 大卫领他父母到摩押王面前。大卫住山寨多少日子，他父母也住摩押王那里多少日子。",
"5 先知迦得对大卫说：「你不要住在山寨，要往犹大地去。」大卫就离开那里，进入哈列的树林。",
"6 扫罗在基比亚的拉玛，坐在垂丝柳树下，手里拿著枪，众臣仆侍立在左右。扫罗听见大卫和跟随他的人在何处，",
"7 就对左右侍立的臣仆说：「便雅悯人哪，你们要听我的话！耶西的儿子能将田地和葡萄园赐给你们各人吗？能立你们各人作千夫长百夫长吗？",
"8 你们竟都结党害我！我的儿子与耶西的儿子结盟的时候，无人告诉我；我的儿子挑唆我的臣子谋害我，就如今日的光景，也无人告诉我，为我忧虑。」",
"9 那时以东人多益站在扫罗的臣仆中，对他说：「我曾看见耶西的儿子到了挪伯，亚希突的儿子亚希米勒那里。",
"",
"——【撒母耳记上 22】",
],
[
"7 What shall we say then? Is the law sin? God forbid. Nay, I had not known sin, but by the law: for I had not known lust, except the law had said, Thou shalt not covet.",
"8 But sin, taking occasion by the commandment, wrought in me all manner of concupiscence. For without the law sin was dead.",
"9 For I was alive without the law once: but when the commandment came, sin revived, and I died.",
"10 And the commandment, which was ordained to life, I found to be unto death.",
"11 For sin, taking occasion by the commandment, deceived me, and by it slew me.",
"",
"——【The Epistle of Paul the Apostle to the Romans 7】",
"",
"7 这样，我们可说什么呢？律法是罪么？断乎不是！只是非因律法，我就不知何为罪。非律法说不可起贪心，我就不知何为贪心。",
"8 然而罪趁著机会，就借著诫命叫诸般的贪心在我里头发动；因为没有律法，罪是死的。",
"9 我以前没有律法是活著的；但是诫命来到，罪又活了，我就死了。",
"10 那本来叫人活的诫命，反倒叫我死；",
"11 因为罪趁著机会，就借著诫命引诱我，并且杀了我。",
"",
"——【罗马书 7】",
],
[
"23 And one loaf of bread, and one cake of oiled bread, and one wafer out of the basket of the unleavened bread that is before the LORD:",
"24 And thou shalt put all in the hands of Aaron, and in the hands of his sons; and shalt wave them for a wave offering before the LORD.",
"25 And thou shalt receive them of their hands, and burn them upon the altar for a burnt offering, for a sweet savour before the LORD: it is an offering made by fire unto the LORD.",
"26 And thou shalt take the breast of the ram of Aaron's consecration, and wave it for a wave offering before the LORD: and it shall be thy part.",
"27 And thou shalt sanctify the breast of the wave offering, and the shoulder of the heave offering, which is waved, and which is heaved up, of the ram of the consecration, even of that which is for Aaron, and of that which is for his sons:",
"28 And it shall be Aaron's and his sons' by a statute for ever from the children of Israel: for it is an heave offering: and it shall be an heave offering from the children of Israel of the sacrifice of their peace offerings, even their heave offering unto the LORD.",
"",
"——【The Second Book of Moses: Called Exodus 29】",
"",
"23 再从耶和华面前装无酵饼的筐子中取一个饼，一个调油的饼和一个薄饼，",
"24 都放在亚伦的手上和他儿子的手上，作为摇祭，在耶和华面前摇一摇。",
"25 要从他们手中接过来，烧在耶和华面前坛上的燔祭上，是献给耶和华为馨香的火祭。",
"26 「你要取亚伦承接圣职所献公羊的胸，作为摇祭，在耶和华面前摇一摇，这就可以作你的分。",
"27 那摇祭的胸和举祭的腿，就是承接圣职所摇的、所举的，是归亚伦和他儿子的。这些你都要成为圣，",
"28 作亚伦和他子孙从以色列人中永远所得的分，因为是举祭。这要从以色列人的平安祭中，作为献给耶和华的举祭。",
"",
"——【出埃及记 29】",
],
[
"5 I tell you, Nay: but, except ye repent, ye shall all likewise perish.",
"6 He spake also this parable; A certain man had a fig tree planted in his vineyard; and he came and sought fruit thereon, and found none.",
"7 Then said he unto the dresser of his vineyard, Behold, these three years I come seeking fruit on this fig tree, and find none: cut it down; why cumbereth it the ground?",
"",
"——【The Gospel According to Saint Luke 13】",
"",
"5 我告诉你们，不是的！你们若不悔改，都要如此灭亡！",
"6 于是用比喻说：一个人有一棵无花果树栽在葡萄园里。他来到树前找果子，却找不著。",
"7 就对管园的说：看哪，我这三年来到这无花果树前找果子，竟找不著。把它砍了吧，何必白占地土呢！",
"",
"——【路加福音 13】",
],
[
"15 And now the wise men, the astrologers, have been brought in before me, that they should read this writing, and make known unto me the interpretation thereof: but they could not shew the interpretation of the thing:",
"16 And I have heard of thee, that thou canst make interpretations, and dissolve doubts: now if thou canst read the writing, and make known to me the interpretation thereof, thou shalt be clothed with scarlet, and have a chain of gold about thy neck, and shalt be the third ruler in the kingdom.",
"17 Then Daniel answered and said before the king, Let thy gifts be to thyself, and give thy rewards to another; yet I will read the writing unto the king, and make known to him the interpretation.",
"",
"——【The Book of Daniel 5】",
"",
"15 现在哲士和用法术的都领到我面前，为叫他们读这文字，把讲解告诉我，无奈他们都不能把讲解说出来。",
"16 我听说你善于讲解，能解疑惑；现在你若能读这文字，把讲解告诉我，就必身穿紫袍，项戴金鍊，在我国中位列第三。」",
"17 但以理在王面前回答说：「你的赠品可以归你自己，你的赏赐可以归给别人；我却要为王读这文字，把讲解告诉王。",
"",
"——【但以理书 5】",
],
[
"10 He that loveth his brother abideth in the light, and there is none occasion of stumbling in him.",
"11 But he that hateth his brother is in darkness, and walketh in darkness, and knoweth not whither he goeth, because that darkness hath blinded his eyes.",
"12 I write unto you, little children, because your sins are forgiven you for his name's sake.",
"13 I write unto you, fathers, because ye have known him that is from the beginning. I write unto you, young men, because ye have overcome the wicked one. I write unto you, little children, because ye have known the Father.",
"",
"——【The First Epistle General of John 2】",
"",
"10 爱弟兄的，就是住在光明中，在他并没有绊跌的缘由。",
"11 惟独恨弟兄的，是在黑暗里，且在黑暗里行，也不知道往那里去，因为黑暗叫他眼睛瞎了。",
"12 小子们哪，我写信给你们，因为你们的罪借著主名得了赦免。",
"13 父老啊，我写信给你们，因为你们认识那从起初原有的。少年人哪，我写信给你们，因为你们胜了那恶者。小子们哪，我曾写信给你们，因为你们认识父。",
"",
"——【约翰一书 2】",
],
[
"13 And they shall not come near unto me, to do the office of a priest unto me, nor to come near to any of my holy things, in the most holy place: but they shall bear their shame, and their abominations which they have committed.",
"14 But I will make them keepers of the charge of the house, for all the service thereof, and for all that shall be done therein.",
"15 But the priests the Levites, the sons of Zadok, that kept the charge of my sanctuary when the children of Israel went astray from me, they shall come near to me to minister unto me, and they shall stand before me to offer unto me the fat and the blood, saith the Lord GOD:",
"16 They shall enter into my sanctuary, and they shall come near to my table, to minister unto me, and they shall keep my charge.",
"17 And it shall come to pass, that when they enter in at the gates of the inner court, they shall be clothed with linen garments; and no wool shall come upon them, whiles they minister in the gates of the inner court, and within.",
"18 They shall have linen bonnets upon their heads, and shall have linen breeches upon their loins; they shall not gird themselves with any thing that causeth sweat.",
"",
"——【The Book of the Prophet Ezekiel 44】",
"",
"13 他们不可亲近我，给我供祭司的职分，也不可挨近我的一件圣物，就是至圣的物；他们却要担当自己的羞辱和所行可憎之事的报应。",
"14 然而我要使他们看守殿宇，办理其中的一切事，并做其内一切当做之工。」",
"15 「以色列人走迷离开我的时候，祭司利未人撒督的子孙仍看守我的圣所。他们必亲近我，事奉我，并且侍立在我面前，将脂油与血献给我。这是主耶和华说的。",
"16 他们必进入我的圣所，就近我的桌前事奉我，守我所吩咐的。",
"17 他们进内院门必穿细麻衣。在内院门和殿内供职的时候不可穿羊毛衣服。",
"18 他们头上要戴细麻布裹头巾，腰穿细麻布裤子；不可穿使身体出汗的衣服。",
"",
"——【以西结书 44】",
],
[
"14 Bring forth him that hath cursed without the camp; and let all that heard him lay their hands upon his head, and let all the congregation stone him.",
"15 And thou shalt speak unto the children of Israel, saying, Whosoever curseth his God shall bear his sin.",
"",
"——【The Third Book of Moses: Called Leviticus 24】",
"",
"14 「把那咒诅圣名的人带到营外。叫听见的人都放手在他头上；全会众就要用石头打死他。",
"15 你要晓谕以色列人说：凡咒诅　神的，必担当他的罪。",
"",
"——【利未记 24】",
],
[
"10 The bricks are fallen down, but we will build with hewn stones: the sycomores are cut down, but we will change them into cedars.",
"11 Therefore the LORD shall set up the adversaries of Rezin against him, and join his enemies together;",
"12 The Syrians before, and the Philistines behind; and they shall devour Israel with open mouth. For all this his anger is not turned away, but his hand is stretched out still.",
"13 For the people turneth not unto him that smiteth them, neither do they seek the LORD of hosts.",
"14 Therefore the LORD will cut off from Israel head and tail, branch and rush, in one day.",
"15 The ancient and honourable, he is the head; and the prophet that teacheth lies, he is the tail.",
"",
"——【The Book of the Prophet Isaiah 9】",
"",
"10 砖墙塌了，我们却要凿石头建筑；桑树砍了，我们却要换香柏树。",
"11 因此，耶和华要高举利汛的敌人来攻击以色列，并要激动以色列的仇敌。",
"12 东有亚兰人，西有非利士人；他们张口要吞吃以色列。虽然如此，耶和华的怒气还未转消；他的手仍伸不缩。",
"13 这百姓还没有归向击打他们的主，也没有寻求万军之耶和华。",
"14 因此，耶和华一日之间必从以色列中剪除头与尾，棕枝与芦苇─",
"15 长老和尊贵人就是头，以谎言教人的先知就是尾。",
"",
"——【以赛亚书 9】",
],
[
"1 Then answered Bildad the Shuhite, and said,",
"2 Dominion and fear are with him, he maketh peace in his high places.",
"3 Is there any number of his armies? and upon whom doth not his light arise?",
"4 How then can man be justified with God? or how can he be clean that is born of a woman?",
"5 Behold even to the moon, and it shineth not; yea, the stars are not pure in his sight.",
"6 How much less man, that is a worm? and the son of man, which is a worm?",
"",
"——【The Book of Job 25】",
"",
"1 书亚人比勒达回答说：",
"2 　神有治理之权，有威严可畏；他在高处施行和平。",
"3 他的诸军岂能数算？他的光亮一发，谁不蒙照呢？",
"4 这样在　神面前，人怎能称义？妇人所生的怎能洁净？",
"5 在　神眼前，月亮也无光亮，星宿也不清洁。",
"6 何况如虫的人，如蛆的世人呢！",
"",
"——【约伯记 25】",
],
[
"20 In his days Edom revolted from under the hand of Judah, and made a king over themselves.",
"21 So Joram went over to Zair, and all the chariots with him: and he rose by night, and smote the Edomites which compassed him about, and the captains of the chariots: and the people fled into their tents.",
"22 Yet Edom revolted from under the hand of Judah unto this day. Then Libnah revolted at the same time.",
"23 And the rest of the acts of Joram, and all that he did, are they not written in the book of the chronicles of the kings of Judah?",
"",
"——【The Second Book of the Kings 8】",
"",
"20 约兰年间，以东人背叛犹大，脱离他的权下，自己立王。",
"21 约兰率领所有的战车往撒益去，夜间起来，攻打围困他的以东人和车兵长；犹大兵就逃跑，各回各家去了。",
"22 这样，以东人背叛犹大，脱离他的权下，直到今日。那时立拿人也背叛了。",
"23 约兰其余的事，凡他所行的，都写在犹大列王记上。",
"",
"——【列王记下 8】",
],
[
"1 And Samson went down to Timnath, and saw a woman in Timnath of the daughters of the Philistines.",
"2 And he came up, and told his father and his mother, and said, I have seen a woman in Timnath of the daughters of the Philistines: now therefore get her for me to wife.",
"",
"——【The Book of Judges 14】",
"",
"1 参孙下到亭拿，在那里看见一个女子，是非利士人的女儿。",
"2 参孙上来禀告他父母说：「我在亭拿看见一个女子，是非利士人的女儿，愿你们给我娶来为妻。」",
"",
"——【士师记 14】",
],
[
"20 My bone cleaveth to my skin and to my flesh, and I am escaped with the skin of my teeth.",
"21 Have pity upon me, have pity upon me, O ye my friends; for the hand of God hath touched me.",
"",
"——【The Book of Job 19】",
"",
"20 我的皮肉紧贴骨头；我只剩牙皮逃脱了。",
"21 我朋友啊，可怜我！可怜我！因为　神的手攻击我。",
"",
"——【约伯记 19】",
],
[
"14 That the blessing of Abraham might come on the Gentiles through Jesus Christ; that we might receive the promise of the Spirit through faith.",
"15 Brethren, I speak after the manner of men; Though it be but a man's covenant, yet if it be confirmed, no man disannulleth, or addeth thereto.",
"16 Now to Abraham and his seed were the promises made. He saith not, And to seeds, as of many; but as of one, And to thy seed, which is Christ.",
"17 And this I say, that the covenant, that was confirmed before of God in Christ, the law, which was four hundred and thirty years after, cannot disannul, that it should make the promise of none effect.",
"18 For if the inheritance be of the law, it is no more of promise: but God gave it to Abraham by promise.",
"",
"——【The Epistle of Paul the Apostle to the Galatians 3】",
"",
"14 这便叫亚伯拉罕的福，因基督耶稣可以临到外邦人，使我们因信得著所应许的圣灵。",
"15 弟兄们，我且照著人的常话说：虽然是人的文约，若已经立定了，就没有能废弃或加增的。",
"16 所应许的原是向亚伯拉罕和他子孙说的。　神并不是说众子孙，指著许多人，乃是说你那一个子孙，指著一个人，就是基督。",
"17 我是这么说，　神预先所立的约，不能被那四百三十年以后的律法废掉，叫应许归于虚空。",
"18 因为承受产业，若本乎律法，就不本乎应许；但　神是凭著应许把产业赐给亚伯拉罕。",
"",
"——【加拉太书 3】",
],
[
"13 But hast walked in the way of the kings of Israel, and hast made Judah and the inhabitants of Jerusalem to go a whoring, like to the whoredoms of the house of Ahab, and also hast slain thy brethren of thy father's house, which were better than thyself:",
"14 Behold, with a great plague will the LORD smite thy people, and thy children, and thy wives, and all thy goods:",
"15 And thou shalt have great sickness by disease of thy bowels, until thy bowels fall out by reason of the sickness day by day.",
"16 Moreover the LORD stirred up against Jehoram the spirit of the Philistines, and of the Arabians, that were near the Ethiopians:",
"17 And they came up into Judah, and brake into it, and carried away all the substance that was found in the king's house, and his sons also, and his wives; so that there was never a son left him, save Jehoahaz, the youngest of his sons.",
"",
"——【The Second Book of the Chronicles 21】",
"",
"13 乃行以色列诸王的道，使犹大人和耶路撒冷的居民行邪淫，像亚哈家一样，又杀了你父家比你好的诸兄弟。",
"14 故此，耶和华降大灾与你的百姓和你的妻子、儿女，并你一切所有的。",
"15 你的肠子必患病，日加沉重，以致你的肠子坠落下来。』」",
"16 以后，耶和华激动非利士人和靠近古实的阿拉伯人来攻击约兰。",
"17 他们上来攻击犹大，侵入境内，掳掠了王宫里所有的财货和他的妻子、儿女，除了他小儿子约哈斯【又名亚哈谢】之外，没有留下一个儿子。",
"",
"——【历代志下 21】",
],
[
"1 But there were false prophets also among the people, even as there shall be false teachers among you, who privily shall bring in damnable heresies, even denying the Lord that bought them, and bring upon themselves swift destruction.",
"2 And many shall follow their pernicious ways; by reason of whom the way of truth shall be evil spoken of.",
"3 And through covetousness shall they with feigned words make merchandise of you: whose judgment now of a long time lingereth not, and their damnation slumbereth not.",
"",
"——【The Second General Epistle of Peter 2】",
"",
"1 从前在百姓中有假先知起来，将来在你们中间也必有假师傅，私自引进陷害人的异端，连买他们的主他们也不承认，自取速速的灭亡。",
"2 将有许多人随从他们邪淫的行为，便叫真道因他们的缘故被毁谤。",
"3 他们因有贪心，要用捏造的言语在你们身上取利。他们的刑罚，自古以来并不迟延；他们的灭亡也必速速来到（原文是不打盹）。",
"",
"——【彼得后书 2】",
],
[
"31 Behold, I am against the prophets, saith the LORD, that use their tongues, and say, He saith.",
"32 Behold, I am against them that prophesy false dreams, saith the LORD, and do tell them, and cause my people to err by their lies, and by their lightness; yet I sent them not, nor commanded them: therefore they shall not profit this people at all, saith the LORD.",
"33 And when this people, or the prophet, or a priest, shall ask thee, saying, What is the burden of the LORD? thou shalt then say unto them, What burden? I will even forsake you, saith the LORD.",
"34 And as for the prophet, and the priest, and the people, that shall say, The burden of the LORD, I will even punish that man and his house.",
"35 Thus shall ye say every one to his neighbour, and every one to his brother, What hath the LORD answered? and, What hath the LORD spoken?",
"36 And the burden of the LORD shall ye mention no more: for every man's word shall be his burden; for ye have perverted the words of the living God, of the LORD of hosts our God.",
"",
"——【The Book of the Prophet Jeremiah 23】",
"",
"31 耶和华说：「那些先知用舌头，说是耶和华说的；我必与他们反对。」",
"32 耶和华说：「那些以幻梦为预言，又述说这梦，以谎言和矜夸使我百姓走错了路的，我必与他们反对。我没有打发他们，也没有吩咐他们。他们与这百姓毫无益处。这是耶和华说的。」",
"33 「无论是百姓，是先知，是祭司，问你说：『耶和华有什么默示呢？』你就对他们说：『什么默示啊？耶和华说：我要撇弃你们。』",
"34 无论是先知，是祭司，是百姓，说『耶和华的默示』，我必刑罚那人和他的家。",
"35 你们各人要对邻舍，各人要对弟兄如此说：『耶和华回答什么？』『耶和华说了什么呢？』",
"36 『耶和华的默示』你们不可再提，各人所说的话必作自己的重担（重担和默示原文同），因为你们谬用永生　神、万军之耶和华─我们　神的言语。",
"",
"——【耶利米书 23】",
],
[
"40 Thou hast broken down all his hedges; thou hast brought his strong holds to ruin.",
"41 All that pass by the way spoil him: he is a reproach to his neighbours.",
"42 Thou hast set up the right hand of his adversaries; thou hast made all his enemies to rejoice.",
"43 Thou hast also turned the edge of his sword, and hast not made him to stand in the battle.",
"",
"——【The Book of Psalms 89】",
"",
"40 你拆毁了他一切的篱笆，使他的保障变为荒场。",
"41 凡过路的人都抢夺他；他成为邻邦的羞辱。",
"42 你高举了他敌人的右手；你叫他一切的仇敌欢喜。",
"43 你叫他的刀剑捲刃，叫他在争战之中站立不住。",
"",
"——【诗篇 89】",
],
];
