var bible31_global=[
[
"14 Where we found brethren, and were desired to tarry with them seven days: and so we went toward Rome.",
"15 And from thence, when the brethren heard of us, they came to meet us as far as Appii forum, and The three taverns: whom when Paul saw, he thanked God, and took courage.",
"16 And when we came to Rome, the centurion delivered the prisoners to the captain of the guard: but Paul was suffered to dwell by himself with a soldier that kept him.",
"17 And it came to pass, that after three days Paul called the chief of the Jews together: and when they were come together, he said unto them, Men and brethren, though I have committed nothing against the people, or customs of our fathers, yet was I delivered prisoner from Jerusalem into the hands of the Romans.",
"",
"——【The Acts of the Apostles 28】",
"",
"14 在那里遇见弟兄们，请我们与他们同住了七天。这样，我们来到罗马。",
"15 那里的弟兄们一听见我们的信息就出来，到亚比乌市和三馆地方迎接我们。保罗见了他们，就感谢　神，放心壮胆。",
"16 进了罗马城，（有古卷在此有：百夫长把众囚犯交给御营的统领，惟有）保罗蒙准和一个看守他的兵另住在一处。",
"17 过了三天，保罗请犹太人的首领来。他们来了，就对他们说：弟兄们，我虽没有做什么事干犯本国的百姓和我们祖宗的规条，却被锁绑，从耶路撒冷解在罗马人的手里。",
"",
"——【使徒行传 28】",
],
[
"32 And John bare record, saying, I saw the Spirit descending from heaven like a dove, and it abode upon him.",
"33 And I knew him not: but he that sent me to baptize with water, the same said unto me, Upon whom thou shalt see the Spirit descending, and remaining on him, the same is he which baptizeth with the Holy Ghost.",
"34 And I saw, and bare record that this is the Son of God.",
"35 Again the next day after John stood, and two of his disciples;",
"36 And looking upon Jesus as he walked, he saith, Behold the Lamb of God!",
"37 And the two disciples heard him speak, and they followed Jesus.",
"",
"——【The Gospel According to Saint John 1】",
"",
"32 约翰又作见证说：「我曾看见圣灵，彷彿鸽子从天降下，住在他的身上。",
"33 我先前不认识他，只是那差我来用水施洗的、对我说：『你看见圣灵降下来，住在谁的身上，谁就是用圣灵施洗的。』",
"34 我看见了，就证明这是　神的儿子。」",
"35 再次日，约翰同两个门徒站在那里。",
"36 他见耶稣行走，就说：「看哪，这是　神的羔羊！」",
"37 两个门徒听见他的话，就跟从了耶稣。",
"",
"——【约翰福音 1】",
],
[
"3 And David went thence to Mizpeh of Moab: and he said unto the king of Moab, Let my father and my mother, I pray thee, come forth, and be with you, till I know what God will do for me.",
"4 And he brought them before the king of Moab: and they dwelt with him all the while that David was in the hold.",
"5 And the prophet Gad said unto David, Abide not in the hold; depart, and get thee into the land of Judah. Then David departed, and came into the forest of Hareth.",
"",
"——【The First Book of Samuel 22】",
"",
"3 大卫从那里往摩押的米斯巴去，对摩押王说：「求你容我父母搬来，住在你们这里，等我知道　神要为我怎样行。」",
"4 大卫领他父母到摩押王面前。大卫住山寨多少日子，他父母也住摩押王那里多少日子。",
"5 先知迦得对大卫说：「你不要住在山寨，要往犹大地去。」大卫就离开那里，进入哈列的树林。",
"",
"——【撒母耳记上 22】",
],
[
"22 He that hasteth to be rich hath an evil eye, and considereth not that poverty shall come upon him.",
"23 He that rebuketh a man afterwards shall find more favour than he that flattereth with the tongue.",
"24 Whoso robbeth his father or his mother, and saith, It is no transgression; the same is the companion of a destroyer.",
"25 He that is of a proud heart stirreth up strife: but he that putteth his trust in the LORD shall be made fat.",
"26 He that trusteth in his own heart is a fool: but whoso walketh wisely, he shall be delivered.",
"27 He that giveth unto the poor shall not lack: but he that hideth his eyes shall have many a curse.",
"",
"——【The Proverbs 28】",
"",
"22 人有恶眼想要急速发财，却不知穷乏必临到他身。",
"23 责备人的，后来蒙人喜悦，多于那用舌头谄媚人的。",
"24 偷窃父母的，说：这不是罪，此人就是与强盗同类。",
"25 心中贪婪的，挑起争端；倚靠耶和华的，必得丰裕。",
"26 心中自是的，便是愚昧人；凭智慧行事的，必蒙拯救。",
"27 赒济贫穷的，不致缺乏；佯为不见的，必多受咒诅。",
"",
"——【箴言 28】",
],
[
"18 Their soul abhorreth all manner of meat; and they draw near unto the gates of death.",
"19 Then they cry unto the LORD in their trouble, and he saveth them out of their distresses.",
"20 He sent his word, and healed them, and delivered them from their destructions.",
"",
"——【The Book of Psalms 107】",
"",
"18 他们心里厌恶各样的食物，就临近死门。",
"19 于是，他们在苦难中哀求耶和华；他从他们的祸患中拯救他们。",
"20 他发命医治他们，救他们脱离死亡。",
"",
"——【诗篇 107】",
],
[
"9 Kings' daughters were among thy honourable women: upon thy right hand did stand the queen in gold of Ophir.",
"10 Hearken, O daughter, and consider, and incline thine ear; forget also thine own people, and thy father's house;",
"11 So shall the king greatly desire thy beauty: for he is thy Lord; and worship thou him.",
"12 And the daughter of Tyre shall be there with a gift; even the rich among the people shall intreat thy favour.",
"13 The king's daughter is all glorious within: her clothing is of wrought gold.",
"",
"——【The Book of Psalms 45】",
"",
"9 有君王的女儿在你尊贵妇女之中；王后佩戴俄斐金饰站在你右边。",
"10 女子啊，你要听，要想，要侧耳而听！不要记念你的民和你的父家，",
"11 王就羨慕你的美貌；因为他是你的主，你当敬拜他。",
"12 推罗的民（原文是女子）必来送礼；民中的富足人也必向你求恩。",
"13 王女在宫里极其荣华；她的衣服是用金线绣的。",
"",
"——【诗篇 45】",
],
[
"26 He shall cry unto me, Thou art my father, my God, and the rock of my salvation.",
"27 Also I will make him my firstborn, higher than the kings of the earth.",
"28 My mercy will I keep for him for evermore, and my covenant shall stand fast with him.",
"29 His seed also will I make to endure for ever, and his throne as the days of heaven.",
"30 If his children forsake my law, and walk not in my judgments;",
"31 If they break my statutes, and keep not my commandments;",
"",
"——【The Book of Psalms 89】",
"",
"26 他要称呼我说：你是我的父，是我的　神，是拯救我的磐石。",
"27 我也要立他为长子，为世上最高的君王。",
"28 我要为他存留我的慈爱，直到永远；我与他立的约必要坚定。",
"29 我也要使他的后裔存到永远，使他的宝座如天之久。",
"30 倘若他的子孙离弃我的律法，不照我的典章行，",
"31 背弃我的律例，不遵守我的诫命，",
"",
"——【诗篇 89】",
],
[
"3 Who also eat the flesh of my people, and flay their skin from off them; and they break their bones, and chop them in pieces, as for the pot, and as flesh within the caldron.",
"4 Then shall they cry unto the LORD, but he will not hear them: he will even hide his face from them at that time, as they have behaved themselves ill in their doings.",
"5 Thus saith the LORD concerning the prophets that make my people err, that bite with their teeth, and cry, Peace; and he that putteth not into their mouths, they even prepare war against him.",
"",
"——【Micah 3】",
"",
"3 吃我民的肉，剥他们的皮，打折他们的骨头，分成块子像要下锅，又像釜中的肉。",
"4 到了遭灾的时候，这些人必哀求耶和华，他却不应允他们。那时他必照他们所行的恶事向他们掩面。",
"5 论到使我民走差路的先知─他们牙齿有所嚼的，他们就呼喊说：平安了！凡不供给他们吃的，他们就预备攻击他（预备攻击他：或译说必遭遇刀兵）─耶和华如此说：",
"",
"——【弥迦书 3】",
],
[
"4 And all the congregation said that they would do so: for the thing was right in the eyes of all the people.",
"5 So David gathered all Israel together, from Shihor of Egypt even unto the entering of Hemath, to bring the ark of God from Kirjath–jearim.",
"",
"——【The First Book of the Chronicles 13】",
"",
"4 全会众都说可以如此行；这事在众民眼中都看为好。",
"5 于是，大卫将以色列人从埃及的西曷河直到哈马口都招聚了来，要从基列‧耶琳将　神的约柜运来。",
"",
"——【历代志上 13】",
],
[
"3 Then they had swallowed us up quick, when their wrath was kindled against us:",
"4 Then the waters had overwhelmed us, the stream had gone over our soul:",
"5 Then the proud waters had gone over our soul.",
"",
"——【The Book of Psalms 124】",
"",
"3 向我们发怒的时候，就把我们活活地吞了。",
"4 那时，波涛必漫过我们，河水必淹没我们，",
"5 狂傲的水必淹没我们。",
"",
"——【诗篇 124】",
],
[
"1 LORD, who shall abide in thy tabernacle? who shall dwell in thy holy hill?",
"2 He that walketh uprightly, and worketh righteousness, and speaketh the truth in his heart.",
"3 He that backbiteth not with his tongue, nor doeth evil to his neighbour, nor taketh up a reproach against his neighbour.",
"4 In whose eyes a vile person is contemned; but he honoureth them that fear the LORD. He that sweareth to his own hurt, and changeth not.",
"",
"——【The Book of Psalms 15】",
"",
"1 （大卫的诗。）耶和华啊，谁能寄居你的帐幕？谁能住在你的圣山？",
"2 就是行为正直、做事公义、心里说实话的人。",
"3 他不以舌头谗谤人，不恶待朋友，也不随伙毁谤邻里。",
"4 他眼中藐视匪类，却尊重那敬畏耶和华的人。他发了誓，虽然自己吃亏也不更改。",
"",
"——【诗篇 15】",
],
[
"1 Except the LORD build the house, they labour in vain that build it: except the LORD keep the city, the watchman waketh but in vain.",
"2 It is vain for you to rise up early, to sit up late, to eat the bread of sorrows: for so he giveth his beloved sleep.",
"3 Lo, children are an heritage of the LORD: and the fruit of the womb is his reward.",
"4 As arrows are in the hand of a mighty man; so are children of the youth.",
"",
"——【The Book of Psalms 127】",
"",
"1 （所罗门上行之诗。）若不是耶和华建造房屋，建造的人就枉然劳力；若不是耶和华看守城池，看守的人就枉然警醒。",
"2 你们清晨早起，夜晚安歇，吃劳碌得来的饭，本是枉然；惟有耶和华所亲爱的，必叫他安然睡觉。",
"3 儿女是耶和华所赐的产业；所怀的胎是他所给的赏赐。",
"4 少年时所生的儿女好像勇士手中的箭。",
"",
"——【诗篇 127】",
],
[
"1 And it came to pass, as he went into the house of one of the chief Pharisees to eat bread on the sabbath day, that they watched him.",
"2 And, behold, there was a certain man before him which had the dropsy.",
"",
"——【The Gospel According to Saint Luke 14】",
"",
"1 安息日，耶稣到一个法利赛人的首领家里去吃饭，他们就窥探他。",
"2 在他面前有一个患水臌的人。",
"",
"——【路加福音 14】",
],
[
"38 Watch ye and pray, lest ye enter into temptation. The spirit truly is ready, but the flesh is weak.",
"39 And again he went away, and prayed, and spake the same words.",
"40 And when he returned, he found them asleep again, (for their eyes were heavy,) neither wist they what to answer him.",
"",
"——【The Gospel According to Saint Mark 14】",
"",
"38 总要儆醒祷告，免得入了迷惑。你们心灵固然愿意，肉体却软弱了。",
"39 耶稣又去祷告，说的话还是与先前一样，",
"40 又来见他们睡著了，因为他们的眼睛甚是困倦；他们也不知道怎么回答。",
"",
"——【马可福音 14】",
],
[
"42 And he commanded us to preach unto the people, and to testify that it is he which was ordained of God to be the Judge of quick and dead.",
"43 To him give all the prophets witness, that through his name whosoever believeth in him shall receive remission of sins.",
"44 While Peter yet spake these words, the Holy Ghost fell on all them which heard the word.",
"45 And they of the circumcision which believed were astonished, as many as came with Peter, because that on the Gentiles also was poured out the gift of the Holy Ghost.",
"46 For they heard them speak with tongues, and magnify God. Then answered Peter,",
"47 Can any man forbid water, that these should not be baptized, which have received the Holy Ghost as well as we?",
"",
"——【The Acts of the Apostles 10】",
"",
"42 他吩咐我们传道给众人，证明他是　神所立定的，要作审判活人、死人的主。",
"43 众先知也为他作见证说：凡信他的人必因他的名得蒙赦罪。",
"44 彼得还说这话的时候，圣灵降在一切听道的人身上。",
"45 那些奉割礼、和彼得同来的信徒，见圣灵的恩赐也浇在外邦人身上，就都希奇；",
"46 因听见他们说方言，称讚　神为大。",
"47 于是彼得说：这些人既受了圣灵，与我们一样，谁能禁止用水给他们施洗呢？",
"",
"——【使徒行传 10】",
],
[
"2 Sing forth the honour of his name: make his praise glorious.",
"3 Say unto God, How terrible art thou in thy works! through the greatness of thy power shall thine enemies submit themselves unto thee.",
"",
"——【The Book of Psalms 66】",
"",
"2 歌颂他名的荣耀！用讚美的言语将他的荣耀发明！",
"3 当对　神说：你的作为何等可畏！因你的大能，仇敌要投降你。",
"",
"——【诗篇 66】",
],
[
"1 I will extol thee, my God, O king; and I will bless thy name for ever and ever.",
"2 Every day will I bless thee; and I will praise thy name for ever and ever.",
"3 Great is the LORD, and greatly to be praised; and his greatness is unsearchable.",
"4 One generation shall praise thy works to another, and shall declare thy mighty acts.",
"5 I will speak of the glorious honour of thy majesty, and of thy wondrous works.",
"6 And men shall speak of the might of thy terrible acts: and I will declare thy greatness.",
"",
"——【The Book of Psalms 145】",
"",
"1 （大卫的讚美诗。）我的　神我的王啊，我要尊崇你！我要永永远远称颂你的名！",
"2 我要天天称颂你，也要永永远远讚美你的名！",
"3 耶和华本为大，该受大讚美；其大无法测度。",
"4 这代要对那代颂讚你的作为，也要传扬你的大能。",
"5 我要默念你威严的尊荣和你奇妙的作为。",
"6 人要传说你可畏之事的能力；我也要传扬你的大德。",
"",
"——【诗篇 145】",
],
[
"11 And I will punish the world for their evil, and the wicked for their iniquity; and I will cause the arrogancy of the proud to cease, and will lay low the haughtiness of the terrible.",
"12 I will make a man more precious than fine gold; even a man than the golden wedge of Ophir.",
"",
"——【The Book of the Prophet Isaiah 13】",
"",
"11 我必因邪恶刑罚世界，因罪孽刑罚恶人，使骄傲人的狂妄止息，制伏强暴人的狂傲。",
"12 我必使人比精金还少，使人比俄斐纯金更少。",
"",
"——【以赛亚书 13】",
],
[
"7 And they said every one to his fellow, Come, and let us cast lots, that we may know for whose cause this evil is upon us. So they cast lots, and the lot fell upon Jonah.",
"8 Then said they unto him, Tell us, we pray thee, for whose cause this evil is upon us; What is thine occupation? and whence comest thou? what is thy country? and of what people art thou?",
"9 And he said unto them, I am an Hebrew; and I fear the LORD, the God of heaven, which hath made the sea and the dry land.",
"10 Then were the men exceedingly afraid, and said unto him, Why hast thou done this? For the men knew that he fled from the presence of the LORD, because he had told them.",
"",
"——【Jonah 1】",
"",
"7 船上的人彼此说：「来吧，我们掣籤，看看这灾临到我们是因谁的缘故。」于是他们掣籤，掣出约拿来。",
"8 众人对他说：「请你告诉我们，这灾临到我们是因谁的缘故？你以何事为业？你从哪里来？你是哪一国？属哪一族的人？」",
"9 他说：「我是希伯来人。我敬畏耶和华─那创造沧海旱地之天上的　神。」",
"10 他们就大大惧怕，对他说：「你做的是什么事呢？」他们已经知道他躲避耶和华，因为他告诉了他们。",
"",
"——【约拿书 1】",
],
[
"11 And he said, A certain man had two sons:",
"12 And the younger of them said to his father, Father, give me the portion of goods that falleth to me. And he divided unto them his living.",
"13 And not many days after the younger son gathered all together, and took his journey into a far country, and there wasted his substance with riotous living.",
"14 And when he had spent all, there arose a mighty famine in that land; and he began to be in want.",
"",
"——【The Gospel According to Saint Luke 15】",
"",
"11 耶稣又说：一个人有两个儿子。",
"12 小儿子对父亲说：父亲，请你把我应得的家业分给我。他父亲就把产业分给他们。",
"13 过了不多几日，小儿子就把他一切所有的都收拾起来，往远方去了。在那里任意放荡，浪费赀财。",
"14 既耗尽了一切所有的，又遇著那地方大遭饥荒，就穷苦起来。",
"",
"——【路加福音 15】",
],
[
"7 And there are gathered unto him vain men, the children of Belial, and have strengthened themselves against Rehoboam the son of Solomon, when Rehoboam was young and tenderhearted, and could not withstand them.",
"8 And now ye think to withstand the kingdom of the LORD in the hand of the sons of David; and ye be a great multitude, and there are with you golden calves, which Jeroboam made you for gods.",
"9 Have ye not cast out the priests of the LORD, the sons of Aaron, and the Levites, and have made you priests after the manner of the nations of other lands? so that whosoever cometh to consecrate himself with a young bullock and seven rams, the same may be a priest of them that are no gods.",
"",
"——【The Second Book of the Chronicles 13】",
"",
"7 有些无赖的匪徒聚集跟从他，逞强攻击所罗门的儿子罗波安；那时罗波安还幼弱，不能抵挡他们。",
"8 现在你们有意抗拒大卫子孙手下所治耶和华的国，你们的人也甚多，你们那里又有耶罗波安为你们所造当作神的金牛犊。",
"9 你们不是驱逐耶和华的祭司亚伦的后裔和利未人吗？不是照著外邦人的恶俗为自己立祭司吗？无论何人牵一只公牛犊、七只公绵羊将自己分别出来，就可作虚无之神的祭司。",
"",
"——【历代志下 13】",
],
[
"7 Beareth all things, believeth all things, hopeth all things, endureth all things.",
"8 Charity never faileth: but whether there be prophecies, they shall fail; whether there be tongues, they shall cease; whether there be knowledge, it shall vanish away.",
"9 For we know in part, and we prophesy in part.",
"10 But when that which is perfect is come, then that which is in part shall be done away.",
"11 When I was a child, I spake as a child, I understood as a child, I thought as a child: but when I became a man, I put away childish things.",
"12 For now we see through a glass, darkly; but then face to face: now I know in part; but then shall I know even as also I am known.",
"",
"——【The First Epistle of Paul the Apostle to the Corinthians 13】",
"",
"7 凡事包容，凡事相信，凡事盼望，凡事忍耐。",
"8 爱是永不止息。先知讲道之能终必归于无有；说方言之能终必停止；知识也终必归于无有。",
"9 我们现在所知道的有限，先知所讲的也有限，",
"10 等那完全的来到，这有限的必归于无有了。",
"11 我作孩子的时候，话语像孩子，心思像孩子，意念像孩子，既成了人，就把孩子的事丢弃了。",
"12 我们如今彷彿对著镜子观看，糢糊不清（原文作：如同猜谜）；到那时就要面对面了。我如今所知道的有限，到那时就全知道，如同主知道我一样。",
"",
"——【哥林多前书 13】",
],
[
"5 For he established a testimony in Jacob, and appointed a law in Israel, which he commanded our fathers, that they should make them known to their children:",
"6 That the generation to come might know them, even the children which should be born; who should arise and declare them to their children:",
"7 That they might set their hope in God, and not forget the works of God, but keep his commandments:",
"",
"——【The Book of Psalms 78】",
"",
"5 因为，他在雅各中立法度，在以色列中设律法；是他吩咐我们祖宗要传给子孙的，",
"6 使将要生的后代子孙可以晓得；他们也要起来告诉他们的子孙，",
"7 好叫他们仰望　神，不忘记　神的作为，惟要守他的命令。",
"",
"——【诗篇 78】",
],
[
"21 And the LORD shall separate him unto evil out of all the tribes of Israel, according to all the curses of the covenant that are written in this book of the law:",
"22 So that the generation to come of your children that shall rise up after you, and the stranger that shall come from a far land, shall say, when they see the plagues of that land, and the sicknesses which the LORD hath laid upon it;",
"23 And that the whole land thereof is brimstone, and salt, and burning, that it is not sown, nor beareth, nor any grass groweth therein, like the overthrow of Sodom, and Gomorrah, Admah, and Zeboim, which the LORD overthrew in his anger, and in his wrath:",
"24 Even all nations shall say, Wherefore hath the LORD done thus unto this land? what meaneth the heat of this great anger?",
"25 Then men shall say, Because they have forsaken the covenant of the LORD God of their fathers, which he made with them when he brought them forth out of the land of Egypt:",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 29】",
"",
"21 也必照著写在律法书上、约中的一切咒诅将他从以色列众支派中分别出来，使他受祸。",
"22 你们的后代，就是以后兴起来的子孙，和远方来的外人，看见这地的灾殃，并耶和华所降与这地的疾病，",
"23 又看见遍地有硫磺，有盐卤，有火迹，没有耕种，没有出产，连草都不生长─好像耶和华在忿怒中所倾覆的所多玛、蛾摩拉、押玛、洗扁一样─",
"24 所看见的人，连万国人，都必问说：『耶和华为何向此地这样行呢？这样大发烈怒是什么意思呢？』",
"25 人必回答说：『是因这地的人离弃了耶和华─他们列祖的　神，领他们出埃及地的时候与他们所立的约，",
"",
"——【申命记 29】",
],
[
"2 For the truth's sake, which dwelleth in us, and shall be with us for ever.",
"3 Grace be with you, mercy, and peace, from God the Father, and from the Lord Jesus Christ, the Son of the Father, in truth and love.",
"4 I rejoiced greatly that I found of thy children walking in truth, as we have received a commandment from the Father.",
"5 And now I beseech thee, lady, not as though I wrote a new commandment unto thee, but that which we had from the beginning, that we love one another.",
"6 And this is love, that we walk after his commandments. This is the commandment, That, as ye have heard from the beginning, ye should walk in it.",
"",
"——【The Second Epistle General of John 1】",
"",
"2 爱你们是为真理的缘故，这真理存在我们里面，也必永远与我们同在。",
"3 恩惠，怜悯，平安从父　神和他儿子耶稣基督在真理和爱心上必常与我们同在！",
"4 我见你的儿女，有照我们从父所受之命令遵行真理的，就甚欢喜。",
"5 太太啊，我现在劝你，我们大家要彼此相爱。这并不是我写一条新命令给你，乃是我们从起初所受的命令。",
"6 我们若照他的命令行，这就是爱。你们从起初所听见当行的，就是这命令。",
"",
"——【约翰二书 1】",
],
[
"3 Blow up the trumpet in the new moon, in the time appointed, on our solemn feast day.",
"4 For this was a statute for Israel, and a law of the God of Jacob.",
"5 This he ordained in Joseph for a testimony, when he went out through the land of Egypt: where I heard a language that I understood not.",
"6 I removed his shoulder from the burden: his hands were delivered from the pots.",
"7 Thou calledst in trouble, and I delivered thee; I answered thee in the secret place of thunder: I proved thee at the waters of Meribah. Selah.",
"",
"——【The Book of Psalms 81】",
"",
"3 当在月朔并月望─我们过节的日期吹角，",
"4 因这是为以色列定的律例，是雅各　神的典章。",
"5 他去攻击埃及地的时候，在约瑟中间立此为证。我在那里听见我所不明白的言语：",
"6 　神说：我使你的肩得脱重担，你的手放下筐子。",
"7 你在急难中呼求，我就搭救你；我在雷的隐密处应允你，在米利巴水那里试验你。（细拉）",
"",
"——【诗篇 81】",
],
[
"1 The LORD reigneth; let the people tremble: he sitteth between the cherubims; let the earth be moved.",
"2 The LORD is great in Zion; and he is high above all the people.",
"3 Let them praise thy great and terrible name; for it is holy.",
"4 The king's strength also loveth judgment; thou dost establish equity, thou executest judgment and righteousness in Jacob.",
"",
"——【The Book of Psalms 99】",
"",
"1 耶和华作王；万民当战抖！他坐在二基路伯上，地当动摇。",
"2 耶和华在锡安为大；他超乎万民之上。",
"3 他们当称讚他大而可畏的名；他本为圣！",
"4 王有能力，喜爱公平，坚立公正，在雅各中施行公平和公义。",
"",
"——【诗篇 99】",
],
[
"1 Now it came to pass in the days when the judges ruled, that there was a famine in the land. And a certain man of Beth–lehem–judah went to sojourn in the country of Moab, he, and his wife, and his two sons.",
"2 And the name of the man was Elimelech, and the name of his wife Naomi, and the name of his two sons Mahlon and Chilion, Ephrathites of Beth–lehem–judah. And they came into the country of Moab, and continued there.",
"3 And Elimelech Naomi's husband died; and she was left, and her two sons.",
"4 And they took them wives of the women of Moab; the name of the one was Orpah, and the name of the other Ruth: and they dwelled there about ten years.",
"5 And Mahlon and Chilion died also both of them; and the woman was left of her two sons and her husband.",
"",
"——【The Book of Ruth 1】",
"",
"1 当士师秉政的时候，国中遭遇饥荒。在犹大、伯利恒，有一个人带著妻子和两个儿子往摩押地去寄居。",
"2 这人名叫以利米勒，他的妻名叫拿俄米；他两个儿子，一个名叫玛伦，一个名叫基连，都是犹大的伯利恒的以法他人。他们到了摩押地，就住在那里。",
"3 后来拿俄米的丈夫以利米勒死了，剩下妇人和她两个儿子。",
"4 这两个儿子娶了摩押女子为妻，一个名叫俄珥巴，一个名叫路得，在那里住了约有十年。",
"5 玛伦和基连二人也死了，剩下拿俄米，没有丈夫，也没有儿子。",
"",
"——【路得记 1】",
],
[
"7 He overlaid also the house, the beams, the posts, and the walls thereof, and the doors thereof, with gold; and graved cherubims on the walls.",
"8 And he made the most holy house, the length whereof was according to the breadth of the house, twenty cubits, and the breadth thereof twenty cubits: and he overlaid it with fine gold, amounting to six hundred talents.",
"9 And the weight of the nails was fifty shekels of gold. And he overlaid the upper chambers with gold.",
"10 And in the most holy house he made two cherubims of image work, and overlaid them with gold.",
"",
"——【The Second Book of the Chronicles 3】",
"",
"7 又用金子贴殿和殿的栋梁、门槛、墙壁、门扇；墙上雕刻基路伯。",
"8 又建造至圣所，长二十肘，与殿的宽窄一样，宽也是二十肘；贴上精金，共用金子六百他连得。",
"9 金钉重五十舍客勒。楼房都贴上金子。",
"10 在至圣所按造像的法子造两个基路伯，用金子包裹。",
"",
"——【历代志下 3】",
],
[
"13 And I gave my heart to seek and search out by wisdom concerning all things that are done under heaven: this sore travail hath God given to the sons of man to be exercised therewith.",
"14 I have seen all the works that are done under the sun; and, behold, all is vanity and vexation of spirit.",
"",
"——【Ecclesiastes 1】",
"",
"13 我专心用智慧寻求、查究天下所做的一切事，乃知　神叫世人所经练的是极重的劳苦。",
"14 我见日光之下所做的一切事，都是虚空，都是捕风。",
"",
"——【传道书 1】",
],
[
"1 Say ye unto your brethren, Ammi; and to your sisters, Ru–hamah.",
"2 Plead with your mother, plead: for she is not my wife, neither am I her husband: let her therefore put away her whoredoms out of her sight, and her adulteries from between her breasts;",
"3 Lest I strip her naked, and set her as in the day that she was born, and make her as a wilderness, and set her like a dry land, and slay her with thirst.",
"",
"——【Hosea 2】",
"",
"1 你们要称你们的弟兄为阿米（就是我民的意思），称你们的姊妹为路哈玛（就是蒙怜悯的意思）。",
"2 你们要与你们的母亲大大争辩；因为她不是我的妻子，我也不是她的丈夫。叫她除掉脸上的淫像和胸间的淫态，",
"3 免得我剥她的衣服，使她赤体，与才生的时候一样，使她如旷野，如干旱之地，因渴而死。",
"",
"——【何西阿书 2】",
],
];
