var bible31_global=[
[
"1 And the LORD spake unto Moses, saying,",
"2 Speak unto Aaron, and unto his sons, and unto all the children of Israel, and say unto them; This is the thing which the LORD hath commanded, saying,",
"3 What man soever there be of the house of Israel, that killeth an ox, or lamb, or goat, in the camp, or that killeth it out of the camp,",
"4 And bringeth it not unto the door of the tabernacle of the congregation, to offer an offering unto the LORD before the tabernacle of the LORD; blood shall be imputed unto that man; he hath shed blood; and that man shall be cut off from among his people:",
"5 To the end that the children of Israel may bring their sacrifices, which they offer in the open field, even that they may bring them unto the LORD, unto the door of the tabernacle of the congregation, unto the priest, and offer them for peace offerings unto the LORD.",
"",
"——【The Third Book of Moses: Called Leviticus 17】",
"",
"1 耶和华对摩西说：",
"2 「你晓谕亚伦和他儿子并以色列众人说，耶和华所吩咐的乃是这样：",
"3 凡以色列家中的人宰公牛，或是绵羊羔，或是山羊，不拘宰于营内营外，",
"4 若未曾牵到会幕门口、耶和华的帐幕前献给耶和华为供物，流血的罪必归到那人身上。他流了血，要从民中剪除。",
"5 这是为要使以色列人把他们在田野里所献的祭带到会幕门口、耶和华面前，交给祭司，献与耶和华为平安祭。",
"",
"——【利未记 17】",
],
[
"1 Thus saith the LORD, Where is the bill of your mother's divorcement, whom I have put away? or which of my creditors is it to whom I have sold you? Behold, for your iniquities have ye sold yourselves, and for your transgressions is your mother put away.",
"2 Wherefore, when I came, was there no man? when I called, was there none to answer? Is my hand shortened at all, that it cannot redeem? or have I no power to deliver? behold, at my rebuke I dry up the sea, I make the rivers a wilderness: their fish stinketh, because there is no water, and dieth for thirst.",
"3 I clothe the heavens with blackness, and I make sackcloth their covering.",
"4 The Lord GOD hath given me the tongue of the learned, that I should know how to speak a word in season to him that is weary: he wakeneth morning by morning, he wakeneth mine ear to hear as the learned.",
"5 The Lord GOD hath opened mine ear, and I was not rebellious, neither turned away back.",
"",
"——【The Book of the Prophet Isaiah 50】",
"",
"1 耶和华如此说：我休你们的母亲，休书在哪里呢？我将你们卖给我哪一个债主呢？你们被卖，是因你们的罪孽；你们的母亲被休，是因你们的过犯。",
"2 我来的时候，为何无人等候呢？我呼唤的时候，为何无人答应呢？我的膀臂岂是缩短、不能救赎吗？我岂无拯救之力吗？看哪，我一斥责，海就干了；我使江河变为旷野；其中的鱼因无水腥臭，干渴而死。",
"3 我使诸天以黑暗为衣服，以麻布为遮盖。",
"4 主耶和华赐我受教者的舌头，使我知道怎样用言语扶助疲乏的人。主每早晨提醒，提醒我的耳朵，使我能听，像受教者一样。",
"5 主耶和华开通我的耳朵；我并没有违背，也没有退后。",
"",
"——【以赛亚书 50】",
],
[
"3 Then said the princes of the Philistines, What do these Hebrews here? And Achish said unto the princes of the Philistines, Is not this David, the servant of Saul the king of Israel, which hath been with me these days, or these years, and I have found no fault in him since he fell unto me unto this day?",
"4 And the princes of the Philistines were wroth with him; and the princes of the Philistines said unto him, Make this fellow return, that he may go again to his place which thou hast appointed him, and let him not go down with us to battle, lest in the battle he be an adversary to us: for wherewith should he reconcile himself unto his master? should it not be with the heads of these men?",
"5 Is not this David, of whom they sang one to another in dances, saying, Saul slew his thousands, and David his ten thousands?",
"6 Then Achish called David, and said unto him, Surely, as the LORD liveth, thou hast been upright, and thy going out and thy coming in with me in the host is good in my sight: for I have not found evil in thee since the day of thy coming unto me unto this day: nevertheless the lords favour thee not.",
"7 Wherefore now return, and go in peace, that thou displease not the lords of the Philistines.",
"",
"——【The First Book of Samuel 29】",
"",
"3 非利士人的首领说：「这些希伯来人在这里做什么呢？」亚吉对他们说：「这不是以色列王扫罗的臣子大卫么？他在我这里有些年日了。自从他投降我直到今日，我未曾见他有过错。」",
"4 非利士人的首领向亚吉发怒，对他说：「你要叫这人回你所安置他的地方，不可叫他同我们出战，恐怕他在阵上反为我们的敌人。他用什么与他主人复和呢？岂不是用我们这些人的首级么？",
"5 从前以色列的妇女跳舞唱和说：『扫罗杀死千千，大卫杀死万万』，所说的不是这个大卫吗？」",
"6 亚吉叫大卫来，对他说：「我指著永生的耶和华起誓，你是正直人。你随我在军中出入，我看你甚好。自从你投奔我到如今，我未曾见你有什么过失；只是众首领不喜悦你。",
"7 现在你可以平平安安地回去，免得非利士人的首领不欢喜你。」",
"",
"——【撒母耳记上 29】",
],
[
"7 And he knew their desolate palaces, and he laid waste their cities; and the land was desolate, and the fulness thereof, by the noise of his roaring.",
"8 Then the nations set against him on every side from the provinces, and spread their net over him: he was taken in their pit.",
"9 And they put him in ward in chains, and brought him to the king of Babylon: they brought him into holds, that his voice should no more be heard upon the mountains of Israel.",
"",
"——【The Book of the Prophet Ezekiel 19】",
"",
"7 他知道列国的宫殿，又使他们的城邑变为荒场；因他咆哮的声音，遍地和其中所有的就都荒废。",
"8 于是四围邦国各省的人来攻击他，将网撒在他身上，捉在他们的坑中。",
"9 他们用钩子钩住他，将他放在笼中，带到巴比伦王那里，将他放入坚固之所，使他的声音在以色列山上不再听见。",
"",
"——【以西结书 19】",
],
[
"36 Seven days ye shall offer an offering made by fire unto the LORD: on the eighth day shall be an holy convocation unto you; and ye shall offer an offering made by fire unto the LORD: it is a solemn assembly; and ye shall do no servile work therein.",
"37 These are the feasts of the LORD, which ye shall proclaim to be holy convocations, to offer an offering made by fire unto the LORD, a burnt offering, and a meat offering, a sacrifice, and drink offerings, every thing upon his day:",
"38 Beside the sabbaths of the LORD, and beside your gifts, and beside all your vows, and beside all your freewill offerings, which ye give unto the LORD.",
"39 Also in the fifteenth day of the seventh month, when ye have gathered in the fruit of the land, ye shall keep a feast unto the LORD seven days: on the first day shall be a sabbath, and on the eighth day shall be a sabbath.",
"40 And ye shall take you on the first day the boughs of goodly trees, branches of palm trees, and the boughs of thick trees, and willows of the brook; and ye shall rejoice before the LORD your God seven days.",
"41 And ye shall keep it a feast unto the LORD seven days in the year. It shall be a statute for ever in your generations: ye shall celebrate it in the seventh month.",
"",
"——【The Third Book of Moses: Called Leviticus 23】",
"",
"36 七日内要将火祭献给耶和华。第八日当守圣会，要将火祭献给耶和华。这是严肃会，什么劳碌的工都不可做。",
"37 「这是耶和华的节期，就是你们要宣告为圣会的节期；要将火祭、燔祭、素祭、祭物，并奠祭，各归各日，献给耶和华。",
"38 这是在耶和华的安息日以外，又在你们的供物和所许的愿，并甘心献给耶和华的以外。",
"39 「你们收藏了地的出产，就从七月十五日起，要守耶和华的节七日。第一日为圣安息；第八日也为圣安息。",
"40 第一日要拿美好树上的果子和棕树上的枝子，与茂密树的枝条并河旁的柳枝，在耶和华─你们的　神面前欢乐七日。",
"41 每年七月间，要向耶和华守这节七日。这为你们世世代代永远的定例。",
"",
"——【利未记 23】",
],
[
"8 And I will sell your sons and your daughters into the hand of the children of Judah, and they shall sell them to the Sabeans, to a people far off: for the LORD hath spoken it.",
"9 Proclaim ye this among the Gentiles; Prepare war, wake up the mighty men, let all the men of war draw near; let them come up:",
"",
"——【Joel 3】",
"",
"8 我必将你们的儿女卖在犹大人的手中，他们必卖给远方示巴国的人。这是耶和华说的。」",
"9 当在万民中宣告说：要预备打仗；激动勇士，使一切战士上前来。",
"",
"——【约珥书 3】",
],
[
"1 Then I turned, and lifted up mine eyes, and looked, and behold a flying roll.",
"2 And he said unto me, What seest thou? And I answered, I see a flying roll; the length thereof is twenty cubits, and the breadth thereof ten cubits.",
"",
"——【Zechariah 5】",
"",
"1 我又举目观看，见有一飞行书卷。",
"2 他问我说：「你看见什么？」我回答说：「我看见一飞行的书卷，长二十肘，宽十肘。」",
"",
"——【撒迦利亚书 5】",
],
[
"30 And Pharaoh rose up in the night, he, and all his servants, and all the Egyptians; and there was a great cry in Egypt; for there was not a house where there was not one dead.",
"31 And he called for Moses and Aaron by night, and said, Rise up, and get you forth from among my people, both ye and the children of Israel; and go, serve the LORD, as ye have said.",
"32 Also take your flocks and your herds, as ye have said, and be gone; and bless me also.",
"33 And the Egyptians were urgent upon the people, that they might send them out of the land in haste; for they said, We be all dead men.",
"",
"——【The Second Book of Moses: Called Exodus 12】",
"",
"30 法老和一切臣仆，并埃及众人，夜间都起来了。在埃及有大哀号，无一家不死一个人的。",
"31 夜间，法老召了摩西、亚伦来，说：「起来！连你们带以色列人，从我民中出去，依你们所说的，去事奉耶和华吧！",
"32 也依你们所说的，连羊群牛群带著走吧！并要为我祝福。」",
"33 埃及人催促百姓，打发他们快快出离那地，因为埃及人说：「我们都要死了。」",
"",
"——【出埃及记 12】",
],
[
"8 Ephraim, he hath mixed himself among the people; Ephraim is a cake not turned.",
"9 Strangers have devoured his strength, and he knoweth it not: yea, gray hairs are here and there upon him, yet he knoweth not.",
"10 And the pride of Israel testifieth to his face: and they do not return to the LORD their God, nor seek him for all this.",
"11 Ephraim also is like a silly dove without heart: they call to Egypt, they go to Assyria.",
"12 When they shall go, I will spread my net upon them; I will bring them down as the fowls of the heaven; I will chastise them, as their congregation hath heard.",
"13 Woe unto them! for they have fled from me: destruction unto them! because they have transgressed against me: though I have redeemed them, yet they have spoken lies against me.",
"",
"——【Hosea 7】",
"",
"8 以法莲与列邦人搀杂；以法莲是没有翻过的饼。",
"9 外邦人吞吃他劳力得来的，他却不知道；头发斑白，他也不觉得。",
"10 以色列的骄傲当面见证自己，虽遭遇这一切，他们仍不归向耶和华─他们的　神，也不寻求他。",
"11 以法莲好像鸽子愚蠢无知；他们求告埃及，投奔亚述。",
"12 他们去的时候，我必将我的网撒在他们身上；我要打下他们，如同空中的鸟。我必按他们会众所听见的惩罚他们。",
"13 他们因离弃我，必定有祸；因违背我，必被毁灭。我虽要救赎他们，他们却向我说谎。",
"",
"——【何西阿书 7】",
],
[
"7 He overlaid also the house, the beams, the posts, and the walls thereof, and the doors thereof, with gold; and graved cherubims on the walls.",
"8 And he made the most holy house, the length whereof was according to the breadth of the house, twenty cubits, and the breadth thereof twenty cubits: and he overlaid it with fine gold, amounting to six hundred talents.",
"9 And the weight of the nails was fifty shekels of gold. And he overlaid the upper chambers with gold.",
"",
"——【The Second Book of the Chronicles 3】",
"",
"7 又用金子贴殿和殿的栋梁、门槛、墙壁、门扇；墙上雕刻基路伯。",
"8 又建造至圣所，长二十肘，与殿的宽窄一样，宽也是二十肘；贴上精金，共用金子六百他连得。",
"9 金钉重五十舍客勒。楼房都贴上金子。",
"",
"——【历代志下 3】",
],
[
"34 Then shall the King say unto them on his right hand, Come, ye blessed of my Father, inherit the kingdom prepared for you from the foundation of the world:",
"35 For I was an hungred, and ye gave me meat: I was thirsty, and ye gave me drink: I was a stranger, and ye took me in:",
"36 Naked, and ye clothed me: I was sick, and ye visited me: I was in prison, and ye came unto me.",
"37 Then shall the righteous answer him, saying, Lord, when saw we thee an hungred, and fed thee? or thirsty, and gave thee drink?",
"38 When saw we thee a stranger, and took thee in? or naked, and clothed thee?",
"",
"——【The Gospel According to Saint Matthew 25】",
"",
"34 于是王要向那右边的说：你们这蒙我父赐福的，可来承受那创世以来为你们所预备的国；",
"35 因为我饿了，你们给我吃，渴了，你们给我喝；我作客旅，你们留我住；",
"36 我赤身露体，你们给我穿；我病了、你们看顾我；我在监里，你们来看我。",
"37 义人就回答说：主啊，我们什么时候见你饿了，给你吃，渴了，给你喝？",
"38 什么时候见你作客旅，留你住，或是赤身露体，给你穿？",
"",
"——【马太福音 25】",
],
[
"1 Then all the people of Judah took Uzziah, who was sixteen years old, and made him king in the room of his father Amaziah.",
"2 He built Eloth, and restored it to Judah, after that the king slept with his fathers.",
"3 Sixteen years old was Uzziah when he began to reign, and he reigned fifty and two years in Jerusalem. His mother's name also was Jecoliah of Jerusalem.",
"4 And he did that which was right in the sight of the LORD, according to all that his father Amaziah did.",
"5 And he sought God in the days of Zechariah, who had understanding in the visions of God: and as long as he sought the LORD, God made him to prosper.",
"",
"——【The Second Book of the Chronicles 26】",
"",
"1 犹大众民立亚玛谢的儿子乌西雅【又名亚撒利雅】接续他父作王，那时他年十六岁。",
"2 〈亚玛谢与他列祖同睡之后，乌西雅收回以禄仍归犹大，又重新修理。〉",
"3 乌西雅登基的时候年十六岁，在耶路撒冷作王五十二年。他母亲名叫耶可利雅，是耶路撒冷人。",
"4 乌西雅行耶和华眼中看为正的事，效法他父亚玛谢一切所行的；",
"5 通晓　神默示，撒迦利亚在世的时候，乌西雅定意寻求　神；他寻求耶和华，　神就使他亨通。",
"",
"——【历代志下 26】",
],
[
"7 For the LORD thy God bringeth thee into a good land, a land of brooks of water, of fountains and depths that spring out of valleys and hills;",
"8 A land of wheat, and barley, and vines, and fig trees, and pomegranates; a land of oil olive, and honey;",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 8】",
"",
"7 因为耶和华─你　神领你进入美地，那地有河，有泉，有源，从山谷中流出水来。",
"8 那地有小麦、大麦、葡萄树、无花果树、石榴树、橄榄树，和蜜。",
"",
"——【申命记 8】",
],
[
"1 My brethren, have not the faith of our Lord Jesus Christ, the Lord of glory, with respect of persons.",
"2 For if there come unto your assembly a man with a gold ring, in goodly apparel, and there come in also a poor man in vile raiment;",
"3 And ye have respect to him that weareth the gay clothing, and say unto him, Sit thou here in a good place; and say to the poor, Stand thou there, or sit here under my footstool:",
"4 Are ye not then partial in yourselves, and are become judges of evil thoughts?",
"",
"——【The General Epistle of James 2】",
"",
"1 我的弟兄们，你们信奉我们荣耀的主耶稣基督，便不可按著外貌待人。",
"2 若有一个人带著金戒指，穿著华美衣服，进你们的会堂去；又有一个穷人穿著肮脏衣服也进去；",
"3 你们就重看那穿华美衣服的人，说「请坐在这好位上」；又对那穷人说：「你站在那里」，或「坐在我脚凳下边。」",
"4 这岂不是你们偏心待人，用恶意断定人吗？",
"",
"——【雅各书 2】",
],
[
"20 I cry unto thee, and thou dost not hear me: I stand up, and thou regardest me not.",
"21 Thou art become cruel to me: with thy strong hand thou opposest thyself against me.",
"22 Thou liftest me up to the wind; thou causest me to ride upon it, and dissolvest my substance.",
"23 For I know that thou wilt bring me to death, and to the house appointed for all living.",
"24 Howbeit he will not stretch out his hand to the grave, though they cry in his destruction.",
"",
"——【The Book of Job 30】",
"",
"20 主啊，我呼求你，你不应允我；我站起来，你就定睛看我。",
"21 你向我变心，待我残忍，又用大能追逼我，",
"22 把我提在风中，使我驾风而行，又使我消灭在烈风中。",
"23 我知道要使我临到死地，到那为众生所定的阴宅。",
"24 然而，人仆倒岂不伸手？遇灾难岂不求救呢？",
"",
"——【约伯记 30】",
],
[
"27 Fulfil her week, and we will give thee this also for the service which thou shalt serve with me yet seven other years.",
"28 And Jacob did so, and fulfilled her week: and he gave him Rachel his daughter to wife also.",
"29 And Laban gave to Rachel his daughter Bilhah his handmaid to be her maid.",
"",
"——【The First Book of Moses: Called Genesis 29】",
"",
"27 你为这个满了七日，我就把那个也给你，你再为她服事我七年。」",
"28 雅各就如此行。满了利亚的七日，拉班便将女儿拉结给雅各为妻。",
"29 拉班又将婢女辟拉给女儿拉结作使女。",
"",
"——【创世记 29】",
],
[
"1 And when the day of Pentecost was fully come, they were all with one accord in one place.",
"2 And suddenly there came a sound from heaven as of a rushing mighty wind, and it filled all the house where they were sitting.",
"",
"——【The Acts of the Apostles 2】",
"",
"1 五旬节到了，门徒都聚集在一处。",
"2 忽然，从天上有响声下来，好像一阵大风吹过，充满了他们所坐的屋子，",
"",
"——【使徒行传 2】",
],
[
"1 I am come into my garden, my sister, my spouse: I have gathered my myrrh with my spice; I have eaten my honeycomb with my honey; I have drunk my wine with my milk: eat, O friends; drink, yea, drink abundantly, O beloved.",
"2 I sleep, but my heart waketh: it is the voice of my beloved that knocketh, saying, Open to me, my sister, my love, my dove, my undefiled: for my head is filled with dew, and my locks with the drops of the night.",
"3 I have put off my coat; how shall I put it on? I have washed my feet; how shall I defile them?",
"4 My beloved put in his hand by the hole of the door, and my bowels were moved for him.",
"5 I rose up to open to my beloved; and my hands dropped with myrrh, and my fingers with sweet smelling myrrh, upon the handles of the lock.",
"",
"——【The Song of Solomon 5】",
"",
"1 我妹子，我新妇，我进了我的园中，采了我的没药和香料，吃了我的蜜房和蜂蜜，喝了我的酒和奶。我的朋友们，请吃！我所亲爱的，请喝，且多多地喝！",
"2 我身睡卧，我心却醒。这是我良人的声音；他敲门说：我的妹子，我的佳偶，我的鸽子，我的完全人，求你给我开门；因我的头满了露水，我的头发被夜露滴湿。",
"3 我回答说：我脱了衣裳，怎能再穿上呢？我洗了脚，怎能再玷污呢？",
"4 我的良人从门孔里伸进手来，我便因他动了心。",
"5 我起来，要给我良人开门。我的两手滴下没药；我的指头有没药汁滴在门闩上。",
"",
"——【雅歌 5】",
],
[
"29 Then Joshua passed from Makkedah, and all Israel with him, unto Libnah, and fought against Libnah:",
"30 And the LORD delivered it also, and the king thereof, into the hand of Israel; and he smote it with the edge of the sword, and all the souls that were therein; he let none remain in it; but did unto the king thereof as he did unto the king of Jericho.",
"31 And Joshua passed from Libnah, and all Israel with him, unto Lachish, and encamped against it, and fought against it:",
"",
"——【The Book of Joshua 10】",
"",
"29 约书亚和以色列众人从玛基大往立拿去，攻打立拿。",
"30 耶和华将立拿和立拿的王也交在以色列人手里。约书亚攻打这城，用刀击杀了城中的一切人口，没有留下一个。他待立拿王，像从前待耶利哥王一样。",
"31 约书亚和以色列众人从立拿往拉吉去，对著拉吉安营，攻打这城。",
"",
"——【约书亚记 10】",
],
[
"13 Be of good courage, and let us behave ourselves valiantly for our people, and for the cities of our God: and let the LORD do that which is good in his sight.",
"14 So Joab and the people that were with him drew nigh before the Syrians unto the battle; and they fled before him.",
"15 And when the children of Ammon saw that the Syrians were fled, they likewise fled before Abishai his brother, and entered into the city. Then Joab came to Jerusalem.",
"16 And when the Syrians saw that they were put to the worse before Israel, they sent messengers, and drew forth the Syrians that were beyond the river: and Shophach the captain of the host of Hadarezer went before them.",
"17 And it was told David; and he gathered all Israel, and passed over Jordan, and came upon them, and set the battle in array against them. So when David had put the battle in array against the Syrians, they fought with him.",
"",
"——【The First Book of the Chronicles 19】",
"",
"13 我们都当刚强，为本国的民和　神的城邑作大丈夫，愿耶和华凭他的意旨而行。",
"14 于是约押和跟随他的人前进攻打亚兰人；亚兰人在约押面前逃跑。",
"15 亚扪人见亚兰人逃跑，他们也在约押的兄弟亚比筛面前逃跑进城。约押就回耶路撒冷去了。",
"16 亚兰人见自己被以色列人打败，就打发使者将大河那边的亚兰人调来，哈大利谢的将军朔法率领他们。",
"17 有人告诉大卫，他就聚集以色列众人过约旦河，来到亚兰人那里，迎著他们摆阵。大卫既摆阵攻击亚兰人，亚兰人就与他打仗。",
"",
"——【历代志上 19】",
],
[
"10 The king of Jerusalem, one; the king of Hebron, one;",
"11 The king of Jarmuth, one; the king of Lachish, one;",
"12 The king of Eglon, one; the king of Gezer, one;",
"",
"——【The Book of Joshua 12】",
"",
"10 一个是耶路撒冷王，一个是希伯崙王，",
"11 一个是耶末王，一个是拉吉王，",
"12 一个是伊矶伦王，一个是基色王，",
"",
"——【约书亚记 12】",
],
[
"17 And Saul knew David's voice, and said, Is this thy voice, my son David? And David said, It is my voice, my lord, O king.",
"18 And he said, Wherefore doth my lord thus pursue after his servant? for what have I done? or what evil is in mine hand?",
"19 Now therefore, I pray thee, let my lord the king hear the words of his servant. If the LORD have stirred thee up against me, let him accept an offering: but if they be the children of men, cursed be they before the LORD; for they have driven me out this day from abiding in the inheritance of the LORD, saying, Go, serve other gods.",
"20 Now therefore, let not my blood fall to the earth before the face of the LORD: for the king of Israel is come out to seek a flea, as when one doth hunt a partridge in the mountains.",
"21 Then said Saul, I have sinned: return, my son David: for I will no more do thee harm, because my soul was precious in thine eyes this day: behold, I have played the fool, and have erred exceedingly.",
"",
"——【The First Book of Samuel 26】",
"",
"17 扫罗听出是大卫的声音，就说：「我儿大卫，这是你的声音吗？」大卫说：「主─我的王啊，是我的声音」；",
"18 又说：「我做了什么？我手里有什么恶事？我主竟追赶仆人呢？",
"19 求我主我王听仆人的话：若是耶和华激发你攻击我，愿耶和华收纳祭物；若是人激发你，愿他在耶和华面前受咒诅；因为他现今赶逐我，不容我在耶和华的产业上有分，说：『你去事奉别神吧！』",
"20 现在求王不要使我的血流在离耶和华远的地方。以色列王出来是寻找一个虼蚤，如同人在山上猎取一个鹧鸪一般。」",
"21 扫罗说：「我有罪了！我儿大卫，你可以回来，因你今日看我的性命为宝贵；我必不再加害于你。我是糊涂人，大大错了。」",
"",
"——【撒母耳记上 26】",
],
[
"1 Make a joyful noise unto the LORD, all ye lands.",
"2 Serve the LORD with gladness: come before his presence with singing.",
"3 Know ye that the LORD he is God: it is he that hath made us, and not we ourselves; we are his people, and the sheep of his pasture.",
"4 Enter into his gates with thanksgiving, and into his courts with praise: be thankful unto him, and bless his name.",
"5 For the LORD is good; his mercy is everlasting; and his truth endureth to all generations.",
"",
"——【The Book of Psalms 100】",
"",
"1 （称谢诗。）普天下当向耶和华欢呼！",
"2 你们当乐意事奉耶和华，当来向他歌唱！",
"3 你们当晓得耶和华是　神！我们是他造的，也是属他的；我们是他的民，也是他草场的羊。",
"4 当称谢进入他的门；当讚美进入他的院。当感谢他，称颂他的名！",
"5 因为耶和华本为善。他的慈爱存到永远；他的信实直到万代。",
"",
"——【诗篇 100】",
],
[
"16 And whosoever toucheth one that is slain with a sword in the open fields, or a dead body, or a bone of a man, or a grave, shall be unclean seven days.",
"17 And for an unclean person they shall take of the ashes of the burnt heifer of purification for sin, and running water shall be put thereto in a vessel:",
"18 And a clean person shall take hyssop, and dip it in the water, and sprinkle it upon the tent, and upon all the vessels, and upon the persons that were there, and upon him that touched a bone, or one slain, or one dead, or a grave:",
"",
"——【The Fourth Book of Moses: Called Numbers 19】",
"",
"16 无论何人在田野里摸了被刀杀的，或是尸首，或是人的骨头，或是坟墓，就要七天不洁净。",
"17 要为这不洁净的人拿些烧成的除罪灰放在器皿里，倒上活水。",
"18 必当有一个洁净的人拿牛膝草蘸在这水中，把水洒在帐棚上，和一切器皿并帐棚内的众人身上，又洒在摸了骨头，或摸了被杀的，或摸了自死的，或摸了坟墓的那人身上。",
"",
"——【民数记 19】",
],
[
"1 In the end of the sabbath, as it began to dawn toward the first day of the week, came Mary Magdalene and the other Mary to see the sepulchre.",
"2 And, behold, there was a great earthquake: for the angel of the Lord descended from heaven, and came and rolled back the stone from the door, and sat upon it.",
"3 His countenance was like lightning, and his raiment white as snow:",
"",
"——【The Gospel According to Saint Matthew 28】",
"",
"1 安息日将尽，七日的头一日，天快亮的时候，抹大拉的马利亚和那个马利亚来看坟墓。",
"2 忽然，地大震动；因为有主的使者从天上下来，把石头滚开，坐在上面。",
"3 他的像貌如同闪电，衣服洁白如雪。",
"",
"——【马太福音 28】",
],
[
"1 Why boastest thou thyself in mischief, O mighty man? the goodness of God endureth continually.",
"2 Thy tongue deviseth mischiefs; like a sharp razor, working deceitfully.",
"3 Thou lovest evil more than good; and lying rather than to speak righteousness. Selah.",
"4 Thou lovest all devouring words, O thou deceitful tongue.",
"5 God shall likewise destroy thee for ever, he shall take thee away, and pluck thee out of thy dwelling place, and root thee out of the land of the living. Selah.",
"",
"——【The Book of Psalms 52】",
"",
"1 （以东人多益来告诉扫罗说：大卫到了亚希米勒家。那时，大卫作这训诲诗，交与伶长。）勇士啊，你为何以作恶自夸？　神的慈爱是常存的。",
"2 你的舌头邪恶诡诈，好像剃头刀，快利伤人。",
"3 你爱恶胜似爱善，又爱说谎，不爱说公义。（细拉）",
"4 诡诈的舌头啊，你爱说一切毁灭的话！",
"5 　神也要毁灭你，直到永远；他要把你拿去，从你的帐棚中抽出，从活人之地将你拔出。（细拉）",
"",
"——【诗篇 52】",
],
[
"3 Know ye not that we shall judge angels? how much more things that pertain to this life?",
"4 If then ye have judgments of things pertaining to this life, set them to judge who are least esteemed in the church.",
"5 I speak to your shame. Is it so, that there is not a wise man among you? no, not one that shall be able to judge between his brethren?",
"6 But brother goeth to law with brother, and that before the unbelievers.",
"",
"——【The First Epistle of Paul the Apostle to the Corinthians 6】",
"",
"3 岂不知我们要审判天使吗？何况今生的事呢？",
"4 既是这样，你们若有今生的事当审判，是派教会所轻看的人审判吗？",
"5 我说这话是要叫你们羞耻。难道你们中间没有一个智慧人能审断弟兄们的事吗？",
"6 你们竟是弟兄与弟兄告状，而且告在不信主的人面前。",
"",
"——【哥林多前书 6】",
],
[
"7 For they have devoured Jacob, and laid waste his dwelling place.",
"8 O remember not against us former iniquities: let thy tender mercies speedily prevent us: for we are brought very low.",
"9 Help us, O God of our salvation, for the glory of thy name: and deliver us, and purge away our sins, for thy name's sake.",
"",
"——【The Book of Psalms 79】",
"",
"7 因为他们吞了雅各，把他的住处变为荒场。",
"8 求你不要记念我们先祖的罪孽，向我们追讨；愿你的慈悲快迎著我们，因为我们落到极卑微的地步。",
"9 拯救我们的　神啊，求你因你名的荣耀帮助我们！为你名的缘故搭救我们，赦免我们的罪。",
"",
"——【诗篇 79】",
],
[
"3 Thus shall Aaron come into the holy place: with a young bullock for a sin offering, and a ram for a burnt offering.",
"4 He shall put on the holy linen coat, and he shall have the linen breeches upon his flesh, and shall be girded with a linen girdle, and with the linen mitre shall he be attired: these are holy garments; therefore shall he wash his flesh in water, and so put them on.",
"5 And he shall take of the congregation of the children of Israel two kids of the goats for a sin offering, and one ram for a burnt offering.",
"",
"——【The Third Book of Moses: Called Leviticus 16】",
"",
"3 亚伦进圣所，要带一只公牛犊为赎罪祭，一只公绵羊为燔祭。",
"4 要穿上细麻布圣内袍，把细麻布裤子穿在身上，腰束细麻布带子，头戴细麻布冠冕；这都是圣服。他要用水洗身，然后穿戴。",
"5 要从以色列会众取两只公山羊为赎罪祭，一只公绵羊为燔祭。",
"",
"——【利未记 16】",
],
[
"17 And he said, I will send thee a kid from the flock. And she said, Wilt thou give me a pledge, till thou send it?",
"18 And he said, What pledge shall I give thee? And she said, Thy signet, and thy bracelets, and thy staff that is in thine hand. And he gave it her, and came in unto her, and she conceived by him.",
"",
"——【The First Book of Moses: Called Genesis 38】",
"",
"17 犹大说：「我从羊群里取一只山羊羔，打发人送来给你。」她玛说：「在未送以先，你愿意给我一个当头吗？」",
"18 他说：「我给你什么当头呢？」她玛说：「你的印、你的带子，和你手里的杖。」犹大就给了她，与她同寝，她就从犹大怀了孕。",
"",
"——【创世记 38】",
],
[
"3 I will consume man and beast; I will consume the fowls of the heaven, and the fishes of the sea, and the stumblingblocks with the wicked; and I will cut off man from off the land, saith the LORD.",
"4 I will also stretch out mine hand upon Judah, and upon all the inhabitants of Jerusalem; and I will cut off the remnant of Baal from this place, and the name of the Chemarims with the priests;",
"5 And them that worship the host of heaven upon the housetops; and them that worship and that swear by the LORD, and that swear by Malcham;",
"6 And them that are turned back from the LORD; and those that have not sought the LORD, nor enquired for him.",
"7 Hold thy peace at the presence of the Lord GOD: for the day of the LORD is at hand: for the LORD hath prepared a sacrifice, he hath bid his guests.",
"8 And it shall come to pass in the day of the LORD'S sacrifice, that I will punish the princes, and the king's children, and all such as are clothed with strange apparel.",
"",
"——【Zephaniah 1】",
"",
"3 我必除灭人和牲畜，与空中的鸟、海里的鱼，以及绊脚石和恶人；我必将人从地上剪除。这是耶和华说的。",
"4 我必伸手攻击犹大和耶路撒冷的一切居民，也必从这地方剪除所剩下的巴力，并基玛林的名和祭司，",
"5 与那些在房顶上敬拜天上万象的，并那些敬拜耶和华指著他起誓，又指著玛勒堪起誓的，",
"6 与那些转去不跟从耶和华的，和不寻求耶和华也不访问他的。",
"7 你要在主耶和华面前静默无声，因为耶和华的日子快到。耶和华已经预备祭物，将他的客分别为圣。",
"8 到了我─耶和华献祭的日子，必惩罚首领和王子，并一切穿外邦衣服的。",
"",
"——【西番雅书 1】",
],
];
