var bible31_global=[
[
"7 For none of us liveth to himself, and no man dieth to himself.",
"8 For whether we live, we live unto the Lord; and whether we die, we die unto the Lord: whether we live therefore, or die, we are the Lord's.",
"9 For to this end Christ both died, and rose, and revived, that he might be Lord both of the dead and living.",
"10 But why dost thou judge thy brother? or why dost thou set at nought thy brother? for we shall all stand before the judgment seat of Christ.",
"11 For it is written, As I live, saith the Lord, every knee shall bow to me, and every tongue shall confess to God.",
"12 So then every one of us shall give account of himself to God.",
"",
"——【The Epistle of Paul the Apostle to the Romans 14】",
"",
"7 我们没有一个人为自己活，也没有一个人为自己死。",
"8 我们若活着，是为主而活；若死了，是为主而死。所以，我们或活或死总是主的人。",
"9 因此基督死了又活了，为要作死人并活人的主。",
"10 你这个人，为什么论断弟兄呢？又为什么轻看弟兄呢？因我们都要站在　神的台前。",
"11 经上写着：主说：我凭着我的永生起誓：万膝必向我跪拜；万口必向我承认。",
"12 这样看来，我们各人必要将自己的事在　神面前说明。",
"",
"——【罗马书 14】",
],
[
"17 Then said Saul unto the people that were with him, Number now, and see who is gone from us. And when they had numbered, behold, Jonathan and his armourbearer were not there.",
"18 And Saul said unto Ahiah, Bring hither the ark of God. For the ark of God was at that time with the children of Israel.",
"",
"——【The First Book of Samuel 14】",
"",
"17 扫罗就对跟随他的民说：「你们查点查点，看从我们这里出去的是谁？」他们一查点，就知道约拿单和拿兵器的人没有在这里。",
"18 那时　神的约柜在以色列人那里。扫罗对亚希亚说：「你将　神的约柜运了来。」",
"",
"——【撒母耳记上 14】",
],
[
"1 The earth is the LORD'S, and the fulness thereof; the world, and they that dwell therein.",
"2 For he hath founded it upon the seas, and established it upon the floods.",
"3 Who shall ascend into the hill of the LORD? or who shall stand in his holy place?",
"4 He that hath clean hands, and a pure heart; who hath not lifted up his soul unto vanity, nor sworn deceitfully.",
"",
"——【The Book of Psalms 24】",
"",
"1 （大卫的诗。）地和其中所充满的，世界和住在其间的，都属耶和华。",
"2 他把地建立在海上，安定在大水之上。",
"3 谁能登耶和华的山？谁能站在他的圣所？",
"4 就是手洁心清、不向虚妄、起誓不怀诡诈的人。",
"",
"——【诗篇 24】",
],
[
"1 Truly my soul waiteth upon God: from him cometh my salvation.",
"2 He only is my rock and my salvation; he is my defence; I shall not be greatly moved.",
"3 How long will ye imagine mischief against a man? ye shall be slain all of you: as a bowing wall shall ye be, and as a tottering fence.",
"4 They only consult to cast him down from his excellency: they delight in lies: they bless with their mouth, but they curse inwardly. Selah.",
"5 My soul, wait thou only upon God; for my expectation is from him.",
"6 He only is my rock and my salvation: he is my defence; I shall not be moved.",
"",
"——【The Book of Psalms 62】",
"",
"1 （大卫的诗，照耶杜顿的作法，交与伶长。）我的心默默无声，专等候　神；我的救恩是从他而来。",
"2 惟独他是我的磐石，我的拯救；他是我的高台，我必不很动摇。",
"3 你们大家攻击一人，把他毁坏，如同毁坏歪斜的墙、将倒的壁，要到几时呢？",
"4 他们彼此商议，专要从他的尊位上把他推下；他们喜爱谎话，口虽祝福，心却咒诅。（细拉）",
"5 我的心哪，你当默默无声，专等候　神，因为我的盼望是从他而来。",
"6 惟独他是我的磐石，我的拯救；他是我的高台，我必不动摇。",
"",
"——【诗篇 62】",
],
[
"20 For thy servant doth know that I have sinned: therefore, behold, I am come the first this day of all the house of Joseph to go down to meet my lord the king.",
"21 But Abishai the son of Zeruiah answered and said, Shall not Shimei be put to death for this, because he cursed the LORD'S anointed?",
"22 And David said, What have I to do with you, ye sons of Zeruiah, that ye should this day be adversaries unto me? shall there any man be put to death this day in Israel? for do not I know that I am this day king over Israel?",
"23 Therefore the king said unto Shimei, Thou shalt not die. And the king sware unto him.",
"",
"——【The Second Book of Samuel 19】",
"",
"20 仆人明知自己有罪，所以约瑟全家之中，今日我首先下来迎接我主我王。」",
"21 洗鲁雅的儿子亚比筛说：「示每既咒骂耶和华的受膏者，不应当治死他吗？」",
"22 大卫说：「洗鲁雅的儿子，我与你们有何关涉，使你们今日与我反对呢？今日在以色列中岂可治死人呢？我岂不知今日我作以色列的王吗？」",
"23 于是王对示每说：「你必不死。」王就向他起誓。",
"",
"——【撒母耳记下 19】",
],
[
"10 And David enquired of God, saying, Shall I go up against the Philistines? and wilt thou deliver them into mine hand? And the LORD said unto him, Go up; for I will deliver them into thine hand.",
"11 So they came up to Baal–perazim; and David smote them there. Then David said, God hath broken in upon mine enemies by mine hand like the breaking forth of waters: therefore they called the name of that place Baal–perazim.",
"12 And when they had left their gods there, David gave a commandment, and they were burned with fire.",
"13 And the Philistines yet again spread themselves abroad in the valley.",
"",
"——【The First Book of the Chronicles 14】",
"",
"10 大卫求问　神，说：「我可以上去攻打非利士人吗？你将他们交在我手里吗？」耶和华说：「你可以上去，我必将他们交在你手里。」",
"11 非利士人来到巴力‧毗拉心，大卫在那里杀败他们。大卫说：「　神借我的手冲破敌人，如同水冲去一般」；因此称那地方为巴力‧毗拉心。",
"12 非利士人将神像撇在那里，大卫吩咐人用火焚烧了。",
"13 非利士人又布散在利乏音谷。",
"",
"——【历代志上 14】",
],
[
"13 He said also unto me, Turn thee yet again, and thou shalt see greater abominations that they do.",
"14 Then he brought me to the door of the gate of the LORD'S house which was toward the north; and, behold, there sat women weeping for Tammuz.",
"15 Then said he unto me, Hast thou seen this, O son of man? turn thee yet again, and thou shalt see greater abominations than these.",
"",
"——【The Book of the Prophet Ezekiel 8】",
"",
"13 他又说：「你还要看见他们另外行大可憎的事。」",
"14 他领我到耶和华殿外院朝北的门口。谁知，在那里有妇女坐着，为搭模斯哭泣。",
"15 他对我说：「人子啊，你看见了吗？你还要看见比这更可憎的事。」",
"",
"——【以西结书 8】",
],
[
"7 What then? Israel hath not obtained that which he seeketh for; but the election hath obtained it, and the rest were blinded",
"8 (According as it is written, God hath given them the spirit of slumber, eyes that they should not see, and ears that they should not hear;) unto this day.",
"9 And David saith, Let their table be made a snare, and a trap, and a stumblingblock, and a recompence unto them:",
"10 Let their eyes be darkened, that they may not see, and bow down their back alway.",
"11 I say then, Have they stumbled that they should fall? God forbid: but rather through their fall salvation is come unto the Gentiles, for to provoke them to jealousy.",
"12 Now if the fall of them be the riches of the world, and the diminishing of them the riches of the Gentiles; how much more their fulness?",
"",
"——【The Epistle of Paul the Apostle to the Romans 11】",
"",
"7 这是怎么样呢？以色列人所求的，他们没有得着，惟有蒙拣选的人得着了；其余的就成了顽梗不化的。",
"8 如经上所记：　神给他们昏迷的心，眼睛不能看见，耳朵不能听见，直到今日。",
"9 大卫也说：愿他们的筵席变为网罗，变为机槛，变为绊脚石，作他们的报应。",
"10 愿他们的眼睛昏蒙，不得看见；愿你时常弯下他们的腰。",
"11 我且说，他们失脚是要他们跌倒吗？断乎不是！反倒因他们的过失，救恩便临到外邦人，要激动他们发愤。",
"12 若他们的过失，为天下的富足，他们的缺乏，为外邦人的富足；何况他们的丰满呢？",
"",
"——【罗马书 11】",
],
[
"3 And David smote Hadarezer king of Zobah unto Hamath, as he went to stablish his dominion by the river Euphrates.",
"4 And David took from him a thousand chariots, and seven thousand horsemen, and twenty thousand footmen: David also houghed all the chariot horses, but reserved of them an hundred chariots.",
"5 And when the Syrians of Damascus came to help Hadarezer king of Zobah, David slew of the Syrians two and twenty thousand men.",
"6 Then David put garrisons in Syria–damascus; and the Syrians became David's servants, and brought gifts. Thus the LORD preserved David whithersoever he went.",
"7 And David took the shields of gold that were on the servants of Hadarezer, and brought them to Jerusalem.",
"",
"——【The First Book of the Chronicles 18】",
"",
"3 琐巴王哈大利谢【撒下八章三节作哈大底谢】往伯拉河去，要坚定自己的国权，大卫就攻打他，直到哈马，",
"4 夺了他的战车一千，马兵七千，步兵二万，将拉战车的马砍断蹄筋，但留下一百辆车的马。",
"5 大马士革的亚兰人来帮助琐巴王哈大利谢，大卫就杀了亚兰人二万二千。",
"6 于是大卫在大马士革的亚兰地设立防营，亚兰人就归服他，给他进贡。大卫无论往哪里去，耶和华都使他得胜。",
"7 他夺了哈大利谢臣仆所拿的金盾牌带到耶路撒冷。",
"",
"——【历代志上 18】",
],
[
"6 And so did he in the cities of Manasseh, and Ephraim, and Simeon, even unto Naphtali, with their mattocks round about.",
"7 And when he had broken down the altars and the groves, and had beaten the graven images into powder, and cut down all the idols throughout all the land of Israel, he returned to Jerusalem.",
"8 Now in the eighteenth year of his reign, when he had purged the land, and the house, he sent Shaphan the son of Azaliah, and Maaseiah the governor of the city, and Joah the son of Joahaz the recorder, to repair the house of the LORD his God.",
"9 And when they came to Hilkiah the high priest, they delivered the money that was brought into the house of God, which the Levites that kept the doors had gathered of the hand of Manasseh and Ephraim, and of all the remnant of Israel, and of all Judah and Benjamin; and they returned to Jerusalem.",
"",
"——【The Second Book of the Chronicles 34】",
"",
"6 又在玛拿西、以法莲、西缅、拿弗他利各城，和四围破坏之处，都这样行；",
"7 又拆毁祭坛，把木偶和雕刻的像打碎成灰，砍断以色列遍地所有的日像，就回耶路撒冷去了。",
"8 约西亚王十八年，净地净殿之后，就差遣亚萨利雅的儿子沙番、邑宰玛西雅、约哈斯的儿子史官约亚去修理耶和华─他　神的殿。",
"9 他们就去见大祭司希勒家，将奉到　神殿的银子交给他；这银子是看守殿门的利未人从玛拿西、以法莲，和一切以色列剩下的人，以及犹大、便雅悯众人，并耶路撒冷的居民收来的。",
"",
"——【历代志下 34】",
],
[
"1 And Jehoshaphat the king of Judah returned to his house in peace to Jerusalem.",
"2 And Jehu the son of Hanani the seer went out to meet him, and said to king Jehoshaphat, Shouldest thou help the ungodly, and love them that hate the LORD? therefore is wrath upon thee from before the LORD.",
"3 Nevertheless there are good things found in thee, in that thou hast taken away the groves out of the land, and hast prepared thine heart to seek God.",
"4 And Jehoshaphat dwelt at Jerusalem: and he went out again through the people from Beer–sheba to mount Ephraim, and brought them back unto the LORD God of their fathers.",
"",
"——【The Second Book of the Chronicles 19】",
"",
"1 犹大王约沙法平平安安地回耶路撒冷，到宫里去了。",
"2 先见哈拿尼的儿子耶户出来迎接约沙法王，对他说：「你岂当帮助恶人，爱那恨恶耶和华的人呢？因此耶和华的忿怒临到你。",
"3 然而你还有善行，因你从国中除掉木偶，立定心意寻求　神。」",
"4 约沙法住在耶路撒冷，以后又出巡民间，从别是巴直到以法莲山地，引导民归向耶和华─他们列祖的　神；",
"",
"——【历代志下 19】",
],
[
"15 And he said unto him, If thy presence go not with me, carry us not up hence.",
"16 For wherein shall it be known here that I and thy people have found grace in thy sight? is it not in that thou goest with us? so shall we be separated, I and thy people, from all the people that are upon the face of the earth.",
"17 And the LORD said unto Moses, I will do this thing also that thou hast spoken: for thou hast found grace in my sight, and I know thee by name.",
"18 And he said, I beseech thee, shew me thy glory.",
"",
"——【The Second Book of Moses: Called Exodus 33】",
"",
"15 摩西说：「你若不亲自和我同去，就不要把我们从这里领上去。",
"16 人在何事上得以知道我和你的百姓在你眼前蒙恩呢？岂不是因你与我们同去、使我和你的百姓与地上的万民有分别吗？」",
"17 耶和华对摩西说：「你这所求的我也要行；因为你在我眼前蒙了恩，并且我按你的名认识你。」",
"18 摩西说：「求你显出你的荣耀给我看。」",
"",
"——【出埃及记 33】",
],
[
"4 One thing have I desired of the LORD, that will I seek after; that I may dwell in the house of the LORD all the days of my life, to behold the beauty of the LORD, and to enquire in his temple.",
"5 For in the time of trouble he shall hide me in his pavilion: in the secret of his tabernacle shall he hide me; he shall set me up upon a rock.",
"6 And now shall mine head be lifted up above mine enemies round about me: therefore will I offer in his tabernacle sacrifices of joy; I will sing, yea, I will sing praises unto the LORD.",
"7 Hear, O LORD, when I cry with my voice: have mercy also upon me, and answer me.",
"8 When thou saidst, Seek ye my face; my heart said unto thee, Thy face, LORD, will I seek.",
"",
"——【The Book of Psalms 27】",
"",
"4 有一件事，我曾求耶和华，我仍要寻求：就是一生一世住在耶和华的殿中，瞻仰他的荣美，在他的殿里求问。",
"5 因为我遭遇患难，他必暗暗地保守我；在他亭子里，把我藏在他帐幕的隐密处，将我高举在磐石上。",
"6 现在我得以昂首，高过四面的仇敌。我要在他的帐幕里欢然献祭；我要唱诗歌颂耶和华。",
"7 耶和华啊，我用声音呼吁的时候，求你垂听；并求你怜恤我，应允我。",
"8 你说：你们当寻求我的面。那时我心向你说：耶和华啊，你的面我正要寻求。",
"",
"——【诗篇 27】",
],
[
"4 So Esther's maids and her chamberlains came and told it her. Then was the queen exceedingly grieved; and she sent raiment to clothe Mordecai, and to take away his sackcloth from him: but he received it not.",
"5 Then called Esther for Hatach, one of the king's chamberlains, whom he had appointed to attend upon her, and gave him a commandment to Mordecai, to know what it was, and why it was.",
"",
"——【The Book of Esther 4】",
"",
"4 王后以斯帖的宫女和太监来把这事告诉以斯帖，她甚是忧愁，就送衣服给末底改穿，要他脱下麻衣，他却不受。",
"5 以斯帖就把王所派伺候她的一个太监，名叫哈他革召来，吩咐他去见末底改，要知道这是什么事，是什么缘故。",
"",
"——【以斯帖记 4】",
],
[
"1 We then, as workers together with him, beseech you also that ye receive not the grace of God in vain.",
"2 (For he saith, I have heard thee in a time accepted, and in the day of salvation have I succoured thee: behold, now is the accepted time; behold, now is the day of salvation.)",
"3 Giving no offence in any thing, that the ministry be not blamed:",
"",
"——【The Second Epistle of Paul the Apostle to the Corinthians 6】",
"",
"1 我们与　神同工的，也劝你们不可徒受他的恩典。",
"2 因为他说：在悦纳的时候，我应允了你；在拯救的日子，我搭救了你。看哪！现在正是悦纳的时候；现在正是拯救的日子。",
"3 我们凡事都不叫人有妨碍，免得这职分被人毁谤；",
"",
"——【哥林多后书 6】",
],
[
"28 Then shall he return into his land with great riches; and his heart shall be against the holy covenant; and he shall do exploits, and return to his own land.",
"29 At the time appointed he shall return, and come toward the south; but it shall not be as the former, or as the latter.",
"",
"——【The Book of Daniel 11】",
"",
"28 北方王（原文是他）必带许多财宝回往本国，他的心反对圣约，任意而行，回到本地。",
"29 到了定期，他必返回，来到南方。后一次却不如前一次，",
"",
"——【但以理书 11】",
],
[
"17 And it came to pass, that after three days Paul called the chief of the Jews together: and when they were come together, he said unto them, Men and brethren, though I have committed nothing against the people, or customs of our fathers, yet was I delivered prisoner from Jerusalem into the hands of the Romans.",
"18 Who, when they had examined me, would have let me go, because there was no cause of death in me.",
"19 But when the Jews spake against it, I was constrained to appeal unto Cæsar; not that I had ought to accuse my nation of.",
"",
"——【The Acts of the Apostles 28】",
"",
"17 过了三天，保罗请犹太人的首领来。他们来了，就对他们说：弟兄们，我虽没有做什么事干犯本国的百姓和我们祖宗的规条，却被锁绑，从耶路撒冷解在罗马人的手里。",
"18 他们审问了我，就愿意释放我；因为在我身上，并没有该死的罪。",
"19 无奈犹太人不服，我不得已，只好上告于凯撒，并非有什么事要控告我本国的百姓。",
"",
"——【使徒行传 28】",
],
[
"7 The full soul loatheth an honeycomb; but to the hungry soul every bitter thing is sweet.",
"8 As a bird that wandereth from her nest, so is a man that wandereth from his place.",
"9 Ointment and perfume rejoice the heart: so doth the sweetness of a man's friend by hearty counsel.",
"",
"——【The Proverbs 27】",
"",
"7 人吃饱了，厌恶蜂房的蜜；人饥饿了，一切苦物都觉甘甜。",
"8 人离本处飘流，好像雀鸟离窝游飞。",
"9 膏油与香料使人心喜悦；朋友诚实的劝教也是如此甘美。",
"",
"——【箴言 27】",
],
[
"9 These were all the sons of David, beside the sons of the concubines, and Tamar their sister.",
"10 And Solomon's son was Rehoboam, Abia his son, Asa his son, Jehoshaphat his son,",
"",
"——【The First Book of the Chronicles 3】",
"",
"9 这都是大卫的儿子，还有他们的妹子她玛，妃嫔的儿子不在其内。",
"10 所罗门的儿子是罗波安；罗波安的儿子是亚比雅；亚比雅的儿子是亚撒；亚撒的儿子是约沙法；",
"",
"——【历代志上 3】",
],
[
"43 Woe unto you, Pharisees! for ye love the uppermost seats in the synagogues, and greetings in the markets.",
"44 Woe unto you, scribes and Pharisees, hypocrites! for ye are as graves which appear not, and the men that walk over them are not aware of them.",
"",
"——【The Gospel According to Saint Luke 11】",
"",
"43 你们法利赛人有祸了！因为你们喜爱会堂里的首位，又喜爱人在街市上问你们的安。",
"44 你们有祸了！因为你们如同不显露的坟墓，走在上面的人并不知道。",
"",
"——【路加福音 11】",
],
[
"7 And he made ten candlesticks of gold according to their form, and set them in the temple, five on the right hand, and five on the left.",
"8 He made also ten tables, and placed them in the temple, five on the right side, and five on the left. And he made an hundred basons of gold.",
"9 Furthermore he made the court of the priests, and the great court, and doors for the court, and overlaid the doors of them with brass.",
"10 And he set the sea on the right side of the east end, over against the south.",
"11 And Huram made the pots, and the shovels, and the basons. And Huram finished the work that he was to make for king Solomon for the house of God;",
"12 To wit, the two pillars, and the pommels, and the chapiters which were on the top of the two pillars, and the two wreaths to cover the two pommels of the chapiters which were on the top of the pillars;",
"",
"——【The Second Book of the Chronicles 4】",
"",
"7 他又照所定的样式造十个金灯台放在殿里：五个在右边，五个在左边；",
"8 又造十张桌子放在殿里：五张在右边，五张在左边；又造一百个金碗；",
"9 又建立祭司院和大院，并院门，用铜包裹门扇；",
"10 将海安在殿门的右边，就是南边。",
"11 户兰又造了盆、铲、碗。这样，他为所罗门王做完了　神殿的工。",
"12 所造的就是：两根柱子和柱上两个如球的顶，并两个盖柱顶的网子",
"",
"——【历代志下 4】",
],
[
"22 But ye know the proof of him, that, as a son with the father, he hath served with me in the gospel.",
"23 Him therefore I hope to send presently, so soon as I shall see how it will go with me.",
"24 But I trust in the Lord that I also myself shall come shortly.",
"25 Yet I supposed it necessary to send to you Epaphroditus, my brother, and companion in labour, and fellowsoldier, but your messenger, and he that ministered to my wants.",
"",
"——【The Epistle of Paul the Apostle to the Philippians 2】",
"",
"22 但你们知道提摩太的明证；他兴旺福音，与我同劳，待我像儿子待父亲一样。",
"23 所以，我一看出我的事要怎样了结，就盼望立刻打发他去；",
"24 但我靠着主自信我也必快去。",
"25 然而，我想必须打发以巴弗提到你们那里去。他是我的兄弟，与我一同做工，一同当兵，是你们所差遣的，也是供给我需用的。",
"",
"——【腓立比书 2】",
],
[
"13 Therefore thus saith the LORD; Ask ye now among the heathen, who hath heard such things: the virgin of Israel hath done a very horrible thing.",
"14 Will a man leave the snow of Lebanon which cometh from the rock of the field? or shall the cold flowing waters that come from another place be forsaken?",
"15 Because my people hath forgotten me, they have burned incense to vanity, and they have caused them to stumble in their ways from the ancient paths, to walk in paths, in a way not cast up;",
"",
"——【The Book of the Prophet Jeremiah 18】",
"",
"13 所以，耶和华如此说：你们且往各国访问，有谁听见这样的事？以色列民（原文是处女）行了一件极可憎恶的事。",
"14 黎巴嫩的雪从田野的磐石上岂能断绝呢？从远处流下的凉水岂能干涸呢？",
"15 我的百姓竟忘记我，向假神烧香，使他们在所行的路上，在古道上绊跌，使他们行没有修筑的斜路，",
"",
"——【耶利米书 18】",
],
[
"1 The LORD is my shepherd; I shall not want.",
"2 He maketh me to lie down in green pastures: he leadeth me beside the still waters.",
"3 He restoreth my soul: he leadeth me in the paths of righteousness for his name's sake.",
"4 Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.",
"",
"——【The Book of Psalms 23】",
"",
"1 （大卫的诗。）耶和华是我的牧者，我必不致缺乏。",
"2 他使我躺卧在青草地上，领我在可安歇的水边。",
"3 他使我的灵魂苏醒，为自己的名引导我走义路。",
"4 我虽然行过死荫的幽谷，也不怕遭害，因为你与我同在；你的杖，你的竿，都安慰我。",
"",
"——【诗篇 23】",
],
[
"8 And thou hast filled me with wrinkles, which is a witness against me: and my leanness rising up in me beareth witness to my face.",
"9 He teareth me in his wrath, who hateth me: he gnasheth upon me with his teeth; mine enemy sharpeneth his eyes upon me.",
"10 They have gaped upon me with their mouth; they have smitten me upon the cheek reproachfully; they have gathered themselves together against me.",
"11 God hath delivered me to the ungodly, and turned me over into the hands of the wicked.",
"12 I was at ease, but he hath broken me asunder: he hath also taken me by my neck, and shaken me to pieces, and set me up for his mark.",
"",
"——【The Book of Job 16】",
"",
"8 又抓住我，作见证攻击我；我身体的枯瘦也当面见证我的不是。",
"9 主发怒撕裂我，逼迫我，向我切齿；我的敌人怒目看我。",
"10 他们向我开口，打我的脸羞辱我，聚会攻击我。",
"11 　神把我交给不敬虔的人，把我扔到恶人的手中。",
"12 我素来安逸，他折断我，掐住我的颈项，把我摔碎，又立我为他的箭靶子。",
"",
"——【约伯记 16】",
],
[
"6 I stretch forth my hands unto thee: my soul thirsteth after thee, as a thirsty land. Selah.",
"7 Hear me speedily, O LORD: my spirit faileth: hide not thy face from me, lest I be like unto them that go down into the pit.",
"8 Cause me to hear thy lovingkindness in the morning; for in thee do I trust: cause me to know the way wherein I should walk; for I lift up my soul unto thee.",
"9 Deliver me, O LORD, from mine enemies: I flee unto thee to hide me.",
"10 Teach me to do thy will; for thou art my God: thy spirit is good; lead me into the land of uprightness.",
"",
"——【The Book of Psalms 143】",
"",
"6 我向你举手；我的心渴想你，如干旱之地盼雨一样。（细拉）",
"7 耶和华啊，求你速速应允我！我心神耗尽！不要向我掩面，免得我像那些下坑的人一样。",
"8 求你使我清晨得听你慈爱之言，因我倚靠你；求你使我知道当行的路，因我的心仰望你。",
"9 耶和华啊，求你救我脱离我的仇敌！我往你那里藏身。",
"10 求你指教我遵行你的旨意，因你是我的　神。你的灵本为善；求你引我到平坦之地。",
"",
"——【诗篇 143】",
],
[
"1 And the LORD spake unto Moses, saying,",
"2 Command the children of Israel, that they bring unto thee pure oil olive beaten for the light, to cause the lamps to burn continually.",
"3 Without the vail of the testimony, in the tabernacle of the congregation, shall Aaron order it from the evening unto the morning before the LORD continually: it shall be a statute for ever in your generations.",
"4 He shall order the lamps upon the pure candlestick before the LORD continually.",
"",
"——【The Third Book of Moses: Called Leviticus 24】",
"",
"1 耶和华晓谕摩西说：",
"2 「要吩咐以色列人，把那为点灯捣成的清橄榄油拿来给你，使灯常常点着。",
"3 在会幕中法柜的幔子外，亚伦从晚上到早晨必在耶和华面前经理这灯。这要作你们世世代代永远的定例。",
"4 他要在耶和华面前常收拾精金灯台上的灯。」",
"",
"——【利未记 24】",
],
[
"16 Send one of you, and let him fetch your brother, and ye shall be kept in prison, that your words may be proved, whether there be any truth in you: or else by the life of Pharaoh surely ye are spies.",
"17 And he put them all together into ward three days.",
"18 And Joseph said unto them the third day, This do, and live; for I fear God:",
"19 If ye be true men, let one of your brethren be bound in the house of your prison: go ye, carry corn for the famine of your houses:",
"",
"——【The First Book of Moses: Called Genesis 42】",
"",
"16 须要打发你们中间一个人去，把你们的兄弟带来。至于你们，都要囚在这里，好证验你们的话真不真，若不真，我指着法老的性命起誓，你们一定是奸细。」",
"17 于是约瑟把他们都下在监里三天。",
"18 到了第三天，约瑟对他们说：「我是敬畏　神的；你们照我的话行就可以存活。",
"19 你们如果是诚实人，可以留你们中间的一个人囚在监里，但你们可以带着粮食回去，救你们家里的饥荒。",
"",
"——【创世记 42】",
],
[
"2 Feed the flock of God which is among you, taking the oversight thereof, not by constraint, but willingly; not for filthy lucre, but of a ready mind;",
"3 Neither as being lords over God's heritage, but being ensamples to the flock.",
"4 And when the chief Shepherd shall appear, ye shall receive a crown of glory that fadeth not away.",
"5 Likewise, ye younger, submit yourselves unto the elder. Yea, all of you be subject one to another, and be clothed with humility: for God resisteth the proud, and giveth grace to the humble.",
"6 Humble yourselves therefore under the mighty hand of God, that he may exalt you in due time:",
"7 Casting all your care upon him; for he careth for you.",
"",
"——【The First Epistle General of Peter 5】",
"",
"2 务要牧养在你们中间　神的群羊，按着　神旨意照管他们；不是出于勉强，乃是出于甘心；也不是因为贪财，乃是出于乐意；",
"3 也不是辖制所托付你们的，乃是作群羊的榜样。",
"4 到了牧长显现的时候，你们必得那永不衰残的荣耀冠冕。",
"5 你们年幼的，也要顺服年长的。就是你们众人也都要以谦卑束腰，彼此顺服；因为　神阻挡骄傲的人，赐恩给谦卑的人。",
"6 所以，你们要自卑，服在　神大能的手下，到了时候他必叫你们升高。",
"7 你们要将一切的忧虑卸给　神，因为他顾念你们。",
"",
"——【彼得前书 5】",
],
[
"14 At the end of seven years let ye go every man his brother an Hebrew, which hath been sold unto thee; and when he hath served thee six years, thou shalt let him go free from thee: but your fathers hearkened not unto me, neither inclined their ear.",
"15 And ye were now turned, and had done right in my sight, in proclaiming liberty every man to his neighbour; and ye had made a covenant before me in the house which is called by my name:",
"16 But ye turned and polluted my name, and caused every man his servant, and every man his handmaid, whom ye had set at liberty at their pleasure, to return, and brought them into subjection, to be unto you for servants and for handmaids.",
"17 Therefore thus saith the LORD; Ye have not hearkened unto me, in proclaiming liberty, every one to his brother, and every man to his neighbour: behold, I proclaim a liberty for you, saith the LORD, to the sword, to the pestilence, and to the famine; and I will make you to be removed into all the kingdoms of the earth.",
"",
"——【The Book of the Prophet Jeremiah 34】",
"",
"14 『你的一个希伯来弟兄若卖给你，服事你六年，到第七年你们各人就要任他自由出去。』只是你们列祖不听从我，也不侧耳而听。",
"15 如今你们回转，行我眼中看为正的事，各人向邻舍宣告自由，并且在称为我名下的殿中、在我面前立约。",
"16 你们却又反悔，亵渎我的名，各人叫所任去随意自由的仆人婢女回来，勉强他们仍为仆婢。",
"17 所以耶和华如此说：你们没有听从我，各人向弟兄邻舍宣告自由。看哪！我向你们宣告一样自由，就是使你们自由于刀剑、饥荒、瘟疫之下，并且使你们在天下万国中抛来抛去。这是耶和华说的。",
"",
"——【耶利米书 34】",
],
[
"8 I will meet them as a bear that is bereaved of her whelps, and will rend the caul of their heart, and there will I devour them like a lion: the wild beast shall tear them.",
"9 O Israel, thou hast destroyed thyself; but in me is thine help.",
"10 I will be thy king: where is any other that may save thee in all thy cities? and thy judges of whom thou saidst, Give me a king and princes?",
"11 I gave thee a king in mine anger, and took him away in my wrath.",
"",
"——【Hosea 13】",
"",
"8 我遇见他们必像丢崽子的母熊，撕裂他们的胸膛（或译：心膜）。在那里，我必像母狮吞吃他们；野兽必撕裂他们。",
"9 以色列啊，你与我反对，就是反对帮助你的，自取败坏。",
"10 你曾求我说：给我立王和首领。现在你的王在哪里呢？治理你的在哪里呢？让他在你所有的城中拯救你吧！",
"11 我在怒气中将王赐你，又在烈怒中将王废去。",
"",
"——【何西阿书 13】",
],
];
