var bible31_global=[
[
"1 Help, LORD; for the godly man ceaseth; for the faithful fail from among the children of men.",
"2 They speak vanity every one with his neighbour: with flattering lips and with a double heart do they speak.",
"3 The LORD shall cut off all flattering lips, and the tongue that speaketh proud things:",
"4 Who have said, With our tongue will we prevail; our lips are our own: who is lord over us?",
"",
"——【The Book of Psalms 12】",
"",
"1 （大卫的诗，交与伶长。调用第八。）耶和华啊，求你帮助，因虔诚人断绝了；世人中间的忠信人没有了。",
"2 人人向邻舍说谎；他们说话，是嘴唇油滑，心口不一。",
"3 凡油滑的嘴唇和夸大的舌头，耶和华必要剪除。",
"4 他们曾说：我们必能以舌头得胜；我们的嘴唇是我们自己的，谁能作我们的主呢？",
"",
"——【诗篇 12】",
],
[
"11 Come, ye children, hearken unto me: I will teach you the fear of the LORD.",
"12 What man is he that desireth life, and loveth many days, that he may see good?",
"13 Keep thy tongue from evil, and thy lips from speaking guile.",
"14 Depart from evil, and do good; seek peace, and pursue it.",
"",
"——【The Book of Psalms 34】",
"",
"11 众弟子啊，你们当来听我的话！我要将敬畏耶和华的道教训你们。",
"12 有何人喜好存活，爱慕长寿，得享美福，",
"13 就要禁止舌头不出恶言，嘴唇不说诡诈的话。",
"14 要离恶行善，寻求和睦，一心追赶。",
"",
"——【诗篇 34】",
],
[
"14 Behold, thou hast driven me out this day from the face of the earth; and from thy face shall I be hid; and I shall be a fugitive and a vagabond in the earth; and it shall come to pass, that every one that findeth me shall slay me.",
"15 And the LORD said unto him, Therefore whosoever slayeth Cain, vengeance shall be taken on him sevenfold. And the LORD set a mark upon Cain, lest any finding him should kill him.",
"16 And Cain went out from the presence of the LORD, and dwelt in the land of Nod, on the east of Eden.",
"",
"——【The First Book of Moses: Called Genesis 4】",
"",
"14 你如今赶逐我离开这地，以致不见你面；我必流离飘荡在地上，凡遇见我的必杀我。」",
"15 耶和华对他说：「凡杀该隐的，必遭报七倍。」耶和华就给该隐立一个记号，免得人遇见他就杀他。",
"16 于是该隐离开耶和华的面，去住在伊甸东边挪得之地。",
"",
"——【创世记 4】",
],
[
"7 Confounded be all they that serve graven images, that boast themselves of idols: worship him, all ye gods.",
"8 Zion heard, and was glad; and the daughters of Judah rejoiced because of thy judgments, O LORD.",
"",
"——【The Book of Psalms 97】",
"",
"7 愿一切事奉雕刻的偶像、靠虚无之神自夸的，都蒙羞愧。万神哪，你们都当拜他。",
"8 耶和华啊，锡安听见你的判断就欢喜；犹大的城邑（原文是女子）也都快乐。",
"",
"——【诗篇 97】",
],
[
"17 Jehoshaphat the son of Paruah, in Issachar:",
"18 Shimei the son of Elah, in Benjamin:",
"19 Geber the son of Uri was in the country of Gilead, in the country of Sihon king of the Amorites, and of Og king of Bashan; and he was the only officer which was in the land.",
"20 Judah and Israel were many, as the sand which is by the sea in multitude, eating and drinking, and making merry.",
"21 And Solomon reigned over all kingdoms from the river unto the land of the Philistines, and unto the border of Egypt: they brought presents, and served Solomon all the days of his life.",
"",
"——【The First Book of the Kings 4】",
"",
"17 在以萨迦有帕路亚的儿子约沙法；",
"18 在便雅悯有以拉的儿子示每；",
"19 在基列地，就是从前属亚摩利王西宏和巴珊王噩之地，有乌利的儿子基别一人管理。",
"20 犹大人和以色列人如同海边的沙那样多，都吃喝快乐。",
"21 所罗门统管诸国，从大河到非利士地，直到埃及的边界。所罗门在世的日子，这些国都进贡服事他。",
"",
"——【列王记上 4】",
],
[
"5 Thou mayest not sacrifice the passover within any of thy gates, which the LORD thy God giveth thee:",
"6 But at the place which the LORD thy God shall choose to place his name in, there thou shalt sacrifice the passover at even, at the going down of the sun, at the season that thou camest forth out of Egypt.",
"7 And thou shalt roast and eat it in the place which the LORD thy God shall choose: and thou shalt turn in the morning, and go unto thy tents.",
"8 Six days thou shalt eat unleavened bread: and on the seventh day shall be a solemn assembly to the LORD thy God: thou shalt do no work therein.",
"9 Seven weeks shalt thou number unto thee: begin to number the seven weeks from such time as thou beginnest to put the sickle to the corn.",
"10 And thou shalt keep the feast of weeks unto the LORD thy God with a tribute of a freewill offering of thine hand, which thou shalt give unto the LORD thy God, according as the LORD thy God hath blessed thee:",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 16】",
"",
"5 在耶和华─你　神所赐的各城中，你不可献逾越节的祭；",
"6 只当在耶和华─你　神所选择要立为他名的居所，晚上日落的时候，乃是你出埃及的时候，献逾越节的祭。",
"7 当在耶和华─你　神所选择的地方把肉烤了吃（烤：或作煮），次日早晨就回到你的帐棚去。",
"8 你要吃无酵饼六日，第七日要向耶和华─你的　神守严肃会，不可做工。」",
"9 「你要计算七七日：从你开镰收割禾稼时算起，共计七七日。",
"10 你要照耶和华─你　神所赐你的福，手里拿着甘心祭，献在耶和华─你的　神面前，守七七节。",
"",
"——【申命记 16】",
],
[
"9 And the number of them, after their genealogy by their generations, heads of the house of their fathers, mighty men of valour, was twenty thousand and two hundred.",
"10 The sons also of Jediael; Bilhan: and the sons of Bilhan; Jeush, and Benjamin, and Ehud, and Chenaanah, and Zethan, and Tharshish, and Ahishahar.",
"11 All these the sons of Jediael, by the heads of their fathers, mighty men of valour, were seventeen thousand and two hundred soldiers, fit to go out for war and battle.",
"",
"——【The First Book of the Chronicles 7】",
"",
"9 他们都是族长，是大能的勇士。按着家谱计算，他们的子孙共有二万零二百人。",
"10 耶叠的儿子是比勒罕；比勒罕的儿子是耶乌施、便雅悯、以忽、基拿拿、细坦、他施、亚希沙哈。",
"11 这都是耶叠的儿子，都是族长，是大能的勇士；他们的子孙能上阵打仗的，共有一万七千二百人。",
"",
"——【历代志上 7】",
],
[
"17 He that passeth by, and meddleth with strife belonging not to him, is like one that taketh a dog by the ears.",
"18 As a mad man who casteth firebrands, arrows, and death,",
"19 So is the man that deceiveth his neighbour, and saith, Am not I in sport?",
"20 Where no wood is, there the fire goeth out: so where there is no talebearer, the strife ceaseth.",
"",
"——【The Proverbs 26】",
"",
"17 过路被事激动，管理不干己的争竞，好像人揪住狗耳。",
"18 人欺凌邻舍，却说：我岂不是戏耍吗？他就像疯狂的人抛掷火把、利箭，与杀人的兵器（原文是死亡）。",
"19 并入上一节",
"20 火缺了柴就必熄灭；无人传舌，争竞便止息。",
"",
"——【箴言 26】",
],
[
"46 And Jesus said, Somebody hath touched me: for I perceive that virtue is gone out of me.",
"47 And when the woman saw that she was not hid, she came trembling, and falling down before him, she declared unto him before all the people for what cause she had touched him, and how she was healed immediately.",
"",
"——【The Gospel According to Saint Luke 8】",
"",
"46 耶稣说：总有人摸我，因我觉得有能力从我身上出去。",
"47 那女人知道不能隐藏，就战战兢兢的来俯伏在耶稣脚前，把摸他的缘故和怎样立刻得好了，当着众人都说出来。",
"",
"——【路加福音 8】",
],
[
"11 And the beast that was, and is not, even he is the eighth, and is of the seven, and goeth into perdition.",
"12 And the ten horns which thou sawest are ten kings, which have received no kingdom as yet; but receive power as kings one hour with the beast.",
"13 These have one mind, and shall give their power and strength unto the beast.",
"14 These shall make war with the Lamb, and the Lamb shall overcome them: for he is Lord of lords, and King of kings: and they that are with him are called, and chosen, and faithful.",
"15 And he saith unto me, The waters which thou sawest, where the whore sitteth, are peoples, and multitudes, and nations, and tongues.",
"16 And the ten horns which thou sawest upon the beast, these shall hate the whore, and shall make her desolate and naked, and shall eat her flesh, and burn her with fire.",
"",
"——【The Revelation of Saint John the Devine 17】",
"",
"11 那先前有如今没有的兽，就是第八位；他也和那七位同列，并且归于沉沦。",
"12 你所看见的那十角就是十王；他们还没有得国，但他们一时之间要和兽同得权柄，与王一样。",
"13 他们同心合意将自己的能力、权柄给那兽。",
"14 他们与羔羊争战，羔羊必胜过他们，因为羔羊是万主之主、万王之王。同着羔羊的，就是蒙召、被选、有忠心的，也必得胜。",
"15 天使又对我说，你所看见那淫妇坐的众水，就是多民、多人、多国、多方。",
"16 你所看见的那十角与兽必恨这淫妇，使她冷落赤身，又要吃她的肉，用火将她烧尽。",
"",
"——【启示录 17】",
],
[
"3 If the clouds be full of rain, they empty themselves upon the earth: and if the tree fall toward the south, or toward the north, in the place where the tree falleth, there it shall be.",
"4 He that observeth the wind shall not sow; and he that regardeth the clouds shall not reap.",
"5 As thou knowest not what is the way of the spirit, nor how the bones do grow in the womb of her that is with child: even so thou knowest not the works of God who maketh all.",
"6 In the morning sow thy seed, and in the evening withhold not thine hand: for thou knowest not whether shall prosper, either this or that, or whether they both shall be alike good.",
"",
"——【Ecclesiastes 11】",
"",
"3 云若满了雨，就必倾倒在地上。树若向南倒，或向北倒，树倒在何处，就存在何处。",
"4 看风的，必不撒种；望云的，必不收割。",
"5 风从何道来，骨头在怀孕妇人的胎中如何长成，你尚且不得知道；这样，行万事之　神的作为，你更不得知道。",
"6 早晨要撒你的种，晚上也不要歇你的手，因为你不知道哪一样发旺；或是早撒的，或是晚撒的，或是两样都好。",
"",
"——【传道书 11】",
],
[
"1 Praise ye the LORD: for it is good to sing praises unto our God; for it is pleasant; and praise is comely.",
"2 The LORD doth build up Jerusalem: he gathereth together the outcasts of Israel.",
"3 He healeth the broken in heart, and bindeth up their wounds.",
"",
"——【The Book of Psalms 147】",
"",
"1 你们要赞美耶和华！因歌颂我们的　神为善为美；赞美的话是合宜的。",
"2 耶和华建造耶路撒冷，聚集以色列中被赶散的人。",
"3 他医好伤心的人，裹好他们的伤处。",
"",
"——【诗篇 147】",
],
[
"10 The name of the LORD is a strong tower: the righteous runneth into it, and is safe.",
"11 The rich man's wealth is his strong city, and as an high wall in his own conceit.",
"",
"——【The Proverbs 18】",
"",
"10 耶和华的名是坚固台；义人奔入便得安稳。",
"11 富足人的财物是他的坚城，在他心想，犹如高墙。",
"",
"——【箴言 18】",
],
[
"11 That ye may suck, and be satisfied with the breasts of her consolations; that ye may milk out, and be delighted with the abundance of her glory.",
"12 For thus saith the LORD, Behold, I will extend peace to her like a river, and the glory of the Gentiles like a flowing stream: then shall ye suck, ye shall be borne upon her sides, and be dandled upon her knees.",
"13 As one whom his mother comforteth, so will I comfort you; and ye shall be comforted in Jerusalem.",
"",
"——【The Book of the Prophet Isaiah 66】",
"",
"11 使你们在她安慰的怀中吃奶得饱，使他们得她丰盛的荣耀，犹如挤奶，满心喜乐。",
"12 耶和华如此说：我要使平安延及她，好像江河，使列国的荣耀延及她，如同涨溢的河。你们要从中享受（原文是咂）；你们必蒙抱在肋旁，摇弄在膝上。",
"13 母亲怎样安慰儿子，我就照样安慰你们；你们也必因（或译：在）耶路撒冷得安慰。",
"",
"——【以赛亚书 66】",
],
[
"23 And I say unto thee, Let my son go, that he may serve me: and if thou refuse to let him go, behold, I will slay thy son, even thy firstborn.",
"24 And it came to pass by the way in the inn, that the LORD met him, and sought to kill him.",
"25 Then Zipporah took a sharp stone, and cut off the foreskin of her son, and cast it at his feet, and said, Surely a bloody husband art thou to me.",
"26 So he let him go: then she said, A bloody husband thou art, because of the circumcision.",
"27 And the LORD said to Aaron, Go into the wilderness to meet Moses. And he went, and met him in the mount of God, and kissed him.",
"",
"——【The Second Book of Moses: Called Exodus 4】",
"",
"23 我对你说过：容我的儿子去，好事奉我。你还是不肯容他去。看哪，我要杀你的长子。』」",
"24 摩西在路上住宿的地方，耶和华遇见他，想要杀他。",
"25 西坡拉就拿一块火石，割下他儿子的阳皮，丢在摩西脚前，说：「你真是我的血郎了。」",
"26 这样，耶和华才放了他。西坡拉说：「你因割礼就是血郎了。」",
"27 耶和华对亚伦说：「你往旷野去迎接摩西。」他就去，在　神的山遇见摩西，和他亲嘴。",
"",
"——【出埃及记 4】",
],
[
"14 Now he hath not directed his words against me: neither will I answer him with your speeches.",
"15 They were amazed, they answered no more: they left off speaking.",
"16 When I had waited, (for they spake not, but stood still, and answered no more;)",
"",
"——【The Book of Job 32】",
"",
"14 约伯没有向我争辩；我也不用你们的话回答他。",
"15 他们惊奇不再回答，一言不发。",
"16 我岂因他们不说话，站住不再回答，仍旧等候呢？",
"",
"——【约伯记 32】",
],
[
"1 Thou shalt not sacrifice unto the LORD thy God any bullock, or sheep, wherein is blemish, or any evilfavouredness: for that is an abomination unto the LORD thy God.",
"2 If there be found among you, within any of thy gates which the LORD thy God giveth thee, man or woman, that hath wrought wickedness in the sight of the LORD thy God, in transgressing his covenant,",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 17】",
"",
"1 「凡有残疾，或有什么恶病的牛羊，你都不可献给耶和华─你的　神，因为这是耶和华─你　神所憎恶的。",
"2 「在你们中间，在耶和华─你　神所赐你的诸城中，无论那座城里，若有人，或男或女，行耶和华─你　神眼中看为恶的事，违背了他的约，",
"",
"——【申命记 17】",
],
[
"1 Now Peter and John went up together into the temple at the hour of prayer, being the ninth hour.",
"2 And a certain man lame from his mother's womb was carried, whom they laid daily at the gate of the temple which is called Beautiful, to ask alms of them that entered into the temple;",
"3 Who seeing Peter and John about to go into the temple asked an alms.",
"",
"——【The Acts of the Apostles 3】",
"",
"1 申初祷告的时候，彼得、约翰上圣殿去。",
"2 有一个人，生来是瘸腿的，天天被人抬来，放在殿的一个门口，那门名叫美门，要求进殿的人赒济。",
"3 他看见彼得、约翰将要进殿，就求他们赒济。",
"",
"——【使徒行传 3】",
],
[
"15 And they shall know that I am the LORD, when I shall scatter them among the nations, and disperse them in the countries.",
"16 But I will leave a few men of them from the sword, from the famine, and from the pestilence; that they may declare all their abominations among the heathen whither they come; and they shall know that I am the LORD.",
"17 Moreover the word of the LORD came to me, saying,",
"18 Son of man, eat thy bread with quaking, and drink thy water with trembling and with carefulness;",
"",
"——【The Book of the Prophet Ezekiel 12】",
"",
"15 我将他们四散在列国、分散在列邦的时候，他们就知道我是耶和华。",
"16 我却要留下他们几个人得免刀剑、饥荒、瘟疫，使他们在所到的各国中述说他们一切可憎的事，人就知道我是耶和华。」",
"17 耶和华的话又临到我说：",
"18 「人子啊，你吃饭必胆战，喝水必惶惶忧虑。",
"",
"——【以西结书 12】",
],
[
"5 And whosoever toucheth his bed shall wash his clothes, and bathe himself in water, and be unclean until the even.",
"6 And he that sitteth on any thing whereon he sat that hath the issue shall wash his clothes, and bathe himself in water, and be unclean until the even.",
"",
"——【The Third Book of Moses: Called Leviticus 15】",
"",
"5 凡摸那床的，必不洁净到晚上，并要洗衣服，用水洗澡。",
"6 那坐患漏症人所坐之物的，必不洁净到晚上，并要洗衣服，用水洗澡。",
"",
"——【利未记 15】",
],
[
"12 And the children of Israel took their journeys out of the wilderness of Sinai; and the cloud rested in the wilderness of Paran.",
"13 And they first took their journey according to the commandment of the LORD by the hand of Moses.",
"14 In the first place went the standard of the camp of the children of Judah according to their armies: and over his host was Nahshon the son of Amminadab.",
"15 And over the host of the tribe of the children of Issachar was Nethaneel the son of Zuar.",
"16 And over the host of the tribe of the children of Zebulun was Eliab the son of Helon.",
"17 And the tabernacle was taken down; and the sons of Gershon and the sons of Merari set forward, bearing the tabernacle.",
"",
"——【The Fourth Book of Moses: Called Numbers 10】",
"",
"12 以色列人就按站往前行，离开西奈的旷野，云彩停住在巴兰的旷野。",
"13 这是他们照耶和华借摩西所吩咐的，初次往前行。",
"14 按着军队首先往前行的是犹大营的纛。统领军队的是亚米拿达的儿子拿顺。",
"15 统领以萨迦支派军队的是苏押的儿子拿坦业。",
"16 统领西布伦支派军队的是希伦的儿子以利押。",
"17 帐幕拆卸，革顺的子孙和米拉利的子孙就抬着帐幕先往前行。",
"",
"——【民数记 10】",
],
[
"1 Hear the right, O LORD, attend unto my cry, give ear unto my prayer, that goeth not out of feigned lips.",
"2 Let my sentence come forth from thy presence; let thine eyes behold the things that are equal.",
"3 Thou hast proved mine heart; thou hast visited me in the night; thou hast tried me, and shalt find nothing; I am purposed that my mouth shall not transgress.",
"",
"——【The Book of Psalms 17】",
"",
"1 （大卫的祈祷。）耶和华啊，求你听闻公义，侧耳听我的呼吁！求你留心听我这不出于诡诈嘴唇的祈祷！",
"2 愿我的判语从你面前发出；愿你的眼睛观看公正。",
"3 你已经试验我的心；你在夜间鉴察我；你熬炼我，却找不着什么；我立志叫我口中没有过失。",
"",
"——【诗篇 17】",
],
[
"1 Ephraim feedeth on wind, and followeth after the east wind: he daily increaseth lies and desolation; and they do make a covenant with the Assyrians, and oil is carried into Egypt.",
"2 The LORD hath also a controversy with Judah, and will punish Jacob according to his ways; according to his doings will he recompense him.",
"3 He took his brother by the heel in the womb, and by his strength he had power with God:",
"4 Yea, he had power over the angel, and prevailed: he wept, and made supplication unto him: he found him in Beth–el, and there he spake with us;",
"5 Even the LORD God of hosts; the LORD is his memorial.",
"",
"——【Hosea 12】",
"",
"1 以法莲吃风，且追赶东风，时常增添虚谎和强暴，与亚述立约，把油送到埃及。",
"2 耶和华与犹大争辩，必照雅各所行的惩罚他，按他所做的报应他。",
"3 他在腹中抓住哥哥的脚跟，壮年的时候与　神较力，",
"4 与天使较力，并且得胜，哭泣恳求，在伯特利遇见耶和华。耶和华─万军之　神在那里晓谕我们以色列人；耶和华是他可记念的名。",
"5 并入上节",
"",
"——【何西阿书 12】",
],
[
"1 Hear my prayer, O LORD, give ear to my supplications: in thy faithfulness answer me, and in thy righteousness.",
"2 And enter not into judgment with thy servant: for in thy sight shall no man living be justified.",
"3 For the enemy hath persecuted my soul; he hath smitten my life down to the ground; he hath made me to dwell in darkness, as those that have been long dead.",
"4 Therefore is my spirit overwhelmed within me; my heart within me is desolate.",
"5 I remember the days of old; I meditate on all thy works; I muse on the work of thy hands.",
"6 I stretch forth my hands unto thee: my soul thirsteth after thee, as a thirsty land. Selah.",
"",
"——【The Book of Psalms 143】",
"",
"1 （大卫的诗。）耶和华啊，求你听我的祷告，留心听我的恳求，凭你的信实和公义应允我。",
"2 求你不要审问仆人；因为在你面前，凡活着的人没有一个是义的。",
"3 原来仇敌逼迫我，将我打倒在地，使我住在幽暗之处，像死了许久的人一样。",
"4 所以，我的灵在我里面发昏；我的心在我里面悽惨。",
"5 我追想古时之日，思想你的一切作为，默念你手的工作。",
"6 我向你举手；我的心渴想你，如干旱之地盼雨一样。（细拉）",
"",
"——【诗篇 143】",
],
[
"21 Also take no heed unto all words that are spoken; lest thou hear thy servant curse thee:",
"22 For oftentimes also thine own heart knoweth that thou thyself likewise hast cursed others.",
"23 All this have I proved by wisdom: I said, I will be wise; but it was far from me.",
"24 That which is far off, and exceeding deep, who can find it out?",
"25 I applied mine heart to know, and to search, and to seek out wisdom, and the reason of things, and to know the wickedness of folly, even of foolishness and madness:",
"26 And I find more bitter than death the woman, whose heart is snares and nets, and her hands as bands: whoso pleaseth God shall escape from her; but the sinner shall be taken by her.",
"",
"——【Ecclesiastes 7】",
"",
"21 人所说的一切话，你不要放在心上，恐怕听见你的仆人咒诅你。",
"22 因为你心里知道，自己也曾屡次咒诅别人。",
"23 我曾用智慧试验这一切事；我说，要得智慧，智慧却离我远。",
"24 万事之理，离我甚远，而且最深，谁能测透呢？",
"25 我转念，一心要知道，要考察，要寻求智慧和万事的理由；又要知道邪恶为愚昧，愚昧为狂妄。",
"26 我得知有等妇人比死还苦：她的心是网罗，手是锁链。凡蒙　神喜悦的人必能躲避她；有罪的人却被她缠住了。",
"",
"——【传道书 7】",
],
[
"27 Out of the spoils won in battles did they dedicate to maintain the house of the LORD.",
"28 And all that Samuel the seer, and Saul the son of Kish, and Abner the son of Ner, and Joab the son of Zeruiah, had dedicated; and whosoever had dedicated any thing, it was under the hand of Shelomith, and of his brethren.",
"29 Of the Izharites, Chenaniah and his sons were for the outward business over Israel, for officers and judges.",
"30 And of the Hebronites, Hashabiah and his brethren, men of valour, a thousand and seven hundred, were officers among them of Israel on this side Jordan westward in all the business of the LORD, and in the service of the king.",
"",
"——【The First Book of the Chronicles 26】",
"",
"27 他们将争战时所夺的财物分别为圣，以备修造耶和华的殿。",
"28 先见撒母耳、基士的儿子扫罗、尼珥的儿子押尼珥、洗鲁雅的儿子约押所分别为圣的物都归示罗密和他的弟兄掌管。",
"29 以斯哈族有基拿尼雅和他众子作官长和士师，管理以色列的外事。",
"30 希伯伦族有哈沙比雅和他弟兄一千七百人，都是壮士，在约旦河西、以色列地办理耶和华与王的事。",
"",
"——【历代志上 26】",
],
[
"1 The burden of Nineveh. The book of the vision of Nahum the Elkoshite.",
"2 God is jealous, and the LORD revengeth; the LORD revengeth, and is furious; the LORD will take vengeance on his adversaries, and he reserveth wrath for his enemies.",
"3 The LORD is slow to anger, and great in power, and will not at all acquit the wicked: the LORD hath his way in the whirlwind and in the storm, and the clouds are the dust of his feet.",
"4 He rebuketh the sea, and maketh it dry, and drieth up all the rivers: Bashan languisheth, and Carmel, and the flower of Lebanon languisheth.",
"5 The mountains quake at him, and the hills melt, and the earth is burned at his presence, yea, the world, and all that dwell therein.",
"",
"——【Nahum 1】",
"",
"1 论尼尼微的默示，就是伊勒歌斯人那鸿所得的默示。",
"2 耶和华是忌邪施报的　神。耶和华施报大有忿怒；向他的敌人施报，向他的仇敌怀怒。",
"3 耶和华不轻易发怒，大有能力，万不以有罪的为无罪。他乘旋风和暴风而来，云彩为他脚下的尘土。",
"4 他斥责海，使海干了，使一切江河干涸。巴珊和迦密的树林衰残；黎巴嫩的花草也衰残了。",
"5 大山因他震动；小山也都消化。大地在他面前突起；世界和住在其间的也都如此。",
"",
"——【那鸿书 1】",
],
[
"15 And have hope toward God, which they themselves also allow, that there shall be a resurrection of the dead, both of the just and unjust.",
"16 And herein do I exercise myself, to have always a conscience void of offence toward God, and toward men.",
"17 Now after many years I came to bring alms to my nation, and offerings.",
"",
"——【The Acts of the Apostles 24】",
"",
"15 并且靠着　神，盼望死人，无论善恶，都要复活，就是他们自己也有这个盼望。",
"16 我因此自己勉励，对　神对人，常存无亏的良心。",
"17 过了几年，我带着赒济本国的捐项和供献的物上去。",
"",
"——【使徒行传 24】",
],
[
"9 For they shall be an ornament of grace unto thy head, and chains about thy neck.",
"10 My son, if sinners entice thee, consent thou not.",
"11 If they say, Come with us, let us lay wait for blood, let us lurk privily for the innocent without cause:",
"12 Let us swallow them up alive as the grave; and whole, as those that go down into the pit:",
"13 We shall find all precious substance, we shall fill our houses with spoil:",
"14 Cast in thy lot among us; let us all have one purse:",
"",
"——【The Proverbs 1】",
"",
"9 因为这要作你头上的华冠，你项上的金链。",
"10 我儿，恶人若引诱你，你不可随从。",
"11 他们若说：你与我们同去，我们要埋伏流人之血，要蹲伏害无罪之人；",
"12 我们好像阴间，把他们活活吞下；他们如同下坑的人，被我们囫囵吞了；",
"13 我们必得各样宝物，将所掳来的，装满房屋；",
"14 你与我们大家同分，我们共用一个囊袋；",
"",
"——【箴言 1】",
],
[
"1 Paul, and Silvanus, and Timotheus, unto the church of the Thessalonians which is in God the Father and in the Lord Jesus Christ: Grace be unto you, and peace, from God our Father, and the Lord Jesus Christ.",
"2 We give thanks to God always for you all, making mention of you in our prayers;",
"",
"——【The First Epistle of Paul the Apostle to the Thessalonians 1】",
"",
"1 保罗、西拉、提摩太写信给帖撒罗尼迦在父　神和主耶稣基督里的教会。愿恩惠、平安归与你们！",
"2 我们为你们众人常常感谢　神，祷告的时候提到你们，",
"",
"——【帖撒罗尼迦前书 1】",
],
[
"8 And rent the kingdom away from the house of David, and gave it thee: and yet thou hast not been as my servant David, who kept my commandments, and who followed me with all his heart, to do that only which was right in mine eyes;",
"9 But hast done evil above all that were before thee: for thou hast gone and made thee other gods, and molten images, to provoke me to anger, and hast cast me behind thy back:",
"10 Therefore, behold, I will bring evil upon the house of Jeroboam, and will cut off from Jeroboam him that pisseth against the wall, and him that is shut up and left in Israel, and will take away the remnant of the house of Jeroboam, as a man taketh away dung, till it be all gone.",
"11 Him that dieth of Jeroboam in the city shall the dogs eat; and him that dieth in the field shall the fowls of the air eat: for the LORD hath spoken it.",
"",
"——【The First Book of the Kings 14】",
"",
"8 将国从大卫家夺回赐给你；你却不效法我仆人大卫，遵守我的诫命，一心顺从我，行我眼中看为正的事。",
"9 你竟行恶，比那在你以先的更甚，为自己立了别神，铸了偶像，惹我发怒，将我丢在背后。",
"10 因此，我必使灾祸临到耶罗波安的家，将属耶罗波安的男丁，无论困住的、自由的都从以色列中剪除，必除尽耶罗波安的家，如人除尽粪土一般。",
"11 凡属耶罗波安的人，死在城中的必被狗吃，死在田野的必被空中的鸟吃。这是耶和华说的。』",
"",
"——【列王记上 14】",
],
];
