var bible31_global=[
[
"1 The burden which Habakkuk the prophet did see.",
"2 O LORD, how long shall I cry, and thou wilt not hear! even cry out unto thee of violence, and thou wilt not save!",
"3 Why dost thou shew me iniquity, and cause me to behold grievance? for spoiling and violence are before me: and there are that raise up strife and contention.",
"4 Therefore the law is slacked, and judgment doth never go forth: for the wicked doth compass about the righteous; therefore wrong judgment proceedeth.",
"5 Behold ye among the heathen, and regard, and wonder marvellously: for I will work a work in your days, which ye will not believe, though it be told you.",
"",
"——【Habakkuk 1】",
"",
"1 先知哈巴谷所得的默示。",
"2 他说：耶和华啊！我呼求你，你不应允，要到几时呢？我因强暴哀求你，你还不拯救。",
"3 你为何使我看见罪孽？你为何看著奸恶而不理呢？毁灭和强暴在我面前，又起了争端和相斗的事。",
"4 因此律法放松，公理也不显明，恶人围困义人，所以公理显然颠倒。",
"5 耶和华说：你们要向列国中观看，大大惊奇；因为在你们的时候，我行一件事，虽有人告诉你们，你们总是不信。",
"",
"——【哈巴谷书 1】",
],
[
"1 The word of the LORD that came to Jeremiah the prophet against the Philistines, before that Pharaoh smote Gaza.",
"2 Thus saith the LORD; Behold, waters rise up out of the north, and shall be an overflowing flood, and shall overflow the land, and all that is therein; the city, and them that dwell therein: then the men shall cry, and all the inhabitants of the land shall howl.",
"3 At the noise of the stamping of the hoofs of his strong horses, at the rushing of his chariots, and at the rumbling of his wheels, the fathers shall not look back to their children for feebleness of hands;",
"4 Because of the day that cometh to spoil all the Philistines, and to cut off from Tyrus and Zidon every helper that remaineth: for the LORD will spoil the Philistines, the remnant of the country of Caphtor.",
"5 Baldness is come upon Gaza; Ashkelon is cut off with the remnant of their valley: how long wilt thou cut thyself?",
"6 O thou sword of the LORD, how long will it be ere thou be quiet? put up thyself into thy scabbard, rest, and be still.",
"",
"——【The Book of the Prophet Jeremiah 47】",
"",
"1 法老攻击迦萨之先，有耶和华论非利士人的话临到先知耶利米。",
"2 耶和华如此说：有水从北方发起，成为涨溢的河，要涨过遍地和其中所有的，并城和其中所住的。人必呼喊；境内的居民都必哀号。",
"3 听见敌人壮马蹄跳的响声和战车隆隆、车轮轰轰；为父的手就发软，不回头看顾儿女。",
"4 因为日子将到，要毁灭一切非利士人，剪除帮助推罗、西顿所剩下的人。原来耶和华必毁灭非利士人，就是迦斐托海岛余剩的人。",
"5 迦萨成了光秃；平原中所剩的亚实基伦归于无有。你用刀划身，要到几时呢？",
"6 耶和华的刀剑哪，你到几时才止息呢？你要入鞘，安靖不动。",
"",
"——【耶利米书 47】",
],
[
"13 Otherwise I should have wrought falsehood against mine own life: for there is no matter hid from the king, and thou thyself wouldest have set thyself against me.",
"14 Then said Joab, I may not tarry thus with thee. And he took three darts in his hand, and thrust them through the heart of Absalom, while he was yet alive in the midst of the oak.",
"15 And ten young men that bare Joab's armour compassed about and smote Absalom, and slew him.",
"16 And Joab blew the trumpet, and the people returned from pursuing after Israel: for Joab held back the people.",
"17 And they took Absalom, and cast him into a great pit in the wood, and laid a very great heap of stones upon him: and all Israel fled every one to his tent.",
"",
"——【The Second Book of Samuel 18】",
"",
"13 我若妄为害了他的性命，就是你自己也必与我为敌（原来，无论何事都瞒不过王。）」",
"14 约押说：「我不能与你留连。」约押手拿三杆短枪，趁押沙龙在橡树上还活著，就刺透他的心。",
"15 给约押拿兵器的十个少年人围绕押沙龙，将他杀死。",
"16 约押吹角，拦阻众人，他们就回来，不再追赶以色列人。",
"17 他们将押沙龙丢在林中一个大坑里，上头堆起一大堆石头。以色列众人都逃跑，各回各家去了。",
"",
"——【撒母耳记下 18】",
],
[
"3 I taught Ephraim also to go, taking them by their arms; but they knew not that I healed them.",
"4 I drew them with cords of a man, with bands of love: and I was to them as they that take off the yoke on their jaws, and I laid meat unto them.",
"5 He shall not return into the land of Egypt, but the Assyrian shall be his king, because they refused to return.",
"6 And the sword shall abide on his cities, and shall consume his branches, and devour them, because of their own counsels.",
"7 And my people are bent to backsliding from me: though they called them to the most High, none at all would exalt him.",
"",
"——【Hosea 11】",
"",
"3 我原教导以法莲行走，用膀臂抱著他们，他们却不知道是我医治他们。",
"4 我用慈绳（慈：原文是人的）爱索牵引他们；我待他们如人放松牛的两腮夹板，把粮食放在他们面前。",
"5 他们必不归回埃及地，亚述人却要作他们的王，因他们不肯归向我。",
"6 刀剑必临到他们的城邑，毁坏门闩，把人吞灭，都因他们随从自己的计谋。",
"7 我的民偏要背道离开我；众先知虽然招呼他们归向至上的主，却无人尊崇主。",
"",
"——【何西阿书 11】",
],
[
"1 Now it came to pass in the days of Ahasuerus, (this is Ahasuerus which reigned, from India even unto Ethiopia, over an hundred and seven and twenty provinces:)",
"2 That in those days, when the king Ahasuerus sat on the throne of his kingdom, which was in Shushan the palace,",
"3 In the third year of his reign, he made a feast unto all his princes and his servants; the power of Persia and Media, the nobles and princes of the provinces, being before him:",
"4 When he shewed the riches of his glorious kingdom and the honour of his excellent majesty many days, even an hundred and fourscore days.",
"5 And when these days were expired, the king made a feast unto all the people that were present in Shushan the palace, both unto great and small, seven days, in the court of the garden of the king's palace;",
"",
"——【The Book of Esther 1】",
"",
"1 亚哈随鲁作王，从印度直到古实，统管一百二十七省。",
"2 亚哈随鲁王在书珊城的宫登基；",
"3 在位第三年，为他一切首领臣仆设摆筵席，有波斯和玛代的权贵，就是各省的贵冑与首领，在他面前。",
"4 他把他荣耀之国的丰富和他美好威严的尊贵给他们看了许多日，就是一百八十日。",
"5 这日子满了，又为所有住书珊城的大小人民在御园的院子里设摆筵席七日。",
"",
"——【以斯帖记 1】",
],
[
"13 And one of the company said unto him, Master, speak to my brother, that he divide the inheritance with me.",
"14 And he said unto him, Man, who made me a judge or a divider over you?",
"15 And he said unto them, Take heed, and beware of covetousness: for a man's life consisteth not in the abundance of the things which he possesseth.",
"16 And he spake a parable unto them, saying, The ground of a certain rich man brought forth plentifully:",
"",
"——【The Gospel According to Saint Luke 12】",
"",
"13 众人中有一个人对耶稣说：夫子！请你吩咐我的兄长和我分开家业。",
"14 耶稣说：你这个人！谁立我作你们断事的官，给你们分家业呢？",
"15 于是对众人说：你们要谨慎自守，免去一切的贪心，因为人的生命不在乎家道丰富。",
"16 就用比喻对他们说：有一个财主田产丰盛；",
"",
"——【路加福音 12】",
],
[
"42 And he said unto Jesus, Lord, remember me when thou comest into thy kingdom.",
"43 And Jesus said unto him, Verily I say unto thee, To day shalt thou be with me in paradise.",
"44 And it was about the sixth hour, and there was a darkness over all the earth until the ninth hour.",
"45 And the sun was darkened, and the veil of the temple was rent in the midst.",
"46 And when Jesus had cried with a loud voice, he said, Father, into thy hands I commend my spirit: and having said thus, he gave up the ghost.",
"47 Now when the centurion saw what was done, he glorified God, saying, Certainly this was a righteous man.",
"",
"——【The Gospel According to Saint Luke 23】",
"",
"42 就说：耶稣啊，你得国降临的时候，求你记念我！",
"43 耶稣对他说：我实在告诉你，今日你要同我在乐园里了。",
"44 那时约有午正，遍地都黑暗了，直到申初，",
"45 日头变黑了；殿里的幔子从当中裂为两半。",
"46 耶稣大声喊著说：父啊！我将我的灵魂交在你手里。说了这话，气就断了。",
"47 百夫长看见所成的事，就归荣耀与　神，说：这真是个义人！",
"",
"——【路加福音 23】",
],
[
"9 And he that bade thee and him come and say to thee, Give this man place; and thou begin with shame to take the lowest room.",
"10 But when thou art bidden, go and sit down in the lowest room; that when he that bade thee cometh, he may say unto thee, Friend, go up higher: then shalt thou have worship in the presence of them that sit at meat with thee.",
"11 For whosoever exalteth himself shall be abased; and he that humbleth himself shall be exalted.",
"12 Then said he also to him that bade him, When thou makest a dinner or a supper, call not thy friends, nor thy brethren, neither thy kinsmen, nor thy rich neighbours; lest they also bid thee again, and a recompence be made thee.",
"",
"——【The Gospel According to Saint Luke 14】",
"",
"9 那请你们的人前来对你说：让座给这一位吧！你就羞羞惭惭的退到末位上去了。",
"10 你被请的时候，就去坐在末位上，好叫那请你的人来对你说：朋友，请上坐。那时，你在同席的人面前就有光彩了。",
"11 因为，凡自高的，必降为卑，自卑的，必升为高。",
"12 耶稣又对请他的人说：你摆设午饭或晚饭，不要请你的朋友、弟兄、亲属，和富足的邻舍，恐怕他们也请你，你就得了报答。",
"",
"——【路加福音 14】",
],
[
"9 What shall therefore the lord of the vineyard do? he will come and destroy the husbandmen, and will give the vineyard unto others.",
"10 And have ye not read this scripture; The stone which the builders rejected is become the head of the corner:",
"11 This was the Lord's doing, and it is marvellous in our eyes?",
"",
"——【The Gospel According to Saint Mark 12】",
"",
"9 这样，葡萄园的主人要怎么办呢？他要来除灭那些园户，将葡萄园转给别人。",
"10 经上写著说：匠人所弃的石头，已作了房角的头块石头。",
"11 这是主所作的，在我们眼中看为希奇。这经你们没有念过吗？",
"",
"——【马可福音 12】",
],
[
"2 For the king said to Joab the captain of the host, which was with him, Go now through all the tribes of Israel, from Dan even to Beer–sheba, and number ye the people, that I may know the number of the people.",
"3 And Joab said unto the king, Now the LORD thy God add unto the people, how many soever they be, an hundredfold, and that the eyes of my lord the king may see it: but why doth my lord the king delight in this thing?",
"4 Notwithstanding the king's word prevailed against Joab, and against the captains of the host. And Joab and the captains of the host went out from the presence of the king, to number the people of Israel.",
"5 And they passed over Jordan, and pitched in Aroer, on the right side of the city that lieth in the midst of the river of Gad, and toward Jazer:",
"6 Then they came to Gilead, and to the land of Tahtim–hodshi; and they came to Dan–jaan, and about to Zidon,",
"",
"——【The Second Book of Samuel 24】",
"",
"2 大卫就吩咐跟随他的元帅约押说：「你去走遍以色列众支派，从但直到别是巴，数点百姓，我好知道他们的数目。」",
"3 约押对王说：「无论百姓多少，愿耶和华─你的　神再加增百倍，使我主我王亲眼得见。我主我王何必喜悦行这事呢？」",
"4 但王的命令胜过约押和众军长。约押和众军长就从王面前出去，数点以色列的百姓。",
"5 他们过了约旦河，在迦得谷中、城的右边亚罗珥安营，与雅谢相对，",
"6 又到了基列和他停‧合示地，又到了但‧雅安，绕到西顿，",
"",
"——【撒母耳记下 24】",
],
[
"17 Thou shalt not kill.",
"18 Neither shalt thou commit adultery.",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 5】",
"",
"17 「『不可杀人。",
"18 「『不可奸淫。",
"",
"——【申命记 5】",
],
[
"1 In Judah is God known: his name is great in Israel.",
"2 In Salem also is his tabernacle, and his dwelling place in Zion.",
"3 There brake he the arrows of the bow, the shield, and the sword, and the battle. Selah.",
"4 Thou art more glorious and excellent than the mountains of prey.",
"5 The stouthearted are spoiled, they have slept their sleep: and none of the men of might have found their hands.",
"6 At thy rebuke, O God of Jacob, both the chariot and horse are cast into a dead sleep.",
"",
"——【The Book of Psalms 76】",
"",
"1 （亚萨的诗歌，交与伶长。用丝弦的乐器。）在犹大，　神为人所认识；在以色列，他的名为大。",
"2 在撒冷有他的帐幕；在锡安有他的居所。",
"3 他在那里折断弓上的火箭，并盾牌、刀剑，和争战的兵器。（细拉）",
"4 你从有野食之山而来，有光华和荣美。",
"5 心中勇敢的人都被抢夺；他们睡了长觉，没有一个英雄能措手。",
"6 雅各的　神啊，你的斥责一发，坐车的、骑马的都沉睡了。",
"",
"——【诗篇 76】",
],
[
"30 And Eltolad, and Chesil, and Hormah,",
"31 And Ziklag, and Madmannah, and Sansannah,",
"32 And Lebaoth, and Shilhim, and Ain, and Rimmon: all the cities are twenty and nine, with their villages:",
"",
"——【The Book of Joshua 15】",
"",
"30 伊勒多腊、基失、何珥玛、",
"31 洗革拉、麦玛拿、三撒拿、",
"32 利巴勿、实忻、亚因、临门，共二十九座城，还有属城的村庄。",
"",
"——【约书亚记 15】",
],
[
"1 Be ye followers of me, even as I also am of Christ.",
"2 Now I praise you, brethren, that ye remember me in all things, and keep the ordinances, as I delivered them to you.",
"3 But I would have you know, that the head of every man is Christ; and the head of the woman is the man; and the head of Christ is God.",
"4 Every man praying or prophesying, having his head covered, dishonoureth his head.",
"",
"——【The First Epistle of Paul the Apostle to the Corinthians 11】",
"",
"1 你们该效法我，像我效法基督一样。",
"2 我称赞你们，因你们凡事记念我，又坚守我所传给你们的。",
"3 我愿意你们知道，基督是各人的头；男人是女人的头；　神是基督的头。",
"4 凡男人祷告或是讲道（或作：说预言；下同），若蒙著头，就羞辱自己的头。",
"",
"——【哥林多前书 11】",
],
[
"1 And Joshua rose early in the morning; and they removed from Shittim, and came to Jordan, he and all the children of Israel, and lodged there before they passed over.",
"2 And it came to pass after three days, that the officers went through the host;",
"",
"——【The Book of Joshua 3】",
"",
"1 约书亚清早起来，和以色列众人都离开什亭，来到约旦河，就住在那里，等候过河。",
"2 过了三天，官长走遍营中，",
"",
"——【约书亚记 3】",
],
[
"7 Remember, and forget not, how thou provokedst the LORD thy God to wrath in the wilderness: from the day that thou didst depart out of the land of Egypt, until ye came unto this place, ye have been rebellious against the LORD.",
"8 Also in Horeb ye provoked the LORD to wrath, so that the LORD was angry with you to have destroyed you.",
"9 When I was gone up into the mount to receive the tables of stone, even the tables of the covenant which the LORD made with you, then I abode in the mount forty days and forty nights, I neither did eat bread nor drink water:",
"10 And the LORD delivered unto me two tables of stone written with the finger of God; and on them was written according to all the words, which the LORD spake with you in the mount out of the midst of the fire in the day of the assembly.",
"11 And it came to pass at the end of forty days and forty nights, that the LORD gave me the two tables of stone, even the tables of the covenant.",
"12 And the LORD said unto me, Arise, get thee down quickly from hence; for thy people which thou hast brought forth out of Egypt have corrupted themselves; they are quickly turned aside out of the way which I commanded them; they have made them a molten image.",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 9】",
"",
"7 你当记念不忘，你在旷野怎样惹耶和华─你　神发怒。自从你出了埃及地的那日，直到你们来到这地方，你们时常悖逆耶和华。",
"8 你们在何烈山又惹耶和华发怒；他恼怒你们，要灭绝你们。",
"9 我上了山，要领受两块石版，就是耶和华与你们立约的版。那时我在山上住了四十昼夜，没有吃饭，也没有喝水。",
"10 耶和华把那两块石版交给我，是　神用指头写的。版上所写的是照耶和华在大会的日子、在山上、从火中对你们所说的一切话。",
"11 过了四十昼夜，耶和华把那两块石版，就是约版，交给我。",
"12 对我说：『你起来，赶快下去！因为你从埃及领出来的百姓已经败坏了自己；他们快快的偏离了我所吩咐的道，为自己铸成了偶像。』",
"",
"——【申命记 9】",
],
[
"15 Whom, though I were righteous, yet would I not answer, but I would make supplication to my judge.",
"16 If I had called, and he had answered me; yet would I not believe that he had hearkened unto my voice.",
"17 For he breaketh me with a tempest, and multiplieth my wounds without cause.",
"18 He will not suffer me to take my breath, but filleth me with bitterness.",
"",
"——【The Book of Job 9】",
"",
"15 我虽有义，也不回答他，只要向那审判我的恳求。",
"16 我若呼籲，他应允我；我仍不信他真听我的声音。",
"17 他用暴风折断我，无故地加增我的损伤。",
"18 我就是喘一口气，他都不容，倒使我满心苦恼。",
"",
"——【约伯记 9】",
],
[
"5 Then said I, Woe is me! for I am undone; because I am a man of unclean lips, and I dwell in the midst of a people of unclean lips: for mine eyes have seen the King, the LORD of hosts.",
"6 Then flew one of the seraphims unto me, having a live coal in his hand, which he had taken with the tongs from off the altar:",
"7 And he laid it upon my mouth, and said, Lo, this hath touched thy lips; and thine iniquity is taken away, and thy sin purged.",
"8 Also I heard the voice of the Lord, saying, Whom shall I send, and who will go for us? Then said I, Here am I; send me.",
"9 And he said, Go, and tell this people, Hear ye indeed, but understand not; and see ye indeed, but perceive not.",
"",
"——【The Book of the Prophet Isaiah 6】",
"",
"5 那时我说：「祸哉！我灭亡了！因为我是嘴唇不洁的人，又住在嘴唇不洁的民中，又因我眼见大君王─万军之耶和华。」",
"6 有一撒拉弗飞到我跟前，手里拿着红炭，是用火剪从坛上取下来的，",
"7 将炭沾我的口，说：「看哪，这炭沾了你的嘴，你的罪孽便除掉，你的罪恶就赦免了。」",
"8 我又听见主的声音说：「我可以差遣谁呢？谁肯为我们去呢？」我说：「我在这里，请差遣我！」",
"9 他说：「你去告诉这百姓说：你们听是要听见，却不明白；看是要看见，却不晓得。",
"",
"——【以赛亚书 6】",
],
[
"2 For by it the elders obtained a good report.",
"3 Through faith we understand that the worlds were framed by the word of God, so that things which are seen were not made of things which do appear.",
"4 By faith Abel offered unto God a more excellent sacrifice than Cain, by which he obtained witness that he was righteous, God testifying of his gifts: and by it he being dead yet speaketh.",
"",
"——【The Epistle of Paul the Apostle to the Hebrews 11】",
"",
"2 古人在这信上得了美好的证据。",
"3 我们因著信，就知道诸世界是借　神话造成的；这样，所看见的，并不是从显然之物造出来的。",
"4 亚伯因著信，献祭与　神，比该隐所献的更美，因此便得了称义的见证，就是　神指他礼物作的见证。他虽然死了，却因这信，仍旧说话。",
"",
"——【希伯来书 11】",
],
[
"6 And Elihu the son of Barachel the Buzite answered and said, I am young, and ye are very old; wherefore I was afraid, and durst not shew you mine opinion.",
"7 I said, Days should speak, and multitude of years should teach wisdom.",
"8 But there is a spirit in man: and the inspiration of the Almighty giveth them understanding.",
"9 Great men are not always wise: neither do the aged understand judgment.",
"10 Therefore I said, Hearken to me; I also will shew mine opinion.",
"11 Behold, I waited for your words; I gave ear to your reasons, whilst ye searched out what to say.",
"",
"——【The Book of Job 32】",
"",
"6 布西人巴拉迦的儿子以利户回答说：我年轻，你们老迈；因此我退让，不敢向你们陈说我的意见。",
"7 我说，年老的当先说话；寿高的当以智慧教训人。",
"8 但在人里面有灵；全能者的气使人有聪明。",
"9 尊贵的不都有智慧；寿高的不都能明白公平。",
"10 因此我说：你们要听我言；我也要陈说我的意见。",
"11 你们查究所要说的话；那时我等候你们的话，侧耳听你们的辩论，",
"",
"——【约伯记 32】",
],
[
"7 And the unicorns shall come down with them, and the bullocks with the bulls; and their land shall be soaked with blood, and their dust made fat with fatness.",
"8 For it is the day of the LORD'S vengeance, and the year of recompences for the controversy of Zion.",
"",
"——【The Book of the Prophet Isaiah 34】",
"",
"7 野牛、牛犊，和公牛要一同下来。他们的地喝醉了血；他们的尘土因脂油肥润。",
"8 因耶和华有报仇之日，为锡安的争辩有报应之年。",
"",
"——【以赛亚书 34】",
],
[
"5 Behold, thou shalt call a nation that thou knowest not, and nations that knew not thee shall run unto thee because of the LORD thy God, and for the Holy One of Israel; for he hath glorified thee.",
"6 Seek ye the LORD while he may be found, call ye upon him while he is near:",
"7 Let the wicked forsake his way, and the unrighteous man his thoughts: and let him return unto the LORD, and he will have mercy upon him; and to our God, for he will abundantly pardon.",
"",
"——【The Book of the Prophet Isaiah 55】",
"",
"5 你素不认识的国民，你也必召来；素不认识你的国民也必向你奔跑，都因耶和华─你的　神以色列的圣者，因为他已经荣耀你。",
"6 当趁耶和华可寻找的时候寻找他，相近的时候求告他。",
"7 恶人当离弃自己的道路；不义的人当除掉自己的意念。归向耶和华，耶和华就必怜恤他；当归向我们的　神，因为　神必广行赦免。",
"",
"——【以赛亚书 55】",
],
[
"17 Leah was tender eyed; but Rachel was beautiful and well favoured.",
"18 And Jacob loved Rachel; and said, I will serve thee seven years for Rachel thy younger daughter.",
"19 And Laban said, It is better that I give her to thee, than that I should give her to another man: abide with me.",
"20 And Jacob served seven years for Rachel; and they seemed unto him but a few days, for the love he had to her.",
"21 And Jacob said unto Laban, Give me my wife, for my days are fulfilled, that I may go in unto her.",
"",
"——【The First Book of Moses: Called Genesis 29】",
"",
"17 利亚的眼睛没有神气，拉结却生得美貌俊秀。",
"18 雅各爱拉结，就说：「我愿为你小女儿拉结服事你七年。」",
"19 拉班说：「我把她给你，胜似给别人，你与我同住吧！」",
"20 雅各就为拉结服事了七年；他因为深爱拉结，就看这七年如同几天。",
"21 雅各对拉班说：「日期已经满了，求你把我的妻子给我，我好与她同房。」",
"",
"——【创世记 29】",
],
[
"12 Moreover also I gave them my sabbaths, to be a sign between me and them, that they might know that I am the LORD that sanctify them.",
"13 But the house of Israel rebelled against me in the wilderness: they walked not in my statutes, and they despised my judgments, which if a man do, he shall even live in them; and my sabbaths they greatly polluted: then I said, I would pour out my fury upon them in the wilderness, to consume them.",
"14 But I wrought for my name's sake, that it should not be polluted before the heathen, in whose sight I brought them out.",
"15 Yet also I lifted up my hand unto them in the wilderness, that I would not bring them into the land which I had given them, flowing with milk and honey, which is the glory of all lands;",
"16 Because they despised my judgments, and walked not in my statutes, but polluted my sabbaths: for their heart went after their idols.",
"17 Nevertheless mine eye spared them from destroying them, neither did I make an end of them in the wilderness.",
"",
"——【The Book of the Prophet Ezekiel 20】",
"",
"12 又将我的安息日赐给他们，好在我与他们中间为证据，使他们知道我─耶和华是叫他们成为圣的。",
"13 以色列家却在旷野悖逆我，不顺从我的律例，厌弃我的典章（人若遵行就必因此活著），大大干犯我的安息日。「我就说，要在旷野将我的忿怒倾在他们身上，灭绝他们。",
"14 我却为我名的缘故，没有这样行，免得我的名在我领他们出埃及的列国人眼前被亵渎。",
"15 并且我在旷野向他们起誓，必不领他们进入我所赐给他们流奶与蜜之地（那地在万国中是有荣耀的）；",
"16 因为他们厌弃我的典章，不顺从我的律例，干犯我的安息日，他们的心随从自己的偶像。",
"17 虽然如此，我眼仍顾惜他们，不毁灭他们，不在旷野将他们灭绝净尽。",
"",
"——【以西结书 20】",
],
[
"7 As ye also learned of Epaphras our dear fellowservant, who is for you a faithful minister of Christ;",
"8 Who also declared unto us your love in the Spirit.",
"9 For this cause we also, since the day we heard it, do not cease to pray for you, and to desire that ye might be filled with the knowledge of his will in all wisdom and spiritual understanding;",
"10 That ye might walk worthy of the Lord unto all pleasing, being fruitful in every good work, and increasing in the knowledge of God;",
"11 Strengthened with all might, according to his glorious power, unto all patience and longsuffering with joyfulness;",
"12 Giving thanks unto the Father, which hath made us meet to be partakers of the inheritance of the saints in light:",
"",
"——【The Epistle of Paul the Apostle to the Colossians 1】",
"",
"7 正如你们从我们所亲爱、一同作仆人的以巴弗所学的。他为我们（有古卷：你们）作了基督忠心的执事，",
"8 也把你们因圣灵所存的爱心告诉了我们。",
"9 因此，我们自从听见的日子，也就为你们不住的祷告祈求，愿你们在一切属灵的智慧悟性上，满心知道　神的旨意；",
"10 好叫你们行事为人对得起主，凡事蒙他喜悦，在一切善事上结果子，渐渐的多知道　神；",
"11 照他荣耀的权能，得以在各样的力上加力，好叫你们凡事欢欢喜喜的忍耐宽容；",
"12 又感谢父，叫我们能与众圣徒在光明中同得基业。",
"",
"——【歌罗西书 1】",
],
[
"5 And there fell ten portions to Manasseh, beside the land of Gilead and Bashan, which were on the other side Jordan;",
"6 Because the daughters of Manasseh had an inheritance among his sons: and the rest of Manasseh's sons had the land of Gilead.",
"",
"——【The Book of Joshua 17】",
"",
"5 除了约旦河东的基列和巴珊地之外，还有十分地归玛拿西，",
"6 因为玛拿西的孙女们在玛拿西的孙子中得了产业。基列地是属玛拿西其余的子孙。",
"",
"——【约书亚记 17】",
],
[
"3 Now these are the things wherein Solomon was instructed for the building of the house of God. The length by cubits after the first measure was threescore cubits, and the breadth twenty cubits.",
"4 And the porch that was in the front of the house, the length of it was according to the breadth of the house, twenty cubits, and the height was an hundred and twenty: and he overlaid it within with pure gold.",
"5 And the greater house he cieled with fir tree, which he overlaid with fine gold, and set thereon palm trees and chains.",
"6 And he garnished the house with precious stones for beauty: and the gold was gold of Parvaim.",
"7 He overlaid also the house, the beams, the posts, and the walls thereof, and the doors thereof, with gold; and graved cherubims on the walls.",
"",
"——【The Second Book of the Chronicles 3】",
"",
"3 所罗门建筑　神殿的根基，乃是这样：长六十肘，宽二十肘，都按著古时的尺寸。",
"4 殿前的廊子长二十肘，与殿的宽窄一样，高一百二十肘；里面贴上精金。",
"5 大殿的墙，都用松木板遮蔽，又贴了精金，上面雕刻棕树和链子；",
"6 又用宝石装饰殿墙，使殿华美；所用的金子都是巴瓦音的金子。",
"7 又用金子贴殿和殿的栋梁、门槛、墙壁、门扇；墙上雕刻基路伯。",
"",
"——【历代志下 3】",
],
[
"6 And it came to pass, that when he had commanded the man clothed with linen, saying, Take fire from between the wheels, from between the cherubims; then he went in, and stood beside the wheels.",
"7 And one cherub stretched forth his hand from between the cherubims unto the fire that was between the cherubims, and took thereof, and put it into the hands of him that was clothed with linen: who took it, and went out.",
"8 And there appeared in the cherubims the form of a man's hand under their wings.",
"",
"——【The Book of the Prophet Ezekiel 10】",
"",
"6 他吩咐那穿细麻衣的人说：「要从旋转的轮内基路伯中间取火。」那人就进去站在一个轮子旁边。",
"7 有一个基路伯从基路伯中伸手到基路伯中间的火那里，取些放在那穿细麻衣的人两手中，那人就拿出去了。",
"8 在基路伯翅膀之下，显出有人手的样式。",
"",
"——【以西结书 10】",
],
[
"41 And the priests; Eliakim, Maaseiah, Miniamin, Michaiah, Elioenai, Zechariah, and Hananiah, with trumpets;",
"42 And Maaseiah, and Shemaiah, and Eleazar, and Uzzi, and Jehohanan, and Malchijah, and Elam, and Ezer. And the singers sang loud, with Jezrahiah their overseer.",
"43 Also that day they offered great sacrifices, and rejoiced: for God had made them rejoice with great joy: the wives also and the children rejoiced: so that the joy of Jerusalem was heard even afar off.",
"44 And at that time were some appointed over the chambers for the treasures, for the offerings, for the firstfruits, and for the tithes, to gather into them out of the fields of the cities the portions of the law for the priests and Levites: for Judah rejoiced for the priests and for the Levites that waited.",
"",
"——【The Book of Nehemiah 12】",
"",
"41 还有祭司以利亚金、玛西雅、米拿民、米该雅、以利约乃、撒迦利亚、哈楠尼亚吹号；",
"42 又有玛西雅、示玛雅、以利亚撒、乌西、约哈难、玛基雅、以拦，和以谢奏乐。歌唱的就大声歌唱，伊斯拉希雅管理他们。",
"43 那日，众人献大祭而欢乐；因为　神使他们大大欢乐，连妇女带孩童也都欢乐，甚至耶路撒冷中的欢声听到远处。",
"44 当日，派人管理库房，将举祭、初熟之物和所取的十分之一，就是按各城田地，照律法所定归给祭司和利未人的分，都收在里头。犹大人因祭司和利未人供职，就欢乐了。",
"",
"——【尼希米记 12】",
],
[
"1 Now when all this was finished, all Israel that were present went out to the cities of Judah, and brake the images in pieces, and cut down the groves, and threw down the high places and the altars out of all Judah and Benjamin, in Ephraim also and Manasseh, until they had utterly destroyed them all. Then all the children of Israel returned, every man to his possession, into their own cities.",
"2 And Hezekiah appointed the courses of the priests and the Levites after their courses, every man according to his service, the priests and Levites for burnt offerings and for peace offerings, to minister, and to give thanks, and to praise in the gates of the tents of the LORD.",
"3 He appointed also the king's portion of his substance for the burnt offerings, to wit, for the morning and evening burnt offerings, and the burnt offerings for the sabbaths, and for the new moons, and for the set feasts, as it is written in the law of the LORD.",
"4 Moreover he commanded the people that dwelt in Jerusalem to give the portion of the priests and the Levites, that they might be encouraged in the law of the LORD.",
"",
"——【The Second Book of the Chronicles 31】",
"",
"1 这事既都完毕，在那里的以色列众人就到犹大的城邑，打碎柱像，砍断木偶，又在犹大、便雅悯、以法莲、玛拿西遍地将邱坛和祭坛拆毁净尽。于是以色列众人各回各城，各归各地。",
"2 希西家派定祭司利未人的班次，各按各职献燔祭和平安祭，又在耶和华殿【原文作营】门内事奉，称谢颂赞耶和华。",
"3 王又从自己的产业中定出分来为燔祭，就是早晚的燔祭和安息日、月朔，并节期的燔祭，都是按耶和华律法上所载的；",
"4 又吩咐住耶路撒冷的百姓将祭司、利未人所应得的分给他们，使他们专心遵守耶和华的律法。",
"",
"——【历代志下 31】",
],
[
"25 And he said, Bring it near to me, and I will eat of my son's venison, that my soul may bless thee. And he brought it near to him, and he did eat: and he brought him wine, and he drank.",
"26 And his father Isaac said unto him, Come near now, and kiss me, my son.",
"",
"——【The First Book of Moses: Called Genesis 27】",
"",
"25 以撒说：「你递给我，我好吃我儿子的野味，给你祝福。」雅各就递给他，他便吃了，又拿酒给他，他也喝了。",
"26 他父亲以撒对他说：「我儿，你上前来与我亲嘴」。",
"",
"——【创世记 27】",
],
];
