var bible31_global=[
[
"14 And Joseph said unto them, That is it that I spake unto you, saying, Ye are spies:",
"15 Hereby ye shall be proved: By the life of Pharaoh ye shall not go forth hence, except your youngest brother come hither.",
"16 Send one of you, and let him fetch your brother, and ye shall be kept in prison, that your words may be proved, whether there be any truth in you: or else by the life of Pharaoh surely ye are spies.",
"17 And he put them all together into ward three days.",
"18 And Joseph said unto them the third day, This do, and live; for I fear God:",
"19 If ye be true men, let one of your brethren be bound in the house of your prison: go ye, carry corn for the famine of your houses:",
"",
"——【The First Book of Moses: Called Genesis 42】",
"",
"14 约瑟说：「我才说你们是奸细，这话实在不错。",
"15 我指着法老的性命起誓，若是你们的小兄弟不到这里来，你们就不得出这地方，从此就可以把你们证验出来了。",
"16 须要打发你们中间一个人去，把你们的兄弟带来。至于你们，都要囚在这里，好证验你们的话真不真，若不真，我指着法老的性命起誓，你们一定是奸细。」",
"17 于是约瑟把他们都下在监里三天。",
"18 到了第三天，约瑟对他们说：「我是敬畏　神的；你们照我的话行就可以存活。",
"19 你们如果是诚实人，可以留你们中间的一个人囚在监里，但你们可以带著粮食回去，救你们家里的饥荒。",
"",
"——【创世记 42】",
],
[
"21 And he that regarded not the word of the LORD left his servants and his cattle in the field.",
"22 And the LORD said unto Moses, Stretch forth thine hand toward heaven, that there may be hail in all the land of Egypt, upon man, and upon beast, and upon every herb of the field, throughout the land of Egypt.",
"23 And Moses stretched forth his rod toward heaven: and the LORD sent thunder and hail, and the fire ran along upon the ground; and the LORD rained hail upon the land of Egypt.",
"24 So there was hail, and fire mingled with the hail, very grievous, such as there was none like it in all the land of Egypt since it became a nation.",
"25 And the hail smote throughout all the land of Egypt all that was in the field, both man and beast; and the hail smote every herb of the field, and brake every tree of the field.",
"",
"——【The Second Book of Moses: Called Exodus 9】",
"",
"21 但那不把耶和华这话放在心上的，就将他的奴仆和牲畜留在田里。",
"22 耶和华对摩西说：「你向天伸杖，使埃及遍地的人身上和牲畜身上，并田间各样菜蔬上，都有冰雹。」",
"23 摩西向天伸杖，耶和华就打雷下雹，有火闪到地上；耶和华下雹在埃及地上。",
"24 那时，雹与火搀杂，甚是利害，自从埃及成国以来，遍地没有这样的。",
"25 在埃及遍地，雹击打了田间所有的人和牲畜，并一切的菜蔬，又打坏田间一切的树木。",
"",
"——【出埃及记 9】",
],
[
"16 She is hardened against her young ones, as though they were not hers: her labour is in vain without fear;",
"17 Because God hath deprived her of wisdom, neither hath he imparted to her understanding.",
"",
"——【The Book of Job 39】",
"",
"16 牠忍心待雏，似乎不是自己的；虽然徒受劳苦，也不为雏惧怕；",
"17 因为　神使牠没有智慧，也未将悟性赐给牠。",
"",
"——【约伯记 39】",
],
[
"13 And they were more than forty which had made this conspiracy.",
"14 And they came to the chief priests and elders, and said, We have bound ourselves under a great curse, that we will eat nothing until we have slain Paul.",
"15 Now therefore ye with the council signify to the chief captain that he bring him down unto you to morrow, as though ye would enquire something more perfectly concerning him: and we, or ever he come near, are ready to kill him.",
"16 And when Paul's sister's son heard of their lying in wait, he went and entered into the castle, and told Paul.",
"17 Then Paul called one of the centurions unto him, and said, Bring this young man unto the chief captain: for he hath a certain thing to tell him.",
"",
"——【The Acts of the Apostles 23】",
"",
"13 这样同心起誓的有四十多人。",
"14 他们来见祭司长和长老，说：我们已经起了一个大誓，若不先杀保罗就不吃什么。",
"15 现在你们和公会要知会千夫长，叫他带下保罗到你们这里来，假作要详细察考他的事；我们已经预备好了，不等他来到跟前就杀他。",
"16 保罗的外甥听见他们设下埋伏，就来到营楼里告诉保罗。",
"17 保罗请一个百夫长来，说：你领这少年人去见千夫长，他有事告诉他。",
"",
"——【使徒行传 23】",
],
[
"1 Ephraim feedeth on wind, and followeth after the east wind: he daily increaseth lies and desolation; and they do make a covenant with the Assyrians, and oil is carried into Egypt.",
"2 The LORD hath also a controversy with Judah, and will punish Jacob according to his ways; according to his doings will he recompense him.",
"3 He took his brother by the heel in the womb, and by his strength he had power with God:",
"",
"——【Hosea 12】",
"",
"1 以法莲吃风，且追赶东风，时常增添虚谎和强暴，与亚述立约，把油送到埃及。",
"2 耶和华与犹大争辩，必照雅各所行的惩罚他，按他所做的报应他。",
"3 他在腹中抓住哥哥的脚跟，壮年的时候与　神较力，",
"",
"——【何西阿书 12】",
],
[
"5 Declare ye in Judah, and publish in Jerusalem; and say, Blow ye the trumpet in the land: cry, gather together, and say, Assemble yourselves, and let us go into the defenced cities.",
"6 Set up the standard toward Zion: retire, stay not: for I will bring evil from the north, and a great destruction.",
"7 The lion is come up from his thicket, and the destroyer of the Gentiles is on his way; he is gone forth from his place to make thy land desolate; and thy cities shall be laid waste, without an inhabitant.",
"8 For this gird you with sackcloth, lament and howl: for the fierce anger of the LORD is not turned back from us.",
"9 And it shall come to pass at that day, saith the LORD, that the heart of the king shall perish, and the heart of the princes; and the priests shall be astonished, and the prophets shall wonder.",
"",
"——【The Book of the Prophet Jeremiah 4】",
"",
"5 你们当传扬在犹大，宣告在耶路撒冷说：你们当在国中吹角，高声呼叫说：你们当聚集！我们好进入坚固城！",
"6 应当向锡安竖立大旗。要逃避，不要迟延，因我必使灾祸与大毁灭从北方来到。",
"7 有狮子从密林中上来，是毁坏列国的。牠已经动身出离本处，要使你的地荒凉，使你的城邑变为荒场无人居住。",
"8 因此，你们当腰束麻布，大声哀号，因为耶和华的烈怒没有向我们转消。",
"9 耶和华说：「到那时，君王和首领的心都要消灭；祭司都要惊奇，先知都要诧异。」",
"",
"——【耶利米书 4】",
],
[
"5 Let the priests take it to them, every man of his acquaintance: and let them repair the breaches of the house, wheresoever any breach shall be found.",
"6 But it was so, that in the three and twentieth year of king Jehoash the priests had not repaired the breaches of the house.",
"7 Then king Jehoash called for Jehoiada the priest, and the other priests, and said unto them, Why repair ye not the breaches of the house? now therefore receive no more money of your acquaintance, but deliver it for the breaches of the house.",
"8 And the priests consented to receive no more money of the people, neither to repair the breaches of the house.",
"",
"——【The Second Book of the Kings 12】",
"",
"5 你们当从所认识的人收了来，修理殿的一切破坏之处。」",
"6 无奈到了约阿施王二十三年，祭司仍未修理殿的破坏之处。",
"7 所以约阿施王召了大祭司耶何耶大和众祭司来，对他们说：「你们怎么不修理殿的破坏之处呢？从今以后，你们不要从所认识的人再收银子，要将所收的交出来，修理殿的破坏之处。」",
"8 众祭司答应不再收百姓的银子，也不修理殿的破坏之处。",
"",
"——【列王记下 12】",
],
[
"33 The Jews answered him, saying, For a good work we stone thee not; but for blasphemy; and because that thou, being a man, makest thyself God.",
"34 Jesus answered them, Is it not written in your law, I said, Ye are gods?",
"35 If he called them gods, unto whom the word of God came, and the scripture cannot be broken;",
"36 Say ye of him, whom the Father hath sanctified, and sent into the world, Thou blasphemest; because I said, I am the Son of God?",
"37 If I do not the works of my Father, believe me not.",
"",
"——【The Gospel According to Saint John 10】",
"",
"33 犹太人回答说：我们不是为善事拿石头打你，是为你说僭妄的话；又为你是个人，反将自己当作　神。",
"34 耶稣说：你们的律法上岂不是写著我曾说你们是神吗？",
"35 经上的话是不能废的；若那些承受　神道的人尚且称为神，",
"36 父所分别为圣、又差到世间来的，他自称是　神的儿子，你们还向他说你说僭妄的话吗？",
"37 我若不行我父的事，你们就不必信我；",
"",
"——【约翰福音 10】",
],
[
"10 And thou shalt stone him with stones, that he die; because he hath sought to thrust thee away from the LORD thy God, which brought thee out of the land of Egypt, from the house of bondage.",
"11 And all Israel shall hear, and fear, and shall do no more any such wickedness as this is among you.",
"12 If thou shalt hear say in one of thy cities, which the LORD thy God hath given thee to dwell there, saying,",
"13 Certain men, the children of Belial, are gone out from among you, and have withdrawn the inhabitants of their city, saying, Let us go and serve other gods, which ye have not known;",
"14 Then shalt thou enquire, and make search, and ask diligently; and, behold, if it be truth, and the thing certain, that such abomination is wrought among you;",
"15 Thou shalt surely smite the inhabitants of that city with the edge of the sword, destroying it utterly, and all that is therein, and the cattle thereof, with the edge of the sword.",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 13】",
"",
"10 要用石头打死他，因为他想要勾引你离开那领你埃出及地为奴之家的耶和华─你的　神。",
"11 以色列众人都要听见害怕，就不敢在你们中间再行这样的恶了。",
"12 在耶和华─你　神所赐你居住的各城中，你若听人说，有些匪类从你们中间的一座城出来勾引本城的居民，说：『我们不如去事奉你们素来所不认识的别神』；",
"13 并入上一节",
"14 你就要探听，查究，细细地访问，果然是真，准有这可憎恶的事行在你们中间，",
"15 你必要用刀杀那城里的居民，把城里所有的，连牲畜，都用刀杀尽。",
"",
"——【申命记 13】",
],
[
"11 The king of Jarmuth, one; the king of Lachish, one;",
"12 The king of Eglon, one; the king of Gezer, one;",
"13 The king of Debir, one; the king of Geder, one;",
"14 The king of Hormah, one; the king of Arad, one;",
"",
"——【The Book of Joshua 12】",
"",
"11 一个是耶末王，一个是拉吉王，",
"12 一个是伊矶伦王，一个是基色王，",
"13 一个是底璧王，一个是基德王，",
"14 一个是何珥玛王，一个是亚拉得王，",
"",
"——【约书亚记 12】",
],
[
"2 Grace be to you and peace from God our Father, and from the Lord Jesus Christ.",
"3 Blessed be God, even the Father of our Lord Jesus Christ, the Father of mercies, and the God of all comfort;",
"4 Who comforteth us in all our tribulation, that we may be able to comfort them which are in any trouble, by the comfort wherewith we ourselves are comforted of God.",
"",
"——【The Second Epistle of Paul the Apostle to the Corinthians 1】",
"",
"2 愿恩惠、平安从　神我们的父和主耶稣基督归与你们！",
"3 愿颂赞归与我们的主耶稣基督的父　神，就是发慈悲的父，赐各样安慰的　神。",
"4 我们在一切患难中，他就安慰我们，叫我们能用　神所赐的安慰去安慰那遭各样患难的人。",
"",
"——【哥林多后书 1】",
],
[
"12 The kings of the earth, and all the inhabitants of the world, would not have believed that the adversary and the enemy should have entered into the gates of Jerusalem.",
"13 For the sins of her prophets, and the iniquities of her priests, that have shed the blood of the just in the midst of her,",
"14 They have wandered as blind men in the streets, they have polluted themselves with blood, so that men could not touch their garments.",
"",
"——【The Lamentations of Jeremiah 4】",
"",
"12 地上的君王和世上的居民都不信敌人和仇敌能进耶路撒冷的城门。",
"13 这都因他先知的罪恶和祭司的罪孽；他们在城中流了义人的血。",
"14 他们在街上如瞎子乱走，又被血玷污，以致人不能摸他们的衣服。",
"",
"——【耶利米哀歌 4】",
],
[
"2 And now is not Boaz of our kindred, with whose maidens thou wast? Behold, he winnoweth barley to night in the threshingfloor.",
"3 Wash thyself therefore, and anoint thee, and put thy raiment upon thee, and get thee down to the floor: but make not thyself known unto the man, until he shall have done eating and drinking.",
"",
"——【The Book of Ruth 3】",
"",
"2 你与波阿斯的使女常在一处，波阿斯不是我们的亲族吗？他今夜在场上簸大麦；",
"3 你要沐浴抹膏，换上衣服，下到场上，却不要使那人认出你来。你等他吃喝完了，",
"",
"——【路得记 3】",
],
[
"1 Now I Paul myself beseech you by the meekness and gentleness of Christ, who in presence am base among you, but being absent am bold toward you:",
"2 But I beseech you, that I may not be bold when I am present with that confidence, wherewith I think to be bold against some, which think of us as if we walked according to the flesh.",
"3 For though we walk in the flesh, we do not war after the flesh:",
"4 (For the weapons of our warfare are not carnal, but mighty through God to the pulling down of strong holds;)",
"",
"——【The Second Epistle of Paul the Apostle to the Corinthians 10】",
"",
"1 我保罗，就是与你们见面的时候是谦卑的，不在你们那里的时候向你们是勇敢的，如今亲自借著基督的温柔、和平劝你们。",
"2 有人以为我是凭著血气行事，我也以为必须用勇敢待这等人；求你们不要叫我在你们那里的时候，有这样的勇敢。",
"3 因为我们虽然在血气中行事，却不凭著血气争战。",
"4 我们争战的兵器本不是属血气的，乃是在　神面前有能力，可以攻破坚固的营垒，",
"",
"——【哥林多后书 10】",
],
[
"7 And she shall follow after her lovers, but she shall not overtake them; and she shall seek them, but shall not find them: then shall she say, I will go and return to my first husband; for then was it better with me than now.",
"8 For she did not know that I gave her corn, and wine, and oil, and multiplied her silver and gold, which they prepared for Baal.",
"",
"——【Hosea 2】",
"",
"7 她必追随所爱的，却追不上；她必寻找他们，却寻不见，便说：我要归回前夫，因我那时的光景比如今还好。",
"8 她不知道是我给她五谷、新酒，和油，又加增她的金银；她却以此供奉（或译：制造）巴力。",
"",
"——【何西阿书 2】",
],
[
"22 For as in Adam all die, even so in Christ shall all be made alive.",
"23 But every man in his own order: Christ the firstfruits; afterward they that are Christ's at his coming.",
"24 Then cometh the end, when he shall have delivered up the kingdom to God, even the Father; when he shall have put down all rule and all authority and power.",
"25 For he must reign, till he hath put all enemies under his feet.",
"26 The last enemy that shall be destroyed is death.",
"",
"——【The First Epistle of Paul the Apostle to the Corinthians 15】",
"",
"22 在亚当里众人都死了；照样，在基督里众人也都要复活。",
"23 但各人是按著自己的次序复活：初熟的果子是基督；以后，在他来的时候，是那些属基督的。",
"24 再后，末期到了，那时基督既将一切执政的、掌权的、有能的、都毁灭了，就把国交与父　神。",
"25 因为基督必要作王，等　神把一切仇敌都放在他的脚下。",
"26 尽末了所毁灭的仇敌，就是死。",
"",
"——【哥林多前书 15】",
],
[
"1 In that day shall this song be sung in the land of Judah; We have a strong city; salvation will God appoint for walls and bulwarks.",
"2 Open ye the gates, that the righteous nation which keepeth the truth may enter in.",
"3 Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee.",
"4 Trust ye in the LORD for ever: for in the LORD JEHOVAH is everlasting strength:",
"5 For he bringeth down them that dwell on high; the lofty city, he layeth it low; he layeth it low, even to the ground; he bringeth it even to the dust.",
"",
"——【The Book of the Prophet Isaiah 26】",
"",
"1 当那日，在犹大地人必唱这歌说：我们有坚固的城。耶和华要将救恩定为城墙，为外郭。",
"2 敞开城门，使守信的义民得以进入。",
"3 坚心倚赖你的，你必保守他十分平安，因为他倚靠你。",
"4 你们当倚靠耶和华直到永远，因为耶和华是永久的磐石。",
"5 他使住高处的与高城一并败落，将城拆毁，拆平，直到尘埃，",
"",
"——【以赛亚书 26】",
],
[
"17 Nevertheless he left not himself without witness, in that he did good, and gave us rain from heaven, and fruitful seasons, filling our hearts with food and gladness.",
"18 And with these sayings scarce restrained they the people, that they had not done sacrifice unto them.",
"",
"——【The Acts of the Apostles 14】",
"",
"17 然而为自己未尝不显出证据来，就如常施恩惠，从天降雨，赏赐丰年，叫你们饮食饱足，满心喜乐。",
"18 二人说了这些话，仅仅的拦住众人不献祭与他们。",
"",
"——【使徒行传 14】",
],
[
"18 For there is verily a disannulling of the commandment going before for the weakness and unprofitableness thereof.",
"19 For the law made nothing perfect, but the bringing in of a better hope did; by the which we draw nigh unto God.",
"20 And inasmuch as not without an oath he was made priest:",
"21 (For those priests were made without an oath; but this with an oath by him that said unto him, The Lord sware and will not repent, Thou art a priest for ever after the order of Melchisedec:)",
"",
"——【The Epistle of Paul the Apostle to the Hebrews 7】",
"",
"18 先前的条例，因软弱无益，所以废掉了，",
"19 （律法原来一无所成）就引进了更美的指望；靠这指望，我们便可以进到　神面前。",
"20 再者，耶稣为祭司，并不是不起誓立的。",
"21 至于那些祭司，原不是起誓立的，只有耶稣是起誓立的；因为那立他的对他说：主起了誓，决不后悔，你是永远为祭司。",
"",
"——【希伯来书 7】",
],
[
"8 With him will I speak mouth to mouth, even apparently, and not in dark speeches; and the similitude of the LORD shall he behold: wherefore then were ye not afraid to speak against my servant Moses?",
"9 And the anger of the LORD was kindled against them; and he departed.",
"10 And the cloud departed from off the tabernacle; and, behold, Miriam became leprous, white as snow: and Aaron looked upon Miriam, and, behold, she was leprous.",
"11 And Aaron said unto Moses, Alas, my lord, I beseech thee, lay not the sin upon us, wherein we have done foolishly, and wherein we have sinned.",
"12 Let her not be as one dead, of whom the flesh is half consumed when he cometh out of his mother's womb.",
"13 And Moses cried unto the LORD, saying, Heal her now, O God, I beseech thee.",
"",
"——【The Fourth Book of Moses: Called Numbers 12】",
"",
"8 我要与他面对面说话，乃是明说，不用谜语，并且他必见我的形像。你们毁谤我的仆人摩西，为何不惧怕呢？「」",
"9 耶和华就向他们二人发怒而去。",
"10 云彩从会幕上挪开了，不料，米利暗长了大痲疯，有雪那样白，亚伦一看米利暗长了大痲疯，",
"11 就对摩西说：「我主啊，求你不要因我们愚昧犯罪，便将这罪加在我们身上。",
"12 求你不要使她像那出母腹、肉已半烂的死胎。」",
"13 于是摩西哀求耶和华说：「　神啊，求你医治她！」",
"",
"——【民数记 12】",
],
[
"2 Thus saith the LORD; Behold, waters rise up out of the north, and shall be an overflowing flood, and shall overflow the land, and all that is therein; the city, and them that dwell therein: then the men shall cry, and all the inhabitants of the land shall howl.",
"3 At the noise of the stamping of the hoofs of his strong horses, at the rushing of his chariots, and at the rumbling of his wheels, the fathers shall not look back to their children for feebleness of hands;",
"4 Because of the day that cometh to spoil all the Philistines, and to cut off from Tyrus and Zidon every helper that remaineth: for the LORD will spoil the Philistines, the remnant of the country of Caphtor.",
"",
"——【The Book of the Prophet Jeremiah 47】",
"",
"2 耶和华如此说：有水从北方发起，成为涨溢的河，要涨过遍地和其中所有的，并城和其中所住的。人必呼喊；境内的居民都必哀号。",
"3 听见敌人壮马蹄跳的响声和战车隆隆、车轮轰轰；为父的手就发软，不回头看顾儿女。",
"4 因为日子将到，要毁灭一切非利士人，剪除帮助推罗、西顿所剩下的人。原来耶和华必毁灭非利士人，就是迦斐托海岛余剩的人。",
"",
"——【耶利米书 47】",
],
[
"4 And the priest answered David, and said, There is no common bread under mine hand, but there is hallowed bread; if the young men have kept themselves at least from women.",
"5 And David answered the priest, and said unto him, Of a truth women have been kept from us about these three days, since I came out, and the vessels of the young men are holy, and the bread is in a manner common, yea, though it were sanctified this day in the vessel.",
"6 So the priest gave him hallowed bread: for there was no bread there but the shewbread, that was taken from before the LORD, to put hot bread in the day when it was taken away.",
"7 Now a certain man of the servants of Saul was there that day, detained before the LORD; and his name was Doeg, an Edomite, the chiefest of the herdmen that belonged to Saul.",
"",
"——【The First Book of Samuel 21】",
"",
"4 祭司对大卫说：「我手下没有寻常的饼，只有圣饼；若少年人没有亲近妇人才可以给。」",
"5 大卫对祭司说：「实在约有三日我们没有亲近妇人；我出来的时候，虽是寻常行路，少年人的器皿还是洁净的；何况今日不更是洁净吗？」",
"6 祭司就拿圣饼给他；因为在那里没有别样饼，只有更换新饼，从耶和华面前撤下来的陈设饼。",
"7 （当日有扫罗的一个臣子留在耶和华面前。他名叫多益，是以东人，作扫罗的司牧长。）",
"",
"——【撒母耳记上 21】",
],
[
"8 For Jerusalem is ruined, and Judah is fallen: because their tongue and their doings are against the LORD, to provoke the eyes of his glory.",
"9 The shew of their countenance doth witness against them; and they declare their sin as Sodom, they hide it not. Woe unto their soul! for they have rewarded evil unto themselves.",
"10 Say ye to the righteous, that it shall be well with him: for they shall eat the fruit of their doings.",
"11 Woe unto the wicked! it shall be ill with him: for the reward of his hands shall be given him.",
"12 As for my people, children are their oppressors, and women rule over them. O my people, they which lead thee cause thee to err, and destroy the way of thy paths.",
"",
"——【The Book of the Prophet Isaiah 3】",
"",
"8 耶路撒冷败落，犹大倾倒；因为他们的舌头和行为与耶和华反对，惹了他荣光的眼目。",
"9 他们的面色证明自己的不正；他们述说自己的罪恶，并不隐瞒，好像所多玛一样。他们有祸了！因为作恶自害。",
"10 你们要论义人说：他必享福乐，因为要吃自己行为所结的果子。",
"11 恶人有祸了！他必遭灾难！因为要照自己手所行的受报应。",
"12 至于我的百姓，孩童欺压他们，妇女辖管他们。我的百姓啊，引导你的使你走错，并毁坏你所行的道路。",
"",
"——【以赛亚书 3】",
],
[
"13 (For until the law sin was in the world: but sin is not imputed when there is no law.",
"14 Nevertheless death reigned from Adam to Moses, even over them that had not sinned after the similitude of Adam's transgression, who is the figure of him that was to come.",
"15 But not as the offence, so also is the free gift. For if through the offence of one many be dead, much more the grace of God, and the gift by grace, which is by one man, Jesus Christ, hath abounded unto many.",
"16 And not as it was by one that sinned, so is the gift: for the judgment was by one to condemnation, but the free gift is of many offences unto justification.",
"17 For if by one man's offence death reigned by one; much more they which receive abundance of grace and of the gift of righteousness shall reign in life by one, Jesus Christ.)",
"18 Therefore as by the offence of one judgment came upon all men to condemnation; even so by the righteousness of one the free gift came upon all men unto justification of life.",
"",
"——【The Epistle of Paul the Apostle to the Romans 5】",
"",
"13 没有律法之先，罪已经在世上；但没有律法，罪也不算罪。",
"14 然而从亚当到摩西，死就作了王，连那些不与亚当犯一样罪过的，也在他的权下。亚当乃是那以后要来之人的豫像。",
"15 只是过犯不如恩赐，若因一人的过犯，众人都死了，何况　神的恩典，与那因耶稣基督一人恩典中的赏赐，岂不更加倍的临到众人吗？",
"16 因一人犯罪就定罪，也不如恩赐，原来审判是由一人而定罪，恩赐乃是由许多过犯而称义。",
"17 若因一人的过犯，死就因这一人作了王，何况那些受洪恩又蒙所赐之义的，岂不更要因耶稣基督一人在生命中作王吗？",
"18 如此说来，因一次的过犯，众人都被定罪；照样，因一次的义行，众人也就被称义得生命了。",
"",
"——【罗马书 5】",
],
[
"25 At that time Jesus answered and said, I thank thee, O Father, Lord of heaven and earth, because thou hast hid these things from the wise and prudent, and hast revealed them unto babes.",
"26 Even so, Father: for so it seemed good in thy sight.",
"27 All things are delivered unto me of my Father: and no man knoweth the Son, but the Father; neither knoweth any man the Father, save the Son, and he to whomsoever the Son will reveal him.",
"28 Come unto me, all ye that labour and are heavy laden, and I will give you rest.",
"",
"——【The Gospel According to Saint Matthew 11】",
"",
"25 那时，耶稣说：父啊，天地的主，我感谢你！因为你将这些事向聪明通达人就藏起来，向婴孩就显出来。",
"26 父啊，是的，因为你的美意本是如此。",
"27 一切所有的，都是我父交付我的；除了父，没有人知道子；除了子和子所愿意指示的，没有人知道父。",
"28 凡劳苦担重担的人可以到我这里来，我就使你们得安息。",
"",
"——【马太福音 11】",
],
[
"1 We then that are strong ought to bear the infirmities of the weak, and not to please ourselves.",
"2 Let every one of us please his neighbour for his good to edification.",
"3 For even Christ pleased not himself; but, as it is written, The reproaches of them that reproached thee fell on me.",
"4 For whatsoever things were written aforetime were written for our learning, that we through patience and comfort of the scriptures might have hope.",
"5 Now the God of patience and consolation grant you to be likeminded one toward another according to Christ Jesus:",
"",
"——【The Epistle of Paul the Apostle to the Romans 15】",
"",
"1 我们坚固的人应该担代不坚固人的软弱，不求自己的喜悦。",
"2 我们各人务要叫邻舍喜悦，使他得益处，建立德行。",
"3 因为基督也不求自己的喜悦，如经上所记：辱骂你人的辱骂都落在我身上。",
"4 从前所写的圣经都是为教训我们写的，叫我们因圣经所生的忍耐和安慰可以得著盼望。",
"5 但愿赐忍耐安慰的　神叫你们彼此同心，效法基督耶稣，",
"",
"——【罗马书 15】",
],
[
"6 And men shall speak of the might of thy terrible acts: and I will declare thy greatness.",
"7 They shall abundantly utter the memory of thy great goodness, and shall sing of thy righteousness.",
"8 The LORD is gracious, and full of compassion; slow to anger, and of great mercy.",
"9 The LORD is good to all: and his tender mercies are over all his works.",
"10 All thy works shall praise thee, O LORD; and thy saints shall bless thee.",
"11 They shall speak of the glory of thy kingdom, and talk of thy power;",
"",
"——【The Book of Psalms 145】",
"",
"6 人要传说你可畏之事的能力；我也要传扬你的大德。",
"7 他们记念你的大恩就要传出来，并要歌唱你的公义。",
"8 耶和华有恩惠，有怜悯，不轻易发怒，大有慈爱。",
"9 耶和华善待万民；他的慈悲覆庇他一切所造的。",
"10 耶和华啊，你一切所造的都要称谢你；你的圣民也要称颂你，",
"11 传说你国的荣耀，谈论你的大能，",
"",
"——【诗篇 145】",
],
[
"1 Judge me, O LORD; for I have walked in mine integrity: I have trusted also in the LORD; therefore I shall not slide.",
"2 Examine me, O LORD, and prove me; try my reins and my heart.",
"3 For thy lovingkindness is before mine eyes: and I have walked in thy truth.",
"",
"——【The Book of Psalms 26】",
"",
"1 （大卫的诗。）耶和华啊，求你为我伸冤，因我向来行事纯全；我又倚靠耶和华，并不摇动。",
"2 耶和华啊，求你察看我，试验我，熬炼我的肺腑心肠。",
"3 因为你的慈爱常在我眼前，我也按你的真理而行。",
"",
"——【诗篇 26】",
],
[
"6 Though I speak, my grief is not asswaged: and though I forbear, what am I eased?",
"7 But now he hath made me weary: thou hast made desolate all my company.",
"",
"——【The Book of Job 16】",
"",
"6 我虽说话，忧愁仍不得消解；我虽停住不说，忧愁就离开我吗？",
"7 但现在　神使我困倦，使亲友远离我，",
"",
"——【约伯记 16】",
],
[
"1 And the LORD said unto Samuel, How long wilt thou mourn for Saul, seeing I have rejected him from reigning over Israel? fill thine horn with oil, and go, I will send thee to Jesse the Beth–lehemite: for I have provided me a king among his sons.",
"2 And Samuel said, How can I go? if Saul hear it, he will kill me. And the LORD said, Take an heifer with thee, and say, I am come to sacrifice to the LORD.",
"",
"——【The First Book of Samuel 16】",
"",
"1 耶和华对撒母耳说：「我既厌弃扫罗作以色列的王，你为他悲伤要到几时呢？你将膏油盛满了角，我差遣你往伯利恒人耶西那里去；因为我在他众子之内，预定一个作王的。」",
"2 撒母耳说：「我怎能去呢？扫罗若听见，必要杀我。」耶和华说：「你可以带一只牛犊去，就说：『我来是要向耶和华献祭。』",
"",
"——【撒母耳记上 16】",
],
[
"4 So he went with them. And when they came to Jordan, they cut down wood.",
"5 But as one was felling a beam, the axe head fell into the water: and he cried, and said, Alas, master! for it was borrowed.",
"",
"——【The Second Book of the Kings 6】",
"",
"4 于是以利沙与他们同去。到了约旦河，就砍伐树木。",
"5 有一人砍树的时候，斧头掉在水里，他就呼叫说：「哀哉！我主啊，这斧子是借的。」",
"",
"——【列王记下 6】",
],
];
