var bible31_global=[
[
"10 And the sons of strangers shall build up thy walls, and their kings shall minister unto thee: for in my wrath I smote thee, but in my favour have I had mercy on thee.",
"11 Therefore thy gates shall be open continually; they shall not be shut day nor night; that men may bring unto thee the forces of the Gentiles, and that their kings may be brought.",
"",
"——【The Book of the Prophet Isaiah 60】",
"",
"10 外邦人必建筑你的城墙；他们的王必服事你。我曾发怒击打你，现今却施恩怜恤你。",
"11 你的城门必时常开放，昼夜不关；使人把列国的财物带来归你，并将他们的君王牵引而来。",
"",
"——【以赛亚书 60】",
],
[
"1 Then said the LORD unto me, Go yet, love a woman beloved of her friend, yet an adulteress, according to the love of the LORD toward the children of Israel, who look to other gods, and love flagons of wine.",
"2 So I bought her to me for fifteen pieces of silver, and for an homer of barley, and an half homer of barley:",
"3 And I said unto her, Thou shalt abide for me many days; thou shalt not play the harlot, and thou shalt not be for another man: so will I also be for thee.",
"",
"——【Hosea 3】",
"",
"1 耶和华对我说：「你再去爱一个淫妇，就是她情人所爱的；好像以色列人，虽然偏向别神，喜爱葡萄饼，耶和华还是爱他们。」",
"2 我便用银子十五舍客勒，大麦一贺梅珥半，买她归我。",
"3 我对她说：「你当多日为我独居，不可行淫，不可归别人为妻，我向你也必这样。」",
"",
"——【何西阿书 3】",
],
[
"1 Why boastest thou thyself in mischief, O mighty man? the goodness of God endureth continually.",
"2 Thy tongue deviseth mischiefs; like a sharp razor, working deceitfully.",
"3 Thou lovest evil more than good; and lying rather than to speak righteousness. Selah.",
"4 Thou lovest all devouring words, O thou deceitful tongue.",
"5 God shall likewise destroy thee for ever, he shall take thee away, and pluck thee out of thy dwelling place, and root thee out of the land of the living. Selah.",
"6 The righteous also shall see, and fear, and shall laugh at him:",
"",
"——【The Book of Psalms 52】",
"",
"1 （以东人多益来告诉扫罗说：大卫到了亚希米勒家。那时，大卫作这训诲诗，交与伶长。）勇士啊，你为何以作恶自夸？　神的慈爱是常存的。",
"2 你的舌头邪恶诡诈，好像剃头刀，快利伤人。",
"3 你爱恶胜似爱善，又爱说谎，不爱说公义。（细拉）",
"4 诡诈的舌头啊，你爱说一切毁灭的话！",
"5 　神也要毁灭你，直到永远；他要把你拿去，从你的帐棚中抽出，从活人之地将你拔出。（细拉）",
"6 义人要看见而惧怕，并要笑他，",
"",
"——【诗篇 52】",
],
[
"5 To be discreet, chaste, keepers at home, good, obedient to their own husbands, that the word of God be not blasphemed.",
"6 Young men likewise exhort to be sober minded.",
"7 In all things shewing thyself a pattern of good works: in doctrine shewing uncorruptness, gravity, sincerity,",
"8 Sound speech, that cannot be condemned; that he that is of the contrary part may be ashamed, having no evil thing to say of you.",
"9 Exhort servants to be obedient unto their own masters, and to please them well in all things; not answering again;",
"10 Not purloining, but shewing all good fidelity; that they may adorn the doctrine of God our Saviour in all things.",
"",
"——【The Epistle of Paul the Apostle to Titus 2】",
"",
"5 谨守，贞洁，料理家务，待人有恩，顺服自己的丈夫，免得　神的道理被毁谤。",
"6 又劝少年人要谨守。",
"7 你自己凡事要显出善行的榜样；在教训上要正直、端庄，",
"8 言语纯全，无可指责，叫那反对的人，既无处可说我们的不是，便自觉羞愧。",
"9 劝仆人要顺服自己的主人，凡事讨他的喜欢，不可顶撞他，",
"10 不可私拿东西；要显为忠诚，以致凡事尊荣我们救主　神的道。",
"",
"——【提多书 2】",
],
[
"32 They angered him also at the waters of strife, so that it went ill with Moses for their sakes:",
"33 Because they provoked his spirit, so that he spake unadvisedly with his lips.",
"34 They did not destroy the nations, concerning whom the LORD commanded them:",
"35 But were mingled among the heathen, and learned their works.",
"36 And they served their idols: which were a snare unto them.",
"",
"——【The Book of Psalms 106】",
"",
"32 他们在米利巴水又叫耶和华发怒，甚至摩西也受了亏损，",
"33 是因他们惹动他的灵，摩西（原文是他）用嘴说了急躁的话。",
"34 他们不照耶和华所吩咐的灭绝外邦人，",
"35 反与他们混杂相合，学习他们的行为，",
"36 事奉他们的偶像，这就成了自己的网罗，",
"",
"——【诗篇 106】",
],
[
"12 And the priest shall value it, whether it be good or bad: as thou valuest it, who art the priest, so shall it be.",
"13 But if he will at all redeem it, then he shall add a fifth part thereof unto thy estimation.",
"14 And when a man shall sanctify his house to be holy unto the LORD, then the priest shall estimate it, whether it be good or bad: as the priest shall estimate it, so shall it stand.",
"",
"——【The Third Book of Moses: Called Leviticus 27】",
"",
"12 祭司就要估定价值；牲畜是好是坏，祭司怎样估定，就要以怎样为是。",
"13 他若一定要赎回，就要在你所估定的价值以外加上五分之一。",
"14 「人将房屋分别为圣，归给耶和华，祭司就要估定价值。房屋是好是坏，祭司怎样估定，就要以怎样为定。",
"",
"——【利未记 27】",
],
[
"4 Thou art my King, O God: command deliverances for Jacob.",
"5 Through thee will we push down our enemies: through thy name will we tread them under that rise up against us.",
"",
"——【The Book of Psalms 44】",
"",
"4 　神啊，你是我的王；求你出令使雅各得胜。",
"5 我们靠你要推倒我们的敌人，靠你的名要践踏那起来攻击我们的人。",
"",
"——【诗篇 44】",
],
[
"7 And David took the shields of gold that were on the servants of Hadadezer, and brought them to Jerusalem.",
"8 And from Betah, and from Berothai, cities of Hadadezer, king David took exceeding much brass.",
"",
"——【The Second Book of Samuel 8】",
"",
"7 他夺了哈大底谢臣仆所拿的金盾牌，带到耶路撒冷。",
"8 大卫王又从属哈大底谢的比他和比罗他城中夺取了许多的铜。",
"",
"——【撒母耳记下 8】",
],
[
"3 And let the king appoint officers in all the provinces of his kingdom, that they may gather together all the fair young virgins unto Shushan the palace, to the house of the women, unto the custody of Hege the king's chamberlain, keeper of the women; and let their things for purification be given them:",
"4 And let the maiden which pleaseth the king be queen instead of Vashti. And the thing pleased the king; and he did so.",
"5 Now in Shushan the palace there was a certain Jew, whose name was Mordecai, the son of Jair, the son of Shimei, the son of Kish, a Benjamite;",
"",
"——【The Book of Esther 2】",
"",
"3 王可以派官在国中的各省招聚美貌的处女到书珊城（或译：宫）的女院，交给掌管女子的太监希该，给她们当用的香品。",
"4 王所喜爱的女子可以立为王后，代替瓦实提。」王以这事为美，就如此行。",
"5 书珊城有一个犹大人，名叫末底改，是便雅悯人基士的曾孙，示每的孙子，睚珥的儿子。",
"",
"——【以斯帖记 2】",
],
[
"1 Make a joyful noise unto the LORD, all ye lands.",
"2 Serve the LORD with gladness: come before his presence with singing.",
"3 Know ye that the LORD he is God: it is he that hath made us, and not we ourselves; we are his people, and the sheep of his pasture.",
"4 Enter into his gates with thanksgiving, and into his courts with praise: be thankful unto him, and bless his name.",
"5 For the LORD is good; his mercy is everlasting; and his truth endureth to all generations.",
"",
"——【The Book of Psalms 100】",
"",
"1 （称谢诗。）普天下当向耶和华欢呼！",
"2 你们当乐意事奉耶和华，当来向他歌唱！",
"3 你们当晓得耶和华是　神！我们是他造的，也是属他的；我们是他的民，也是他草场的羊。",
"4 当称谢进入他的门；当讚美进入他的院。当感谢他，称颂他的名！",
"5 因为耶和华本为善。他的慈爱存到永远；他的信实直到万代。",
"",
"——【诗篇 100】",
],
[
"7 And the LORD said unto Satan, Whence comest thou? Then Satan answered the LORD, and said, From going to and fro in the earth, and from walking up and down in it.",
"8 And the LORD said unto Satan, Hast thou considered my servant Job, that there is none like him in the earth, a perfect and an upright man, one that feareth God, and escheweth evil?",
"9 Then Satan answered the LORD, and said, Doth Job fear God for nought?",
"10 Hast not thou made an hedge about him, and about his house, and about all that he hath on every side? thou hast blessed the work of his hands, and his substance is increased in the land.",
"",
"——【The Book of Job 1】",
"",
"7 耶和华问撒但说：「你从哪里来？」撒但回答说：「我从地上走来走去，往返而来。」",
"8 耶和华问撒但说：「你曾用心察看我的仆人约伯没有？地上再没有人像他完全正直，敬畏　神，远离恶事。」",
"9 撒但回答耶和华说：「约伯敬畏　神，岂是无故呢？",
"10 你岂不是四面圈上篱笆围护他和他的家，并他一切所有的吗？他手所做的都蒙你赐福；他的家产也在地上增多。",
"",
"——【约伯记 1】",
],
[
"21 And their meat offering and their drink offerings for the bullocks, for the rams, and for the lambs, shall be according to their number, after the manner:",
"22 And one goat for a sin offering; beside the continual burnt offering, and his meat offering, and his drink offering.",
"23 And on the fourth day ten bullocks, two rams, and fourteen lambs of the first year without blemish:",
"",
"——【The Fourth Book of Moses: Called Numbers 29】",
"",
"21 并为公牛、公羊，和羊羔，按数照例，献同献的素祭和同献的奠祭。",
"22 又要献一只公山羊为赎罪祭。这是在常献的燔祭和同献的素祭并同献的奠祭以外。",
"23 「第四日要献公牛十只，公羊两只，没有残疾、一岁的公羊羔十四只；",
"",
"——【民数记 29】",
],
[
"105 Thy word is a lamp unto my feet, and a light unto my path.",
"106 I have sworn, and I will perform it, that I will keep thy righteous judgments.",
"107 I am afflicted very much: quicken me, O LORD, according unto thy word.",
"108 Accept, I beseech thee, the freewill offerings of my mouth, O LORD, and teach me thy judgments.",
"109 My soul is continually in my hand: yet do I not forget thy law.",
"110 The wicked have laid a snare for me: yet I erred not from thy precepts.",
"",
"——【The Book of Psalms 119】",
"",
"105 你的话是我脚前的灯，是我路上的光。",
"106 你公义的典章，我曾起誓遵守，我必按誓而行。",
"107 我甚是受苦；耶和华啊，求你照你的话将我救活！",
"108 耶和华啊，求你悦纳我口中的讚美为供物，又将你的典章教训我！",
"109 我的性命常在危险之中，我却不忘记你的律法。",
"110 恶人为我设下网罗，我却没有偏离你的训词。",
"",
"——【诗篇 119】",
],
[
"1 Unto thee lift I up mine eyes, O thou that dwellest in the heavens.",
"2 Behold, as the eyes of servants look unto the hand of their masters, and as the eyes of a maiden unto the hand of her mistress; so our eyes wait upon the LORD our God, until that he have mercy upon us.",
"",
"——【The Book of Psalms 123】",
"",
"1 （上行之诗。）坐在天上的主啊，我向你举目。",
"2 看哪，仆人的眼睛怎样望主人的手，使女的眼睛怎样望主母的手，我们的眼睛也照样望耶和华─我们的　神，直到他怜悯我们。",
"",
"——【诗篇 123】",
],
[
"1 Finally, brethren, pray for us, that the word of the Lord may have free course, and be glorified, even as it is with you:",
"2 And that we may be delivered from unreasonable and wicked men: for all men have not faith.",
"3 But the Lord is faithful, who shall stablish you, and keep you from evil.",
"4 And we have confidence in the Lord touching you, that ye both do and will do the things which we command you.",
"5 And the Lord direct your hearts into the love of God, and into the patient waiting for Christ.",
"6 Now we command you, brethren, in the name of our Lord Jesus Christ, that ye withdraw yourselves from every brother that walketh disorderly, and not after the tradition which he received of us.",
"",
"——【The Second Epistle of Paul the Apostle to the Thessalonians 3】",
"",
"1 弟兄们，我还有话说：请你们为我们祷告，好叫主的道理快快行开，得著荣耀，正如在你们中间一样。",
"2 也叫我们脱离无理之恶人的手，因为人不都是有信心。",
"3 但主是信实的，要坚固你们，保护你们脱离那恶者（或作：脱离凶恶）。",
"4 我们靠主深信，你们现在是遵行我们所吩咐的，后来也必要遵行。",
"5 愿主引导你们的心，叫你们爱　神，并学基督的忍耐。",
"6 弟兄们，我们奉主耶稣基督的名吩咐你们，凡有弟兄不按规矩而行，不遵守从我们所受的教训，就当远离他。",
"",
"——【帖撒罗尼迦后书 3】",
],
[
"13 And he said, O my Lord, send, I pray thee, by the hand of him whom thou wilt send.",
"14 And the anger of the LORD was kindled against Moses, and he said, Is not Aaron the Levite thy brother? I know that he can speak well. And also, behold, he cometh forth to meet thee: and when he seeth thee, he will be glad in his heart.",
"15 And thou shalt speak unto him, and put words in his mouth: and I will be with thy mouth, and with his mouth, and will teach you what ye shall do.",
"",
"——【The Second Book of Moses: Called Exodus 4】",
"",
"13 摩西说：「主啊，你愿意打发谁，就打发谁去吧！」",
"14 耶和华向摩西发怒说：「不是有你的哥哥利未人亚伦吗？我知道他是能言的；现在他出来迎接你，他一见你，心里就欢喜。",
"15 你要将当说的话传给他；我也要赐你和他口才，又要指教你们所当行的事。",
"",
"——【出埃及记 4】",
],
[
"3 And four great beasts came up from the sea, diverse one from another.",
"4 The first was like a lion, and had eagle's wings: I beheld till the wings thereof were plucked, and it was lifted up from the earth, and made stand upon the feet as a man, and a man's heart was given to it.",
"5 And behold another beast, a second, like to a bear, and it raised up itself on one side, and it had three ribs in the mouth of it between the teeth of it: and they said thus unto it, Arise, devour much flesh.",
"",
"——【The Book of Daniel 7】",
"",
"3 有四个大兽从海中上来，形状各有不同：",
"4 头一个像狮子，有鹰的翅膀；我正观看的时候，兽的翅膀被拔去，兽从地上得立起来，用两脚站立，像人一样，又得了人心。",
"5 又有一兽如熊，就是第二兽，旁跨而坐，口齿内啣著三根肋骨。有吩咐这兽的说：起来吞吃多肉。",
"",
"——【但以理书 7】",
],
[
"1 Praise ye the LORD. Praise God in his sanctuary: praise him in the firmament of his power.",
"2 Praise him for his mighty acts: praise him according to his excellent greatness.",
"",
"——【The Book of Psalms 150】",
"",
"1 你们要讚美耶和华！在　神的圣所讚美他！在他显能力的穹苍讚美他！",
"2 要因他大能的作为讚美他，按著他极美的大德讚美他！",
"",
"——【诗篇 150】",
],
[
"19 I Paul have written it with mine own hand, I will repay it: albeit I do not say to thee how thou owest unto me even thine own self besides.",
"20 Yea, brother, let me have joy of thee in the Lord: refresh my bowels in the Lord.",
"21 Having confidence in thy obedience I wrote unto thee, knowing that thou wilt also do more than I say.",
"22 But withal prepare me also a lodging: for I trust that through your prayers I shall be given unto you.",
"23 There salute thee Epaphras, my fellowprisoner in Christ Jesus;",
"",
"——【The Epistle of Paul the Apostle to Philemon 1】",
"",
"19 我必偿还。这是我保罗亲笔写的。我并不用对你说，连你自己也是亏欠于我。",
"20 兄弟啊，望你使我在主里因你得快乐（或作：益处）并望你使我的心在基督里得畅快。",
"21 我写信给你，深信你必顺服，知道你所要行的，必过于我所说的。",
"22 此外你还要给我预备住处；因为我盼望借著你们的祷告，必蒙恩到你们那里去。",
"23 为基督耶稣与我同坐监的以巴弗问你安。",
"",
"——【腓利门书 1】",
],
[
"1 O God, thou art my God; early will I seek thee: my soul thirsteth for thee, my flesh longeth for thee in a dry and thirsty land, where no water is;",
"2 To see thy power and thy glory, so as I have seen thee in the sanctuary.",
"3 Because thy lovingkindness is better than life, my lips shall praise thee.",
"4 Thus will I bless thee while I live: I will lift up my hands in thy name.",
"5 My soul shall be satisfied as with marrow and fatness; and my mouth shall praise thee with joyful lips:",
"6 When I remember thee upon my bed, and meditate on thee in the night watches.",
"",
"——【The Book of Psalms 63】",
"",
"1 （大卫在犹大旷野的时候，作了这诗。）　神啊，你是我的　神，我要切切地寻求你，在干旱疲乏无水之地，我渴想你；我的心切慕你。",
"2 我在圣所中曾如此瞻仰你，为要见你的能力和你的荣耀。",
"3 因你的慈爱比生命更好，我的嘴唇要颂讚你。",
"4 我还活的时候要这样称颂你；我要奉你的名举手。",
"5 我在床上记念你，在夜更的时候思想你；我的心就像饱足了骨髓肥油，我也要以欢乐的嘴唇讚美你。",
"6 合和译本并入上一节",
"",
"——【诗篇 63】",
],
[
"11 Then these men assembled, and found Daniel praying and making supplication before his God.",
"12 Then they came near, and spake before the king concerning the king's decree; Hast thou not signed a decree, that every man that shall ask a petition of any God or man within thirty days, save of thee, O king, shall be cast into the den of lions? The king answered and said, The thing is true, according to the law of the Medes and Persians, which altereth not.",
"13 Then answered they and said before the king, That Daniel, which is of the children of the captivity of Judah, regardeth not thee, O king, nor the decree that thou hast signed, but maketh his petition three times a day.",
"14 Then the king, when he heard these words, was sore displeased with himself, and set his heart on Daniel to deliver him: and he laboured till the going down of the sun to deliver him.",
"15 Then these men assembled unto the king, and said unto the king, Know, O king, that the law of the Medes and Persians is, That no decree nor statute which the king establisheth may be changed.",
"",
"——【The Book of Daniel 6】",
"",
"11 那些人就纷纷聚集，见但以理在他　神面前祈祷恳求。",
"12 他们便进到王前，提王的禁令，说：「王啊，三十日内不拘何人，若在王以外，或向神或向人求什么，必被扔在狮子坑中。王不是在这禁令上盖了玉玺么？」王回答说：「实有这事，照玛代和波斯人的例是不可更改的。」",
"13 他们对王说：「王啊，那被掳之犹大人中的但以理不理你，也不遵你盖了玉玺的禁令，他竟一日三次祈祷。」",
"14 王听见这话，就甚愁烦，一心要救但以理，筹划解救他，直到日落的时候。",
"15 那些人就纷纷聚集来见王，说：「王啊，当知道玛代人和波斯人有例，凡王所立的禁令和律例都不可更改。」",
"",
"——【但以理书 6】",
],
[
"1 God be merciful unto us, and bless us; and cause his face to shine upon us; Selah.",
"2 That thy way may be known upon earth, thy saving health among all nations.",
"3 Let the people praise thee, O God; let all the people praise thee.",
"",
"——【The Book of Psalms 67】",
"",
"1 （一篇诗歌，交与伶长。用丝弦的乐器。）愿　神怜悯我们，赐福与我们，用脸光照我们，（细拉）",
"2 好叫世界得知你的道路，万国得知你的救恩。",
"3 　神啊，愿列邦称讚你！愿万民都称讚你！",
"",
"——【诗篇 67】",
],
[
"11 And it came to pass about this time, that Joseph went into the house to do his business; and there was none of the men of the house there within.",
"12 And she caught him by his garment, saying, Lie with me: and he left his garment in her hand, and fled, and got him out.",
"",
"——【The First Book of Moses: Called Genesis 39】",
"",
"11 有一天，约瑟进屋里去办事，家中人没有一个在那屋里，",
"12 妇人就拉住他的衣裳，说：「你与我同寝吧！」约瑟把衣裳丢在妇人手里，跑到外边去了。",
"",
"——【创世记 39】",
],
[
"7 I charge you, O ye daughters of Jerusalem, by the roes, and by the hinds of the field, that ye stir not up, nor awake my love, till he please.",
"8 The voice of my beloved! behold, he cometh leaping upon the mountains, skipping upon the hills.",
"9 My beloved is like a roe or a young hart: behold, he standeth behind our wall, he looketh forth at the windows, shewing himself through the lattice.",
"10 My beloved spake, and said unto me, Rise up, my love, my fair one, and come away.",
"11 For, lo, the winter is past, the rain is over and gone;",
"",
"——【The Song of Solomon 2】",
"",
"7 耶路撒冷的众女子啊，我指著羚羊或田野的母鹿嘱咐你们：不要惊动、不要叫醒我所亲爱的，等他自己情愿（不要叫醒……情愿：或译不要激动爱情，等他自发）。",
"8 听啊！是我良人的声音；看哪！他蹿山越岭而来。",
"9 我的良人好像羚羊，或像小鹿。他站在我们墙壁后，从窗户往里观看，从窗櫺往里窥探。",
"10 我良人对我说：我的佳偶，我的美人，起来，与我同去！",
"11 因为冬天已往，雨水止住过去了。",
"",
"——【雅歌 2】",
],
[
"5 And one of the elders saith unto me, Weep not: behold, the Lion of the tribe of Juda, the Root of David, hath prevailed to open the book, and to loose the seven seals thereof.",
"6 And I beheld, and, lo, in the midst of the throne and of the four beasts, and in the midst of the elders, stood a Lamb as it had been slain, having seven horns and seven eyes, which are the seven Spirits of God sent forth into all the earth.",
"7 And he came and took the book out of the right hand of him that sat upon the throne.",
"8 And when he had taken the book, the four beasts and four and twenty elders fell down before the Lamb, having every one of them harps, and golden vials full of odours, which are the prayers of saints.",
"",
"——【The Revelation of Saint John the Devine 5】",
"",
"5 长老中有一位对我说：不要哭。看哪，犹大支派中的狮子，大卫的根，他已得胜，能以展开那书卷，揭开那七印。",
"6 我又看见宝座与四活物，并长老之中有羔羊站立，像是被杀过的，有七角七眼，就是　神的七灵，奉差遣往普天下去的。",
"7 这羔羊前来，从坐宝座的右手里拿了书卷。",
"8 他既拿了书卷，四活物和二十四位长老就俯伏在羔羊面前，各拿著琴和盛满了香的金炉；这香就是众圣徒的祈祷。",
"",
"——【启示录 5】",
],
[
"4 For they are impudent children and stiffhearted. I do send thee unto them; and thou shalt say unto them, Thus saith the Lord GOD.",
"5 And they, whether they will hear, or whether they will forbear, (for they are a rebellious house,) yet shall know that there hath been a prophet among them.",
"",
"——【The Book of the Prophet Ezekiel 2】",
"",
"4 这众子面无羞耻，心里刚硬。我差你往他们那里去，你要对他们说：主耶和华如此说。",
"5 他们或听，或不听，（他们是悖逆之家），必知道在他们中间有了先知。",
"",
"——【以西结书 2】",
],
[
"1 Say ye unto your brethren, Ammi; and to your sisters, Ru–hamah.",
"2 Plead with your mother, plead: for she is not my wife, neither am I her husband: let her therefore put away her whoredoms out of her sight, and her adulteries from between her breasts;",
"3 Lest I strip her naked, and set her as in the day that she was born, and make her as a wilderness, and set her like a dry land, and slay her with thirst.",
"4 And I will not have mercy upon her children; for they be the children of whoredoms.",
"5 For their mother hath played the harlot: she that conceived them hath done shamefully: for she said, I will go after my lovers, that give me my bread and my water, my wool and my flax, mine oil and my drink.",
"",
"——【Hosea 2】",
"",
"1 你们要称你们的弟兄为阿米（就是我民的意思），称你们的姊妹为路哈玛（就是蒙怜悯的意思）。",
"2 你们要与你们的母亲大大争辩；因为她不是我的妻子，我也不是她的丈夫。叫她除掉脸上的淫像和胸间的淫态，",
"3 免得我剥她的衣服，使她赤体，与才生的时候一样，使她如旷野，如干旱之地，因渴而死。",
"4 我必不怜悯她的儿女，因为他们是从淫乱而生的。",
"5 他们的母亲行了淫乱，怀他们的母做了可羞耻的事，因为她说：我要随从所爱的；我的饼、水、羊毛、麻、油、酒都是他们给的。",
"",
"——【何西阿书 2】",
],
[
"14 And these be the names of those that were born unto him in Jerusalem; Shammua, and Shobab, and Nathan, and Solomon,",
"15 Ibhar also, and Elishua, and Nepheg, and Japhia,",
"16 And Elishama, and Eliada, and Eliphalet.",
"",
"——【The Second Book of Samuel 5】",
"",
"14 在耶路撒冷所生的儿子是沙母亚、朔罢、拿单、所罗门、",
"15 益辖、以利书亚、尼斐、雅非亚、",
"16 以利沙玛、以利雅大、以利法列。",
"",
"——【撒母耳记下 5】",
],
[
"26 And they went and came to Moses, and to Aaron, and to all the congregation of the children of Israel, unto the wilderness of Paran, to Kadesh; and brought back word unto them, and unto all the congregation, and shewed them the fruit of the land.",
"27 And they told him, and said, We came unto the land whither thou sentest us, and surely it floweth with milk and honey; and this is the fruit of it.",
"28 Nevertheless the people be strong that dwell in the land, and the cities are walled, and very great: and moreover we saw the children of Anak there.",
"29 The Amalekites dwell in the land of the south: and the Hittites, and the Jebusites, and the Amorites, dwell in the mountains: and the Canaanites dwell by the sea, and by the coast of Jordan.",
"30 And Caleb stilled the people before Moses, and said, Let us go up at once, and possess it; for we are well able to overcome it.",
"31 But the men that went up with him said, We be not able to go up against the people; for they are stronger than we.",
"",
"——【The Fourth Book of Moses: Called Numbers 13】",
"",
"26 到了巴兰旷野的加低斯，见摩西、亚伦，并以色列的全会众，回报摩西、亚伦，并全会众，又把那地的果子给他们看；",
"27 又告诉摩西说：「我们到了你所打发我们去的那地，果然是流奶与蜜之地；这就是那地的果子。",
"28 然而住那地的民强壮，城邑也坚固宽大，并且我们在那里看见了亚衲族的人。",
"29 亚玛力人住在南地；赫人、耶布斯人、亚摩利人、住在山地；迦南人住在海边并约旦河旁。」",
"30 迦勒在摩西面前安抚百姓，说：「我们立刻上去得那地吧！我们足能得胜。」",
"31 但那些和他同去的人说：「我们不能上去攻击那民，因为他们比我们强壮。」",
"",
"——【民数记 13】",
],
[
"1 Ho, every one that thirsteth, come ye to the waters, and he that hath no money; come ye, buy, and eat; yea, come, buy wine and milk without money and without price.",
"2 Wherefore do ye spend money for that which is not bread? and your labour for that which satisfieth not? hearken diligently unto me, and eat ye that which is good, and let your soul delight itself in fatness.",
"",
"——【The Book of the Prophet Isaiah 55】",
"",
"1 你们一切干渴的都当就近水来；没有银钱的也可以来。你们都来，买了吃；不用银钱，不用价值，也来买酒和奶。",
"2 你们为何花钱（原文是平银）买那不足为食物的？用劳碌得来的买那不使人饱足的呢？你们要留意听我的话就能吃那美物，得享肥甘，心中喜乐。",
"",
"——【以赛亚书 55】",
],
[
"5 And when all these kings were met together, they came and pitched together at the waters of Merom, to fight against Israel.",
"6 And the LORD said unto Joshua, Be not afraid because of them: for to morrow about this time will I deliver them up all slain before Israel: thou shalt hough their horses, and burn their chariots with fire.",
"7 So Joshua came, and all the people of war with him, against them by the waters of Merom suddenly; and they fell upon them.",
"",
"——【The Book of Joshua 11】",
"",
"5 这诸王会合，来到米伦水边，一同安营，要与以色列人争战。",
"6 耶和华对约书亚说：「你不要因他们惧怕。明日这时，我必将他们交付以色列人全然杀了。你要砍断他们马的蹄筋，用火焚烧他们的车辆。」",
"7 于是约书亚率领一切兵丁，在米伦水边突然向前攻打他们。",
"",
"——【约书亚记 11】",
],
];
