var bible31_global=[
[
"16 And if the ear shall say, Because I am not the eye, I am not of the body; is it therefore not of the body?",
"17 If the whole body were an eye, where were the hearing? If the whole were hearing, where were the smelling?",
"18 But now hath God set the members every one of them in the body, as it hath pleased him.",
"19 And if they were all one member, where were the body?",
"20 But now are they many members, yet but one body.",
"21 And the eye cannot say unto the hand, I have no need of thee: nor again the head to the feet, I have no need of you.",
"",
"——【The First Epistle of Paul the Apostle to the Corinthians 12】",
"",
"16 设若耳说：我不是眼，所以不属乎身子；它也不能因此就不属乎身子。",
"17 若全身是眼，从那里听声呢？若全身是耳，从那里闻味呢？",
"18 但如今，　神随自己的意思把肢体俱各安排在身上了。",
"19 若都是一个肢体，身子在那里呢？",
"20 但如今肢体是多的，身子却是一个。",
"21 眼不能对手说：我用不著你；头也不能对脚说：我用不著你。",
"",
"——【哥林多前书 12】",
],
[
"1 Now Peter and John went up together into the temple at the hour of prayer, being the ninth hour.",
"2 And a certain man lame from his mother's womb was carried, whom they laid daily at the gate of the temple which is called Beautiful, to ask alms of them that entered into the temple;",
"",
"——【The Acts of the Apostles 3】",
"",
"1 申初祷告的时候，彼得、约翰上圣殿去。",
"2 有一个人，生来是瘸腿的，天天被人抬来，放在殿的一个门口，那门名叫美门，要求进殿的人赒济。",
"",
"——【使徒行传 3】",
],
[
"9 Thou whom I have taken from the ends of the earth, and called thee from the chief men thereof, and said unto thee, Thou art my servant; I have chosen thee, and not cast thee away.",
"10 Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.",
"11 Behold, all they that were incensed against thee shall be ashamed and confounded: they shall be as nothing; and they that strive with thee shall perish.",
"12 Thou shalt seek them, and shalt not find them, even them that contended with thee: they that war against thee shall be as nothing, and as a thing of nought.",
"13 For I the LORD thy God will hold thy right hand, saying unto thee, Fear not; I will help thee.",
"",
"——【The Book of the Prophet Isaiah 41】",
"",
"9 你是我从地极所领（原文是抓）来的，从地角所召来的，且对你说：你是我的仆人；我拣选你，并不弃绝你。",
"10 你不要害怕，因为我与你同在；不要惊惶，因为我是你的　神。我必坚固你，我必帮助你；我必用我公义的右手扶持你。",
"11 凡向你发怒的必都抱愧蒙羞；与你相争的必如无有，并要灭亡。",
"12 与你争竞的，你要找他们也找不着；与你争战的必如无有，成为虚无。",
"13 因为我耶和华─你的　神必搀扶你的右手，对你说：不要害怕！我必帮助你。",
"",
"——【以赛亚书 41】",
],
[
"15 And the prayer of faith shall save the sick, and the Lord shall raise him up; and if he have committed sins, they shall be forgiven him.",
"16 Confess your faults one to another, and pray one for another, that ye may be healed. The effectual fervent prayer of a righteous man availeth much.",
"17 Elias was a man subject to like passions as we are, and he prayed earnestly that it might not rain: and it rained not on the earth by the space of three years and six months.",
"18 And he prayed again, and the heaven gave rain, and the earth brought forth her fruit.",
"19 Brethren, if any of you do err from the truth, and one convert him;",
"",
"——【The General Epistle of James 5】",
"",
"15 出于信心的祈祷要救那病人，主必叫他起来；他若犯了罪，也必蒙赦免。",
"16 所以你们要彼此认罪，互相代求，使你们可以得医治。义人祈祷所发的力量是大有功效的。",
"17 以利亚与我们是一样性情的人，他恳切祷告，求不要下雨，雨就三年零六个月不下在地上。",
"18 他又祷告，天就降下雨来，地也生出土产。",
"19 我的弟兄们，你们中间若有失迷真道的，有人使他回转，",
"",
"——【雅各书 5】",
],
[
"9 And they went up on the breadth of the earth, and compassed the camp of the saints about, and the beloved city: and fire came down from God out of heaven, and devoured them.",
"10 And the devil that deceived them was cast into the lake of fire and brimstone, where the beast and the false prophet are, and shall be tormented day and night for ever and ever.",
"11 And I saw a great white throne, and him that sat on it, from whose face the earth and the heaven fled away; and there was found no place for them.",
"",
"——【The Revelation of Saint John the Devine 20】",
"",
"9 他们上来遍满了全地，围住圣徒的营与蒙爱的城，就有火从天降下，烧灭了他们。",
"10 那迷惑他们的魔鬼被扔在硫磺的火湖里，就是兽和假先知所在的地方。他们必昼夜受痛苦，直到永永远远。",
"11 我又看见一个白色的大宝座与坐在上面的；从他面前天地都逃避，再无可见之处了。",
"",
"——【启示录 20】",
],
[
"19 Behold, a whirlwind of the LORD is gone forth in fury, even a grievous whirlwind: it shall fall grievously upon the head of the wicked.",
"20 The anger of the LORD shall not return, until he have executed, and till he have performed the thoughts of his heart: in the latter days ye shall consider it perfectly.",
"",
"——【The Book of the Prophet Jeremiah 23】",
"",
"19 看哪！耶和华的忿怒好像暴风，已经发出；是暴烈的旋风，必转到恶人的头上。",
"20 耶和华的怒气必不转消，直到他心中所拟定的成就了。末后的日子你们要全然明白。",
"",
"——【耶利米书 23】",
],
[
"11 As an eagle stirreth up her nest, fluttereth over her young, spreadeth abroad her wings, taketh them, beareth them on her wings:",
"12 So the LORD alone did lead him, and there was no strange god with him.",
"13 He made him ride on the high places of the earth, that he might eat the increase of the fields; and he made him to suck honey out of the rock, and oil out of the flinty rock;",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 32】",
"",
"11 又如鹰搅动巢窝，在雏鹰以上两翅搧展，接取雏鹰，背在两翼之上。",
"12 这样，耶和华独自引导他，并无外邦神与他同在。",
"13 耶和华使他乘驾地的高处，得吃田间的土产；又使他从磐石中咂蜜，从坚石中吸油；",
"",
"——【申命记 32】",
],
[
"15 The LORD hath taken away thy judgments, he hath cast out thine enemy: the king of Israel, even the LORD, is in the midst of thee: thou shalt not see evil any more.",
"16 In that day it shall be said to Jerusalem, Fear thou not: and to Zion, Let not thine hands be slack.",
"17 The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy; he will rest in his love, he will joy over thee with singing.",
"",
"——【Zephaniah 3】",
"",
"15 耶和华已经除去你的刑罚，赶出你的仇敌。以色列的王─耶和华在你中间；你必不再惧怕灾祸。",
"16 当那日，必有话向耶路撒冷说：不要惧怕！锡安哪；不要手软！",
"17 耶和华─你的　神是施行拯救、大有能力的主。他在你中间必因你欢欣喜乐，默然爱你，且因你喜乐而欢呼。",
"",
"——【西番雅书 3】",
],
[
"19 And the sons of Merari; Mahali and Mushi: these are the families of Levi according to their generations.",
"20 And Amram took him Jochebed his father's sister to wife; and she bare him Aaron and Moses: and the years of the life of Amram were an hundred and thirty and seven years.",
"21 And the sons of Izhar; Korah, and Nepheg, and Zichri.",
"",
"——【The Second Book of Moses: Called Exodus 6】",
"",
"19 米拉利的儿子是抹利和母示；这是利未的家，都按著他们的后代。",
"20 暗兰娶了他父亲的妹妹约基别为妻，她给他生了亚伦和摩西。暗兰一生的岁数是一百三十七岁。",
"21 以斯哈的儿子是可拉、尼斐、细基利。",
"",
"——【出埃及记 6】",
],
[
"4 But let every man prove his own work, and then shall he have rejoicing in himself alone, and not in another.",
"5 For every man shall bear his own burden.",
"6 Let him that is taught in the word communicate unto him that teacheth in all good things.",
"7 Be not deceived; God is not mocked: for whatsoever a man soweth, that shall he also reap.",
"",
"——【The Epistle of Paul the Apostle to the Galatians 6】",
"",
"4 各人应当察验自己的行为；这样，他所夸的就专在自己，不在别人了，",
"5 因为各人必担当自己的担子。",
"6 在道理上受教的，当把一切需用的供给施教的人。",
"7 不要自欺，　神是轻慢不得的。人种的是什么，收的也是什么。",
"",
"——【加拉太书 6】",
],
[
"3 In the first year of Cyrus the king the same Cyrus the king made a decree concerning the house of God at Jerusalem, Let the house be builded, the place where they offered sacrifices, and let the foundations thereof be strongly laid; the height thereof threescore cubits, and the breadth thereof threescore cubits;",
"4 With three rows of great stones, and a row of new timber: and let the expenses be given out of the king's house:",
"",
"——【Ezra 6】",
"",
"3 「古列王元年，他降旨论到耶路撒冷　神的殿，要建造这殿为献祭之处，坚立殿的根基。殿高六十肘，宽六十肘，",
"4 用三层大石头，一层新木头，经费要出于王库；",
"",
"——【以斯拉记 6】",
],
[
"22 And one goat for a sin offering; beside the continual burnt offering, and his meat offering, and his drink offering.",
"23 And on the fourth day ten bullocks, two rams, and fourteen lambs of the first year without blemish:",
"24 Their meat offering and their drink offerings for the bullocks, for the rams, and for the lambs, shall be according to their number, after the manner:",
"25 And one kid of the goats for a sin offering; beside the continual burnt offering, his meat offering, and his drink offering.",
"",
"——【The Fourth Book of Moses: Called Numbers 29】",
"",
"22 又要献一只公山羊为赎罪祭。这是在常献的燔祭和同献的素祭并同献的奠祭以外。",
"23 「第四日要献公牛十只，公羊两只，没有残疾、一岁的公羊羔十四只；",
"24 并为公牛、公羊，和羊羔，按数照例，献同献的素祭和同献的奠祭。",
"25 又要献一只公山羊为赎罪祭。这是在常献的燔祭和同献的素祭并同献的奠祭以外。",
"",
"——【民数记 29】",
],
[
"48 As is the earthy, such are they also that are earthy: and as is the heavenly, such are they also that are heavenly.",
"49 And as we have borne the image of the earthy, we shall also bear the image of the heavenly.",
"50 Now this I say, brethren, that flesh and blood cannot inherit the kingdom of God; neither doth corruption inherit incorruption.",
"51 Behold, I shew you a mystery; We shall not all sleep, but we shall all be changed,",
"52 In a moment, in the twinkling of an eye, at the last trump: for the trumpet shall sound, and the dead shall be raised incorruptible, and we shall be changed.",
"",
"——【The First Epistle of Paul the Apostle to the Corinthians 15】",
"",
"48 那属土的怎样，凡属土的也就怎样；属天的怎样，凡属天的也就怎样。",
"49 我们既有属土的形状，将来也必有属天的形状。",
"50 弟兄们，我告诉你们说，血肉之体不能承受　神的国，必朽坏的不能承受不朽坏的。",
"51 我如今把一件奥祕的事告诉你们：我们不是都要睡觉，乃是都要改变，",
"52 就在一霎时，眨眼之间，号筒末次吹响的时候。因号筒要响，死人要复活成为不朽坏的，我们也要改变。",
"",
"——【哥林多前书 15】",
],
[
"1 And the LORD spake unto Moses, saying,",
"2 Speak unto the children of Israel, and say unto them, Concerning the feasts of the LORD, which ye shall proclaim to be holy convocations, even these are my feasts.",
"3 Six days shall work be done: but the seventh day is the sabbath of rest, an holy convocation; ye shall do no work therein: it is the sabbath of the LORD in all your dwellings.",
"4 These are the feasts of the LORD, even holy convocations, which ye shall proclaim in their seasons.",
"",
"——【The Third Book of Moses: Called Leviticus 23】",
"",
"1 耶和华对摩西说：",
"2 「你晓谕以色列人说：耶和华的节期，你们要宣告为圣会的节期。",
"3 六日要做工，第七日是圣安息日，当有圣会；你们什么工都不可做。这是在你们一切的住处向耶和华守的安息日。",
"4 耶和华的节期，就是你们到了日期要宣告为圣会的，乃是这些。」",
"",
"——【利未记 23】",
],
[
"5 He shall receive the blessing from the LORD, and righteousness from the God of his salvation.",
"6 This is the generation of them that seek him, that seek thy face, O Jacob. Selah.",
"7 Lift up your heads, O ye gates; and be ye lift up, ye everlasting doors; and the King of glory shall come in.",
"8 Who is this King of glory? The LORD strong and mighty, the LORD mighty in battle.",
"",
"——【The Book of Psalms 24】",
"",
"5 他必蒙耶和华赐福，又蒙救他的　神使他成义。",
"6 这是寻求耶和华的族类，是寻求你面的雅各。（细拉）",
"7 众城门哪，你们要抬起头来！永久的门户，你们要被举起！那荣耀的王将要进来！",
"8 荣耀的王是谁呢？就是有力有能的耶和华，在战场上有能的耶和华！",
"",
"——【诗篇 24】",
],
[
"36 And Sharaim, and Adithaim, and Gederah, and Gederothaim; fourteen cities with their villages:",
"37 Zenan, and Hadashah, and Migdal–gad,",
"",
"——【The Book of Joshua 15】",
"",
"36 沙拉音、亚底他音、基底拉、基底罗他音，共十四座城，还有属城的村庄。",
"37 又有洗楠、哈大沙、麦大‧迦得、",
"",
"——【约书亚记 15】",
],
[
"7 And he made two cherubims of gold, beaten out of one piece made he them, on the two ends of the mercy seat;",
"8 One cherub on the end on this side, and another cherub on the other end on that side: out of the mercy seat made he the cherubims on the two ends thereof.",
"9 And the cherubims spread out their wings on high, and covered with their wings over the mercy seat, with their faces one to another; even to the mercy seatward were the faces of the cherubims.",
"",
"——【The Second Book of Moses: Called Exodus 37】",
"",
"7 用金子锤出两个基路伯来，安在施恩座的两头，",
"8 这头做一个基路伯，那头做一个基路伯，二基路伯接连一块，在施恩座的两头。",
"9 二基路伯高张翅膀，遮掩施恩座；基路伯是脸对脸，朝著施恩座。",
"",
"——【出埃及记 37】",
],
[
"1 The earth is the LORD'S, and the fulness thereof; the world, and they that dwell therein.",
"2 For he hath founded it upon the seas, and established it upon the floods.",
"",
"——【The Book of Psalms 24】",
"",
"1 （大卫的诗。）地和其中所充满的，世界和住在其间的，都属耶和华。",
"2 他把地建立在海上，安定在大水之上。",
"",
"——【诗篇 24】",
],
[
"9 When Toi king of Hamath heard that David had smitten all the host of Hadadezer,",
"10 Then Toi sent Joram his son unto king David, to salute him, and to bless him, because he had fought against Hadadezer, and smitten him: for Hadadezer had wars with Toi. And Joram brought with him vessels of silver, and vessels of gold, and vessels of brass:",
"",
"——【The Second Book of Samuel 8】",
"",
"9 哈马王陀以听见大卫杀败哈大底谢的全军，",
"10 就打发他儿子约兰去见大卫王，问他的安，为他祝福，因为他杀败了哈大底谢（原来陀以与哈大底谢常常争战）。约兰带了金银铜的器皿来，",
"",
"——【撒母耳记下 8】",
],
[
"6 Also their love, and their hatred, and their envy, is now perished; neither have they any more a portion for ever in any thing that is done under the sun.",
"7 Go thy way, eat thy bread with joy, and drink thy wine with a merry heart; for God now accepteth thy works.",
"8 Let thy garments be always white; and let thy head lack no ointment.",
"",
"——【Ecclesiastes 9】",
"",
"6 他们的爱，他们的恨，他们的嫉妒，早都消灭了。在日光之下所行的一切事上，他们永不再有分了。",
"7 你只管去欢欢喜喜吃你的饭，心中快乐喝你的酒，因为　神已经悦纳你的作为。",
"8 你的衣服当时常洁白，你头上也不要缺少膏油。",
"",
"——【传道书 9】",
],
[
"1 The song of songs, which is Solomon's.",
"2 Let him kiss me with the kisses of his mouth: for thy love is better than wine.",
"3 Because of the savour of thy good ointments thy name is as ointment poured forth, therefore do the virgins love thee.",
"4 Draw me, we will run after thee: the king hath brought me into his chambers: we will be glad and rejoice in thee, we will remember thy love more than wine: the upright love thee.",
"5 I am black, but comely, O ye daughters of Jerusalem, as the tents of Kedar, as the curtains of Solomon.",
"6 Look not upon me, because I am black, because the sun hath looked upon me: my mother's children were angry with me; they made me the keeper of the vineyards; but mine own vineyard have I not kept.",
"",
"——【The Song of Solomon 1】",
"",
"1 所罗门的歌，是歌中的雅歌。",
"2 愿他用口与我亲嘴；因你的爱情比酒更美。",
"3 你的膏油馨香；你的名如同倒出来的香膏，所以众童女都爱你。",
"4 愿你吸引我，我们就快跑跟随你。王带我进了内室，我们必因你欢喜快乐。我们要称赞你的爱情，胜似称赞美酒。他们爱你是理所当然的。",
"5 耶路撒冷的众女子啊，我虽然黑，却是秀美，如同基达的帐棚，好像所罗门的幔子。",
"6 不要因日头把我晒黑了就轻看我。我同母的弟兄向我发怒，他们使我看守葡萄园；我自己的葡萄园却没有看守。",
"",
"——【雅歌 1】",
],
[
"1 Then there was a famine in the days of David three years, year after year; and David enquired of the LORD. And the LORD answered, It is for Saul, and for his bloody house, because he slew the Gibeonites.",
"2 And the king called the Gibeonites, and said unto them; (now the Gibeonites were not of the children of Israel, but of the remnant of the Amorites; and the children of Israel had sworn unto them: and Saul sought to slay them in his zeal to the children of Israel and Judah.)",
"3 Wherefore David said unto the Gibeonites, What shall I do for you? and wherewith shall I make the atonement, that ye may bless the inheritance of the LORD?",
"4 And the Gibeonites said unto him, We will have no silver nor gold of Saul, nor of his house; neither for us shalt thou kill any man in Israel. And he said, What ye shall say, that will I do for you.",
"5 And they answered the king, The man that consumed us, and that devised against us that we should be destroyed from remaining in any of the coasts of Israel,",
"6 Let seven men of his sons be delivered unto us, and we will hang them up unto the LORD in Gibeah of Saul, whom the LORD did choose. And the king said, I will give them.",
"",
"——【The Second Book of Samuel 21】",
"",
"1 大卫年间有饥荒，一连三年，大卫就求问耶和华。耶和华说：「这饥荒是因扫罗和他流人血之家杀死基遍人。」",
"2 原来这基遍人不是以色列人，乃是亚摩利人中所剩的；以色列人曾向他们起誓，不杀灭他们，扫罗却为以色列人和犹大人发热心，想要杀灭他们。大卫王召了他们来，",
"3 问他们说：「我当为你们怎样行呢？可用什么赎这罪，使你们为耶和华的产业祝福呢？」",
"4 基遍人回答说：「我们和扫罗与他家的事并不关乎金银，也不要因我们的缘故杀一个以色列人。」大卫说：「你们怎样说，我就为你们怎样行。」",
"5 他们对王说：「那从前谋害我们、要灭我们、使我们不得再住以色列境内的人，",
"6 现在愿将他的子孙七人交给我们，我们好在耶和华面前，将他们悬挂在耶和华拣选扫罗的基比亚。」王说：「我必交给你们。」",
"",
"——【撒母耳记下 21】",
],
[
"7 Shall they escape by iniquity? in thine anger cast down the people, O God.",
"8 Thou tellest my wanderings: put thou my tears into thy bottle: are they not in thy book?",
"9 When I cry unto thee, then shall mine enemies turn back: this I know; for God is for me.",
"10 In God will I praise his word: in the LORD will I praise his word.",
"",
"——【The Book of Psalms 56】",
"",
"7 他们岂能因罪孽逃脱吗？　神啊，求你在怒中使众民堕落！",
"8 我几次流离，你都记数；求你把我眼泪装在你的皮袋里。这不都记在你册子上吗？",
"9 我呼求的日子，我的仇敌都要转身退后。　神帮助我，这是我所知道的。",
"10 我倚靠　神，我要赞美他的话；我倚靠耶和华，我要赞美他的话。",
"",
"——【诗篇 56】",
],
[
"1 Praise ye the LORD. Sing unto the LORD a new song, and his praise in the congregation of saints.",
"2 Let Israel rejoice in him that made him: let the children of Zion be joyful in their King.",
"3 Let them praise his name in the dance: let them sing praises unto him with the timbrel and harp.",
"4 For the LORD taketh pleasure in his people: he will beautify the meek with salvation.",
"5 Let the saints be joyful in glory: let them sing aloud upon their beds.",
"",
"——【The Book of Psalms 149】",
"",
"1 你们要赞美耶和华！向耶和华唱新歌，在圣民的会中赞美他！",
"2 愿以色列因造他的主欢喜！愿锡安的民因他们的王快乐！",
"3 愿他们跳舞赞美他的名，击鼓弹琴歌颂他！",
"4 因为耶和华喜爱他的百姓；他要用救恩当作谦卑人的妆饰。",
"5 愿圣民因所得的荣耀高兴！愿他们在床上欢呼！",
"",
"——【诗篇 149】",
],
[
"1 The burden of Nineveh. The book of the vision of Nahum the Elkoshite.",
"2 God is jealous, and the LORD revengeth; the LORD revengeth, and is furious; the LORD will take vengeance on his adversaries, and he reserveth wrath for his enemies.",
"",
"——【Nahum 1】",
"",
"1 论尼尼微的默示，就是伊勒歌斯人那鸿所得的默示。",
"2 耶和华是忌邪施报的　神。耶和华施报大有忿怒；向他的敌人施报，向他的仇敌怀怒。",
"",
"——【那鸿书 1】",
],
[
"2 And devout men carried Stephen to his burial, and made great lamentation over him.",
"3 As for Saul, he made havock of the church, entering into every house, and haling men and women committed them to prison.",
"4 Therefore they that were scattered abroad went every where preaching the word.",
"",
"——【The Acts of the Apostles 8】",
"",
"2 有虔诚的人把司提反埋葬了，为他捶胸大哭。",
"3 扫罗却残害教会，进各人的家，拉著男女下在监里。",
"4 那些分散的人往各处去传道。",
"",
"——【使徒行传 8】",
],
[
"2 Grace and peace be multiplied unto you through the knowledge of God, and of Jesus our Lord,",
"3 According as his divine power hath given unto us all things that pertain unto life and godliness, through the knowledge of him that hath called us to glory and virtue:",
"4 Whereby are given unto us exceeding great and precious promises: that by these ye might be partakers of the divine nature, having escaped the corruption that is in the world through lust.",
"5 And beside this, giving all diligence, add to your faith virtue; and to virtue knowledge;",
"6 And to knowledge temperance; and to temperance patience; and to patience godliness;",
"7 And to godliness brotherly kindness; and to brotherly kindness charity.",
"",
"——【The Second General Epistle of Peter 1】",
"",
"2 愿恩惠、平安，因你们认识　神和我们主耶稣，多多的加给你们。",
"3 　神的神能已将一切关乎生命和虔敬的事赐给我们，皆因我们认识那用自己荣耀和美德召我们的主。",
"4 因此，他已将又宝贵又极大的应许赐给我们，叫我们既脱离世上从情欲来的败坏，就得与　神的性情有分。",
"5 正因这缘故，你们要分外地殷勤；有了信心，又要加上德行；有了德行，又要加上知识；",
"6 有了知识，又要加上节制；有了节制，又要加上忍耐；有了忍耐，又要加上虔敬；",
"7 有了虔敬，又要加上爱弟兄的心；有了爱弟兄的心，又要加上爱众人的心；",
"",
"——【彼得后书 1】",
],
[
"18 Thou shalt not bring the hire of a whore, or the price of a dog, into the house of the LORD thy God for any vow: for even both these are abomination unto the LORD thy God.",
"19 Thou shalt not lend upon usury to thy brother; usury of money, usury of victuals, usury of any thing that is lent upon usury:",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 23】",
"",
"18 娼妓所得的钱，或娈童（原文作狗）所得的价，你不可带入耶和华─你　神的殿还愿，因为这两样都是耶和华─你　神所憎恶的。",
"19 「你借给你弟兄的，或是钱财或是粮食，无论什么可生利的物，都不可取利。",
"",
"——【申命记 23】",
],
[
"15 And I will give you pastors according to mine heart, which shall feed you with knowledge and understanding.",
"16 And it shall come to pass, when ye be multiplied and increased in the land, in those days, saith the LORD, they shall say no more, The ark of the covenant of the LORD: neither shall it come to mind: neither shall they remember it; neither shall they visit it; neither shall that be done any more.",
"17 At that time they shall call Jerusalem the throne of the LORD; and all the nations shall be gathered unto it, to the name of the LORD, to Jerusalem: neither shall they walk any more after the imagination of their evil heart.",
"18 In those days the house of Judah shall walk with the house of Israel, and they shall come together out of the land of the north to the land that I have given for an inheritance unto your fathers.",
"",
"——【The Book of the Prophet Jeremiah 3】",
"",
"15 我也必将合我心的牧者赐给你们。他们必以知识和智慧牧养你们。」",
"16 耶和华说：「你们在国中生养众多；当那些日子，人必不再提说耶和华的约柜，不追想，不记念，不觉缺少，也不再制造。",
"17 那时，人必称耶路撒冷为耶和华的宝座；万国必到耶路撒冷，在耶和华立名的地方聚集。他们必不再随从自己顽梗的恶心行事。",
"18 当那些日子，犹大家要和以色列家同行，从北方之地一同来到我赐给你们列祖为业之地。」",
"",
"——【耶利米书 3】",
],
[
"21 Shall not God search this out? for he knoweth the secrets of the heart.",
"22 Yea, for thy sake are we killed all the day long; we are counted as sheep for the slaughter.",
"",
"——【The Book of Psalms 44】",
"",
"21 　神岂不鉴察这事吗？因为他晓得人心里的隐祕。",
"22 我们为你的缘故终日被杀；人看我们如将宰的羊。",
"",
"——【诗篇 44】",
],
[
"43 Blessed is that servant, whom his lord when he cometh shall find so doing.",
"44 Of a truth I say unto you, that he will make him ruler over all that he hath.",
"",
"——【The Gospel According to Saint Luke 12】",
"",
"43 主人来到，看见仆人这样行，那仆人就有福了。",
"44 我实在告诉你们，主人要派他管理一切所有的。",
"",
"——【路加福音 12】",
],
];
