var bible31_global=[
[
"3 And this shall be his uncleanness in his issue: whether his flesh run with his issue, or his flesh be stopped from his issue, it is his uncleanness.",
"4 Every bed, whereon he lieth that hath the issue, is unclean: and every thing, whereon he sitteth, shall be unclean.",
"5 And whosoever toucheth his bed shall wash his clothes, and bathe himself in water, and be unclean until the even.",
"",
"——【The Third Book of Moses: Called Leviticus 15】",
"",
"3 他患漏症，无论是下流的，是止住的，都是不洁净。",
"4 他所躺的床都为不洁净，所坐的物也为不洁净。",
"5 凡摸那床的，必不洁净到晚上，并要洗衣服，用水洗澡。",
"",
"——【利未记 15】",
],
[
"25 (Now the Amalekites and the Canaanites dwelt in the valley.) To morrow turn you, and get you into the wilderness by the way of the Red sea.",
"26 And the LORD spake unto Moses and unto Aaron, saying,",
"27 How long shall I bear with this evil congregation, which murmur against me? I have heard the murmurings of the children of Israel, which they murmur against me.",
"28 Say unto them, As truly as I live, saith the LORD, as ye have spoken in mine ears, so will I do to you:",
"",
"——【The Fourth Book of Moses: Called Numbers 14】",
"",
"25 亚玛力人和迦南人住在谷中，明天你们要转回，从红海的路往旷野去。」",
"26 耶和华对摩西、亚伦说：",
"27 「这恶会众向我发怨言，我忍耐他们要到几时呢？以色列人向我所发的怨言，我都听见了。",
"28 你们告诉他们，耶和华说：『我指著我的永生起誓，我必要照你们达到我耳中的话待你们。",
"",
"——【民数记 14】",
],
[
"13 And one of his servants answered and said, Let some take, I pray thee, five of the horses that remain, which are left in the city, (behold, they are as all the multitude of Israel that are left in it: behold, I say, they are even as all the multitude of the Israelites that are consumed:) and let us send and see.",
"14 They took therefore two chariot horses; and the king sent after the host of the Syrians, saying, Go and see.",
"",
"——【The Second Book of the Kings 7】",
"",
"13 有一个臣仆对王说：「我们不如用城里剩下之马中的五匹马（马和城里剩下的以色列人都是一样，快要灭绝），打发人去窥探。」",
"14 于是取了两辆车和马，王差人去追寻亚兰军，说：「你们去窥探窥探。」",
"",
"——【列王记下 7】",
],
[
"16 They that see thee shall narrowly look upon thee, and consider thee, saying, Is this the man that made the earth to tremble, that did shake kingdoms;",
"17 That made the world as a wilderness, and destroyed the cities thereof; that opened not the house of his prisoners?",
"18 All the kings of the nations, even all of them, lie in glory, every one in his own house.",
"19 But thou art cast out of thy grave like an abominable branch, and as the raiment of those that are slain, thrust through with a sword, that go down to the stones of the pit; as a carcase trodden under feet.",
"",
"——【The Book of the Prophet Isaiah 14】",
"",
"16 凡看见你的都要定睛看你，留意看你，说：使大地战抖，使列国震动，",
"17 使世界如同荒野，使城邑倾覆，不释放被掳的人归家，是这个人吗？",
"18 列国的君王俱各在自己阴宅的荣耀中安睡。",
"19 惟独你被抛弃，不得入你的坟墓，好像可憎的枝子，以被杀的人为衣，就是被刀刺透，坠落坑中石头那里的；你又像被践踏的尸首一样。",
"",
"——【以赛亚书 14】",
],
[
"21 And the king commanded all the people, saying, Keep the passover unto the LORD your God, as it is written in the book of this covenant.",
"22 Surely there was not holden such a passover from the days of the judges that judged Israel, nor in all the days of the kings of Israel, nor of the kings of Judah;",
"23 But in the eighteenth year of king Josiah, wherein this passover was holden to the LORD in Jerusalem.",
"24 Moreover the workers with familiar spirits, and the wizards, and the images, and the idols, and all the abominations that were spied in the land of Judah and in Jerusalem, did Josiah put away, that he might perform the words of the law which were written in the book that Hilkiah the priest found in the house of the LORD.",
"25 And like unto him was there no king before him, that turned to the LORD with all his heart, and with all his soul, and with all his might, according to all the law of Moses; neither after him arose there any like him.",
"26 Notwithstanding the LORD turned not from the fierceness of his great wrath, wherewith his anger was kindled against Judah, because of all the provocations that Manasseh had provoked him withal.",
"",
"——【The Second Book of the Kings 23】",
"",
"21 王吩咐众民说：「你们当照这约书上所写的，向耶和华─你们的　神守逾越节。」",
"22 自从士师治理以色列人和以色列王、犹大王的时候，直到如今，实在没有守过这样的逾越节；",
"23 只有约西亚王十八年在耶路撒冷向耶和华守这逾越节。",
"24 凡犹大国和耶路撒冷所有交鬼的、行巫术的，与家中的神像和偶像，并一切可憎之物，约西亚尽都除掉，成就了祭司希勒家在耶和华殿里所得律法书上所写的话。",
"25 在约西亚以前没有王像他尽心、尽性、尽力地归向耶和华，遵行摩西的一切律法；在他以后也没有兴起一个王像他。",
"26 然而，耶和华向犹大所发猛烈的怒气仍不止息，是因玛拿西诸事惹动他。",
"",
"——【列王记下 23】",
],
[
"20 All the brethren greet you. Greet ye one another with an holy kiss.",
"21 The salutation of me Paul with mine own hand.",
"22 If any man love not the Lord Jesus Christ, let him be Anathema Maranatha.",
"23 The grace of our Lord Jesus Christ be with you.",
"24 My love be with you all in Christ Jesus. Amen.  The first epistle to the Corinthians was written from Philippi by Stephanas, and Fortunatus, and Achaicus, and Timotheus.",
"",
"——【The First Epistle of Paul the Apostle to the Corinthians 16】",
"",
"20 众弟兄都问你们安。你们要亲嘴问安，彼此务要圣洁。",
"21 我─保罗亲笔问安。",
"22 若有人不爱主，这人可诅可咒。主必要来！",
"23 愿主耶稣基督的恩常与你们众人同在！",
"24 我在基督耶稣里的爱与你们众人同在。阿们！",
"",
"——【哥林多前书 16】",
],
[
"1 And it came to pass in the fourth year of king Darius, that the word of the LORD came unto Zechariah in the fourth day of the ninth month, even in Chisleu;",
"2 When they had sent unto the house of God Sherezer and Regem–melech, and their men, to pray before the LORD,",
"3 And to speak unto the priests which were in the house of the LORD of hosts, and to the prophets, saying, Should I weep in the fifth month, separating myself, as I have done these so many years?",
"",
"——【Zechariah 7】",
"",
"1 大利乌王第四年九月，就是基斯流月初四日，耶和华的话临到撒迦利亚。",
"2 那时伯特利人已经打发沙利亚和利坚米勒，并跟从他们的人，去恳求耶和华的恩，",
"3 并问万军之耶和华殿中的祭司和先知说：「我历年以来，在五月间哭泣斋戒，现在还当这样行吗？」",
"",
"——【撒迦利亚书 7】",
],
[
"12 Then spake Jesus again unto them, saying, I am the light of the world: he that followeth me shall not walk in darkness, but shall have the light of life.",
"13 The Pharisees therefore said unto him, Thou bearest record of thyself; thy record is not true.",
"14 Jesus answered and said unto them, Though I bear record of myself, yet my record is true: for I know whence I came, and whither I go; but ye cannot tell whence I come, and whither I go.",
"15 Ye judge after the flesh; I judge no man.",
"16 And yet if I judge, my judgment is true: for I am not alone, but I and the Father that sent me.",
"",
"——【The Gospel According to Saint John 8】",
"",
"12 耶稣又对众人说：我是世界的光。跟从我的，就不在黑暗里走，必要得著生命的光。",
"13 法利赛人对他说：你是为自己作见证，你的见证不真。",
"14 耶稣说：我虽然为自己作见证，我的见证还是真的；因我知道我从那里来，往那里去；你们却不知道我从那里来，往那里去。",
"15 你们是以外貌（原文是凭肉身）判断人，我却不判断人。",
"16 就是判断人，我的判断也是真的；因为不是我独自在这里，还有差我来的父与我同在。",
"",
"——【约翰福音 8】",
],
[
"1 And the LORD spake unto Moses, saying,",
"2 On the first day of the first month shalt thou set up the tabernacle of the tent of the congregation.",
"3 And thou shalt put therein the ark of the testimony, and cover the ark with the vail.",
"4 And thou shalt bring in the table, and set in order the things that are to be set in order upon it; and thou shalt bring in the candlestick, and light the lamps thereof.",
"5 And thou shalt set the altar of gold for the incense before the ark of the testimony, and put the hanging of the door to the tabernacle.",
"6 And thou shalt set the altar of the burnt offering before the door of the tabernacle of the tent of the congregation.",
"",
"——【The Second Book of Moses: Called Exodus 40】",
"",
"1 耶和华晓谕摩西说：",
"2 「正月初一日，你要立起帐幕，",
"3 把法柜安放在里面，用幔子将柜遮掩。",
"4 把桌子搬进去，摆设上面的物。把灯台搬进去，点其上的灯。",
"5 把烧香的金坛安在法柜前，挂上帐幕的门帘。",
"6 把燔祭坛安在帐幕门前。",
"",
"——【出埃及记 40】",
],
[
"6 Wherewith shall I come before the LORD, and bow myself before the high God? shall I come before him with burnt offerings, with calves of a year old?",
"7 Will the LORD be pleased with thousands of rams, or with ten thousands of rivers of oil? shall I give my firstborn for my transgression, the fruit of my body for the sin of my soul?",
"8 He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?",
"",
"——【Micah 6】",
"",
"6 我朝见耶和华，在至高　神面前跪拜，当献上什么呢？岂可献一岁的牛犊为燔祭吗？",
"7 耶和华岂喜悦千千的公羊，或是万万的油河吗？我岂可为自己的罪过献我的长子吗？为心中的罪恶献我身所生的吗？",
"8 世人哪，耶和华已指示你何为善。他向你所要的是什么呢？只要你行公义，好怜悯，存谦卑的心，与你的　神同行。",
"",
"——【弥迦书 6】",
],
[
"9 And the great dragon was cast out, that old serpent, called the Devil, and Satan, which deceiveth the whole world: he was cast out into the earth, and his angels were cast out with him.",
"10 And I heard a loud voice saying in heaven, Now is come salvation, and strength, and the kingdom of our God, and the power of his Christ: for the accuser of our brethren is cast down, which accused them before our God day and night.",
"11 And they overcame him by the blood of the Lamb, and by the word of their testimony; and they loved not their lives unto the death.",
"12 Therefore rejoice, ye heavens, and ye that dwell in them. Woe to the inhabiters of the earth and of the sea! for the devil is come down unto you, having great wrath, because he knoweth that he hath but a short time.",
"13 And when the dragon saw that he was cast unto the earth, he persecuted the woman which brought forth the man child.",
"14 And to the woman were given two wings of a great eagle, that she might fly into the wilderness, into her place, where she is nourished for a time, and times, and half a time, from the face of the serpent.",
"",
"——【The Revelation of Saint John the Devine 12】",
"",
"9 大龙就是那古蛇，名叫魔鬼，又叫撒但，是迷惑普天下的。牠被摔在地上，牠的使者也一同被摔下去。",
"10 我听见在天上有大声音说：我　神的救恩、能力、国度、并他基督的权柄，现在都来到了！因为那在我们　神面前昼夜控告我们弟兄的，已经被摔下去了。",
"11 弟兄胜过他，是因羔羊的血和自己所见证的道。他们虽至于死，也不爱惜性命。",
"12 所以，诸天和住在其中的，你们都快乐吧！只是地与海有祸了！因为魔鬼知道自己的时候不多，就气忿忿的下到你们那里去了。",
"13 龙见自己被摔在地上，就逼迫那生男孩子的妇人。",
"14 于是有大鹰的两个翅膀赐给妇人，叫她能飞到旷野，到自己的地方，躲避那蛇；她在那里被养活一载二载半载。",
"",
"——【启示录 12】",
],
[
"5 Trust ye not in a friend, put ye not confidence in a guide: keep the doors of thy mouth from her that lieth in thy bosom.",
"6 For the son dishonoureth the father, the daughter riseth up against her mother, the daughter in law against her mother in law; a man's enemies are the men of his own house.",
"7 Therefore I will look unto the LORD; I will wait for the God of my salvation: my God will hear me.",
"8 Rejoice not against me, O mine enemy: when I fall, I shall arise; when I sit in darkness, the LORD shall be a light unto me.",
"9 I will bear the indignation of the LORD, because I have sinned against him, until he plead my cause, and execute judgment for me: he will bring me forth to the light, and I shall behold his righteousness.",
"10 Then she that is mine enemy shall see it, and shame shall cover her which said unto me, Where is the LORD thy God? mine eyes shall behold her: now shall she be trodden down as the mire of the streets.",
"",
"——【Micah 7】",
"",
"5 不要倚赖邻舍；不要信靠密友。要守住你的口；不要向你怀中的妻提说。",
"6 因为，儿子藐视父亲；女儿抗拒母亲；媳妇抗拒婆婆；人的仇敌就是自己家里的人。",
"7 至于我，我要仰望耶和华，要等候那救我的　神；我的　神必应允我。",
"8 我的仇敌啊，不要向我夸耀。我虽跌倒，却要起来；我虽坐在黑暗里，耶和华却作我的光。",
"9 我要忍受耶和华的恼怒；因我得罪了他，直等他为我辨屈，为我伸冤。他必领我到光明中；我必得见他的公义。",
"10 那时我的仇敌，就是曾对我说耶和华─你　神在哪里的，他一看见这事就被羞愧遮盖。我必亲眼见他遭报；他必被践踏，如同街上的泥土。",
"",
"——【弥迦书 7】",
],
[
"3 Will he make many supplications unto thee? will he speak soft words unto thee?",
"4 Will he make a covenant with thee? wilt thou take him for a servant for ever?",
"",
"——【The Book of Job 41】",
"",
"3 牠岂向你连连恳求，说柔和的话吗？",
"4 岂肯与你立约，使你拿牠永远作奴仆吗？",
"",
"——【约伯记 41】",
],
[
"8 Will ye accept his person? will ye contend for God?",
"9 Is it good that he should search you out? or as one man mocketh another, do ye so mock him?",
"10 He will surely reprove you, if ye do secretly accept persons.",
"11 Shall not his excellency make you afraid? and his dread fall upon you?",
"12 Your remembrances are like unto ashes, your bodies to bodies of clay.",
"13 Hold your peace, let me alone, that I may speak, and let come on me what will.",
"",
"——【The Book of Job 13】",
"",
"8 你们要为　神徇情吗？要为他争论吗？",
"9 他查出你们来，这岂是好吗？人欺哄人，你们也要照样欺哄他吗？",
"10 你们若暗中徇情，他必要责备你们。",
"11 他的尊荣岂不叫你们惧怕吗？他的惊吓岂不临到你们吗？",
"12 你们以为可记念的箴言是炉灰的箴言；你们以为可靠的坚垒是淤泥的坚垒。",
"13 你们不要作声，任凭我吧！让我说话，无论如何我都承当。",
"",
"——【约伯记 13】",
],
[
"15 And let them be for lights in the firmament of the heaven to give light upon the earth: and it was so.",
"16 And God made two great lights; the greater light to rule the day, and the lesser light to rule the night: he made the stars also.",
"17 And God set them in the firmament of the heaven to give light upon the earth,",
"18 And to rule over the day and over the night, and to divide the light from the darkness: and God saw that it was good.",
"19 And the evening and the morning were the fourth day.",
"20 And God said, Let the waters bring forth abundantly the moving creature that hath life, and fowl that may fly above the earth in the open firmament of heaven.",
"",
"——【The First Book of Moses: Called Genesis 1】",
"",
"15 并要发光在天空，普照在地上。」事就这样成了。",
"16 于是　神造了两个大光，大的管昼，小的管夜，又造众星，",
"17 就把这些光摆列在天空，普照在地上，",
"18 管理昼夜，分别明暗。　神看着是好的。",
"19 有晚上，有早晨，是第四日。",
"20 　神说：「水要多多滋生有生命的物；要有雀鸟飞在地面以上，天空之中（原文作天空的表面）。」",
"",
"——【创世记 1】",
],
[
"18 Cursed be he that maketh the blind to wander out of the way. And all the people shall say, Amen.",
"19 Cursed be he that perverteth the judgment of the stranger, fatherless, and widow. And all the people shall say, Amen.",
"20 Cursed be he that lieth with his father's wife; because he uncovereth his father's skirt. And all the people shall say, Amen.",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 27】",
"",
"18 「『使瞎子走差路的，必受咒诅！』百姓都要说：『阿们！』",
"19 「『向寄居的和孤儿寡妇屈枉正直的，必受咒诅！』百姓都要说：『阿们！』",
"20 「『与继母行淫的，必受咒诅！因为掀开他父亲的衣襟。』百姓都要说：『阿们！』",
"",
"——【申命记 27】",
],
[
"6 But she had brought them up to the roof of the house, and hid them with the stalks of flax, which she had laid in order upon the roof.",
"7 And the men pursued after them the way to Jordan unto the fords: and as soon as they which pursued after them were gone out, they shut the gate.",
"8 And before they were laid down, she came up unto them upon the roof;",
"",
"——【The Book of Joshua 2】",
"",
"6 （先是女人领二人上了房顶，将他们藏在那里所摆的麻秸中。）",
"7 那些人就往约旦河的渡口追赶他们去了。追赶他们的人一出去，城门就关了。",
"8 二人还没有躺卧，女人就上房顶，到他们那里，",
"",
"——【约书亚记 2】",
],
[
"13 That thou mayest give him rest from the days of adversity, until the pit be digged for the wicked.",
"14 For the LORD will not cast off his people, neither will he forsake his inheritance.",
"",
"——【The Book of Psalms 94】",
"",
"13 你使他在遭难的日子得享平安；惟有恶人陷在所挖的坑中。",
"14 因为耶和华必不丢弃他的百姓，也不离弃他的产业。",
"",
"——【诗篇 94】",
],
[
"4 For Christ is the end of the law for righteousness to every one that believeth.",
"5 For Moses describeth the righteousness which is of the law, That the man which doeth those things shall live by them.",
"6 But the righteousness which is of faith speaketh on this wise, Say not in thine heart, Who shall ascend into heaven? (that is, to bring Christ down from above:)",
"7 Or, Who shall descend into the deep? (that is, to bring up Christ again from the dead.)",
"8 But what saith it? The word is nigh thee, even in thy mouth, and in thy heart: that is, the word of faith, which we preach;",
"9 That if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved.",
"",
"——【The Epistle of Paul the Apostle to the Romans 10】",
"",
"4 律法的总结就是基督，使凡信他的都得著义。",
"5 摩西写著说：人若行那出于律法的义，就必因此活著。",
"6 惟有出于信心的义如此说：你不要心里说：谁要升到天上去呢？就是要领下基督来；",
"7 谁要下到阴间去呢？就是要领基督从死里上来。",
"8 他到底怎么说呢？他说：这道离你不远，正在你口里，在你心里。（就是我们所传信主的道。）",
"9 你若口里认耶稣为主，心里信　神叫他从死里复活，就必得救。",
"",
"——【罗马书 10】",
],
[
"8 I will hear what God the LORD will speak: for he will speak peace unto his people, and to his saints: but let them not turn again to folly.",
"9 Surely his salvation is nigh them that fear him; that glory may dwell in our land.",
"10 Mercy and truth are met together; righteousness and peace have kissed each other.",
"11 Truth shall spring out of the earth; and righteousness shall look down from heaven.",
"12 Yea, the LORD shall give that which is good; and our land shall yield her increase.",
"13 Righteousness shall go before him; and shall set us in the way of his steps.",
"",
"——【The Book of Psalms 85】",
"",
"8 我要听　神─耶和华所说的话；因为他必应许将平安赐给他的百姓─他的圣民；他们却不可再转去妄行。",
"9 他的救恩诚然与敬畏他的人相近，叫荣耀住在我们的地上。",
"10 慈爱和诚实彼此相遇；公义和平安彼此相亲。",
"11 诚实从地而生；公义从天而现。",
"12 耶和华必将好处赐给我们；我们的地也要多出土产。",
"13 公义要行在他面前，叫他的脚踪成为可走的路。",
"",
"——【诗篇 85】",
],
[
"1 Who hath believed our report? and to whom is the arm of the LORD revealed?",
"2 For he shall grow up before him as a tender plant, and as a root out of a dry ground: he hath no form nor comeliness; and when we shall see him, there is no beauty that we should desire him.",
"3 He is despised and rejected of men; a man of sorrows, and acquainted with grief: and we hid as it were our faces from him; he was despised, and we esteemed him not.",
"4 Surely he hath borne our griefs, and carried our sorrows: yet we did esteem him stricken, smitten of God, and afflicted.",
"5 But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed.",
"",
"——【The Book of the Prophet Isaiah 53】",
"",
"1 我们所传的（或译：所传与我们的）有谁信呢？耶和华的膀臂向谁显露呢？",
"2 他在耶和华面前生长如嫩芽，像根出于干地。他无佳形美容；我们看见他的时候，也无美貌使我们羨慕他。",
"3 他被藐视，被人厌弃；多受痛苦，常经忧患。他被藐视，好像被人掩面不看的一样；我们也不尊重他。",
"4 他诚然担当我们的忧患，背负我们的痛苦；我们却以为他受责罚，被　神击打苦待了。",
"5 哪知他为我们的过犯受害，为我们的罪孽压伤。因他受的刑罚，我们得平安；因他受的鞭伤，我们得医治。",
"",
"——【以赛亚书 53】",
],
[
"5 Even so the tongue is a little member, and boasteth great things. Behold, how great a matter a little fire kindleth!",
"6 And the tongue is a fire, a world of iniquity: so is the tongue among our members, that it defileth the whole body, and setteth on fire the course of nature; and it is set on fire of hell.",
"",
"——【The General Epistle of James 3】",
"",
"5 这样，舌头在百体里也是最小的，却能说大话。看哪，最小的火能点著最大的树林。",
"6 舌头就是火，在我们百体中，舌头是个罪恶的世界，能污秽全身，也能把生命的轮子点起来，并且是从地狱里点著的。",
"",
"——【雅各书 3】",
],
[
"5 And Joshua said unto the people, Sanctify yourselves: for to morrow the LORD will do wonders among you.",
"6 And Joshua spake unto the priests, saying, Take up the ark of the covenant, and pass over before the people. And they took up the ark of the covenant, and went before the people.",
"7 And the LORD said unto Joshua, This day will I begin to magnify thee in the sight of all Israel, that they may know that, as I was with Moses, so I will be with thee.",
"8 And thou shalt command the priests that bear the ark of the covenant, saying, When ye are come to the brink of the water of Jordan, ye shall stand still in Jordan.",
"9 And Joshua said unto the children of Israel, Come hither, and hear the words of the LORD your God.",
"",
"——【The Book of Joshua 3】",
"",
"5 约书亚吩咐百姓说：「你们要自洁，因为明天耶和华必在你们中间行奇事。」",
"6 约书亚又吩咐祭司说：「你们抬起约柜，在百姓前头过去。」于是他们抬起约柜，在百姓前头走。",
"7 耶和华对约书亚说：「从今日起，我必使你在以色列众人眼前尊大，使他们知道我怎样与摩西同在，也必照样与你同在。",
"8 你要吩咐抬约柜的祭司说：『你们到了约旦河的水边上，就要在约旦河水里站住。』」",
"9 约书亚对以色列人说：「你们近前来，听耶和华─你们　神的话。」",
"",
"——【约书亚记 3】",
],
[
"13 Then let our countenances be looked upon before thee, and the countenance of the children that eat of the portion of the king's meat: and as thou seest, deal with thy servants.",
"14 So he consented to them in this matter, and proved them ten days.",
"15 And at the end of ten days their countenances appeared fairer and fatter in flesh than all the children which did eat the portion of the king's meat.",
"16 Thus Melzar took away the portion of their meat, and the wine that they should drink; and gave them pulse.",
"",
"——【The Book of Daniel 1】",
"",
"13 然后看看我们的面貌和用王膳那少年人的面貌，就照你所看的待仆人吧！」",
"14 委办便允准他们这件事，试看他们十天。",
"15 过了十天，见他们的面貌比用王膳的一切少年人更加俊美肥胖。",
"16 于是委办撤去派他们用的膳，饮的酒，给他们素菜吃。",
"",
"——【但以理书 1】",
],
[
"28 And he said unto his brethren, My money is restored; and, lo, it is even in my sack: and their heart failed them, and they were afraid, saying one to another, What is this that God hath done unto us?",
"29 And they came unto Jacob their father unto the land of Canaan, and told him all that befell unto them; saying,",
"30 The man, who is the lord of the land, spake roughly to us, and took us for spies of the country.",
"31 And we said unto him, We are true men; we are no spies:",
"32 We be twelve brethren, sons of our father; one is not, and the youngest is this day with our father in the land of Canaan.",
"",
"——【The First Book of Moses: Called Genesis 42】",
"",
"28 就对弟兄们说：「我的银子归还了，看哪，仍在我口袋里！」他们就提心吊胆，战战兢兢的彼此说：「这是　神向我们做什么呢？」",
"29 他们来到迦南地、他们的父亲雅各那里，将所遭遇的事都告诉他，说：",
"30 「那地的主对我们说严厉的话，把我们当作窥探那地的奸细。",
"31 我们对他说：『我们是诚实人，并不是奸细。",
"32 我们本是弟兄十二人，都是一个父亲的儿子，有一个没有了，顶小的如今同我们的父亲在迦南地。』",
"",
"——【创世记 42】",
],
[
"7 Gird up thy loins now like a man: I will demand of thee, and declare thou unto me.",
"8 Wilt thou also disannul my judgment? wilt thou condemn me, that thou mayest be righteous?",
"9 Hast thou an arm like God? or canst thou thunder with a voice like him?",
"10 Deck thyself now with majesty and excellency; and array thyself with glory and beauty.",
"",
"——【The Book of Job 40】",
"",
"7 你要如勇士束腰；我问你，你可以指示我。",
"8 你岂可废弃我所拟定的？岂可定我有罪，好显自己为义吗？",
"9 你有　神那样的膀臂吗？你能像他发雷声吗？",
"10 你要以荣耀庄严为妆饰，以尊荣威严为衣服；",
"",
"——【约伯记 40】",
],
[
"6 A scorner seeketh wisdom, and findeth it not: but knowledge is easy unto him that understandeth.",
"7 Go from the presence of a foolish man, when thou perceivest not in him the lips of knowledge.",
"8 The wisdom of the prudent is to understand his way: but the folly of fools is deceit.",
"",
"——【The Proverbs 14】",
"",
"6 亵慢人寻智慧，却寻不著；聪明人易得知识。",
"7 到愚昧人面前，不见他嘴中有知识。",
"8 通达人的智慧在乎明白己道；愚昧人的愚妄乃是诡诈（或译：自叹）。",
"",
"——【箴言 14】",
],
[
"1 Hear my cry, O God; attend unto my prayer.",
"2 From the end of the earth will I cry unto thee, when my heart is overwhelmed: lead me to the rock that is higher than I.",
"3 For thou hast been a shelter for me, and a strong tower from the enemy.",
"",
"——【The Book of Psalms 61】",
"",
"1 （大卫的诗，交与伶长。用丝弦的乐器。）　神啊，求你听我的呼求，侧耳听我的祷告！",
"2 我心里发昏的时候，我要从地极求告你。求你领我到那比我更高的磐石！",
"3 因为你作过我的避难所，作过我的坚固台，脱离仇敌。",
"",
"——【诗篇 61】",
],
[
"4 I drew them with cords of a man, with bands of love: and I was to them as they that take off the yoke on their jaws, and I laid meat unto them.",
"5 He shall not return into the land of Egypt, but the Assyrian shall be his king, because they refused to return.",
"6 And the sword shall abide on his cities, and shall consume his branches, and devour them, because of their own counsels.",
"7 And my people are bent to backsliding from me: though they called them to the most High, none at all would exalt him.",
"",
"——【Hosea 11】",
"",
"4 我用慈绳（慈：原文是人的）爱索牵引他们；我待他们如人放松牛的两腮夹板，把粮食放在他们面前。",
"5 他们必不归回埃及地，亚述人却要作他们的王，因他们不肯归向我。",
"6 刀剑必临到他们的城邑，毁坏门闩，把人吞灭，都因他们随从自己的计谋。",
"7 我的民偏要背道离开我；众先知虽然招呼他们归向至上的主，却无人尊崇主。",
"",
"——【何西阿书 11】",
],
[
"5 Let the enemy persecute my soul, and take it; yea, let him tread down my life upon the earth, and lay mine honour in the dust. Selah.",
"6 Arise, O LORD, in thine anger, lift up thyself because of the rage of mine enemies: and awake for me to the judgment that thou hast commanded.",
"",
"——【The Book of Psalms 7】",
"",
"5 就任凭仇敌追赶我，直到追上，将我的性命踏在地下，使我的荣耀归于灰尘。（细拉）",
"6 耶和华啊，求你在怒中起来，挺身而立，抵挡我敌人的暴怒！求你为我兴起！你已经命定施行审判！",
"",
"——【诗篇 7】",
],
[
"11 And I will rebuke the devourer for your sakes, and he shall not destroy the fruits of your ground; neither shall your vine cast her fruit before the time in the field, saith the LORD of hosts.",
"12 And all nations shall call you blessed: for ye shall be a delightsome land, saith the LORD of hosts.",
"",
"——【Malachi 3】",
"",
"11 万军之耶和华说：我必为你们斥责蝗虫（原文是吞噬者），不容牠毁坏你们的土产。你们田间的葡萄树在未熟之先也不掉果子。",
"12 万军之耶和华说：万国必称你们为有福的，因你们的地必成为喜乐之地。」",
"",
"——【玛拉基书 3】",
],
];
