var bible31_global=[
[
"33 And their coast was from Heleph, from Allon to Zaanannim, and Adami, Nekeb, and Jabneel, unto Lakum; and the outgoings thereof were at Jordan:",
"34 And then the coast turneth westward to Aznoth–tabor, and goeth out from thence to Hukkok, and reacheth to Zebulun on the south side, and reacheth to Asher on the west side, and to Judah upon Jordan toward the sunrising.",
"35 And the fenced cities are Ziddim, Zer, and Hammath, Rakkath, and Chinnereth,",
"36 And Adamah, and Ramah, and Hazor,",
"37 And Kedesh, and Edrei, and En–hazor,",
"",
"——【The Book of Joshua 19】",
"",
"33 他们的境界是从希利弗从撒拿音的橡树，从亚大米‧尼吉和雅比聂，直到拉共，通到约旦河；",
"34 又转向西到亚斯纳‧他泊，从那里通到户割，南边到西布伦，西边到亚设，又向日出之地，达到约旦河那里的犹大。",
"35 坚固的城就是：西丁、侧耳、哈末、拉甲、基尼烈、",
"36 亚大玛、拉玛、夏琐、",
"37 基低斯、以得来、隐‧夏琐、",
"",
"——【约书亚记 19】",
],
[
"3 Let them praise his name in the dance: let them sing praises unto him with the timbrel and harp.",
"4 For the LORD taketh pleasure in his people: he will beautify the meek with salvation.",
"5 Let the saints be joyful in glory: let them sing aloud upon their beds.",
"6 Let the high praises of God be in their mouth, and a twoedged sword in their hand;",
"",
"——【The Book of Psalms 149】",
"",
"3 愿他们跳舞赞美他的名，击鼓弹琴歌颂他！",
"4 因为耶和华喜爱他的百姓；他要用救恩当作谦卑人的妆饰。",
"5 愿圣民因所得的荣耀高兴！愿他们在床上欢呼！",
"6 愿他们口中称赞　神为高，手里有两刃的刀，",
"",
"——【诗篇 149】",
],
[
"1 To every thing there is a season, and a time to every purpose under the heaven:",
"2 A time to be born, and a time to die; a time to plant, and a time to pluck up that which is planted;",
"3 A time to kill, and a time to heal; a time to break down, and a time to build up;",
"4 A time to weep, and a time to laugh; a time to mourn, and a time to dance;",
"5 A time to cast away stones, and a time to gather stones together; a time to embrace, and a time to refrain from embracing;",
"",
"——【Ecclesiastes 3】",
"",
"1 凡事都有定期，天下万务都有定时。",
"2 生有时，死有时；栽种有时，拔出所栽种的也有时；",
"3 杀戮有时，医治有时；拆毁有时，建造有时；",
"4 哭有时，笑有时；哀恸有时，跳舞有时；",
"5 抛掷石头有时，堆聚石头有时；怀抱有时，不怀抱有时；",
"",
"——【传道书 3】",
],
[
"1 Oh that my head were waters, and mine eyes a fountain of tears, that I might weep day and night for the slain of the daughter of my people!",
"2 Oh that I had in the wilderness a lodging place of wayfaring men; that I might leave my people, and go from them! for they be all adulterers, an assembly of treacherous men.",
"3 And they bend their tongues like their bow for lies: but they are not valiant for the truth upon the earth; for they proceed from evil to evil, and they know not me, saith the LORD.",
"4 Take ye heed every one of his neighbour, and trust ye not in any brother: for every brother will utterly supplant, and every neighbour will walk with slanders.",
"5 And they will deceive every one his neighbour, and will not speak the truth: they have taught their tongue to speak lies, and weary themselves to commit iniquity.",
"",
"——【The Book of the Prophet Jeremiah 9】",
"",
"1 但愿我的头为水，我的眼为泪的泉源，我好为我百姓（原文是民女；七节同）中被杀的人昼夜哭泣。",
"2 惟愿我在旷野有行路人住宿之处，使我可以离开我的民出去；因他们都是行奸淫的，是行诡诈的一党。",
"3 他们弯起舌头像弓一样，为要说谎话。他们在国中增长势力，不是为行诚实，乃是恶上加恶，并不认识我。这是耶和华说的。",
"4 你们各人当谨防邻舍，不可信靠弟兄；因为弟兄尽行欺骗，邻舍都往来谗谤人。",
"5 他们各人欺哄邻舍，不说真话；他们教舌头学习说谎，劳劳碌碌地作孽。",
"",
"——【耶利米书 9】",
],
[
"15 And Kattath, and Nahallal, and Shimron, and Idalah, and Beth–lehem: twelve cities with their villages.",
"16 This is the inheritance of the children of Zebulun according to their families, these cities with their villages.",
"17 And the fourth lot came out to Issachar, for the children of Issachar according to their families.",
"",
"——【The Book of Joshua 19】",
"",
"15 还有加他、拿哈拉、伸仑、以大拉、伯利恒，共十二座城，还有属城的村庄。",
"16 这些城并属城的村庄就是西布伦人按着宗族所得的地业。",
"17 为以萨迦人，按着宗族，拈出第四阄。",
"",
"——【约书亚记 19】",
],
[
"7 And when the Philistines heard that the children of Israel were gathered together to Mizpeh, the lords of the Philistines went up against Israel. And when the children of Israel heard it, they were afraid of the Philistines.",
"8 And the children of Israel said to Samuel, Cease not to cry unto the LORD our God for us, that he will save us out of the hand of the Philistines.",
"9 And Samuel took a sucking lamb, and offered it for a burnt offering wholly unto the LORD: and Samuel cried unto the LORD for Israel; and the LORD heard him.",
"",
"——【The First Book of Samuel 7】",
"",
"7 非利士人听见以色列人聚集在米斯巴，非利士的首领就上来要攻击以色列人。以色列人听见，就惧怕非利士人。",
"8 以色列人对撒母耳说：「愿你不住地为我们呼求耶和华─我们的　神，救我们脱离非利士人的手。」",
"9 撒母耳就把一只吃奶的羊羔献与耶和华作全牲的燔祭，为以色列人呼求耶和华；耶和华就应允他。",
"",
"——【撒母耳记上 7】",
],
[
"17 Behold, I will stir up the Medes against them, which shall not regard silver; and as for gold, they shall not delight in it.",
"18 Their bows also shall dash the young men to pieces; and they shall have no pity on the fruit of the womb; their eye shall not spare children.",
"19 And Babylon, the glory of kingdoms, the beauty of the Chaldees' excellency, shall be as when God overthrew Sodom and Gomorrah.",
"20 It shall never be inhabited, neither shall it be dwelt in from generation to generation: neither shall the Arabian pitch tent there; neither shall the shepherds make their fold there.",
"21 But wild beasts of the desert shall lie there; and their houses shall be full of doleful creatures; and owls shall dwell there, and satyrs shall dance there.",
"",
"——【The Book of the Prophet Isaiah 13】",
"",
"17 我必激动玛代人来攻击他们。玛代人不注重银子，也不喜爱金子。",
"18 他们必用弓击碎少年人，不怜悯妇人所生的，眼也不顾惜孩子。",
"19 巴比伦素来为列国的荣耀，为迦勒底人所矜夸的华美，必像　神所倾覆的所多玛、蛾摩拉一样。",
"20 其内必永无人烟，世世代代无人居住。亚拉伯人也不在那里支搭帐棚；牧羊的人也不使羊群卧在那里。",
"21 只有旷野的走兽卧在那里；咆哮的兽满了房屋。鸵鸟住在那里；野山羊在那里跳舞。",
"",
"——【以赛亚书 13】",
],
[
"10 Whatsoever thy hand findeth to do, do it with thy might; for there is no work, nor device, nor knowledge, nor wisdom, in the grave, whither thou goest.",
"11 I returned, and saw under the sun, that the race is not to the swift, nor the battle to the strong, neither yet bread to the wise, nor yet riches to men of understanding, nor yet favour to men of skill; but time and chance happeneth to them all.",
"12 For man also knoweth not his time: as the fishes that are taken in an evil net, and as the birds that are caught in the snare; so are the sons of men snared in an evil time, when it falleth suddenly upon them.",
"13 This wisdom have I seen also under the sun, and it seemed great unto me:",
"14 There was a little city, and few men within it; and there came a great king against it, and besieged it, and built great bulwarks against it:",
"",
"——【Ecclesiastes 9】",
"",
"10 凡你手所当做的事要尽力去做；因为在你所必去的阴间没有工作，没有谋算，没有知识，也没有智慧。",
"11 我又转念：见日光之下，快跑的未必能赢；力战的未必得胜；智慧的未必得粮食；明哲的未必得资财；灵巧的未必得喜悦。所临到众人的是在乎当时的机会。",
"12 原来人也不知道自己的定期。鱼被恶网圈住，鸟被网罗捉住，祸患忽然临到的时候，世人陷在其中也是如此。",
"13 我见日光之下有一样智慧，据我看乃是广大，",
"14 就是有一小城，其中的人数稀少，有大君王来攻击，修筑营垒，将城围困。",
"",
"——【传道书 9】",
],
[
"15 And after those days we took up our carriages, and went up to Jerusalem.",
"16 There went with us also certain of the disciples of Cæsarea, and brought with them one Mnason of Cyprus, an old disciple, with whom we should lodge.",
"17 And when we were come to Jerusalem, the brethren received us gladly.",
"18 And the day following Paul went in with us unto James; and all the elders were present.",
"",
"——【The Acts of the Apostles 21】",
"",
"15 过了几日，我们收拾行李上耶路撒冷去。",
"16 有凯撒利亚的几个门徒和我们同去，带我们到一个久为（久为：或作老）门徒的家里，叫我们与他同住；他名叫拿孙，是塞浦路斯人。",
"17 到了耶路撒冷，弟兄们欢欢喜喜的接待我们。",
"18 第二天，保罗同我们去见雅各；长老们也都在那里。",
"",
"——【使徒行传 21】",
],
[
"1 Thus saith the LORD, Where is the bill of your mother's divorcement, whom I have put away? or which of my creditors is it to whom I have sold you? Behold, for your iniquities have ye sold yourselves, and for your transgressions is your mother put away.",
"2 Wherefore, when I came, was there no man? when I called, was there none to answer? Is my hand shortened at all, that it cannot redeem? or have I no power to deliver? behold, at my rebuke I dry up the sea, I make the rivers a wilderness: their fish stinketh, because there is no water, and dieth for thirst.",
"",
"——【The Book of the Prophet Isaiah 50】",
"",
"1 耶和华如此说：我休你们的母亲，休书在哪里呢？我将你们卖给我哪一个债主呢？你们被卖，是因你们的罪孽；你们的母亲被休，是因你们的过犯。",
"2 我来的时候，为何无人等候呢？我呼唤的时候，为何无人答应呢？我的膀臂岂是缩短、不能救赎吗？我岂无拯救之力吗？看哪，我一斥责，海就干了；我使江河变为旷野；其中的鱼因无水腥臭，干渴而死。",
"",
"——【以赛亚书 50】",
],
[
"13 And burned the house of the LORD, and the king's house; and all the houses of Jerusalem, and all the houses of the great men, burned he with fire:",
"14 And all the army of the Chaldeans, that were with the captain of the guard, brake down all the walls of Jerusalem round about.",
"15 Then Nebuzar–adan the captain of the guard carried away captive certain of the poor of the people, and the residue of the people that remained in the city, and those that fell away, that fell to the king of Babylon, and the rest of the multitude.",
"16 But Nebuzar–adan the captain of the guard left certain of the poor of the land for vinedressers and for husbandmen.",
"17 Also the pillars of brass that were in the house of the LORD, and the bases, and the brasen sea that was in the house of the LORD, the Chaldeans brake, and carried all the brass of them to Babylon.",
"",
"——【The Book of the Prophet Jeremiah 52】",
"",
"13 用火焚烧耶和华的殿和王宫，又焚烧耶路撒冷的房屋，就是各大户家的房屋。",
"14 跟从护卫长迦勒底的全军就拆毁耶路撒冷四围的城墙。",
"15 那时护卫长尼布撒拉旦将民中最穷的和城里所剩下的百姓，并已经投降巴比伦王的人，以及大众所剩下的人，都掳去了。",
"16 但护卫长尼布撒拉旦留下些民中最穷的，使他们修理葡萄园，耕种田地。",
"17 耶和华殿的铜柱并殿内的盆座和铜海，迦勒底人都打碎了，将那铜运到巴比伦去了，",
"",
"——【耶利米书 52】",
],
[
"11 Hell and destruction are before the LORD: how much more then the hearts of the children of men?",
"12 A scorner loveth not one that reproveth him: neither will he go unto the wise.",
"13 A merry heart maketh a cheerful countenance: but by sorrow of the heart the spirit is broken.",
"14 The heart of him that hath understanding seeketh knowledge: but the mouth of fools feedeth on foolishness.",
"15 All the days of the afflicted are evil: but he that is of a merry heart hath a continual feast.",
"16 Better is little with the fear of the LORD than great treasure and trouble therewith.",
"",
"——【The Proverbs 15】",
"",
"11 阴间和灭亡尚在耶和华眼前，何况世人的心呢？",
"12 亵慢人不爱受责备；他也不就近智慧人。",
"13 心中喜乐，面带笑容；心里忧愁，灵被损伤。",
"14 聪明人心求知识；愚昧人口吃愚昧。",
"15 困苦人的日子都是愁苦；心中欢畅的，常享丰筵。",
"16 少有财宝，敬畏耶和华，强如多有财宝，烦乱不安。",
"",
"——【箴言 15】",
],
[
"29 Because thy rage against me, and thy tumult, is come up into mine ears, therefore will I put my hook in thy nose, and my bridle in thy lips, and I will turn thee back by the way by which thou camest.",
"30 And this shall be a sign unto thee, Ye shall eat this year such as groweth of itself; and the second year that which springeth of the same: and in the third year sow ye, and reap, and plant vineyards, and eat the fruit thereof.",
"",
"——【The Book of the Prophet Isaiah 37】",
"",
"29 因你向我发烈怒，又因你狂傲的话达到我耳中，我就要用钩子钩上你的鼻子，把嚼环放在你口里，使你从原路转回去。",
"30 「以色列人哪，我赐你们一个证据：你们今年要吃自生的，明年也要吃自长的，至于后年，你们要耕种收割，栽植葡萄园，吃其中的果子。",
"",
"——【以赛亚书 37】",
],
[
"7 So that ye come behind in no gift; waiting for the coming of our Lord Jesus Christ:",
"8 Who shall also confirm you unto the end, that ye may be blameless in the day of our Lord Jesus Christ.",
"9 God is faithful, by whom ye were called unto the fellowship of his Son Jesus Christ our Lord.",
"10 Now I beseech you, brethren, by the name of our Lord Jesus Christ, that ye all speak the same thing, and that there be no divisions among you; but that ye be perfectly joined together in the same mind and in the same judgment.",
"11 For it hath been declared unto me of you, my brethren, by them which are of the house of Chloe, that there are contentions among you.",
"12 Now this I say, that every one of you saith, I am of Paul; and I of Apollos; and I of Cephas; and I of Christ.",
"",
"——【The First Epistle of Paul the Apostle to the Corinthians 1】",
"",
"7 以致你们在恩赐上没有一样不及人的，等候我们的主耶稣基督显现。",
"8 他也必坚固你们到底，叫你们在我们主耶稣基督的日子无可责备。",
"9 　神是信实的，你们原是被他所召，好与他儿子─我们的主耶稣基督一同得分。",
"10 弟兄们，我借我们主耶稣基督的名劝你们都说一样的话。你们中间也不可分党，只要一心一意，彼此相合。",
"11 因为革来氏家里的人曾对我提起弟兄们来，说你们中间有纷争。",
"12 我的意思就是你们各人说：我是属保罗的；我是属亚波罗的；我是属矶法的；我是属基督的。",
"",
"——【哥林多前书 1】",
],
[
"12 So then death worketh in us, but life in you.",
"13 We having the same spirit of faith, according as it is written, I believed, and therefore have I spoken; we also believe, and therefore speak;",
"",
"——【The Second Epistle of Paul the Apostle to the Corinthians 4】",
"",
"12 这样看来，死是在我们身上发动，生却在你们身上发动。",
"13 但我们既有信心，正如经上记着说：我因信，所以如此说话。我们也信，所以也说话。",
"",
"——【哥林多后书 4】",
],
[
"1 And there came one of the seven angels which had the seven vials, and talked with me, saying unto me, Come hither; I will shew unto thee the judgment of the great whore that sitteth upon many waters:",
"2 With whom the kings of the earth have committed fornication, and the inhabitants of the earth have been made drunk with the wine of her fornication.",
"",
"——【The Revelation of Saint John the Devine 17】",
"",
"1 拿着七碗的七位天使中，有一位前来对我说：你到这里来，我将坐在众水上的大淫妇所要受的刑罚指给你看。",
"2 地上的君王与她行淫，住在地上的人喝醉了她淫乱的酒。",
"",
"——【启示录 17】",
],
[
"1 Help, LORD; for the godly man ceaseth; for the faithful fail from among the children of men.",
"2 They speak vanity every one with his neighbour: with flattering lips and with a double heart do they speak.",
"3 The LORD shall cut off all flattering lips, and the tongue that speaketh proud things:",
"",
"——【The Book of Psalms 12】",
"",
"1 （大卫的诗，交与伶长。调用第八。）耶和华啊，求你帮助，因虔诚人断绝了；世人中间的忠信人没有了。",
"2 人人向邻舍说谎；他们说话，是嘴唇油滑，心口不一。",
"3 凡油滑的嘴唇和夸大的舌头，耶和华必要剪除。",
"",
"——【诗篇 12】",
],
[
"1 Be merciful unto me, O God, be merciful unto me: for my soul trusteth in thee: yea, in the shadow of thy wings will I make my refuge, until these calamities be overpast.",
"2 I will cry unto God most high; unto God that performeth all things for me.",
"3 He shall send from heaven, and save me from the reproach of him that would swallow me up. Selah. God shall send forth his mercy and his truth.",
"4 My soul is among lions: and I lie even among them that are set on fire, even the sons of men, whose teeth are spears and arrows, and their tongue a sharp sword.",
"",
"——【The Book of Psalms 57】",
"",
"1 （大卫逃避扫罗，藏在洞里。那时，他作这金诗，交与伶长。调用休要毁坏。）　神啊，求你怜悯我，怜悯我！因为我的心投靠你。我要投靠在你翅膀的荫下，等到灾害过去。",
"2 我要求告至高的　神，就是为我成全诸事的　神。",
"3 那要吞我的人辱骂我的时候，　神从天上必施恩救我，也必向我发出慈爱和诚实。",
"4 我的性命在狮子中间；我躺卧在性如烈火的世人当中。他们的牙齿是枪、箭；他们的舌头是快刀。",
"",
"——【诗篇 57】",
],
[
"10 For before these days there was no hire for man, nor any hire for beast; neither was there any peace to him that went out or came in because of the affliction: for I set all men every one against his neighbour.",
"11 But now I will not be unto the residue of this people as in the former days, saith the LORD of hosts.",
"12 For the seed shall be prosperous; the vine shall give her fruit, and the ground shall give her increase, and the heavens shall give their dew; and I will cause the remnant of this people to possess all these things.",
"13 And it shall come to pass, that as ye were a curse among the heathen, O house of Judah, and house of Israel; so will I save you, and ye shall be a blessing: fear not, but let your hands be strong.",
"14 For thus saith the LORD of hosts; As I thought to punish you, when your fathers provoked me to wrath, saith the LORD of hosts, and I repented not:",
"",
"——【Zechariah 8】",
"",
"10 那日以先，人得不着雇价，牲畜也是如此；且因敌人的缘故，出入之人不得平安，乃因我使众人互相攻击。",
"11 但如今，我待这余剩的民必不像从前。这是万军之耶和华说的。",
"12 因为他们必平安撒种，葡萄树必结果子，地土必有出产，天也必降甘露。我要使这余剩的民享受这一切的福。",
"13 犹大家和以色列家啊，你们从前在列国中怎样成为可咒诅的；照样，我要拯救你们，使人称你们为有福的（或译：使你们叫人得福）。你们不要惧怕，手要强壮。",
"14 万军之耶和华如此说：「你们列祖惹我发怒的时候，我怎样定意降祸，并不后悔。",
"",
"——【撒迦利亚书 8】",
],
[
"5 Wherefore should I fear in the days of evil, when the iniquity of my heels shall compass me about?",
"6 They that trust in their wealth, and boast themselves in the multitude of their riches;",
"7 None of them can by any means redeem his brother, nor give to God a ransom for him:",
"8 (For the redemption of their soul is precious, and it ceaseth for ever:)",
"9 That he should still live for ever, and not see corruption.",
"",
"——【The Book of Psalms 49】",
"",
"5 在患难的日子，奸恶随我脚跟，四面环绕我，我何必惧怕？",
"6 那些倚仗财货自夸钱财多的人，",
"7 一个也无法赎自己的弟兄，也不能替他将赎价给　神，",
"8 叫他长远活着，不见朽坏；因为赎他生命的价值极贵，只可永远罢休。",
"9 并入上节",
"",
"——【诗篇 49】",
],
[
"10 And the pride of Israel testifieth to his face: and they do not return to the LORD their God, nor seek him for all this.",
"11 Ephraim also is like a silly dove without heart: they call to Egypt, they go to Assyria.",
"",
"——【Hosea 7】",
"",
"10 以色列的骄傲当面见证自己，虽遭遇这一切，他们仍不归向耶和华─他们的　神，也不寻求他。",
"11 以法莲好像鸽子愚蠢无知；他们求告埃及，投奔亚述。",
"",
"——【何西阿书 7】",
],
[
"1 Then came together unto him the Pharisees, and certain of the scribes, which came from Jerusalem.",
"2 And when they saw some of his disciples eat bread with defiled, that is to say, with unwashen, hands, they found fault.",
"",
"——【The Gospel According to Saint Mark 7】",
"",
"1 有法利赛人和几个文士从耶路撒冷来，到耶稣那里聚集。",
"2 他们曾看见他的门徒中有人用俗手，就是没有洗的手，吃饭。",
"",
"——【马可福音 7】",
],
[
"5 For this cause left I thee in Crete, that thou shouldest set in order the things that are wanting, and ordain elders in every city, as I had appointed thee:",
"6 If any be blameless, the husband of one wife, having faithful children not accused of riot or unruly.",
"",
"——【The Epistle of Paul the Apostle to Titus 1】",
"",
"5 我从前留你在克里特，是要你将那没有办完的事都办整齐了，又照我所吩咐你的，在各城设立长老。",
"6 若有无可指责的人，只作一个妇人的丈夫，儿女也是信主的，没有人告他们是放荡不服约束的，就可以设立。",
"",
"——【提多书 1】",
],
[
"5 For Solomon went after Ashtoreth the goddess of the Zidonians, and after Milcom the abomination of the Ammonites.",
"6 And Solomon did evil in the sight of the LORD, and went not fully after the LORD, as did David his father.",
"",
"——【The First Book of the Kings 11】",
"",
"5 因为所罗门随从西顿人的女神亚斯她录和亚扪人可憎的神米勒公。",
"6 所罗门行耶和华眼中看为恶的事，不效法他父亲大卫专心顺从耶和华。",
"",
"——【列王记上 11】",
],
[
"7 Then did Solomon build an high place for Chemosh, the abomination of Moab, in the hill that is before Jerusalem, and for Molech, the abomination of the children of Ammon.",
"8 And likewise did he for all his strange wives, which burnt incense and sacrificed unto their gods.",
"9 And the LORD was angry with Solomon, because his heart was turned from the LORD God of Israel, which had appeared unto him twice,",
"10 And had commanded him concerning this thing, that he should not go after other gods: but he kept not that which the LORD commanded.",
"11 Wherefore the LORD said unto Solomon, Forasmuch as this is done of thee, and thou hast not kept my covenant and my statutes, which I have commanded thee, I will surely rend the kingdom from thee, and will give it to thy servant.",
"12 Notwithstanding in thy days I will not do it for David thy father's sake: but I will rend it out of the hand of thy son.",
"",
"——【The First Book of the Kings 11】",
"",
"7 所罗门为摩押可憎的神基抹和亚扪人可憎的神摩洛，在耶路撒冷对面的山上建筑邱坛。",
"8 他为那些向自己的神烧香献祭的外邦女子，就是他娶来的妃嫔也是这样行。",
"9 耶和华向所罗门发怒，因为他的心偏离向他两次显现的耶和华─以色列的　神。",
"10 耶和华曾吩咐他不可随从别神，他却没有遵守耶和华所吩咐的。",
"11 所以耶和华对他说：「你既行了这事，不遵守我所吩咐你守的约和律例，我必将你的国夺回，赐给你的臣子。",
"12 然而，因你父亲大卫的缘故，我不在你活着的日子行这事，必从你儿子的手中将国夺回。",
"",
"——【列王记上 11】",
],
[
"12 And one of the same place answered and said, But who is their father? Therefore it became a proverb, Is Saul also among the prophets?",
"13 And when he had made an end of prophesying, he came to the high place.",
"14 And Saul's uncle said unto him and to his servant, Whither went ye? And he said, To seek the asses: and when we saw that they were no where, we came to Samuel.",
"15 And Saul's uncle said, Tell me, I pray thee, what Samuel said unto you.",
"16 And Saul said unto his uncle, He told us plainly that the asses were found. But of the matter of the kingdom, whereof Samuel spake, he told him not.",
"17 And Samuel called the people together unto the LORD to Mizpeh;",
"",
"——【The First Book of Samuel 10】",
"",
"12 那地方有一个人说：「这些人的父亲是谁呢？」此后有句俗语说：「扫罗也列在先知中吗？」",
"13 扫罗受感说话已毕，就上邱坛去了。",
"14 扫罗的叔叔问扫罗和他仆人说：「你们往哪里去了？」回答说：「找驴去了。我们见没有驴，就到了撒母耳那里。」",
"15 扫罗的叔叔说：「请将撒母耳向你们所说的话告诉我。」",
"16 扫罗对他叔叔说：「他明明地告诉我们驴已经找着了。」至于撒母耳所说的国事，扫罗却没有告诉叔叔。",
"17 撒母耳将百姓招聚到米斯巴耶和华那里，",
"",
"——【撒母耳记上 10】",
],
[
"14 And afterward they made ready for themselves, and for the priests: because the priests the sons of Aaron were busied in offering of burnt offerings and the fat until night; therefore the Levites prepared for themselves, and for the priests the sons of Aaron.",
"15 And the singers the sons of Asaph were in their place, according to the commandment of David, and Asaph, and Heman, and Jeduthun the king's seer; and the porters waited at every gate; they might not depart from their service; for their brethren the Levites prepared for them.",
"16 So all the service of the LORD was prepared the same day, to keep the passover, and to offer burnt offerings upon the altar of the LORD, according to the commandment of king Josiah.",
"17 And the children of Israel that were present kept the passover at that time, and the feast of unleavened bread seven days.",
"",
"——【The Second Book of the Chronicles 35】",
"",
"14 然后为自己和祭司预备祭物；因为祭司亚伦的子孙献燔祭和脂油，直到晚上。所以利未人为自己和祭司亚伦的子孙，预备祭物。",
"15 歌唱的亚萨之子孙，照着大卫、亚萨、希幔，和王的先见耶杜顿所吩咐的，站在自己的地位上。守门的看守各门，不用离开他们的职事，因为他们的弟兄利未人给他们预备祭物。",
"16 当日，供奉耶和华的事齐备了，就照约西亚王的吩咐守逾越节，献燔祭在耶和华的坛上。",
"17 当时在耶路撒冷的以色列人守逾越节，又守除酵节七日。",
"",
"——【历代志下 35】",
],
[
"21 And, behold, I have given the children of Levi all the tenth in Israel for an inheritance, for their service which they serve, even the service of the tabernacle of the congregation.",
"22 Neither must the children of Israel henceforth come nigh the tabernacle of the congregation, lest they bear sin, and die.",
"23 But the Levites shall do the service of the tabernacle of the congregation, and they shall bear their iniquity: it shall be a statute for ever throughout your generations, that among the children of Israel they have no inheritance.",
"24 But the tithes of the children of Israel, which they offer as an heave offering unto the LORD, I have given to the Levites to inherit: therefore I have said unto them, Among the children of Israel they shall have no inheritance.",
"25 And the LORD spake unto Moses, saying,",
"26 Thus speak unto the Levites, and say unto them, When ye take of the children of Israel the tithes which I have given you from them for your inheritance, then ye shall offer up an heave offering of it for the LORD, even a tenth part of the tithe.",
"",
"——【The Fourth Book of Moses: Called Numbers 18】",
"",
"21 「凡以色列中出产的十分之一，我已赐给利未的子孙为业；因他们所办的是会幕的事，所以赐给他们为酬他们的劳。",
"22 从今以后，以色列人不可挨近会幕，免得他们担罪而死。",
"23 惟独利未人要办会幕的事，担当罪孽；这要作你们世世代代永远的定例。他们在以色列人中不可有产业；",
"24 因为以色列人中出产的十分之一，就是献给耶和华为举祭的，我已赐给利未人为业。所以我对他们说：『在以色列人中不可有产业。』」",
"25 耶和华吩咐摩西说：",
"26 「你晓谕利未人说：你们从以色列人中所取的十分之一，就是我给你们为业的，要再从那十分之一中取十分之一作为举祭献给耶和华，",
"",
"——【民数记 18】",
],
[
"15 And it came to pass on the seventh day, that they rose early about the dawning of the day, and compassed the city after the same manner seven times: only on that day they compassed the city seven times.",
"16 And it came to pass at the seventh time, when the priests blew with the trumpets, Joshua said unto the people, Shout; for the LORD hath given you the city.",
"17 And the city shall be accursed, even it, and all that are therein, to the LORD: only Rahab the harlot shall live, she and all that are with her in the house, because she hid the messengers that we sent.",
"18 And ye, in any wise keep yourselves from the accursed thing, lest ye make yourselves accursed, when ye take of the accursed thing, and make the camp of Israel a curse, and trouble it.",
"19 But all the silver, and gold, and vessels of brass and iron, are consecrated unto the LORD: they shall come into the treasury of the LORD.",
"20 So the people shouted when the priests blew with the trumpets: and it came to pass, when the people heard the sound of the trumpet, and the people shouted with a great shout, that the wall fell down flat, so that the people went up into the city, every man straight before him, and they took the city.",
"",
"——【The Book of Joshua 6】",
"",
"15 第七日清早，黎明的时候，他们起来，照样绕城七次；惟独这日把城绕了七次。",
"16 到了第七次，祭司吹角的时候，约书亚吩咐百姓说：「呼喊吧，因为耶和华已经把城交给你们了！",
"17 这城和其中所有的都要在耶和华面前毁灭；只有妓女喇合与她家中所有的可以存活，因为她隐藏了我们所打发的使者。",
"18 至于你们，务要谨慎，不可取那当灭的物，恐怕你们取了那当灭的物就连累以色列的全营，使全营受咒诅。",
"19 惟有金子、银子，和铜铁的器皿都要归耶和华为圣，必入耶和华的库中。」",
"20 于是百姓呼喊，祭司也吹角。百姓听见角声，便大声呼喊，城墙就塌陷，百姓便上去进城，各人往前直上，将城夺取。",
"",
"——【约书亚记 6】",
],
[
"13 And the LORD'S anger was kindled against Israel, and he made them wander in the wilderness forty years, until all the generation, that had done evil in the sight of the LORD, was consumed.",
"14 And, behold, ye are risen up in your fathers' stead, an increase of sinful men, to augment yet the fierce anger of the LORD toward Israel.",
"",
"——【The Fourth Book of Moses: Called Numbers 32】",
"",
"13 耶和华的怒气向以色列人发作，使他们在旷野飘流四十年，等到在耶和华眼前行恶的那一代人都消灭了。",
"14 谁知，你们起来接续先祖，增添罪人的数目，使耶和华向以色列大发烈怒。",
"",
"——【民数记 32】",
],
[
"13 Thou hast been in Eden the garden of God; every precious stone was thy covering, the sardius, topaz, and the diamond, the beryl, the onyx, and the jasper, the sapphire, the emerald, and the carbuncle, and gold: the workmanship of thy tabrets and of thy pipes was prepared in thee in the day that thou wast created.",
"14 Thou art the anointed cherub that covereth; and I have set thee so: thou wast upon the holy mountain of God; thou hast walked up and down in the midst of the stones of fire.",
"15 Thou wast perfect in thy ways from the day that thou wast created, till iniquity was found in thee.",
"",
"——【The Book of the Prophet Ezekiel 28】",
"",
"13 你曾在伊甸　神的园中，佩戴各样宝石，就是红宝石、红璧玺、金钢石、水苍玉、红玛瑙、碧玉、蓝宝石、绿宝石、红玉，和黄金；又有精美的鼓笛在你那里，都是在你受造之日预备齐全的。",
"14 你是那受膏遮掩约柜的基路伯；我将你安置在　神的圣山上；你在发光如火的宝石中间往来。",
"15 你从受造之日所行的都完全，后来在你中间又察出不义。",
"",
"——【以西结书 28】",
],
];
