var bible31_global=[
[
"6 Wherefore also it is contained in the scripture, Behold, I lay in Sion a chief corner stone, elect, precious: and he that believeth on him shall not be confounded.",
"7 Unto you therefore which believe he is precious: but unto them which be disobedient, the stone which the builders disallowed, the same is made the head of the corner,",
"8 And a stone of stumbling, and a rock of offence, even to them which stumble at the word, being disobedient: whereunto also they were appointed.",
"9 But ye are a chosen generation, a royal priesthood, an holy nation, a peculiar people; that ye should shew forth the praises of him who hath called you out of darkness into his marvellous light:",
"",
"——【The First Epistle General of Peter 2】",
"",
"6 因为经上说：看哪，我把所拣选、所宝贵的房角石安放在锡安；信靠他的人必不至于羞愧。",
"7 所以，他在你们信的人就为宝贵，在那不信的人有话说：匠人所弃的石头已作了房角的头块石头。",
"8 又说：作了绊脚的石头，跌人的磐石。他们既不顺从，就在道理上绊跌（或译：他们绊跌都因不顺从道理）；他们这样绊跌也是预定的。",
"9 惟有你们是被拣选的族类，是有君尊的祭司，是圣洁的国度，是属　神的子民，要叫你们宣扬那召你们出黑暗入奇妙光明者的美德。",
"",
"——【彼得前书 2】",
],
[
"4 For thy mercy is great above the heavens: and thy truth reacheth unto the clouds.",
"5 Be thou exalted, O God, above the heavens: and thy glory above all the earth;",
"6 That thy beloved may be delivered: save with thy right hand, and answer me.",
"7 God hath spoken in his holiness; I will rejoice, I will divide Shechem, and mete out the valley of Succoth.",
"8 Gilead is mine; Manasseh is mine; Ephraim also is the strength of mine head; Judah is my lawgiver;",
"9 Moab is my washpot; over Edom will I cast out my shoe; over Philistia will I triumph.",
"",
"——【The Book of Psalms 108】",
"",
"4 因为，你的慈爱大过诸天；你的诚实达到穹苍。",
"5 　神啊，愿你崇高过于诸天！愿你的荣耀高过全地！",
"6 求你应允我们，用右手拯救我们，好叫你所亲爱的人得救。",
"7 　神已经指着他的圣洁说（说：或译应许我）：我要欢乐；我要分开示剑，丈量疏割谷。",
"8 基列是我的；玛拿西是我的；以法莲是护卫我头的；犹大是我的杖；",
"9 摩押是我的沐浴盆；我要向以东抛鞋；我必因胜非利士呼喊。",
"",
"——【诗篇 108】",
],
[
"13 Then she said, Let me find favour in thy sight, my lord; for that thou hast comforted me, and for that thou hast spoken friendly unto thine handmaid, though I be not like unto one of thine handmaidens.",
"14 And Boaz said unto her, At mealtime come thou hither, and eat of the bread, and dip thy morsel in the vinegar. And she sat beside the reapers: and he reached her parched corn, and she did eat, and was sufficed, and left.",
"15 And when she was risen up to glean, Boaz commanded his young men, saying, Let her glean even among the sheaves, and reproach her not:",
"16 And let fall also some of the handfuls of purpose for her, and leave them, that she may glean them, and rebuke her not.",
"17 So she gleaned in the field until even, and beat out that she had gleaned: and it was about an ephah of barley.",
"18 And she took it up, and went into the city: and her mother in law saw what she had gleaned: and she brought forth, and gave to her that she had reserved after she was sufficed.",
"",
"——【The Book of Ruth 2】",
"",
"13 路得说：「我主啊，愿在你眼前蒙恩。我虽然不及你的一个使女，你还用慈爱的话安慰我的心。」",
"14 到了吃饭的时候，波阿斯对路得说：「你到这里来吃饼，将饼蘸在醋里。」路得就在收割的人旁边坐下；他们把烘了的穗子递给她。她吃饱了，还有余剩的。",
"15 她起来又拾取麦穗，波阿斯吩咐仆人说：「她就是在捆中拾取麦穗，也可以容她，不可羞辱她；",
"16 并要从捆里抽出些来，留在地下任她拾取，不可叱吓她。」",
"17 这样，路得在田间拾取麦穗，直到晚上，将所拾取的打了，约有一伊法大麦。",
"18 她就把所拾取的带进城去给婆婆看，又把她吃饱了所剩的给了婆婆。",
"",
"——【路得记 2】",
],
[
"14 Therefore the LORD will cut off from Israel head and tail, branch and rush, in one day.",
"15 The ancient and honourable, he is the head; and the prophet that teacheth lies, he is the tail.",
"16 For the leaders of this people cause them to err; and they that are led of them are destroyed.",
"17 Therefore the Lord shall have no joy in their young men, neither shall have mercy on their fatherless and widows: for every one is an hypocrite and an evildoer, and every mouth speaketh folly. For all this his anger is not turned away, but his hand is stretched out still.",
"18 For wickedness burneth as the fire: it shall devour the briers and thorns, and shall kindle in the thickets of the forest, and they shall mount up like the lifting up of smoke.",
"",
"——【The Book of the Prophet Isaiah 9】",
"",
"14 因此，耶和华一日之间必从以色列中剪除头与尾，棕枝与芦苇─",
"15 长老和尊贵人就是头，以谎言教人的先知就是尾。",
"16 因为，引导这百姓的使他们走错了路；被引导的都必败亡。",
"17 所以，主必不喜悦他们的少年人，也不怜恤他们的孤儿寡妇；因为，各人是亵渎的，是行恶的，并且各人的口都说愚妄的话。虽然如此，耶和华的怒气还未转消；他的手仍伸不缩。",
"18 邪恶像火焚烧，烧灭荆棘和蒺藜，在稠密的树林中著起来，就成为烟柱，旋转上腾。",
"",
"——【以赛亚书 9】",
],
[
"5 And they shall divide it into seven parts: Judah shall abide in their coast on the south, and the house of Joseph shall abide in their coasts on the north.",
"6 Ye shall therefore describe the land into seven parts, and bring the description hither to me, that I may cast lots for you here before the LORD our God.",
"7 But the Levites have no part among you; for the priesthood of the LORD is their inheritance: and Gad, and Reuben, and half the tribe of Manasseh, have received their inheritance beyond Jordan on the east, which Moses the servant of the LORD gave them.",
"8 And the men arose, and went away: and Joshua charged them that went to describe the land, saying, Go and walk through the land, and describe it, and come again to me, that I may here cast lots for you before the LORD in Shiloh.",
"",
"——【The Book of Joshua 18】",
"",
"5 他们要将地分做七分；犹大仍在南方，住在他的境内。约瑟家仍在北方，住在他的境内。",
"6 你们要将地分做七分，写明了拿到我这里来。我要在耶和华─我们　神面前，为你们拈阄。",
"7 利未人在你们中间没有分，因为供耶和华祭司的职任就是他们的产业。迦得支派、流便支派，和玛拿西半支派已经在约旦河东得了地业，就是耶和华仆人摩西所给他们的。」",
"8 划地势的人起身去的时候，约书亚嘱咐他们说：「你们去走遍那地，划明地势，就回到我这里来。我要在示罗这里，耶和华面前，为你们拈阄。」",
"",
"——【约书亚记 18】",
],
[
"11 And when they had brought their ships to land, they forsook all, and followed him.",
"12 And it came to pass, when he was in a certain city, behold a man full of leprosy: who seeing Jesus fell on his face, and besought him, saying, Lord, if thou wilt, thou canst make me clean.",
"13 And he put forth his hand, and touched him, saying, I will: be thou clean. And immediately the leprosy departed from him.",
"14 And he charged him to tell no man: but go, and shew thyself to the priest, and offer for thy cleansing, according as Moses commanded, for a testimony unto them.",
"15 But so much the more went there a fame abroad of him: and great multitudes came together to hear, and to be healed by him of their infirmities.",
"",
"——【The Gospel According to Saint Luke 5】",
"",
"11 他们把两只船拢了岸，就撇下所有的，跟从了耶稣。",
"12 有一回，耶稣在一个城里，有人满身长了大痲疯，看见他，就俯伏在地，求他说：主若肯，必能叫我洁净了。",
"13 耶稣伸手摸他，说：我肯，你洁净了吧！大痲疯立刻就离了他的身。",
"14 耶稣嘱咐他：你切不可告诉人，只要去把身体给祭司察看，又要为你得了洁净，照摩西所吩咐的献上礼物，对众人作证据。",
"15 但耶稣的名声越发传扬出去。有极多的人聚集来听道，也指望医治他们的病。",
"",
"——【路加福音 5】",
],
[
"20 And he closed the book, and he gave it again to the minister, and sat down. And the eyes of all them that were in the synagogue were fastened on him.",
"21 And he began to say unto them, This day is this scripture fulfilled in your ears.",
"22 And all bare him witness, and wondered at the gracious words which proceeded out of his mouth. And they said, Is not this Joseph's son?",
"23 And he said unto them, Ye will surely say unto me this proverb, Physician, heal thyself: whatsoever we have heard done in Capernaum, do also here in thy country.",
"",
"——【The Gospel According to Saint Luke 4】",
"",
"20 于是把书捲起来，交还执事，就坐下。会堂里的人都定睛看他。",
"21 耶稣对他们说：今天这经应验在你们耳中了。",
"22 众人都称赞他，并希奇他口中所出的恩言；又说：这不是约瑟的儿子吗？",
"23 耶稣对他们说：你们必引这俗语向我说：医生，你医治自己吧！我们听见你在迦百农所行的事，也当行在你自己家乡里；",
"",
"——【路加福音 4】",
],
[
"1 Rejoice not, O Israel, for joy, as other people: for thou hast gone a whoring from thy God, thou hast loved a reward upon every cornfloor.",
"2 The floor and the winepress shall not feed them, and the new wine shall fail in her.",
"3 They shall not dwell in the LORD'S land; but Ephraim shall return to Egypt, and they shall eat unclean things in Assyria.",
"4 They shall not offer wine offerings to the LORD, neither shall they be pleasing unto him: their sacrifices shall be unto them as the bread of mourners; all that eat thereof shall be polluted: for their bread for their soul shall not come into the house of the LORD.",
"5 What will ye do in the solemn day, and in the day of the feast of the LORD?",
"6 For, lo, they are gone because of destruction: Egypt shall gather them up, Memphis shall bury them: the pleasant places for their silver, nettles shall possess them: thorns shall be in their tabernacles.",
"",
"——【Hosea 9】",
"",
"1 以色列啊，不要像外邦人欢喜快乐；因为你行邪淫离弃你的　神，在各谷场上如妓女喜爱赏赐。",
"2 谷场和酒醡都不够以色列人使用；新酒也必缺乏。",
"3 他们必不得住耶和华的地；以法莲却要归回埃及，必在亚述吃不洁净的食物。",
"4 他们必不得向耶和华奠酒，即便奠酒也不蒙悦纳。他们的祭物必如居丧者的食物，凡吃的必被玷污；因他们的食物只为自己的口腹，必不奉入耶和华的殿。",
"5 在大会的日子，到耶和华的节期，你们怎样行呢？",
"6 看哪，他们逃避灾难；埃及人必收殓他们的尸首，摩弗人必葬埋他们的骸骨。他们用银子做的美物上必长蒺藜；他们的帐棚中必生荆棘。",
"",
"——【何西阿书 9】",
],
[
"3 And it shall come to pass, that when any shall yet prophesy, then his father and his mother that begat him shall say unto him, Thou shalt not live; for thou speakest lies in the name of the LORD: and his father and his mother that begat him shall thrust him through when he prophesieth.",
"4 And it shall come to pass in that day, that the prophets shall be ashamed every one of his vision, when he hath prophesied; neither shall they wear a rough garment to deceive:",
"5 But he shall say, I am no prophet, I am an husbandman; for man taught me to keep cattle from my youth.",
"",
"——【Zechariah 13】",
"",
"3 若再有人说预言，生他的父母必对他说：『你不得存活，因为你托耶和华的名说假预言。』生他的父母在他说预言的时候，要将他刺透。",
"4 那日，凡作先知说预言的必因他所论的异象羞愧，不再穿毛衣哄骗人。",
"5 他必说：『我不是先知，我是耕地的；我从幼年作人的奴仆。』",
"",
"——【撒迦利亚书 13】",
],
[
"10 And when there arose a great dissension, the chief captain, fearing lest Paul should have been pulled in pieces of them, commanded the soldiers to go down, and to take him by force from among them, and to bring him into the castle.",
"11 And the night following the Lord stood by him, and said, Be of good cheer, Paul: for as thou hast testified of me in Jerusalem, so must thou bear witness also at Rome.",
"",
"——【The Acts of the Apostles 23】",
"",
"10 那时大起争吵，千夫长恐怕保罗被他们扯碎了，就吩咐兵丁下去，把他从众人当中抢出来，带进营楼去。",
"11 当夜，主站在保罗旁边，说：放心吧！你怎样在耶路撒冷为我作见证，也必怎样在罗马为我作见证。",
"",
"——【使徒行传 23】",
],
[
"8 All that ever came before me are thieves and robbers: but the sheep did not hear them.",
"9 I am the door: by me if any man enter in, he shall be saved, and shall go in and out, and find pasture.",
"10 The thief cometh not, but for to steal, and to kill, and to destroy: I am come that they might have life, and that they might have it more abundantly.",
"",
"——【The Gospel According to Saint John 10】",
"",
"8 凡在我以先来的都是贼，是强盗；羊却不听他们。",
"9 我就是门；凡从我进来的，必然得救，并且出入得草吃。",
"10 盗贼来，无非要偷窃，杀害，毁坏；我来了，是要叫羊（或作：人）得生命，并且得的更丰盛。",
"",
"——【约翰福音 10】",
],
[
"5 Of the sons of Kohath; Uriel the chief, and his brethren an hundred and twenty:",
"6 Of the sons of Merari; Asaiah the chief, and his brethren two hundred and twenty:",
"7 Of the sons of Gershom; Joel the chief, and his brethren an hundred and thirty:",
"8 Of the sons of Elizaphan; Shemaiah the chief, and his brethren two hundred:",
"",
"——【The First Book of the Chronicles 15】",
"",
"5 哥辖子孙中有族长乌列和他的弟兄一百二十人。",
"6 米拉利子孙中有族长亚帅雅和他的弟兄二百二十人。",
"7 革顺子孙中有族长约珥和他的弟兄一百三十人。",
"8 以利撒反子孙中有族长示玛雅和他的弟兄二百人。",
"",
"——【历代志上 15】",
],
[
"11 And when the king entered into the house of the LORD, the guard came and fetched them, and brought them again into the guard chamber.",
"12 And when he humbled himself, the wrath of the LORD turned from him, that he would not destroy him altogether: and also in Judah things went well.",
"13 So king Rehoboam strengthened himself in Jerusalem, and reigned: for Rehoboam was one and forty years old when he began to reign, and he reigned seventeen years in Jerusalem, the city which the LORD had chosen out of all the tribes of Israel, to put his name there. And his mother's name was Naamah an Ammonitess.",
"14 And he did evil, because he prepared not his heart to seek the LORD.",
"",
"——【The Second Book of the Chronicles 12】",
"",
"11 王每逢进耶和华的殿，护卫兵就拿这盾牌，随后仍将盾牌送回，放在护卫房。",
"12 王自卑的时候，耶和华的怒气就转消了，不将他灭尽，并且在犹大中间也有善益的事。",
"13 罗波安王自强，在耶路撒冷作王。他登基的时候年四十一岁，在耶路撒冷，就是耶和华从以色列众支派中所选择立他名的城，作王十七年。罗波安的母亲名叫拿玛，是亚扪人。",
"14 罗波安行恶，因他不立定心意寻求耶和华。",
"",
"——【历代志下 12】",
],
[
"21 And all the people of Judah took Azariah, which was sixteen years old, and made him king instead of his father Amaziah.",
"22 He built Elath, and restored it to Judah, after that the king slept with his fathers.",
"",
"——【The Second Book of the Kings 14】",
"",
"21 犹大众民立亚玛谢的儿子亚撒利雅【又名乌西雅】接续他父作王，那时他年十六岁。",
"22 亚玛谢与他列祖同睡之后，亚撒利雅收回以拉他仍归犹大，又重新修理。",
"",
"——【列王记下 14】",
],
[
"7 And all the graven images thereof shall be beaten to pieces, and all the hires thereof shall be burned with the fire, and all the idols thereof will I lay desolate: for she gathered it of the hire of an harlot, and they shall return to the hire of an harlot.",
"8 Therefore I will wail and howl, I will go stripped and naked: I will make a wailing like the dragons, and mourning as the owls.",
"9 For her wound is incurable; for it is come unto Judah; he is come unto the gate of my people, even to Jerusalem.",
"10 Declare ye it not at Gath, weep ye not at all: in the house of Aphrah roll thyself in the dust.",
"",
"——【Micah 1】",
"",
"7 她一切雕刻的偶像必被打碎；她所得的财物必被火烧；所有的偶像我必毁灭；因为是从妓女雇价所聚来的，后必归为妓女的雇价。",
"8 先知说：因此我必大声哀号，赤脚露体而行；又要呼号如野狗，哀鸣如鸵鸟。",
"9 因为撒马利亚的伤痕无法医治，延及犹大和耶路撒冷我民的城门。",
"10 不要在迦特报告这事，总不要哭泣；我在伯‧亚弗拉滚于灰尘之中。",
"",
"——【弥迦书 1】",
],
[
"16 And they said unto him, Behold now, there be with thy servants fifty strong men; let them go, we pray thee, and seek thy master: lest peradventure the Spirit of the LORD hath taken him up, and cast him upon some mountain, or into some valley. And he said, Ye shall not send.",
"17 And when they urged him till he was ashamed, he said, Send. They sent therefore fifty men; and they sought three days, but found him not.",
"18 And when they came again to him, (for he tarried at Jericho,) he said unto them, Did I not say unto you, Go not?",
"19 And the men of the city said unto Elisha, Behold, I pray thee, the situation of this city is pleasant, as my lord seeth: but the water is naught, and the ground barren.",
"",
"——【The Second Book of the Kings 2】",
"",
"16 对他说：「仆人们这里有五十个壮士，求你容他们去寻找你师傅，或者耶和华的灵将他提起来，投在某山某谷。」以利沙说：「你们不必打发人去。」",
"17 他们再三催促他，他难以推辞，就说：「你们打发人去吧！」他们便打发五十人去，寻找了三天，也没有找著。",
"18 以利沙仍然在耶利哥等候他们回到他那里；他对他们说：「我岂没有告诉你们不必去吗？」",
"19 耶利哥城的人对以利沙说：「这城的地势美好，我主看见了；只是水恶劣，土产不熟而落。」",
"",
"——【列王记下 2】",
],
[
"13 Nevertheless the children of Israel expelled not the Geshurites, nor the Maachathites: but the Geshurites and the Maachathites dwell among the Israelites until this day.",
"14 Only unto the tribe of Levi he gave none inheritance; the sacrifices of the LORD God of Israel made by fire are their inheritance, as he said unto them.",
"15 And Moses gave unto the tribe of the children of Reuben inheritance according to their families.",
"16 And their coast was from Aroer, that is on the bank of the river Arnon, and the city that is in the midst of the river, and all the plain by Medeba;",
"17 Heshbon, and all her cities that are in the plain; Dibon, and Bamoth–baal, and Beth–baal–meon,",
"",
"——【The Book of Joshua 13】",
"",
"13 以色列人却没有赶逐基述人、玛迦人；这些人仍住在以色列中，直到今日。",
"14 只是利未支派，摩西（原文作他）没有把产业分给他们。他们的产业乃是献与耶和华─以色列　神的火祭，正如耶和华所应许他们的。",
"15 摩西按著流便支派的宗族分给他们产业。",
"16 他们的境界是亚嫩谷边的亚罗珥和谷中的城，靠近米底巴的全平原；",
"17 希实本并属希实本平原的各城，底本、巴末‧巴力、伯‧巴力‧勉、",
"",
"——【约书亚记 13】",
],
[
"9 Kings' daughters were among thy honourable women: upon thy right hand did stand the queen in gold of Ophir.",
"10 Hearken, O daughter, and consider, and incline thine ear; forget also thine own people, and thy father's house;",
"11 So shall the king greatly desire thy beauty: for he is thy Lord; and worship thou him.",
"12 And the daughter of Tyre shall be there with a gift; even the rich among the people shall intreat thy favour.",
"13 The king's daughter is all glorious within: her clothing is of wrought gold.",
"14 She shall be brought unto the king in raiment of needlework: the virgins her companions that follow her shall be brought unto thee.",
"",
"——【The Book of Psalms 45】",
"",
"9 有君王的女儿在你尊贵妇女之中；王后佩戴俄斐金饰站在你右边。",
"10 女子啊，你要听，要想，要侧耳而听！不要记念你的民和你的父家，",
"11 王就羨慕你的美貌；因为他是你的主，你当敬拜他。",
"12 推罗的民（原文是女子）必来送礼；民中的富足人也必向你求恩。",
"13 王女在宫里极其荣华；她的衣服是用金线绣的。",
"14 她要穿锦绣的衣服，被引到王前；随从她的陪伴童女也要被带到你面前。",
"",
"——【诗篇 45】",
],
[
"15 Yea, and we are found false witnesses of God; because we have testified of God that he raised up Christ: whom he raised not up, if so be that the dead rise not.",
"16 For if the dead rise not, then is not Christ raised:",
"17 And if Christ be not raised, your faith is vain; ye are yet in your sins.",
"18 Then they also which are fallen asleep in Christ are perished.",
"19 If in this life only we have hope in Christ, we are of all men most miserable.",
"20 But now is Christ risen from the dead, and become the firstfruits of them that slept.",
"",
"——【The First Epistle of Paul the Apostle to the Corinthians 15】",
"",
"15 并且明显我们是为　神妄作见证的，因我们见证　神是叫基督复活了。若死人真不复活，　神也就没有叫基督复活了。",
"16 因为死人若不复活，基督也就没有复活了。",
"17 基督若没有复活，你们的信便是徒然，你们仍在罪里。",
"18 就是在基督里睡了的人也灭亡了。",
"19 我们若靠基督，只在今生有指望，就算比众人更可怜。",
"20 但基督已经从死里复活，成为睡了之人初熟的果子。",
"",
"——【哥林多前书 15】",
],
[
"16 For it increaseth. Thou huntest me as a fierce lion: and again thou shewest thyself marvellous upon me.",
"17 Thou renewest thy witnesses against me, and increasest thine indignation upon me; changes and war are against me.",
"18 Wherefore then hast thou brought me forth out of the womb? Oh that I had given up the ghost, and no eye had seen me!",
"19 I should have been as though I had not been; I should have been carried from the womb to the grave.",
"20 Are not my days few? cease then, and let me alone, that I may take comfort a little,",
"21 Before I go whence I shall not return, even to the land of darkness and the shadow of death;",
"",
"——【The Book of Job 10】",
"",
"16 我若昂首自得，你就追捕我如狮子，又在我身上显出奇能。",
"17 你重立见证攻击我，向我加增恼怒，如军兵更换著攻击我。",
"18 你为何使我出母胎呢？不如我当时气绝，无人得见我；",
"19 这样，就如没有我一般，一出母胎就被送入坟墓。",
"20 我的日子不是甚少吗？求你停手宽容我，叫我在往而不返之先─就是往黑暗和死荫之地以先─可以稍得畅快。",
"21 并入上一节",
"",
"——【约伯记 10】",
],
[
"21 Submitting yourselves one to another in the fear of God.",
"22 Wives, submit yourselves unto your own husbands, as unto the Lord.",
"",
"——【The Epistle of Paul the Apostle to the Ephesians 5】",
"",
"21 又当存敬畏基督的心，彼此顺服。",
"22 你们作妻子的，当顺服自己的丈夫，如同顺服主。",
"",
"——【以弗所书 5】",
],
[
"12 No man hath seen God at any time. If we love one another, God dwelleth in us, and his love is perfected in us.",
"13 Hereby know we that we dwell in him, and he in us, because he hath given us of his Spirit.",
"",
"——【The First Epistle General of John 4】",
"",
"12 从来没有人见过　神，我们若彼此相爱，　神就住在我们里面，爱他的心在我们里面得以完全了。",
"13 　神将他的灵赐给我们，从此就知道我们是住在他里面，他也住在我们里面。",
"",
"——【约翰一书 4】",
],
[
"1 In the LORD put I my trust: how say ye to my soul, Flee as a bird to your mountain?",
"2 For, lo, the wicked bend their bow, they make ready their arrow upon the string, that they may privily shoot at the upright in heart.",
"",
"——【The Book of Psalms 11】",
"",
"1 （大卫的诗，交与伶长。）我是投靠耶和华；你们怎么对我说：你当像鸟飞往你的山去。",
"2 看哪，恶人弯弓，把箭搭在弦上，要在暗中射那心里正直的人。",
"",
"——【诗篇 11】",
],
[
"12 For the which cause I also suffer these things: nevertheless I am not ashamed: for I know whom I have believed, and am persuaded that he is able to keep that which I have committed unto him against that day.",
"13 Hold fast the form of sound words, which thou hast heard of me, in faith and love which is in Christ Jesus.",
"",
"——【The Second Epistle of Paul the Apostle to Timothy 1】",
"",
"12 为这缘故，我也受这些苦难。然而我不以为耻；因为知道我所信的是谁，也深信他能保全我所交付他的（或作：他所交托我的），直到那日。",
"13 你从我听的那纯正话语的规模，要用在基督耶稣里的信心和爱心，常常守著。",
"",
"——【提摩太后书 1】",
],
[
"11 Let the extortioner catch all that he hath; and let the strangers spoil his labour.",
"12 Let there be none to extend mercy unto him: neither let there be any to favour his fatherless children.",
"13 Let his posterity be cut off; and in the generation following let their name be blotted out.",
"14 Let the iniquity of his fathers be remembered with the LORD; and let not the sin of his mother be blotted out.",
"15 Let them be before the LORD continually, that he may cut off the memory of them from the earth.",
"",
"——【The Book of Psalms 109】",
"",
"11 愿强暴的债主牢笼他一切所有的！愿外人抢他劳碌得来的！",
"12 愿无人向他延绵施恩！愿无人可怜他的孤儿！",
"13 愿他的后人断绝，名字被涂抹，不传于下代！",
"14 愿他祖宗的罪孽被耶和华记念！愿他母亲的罪过不被涂抹！",
"15 愿这些罪常在耶和华面前，使他的名号断绝于世！",
"",
"——【诗篇 109】",
],
[
"6 And Noah was six hundred years old when the flood of waters was upon the earth.",
"7 And Noah went in, and his sons, and his wife, and his sons' wives with him, into the ark, because of the waters of the flood.",
"8 Of clean beasts, and of beasts that are not clean, and of fowls, and of every thing that creepeth upon the earth,",
"9 There went in two and two unto Noah into the ark, the male and the female, as God had commanded Noah.",
"",
"——【The First Book of Moses: Called Genesis 7】",
"",
"6 当洪水泛滥在地上的时候，挪亚整六百岁。",
"7 挪亚就同他的妻和儿子儿妇都进入方舟，躲避洪水。",
"8 洁净的畜类和不洁净的畜类，飞鸟并地上一切的昆虫，",
"9 都是一对一对的，有公有母，到挪亚那里进入方舟，正如　神所吩咐挪亚的。",
"",
"——【创世记 7】",
],
[
"14 And every raven after his kind,",
"15 And the owl, and the night hawk, and the cuckow, and the hawk after his kind,",
"16 The little owl, and the great owl, and the swan,",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 14】",
"",
"14 乌鸦与其类，",
"15 鸵鸟、夜鹰、鱼鹰、鹰与其类，",
"16 鸮鸟、猫头鹰、角鸱、",
"",
"——【申命记 14】",
],
[
"5 Therefore his height was exalted above all the trees of the field, and his boughs were multiplied, and his branches became long because of the multitude of waters, when he shot forth.",
"6 All the fowls of heaven made their nests in his boughs, and under his branches did all the beasts of the field bring forth their young, and under his shadow dwelt all great nations.",
"7 Thus was he fair in his greatness, in the length of his branches: for his root was by great waters.",
"8 The cedars in the garden of God could not hide him: the fir trees were not like his boughs, and the chesnut trees were not like his branches; nor any tree in the garden of God was like unto him in his beauty.",
"9 I have made him fair by the multitude of his branches: so that all the trees of Eden, that were in the garden of God, envied him.",
"",
"——【The Book of the Prophet Ezekiel 31】",
"",
"5 所以他高大超过田野诸树；发旺的时候，枝子繁多，因得大水之力枝条长长。",
"6 空中的飞鸟都在枝子上搭窝；田野的走兽都在枝条下生子；所有大国的人民都在它荫下居住。",
"7 树大条长，成为荣美，因为根在众水之旁。",
"8 　神园中的香柏树不能遮蔽它；松树不及它的枝子；枫树不及它的枝条；　神园中的树都没有它荣美。",
"9 我使它的枝条蕃多，成为荣美，以致　神伊甸园中的树都嫉妒它。」",
"",
"——【以西结书 31】",
],
[
"13 Remember the word which Moses the servant of the LORD commanded you, saying, The LORD your God hath given you rest, and hath given you this land.",
"14 Your wives, your little ones, and your cattle, shall remain in the land which Moses gave you on this side Jordan; but ye shall pass before your brethren armed, all the mighty men of valour, and help them;",
"15 Until the LORD have given your brethren rest, as he hath given you, and they also have possessed the land which the LORD your God giveth them: then ye shall return unto the land of your possession, and enjoy it, which Moses the LORD'S servant gave you on this side Jordan toward the sunrising.",
"16 And they answered Joshua, saying, All that thou commandest us we will do, and whithersoever thou sendest us, we will go.",
"17 According as we hearkened unto Moses in all things, so will we hearken unto thee: only the LORD thy God be with thee, as he was with Moses.",
"18 Whosoever he be that doth rebel against thy commandment, and will not hearken unto thy words in all that thou commandest him, he shall be put to death: only be strong and of a good courage.",
"",
"——【The Book of Joshua 1】",
"",
"13 「你们要追念耶和华的仆人摩西所吩咐你们的话说：『耶和华─你们的　神使你们得享平安，也必将这地赐给你们。』",
"14 你们的妻子、孩子，和牲畜都可以留在约旦河东、摩西所给你们的地；但你们中间一切大能的勇士都要带著兵器在你们的弟兄前面过去，帮助他们，",
"15 等到耶和华使你们的弟兄像你们一样得享平安，并且得著耶和华─你们　神所赐他们为业之地，那时才可以回你们所得之地，承受为业，就是耶和华的仆人摩西在约旦河东、向日出之地所给你们的。」",
"16 他们回答约书亚说：「你所吩咐我们行的，我们都必行；你所差遣我们去的，我们都必去。",
"17 我们从前在一切事上怎样听从摩西，现在也必照样听从你；惟愿耶和华─你的　神与你同在，像与摩西同在一样。",
"18 无论什么人违背你的命令，不听从你所吩咐他的一切话，就必治死他。你只要刚强壮胆！」",
"",
"——【约书亚记 1】",
],
[
"5 Then the king Ahasuerus answered and said unto Esther the queen, Who is he, and where is he, that durst presume in his heart to do so?",
"6 And Esther said, The adversary and enemy is this wicked Haman. Then Haman was afraid before the king and the queen.",
"7 And the king arising from the banquet of wine in his wrath went into the palace garden: and Haman stood up to make request for his life to Esther the queen; for he saw that there was evil determined against him by the king.",
"8 Then the king returned out of the palace garden into the place of the banquet of wine; and Haman was fallen upon the bed whereon Esther was. Then said the king, Will he force the queen also before me in the house? As the word went out of the king's mouth, they covered Haman's face.",
"9 And Harbonah, one of the chamberlains, said before the king, Behold also, the gallows fifty cubits high, which Haman had made for Mordecai, who had spoken good for the king, standeth in the house of Haman. Then the king said, Hang him thereon.",
"",
"——【The Book of Esther 7】",
"",
"5 亚哈随鲁王问王后以斯帖说：「擅敢起意如此行的是谁？这人在哪里呢？」",
"6 以斯帖说：「仇人敌人就是这恶人哈曼！」哈曼在王和王后面前就甚惊惶。",
"7 王便大怒，起来离开酒席往御园去了。哈曼见王定意要加罪与他，就起来，求王后以斯帖救命。",
"8 王从御园回到酒席之处，见哈曼伏在以斯帖所靠的榻上；王说：「他竟敢在宫内、在我面前凌辱王后吗？」这话一出王口，人就蒙了哈曼的脸。",
"9 伺候王的一个太监名叫哈波拿，说：「哈曼为那救王有功的末底改做了五丈高的木架，现今立在哈曼家里。」王说：「把哈曼挂在其上。」",
"",
"——【以斯帖记 7】",
],
[
"1 Behold, how good and how pleasant it is for brethren to dwell together in unity!",
"2 It is like the precious ointment upon the head, that ran down upon the beard, even Aaron's beard: that went down to the skirts of his garments;",
"",
"——【The Book of Psalms 133】",
"",
"1 （大卫上行之诗。）看哪，弟兄和睦同居是何等地善，何等地美！",
"2 这好比那贵重的油浇在亚伦的头上，流到胡须，又流到他的衣襟；",
"",
"——【诗篇 133】",
],
];
