var bible31_global=[
[
"13 Withhold not correction from the child: for if thou beatest him with the rod, he shall not die.",
"14 Thou shalt beat him with the rod, and shalt deliver his soul from hell.",
"15 My son, if thine heart be wise, my heart shall rejoice, even mine.",
"16 Yea, my reins shall rejoice, when thy lips speak right things.",
"17 Let not thine heart envy sinners: but be thou in the fear of the LORD all the day long.",
"",
"——【The Proverbs 23】",
"",
"13 不可不管教孩童；你用杖打他，他必不至于死。",
"14 你要用杖打他，就可以救他的灵魂免下阴间。",
"15 我儿，你心若存智慧，我的心也甚欢喜。",
"16 你的嘴若说正直话，我的心肠也必快乐。",
"17 你心中不要嫉妒罪人，只要终日敬畏耶和华；",
"",
"——【箴言 23】",
],
[
"1 After these things, when the wrath of king Ahasuerus was appeased, he remembered Vashti, and what she had done, and what was decreed against her.",
"2 Then said the king's servants that ministered unto him, Let there be fair young virgins sought for the king:",
"3 And let the king appoint officers in all the provinces of his kingdom, that they may gather together all the fair young virgins unto Shushan the palace, to the house of the women, unto the custody of Hege the king's chamberlain, keeper of the women; and let their things for purification be given them:",
"",
"——【The Book of Esther 2】",
"",
"1 这事以后，亚哈随鲁王的忿怒止息，就想念瓦实提和她所行的，并怎样降旨办她。",
"2 于是王的侍臣对王说：「不如为王寻找美貌的处女。",
"3 王可以派官在国中的各省招聚美貌的处女到书珊城（或译：宫）的女院，交给掌管女子的太监希该，给她们当用的香品。",
"",
"——【以斯帖记 2】",
],
[
"1 What shall we say then that Abraham our father, as pertaining to the flesh, hath found?",
"2 For if Abraham were justified by works, he hath whereof to glory; but not before God.",
"3 For what saith the scripture? Abraham believed God, and it was counted unto him for righteousness.",
"4 Now to him that worketh is the reward not reckoned of grace, but of debt.",
"",
"——【The Epistle of Paul the Apostle to the Romans 4】",
"",
"1 如此说来，我们的祖宗亚伯拉罕凭着肉体得了什么呢？",
"2 倘若亚伯拉罕是因行为称义，就有可夸的；只是在　神面前并无可夸。",
"3 经上说什么呢？说：亚伯拉罕信　神，这就算为他的义。",
"4 做工的得工价，不算恩典，乃是该得的；",
"",
"——【罗马书 4】",
],
[
"5 And the rest of the children of Kohath had by lot out of the families of the tribe of Ephraim, and out of the tribe of Dan, and out of the half tribe of Manasseh, ten cities.",
"6 And the children of Gershon had by lot out of the families of the tribe of Issachar, and out of the tribe of Asher, and out of the tribe of Naphtali, and out of the half tribe of Manasseh in Bashan, thirteen cities.",
"7 The children of Merari by their families had out of the tribe of Reuben, and out of the tribe of Gad, and out of the tribe of Zebulun, twelve cities.",
"8 And the children of Israel gave by lot unto the Levites these cities with their suburbs, as the LORD commanded by the hand of Moses.",
"9 And they gave out of the tribe of the children of Judah, and out of the tribe of the children of Simeon, these cities which are here mentioned by name,",
"10 Which the children of Aaron, being of the families of the Kohathites, who were of the children of Levi, had: for theirs was the first lot.",
"",
"——【The Book of Joshua 21】",
"",
"5 哥辖其余的子孙，从以法莲支派、但支派、玛拿西半支派的地业中，按阄得了十座城。",
"6 革顺的子孙，从以萨迦支派、亚设支派、拿弗他利支派、住巴珊的玛拿西半支派的地业中，按阄得了十三座城。",
"7 米拉利的子孙，按着宗族，从流便支派、迦得支派、西布伦支派的地业中，按阄得了十二座城。",
"8 以色列人照着耶和华借摩西所吩咐的，将这些城邑和城邑的郊野，按阄分给利未人。",
"9 从犹大支派、西缅支派的地业中，将以下所记的城给了利未支派哥辖宗族亚伦的子孙；因为给他们拈出头一阄，",
"10 并入上一节",
"",
"——【约书亚记 21】",
],
[
"17 And Judah went with Simeon his brother, and they slew the Canaanites that inhabited Zephath, and utterly destroyed it. And the name of the city was called Hormah.",
"18 Also Judah took Gaza with the coast thereof, and Askelon with the coast thereof, and Ekron with the coast thereof.",
"",
"——【The Book of Judges 1】",
"",
"17 犹大和他哥哥西缅同去，击杀了住洗法的迦南人，将城尽行毁灭，那城的名便叫何珥玛。",
"18 犹大又取了迦萨和迦萨的四境，亚实基伦和亚实基伦的四境，以革伦和以革伦的四境。",
"",
"——【士师记 1】",
],
[
"9 Joshua therefore came unto them suddenly, and went up from Gilgal all night.",
"10 And the LORD discomfited them before Israel, and slew them with a great slaughter at Gibeon, and chased them along the way that goeth up to Beth–horon, and smote them to Azekah, and unto Makkedah.",
"11 And it came to pass, as they fled from before Israel, and were in the going down to Beth–horon, that the LORD cast down great stones from heaven upon them unto Azekah, and they died: they were more which died with hailstones than they whom the children of Israel slew with the sword.",
"12 Then spake Joshua to the LORD in the day when the LORD delivered up the Amorites before the children of Israel, and he said in the sight of Israel, Sun, stand thou still upon Gibeon; and thou, Moon, in the valley of Ajalon.",
"13 And the sun stood still, and the moon stayed, until the people had avenged themselves upon their enemies. Is not this written in the book of Jasher? So the sun stood still in the midst of heaven, and hasted not to go down about a whole day.",
"",
"——【The Book of Joshua 10】",
"",
"9 约书亚就终夜从吉甲上去，猛然临到他们那里。",
"10 耶和华使他们在以色列人面前溃乱。约书亚在基遍大大的杀败他们，追赶他们，在伯‧和仑的上坡路击杀他们，直到亚西加和玛基大。",
"11 他们在以色列人面前逃跑，正在伯‧和仑下坡的时候，耶和华从天上降大冰雹在他们身上，（冰雹原文作石头）直降到亚西加，打死他们。被冰雹打死的，比以色列人用刀杀死的还多。",
"12 当耶和华将亚摩利人交付以色列人的日子，约书亚就祷告耶和华，在以色列人眼前说：日头啊，你要停在基遍；月亮啊，你要止在亚雅仑谷。",
"13 于是日头停留，月亮止住，直等国民向敌人报仇。这事岂不是写在雅煞珥书上吗？日头在天当中停住，不急速下落，约有一日之久。",
"",
"——【约书亚记 10】",
],
[
"5 And offer a sacrifice of thanksgiving with leaven, and proclaim and publish the free offerings: for this liketh you, O ye children of Israel, saith the Lord GOD.",
"6 And I also have given you cleanness of teeth in all your cities, and want of bread in all your places: yet have ye not returned unto me, saith the LORD.",
"7 And also I have withholden the rain from you, when there were yet three months to the harvest: and I caused it to rain upon one city, and caused it not to rain upon another city: one piece was rained upon, and the piece whereupon it rained not withered.",
"8 So two or three cities wandered unto one city, to drink water; but they were not satisfied: yet have ye not returned unto me, saith the LORD.",
"9 I have smitten you with blasting and mildew: when your gardens and your vineyards and your fig trees and your olive trees increased, the palmerworm devoured them: yet have ye not returned unto me, saith the LORD.",
"",
"——【Amos 4】",
"",
"5 任你们献有酵的感谢祭，把甘心祭宣传报告给众人，因为是你们所喜爱的。这是主耶和华说的。",
"6 我使你们在一切城中牙齿干净，在你们各处粮食缺乏，你们仍不归向我。这是耶和华说的。",
"7 在收割的前三月，我使雨停止，不降在你们那里；我降雨在这城，不降雨在那城；这块地有雨，那块地无雨；无雨的就枯干了。",
"8 这样，两三城的人凑到一城去找水，却喝不足；你们仍不归向我。这是耶和华说的。",
"9 我以旱风、霉烂攻击你们，你们园中许多菜蔬、葡萄树、无花果树、橄榄树都被剪虫所吃；你们仍不归向我。这是耶和华说的。",
"",
"——【阿摩司书 4】",
],
[
"6 And I will make thee exceeding fruitful, and I will make nations of thee, and kings shall come out of thee.",
"7 And I will establish my covenant between me and thee and thy seed after thee in their generations for an everlasting covenant, to be a God unto thee, and to thy seed after thee.",
"8 And I will give unto thee, and to thy seed after thee, the land wherein thou art a stranger, all the land of Canaan, for an everlasting possession; and I will be their God.",
"",
"——【The First Book of Moses: Called Genesis 17】",
"",
"6 我必使你的后裔极其繁多；国度从你而立，君王从你而出。",
"7 我要与你并你世世代代的后裔坚立我的约，作永远的约，是要作你和你后裔的　神。",
"8 我要将你现在寄居的地，就是迦南全地，赐给你和你的后裔永远为业，我也必作他们的　神。」",
"",
"——【创世记 17】",
],
[
"1 Now these are the kings of the land, which the children of Israel smote, and possessed their land on the other side Jordan toward the rising of the sun, from the river Arnon unto mount Hermon, and all the plain on the east:",
"2 Sihon king of the Amorites, who dwelt in Heshbon, and ruled from Aroer, which is upon the bank of the river Arnon, and from the middle of the river, and from half Gilead, even unto the river Jabbok, which is the border of the children of Ammon;",
"3 And from the plain to the sea of Chinneroth on the east, and unto the sea of the plain, even the salt sea on the east, the way to Beth–jeshimoth; and from the south, under Ashdoth–pisgah:",
"4 And the coast of Og king of Bashan, which was of the remnant of the giants, that dwelt at Ashtaroth and at Edrei,",
"5 And reigned in mount Hermon, and in Salcah, and in all Bashan, unto the border of the Geshurites and the Maachathites, and half Gilead, the border of Sihon king of Heshbon.",
"",
"——【The Book of Joshua 12】",
"",
"1 以色列人在约旦河外向日出之地击杀二王，得他们的地，就是从亚嫩谷直到黑门山，并东边的全亚拉巴之地。",
"2 这二王，有住希实本、亚摩利人的王西宏。他所管之地是从亚嫩谷边的亚罗珥和谷中的城，并基列一半，直到亚扪人的境界，雅博河",
"3 与约旦河东边的亚拉巴，直到基尼烈海，又到亚拉巴的海，就是盐海，通伯‧耶西末的路，以及南方，直到毘斯迦的山根。",
"4 又有巴珊王噩。他是利乏音人所剩下的，住在亚斯他录和以得来。",
"5 他所管之地是黑门山、撒迦、巴珊全地，直到基述人和玛迦人的境界，并基列一半，直到希实本王西宏的境界。",
"",
"——【约书亚记 12】",
],
[
"33 Azmaveth the Baharumite, Eliahba the Shaalbonite,",
"34 The sons of Hashem the Gizonite, Jonathan the son of Shage the Hararite,",
"35 Ahiam the son of Sacar the Hararite, Eliphal the son of Ur,",
"36 Hepher the Mecherathite, Ahijah the Pelonite,",
"37 Hezro the Carmelite, Naarai the son of Ezbai,",
"",
"——【The First Book of the Chronicles 11】",
"",
"33 巴路米人押斯玛弗，沙本人以利雅哈巴，",
"34 基孙人哈深的众子，哈拉人沙基的儿子约拿单，",
"35 哈拉人沙甲的儿子亚希暗，吾珥的儿子以利法勒，",
"36 米基拉人希弗，比伦人亚希雅，",
"37 迦密人希斯罗，伊斯拜的儿子拿莱，",
"",
"——【历代志上 11】",
],
[
"22 But I say unto you, It shall be more tolerable for Tyre and Sidon at the day of judgment, than for you.",
"23 And thou, Capernaum, which art exalted unto heaven, shalt be brought down to hell: for if the mighty works, which have been done in thee, had been done in Sodom, it would have remained until this day.",
"24 But I say unto you, That it shall be more tolerable for the land of Sodom in the day of judgment, than for thee.",
"",
"——【The Gospel According to Saint Matthew 11】",
"",
"22 但我告诉你们，当审判的日子，泰尔、西顿所受的，比你们还容易受呢！",
"23 迦百农啊，你已经升到天上（或作：你将要升到天上吗），将来必坠落阴间；因为在你那里所行的异能，若行在所多玛，它还可以存到今日。",
"24 但我告诉你们，当审判的日子，所多玛所受的，比你还容易受呢！",
"",
"——【马太福音 11】",
],
[
"1 Behold my servant, whom I uphold; mine elect, in whom my soul delighteth; I have put my spirit upon him: he shall bring forth judgment to the Gentiles.",
"2 He shall not cry, nor lift up, nor cause his voice to be heard in the street.",
"3 A bruised reed shall he not break, and the smoking flax shall he not quench: he shall bring forth judgment unto truth.",
"4 He shall not fail nor be discouraged, till he have set judgment in the earth: and the isles shall wait for his law.",
"",
"——【The Book of the Prophet Isaiah 42】",
"",
"1 看哪，我的仆人─我所扶持所拣选、心里所喜悦的！我已将我的灵赐给他；他必将公理传给外邦。",
"2 他不喧嚷，不扬声，也不使街上听见他的声音。",
"3 压伤的芦苇，他不折断；将残的灯火，他不吹灭。他凭真实将公理传开。",
"4 他不灰心，也不丧胆，直到他在地上设立公理；海岛都等候他的训诲。",
"",
"——【以赛亚书 42】",
],
[
"43 For a good tree bringeth not forth corrupt fruit; neither doth a corrupt tree bring forth good fruit.",
"44 For every tree is known by his own fruit. For of thorns men do not gather figs, nor of a bramble bush gather they grapes.",
"45 A good man out of the good treasure of his heart bringeth forth that which is good; and an evil man out of the evil treasure of his heart bringeth forth that which is evil: for of the abundance of the heart his mouth speaketh.",
"46 And why call ye me, Lord, Lord, and do not the things which I say?",
"47 Whosoever cometh to me, and heareth my sayings, and doeth them, I will shew you to whom he is like:",
"",
"——【The Gospel According to Saint Luke 6】",
"",
"43 因为，没有好树结坏果子，也没有坏树结好果子。",
"44 凡树木看果子，就可以认出它来。人不是从荆棘上摘无花果，也不是从蒺藜里摘葡萄。",
"45 善人从他心里所存的善就发出善来；恶人从他心里所存的恶就发出恶来；因为心里所充满的，口里就说出来。",
"46 你们为什么称呼我主啊，主啊，却不遵我的话行呢？",
"47 凡到我这里来，听见我的话就去行的，我要告诉你们他像什么人：",
"",
"——【路加福音 6】",
],
[
"1 His foundation is in the holy mountains.",
"2 The LORD loveth the gates of Zion more than all the dwellings of Jacob.",
"",
"——【The Book of Psalms 87】",
"",
"1 （可拉后裔的诗歌。）耶和华所立的根基在圣山上。",
"2 他爱锡安的门，胜于爱雅各一切的住处。",
"",
"——【诗篇 87】",
],
[
"7 And also I have withholden the rain from you, when there were yet three months to the harvest: and I caused it to rain upon one city, and caused it not to rain upon another city: one piece was rained upon, and the piece whereupon it rained not withered.",
"8 So two or three cities wandered unto one city, to drink water; but they were not satisfied: yet have ye not returned unto me, saith the LORD.",
"9 I have smitten you with blasting and mildew: when your gardens and your vineyards and your fig trees and your olive trees increased, the palmerworm devoured them: yet have ye not returned unto me, saith the LORD.",
"10 I have sent among you the pestilence after the manner of Egypt: your young men have I slain with the sword, and have taken away your horses; and I have made the stink of your camps to come up unto your nostrils: yet have ye not returned unto me, saith the LORD.",
"",
"——【Amos 4】",
"",
"7 在收割的前三月，我使雨停止，不降在你们那里；我降雨在这城，不降雨在那城；这块地有雨，那块地无雨；无雨的就枯干了。",
"8 这样，两三城的人凑到一城去找水，却喝不足；你们仍不归向我。这是耶和华说的。",
"9 我以旱风、霉烂攻击你们，你们园中许多菜蔬、葡萄树、无花果树、橄榄树都被剪虫所吃；你们仍不归向我。这是耶和华说的。",
"10 我降瘟疫在你们中间，像在埃及一样；用刀杀戮你们的少年人，使你们的马匹被掳掠，营中尸首的臭气扑鼻；你们仍不归向我。这是耶和华说的。",
"",
"——【阿摩司书 4】",
],
[
"22 The desire of a man is his kindness: and a poor man is better than a liar.",
"23 The fear of the LORD tendeth to life: and he that hath it shall abide satisfied; he shall not be visited with evil.",
"24 A slothful man hideth his hand in his bosom, and will not so much as bring it to his mouth again.",
"25 Smite a scorner, and the simple will beware: and reprove one that hath understanding, and he will understand knowledge.",
"26 He that wasteth his father, and chaseth away his mother, is a son that causeth shame, and bringeth reproach.",
"27 Cease, my son, to hear the instruction that causeth to err from the words of knowledge.",
"",
"——【The Proverbs 19】",
"",
"22 施行仁慈的，令人爱慕；穷人强如说谎言的。",
"23 敬畏耶和华的，得着生命；他必恒久知足，不遭祸患。",
"24 懒惰人放手在盘子里，就是向口撤回，他也不肯。",
"25 鞭打亵慢人，愚蒙人必长见识；责备明哲人，他就明白知识。",
"26 虐待父亲、撵出母亲的，是贻羞致辱之子。",
"27 我儿，不可听了教训而又偏离知识的言语。",
"",
"——【箴言 19】",
],
[
"18 And he said, It is not the voice of them that shout for mastery, neither is it the voice of them that cry for being overcome: but the noise of them that sing do I hear.",
"19 And it came to pass, as soon as he came nigh unto the camp, that he saw the calf, and the dancing: and Moses' anger waxed hot, and he cast the tables out of his hands, and brake them beneath the mount.",
"20 And he took the calf which they had made, and burnt it in the fire, and ground it to powder, and strawed it upon the water, and made the children of Israel drink of it.",
"21 And Moses said unto Aaron, What did this people unto thee, that thou hast brought so great a sin upon them?",
"22 And Aaron said, Let not the anger of my lord wax hot: thou knowest the people, that they are set on mischief.",
"23 For they said unto me, Make us gods, which shall go before us: for as for this Moses, the man that brought us up out of the land of Egypt, we wot not what is become of him.",
"",
"——【The Second Book of Moses: Called Exodus 32】",
"",
"18 摩西说：「这不是人打胜仗的声音，也不是人打败仗的声音，我所听见的乃是人歌唱的声音。」",
"19 摩西挨近营前就看见牛犊，又看见人跳舞，便发烈怒，把两块版扔在山下摔碎了，",
"20 又将他们所铸的牛犊用火焚烧，磨得粉碎，撒在水面上，叫以色列人喝。",
"21 摩西对亚伦说：「这百姓向你做了什么？你竟使他们陷在大罪里！」",
"22 亚伦说：「求我主不要发烈怒。这百姓专于作恶，是你知道的。」",
"23 他们对我说：『你为我们做神像，可以在我们前面引路；因为领我们出埃及地的那个摩西，我们不知道他遭了什么事。』",
"",
"——【出埃及记 32】",
],
[
"4 And all the host of heaven shall be dissolved, and the heavens shall be rolled together as a scroll: and all their host shall fall down, as the leaf falleth off from the vine, and as a falling fig from the fig tree.",
"5 For my sword shall be bathed in heaven: behold, it shall come down upon Idumea, and upon the people of my curse, to judgment.",
"6 The sword of the LORD is filled with blood, it is made fat with fatness, and with the blood of lambs and goats, with the fat of the kidneys of rams: for the LORD hath a sacrifice in Bozrah, and a great slaughter in the land of Idumea.",
"",
"——【The Book of the Prophet Isaiah 34】",
"",
"4 天上的万象都要消没；天被卷起，好像书卷。其上的万象要残败，像葡萄树的叶子残败，又像无花果树的叶子残败一样。",
"5 因为我的刀在天上已经喝足；这刀必临到以东和我所咒诅的民，要施行审判。",
"6 耶和华的刀满了血，用脂油和羊羔、公山羊的血，并公绵羊腰子的脂油滋润的；因为耶和华在波斯拉有献祭的事，在以东地大行杀戮。",
"",
"——【以赛亚书 34】",
],
[
"10 The ten sons of Haman the son of Hammedatha, the enemy of the Jews, slew they; but on the spoil laid they not their hand.",
"11 On that day the number of those that were slain in Shushan the palace was brought before the king.",
"12 And the king said unto Esther the queen, The Jews have slain and destroyed five hundred men in Shushan the palace, and the ten sons of Haman; what have they done in the rest of the king's provinces? now what is thy petition? and it shall be granted thee: or what is thy request further? and it shall be done.",
"13 Then said Esther, If it please the king, let it be granted to the Jews which are in Shushan to do to morrow also according unto this day's decree, and let Haman's ten sons be hanged upon the gallows.",
"14 And the king commanded it so to be done: and the decree was given at Shushan; and they hanged Haman's ten sons.",
"",
"——【The Book of Esther 9】",
"",
"10 这十人都是哈米大他的孙子、犹大人仇敌哈曼的儿子。犹大人却没有下手夺取财物。",
"11 当日，将书珊城被杀的人数呈在王前。",
"12 王对王后以斯帖说：「犹大人在书珊城杀灭了五百人，又杀了哈曼的十个儿子，在王的各省不知如何呢？现在你要什么，我必赐给你；你还求什么，也必为你成就。」",
"13 以斯帖说：「王若以为美，求你准书珊的犹大人，明日也照今日的旨意行，并将哈曼十个儿子的尸首挂在木架上。」",
"14 王便允准如此行。旨意传在书珊，人就把哈曼十个儿子的尸首挂起来了。",
"",
"——【以斯帖记 9】",
],
[
"5 Wherefore ye must needs be subject, not only for wrath, but also for conscience sake.",
"6 For for this cause pay ye tribute also: for they are God's ministers, attending continually upon this very thing.",
"7 Render therefore to all their dues: tribute to whom tribute is due; custom to whom custom; fear to whom fear; honour to whom honour.",
"8 Owe no man any thing, but to love one another: for he that loveth another hath fulfilled the law.",
"9 For this, Thou shalt not commit adultery, Thou shalt not kill, Thou shalt not steal, Thou shalt not bear false witness, Thou shalt not covet; and if there be any other commandment, it is briefly comprehended in this saying, namely, Thou shalt love thy neighbour as thyself.",
"",
"——【The Epistle of Paul the Apostle to the Romans 13】",
"",
"5 所以你们必须顺服，不但是因为刑罚，也是因为良心。",
"6 你们纳粮，也为这个缘故；因他们是　神的差役，常常特管这事。",
"7 凡人所当得的，就给他。当得粮的，给他纳粮；当得税的，给他上税；当惧怕的，惧怕他；当恭敬的，恭敬他。",
"8 凡事都不可亏欠人，惟有彼此相爱要常以为亏欠，因为爱人的就完全了律法。",
"9 像那不可奸淫，不可杀人，不可偷盗，不可贪婪，或有别的诫命，都包在爱人如己这一句话之内了。",
"",
"——【罗马书 13】",
],
[
"7 Turn us again, O God of hosts, and cause thy face to shine; and we shall be saved.",
"8 Thou hast brought a vine out of Egypt: thou hast cast out the heathen, and planted it.",
"9 Thou preparedst room before it, and didst cause it to take deep root, and it filled the land.",
"10 The hills were covered with the shadow of it, and the boughs thereof were like the goodly cedars.",
"11 She sent out her boughs unto the sea, and her branches unto the river.",
"12 Why hast thou then broken down her hedges, so that all they which pass by the way do pluck her?",
"",
"——【The Book of Psalms 80】",
"",
"7 万军之　神啊，求你使我们回转，使你的脸发光，我们便要得救！",
"8 你从埃及挪出一棵葡萄树，赶出外邦人，把这树栽上。",
"9 你在这树根前预备了地方，它就深深扎根，爬满了地。",
"10 它的影子遮满了山，枝子好像佳美的香柏树。",
"11 它发出枝子，长到大海，发出蔓子，延到大河。",
"12 你为何拆毁这树的篱笆，任凭一切过路的人摘取？",
"",
"——【诗篇 80】",
],
[
"6 We have sinned with our fathers, we have committed iniquity, we have done wickedly.",
"7 Our fathers understood not thy wonders in Egypt; they remembered not the multitude of thy mercies; but provoked him at the sea, even at the Red sea.",
"8 Nevertheless he saved them for his name's sake, that he might make his mighty power to be known.",
"",
"——【The Book of Psalms 106】",
"",
"6 我们与我们的祖宗一同犯罪；我们作了孽，行了恶。",
"7 我们的祖宗在埃及不明白你的奇事，不记念你丰盛的慈爱，反倒在红海行了悖逆。",
"8 然而，他因自己的名拯救他们，为要彰显他的大能，",
"",
"——【诗篇 106】",
],
[
"1 In the three and twentieth year of Joash the son of Ahaziah king of Judah Jehoahaz the son of Jehu began to reign over Israel in Samaria, and reigned seventeen years.",
"2 And he did that which was evil in the sight of the LORD, and followed the sins of Jeroboam the son of Nebat, which made Israel to sin; he departed not therefrom.",
"3 And the anger of the LORD was kindled against Israel, and he delivered them into the hand of Hazael king of Syria, and into the hand of Ben–hadad the son of Hazael, all their days.",
"4 And Jehoahaz besought the LORD, and the LORD hearkened unto him: for he saw the oppression of Israel, because the king of Syria oppressed them.",
"5 (And the LORD gave Israel a saviour, so that they went out from under the hand of the Syrians: and the children of Israel dwelt in their tents, as beforetime.",
"",
"——【The Second Book of the Kings 13】",
"",
"1 犹大王亚哈谢的儿子约阿施二十三年，耶户的儿子约哈斯在撒马利亚登基作以色列王十七年。",
"2 约哈斯行耶和华眼中看为恶的事，效法尼八的儿子耶罗波安使以色列人陷在罪里的那罪，总不离开。",
"3 于是，耶和华的怒气向以色列人发作，将他们屡次交在亚兰王哈薛和他儿子便哈达的手里。",
"4 约哈斯恳求耶和华，耶和华就应允他，因为见以色列人所受亚兰王的欺压。",
"5 耶和华赐给以色列人一位拯救者，使他们脱离亚兰人的手；于是以色列人仍旧安居在家里。",
"",
"——【列王记下 13】",
],
[
"16 Then said Samuel, Wherefore then dost thou ask of me, seeing the LORD is departed from thee, and is become thine enemy?",
"17 And the LORD hath done to him, as he spake by me: for the LORD hath rent the kingdom out of thine hand, and given it to thy neighbour, even to David:",
"",
"——【The First Book of Samuel 28】",
"",
"16 撒母耳说：「耶和华已经离开你，且与你为敌，你何必问我呢？",
"17 耶和华照他借我说的话，已经从你手里夺去国权，赐与别人，就是大卫。",
"",
"——【撒母耳记上 28】",
],
[
"1 Remember now thy Creator in the days of thy youth, while the evil days come not, nor the years draw nigh, when thou shalt say, I have no pleasure in them;",
"2 While the sun, or the light, or the moon, or the stars, be not darkened, nor the clouds return after the rain:",
"3 In the day when the keepers of the house shall tremble, and the strong men shall bow themselves, and the grinders cease because they are few, and those that look out of the windows be darkened,",
"",
"——【Ecclesiastes 12】",
"",
"1 你趁着年幼、衰败的日子尚未来到，就是你所说，我毫无喜乐的那些年日未曾临近之先，当记念造你的主。",
"2 不要等到日头、光明、月亮、星宿变为黑暗，雨后云彩反回，",
"3 看守房屋的发颤，有力的屈身，推磨的稀少就止息，从窗户往外看的都昏暗；",
"",
"——【传道书 12】",
],
[
"10 For I am with thee, and no man shall set on thee to hurt thee: for I have much people in this city.",
"11 And he continued there a year and six months, teaching the word of God among them.",
"",
"——【The Acts of the Apostles 18】",
"",
"10 有我与你同在，必没有人下手害你，因为在这城里我有许多的百姓。",
"11 保罗在那里住了一年零六个月，将　神的道教训他们。",
"",
"——【使徒行传 18】",
],
[
"3 Then say thou, Thus saith the Lord GOD, The city sheddeth blood in the midst of it, that her time may come, and maketh idols against herself to defile herself.",
"4 Thou art become guilty in thy blood that thou hast shed; and hast defiled thyself in thine idols which thou hast made; and thou hast caused thy days to draw near, and art come even unto thy years: therefore have I made thee a reproach unto the heathen, and a mocking to all countries.",
"5 Those that be near, and those that be far from thee, shall mock thee, which art infamous and much vexed.",
"6 Behold, the princes of Israel, every one were in thee to their power to shed blood.",
"7 In thee have they set light by father and mother: in the midst of thee have they dealt by oppression with the stranger: in thee have they vexed the fatherless and the widow.",
"",
"——【The Book of the Prophet Ezekiel 22】",
"",
"3 你要说，主耶和华如此说：哎！这城有流人血的事在其中，叫她受报的日期来到，又做偶像玷污自己，陷害自己。",
"4 你因流了人的血，就为有罪；你做了偶像，就玷污自己，使你受报之日临近，报应之年来到。所以我叫你受列国的凌辱和列邦的讥诮。",
"5 你这名臭、多乱的城啊，那些离你近、离你远的都必讥诮你。",
"6 「看哪，以色列的首领各逞其能，在你中间流人之血。",
"7 在你中间有轻慢父母的，有欺压寄居的，有亏负孤儿寡妇的。",
"",
"——【以西结书 22】",
],
[
"7 For the mystery of iniquity doth already work: only he who now letteth will let, until he be taken out of the way.",
"8 And then shall that Wicked be revealed, whom the Lord shall consume with the spirit of his mouth, and shall destroy with the brightness of his coming:",
"9 Even him, whose coming is after the working of Satan with all power and signs and lying wonders,",
"10 And with all deceivableness of unrighteousness in them that perish; because they received not the love of the truth, that they might be saved.",
"11 And for this cause God shall send them strong delusion, that they should believe a lie:",
"",
"——【The Second Epistle of Paul the Apostle to the Thessalonians 2】",
"",
"7 因为那不法的隐意已经发动，只是现在有一个拦阻的，等到那拦阻的被除去，",
"8 那时这不法的人必显露出来。主耶稣要用口中的气灭绝他，用降临的荣光废掉他。",
"9 这不法的人来，是照撒但的运动，行各样的异能、神迹，和一切虚假的奇事，",
"10 并且在那沉沦的人身上行各样出于不义的诡诈；因他们不领受爱真理的心，使他们得救。",
"11 故此，　神就给他们一个生发错误的心，叫他们信从虚谎，",
"",
"——【帖撒罗尼迦后书 2】",
],
[
"1 I said, I will take heed to my ways, that I sin not with my tongue: I will keep my mouth with a bridle, while the wicked is before me.",
"2 I was dumb with silence, I held my peace, even from good; and my sorrow was stirred.",
"3 My heart was hot within me, while I was musing the fire burned: then spake I with my tongue,",
"4 LORD, make me to know mine end, and the measure of my days, what it is; that I may know how frail I am.",
"5 Behold, thou hast made my days as an handbreadth; and mine age is as nothing before thee: verily every man at his best state is altogether vanity. Selah.",
"",
"——【The Book of Psalms 39】",
"",
"1 （大卫的诗，交与伶长耶杜顿。）我曾说：我要谨慎我的言行，免得我舌头犯罪；恶人在我面前的时候，我要用嚼环勒住我的口。",
"2 我默然无声，连好话也不出口；我的愁苦就发动了，",
"3 我的心在我里面发热。我默想的时候，火就烧起，我便用舌头说话。",
"4 耶和华啊，求你叫我晓得我身之终！我的寿数几何？叫我知道我的生命不长！",
"5 你使我的年日窄如手掌；我一生的年数，在你面前如同无有。各人最稳妥的时候，真是全然虚幻。（细拉）",
"",
"——【诗篇 39】",
],
[
"4 And I will bring again to this place Jeconiah the son of Jehoiakim king of Judah, with all the captives of Judah, that went into Babylon, saith the LORD: for I will break the yoke of the king of Babylon.",
"5 Then the prophet Jeremiah said unto the prophet Hananiah in the presence of the priests, and in the presence of all the people that stood in the house of the LORD,",
"6 Even the prophet Jeremiah said, Amen: the LORD do so: the LORD perform thy words which thou hast prophesied, to bring again the vessels of the LORD'S house, and all that is carried away captive, from Babylon into this place.",
"7 Nevertheless hear thou now this word that I speak in thine ears, and in the ears of all the people;",
"8 The prophets that have been before me and before thee of old prophesied both against many countries, and against great kingdoms, of war, and of evil, and of pestilence.",
"",
"——【The Book of the Prophet Jeremiah 28】",
"",
"4 我又要将犹大王约雅敬的儿子耶哥尼雅和被掳到巴比伦去的一切犹大人带回此地，因为我要折断巴比伦王的轭。这是耶和华说的。」",
"5 先知耶利米当着祭司和站在耶和华殿里的众民对先知哈拿尼雅说：",
"6 「阿们！愿耶和华如此行，愿耶和华成就你所预言的话，将耶和华殿中的器皿和一切被掳去的人从巴比伦带回此地。",
"7 然而我向你和众民耳中所要说的话，你应当听。",
"8 从古以来，在你我以前的先知，向多国和大邦说预言，论到争战、灾祸、瘟疫的事。",
"",
"——【耶利米书 28】",
],
[
"15 And we sailed thence, and came the next day over against Chios; and the next day we arrived at Samos, and tarried at Trogyllium; and the next day we came to Miletus.",
"16 For Paul had determined to sail by Ephesus, because he would not spend the time in Asia: for he hasted, if it were possible for him, to be at Jerusalem the day of Pentecost.",
"17 And from Miletus he sent to Ephesus, and called the elders of the church.",
"",
"——【The Acts of the Apostles 20】",
"",
"15 从那里开船，次日到了基阿的对面；又次日，在撒摩靠岸；又次日，来到米利都。",
"16 乃因保罗早已定意越过以弗所，免得在亚细亚耽延，他急忙前走，巴不得赶五旬节能到耶路撒冷。",
"17 保罗从米利都打发人往以弗所去，请教会的长老来。",
"",
"——【使徒行传 20】",
],
];
