var bible31_global=[
[
"2 From the end of the earth will I cry unto thee, when my heart is overwhelmed: lead me to the rock that is higher than I.",
"3 For thou hast been a shelter for me, and a strong tower from the enemy.",
"",
"——【The Book of Psalms 61】",
"",
"2 我心里发昏的时候，我要从地极求告你。求你领我到那比我更高的磐石！",
"3 因为你作过我的避难所，作过我的坚固台，脱离仇敌。",
"",
"——【诗篇 61】",
],
[
"8 But Noah found grace in the eyes of the LORD.",
"9 These are the generations of Noah: Noah was a just man and perfect in his generations, and Noah walked with God.",
"",
"——【The First Book of Moses: Called Genesis 6】",
"",
"8 惟有挪亚在耶和华眼前蒙恩。",
"9 挪亚的后代记在下面。挪亚是个义人，在当时的世代是个完全人。挪亚与　神同行。",
"",
"——【创世记 6】",
],
[
"8 At that time the LORD separated the tribe of Levi, to bear the ark of the covenant of the LORD, to stand before the LORD to minister unto him, and to bless in his name, unto this day.",
"9 Wherefore Levi hath no part nor inheritance with his brethren; the LORD is his inheritance, according as the LORD thy God promised him.",
"10 And I stayed in the mount, according to the first time, forty days and forty nights; and the LORD hearkened unto me at that time also, and the LORD would not destroy thee.",
"11 And the LORD said unto me, Arise, take thy journey before the people, that they may go in and possess the land, which I sware unto their fathers to give unto them.",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 10】",
"",
"8 那时，耶和华将利未支派分别出来，抬耶和华的约柜，又侍立在耶和华面前事奉他，奉他的名祝福，直到今日。",
"9 所以利未人在他弟兄中无分无业，耶和华是他的产业，正如耶和华─你　神所应许他的。）",
"10 「我又像从前在山上住了四十昼夜。那次耶和华也应允我，不忍将你灭绝。",
"11 耶和华吩咐我说：『你起来引导这百姓，使他们进去得我向他们列祖起誓应许所赐之地。』",
"",
"——【申命记 10】",
],
[
"1 In my distress I cried unto the LORD, and he heard me.",
"2 Deliver my soul, O LORD, from lying lips, and from a deceitful tongue.",
"3 What shall be given unto thee? or what shall be done unto thee, thou false tongue?",
"4 Sharp arrows of the mighty, with coals of juniper.",
"",
"——【The Book of Psalms 120】",
"",
"1 （上行（或作登阶，下同）之诗。）我在急难中求告耶和华，他就应允我。",
"2 耶和华啊，求你救我脱离说谎的嘴唇和诡诈的舌头！",
"3 诡诈的舌头啊，要给你什么呢？要拿什么加给你呢？",
"4 就是勇士的利箭和罗腾木（小树名，松类）的炭火。",
"",
"——【诗篇 120】",
],
[
"7 Moreover he must have a good report of them which are without; lest he fall into reproach and the snare of the devil.",
"8 Likewise must the deacons be grave, not doubletongued, not given to much wine, not greedy of filthy lucre;",
"9 Holding the mystery of the faith in a pure conscience.",
"10 And let these also first be proved; then let them use the office of a deacon, being found blameless.",
"11 Even so must their wives be grave, not slanderers, sober, faithful in all things.",
"12 Let the deacons be the husbands of one wife, ruling their children and their own houses well.",
"",
"——【The First Epistle of Paul the Apostle to Timothy 3】",
"",
"7 监督也必须在教外有好名声，恐怕被人毁谤，落在魔鬼的网罗里。",
"8 作执事的，也是如此：必须端庄，不一口两舌，不好喝酒，不贪不义之财；",
"9 要存清洁的良心，固守真道的奥秘。",
"10 这等人也要先受试验，若没有可责之处，然后叫他们作执事。",
"11 女执事（原文是女人）也是如此：必须端庄，不说谗言，有节制，凡事忠心。",
"12 执事只要作一个妇人的丈夫，好好管理儿女和自己的家。",
"",
"——【提摩太前书 3】",
],
[
"9 And I, behold, I establish my covenant with you, and with your seed after you;",
"10 And with every living creature that is with you, of the fowl, of the cattle, and of every beast of the earth with you; from all that go out of the ark, to every beast of the earth.",
"11 And I will establish my covenant with you; neither shall all flesh be cut off any more by the waters of a flood; neither shall there any more be a flood to destroy the earth.",
"",
"——【The First Book of Moses: Called Genesis 9】",
"",
"9 「我与你们和你们的后裔立约，",
"10 并与你们这里的一切活物─就是飞鸟、牲畜、走兽，凡从方舟里出来的活物─立约。",
"11 我与你们立约，凡有血肉的，不再被洪水灭绝，也不再有洪水毁坏地了。」",
"",
"——【创世记 9】",
],
[
"5 And this man shall be the peace, when the Assyrian shall come into our land: and when he shall tread in our palaces, then shall we raise against him seven shepherds, and eight principal men.",
"6 And they shall waste the land of Assyria with the sword, and the land of Nimrod in the entrances thereof: thus shall he deliver us from the Assyrian, when he cometh into our land, and when he treadeth within our borders.",
"7 And the remnant of Jacob shall be in the midst of many people as a dew from the LORD, as the showers upon the grass, that tarrieth not for man, nor waiteth for the sons of men.",
"8 And the remnant of Jacob shall be among the Gentiles in the midst of many people as a lion among the beasts of the forest, as a young lion among the flocks of sheep: who, if he go through, both treadeth down, and teareth in pieces, and none can deliver.",
"9 Thine hand shall be lifted up upon thine adversaries, and all thine enemies shall be cut off.",
"10 And it shall come to pass in that day, saith the LORD, that I will cut off thy horses out of the midst of thee, and I will destroy thy chariots:",
"",
"——【Micah 5】",
"",
"5 这位必作我们的平安。当亚述人进入我们的地境，践踏宫殿的时候，我们就立起七个牧者，八个首领攻击他。",
"6 他们必用刀剑毁坏亚述地和宁录地的关口。亚述人进入我们的地境践踏的时候，他必拯救我们。",
"7 雅各余剩的人必在多国的民中，如从耶和华那里降下的露水，又如甘霖降在草上；不仗赖人力，也不等候世人之功。",
"8 雅各余剩的人必在多国多民中，如林间百兽中的狮子，又如少壮狮子在羊群中。他若经过就必践踏撕裂，无人搭救。",
"9 愿你的手举起，高过敌人！愿你的仇敌都被剪除！",
"10 耶和华说：到那日，我必从你中间剪除马匹，毁坏车辆，",
"",
"——【弥迦书 5】",
],
[
"10 And he said, Unto you it is given to know the mysteries of the kingdom of God: but to others in parables; that seeing they might not see, and hearing they might not understand.",
"11 Now the parable is this: The seed is the word of God.",
"12 Those by the way side are they that hear; then cometh the devil, and taketh away the word out of their hearts, lest they should believe and be saved.",
"13 They on the rock are they, which, when they hear, receive the word with joy; and these have no root, which for a while believe, and in time of temptation fall away.",
"",
"——【The Gospel According to Saint Luke 8】",
"",
"10 他说：　神国的奥秘只叫你们知道；至于别人，就用比喻，叫他们看也看不见，听也听不明。",
"11 这比喻乃是这样：种子就是　神的道。",
"12 那些在路旁的，就是人听了道，随后魔鬼来，从他们心里把道夺去，恐怕他们信了得救。",
"13 那些在磐石上的，就是人听道，欢喜领受，但心中没有根，不过暂时相信，及至遇见试炼就退后了。",
"",
"——【路加福音 8】",
],
[
"4 And he built Tadmor in the wilderness, and all the store cities, which he built in Hamath.",
"5 Also he built Beth–horon the upper, and Beth–horon the nether, fenced cities, with walls, gates, and bars;",
"",
"——【The Second Book of the Chronicles 8】",
"",
"4 所罗门建造旷野里的达莫，又建造哈马所有的积货城，",
"5 又建造上伯‧和仑、下伯‧和仑作为保障，都有墙，有门，有闩；",
"",
"——【历代志下 8】",
],
[
"5 And beside this, giving all diligence, add to your faith virtue; and to virtue knowledge;",
"6 And to knowledge temperance; and to temperance patience; and to patience godliness;",
"7 And to godliness brotherly kindness; and to brotherly kindness charity.",
"8 For if these things be in you, and abound, they make you that ye shall neither be barren nor unfruitful in the knowledge of our Lord Jesus Christ.",
"",
"——【The Second General Epistle of Peter 1】",
"",
"5 正因这缘故，你们要分外地殷勤；有了信心，又要加上德行；有了德行，又要加上知识；",
"6 有了知识，又要加上节制；有了节制，又要加上忍耐；有了忍耐，又要加上虔敬；",
"7 有了虔敬，又要加上爱弟兄的心；有了爱弟兄的心，又要加上爱众人的心；",
"8 你们若充充足足的有这几样，就必使你们在认识我们的主耶稣基督上不至于闲懒不结果子了。",
"",
"——【彼得后书 1】",
],
[
"17 Gilead abode beyond Jordan: and why did Dan remain in ships? Asher continued on the sea shore, and abode in his breaches.",
"18 Zebulun and Naphtali were a people that jeoparded their lives unto the death in the high places of the field.",
"19 The kings came and fought, then fought the kings of Canaan in Taanach by the waters of Megiddo; they took no gain of money.",
"20 They fought from heaven; the stars in their courses fought against Sisera.",
"21 The river of Kishon swept them away, that ancient river, the river Kishon. O my soul, thou hast trodden down strength.",
"",
"——【The Book of Judges 5】",
"",
"17 基列人安居在约旦河外。但人为何等在船上？亚设人在海口静坐，在港口安居。",
"18 西布伦人是拚命敢死的；拿弗他利人在田野的高处也是如此。",
"19 君王都来争战。那时迦南诸王在米吉多水旁的他纳争战，却未得掳掠银钱。",
"20 星宿从天上争战，从其轨道攻击西西拉。",
"21 基顺古河把敌人冲没；我的灵啊，应当努力前行。",
"",
"——【士师记 5】",
],
[
"22 But if I say thus unto the young man, Behold, the arrows are beyond thee; go thy way: for the LORD hath sent thee away.",
"23 And as touching the matter which thou and I have spoken of, behold, the LORD be between thee and me for ever.",
"24 So David hid himself in the field: and when the new moon was come, the king sat him down to eat meat.",
"25 And the king sat upon his seat, as at other times, even upon a seat by the wall: and Jonathan arose, and Abner sat by Saul's side, and David's place was empty.",
"26 Nevertheless Saul spake not any thing that day: for he thought, Something hath befallen him, he is not clean; surely he is not clean.",
"27 And it came to pass on the morrow, which was the second day of the month, that David's place was empty: and Saul said unto Jonathan his son, Wherefore cometh not the son of Jesse to meat, neither yesterday, nor to day?",
"",
"——【The First Book of Samuel 20】",
"",
"22 我若对童子说：『箭在前头』，你就要去，因为是耶和华打发你去的。",
"23 至于你我今日所说的话，有耶和华在你我中间为证，直到永远。」",
"24 大卫就去藏在田野。到了初一日，王坐席要吃饭。",
"25 王照常坐在靠墙的位上，约拿单侍立，押尼珥坐在扫罗旁边，大卫的座位空设。",
"26 然而这日扫罗没有说什么，他想大卫遇事，偶染不洁，他必定是不洁。",
"27 初二日大卫的座位还空设。扫罗问他儿子约拿单说：「耶西的儿子为何昨日、今日没有来吃饭呢？」",
"",
"——【撒母耳记上 20】",
],
[
"5 Then said Boaz unto his servant that was set over the reapers, Whose damsel is this?",
"6 And the servant that was set over the reapers answered and said, It is the Moabitish damsel that came back with Naomi out of the country of Moab:",
"7 And she said, I pray you, let me glean and gather after the reapers among the sheaves: so she came, and hath continued even from the morning until now, that she tarried a little in the house.",
"8 Then said Boaz unto Ruth, Hearest thou not, my daughter? Go not to glean in another field, neither go from hence, but abide here fast by my maidens:",
"9 Let thine eyes be on the field that they do reap, and go thou after them: have I not charged the young men that they shall not touch thee? and when thou art athirst, go unto the vessels, and drink of that which the young men have drawn.",
"",
"——【The Book of Ruth 2】",
"",
"5 波阿斯问监管收割的仆人说：「那是谁家的女子？」",
"6 监管收割的仆人回答说：「是那摩押女子，跟随拿俄米从摩押地回来的。",
"7 她说：『请你容我跟着收割的人拾取打捆剩下的麦穗。』她从早晨直到如今，除了在屋子里坐一会儿，常在这里。」",
"8 波阿斯对路得说：「女儿啊，听我说，不要往别人田里拾取麦穗，也不要离开这里，要常与我使女们在一处。",
"9 我的仆人在那块田收割，你就跟着他们去。我已经吩咐仆人不可欺负你；你若渴了，就可以到器皿那里喝仆人打来的水。」",
"",
"——【路得记 2】",
],
[
"13 And the king said unto her, Be not afraid: for what sawest thou? And the woman said unto Saul, I saw gods ascending out of the earth.",
"14 And he said unto her, What form is he of? And she said, An old man cometh up; and he is covered with a mantle. And Saul perceived that it was Samuel, and he stooped with his face to the ground, and bowed himself.",
"15 And Samuel said to Saul, Why hast thou disquieted me, to bring me up? And Saul answered, I am sore distressed; for the Philistines make war against me, and God is departed from me, and answereth me no more, neither by prophets, nor by dreams: therefore I have called thee, that thou mayest make known unto me what I shall do.",
"16 Then said Samuel, Wherefore then dost thou ask of me, seeing the LORD is departed from thee, and is become thine enemy?",
"17 And the LORD hath done to him, as he spake by me: for the LORD hath rent the kingdom out of thine hand, and given it to thy neighbour, even to David:",
"",
"——【The First Book of Samuel 28】",
"",
"13 王对妇人说：「不要惧怕，你看见了什么呢？」妇人对扫罗说：「我看见有神从地里上来。」",
"14 扫罗说：「他是怎样的形状？」妇人说：「有一个老人上来，身穿长衣。」扫罗知道是撒母耳，就屈身，脸伏于地下拜。",
"15 撒母耳对扫罗说：「你为什么搅扰我，招我上来呢？」扫罗回答说：「我甚窘急；因为非利士人攻击我，　神也离开我，不再借先知或梦回答我。因此请你上来，好指示我应当怎样行。」",
"16 撒母耳说：「耶和华已经离开你，且与你为敌，你何必问我呢？",
"17 耶和华照他借我说的话，已经从你手里夺去国权，赐与别人，就是大卫。",
"",
"——【撒母耳记上 28】",
],
[
"18 And this is but a light thing in the sight of the LORD: he will deliver the Moabites also into your hand.",
"19 And ye shall smite every fenced city, and every choice city, and shall fell every good tree, and stop all wells of water, and mar every good piece of land with stones.",
"20 And it came to pass in the morning, when the meat offering was offered, that, behold, there came water by the way of Edom, and the country was filled with water.",
"21 And when all the Moabites heard that the kings were come up to fight against them, they gathered all that were able to put on armour, and upward, and stood in the border.",
"",
"——【The Second Book of the Kings 3】",
"",
"18 在耶和华眼中这还算为小事，他也必将摩押人交在你们手中。",
"19 你们必攻破一切坚城美邑，砍伐各种佳树，塞住一切水泉，用石头糟踏一切美田。」",
"20 次日早晨，约在献祭的时候，有水从以东而来，遍地就满了水。",
"21 摩押众人听见这三王上来要与他们争战，凡能顶盔贯甲的，无论老少，尽都聚集站在边界上。",
"",
"——【列王记下 3】",
],
[
"11 Verily, verily, I say unto thee, We speak that we do know, and testify that we have seen; and ye receive not our witness.",
"12 If I have told you earthly things, and ye believe not, how shall ye believe, if I tell you of heavenly things?",
"13 And no man hath ascended up to heaven, but he that came down from heaven, even the Son of man which is in heaven.",
"",
"——【The Gospel According to Saint John 3】",
"",
"11 我实实在在的告诉你，我们所说的是我们知道的；我们所见证的是我们见过的；你们却不领受我们的见证。",
"12 我对你们说地上的事，你们尚且不信，若说天上的事，如何能信呢？",
"13 除了从天降下、仍旧在天的人子，没有人升过天。",
"",
"——【约翰福音 3】",
],
[
"5 The LORD is the portion of mine inheritance and of my cup: thou maintainest my lot.",
"6 The lines are fallen unto me in pleasant places; yea, I have a goodly heritage.",
"7 I will bless the LORD, who hath given me counsel: my reins also instruct me in the night seasons.",
"8 I have set the LORD always before me: because he is at my right hand, I shall not be moved.",
"9 Therefore my heart is glad, and my glory rejoiceth: my flesh also shall rest in hope.",
"10 For thou wilt not leave my soul in hell; neither wilt thou suffer thine Holy One to see corruption.",
"",
"——【The Book of Psalms 16】",
"",
"5 耶和华是我的产业，是我杯中的分；我所得的，你为我持守。",
"6 用绳量给我的地界，坐落在佳美之处；我的产业实在美好。",
"7 我必称颂那指教我的耶和华；我的心肠在夜间也警戒我。",
"8 我将耶和华常摆在我面前，因他在我右边，我便不致摇动。",
"9 因此，我的心欢喜，我的灵（原文是荣耀）快乐；我的肉身也要安然居住。",
"10 因为你必不将我的灵魂撇在阴间，也不叫你的圣者见朽坏。",
"",
"——【诗篇 16】",
],
[
"4 Now these are the names of his children which he had in Jerusalem; Shammua, and Shobab, Nathan, and Solomon,",
"5 And Ibhar, and Elishua, and Elpalet,",
"6 And Nogah, and Nepheg, and Japhia,",
"7 And Elishama, and Beeliada, and Eliphalet.",
"8 And when the Philistines heard that David was anointed king over all Israel, all the Philistines went up to seek David. And David heard of it, and went out against them.",
"9 And the Philistines came and spread themselves in the valley of Rephaim.",
"",
"——【The First Book of the Chronicles 14】",
"",
"4 在耶路撒冷所生的众子是沙母亚、朔罢、拿单、所罗门、",
"5 益辖、以利书亚、以法列、",
"6 挪迦、尼斐、雅非亚、",
"7 以利沙玛、比利雅大、以利法列。",
"8 非利士人听见大卫受膏作以色列众人的王，非利士众人就上来寻索大卫。大卫听见，就出去迎敌。",
"9 非利士人来了，布散在利乏音谷。",
"",
"——【历代志上 14】",
],
[
"6 For by wise counsel thou shalt make thy war: and in multitude of counsellors there is safety.",
"7 Wisdom is too high for a fool: he openeth not his mouth in the gate.",
"8 He that deviseth to do evil shall be called a mischievous person.",
"9 The thought of foolishness is sin: and the scorner is an abomination to men.",
"",
"——【The Proverbs 24】",
"",
"6 你去打仗，要凭智谋；谋士众多，人便得胜。",
"7 智慧极高，非愚昧人所能及，所以在城门内不敢开口。",
"8 设计作恶的，必称为奸人。",
"9 愚妄人的思念乃是罪恶；亵慢者为人所憎恶。",
"",
"——【箴言 24】",
],
[
"7 At what instant I shall speak concerning a nation, and concerning a kingdom, to pluck up, and to pull down, and to destroy it;",
"8 If that nation, against whom I have pronounced, turn from their evil, I will repent of the evil that I thought to do unto them.",
"9 And at what instant I shall speak concerning a nation, and concerning a kingdom, to build and to plant it;",
"10 If it do evil in my sight, that it obey not my voice, then I will repent of the good, wherewith I said I would benefit them.",
"11 Now therefore go to, speak to the men of Judah, and to the inhabitants of Jerusalem, saying, Thus saith the LORD; Behold, I frame evil against you, and devise a device against you: return ye now every one from his evil way, and make your ways and your doings good.",
"12 And they said, There is no hope: but we will walk after our own devices, and we will every one do the imagination of his evil heart.",
"",
"——【The Book of the Prophet Jeremiah 18】",
"",
"7 我何时论到一邦或一国说，要拔出、拆毁、毁坏；",
"8 我所说的那一邦，若是转意离开他们的恶，我就必后悔，不将我想要施行的灾祸降与他们。",
"9 我何时论到一邦或一国说，要建立、栽植；",
"10 他们若行我眼中看为恶的事，不听从我的话，我就必后悔，不将我所说的福气赐给他们。",
"11 现在你要对犹大人和耶路撒冷的居民说：『耶和华如此说：我造出灾祸攻击你们，定意刑罚你们。你们各人当回头离开所行的恶道，改正你们的行动作为。』",
"12 「他们却说：『这是枉然。我们要照自己的计谋去行。』各人随自己顽梗的恶心做事。」",
"",
"——【耶利米书 18】",
],
[
"2 To speak evil of no man, to be no brawlers, but gentle, shewing all meekness unto all men.",
"3 For we ourselves also were sometimes foolish, disobedient, deceived, serving divers lusts and pleasures, living in malice and envy, hateful, and hating one another.",
"4 But after that the kindness and love of God our Saviour toward man appeared,",
"5 Not by works of righteousness which we have done, but according to his mercy he saved us, by the washing of regeneration, and renewing of the Holy Ghost;",
"6 Which he shed on us abundantly through Jesus Christ our Saviour;",
"",
"——【The Epistle of Paul the Apostle to Titus 3】",
"",
"2 不要毁谤，不要争竞，总要和平，向众人大显温柔。",
"3 我们从前也是无知、悖逆、受迷惑、服事各样私欲，和宴乐，常存恶毒（或作：阴毒）嫉妒的心，是可恨的，又是彼此相恨。",
"4 但到了　神─我们救主的恩慈和他向人所施的慈爱显明的时候，",
"5 他便救了我们；并不是因我们自己所行的义，乃是照他的怜悯，藉着重生的洗和圣灵的更新。",
"6 圣灵就是　神藉着耶稣基督我们救主厚厚浇灌在我们身上的，",
"",
"——【提多书 3】",
],
[
"1 And the Philistines took the ark of God, and brought it from Eben–ezer unto Ashdod.",
"2 When the Philistines took the ark of God, they brought it into the house of Dagon, and set it by Dagon.",
"3 And when they of Ashdod arose early on the morrow, behold, Dagon was fallen upon his face to the earth before the ark of the LORD. And they took Dagon, and set him in his place again.",
"4 And when they arose early on the morrow morning, behold, Dagon was fallen upon his face to the ground before the ark of the LORD; and the head of Dagon and both the palms of his hands were cut off upon the threshold; only the stump of Dagon was left to him.",
"",
"——【The First Book of Samuel 5】",
"",
"1 非利士人将　神的约柜从以便以谢抬到亚实突。",
"2 非利士人将　神的约柜抬进大衮庙，放在大衮的旁边。",
"3 次日清早，亚实突人起来，见大衮仆倒在耶和华的约柜前，脸伏于地，就把大衮仍立在原处。",
"4 又次日清早起来，见大衮仆倒在耶和华的约柜前，脸伏于地，并且大衮的头和两手都在门槛上折断，只剩下大衮的残体。",
"",
"——【撒母耳记上 5】",
],
[
"45 My people, go ye out of the midst of her, and deliver ye every man his soul from the fierce anger of the LORD.",
"46 And lest your heart faint, and ye fear for the rumour that shall be heard in the land; a rumour shall both come one year, and after that in another year shall come a rumour, and violence in the land, ruler against ruler.",
"",
"——【The Book of the Prophet Jeremiah 51】",
"",
"45 我的民哪，你们要从其中出去！各人拯救自己，躲避耶和华的烈怒。",
"46 你们不要心惊胆怯，也不要因境内所听见的风声惧怕；因为这年有风声传来；那年也有风声传来，境内有强暴的事，官长攻击官长。",
"",
"——【耶利米书 51】",
],
[
"4 But her end is bitter as wormwood, sharp as a twoedged sword.",
"5 Her feet go down to death; her steps take hold on hell.",
"",
"——【The Proverbs 5】",
"",
"4 至终却苦似茵蔯，快如两刃的刀。",
"5 她的脚下入死地；她脚步踏住阴间，",
"",
"——【箴言 5】",
],
[
"10 Wherefore, if I come, I will remember his deeds which he doeth, prating against us with malicious words: and not content therewith, neither doth he himself receive the brethren, and forbiddeth them that would, and casteth them out of the church.",
"11 Beloved, follow not that which is evil, but that which is good. He that doeth good is of God: but he that doeth evil hath not seen God.",
"12 Demetrius hath good report of all men, and of the truth itself: yea, and we also bear record; and ye know that our record is true.",
"13 I had many things to write, but I will not with ink and pen write unto thee:",
"14 But I trust I shall shortly see thee, and we shall speak face to face. Peace be to thee. Our friends salute thee. Greet the friends by name.",
"== The General Epistle of Jude ==",
"",
"——【The Third Epistle General of John 1】",
"",
"10 所以我若去，必要提说他所行的事，就是他用恶言妄论我们。还不以此为足，他自己不接待弟兄，有人愿意接待，他也禁止，并且将接待弟兄的人赶出教会。",
"11 亲爱的兄弟啊，不要效法恶，只要效法善。行善的属乎　神；行恶的未曾见过　神。",
"12 低米丢行善，有众人给他作见证，又有真理给他作见证；就是我们也给他作见证。你也知道我们的见证是真的。",
"13 我原有许多事要写给你，却不愿意用笔墨写给你，",
"14 但盼望快快的见你，我们就当面谈论。愿你平安。众位朋友都问你安。请你替我按着姓名问众位朋友安。",
"== 犹大书 ==",
"",
"——【约翰三书 1】",
],
[
"5 The thoughts of the diligent tend only to plenteousness; but of every one that is hasty only to want.",
"6 The getting of treasures by a lying tongue is a vanity tossed to and fro of them that seek death.",
"7 The robbery of the wicked shall destroy them; because they refuse to do judgment.",
"",
"——【The Proverbs 21】",
"",
"5 殷勤筹划的，足致丰裕；行事急躁的，都必缺乏。",
"6 用诡诈之舌求财的，就是自己取死；所得之财乃是吹来吹去的浮云。",
"7 恶人的强暴必将自己扫除，因他们不肯按公平行事。",
"",
"——【箴言 21】",
],
[
"10 Behold, I have refined thee, but not with silver; I have chosen thee in the furnace of affliction.",
"11 For mine own sake, even for mine own sake, will I do it: for how should my name be polluted? and I will not give my glory unto another.",
"12 Hearken unto me, O Jacob and Israel, my called; I am he; I am the first, I also am the last.",
"13 Mine hand also hath laid the foundation of the earth, and my right hand hath spanned the heavens: when I call unto them, they stand up together.",
"",
"——【The Book of the Prophet Isaiah 48】",
"",
"10 我熬炼你，却不像熬炼银子；你在苦难的炉中，我拣选你。",
"11 我为自己的缘故必行这事，我焉能使我的名被亵渎？我必不将我的荣耀归给假　神。",
"12 雅各─我所选召的以色列啊，当听我言：我是耶和华，我是首先的，也是末后的。",
"13 我手立了地的根基；我右手铺张诸天；我一招呼便都立住。",
"",
"——【以赛亚书 48】",
],
[
"3 Shall wood be taken thereof to do any work? or will men take a pin of it to hang any vessel thereon?",
"4 Behold, it is cast into the fire for fuel; the fire devoureth both the ends of it, and the midst of it is burned. Is it meet for any work?",
"",
"——【The Book of the Prophet Ezekiel 15】",
"",
"3 其上可以取木料做什么工用，可以取来做钉子挂什么器皿么？",
"4 看哪，已经抛在火中当作柴烧，火既烧了两头，中间也被烧了，还有益于工用吗？",
"",
"——【以西结书 15】",
],
[
"1 Jotham was twenty and five years old when he began to reign, and he reigned sixteen years in Jerusalem. His mother's name also was Jerushah, the daughter of Zadok.",
"2 And he did that which was right in the sight of the LORD, according to all that his father Uzziah did: howbeit he entered not into the temple of the LORD. And the people did yet corruptly.",
"3 He built the high gate of the house of the LORD, and on the wall of Ophel he built much.",
"",
"——【The Second Book of the Chronicles 27】",
"",
"1 约坦登基的时候年二十五岁，在耶路撒冷作王十六年，他母亲名叫耶路沙，是撒督的女儿。",
"2 约坦行耶和华眼中看为正的事，效法他父乌西雅一切所行的，只是不入耶和华的殿。百姓还行邪僻的事。",
"3 约坦建立耶和华殿的上门，在俄斐勒城上多有建造，",
"",
"——【历代志下 27】",
],
[
"3 And under it was the similitude of oxen, which did compass it round about: ten in a cubit, compassing the sea round about. Two rows of oxen were cast, when it was cast.",
"4 It stood upon twelve oxen, three looking toward the north, and three looking toward the west, and three looking toward the south, and three looking toward the east: and the sea was set above upon them, and all their hinder parts were inward.",
"5 And the thickness of it was an handbreadth, and the brim of it like the work of the brim of a cup, with flowers of lilies; and it received and held three thousand baths.",
"",
"——【The Second Book of the Chronicles 4】",
"",
"3 海周围有野瓜【原文作牛】的样式，每肘十瓜，共有两行，是铸海的时候铸上的；",
"4 有十二只铜牛驮海：三只向北，三只向西，三只向南，三只向东；海在牛上，牛尾向内；",
"5 海厚一掌，边如杯边，又如百合花，可容三千罢特；",
"",
"——【历代志下 4】",
],
[
"29 And at En–rimmon, and at Zareah, and at Jarmuth,",
"30 Zanoah, Adullam, and in their villages, at Lachish, and the fields thereof, at Azekah, and in the villages thereof. And they dwelt from Beer–sheba unto the valley of Hinnom.",
"31 The children also of Benjamin from Geba dwelt at Michmash, and Aija, and Beth–el, and in their villages,",
"32 And at Anathoth, Nob, Ananiah,",
"33 Hazor, Ramah, Gittaim,",
"34 Hadid, Zeboim, Neballat,",
"",
"——【The Book of Nehemiah 11】",
"",
"29 音‧临门、琐拉、耶末、",
"30 撒挪亚、亚杜兰，和属这两处的村庄；拉吉和属拉吉的田地；亚西加和属亚西加的乡村。他们所住的地方是从别是巴直到欣嫩谷。",
"31 便雅悯人从迦巴起，住在密抹、亚雅、伯特利和属伯特利的乡村。",
"32 亚拿突、挪伯、亚难雅、",
"33 夏琐、拉玛、基他音、",
"34 哈叠、洗编、尼八拉、",
"",
"——【尼希米记 11】",
],
];
