var bible31_global=[
[
"6 And he shall flay the burnt offering, and cut it into his pieces.",
"7 And the sons of Aaron the priest shall put fire upon the altar, and lay the wood in order upon the fire:",
"8 And the priests, Aaron's sons, shall lay the parts, the head, and the fat, in order upon the wood that is on the fire which is upon the altar:",
"9 But his inwards and his legs shall he wash in water: and the priest shall burn all on the altar, to be a burnt sacrifice, an offering made by fire, of a sweet savour unto the LORD.",
"10 And if his offering be of the flocks, namely, of the sheep, or of the goats, for a burnt sacrifice; he shall bring it a male without blemish.",
"11 And he shall kill it on the side of the altar northward before the LORD: and the priests, Aaron's sons, shall sprinkle his blood round about upon the altar.",
"",
"——【The Third Book of Moses: Called Leviticus 1】",
"",
"6 那人要剥去燔祭牲的皮，把燔祭牲切成块子。",
"7 祭司亚伦的子孙要把火放在坛上，把柴摆在火上。",
"8 亚伦子孙作祭司的，要把肉块和头并脂油摆在坛上火的柴上。",
"9 但燔祭的脏腑与腿要用水洗。祭司就要把一切全烧在坛上，当作燔祭，献与耶和华为馨香的火祭。",
"10 人的供物若以绵羊或山羊为燔祭，就要献上没有残疾的公羊。",
"11 要把羊宰于坛的北边，在耶和华面前；亚伦子孙作祭司的，要把羊血洒在坛的周围。",
"",
"——【利未记 1】",
],
[
"1 Behold, the LORD'S hand is not shortened, that it cannot save; neither his ear heavy, that it cannot hear:",
"2 But your iniquities have separated between you and your God, and your sins have hid his face from you, that he will not hear.",
"3 For your hands are defiled with blood, and your fingers with iniquity; your lips have spoken lies, your tongue hath muttered perverseness.",
"4 None calleth for justice, nor any pleadeth for truth: they trust in vanity, and speak lies; they conceive mischief, and bring forth iniquity.",
"5 They hatch cockatrice' eggs, and weave the spider's web: he that eateth of their eggs dieth, and that which is crushed breaketh out into a viper.",
"",
"——【The Book of the Prophet Isaiah 59】",
"",
"1 耶和华的膀臂并非缩短，不能拯救，耳朵并非发沉，不能听见，",
"2 但你们的罪孽使你们与　神隔绝；你们的罪恶使他掩面不听你们。",
"3 因你们的手被血沾染，你们的指头被罪孽沾污，你们的嘴唇说谎言，你们的舌头出恶语。",
"4 无一人按公义告状，无一人凭诚实辨白；都倚靠虚妄，说谎言。所怀的是毒害；所生的是罪孽。",
"5 他们菢毒蛇蛋，结蜘蛛网；人吃这蛋必死。这蛋被踏，必出蝮蛇。",
"",
"——【以赛亚书 59】",
],
[
"1 Furthermore Elihu answered and said,",
"2 Hear my words, O ye wise men; and give ear unto me, ye that have knowledge.",
"3 For the ear trieth words, as the mouth tasteth meat.",
"4 Let us choose to us judgment: let us know among ourselves what is good.",
"",
"——【The Book of Job 34】",
"",
"1 以利户又说：",
"2 你们智慧人要听我的话；有知识的人要留心听我说。",
"3 因为耳朵试验话语，好像上膛尝食物。",
"4 我们当选择何为是，彼此知道何为善。",
"",
"——【约伯记 34】",
],
[
"48 And the officers which were over thousands of the host, the captains of thousands, and captains of hundreds, came near unto Moses:",
"49 And they said unto Moses, Thy servants have taken the sum of the men of war which are under our charge, and there lacketh not one man of us.",
"",
"——【The Fourth Book of Moses: Called Numbers 31】",
"",
"48 带领千军的各军长，就是千夫长、百夫长，都近前来见摩西，",
"49 对他说：「仆人权下的兵已经计算总数，并不短少一人。",
"",
"——【民数记 31】",
],
[
"15 And it came to pass on the seventh day, that they rose early about the dawning of the day, and compassed the city after the same manner seven times: only on that day they compassed the city seven times.",
"16 And it came to pass at the seventh time, when the priests blew with the trumpets, Joshua said unto the people, Shout; for the LORD hath given you the city.",
"17 And the city shall be accursed, even it, and all that are therein, to the LORD: only Rahab the harlot shall live, she and all that are with her in the house, because she hid the messengers that we sent.",
"18 And ye, in any wise keep yourselves from the accursed thing, lest ye make yourselves accursed, when ye take of the accursed thing, and make the camp of Israel a curse, and trouble it.",
"19 But all the silver, and gold, and vessels of brass and iron, are consecrated unto the LORD: they shall come into the treasury of the LORD.",
"",
"——【The Book of Joshua 6】",
"",
"15 第七日清早，黎明的时候，他们起来，照样绕城七次；惟独这日把城绕了七次。",
"16 到了第七次，祭司吹角的时候，约书亚吩咐百姓说：「呼喊吧，因为耶和华已经把城交给你们了！",
"17 这城和其中所有的都要在耶和华面前毁灭；只有妓女喇合与她家中所有的可以存活，因为她隐藏了我们所打发的使者。",
"18 至于你们，务要谨慎，不可取那当灭的物，恐怕你们取了那当灭的物就连累以色列的全营，使全营受咒诅。",
"19 惟有金子、银子，和铜铁的器皿都要归耶和华为圣，必入耶和华的库中。」",
"",
"——【约书亚记 6】",
],
[
"9 And Hatach came and told Esther the words of Mordecai.",
"10 Again Esther spake unto Hatach, and gave him commandment unto Mordecai;",
"",
"——【The Book of Esther 4】",
"",
"9 哈他革回来，将末底改的话告诉以斯帖；",
"10 以斯帖就吩咐哈他革去见末底改，说：",
"",
"——【以斯帖记 4】",
],
[
"22 And Samuel said, Hath the LORD as great delight in burnt offerings and sacrifices, as in obeying the voice of the LORD? Behold, to obey is better than sacrifice, and to hearken than the fat of rams.",
"23 For rebellion is as the sin of witchcraft, and stubbornness is as iniquity and idolatry. Because thou hast rejected the word of the LORD, he hath also rejected thee from being king.",
"24 And Saul said unto Samuel, I have sinned: for I have transgressed the commandment of the LORD, and thy words: because I feared the people, and obeyed their voice.",
"",
"——【The First Book of Samuel 15】",
"",
"22 撒母耳说：耶和华喜悦燔祭和平安祭，岂如喜悦人听从他的话呢？听命胜于献祭；顺从胜于公羊的脂油。",
"23 悖逆的罪与行邪术的罪相等；顽梗的罪与拜虚神和偶像的罪相同。你既厌弃耶和华的命令，耶和华也厌弃你作王。",
"24 扫罗对撒母耳说：「我有罪了，我因惧怕百姓，听从他们的话，就违背了耶和华的命令和你的言语。",
"",
"——【撒母耳记上 15】",
],
[
"21 But the Philistines took him, and put out his eyes, and brought him down to Gaza, and bound him with fetters of brass; and he did grind in the prison house.",
"22 Howbeit the hair of his head began to grow again after he was shaven.",
"23 Then the lords of the Philistines gathered them together for to offer a great sacrifice unto Dagon their god, and to rejoice: for they said, Our god hath delivered Samson our enemy into our hand.",
"24 And when the people saw him, they praised their god: for they said, Our god hath delivered into our hands our enemy, and the destroyer of our country, which slew many of us.",
"25 And it came to pass, when their hearts were merry, that they said, Call for Samson, that he may make us sport. And they called for Samson out of the prison house; and he made them sport: and they set him between the pillars.",
"",
"——【The Book of Judges 16】",
"",
"21 非利士人将他拿住，剜了他的眼睛，带他下到迦萨，用铜链拘索他；他就在监里推磨。",
"22 然而他的头发被剃之后，又渐渐长起来了。",
"23 非利士人的首领聚集，要给他们的神大衮献大祭，并且欢乐，因为他们说：「我们的神将我们的仇敌参孙交在我们手中了。」",
"24 众人看见参孙，就赞美他们的神说：「我们的神将毁坏我们地、杀害我们许多人的仇敌交在我们手中了。」",
"25 他们正宴乐的时候，就说：「叫参孙来，在我们面前戏耍戏耍。」于是将参孙从监里提出来，他就在众人面前戏耍。他们使他站在两柱中间。",
"",
"——【士师记 16】",
],
[
"8 And Joseph knew his brethren, but they knew not him.",
"9 And Joseph remembered the dreams which he dreamed of them, and said unto them, Ye are spies; to see the nakedness of the land ye are come.",
"10 And they said unto him, Nay, my lord, but to buy food are thy servants come.",
"11 We are all one man's sons; we are true men, thy servants are no spies.",
"12 And he said unto them, Nay, but to see the nakedness of the land ye are come.",
"13 And they said, Thy servants are twelve brethren, the sons of one man in the land of Canaan; and, behold, the youngest is this day with our father, and one is not.",
"",
"——【The First Book of Moses: Called Genesis 42】",
"",
"8 约瑟认得他哥哥们，他们却不认得他。",
"9 约瑟想起从前所做的那两个梦，就对他们说：「你们是奸细，来窥探这地的虚实。」",
"10 他们对他说：「我主啊，不是的。仆人们是籴粮来的。",
"11 我们都是一个人的儿子，是诚实人；仆人们并不是奸细。」",
"12 约瑟说：「不然，你们必是窥探这地的虚实来的。」",
"13 他们说：「仆人们本是弟兄十二人，是迦南地一个人的儿子，顶小的现今在我们的父亲那里，有一个没有了。」",
"",
"——【创世记 42】",
],
[
"6 From which some having swerved have turned aside unto vain jangling;",
"7 Desiring to be teachers of the law; understanding neither what they say, nor whereof they affirm.",
"8 But we know that the law is good, if a man use it lawfully;",
"",
"——【The First Epistle of Paul the Apostle to Timothy 1】",
"",
"6 有人偏离这些，反去讲虚浮的话，",
"7 想要作教法师，却不明白自己所讲说的所论定的。",
"8 我们知道律法原是好的，只要人用得合宜；",
"",
"——【提摩太前书 1】",
],
[
"26 And he said, Let me go, for the day breaketh. And he said, I will not let thee go, except thou bless me.",
"27 And he said unto him, What is thy name? And he said, Jacob.",
"28 And he said, Thy name shall be called no more Jacob, but Israel: for as a prince hast thou power with God and with men, and hast prevailed.",
"29 And Jacob asked him, and said, Tell me, I pray thee, thy name. And he said, Wherefore is it that thou dost ask after my name? And he blessed him there.",
"30 And Jacob called the name of the place Peniel: for I have seen God face to face, and my life is preserved.",
"31 And as he passed over Penuel the sun rose upon him, and he halted upon his thigh.",
"",
"——【The First Book of Moses: Called Genesis 32】",
"",
"26 那人说：「天黎明了，容我去吧！」雅各说：「你不给我祝福，我就不容你去。」",
"27 那人说：「你名叫什么？」他说：「我名叫雅各。」",
"28 那人说：「你的名不要再叫雅各，要叫以色列；因为你与　神与人较力，都得了胜。」",
"29 雅各问他说：「请将你的名告诉我。」那人说：「何必问我的名？」于是在那里给雅各祝福。",
"30 雅各便给那地方起名叫毗努伊勒【就是　神之面的意思】，意思说：「我面对面见了　神，我的性命仍得保全。」",
"31 日头刚出来的时候，雅各经过毗努伊勒，他的大腿就瘸了。",
"",
"——【创世记 32】",
],
[
"16 Thus saith the whole congregation of the LORD, What trespass is this that ye have committed against the God of Israel, to turn away this day from following the LORD, in that ye have builded you an altar, that ye might rebel this day against the LORD?",
"17 Is the iniquity of Peor too little for us, from which we are not cleansed until this day, although there was a plague in the congregation of the LORD,",
"18 But that ye must turn away this day from following the LORD? and it will be, seeing ye rebel to day against the LORD, that to morrow he will be wroth with the whole congregation of Israel.",
"19 Notwithstanding, if the land of your possession be unclean, then pass ye over unto the land of the possession of the LORD, wherein the LORD'S tabernacle dwelleth, and take possession among us: but rebel not against the LORD, nor rebel against us, in building you an altar beside the altar of the LORD our God.",
"20 Did not Achan the son of Zerah commit a trespass in the accursed thing, and wrath fell on all the congregation of Israel? and that man perished not alone in his iniquity.",
"",
"——【The Book of Joshua 22】",
"",
"16 「耶和华全会众这样说，你们今日转去不跟从耶和华，干犯以色列的　神，为自己筑一座坛，悖逆了耶和华，这犯的是什么罪呢？",
"17 从前拜毗珥的罪孽还算小吗？虽然瘟疫临到耶和华的会众，到今日我们还没有洗净这罪。",
"18 你们今日竟转去不跟从耶和华吗？你们今日既悖逆耶和华，明日他必向以色列全会众发怒。",
"19 你们所得为业之地，若嫌不洁净，就可以过到耶和华之地，就是耶和华的帐幕所住之地，在我们中间得地业。只是不可悖逆耶和华，也不可得罪我们，在耶和华─我们　神的坛以外为自己筑坛。",
"20 从前谢拉的曾孙亚干岂不是在那当灭的物上犯了罪，就有忿怒临到以色列全会众吗？那人在所犯的罪中不独一人死亡。」",
"",
"——【约书亚记 22】",
],
[
"3 Without the vail of the testimony, in the tabernacle of the congregation, shall Aaron order it from the evening unto the morning before the LORD continually: it shall be a statute for ever in your generations.",
"4 He shall order the lamps upon the pure candlestick before the LORD continually.",
"5 And thou shalt take fine flour, and bake twelve cakes thereof: two tenth deals shall be in one cake.",
"6 And thou shalt set them in two rows, six on a row, upon the pure table before the LORD.",
"7 And thou shalt put pure frankincense upon each row, that it may be on the bread for a memorial, even an offering made by fire unto the LORD.",
"8 Every sabbath he shall set it in order before the LORD continually, being taken from the children of Israel by an everlasting covenant.",
"",
"——【The Third Book of Moses: Called Leviticus 24】",
"",
"3 在会幕中法柜的幔子外，亚伦从晚上到早晨必在耶和华面前经理这灯。这要作你们世世代代永远的定例。",
"4 他要在耶和华面前常收拾精金灯台上的灯。」",
"5 「你要取细面，烤成十二个饼，每饼用面伊法十分之二。",
"6 要把饼摆列两行（或作：摞；下同），每行六个，在耶和华面前精金的桌子上；",
"7 又要把净乳香放在每行饼上，作为纪念，就是作为火祭献给耶和华。",
"8 每安息日要常摆在耶和华面前；这为以色列人作永远的约。",
"",
"——【利未记 24】",
],
[
"15 The seventeenth to Hezir, the eighteenth to Aphses,",
"16 The nineteenth to Pethahiah, the twentieth to Jehezekel,",
"17 The one and twentieth to Jachin, the two and twentieth to Gamul,",
"18 The three and twentieth to Delaiah, the four and twentieth to Maaziah.",
"19 These were the orderings of them in their service to come into the house of the LORD, according to their manner, under Aaron their father, as the LORD God of Israel had commanded him.",
"",
"——【The First Book of the Chronicles 24】",
"",
"15 第十七是希悉，第十八是哈辟悉，",
"16 第十九是毗他希雅，第二十是以西结，",
"17 第二十一是雅斤，第二十二是迦末，",
"18 第二十三是第来雅，第二十四是玛西亚。",
"19 这就是他们的班次，要照耶和华─以色列的　神借他们祖宗亚伦所吩咐的条例进入耶和华的殿办理事务。",
"",
"——【历代志上 24】",
],
[
"12 And he exerciseth all the power of the first beast before him, and causeth the earth and them which dwell therein to worship the first beast, whose deadly wound was healed.",
"13 And he doeth great wonders, so that he maketh fire come down from heaven on the earth in the sight of men,",
"14 And deceiveth them that dwell on the earth by the means of those miracles which he had power to do in the sight of the beast; saying to them that dwell on the earth, that they should make an image to the beast, which had the wound by a sword, and did live.",
"15 And he had power to give life unto the image of the beast, that the image of the beast should both speak, and cause that as many as would not worship the image of the beast should be killed.",
"",
"——【The Revelation of Saint John the Devine 13】",
"",
"12 牠在头一个兽面前，施行头一个兽所有的权柄，并且叫地和住在地上的人拜那死伤医好的头一个兽。",
"13 又行大奇事，甚至在人面前，叫火从天降在地上。",
"14 牠因赐给牠权柄在兽面前能行奇事，就迷惑住在地上的人，说：要给那受刀伤还活著的兽作个像。",
"15 又有权柄赐给牠，叫兽像有生气，并且能说话，又叫所有不拜兽像的人都被杀害。",
"",
"——【启示录 13】",
],
[
"3 In like manner shalt thou do with his ass; and so shalt thou do with his raiment; and with all lost thing of thy brother's, which he hath lost, and thou hast found, shalt thou do likewise: thou mayest not hide thyself.",
"4 Thou shalt not see thy brother's ass or his ox fall down by the way, and hide thyself from them: thou shalt surely help him to lift them up again.",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 22】",
"",
"3 你的弟兄无论失落什么，或是驴，或是衣服，你若遇见，都要这样行，不可佯为不见。",
"4 你若看见弟兄的牛或驴跌倒在路上，不可佯为不见，总要帮助他拉起来。",
"",
"——【申命记 22】",
],
[
"1 The LORD also spake unto Joshua, saying,",
"2 Speak to the children of Israel, saying, Appoint out for you cities of refuge, whereof I spake unto you by the hand of Moses:",
"3 That the slayer that killeth any person unawares and unwittingly may flee thither: and they shall be your refuge from the avenger of blood.",
"4 And when he that doth flee unto one of those cities shall stand at the entering of the gate of the city, and shall declare his cause in the ears of the elders of that city, they shall take him into the city unto them, and give him a place, that he may dwell among them.",
"5 And if the avenger of blood pursue after him, then they shall not deliver the slayer up into his hand; because he smote his neighbour unwittingly, and hated him not beforetime.",
"6 And he shall dwell in that city, until he stand before the congregation for judgment, and until the death of the high priest that shall be in those days: then shall the slayer return, and come unto his own city, and unto his own house, unto the city from whence he fled.",
"",
"——【The Book of Joshua 20】",
"",
"1 耶和华晓谕约书亚说：",
"2 「你吩咐以色列人说：你们要照著我借摩西所晓谕你们的，为自己设立逃城，",
"3 使那无心而误杀人的，可以逃到那里。这些城可以作你们逃避报血仇人的地方。",
"4 那杀人的要逃到这些城中的一座城，站在城门口，将他的事情说给城内的长老们听。他们就把他收进城里，给他地方，使他住在他们中间。",
"5 若是报血仇的追了他来，长老不可将他交在报血仇的手里；因为他是素无仇恨，无心杀了人的。",
"6 他要住在那城里，站在会众面前听审判，等到那时的大祭司死了，杀人的才可以回到本城本家，就是他所逃出来的那城。」",
"",
"——【约书亚记 20】",
],
[
"9 And they that escape of you shall remember me among the nations whither they shall be carried captives, because I am broken with their whorish heart, which hath departed from me, and with their eyes, which go a whoring after their idols: and they shall lothe themselves for the evils which they have committed in all their abominations.",
"10 And they shall know that I am the LORD, and that I have not said in vain that I would do this evil unto them.",
"11 Thus saith the Lord GOD; Smite with thine hand, and stamp with thy foot, and say, Alas for all the evil abominations of the house of Israel! for they shall fall by the sword, by the famine, and by the pestilence.",
"",
"——【The Book of the Prophet Ezekiel 6】",
"",
"9 那脱离刀剑的人必在所掳到的各国中记念我，为他们心中何等伤破，是因他们起淫心，远离我，眼对偶像行邪淫。他们因行一切可憎的恶事，必厌恶自己。",
"10 他们必知道我是耶和华；我说要使这灾祸临到他们身上，并非空话。",
"11 「主耶和华如此说：你当拍手顿足，说：哀哉！以色列家行这一切可憎的恶事，他们必倒在刀剑、饥荒、瘟疫之下。",
"",
"——【以西结书 6】",
],
[
"3 Then Esther the queen answered and said, If I have found favour in thy sight, O king, and if it please the king, let my life be given me at my petition, and my people at my request:",
"4 For we are sold, I and my people, to be destroyed, to be slain, and to perish. But if we had been sold for bondmen and bondwomen, I had held my tongue, although the enemy could not countervail the king's damage.",
"5 Then the king Ahasuerus answered and said unto Esther the queen, Who is he, and where is he, that durst presume in his heart to do so?",
"6 And Esther said, The adversary and enemy is this wicked Haman. Then Haman was afraid before the king and the queen.",
"",
"——【The Book of Esther 7】",
"",
"3 王后以斯帖回答说：「我若在王眼前蒙恩，王若以为美，我所愿的，是愿王将我的性命赐给我；我所求的，是求王将我的本族赐给我。",
"4 因我和我的本族被卖了，要剪除杀戮灭绝我们。我们若被卖为奴为婢，我也闭口不言；但王的损失，敌人万不能补足。」",
"5 亚哈随鲁王问王后以斯帖说：「擅敢起意如此行的是谁？这人在哪里呢？」",
"6 以斯帖说：「仇人敌人就是这恶人哈曼！」哈曼在王和王后面前就甚惊惶。",
"",
"——【以斯帖记 7】",
],
[
"1 It is not expedient for me doubtless to glory. I will come to visions and revelations of the Lord.",
"2 I knew a man in Christ above fourteen years ago, (whether in the body, I cannot tell; or whether out of the body, I cannot tell: God knoweth;) such an one caught up to the third heaven.",
"3 And I knew such a man, (whether in the body, or out of the body, I cannot tell: God knoweth;)",
"4 How that he was caught up into paradise, and heard unspeakable words, which it is not lawful for a man to utter.",
"5 Of such an one will I glory: yet of myself I will not glory, but in mine infirmities.",
"6 For though I would desire to glory, I shall not be a fool; for I will say the truth: but now I forbear, lest any man should think of me above that which he seeth me to be, or that he heareth of me.",
"",
"——【The Second Epistle of Paul the Apostle to the Corinthians 12】",
"",
"1 我自夸固然无益，但我是不得已的。如今我要说到主的显现和启示。",
"2 我认得一个在基督里的人，他前十四年被提到第三层天上去；或在身内，我不知道；或在身外，我也不知道；只有　神知道。",
"3 我认得这人；或在身内，或在身外，我都不知道，只有　神知道。",
"4 他被提到乐园里，听见隐祕的言语，是人不可说的。",
"5 为这人，我要夸口；但是为我自己，除了我的软弱以外，我并不夸口。",
"6 我就是愿意夸口也不算狂，因为我必说实话；只是我禁止不说，恐怕有人把我看高了，过于他在我身上所看见所听见的。",
"",
"——【哥林多后书 12】",
],
[
"2 The son of Shallum, the son of Zadok, the son of Ahitub,",
"3 The son of Amariah, the son of Azariah, the son of Meraioth,",
"4 The son of Zerahiah, the son of Uzzi, the son of Bukki,",
"5 The son of Abishua, the son of Phinehas, the son of Eleazar, the son of Aaron the chief priest:",
"",
"——【Ezra 7】",
"",
"2 希勒家是沙龙的儿子，沙龙是撒督的儿子，撒督是亚希突的儿子，",
"3 亚希突是亚玛利雅的儿子，亚玛利雅是亚撒利雅的儿子，亚撒利雅是米拉约的儿子，",
"4 米拉约是西拉希雅的儿子，西拉希雅是乌西的儿子，乌西是布基的儿子，",
"5 布基是亚比书的儿子，亚比书是非尼哈的儿子，非尼哈是以利亚撒的儿子，以利亚撒是大祭司亚伦的儿子。",
"",
"——【以斯拉记 7】",
],
[
"4 Her former husband, which sent her away, may not take her again to be his wife, after that she is defiled; for that is abomination before the LORD: and thou shalt not cause the land to sin, which the LORD thy God giveth thee for an inheritance.",
"5 When a man hath taken a new wife, he shall not go out to war, neither shall he be charged with any business: but he shall be free at home one year, and shall cheer up his wife which he hath taken.",
"6 No man shall take the nether or the upper millstone to pledge: for he taketh a man's life to pledge.",
"",
"——【The Fifth Book of Moses: Called Deuteronomy 24】",
"",
"4 打发她去的前夫不可在妇人玷污之后再娶她为妻，因为这是耶和华所憎恶的；不可使耶和华─你　神所赐为业之地被玷污了。",
"5 「新娶妻之人不可从军出征，也不可托他办理什么公事，可以在家清闲一年，使他所娶的妻快活。",
"6 「不可拿人的全盘磨石或是上磨石作当头，因为这是拿人的命作当头。",
"",
"——【申命记 24】",
],
[
"12 Therefore also now, saith the LORD, turn ye even to me with all your heart, and with fasting, and with weeping, and with mourning:",
"13 And rend your heart, and not your garments, and turn unto the LORD your God: for he is gracious and merciful, slow to anger, and of great kindness, and repenteth him of the evil.",
"14 Who knoweth if he will return and repent, and leave a blessing behind him; even a meat offering and a drink offering unto the LORD your God?",
"",
"——【Joel 2】",
"",
"12 耶和华说：虽然如此，你们应当禁食、哭泣、悲哀，一心归向我。",
"13 你们要撕裂心肠，不撕裂衣服。归向耶和华─你们的　神；因为他有恩典，有怜悯，不轻易发怒，有丰盛的慈爱，并且后悔不降所说的灾。",
"14 或者他转意后悔，留下余福，就是留下献给耶和华─你们　神的素祭和奠祭，也未可知。",
"",
"——【约珥书 2】",
],
[
"37 Behold, I will gather them out of all countries, whither I have driven them in mine anger, and in my fury, and in great wrath; and I will bring them again unto this place, and I will cause them to dwell safely:",
"38 And they shall be my people, and I will be their God:",
"39 And I will give them one heart, and one way, that they may fear me for ever, for the good of them, and of their children after them:",
"",
"——【The Book of the Prophet Jeremiah 32】",
"",
"37 「我在怒气、忿怒，和大恼恨中，将以色列人赶到各国。日后我必从那里将他们招聚出来，领他们回到此地，使他们安然居住。",
"38 他们要作我的子民，我要作他们的　神。",
"39 我要使他们彼此同心同道，好叫他们永远敬畏我，使他们和他们后世的子孙得福乐，",
"",
"——【耶利米书 32】",
],
[
"1 Be merciful unto me, O God, be merciful unto me: for my soul trusteth in thee: yea, in the shadow of thy wings will I make my refuge, until these calamities be overpast.",
"2 I will cry unto God most high; unto God that performeth all things for me.",
"3 He shall send from heaven, and save me from the reproach of him that would swallow me up. Selah. God shall send forth his mercy and his truth.",
"",
"——【The Book of Psalms 57】",
"",
"1 （大卫逃避扫罗，藏在洞里。那时，他作这金诗，交与伶长。调用休要毁坏。）　神啊，求你怜悯我，怜悯我！因为我的心投靠你。我要投靠在你翅膀的荫下，等到灾害过去。",
"2 我要求告至高的　神，就是为我成全诸事的　神。",
"3 那要吞我的人辱骂我的时候，　神从天上必施恩救我，也必向我发出慈爱和诚实。",
"",
"——【诗篇 57】",
],
[
"1 O God, my heart is fixed; I will sing and give praise, even with my glory.",
"2 Awake, psaltery and harp: I myself will awake early.",
"3 I will praise thee, O LORD, among the people: and I will sing praises unto thee among the nations.",
"4 For thy mercy is great above the heavens: and thy truth reacheth unto the clouds.",
"5 Be thou exalted, O God, above the heavens: and thy glory above all the earth;",
"",
"——【The Book of Psalms 108】",
"",
"1 （大卫的诗歌。）　神啊，我心坚定；我口（原文是荣耀）要唱诗歌颂！",
"2 琴瑟啊，你们当醒起！我自己要极早醒起！",
"3 耶和华啊，我要在万民中称谢你，在列邦中歌颂你！",
"4 因为，你的慈爱大过诸天；你的诚实达到穹苍。",
"5 　神啊，愿你崇高过于诸天！愿你的荣耀高过全地！",
"",
"——【诗篇 108】",
],
[
"9 And saith unto him, All these things will I give thee, if thou wilt fall down and worship me.",
"10 Then saith Jesus unto him, Get thee hence, Satan: for it is written, Thou shalt worship the Lord thy God, and him only shalt thou serve.",
"11 Then the devil leaveth him, and, behold, angels came and ministered unto him.",
"12 Now when Jesus had heard that John was cast into prison, he departed into Galilee;",
"13 And leaving Nazareth, he came and dwelt in Capernaum, which is upon the sea coast, in the borders of Zabulon and Nephthalim:",
"14 That it might be fulfilled which was spoken by Esaias the prophet, saying,",
"",
"——【The Gospel According to Saint Matthew 4】",
"",
"9 对他说：「你若俯伏拜我，我就把这一切都赐给你。」",
"10 耶稣说：「撒但（撒但就是抵挡的意思，乃魔鬼的别名），退去吧！因为经上记著说：当拜主你的　神，单要事奉他。」",
"11 于是，魔鬼离了耶稣，有天使来伺候他。",
"12 耶稣听见约翰下了监，就退到加利利去；",
"13 后又离开拿撒勒，往迦百农去，就住在那里。那地方靠海，在西布伦和拿弗他利的边界上。",
"14 这是要应验先知以赛亚的话，",
"",
"——【马太福音 4】",
],
[
"2 And they went about in Judah, and gathered the Levites out of all the cities of Judah, and the chief of the fathers of Israel, and they came to Jerusalem.",
"3 And all the congregation made a covenant with the king in the house of God. And he said unto them, Behold, the king's son shall reign, as the LORD hath said of the sons of David.",
"4 This is the thing that ye shall do; A third part of you entering on the sabbath, of the priests and of the Levites, shall be porters of the doors;",
"",
"——【The Second Book of the Chronicles 23】",
"",
"2 他们走遍犹大，从犹大各城里招聚利未人和以色列的众族长到耶路撒冷来。",
"3 会众在　神殿里与王立约。耶何耶大对他们说：「看哪，王的儿子必当作王，正如耶和华指著大卫子孙所应许的话」；",
"4 又说：「你们当这样行：祭司和利未人凡安息日进班的，三分之一要把守各门，",
"",
"——【历代志下 23】",
],
[
"5 But I will send a fire upon Judah, and it shall devour the palaces of Jerusalem.",
"6 Thus saith the LORD; For three transgressions of Israel, and for four, I will not turn away the punishment thereof; because they sold the righteous for silver, and the poor for a pair of shoes;",
"7 That pant after the dust of the earth on the head of the poor, and turn aside the way of the meek: and a man and his father will go in unto the same maid, to profane my holy name:",
"8 And they lay themselves down upon clothes laid to pledge by every altar, and they drink the wine of the condemned in the house of their god.",
"9 Yet destroyed I the Amorite before them, whose height was like the height of the cedars, and he was strong as the oaks; yet I destroyed his fruit from above, and his roots from beneath.",
"10 Also I brought you up from the land of Egypt, and led you forty years through the wilderness, to possess the land of the Amorite.",
"",
"——【Amos 2】",
"",
"5 我却要降火在犹大，烧灭耶路撒冷的宫殿。",
"6 耶和华如此说：以色列人三番四次地犯罪，我必不免去他们的刑罚；因他们为银子卖了义人，为一双鞋卖了穷人。",
"7 他们见穷人头上所蒙的灰也都垂涎，阻碍谦卑人的道路。父子同一个女子行淫，亵渎我的圣名。",
"8 他们在各坛旁铺人所当的衣服，卧在其上，又在他们神的庙中喝受罚之人的酒。",
"9 我从以色列人面前除灭亚摩利人。他虽高大如香柏树，坚固如橡树，我却上灭他的果子，下绝他的根本。",
"10 我也将你们从埃及地领上来，在旷野引导你们四十年，使你们得亚摩利人之地为业。",
"",
"——【阿摩司书 2】",
],
[
"1 Now Jehoshaphat slept with his fathers, and was buried with his fathers in the city of David. And Jehoram his son reigned in his stead.",
"2 And he had brethren the sons of Jehoshaphat, Azariah, and Jehiel, and Zechariah, and Azariah, and Michael, and Shephatiah: all these were the sons of Jehoshaphat king of Israel.",
"3 And their father gave them great gifts of silver, and of gold, and of precious things, with fenced cities in Judah: but the kingdom gave he to Jehoram; because he was the firstborn.",
"4 Now when Jehoram was risen up to the kingdom of his father, he strengthened himself, and slew all his brethren with the sword, and divers also of the princes of Israel.",
"",
"——【The Second Book of the Chronicles 21】",
"",
"1 约沙法与他列祖同睡，葬在大卫城他列祖的坟地里。他儿子约兰接续他作王。",
"2 约兰有几个兄弟，就是约沙法的儿子亚撒利雅、耶歇、撒迦利雅、亚撒利雅、米迦勒、示法提雅。这都是犹大王约沙法的儿子。",
"3 他们的父亲将许多金银、财宝，和犹大地的坚固城赐给他们；但将国赐给约兰，因为他是长子。",
"4 约兰兴起坐他父的位，奋勇自强，就用刀杀了他的众兄弟和以色列的几个首领。",
"",
"——【历代志下 21】",
],
[
"1 Now of the things which we have spoken this is the sum: We have such an high priest, who is set on the right hand of the throne of the Majesty in the heavens;",
"2 A minister of the sanctuary, and of the true tabernacle, which the Lord pitched, and not man.",
"3 For every high priest is ordained to offer gifts and sacrifices: wherefore it is of necessity that this man have somewhat also to offer.",
"",
"——【The Epistle of Paul the Apostle to the Hebrews 8】",
"",
"1 我们所讲的事，其中第一要紧的，就是我们有这样的大祭司，已经坐在天上至大者宝座的右边，",
"2 在圣所，就是真帐幕里，作执事；这帐幕是主所支的，不是人所支的。",
"3 凡大祭司都是为献礼物和祭物设立的，所以这位大祭司也必须有所献的。",
"",
"——【希伯来书 8】",
],
];
