var bible31_global=[
[
"1 The song of songs, which is Solomon's.",
"2 Let him kiss me with the kisses of his mouth: for thy love is better than wine.",
"",
"——【The Song of Solomon 1】",
"",
"1 所罗门的歌，是歌中的雅歌。",
"2 愿他用口与我亲嘴；因你的爱情比酒更美。",
"",
"——【雅歌 1】",
],
[
"8 And they said, What one is there of the tribes of Israel that came not up to Mizpeh to the LORD? And, behold, there came none to the camp from Jabesh–gilead to the assembly.",
"9 For the people were numbered, and, behold, there were none of the inhabitants of Jabesh–gilead there.",
"10 And the congregation sent thither twelve thousand men of the valiantest, and commanded them, saying, Go and smite the inhabitants of Jabesh–gilead with the edge of the sword, with the women and the children.",
"11 And this is the thing that ye shall do, Ye shall utterly destroy every male, and every woman that hath lain by man.",
"12 And they found among the inhabitants of Jabesh–gilead four hundred young virgins, that had known no man by lying with any male: and they brought them unto the camp to Shiloh, which is in the land of Canaan.",
"",
"——【The Book of Judges 21】",
"",
"8 又彼此问说：「以色列支派中谁没有上米斯巴到耶和华面前来呢？」他们就查出基列‧雅比没有一人进营到会众那里；",
"9 因为百姓被数的时候，没有一个基列‧雅比人在那里。",
"10 会众就打发一万二千大勇士，吩咐他们说：「你们去用刀将基列‧雅比人连妇女带孩子都击杀了。",
"11 所当行的就是这样：要将一切男子和已嫁的女子尽行杀戮。」",
"12 他们在基列‧雅比人中，遇见了四百个未嫁的处女，就带到迦南地的示罗营里。",
"",
"——【士师记 21】",
],
[
"2 I beseech Euodias, and beseech Syntyche, that they be of the same mind in the Lord.",
"3 And I intreat thee also, true yokefellow, help those women which laboured with me in the gospel, with Clement also, and with other my fellowlabourers, whose names are in the book of life.",
"4 Rejoice in the Lord alway: and again I say, Rejoice.",
"5 Let your moderation be known unto all men. The Lord is at hand.",
"",
"——【The Epistle of Paul the Apostle to the Philippians 4】",
"",
"2 我劝友阿爹和循都基，要在主里同心。",
"3 我也求你这真实同负一轭的，帮助这两个女人，因为他们在福音上曾与我一同劳苦；还有革利免，并其余和我一同做工的，他们的名字都在生命册上。",
"4 你们要靠主常常喜乐。我再说，你们要喜乐。",
"5 当叫众人知道你们谦让的心。主已经近了。",
"",
"——【腓立比书 4】",
],
[
"2 Hear ye, O mountains, the LORD'S controversy, and ye strong foundations of the earth: for the LORD hath a controversy with his people, and he will plead with Israel.",
"3 O my people, what have I done unto thee? and wherein have I wearied thee? testify against me.",
"4 For I brought thee up out of the land of Egypt, and redeemed thee out of the house of servants; and I sent before thee Moses, Aaron, and Miriam.",
"5 O my people, remember now what Balak king of Moab consulted, and what Balaam the son of Beor answered him from Shittim unto Gilgal; that ye may know the righteousness of the LORD.",
"6 Wherewith shall I come before the LORD, and bow myself before the high God? shall I come before him with burnt offerings, with calves of a year old?",
"7 Will the LORD be pleased with thousands of rams, or with ten thousands of rivers of oil? shall I give my firstborn for my transgression, the fruit of my body for the sin of my soul?",
"",
"——【Micah 6】",
"",
"2 山岭和地永久的根基啊，要听耶和华争辩的话！因为耶和华要与他的百姓争辩，与以色列争论。",
"3 我的百姓啊，我向你做了什么呢？我在什么事上使你厌烦？你可以对我证明。",
"4 我曾将你从埃及地领出来，从作奴仆之家救赎你；我也差遣摩西、亚伦，和米利暗在你前面行。",
"5 我的百姓啊，你们当追念摩押王巴勒所设的谋和比珥的儿子巴兰回答他的话，并你们从什亭到吉甲所遇见的事，好使你们知道耶和华公义的作为。",
"6 我朝见耶和华，在至高　神面前跪拜，当献上什么呢？岂可献一岁的牛犊为燔祭吗？",
"7 耶和华岂喜悦千千的公羊，或是万万的油河吗？我岂可为自己的罪过献我的长子吗？为心中的罪恶献我身所生的吗？",
"",
"——【弥迦书 6】",
],
[
"13 As for the wheels, it was cried unto them in my hearing, O wheel.",
"14 And every one had four faces: the first face was the face of a cherub, and the second face was the face of a man, and the third the face of a lion, and the fourth the face of an eagle.",
"15 And the cherubims were lifted up. This is the living creature that I saw by the river of Chebar.",
"",
"——【The Book of the Prophet Ezekiel 10】",
"",
"13 至于这些轮子，我耳中听见说是旋转的。",
"14 基路伯各有四脸：第一是基路伯的脸，第二是人的脸，第三是狮子的脸，第四是鹰的脸。",
"15 基路伯升上去了；这是我在迦巴鲁河边所见的活物。",
"",
"——【以西结书 10】",
],
[
"13 If we believe not, yet he abideth faithful: he cannot deny himself.",
"14 Of these things put them in remembrance, charging them before the Lord that they strive not about words to no profit, but to the subverting of the hearers.",
"",
"——【The Second Epistle of Paul the Apostle to Timothy 2】",
"",
"13 我们纵然失信，他仍是可信的，因为他不能背乎自己。",
"14 你要使众人回想这些事，在主面前嘱咐他们：不可为言语争辩；这是没有益处的，只能败坏听见的人。",
"",
"——【提摩太后书 2】",
],
[
"15 And Hilkiah answered and said to Shaphan the scribe, I have found the book of the law in the house of the LORD. And Hilkiah delivered the book to Shaphan.",
"16 And Shaphan carried the book to the king, and brought the king word back again, saying, All that was committed to thy servants, they do it.",
"17 And they have gathered together the money that was found in the house of the LORD, and have delivered it into the hand of the overseers, and to the hand of the workmen.",
"",
"——【The Second Book of the Chronicles 34】",
"",
"15 希勒家对书记沙番说：「我在耶和华殿里得了律法书。」遂将书递给沙番。",
"16 沙番把书拿到王那里，回复王说：「凡交给仆人们办的都办理了。",
"17 耶和华殿里的银子倒出来，交给督工的和匠人的手里了。」",
"",
"——【历代志下 34】",
],
[
"9 And Moses said unto Joshua, Choose us out men, and go out, fight with Amalek: to morrow I will stand on the top of the hill with the rod of God in mine hand.",
"10 So Joshua did as Moses had said to him, and fought with Amalek: and Moses, Aaron, and Hur went up to the top of the hill.",
"11 And it came to pass, when Moses held up his hand, that Israel prevailed: and when he let down his hand, Amalek prevailed.",
"",
"——【The Second Book of Moses: Called Exodus 17】",
"",
"9 摩西对约书亚说：「你为我们选出人来，出去和亚玛力人争战。明天我手里要拿着　神的杖，站在山顶上。」",
"10 于是约书亚照着摩西对他所说的话行，和亚玛力人争战。摩西、亚伦，与户珥都上了山顶。",
"11 摩西何时举手，以色列人就得胜，何时垂手，亚玛力人就得胜。",
"",
"——【出埃及记 17】",
],
[
"1 Then answered Bildad the Shuhite, and said,",
"2 Dominion and fear are with him, he maketh peace in his high places.",
"3 Is there any number of his armies? and upon whom doth not his light arise?",
"",
"——【The Book of Job 25】",
"",
"1 书亚人比勒达回答说：",
"2 　神有治理之权，有威严可畏；他在高处施行和平。",
"3 他的诸军岂能数算？他的光亮一发，谁不蒙照呢？",
"",
"——【约伯记 25】",
],
[
"11 And our adversaries said, They shall not know, neither see, till we come in the midst among them, and slay them, and cause the work to cease.",
"12 And it came to pass, that when the Jews which dwelt by them came, they said unto us ten times, From all places whence ye shall return unto us they will be upon you.",
"",
"——【The Book of Nehemiah 4】",
"",
"11 我们的敌人且说：「趁他们不知不见，我们进入他们中间，杀他们，使工作止住。」",
"12 那靠近敌人居住的犹大人十次从各处来见我们，说：「你们必要回到我们那里。」",
"",
"——【尼希米记 4】",
],
[
"27 And Shimei had sixteen sons and six daughters; but his brethren had not many children, neither did all their family multiply, like to the children of Judah.",
"28 And they dwelt at Beer–sheba, and Moladah, and Hazar–shual,",
"",
"——【The First Book of the Chronicles 4】",
"",
"27 示每有十六个儿子，六个女儿，他弟兄的儿女不多，他们各家不如犹大族的人丁增多。",
"28 西缅人住在别是巴、摩拉大、哈萨‧书亚、",
"",
"——【历代志上 4】",
],
[
"3 Asshur shall not save us; we will not ride upon horses: neither will we say any more to the work of our hands, Ye are our gods: for in thee the fatherless findeth mercy.",
"4 I will heal their backsliding, I will love them freely: for mine anger is turned away from him.",
"5 I will be as the dew unto Israel: he shall grow as the lily, and cast forth his roots as Lebanon.",
"6 His branches shall spread, and his beauty shall be as the olive tree, and his smell as Lebanon.",
"7 They that dwell under his shadow shall return; they shall revive as the corn, and grow as the vine: the scent thereof shall be as the wine of Lebanon.",
"",
"——【Hosea 14】",
"",
"3 我们不向亚述求救，不骑埃及的马，也不再对我们手所造的说：你是我们的　神。因为孤儿在你─耶和华那里得蒙怜悯。",
"4 我必医治他们背道的病，甘心爱他们；因为我的怒气向他们转消。",
"5 我必向以色列如甘露；他必如百合花开放，如黎巴嫩的树木扎根。",
"6 他的枝条必延长；他的荣华如橄榄树；他的香气如黎巴嫩的香柏树。",
"7 曾住在他荫下的必归回，发旺如五谷，开花如葡萄树。他的香气如黎巴嫩的酒。",
"",
"——【何西阿书 14】",
],
[
"1 Who is as the wise man? and who knoweth the interpretation of a thing? a man's wisdom maketh his face to shine, and the boldness of his face shall be changed.",
"2 I counsel thee to keep the king's commandment, and that in regard of the oath of God.",
"",
"——【Ecclesiastes 8】",
"",
"1 谁如智慧人呢？谁知道事情的解释呢？人的智慧使他的脸发光，并使他脸上的暴气改变。",
"2 我劝你遵守王的命令；既指　神起誓，理当如此。",
"",
"——【传道书 8】",
],
[
"17 And the LORD hath done to him, as he spake by me: for the LORD hath rent the kingdom out of thine hand, and given it to thy neighbour, even to David:",
"18 Because thou obeyedst not the voice of the LORD, nor executedst his fierce wrath upon Amalek, therefore hath the LORD done this thing unto thee this day.",
"19 Moreover the LORD will also deliver Israel with thee into the hand of the Philistines: and to morrow shalt thou and thy sons be with me: the LORD also shall deliver the host of Israel into the hand of the Philistines.",
"20 Then Saul fell straightway all along on the earth, and was sore afraid, because of the words of Samuel: and there was no strength in him; for he had eaten no bread all the day, nor all the night.",
"21 And the woman came unto Saul, and saw that he was sore troubled, and said unto him, Behold, thine handmaid hath obeyed thy voice, and I have put my life in my hand, and have hearkened unto thy words which thou spakest unto me.",
"",
"——【The First Book of Samuel 28】",
"",
"17 耶和华照他借我说的话，已经从你手里夺去国权，赐与别人，就是大卫。",
"18 因你没有听从耶和华的命令；他恼怒亚玛力人，你没有灭绝他们，所以今日耶和华向你这样行，",
"19 并且耶和华必将你和以色列人交在非利士人的手里。明日你和你众子必与我在一处了；耶和华必将以色列的军兵交在非利士人手里。」",
"20 扫罗猛然仆倒，挺身在地，因撒母耳的话甚是惧怕；那一昼一夜没有吃什么，就毫无气力。",
"21 妇人到扫罗面前，见他极其惊恐，对他说：「婢女听从你的话，不顾惜自己的性命，遵从你所吩咐的。",
"",
"——【撒母耳记上 28】",
],
[
"8 But what went ye out for to see? A man clothed in soft raiment? behold, they that wear soft clothing are in kings' houses.",
"9 But what went ye out for to see? A prophet? yea, I say unto you, and more than a prophet.",
"10 For this is he, of whom it is written, Behold, I send my messenger before thy face, which shall prepare thy way before thee.",
"11 Verily I say unto you, Among them that are born of women there hath not risen a greater than John the Baptist: notwithstanding he that is least in the kingdom of heaven is greater than he.",
"",
"——【The Gospel According to Saint Matthew 11】",
"",
"8 你们出去到底是要看什么？要看穿细软衣服的人么？那穿细软衣服的人是在王宫里。",
"9 你们出去究竟是为什么？是要看先知么？我告诉你们，是的，他比先知大多了。",
"10 经上记着说：我要差遣我的使者在你前面预备道路，所说的就是这个人。",
"11 我实在告诉你们，凡妇人所生的，没有一个兴起来大过施洗约翰的；然而天国里最小的比他还大。",
"",
"——【马太福音 11】",
],
[
"3 Of Jeduthun: the sons of Jeduthun; Gedaliah, and Zeri, and Jeshaiah, Hashabiah, and Mattithiah, six, under the hands of their father Jeduthun, who prophesied with a harp, to give thanks and to praise the LORD.",
"4 Of Heman: the sons of Heman; Bukkiah, Mattaniah, Uzziel, Shebuel, and Jerimoth, Hananiah, Hanani, Eliathah, Giddalti, and Romamti–ezer, Joshbekashah, Mallothi, Hothir, and Mahazioth:",
"5 All these were the sons of Heman the king's seer in the words of God, to lift up the horn. And God gave to Heman fourteen sons and three daughters.",
"6 All these were under the hands of their father for song in the house of the LORD, with cymbals, psalteries, and harps, for the service of the house of God, according to the king's order to Asaph, Jeduthun, and Heman.",
"7 So the number of them, with their brethren that were instructed in the songs of the LORD, even all that were cunning, was two hundred fourscore and eight.",
"",
"——【The First Book of the Chronicles 25】",
"",
"3 耶杜顿的儿子基大利、西利、耶筛亚、哈沙比雅、玛他提雅、示每共六人，都归他们父亲耶杜顿指教，弹琴，唱歌，称谢，颂赞耶和华。",
"4 希幔的儿子布基雅、玛探雅、乌薛、细布业、耶利摩、哈拿尼雅、哈拿尼、以利亚他、基大利提、罗幔提•以谢、约施比加沙、玛罗提、何提、玛哈秀；",
"5 这都是希幔的儿子，吹角颂赞。希幔奉　神之命作王的先见。　神赐给希幔十四个儿子，三个女儿，",
"6 都归他们父亲指教，在耶和华的殿唱歌、敲钹、弹琴、鼓瑟，办　神殿的事务。亚萨、耶杜顿、希幔都是王所命定的。",
"7 他们和他们的弟兄学习颂赞耶和华；善于歌唱的共有二百八十八人。",
"",
"——【历代志上 25】",
],
[
"18 But as God is true, our word toward you was not yea and nay.",
"19 For the Son of God, Jesus Christ, who was preached among you by us, even by me and Silvanus and Timotheus, was not yea and nay, but in him was yea.",
"20 For all the promises of God in him are yea, and in him Amen, unto the glory of God by us.",
"",
"——【The Second Epistle of Paul the Apostle to the Corinthians 1】",
"",
"18 我指着信实的　神说，我们向你们所传的道，并没有是而又非的。",
"19 因为我和西拉并提摩太，在你们中间所传　神的儿子耶稣基督，总没有是而又非的，在他只有一是。",
"20 　神的应许，不论有多少，在基督都是是的。所以藉着他也都是实在（实在：原文是阿们）的，叫　神因我们得荣耀。",
"",
"——【哥林多后书 1】",
],
[
"1 And it came to pass in the eleventh year, in the third month, in the first day of the month, that the word of the LORD came unto me, saying,",
"2 Son of man, speak unto Pharaoh king of Egypt, and to his multitude; Whom art thou like in thy greatness?",
"3 Behold, the Assyrian was a cedar in Lebanon with fair branches, and with a shadowing shroud, and of an high stature; and his top was among the thick boughs.",
"4 The waters made him great, the deep set him up on high with her rivers running round about his plants, and sent out her little rivers unto all the trees of the field.",
"5 Therefore his height was exalted above all the trees of the field, and his boughs were multiplied, and his branches became long because of the multitude of waters, when he shot forth.",
"6 All the fowls of heaven made their nests in his boughs, and under his branches did all the beasts of the field bring forth their young, and under his shadow dwelt all great nations.",
"",
"——【The Book of the Prophet Ezekiel 31】",
"",
"1 十一年三月初一日，耶和华的话临到我说：",
"2 「人子啊，你要向埃及王法老和他的众人说：在威势上谁能与你相比呢？",
"3 亚述王曾如黎巴嫩中的香柏树，枝条荣美，影密如林，极其高大，树尖插入云中。",
"4 众水使它生长；深水使它长大。所栽之地有江河围流，汊出的水道延到田野诸树。",
"5 所以他高大超过田野诸树；发旺的时候，枝子繁多，因得大水之力枝条长长。",
"6 空中的飞鸟都在枝子上搭窝；田野的走兽都在枝条下生子；所有大国的人民都在它荫下居住。",
"",
"——【以西结书 31】",
],
[
"1 The Revelation of Jesus Christ, which God gave unto him, to shew unto his servants things which must shortly come to pass; and he sent and signified it by his angel unto his servant John:",
"2 Who bare record of the word of God, and of the testimony of Jesus Christ, and of all things that he saw.",
"3 Blessed is he that readeth, and they that hear the words of this prophecy, and keep those things which are written therein: for the time is at hand.",
"4 John to the seven churches which are in Asia: Grace be unto you, and peace, from him which is, and which was, and which is to come; and from the seven Spirits which are before his throne;",
"",
"——【The Revelation of Saint John the Devine 1】",
"",
"1 耶稣基督的启示，就是　神赐给他，叫他将必要快成的事指示他的众仆人。他就差遣使者晓谕他的仆人约翰。",
"2 约翰便将　神的道和耶稣基督的见证，凡自己所看见的都证明出来。",
"3 念这书上预言的和那些听见又遵守其中所记载的，都是有福的，因为日期近了。",
"4 约翰写信给亚细亚的七个教会。但愿从那昔在、今在、以后永在的　神，和他宝座前的七灵，",
"",
"——【启示录 1】",
],
[
"33 And they made their father drink wine that night: and the firstborn went in, and lay with her father; and he perceived not when she lay down, nor when she arose.",
"34 And it came to pass on the morrow, that the firstborn said unto the younger, Behold, I lay yesternight with my father: let us make him drink wine this night also; and go thou in, and lie with him, that we may preserve seed of our father.",
"35 And they made their father drink wine that night also: and the younger arose, and lay with him; and he perceived not when she lay down, nor when she arose.",
"36 Thus were both the daughters of Lot with child by their father.",
"",
"——【The First Book of Moses: Called Genesis 19】",
"",
"33 于是，那夜她们叫父亲喝酒，大女儿就进去和她父亲同寝；她几时躺下，几时起来，父亲都不知道。",
"34 第二天，大女儿对小女儿说：「我昨夜与父亲同寝。今夜我们再叫他喝酒，你可以进去与他同寝。这样，我们好从父亲存留后裔。」",
"35 于是，那夜她们又叫父亲喝酒，小女儿起来与她父亲同寝；她几时躺下，几时起来，父亲都不知道。",
"36 这样，罗得的两个女儿都从她父亲怀了孕。",
"",
"——【创世记 19】",
],
[
"13 Even after a certain rate every day, offering according to the commandment of Moses, on the sabbaths, and on the new moons, and on the solemn feasts, three times in the year, even in the feast of unleavened bread, and in the feast of weeks, and in the feast of tabernacles.",
"14 And he appointed, according to the order of David his father, the courses of the priests to their service, and the Levites to their charges, to praise and minister before the priests, as the duty of every day required: the porters also by their courses at every gate: for so had David the man of God commanded.",
"15 And they departed not from the commandment of the king unto the priests and Levites concerning any matter, or concerning the treasures.",
"16 Now all the work of Solomon was prepared unto the day of the foundation of the house of the LORD, and until it was finished. So the house of the LORD was perfected.",
"17 Then went Solomon to Ezion–geber, and to Eloth, at the sea side in the land of Edom.",
"",
"——【The Second Book of the Chronicles 8】",
"",
"13 又遵着摩西的吩咐在安息日、月朔，并一年三节，就是除酵节、七七节、住棚节，献每日所当献的祭。",
"14 所罗门照着他父大卫所定的例，派定祭司的班次，使他们各供己事，又使利未人各尽其职，赞美耶和华，在祭司面前做每日所当做的；又派守门的按着班次看守各门，因为神人大卫是这样吩咐的。",
"15 王所吩咐众祭司和利未人的，无论是管府库或办别的事，他们都不违背。",
"16 所罗门建造耶和华的殿，从立根基直到成功的日子，工料俱备。这样，耶和华的殿全然完毕。",
"17 那时，所罗门往以东地靠海的以旬‧迦别和以禄去。",
"",
"——【历代志下 8】",
],
[
"19 Now I tell you before it come, that, when it is come to pass, ye may believe that I am he.",
"20 Verily, verily, I say unto you, He that receiveth whomsoever I send receiveth me; and he that receiveth me receiveth him that sent me.",
"21 When Jesus had thus said, he was troubled in spirit, and testified, and said, Verily, verily, I say unto you, that one of you shall betray me.",
"22 Then the disciples looked one on another, doubting of whom he spake.",
"23 Now there was leaning on Jesus' bosom one of his disciples, whom Jesus loved.",
"",
"——【The Gospel According to Saint John 13】",
"",
"19 如今事情还没有成就，我要先告诉你们，叫你们到事情成就的时候可以信我是基督。",
"20 我实实在在的告诉你们，有人接待我所差遣的，就是接待我；接待我，就是接待那差遣我的。",
"21 耶稣说了这话，心里忧愁，就明说：我实实在在的告诉你们，你们中间有一个人要卖我了。",
"22 门徒彼此对看，猜不透所说的是谁。",
"23 有一个门徒，是耶稣所爱的，侧身挨近耶稣的怀里。",
"",
"——【约翰福音 13】",
],
[
"4 A wicked and adulterous generation seeketh after a sign; and there shall no sign be given unto it, but the sign of the prophet Jonas. And he left them, and departed.",
"5 And when his disciples were come to the other side, they had forgotten to take bread.",
"6 Then Jesus said unto them, Take heed and beware of the leaven of the Pharisees and of the Sadducees.",
"7 And they reasoned among themselves, saying, It is because we have taken no bread.",
"8 Which when Jesus perceived, he said unto them, O ye of little faith, why reason ye among yourselves, because ye have brought no bread?",
"",
"——【The Gospel According to Saint Matthew 16】",
"",
"4 一个邪恶淫乱的世代求神迹，除了约拿的神迹以外，再没有神迹给他看。耶稣就离开他们去了。",
"5 门徒渡到那边去，忘了带饼。",
"6 耶稣对他们说：你们要谨慎，防备法利赛人和撒都该人的酵。",
"7 门徒彼此议论说：这是因为我们没有带饼吧。",
"8 耶稣看出来，就说：你们这小信的人，为什么因为没有饼彼此议论呢？",
"",
"——【马太福音 16】",
],
[
"26 This is the purpose that is purposed upon the whole earth: and this is the hand that is stretched out upon all the nations.",
"27 For the LORD of hosts hath purposed, and who shall disannul it? and his hand is stretched out, and who shall turn it back?",
"28 In the year that king Ahaz died was this burden.",
"29 Rejoice not thou, whole Palestina, because the rod of him that smote thee is broken: for out of the serpent's root shall come forth a cockatrice, and his fruit shall be a fiery flying serpent.",
"30 And the firstborn of the poor shall feed, and the needy shall lie down in safety: and I will kill thy root with famine, and he shall slay thy remnant.",
"31 Howl, O gate; cry, O city; thou, whole Palestina, art dissolved: for there shall come from the north a smoke, and none shall be alone in his appointed times.",
"",
"——【The Book of the Prophet Isaiah 14】",
"",
"26 这是向全地所定的旨意；这是向万国所伸出的手。",
"27 万军之耶和华既然定意，谁能废弃呢？他的手已经伸出，谁能转回呢？",
"28 亚哈斯王崩的那年，就有以下的默示：",
"29 非利士全地啊，不要因击打你的杖折断就喜乐。因为从蛇的根必生出毒蛇；牠所生的是火焰的飞龙。",
"30 贫寒人的长子必有所食；穷乏人必安然躺卧。我必以饥荒治死你的根；你所余剩的人必被杀戮。",
"31 门哪，应当哀号！城啊，应当呼喊！非利士全地啊，你都消化了！因为有烟从北方出来，他行伍中并无乱队的。",
"",
"——【以赛亚书 14】",
],
[
"1 Be merciful unto me, O God, be merciful unto me: for my soul trusteth in thee: yea, in the shadow of thy wings will I make my refuge, until these calamities be overpast.",
"2 I will cry unto God most high; unto God that performeth all things for me.",
"3 He shall send from heaven, and save me from the reproach of him that would swallow me up. Selah. God shall send forth his mercy and his truth.",
"",
"——【The Book of Psalms 57】",
"",
"1 （大卫逃避扫罗，藏在洞里。那时，他作这金诗，交与伶长。调用休要毁坏。）　神啊，求你怜悯我，怜悯我！因为我的心投靠你。我要投靠在你翅膀的荫下，等到灾害过去。",
"2 我要求告至高的　神，就是为我成全诸事的　神。",
"3 那要吞我的人辱骂我的时候，　神从天上必施恩救我，也必向我发出慈爱和诚实。",
"",
"——【诗篇 57】",
],
[
"2 Pass ye unto Calneh, and see; and from thence go ye to Hamath the great: then go down to Gath of the Philistines: be they better than these kingdoms? or their border greater than your border?",
"3 Ye that put far away the evil day, and cause the seat of violence to come near;",
"",
"——【Amos 6】",
"",
"2 你们要过到甲尼察看，从那里往大城哈马去，又下到非利士人的迦特。看那些比你们的国还强吗？境界比你们的境界还宽吗？",
"3 你们以为降祸的日子还远，坐在位上尽行强暴（或译：行强暴使审判临近）。",
"",
"——【阿摩司书 6】",
],
[
"9 He couched, he lay down as a lion, and as a great lion: who shall stir him up? Blessed is he that blesseth thee, and cursed is he that curseth thee.",
"10 And Balak's anger was kindled against Balaam, and he smote his hands together: and Balak said unto Balaam, I called thee to curse mine enemies, and, behold, thou hast altogether blessed them these three times.",
"11 Therefore now flee thou to thy place: I thought to promote thee unto great honour; but, lo, the LORD hath kept thee back from honour.",
"12 And Balaam said unto Balak, Spake I not also to thy messengers which thou sentest unto me, saying,",
"13 If Balak would give me his house full of silver and gold, I cannot go beyond the commandment of the LORD, to do either good or bad of mine own mind; but what the LORD saith, that will I speak?",
"14 And now, behold, I go unto my people: come therefore, and I will advertise thee what this people shall do to thy people in the latter days.",
"",
"——【The Fourth Book of Moses: Called Numbers 24】",
"",
"9 他蹲如公狮，卧如母狮，谁敢惹他？凡给你祝福的，愿他蒙福；凡咒诅你的，愿他受咒诅。",
"10 巴勒向巴兰生气，就拍起手来，对巴兰说：「我召你来为我咒诅仇敌，不料，你这三次竟为他们祝福。",
"11 如今你快回本地去吧！我想使你得大尊荣，耶和华却阻止你不得尊荣。」",
"12 巴兰对巴勒说：「我岂不是对你所差遣到我那里的使者说：",
"13 『巴勒就是将他满屋的金银给我，我也不得越过耶和华的命，凭自己的心意行好行歹。耶和华说什么，我就要说什么？』",
"14 「现在我要回本族去。你来，我告诉你这民日后要怎样待你的民。」",
"",
"——【民数记 24】",
],
[
"11 Take, I pray thee, my blessing that is brought to thee; because God hath dealt graciously with me, and because I have enough. And he urged him, and he took it.",
"12 And he said, Let us take our journey, and let us go, and I will go before thee.",
"13 And he said unto him, My lord knoweth that the children are tender, and the flocks and herds with young are with me: and if men should overdrive them one day, all the flock will die.",
"",
"——【The First Book of Moses: Called Genesis 33】",
"",
"11 求你收下我带来给你的礼物；因为　神恩待我，使我充足。」雅各再三地求他，他才收下了。",
"12 以扫说：「我们可以起身前往，我在你前头走。」",
"13 雅各对他说：「我主知道孩子们年幼娇嫩，牛羊也正在乳养的时候，若是催赶一天，群畜都必死了。",
"",
"——【创世记 33】",
],
[
"5 It shall be a place for the spreading of nets in the midst of the sea: for I have spoken it, saith the Lord GOD: and it shall become a spoil to the nations.",
"6 And her daughters which are in the field shall be slain by the sword; and they shall know that I am the LORD.",
"",
"——【The Book of the Prophet Ezekiel 26】",
"",
"5 她必在海中作晒网的地方，也必成为列国的掳物。这是主耶和华说的。",
"6 属推罗城邑的居民（原文是田间的众女；八节同）必被刀剑杀灭，他们就知道我是耶和华。",
"",
"——【以西结书 26】",
],
[
"1 O LORD, thou hast searched me, and known me.",
"2 Thou knowest my downsitting and mine uprising, thou understandest my thought afar off.",
"3 Thou compassest my path and my lying down, and art acquainted with all my ways.",
"",
"——【The Book of Psalms 139】",
"",
"1 （大卫的诗，交与伶长。）耶和华啊，你已经鉴察我，认识我。",
"2 我坐下，我起来，你都晓得；你从远处知道我的意念。",
"3 我行路，我躺卧，你都细察；你也深知我一切所行的。",
"",
"——【诗篇 139】",
],
[
"21 If so be that ye have heard him, and have been taught by him, as the truth is in Jesus:",
"22 That ye put off concerning the former conversation the old man, which is corrupt according to the deceitful lusts;",
"",
"——【The Epistle of Paul the Apostle to the Ephesians 4】",
"",
"21 如果你们听过他的道，领了他的教，学了他的真理，",
"22 就要脱去你们从前行为上的旧人，这旧人是因私欲的迷惑渐渐变坏的；",
"",
"——【以弗所书 4】",
],
];
