var quote31_global=[
[
"			 				从山上下来，崇祯殉国的地方依然是那么半死的槐树。据说树上原有一条链子锁着，庚子联军入京以后就不见了。现在那枯槁的部分，还有一个大洞，当时的链痕还隐约可以看见。义和团运动的结果，从解放这棵树发展到解放这民族。这是一件多么可以发人深思的对象呢？山后的柏树发出幽恬的香气，好像是对于这地方的永远供物。",
"—— 《许地山经典全集》 (line 508)",
],
[
"二　春",
"（一齐向赵的屋子跑，立在窗外）怎样啦？怎样啦？",
"小　妞",
"大　妈　只顾了穷忙，把他老人家忘了。二春，先作点开水！",
"二　春　（往回跑）我找汆子去。（入屋中）",
"四　嫂　（向屋内）赵大爷，您要点什么呀？",
"疯　子　丁四嫂，你很忙，伺候病人我在行。（跑到赵的窗外）赵大爷，您好点吧？",
"—— 《茶馆》 (line 1267 - 1273)",
],
[
"周有玉版，纣令胶鬲索之，文王不予；费仲来求，因予之。是胶鬲贤而费仲无道也。周恶贤者之得志也，故予费仲。文王举太公于渭滨者，贵之也；而资费仲玉版者，是爱之也。故曰：“不贵其师，不爱其资，虽知大迷，是谓要妙。”",
"第21章说林上",
"汤以伐桀，而恐天下言己为贪也，因乃让天下于务光。而恐务光之受之也，乃使人说务光曰：“汤杀君而欲传恶声于子，故让天下于子。”务光因自投于河。",
"—— 《韩非子》 (line 234 - 236)",
],
[
"朱樱斗帐掩流苏，",
"通犀还解辟寒无。",
"诉衷情",
"夜来沉醉卸装迟，",
"梅萼插残枝。",
"酒醒熏破春睡，",
"梦远不成归。",
"人悄悄，",
"月依依，",
"翠帘垂。",
"更挼残蕊，",
"更撚余香，",
"更得些时。",
"浪淘沙",
"—— 《李清照集》 (line 371 - 384)",
],
[
"At night sometimes, when the English patient is asleep or even after she has read alone outside his door for a while, she goes looking for Caravaggio. He will be in the garden lying along the stone rim of the fountain looking up at stars, or she will come across him on a lower terrace. In this early-summer weather he finds it difficult to stay indoors at night. Most of the time he is on the roof beside the broken chimney, but he slips down silently when he sees her figure cross the terrace looking for him. She will find him near the headless statue of a count, upon whose stub of neck one of the local cats likes to sit, solemn and drooling when humans appear. She is always made to feel that she is the one who has found him, this man who knows darkness, who when drunk used to claim he was brought up by a family of owls.",
"—— 《The English Patient (Vintage International)(Michael Ondaatje)》 (line 248)",
],
[
"He was living in an old town, full of intelligence and vitality, but also full of patrician pride, self-contained, and self-satisfied. There was a bourgeois aristocracy with a taste for work and the higher culture, but narrow and pietistic, who were calmly convinced of their own superiority and the superiority of their city, and quite content to live in family isolation. There were enormous families with vast ramifications. Each family had its day for a general gathering of the clan. They were hardly at all open to the outside world. All these great houses, with fortunes generations old, felt no need of showing their wealth. They knew each other, and that was enough: the opinion of others was a thing of no consequence. There were millionaires dressed like humble shopkeepers, talking their raucous dialect with its pungent expressions, going conscientiously to their offices, every day of their lives, even at an age when the most industrious of men will grant themselves the right to rest. Their wives prided themselves on their domestic skill. No dowry was given to the daughters. Rich men let their sons in their turn go through the same hard apprenticeship that they themselves had served. They practised strict economy in their daily lives. But they made a noble use of their fortune in collecting works of art, picture galleries, and in social work: they were forever giving enormous sums, nearly always anonymously, to found charities and to enrich the museums. They were a mixture of greatness and absurdity, both of another age. This little world, for which the rest of the world seemed not to exist—(although its members knew it thoroughly through their business, and their distant relationships, and the long and extended voyages which they forced their sons to take,)—this little world, for which fame and celebrity in another land only were esteemed from the moment when they were welcomed and recognized by itself,—practised the severest discipline upon itself. Every member of it kept a watch upon himself and upon the rest. The result of all this was a collective conscience which masked all individual differences (more marked than elsewhere among the robust personalities of the place) under the veil of religious and moral uniformity. Everybody practised it, everybody believed in it. Not a single soul doubted it or would admit of doubt. It were impossible to know what took place in the depths of souls which were the more hermetically sealed against prying eyes inasmuch as they knew that they were surrounded by a narrow scrutiny, and that every man took upon himself the right to examine into the conscience of other men. It was said that even those who had left the country and thought themselves emancipated—as soon as they set foot in it again were dominated by the traditions, the habits, the atmosphere of the town: even the most skeptical were at once forced to practise and to believe. Not to believe would have seemed to them an offense against Nature. Not to believe was the mark of an inferior caste, a sign of bad breeding. It was never admitted that a man of their world could possibly be absolved of his religious duties. If a man did not practise their religion, he was at once unclassed, and all doors were closed to him.",
"—— 《Jean-Christophe Journey's End, by Romain Rolland》 (line 1500)",
],
[
"	“金曜Entertainment”是富士电视台在周五晚间21点开播的两小时电视剧时段，与其他三大民间电视台不同，富士台并没有将其单纯地用于播出推理作品，而是间或播出纪实类节目和综艺节目，与周六晚间21点的电视剧时段也多有联动。",
"	这一时段正式创立于1993年4月，至2006年9月告一段落。前身可以追溯到1984年10月开播的“金曜女性Drama SP”，其后历经“The Dra-matic 	Night”“男人和女人的悬疑”“金曜Drama Theatre”等多次改版，成为富士台首屈一指的推理剧播映平台。",
"—— 《知日·了不起的推理》 (line 1402 - 1403)",
],
[
"食防难化常思节，衣必宜温莫懒增。",
"谁道山翁拙于用，也能康济自家身。",
"注释",
"注862　程明道：程颢（1032 - 1085），字伯淳，河南府（今洛阳）人，北宋诗人、理学家。世称其“修养有道，和粹之气，盎然于面”，一生不见急厉之色。时人称其为明道先生。与其弟程颐并称“二程”。",
"—— 《浮生六记(沈复)》 (line 3026 - 3029)",
],
[
"痴心妄想居周室，斩首周岐谢将台。",
"话说飞廉与恶来共议弃纣归周不表。",
"且说纣王入内宫，有妲己、胡喜媚、王贵人三个前来接驾。纣王一见三人，不觉心头酸楚，语言悲咽，对妲己曰：“朕每以姬发、姜尚小视，不曾着心料理，岂知彼纠合天下诸侯，会兵于此。今日朕亲与姜尚会兵，势孤莫敌，虽然斩了他数员反臣，倒被姜文焕这厮鞭伤后背，致鲁仁杰阵亡，雷鵾兄弟死节。朕静坐自思，料此不能久守，亡在旦夕。想成汤传位二十八世，今一旦有失，朕将何面目见先帝于在天也！朕已追悔无及，只三位美人与朕久处，一旦分离，朕心不忍，为之奈何？倘武王兵入内庭，朕岂肯为彼所掳，朕当先期自尽。但朕绝之后，卿等必归姬发。只朕与卿等一番恩爱，竟如此结局，言之痛心！”道罢，泪如雨下。三妖闻纣王之言，齐齐跪下，泣对纣王曰：“妾等蒙陛下眷爱，镂心刻骨，没世难忘。今不幸遭此离乱，陛下欲舍妾身何往？”纣王泣曰：“朕恐被姜尚所掳，有辱我万乘之尊。朕今别你三人，自有去向。”妲己俯伏纣王膝上，泣曰：“妾听陛下之言，心如刀割。陛下何遽忍舍妾等而他往耶？”遂扯住纣王袍服，泪流满面，柔声娇语，哭在一处，甚难割舍。纣王亦无可奈何，遂命左右治酒，与三美人共饮作别。纣王把盏，作诗一首，歌之以劝酒，诗曰：",
"—— 《封神演义》 (line 3733 - 3735)",
],
[
"冲虚低声道：“任我行应变神速，行动如电，椅中虽有机簧，他只要一觉不妥，立即跃起，须伤他不到。这张椅子脚下装有药引，通到一堆火药之中。”",
"他此言一出，令狐冲和少林诸僧均是脸上变色。方证口念佛号：“阿弥陀佛！”",
"冲虚又道：“这机簧的好处，在于有人随便一坐，并无事故，一定要坐到一炷香时分，药引这才引发。那任我行为人多疑，又极精细，突见恒山见性峰上有这样一张椅子，一定不会立即就坐，定是派手下人先坐上去试试。这椅套上既有金龙捧日，又有什么‘千秋万载，一统江湖’的字样，魔教中的头目自然谁也不敢久坐，而任我行一坐上去之后，又一定舍不得下来。”令狐冲道：“道长果然设想周到。”冲虚道：“清虚师弟又另有布置，倘若任我行竟是不坐，叫人拿下椅套、椅垫，甚或拆开椅子瞧瞧，只要一拆动，一样的引发机关。成高师侄这次带到宝山来的，共有二万斤炸药。毁坏宝山灵景，恐怕是在所不免的了。”",
"—— 《笑傲江湖(修订版)(金庸)》 (line 8503 - 8505)",
],
[
"著者：毛泽东",
"整顿党的作风（背景资料）",
"这是毛泽东1942年2月1日在延安中共中央党校开学典礼上的演说，全文约11600字。原题为《整顿学风党风文风》，曾刊载于1942年4月27日延安《解放日报》、1942年5月5日《晋冀日报》、1942年5月17日《新华日报》。收入1942年4月延安解放社出版的《整顿三风文献》、1942年7月中共中央书记处编印的《抗战以来重要文件汇集》、1943年10月编印的《两条路线》（下）。1947年3月、1948年5月、1948年分别收入中共晋察冀中央局、东北书店、中共晋冀鲁豫中央局编印的《毛泽东选集》。1953年2月出版的《毛泽东选集》第3卷、1986年8月出版的《毛泽东著作选读》（下册）也收入该文。该文的单行本有50多种。其中汉文版10种，少数民族文版10多种，外文版30多种，还有盲文版1种。",
"—— 《整顿党的作风(毛泽东)》 (line 72 - 74)",
],
[
"乡人无意逢殃",
"话说老董说到此处，老残问道：“那不仍就把这人家爷儿三个都站死了吗？”老董道：“可不是呢！那吴举人到府衙门请见的时候，他女儿，于学礼的媳妇，也跟到衙门口，借了延生堂生药铺里坐下，打听消息。听说府里大人不见他父亲，已到衙门里头求师爷去了。吴氏便知事体不好，立刻叫人把三班头儿请来。那头儿姓陈，名仁美，是曹州府著名的能吏。吴氏将他请来，把被屈的情形告诉了一遍，央他从中设法。陈仁美听了，把头连摇几摇，说：‘这是强盗报仇，做的圈套。你们家又有上夜的，又有保家的，怎么就让强盗把赃物送到家中屋子里还不知道？也算得个特等马糊了！’吴氏就从手上抹下一副金镯子，递给陈头，说：‘无论怎样，总要头儿费心！但能救得三人性命，无论花多少钱都愿意！不怕将田地房产卖尽，咱一家子要饭吃去都使得！’",
"—— 《老残游记(刘鹗)》 (line 98 - 99)",
],
[
"过了些日子，老厨子又说：",
"“老胡家要‘休妻’了，要‘休’了那小妖怪。”",
"祖父以为老胡家那人家不大好。",
"祖父说：“二月让他搬家。把人家的孩子快捉弄死了，又不要了。”",
"九",
"还没有到二月，那黑忽忽的，笑呵呵的小团圆媳妇就死了。是一个大清早晨，老胡家的大儿子，那个黄脸大眼睛的车老板子就来了。一见了祖父，他就双手举在胸前作了一个揖。",
"—— 《呼兰河传》 (line 1444 - 1449)",
],
[
"\"Well, everything is going to ruin! Robbery in the law courts, in the army nothing but flogging, drilling, and Military Settlements;<sup>7</sup> the people are tortured, enlightenment is suppressed. All that is young and honest is crushed! Everyone sees that this cannot go on. Everything is strained to such a degree that it will certainly break,\" said Pierre (as those who examine the actions of any government have always said since governments began).<sup>8</sup> \"I told them just one thing in Petersburg.\"",
"—— 《War and Peace(graf Leo Tolstoy)》 (line 12109)",
],
[
"七　统筹兼顾、适当安排",
"八　关于百花齐放、百家争鸣、长期共存、互相监督",
"九　关于少数人闹事问题",
"十　坏事能否变成好事？",
"十一　关于节约",
"十二　中国工业化的道路",
"关于正确处理人民内部矛盾的问题（不同版本封面）",
"关于正确处理人民内部矛盾的问题（背景资料）",
"关于正确处理人民内部矛盾的问题（旧版）",
"—— 《关于正确处理人民内部矛盾的问题(毛泽东)》 (line 11 - 19)",
],
[
"智光道：“后来你自己知道了。你长到七岁之时，在少室山中采栗，遇到野狼。有一位少林寺的僧人将你救了下来，杀死恶狼，给你治伤，自后每天便来传你武功，是也不是？”",
"乔峰道：“是！原来这件事你也知道。”那少林僧玄苦大师传他武功之时，叫他决计不可向任何人说起，是以江湖上只知他是丐帮汪帮主的嫡传弟子，谁也不知他和少林寺实有极深的渊源。",
"—— 《金庸作品集：天龙八部（修订版）(全5册)(金庸)》 (line 3338 - 3339)",
],
[
"\"Good,\" said Lothair. \"I thought so too. He will succeed, then?\"",
"\"Yes, I think so. He has power,\"",
"\"Very good,\" said Lothair with the magnificent logic of the strong who are only interested in the strong, \"we must help him.\"",
"—— 《Jean-Christophe, Volume I, by Romain Rolland》 (line 2350 - 2352)",
],
[
"The rest of the team hung back to talk to each other as usual at the end of practice, but Harry headed straight back to the Gryffindor common room, where he found Ron and Hermione playing chess. Chess was the only thing Hermione ever lost at, something Harry and Ron thought was very good for her.",
"—— 《Harry Potter and the Philosopher's Stone》 (line 2157)",
],
[
"◎ 以发展强村",
"◎ 靠建设美村",
"◎ 抓反哺富村",
"◎ 促改革活村",
"◎ 讲文明兴村",
"◎ 建法治安村",
"◎ 强班子带村",
"◎ “四位一体”的辩证统一",
"◎ 法治：新形势的新要求",
"◎ 市场经济必然是法治经济",
"◎ 和谐社会本质上是法治社会",
"—— 《之江新语(习近平)》 (line 197 - 207)",
],
[
"“明天你在家吗？”",
"“Qua！”",
"“什么？”",
"“啊，就是说在家。”",
"基本上就像这个样子。",
"从河童国回来正好一年之后，我因为一件事业的失败……",
"（当他说到这里时，S博士马上提醒他：“别提那件事情了！”据S博士讲，他一说起这件事情，就变得异常暴躁，让看护者束手无策。）",
"那就罢了，不说它了。可是，正因为事业上的失败，我又有了想回到河童之国的念头。是的，不是“想去”，而是“想回去”！河童国对我来说就像自己的故乡一样。",
"—— 《河童(芥川龙之介)》 (line 437 - 444)",
],
[
"大学的分裂",
"在康奈尔大学的枪击事件后，这一切变得再清楚不过，而且随着这所大学的分裂，我也有机会对它的构造有所了解。总的来说，没有哪个学科——只有个人——对学术自由和学术诚信受到的攻击做出了很好的反应，但各个学科的反应却各具特色。专业学院——工程、家政、产业与劳工关系以及农业——的教员干脆回到家里闭门不出。（法学院的一些教授确实表达了义愤，其中一部分人最后还公开声明支持撤换校长。）人们一般认为这些院系是保守的，但他们只是不想找麻烦，他们不认为那是他们应当参加的战斗。黑人学生的怨言不是针对他们；无论发生怎样的思想变化，都不会触动他们。尽管人人抱怨学科太多导致大学失去重心，不能平衡发展，但大家都很清楚文理学院发挥的作用，其他的学院从属于它们，它们是学问和声望的中心。这种古老的秩序大部分一直被保存着。在康奈尔，挑战正是针对文理学院，就像整个20世纪60年代其他大学的情形一样。因此，自然科学、社会科学和人文科学都遇到了麻烦，它们被要求改变教学内容和标准，消除学生们“感觉到的”精英主义、种族主义和性别歧视。学者的共同体被证明为不是共同体。在捍卫追求真理的过程中不存在同舟共济。",
"—— 《美国精神的封闭 ([美]艾伦·布卢姆)》 (line 675 - 676)",
],
[
"夏，四月，梁孝王薨。窦太后闻之，哭极哀，不食，曰：“帝果杀吾子！”帝哀惧，不知所为；与长公主计之，乃分梁为五国，尽立孝王男五人为王：买为梁王，明为济川王，彭离为济东王，定为山阳王，不识为济阴王；女五人皆食汤沐邑。奏之太后，太后乃说，为帝加一餐。孝王未死时，财以巨万计，及死，藏府余黄金尚四十余万斤，他物称是。",
"上既减笞法，笞者犹不全；乃更减笞三百曰二百，笞二百曰一百。又定棰令：棰长五尺，其本大一寸，竹也；末薄半寸，皆平其节。当笞者笞臀；毕一罪，乃更人。自是笞者得全。然死刑既重而生刑又轻，民易犯之。",
"—— 《文白对照资治通鉴精选本：全6册（套装6册）(张宏儒)》 (line 1481 - 1482)",
],
[
"	其次，关于所谓的“茶道”开山鼻祖村田珠光，其身世也一直是个谜，著名的日本历史学家、茶道研究家永岛福太郎先生终其一生也未能用史料来确证这个人物的事迹。而且，就连“茶道”一词开始见诸日本的相关文献，也都是17世纪中后期的事了。",
"	日本茶道的特色在于它的时空观。千利休之孙千宗旦，通过创建“又隐”茶室，再现了千利休的四张半榻榻米茶室的风貌，正保三年（1646年），作为侘茶的终极境界之相，又在宅邸内建了一个只有一又四分之三榻榻米大小的茶室“今日庵”，也就是说，想要建比“今日庵”再小的茶室已经不可能了。宗旦以极致之美，展现和继承了千利休的道统。因此，也有茶道研究学者据此指出，千利休之孙千宗旦才是日本茶道真正的集大成者。",
"—— 《知日·日本禅》 (line 664 - 665)",
],
[
"凡人都要死。皇帝是人，皇帝万岁。",
"还有：",
"人都要死，皇帝是人，皇帝也会死。",
"这两种说法王二都接受，你看他还有救吗？很明显，这个世界里存在着两个体系，一个来自生存的必要，一个来自存在本身，于是乎对每一个问题同时存在两个答案。这就叫虚伪，我那篇论文题目就叫《虚伪论》。",
"—— 《黄金时代》 (line 436 - 439)",
],
[
"注170 苏文：“传统、改革与革命：1917年俄国革命再认识”，载《二十一世纪》总第43期，香港中文大学中国文化研究所1997年10月刊。",
"注171 1921年列宁曾用新经济政策应付战时危机，俄国近一亿农民形成2500万个家庭农场。这时，村社是建立在家庭农场之上的，但并不一定受苏维埃控制。在二十世纪二十年代末的经济危机中，苏联农业受到巨大打击。苏联在二十世纪三十年代实行农业集体化，打击富农，将家庭农场组成的村社转变为国家控制下的集体农庄。",
"—— 《历史的巨镜(金观涛)》 (line 858 - 859)",
],
[
"裳裳者华，其叶湑兮。我覯之子，我心写兮。我心写兮，是以有誉处兮。",
"裳裳者华，芸其黄矣。我覯之子，维其有章矣。维其有章矣，是以有庆矣。",
"裳裳者华，或黄或白。我覯之子，乘其四骆。乘其四骆，六辔沃若。",
"左之左之，君子宜之。右之右之，君子有之。维其有之，是以似之。",
"桑扈",
"—— 《诗经》 (line 1042 - 1046)",
],
[
"一",
"我是史铁生——很小的时候我就觉得这话有点怪，好像我除了是我还可以是别的什么。这感觉一直不能消灭，独处时犹为挥之不去，终于想懂：史铁生是别人眼中的我，我并非全是史铁生。",
"多数情况下，我被史铁生减化和美化着。减化在所难免。美化或出于他人的善意，或出于我的伪装，还可能出于某种文体的积习——中国人喜爱赞歌。因而史铁生以外，还有着更为丰富、更为浑沌的我。这样的我，连我也常看他是个谜团。我肯定他在，但要把他全部捉拿归案却非易事。总之，他远非坐在轮椅上、边缘清晰齐整的那一个中年男人。白昼有一种魔力，常使人为了一个姓名的牵挂而拘谨、犹豫，甚至于慌不择路。一俟白昼的魔法遁去，夜的自由到来，姓名脱落为一张扁平的画皮，剩下的东西才渐渐与我重合，虽似朦胧缥缈了，却真实起来。这无论对于独处，还是对于写作，都是必要的心理环境。",
"—— 《病隙碎笔》 (line 222 - 224)",
],
[
"Randolph，John，of Roanoke，Virginian leader 伦道夫，约翰，罗诺克的，弗吉尼亚领袖",
"Rationalism 理性主义",
"Ravenna，Italian city 拉文纳，意大利城市",
"Realists，medieval 唯实论者，中世纪的",
"Reason 理性",
"—— 《美国秩序的根基(拉塞尔·柯克)》 (line 3582 - 3586)",
],
[
"1967年·25岁·男\B市作家协会干部",
"托李敏送给毛主席的生日礼物——在两种崇拜之间痛苦的抉择——一连十天参加他的批斗会——结婚之夜抱头痛哭——他是从五楼窗户跳下去的——竟然是革命样板戏救我一命——逃离魔掌——崇拜的毁灭和毁灭的崇拜",
"上部分：崇拜的痛苦",
"一",
"—— 《一百个人的十年(冯骥才)》 (line 145 - 148)",
],
[
"豆芽兵们不敢动了。",
"“退出去！我数一二三。到三时你们不退出去，我就杀了她！”宰相得寸进尺。",
"“一——二——”宰相大声喊着。",
"豆芽兵们缓缓地向后退去。",
"“啊——”宰相大叫一声，倒在地上，死了。",
"一只白蚁卫士从他背后刺了一刀。",
"豆芽兵们一拥而上，俘虏了蚁后和文武百官。鲁西西得救了。",
"—— 《皮皮鲁传+鲁西西传+大灰狼罗克传+舒克贝塔传》 (line 5178 - 5184)",
],
[
"许多事例都表明，重新得到和发展自我都具有充足的可能性，就算在最初的时候，这些可能性有着无法预知的力量。假如真我遭受了重创，那这个人就失去了自身力量的中心，从而受控于内部或者外界的其他力量。他或许会强迫自己变成一个机械化的人，以对自己周边的环境进行适应。他或许会发觉，对于别人来说，自己生命的存在纯粹是有益的，尽管自己内部缺少任何力量的中心，这必然会对他发挥能力造成阻碍，不过从社会价值的角度来讲，他依然是能发挥作用的。对于内部的指挥官能，他或许已经彻底失去了；或四处飘荡着，却毫无目的；或彻底受控于神经症倾向；正如在探讨过于“成功”的神经症倾向时所提及的那般。他已经慢慢创建的有关他本人的夸大形象或许彻底左右了他的情感、思想与行为：他并不是因为自己真正感觉到自己的形象，所以才怀有怜悯心，而是因为怜悯心仅仅是他形象的一部分。他的形象需要一些特别的“朋友”或者“兴趣”，所以他将会具备这些。",
"—— 《自我分析(卡伦·霍尼)》 (line 659)",
],
];
