var quote31_global=[
[
"太阳·大札撒",
"（残稿）",
"1988",
"抒情诗<sup>(1)</sup>",
"一",
"八月的日子就要来到",
"我的镰刀斜插在腰上",
"我抱起了庄稼的尸体",
"许多闪光的乳头在稻草秆上",
"我让乳房竖起在我嘴上",
"乳房在山上飞过，割倒了庄稼",
"山顶洞中只有酒、粮食与阴部",
"用火烤着一只雄壮的公兽",
"—— 《海子诗全集》 (line 10798 - 10810)",
],
[
"第十六卷　小夫人金钱赠年少",
"谁言今古事难穷？大抵荣枯总是空。算得生前随分过，争如云外指溟鸿。",
"暗添雪色眉根白，旋落花光脸上红。惆怅凄凉两回首，暮林萧索起悲风。",
"这八句诗，乃西川成都府华阳县王处厚，年纪将及六旬，把镜照面，见须发有几根白的，有感而作。世上之物，少则有壮，壮则有老，古之常理，人人都免不得的。原来诸物都是先白后黑，惟有髭须却是先黑后白。又有戴花刘使君，对镜中见这头发斑白，曾作《醉亭楼》词：",
"—— 《警世通言(冯梦龙)》 (line 570 - 573)",
],
[
"I am not the last boy in the school. I have risen in a few months, over several heads. But the first boy seems to me a mighty creature, dwelling afar off, whose giddy height is unattainable. Agnes says ‘No,’ but I say ‘Yes,’ and tell her that she little thinks what stores of knowledge have been mastered by the wonderful Being, at whose place she thinks I, even I, weak aspirant, may arrive in time. He is not my private friend and public patron, as Steerforth was, but I hold him in a reverential respect. I chiefly wonder what he’ll be, when he leaves Doctor Strong’s, and what mankind will do to maintain any place against him.",
"—— 《David Copperfield(Charles Dickens)》 (line 2170)",
],
[
"The construction guy indicated the tight squeeze, made worse by the fleet of cop cars swarming the scene. Then he smirked at Blake.",
"“Where can I move it?”",
"—— 《大电影双语阅读.蝙蝠侠：黑暗骑士崛起The Dark Knight Rises(华纳兄弟娱乐公司)》 (line 1048 - 1049)",
],
[
"罗汉大爷说：“弟兄们，有话好说，有话好说。”",
"大个子伪军说：“老畜生，滚到一边去。”",
"罗汉大爷说：“这是东家的牲口，不能拉。”",
"伪军说：“再吵嚷就毙了你个小舅子！”",
"日本兵端着枪，像泥神一样。",
"奶奶和我父亲一进院，罗汉大爷就说：“他们要拉咱的骡子。”",
"奶奶说：“先生，我们是良民。”",
"—— 《红高粱(莫言)》 (line 58 - 64)",
],
[
"如何云无情，忽尔横阻断！",
"译二",
"美酒神山三轮山，",
"我要一路仔细看。",
"奈良山路曲曲弯，",
"我要曲曲回头盼；",
"直到山中不见影，",
"直到拐弯几万千。",
"如何云天太无情，",
"把个山容生遮断！",
"反歌",
"译一",
"云但有情何此忍，三轮遮绝不容看。",
"—— 《万叶集 下》 (line 408 - 420)",
],
[
"“我究竟做了什么？”",
"二十一",
"“我无意打扰你。”墨菲擦掉眼泪时，背后有人柔声说道。她转身发现，原来是布兰德教授。之前她没有听到他的轮椅接近的动静。",
"“只是我以前从没见你来过这儿。”他说道。",
"墨菲站起身来。",
"“因为我以前确实没来过这儿。”说完这句话，她便不假思索地握住轮椅背后的把手，推着他进了走廊。",
"—— 《大电影双语阅读.星际穿越 Interstellar(华纳兄弟娱乐公司)》 (line 4339 - 4344)",
],
[
"书中主要人物",
"纳粹党卫队职阶名称",
"导言",
"第一章 “我的名字成了象征”",
"第二章 间奏曲：在中东的虚假踪迹",
"第三章 艾希曼在阿根廷",
"第四章 所谓的萨森访谈",
"第五章 虚假的安全感",
"第六章 角色的转换：艾希曼在耶路撒冷",
"—— 《理想国译丛041 耶路撒冷之前的艾希曼：平庸面具下的大屠杀刽子([德]贝蒂娜·施汤内特)》 (line 45 - 53)",
],
[
"Local law prohibited the time-reversal faculty by which the dead returned to life; they had spelled it out to him during his sixteenth year. He continued for another year to do it secretly, in the still remaining woods, but an old woman whom he had never seen or heard of had told. Without his parents’ consent they – the killers – had bombarded the unique nodule which had formed in his brain, had attacked it with radioactive cobalt, and this had plunged him into a different world, one whose existence he had never suspected. It had been a pit of corpses and dead bones and he had struggled for years to get up from it. The donkey and especially the toad, the creatures most important to him, had vanished, had become extinct; only rotting fragments, an eyeless head here, part of a hand there, remained. At last a bird which had come there to die told him where he was. He had sunk down into the tomb world. He could not get out until the bones strewn around him grew back into living creatures; he had become joined to the metabolism of other lives and until they rose he could not rise either.",
"—— 《Blade Runner(Philip K Dick)》 (line 154)",
],
[
"戴安娜来到了村庄的边缘，他们面前的楼房上满是子弹和火炮造成的弹坑。很多窗户上的玻璃已经不知所终，并被木板封死。铺满鹅卵石的街道和人行道上布满了泥土和战争产生的碎片：建筑表面被炸碎的石屑、碎裂的玻璃、木头的碎块，以及数以千计的弹壳。村庄里空无一人，地面也无人打扫。",
"在她前行的途中，街对面二楼的窗口和一楼的门口都传来了枪声。一颗子弹在她身后的砖墙上凿开一个小洞，另一颗将她脚边的一颗鹅卵石震起。",
"—— 《大电影双语阅读.神奇女侠 Wonder Woman(华纳兄弟娱乐公司)》 (line 3147 - 3148)",
],
[
"其一，关于学校教育。陈亮认为，学校教育应兼容百家异流，使学生自由学习研究时政和诸家学说，以培养实际有用的才干。他说：“天子设学校于行都，使之群居切磨，朝暮讲究，斥百家之异说而不以为诞，言当今之利害而不以为狂，所以养成其才而充其气也。”〔106〕实即反对用单一的理学观点限制学生。他主张学校立法，应取胡瑗的苏湖教学法、王安石的三舍法和程颐的元祐学法，各取其长而用之，使太学生能尽自己之所长而自奋。陈亮还肯定王安石变法改革教育，兴功利之学。他说：“神宗皇帝方锐意于三代之治，荆公以霸者功利之说，饰以三代之文，正百官，定职业，修民兵，制国用，兴学校以养天下之才。”〔107〕他又指出其弊是天下“纷然趋于功利而不可禁。学者又习于当时之所谓经义者，剥裂牵缀，气日以卑”〔108〕。而在《变文格》中，陈亮又针对宋代科举考试与学校考选关于经义与诗赋之争，比较系统地发表自己对这个问题的看法。考察宋代文风演变过程，他论及南宋时期太学的文风和学风，认为太学极盛，是胡瑗、孙复、石介、梅尧臣等人在太学居讲席时，其后王安石变法改革，但司马光尽废新法，不能参以“熙宁经术造士之意、取其学校课试之大略，徒取快于一时而已”。陈亮出“古人重变法，而尤重于变文，则必有深意”的见解，实即出对此问题的改革主张。",
"—— 《两宋文化史(杨渭生)》 (line 3332)",
],
[
"社会规范和法律都是制度的表现形式，在本质上都属于规范（norm），通过规则来协调人们之间的行为，实现一定的社会秩序和社会共识，并维护主流的价值观念。社会规范是人们在长期的相互交往中逐步形成的、得到普遍认可的行为准则；法律是立法机关制定的行为规则。当然，许多法律本身也是从习惯演变而来的，并非立法者的随意创造。但不论是法律还是社会规范，它们的主要功能之一是协调预期，帮助人们在多个均衡中筛选出一个特定的纳什均衡。",
"—— 《博弈与社会(张维迎)》 (line 672)",
],
[
"The rover has no toilet. We were expected to use our suits’ reclamation systems for that. But they aren’t designed to hold twenty days’ worth of output.",
"My morning piss goes in a resealable plastic box. When I open it, the rover reeks like a truck-stop men’s room. I could take it outside and let it boil off. But I worked hard to make that water, and the last thing I’m going to do is waste it. I’ll feed it to the water reclaimer when I get back.",
"—— 《The Martian(Andy Weir)》 (line 1130 - 1131)",
],
[
"低碳之争",
"纯利率影响文化品位",
"第二节 保险的机制与实践",
"灾难预报与保险公司",
"保险机制的演进",
"中国医疗保险的特点和症结",
"“医疗税”并非“医疗险”",
"第三章 互相依赖",
"第一节 信息不对称与市场的应对",
"医患之间的信任",
"何谓优质",
"—— 《经济学通识(薛兆丰)》 (line 56 - 66)",
],
[
"命犯災星必主低，身輕煞重有災危。時日若逢真太歲，就是神仙也皺眉。",
"月娘道：“命不好，請問先生還有解麽？”神仙道：“白虎當頭，喪門坐命，神仙也無解，太歲也難推。造物已定，神鬼莫移。”月娘只得拿了一匹布，謝了神仙，打發出門。月娘見求神問卜皆有凶無吉，心中慌了。到晚夕，天井內焚香，對天發願，許下“兒夫好了，要往泰安州頂上與娘娘進香掛袍三年”。孟玉樓又許下逢七拜鬥，獨金蓮與李嬌兒不許願心。",
"—— 《金瓶梅》 (line 2054 - 2055)",
],
[
"“Finally, I wish to see Councilor Albedo, Senator Kolchev, and Speaker Gibbons in my private chambers in three minutes. Are there any questions from anyone?”",
"—— 《The Fall of Hyperion (Hyperion Cantos, Book 2)(Dan Simmons)》 (line 1926)",
],
[
"敌方已经显露出来，而另一股势力又在发展，将要有所行动；这时应该借这股力量去摧毁敌人。",
"例如，西周末年，郑桓公想要袭击郐国，先将郐国豪杰、良臣、能言善辩之士、勇士等有本领的文臣武将的名单列出来，然后把郐国肥沃的田地及各种名称的官职爵位写在其姓名之下，并在城门外开设祭坛，把名单埋于坛下，用公鸡和公猪做祭品，装作盟誓的样子。郐国国君一听到这个消息，担心名单上的人会勾结郑国，便将其全部杀害。之后，郑桓公起兵进攻郐国，轻而易举就拿下了郐国。",
"—— 《中国古典文学荟萃》 (line 1964 - 1965)",
],
[
"——他们宣称中国没有遵守过去签订的战后条约。",
"是的。中国违反了条约，日本是受害者，因此必须从无法无天的中国手中保护日本在满蒙的特殊权益的言论，简直可以说是条约“原教旨主义”了。但是，石原等人的言论却完全不同。",
"——取得满蒙是为了将来的战争。",
"是的，就是这样。军人们主要着眼于应对可能爆发的对苏战争，因而需要满蒙作为基地。而且对苏作战时，美国很可能会进行干涉，更需要满蒙作为对美持久战的资源供应地，所以才要策划把满蒙从中国国民政府手中分离出去。至于那些国际法和条约规定的日本权益，到底有没有被中国侵害，事实上和军人的真正目的并没有太大的关系。但是，参谋本部的情报部部长建川美次却煽动民众说：“这在条约中有明确规定，但是如今却没有一条真正得到遵守。”",
"—— 《日本人为何选择了战争(加藤阳子)》 (line 1168 - 1171)",
],
[
"宿吴门",
"秋深风落木，清水半池荷。驱马向何去？吴门客子多。",
"其二",
"屋有图书润，庭无秋菊鲜。应知彭泽令，一夜不曾眠。",
"同深有上人看梅",
"东阁观梅去，清尊怨未开。徘徊天际暮，独与老僧来。",
"又观梅",
"雷雨惊春候，寒梅次第开。金陵有逸客，特地看花来。",
"郑楼",
"谷口郑子真，栖迟市门里。小楼延上客，酒酣犹未已。",
"—— 《焚书((明)李贽)》 (line 1207 - 1216)",
],
[
"“——我本来英文是不行的，这次教英文一半也因为刘先生的命令，讲错当然免不了，只希望刘先生当面教正。不过，这位同事听说跟刘先生有点意见，传来的话我也不甚相信。他还说，我班上那三个旁听的学生也是刘先生派来侦探的。”",
"“啊？什么三个学生——孙小姐，你到图书室去替我借一本——呃——呃——商务出版的《大学英文选》来，还到庶务科去领——领一百张稿纸来。”",
"—— 《围城(钱钟书)》 (line 907 - 908)",
],
[
"国语（国学基本丛书本）/45",
"六朝墓志菁英二编（罗振玉印本）/46",
"唐写本《世说新书》（罗振玉印本）/46",
"金冬心书画小记/47",
"六朝墓志菁英（罗振玉印本）/47",
"湖海诗传/47",
"元文类/47",
"乐府诗集/48",
"—— 《书衣文录（增订本）(孙犁)》 (line 1919 - 1926)",
],
[
"（81）维斯帕西亚努斯在亚历山大等待着夏天的风与平静的海洋这样一个例行季节<sup>(1151)</sup>的到来，就在这几个月里，出现了许多奇迹表明上天的眷顾和诸神对他的某种偏爱。亚历山大的一个由于失明而为人所熟知的普通人跪到维斯帕西亚努斯的面前，恳切要求维斯帕西亚努斯医治他的失明，因为塞拉皮斯神命令他这样做。这个最迷信的民族所最崇奉的神，就是塞拉皮斯。这个盲人请求皇帝俯允用唾液涂在他的面颊和眼睛上面。<sup>(1152)</sup>另一名有一只手残废了的人也因为受到同一位神的命令而请求凯撒用脚踏一踏这只残废的手。维斯帕西亚努斯起初嘲笑这些请求，并且以轻蔑的态度对待他们；然而当他们坚持请求的时候，他开始有了不同的想法。他一时里担心治不好病而自己丢面子，一时里在请求者的恳请和他的廷臣的谄媚之下又认为有希望能得到成功。最后他问医生们，这种盲目和这种残废是否为人力所能挽回，命令他们提出看法。对这两种情况，他们提出了不同的回答。他们说，在第一种情况下，视力并未完全损坏，如果视力的障碍消除的话，那个人是可以重新看到东西的。但在第二种情况下，是关节脱了节、变了位，如果在医疗上对它加以压力的话，他也是可以恢复正常的。这也许就是诸神的意旨，可能皇帝不过是被选来执行上天交付的任务罢了。但无论如何，如果能够治愈的话，这将是凯撒的光荣；如果失败的话，那么人们嘲笑的就只能是那些可怜的请求者了。因此，维斯帕西亚努斯既然相信他的好运可以做出任何事情来，<sup>(1153)</sup>而且不再有任何事情是不可信的，于是他就微笑着，在旁边侍立的人们的十分紧张兴奋的心情当中按照向他所请求的那样做了。那只残废的手立刻能转动了，而那盲人也立刻重新看见了光明。甚至现在，<sup>(1154)</sup>当谎言并不能取得任何报酬的时候，当时的目击者对这两件事实也还是津津乐道的。",
"—— 《塔西佗历史 (汉译世界学术名著丛书)(塔西佗)》 (line 673)",
],
[
"“我买了，那帮猴子现在在我家开的奥比克义肢厂，给医生做动物模型，经过精确测量后，它们都会被装上假肢。”她喝了一大口咖啡，心率加快，感觉敏锐，“怎么样？这下你放心了吧？立春来我这儿上班吗？”",
"一孤花零落之山",
"<jsdocimg>00012.jpeg</jsdocimg>",
"<jsdocimg>00021.jpeg</jsdocimg>",
"<jsdocimg>00015.jpeg</jsdocimg>",
"—— 《致我们所钟意的黄油小饼干(杜梨)》 (line 243 - 247)",
],
[
"“Please tell me what it is,” begged Wilbur.",
"“I’ll tell you in the morning,” she said. “When the first light comes into the sky and the sparrows stir and the cows rattle their chains, when the rooster crows and the stars fade, when early cars whisper along the highway, you look up here and I’ll show you something. I will show you my masterpiece.”",
"—— 《Charlotte's Web (Trophy Newbery)(E. B. White)》 (line 937 - 938)",
],
[
"				我不知道造物者认不认得",
"				自己图画；",
"				乡下人的笠帽，草鞋，",
"				乡下人的性情。",
"				暑中在山东乡间步行，二十五年夏",
"				原载1936年12月《新诗》第3期",
"红叶里的信念",
"				年年不是要看西山的红叶，",
"—— 《林徽因经典全集》 (line 958 - 965)",
],
[
"责任编辑 　文　青",
"营销编辑　 邓　宇",
"装帧设计　水玉银文化",
"市场的逻辑（增订版）",
"张维迎　著",
"出 版 世纪出版集团 上海人民出版社",
"（200001 上海福建中路193号 www.ewen.cc）",
"出 品 世纪出版股份有限公司 北京世纪文景文化传播有限责任公司",
"—— 《市场的逻辑(增订本)(张维迎)》 (line 1525 - 1532)",
],
[
"我们认识到，为了从根本上解决经济的长远发展问题，必须坚定推动结构改革，宁可将增长速度降下来一些。任何一项事业，都需要远近兼顾、深谋远虑，杀鸡取卵、竭泽而渔式的发展是不会长久的。",
"中国经济同世界经济高度融合。一个经济运行更稳定、增长质量更高、增长前景更可持续的中国，对世界经济发展是长期利好的。中国有条件有能力实现经济持续健康发展，为各国创造更广阔的市场和发展空间，为世界经济带来更多正面外溢效应。",
"—— 《习近平谈治国理政（第一卷简体中文版）(习近平)》 (line 1603 - 1604)",
],
[
"伊万原来也在忙着设计他的新装甲和新鞭子。它们装在凡科前臂内侧的凹槽内，能当做他手臂的延伸。这两条鞭子更粗更长，看起来能达到的温度也比托尼之前在摩纳哥碰到的时候更高。",
"“我有这个。”罗迪说。他打开了导弹舱，发射出一枚迷你火箭，据说它能夷平绝大多数的堡垒。",
"可它却从凡科的盔甲上弹开了，看起来根本没有造成任何损害，然后发出嘶嘶的响声，落在了淤泥里。“汉默科技？”托尼问，不过他早就知道答案了。",
"—— 《大电影双语阅读. Iron Man 2 钢铁侠 2(美国漫威公司)》 (line 1166 - 1168)",
],
[
"“One that I had suspected as a possibility from the first. I said to myself, if this were Earth, and Dr. Delmarre were as he was described to be and Gladia Delmarre as she seemed to be, I would say that she was in love with him, or had been, and that he was in love only with himself. The difficulty was to tell whether Solarians felt love or reacted to love in any Earthly sense. My judgment as to their emotions and reactions wasn’t to be trusted. It was why I had to see a few. <em>Not</em> view them, but see them.”",
"—— 《The Naked Sun (The Robot Series Book 2)(Isaac Asimov)》 (line 2530)",
],
[
"Amerigo Bonasera had a terrible nightmare. In his dreams he saw Don Corleone, in peaked cap, overalls and heavy gloves, unloading bullet-riddled corpses in front of his funeral parlor and shouting, “Remember, Amerigo, not a word to anyone, and bury them quickly.” He groaned so loud and long in his sleep that his wife shook him awake. “Eh, what a man you are,” she grumbled. “To have a nightmare only after a wedding.”",
"—— 《The Godfather- 50th Anniversary Edition(Mario Puzo)》 (line 373)",
],
[
"<i>Copyright</i>",
"<i>Dedication</i>",
"<i>Epigraph</i>",
"Chapter 1",
"Chapter 2",
"Chapter 3",
"Chapter 4",
"Chapter 5",
"Chapter 6",
"Chapter 7",
"—— 《Forrest Gump (Vintage Contemporaries)(Winston Groom)》 (line 41 - 50)",
],
];
