var quote31_global=[
[
"“你有啥打算？”他问她。",
"“哪里能杀古尔库人，我就去哪里。”她不假思索脱口而出，“我去找其他武器，和他们斗到底。”其实她不相信这番话，她已感觉不到曾经的浓烈恨意。只要古尔库人不来招惹她，让她做自己想做的事，复仇也许已无关紧要，可惜怀疑和失望让她更加偏执。“一切照旧，我要复仇。”",
"沉默。",
"她偷偷瞥去，发现九指皱眉盯着黝黑海面上的白色泡沫，似乎对这答案不满意。改口本来轻而易举。“你去哪儿，我就去哪儿。”她可以这么说，又有什么损失？没有，至少对她没有。但她就是不肯遂他的愿。两人之间好似隔了一道无形的墙。无法穿透的墙。",
"—— 《第一律法三部曲(乔·阿克罗比)》 (line 10594 - 10597)",
],
[
"Mr. Collins was not a sensible man, and the deficiency of nature had been but little assisted by education or society; the greatest part of his life having been spent under the guidance of an illiterate and miserly father; and though he belonged to one of the universities, he had merely kept the necessary terms, without forming at it any useful acquaintance. The subjection in which his father had brought him up had given him originally great humility of manner; but it was now a good deal counteracted by the self-conceit of a weak head, living in retirement, and the consequential feelings of early and unexpected prosperity. A fortunate chance had recommended him to Lady Catherine de Bourgh when the living of Hunsford was vacant; and the respect which he felt for her high rank, and his veneration for her as his patroness, mingling with a very good opinion of himself, of his authority as a clergyman, and his right as a rector, made him altogether a mixture of pride and obsequiousness, self-importance and humility.",
"—— 《Pride and Prejudice》 (line 556)",
],
[
"图2.1　2010年是人口红利I的拐点",
"如图2.2所示，截至2018年，中国的工作年龄人口占比依然显著高于美国、欧盟与日本：中国的工作年龄人口占比要比美国、欧盟高出5个百分点以上，要比日本高出10个百分点以上。但是，2010年以来中国工作年龄人口占比曲线的下降斜率，却显著高于美国与欧盟。各方面证据均显示，中国将在未来30年内迎来快速的人口老龄化。这意味着中国人口红利I在未来将会加速衰减。",
"—— 《宏观中国：经济增长、周期波动与资产配置(张明)》 (line 244 - 245)",
],
[
"在集体主义制度之下，将会继续受到尊重的美德和将会消失的美德之间的区别，可用一个对比来很好地说明，这就是那种就连他们最拙劣的敌人也承认说德国人或者不如说“典型的普鲁士人”所具有的那些美德和人们通常认为是他们所缺少，但同时却是英国人有理由作为优越之处引以自豪的那些美德之间的对比。很少有人会否认德国人在总体上是勤勉而守纪律的，认真和干劲都达到无情的程度，对于他们所执行的任务是忠诚和专心致志的；他们有一种强烈的纪律与责任心，而且严格服从当局；他们在遇到身体上的危险时，时常表现出自我牺牲的决心和大无畏的精神。所有这一切把德国人造就成完成指派任务的有效工具，并且，在旧的普鲁士邦和普鲁士人统治的新帝国中，他们就是这样被细心地培养起来的。人们时常认为“典型的德国人”所缺少的个人主义美德是：宽容和尊重其他的个人及其意见，独立精神，正直的性格和维护自己的意见而不为上级所左右的那种意愿（德国人也常常意识到自己缺乏这一点，并把这叫做“刚直不阿”），还有对于弱者和衰老者的体恤，和只是个人自由的古老传统才创造出来的对权力的极度鄙视与憎恨。他们似乎还缺少大多数很细小的，但很重要的品质，就是在一个自由社会里会促进人与人之间互相交往的那些品质：和蔼和幽默感，个人谦逊，尊重别人的隐私和对邻人的善意怀有信任。",
"—— 《通往奴役之路(哈耶克)》 (line 549)",
],
[
"（《义门读书记》）",
"（清）王夫之评曰：情乍近而终远，词在苦而如甘。“入室”之誉，以此当之，庶几无愧。乃以植驵才，奈何一旦顿造斯品，意其谲冒家传，豪华固有，门多赋客，或代其庖。如曹洪托笔孔璋，以欺子桓，则未卜斯篇之定为植作也。不然，陶皆苦窳，忽成佳器，亦物之不祥矣。“明月照高楼，流光正徘徊。”可谓物外传心，空中造色，结语居然在人意中，而如从天陨，匪可识寻，当由智得。",
"—— 《汉魏六朝诗、文、赋(程怡)》 (line 924 - 925)",
],
[
"The snake and the robot grumbled a little, but they crawled out from under the bed to help.",
"A few paces away, the sheriff heard a squeak. He grinned. The knobs were twitching on Etch A Sketch, Andy’s rectangular drawing toy. “Hey, Etch!” the sheriff called out. “Draw!” Woody’s gun arm shot to his empty holster. Too late.",
"—— 《迪士尼大电影中英文阅读·玩具总动员(美国迪士尼公司)》 (line 143 - 144)",
],
[
"丽仙念毕，爱卿道：“巧云妹妹，你该联一句。”袁巧云听了道：“我是不会的。”爱卿亦知巧云不善吟哦，便道：“随意说一句，不失粘就是了。”巧云无奈，只管搔头摸耳，细想了许久，说道：“有一句在此。”大家道：“如此，快些请教。”巧云道：“霏霏……”说了两字，又顿住了口。爱卿道：“为何说了两字不说了？”巧云道：“不好，不好。不象，不象。”又想了良久，复说道：“霏霏霏……”大家听了道：“为何又多了一字？”巧云道：“下面再加‘木屑’两字可好？”巧云说着，弄得大家捧腹而笑。巧云道：“不算，不算。重说，重说。”便红着脸，又想了片晌，念道：",
"—— 《青楼梦(慕真山人)》 (line 756)",
],
[
"我拿着背包，再次踏出了家门。",
"今天可以说是马不停蹄，因为要跑好几千里路。",
"早上从香港坐火车到深圳，然后坐机场巴士到了深圳机场。经过两个小时的飞行，飞机抵达了昆明机场。",
"因为“非典”的关系，整个城市弥漫着一片紧张的气氛，昆明到大理的航班已经全部被取消。",
"我马上从机场打车到长途汽车站。司机说因为“非典”的关系，昆明去大理的长途汽车班次比以前少多了，这让我非常担心。",
"—— 《藏地白皮书(傅真 & 毛铭基)》 (line 935 - 939)",
],
[
"这时，外面传来了吼声：“小兔崽子，你给我滚出来！今天你不还我豆饼，不管你躲到哪儿，我也要把你找出来！”",
"没人给徐克盛粥。",
"徐克夺过吴振庆的粥碗，喝起来……",
"吴振庆忐忑地站起来，走到外面去看……",
"母亲说：“小嵩，扶我出去……”",
"王小嵩说：“妈，你躺着吧，又不是我干的事儿！”",
"徐克说：“对，大婶你老老实实躺着吧。那人找不见我，一会儿就会走的！”",
"—— 《年轮(梁晓声)》 (line 450 - 456)",
],
[
"(1174)阿格里帕是特拉科尼提斯和迦利里的国王。",
"(1175)索海木斯是索佩尼的国王和叙利亚的埃美撒的国王。",
"(1176)安提奥库斯是孔玛盖尼和部分奇里奇亚的国王。以上参见本书第2卷，第81章。",
"(1177)塔西佗的关于犹太人的这一简略的但是有些混乱的记述，显然是采用了亚历山大的历史家凯列蒙（Chaeremon）和吕西玛库斯（Lysimachus）的史料。",
"—— 《塔西佗历史 (汉译世界学术名著丛书)(塔西佗)》 (line 1912 - 1915)",
],
[
"“我们拦不住他。”希芙说道。范德洛尔同意道：“至少他只是被放逐了，又不是死了。要不是那名守卫告诉奥丁我们去哪儿了，我们就都得死。”",
"“那名守卫是如何知道的？”沃尔斯塔格问道。",
"一阵短暂的沉默后，洛基说：“是我告诉他的。”",
"“什么？”范德洛尔感到震惊。",
"“我让他等我们一走就去找奥丁。然而他却花了这么长的时间，应该受到鞭笞。”洛基说道。",
"—— 《大电影双语阅读. Thor 雷神(美国漫威公司)》 (line 1360 - 1364)",
],
[
"				事实上，我们是通过对群体心理的调查归纳出了这些原因，基于这些考虑，我要对它们做进一步的阐述。",
"				毫无疑问，普选制度的弱点十分突出，因此我们很难对其视而不见。但是我们无法否认一桩事实，那就是社会一定是要由少数人操纵的。",
"				我们的文明，乃是少数智力超常的人的产物，这些人构成了一个金字塔的顶点。随着这个金字塔各个层次的加宽，智力也相应地越来越少，而这个金字塔的底座，就是一个民族中的广大群众。",
"—— 《乌合之众(古斯塔夫·勒庞 (Gustave Le Bon))》 (line 1994 - 1996)",
],
[
"子曰：“居上不宽，为礼不敬，临丧不哀，吾何以观之哉？”",
"里仁　第四",
"子曰：“里仁为美。择不处仁，焉得知？”",
"子曰：“不仁者不可以久处约，不可以长处乐。仁者安仁，知者利仁。”",
"子曰：“唯仁者能好人，能恶人。”",
"子曰：“苟志于仁矣，无恶也。”",
"子曰：“富与贵，是人之所欲也；不以其道得之，不处也。贫与贱，是人之所恶也；不以其道得之，不去也。君子去仁，恶乎成名？君子无终食之间违仁，造次必于是，颠沛必于是。”",
"—— 《四书：大学·中庸·论语·孟子》 (line 185 - 191)",
],
[
"从数量角度看，在19世纪的英国和德国，商业和土地贵族之间的相互渗透可能并没有太大的不同。非常令人惊讶的是，甚至有一些统计证据表明这种渗透在普鲁士更为广泛。有一个研究人员宣称，他发现，1918年之前好多年，普鲁士下议院成员中平均有78％以上的人来自普通阶层和新晋贵族。而在另一方面，平民在外交和行政管理这两个德国关键的权力部门中所占的比例分别只有38％和43％。对1841年到1847年英国议会进行的一项研究表明，只有40％的成员与商业有关，余下的60％则与商业世界没有任何关系。<sup>【98】</sup>在如何正确地使用这些证据方面存在着许多棘手的技术问题。例如，不同国家的统计数据真的具有可比性吗？把英国议会里40％的人与商业有关和普鲁士下议院里78％的人来自平民放在一起进行比较合适吗？我对这样做是心存怀疑的，不过我也相信，即使技术问题能够得到解决，我们仍然无法获得任何有价值的进展。",
"—— 《大学译丛:专制与民主的社会起源（国家现代化的三种抉择）(巴林顿·摩尔(Moore Barrington))》 (line 193)",
],
[
"<jsdocimg>00153.jpeg</jsdocimg>",
"资料来源：CEIC。",
"图2.1　2010年是人口红利I的拐点",
"如图2.2所示，截至2018年，中国的工作年龄人口占比依然显著高于美国、欧盟与日本：中国的工作年龄人口占比要比美国、欧盟高出5个百分点以上，要比日本高出10个百分点以上。但是，2010年以来中国工作年龄人口占比曲线的下降斜率，却显著高于美国与欧盟。各方面证据均显示，中国将在未来30年内迎来快速的人口老龄化。这意味着中国人口红利I在未来将会加速衰减。",
"—— 《宏观中国：经济增长、周期波动与资产配置(张明)》 (line 242 - 245)",
],
[
"在另一封信里，他可怜巴巴地说：“我的脚浮肿很厉害，我不得不穿一双大鞋，在脚跟的三四英寸以上有色肿纹，在伸脚时非常疼痛，希望医生给一些药物治疗……”（《东印度公司对华贸易编年史》）",
"这就是中国和英国第一次交往的结果。",
"9",
"经过这次挫折，英国政府决定，必须派出使团，直接与中国政府建立联系，否则中英间的贸易问题永远无法解决。因此才有了开头的那篇禀文。",
"—— 《饥饿的盛世：乾隆时代的得与失(张宏杰)》 (line 2020 - 2023)",
],
[
"一○　旧三民主义和新三民主义",
"资产阶级顽固派完全不知道历史的变化，其知识的贫乏几等于零。他们既不知道共产主义和三民主义的区别，也不知道新三民主义和旧三民主义的区别。",
"我们共产党人承认“三民主义为抗日民族统一战线的政治基础”，承认“三民主义为中国今日之必需，本党愿为其彻底实现而奋斗”，承认共产主义的最低纲领和三民主义的政治原则基本上相同。但是这种三民主义是什么三民主义呢？这种三民主义不是任何别的三民主义，乃是孙中山先生在《中国国民党第一次全国代表大会宣言》中所重新解释的三民主义。我愿顽固派先生们，于其“限共”、“溶共”、“反共”等工作洋洋得意之余，也去翻阅一下这个宣言。原来孙中山先生在这个宣言中说道：“国民党之三民主义，其真释具如此。”就可知只有这种三民主义，才是真三民主义，其他都是伪三民主义。只有《中国国民党第一次全国代表大会宣言》里对于三民主义的解释才是“真释”，其他一切都是伪释。这大概不是共产党“造谣”吧，这篇宣言的通过，我和很多的国民党员都是亲眼看见的。",
"—— 《新民主主义论(毛泽东)》 (line 116 - 118)",
],
[
"“罗辑的破壁人呢？”有人问。",
"这话似乎触动了秦始皇心中的什么东西，他把长剑拄在地上沉思着。这时，空中的太阳突然加快了下落的速度，所有人的影子都被拉长，最后一直伸向天边。在太阳落下一半后，突然改变运行方向，沿着地平线几次起落，像不时浮出黑色海面的金光四射的鲸背，使得由空旷荒漠和这一小群人构成的简单世界在光明与黑暗中时隐时现。",
"“罗辑的破壁人就是他自己，他需要自己找出他对主的威胁所在。”秦始皇说。",
"—— 《三体(刘慈欣)》 (line 3770 - 3772)",
],
[
"1933年2月11日",
"岂明师：",
"返新槐后奉赐书，讲演知将“延期”，已转申敝上司<sup>[1]</sup>，但参知之称殊不敢承，以似有备带某种（式）眼镜之嫌耳。上课期迫而尚欠缺此项强聒兴味，然功令森严奈何？红楼学员听说尚不甚多，后日尚须赖学，以后则难言矣。自交乌鸡运后文思寂然如古井不波，这个年头有什么可说乎？诚如尊谕！",
"二月十一日　弟子庆拜",
"—— 《周作人俞平伯往来通信集(周作人)》 (line 2292 - 2295)",
],
[
"霜　月",
"李商隐",
"初闻征雁已无蝉，百尺楼台水接天。",
"青女素娥俱耐冷，月中霜里斗婵娟。",
"梅",
"王　淇",
"不受尘埃半点侵，竹篱茅舍自甘心。",
"只因误识林和靖，惹得诗人说到今。",
"早　春",
"白玉蟾",
"—— 《千家诗(张居正)》 (line 573 - 582)",
],
[
"王氏藏身有远图，间关到底得逢夫。",
"舟人妄想能同志，一月空将新妇呼。",
"又诗云：",
"芙蓉本似美人妆，何意飘零在路旁？",
"画笔词锋能巧合，相逢犹自墨痕香。",
"又有一首赞叹御史大夫高公云：",
"高公德谊薄云天，能结今生未了缘。",
"不便初时轻逗漏，致今到底得团圆。",
"芙蓉画出原双蒂，萍藻浮来亦共联。",
"—— 《初刻拍案惊奇(凌濛初)》 (line 1223 - 1231)",
],
[
"With an epidemic in which there is no immediate prospect of a vaccine，much less of a cure，prevention plays a larger part in consciousness. But campaigns to keep people from getting ill run into many difficulties with diseases that are venereally transmitted. There has always been reluctance in American health campaigns to communicate information about ways of having safer sex. The <i>US Guide for Schools</i> issued in late 1987 by the Department of Education virtually refuses to discuss reducing risk and proposes abstinence as the best way of safeguarding against AIDS，recalling lectures given soldiers during World War I that chastity was the only safeguard against syphilis as well as part of their patriotic duty in fighting the Hun.<sup>[12]</sup> Talk of condoms and clean needles is felt to be tantamount to condoning and abetting illicit sex，illegal chemicals. （And to some extent is. Education about how to keep from getting AIDS does imply an acknowledgment of，therefore tolerance of，the ineradicable variousness of expression of sexual feeling.） European societies，less committed to sexual hypocrisy at the level of public edict，are unlikely to urge people to be chaste as a way of warning them to be prudent. ‘Be careful. AIDS.’ And ‘AIDS. Don’t die of ignorance.’ The specific meaning of these generalities to be seen on billboards and television spots throughout Western Europe for several years is：Use condoms. But there is a larger meaning in all these messages about being careful，not being ignorant，that will facilitate the acceptance of this kind of public service ad here as well. Part of making an event real is just <i>saying</i> it，over and over. In this case，to say it over and over is to instill the consciousness of risk，the necessity of prudence as such，prior to and superseding any specific recommendation.",
"—— 《疾病的隐喻(苏珊·桑塔格)》 (line 787)",
],
[
"道聪不信，引入密室验之。你说怎么验法？用细细干灰铺放余桶之内，却教女子解了下衣坐于桶上，用绵纸条栖入鼻中，要他打喷嚏。若是破身的，上气泄，下气亦泄，干灰必然吹动；若是童身，其灰如旧。朝廷选妃，都用此法，道聪生长京师，岂有不知？当时试那妹子，果是未破的童身，于是姊妹两人抱头而哭。道聪慌忙开箱，取出自家裙袄，安排妹子香汤沐浴，教他更换衣服。妹子道：“不欺姐姐，我自从出去，未曾解衣露体。今日见了姐姐，方才放心耳。”那一晚张二哥回家，老婆打发在外厢安歇。姊妹两人同被而卧，各诉衷肠，整整的叙了一夜说话，眼也不曾合缝。",
"—— 《喻世明言》 (line 1867)",
],
[
"午食时天气炎热，移泊大树下。饭后以山兜入山，三里至南镇，庙宇新整，神像威武，茶罢即行。七里至香炉峰绝顶，山径盘旋直上，侧首下望，山河襟带，城镇星罗。秦望天柱诸山，宛如列黛。野花弥漫郊，如碎紫锦。中途稍憩小庙。又逾岭冈数重，始见香炉峰。峰形峭削，山径窄而陡，旁设木栏以卫行客。有石梁跨两崖间。逾之不数武，路忽转，两圆石对峙，舆行其间，乘者须敛足曲肱而过。绝顶仅一小庙，绝湫隘，闻值香汛，香客来者以千数。峰顶尖小，故除庙外无立足地，仅可从窗棂间下窥，绍兴城郭庐舍楚楚可辨，钱江一线远亘云表，群峰多如培，惟秦望独尊。天色欲雨，舆人催客，匆促下山。至南镇，见疏雨张盖。",
"—— 《中年(俞平伯)》 (line 450)",
],
[
"小阑干高倚长空，壮观山城，仿佛天宫。盩遍画鼍，嘶残玉凤，漏尽铜龙。催古寺一百八晓钟，动晨光三十六晴峰。雄视江东，万井春风，太守神功。",
"湖上雪晴鲁至道席间赋",
"想当年雁塔题名，衣锦归来，揽辔澄清。试坐渔矶，相亲蚁绿，不负鸥盟。青山老西施暮景，碧天高东鲁文星。陶写襟灵，玉手琵琶，翠袖娉婷。",
"赠胡存善",
"掌梨园乐府须知，富有牙签，名动金闺。一代风流，九州人物，万斛珠玑。解流水高山子期，制暗香疏影姜夔。胸次清奇，笑毁黄钟，识透玄机。",
"—— 《全元散曲》 (line 5736 - 5740)",
],
[
"一时起，三春暮，",
"若言来，且就阳台路。",
"卷21_94【相和歌辞·上云乐】",
"李白",
"金天之西，白日所没。",
"康老胡雏，生彼月窟。",
"巉岩仪容，戌削风骨。",
"碧玉炅炅双目瞳，黄金拳拳两鬓红。",
"华盖垂下睫，嵩岳临上唇。",
"—— 《全唐诗》 (line 8040 - 8048)",
],
[
"⑳ 我这里不是指你一定要持有诺姆 · 乔姆斯基的观点，而是指你不得不变成一个专业的辩论者（controversialist）。如果说了“不能说的话”，你就同时得罪了保守派和自由派，两派都会与你辩论。好比回到维多利亚女王时代的英国，你同时得罪了辉格党和托利党，那么你的一张嘴怎么能是两大党派的对手呢？（编者注：诺姆 · 乔姆斯基是著名的语言学家，麻省理工学院的语言学和哲学教授。）",
"—— 《黑客与画家(Paul Graham)》 (line 494)",
],
[
"日本把西洋的文化整个吞咽下去，它的军国主义，它的资本主义，它的民族主义，以及它的权力的信仰，把它加在一个封建社会上面，没有时间替自己思想。这一来，给她的文化一种机械的，缺乏幽默的，不近情的特点。这种机械的，缺乏幽默的特点，可以从日本税关人员和替察那种令人讨厌，爱好规律，以及极度严肃的态度，从军人的虚荣梦想，以及从“日本高于一切”式的对世界（包括大不列颠）的外交挑战的傲慢态度看到。",
"—— 《浮生若梦(林语堂)》 (line 382)",
],
[
"[1] Owen 2011; see also the relevant chapter in Adams 2015.",
"[2] See Adams 2015 for a collection of the claims, which he investigated.",
"[3] Herodotus, Histories, IV.147; http:// www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0126% 3Abook%3D4%3Achapter%3D147%3Asection%3D1.",
"—— 《考古的故事(埃里克·H·克莱因)》 (line 1062 - 1064)",
],
[
"玉香正在要緊頭上，恐怕走上床去未免要取出玉麈來，把快活事打斷了。況且此時手酸腳軟動彈不得，要走也走不上床。聞他一說這一句只是閉了雙眼搖頭不應。未央生道：“心肝，你莫非走不動麽？”玉香把頭點一點。未央生道：“待我抱你上去就是。”竟把她雙足架在手臂上。玉香雙手抱住未央生，口裡含了絳舌。未央生抱將起來，玉塵留在陰中並不抽出，一邊行走一邊抽送做個走馬看花的勢。抱到床上，把玉香放倒，架起雙足從頭乾起。再抽數百抽，玉香忽然叫道：“ 心肝，我要不好了！”雙手緊緊摟住未央生，口裡哼哼嚇嚇就像大病之人要絕命的一般。未央生知道陰精已生，把玉麈頂住花心用力一揉，也陪她似死。",
"—— 《肉蒲團(李漁)》 (line 56)",
],
[
"Toye，Hugh．Laos：Buffer State or Battleground． London：Oxford University Press．1968．",
"Turner，Victor．Dramas，Fields and Metaphors．Symbolic Action in Human Society． Ithaca：Cornell University Press．1974．",
"—— 《想象的共同体(本尼迪克特·安德森)》 (line 1464 - 1465)",
],
];
