var quote31_global=[
[
"我们来到通往火山口湖的岔口，然后沿着一条整洁的公路进入国家公园[3]——里面清理得非常干净，保存完好。国家公园就该是这个样子，但它也没因为拥有良质而获得什么奖金。它成了一座天然的博物馆。这里仍是白人到来之前的景象——到处流淌着美丽的熔岩，参天的树林里，看不到任何啤酒罐。白人来了之后，一切看起来都虚假多了。或许国家公园管理处应该在熔岩的中央堆起一些啤酒罐，那样可能就会显得比较有生气。没有啤酒罐仿佛缺少了什么。",
"—— 《禅与摩托车维修艺术(罗伯特·M·波西格)》 (line 2625)",
],
[
"obtain permission for the use of the work and the Project Gutenberg-tm",
"trademark as set forth in paragraphs 1.E.8 or 1.E.9.",
"1.E.3. If an individual Project Gutenberg-tm electronic work is posted",
"—— 《The Dunwich Horror(H. P. Lovecraft)》 (line 281 - 283)",
],
[
"* * * * *",
"Just as it is possible to learn more of a human being in one minute of love than in months of observation, so Christophe had learned more about France in a week of intimacy with Olivier, hardly ever leaving the house, than during a whole year of blind wandering through Paris, and standing at attention at various intellectual and political gatherings. Amid the universal anarchy in which he had been floundering, a soul like that of his friend seemed to him veritably to be the \"Île de France\"—the island of reason and serenity in the midst of the ocean. The inward peace which was in Olivier was all the more striking, inasmuch as it had no intellectual support,—as it existed amid unhappy circumstances,—(in poverty and solitude, while the country of its birth was decadent),—and as its body was weak, sickly, and nerve-ridden. That serenity was apparently not the fruit of any effort of will striving to realize it,—(Olivier had little will);—it came from the depths of his being and his race. In many of the men of Olivier's acquaintance Christophe perceived the distant light of that [Greek: sophrosynae],—\"the silent calm of the motionless sea\";—and he, who knew, none better, the stormy, troublous depths of his own soul, and how he had to stretch his will-power to the utmost to maintain the balance in his lusty nature, marveled at its veiled harmony.",
"—— 《Jean Christophe: in Paris The Market-Place, Antoinette, the House, by Romain Rolland》 (line 1626 - 1627)",
],
[
"The idea was riveting, but the canvas overwhelmed me. Summoning characters who could manifest the intellect and the ferocity such logic would provoke proved beyond my imagination until I remembered one of the books I had published back when I had a job. A newspaper clipping in <i>The Black Book</i> summarized the story of Margaret Garner, a young mother who, having escaped slavery, was arrested for killing one of her children (and trying to kill the others) rather than let them be returned to the owner’s plantation. She became a cause célèbre in the fight against the Fugitive Slave laws, which mandated the return of escapees to their owners. Her sanity and lack of repentance caught the attention of Abolitionists as well as newspapers. She was certainly single-minded and, judging by her comments, she had the intellect, the ferocity, and the willingness to risk everything for what was to her the necessity of freedom.",
"—— 《Beloved (Vintage International)(Toni Morrison)》 (line 104)",
],
[
"The little fleet was well out into the bay when Cersei indicated that it was time to go. Bronn brought Tyrion’s horse and helped him mount. That was Podrick Payne’s task, but they had left Pod back at the Red Keep. The gaunt sellsword made for a much more reassuring presence than the boy would have.",
"—— 《George R. R. Martin's A Game of Thrones 5-Book Boxed Set (Song of Ice and Fire Series)(George R. R. Martin)》 (line 12230)",
],
[
"举一个较为简单的例子可能有助于说明这个问题。某一个团体的领导人渴求无限的权力和威望，没有他，什么事也决定不了或干不成。他不愿意把责任托付给别的受过专门训练的更有能力处理某些事物的人。在他心中，任何事都只有他最懂行。此外，他还不要别人感到他们也是他不可缺少的帮手或真正变得不可缺少了。他只是因为时间和精力的限制，才不可能如愿以偿。但这个人不仅想支配他人，也想屈从他人，想做一个大好人。由于这些冲突的存在，他身上便有了我们描述过的所有症状：怠惰、嗜睡、犹豫、拖沓，因而不能安排自己的时间。又由于他感到守约是一种不可忍受的强迫，他暗暗喜欢让别人等候他。还有，他做了许多无关紧要的事，只是因为那样能满足自己的虚荣。最后，他又很想做模范丈夫，而这又要耗费他不少时间和心思。所以，这个团体自然不能很好地发挥作用。但由于他看不到自己的毛病，他反而怪罪团体里别的人员，或责怪外在条件不利。",
"—— 《我们内心的冲突(卡伦·霍妮)》 (line 324)",
],
[
"岳少保坟祠，祠南向，旧在阛阓。孙中贵为买民居，开道临湖，殊惬大观。祠右衣冠葬焉。石门华表，形制不巨，雅有古色。",
"周诗《岳王坟》诗：",
"将军埋骨处，过客式英风。北伐生前烈，南枝死后忠。",
"干戈戎马异，涕泪古今同。目断封丘上，苍苍夕照中。",
"高启《岳王坟》诗：",
"大树无枝向北风，千年遗恨泣英雄。",
"—— 《西湖梦寻(张岱)》 (line 271 - 276)",
],
[
"人们经常提出这样一个问题——什么类型的人会犯下如此恐怖的罪行？一个回答是给这些犯罪者贴上虐待狂的标签，但是有证据表明，只有少数的犯罪者事实上是虐待杀人狂。甚至在不动感情之中以高效率处死数千名无依无靠的受害者的纳粹医生当中，几乎也没有任何临床意义上的虐待狂倾向。正如奥斯维辛集中营的幸存者埃拉·林根斯·赖纳所认为的那样：“这里几乎没有什么虐待狂。只有不到5%或5%的人在临床意义上是病态的罪犯。其他人完全是正常的，知道正确和错误之间的差异。他们都知道他们的所作所为。”假如虐待狂只是起了次要的角色，那么关注的焦点就必须转移到德国社会更广大的文化形态上，它们提供了动机和制度上的机制，使得通过国家的命令杀害数百万民众成为可能。在本书所展示的分析当中，有四种形态被认为是至关重要的，必须再次突出出来：（1）恶毒的、具有强烈的生物学和宗教成分的反犹太主义；（2）在家庭、学校、每日生活当中强有力的制度化极权主义的倾向；（3）建立在缺乏身份、不安全感和战败创伤基础上的好战的民族主义；（4）被一个罪恶的领导层统治。",
"—— 《纳粹德国：一部新的历史([美国]克劳斯•P.费舍尔)》 (line 1948)",
],
[
"贡缎、宁价值几何，今天的读者可能不太清楚。不过“乌云豹一千张，银鼠一千张”的分量应该可以想象。“乌云豹”者，《清稗类钞》云：“狐项下细毛深温黑白成文者”，指生于沙漠地带的野生沙狐颌下的那一小块皮。银鼠即白貂，毛色银白而富于光泽，历来价值极其昂贵。",
"五天后，皇帝行至宝家营，湖北巡抚陈辉祖等候在此，进了一批小玩意儿：“洋磁小刀三十六把、海龙帽檐五十付、象牙火镰包三十六个。”",
"—— 《饥饿的盛世：乾隆时代的得与失(张宏杰)》 (line 1611 - 1612)",
],
[
"041　耶路撒冷之前的艾希曼：平庸面具下的大屠杀刽子手",
"［德］贝蒂娜·施汤内特 著",
"042　残酷剧场：艺术、电影与战争阴影",
"［荷］伊恩·布鲁玛 著",
"043　资本主义的未来",
"［英］保罗·科利尔 著",
"044　救赎者：拉丁美洲的面孔与思想",
"—— 《美国的反智传统([美]理查德·霍夫施塔特)》 (line 1814 - 1820)",
],
[
"（宋）张耒：《柯山集》，《丛书集成》初编本。",
"（宋）俞文豹：《吹剑录外集》、《知不足斋丛书》本。",
"（宋）程颢、程颐：《二程遗书》，见《二程集》，中华书局点校本1981年版。",
"（宋）黄震：《黄氏日抄》，《四库全书·文渊阁》影印本。",
"（宋）车若水：《脚气集》，明《宝颜堂秘》本。",
"（宋）陆游：《放翁家训》，《知不足斋丛书》本。",
"—— 《两宋文化史(杨渭生)》 (line 7211 - 7216)",
],
[
"越日，由太皇太后特旨，立崇国夫人韩氏为皇后。后系故忠献王韩琦六世孙，初与姊俱被选入宫，事两宫太后，独后能曲承意旨，因此归嘉王邸，封新安郡夫人，晋封崇国夫人。后父名同卿，侂胄系同卿季父，自后既正位，侂胄兼得两重后戚，且自居定策功，遂渐渐的专横起来。为后文写照。汝愚请召还留正，命为大行攒宫总护使，留正入辞，嗣复出城。太皇太后命速追回，汝愚亦入请帝前，乃特下御札，召留正还，仍命为左丞相，改令郭师禹为攒宫总护使。一面由嗣皇带领群臣，拜表泰安宫。光宗方才闻知，召嗣皇入见。韩侂胄随嗣皇进谒，光宗瞪目视道：“是吾儿么？”（光宗已死了半个。）复顾侂胄道：“汝等不先报我，乃作此事，但既是吾儿受禅，也无庸说了。”嗣皇及侂胄均拜谢而退，自是禅位遂定，历史上称作宁宗皇帝，改元庆元。",
"—— 《宋史演义(蔡东藩)》 (line 1599)",
],
[
"正因為儒家思想，一着眼即直瞥見了「心我」，即直接嚮往到此人類最高的自由，因此儒家往往有時不很注重到人類生活之外圍，而直指本心，單刀直入，逕自注重到人之精神我與道德我之最高自由上。當知人類儘向自然科學發展，儘把自然所與的物質條件盡量改進，而人類生活仍可未能獲得此一最高之自由。又若人類儘向社會科學發展，儘把社會種種關係盡量改進，而人類生活仍可未能獲得此一最高之自由。而若人類能一眼直瞥見了此心我，一下直接接觸到了此精神我，一下悟到我心我性之最高自由的道德，人類可以當下現前，無入而不自得，即是在種種現實情況下而無條件地獲得了他所需的最高自由了。於是在儒家思想的指示下，既不能發展出宗教信仰，而同時又不能發展出科學與法律兩方的精密探檢，與精密安排了。",
"—— 《人生十论 (钱穆国学作品集（套装共10册） 6)(钱穆)》 (line 523)",
],
[
"Lay out the plates and make a better fire.",
"MARY",
"I will not cook for you.",
"SHEMUS",
"Not cook! not cook!",
"Do not be angry. She wants to pay me back",
"—— 《Poems by W. B. Yeats》 (line 618 - 623)",
],
[
"\"Give him to me.\"",
"The old man began, as usual, to air his theories:",
"\"You ought not to give way to children when they cry. You must just let them cry.\"",
"—— 《Jean-Christophe, Volume I, by Romain Rolland》 (line 44 - 46)",
],
[
"忒塞尔的声音低沉下去，渐渐降成一阵呢喃，最后归于沉寂。他佝偻着身体坐在原地，眼睛盯着地面，手指一会儿扣紧，一会儿又放开。",
"哈伦静静等着老人的下一句话，发现他陷入沉思之后，便清了清嗓子。他觉得自己很同情这个人，即使这老人犯下那么多罪行。他说：“就这样了？”",
"忒塞尔低语：“还没有，最悲惨的——最悲惨的——是我儿子在新的现实中依然存在。在新的现实中，他的确存在——作为一个从四岁起就得了小儿麻痹的患者，在床上躺了42年。在这种情况下，我无法为他安排900世纪的神经重建技术来治疗，甚至不能给他安排一次安乐死。",
"—— 《永恒的终结(艾萨克•阿西莫夫)》 (line 1866 - 1868)",
],
[
"129.唐长孺有《艺圃小集》",
"《桐江续集》卷三三《唐长孺艺圃小集序》：",
"“艺圃有作所谓小园，仅有百步者，凡十六句，似乎作拟陶，后二首亦然，予为题曰《艺圃小集》而序之。”",
"“其（诗）所以可人意者，格高也。何以谓之格高？近人之学许浑、姚合者，长孺扫之如粃糠，而以陶、杜、黄（庭坚）、陈（后山）为师者也。”",
"—— 《《全宋诗》补阙——补诗人、补诗事、补诗评(高志忠)》 (line 1744 - 1747)",
],
[
"发行电话　（010）68992190/3/5/6",
"网　　址　www.jiuzhoupress.com",
"电子信箱　jiuzhou@jiuzhoupress.com",
"印　　刷　三河市九洲财鑫印刷有限公司",
"开　　本　880毫米×1230毫米　32开",
"印　　张　6",
"字　　数　114千字",
"—— 《中国历代政治得失(钱穆)》 (line 16 - 22)",
],
[
"‘You should call her Jane,’ Melony advised Homer; Melony was alternately sick of Jane Eyre and completely identified with her.",
"‘I could have called her Melony,’ Homer responded, but humor was not reliably to be found in Melony, who preferred to play her own jokes.",
"—— 《The Cider House Rules (Black Swan)(John Irving)》 (line 867 - 868)",
],
[
"理查兹（I.A.Richards）　225",
"理查森（Brian Richardson）　1，145，209，218，372，373，375，376，389，392，393",
"理查逊（Sanmuel Richardson）　9，10，12，14，17-24，27，29，30，32，36，37，40-43，46，47，52，53，57，60，68，70，71，73，84",
"—— 《英美小说叙事理论研究(申丹 韩加明 王丽亚)》 (line 1526 - 1528)",
],
[
"人类要堕落，义士和圣女也都要堕落，这是不可阻挡的，也无法靠防止堕落来拯救人类。……并不是因为战败才堕落的。因为是人，所以堕落；因为活着，所以堕落。",
"这话乍一听似乎离经叛道，实际上不难理解其本意。安吾认为，特攻队员做黑市买卖（生存）、遗孀找寻第二春（情感），是人性之必然，再合理不过。而日本的政治家———从平安时代的贵族，到二战期间的军部———为了维护自身的统治，编造出种种谎言，用节妇烈女、忠臣孝子的幻影来压抑人性。",
"—— 《堕落论([日]坂口安吾)》 (line 42 - 43)",
],
[
"只听石清缓缓道：“你我二人行侠江湖，生平没做过亏心之事。这几年来为了要保玉儿平安，更竭力多行善举，倘若老天爷真要我二人无后，那也是人力不可胜天。何况像玉儿这样的不肖孩儿，无子胜于有子。咱们算是没生这个孩儿，也就是了。”",
"闵柔低声道：“玉儿虽从小顽皮淘气，他⋯⋯他还是我们的心肝宝贝。总是为了坚儿惨死人手，咱们对玉儿特别宠爱了些，才成今日之累，可是⋯⋯可是我也始终不怨。那日在那小庙之中，我瞧他也决不是坏到了透顶，倘若不是我失手刺了他一剑，也不会⋯⋯也不会⋯⋯”说到这里，语音呜咽，自伤自艾，痛不自胜。",
"—— 《侠客行+越女剑(新修版)(金庸)》 (line 1993 - 1994)",
],
[
"remain there and still be tended with care for many days.",
"‘The Lady Éowyn,’ said Aragorn, ‘will wish soon to rise and depart; but she should not be permitted to do so, if you can in",
"—— 《The Lord of the Rings - The classic fantasy masterpiece(J.R.R. Tolkien)》 (line 21360 - 21361)",
],
[
"论社会权力之于个人的限度",
"然则，个人之于自己的主权，其正当界限在哪里？社会的权力又该从哪里开始？人类生活，哪些应该听其自谋，哪些应该委诸社会？",
"如果个人与社会都有其各自特别关切之事，它们就该接受各自固有的部分。凡是生活中大体关系个人利害的事情，就该属于个性；而凡是主要关系社会利害的事情，就该属于社会。",
"尽管社会并非立于契约之上，并且即便发明一项契约使各种社会义务尽出于此也于事无益，但既然每个人都受到社会的保护，就应该对社会有所回报，而且既然事实上每个人都要在社会中生活，就不得不在事关他人的行为上遵守一定的界限。首先，个人行为不得损害彼此的利益，更确切地说，不得损害法律明确规定或公众默示应予视作权利的正当利益；其次，为保卫社会及其成员免遭外侵及内乱，人人都须（在某种公平的原则下）共同分担此项必须的力役与牺牲。如果社会成员竭力拒绝履行这些义务，则社会就可以理直气壮地强制其履行而在所不惜。且社会可做之事不止于此。个人行为即便没有达到侵犯他人任何法定权利的程度，也可能会对他人造成伤害，或者因考虑不周而对他人不利。如此，则行事者虽不至于要受到法律的绳范，也理所当然地要受到舆论的制裁。只要个人行为的任何部分有损他人利益，社会对此就有了裁夺的正当权力，而这种干涉是否能够提高社会的总体福利也要成为公开讨论的话题。但是当一个人的行为，其利害仅止于自身而不关涉他人，或虽有影响也是出于他们自愿（注意这里所谈及的个人都是指已经成年且具有一般是非常识的人），则上述所论于此迄无用武之地。在一切此类情境之下，他们都该完全不受法律和社会的束缚而自由行动，并且自得其乐或自食其果。",
"—— 《论自由(John Stuart Mill)》 (line 165 - 168)",
],
[
"臣　甲　不要这样瞧着我，我的好爵爷，他就会说起您的。",
"兵士甲　公爵对他的信用怎样？",
"帕　洛　公爵只知道他是我手下的一个下级军官，前天还写信给我叫我把他开革；我想他的信还在我的口袋里呢。",
"兵士甲　好，我们来搜。",
"帕　洛　不瞒您说，我记得可不大清楚，也许它在我口袋里，也许我已经把它跟公爵给我的其余的信一起放在营里归档了！",
"—— 《莎士比亚全集》 (line 12392 - 12396)",
],
[
"“You’re lucky I was able to even salvage that, much less get the remote systems online to pilot it from here,” David said, irritated. “And that ‘gaping hole’ is where your Aquaman left my father to die!”",
"—— 《大电影双语阅读.海王 Aquaman(华纳兄弟娱乐公司)》 (line 358)",
],
[
"视线之外，运货马车吱吱呀呀地驶下蓝石路。里面没有人开口。大车已经把婴儿摇晃得睡着了。炎热的太阳晒干了塞丝的裙子，硬挺挺的，仿佛尸僵。",
"那不是她的嘴。",
"素不相识的人，或者也许只从餐馆的门洞里瞥见过她一眼的人，可能会认为那是她的嘴，但是这事保罗·D更明白。噢，的确，前额上还笼罩着那么一点东西——一种安详——能使你想起她来。可是你单凭这个就说那是她的嘴，那可不行，于是他就这样讲了。告诉了正在审视他的斯坦普·沛德。",
"—— 《宠儿(托妮•莫里森)》 (line 1355 - 1357)",
],
[
"“Are you listening, Geoffrey?”",
"“Yes, my darling.”",
"<em>He said to Gyges: “Gyges, I think that you do not believe me when I tell you of the beauty of my wife, for it happens that men’s ears are less apt of belief than their eyes. Contrive therefore means by which you may look upon her naked.”</em>",
"—— 《The English Patient (Vintage International)(Michael Ondaatje)》 (line 1340 - 1342)",
],
[
"长城的最初修建年代已无从考证，但它的建成年代据查是在公元前三百年。从那时起，中华帝国的历史便世代相传，中间没有空白期。中国历史悠久，有无数官方文件和私人著作可以佐证。世界上其他国家都不像中国那样注意保留历史材料，也没有人像中国学者那样认真地把历史当作一门专业来研究。中国几乎每个大城市都有自己的历史记录。无数历史著作中关于长城的记载，无论是当时的资料记录，还是后来者的文献考据，堪称是汗牛充栋，理据充分，因此我们没有理由怀疑这个耗费千百万人毕生精力建造的长城历史年代的可靠性。历史的真实性首先根据当代作家的信誉，其次依靠读者掌握的材料来进行核对。重考据的作家会依照这种方法对前代作家的著作进行严格的推演追溯，这样证明出来的史料真实性是绝对可信的。我们不能根据自己的主观臆断来加以揣测，只能相信历史事实。根据同样的方法和理由，我们不能怀疑罗马帝国是否存在，也不能怀疑诺曼征服者是否曾入侵英国，以及亚克兴海战[4]的事实。",
"—— 《英使谒见乾隆纪实(George Leonard Staunton)》 (line 1097)",
],
[
"“Good luck,” he sneered. “It’s internally wired.”",
"“I’ll figure something out,” she said.",
"Peter was running down the corridor with the prisoner’s leg, back out to where the others were, when he was spotted by a guard. “Drop the leg!” the guard shouted, his gun leveled at Peter. “Drop the leg and move back to your cell!”",
"—— 《大电影双语阅读. Guardians of the Galaxy 银河护卫队(美国漫威公司)》 (line 449 - 451)",
],
[
"第二十二类　炼丹骗",
"深地炼丹置长符",
"古有炼丹之说，点铁成金，盖仙方，非人世有也。世所传炼丹之术，用好纹银三两，杂诸铅汞辰朱砂药物，在炉同炼，每次须炼四十九日。至四十日后，须两人轮番守炉，昼夜不得暂时离守。丹成可得九两，内除三两银本，要三两买药物，每次只出三两，一年可炼四次，共可得十二两，仅足供两人食用。故真得此方者，亦不屑为。其炼出丹银，亦可经煎，每次渐渐亏少，复归于无。但此银第二次，不可为银母。若再炼，须另以纹银为母。此相传真方，费心费工，甚不易为。若云游方士，托炼丹为名，以行骗者，用砒霜雄黄诸物，炒好银为灰砂，假称曰丹头，然后将此与好银同煎。仍煎成银，彼便道丹药可点成银。此个是弄假行骗之套子。",
"—— 《杜骗新书(明•张应俞)》 (line 455 - 457)",
],
];
