var quote31_global=[
[
"丹尼尔在1725年（25岁时）成了圣彼得堡的数学教授。他非常讨厌圣彼得堡的相对粗野的生活，一有机会（8年后）就回到巴塞尔，在那里担任解剖学和植物学教授，最后任物理学教授。他的数学工作包括微积分学、微分方程、概率、弦振动理论、气体动理学理论的一次尝试，以及应用数学中的许多其他问题。丹尼尔·伯努利被称为数理物理学的奠基人。",
"从遗传的观点看，指出丹尼尔的天性中有思辨哲学的显著气质是有意义的，他这种气质也许是他祖先的胡格诺教派信仰的理想化。同样的气质也出现在受宗教迫害的著名流亡者们的众多后代身上。",
"—— 《数学大师：从芝诺到庞加莱(哲人石珍藏版)(埃里克•坦普尔•贝尔)》 (line 733 - 734)",
],
[
"做好网上舆论工作是一项长期任务，要创新改进网上宣传，运用网络传播规律，弘扬主旋律，激发正能量，大力培育和践行社会主义核心价值观，把握好网上舆论引导的时、度、效，使网络空间清朗起来。",
"网络信息是跨国界流动的，信息流引领技术流、资金流、人才流，信息资源日益成为重要生产要素和社会财富，信息掌握的多寡成为国家软实力和竞争力的重要标志。信息技术和产业发展程度决定着信息化发展水平，要加强核心技术自主创新和基础设施建设，提升信息采集、处理、传播、利用、安全能力，更好惠及民生。",
"—— 《习近平谈治国理政（第一卷简体中文版）(习近平)》 (line 943 - 944)",
],
[
"阿瑄是在为首的官员之后第三个人，在他正跳到车上时，一个两磅重的圆石头打中他的头，把他打昏，跌到地上。幸而别的人已经赶到，日本人不能再扔石头。一个日本人带着一把斧子，对准为首的人就劈下来，为首的人迅速一拳打中日本人的肚子，斧子落在车上。",
"赶骡子的中国人跑掉，车停住了。双方混战了片刻，后面的两个日本人和三个高丽人被制伏，捆缚起来。前面车上的日本人，因为喝了半醉，在六月的下午正在困倦，没有抵抗，束手就擒，用听不懂的日本话乱骂。",
"—— 《京华烟云(林语堂)》 (line 6117 - 6118)",
],
[
"“I suppose Trantor is heavily automated wherever possible and if anything calls for automation it would be this treatment of wastes,” said Dors. “We may be safe…for a while.”",
"—— 《Prelude to Foundation(Isaac Asimov)》 (line 4202)",
],
[
"第十一篇　农民在官僚政治下的社会经济生活",
"第十二篇　官僚政治对于中国社会长期停滞的影响",
"第十三篇　中国官僚政治在现代的转型",
"第十四篇　传统的旧官僚政治之覆败",
"第十五篇　新旧官僚政治的推移与转化",
"第十六篇　新官僚政治的成长",
"第十七篇　中国官僚政治的前途",
"—— 《中国官僚政治研究(王亚南)》 (line 16 - 22)",
],
[
"‘You said “All things serve the Beam.” I think that was it.’",
"‘Perhaps sometime I’ll tell you, but not today. Today you’re going to the beach, aren’t you?’",
"—— 《Stephen King Goes to the Movies: Featuring Rita Hayworth and Shawshank Redemption(Stephen King)》 (line 1190 - 1191)",
],
[
"二〇　郎中窦武，融之玄孙也，有女为贵人。采女田圣有宠于帝，帝将立之为后。司隶校尉应奉上书曰：“母后之重，兴废所因；汉立飞燕，胤礼泯绝。宜思关雎之所求，远五禁这所忌。”太尉陈蕃亦以田氏卑微，窦族良家，争之甚固。帝不得已，辛巳，立窦贵人为皇后，拜武为特进、城门校尉，封槐里侯。",
"二一　十一月，壬子，黄门北寺火。",
"—— 《资治通鉴》 (line 5342 - 5343)",
],
[
"“他没有痛苦……走得很安详，”她说，“我对此深表遗憾。”",
"“是墨菲吗？”布兰德声音空洞地问道。",
"库珀点了点头，见墨菲伸手要将摄像头关掉，又想找些话说。",
"“她长成了——”布兰德博士刚说了一半便又停下，因为墨菲并没有关掉摄像头。她将手收回，脸上浮现一种奇怪的神情，像是瞬间爆发的强烈怒火。",
"“你知道吗，布兰德博士？”她愤怒地质问道，“他告诉你真相了吗？你知道A计划是个骗局吗？你知道的，对不对？你们把我们扔在这里，等死。",
"—— 《大电影双语阅读.星际穿越 Interstellar(华纳兄弟娱乐公司)》 (line 4583 - 4587)",
],
[
"And caught the silver harp away,",
"And, weeping over the white strings, hurled",
"It down in a leaf-hid, hollow place",
"That kept dim waters from the sky;",
"And each one said, with a long, long sigh,",
"—— 《Poems by W. B. Yeats》 (line 4033 - 4037)",
],
[
"'I looked about me to see if any traces of animal life remained. A certain indefinable apprehension still kept me in the saddle of the machine. But I saw nothing moving, in earth or sky or sea. The green slime on the rocks alone testified that life was not extinct. A shallow sandbank had appeared in the sea and the water had receded from the beach. I fancied I saw some black object flopping about upon this bank, but it became motionless as I looked at it, and I judged that my eye had been deceived, and that the black object was merely a rock. The stars in the sky were intensely bright and seemed to me to twinkle very little.",
"—— 《The Time Machine》 (line 293)",
],
[
"“该怎么说呢，或许因为我是笨蛋才有这种想法吧，不过我在学校跟聪明的家伙说话时，对方经常会用一些莫名艰深的字句，引用一些我不想知道的典故，让我怀疑对方到底聪不聪明。不过翼姐姐虽然头脑很好，却会和我用相同的立场说话，这让我觉得好窝心。”",
"“没错。”",
"月火妹妹也如此附和。",
"她在浴室解开辫子，就看得出头发好长。",
"这孩子留头发的速度，似乎更胜于神原学妹。",
"—— 《物语系列：猫物语.白(西尾维新)》 (line 2314 - 2318)",
],
[
"同室的三名女犯相继被提走，监室里只剩叶文洁一个人了。墙角的那一小堆煤用完了也没人来加，炉子很快灭了，监室里冷了下来，叶文洁不得不将被子裹在身上。",
"天黑前来了两个人，其中一名是年长些的女干部，随行的那人介绍说她是中级法院军管会的军代表。",
"“程丽华。”女干部自我介绍说，她四十多岁，身穿军大衣，戴着一副宽边眼镜，脸上线条柔和，看得出年轻时一定很漂亮，说话时面带微笑，让人感到平易近人。叶文洁清楚，这样级别的人来到监室见一个待审的犯人，很不寻常。她谨慎地对程丽华点点头，起身在狭窄的床铺上给她让出坐的地方。",
"—— 《三体(刘慈欣)》 (line 757 - 759)",
],
[
"次立十七年薨，子鸾嗣。鸾薨，子政嗣。政薨，无子，建安十一年，国除。",
"河闲孝王开，以永元二年封，分乐成、勃海、涿郡为国。延平元年就国。开奉遵法度，吏人敬之。永宁元年，邓太后封开子翼为平原王，奉怀王胜祀；胜，和帝子。子德为安平王，奉乐成王党祀。党，明帝子也。",
"开立四十二年薨，子惠王政嗣。政慠佷，不奉法宪。顺帝以侍御史吴郡沈景有强能称，故擢为河闲相。景到国谒王，王不正服，箕踞殿上。侍郎赞拜，景峙不为礼。峙，立也。问王所在，虎贲曰：“是非王邪？”景曰：“王不服，常人何别！今相谒王，岂谒无礼者邪！”王惭而更服，景然后拜。出住宫门外，请王傅责之曰：“前发京师，陛下见受诏，以王不恭，使检督。诸君空受爵禄，而无训导之义。”因奏治罪。诏书让政而诘责傅。景因捕诸奸人上案其罪，上，奏上也，音市丈反。杀戮尤恶者数十人，出冤狱百余人。政遂为改节，悔过自修。阳嘉元年，封政弟十三人皆为亭侯。",
"—— 《后汉书(范晔)》 (line 4307 - 4309)",
],
[
"***",
"These lusty, ruddy vocalists were among the first English-speaking prisoners to be taken in the Second World War. Now they were singing to nearly the last. They had not seen a woman or a child for four years or more. They hadn’t seen any birds, either. Not even sparrows would come into the camp.",
"—— 《Slaughterhouse-Five(Kurt Vonnegut)》 (line 724 - 725)",
],
[
"道德与法律如何对待",
"婚外性交合的作用与意义",
"第二十五章　同性性反应与性接触",
"生理基础与历史状况",
"年龄和婚姻状况的作用",
"教育、时代和宗教的作用",
"女人同性性接触的技巧",
"测定同性性行为的程度",
"同性性行为在社会中的处境",
"第二十六章　与动物的性接触",
"—— 《金赛性学报告(男人篇&女人篇)》 (line 177 - 186)",
],
[
"朋友，君子尚可以欺以其方，何况一个幽居深宫、糊涂无知的小寡妇。说穿了，袁世凯也是在欺君罔上，但是欺君以方，比弒君砍头，究竟还要文明得多。后来小皇帝溥仪长大了，回忆起这时的情况，他记得太后在哭，跪在她面前的一个老头子，也泪流满面（见溥仪著《我的前半生》，第二章，第一节）。这时太后的确在哭；老头子泪流满面，就是在演戏了。",
"据说老头子这时就告诉太后，革命军无孔不入，是如何的厉害；孙文三头六臂，是如何的有钱。这次他带回海外华侨的捐款数千百万。官军粮饷皆缺，如何能和孙文打仗？寡妇太后一听，怎能不哭？太后一哭，老宰相事君无力，怎能不一掬同情之泪？",
"—— 《袁氏当国(唐德刚)》 (line 220 - 221)",
],
[
"第九十七回　假弟妹暗續鸞膠　真夫婦明諧花燭",
"詞曰：",
"追悔當初辜深願，經年價，兩成幽怨。任越水吳山，似屏如障堪游玩，奈獨自慵抬眼。 賞煙花，聽弦管，徒歡娛，轉加腸斷。總時轉丹青，強拈書信頻頻看，又曾似親眼見。",
"話說陳敬濟，到於守備府中，下了馬，張勝先進去稟報春梅。春梅分付，教他在外邊班直房內，用香湯沐浴了身體，後邊使養娘包出一套新衣服靴帽來，與他更換了。然後稟了春梅。那時守備還未退廳，春梅請敬濟到後堂，盛妝打扮，出來相見。這敬濟進門就望春梅拜了四雙八拜，讓姐姐受禮。那春梅受了半禮，對面坐下。敘了寒溫離別之情，彼此皆眼中垂淚。春梅恐怕守備退廳進來，見無人在根前，使眼色與敬濟，悄悄說：“等住回他若問你，只說是姑表兄弟。我大你一歲，二十五歲了，四月廿五日午時生的。”敬濟道：“我知道了。”不一時，丫鬟拿上茶來，兩人吃了茶，春梅便問：“你一向怎麼出了家做了道士？守備不知是我的親，錯打了你，悔的要不的。若不是那時就留下你，爭奈有雪娥那賤人在這裡，不好安插你的。所以放你去了。落後打發了那賤人，才使張勝到處尋你不著，誰知你在城外做工，流落至此地位。”敬濟道：“不瞞姐姐說，一言難盡。自從與你相別，要娶六姐，我父親死在東京，來遲了，不曾娶成，被武鬆殺了。聞得你好心，葬埋了他永福寺，我也到那裡燒紙來。落後又把俺娘沒了，剛打發喪事出去，被人坑陷了資本。來家又是大姐死了，被俺丈母那淫婦告了一狀，床帳妝奩，都搬的去了。打了一場官司，將房兒賣了，弄的我一貧如洗。多虧了俺爹朋友王杏庵周濟，把我才送到臨清晏公廟那裡出家。不料又被光棍打了，拴到咱府中。自從咱府中出去，投親不理，投友不顧，因此在寺內佣工。多虧姐姐掛心，使張管家尋將我來，得見姐姐一面，猶如再世為人了。”說到傷心處，兩個都哭了。",
"—— 《金瓶梅》 (line 2469 - 2472)",
],
[
"我们只看西汉初年晁错所讲移民殖边的一切规划，便可想象到西周当年向东封建的大概情形了。这也是我们中国民族拥有深远伟大的历史经验之一例。两汉的屯田，不仅在边塞，而且还深入到国外。这是尽人所知的。东汉只为罢免了西域的屯田，才引起边塞动乱，而逐渐地蔓延到全中国。",
"其实西魏、北周和隋唐的府兵制，也即是屯田制度变相的运用。屯田主要在戍守边疆和控领国外，而府兵则在内地屯田。而唐代的边外屯田，北方远至瀚海都护府，东北远至百济，西北远至西域及青海，国力远扩，这是如影随形，必然不可少的一制度。宋代积弱，其最大原因之一，便是把经济生产和武装战斗的两系统分开了。宋代禁军，分番戍边，仆仆道途，却没有在边境上扎下来屯田。宋代的厢军，只在地方充劳役，当杂差，也没有教他们耕作与生产。只因这一制度之颓废，便影响到全部国力。",
"—— 《中国历史精神 (钱穆国学作品集（套装共10册） 4)(钱穆)》 (line 287 - 288)",
],
[
"第十四回　花子虛因氣喪身　李瓶兒迎姦赴會",
"詩曰：",
"眼意心期未即休，不堪拈弄玉搔頭。春回笑臉花含媚，黛蹙娥眉柳帶愁。 粉暈桃腮思伉儷，寒生蘭室盼綢繆。何如得遂相如意，不讓文君詠白頭。",
"話說一日吳月娘心中不快，吳大妗子來看，月娘留他住兩日。正陪在房中坐的，忽見小廝玳安抱進氈包來，說：“爹來家了。”吳大妗子便往李嬌兒房裡去了。西門慶進來，脫了衣服坐下。小玉拿茶來也不吃。月娘見他面色改常，便問：“你今日會茶，來家恁早？”西門慶道：“今該常二哥會，他家沒地方，請俺們在城外永福寺去耍子。有花二哥邀了應二哥，俺們四五個，往院里鄭愛香兒家吃酒。正吃著，忽見幾個做公的進來，不由分說，把花二哥拿的去了。把眾人嚇了一驚。我便走到李桂姐躲了半日，不放心，使人打聽。原來是花二哥內臣家房族中告家財，在東京開封府遞了狀子，批下來，著落本縣拿人。俺們才放心，各人散歸家來。”月娘聞言，便道：“這是正該的，你整日跟著這夥人，不著個家，只在外邊胡撞；今日只當丟出事來，才是個了手。你如今還不心死。到明日不吃人掙鋒廝打，群到那日是個爛羊頭，你肯斷絕了這條路兒！正經家裡老婆的言語說著你肯聽？只是院里淫婦在你跟前說句話兒，你到著個驢耳朵聽他。正是：家人說著耳邊風，外人說著金字經。”西門慶笑道：“誰人敢七個頭八個膽打我！”月娘道：“你這行貨子，只好家裡嘴頭子罷了。”",
"—— 《金瓶梅》 (line 338 - 341)",
],
[
"德国新教高度主观的这一翼，在摩拉维安兄弟会，在如下这些人的神秘主义当中，可以找到其相似物，他们包括雅各比·伯麦的英国弟子（如波戴奇）、魏格尔、阿恩特，以及18世纪的威廉·劳、卫理公会教派的传教士——卫斯理兄弟与怀特菲尔德——史威登堡及其弟子（如威廉·布莱克）的追随者。它在斯堪的纳维亚、英国和美国，在法国和德国的共济会和玫瑰十字会的分会中广泛传播。德国的虔敬派因个人的情感主义，特别是17世纪下半叶阴郁清教徒式的谦卑和苦行，以及对此世快乐特别是世俗艺术530的坚决反对（日内瓦、苏格兰和英格兰的加尔文派也曾因其而闻名）而引人注目。",
"—— 《启蒙的三个批评者([英国]以赛亚·伯林)》 (line 515)",
],
[
"革命初期，人们害怕它会像一九〇五年革命那样，唯恐这次革命也是有教养的上层分子历史中的一个短暂的事件，不能深入到底层，也不能在他们当中牢靠地占据一席之地，只有竭尽全力说服群众，鼓吹革命，把他们搅得慌乱惊恐，怒气冲天，让他们不得安宁。",
"在革命最初的一段日子里，像士兵帕姆菲尔这样的人，不需要任何鼓动，便能够像极端疯狂的野兽一样仇恨知识分子、老爷和军官，成了狂热左派知识分子不可多得的宝贵力量，身价百倍。他们的暴虐被看作是阶级意识的奇迹，他们的野蛮行为则成了无产阶级的坚毅和革命本能的典范。帕姆菲尔的荣誉就是这样巩固起来的。他在游击队的头头们和党的领导者们那儿也有如此的好名声。尤里·安德烈耶维苛却觉得这个阴郁的、反社会主义的大力士是个不完全正常的孬种，因为他冷酷无情，单调乏味，他所从事的事业同污秽的东西又十分亲近。",
"—— 《日瓦戈医生(帕斯捷尔纳克)》 (line 2802 - 2803)",
],
[
"<i>SCRAMBLES AMONGST THE ALPS</i>",
"We sleep to time’s hurdy-gurdy; we wake, if we ever wake, to the silence of God. And then, when we wake to the deep shores of time uncreated, then when the dazzling dark breaks over the far slopes of time, then it’s time to toss things, like our reason, and our will; then it’s time to break our necks for home.",
"—— 《Into the Wild (Picador Classic)(Jon Krakauer)》 (line 985 - 986)",
],
[
"和尚剪绢调佃妇",
"地理寄妇脱好种",
"奸人婢致盗去银",
"奸牙人女被脱骗",
"第十八类　妇人骗",
"哄婶成奸骗油客",
"爬灰复骗奸姻母",
"佃妇卖奸脱主田",
"三妇骑走三匹马",
"尼姑撒珠以诱奸",
"第十九类　拐带骗",
"—— 《杜骗新书(明•张应俞)》 (line 75 - 85)",
],
[
"The robot shook his head, ‘I don’t know. One moment I was handling a tough outcropping in Tunnel 17, and the next I was aware of humans close by, and I found myself half a mile down main-stem.’",
"—— 《I, Robot(Isaac Asimov)》 (line 898)",
],
[
"上海钦州南路81号 　电话／传真：64515005",
"网址：www.xuelinpress.com",
"责任编辑：岳拯士",
"特邀编辑：孟凡礼　吴晓斌",
"装帧设计：陆智昌",
"内文制作：陈基胜",
"理想国译丛序",
"“如果没有翻译，”批评家乔治·斯坦纳（George Steiner）曾写道，“我们无异于住在彼此沉默、言语不通的省份。”而作家安东尼·伯吉斯（Anthony Burgess）回应说，“翻译不仅仅是言词之事，它让整个文化变得可以理解。”",
"—— 《理想国译丛: “当代政治经济学巨擘”·2016全球思想领袖 弗朗西斯·福山作品集》 (line 11878 - 11885)",
],
[
"I found the Hab signal today. No more chance to get lost. According to the computer, I’m 24,718 meters away.",
"I’ll be home tomorrow. Even if the rover has a catastrophic failure, I’ll be fine. I can <i>walk</i> to the Hab from here.",
"—— 《The Martian(Andy Weir)》 (line 1245 - 1246)",
],
[
"没有人来欣赏",
"我想起一位四十多岁的乡村女老师",
"总是给大家看她年轻时的照片",
"连忧伤都那么无暇",
"花落无声，人面不见",
"不是每个人都可以",
"假装自己是童话里的仙子",
"远方",
"我住在山里",
"却将眼睛挂在天堂",
"假如",
"—— 《有只狐狸看月亮(李田田)》 (line 319 - 329)",
],
[
"“A good one?”",
"“I’d like to think so, but it’s a hard thing to guarantee.”",
"“And you’re interested in intractable problems?”",
"Seldon said feelingly, “I’m stuck with one.”",
"—— 《Prelude to Foundation(Isaac Asimov)》 (line 1128 - 1131)",
],
[
"Lidia Ivanovna’s dress had cost her great pains, as indeed all her dresses had done of late. Her aim in dress was now quite the reverse of that she had pursued thirty years before. Then her desire had been to adorn herself with something, and the more adorned the better. Now, on the contrary, she was perforce decked out in a way so inconsistent with her age and her figure, that her one anxiety was to contrive that the contrast between these adornments and her own exterior should not be too appalling. And as far as Alexey Alexandrovitch was concerned she succeeded, and was in his eyes attractive. For him she was the one island not only of goodwill to him, but of love in the midst of the sea of hostility and jeering that surrounded him.",
"—— 《Anna Karenina》 (line 4809)",
],
[
"“Some of the raptors followed us. We’ve got two on the roof now.”",
"“So what? The building’s impregnable.”",
"Muldoon coughed. “Apparently not. It was never expected that animals would get up on the roof.” The radio crackled, “—must have planted a tree too close to the fence. The raptors got over the fence, and onto the roof. Anyway, the steel bars on the skylight are supposed to be electrified, but of course the power’s off. They’re biting through the bars of the skylight.”",
"—— 《Jurassic Park: A Novel(Michael Crichton)》 (line 4375 - 4377)",
],
[
"“Nothing.”",
"Where does the blood on her skirt come from?",
"“From the fish.”",
"She stands up, tosses the knife aside, and walks off to wash.",
"And then, unexpectedly, the infant under the gutting table begins to squall. They have a look, and beneath a swarm of flies and amid the offal and fish heads they discover the newborn child. They pull it out. As prescribed by law, they give it to a wet nurse and arrest the mother. And since she confesses, openly admitting that she would definitely have let the thing perish, just as she had with those other four by the way, she is tried, found guilty of multiple infanticide, and a few weeks later decapitated at the place de Grève.",
"—— 《Perfume (Vintage International)(Patrick Suskind)》 (line 115 - 119)",
],
];
