var csbooklist_source_global=[
["anna_karenina_1223","Anna Karenina","englishwords,已整理","3",""],
["zi_zhi_tong_jian_138381","资治通鉴","历史,已整理","3",""],
["jiu_tang_shu_67933","旧唐书(刘昫等)","历史,已整理","3",""],
["hong_lou_meng_86212","红楼梦(曹雪芹)","五大名著,已整理","3",""],
["xi_xiang_ji_wang_shi_f_92369", "西厢记(王实甫)","已整理","3",""],
["zhao_shi_gu_er_yuan_jjx_108071", "赵氏孤儿(（元）纪君祥)","已整理","3",""],
["dou_e_yuan_guan_han_q_75375", "窦娥冤(关汉卿)","已整理","3",""],
["po_you_meng_gu_yan_hgqymzy_226107", "破幽梦孤雁汉宫秋(（元）马致远)","已整理","3",""],
["pi_pa_ji_yuan_gao_m_95259", "琵琶记(（元）高明)","已整理","3",""],
["zhang_sheng_dian_qing_hong_s_95837", "长生殿(（清）洪昇)","已整理","3",""],
["sheng_jing_he_he_ben_124338","圣经和合本","圣经,已整理,已读","3",""],
["bin_feng_guang_yi_qing_ys_119305", "豳风广义(清·杨屾)","已整理","3",""],
["ming_yi_dai_fang_lu_hzx_133598", "明夷待访录(黄宗羲)","已整理","3",""],
["ren_jian_ci_hua_130136","人间词话(王国维)","已整理","3",""],
["jin_gu_qi_guan_bao_wlr_207970","今古奇观(抱瓮老人)","已整理","3",""],
["ji_lin_zhang_duan_ju_qwgw_155566", "集林长短句(【清】王国维)","已整理","3",""],
["gu_shi_shi_jiu_shou_u_137967", "古诗十九首","诗词,已整理","3",""],
["wei_liao_zi_unknown_79494", "尉缭子","已整理","3",""],
["shi_shuo_xin_yu_liu_yq_117671","世说新语(刘义庆)","已整理","3",""],
["mu_dan_ting_tang_xian_z_154512","牡丹亭(汤显祖)","已整理","3",""],
["fen_shu_ming_li_zhi_49024", "焚书((明)李贽)","已整理","3",""],
["the_dunwich_horror_1711","The Dunwich Horror(H. P. Lovecraft)","已整理,englishwords","3",""],
["the_warden_trollope_anthony_2641","The Warden(Trollope,Anthony)","englishwords,已整理","3",""],
["tao_hua_shan_kong_shang_r_152565","桃花扇(孔尚任)","已整理","3",""],
["david_copperfield_1653","David Copperfield(Charles Dickens)","englishwords,已整理","3",""],
["little_women_1172","Little Women(Louisa May Alcott)","englishwords,已整理","3",""],
["frankenstein_1256", "Frankenstein(Mary Wollstonecraft Shelley)","englishwords,已整理","3",""],
["chambers_s_twentieth_century_dictionary_p4o4szas_6663", "Chambers's Twentieth Century Dictionary (part 4 of 4: S-Z and supplements)","en_minor,已整理","3",""],
["chambers_s_twentieth_century_dictionary_p3o4nr_5062", "Chambers's Twentieth Century Dictionary (part 3 of 4: N-R)","en_minor,已整理","3",""],
["chambers_s_twentieth_century_dictionary_p2o4em_5047", "Chambers's Twentieth Century Dictionary (part 2 of 4: E-M)","en_minor,已整理","3",""],
["chambers_s_twentieth_century_dictionary_p1o4ad_5033", "Chambers's Twentieth Century Dictionary (part 1 of 4: A-D)","en_minor,已整理","3",""],
["lao_zi_li_er_56145", "老子(李耳)","已整理","3",""],
["sheng_lv_qi_meng_che_wy_102723", "声律启蒙(车万育)","诗词,已整理","3",""],
["hou_han_shu_fan_ye_69309", "后汉书(范晔)","历史,已整理","3",""],
["xi_hu_meng_xun_zhang_d_113782", "西湖梦寻(张岱)","已整理","3",""],
["lao_can_you_ji_liu_e_185908","老残游记(刘鹗)","已整理","3",""],
["liao_shi_ji_shi_ben_mldjsbm_310689","辽史纪事本末 (历代纪事本末)(清•李有棠)","历史,已整理","3",""],
["jin_shi_ji_shi_ben_mldjsbm_311221","金史纪事本末 (历代纪事本末)(清•李有棠)","已整理","3",""],
["er_shi_nian_mu_du_zgxzwjr_308350","二十年目睹之怪现状(吴趼人)","已整理","3",""],
["around_the_world_in_80_dmfgbs_129587", "Around the World in 80 Days(Verne,Jules)","englishwords,已整理","3",""],
["the_call_of_the_wild_1731", "The Call of the Wild(Jack London)","englishwords,已整理","3",""],
["a_princess_of_mars_1616","A Princess of Mars","englishwords,已整理","3",""],
["the_mysterious_island_2048","The Mysterious Island","englishwords,已整理","3",""],
["metamorphosis_1387", "Metamorphosis(Franz Kafka)","englishwords,已整理","3",""],
["the_complete_works_of_william_s_3872","The Complete Works of William Shakespeare","englishwords,已整理","3",""],
["jane_eyre_819","Jane Eyre","englishwords,已整理","3",""],
["in_search_of_the_castaways_otcocg_5418","In Search of the Castaways; or the Children of Captain Grant","englishwords,已整理","3",""],
["a_journey_to_the_centre_ote_3228","A Journey to the Centre of the Earth","englishwords,已整理","3",""],
["the_war_of_the_worlds_whg_2795","The War of the Worlds(Wells,H. G.)","englishwords,幻想,已整理","3",""],
["twenty_thousand_leagues_under_the_sautotw_6548","Twenty Thousand Leagues Under the Seas: An Underwater Tour of the World","englishwords,已整理","3",""],
["jean_christophe_in_paris_the_mpath_5878","Jean Christophe: in Paris The Market-Place, Antoinette, the House, by Romain Rolland","englishwords,已整理","3",""],
["jean_christophe_journey_s_end_2721","Jean-Christophe Journey's End, by Romain Rolland","englishwords,已整理","3",""],
["jean_christophe_volume_i_mian_fgbs_129538","Jean-Christophe, Volume I, by Romain Rolland","englishwords,已整理","3",""],
["the_federalist_papers_1999","The Federalist Papers","englishwords,已整理","3",""],
["pride_and_prejudice_1794","Pride and Prejudice","englishwords,已整理","3",""],
["the_time_machine_1445","The Time Machine","englishwords,幻想,已整理","3",""],
["jing_shi_tong_yan_127894","警世通言(冯梦龙)","已整理","3",""],
["yu_shi_ming_yan_103391","喻世明言","已整理","3",""],
["feng_shen_yan_yi_103100","封神演义(许仲琳)","已整理","3",""],
["xi_you_ji_99175","西游记(吴承恩)","五大名著,已整理","3",""],
["liao_zhai_zhi_yi_107694","聊斋志异(蒲松龄)","幻想,已整理","3",""],
["shui_hu_chuan_75942","水浒传(施耐庵)","五大名著,已整理","3",""],
["san_guo_yan_yi_90723","三国演义(罗贯中)","五大名著,已整理","3",""],
["qing_lou_meng_zhong_guo_gdwxmzcs_322109", "青楼梦(慕真山人)","已整理","3",""],
["song_shi_yan_yi_93402","宋史演义(蔡东藩)","","3",""],
["su_shi_ji_108817","苏轼集","诗词","3",""],
["qian_jia_shi_80592","千家诗(张居正)","诗词","3",""],
["gu_wen_guan_zhi_110223","古文观止(吴楚材 & 吴调侯)","","3",""],
["dong_zhou_lie_guo_zhi_109423","东周列国志(冯梦龙)","历史","3",""],
["han_shu_ban_gu_47791","汉书(班固)","历史","3",""],
["bible_kjv_890","Bible(kjv)","englishwords,圣经,已整理","3",""],
["han_fei_zi_101015","韩非子","","3",""],
["shi_jing_68262","诗经","诗词","3",""],
["shi_ji_57250","史记","历史","3",""],
["dong_jing_meng_hua_lu_myl_189701","东京梦华录(孟元老)","","3",""],
];
