var csbooklist_source_global=[
["the_republic_1143", "The Republic(Plato)","已整理,englishwords","3",""],
["mariner_mission_to_venus_2308", "Mariner Mission to Venus(Jet Propulsion Laboratory)","已整理,englishwords","3",""],
["the_battle_for_khe_sanh_2022", "The Battle for Khe Sanh(Moyers S. Shore)","已整理,englishwords","3",""],
["the_art_of_war_1191", "The Art of War(active 6th century B.C. Sunzi)","已整理,englishwords","3",""],
["gulliver_s_travels_into_several_rrotw_5554", "Gulliver's Travels into Several Remote Regions of the World(Jonathan Swift)","已整理,englishwords","3",""],
["new_atlantis_1162", "New Atlantis(Francis Bacon)","已整理,englishwords","3",""],
["autobiography_of_benjamin_franklin_3308", "Autobiography of Benjamin Franklin(Benjamin Franklin)","已整理,englishwords","3",""],
["the_oriental_rug_a_monograph_oera_4518", "The Oriental Rug  A Monograph on Eastern Rugs and...(William De Lancey Ellwanger)","已整理,englishwords","3",""],
["a_history_of_caricature_and_gilaa_5487", "A History of Caricature and Grotesque in Literature and Art(Thomas Wright)","已整理,englishwords","3",""],
["history_of_lace_1404", "History of Lace(Mrs. Bury Palliser)","已整理,englishwords","3",""],
["the_practice_and_science_of_d_3194", "The Practice and Science of Drawing(Harold Speed)","已整理,englishwords","3",""],
["the_notebooks_of_leonardo_da_vc_12201", "The Notebooks of Leonardo Da Vinci — Complete(da Vinci Leonardo)","已整理,englishwords","3",""],
["women_in_the_fine_arts_ftscbctttcad_7342", "Women in the fine arts, from the Seventh Century B.C. to the Twentieth Century A.D.(Clara Erskine Clement Waters)","已整理,englishwords","3",""],
["what_is_art_1014", "What Is Art?(graf Leo Tolstoy)","已整理,englishwords","3",""],
["the_renaissance_studies_in_art_ap_3855", "The Renaissance: Studies in Art and Poetry(Walter Pater)","已整理,englishwords","3",""],
["the_dor_bible_gallery_complete_cohsiaapoelpfe_11922", "The Doré Bible Gallery, Complete  Containing One Hundred Superb Illustrations, and a Page of Explanatory Letter-press Facing Each(Unknown)","已整理,englishwords","3",""],
["bell_s_cathedrals_the_cathedral_corashotcaadoif_9886", "Bell's Cathedrals- The Cathedral Church of Ripon  A Short History of the Church and a Description of Its Fabric(Cecil Walter Charles Hallett)","已整理,englishwords","3",""],
["the_ten_books_on_architecture_2694", "The Ten Books on Architecture(Vitruvius Pollio)","已整理,englishwords","3",""],
["how_france_built_her_cathedrals_asittatc_7320", "How France Built Her Cathedrals- A Study in the Twelfth and Thirteenth Centuries(Elizabeth Boyle O'Reilly)","已整理,englishwords","3",""],
["architecture_1251", "Architecture(Henry-Russell Hitchcock)","已整理,englishwords","3",""],
["the_seven_lamps_of_architecture_2903", "The Seven Lamps of Architecture(John Ruskin)","已整理,englishwords","3",""],
["ancient_monuments_of_the_mississippi_vsctkvi_8621", "Ancient Monuments of the Mississippi Valley  Smithsonian Contributions to Knowledge, Vol. I.(E. G. Squier)","已整理,englishwords","3",""],
["history_of_egypt_chaldea_syria_baaitlord_8040", "History of Egypt, Chaldea, Syria, Babylonia, and Assyria in the Light of Recent Discovery(L. W. King)","已整理,englishwords","3",""],
["an_introduction_to_the_study_otmh_4890", "An Introduction to the Study of the Maya Hieroglyphs(Sylvanus Griswold Morley)","已整理,englishwords","3",""],
["all_about_coffee_1436", "All About Coffee(William H. Ukers)","已整理,englishwords","3",""],
["encyclopedia_of_needlework_2549", "Encyclopedia of Needlework(Thérèse de Dillmont)","已整理,englishwords","3",""],
["the_strange_case_of_dr_jamh_3647", "The Strange Case of Dr. Jekyll and Mr. Hyde(Robert Louis Stevenson)","已整理,englishwords","3",""],
["simple_sabotage_field_manual_2610", "Simple Sabotage Field Manual(United States. Office of Strategic Services)","已整理,englishwords","3",""],
["memoirs_of_fanny_hill_a_nageftotl1_7382", "Memoirs of Fanny Hill  A New and Genuine Edition from the Original Text (London, 1749)(John Cleland)","已整理,englishwords","3",""],
["emmajane_austen_384", "Emma(Jane Austen)","已整理,englishwords","3",""],
["venus_in_furs_1224", "Venus in Furs(Ritter von Leopold Sacher-Masoch)","已整理,englishwords","3",""],
["the_satyricon_complete_10378", "The Satyricon — Complete(Petronius Arbiter)","已整理,englishwords","3",""],
["oliver_twist_1196", "Oliver Twist(Charles Dickens)","已整理,englishwords","3",""],
["lady_chatterley_s_lover_2209", "Lady Chatterley's lover(D. H. Lawrence)","已整理,englishwords","3",""],
["guang_zhi_yi_wang_shi_xm_81188", "广志绎(王士性(明))","已整理","3",""],
["politics_a_treatise_on_government_3192", "Politics- A Treatise on Government(Aristotle)","已整理,englishwords","3",""],
["deng_xiao_ping_wen_xuan_dsjqsw_220497", "邓小平文选第三卷(求是网)","已整理","3",""],
["japanese_girls_and_women_revised_aee_4948", "Japanese Girls and Women Revised and Enlarged Edition(Alice Mabel Bacon)","已整理,englishwords","3",""],
["san_xia_wu_yi_jian_tbbggdcs_287176", "三侠五义([清]石玉昆)","已整理,D版","3",""],
["qi_xia_wu_yi_zhong_ggdxspjwk_322508", "七侠五义(石玉昆)","已整理,D版","3",""],
["da_dai_li_ji_zhong_gzxsdzhjhj_114759", "大戴礼记(中国哲学书电子化计划)","已整理","3",""],
["twenty_thousand_leagues_under_the_sautotw_6548","Twenty Thousand Leagues Under the Seas: An Underwater Tour of the World","englishwords,已整理","3",""],
["adventures_of_huckleberry_finn_2913", "Adventures of Huckleberry Finn(Mark Twain)","已整理,englishwords","3",""],
["essays_of_michel_de_montaigne_c_11799", "Essays of Michel de Montaigne — Complete(Michel de Montaigne)","已整理,englishwords","3",""],
["deng_xiao_ping_wen_xuan_dyjqsw_220488", "邓小平文选第一卷(求是网)","已整理","3",""],
["deng_xiao_ping_wen_xuan_dejqsw_220628", "邓小平文选第二卷(求是网)","已整理","3",""],
["ben_hur_a_tale_of_tc_2472", "Ben-Hur - A tale of the Christ(Lew Wallace)","已整理,englishwords","3",""],
["a_child_s_history_of_tw_2671", "A Child's History of the World(V. M. Hillyer)","已整理,englishwords","3",""],
["the_pickwick_papers_1793", "The Pickwick Papers(Charles Dickens)","已整理,englishwords","3",""],
["meditations_1153", "Meditations(Emperor of Rome Marcus Aurelius)","已整理,englishwords","3",""],
["the_odyssey_rendered_into_english_pftuotwcrto_8375", "The Odyssey Rendered into English prose for the use of those who cannot read the original(Homer)","已整理,englishwords","3",""],
["down_and_out_in_the_mk_2949", "Down and Out in the Magic Kingdom(Cory Doctorow)","已整理,englishwords","3",""],
["grimms_fairy_tales_1738", "Grimms' Fairy Tales(Jacob Grimm)","已整理,englishwords","3",""],
["peter_panj_m_barrie_831", "Peter Pan(J. M. Barrie)","已整理,englishwords","3",""],
["anne_of_green_gables_1782", "Anne of Green Gables(L. M. Montgomery)","已整理,englishwords","3",""],
["beyond_good_and_evil_1805", "Beyond Good and Evil(Friedrich Wilhelm Nietzsche)","已整理,englishwords","3",""],
["on_the_duty_of_civil_d_3022", "On the Duty of Civil Disobedience(Henry David Thoreau)","已整理,englishwords","3",""],
["the_romance_of_lust_a_cven_4876", "The Romance of Lust - A classic Victorian erotic novel(Anonymous)","已整理,englishwords","3",""],
["the_prince_930", "The Prince(Niccolò Machiavelli)","已整理,englishwords","3",""],
["the_adventures_of_tom_sawyer_c_3527", "The Adventures of Tom Sawyer, Complete(Mark Twain)","已整理,englishwords","3",""],
["crime_and_punishment_1934", "Crime and Punishment(Fyodor Dostoyevsky)","已整理,englishwords","3",""],
["the_wonderful_wizard_of_oz_2406", "The Wonderful Wizard of Oz(L. Frank Baum)","已整理,englishwords","3",""],
["the_varieties_of_religious_experience_asihn_5699", "The Varieties of Religious Experience - A Study in Human Nature(William James)","已整理,englishwords","3",""],
["the_imitation_of_christ_2161", "The Imitation of Christ(à Kempis Thomas)","已整理,englishwords","3",""],
["ulyssesjames_joyce_760", "Ulysses(James Joyce)","已整理,englishwords","3",""],
["a_modest_proposal", "A Modest Proposal(Jonathan Swift)","已整理,englishwords","3",""],
["the_count_of_monte_cristo_i_3535", "The Count of Monte Cristo, Illustrated(Alexandre Dumas)","已整理,englishwords","3",""],
["the_brothers_karamazov_2134", "The Brothers Karamazov(Fyodor Dostoyevsky)","已整理,englishwords","3",""],
["great_expectations_1802", "Great Expectations(Charles Dickens)","已整理,englishwords","3",""],
["the_yellow_wallpaper_1925", "The Yellow Wallpaper(Charlotte Perkins Gilman)","已整理,englishwords","3",""],
["a_doll_s_house_1194", "A Doll's House(a play)","已整理,englishwords","3",""],
["the_importance_of_being_earnest_atcfsp_6207", "The Importance of Being Earnest - A Trivial Comedy for Serious People(Oscar Wilde)","已整理,englishwords","3",""],
["a_tale_of_two_cities_1719", "A Tale of Two Cities(Charles Dickens)","已整理,englishwords","3",""],
["draculabram_stoker_700", "Dracula(Bram Stoker)","已整理,englishwords","3",""],
["the_picture_of_dorian_gray_2370", "The Picture of Dorian Gray(Oscar Wilde)","已整理,englishwords","3",""],
["my_life_volume_1_9603", "My Life — Volume 1(Richard Wagner)","已整理,englishwords","3",""],
["alice_s_adventures_in_wonderland_3038", "Alice's Adventures in Wonderland(Lewis Carroll)","已整理,englishwords","3",""],
["history_of_tom_jones_a_f_3017", "History of Tom Jones, a Foundling(Henry Fielding)","已整理,englishwords","3",""],
["the_adventures_of_roderick_random_3115", "The Adventures of Roderick Random(T. Smollett)","已整理,englishwords","3",""],
["cranfordelizabeth_cleghorn_gaskell_815", "Cranford(Elizabeth Cleghorn Gaskell)","已整理,englishwords","3",""],
["the_expedition_of_humphry_clinker_3140", "The Expedition of Humphry Clinker(T. Smollett)","已整理,englishwords","3",""],
["the_adventures_of_ferdinand_count_fc_12855", "The Adventures of Ferdinand Count Fathom — Complete(T. Smollett)","已整理,englishwords","3",""],
["the_blue_castle_a_novel_2103", "The Blue Castle - a novel(L. M. Montgomery)","已整理,englishwords","3",""],
["the_enchanted_april_1763", "The Enchanted April(Elizabeth Von Arnim)","已整理,englishwords","3",""],
["middlemarch_1114", "Middlemarch(George Eliot)","已整理,englishwords","3",""],
["a_room_with_a_view_1558", "A Room with a View(E. M. Forster)","已整理,englishwords","3",""],
["moby_dick_or_the_whale_1996", "Moby Dick; Or, The Whale(Herman Melville)","已整理,englishwords","3",""],
["the_great_gatsby_1470", "The Great Gatsby(F. Scott Fitzgerald)","已整理,englishwords","3",""],
["the_three_musketeers_1921", "The Three Musketeers(Alexandre Dumas)","已整理,englishwords","3",""],
["the_man_in_the_iron_m_2073", "The Man in the Iron Mask(Alexandre Dumas)","已整理,englishwords","3",""],
["ten_years_later_1379", "Ten Years Later(Alexandre Dumas)","已整理,englishwords","3",""],
["twenty_years_after_1729", "Twenty Years After(Alexandre Dumas)","已整理,englishwords","3",""],
["robert_s_rules_of_order_pmoroofda_7672", "Robert's Rules of Order Pocket Manual of Rules of Order for Deliberative Assemblies(Henry M. Robert)","已整理,englishwords","3",""],
["anna_karenina_1223","Anna Karenina","englishwords,已整理","3",""],
["zi_zhi_tong_jian_138381","资治通鉴","历史,已整理","3",""],
["jiu_tang_shu_67933","旧唐书(刘昫等)","历史,已整理","3",""],
["hong_lou_meng_86212","红楼梦(曹雪芹)","五大名著,已整理","3",""],
["xi_xiang_ji_wang_shi_f_92369", "西厢记(王实甫)","已整理","3",""],
["zhao_shi_gu_er_yuan_jjx_108071", "赵氏孤儿(（元）纪君祥)","已整理","3",""],
["dou_e_yuan_guan_han_q_75375", "窦娥冤(关汉卿)","已整理","3",""],
["po_you_meng_gu_yan_hgqymzy_226107", "破幽梦孤雁汉宫秋(（元）马致远)","已整理","3",""],
["pi_pa_ji_yuan_gao_m_95259", "琵琶记(（元）高明)","已整理","3",""],
["zhang_sheng_dian_qing_hong_s_95837", "长生殿(（清）洪昇)","已整理","3",""],
["sheng_jing_he_he_ben_124338","圣经和合本","圣经,已整理,已读","3","Jbible"],
["bin_feng_guang_yi_qing_ys_119305", "豳风广义(清·杨屾)","已整理","3",""],
["ming_yi_dai_fang_lu_hzx_133598", "明夷待访录(黄宗羲)","已整理","3",""],
["ren_jian_ci_hua_130136","人间词话(王国维)","已整理","3",""],
["jin_gu_qi_guan_bao_wlr_207970","今古奇观(抱瓮老人)","已整理","3",""],
["ji_lin_zhang_duan_ju_qwgw_155566", "集林长短句(【清】王国维)","已整理","3",""],
["gu_shi_shi_jiu_shou_u_137967", "古诗十九首","诗词,已整理","3",""],
["wei_liao_zi_unknown_79494", "尉缭子","已整理","3",""],
["shi_shuo_xin_yu_liu_yq_117671","世说新语(刘义庆)","已整理","3",""],
["mu_dan_ting_tang_xian_z_154512","牡丹亭(汤显祖)","已整理","3",""],
["fen_shu_ming_li_zhi_49024", "焚书((明)李贽)","已整理","3",""],
["the_dunwich_horror_1711","The Dunwich Horror(H. P. Lovecraft)","已整理,englishwords","3",""],
["the_warden_trollope_anthony_2641","The Warden(Trollope,Anthony)","englishwords,已整理","3",""],
["tao_hua_shan_kong_shang_r_152565","桃花扇(孔尚任)","已整理","3",""],
["david_copperfield_1653","David Copperfield(Charles Dickens)","englishwords,已整理","3",""],
["little_women_1172","Little Women(Louisa May Alcott)","englishwords,已整理","3",""],
["frankenstein_1256", "Frankenstein(Mary Wollstonecraft Shelley)","englishwords,已整理","3",""],
["chambers_s_twentieth_century_dictionary_p4o4szas_6663", "Chambers's Twentieth Century Dictionary (part 4 of 4: S-Z and supplements)","en_minor,已整理","3",""],
["chambers_s_twentieth_century_dictionary_p3o4nr_5062", "Chambers's Twentieth Century Dictionary (part 3 of 4: N-R)","en_minor,已整理","3",""],
["chambers_s_twentieth_century_dictionary_p2o4em_5047", "Chambers's Twentieth Century Dictionary (part 2 of 4: E-M)","en_minor,已整理","3",""],
["chambers_s_twentieth_century_dictionary_p1o4ad_5033", "Chambers's Twentieth Century Dictionary (part 1 of 4: A-D)","en_minor,已整理","3",""],
["lao_zi_li_er_56145", "老子(李耳)","已整理","3",""],
["sheng_lv_qi_meng_che_wy_102723", "声律启蒙(车万育)","诗词,已整理","3",""],
["hou_han_shu_fan_ye_69309", "后汉书(范晔)","历史,已整理","3",""],
["xi_hu_meng_xun_zhang_d_113782", "西湖梦寻(张岱)","已整理","3",""],
["lao_can_you_ji_liu_e_185908","老残游记(刘鹗)","已整理","3",""],
["liao_shi_ji_shi_ben_mldjsbm_310689","辽史纪事本末 (历代纪事本末)(清•李有棠)","历史,已整理","3",""],
["jin_shi_ji_shi_ben_mldjsbm_311221","金史纪事本末 (历代纪事本末)(清•李有棠)","已整理","3",""],
["er_shi_nian_mu_du_zgxzwjr_308350","二十年目睹之怪现状(吴趼人)","已整理","3",""],
["around_the_world_in_80_dmfgbs_129587", "Around the World in 80 Days(Verne,Jules)","englishwords,已整理","3",""],
["the_call_of_the_wild_1731", "The Call of the Wild(Jack London)","englishwords,已整理","3",""],
["a_princess_of_mars_1616","A Princess of Mars","englishwords,已整理","3",""],
["the_mysterious_island_2048","The Mysterious Island","englishwords,已整理","3",""],
["metamorphosis_1387", "Metamorphosis(Franz Kafka)","englishwords,已整理","3",""],
["the_complete_works_of_william_s_3872","The Complete Works of William Shakespeare","englishwords,已整理","3",""],
["jane_eyre_819","Jane Eyre","englishwords,已整理","3",""],
["in_search_of_the_castaways_otcocg_5418","In Search of the Castaways; or the Children of Captain Grant","englishwords,已整理","3",""],
["a_journey_to_the_centre_ote_3228","A Journey to the Centre of the Earth","englishwords,已整理","3",""],
["the_war_of_the_worlds_whg_2795","The War of the Worlds(Wells,H. G.)","englishwords,幻想,已整理","3",""],
["jean_christophe_in_paris_the_mpath_5878","Jean Christophe: in Paris The Market-Place, Antoinette, the House, by Romain Rolland","englishwords,已整理","3",""],
["jean_christophe_journey_s_end_2721","Jean-Christophe Journey's End, by Romain Rolland","englishwords,已整理","3",""],
["jean_christophe_volume_i_mian_fgbs_129538","Jean-Christophe, Volume I, by Romain Rolland","englishwords,已整理","3",""],
["the_federalist_papers_1999","The Federalist Papers","englishwords,已整理","3",""],
["pride_and_prejudice_1794","Pride and Prejudice","englishwords,已整理","3",""],
["the_time_machine_1445","The Time Machine","englishwords,幻想,已整理","3",""],
["jing_shi_tong_yan_127894","警世通言(冯梦龙)","已整理","3",""],
["yu_shi_ming_yan_103391","喻世明言","已整理","3",""],
["feng_shen_yan_yi_103100","封神演义(许仲琳)","已整理","3",""],
["xi_you_ji_99175","西游记(吴承恩)","五大名著,已整理","3",""],
["liao_zhai_zhi_yi_107694","聊斋志异(蒲松龄)","幻想,已整理","3",""],
["shui_hu_chuan_75942","水浒传(施耐庵)","五大名著,已整理","3",""],
["san_guo_yan_yi_90723","三国演义(罗贯中)","五大名著,已整理","3",""],
["qing_lou_meng_zhong_guo_gdwxmzcs_322109", "青楼梦(慕真山人)","已整理","3",""],
["song_shi_yan_yi_93402","宋史演义(蔡东藩)","","3",""],
["su_shi_ji_108817","苏轼集","诗词","3",""],
["qian_jia_shi_80592","千家诗(张居正)","诗词","3",""],
["gu_wen_guan_zhi_110223","古文观止(吴楚材 & 吴调侯)","","3",""],
["dong_zhou_lie_guo_zhi_109423","东周列国志(冯梦龙)","历史","3",""],
["han_shu_ban_gu_47791","汉书(班固)","历史","3",""],
["bible_kjv_890","Bible(kjv)","englishwords,圣经,已整理","3","Jbible"],
["han_fei_zi_101015","韩非子","","3",""],
["shi_jing_68262","诗经","诗词","3",""],
["shi_ji_57250","史记","历史","3",""],
["dong_jing_meng_hua_lu_myl_189701","东京梦华录(孟元老)","","3",""],
];
