var nobel_prize_global=[
["1901","chemistry","Jacobus Henricus van 't Hoff","Netherlands","laws of chemical dynamics and osmotic pressure"],
["1901","literature","Sully Prudhomme","France",""],
["1901","peace","Henri Dunant","Switzerland",""],
["1901","peace","Frédéric Passy","France",""],
["1901","physics","Wilhelm Conrad Röntgen","Germany","discovery of X-rays"],
["1901","physiology/medicine","Emil von Behring","Germany","work on serum therapy"],
["1902","chemistry","Emil Fischer","Germany","work on sugar and purine syntheses"],
["1902","literature","Theodor Mommsen","Germany",""],
["1902","peace","Élie Ducommun","Switzerland",""],
["1902","peace","Charles-Albert Gobat","Switzerland",""],
["1902","physics","Hendrik Antoon Lorentz","Netherlands","investigation of the influence of magnetism on radiation"],
["1902","physics","Pieter Zeeman","Netherlands","investigation of the influence of magnetism on radiation"],
["1902","physiology/medicine","Sir Ronald Ross","U.K.","discovery of how malaria enters an organism"],
["1903","chemistry","Svante Arrhenius","Sweden","theory of electrolytic dissociation"],
["1903","literature","Bjørnstjerne Martinius Bjørnson","Norway",""],
["1903","peace","Sir Randal Cremer","U.K.",""],
["1903","physics","Henri Becquerel","France","discovery of spontaneous radioactivity"],
["1903","physics","Marie Curie","France","investigations of radiation phenomena discovered by Becquerel"],
["1903","physics","Pierre Curie","France","investigations of radiation phenomena discovered by Becquerel"],
["1903","physiology/medicine","Niels Ryberg Finsen","Denmark","treatment of skin diseases with light"],
["1904","chemistry","Sir William Ramsay","U.K.","discovery of inert gas elements and their places in the periodic system"],
["1904","literature","José Echegaray y Eizaguirre","Spain",""],
["1904","literature","Frédéric Mistral","France",""],
["1904","peace","Institute of International Law","(founded 1873)",""],
["1904","physics","Lord Rayleigh","U.K.","discovery of argon"],
["1904","physiology/medicine","Ivan Pavlov","Russia","work on the physiology of digestion"],
["1905","chemistry","Adolf von Baeyer","Germany","work on organic dyes, hydroaromatic compounds"],
["1905","literature","Henryk Sienkiewicz","Poland",""],
["1905","peace","Bertha, baroness von Suttner","Austria-Hungary",""],
["1905","physics","Philipp Lenard","Germany","research on cathode rays"],
["1905","physiology/medicine","Robert Koch","Germany","tuberculosis research"],
["1906","chemistry","Henri Moissan","France","isolation of fluorine; introduction of Moissan furnace"],
["1906","literature","Giosuè Carducci","Italy",""],
["1906","peace","Theodore Roosevelt","U.S.",""],
["1906","physics","Sir J.J. Thomson","U.K.","researches into electrical conductivity of gases"],
["1906","physiology/medicine","Camillo Golgi","Italy","work on the structure of the nervous system"],
["1906","physiology/medicine","Santiago Ramón y Cajal","Spain","work on the structure of the nervous system"],
["1907","chemistry","Eduard Buchner","Germany","discovery of noncellular fermentation"],
["1907","literature","Rudyard Kipling","U.K.",""],
["1907","peace","Ernesto Teodoro Moneta","Italy",""],
["1907","peace","Louis Renault","France",""],
["1907","physics","A.A. Michelson","U.S.","spectroscopic and metrological investigations"],
["1907","physiology/medicine","Alphonse Laveran","France","discovery of the role of protozoa in diseases"],
["1908","chemistry","Ernest Rutherford","U.K.","investigations into the disintegration of elements and the chemistry of radioactive substances"],
["1908","literature","Rudolf Christoph Eucken","Germany",""],
["1908","peace","Klas Pontus Arnoldson","Sweden",""],
["1908","peace","Fredrik Bajer","Denmark",""],
["1908","physics","Gabriel Lippmann","France","photographic reproduction of colours"],
["1908","physiology/medicine","Paul Ehrlich","Germany","work on immunity"],
["1908","physiology/medicine","Élie Metchnikoff","Russia","work on immunity"],
["1909","chemistry","Wilhelm Ostwald","Germany","pioneer work on catalysis, chemical equilibrium, and reaction velocities"],
["1909","literature","Selma Lagerlöf","Sweden",""],
["1909","peace","Auguste-Marie-François Beernaert","Belgium",""],
["1909","peace","Paul-H.-B. d'Estournelles de Constant","France",""],
["1909","physics","Ferdinand Braun","Germany","development of wireless telegraphy"],
["1909","physics","Guglielmo Marconi","Italy","development of wireless telegraphy"],
["1909","physiology/medicine","Emil Theodor Kocher","Switzerland","physiology, pathology, and surgery of the thyroid gland"],
["1910","chemistry","Otto Wallach","Germany","pioneer work in alicyclic combinations"],
["1910","literature","Paul Johann Ludwig von Heyse","Germany",""],
["1910","peace","International Peace Bureau","(founded 1891)",""],
["1910","physics","Johannes Diederik van der Waals","Netherlands","research concerning the equation of state of gases and liquids"],
["1910","physiology/medicine","Albrecht Kossel","Germany","researches in cellular chemistry"],
["1911","chemistry","Marie Curie","France","discovery of radium and polonium; isolation of radium"],
["1911","literature","Maurice Maeterlinck","Belgium",""],
["1911","peace","Tobias Michael Carel Asser","Netherlands",""],
["1911","peace","Alfred Hermann Fried","Austria-Hungary",""],
["1911","physics","Wilhelm Wien","Germany","discoveries regarding laws governing heat radiation"],
["1911","physiology/medicine","Allvar Gullstrand","Sweden","work on dioptrics of the eye"],
["1912","chemistry","Victor Grignard","France","discovery of the Grignard reagents"],
["1912","chemistry","Paul Sabatier","France","method of hydrogenating organic compounds"],
["1912","literature","Gerhart Hauptmann","Germany",""],
["1912","peace","Elihu Root","U.S.",""],
["1912","physics","Nils Dalén","Sweden","invention of automatic regulators for lighting coastal beacons and light buoys"],
["1912","physiology/medicine","Alexis Carrel","France","work on vascular suture; transplantation of organs"],
["1913","chemistry","Alfred Werner","Switzerland","work on the linkage of atoms in molecules"],
["1913","literature","Rabindranath Tagore","India",""],
["1913","peace","Henri-Marie Lafontaine","Belgium",""],
["1913","physics","Heike Kamerlingh Onnes","Netherlands","investigation into the properties of matter at low temperatures; production of liquid helium"],
["1913","physiology/medicine","Charles Richet","France","work on anaphylaxis"],
["1914","chemistry","Theodore William Richards","U.S.","accurate determination of the atomic weights of numerous elements"],
["1914","physics","Max von Laue","Germany","discovery of diffraction of X-rays by crystals"],
["1914","physiology/medicine","Robert Bárány","Austria-Hungary","work on vestibular apparatus"],
["1915","chemistry","Richard Willstätter","Germany","pioneer researches in plant pigments, especially chlorophyll"],
["1915","literature","Romain Rolland","France",""],
["1915","physics","Sir Lawrence Bragg","U.K.","analysis of crystal structure by means of X-rays"],
["1915","physics","Sir William Bragg","U.K.","analysis of crystal structure by means of X-rays"],
["1916","literature","Verner von Heidenstam","Sweden"],
["1917","literature","Karl Adolph Gjellerup","Denmark",""],
["1917","literature","Henrik Pontoppidan","Denmark",""],
["1917","peace","International Committee of the Red Cross","(founded 1863)",""],
["1917","physics","Charles Glover Barkla","U.K.","discovery of characteristic X-radiation of elements"],
["1918","chemistry","Fritz Haber","Germany","synthesis of ammonia"],
["1918","literature","Erik Axel Karlfeldt (declined)","Sweden",""],
["1918","physics","Max Planck","Germany","discovery of the elemental quanta"],
["1919","literature","Carl Spitteler","Switzerland",""],
["1919","peace","Woodrow Wilson","U.S.",""],
["1919","physics","Johannes Stark","Germany","discovery of Doppler effect in positive ion rays and division of spectral lines in electric field"],
["1919","physiology/medicine","Jules Bordet","Belgium","work on immunity factors in blood serum"],
["1920","chemistry","Walther Hermann Nernst","Germany","work in thermochemistry"],
["1920","literature","Knut Hamsun","Norway",""],
["1920","peace","Léon Bourgeois","France",""],
["1920","physics","Charles Édouard Guillaume","Switzerland","discovery of anomalies in alloys"],
["1920","physiology/medicine","August Krogh","Denmark","discovery of capillary motor-regulating mechanism"],
["1921","chemistry","Frederick Soddy","U.K.","chemistry of radioactive substances; occurrence and nature of isotopes"],
["1921","literature","Anatole France","France",""],
["1921","peace","Karl Hjalmar Branting","Sweden",""],
["1921","peace","Christian Lous Lange","Norway",""],
["1921","physics","Albert Einstein","Switzerland","work in theoretical physics"],
["1922","chemistry","Francis William Aston","U.K.","work with mass spectrograph; whole-number rule"],
["1922","literature","Jacinto Benavente y Martínez","Spain",""],
["1922","peace","Fridtjof Nansen","Norway",""],
["1922","physics","Niels Bohr","Denmark","investigation of atomic structure and radiation"],
["1922","physiology/medicine","A.V. Hill","U.K.","discoveries concerning heat production in muscles"],
["1922","physiology/medicine","Otto Meyerhof","Germany","work on metabolism of lactic acid in muscles"],
["1923","chemistry","Fritz Pregl","Austria","method of microanalysis of organic substances"],
["1923","literature","William Butler Yeats","Ireland",""],
["1923","physics","Robert Andrews Millikan","U.S.","work on elementary electric charge and the photoelectric effect"],
["1923","physiology/medicine","Sir Frederick Grant Banting","Canada","discovery of insulin"],
["1923","physiology/medicine","J.J.R. Macleod","U.K.","discovery of insulin"],
["1924","literature","Władysław Stanisław Reymont","Poland",""],
["1924","physics","Karl Manne Georg Siegbahn","Sweden","work in X-ray spectroscopy"],
["1924","physiology/medicine","Willem Einthoven","Netherlands","discovery of electrocardiogram mechanism"],
["1925","chemistry","Richard Zsigmondy","Austria","elucidation of the heterogeneous nature of colloidal solutions"],
["1925","literature","George Bernard Shaw","Ireland",""],
["1925","peace","Sir Austen Chamberlain","U.K.",""],
["1925","peace","Charles G. Dawes","U.S.",""],
["1925","physics","James Franck","Germany","discovery of the laws governing the impact of an electron upon an atom"],
["1925","physics","Gustav Hertz","Germany","discovery of the laws governing the impact of an electron upon an atom"],
["1926","chemistry","Theodor H.E. Svedberg","Sweden","work on disperse systems"],
["1926","literature","Grazia Deledda","Italy",""],
["1926","peace","Aristide Briand","France",""],
["1926","peace","Gustav Stresemann","Germany",""],
["1926","physics","Jean Perrin","France","work on discontinuous structure of matter"],
["1926","physiology/medicine","Johannes Fibiger","Denmark","contributions to cancer research"],
["1927","chemistry","Heinrich Otto Wieland","Germany","researches into the constitution of bile acids"],
["1927","literature","Henri Bergson","France",""],
["1927","peace","Ferdinand-Édouard Buisson","France",""],
["1927","peace","Ludwig Quidde","Germany",""],
["1927","physics","Arthur Holly Compton","U.S.","discovery of wavelength change in diffused X-rays"],
["1927","physics","C.T.R. Wilson","U.K.","method of making visible the paths of electrically charged particles"],
["1927","physiology/medicine","Julius Wagner-Jauregg","Austria","work on malaria inoculation in dementia paralytica"],
["1928","chemistry","Adolf Windaus","Germany","constitution of sterols and their connection with vitamins"],
["1928","literature","Sigrid Undset","Norway",""],
["1928","physics","Sir Owen Willans Richardson","U.K.","work on electron emission by hot metals"],
["1928","physiology/medicine","Charles-Jules-Henri Nicolle","France","work on typhus"],
["1929","chemistry","Hans von Euler-Chelpin","Sweden","investigations in the fermentation of sugars and the enzyme action involved"],
["1929","chemistry","Sir Arthur Harden","U.K.","investigations in the fermentation of sugars and the enzyme action involved"],
["1929","literature","Thomas Mann","Germany",""],
["1929","peace","Frank B. Kellogg","U.S.",""],
["1929","physics","Louis de Broglie","France","discovery of the wave nature of electrons"],
["1929","physiology/medicine","Christiaan Eijkman","Netherlands","discovery of the antineuritic vitamin"],
["1929","physiology/medicine","Sir Frederick Gowland Hopkins","U.K.","discovery of growth-stimulating vitamins"],
["1930","chemistry","Hans Fischer","Germany","hemin, chlorophyll research; synthesis of hemin"],
["1930","literature","Sinclair Lewis","U.S.",""],
["1930","peace","Nathan Söderblom","Sweden",""],
["1930","physics","Sir Chandrasekhara Venkata Raman","India","work on light diffusion; discovery of Raman effect"],
["1930","physiology/medicine","Karl Landsteiner","U.S.","grouping of human blood types"],
["1931","chemistry","Friedrich Bergius","Germany","invention and development of chemical high-pressure methods"],
["1931","chemistry","Carl Bosch","Germany","invention and development of chemical high-pressure methods"],
["1931","literature","Erik Axel Karlfeldt (posthumous award)","Sweden",""],
["1931","peace","Jane Addams","U.S.",""],
["1931","peace","Nicholas Murray Butler","U.S.",""],
["1931","physiology/medicine","Otto Warburg","Germany","discovery of nature and action of respiratory enzyme"],
["1932","chemistry","Irving Langmuir","U.S.","discoveries and investigations in surface chemistry"],
["1932","literature","John Galsworthy","U.K.",""],
["1932","physics","Werner Heisenberg","Germany","creation of quantum mechanics"],
["1932","physiology/medicine","Edgar Douglas Adrian, 1st Baron Adrian","U.K.","discoveries regarding function of neurons"],
["1932","physiology/medicine","Sir Charles Scott Sherrington","U.K.","discoveries regarding function of neurons"],
["1933","literature","Ivan Bunin","U.S.S.R.",""],
["1933","peace","Sir Norman Angell","U.K.",""],
["1933","physics","P.A.M. Dirac","U.K.","introduction of wave equations in quantum mechanics"],
["1933","physics","Erwin Schrödinger","Austria","introduction of wave equations in quantum mechanics"],
["1933","physiology/medicine","Thomas Hunt Morgan","U.S.","heredity transmission functions of chromosomes"],
["1934","chemistry","Harold C. Urey","U.S.","discovery of heavy hydrogen"],
["1934","literature","Luigi Pirandello","Italy",""],
["1934","peace","Arthur Henderson","U.K.",""],
["1934","physiology/medicine","George Richards Minot","U.S.","discoveries concerning liver treatment for anemia"],
["1934","physiology/medicine","William P. Murphy","U.S.","discoveries concerning liver treatment for anemia"],
["1934","physiology/medicine","George H. Whipple","U.S.","discoveries concerning liver treatment for anemia"],
["1935","chemistry","Frédéric and Irène Joliot-Curie","France","synthesis of new radioactive elements"],
["1935","peace","Carl von Ossietzky","Germany",""],
["1935","physics","Sir James Chadwick","U.K.","discovery of the neutron"],
["1935","physiology/medicine","Hans Spemann","Germany","organizer effect in embryo"],
["1936","chemistry","Peter Debye","Netherlands","work on dipole moments and diffraction of X-rays and electrons in gases"],
["1936","literature","Eugene O'Neill","U.S.",""],
["1936","peace","Carlos Saavedra Lamas","Argentina",""],
["1936","physics","Carl David Anderson","U.S.","discovery of the positron"],
["1936","physics","Victor Francis Hess","Austria","discovery of cosmic radiation"],
["1936","physiology/medicine","Sir Henry Dale","U.K.","work on chemical transmission of nerve impulses"],
["1936","physiology/medicine","Otto Loewi","Germany","work on chemical transmission of nerve impulses"],
["1937","chemistry","Sir Norman Haworth","U.K.","research on carbohydrates and vitamin C"],
["1937","chemistry","Paul Karrer","Switzerland","research on carotenoids, flavins, and vitamins"],
["1937","literature","Roger Martin du Gard","France",""],
["1937","peace","Robert Gascoyne-Cecil, 1st Viscount Cecil","U.K.",""],
["1937","physics","Clinton Joseph Davisson","U.S.","experimental demonstration of the interference phenomenon in crystals irradiated by electrons"],
["1937","physics","Sir George Paget Thomson","U.K.","experimental demonstration of the interference phenomenon in crystals irradiated by electrons"],
["1937","physiology/medicine","Albert Szent-Györgyi","Hungary","work on biological combustion"],
["1938","chemistry","Richard Kuhn (declined)","Germany","carotenoid and vitamin research"],
["1938","literature","Pearl Buck","U.S.",""],
["1938","peace","Nansen International Office for Refugees","(founded 1931)",""],
["1938","physics","Enrico Fermi","Italy","disclosure of artificial radioactive elements produced by neutron irradiation"],
["1938","physiology/medicine","Corneille Heymans","Belgium","discovery of role of sinus and aortic mechanisms in respiration regulation"],
["1939","chemistry","Adolf Butenandt (declined)","Germany","work on sexual hormones"],
["1939","chemistry","Leopold Ruzicka","Switzerland","work on polymethylenes and higher terpenes"],
["1939","literature","Frans Eemil Sillanpää","Finland",""],
["1939","physics","Ernest Orlando Lawrence","U.S.","invention of the cyclotron"],
["1939","physiology/medicine","Gerhard Domagk (declined)","Germany","antibacterial effect of Prontosil"],
["1943","chemistry","Georg Charles von Hevesy","Hungary","use of isotopes as tracers in chemical research"],
["1943","physics","Otto Stern","U.S.","discovery of the magnetic moment of the proton"],
["1943","physiology/medicine","Henrik Dam","Denmark","discovery of vitamin K"],
["1943","physiology/medicine","Edward Adelbert Doisy","U.S.","discovery of chemical nature of vitamin K"],
["1944","chemistry","Otto Hahn","Germany","discovery of the fission of heavy nuclei"],
["1944","literature","Johannes V. Jensen","Denmark",""],
["1944","peace","International Committee of the Red Cross","(founded 1863)",""],
["1944","physics","Isidor Isaac Rabi","U.S.","resonance method for registration of various properties of atomic nuclei"],
["1944","physiology/medicine","Joseph Erlanger","U.S.","researches on differentiated functions of nerve fibres"],
["1944","physiology/medicine","Herbert Spencer Gasser","U.S.","researches on differentiated functions of nerve fibres"],
["1945","chemistry","Artturi Ilmari Virtanen","Finland","invention of fodder preservation method"],
["1945","literature","Gabriela Mistral","Chile",""],
["1945","peace","Cordell Hull","U.S.",""],
["1945","physics","Wolfgang Pauli","Austria","discovery of the exclusion principle of electrons"],
["1945","physiology/medicine","Sir Ernst Boris Chain","U.K.","discovery of penicillin and its curative value"],
["1945","physiology/medicine","Sir Alexander Fleming","U.K.","discovery of penicillin and its curative value"],
["1945","physiology/medicine","Howard Walter Florey, Baron Florey","Australia","discovery of penicillin and its curative value"],
["1946","chemistry","John Howard Northrop","U.S.","preparation of enzymes and virus proteins in pure form"],
["1946","chemistry","Wendell Meredith Stanley","U.S.","preparation of enzymes and virus proteins in pure form"],
["1946","chemistry","James Batcheller Sumner","U.S.","discovery of enzyme crystallization"],
["1946","literature","Hermann Hesse","Switzerland",""],
["1946","peace","Emily Greene Balch","U.S.",""],
["1946","peace","John R. Mott","U.S.",""],
["1946","physics","Percy Williams Bridgman","U.S.","discoveries in the domain of high-pressure physics"],
["1946","physiology/medicine","Hermann Joseph Muller","U.S.","production of mutations by X-ray irradiation"],
["1947","chemistry","Sir Robert Robinson","U.K.","investigation of alkaloids and other plant products"],
["1947","literature","André Gide","France",""],
["1947","peace","American Friends Service Committee","U.S.",""],
["1947","peace","Friends Service Council (FSC)","U.K.",""],
["1947","physics","Sir Edward Victor Appleton","U.K.","discovery of Appleton layer in upper atmosphere"],
["1947","physiology/medicine","Carl and Gerty Cori","U.S.","discovery of how glycogen is catalytically converted"],
["1947","physiology/medicine","Bernardo Alberto Houssay","Argentina","pituitary hormone function in sugar metabolism"],
["1948","chemistry","Arne Tiselius","Sweden","researches in electrophoresis and adsorption analysis; serum proteins"],
["1948","literature","T.S. Eliot","U.K.",""],
["1948","physics","Patrick M.S. Blackett","U.K.","discoveries in the domain of nuclear physics and cosmic radiation"],
["1948","physiology/medicine","Paul Hermann Müller","Switzerland","properties of DDT"],
["1949","chemistry","William Francis Giauque","U.S.","behaviour of substances at extremely low temperatures"],
["1949","literature","William Faulkner","U.S.",""],
["1949","peace","John Boyd Orr, Baron Boyd-Orr of Brechin Mearns","U.K.",""],
["1949","physics","Yukawa Hideki","Japan","prediction of the existence of mesons"],
["1949","physiology/medicine","António Egas Moniz","Portugal","therapeutic value of leucotomy in psychoses"],
["1949","physiology/medicine","Walter Rudolf Hess","Switzerland","discovery of function of interbrain"],
["1950","chemistry","Kurt Alder","West Germany","discovery and development of diene synthesis"],
["1950","chemistry","Otto Paul Hermann Diels","West Germany","discovery and development of diene synthesis"],
["1950","literature","Bertrand Russell","U.K.",""],
["1950","peace","Ralph Bunche","U.S.",""],
["1950","physics","Cecil Frank Powell","U.K.","photographic method of studying nuclear processes; discoveries concerning mesons"],
["1950","physiology/medicine","Philip Showalter Hench","U.S.","research on adrenal cortex hormones, their structure and biological effects"],
["1950","physiology/medicine","Edward Calvin Kendall","U.S.","research on adrenal cortex hormones, their structure and biological effects"],
["1950","physiology/medicine","Tadeus Reichstein","Switzerland","research on adrenal cortex hormones, their structure and biological effects"],
["1951","chemistry","Edwin Mattison McMillan","U.S.","discovery of and research on transuranium elements"],
["1951","chemistry","Glenn T. Seaborg","U.S.","discovery of and research on transuranium elements"],
["1951","literature","Pär Lagerkvist","Sweden",""],
["1951","peace","Léon Jouhaux","France",""],
["1951","physics","Sir John Douglas Cockcroft","U.K.","work on transmutation of atomic nuclei by accelerated particles"],
["1951","physics","Ernest Thomas Sinton Walton","Ireland","work on transmutation of atomic nuclei by accelerated particles"],
["1951","physiology/medicine","Max Theiler","South Africa","yellow fever discoveries"],
["1952","chemistry","A.J.P. Martin","U.K.","development of partition chromatography"],
["1952","chemistry","R.L.M. Synge","U.K.","development of partition chromatography"],
["1952","literature","François Mauriac","France",""],
["1952","peace","Albert Schweitzer","Alsace",""],
["1952","physics","Felix Bloch","U.S.","discovery of nuclear magnetic resonance in solids"],
["1952","physics","E.M. Purcell","U.S.","discovery of nuclear magnetic resonance in solids"],
["1952","physiology/medicine","Selman Abraham Waksman","U.S.","discovery of streptomycin"],
["1953","chemistry","Hermann Staudinger","West Germany","work on macromolecules"],
["1953","literature","Sir Winston Churchill","U.K.",""],
["1953","peace","George C. Marshall","U.S.",""],
["1953","physics","Frits Zernike","Netherlands","method of phase-contrast microscopy"],
["1953","physiology/medicine","Sir Hans Adolf Krebs","U.K.","discovery of coenzyme A–citric acid cycle in metabolism of carbohydrates"],
["1953","physiology/medicine","Fritz Albert Lipmann","U.S.","discovery of coenzyme A–citric acid cycle in metabolism of carbohydrates"],
["1954","chemistry","Linus Pauling","U.S.","study of the nature of the chemical bond"],
["1954","literature","Ernest Hemingway","U.S.",""],
["1954","peace","Office of the United Nations High Commissioner for Refugees","(founded 1951)",""],
["1954","physics","Max Born","U.K.","statistical studies of atomic wave functions"],
["1954","physics","Walther Bothe","West Germany","invention of coincidence method"],
["1954","physiology/medicine","John Franklin Enders","U.S.","cultivation of the poliomyelitis virus in tissue cultures"],
["1954","physiology/medicine","Frederick Chapman Robbins","U.S.","cultivation of the poliomyelitis virus in tissue cultures"],
["1954","physiology/medicine","Thomas H. Weller","U.S.","cultivation of the poliomyelitis virus in tissue cultures"],
["1955","chemistry","Vincent du Vigneaud","U.S.","first synthesis of a polypeptide hormone"],
["1955","literature","Halldór Laxness","Iceland",""],
["1955","physics","Polykarp Kusch","U.S.","measurement of magnetic moment of electron"],
["1955","physics","Willis Eugene Lamb, Jr.","U.S.","discoveries in the hydrogen spectrum"],
["1955","physiology/medicine","Axel Hugo Teodor Theorell","Sweden","nature and mode of action of oxidation enzymes"],
["1956","chemistry","Sir Cyril Norman Hinshelwood","U.K.","work on the kinetics of chemical reactions"],
["1956","chemistry","Nikolay Nikolayevich Semyonov","U.S.S.R.","work on the kinetics of chemical reactions"],
["1956","literature","Juan Ramón Jiménez","Spain",""],
["1956","physics","John Bardeen","U.S.","investigations on semiconductors and invention of the transistor"],
["1956","physics","Walter H. Brattain","U.S.","investigations on semiconductors and invention of the transistor"],
["1956","physics","William B. Shockley","U.S.","investigations on semiconductors and invention of the transistor"],
["1956","physiology/medicine","André F. Cournand","U.S.","discoveries concerning heart catheterization and circulatory changes"],
["1956","physiology/medicine","Werner Forssmann","West Germany","discoveries concerning heart catheterization and circulatory changes"],
["1956","physiology/medicine","Dickinson Woodruff Richards","U.S.","discoveries concerning heart catheterization and circulatory changes"],
["1957","chemistry","Alexander Robertus Todd, Baron Todd","U.K.","work on nucleotides and nucleotide coenzymes"],
["1957","literature","Albert Camus","France",""],
["1957","peace","Lester B. Pearson","Canada",""],
["1957","physics","Tsung-Dao Lee","China","discovery of violations of the principle of parity"],
["1957","physics","Chen Ning Yang","China","discovery of violations of the principle of parity"],
["1957","physiology/medicine","Daniel Bovet","Italy","production of synthetic curare"],
["1958","chemistry","Frederick Sanger","U.K.","determination of the structure of the insulin molecule"],
["1958","literature","Boris Leonidovich Pasternak (declined)","U.S.S.R.",""],
["1958","peace","Dominique Pire","Belgium",""],
["1958","physics","Pavel Alekseyevich Cherenkov","U.S.S.R.","discovery and interpretation of the Cherenkov effect"],
["1958","physics","Ilya Mikhaylovich Frank","U.S.S.R.","discovery and interpretation of the Cherenkov effect"],
["1958","physics","Igor Yevgenyevich Tamm","U.S.S.R.","discovery and interpretation of the Cherenkov effect"],
["1958","physiology/medicine","George Wells Beadle","U.S.","genetic regulation of chemical processes"],
["1958","physiology/medicine","Joshua Lederberg","U.S.","genetic recombination"],
["1958","physiology/medicine","Edward L. Tatum","U.S.","genetic regulation of chemical processes"],
["1959","chemistry","Jaroslav Heyrovský","Czechoslovakia","discovery and development of polarography"],
["1959","literature","Salvatore Quasimodo","Italy",""],
["1959","peace","Philip John Noel-Baker, Baron Noel-Baker","U.K.",""],
["1959","physics","Owen Chamberlain","U.S.","confirmation of the existence of the antiproton"],
["1959","physics","Emilio Segrè","U.S.","confirmation of the existence of the antiproton"],
["1959","physiology/medicine","Arthur Kornberg","U.S.","work on producing nucleic acids artificially"],
["1959","physiology/medicine","Severo Ochoa","U.S.","work on producing nucleic acids artificially"],
["1960","chemistry","Willard Frank Libby","U.S.","development of radiocarbon dating"],
["1960","literature","Saint-John Perse","France",""],
["1960","peace","Albert John Luthuli","South Africa",""],
["1960","physics","Donald A. Glaser","U.S.","development of the bubble chamber"],
["1960","physiology/medicine","Sir Macfarlane Burnet","Australia","acquired immunity to tissue transplants"],
["1960","physiology/medicine","Sir Peter B. Medawar","U.K.","acquired immunity to tissue transplants"],
["1961","chemistry","Melvin Calvin","U.S.","study of chemical steps that take place during photosynthesis"],
["1961","literature","Ivo Andric","Yugoslavia",""],
["1961","peace","Dag Hammarskjöld","Sweden",""],
["1961","physics","Robert Hofstadter","U.S.","determination of shape and size of atomic nucleons"],
["1961","physics","Rudolf Ludwig Mössbauer","West Germany","discovery of the Mössbauer effect"],
["1961","physiology/medicine","Georg von Békésy","U.S.","functions of the inner ear"],
["1962","chemistry","Sir John Cowdery Kendrew","U.K.","determination of the structure of hemoproteins"],
["1962","chemistry","Max Ferdinand Perutz","U.K.","determination of the structure of hemoproteins"],
["1962","literature","John Steinbeck","U.S.",""],
["1962","peace","Linus Pauling","U.S.",""],
["1962","physics","Lev Davidovich Landau","U.S.S.R.","contributions to the understanding of condensed states of matter"],
["1962","physiology/medicine","Francis Harry Compton Crick","U.K.","discoveries concerning the molecular structure of DNA"],
["1962","physiology/medicine","James Dewey Watson","U.S.","discoveries concerning the molecular structure of DNA"],
["1962","physiology/medicine","Maurice Wilkins","U.K.","discoveries concerning the molecular structure of DNA"],
["1963","chemistry","Giulio Natta","Italy","structure and synthesis of polymers in the field of plastics"],
["1963","chemistry","Karl Ziegler","West Germany","structure and synthesis of polymers in the field of plastics"],
["1963","literature","George Seferis","Greece",""],
["1963","peace","International Committee of the Red Cross","(founded 1863)",""],
["1963","peace","League of Red Cross Societies","",""],
["1963","physics","J. Hans D. Jensen","West Germany","development of shell model theory of the structure of the atomic nuclei"],
["1963","physics","Maria Goeppert Mayer","U.S.","development of shell model theory of the structure of the atomic nuclei"],
["1963","physics","Eugene Paul Wigner","U.S.","principles governing interaction of protons and neutrons in the nucleus"],
["1963","physiology/medicine","Sir John Carew Eccles","Australia","study of the transmission of impulses along a nerve fibre"],
["1963","physiology/medicine","Sir Alan Hodgkin","U.K.","study of the transmission of impulses along a nerve fibre"],
["1963","physiology/medicine","Sir Andrew Fielding Huxley","U.K.","study of the transmission of impulses along a nerve fibre"],
["1964","chemistry","Dorothy Mary Crowfoot Hodgkin","U.K.","determining the structure of biochemical compounds essential in combating pernicious anemia"],
["1964","literature","Jean-Paul Sartre (declined)","France",""],
["1964","peace","Martin Luther King, Jr.","U.S.",""],
["1964","physics","Nikolay Gennadiyevich Basov","U.S.S.R.","work in quantum electronics leading to construction of instruments based on maser-laser principles"],
["1964","physics","Aleksandr Mikhaylovich Prokhorov","U.S.S.R.","work in quantum electronics leading to construction of instruments based on maser-laser principles"],
["1964","physics","Charles Hard Townes","U.S.","work in quantum electronics leading to construction of instruments based on maser-laser principles"],
["1964","physiology/medicine","Konrad Bloch","U.S.","discoveries concerning cholesterol and fatty-acid metabolism"],
["1964","physiology/medicine","Feodor Lynen","West Germany","discoveries concerning cholesterol and fatty-acid metabolism"],
["1965","chemistry","R.B. Woodward","U.S.","synthesis of sterols, chlorophyll, and other substances"],
["1965","literature","Mikhail Aleksandrovich Sholokhov","U.S.S.R.",""],
["1965","peace","United Nations Children's Fund","(founded 1946)",""],
["1965","physics","Richard P. Feynman","U.S.","basic principles of quantum electrodynamics"],
["1965","physics","Julian Seymour Schwinger","U.S.","basic principles of quantum electrodynamics"],
["1965","physics","Tomonaga Shin'ichiro","Japan","basic principles of quantum electrodynamics"],
["1965","physiology/medicine","François Jacob","France","discoveries concerning regulatory activities of the body cells"],
["1965","physiology/medicine","André Lwoff","France","discoveries concerning regulatory activities of the body cells"],
["1965","physiology/medicine","Jacques Monod","France","discoveries concerning regulatory activities of the body cells"],
["1966","chemistry","Robert Sanderson Mulliken","U.S.","work concerning chemical bonds and the electronic structure of molecules"],
["1966","literature","S.Y. Agnon","Israel",""],
["1966","literature","Nelly Sachs","Sweden",""],
["1966","physics","Alfred Kastler","France","discovery of optical methods for studying Hertzian resonances in atoms"],
["1966","physiology/medicine","Charles B. Huggins","U.S.","research on causes and treatment of cancer"],
["1966","physiology/medicine","Peyton Rous","U.S.","research on causes and treatment of cancer"],
["1967","chemistry","Manfred Eigen","West Germany","studies of extremely fast chemical reactions"],
["1967","chemistry","Ronald George Wreyford Norrish","U.K.","studies of extremely fast chemical reactions"],
["1967","chemistry","Sir George Porter","U.K.","studies of extremely fast chemical reactions"],
["1967","literature","Miguel Ángel Asturias","Guatemala",""],
["1967","physics","Hans Bethe","U.S.","discoveries concerning the energy production of stars"],
["1967","physiology/medicine","Ragnar Arthur Granit","Sweden","discoveries about chemical and physiological visual processes in the eye"],
["1967","physiology/medicine","Haldan Keffer Hartline","U.S.","discoveries about chemical and physiological visual processes in the eye"],
["1967","physiology/medicine","George Wald","U.S.","discoveries about chemical and physiological visual processes in the eye"],
["1968","chemistry","Lars Onsager","U.S.","work on theory of thermodynamics of irreversible processes"],
["1968","literature","Kawabata Yasunari","Japan",""],
["1968","peace","René Cassin","France",""],
["1968","physics","Luis W. Alvarez","U.S.","work with elementary particles, discovery of resonance states"],
["1968","physiology/medicine","Robert William Holley","U.S.","deciphering of the genetic code"],
["1968","physiology/medicine","Har Gobind Khorana","U.S.","deciphering of the genetic code"],
["1968","physiology/medicine","Marshall William Nirenberg","U.S.","deciphering of the genetic code"],
["1969","chemistry","Sir Derek H.R. Barton","U.K.","work in determining actual three-dimensional shape of molecules"],
["1969","chemistry","Odd Hassel","Norway","work in determining actual three-dimensional shape of molecules"],
["1969","economics","Ragnar Frisch","Norway","work in econometrics"],
["1969","economics","Jan Tinbergen","Netherlands","work in econometrics"],
["1969","literature","Samuel Beckett","Ireland",""],
["1969","peace","International Labour Organisation","(founded 1919)"],
["1969","physics","Murray Gell-Mann","U.S.","classification of elementary particles and their interactions"],
["1969","physiology/medicine","Max Delbrück","U.S.","research and discoveries concerning viruses and viral diseases"],
["1969","physiology/medicine","A.D. Hershey","U.S.","research and discoveries concerning viruses and viral diseases"],
["1969","physiology/medicine","Salvador Luria","U.S.","research and discoveries concerning viruses and viral diseases"],
["1970","chemistry","Luis Federico Leloir","Argentina","discovery of sugar nucleotides and their role in the biosynthesis of carbohydrates"],
["1970","economics","Paul Samuelson","U.S.","work in scientific analysis of economic theory"],
["1970","literature","Aleksandr Isayevich Solzhenitsyn","U.S.S.R.",""],
["1970","peace","Norman Ernest Borlaug","U.S.",""],
["1970","physics","Hannes Alfvén","Sweden","work in magnetohydrodynamics and in antiferromagnetism and ferrimagnetism"],
["1970","physics","Louis-Eugène-Félix Néel","France","work in magnetohydrodynamics and in antiferromagnetism and ferrimagnetism"],
["1970","physiology/medicine","Julius Axelrod","U.S.","discoveries concerning the chemistry of nerve transmission"],
["1970","physiology/medicine","Ulf von Euler","Sweden","discoveries concerning the chemistry of nerve transmission"],
["1970","physiology/medicine","Sir Bernard Katz","U.K.","discoveries concerning the chemistry of nerve transmission"],
["1971","chemistry","Gerhard Herzberg","Canada","research in the structure of molecules"],
["1971","economics","Simon Kuznets","U.S.","extensive research on the economic growth of nations"],
["1971","literature","Pablo Neruda","Chile",""],
["1971","peace","Willy Brandt","West Germany",""],
["1971","physics","Dennis Gabor","U.K.","invention of holography"],
["1971","physiology/medicine","Earl W. Sutherland, Jr.","U.S.","action of hormones"],
["1972","chemistry","Christian B. Anfinsen","U.S.","fundamental contributions to enzyme chemistry"],
["1972","chemistry","Stanford Moore","U.S.","fundamental contributions to enzyme chemistry"],
["1972","chemistry","William H. Stein","U.S.","fundamental contributions to enzyme chemistry"],
["1972","economics","Kenneth J. Arrow","U.S.","contributions to general economic equilibrium theory and welfare theory"],
["1972","economics","Sir John R. Hicks","U.K.","contributions to general economic equilibrium theory and welfare theory"],
["1972","literature","Heinrich Böll","West Germany",""],
["1972","physics","John Bardeen","U.S.","development of the theory of superconductivity"],
["1972","physics","Leon N. Cooper","U.S.","development of the theory of superconductivity"],
["1972","physics","John Robert Schrieffer","U.S.","development of the theory of superconductivity"],
["1972","physiology/medicine","Gerald Maurice Edelman","U.S.","research on the chemical structure of antibodies"],
["1972","physiology/medicine","Rodney Robert Porter","U.K.","research on the chemical structure of antibodies"],
["1973","chemistry","Ernst Otto Fischer","West Germany","organometallic chemistry"],
["1973","chemistry","Sir Geoffrey Wilkinson","U.K.","organometallic chemistry"],
["1973","economics","Wassily Leontief","U.S.","input-output analysis"],
["1973","literature","Patrick White","Australia",""],
["1973","peace","Henry A. Kissinger","U.S.",""],
["1973","peace","Le Duc Tho (declined)","North Vietnam",""],
["1973","physics","Leo Esaki","Japan","tunneling in semiconductors and superconductors"],
["1973","physics","Ivar Giaever","U.S.","tunneling in semiconductors and superconductors"],
["1973","physics","Brian D. Josephson","U.K.","tunneling in semiconductors and superconductors"],
["1973","physiology/medicine","Karl von Frisch","Austria","discoveries in animal behaviour patterns"],
["1973","physiology/medicine","Konrad Lorenz","Austria","discoveries in animal behaviour patterns"],
["1973","physiology/medicine","Nikolaas Tinbergen","U.K.","discoveries in animal behaviour patterns"],
["1974","chemistry","Paul J. Flory","U.S.","studies of long-chain molecules"],
["1974","economics","Friedrich von Hayek","U.K.","pioneering analysis of the interdependence of economic, social, and institutional phenomena"],
["1974","economics","Gunnar Myrdal","Sweden","pioneering analysis of the interdependence of economic, social, and institutional phenomena"],
["1974","literature","Eyvind Johnson","Sweden",""],
["1974","literature","Harry Martinson","Sweden",""],
["1974","peace","Seán MacBride","Ireland",""],
["1974","peace","Sato Eisaku","Japan",""],
["1974","physics","Antony Hewish","U.K.","work in radio astronomy"],
["1974","physics","Sir Martin Ryle","U.K.","work in radio astronomy"],
["1974","physiology/medicine","Albert Claude","U.S.","research on structural and functional organization of cells"],
["1974","physiology/medicine","Christian René de Duve","Belgium","research on structural and functional organization of cells"],
["1974","physiology/medicine","George E. Palade","U.S.","research on structural and functional organization of cells"],
["1975","chemistry","Sir John Warcup Cornforth","U.K.","work in stereochemistry"],
["1975","chemistry","Vladimir Prelog","Switzerland","work in stereochemistry"],
["1975","economics","Leonid Vitalyevich Kantorovich","U.S.S.R.","contributions to the theory of optimum allocation of resources"],
["1975","economics","Tjalling C. Koopmans","U.S.","contributions to the theory of optimum allocation of resources"],
["1975","literature","Eugenio Montale","Italy",""],
["1975","peace","Andrey Dmitriyevich Sakharov","U.S.S.R.",""],
["1975","physics","Aage N. Bohr","Denmark","work on the atomic nucleus that paved the way for nuclear fusion"],
["1975","physics","Ben R. Mottelson","Denmark","work on the atomic nucleus that paved the way for nuclear fusion"],
["1975","physics","James Rainwater","U.S.","work on the atomic nucleus that paved the way for nuclear fusion"],
["1975","physiology/medicine","David Baltimore","U.S.","interaction between tumour viruses and the genetic material of the cell"],
["1975","physiology/medicine","Renato Dulbecco","U.S.","interaction between tumour viruses and the genetic material of the cell"],
["1975","physiology/medicine","Howard Martin Temin","U.S.","interaction between tumour viruses and the genetic material of the cell"],
["1976","chemistry","William Nunn Lipscomb, Jr.","U.S.","structure of boranes"],
["1976","economics","Milton Friedman","U.S.","consumption analysis, monetary theory, and economic stabilization"],
["1976","literature","Saul Bellow","U.S.",""],
["1976","peace","Mairéad Corrigan","Northern Ireland",""],
["1976","peace","Betty Williams","Northern Ireland",""],
["1976","physics","Burton Richter","U.S.","discovery of new class of elementary particles (psi, or J)"],
["1976","physics","Samuel C.C. Ting","U.S.","discovery of new class of elementary particles (psi, or J)"],
["1976","physiology/medicine","Baruch S. Blumberg","U.S.","studies of origin and spread of infectious diseases"],
["1976","physiology/medicine","D. Carleton Gajdusek","U.S.","studies of origin and spread of infectious diseases"],
["1977","chemistry","Ilya Prigogine","Belgium","widening the scope of thermodynamics"],
["1977","economics","James Edward Meade","U.K.","contributions to theory of international trade"],
["1977","economics","Bertil Ohlin","Sweden","contributions to theory of international trade"],
["1977","literature","Vicente Aleixandre","Spain",""],
["1977","peace","Amnesty International","(founded 1961)",""],
["1977","physics","Philip W. Anderson","U.S.","contributions to understanding the behaviour of electrons in magnetic, noncrystalline solids"],
["1977","physics","Sir Nevill F. Mott","U.K.","contributions to understanding the behaviour of electrons in magnetic, noncrystalline solids"],
["1977","physics","John H. Van Vleck","U.S.","contributions to understanding the behaviour of electrons in magnetic, noncrystalline solids"],
["1977","physiology/medicine","Roger Charles Louis Guillemin","U.S.","research on pituitary hormones"],
["1977","physiology/medicine","Andrew Victor Schally","U.S.","research on pituitary hormones"],
["1977","physiology/medicine","Rosalyn S. Yalow","U.S.","development of radioimmunoassay"],
["1978","chemistry","Peter Dennis Mitchell","U.K.","formulation of a theory of energy transfer processes in biological systems"],
["1978","economics","Herbert Alexander Simon","U.S.","decision-making processes in economic organizations"],
["1978","literature","Isaac Bashevis Singer","U.S.",""],
["1978","peace","Menachem Begin","Israel",""],
["1978","peace","Anwar el-Sadat","Egypt",""],
["1978","physics","Pyotr Leonidovich Kapitsa","U.S.S.R.","invention and application of helium liquefier"],
["1978","physics","Arno Penzias","U.S.","discovery of cosmic microwave background radiation, providing support for the big-bang theory"],
["1978","physics","Robert Woodrow Wilson","U.S.","discovery of cosmic microwave background radiation, providing support for the big-bang theory"],
["1978","physiology/medicine","Werner Arber","Switzerland","discovery and application of enzymes that fragment DNA"],
["1978","physiology/medicine","Daniel Nathans","U.S.","discovery and application of enzymes that fragment DNA"],
["1978","physiology/medicine","Hamilton Othanel Smith","U.S.","discovery and application of enzymes that fragment DNA"],
["1979","chemistry","Herbert Charles Brown","U.S.","introduction of compounds of boron and phosphorus in the synthesis of organic substances"],
["1979","chemistry","Georg Wittig","West Germany","introduction of compounds of boron and phosphorus in the synthesis of organic substances"],
["1979","economics","Sir Arthur Lewis","U.K.","analyses of economic processes in developing nations"],
["1979","economics","Theodore William Schultz","U.S.","analyses of economic processes in developing nations"],
["1979","literature","Odysseus Elytis","Greece",""],
["1979","peace","Mother Teresa","India",""],
["1979","physics","Sheldon Lee Glashow","U.S.","unification of electromagnetism and the weak interactions of subatomic particles"],
["1979","physics","Abdus Salam","Pakistan","unification of electromagnetism and the weak interactions of subatomic particles"],
["1979","physics","Steven Weinberg","U.S.","unification of electromagnetism and the weak interactions of subatomic particles"],
["1979","physiology/medicine","Allan MacLeod Cormack","U.S.","development of the CAT scan"],
["1979","physiology/medicine","Sir Godfrey Newbold Hounsfield","U.K.","development of the CAT scan"],
["1980","chemistry","Paul Berg","U.S.","first preparation of a hybrid DNA"],
["1980","chemistry","Walter Gilbert","U.S.","development of chemical and biological analyses of DNA structure"],
["1980","chemistry","Frederick Sanger","U.K.","development of chemical and biological analyses of DNA structure"],
["1980","economics","Lawrence Robert Klein","U.S.","development and analysis of empirical models of business fluctuations"],
["1980","literature","Czesław Miłosz","U.S.",""],
["1980","peace","Adolfo Pérez Esquivel","Argentina",""],
["1980","physics","James Watson Cronin","U.S.","demonstration of simultaneous violation of both charge-conjugation and parity-inversion symmetries"],
["1980","physics","Val Logsdon Fitch","U.S.","demonstration of simultaneous violation of both charge-conjugation and parity-inversion symmetries"],
["1980","physiology/medicine","Baruj Benacerraf","U.S.","investigations of genetic control of the response of the immune system to foreign substances"],
["1980","physiology/medicine","Jean-Baptiste-Gabriel-Joachim Dausset","France","investigations of genetic control of the response of the immune system to foreign substances"],
["1980","physiology/medicine","George Davis Snell","U.S.","investigations of genetic control of the response of the immune system to foreign substances"],
["1981","chemistry","Fukui Kenichi","Japan","orbital symmetry interpretation of chemical reactions"],
["1981","chemistry","Roald Hoffmann","U.S.","orbital symmetry interpretation of chemical reactions"],
["1981","economics","James Tobin","U.S.","portfolio selection theory of investment"],
["1981","literature","Elias Canetti","Bulgaria",""],
["1981","peace","Office of the United Nations High Commissioner for Refugees","(founded 1951)",""],
["1981","physics","Nicolaas Bloembergen","U.S.","applications of lasers in spectroscopy"],
["1981","physics","Arthur Leonard Schawlow","U.S.","applications of lasers in spectroscopy"],
["1981","physics","Kai Manne Börje Siegbahn","Sweden","electron spectroscopy for chemical analysis"],
["1981","physiology/medicine","David Hunter Hubel","U.S.","processing of visual information by the brain"],
["1981","physiology/medicine","Roger Wolcott Sperry","U.S.","functions of the cerebral hemispheres"],
["1981","physiology/medicine","Torsten Nils Wiesel","Sweden","processing of visual information by the brain"],
["1982","chemistry","Aaron Klug","U.K.","determination of structure of biological substances"],
["1982","economics","George J. Stigler","U.S.","economic effects of governmental regulation"],
["1982","literature","Gabriel García Márquez","Colombia",""],
["1982","peace","Alfonso García Robles","Mexico",""],
["1982","peace","Alva Myrdal","Sweden",""],
["1982","physics","Kenneth Geddes Wilson","U.S.","analysis of continuous phase transitions"],
["1982","physiology/medicine","Sune K. Bergström","Sweden","biochemistry and physiology of prostaglandins"],
["1982","physiology/medicine","Bengt Ingemar Samuelsson","Sweden","biochemistry and physiology of prostaglandins"],
["1982","physiology/medicine","John Robert Vane","U.K.","biochemistry and physiology of prostaglandins"],
["1983","chemistry","Henry Taube","U.S.","study of electron transfer reactions"],
["1983","economics","Gerard Debreu","U.S.","mathematical proof of supply and demand theory"],
["1983","literature","Sir William Golding","U.K.",""],
["1983","peace","Lech Wałęsa","Poland",""],
["1983","physics","Subrahmanyan Chandrasekhar","U.S.","contributions to understanding the evolution and devolution of stars"],
["1983","physics","William A. Fowler","U.S.","contributions to understanding the evolution and devolution of stars"],
["1983","physiology/medicine","Barbara McClintock","U.S.","discovery of mobile plant genes that affect heredity"],
["1984","chemistry","Bruce Merrifield","U.S.","development of a method of polypeptide synthesis"],
["1984","economics","Sir Richard Stone","U.K.","development of national income accounting system"],
["1984","literature","Jaroslav Seifert","Czechoslovakia",""],
["1984","peace","Desmond Tutu","South Africa",""],
["1984","physics","Simon van der Meer","Netherlands","discovery of subatomic particles W and Z, which supports the electroweak theory"],
["1984","physics","Carlo Rubbia","Italy","discovery of subatomic particles W and Z, which supports the electroweak theory"],
["1984","physiology/medicine","Niels K. Jerne","U.K.-Denmark","theory and development of a technique for producing monoclonal antibodies"],
["1984","physiology/medicine","Georges J.F. Köhler","West Germany","theory and development of a technique for producing monoclonal antibodies"],
["1984","physiology/medicine","César Milstein","Argentina","theory and development of a technique for producing monoclonal antibodies"],
["1985","chemistry","Herbert A. Hauptman","U.S.","development of a way to map the chemical structures of small molecules"],
["1985","chemistry","Jerome Karle","U.S.","development of a way to map the chemical structures of small molecules"],
["1985","economics","Franco Modigliani","U.S.","analyses of household savings and financial markets"],
["1985","literature","Claude Simon","France",""],
["1985","peace","International Physicians for the Prevention of Nuclear War","(founded 1980)",""],
["1985","physics","Klaus von Klitzing","West Germany","discovery of the quantized Hall effect, permitting exact measurements of electrical resistance"],
["1985","physiology/medicine","Michael S. Brown","U.S.","discovery of cell receptors relating to cholesterol metabolism"],
["1985","physiology/medicine","Joseph L. Goldstein","U.S.","discovery of cell receptors relating to cholesterol metabolism"],
["1986","chemistry","Dudley R. Herschbach","U.S.","development of methods for analyzing basic chemical reactions"],
["1986","chemistry","Yuan T. Lee","U.S.","development of methods for analyzing basic chemical reactions"],
["1986","chemistry","John C. Polanyi","Canada","development of methods for analyzing basic chemical reactions"],
["1986","economics","James M. Buchanan","U.S.","public-choice theory bridging economics and political science"],
["1986","literature","Wole Soyinka","Nigeria",""],
["1986","peace","Elie Wiesel","U.S.",""],
["1986","physics","Gerd Binnig","West Germany","development of special electron microscopes"],
["1986","physics","Heinrich Rohrer","Switzerland","development of special electron microscopes"],
["1986","physics","Ernst Ruska","West Germany","development of special electron microscopes"],
["1986","physiology/medicine","Stanley Cohen","U.S.","discovery of chemical agents that help regulate the growth of cells"],
["1986","physiology/medicine","Rita Levi-Montalcini","Italy","discovery of chemical agents that help regulate the growth of cells"],
["1987","chemistry","Donald J. Cram","U.S.","development of molecules that can link with other molecules"],
["1987","chemistry","Jean-Marie Lehn","France","development of molecules that can link with other molecules"],
["1987","chemistry","Charles J. Pedersen","U.S.","development of molecules that can link with other molecules"],
["1987","economics","Robert Merton Solow","U.S.","contributions to the theory of economic growth"],
["1987","literature","Joseph Brodsky","U.S.",""],
["1987","peace","Oscar Arias Sánchez","Costa Rica",""],
["1987","physics","J. Georg Bednorz","West Germany","discovery of new superconducting materials"],
["1987","physics","Karl Alex Müller","Switzerland","discovery of new superconducting materials"],
["1987","physiology/medicine","Tonegawa Susumu","Japan","study of genetic aspects of antibodies"],
["1988","chemistry","Johann Deisenhofer","West Germany","discovery of structure of proteins needed in photosynthesis"],
["1988","chemistry","Robert Huber","West Germany","discovery of structure of proteins needed in photosynthesis"],
["1988","chemistry","Hartmut Michel","West Germany","discovery of structure of proteins needed in photosynthesis"],
["1988","economics","Maurice Allais","France","contributions to the theory of markets and efficient use of resources"],
["1988","literature","Naguib Mahfouz","Egypt",""],
["1988","peace","United Nations Peacekeeping Forces","",""],
["1988","physics","Leon Max Lederman","U.S.","research in subatomic particles"],
["1988","physics","Melvin Schwartz","U.S.","research in subatomic particles"],
["1988","physics","Jack Steinberger","U.S.","research in subatomic particles"],
["1988","physiology/medicine","Sir James Black","U.K.","development of new classes of drugs for combating disease"],
["1988","physiology/medicine","Gertrude Belle Elion","U.S.","development of new classes of drugs for combating disease"],
["1988","physiology/medicine","George Herbert Hitchings","U.S.","development of new classes of drugs for combating disease"],
["1989","chemistry","Sidney Altman","U.S.","discovery of certain basic properties of RNA"],
["1989","chemistry","Thomas Robert Cech","U.S.","discovery of certain basic properties of RNA"],
["1989","economics","Trygve Haavelmo","Norway","development of statistical techniques for economic forecasting"],
["1989","literature","Camilo José Cela","Spain",""],
["1989","peace","Dalai Lama","Tibet",""],
["1989","physics","Hans Georg Dehmelt","U.S.","development of methods to isolate atoms and subatomic particles for study"],
["1989","physics","Wolfgang Paul","West Germany","development of methods to isolate atoms and subatomic particles for study"],
["1989","physics","Norman Foster Ramsey","U.S.","development of the atomic clock"],
["1989","physiology/medicine","J. Michael Bishop","U.S.","study of cancer-causing genes called oncogenes"],
["1989","physiology/medicine","Harold Varmus","U.S.","study of cancer-causing genes called oncogenes"],
["1990","chemistry","Elias James Corey","U.S.","development of retrosynthetic analysis for synthesis of complex molecules"],
["1990","economics","Harry M. Markowitz","U.S.","study of financial markets and investment decision-making"],
["1990","economics","Merton H. Miller","U.S.","study of financial markets and investment decision-making"],
["1990","economics","William F. Sharpe","U.S.","study of financial markets and investment decision-making"],
["1990","literature","Octavio Paz","Mexico",""],
["1990","peace","Mikhail Gorbachev","U.S.S.R.",""],
["1990","physics","Jerome Isaac Friedman","U.S.","discovery of atomic quarks"],
["1990","physics","Henry Way Kendall","U.S.","discovery of atomic quarks"],
["1990","physics","Richard E. Taylor","Canada","discovery of atomic quarks"],
["1990","physiology/medicine","Joseph E. Murray","U.S.","development of kidney and bone-marrow transplants"],
["1990","physiology/medicine","E. Donnall Thomas","U.S.","development of kidney and bone-marrow transplants"],
["1991","chemistry","Richard R. Ernst","Switzerland","improvements in nuclear magnetic resonance spectroscopy"],
["1991","economics","Ronald Coase","U.S.","application of economic principles to the study of law"],
["1991","literature","Nadine Gordimer","South Africa",""],
["1991","peace","Aung San Suu Kyi","Myanmar",""],
["1991","physics","Pierre-Gilles de Gennes","France","discovery of general rules for behaviour of molecules"],
["1991","physiology/medicine","Erwin Neher","Germany","discovery of how cells communicate, as related to diseases"],
["1991","physiology/medicine","Bert Sakmann","Germany","discovery of how cells communicate, as related to diseases"],
["1992","chemistry","Rudolph A. Marcus","U.S.","explanation of how electrons transfer between molecules"],
["1992","economics","Gary S. Becker","U.S.","application of economic theory to social sciences"],
["1992","literature","Derek Walcott","St. Lucia",""],
["1992","peace","Rigoberta Menchú","Guatemala",""],
["1992","physics","Georges Charpak","France","inventor of detector that traces subatomic particles"],
["1992","physiology/medicine","Edmond H. Fischer","U.S.","discovery of class of enzymes called protein kinases"],
["1992","physiology/medicine","Edwin Gerhard Krebs","U.S.","discovery of class of enzymes called protein kinases"],
["1993","chemistry","Kary B. Mullis","U.S.","inventors of techniques for gene study and manipulation"],
["1993","chemistry","Michael Smith","Canada","inventors of techniques for gene study and manipulation"],
["1993","economics","Robert William Fogel","U.S.","contributions to economic history"],
["1993","economics","Douglass C. North","U.S.","contributions to economic history"],
["1993","literature","Toni Morrison","U.S.",""],
["1993","peace","F.W. de Klerk","South Africa",""],
["1993","peace","Nelson Mandela","South Africa",""],
["1993","physics","Russell Alan Hulse","U.S.","identifying binary pulsars"],
["1993","physics","Joseph H. Taylor, Jr.","U.S.","identifying binary pulsars"],
["1993","physiology/medicine","Richard J. Roberts","U.K.","discovery of \"split,\" or interrupted, genetic structure"],
["1993","physiology/medicine","Phillip A. Sharp","U.S.","discovery of \"split,\" or interrupted, genetic structure"],
["1994","chemistry","George A. Olah","U.S.","development of techniques to study hydrocarbon molecules"],
["1994","economics","John C. Harsanyi","U.S.","development of game theory"],
["1994","economics","John F. Nash","U.S.","development of game theory"],
["1994","economics","Reinhard Selten","Germany","development of game theory"],
["1994","literature","Oe Kenzaburo","Japan",""],
["1994","peace","Yasser Arafat","Palestinian",""],
["1994","peace","Shimon Peres","Israel",""],
["1994","peace","Yitzhak Rabin","Israel",""],
["1994","physics","Bertram N. Brockhouse","Canada","development of neutron-scattering techniques"],
["1994","physics","Clifford G. Shull","U.S.","development of neutron-scattering techniques"],
["1994","physiology/medicine","Alfred G. Gilman","U.S.","discovery of cell signalers called G-proteins"],
["1994","physiology/medicine","Martin Rodbell","U.S.","discovery of cell signalers called G-proteins"],
["1995","chemistry","Paul Crutzen","Netherlands","explanation of processes that deplete Earth's ozone layer"],
["1995","chemistry","Mario Molina","U.S.","explanation of processes that deplete Earth's ozone layer"],
["1995","chemistry","F. Sherwood Rowland","U.S.","explanation of processes that deplete Earth's ozone layer"],
["1995","economics","Robert E. Lucas, Jr.","U.S.","incorporation of rational expectations in macroeconomic theory"],
["1995","literature","Seamus Heaney","Ireland",""],
["1995","peace","Pugwash Conferences","(founded 1957)",""],
["1995","peace","Joseph Rotblat","U.K.",""],
["1995","physics","Martin Lewis Perl","U.S.","discovery of tau subatomic particle"],
["1995","physics","Frederick Reines","U.S.","discovery of neutrino subatomic particle"],
["1995","physiology/medicine","Edward B. Lewis","U.S.","identification of genes that control the body's early structural development"],
["1995","physiology/medicine","Christiane Nüsslein-Volhard","Germany","identification of genes that control the body's early structural development"],
["1995","physiology/medicine","Eric F. Wieschaus","U.S.","identification of genes that control the body's early structural development"],
["1996","chemistry","Robert F. Curl, Jr.","U.S.","discovery of new carbon compounds called fullerenes"],
["1996","chemistry","Sir Harold W. Kroto","U.K.","discovery of new carbon compounds called fullerenes"],
["1996","chemistry","Richard E. Smalley","U.S.","discovery of new carbon compounds called fullerenes"],
["1996","economics","James A. Mirrlees","U.K.","contributions to theory of incentives under conditions of asymmetric information"],
["1996","economics","William Vickrey","U.S.","contributions to theory of incentives under conditions of asymmetric information"],
["1996","literature","Wisława Szymborska","Poland",""],
["1996","peace","Carlos Felipe Ximenes Belo","Timorese",""],
["1996","peace","José Ramos-Horta","Timorese",""],
["1996","physics","David M. Lee","U.S.","discovery of superfluidity in isotope helium-3"],
["1996","physics","Douglas D. Osheroff","U.S.","discovery of superfluidity in isotope helium-3"],
["1996","physics","Robert C. Richardson","U.S.","discovery of superfluidity in isotope helium-3"],
["1996","physiology/medicine","Peter C. Doherty","Australia","discovery of how the immune system recognizes virus-infected cells"],
["1996","physiology/medicine","Rolf M. Zinkernagel","Switzerland","discovery of how the immune system recognizes virus-infected cells"],
["1997","chemistry","Paul D. Boyer","U.S.","explanation of the enzymatic conversion of adenosine triphosphate"],
["1997","chemistry","Jens C. Skou","Denmark","discovery of sodium-potassium-activated adenosine triphosphatase"],
["1997","chemistry","John E. Walker","U.K.","explanation of the enzymatic conversion of adenosine triphosphate"],
["1997","economics","Robert C. Merton","U.S.","methods for determining the value of stock options and other derivatives"],
["1997","economics","Myron S. Scholes","U.S.","methods for determining the value of stock options and other derivatives"],
["1997","literature","Dario Fo","Italy",""],
["1997","peace","International Campaign to Ban Landmines","(founded 1992)",""],
["1997","peace","Jody Williams","U.S.",""],
["1997","physics","Steven Chu","U.S.","process of trapping atoms with laser cooling"],
["1997","physics","Claude Cohen-Tannoudji","France","process of trapping atoms with laser cooling"],
["1997","physics","William D. Phillips","U.S.","process of trapping atoms with laser cooling"],
["1997","physiology/medicine","Stanley B. Prusiner","U.S.","discovery of the prion, a type of disease-causing protein"],
["1998","chemistry","Walter Kohn","U.S.","development of the density-functional theory"],
["1998","chemistry","John A. Pople","U.K.","development of computational methods in quantum chemistry"],
["1998","economics","Amartya Sen","India","contribution to welfare economics"],
["1998","literature","José Saramago","Portugal"],
["1998","peace","John Hume","Northern Ireland",""],
["1998","peace","David Trimble","Northern Ireland",""],
["1998","physics","Robert B. Laughlin","U.S.","discovery of fractional quantum Hall effect"],
["1998","physics","Horst L. Störmer","U.S.","discovery of fractional quantum Hall effect"],
["1998","physics","Daniel C. Tsui","U.S.","discovery of fractional quantum Hall effect"],
["1998","physiology/medicine","Robert F. Furchgott","U.S.","discovery that nitric oxide (NO) acts as a signaling molecule in the cardiovascular system"],
["1998","physiology/medicine","Louis J. Ignarro","U.S.","discovery that nitric oxide (NO) acts as a signaling molecule in the cardiovascular system"],
["1998","physiology/medicine","Ferid Murad","U.S.","discovery that nitric oxide (NO) acts as a signaling molecule in the cardiovascular system"],
["1999","chemistry","Ahmed H. Zewail","Egypt/U.S.","study of the transition states of chemical reactions using femtosecond spectroscopy"],
["1999","economics","Robert A. Mundell","Canada","analysis of optimum currency areas and of policy under different exchange rate regimes"],
["1999","literature","Günter Grass","Germany",""],
["1999","peace","Doctors Without Borders","(founded 1971)",""],
["1999","physics","Gerardus 't Hooft","Netherlands","study of quantum structure of electroweak interactions"],
["1999","physics","Martinus J.G. Veltman","Netherlands","study of quantum structure of electroweak interactions"],
["1999","physiology/medicine","Günter Blobel","U.S.","discovery that proteins have signals governing cellular organization"],
["2000","chemistry","Alan J. Heeger","U.S.","discovery of plastics that conduct electricity"],
["2000","chemistry","Alan G. MacDiarmid","U.S.","discovery of plastics that conduct electricity"],
["2000","chemistry","Shirakawa Hideki","Japan","discovery of plastics that conduct electricity"],
["2000","economics","James J. Heckman","U.S.","development of methods of statistical analysis of individual and household behaviour"],
["2000","economics","Daniel L. McFadden","U.S.","development of methods of statistical analysis of individual and household behaviour"],
["2000","literature","Gao Xingjian","France",""],
["2000","peace","Kim Dae-Jung","South Korea",""],
["2000","physics","Zhores I. Alferov","Russia","development of fast semiconductors for use in microelectronics"],
["2000","physics","Jack S. Kilby","U.S.","development of the integrated circuit (microchip)"],
["2000","physics","Herbert Kroemer","Germany","development of fast semiconductors for use in microelectronics"],
["2000","physiology/medicine","Arvid Carlsson","Sweden","discovery of how signals are transmitted between nerve cells in the brain"],
["2000","physiology/medicine","Paul Greengard","U.S.","discovery of how signals are transmitted between nerve cells in the brain"],
["2000","physiology/medicine","Eric R. Kandel","U.S.","discovery of how signals are transmitted between nerve cells in the brain"],
["2001","chemistry","William S. Knowles","U.S.","work on chirally catalyzed hydrogenation reactions"],
["2001","chemistry","Noyori Ryoji","Japan","work on chirally catalyzed hydrogenation reactions"],
["2001","chemistry","K. Barry Sharpless","U.S.","work on chirally catalyzed oxidation reactions"],
["2001","economics","George A. Akerlof","U.S.","analysis of markets with asymmetric information"],
["2001","economics","A. Michael Spence","U.S.","analysis of markets with asymmetric information"],
["2001","economics","Joseph E. Stiglitz","U.S.","analysis of markets with asymmetric information"],
["2001","literature","Sir V.S. Naipaul","Trinidad",""],
["2001","peace","United Nations","(founded 1945)",""],
["2001","peace","Kofi Annan","Ghana",""],
["2001","physics","Eric A. Cornell","U.S.","achievement of Bose-Einstein condensation in dilute gases of alkali atoms; early fundamental studies of the properties of the condensates"],
["2001","physics","Wolfgang Ketterle","Germany","achievement of Bose-Einstein condensation in dilute gases of alkali atoms; early fundamental studies of the properties of the condensates"],
["2001","physics","Carl E. Wieman","U.S.","achievement of Bose-Einstein condensation in dilute gases of alkali atoms; early fundamental studies of the properties of the condensates"],
["2001","physiology/medicine","Leland H. Hartwell","U.S.","discovery of key regulators of the cell cycle"],
["2001","physiology/medicine","R. Timothy Hunt","U.K.","discovery of key regulators of the cell cycle"],
["2001","physiology/medicine","Sir Paul M. Nurse","U.K.","discovery of key regulators of the cell cycle"],
["2002","chemistry","John B. Fenn","U.S.","development of techniques to identify and analyze proteins and other large molecules"],
["2002","chemistry","Tanaka Koichi","Japan","development of techniques to identify and analyze proteins and other large molecules"],
["2002","chemistry","Kurt Wüthrich","Switzerland","development of techniques to identify and analyze proteins and other large molecules"],
["2002","economics","Daniel Kahneman","U.S./Israel","integration of psychological research into economic science, especially concerning human judgment and decision-making under uncertainty"],
["2002","economics","Vernon L. Smith","U.S.","establishment of laboratory experiments as a tool in empirical economic analysis"],
["2002","literature","Imre Kertész","Hungary",""],
["2002","peace","Jimmy Carter","U.S.",""],
["2002","physics","Raymond Davis, Jr.","U.S.","detection of neutrinos"],
["2002","physics","Riccardo Giacconi","U.S.","seminal discoveries of cosmic sources of X-rays"],
["2002","physics","Koshiba Masatoshi","Japan","detection of neutrinos"],
["2002","physiology/medicine","Sydney Brenner","U.K.","discoveries concerning genetic regulation of organ development and programmed cell death (apoptosis)"],
["2002","physiology/medicine","H. Robert Horvitz","U.S.","discoveries concerning genetic regulation of organ development and programmed cell death (apoptosis)"],
["2002","physiology/medicine","John E. Sulston","U.K.","discoveries concerning genetic regulation of organ development and programmed cell death (apoptosis)"],
["2003","chemistry","Peter Agre","U.S.","discoveries regarding water channels and ion channels in cells"],
["2003","chemistry","Roderick MacKinnon","U.S.","discoveries regarding water channels and ion channels in cells"],
["2003","economics","Robert F. Engle","U.S.","development of techniques for the analysis of time series data"],
["2003","economics","Clive W.J. Granger","U.K.","development of techniques for the analysis of time series data"],
["2003","literature","J.M. Coetzee","South Africa",""],
["2003","peace","Shirin Ebadi","Iran",""],
["2003","physics","Alexei A. Abrikosov","U.S.","discoveries regarding superconductivity and superfluidity at very low temperatures"],
["2003","physics","Vitaly L. Ginzburg","Russia","discoveries regarding superconductivity and superfluidity at very low temperatures"],
["2003","physics","Anthony J. Leggett","U.S.","discoveries regarding superconductivity and superfluidity at very low temperatures"],
["2003","physiology/medicine","Paul Lauterbur","U.S.","development of magnetic resonance imaging (MRI)"],
["2003","physiology/medicine","Sir Peter Mansfield","U.K.","development of magnetic resonance imaging (MRI)"],
["2004","chemistry","Aaron Ciechanover","Israel","discovery of ubiquitin-mediated protein degradation"],
["2004","chemistry","Avram Hershko","Israel","discovery of ubiquitin-mediated protein degradation"],
["2004","chemistry","Irwin Rose","U.S.","discovery of ubiquitin-mediated protein degradation"],
["2004","economics","Finn E. Kydland","Norway","contributions to dynamic macroeconomics"],
["2004","economics","Edward C. Prescott","U.S.","contributions to dynamic macroeconomics"],
["2004","literature","Elfriede Jelinek","Austria",""],
["2004","peace","Wangari Maathi","Kenya",""],
["2004","physics","David J. Gross","U.S.","discovery of asymptotic freedom in the theory of the strong interaction"],
["2004","physics","H. David Politzer","U.S.","discovery of asymptotic freedom in the theory of the strong interaction"],
["2004","physics","Frank Wilczek","U.S.","discovery of asymptotic freedom in the theory of the strong interaction"],
["2004","physiology/medicine","Richard Axel","U.S.","discovery of odorant receptors and the organization of the olfactory system"],
["2004","physiology/medicine","Linda B. Buck","U.S.","discovery of odorant receptors and the organization of the olfactory system"],
["2005","chemistry","Yves Chauvin","France","development of the metathesis method in organic synthesis"],
["2005","chemistry","Robert H. Grubbs","U.S.","development of the metathesis method in organic synthesis"],
["2005","chemistry","Richard R. Schrock","U.S.","development of the metathesis method in organic synthesis"],
["2005","economics","Robert J. Aumann","Israel","contributions to game-theory analysis"],
["2005","economics","Thomas C. Schelling","U.S.","contributions to game-theory analysis"],
["2005","literature","Harold Pinter","U.K.",""],
["2005","peace","Mohamed ElBaradei","Egypt",""],
["2005","peace","International Atomic Energy Agency","(founded 1957)",""],
["2005","physics","Roy J. Glauber","U.S.","contributions to the field of optics"],
["2005","physics","John L. Hall","U.S.","contributions to the development of laser spectroscopy"],
["2005","physics","Theodor W. Hänsch","Germany","contributions to the development of laser spectroscopy"],
["2005","physiology/medicine","Barry J. Marshall","Australia","discovery of bacteria's role in peptic ulcer disease"],
["2005","physiology/medicine","J. Robin Warren","Australia","discovery of bacteria's role in peptic ulcer disease"],
["2006","chemistry","Roger D. Kornberg","U.S.","work on the molecular basis of eukaryotic transcription"],
["2006","economics","Edmund S. Phelps","U.S.","analysis of intertemporal trade-offs in macroeconomic policy"],
["2006","literature","Orhan Pamuk","Turkey",""],
["2006","peace","Grameen Bank","(founded 1976)",""],
["2006","peace","Muhammad Yunus","Bangladesh",""],
["2006","physics","John C. Mather","U.S.","discovery of the blackbody form and anisotropy of the cosmic microwave background radiation"],
["2006","physics","George F. Smoot","U.S.","discovery of the blackbody form and anisotropy of the cosmic microwave background radiation"],
["2006","physiology/medicine","Andrew Z. Fire","U.S.","discovery of RNA interference—gene silencing by double-stranded RNA"],
["2006","physiology/medicine","Craig C. Mello","U.S.","discovery of RNA interference—gene silencing by double-stranded RNA"],
["2007","chemistry","Gerhard Ertl","Germany","studies of chemical processes on solid surfaces"],
["2007","economics","Leonid Hurwicz","U.S.","work that laid the foundations of mechanism design theory"],
["2007","economics","Eric S. Maskin","U.S.","work that laid the foundations of mechanism design theory"],
["2007","economics","Roger B. Myerson","U.S.","work that laid the foundations of mechanism design theory"],
["2007","literature","Doris Lessing","U.S.",""],
["2007","peace","Al Gore","U.S.",""],
["2007","peace","Intergovernmental Panel on Climate Change","(founded 1988)",""],
["2007","physics","Albert Fert","France","discovery of giant magnetoresistance"],
["2007","physics","Peter Grünberg","Germany","discovery of giant magnetoresistance"],
["2007","physiology/medicine","Mario R. Capecchi","U.S.","discovery of principles for introducing specific gene modifications in mice by the use of embryonic stem cells"],
["2007","physiology/medicine","Sir Martin J. Evans","U.K.","discovery of principles for introducing specific gene modifications in mice by the use of embryonic stem cells"],
["2007","physiology/medicine","Oliver Smithies","U.S.","discovery of principles for introducing specific gene modifications in mice by the use of embryonic stem cells"],
["2008","chemistry","Martin Chalfie","U.S.","discovery and development of the green fluorescent protein, GFP"],
["2008","chemistry","Osamu Shimomura","U.S.","discovery and development of the green fluorescent protein, GFP"],
["2008","chemistry","Roger Y. Tsien","U.S.","discovery and development of the green fluorescent protein, GFP"],
["2008","economics","Paul Krugman","U.S.","analysis of trade patterns and location of economic activity"],
["2008","literature","Jean-Marie Gustave Le Clézio","France",""],
["2008","peace","Martti Ahtisaari","Finland",""],
["2008","physics","Kobayashi Makoto","Japan","discovery of the origin of the broken symmetry which predicts the existence of at least three families of quarks in nature"],
["2008","physics","Maskawa Toshihide","Japan","discovery of the origin of the broken symmetry which predicts the existence of at least three families of quarks in nature"],
["2008","physics","Yoichiro Nambu","U.S.","discovery of the mechanism of spontaneous broken symmetry in subatomic physics"],
["2008","physiology/medicine","Françoise Barré-Sinoussi","France","discovery of human immunodeficiency virus"],
["2008","physiology/medicine","Luc Montagnier","France","discovery of human immunodeficiency virus"],
["2008","physiology/medicine","Harald zur Hausen","Germany","discovery of human papilloma viruses causing cervical cancer"],
["2009","chemistry","Venkatraman Ramakrishnan","U.S.","studies of the structure and function of the ribosome"],
["2009","chemistry","Thomas Steitz","U.S.","studies of the structure and function of the ribosome"],
["2009","chemistry","Ada Yonath","Israel","studies of the structure and function of the ribosome"],
["2009","economics","Elinor Ostrom","U.S.","analysis of economic governance, especially the commons"],
["2009","economics","Oliver E. Williamson","U.S.","analysis of economic governance, especially the boundaries of the firm"],
["2009","literature","Herta Müller","Germany",""],
["2009","peace","Barack Obama","U.S.",""],
["2009","physics","Willard Boyle","Canada/U.S.","invention of the CCD sensor, an imaging semiconductor circuit"],
["2009","physics","Charles Kao","U.K./U.S.","achievements concerning the transmission of light in fibres for optical communication"],
["2009","physics","George E. Smith","U.S.","invention of the CCD sensor, an imaging semiconductor circuit"],
["2009","physiology/medicine","Elizabeth H. Blackburn","U.S.","discovery of how chromosomes are protected by telomeres and the enzyme telomerase"],
["2009","physiology/medicine","Carol W. Greider","U.S.","discovery of how chromosomes are protected by telomeres and the enzyme telomerase"],
["2009","physiology/medicine","Jack W. Szostak","U.S.","discovery of how chromosomes are protected by telomeres and the enzyme telomerase"],
["2010","chemistry","Richard F. Heck","U.S.","development of techniques to synthesize complex carbon molecules"],
["2010","chemistry","Negishi Ei-ichi","Japan","development of techniques to synthesize complex carbon molecules"],
["2010","chemistry","Suzmediuki Akira","Japan","development of techniques to synthesize complex carbon molecules"],
["2010","economics","Peter A. Diamond","U.S.","analysis of markets with search frictions"],
["2010","economics","Dale T. Mortensen","U.S.","analysis of markets with search frictions"],
["2010","economics","Christopher A. Pissarides","Cyprus/U.K.","analysis of markets with search frictions"],
["2010","literature","Mario Vargas Llosa","Peru",""],
["2010","peace","Liu Xiaobo","China",""],
["2010","physics","Andre Geim","Netherlands","experiments regarding the two-dimensional material graphene"],
["2010","physics","Konstantin Novoselov","Russia/U.K.","experiments regarding the two-dimensional material graphene"],
["2010","physiology/medicine","Robert Edwards","U.K.","development of in vitro fertilization"],
["2011","chemistry","Daniel Shechtman","Israel","discovery of quasicrystals"],
["2011","economics","Thomas J. Sargent","U.S.","empirical research on cause and effect in the macroeconomy"],
["2011","economics","Christopher A. Sims","U.S.","empirical research on cause and effect in the macroeconomy"],
["2011","literature","Tomas Tranströmer","Sweden",""],
["2011","peace","Leymah Gbowee","Liberia",""],
["2011","peace","Ellen Johnson Sirleaf","Liberia",""],
["2011","peace","Tawakkul Karmān","Yemen",""],
["2011","physics","Saul Perlmutter","U.S.","discovery of the accelerating expansion of the universe through observations of distant supernovae"],
["2011","physics","Adam G. Riess","U.S./Australia","discovery of the accelerating expansion of the universe through observations of distant supernovae"],
["2011","physics","Brian P. Schmidt","U.S.","discovery of the accelerating expansion of the universe through observations of distant supernovae"],
["2011","physiology/medicine","Bruce A. Beutler","U.S.","discoveries concerning the activation of innate immunity"],
["2011","physiology/medicine","Jules A. Hoffman","Luxembourg/France","discoveries concerning the activation of innate immunity"],
["2011","physiology/medicine","Ralph M. Steinman","Canada","discovery of the dendritic cell and its role in adaptive immunity"],
["2012","chemistry","Brian K. Kobilka","U.S.","studies of G-protein-coupled receptors"],
["2012","chemistry","Robert J. Lefkowitz","U.S.","studies of G-protein-coupled receptors"],
["2012","economics","Alvin E. Roth","U.S.","work on market design and matching theory"],
["2012","economics","Lloyd S. Shapley","U.S.","work on market design and matching theory"],
["2012","literature","Mo Yan","China",""],
["2012","peace","European Union","(founded 1993)",""],
["2012","physics","Serge Haroche","France","development of methods that enable measuring and manipulation of individual quantum systems"],
["2012","physics","David J. Wineland","U.S.","development of methods that enable measuring and manipulation of individual quantum systems"],
["2012","physiology/medicine","Sir John Bertrand Gurdon","U.K.","discovery that mature cells can be reprogrammed to become pluripotent"],
["2012","physiology/medicine","Shinya Yamanaka","Japan","discovery that mature cells can be reprogrammed to become pluripotent"],
["2013","chemistry","Martin Karplus","Austria/U.S.","development of multiscale models for complex chemical systems"],
["2013","chemistry","Michael Levitt","U.K./U.S./Israel","development of multiscale models for complex chemical systems"],
["2013","chemistry","Arieh Warshel","Israel/U.S.","development of multiscale models for complex chemical systems"],
["2013","economics","Eugene F. Fama","U.S.","empirical analysis of asset prices"],
["2013","economics","Lars P. Hansen","U.S.","empirical analysis of asset prices"],
["2013","economics","Robert J. Shiller","U.S.","empirical analysis of asset prices"],
["2013","literature","Alice Munro","Canada",""],
["2013","peace","Organisation for the Prohibition of Chemical Weapons","(founded 1997)",""],
["2013","physics","François Englert","Belgium","theoretical discovery of a mechanism that contributes to the understanding of the origin of mass of subatomic particles"],
["2013","physics","Peter Higgs","U.K.","theoretical discovery of a mechanism that contributes to the understanding of the origin of mass of subatomic particles"],
["2013","physiology/medicine","James E. Rothman","U.S.","discoveries of machinery regulating vesicle traffic, a major transport system in cells"],
["2013","physiology/medicine","Randy W. Schekman","U.S.","discoveries of machinery regulating vesicle traffic, a major transport system in cells"],
["2013","physiology/medicine","Thomas C. Südhof","Germany/U.S.","discoveries of machinery regulating vesicle traffic, a major transport system in cells"],
["2014","chemistry","Eric Betzig","U.S.","development of super-resolved fluorescence microscopy"],
["2014","chemistry","Stefan W. Hell","Germany","development of super-resolved fluorescence microscopy"],
["2014","chemistry","William E. Moerner","U.S.","development of super-resolved fluorescence microscopy"],
["2014","economics","Jean Tirole","France","analysis of market power and regulation"],
["2014","literature","Patrick Modiano","France",""],
["2014","peace","Kailash Satyarthi","India",""],
["2014","peace","Malala Yousafzai","Pakistan",""],
["2014","physics","Akasaki Isamu","Japan","invention of efficient blue light-emitting diodes, which has enabled bright and energy-saving white light sources"],
["2014","physics","Amano Hiroshi","Japan","invention of efficient blue light-emitting diodes, which has enabled bright and energy-saving white light sources"],
["2014","physics","Shuji Nakamura","U.S.","invention of efficient blue light-emitting diodes, which has enabled bright and energy-saving white light sources"],
["2014","physiology/medicine","Edvard I. Moser","Norway","discoveries of cells that constitute a positioning system in the brain"],
["2014","physiology/medicine","May-Britt Moser","Norway","discoveries of cells that constitute a positioning system in the brain"],
["2014","physiology/medicine","John O'Keefe","U.S./U.K.","discoveries of cells that constitute a positioning system in the brain"],
["2015","chemistry","Tomas Lindahl","Sweden","mechanistic studies of DNA repair"],
["2015","chemistry","Paul Modrich","U.S.","mechanistic studies of DNA repair"],
["2015","chemistry","Aziz Sancar","Turkey/U.S.","mechanistic studies of DNA repair"],
["2015","economics","Angus S. Deaton","U.K.","analysis of consumption, poverty, and welfare"],
["2015","literature","Svetlana Alexievich","Belarus",""],
["2015","peace","National Dialogue Quartet","(founded 2013)",""],
["2015","physics","Kajita Takaaki","Japan","discovery of neutrino oscillations, which show that neutrinos have mass"],
["2015","physics","Arthur B. McDonald","Canada","discovery of neutrino oscillations, which show that neutrinos have mass"],
["2015","physiology/medicine","William C. Campbell","Ireland","discoveries concerning a novel therapy against infections caused by roundworm parasites"],
["2015","physiology/medicine","Ōmura Satoshi","Japan","discoveries concerning a novel therapy against infections caused by roundworm parasites"],
["2015","physiology/medicine","Tu Youyou","China","discoveries concerning a novel therapy against malaria"],
["2016","chemistry","Jean-Pierre Sauvage","France","design and synthesis of molecular machines"],
["2016","chemistry","J. Fraser Stoddart","U.K.","design and synthesis of molecular machines"],
["2016","chemistry","Bernard Feringa","Netherlands","design and synthesis of molecular machines"],
["2016","economics","Oliver Hart","U.K.","contributions to contract theory"],
["2016","economics","Bengt Holmström","Finland","contributions to contract theory"],
["2016","literature","Bob Dylan","U.S.",""],
["2016","peace","Juan Manuel Santos","Colombia",""],
["2016","physics","David Thouless","U.K.","theoretical discoveries of topological phase transitions and topological phases of matter"],
["2016","physics","Duncan Haldane","U.K.","theoretical discoveries of topological phase transitions and topological phases of matter"],
["2016","physics","Michael Kosterlitz","U.K.","theoretical discoveries of topological phase transitions and topological phases of matter"],
["2016","physiology/medicine","Yoshinori Ohsumi","Japan","discoveries of mechanisms for autophagy"],
["2017","chemistry","Jacques Dubochet","Switzerland","development of cryo-electron microscopy for the high-resolution structure determination of biomolecules in solution"],
["2017","chemistry","Joachim Frank","Germany/U.S.","development of cryo-electron microscopy for the high-resolution structure determination of biomolecules in solution"],
["2017","chemistry","Richard Henderson","U.K.","development of cryo-electron microscopy for the high-resolution structure determination of biomolecules in solution"],
["2017","economics","Richard H. Thaler","U.S.","contributions to behavioral economics"],
["2017","literature","Kazuo Ishiguro","U.K.",""],
["2017","peace","International Campaign to Abolish Nuclear Weapons","(founded 2007)",""],
["2017","physics","Barry C. Barish","U.S.","decisive contributions to the Laser Interferometer Gravitational-Wave Observatory detector and the observation of gravitational waves"],
["2017","physics","Kip S. Thorne","U.S.","decisive contributions to the Laser Interferometer Gravitational-Wave Observatory detector and the observation of gravitational waves"],
["2017","physics","Rainer Weiss","U.S.","decisive contributions to the Laser Interferometer Gravitational-Wave Observatory detector and the observation of gravitational waves"],
["2017","physiology/medicine","Jeffrey C. Hall","U.S.","discoveries of molecular mechanisms controlling the circadian rhythm"],
["2017","physiology/medicine","Michael Rosbash","U.S.","discoveries of molecular mechanisms controlling the circadian rhythm"],
["2017","physiology/medicine","Michael W. Young","U.S.","discoveries of molecular mechanisms controlling the circadian rhythm"],
["2018","chemistry","Frances Arnold","U.S.","first directed evolution of enzymes"],
["2018","chemistry","George P. Smith","U.S.","development of phage display, a method in which a bacteriophage can be used to evolve new proteins"],
["2018","chemistry","Gregory P. Winter","U.K.","work using the phage display method for the directed evolution of antibodies"],
["2018","economics","William Nordhaus","U.S.","integration of climate change into long-run macroeconomic analysis"],
["2018","economics","Paul Romer","U.S.","integration of technological innovations into long-run macroeconomic analysis"],
["2018","literature**","Olga Tokarczuk","Poland",""],
["2018","peace","Denis Mukwege","Democratic Republic of the Congo",""],
["2018","peace","Nadia Murad","Iraq",""],
["2018","physics","Arthur Ashkin","U.S.","invention of optical tweezers and their application to biological systems"],
["2018","physics","Gérard Mourou","France","invention of a method of generating high-intensity ultrashort optical pulses"],
["2018","physics","Donna Strickland","Canada","invention of a method of generating high-intensity ultrashort optical pulses"],
["2018","physiology/medicine","James P. Allison","U.S.","discovery of cancer therapy by inhibition of negative immune regulation"],
["2018","physiology/medicine","Tasuku Honjo","Japan","discovery of cancer therapy by inhibition of negative immune regulation"],
["2019","chemistry","John B. Goodenough","U.S.","development of lithium-ion batteries"],
["2019","chemistry","M. Stanley Whittingham","U.K./U.S.","development of lithium-ion batteries"],
["2019","chemistry","Yoshino Akira","Japan","development of lithium-ion batteries"],
["2019","economics","Abhijit Banerjee","U.S.","experimental approach to alleviating global poverty"],
["2019","economics","Esther Duflo","French/U.S.","experimental approach to alleviating global poverty"],
["2019","economics","Michael Kremer","U.S.","experimental approach to alleviating global poverty"],
["2019","literature","Peter Handke","Austria",""],
["2019","peace","Abiy Ahmed","Ethiopia",""],
["2019","physics","James Peebles","Canada/U.S.","theoretical discoveries in physical cosmology"],
["2019","physics","Michel Mayor","Switzerland","discovery of an exoplanet orbiting a solar-type star"],
["2019","physics","Didier Queloz","Switzerland","discovery of an exoplanet orbiting a solar-type star"],
["2019","physiology/medicine","William G. Kaelin, Jr.","U.S.","discoveries of how cells sense and adapt to oxygen availability"],
["2019","physiology/medicine","Peter J. Ratcliffe","U.K.","discoveries of how cells sense and adapt to oxygen availability"],
["2019","physiology/medicine","Gregg L. Semenza","U.S.","discoveries of how cells sense and adapt to oxygen availability"],
["2020","chemistry","Emmanuelle Charpentier","France","development of a method for genome editing"],
["2020","chemistry","Jennifer Doudna","U.S.","development of a method for genome editing"],
["2020","economics","Paul R. Milgrom","U.S.","improvements to auction theory and inventions of new auction formats"],
["2020","economics","Robert B. Wilson","U.S.","improvements to auction theory and inventions of new auction formats"],
["2020","literature","Louise Glück","U.S.",""],
["2020","peace","World Food Programme","(founded 1961)",""],
["2020","physics","Reinhard Genzel","Germany","discovery of a supermassive compact object at the centre of the Milky Way Galaxy"],
["2020","physics","Andrea Ghez","U.S.","discovery of a supermassive compact object at the centre of the Milky Way Galaxy"],
["2020","physics","Roger Penrose","U.K.","discovery that black hole formation is a robust prediction of the general theory of relativity"],
["2020","physiology/medicine","Harvey J. Alter","U.S.","discovery of hepatitis C virus"],
["2020","physiology/medicine","Michael Houghton","U.K.","discovery of hepatitis C virus"],
["2020","physiology/medicine","Charles M. Rice","U.S.","discovery of hepatitis C virus"],
["2021","chemistry","Benjamin List","Germany","development of asymmetric organocatalysis"],
["2021","chemistry","David W.C. MacMillan","U.K./U.S.","development of asymmetric organocatalysis"],
["2021","economics","Joshua Angrist","Israel/U.S.","methodological contributions to the analysis of causal relationships"],
["2021","economics","David Card","Canada/U.S.","empirical contributions to labour economics"],
["2021","economics","Guido W. Imbens","Neth./U.S.","methodological contributions to the analysis of causal relationships"],
["2021","literature","Abdulrazak Gurnah","Tanz.",""],
["2021","peace","Dmitry Muratov","Russia",""],
["2021","peace","Maria Ressa","Phil./U.S.",""],
["2021","physics","Klaus Hasselmann","Germany","physical modelling of Earth's climate, quantifying variability and reliably predicting global warming"],
["2021","physics","Manabe Syukuro","Japan/U.S.","physical modelling of Earth's climate, quantifying variability and reliably predicting global warming"],
["2021","physics","Giorgio Parisi","Italy","discovery of the interplay of disorder and fluctuations in physical systems from atomic to planetary scales"],
["2021","physiology/medicine","David Julius","U.S.","discoveries of receptors for temperature and touch"],
["2021","physiology/medicine","Ardem Patapoutian","U.S.","discoveries of receptors for temperature and touch"],
["2022","chemistry","Carolyn R. Bertozzi","U.S.","development of click chemistry and bioorthogonal chemistry"],
["2022","chemistry","Morten P. Meldal","Neth.","development of click chemistry and bioorthogonal chemistry"],
["2022","chemistry","K. Barry Sharpless","U.S.","development of click chemistry and bioorthogonal chemistry"],
["2022","economics","Ben Bernanke","U.S.","research on banks and financial crises"],
["2022","economics","Douglas Diamond","U.S.","research on banks and financial crises"],
["2022","economics","Philip Dybvig","U.S.","research on banks and financial crises"],
["2022","literature","Annie Ernaux","France",""],
["2022","peace","Ales Bialiatski","Belarus",""],
["2022","peace","Center for Civil Liberties","Ukraine",""],
["2022","peace","Memorial","Russia",""],
["2022","physics","Alain Aspect","France","experiments with quantum entanglement that laid the foundation for a new era of quantum technology"],
["2022","physics","John F. Clauser","U.S.","experiments with quantum entanglement that laid the foundation for a new era of quantum technology"],
["2022","physics","Anton Zeilinger","Austria","experiments with quantum entanglement that laid the foundation for a new era of quantum technology"],
["2022","physiology/medicine","Svante Pääbo","Sweden","discoveries concerning the genomes of extinct hominins and human evolution"],
["2023","chemistry","Moungi Bawendi","France/U.S.","discovery and synthesis of quantum dots"],
["2023","chemistry","Louis Brus","U.S.","discovery and synthesis of quantum dots"],
["2023","chemistry","Alexei Ekimov","Russia/U.S.","discovery and synthesis of quantum dots"],
["2023","economics","Claudia Goldin","U.S.","research on women’s labour market outcomes"],
["2023","literature","Jon Fosse","U.S.",""],
["2023","peace","Narges Mohammadi","Iran",""],
["2023","physics","Pierre Agostini","France","development of experimental methods that generate attosecond pulses of light for the study of electron dynamics in matter"],
["2023","physics","Ferenc Krausz","Hungary","development of experimental methods that generate attosecond pulses of light for the study of electron dynamics in matter"],
["2023","physics","Anne L’Huillier","France","development of experimental methods that generate attosecond pulses of light for the study of electron dynamics in matter"],
["2023","physiology/medicine","Katalin Karikó","Hungary/U.S.","discoveries concerning nucleoside base modifications that enabled the development of effective mRNA vaccines against COVID-19"],
["2023","physiology/medicine","Drew Weissman","U.S.","discoveries concerning nucleoside base modifications that enabled the development of effective mRNA vaccines against COVID-19"],
["2024","chemistry","David Baker","U.S.","work concerning computational protein design"],
["2024","chemistry","Demis Hassabis","U.K.","work involving protein structure prediction"],
["2024","chemistry","John M. Jumper","U.S.","work involving protein structure prediction"],
["2024","economics","Daron Acemoglu","Turkey/U.S.","studies of how institutions are formed and affect prosperity"],
["2024","economics","Simon Johnson","U.K./U.S.","studies of how institutions are formed and affect prosperity"],
["2024","economics","James A. Robinson","U.S.","studies of how institutions are formed and affect prosperity"],
["2024","literature","Han Kang","South Korea",""],
["2024","peace","Nihon Hidankyo","Japan",""],
["2024","physics","John Hopfield","U.S.","foundational discoveries and inventions that enable machine learning with artificial neural networks"],
["2024","physics","Geoffrey Hinton","U.K./Canada","foundational discoveries and inventions that enable machine learning with artificial neural networks"],
["2024","physiology/medicine","Victor Ambros","U.S.","discovery of microRNA and its role in post-transcriptional gene regulation"],
["2024","physiology/medicine","Gary Ruvkun","U.S.","discovery of microRNA and its role in post-transcriptional gene regulation"],
];
