var common_apps_pb_global=[
["popup:database","database","🛢","1"],
["popup:ENG","ENG","𝔼","1"],
["popup:game","game","games.png","1"],
["popup:PIM","PIM","♺","1"],
["popup:study","study","study.png","1"],
["popup:txtbook","book","🕮","1"],
["{{selenium_news}}/html/array_analyze.htm","Array Analyze","array_analyze512.png","3"],
["{{selenium_news}}/html/bible.htm","Bible","✝️","0_1"],
["{{selenium_news}}/html/book_search_js.htm","EBS_JS","👁","1_1_f"],
["{{selenium_news}}/html/bookshelf.htm","bookshelf","📚","5","txtbook"],
["{{selenium_news}}/html/calculator.htm","Calculator","➗","0_1"],
["{{selenium_news}}/html/calendar.htm","Calendar","calendar256.png","1"],
["{{selenium_news}}/html/canvas_draw.htm","canvas draw","🖍","3",""],
["{{selenium_news}}/html/cn_idiom.htm","cn idiom","😵","2",""],
["{{selenium_news}}/html/diff_js.htm","diff js","diff_js512.png","1"],
["{{selenium_news}}/html/digest.htm","Digest","🗃️","5","txtbook"],
["{{selenium_news}}/html/douban_book.htm","douban book","douban_book512.png","5","txtbook"],
["{{selenium_news}}/html/emoji.htm","emoji","🎁","1"],
["{{selenium_news}}/html/ensentence.htm","ensentence","🗨","5","ENG"],
["{{selenium_news}}/html/enwords_book.htm","生词统计","enwords_book512.png","5","ENG"],
["{{selenium_news}}/html/enwords.htm","enwords","enwords512.png","0","ENG"],
["{{selenium_news}}/html/enwords_slide.htm","单词幻灯片","enwords_slide512.png","5","ENG"],
["{{selenium_news}}/html/enwords_wordle.htm","wordle","😵","5","ENG"],
["{{selenium_news}}/html/f2f.htm","face to face","🫂","5","PIM"],
["{{selenium_news}}/html/forbes_billionaire.htm","forbes billionaire","🏭️","5","database"],
["{{selenium_news}}/html/fortune_500.htm","Fortune 500","🏭️","5","database"],
["{{selenium_news}}/html/gps_https.htm","Coords","🧭","2"],
["{{selenium_news}}/html/gps_news.htm","GPS News","📰","1"],
["{{selenium_news}}/html/gps_points.htm","GPS Points","🧿","0_2"],
["{{selenium_news}}/html/hzpinyin.htm","hzpy","hzpy512.png","0"],
["{{selenium_news}}/html/image2base64.htm","image2base64","image2base64_512.png","1"],
["{{selenium_news}}/html/image_merge.htm","image merge","image_merge512.png","2"],
["{{selenium_news}}/html/imdb.htm","Movie Analyze","🎬","5","database"],
["{{selenium_news}}/html/js_data_file_common_search.htm?d=../jsdata/words/cn_bullshit_data.js&i=💩&t=CN BS Search&v=cn_bullshit_global","CN BS Search","💩","5","database"],
["{{selenium_news}}/html/kleditor.htm","KLEditor","📝","1"],
["{{selenium_news}}/html/klsearch.htm","KL Search","klsearch512.png","1"],
["{{selenium_news}}/html/link_game.htm","link game","link_game512.png","5","game"],
["{{selenium_news}}/html/long_term_plans.htm","Long Term Plans","⛳ ️","5","PIM"],
["{{selenium_news}}/html/lsm.htm","LSM","lsm512.png","1"],
["{{selenium_news}}/html/memo.htm","Memo","🧷","5","PIM"],
["{{selenium_news}}/html/mine.htm","Mine","💣","5","game"],
["{{selenium_news}}/html/money_plan.htm","Money Plan","💵","1"],
["{{selenium_news}}/html/poker24.htm","24","🃏","5","game"],
["{{selenium_news}}/html/progress.htm","progress","📈","2",""],
["{{selenium_news}}/html/proofreader.htm","proofreader","✒","2"],
["{{selenium_news}}/html/qrcode.htm","qrcode","qrcode512.png","1"],
["{{selenium_news}}/html/qrimg.htm","qrimg","qrimg512.png","1"],
["{{selenium_news}}/html/qs_university.htm","QS University","🏛","5","database|education"],
["{{selenium_news}}/html/reader_card.htm","reader card","🗂","5","txtbook"],
["{{selenium_news}}/html/reader.htm?_tag🔖","reader","reader256.png","0","txtbook"],
["{{selenium_news}}/html/reader_idb.htm","reader idb","reader_idb512.png","5","txtbook"],
["{{selenium_news}}/html/rnd_english_words.htm","Random English Words","🇬🇧","5","ENG"],
["{{selenium_news}}/html/routines.htm","Routines","♾","5","PIM"],
["{{selenium_news}}/html/rows.htm","rows","rows512.png","0"],
["{{selenium_news}}/html/screen_canvas.htm","screen canvas","screen_canvas512.png","1"],
["{{selenium_news}}/html/screen_clock.htm","Clock","⏰","2"],
["{{selenium_news}}/html/screen_colorful_boxes.htm","Colorful Boxes","🏳️‍🌈","1"],
["{{selenium_news}}/html/screen_color_picker.htm","Color Picker","⛏️","1"],
["{{selenium_news}}/html/screen_matrix.htm","Matrix","screen_matrix256.png","2"],
["{{selenium_news}}/html/screen_test.htm","Screen Test","screen_test512.png","2"],
["{{selenium_news}}/html/society_data_analyze.htm","Society Data Analyze","society_data_analyze512.png","5","database"],
["{{selenium_news}}/html/sticker_mobile.htm","sticker_mobile","sticker_mobile512.png","2"],
["{{selenium_news}}/html/study_canvas.htm","study canvas","study_canvas512.png","5"],
["{{selenium_news}}/html/study_flot.htm","study flot","📈","5"],
["{{selenium_news}}/html/study_js.htm","study js","study_js512.png","5"],
["{{selenium_news}}/html/study_leaflet.htm","study leaflet","📍","5"],
["{{selenium_news}}/html/sudoku.htm","Sudoku","sudoku512.png","5","game"],
["{{selenium_news}}/html/symbols.htm","Symbols","🔣️","1"],
["{{selenium_news}}/html/cnki_search.htm","cnki search","🛢️","2","database"],
["{{selenium_news}}/html/tetris.htm","Tetris","tetris512.png","5","game"],
["{{selenium_news}}/html/todolist.htm","ToDoList","✅","5","PIM"],
["{{selenium_news}}/html/txtlistsearch.htm?_tag🔖","txtlistsearch","txtlistsearch256.png","0","txtbook"],
["{{selenium_news}}/html/vcard.htm","vcard","📱","2"],
["{{selenium_news}}/html/websites.htm","网址库","websites512.png","0"],
["{{selenium_news}}/html/websites_pwa.htm","Websites PWA","websites_pwa512.png","3"],
["{{selenium_news}}/html/wp_pwa.htm","wp pwa","wp_pwa512.png","1"],
["{{selenium_news}}/html/zj_college_search.htm","ZJ College","💯","5","database|education"],
["{{selenium_news}}/html/zj_company.htm","ZJ Company","🏭","5","database"],
["{{selenium_news}}/module/pdfjs/web/viewer.html","PDF.js","🔖","1"],
];
