var js_file_list_common_pb_global=[
['../jsdata/bible_quote/catchphrase_data.js','💬','Catchphrase','catchphrase_global','catchphrase',''],
['../jsdata/history_pb_data.js',' 𓀀','历史 pb','bigday_history_pb_global','bigday_history',''],
['../jsdata/klwiki_h3_pb_data.js','🖇','KL Wiki h3 pb','klwiki_h3_pb_global','klwiki_h3',''],
['../jsdata/learning_links/learning_links_1_data.js','🖫','learning links','learning_list_global','learning_list',''],
['../jsdata/meishichina_recipe_data.js','🍳','meishichina recipe','meishichina_recipe_global','meishichina_recipe',''],
['../jsdata/words/all_new_words_data.js','🇬🇧','All New Words','all_new_words_global','','言'],
['../jsdata/words/cet6_en_data.js','🇬🇧','英语四六级单词','cet6_en_global','','言'],
['../jsdata/words/cn_bullshit_data.js','💩','CN BS Search','cn_bullshit_global','',''],
['../jsdata/words/cn_ci_data.js',' 🇨🇳','汉语词语','cn_ci_global','','言'],
['../jsdata/words/cn_idoim_data.js',' 🇨🇳','汉语成语','cn_idiom_global','cn_idiom','言'],
['../jsdata/words/enwords_sentence_data.js','🇬🇧','英语例句','en_sentence_global','','言'],
['../jsdata/js_data_file_common_search_blank_data.js','📦','blank data','blank_data_global','blank_data',''],
['../jsdata/britannica_nobel_prize_data.js','🏆','nobel prize','nobel_prize_global','nobel_prize',''],
['../jsdata/rmrb_online/rmrb_online_194605_196612_data.js','🗞','rmrb online','rmrb_online_global','rmrb_online',''],
['../jsdata/dp_zj_data.js','🥧','dp rank','dp_rank_global','dp_rank',''],
['../jsdata/cn_medicine_data.js','💊','cn medicine','cn_medicine_raw_global','cn_medicine',''],
];
