var search_sites_list_global=[
//left_part,right_part,key_word_type,color,site_name,(c:check，用在usescript中 p:proxy b:button),category,title - 保留注释
['https://dict.cn/','',0,'','Dict.cn','c','English',''],
['https://cn.bing.com/dict/search?q=','',0,'','Bing(cn)','c','English',''],
['http://dict.youdao.com/search?le=eng&q=','',0,'','Youdao','c','English',''],
['http://www.iciba.com/','',0,'','ICIBA','c','English',''],
['https://www.merriam-webster.com/dictionary/','',0,'blue','Merriam-Webster','c','English',''],
['https://www.oxfordlearnersdictionaries.com/definition/english/','',2,'green','Oxford','c','English',''],
['https://dictionary.cambridge.org/dictionary/english/','',2,'orange','Cambridge','c','English',''],
['https://www.collinsdictionary.com/dictionary/english/','',2,'purple','Collins','cp','English',''],
['https://www.wordreference.com/definition/','',0, 'cadetblue','WordreRerence','','English',''],
['https://www.wordreference.com/enzh/','',0,'','WordreRerence CN','','English',''],
['https://www.lexico.com/definition/','',0,'#990066','Lexico','','English',''],
['https://www.dictionary.com/browse/','',0,'#6666cc','Dictionary.com','','English',''],
['https://www.thefreedictionary.com/','',0,'#0099ff','The Free Dictionary','','English',''],
['https://www.yourdictionary.com/','',0,'#990033','YourDictionary','','English',''],
['http://wordnetweb.princeton.edu/perl/webwn?s=','',0,'#663300','Wordnet','','English',''],
['https://en.wiktionary.org/wiki/','',0,'#6666cc','Wikitionary','p','English',''],
['https://www.merriam-webster.com/thesaurus/','',0,'#00ff33','Merriam-Webster Thesaurus','','English',''],
['https://www.oxfordlearnersdictionaries.com/us/pronunciation/english/','',2,'#006633','Oxford Pronunciation','','English',''],
['https://www.ahdictionary.com/word/search.html?q=','',0,'','American Heritage Dictionary','','English',''],
['https://www.wordnik.com/words/','',0,'','Wordnik','','English',''],

['https://www.bing.com/search?q=','',0,'salmon','Bing','','Search',''],
['https://duckduckgo.com/?q=','',0,'','DuckDuckGo','','Search',''],
['https://www.baidu.com/s?wd=','',0,'','百度','','Search',''],
['https://www.douban.com/search?q=','',0,'','豆瓣','','Search',''],
['https://en.wikipedia.org/wiki/','',0,'','Wikipedia','','Search',''],
['https://www.dogedoge.com/results?q=','',0,'','Dogedoge','','Search',''],
['https://www.ecosia.org/search?q=','',0,'','Ecosia','','Search',''],
['https://www.so.com/s?q=','',0,'','360','','Search',''],
['https://www.google.com/search?q=','',0,'','Google.com','','Search',''],
['https://search.yahoo.com/search?p=','',0,'','Yahoo','','Search',''],

['https://baike.baidu.com/searchword/?word=','',0,'','百度百科','','Knowledge',''],
['https://baike.baidu.com/item/','',0,'','百度百科正文','','Knowledge',''],
['https://zhidao.baidu.com/q?ct=17&pn=0&tn=ikaslist&rn=10&word=','&fr=wwwt',0,'','百度知道','','Knowledge',''],
['https://wenku.baidu.com/search?word=','',0,'','百度文库','','Knowledge',''],
['https://en.wikipedia.org/wiki/','',0,'','Wikipedia','','Knowledge',''],
['https://zh.wikipedia.org/zh/','',0,'','维基百科','','Knowledge',''],
['https://www.britannica.com/bps/search?query=','',0,'','Britannica','','Knowledge',''],

['https://www.imdb.com/find?q=','&s=all',0,'','IMDb','','MultiMedia',''],
['http://search.azlyrics.com/search.php?q=','',0,'','Azlyrics','','MultiMedia',''],
['https://movie.douban.com/subject_search?search_text=','&cat=1002',0,'','豆瓣电影','','MultiMedia',''],
['https://www.flickr.com/search/?q=','&f=hp',0,'','Flickr','','MultiMedia',''],
['http://so.iqiyi.com/so/q_','',0,'','爱奇艺','','MultiMedia',''],
['https://assrt.net/sub/?searchword=','',0,'','(伪)射手网','','MultiMedia',''],
['http://www.soku.com/search_video/q_','',0,'','Soku Video','','MultiMedia',''],
['http://www.traileraddict.com/search.php?q=','',0,'','Trailer Addict','','MultiMedia',''],
['https://www.youtube.com/results?search_query=','',0,'','YouTube','','MultiMedia',''],

['https://s.taobao.com/search?q=','',4,'','淘宝','','Shopping',''],
['https://list.tmall.com/search_product.htm?q=','',4,'','天猫','','Shopping',''],
['https://search.jd.com/Search?keyword=','&enc=utf-8',0,'','京东','','Shopping',''],
['https://www.amazon.cn/gp/search?field-keywords=','',0,'','亚马逊','','Shopping',''],
['http://book.douban.com/subject_search?search_text=','',0,'','豆瓣读书','','Shopping',''],
['http://searchb.dangdang.com/?key=','',4,'','当当','','Shopping',''],
['http://search.suning.com/emall/search.do?keyword=','',0,'','苏宁','','Shopping',''],

['https://map.baidu.com/m?word=','',0,'','百度地图','','Map',''],
['https://ditu.amap.com/search?query=','',0,'','高德','','Map',''],

['http://tieba.baidu.com/f?kw=','',0,'','百度贴吧','','SNS',''],
['https://s.weibo.com/weibo/','',0,'','新浪微博','','SNS',''],
['https://en.search.wordpress.com/?q=','',0,'','WordPress.com','','SNS',''],

['txtlistsearch.htm?_tag','_reg',0,'','📚','b','Local','书目查询'],
['rnd_english_words.htm?s=','(:r)',0,'','🇬🇧','b','Local','随机单词'],
['bible.htm?s=','(:r)',0,'red','✝','b','Local','Bible'],

];
