var search_sites_list_global=[
//left_part,right_part,key_word_type,color,site_name,(c:check，用在usescript中；p:proxy b:button；0:important；n:without key, just link；l:toLowerCase()；m:show in right menu),category,title - 保留注释
//key_word_type: 1+, 2-,3\s, 4gbk, 5_ - 保留注释
['https://fanyi.baidu.com/mtpe-individual/multimodal','',0,'','百度翻译','n0','ENG',''],
['https://cn.bing.com/dict/search?q=','',0,'','Bing(cn)','c0m','ENG',''],
['https://dict.youdao.com/search?le=eng&q=','',0,'','Youdao','c0m','ENG',''],
['https://dict.cn/','',0,'','Dict.cn','c0','ENG',''],
['https://www.iciba.com/','',0,'','ICIBA','c0','ENG',''],
['https://www.merriam-webster.com/dictionary/','',0,'blue','Merriam-Webster','c0m','ENG',''],
['https://www.collinsdictionary.com/dictionary/english/','',2,'purple','Collins','cp0m','ENG',''],
['https://www.collinsdictionary.com/dictionary/english-chinese/','',2,'','Collins_CN','p0','ENG',''],
['https://www.oxfordlearnersdictionaries.com/definition/english/','',2,'green','Oxford','c0lm','ENG',''],
['https://dictionary.cambridge.org/dictionary/english/','',2,'orange','Cambridge','c0m','ENG',''],
['https://dictionary.cambridge.org/dictionary/english-chinese-simplified/','',2,'','Cambridge_CN','c0','ENG',''],

['https://www.ahdictionary.com/word/search.html?q=','',0,'','AHD','0','ENG',''],
['https://www.definitions.net/definition/','',1,'','definitions','','ENG',''],
['https://www.dictionary.com/browse/','',0,'#6666cc','Dictionary.com','','ENG',''],
['https://www.howtopronounce.com/','',2,'','htp','','ENG',''],
['https://www.behindthename.com/name/','',2,'','btn','','ENG',''],
['https://kaikki.org/dictionary/English/words/index.html?s=','',0,'#CC6600','kaikki','0m','ENG',''], 

['https://www.britannica.com/dictionary/','',0,'','britannicadict','','ENG',''],
['https://www.ldoceonline.com/dictionary/','',2,'','Longman','0','ENG',''],    
['https://www.oed.com/search/dictionary/?q=','',1,'yellowgreen','oed','0','ENG',''],
['https://dictionary.reverso.net/english-definition/','',1,'dodgerblue','reverso','0','ENG',''],
['https://www.thefreedictionary.com/','',0,'#0099ff','TFD','0','ENG',''],
['https://en.wiktionary.org/wiki/','',0,'#6666cc','Wiktionary','p0','ENG',''],
['https://www.wordhippo.com/what-is/the-meaning-of-the-word/','.html',1,'','wordhippo','','ENG',''], 
['https://www.wordow.com/english/dictionary/','',0,'','wordow','','ENG',''],
['https://www.wordreference.com/definition/','',0, 'cadetblue','WR','0','ENG',''],
['https://www.wordreference.com/enzh/','',0,'','WR_CN','0','ENG',''],
['https://www.wordsense.eu/','/',5,'','wordsense','','ENG',''],
['https://www.yourdictionary.com/','',0,'#990033','YourDictionary','','ENG',''],

['https://www.merriam-webster.com/thesaurus/','',0,'#00ff33','Merriam-Webster_Thesaurus','','ENG',''],
['https://www.oxfordlearnersdictionaries.com/us/pronunciation/english/','',2,'#006633','Oxford_Pronunciation','','ENG',''],

['https://www.wordnik.com/words/','',0,'','Wordnik','0','ENG',''],
['https://www.oxfordreference.com/search?q_0=','&f_0=title&avail_5=free',0,'','oxfordreference','','ENG',''],

['https://www.bing.com/search?q=','',0,'salmon','Bing','0m','搜',''],
['https://duckduckgo.com/?q=','',0,'','DuckDuckGo','0','搜',''],
['https://www.baidu.com/s?wd=','',0,'','百度','0m','搜',''],
['https://yandex.com/search/?text=','',1,'','Yandex','0','搜',''],
['https://www.bing.com/search?q=',' site: thepaper.cn',0,'','澎湃','0','搜',''],
['https://www.bing.com/search?q=',' site: www.people.com.cn',0,'','人民','','搜',''],
['https://www.bing.com/search?q=',' site: www.xinhuanet.com',0,'','新华','','搜',''],
['https://search.cctv.com/search.php?qtext=','&type=web',0,'','CCTV','','搜',''],
['https://www.bing.com/search?q=',' site: www.gov.cn',0,'','国务院','','搜',''],
['https://www.bing.com/search?q=',' site: sina.com.cn',0,'','新浪','','搜',''],
['https://www.douban.com/search?q=','',0,'','豆瓣','0m','搜',''],
['https://astiango.com/search.php?q=','',1,'','AstianGO','','搜',''],
['https://www.so.com/s?q=','',0,'','360','','搜',''],
['https://www.google.com/search?q=','',0,'','Google.com','','搜',''],

['https://baike.baidu.com/searchword/?word=','',0,'','百度百科','','知',''],
['https://baike.baidu.com/item/','',0,'','百度百科正文','','知',''],
['https://zhidao.baidu.com/q?ct=17&pn=0&tn=ikaslist&rn=10&word=','&fr=wwwt',0,'','百度知道','','知',''],
['https://wenku.baidu.com/search?word=','',0,'','百度文库','','知',''],
['https://en.wikipedia.org/wiki/','',0,'','Wikipedia','','知',''],
['https://zh.wikipedia.org/zh/','',0,'','维基百科','','知',''],
['https://www.britannica.com/bps/search?query=','',0,'','Britannica','','知',''],

['https://www.imdb.com/find?q=','&s=all',0,'','IMDb','0m','AV',''],
['http://search.azlyrics.com/search.php?q=','',0,'','Azlyrics','','AV',''],
['https://movie.douban.com/subject_search?search_text=','&cat=1002',0,'','豆瓣电影','0','AV',''],
['https://www.flickr.com/search/?q=','&f=hp',0,'','Flickr','','AV',''],
['http://so.iqiyi.com/so/q_','',0,'','爱奇艺','','AV',''],
['https://assrt.net/sub/?searchword=','',0,'','(伪)射手网','','AV',''],
['http://www.soku.com/search_video/q_','',0,'','Soku_Video','','AV',''],
['http://www.traileraddict.com/search.php?q=','',0,'','Trailer_Addict','','AV',''],
['https://www.youtube.com/results?search_query=','',0,'','YouTube','','AV',''],

['https://s.taobao.com/search?q=','',0,'','淘宝','','购',''],
['https://list.tmall.com/search_product.htm?q=','',0,'','天猫','','购',''],
['https://search.jd.com/Search?keyword=','&enc=utf-8',0,'','京东','','购',''],
['http://book.douban.com/subject_search?search_text=','',0,'','豆瓣读书','0','购',''],
['http://search.dangdang.com/?key=','',4,'','当当','','购',''],
['http://search.suning.com/emall/search.do?keyword=','',0,'','苏宁','','购',''],
['https://www.gutenberg.org/ebooks/search/?query=','&sort_order=downloads',1,'','Gutenberg','','购',''],

['https://map.baidu.com/m?word=','',0,'','百度地图','','Map',''],
['https://ditu.amap.com/search?query=','',0,'','高德','','Map',''],

['http://tieba.baidu.com/f?kw=','',0,'','百度贴吧','','SNS',''],
['https://s.weibo.com/weibo/','',0,'','新浪微博','','SNS',''],
['https://en.search.wordpress.com/?q=','',0,'','WordPress.com','','SNS',''],

//以下不复制到 userscript 中 - 保留注释
//batch 系列格式为 &t=batch_type& - 保留注释
['txtlistsearch.htm?_tag','_reg',0,'','📚','b0','Local','书目查询'],
['rnd_english_words.htm?s=','(:r)',0,'','🇬🇧','b','Local','随机单词'],
['bible.htm?s=','(:r)',0,'red','✝','b0','Local','Bible'],
['klsearch.htm?k=','&t=batch_en&iframe',0,'darkslategray','KLSearch(en)','0','Local',''],
['klsearch.htm?k=','&t=batch_en+&iframe',0,'darkslategray','KLSearch(en+)','0','Local',''],
['klsearch.htm?k=','&t=batch_en_wiktionary&close=1',0,'','KLSearch(wiktionary)','1','Local',''],
['klsearch.htm?k=','&t=batch_dwdlw&close=1',0,'','KLSearch(dwdlw)','0','Local',''],
['klsearch.htm?k=','&t=batch_offline&close=1',0,'','KLSearch(batch_offline)','0','Local',''],

];
